### ISSUE TITLE
[WISH] names of modes in variables

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1001]
It would be nice to have the names of modes in variables/constants.  That would allow to redefine them to use shorter names—for example, setting `mu4e-view-mode` to `mu4e:✍`.  This is useful to see the context.

**Comment by djcb** [comment]
You mean, like what `diminish` does?

**Comment by Chris00** [comment]
I did not know about [diminish](https://github.com/myrjola/diminish.el).   The idea is not to hide the major mode but to be able to shorten it (`mu4e:compose` is especially long).

**Comment by djcb** [comment]
`diminish` can in fact set arbitrary names... but it's only for minor-modes. Anyway, don't want to add a variable for this, perhaps you can set `mode-name` in a hook.
