### ISSUE TITLE
Installaiton with emacs 26.0.50.2

### ISSUE THREAD

**Issue by sachdevaprash** [djcb/mu#1005]
## Expected or desired behavior
Should install on emacs 26.0.50.2

## Actual behavior
```configure: WARNING: emacs is too old to build mu4e (need emacs >= 23.x)```

## Steps to reproduce
Try to install with emacs from the github mirror (https://github.com/emacs-mirror/emacs/)

## Versions of mu, mu4e/emacs, operating system etc.
mu 0.9.17 (github latest as of 4th Jan 6:58 UTC)
emacs 26.0.50.2

**Comment by peterwvj** [comment]
I'm currently using Emacs 26.0.50.2/mu4e 0.9.18 C and I'm not experiencing any problems. Have you tried to upgrade mu4e?

**Comment by djcb** [comment]
mu 0.9.17's version check didn't allow for emacs 26; however, mu 0.9.18 (and git) do.

**Comment by sachdevaprash** [comment]
You are right. I was pulling from a branch. Sorry for the bother.
