### ISSUE TITLE
problem with autoconf when installing

### ISSUE THREAD

**Issue by jmburgos** [djcb/mu#1006]
Hello, 
I am having an issue when installing mu4e 9.18 (commit f40ffa2) from git, following the instructions here:

https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html#Installation

After doing autoreconf -i, I get the the following error:

configure.ac:42: warning: macro 'AM_PROG_LIBTOOL' not found in library
guile/Makefile.am:31: error: Libtool library used but 'LIBTOOL' is undefined
guile/Makefile.am:31:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
guile/Makefile.am:31:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
guile/Makefile.am:31:   If 'LT_INIT' is in 'configure.ac', make sure
guile/Makefile.am:31:   its definition is in aclocal's search path.
lib/Makefile.am:46: error: Libtool library used but 'LIBTOOL' is undefined
lib/Makefile.am:46:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
lib/Makefile.am:46:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
lib/Makefile.am:46:   If 'LT_INIT' is in 'configure.ac', make sure
lib/Makefile.am:46:   its definition is in aclocal's search path.
lib/tests/Makefile.am:39: error: Libtool library used but 'LIBTOOL' is undefined
lib/tests/Makefile.am:39:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
lib/tests/Makefile.am:39:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
lib/tests/Makefile.am:39:   If 'LT_INIT' is in 'configure.ac', make sure
lib/tests/Makefile.am:39:   its definition is in aclocal's search path.
toys/mug/Makefile.am:68: error: Libtool library used but 'LIBTOOL' is undefined
toys/mug/Makefile.am:68:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
toys/mug/Makefile.am:68:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
toys/mug/Makefile.am:68:   If 'LT_INIT' is in 'configure.ac', make sure
toys/mug/Makefile.am:68:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

I am installing on CentOS 7, using autoreconf version 2.69 and automake version 1.14.

**Comment by djcb** [comment]
Those instructions are for 0.9.18, but the git version is a bit newer than that; you'll need to run `./autogen.sh` now; it's documented in HACKING. Good luck!

**Comment by jmburgos** [comment]
I did managed to install 0.9.18 from the tar ball, so everything is fine.
