### ISSUE TITLE
Search for hashtags?

### ISSUE THREAD

**Issue by jkitchin** [djcb/mu#1009]
If I am in mu4e, press s to search, and type #test it doesn't find emails containing the string #test. Is that expected?

**Comment by sje30** [comment]
Probably.  mu4e uses xapian for indexing, so there are limits to search terms.

**Comment by jkitchin** [comment]
There must be a way to search for those strings though, some escape syntax or something?

**Comment by sje30** [comment]
I think the xapian backend is pretty inflexible in this regard.  If you
check on the archives for the mu4e mail list, I think you'll see
comments along these lines when people have asked for searching for
strings with "." in them.

**Comment by djcb** [comment]
Yeah, indeed, there's a bit of a mismatch between mu / xapian and these special characters, and the xapian query parser doesn't allow for escaping them. mu tries a few tricks, but it can't handle all cases... Sorry about that.

**Comment by jkitchin** [comment]
ok, thanks for verifying. Thanks also for this great package!
