### ISSUE TITLE
New message hook?

### ISSUE THREAD

**Issue by jkitchin** [djcb/mu#1010]
## Expected or desired behavior
I am interested in auto-tagging new messages containing hashtags (or some similar pattern). Something like you describe at https://www.djcbsoftware.nl/code/mu/mu4e/Adding-a-new-kind-of-mark.html#Adding-a-new-kind-of-mark, but done automatically on new messages.. It seems like a new message-hook is the way to do that. I saw the mu4e-index-updated-hook variable, but it isn't clear how to access the new messages from that. 

Is this the right way to think about doing it?

**Comment by djcb** [comment]
So some kind of `procmail` like program... 

I think it would be tricky to do that on top of `mu4e`... One approach you could try is using the command-line, ie. `mu find flag:new --fields=l` will get you the list of new message files; you can then add/remove fields (for tags), e.g. with `formail`.

**Comment by jkitchin** [comment]
hm. that seems to give me way to many hits.
mu find flag:new --fields=l | wc -l
    6292

I came up with this sort of solution that tags emails when I open them.

(defun mu4e-auto-tag ()
  "Automatically tag messages with hashtags in them."
  (let ((tags '())
	(msg (mu4e-message-at-point)))
    (save-excursion
      (while (re-search-forward "[^a-zA-Z0-9]#\\(\\(\\w*[-_]?\\)*\\)" nil t)
	(add-to-list 'tags (match-string 1)))
      (when tags
	(mu4e-action-retag-message
	 msg
	 (mapconcat (lambda (tag) (concat "+" tag)) tags ","))))))

It works ok, when I want it I put it in this hook:

;; (add-hook 'mu4e-view-mode-hook 'mu4e-auto-tag)
