### ISSUE TITLE
Cannot attach message with unencoded non-ASCII characters in body

### ISSUE THREAD

**Issue by KrzysiekJ** [djcb/mu#1012]
As described on the mailing list, [mu4e fails to send attached message when its file contains non-ASCII characters](https://groups.google.com/d/msg/mu-discuss/FJo0GmRl4Uo/DNlz-KGzqDcJ), which is a behavior derived from `message-mode`. [RFC 822](http://www.faqs.org/rfcs/rfc822.html) says “The body is simply a sequence of lines containing ASCII characters”, so handling this would require one of the following:

* using a more relevant MIME type than `message/rfc822` to represent emails (is there any?);
* converting message to a different content transfer encoding before attaching;
* assuming that is is the email provider’s fault to provide RFC 822-conformant messages and that this issue should be handled on his side.

**Comment by djcb** [comment]
Checked this ancient issue once again, I think there's not really something we can do here. The message is _not_ rfc822 compliant, so message-mode is complaining correctly. Guess the only wayis to attach it as a normal file.
