### ISSUE TITLE
mu4e produces messages not compliant with RFC 822

### ISSUE THREAD

**Issue by KrzysiekJ** [djcb/mu#1013]
## Expected or desired behavior

When sending a draft message, mu4e encodes it to Base64 if it is necessary to handle non-ASCII characters (which are not permitted in [RFC 822](https://tools.ietf.org/html/rfc822)). This is the behavior of raw `message-mode`.

## Actual behavior

mu4e sends messages with `Content-Transfer-Encoding` set to `8-bit` even if they contain non-ASCII characters. This causes problems later when they are to be attached in other messages (see #1012).

## Steps to reproduce

1. Start composing a new message.
2. Enter “Zażółć gęślą jaźń” in the message body.
3. Send the message.

## Versions of mu, mu4e/emacs, operating system etc.

Tested on commit f060cb819687ad651a0f74aac21a9a4c8683718a, Emacs 25.1.1.

**Comment by djcb** [comment]
Can't reproduce that; it's using quoted-printable in my case.  mu4e doesn't do anything with content-transfer-encoding directly, so I suspect it's some setting. Are you using a non-utf8 language environment in emacs?

**Comment by KrzysiekJ** [comment]
I’ve been using a non-UTF-8-based language environment, but after changing it to `UTF-8` the problem persists.

**Comment by djcb** [comment]
Is this still a problem with newer emacs? Perhaps try setting `message-default-charset'.

**Comment by KrzysiekJ** [comment]
The documentation on `message-default-charset` says:

> This variable is obsolete since 26.1;
> The default charset comes from the language environment

It looks though like the problem has vanished in Emacs 26.1 (or in newer mu4e), as messages are encoded using Base64; I’m closing the issue then.

**Comment by eugeneandrienko** [comment]
I can confirm the same problem with mu4e 1.8.13 from FreeBSD 14.1. When I compose e-mail with Cyrillic symbols it looks ok:

![2024-08-27-205752_699x427_scrot](https://github.com/user-attachments/assets/0899b0d0-540e-4918-8c8b-16812f05bf13)

But when I send this message to myself and receive it — it displayed in base64. Same base64 in Gmail web interface, so the recipient couldn't read my e-mails:

![2024-08-27-210135_1148x594_scrot](https://github.com/user-attachments/assets/6b70fe7c-66c6-493d-bbb5-411a7bcf85e1)
![2024-08-27-210253_1764x986_scrot](https://github.com/user-attachments/assets/d647f799-a317-413b-81d2-877f990e19b5)

In Emacs configuration I use UTF8 everywhere:

```
  :config
                                        ; Use UTF8 everywhere
  (prefer-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-language-environment 'utf-8)
```

But this doesn't help.

I use `msmtp` to send e-mails.

Emacs: 29.4

**Comment by djcb** [comment]
I'd recommend upgrading to a newer version of mu4e (1.12.x), many things changed; if you can reproduce there, please file a new ticket.
