### ISSUE TITLE
trashing mail does not move it to trash

### ISSUE THREAD

**Issue by jabranham** [djcb/mu#1018]
## Expected or desired behavior

Marking mail for trash (then executing the mark) should move the message to `mu4e-trash-folder`

## Actual behavior

It doesn't, and I have no idea where it goes. I think it gets deleted from both the server and locally. 

I have three accounts set up. Two are gmail - one "normal" gmail and the other a google apps for work. For those, I just delete emails since they're backed up to the "All Mail" folder anyway.

For the exchange account, I am trying to move folders to the trash, but this doesn't seem to work - it just deletes the email.

## Versions of mu, mu4e/emacs, operating system etc.
I'm using the most recent versions of Emacs and mu4e - 25.1.1 and 0.9.18 respectively. I'm using Arch Linux. I'm using mbsync (isync) to sync mail back and forth. The account in question is a MS exchange account, so I'm using davmail to be able to sync like it's an imap account.

**Comment by jabranham** [comment]
OK, I think I've figured out the problem. mu4e *does* move the message to trash (I had the mbsync interval so short I didn't catch it before). However, it also places a "trashed" flag on the message. When that's synced with the server, the message gets deleted. 

Is there a way to move the message to trash but not put the trash flag on the message?

**Comment by djcb** [comment]
Simply move the message to trash should do the trick.And/or lobby the mbsync people to follow the Maildir flag semantics, ie. "Flag "T" (trashed): the user has moved this message to the trash; the trash will be emptied by a later user action. " (https://cr.yp.to/proto/maildir.html)

**Comment by averter** [comment]
@jabranham Can you please share your mbsyncrc file? I am trying to get mbsync and davmail to work together without success. Thanks in advance!
