### ISSUE TITLE
resend a message

### ISSUE THREAD

**Issue by Popsch** [djcb/mu#102]
Often when I don't get an answer to an email, I just resend the email (instead of reply). It would be good to have this feature (aka gnus-summary-resend-message or gnus-summary-resend-bounced-mail).

**Comment by zakkak** [comment]
@djcb any comments on this issue and #449 ?

**Comment by djcb** [comment]
I've commented on #449; would be interesting to get that in, but it requires a bit of work still.

**Comment by djcb** [comment]
There's `mu4e-compose-resend` now.
