### ISSUE TITLE
error in process filter: cond: Error 3: indexing failed

### ISSUE THREAD

**Issue by lujianmei** [djcb/mu#1022]
Version:

kevin@kevins-MacBook-Pro-2  ~  mu --version
mu (mail indexer/searcher) version 0.9.18
Copyright (C) 2008-2015 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

And I use command to index:

kevin@kevins-MacBook-Pro-2  ~  mu index --maildir=~/Maildir
indexing messages under /Users/kevin/Maildir [/Users/kevin/.mu/xapian]
 processing mail; processed: 8925; updated/new: 7, cleaned-up: 0
cleaning up messages [/Users/kevin/.mu/xapian]
 processing mail; processed: 8939; updated/new: 0, cleaned-up: 0
elapsed: 0 second(s)
\ processing mail; processed: 8939; updated/new: 0, cleaned-up: 0
elapsed: 0 second(s)

But when i use this in my spacemacs, it got following error when i try to jump to other mail sub-directory:

[mu4e] Indexing... processed 0, updated 0
error in process filter: cond: Error 3: indexing failed
error in process filter: Error 3: indexing failed
error in process filter: cond: Error 13: parse error in query
error in process filter: Error 13: parse error in query

When i open debug, got following message:

Debugger entered--Lisp error: (error "Error 13: parse error in query")
  signal(error ("Error 13: parse error in query"))
  error("Error %d: %s" 13 "parse error in query")
  (cond ((eql errcode (quote 4)) (user-error "No matches for this search query.")) (t (error "Error %d: %s" errcode errmsg)))
  mu4e-error-handler(13 "parse error in query")
  funcall(mu4e-error-handler 13 "parse error in query")
  (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func (plist-get sexp :props))) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp)))
  (while sexp (mu4e-log (quote from-server) "%S" sexp) (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func (plist-get sexp :props))) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp))) (setq sexp (mu4e~proc-eat-sexp-from-buf)))
  (let ((inhibit-quit nil)) (while sexp (mu4e-log (quote from-server) "%S" sexp) (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func (plist-get sexp :props))) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp))) (setq sexp (mu4e~proc-eat-sexp-from-buf))))
  (condition-case nil (let ((inhibit-quit nil)) (while sexp (mu4e-log (quote from-server) "%S" sexp) (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func (plist-get sexp :props))) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp))) (setq sexp (mu4e~proc-eat-sexp-from-buf)))) (quit (setq quit-flag t) (eval (quote (ignore nil)))))
  (with-local-quit (while sexp (mu4e-log (quote from-server) "%S" sexp) (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func (plist-get sexp :props))) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp))) (setq sexp (mu4e~proc-eat-sexp-from-buf))))
  (let ((sexp (mu4e~proc-eat-sexp-from-buf))) (with-local-quit (while sexp (mu4e-log (quote from-server) "%S" sexp) (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func (plist-get sexp :props))) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp))) (setq sexp (mu4e~proc-eat-sexp-from-buf)))))
  mu4e~proc-filter(#<process  *mu4e-proc*> "\3762c\377(:error 13 :message \"parse error in query\")\n")

Do you have any idea how i can solve this?
Thanks.

**Comment by djcb** [comment]
Hmmm, do you know the file system path of the maildir you're jumping to?

**Comment by djcb** [comment]
Can you try to get a log from when this happens? See the entry `Logging and debugging` in the mu4e manual. Thanks.

**Comment by djcb** [comment]
No answer for a long time... closing.
