### ISSUE TITLE
"mu: mu_str_escape_c_literal: assertion 'str' failed" when viewing message

### ISSUE THREAD

**Issue by jschwab** [djcb/mu#1023]
I attempt to view a message by navigating to it (as usual) in the headers view.

## Expected or desired behavior

mu4e displays the message

## Actual behavior

mu4e fails to display the message and displays the following error:

    Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
      mu4e-message-body-text((:docid 449235 :subject "advice" :date (22677 8145 0) :size 310413 :message-id "5CE54BC4-C96C-4743-82D8-02A57B9EC9CC@xxxxxxx.org" :path "/home/jschwab/Mail/xxxxxxxxx/[Gmail].All Mail/cur/1486244428_1.29283.monolith,U=5051,FMD5=844bb96d088d057aa1b32ac1fbc67b56:2,RS" :maildir "/xxxxxxxxx/[Gmail].All Mail" :priority normal :flags (replied seen attach) :parts ((:index 1 :name "Xxxxxxxxxx_Xxxxxxx.pdf" :mime-type "application/pdf" :type (leaf inline) :attachment t :size 306613)) :from (("Xxxxxx" . "xxxxxx@xxxxxxx.org")) :to (("Josiah Schwab" . "xxxxxxx@xxxx.edu")) :user-agent "Apple Mail (2.2104)") nil)
      mu4e-view-message-text((:docid 449235 :subject "advice" :date (22677 8145 0) :size 310413 :message-id "5CE54BC4-C96C-4743-82D8-02A57B9EC9CC@xxxxxxx.org" :path "/home/jschwab/Mail/xxxxxxxxx/[Gmail].All Mail/cur/1486244428_1.29283.monolith,U=5051,FMD5=844bb96d088d057aa1b32ac1fbc67b56:2,RS" :maildir "/xxxxxxxxx/[Gmail].All Mail" :priority normal :flags (replied seen attach) :parts ((:index 1 :name "Xxxxxxxxxx_Xxxxxxx.pdf" :mime-type "application/pdf" :type (leaf inline) :attachment t :size 306613)) :from (("Xxxxxx" . "xxxxxx@xxxxxxx.org")) :to (("Josiah Schwab" . "xxxxxxx@xxxx.edu")) :user-agent "Apple Mail (2.2104)"))
      mu4e-view((:docid 449235 :subject "advice" :date (22677 8145 0) :size 310413 :message-id "5CE54BC4-C96C-4743-82D8-02A57B9EC9CC@xxxxxxx.org" :path "/home/jschwab/Mail/xxxxxxxxx/[Gmail].All Mail/cur/1486244428_1.29283.monolith,U=5051,FMD5=844bb96d088d057aa1b32ac1fbc67b56:2,RS" :maildir "/xxxxxxxxx/[Gmail].All Mail" :priority normal :flags (replied seen attach) :parts ((:index 1 :name "Xxxxxxxxxx_Xxxxxxx.pdf" :mime-type "application/pdf" :type (leaf inline) :attachment t :size 306613)) :from (("Xxxxxx" . "xxxxxx@xxxxxxx.org")) :to (("Josiah Schwab" . "xxxxxxx@xxxx.edu")) :user-agent "Apple Mail (2.2104)") #<buffer *mu4e-headers*>)
      mu4e~headers-view-handler((:docid 449235 :subject "advice" :date (22677 8145 0) :size 310413 :message-id "5CE54BC4-C96C-4743-82D8-02A57B9EC9CC@xxxxxxx.org" :path "/home/jschwab/Mail/xxxxxxxxx/[Gmail].All Mail/cur/1486244428_1.29283.monolith,U=5051,FMD5=844bb96d088d057aa1b32ac1fbc67b56:2,RS" :maildir "/xxxxxxxxx/[Gmail].All Mail" :priority normal :flags (replied seen attach) :parts ((:index 1 :name "Xxxxxxxxxx_Xxxxxxx.pdf" :mime-type "application/pdf" :type (leaf inline) :attachment t :size 306613)) :from (("Xxxxxx" . "xxxxxx@xxxxxxx.org")) :to (("Josiah Schwab" . "xxxxxxx@xxxx.edu")) :user-agent "Apple Mail (2.2104)"))
      mu4e~proc-filter(#<process *mu4e-proc*> "mu: mu_str_escape_c_literal: assertion 'str' failed\n\376275\377(:view (\n	:docid 449235\n	:subject \"advice\"\n	:date (22677 8145 0)\n	:size 310413\n	:message-id \"5CE54BC4-C96C-4743-82D8-02A57B9EC9CC@xxxxxxx.org\"\n	:path \"/home/jschwab/Mail/xxxxxxxxx/[Gmail].All Mail/cur/1486244428_1.29283.monolith,U=5051,FMD5=844bb96d088d057aa1b32ac1fbc67b56:2,RS\"\n	:maildir \"/xxxxxxxxx/[Gmail].All Mail\"\n	:priority normal\n	:flags (replied seen attach)\n	:parts ((:index 1 :name \"Xxxxxxxxxx_Xxxxxxx.pdf\" :mime-type \"application/pdf\" :type (leaf inline) :attachment t  :size 306613  ))\n	:from ((\"Xxxxxx\" . \"xxxxxx@xxxxxxx.org\"))\n	:to ((\"Josiah Schwab\" . \"xxxxxxx@xxxx.edu\"))\n	:user-agent \"Apple Mail (2.2104)\"\n)\n)\n\n")
    

## Steps to reproduce

Attempting to view the message immediately and repeatably results in the error. 

Unfortunately, the message that produces this error is sensitive and so I cannot attach it.  It is a message sent by Apple Mail, which has no body text and a single attached PDF file.

## Versions of mu, mu4e/emacs, operating system etc.

emacs-25.2-rc1
mu from git (ad1a372b)

## Any other detail

This was not occuring as of 08f2bb2e.

**Comment by jschwab** [comment]
@stig Just finished bisecting.  b0c618c3 is also OK. So it seems like this related to the changes in #986.

**Comment by djcb** [comment]
I've pushed a change... does it fix the problem?

**Comment by jschwab** [comment]
235dc75a1a8e2dac0b6aba70360a1d6ba1212256 displays the offending message as expected.

Thanks for the quick fix!
