### ISSUE TITLE
mu: problems with running ./configure when building on Ubuntu

### ISSUE THREAD

**Issue by lwiechec** [djcb/mu#1027]
## Expected or desired behavior

GNU autoconf configures mu to be build

## Actual behavior
hi,

I am trying to upgrade my `mu4e` using El-Get package manager.
 
`autoconf` fails to run claiming that `autoconf-archive` package is not installed.

The error message says:
```
~/.../el-get/mu4e [master|✔] 
09:56 $ ./configure 
configure: error: 
    *** We need autoconf-archive for reconfiguring, but it is not found
    *** Please install it.
```
## Steps to reproduce

1. checkout from github repo
2. go to 'mu' directory
3. type 'autoreconf -i'
4. try to run autoconf: `./configure`

## Versions of mu, mu4e/emacs, operating system etc.

mu 0.9.19, emacs 25.1.1, OS: Pepermint 5 Linux distro (clone of Ubuntu), autoreconf 2.69, autoconf 2.69

## Any other detail

it was working ok for version 0.9.17 C (of mu4e)

**Comment by djcb** [comment]
Did you see:
```
configure: error: 
    *** We need autoconf-archive for reconfiguring, but it is not found
    *** Please install it.
```
that should give a hint.

**Comment by lwiechec** [comment]
Hi Dirk-Jan,I know :) but I have installed that package (ubuntu package is called 'autoconf-archive'; I can see lots of macro scripts in /usr/share/autoconf dir) but still I cannot make the 'configure' script, well, find it...                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Dirk-Jan C. BinnemaSent: Thursday, 9 February 2017 19:57To: djcb/muReply To: djcb/muCc: Lukasz Wiechec; AuthorSubject: Re: [djcb/mu] mu: problems with running ./configure when building on Ubuntu (#1027)Did you see:
configure: error: 
    *** We need autoconf-archive for reconfiguring, but it is not found
    *** Please install it.

that should give a hint.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/djcb/mu","title":"djcb/mu","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/djcb/mu"}},"updates":{"snippets":[{"icon":"PERSON","message":"@djcb in #1027: Did you see:\r\n```\r\nconfigure: error: \r\n    *** We need autoconf-archive for reconfiguring, but it is not found\r\n    *** Please install it.\r\n```\r\nthat should give a hint."}],"action":{"name":"View Issue","url":"https://github.com/djcb/mu/issues/1027#issuecomment-278738021"}}}

**Comment by lbolla** [comment]
Same problem here. Just did this:

> $ git pull && make clean && make distclean && autoconf && ./configure                                                                                                                                     (GIT:master) 
Already up-to-date.
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.14 -I m4
 cd . && automake-1.14 --gnu
configure.ac:25: error: required directory ./xua does not exist
configure.ac:47: error: required file 'xua/compile' not found
configure.ac:47:   'automake --add-missing' can install 'compile'
configure.ac:57: error: required file 'xua/config.guess' not found
configure.ac:57:   'automake --add-missing' can install 'config.guess'
configure.ac:57: error: required file 'xua/config.sub' not found
configure.ac:57:   'automake --add-missing' can install 'config.sub'
configure.ac:36: error: required file 'xua/install-sh' not found
configure.ac:36:   'automake --add-missing' can install 'install-sh'
configure.ac:57: error: required file 'xua/ltmain.sh' not found
configure.ac:36: error: required file 'xua/missing' not found
configure.ac:36:   'automake --add-missing' can install 'missing'
contrib/Makefile.am: error: required file 'xua/depcomp' not found
contrib/Makefile.am:   'automake --add-missing' can install 'depcomp'
guile/Makefile.am:50: error: required file 'xua/texinfo.tex' not found
guile/Makefile.am:50:   'automake --add-missing' can install 'texinfo.tex'
make: *** [Makefile.in] Error 1

If I remove `AC_CONFIG_AUX_DIR([xua]) # Win/DOS don't like 'aux'` from `configure.ac` then I get:

> $ autoconf && ./configure                                                                                                                                                                         (GIT:master *) 
configure: error: 
    *** We need autoconf-archive for reconfiguring, but it is not found
    *** Please install it.

**Comment by djcb** [comment]
Yeah, that version is too old. I've improved the error message a bit to reflect that. Note, you can get the official tarball, which doesn't require any of these developer tools.

**Comment by lwiechec** [comment]
@jdcb thanks for better message :) may I ask one more thing? I have installed the newer version of `autoconf-archive` to `/usr/share/autoconf`; how can I tell `./configure` to find it?
