### ISSUE TITLE
Recipient completion with Ivy erases previous buffer contents 

### ISSUE THREAD

**Issue by thblt** [djcb/mu#1029]
## Expected or desired behavior

Completing of e-mail recipient with Ivy should replace the partial string with the full e-mail and optional name. 

## Actual behavior

A few characters at the left of the point get erased when completing.

Eg, the buffer looks like (point is at `|`):

```
From: Thibault <thblt@anna>
To: eds|
Subject: 
--text follows this line--
```

I hit tab to get completions, select `dif.eds@listes.univ-paris1.fr`, press RET, the buffer becomes:

``` 
From: Thibault <thblt@anna>
dif.eds@listes.univ-paris1.fr
Subject: 
--text follows this line--
```

(notice the To: gets dropped)

 - It seems that that the number of characters deleted is equal to the number of characters to the left of the fragment used for completion.  Eg, if I complete from "dif" instead of "eds", everything works well.   If I complete from "s@listes", the buffer becomes:

    ```
    From: Thibault <thblt@annadif.eds@listes.univ-paris1.fdif.eds@listes.univ-paris1.fr
    --text follows this line--
    ```
 - The bug occurs whether the Ivy completion buffer gets actually displayed or not.  (I don't know if this is Ivy-specific:   if only one completion is found, the Ivy menu doesn't appear and expansion appears immediately on TAB) 

 - This happens only with Ivy.  I haven't been able to reproduce the bug with neither company-mode nor Helm. 

## Steps to reproduce

From `emacs -q` (i use lowercase q to get mu4e in the load path in Debian), require ivy and mu4e.

 - Enter Compose mode
 - Put the point in the "To:" field
 - Start entering a part of a name or e-mail, but not the leftmost part (ie, for someone@example.com, not "some" or "someone".)
 - Accept a completion if the ivy buffer appears.

## Versions of mu, mu4e/emacs, operating system etc.

 - Up-to-date Debian Stretch
 - Packaged Emacs 25.1
 - Packaged mu4e 0.9.18

This may be an Ivy bug, so I'm tagging @abo-abo, the author of Ivy.

**Comment by abo-abo** [comment]
@thblt I use mu4e as well, here's my (short) custom setup: https://github.com/abo-abo/oremacs/blob/github/modes/ora-message.el.

Press <kbd>C-M-i</kbd> to complete email. Let me know if it works for you, I'll include it into `counsel.el` eventually.

**Comment by thblt** [comment]
@abo-abo Thanks for answer and for the link to your config!  `counsel-bbdb-mail` doesn't seem to have the same bug, but completes only with data from bbdb (which I don't really use --- yet) and not from mu4e contacts history.  Is that intended behavior?

**Comment by abo-abo** [comment]
> Is that intended behavior?

Yes.

> mu4e contacts history

I had no idea mu4e had its own contacts. I thought it advised using bbdb.

**Comment by thblt** [comment]
> I had no idea mu4e had its own contacts. I thought it advised using bbdb.

Mu has a kind of rudimentary (yet quite efficient) automated contact management system.  It basically builds a database of everyone you've written to/received mail from along with their associated names.  Try `mu cfind` from the command line.  Structured contacts management requires bbdb (or any other contact manager)

**Comment by djcb** [comment]
Indeed - though I'd say mu4e's contact handling is mostly contact completion rather than contact management (such as what bbdb does).

Anyway, is there anything in this issue for mu4e? 

It's often a bit unclear what package ultimately decides what happens when one presses `TAB` in emacs :-)  FWIW, when I type some letters, then manually call "M-x counsel-company", the completion is appended to the letters I typed, rather than replacing them; that seems like the opposite of what's happening in the issue reported here.

**Comment by thblt** [comment]
> Anyway, is there anything in this issue for mu4e?

I just tested with Helm, and it works (of course, this is one of
the first things I should have done before reporting, but it skipped my
mind).  I believe the issue is with Ivy; my apologies for the noise,
feel free to close this (I don't know how to do this through e-mail and
I don't have web access to GitHub right now).

@abo-abo: Should I create a new issue within the Ivy repository?

**Comment by abo-abo** [comment]
@thblt Yes please.
