### ISSUE TITLE
`mu server` mangles dates before 1970 (UNIX epoch)

### ISSUE THREAD

**Issue by Warbo** [djcb/mu#1038]
## Expected or desired behavior

I use mu4e to read my mail, and also news feeds which I convert from RSS into maildir. Some messages created this way have a `Date:` that's before the UNIX epoch of 1970-01-01, for example the [BBC's Reith Lectures podcast](http://www.bbc.co.uk/programmes/b00729d9/episodes/downloads.rss).

These should be handled and displayed in mu4e like any other message, with the `:date` fields returned by `mu server` containing negative numbers to represent the before-1970 dates. Emacs functions like `format-time-string` can handle such numbers, e.g.

    (format-time-string "%Y-%m-%d" '(-2000 37408 0))

    1965-11-06

## Actual behavior

mu4e triggers `Invalid time specification` errors from Emacs, which seem to come from calls to the `format-time-string` function.

Digging a little further, we find the s-expressions returned by `mu server` contain malformed `:date` fields when the date is before 1970; large values are given, suspiciously close to the largest unsigned 32bit integer, rather than negative numbers. For example, here's a result from querying a `mu server` session run in a terminal (Emacs may have ASCIIfied the control characters):

```
141(
	:docid 80153
	:subject "Man and Nature"
	:from ((nil . "ReithLectures"))
	:date (4294967226 8320 0)
	:size 1631
	:message-id "025c3b74472c0d2f@fake-msgid"
	:path "/home/chris/Mail/feeds/ReithLectures/cur/202432017-01-13 14:56:04.28885730270nixos"
	:maildir "/feeds/ReithLectures"
	:priority normal
	:flags (unread)
)
```

It looks like a problem with the formatting when converting to the s-expression format, since `mu` itself can handle such dates without issue, e.g.

```
$ mu find "Man and Nature"
Sun 09 Nov 1969 01:00:00 BST ReithLectures Man and Nature
```

## Steps to reproduce

 - Index a maildir containing the message from this attached zip [example-msg.zip](https://github.com/djcb/mu/files/802337/example-msg.zip)
 - Run `mu server` on that maildir and perform a query which returns it, e.g. I used `cmd:find query:"maildir:/feeds*"` since the message was nested inside a `feeds/foo` directory.
 - Inspect the `:date` field and see the large value.
 - Try copy/pasting the value into a call of Emacs's `format-time-string` function, and see the "invalid" error message.

## Versions of mu, mu4e/emacs, operating system etc.

32bit NixOS Linux

```
$ mu --version
mu (mail indexer/searcher) version 0.9.16
Copyright (C) 2008-2015 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
$ emacs --version
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

`* mu4e - mu for emacs version 0.9.16 C`

**Comment by djcb** [comment]
Thanks for the detailed report; I've committed a fix.
