### ISSUE TITLE
deleted drafts showing up in threading/related messages

### ISSUE THREAD

**Issue by ksjogo** [djcb/mu#1040]
## Expected or desired behavior

Deleted drafts not shown in threading view/related messages inside emacs header view.

## Actual behavior

Deleted drafts are showing up.

## Steps to reproduce

Write some draft, send it, delete it and it somehow remains there.
Query is `(mu4e~headers-search-execute  "(maildir:/1/INBOX OR /2/INBOX or /3/INBOX) AND NOT flag:draft" t)`

![capture d ecran 2017-03-01 a 10 44 19](https://cloud.githubusercontent.com/assets/699858/23454276/1c02008e-fe6c-11e6-9651-a37f9095c577.png)

**Comment by djcb** [comment]
This is the expected behavior, in fact, since they're part of the "related" messages. You can filter those out with `mu4e-headers-hide-predicate`.
