### ISSUE TITLE
don't add user-agent header if mu4e-user-agent-string is nil

### ISSUE THREAD

**Issue by herrsimon** [djcb/mu#1041]
Hi,

for those of us who prefer not to send a user-agent header: In mu4e-draft.el, could you please condition the insertion of the header on mu4e-user-agent-string being set (so that nothing is inserted if mu4e-user-agent-string is nil)? It's a one-minute fix, i.e. wrapping the insertion in a when-statement, so writing it here is quicker than doing a pull request.

Thanks a lot,

Simon

**Comment by djcb** [comment]
Fixed in git.

**Comment by m4lvin** [comment]
I was looking for a way to modify the user-agent and fortunately found this issue.

Would it be possible to also add the variable to `customize`?
