### ISSUE TITLE
Provide signed tarballs

### ISSUE THREAD

**Issue by jubalh** [djcb/mu#1042]
Hi,
I created a mu package for openSUSE and wondered if you could provide [signed tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases).
Thanks!

**Comment by djcb** [comment]
https://github.com/djcb/mu/releases/tag/1.0-alpha0

**Comment by jubalh** [comment]
Hi,
I saw that you created a new alpha release (unfortunately without updating the NEWS.org file yet). However I am not sure how it relates to this issue, since at least for the alpha release there still is no signed tarball. Will you do it for the final release?
