### ISSUE TITLE
Emacs freezes when trying to delete an email with very long subject

### ISSUE THREAD

**Issue by rekado** [djcb/mu#1043]
## Expected or desired behavior

mu4e should mark the email for deletion and move to the next line.

## Actual behavior

Emacs freezes and uses 100% CPU.

## Steps to reproduce

Sometimes I receive spam where the full message is in the subject line.  In the headers view I go to the line containing the message and hit `d` to mark it for deletion.  At this point Emacs freezes reproducibly.

## Versions of mu, mu4e/emacs, operating system etc.

I'm using mu 0.9.18 on GuixSD.

**Comment by djcb** [comment]
This is most likely an emacs bug; please report it there (similar bugs were seen -- and fixed -- in emacs before)
