### ISSUE TITLE
After saving a draft, undo is broken

### ISSUE THREAD

**Issue by ian-kelling** [djcb/mu#1047]
Compose a new message, write some text, (save-buffer), (undo),

No undo happens. Instead, you get a message:
"Changes to be undone are outside visible portion of buffer"

I've tested this under emacs -Q, so it's not my init file. This works fine when composing in gnus.

versions:
a recent emacs from git commit 244de7b0ed3bb2
a recent mu from git commit ff94595fad2

**Comment by djcb** [comment]
Fixed in git.

**Comment by ian-kelling** [comment]
Awesome! Thank you!
