### ISSUE TITLE
mu4e seems to launch many processes

### ISSUE THREAD

**Issue by gitfoxi** [djcb/mu#1048]
## Expected or desired behavior

Launch fewer, shorter-lived processes

## Actual behavior

It seems a new `mu find` process gets created each time I go to read the next message and it doesn't die very soon (though they don't use any CPU so I guess they're all blocked). If I lean on the next message key for a few dozen emails, my process list looks like:

![image](https://cloud.githubusercontent.com/assets/584005/23883525/c3b397ae-0824-11e7-832f-c5631e86fe0a.png)

Eventually system resources become exausted.

## Steps to reproduce

Just lean on the `mu4e-view-headers-next` and watch your activity monitor filtering for the name `mu`.

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 0.9.18

mu4e-mu-version is a variable defined in ‘mu4e-meta.el’.
Its value is "0.9.18"

- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: work (rev. e956e88a1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm

## Any other detail

Using spacemacs mu4e layer

**Comment by gitfoxi** [comment]
Some profiling might give a clue.

![image](https://cloud.githubusercontent.com/assets/584005/23884470/130a3b8c-082a-11e7-8c5c-4e4c564e7451.png)

**Comment by djcb** [comment]
Can you reproduce this with just plain emacs & mu4e? I suspect `evil` or some other external package might be the culprit here.

**Comment by djcb** [comment]
Any update on this? Thanks.

**Comment by gitfoxi** [comment]
Sorry, but it was config related and I'm not sure how. As a new user I
pasted from several tutorials to get started. After starting from scratch I
don't see any problems.

**Comment by djcb** [comment]
No problem. Closing this for now.
