### ISSUE TITLE
Decode accents in attached file names

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1049]
The accents in attached files names should be decoded when displayed in `*mu4e-view*`.  See the picture for the current behavior.

![eco](https://cloud.githubusercontent.com/assets/1255665/23890133/ab377b98-0890-11e7-8507-e0ffbbfc92e9.png)

Mu4e git version (commit `8f1f88ce`) on Debian.

**Comment by djcb** [comment]
Please attach an example message where this happens, thanks.

**Comment by Chris00** [comment]
Is it OK if I send one privately to you?

**Comment by djcb** [comment]
Best would be to attach it here (if you can create a sufficiently anonymized version); otherwise, just send it it me; thanks.

**Comment by Chris00** [comment]
The (relevant part of the) header is
```
User-agent: mu4e 0.9.19; emacs 25.1.1
Subject: =?utf-8?Q?=C3=89conomie?= : transparents finaux
Return-Receipt-To: <Christophe.Troestler@umons.ac.be>
Disposition-Notification-To: <Christophe.Troestler@umons.ac.be>
Date: Tue, 14 Mar 2017 08:14:27 +0100
Message-ID: <87varcpbxo.fsf@umons.ac.be>
Content-Type: application/vnd.oasis.opendocument.presentation
Content-Disposition: attachment; filename="Travail
 =?us-ascii?Q?=3D=3Futf-8=3FQ=3F=3DC3=3DA0=3F=3D?= qu4tre,
 =?us-ascii?Q?=3D=3Futf-8=3FQ=3F=3DC3=3DA9conomie=3D2Eodp=3F=3D=22?="
Content-Transfer-Encoding: base64
```
That explains the problem... but raises another one as this email was composed with _mu4e_...

**Comment by djcb** [comment]
@Chris00: did you send it to me? Don't think I got it. But, as said, best is to attach a message that has this problem here, otherwise there's is little we can do.

**Comment by Chris00** [comment]
Isn't the above header explaining the problem?  

I can try to compose again an email with that attachment to see whether the filename is wrongly encoded as above.

**Comment by djcb** [comment]
Indeed it's a problem with the encoded filename, ie., `g_mime_part_get_filename` (ie., from the GMime library that mu uses) returns the broken filename, while it does give me the correct (decoded) one for other filenames, ascii or not.

What's the (unencoded) name of the file you tried to attach?

**Comment by Chris00** [comment]
The filename was <code>Travail à qu4tre, économie.odp</code>

**Comment by bderembl** [comment]
I encountered a similar issue

**Comment by djcb** [comment]
Oh, this problem has indeed been fixed, I _suspect_ by a change in GMime:
```
Subject: Économie : transparents finaux
Number of recipients: 0
Flags: seen, attach
Date: 2017-03-14 09:14
Maildir: /inbox
Message-Id: 87varcpbxo.fsf@umons.ac.be
Attachments: [1]Travail à qu4tre, économie.odp(9)
User-Agent: mu4e 0.9.19; emacs 25.1.1
```
