### ISSUE TITLE
mu4e-action-view-in-browser : file saved in /tmp is deleted before the browser can open it.

### ISSUE THREAD

**Issue by marierm** [djcb/mu#1053]
## Expected or desired behavior

mu4e-action-view-in-browser should open an html file in my browser (firefox).

## Actual behavior

Firefox posts an error message that states that the file /tmp/mu4e-xxxxxxx.html cannot be found.  For example:
"Firefox can’t find the file at /tmp/mu4e-2710IVt.html."

## Steps to reproduce
In mu4e, doing M-x mu4e-view-action and then V (which executes mu4e-action-view-in-browser).

## Versions of mu, mu4e/emacs, operating system etc.

I am under Arch Linux, using mu-git 0.9.18.92.g21b637f2-1

## Any other detail

The file /tmp/mu4e-xxxxxxx.html is created and exists for a few seconds, but it is deleted before my browser can open it.

**Comment by djcb** [comment]
I've changed it to auto-delete after 30 secs; does that fix the problem for you?
