### ISSUE TITLE
Customise fringe indicators when `mu4e-compose-format-flowed` is `t`

### ISSUE THREAD

**Issue by joostkremers** [djcb/mu#1057]
When `mu4e-compose-format-flowed` is set, fringe indicators appear in the compose buffer if `visual-line-mode` is used. This behaviour is hard-coded, even though Emacs defaults to not displaying them in `visual-line-mode`, unless the user explicitly sets them.

I find the fringe indicators more annoying than helpful, so I was wondering if you would consider making them customisable. I don't mind if the default would be to display them, but I'd very much like to be able to turn them off.

Thanks!

**Comment by djcb** [comment]
Hmmm, I can't reproduce that. Can you point out where this is hard-coded? Thanks!

**Comment by joostkremers** [comment]
Sorry, I could have been more precise about that. In the definition of `mu4e-compose-mode`, there is the following snippet:

``` emacs-lisp
(when mu4e-compose-format-flowed
      (turn-off-auto-fill)
      (setq truncate-lines nil
	word-wrap t
	use-hard-newlines t)
      ;; Set the marks in the fringes before activating visual-line-mode
      (set (make-local-variable 'visual-line-fringe-indicators)
	'(left-curly-arrow right-curly-arrow))
      (visual-line-mode t))
```

which seems to be the culprit. `visual-line-fringe-indicators` is otherwise set to `(nil nil)`.

**Comment by djcb** [comment]
Okay, yeah, that seems like the thing that should be off by default. Have done so now.

**Comment by joostkremers** [comment]
Great, thanks!
