### ISSUE TITLE
Mu4e doesn't play well with neotree

### ISSUE THREAD

**Issue by moliver-resgen** [djcb/mu#1058]
I'm been using neotree recently (https://github.com/jaypei/emacs-neotree). If neotree is enabled and I run '(mu4e-update-mail-and-index)' or press "U" from the mu4e welcome screen, I get the error "split-window: Cannot split side window or parent of side window". If I toggle neotree to off, it works fine. 

To reproduce, install neotree, enable neotree, configure and run mu4e, then press "U".

Can we get this to send it's output to the minibuffer?

mu for emacs version:  0.9.19
emacs version: 25.1.1
mu4e-get-mail-command: offlineimap

**Comment by djcb** [comment]
It seems this problem is specific for neotree, and mu4e is not the only other package where this happens (a little googling shows). So, I recommend taking this up with the neotree developers -- thanks!
