### ISSUE TITLE
Improve the decoding of quoted-printable emails

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1059]
I received an email with `Content-Transfer-Encoding: quoted-printable` that reads (edited):
```
X a enregistr=E9 le bon de commande n=B045272 d'un monta=
nt total de 5=A06,22 EUR sur le compte 00.=0A=
=0DApprouvez ou refusez ce bon de commande=0A=
=0DCe courriel est envoy=E9 automatiquement
```
The line breaks are decoded properly but not the accented letters.  The output in _*mu4e-view*_ buffer reads:
```
X a enregistr. le bon de commande n.45272 d'un montant total de 5.6,22 EUR sur le compte 00.
Approuvez ou refusez ce bon de commande
Ce courriel est envoy. automatiquement
```
It is encoded in latin-1 and [the correct output should be](http://www.webatic.com/run/convert/qp.php):
```
X a enregistré le bon de commande n°45272 d'un montant total de 5 6,22 EUR sur le compte 00.

Approuvez ou refusez ce bon de commande

Ce courriel est envoyé automatiquement
```
Is there an easy way to specify a default encoding for decoding quoted-printable mail (and to switch on the fly)?  Guessing the correct encoding (in a given sort list of interesting encodings for the user) would even be better.

---
GNU Emacs 25.1.1
Devel version of Mu

**Comment by djcb** [comment]
For any issue involving specific messages, please always attach a raw message that shows the problem, otherwise there is very little we can do -- thanks!

**Comment by Chris00** [comment]
Here is the raw message of a test (mixing latin-1 and UTF-8 — encoded as quoted-printable —
[Uploading test.txt…]()
 on purpose):
```
Received: from AspEmail (10.104.14.50) by smtphost.umons.ac.be (10.104.14.11)
 with Microsoft SMTP Server id 14.3.319.2; Wed, 29 Mar 2017 14:47:21 +0200
From: test <xxx@u.a>
To: <zzz@u.a>
Subject: Bon de commande
Date: Wed, 29 Mar 2017 14:47:21 +0200
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

X a enregistr=E9 le bon de commande n=B045272 d'un monta=
nt total de 5=A06,22 EUR sur le compte 00.=0A=
=0DApprouvez ou refusez ce bon de commande=0A=
=0DCe courriel est envoy=E9 automatiquement

X a enregistr=C3=A9 le bon de commande n=C2=B045272 d'un montant total de 5=
6,22 EUR sur le compte 00.

Approuvez ou refusez ce bon de commande

Ce courriel est envoy=C3=A9 automatiquement

X=20a=20enregistr=C3=A9=20le=20bon=20de=20commande=20n=C2=B045272=20d'un=20montant=20total=20de=2056,22=20EUR=20sur=20le=20compte=2000.=0D=0A=0D=0AApprouvez=20ou=20refusez=20ce=20bon=20de=20commande=0D=0A=0D=0ACe=20courriel=20est=20envoy=C3=A9=20automatiquement=0D=0A
```

**Comment by Chris00** [comment]
(As you can notice, I tried to upload it but havoc ensued...)

**Comment by djcb** [comment]
I think the issue is that the message is not valid utf8 (it mixes in iso-8859-1), mu plays it safe and turns it into ascii, and any of the non-ascii characters (like "é") are turned into dots. So with either ISO-8859 or UTF-8, the message has encoding issues.

So, the problem is with the message. One could try to second-guess and try to repair the message (perhaps some clients do that, which is why the sender gets away with it), but not really planning any work in that direction; but perhaps you can warn the sender.

**Comment by Chris00** [comment]
The first part is a simplified version of what I received.  It is only Latin-1 and is not decoded properly: accented letters are still turned into dots.  I put several encodings in the above message to see whether one was picked up by default by mu.
```
From: test <xxx@u.a>
To: <zzz@u.a>
Subject: Bon de commande
Date: Wed, 29 Mar 2017 14:47:21 +0200
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

X a enregistr=E9 le bon de commande n=B045272 d'un monta=
nt total de 5=A06,22 EUR sur le compte 00.=0A=
=0DApprouvez ou refusez ce bon de commande=0A=
=0DCe courriel est envoy=E9 automatiquement
```
If I put
```
Content-Type: text/plain; charset=UTF-8
```
or
```
Content-Type: text/plain; charset=ISO-8859-1
```
or even
```
Content-Type: text/plain; charset=xxx
```
then mu decodes it fine.
The following message
```
From: test <xxx@u.a>
To: <zzz@u.a>
Subject: Bon de commande
Date: Wed, 29 Mar 2017 14:47:21 +0200
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0


X a enregistr=C3=A9 le bon de commande n=C2=B045272 d'un montant total de 5=
6,22 EUR sur le compte 00.

Approuvez ou refusez ce bon de commande

Ce courriel est envoy=C3=A9 automatiquement

X=20a=20enregistr=C3=A9=20le=20bon=20de=20commande=20n=C2=B045272=20d'un=20montant=20total=20de=2056,22=20EUR=20sur=20le=20compte=2000.=0D=0A=0D=0AApprouvez=20ou=20refusez=20ce=20bon=20de=20commande=0D=0A=0D=0ACe=20courriel=20est=20envoy=C3=A9=20automatiquement=0D=0A
```
is also decoded properly.  There `; charset=utf-8` is important, it does not work with other charsets.

Conclusion: When no charset is specified, couldn't mu use utf-8 (or maybe a default charset given by `mu4e-charset-default`)?
