### ISSUE TITLE
One result without --skip-dups, but zero result with it. 

### ISSUE THREAD

**Issue by YoungFrog** [djcb/mu#1060]
I have a message from someone@mail.example. Running "mu find f:someone@mail.example" finds it (once). I have only one mail from that person, so the output is just that one mail. That's expected.

OTOH, running "mu find -u f:someone@mail.example" does not find it: "mu: no matches for search expression (4)". Not sure how to debug this further. Using -d does not give anything useful in the log file:

> > 2017-04-04 12:43:27 [INFO] logging started
> > 2017-04-04 12:43:27 [INFO] _MuStore: opened /home/youngfrog/.mu/xapian read-only
> > 2017-04-04 12:43:27 [INFO] closing xapian database with 43442 document(s)
> > 2017-04-04 12:43:27 [INFO] logging stopped
> 

> $ mu --version
> mu (mail indexer/searcher) version 0.9.19
>

**Comment by djcb** [comment]
Hmm, try a `mu index --rebuild` from the command-line?

**Comment by YoungFrog** [comment]
It fixed the problem. Does that mean I should be fully rebuilding the index more often ?

**Comment by djcb** [comment]
If rebuilding fixed the problem, it means that normal indexing missed something; are you using e.g. `--lazy-check` or `--nocleanup` and/or their `mu4e` versions?

**Comment by YoungFrog** [comment]
I'm sorry I did not answer, I thought I had. I don't currently use lazy-check or nocleanup, but I used to. Not sure if I was using those when the problem began to appear. I'll re-open this report if I can bring new information.
