### ISSUE TITLE
Fancy chars attachment mark causes mis-alignment

### ISSUE THREAD

**Issue by izahn** [djcb/mu#1062]
## Expected or desired behavior
Subject column in the headers view should be left-aligned.

## Actual behavior
Alignment is good except that the subject column for messages with attachments is mis-aligned by exactly one character, as shown in the attached screenshot.
![mu4e-align](https://cloud.githubusercontent.com/assets/321235/24670329/9b385f3a-193b-11e7-9c04-f56453ab7bc9.png)

## Steps to reproduce
Start Emacs, set `mu4e-use-fancy-chars` to `t` and open a headers view.

## Versions of mu, mu4e/emacs, operating system etc.
mu 0.9.18 on Emacs 26.0.5. Same problem on Emacs 25.1.1.

## Any other detail
I'm using https://github.com/cpitclaudel/monospacifier to get mono-space Symbola, but I see this problem with or without it. It only happens for some characters, for example, setting `mu4e-headers-attach-mark    '("a" . "a")` results in perfect alignment, as does `mu4e-headers-attach-mark    '("a" . "✔")`. I use Dejavu Sans Mono for my default font, and it seems like the problem happens with characters not available in that font. The weird thing is that alignment is off by _exactly_ one character, and in the opposite of the direction I would expect given that Symbola is usually wider than DejaVu.

**Comment by djcb** [comment]
There's unfortunately not much we can do about this from mu..., except that you can use non-fancy chars if it bothers you enough.

**Comment by izahn** [comment]
Do you know what causes it? I'm happy to report it elsewhere if appropriate, but mu4e is the only place I can reproduce the problem.

Just to make sure the problem I reported is clear, here is a screenshot with `whitespace-mode` turned on. 

![mu4e-align-whitespace](https://cloud.githubusercontent.com/assets/321235/24828556/91eb9466-1c2d-11e7-94e5-c2553009cb9f.png)

As you can see there is a missing space following the paperclip character. 

Again, if this isn't a mu4e issue I would be very grateful for any information that will help me report the issue to the appropriate project.

**Comment by naclander** [comment]
@djcb @izahn I am seeing and still experiencing the same issue. This issue also happens without fancy-chars, but rather just by using line-numbers. It seems to me like the mu4e row heades don't change regardlses of where the columns actually start. 

I don't see any evidence to suggest this isn't a problem with mu4e, specfically with mu4e-headers. Example screenshot:

![](http://i.imgur.com/9lYVRYs.png)

**Comment by bradyt** [comment]
Bug in Unicode character width in Emacs 25.1, bisected to a761fbf	(Unicode 9.0.0beta import)
https://lists.gnu.org/archive/html/emacs-devel/2016-09/msg00537.html
> ... The mu4e mode has a mu4e-use-fancy-chars option which if set will use ...

**Comment by bradyt** [comment]
Would it be possible to add a space in the setting, to account for emacs eating the space? So something like 

```
(setq mu4e-headers-attach-mark "⚓ ")

;; For readability across fonts, consider the same result from other notation:
;; (setq mu4e-headers-attach-mark (concat "⚓" " "))
;; (setq mu4e-headers-attach-mark (concat '(?\u2693 ?\u0020))
```

I've decided to go with `"@"` for now. But it seems if only mu4e allowed an extra space to be added, it might line up again. Adding the space, does not seem to survive through mu4e's formatting. Perhaps this could be hacked in to the source?

**Comment by cpbotha** [comment]
Perhaps I like color emojis too much, but I did manage to get my mu4e replies to line up perfectly, even for mails with 4 fancy icons.

See e.g.:
![image](https://user-images.githubusercontent.com/937871/147934242-93296a92-7661-435a-8e3b-ebaf444abeba.png)

The trick was to activate precise alignment:

```
  (setq mu4e-use-fancy-chars t)
  ;; without precise alignment, the subjects of e.g. replied to emails are
  ;; shifted right by an extra character
  (setq mu4e-headers-precise-alignment t)
```

... and to give the field column more space:

```
(setq mu4e-headers-fields
        '(
          ;; alternatively, use :human-date
          (:date          .  25) 
          ;; default here is 6, however with fancy-chars, each emoji takes 2 spaces so we need wider field
          (:flags         .   10) 
          (:from          .  22)
          ;; alternatively, use :thread-subject
          (:subject       .  nil)))
```
