### ISSUE TITLE
Progress lines broken on FreeBSD

### ISSUE THREAD

**Issue by duncan-bayne** [djcb/mu#1063]
## Expected or desired behavior

I expect progress lines to update as progress occurs (i.e. only a couple of lines be displayed, at most).

## Actual behavior

Progress updates append to the existing progress line, instead of replacing it.  This looks like a problem with CR on this platform?

![mu4e-progress](https://cloud.githubusercontent.com/assets/65949/24681376/420b283c-19d8-11e7-84e8-7101973cac99.png)

## Steps to reproduce

1. Start mu4e with `M-x mu4e`.
2. Select my context.
3. Sync mail with `C-c C-u`.

## Versions of mu, mu4e/emacs, operating system etc.

```
➜  ~ mu --version
mu (mail indexer/searcher) version 0.9.16
Copyright (C) 2008-2015 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
➜  ~ emacs --version
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
➜  ~ uname -a
FreeBSD x220 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #0: Wed Feb 22 06:12:04 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by djcb** [comment]
If you're an elisp coder, you could check the function `mu4e~get-mail-process-filter` and see if it could be improved for FreeBSD and/or with the mail fetcher program.

Otherwise, note that you can put arbitrary shell commands in `mu4e-get-mail-command`, so you could try to append e.g. `| tr -d '\r'` to see if that makes a difference.

**Comment by duncan-bayne** [comment]
Having a poke around, it looks like the exact opposite problem - the `\r` characters are expected to reset the point to the start of the line (as per a conventional shell) but they're not.  I'm mildly surprised this worked on Linux :confused: Will investigate further.

**Comment by duncan-bayne** [comment]
(Setting up a Linux VM so I can debug that, and FreeBSD, side by side.  Now suspecting that the FreeBSD shell is returning different strings to elisp.)

**Comment by djcb** [comment]
Any further results?
