### ISSUE TITLE
coding system prompt when sending unicode symbols

### ISSUE THREAD

**Issue by ian-kelling** [djcb/mu#1064]
## Steps to reproduce

Send a message with a unicode char, in my case, it was the trademark symbol ™, you get a prompt about the coding system, which should not happen.

On my big screen, the window gets split into several buffers at the time of the prompt. One says:

    These default coding systems were tried to encode text
    in the buffer ‘1491537237.08028a9c05484e47.treetowl:2,S’:
      (utf-8-unix (260 . 4194274) (261 . 4194180) (262 . 4194210))
    However, each of them encountered characters it couldn’t encode:
      utf-8-unix cannot encode these:   \342 \204 \242

    Click on a character (or switch to this window by ‘C-x o’
    and select the characters by RET) to jump to the place it appears,
    where ‘C-u C-x =’ will give information about it.

    Select one of the safe coding systems listed below,
    or cancel the writing with C-g and edit the buffer
       to remove or modify the problematic characters,
    or specify any other coding system (and risk losing
       the problematic characters).

      raw-text no-conversion

At the same time another buffer pops up, which has the message, backed by a sent file, with the trademark symbol displayed as \342\204\242 as special individual characters, the same goes for them in the buffer above, which if coped together to another buffer, is displayed as the trademark symbol. The minibuffer prompt seems to be prompting about saving this buffer.

If I select the default: raw-text something, the message is sent and everything is fine. The sent file is encoded as utf-8, just like any other.

I did a backtrace while the prompt was up, and got this:

    "read-from-minibuffer" (0xffffab80)
    "ivy-read" (0xffffb070)
    "ivy-completing-read" (0xffffb348)
    "read-coding-system" (0xffffb4f8)
    "select-safe-coding-system-interactively" (0xffffb9d8)
    "select-safe-coding-system" (0xffffbea8)
    "write-region" (0xffffc4c8)
    "basic-save-buffer-2" (0xffffc840)
    "basic-save-buffer-1" (0xffffca50)
    "basic-save-buffer" (0xffffcda0)
    "save-buffer" (0xffffcfd0)
    "write-file" (0xffffd210)
    0x457d7c0 PVEC_COMPILED
    "apply" (0xffffd440)
    0x4f8baf0 Lisp type 3
    "message-do-fcc" (0xffffd910)
    "message-send" (0xffffdc48)
    "message-send-and-exit" (0xffffdef0)
    "funcall-interactively" (0xffffdee8)
    "call-interactively" (0xffffe130)
    "command-execute" (0xffffe3c8)

I'm using a recent mu from git, 87ed69ee0314
recent emacs from git, 022755953fc63e

I tested with a minimum configuration. I also tested sending a message from gnus with no configuration and did not hit this. I'd like to figure out a fix, but I'm hoping someone else can do it faster than me.

**Comment by ian-kelling** [comment]
I couldn't resist working on it, I've made some progress, I will comment on progress.

It seems the problem is with `(message-encode-message-body)`
if I do a write-file before it, I don't get the prompt. save after it, I do get the prompt. Digging into that function now.

**Comment by ian-kelling** [comment]
Changing tacts. Maybe it's not the encoding, but how we handle saving
that should be fixed, after all, gnus saves sent messages in maildir
format without prompting. I see in gnus saved message,
it sets Content-Transfer-Encoding: base64, and so the body has no
nonascii chars, and it decodes it when you open the message in gnus,
wheras in mu4e, it's set to 8bit.

Related: Mu4e sets `message-fcc-handler-function` to a function which
primarily does `(write-file some_file)`.

Going to bed. Gonna try to leave this alone so someone else can look at it.

**Comment by djcb** [comment]
This has started happening with recent emacs development versions, see: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25645

So, it seems due to that; we could perhaps set `Content-Transfer-Encoding`, but I'd rather not do that in general.

**Comment by ian-kelling** [comment]
Yes, it seems the best solution is for this to be fixed in emacs, likely in message.el. In that case, further comments should be directed to the emacs bug report.

**Comment by djcb** [comment]
Yeah, hope they'll fix that. Closing this for now.
