### ISSUE TITLE
How can I insert inline images when composing an email?

### ISSUE THREAD

**Issue by amosbird** [djcb/mu#1067]
I've googled for a while but couldn't find anything useful. Is it supported by `mu4e`?

**Comment by djcb** [comment]
`C-c C-a` (`mml-attach-file`) should do the trick.

**Comment by amosbird** [comment]
@djcb um, I just tested an inline image added by `C-c C-a`. It isn't shown in the correct position in gmail client.

**Comment by djcb** [comment]
Sadly we can't influence the way gmail (or other clients) decide to display images in plain-text images.
