### ISSUE TITLE
Cannot send emails containing Chinese characters without being prompted.

### ISSUE THREAD

**Issue by amosbird** [djcb/mu#1068]
## Expected or desired behavior

Sending mails without prompting.

## Actual behavior

When composing an email with Chinese characters, I always need to select some encoding, like the `raw-text` in order to close the composing buffer. In fact, when I'm prompted by the encoding error, the email has already been sent correctly with good encoding.

![](https://paste.wentropy.com/yx3d.jpg)

## Steps to reproduce

Compose an email with `你好，世界` inside mail content and send it.

## Versions of mu, mu4e/emacs, operating system etc.
mu (mail indexer/searcher) version 0.9.19
mu4e, um, how can I get this version? I think it's 0.9.19 too.
emacs 26.0.50
Archlinux

**Comment by jschwab** [comment]
This sounds like #1064.

**Comment by djcb** [comment]
Indeed. It's an (annoying!) issue with the development version of emacs.
