### ISSUE TITLE
mu4e deletes one more message in evil visual line mode 

### ISSUE THREAD

**Issue by amosbird** [djcb/mu#1069]
## Expected or desired behavior

Delete the exact amount of message.
Please describe the behavior you expected / want

## Actual behavior

Delete one more message next to the selected region.
![](https://paste.wentropy.com/tsYS)

## Steps to reproduce

in evil mode, press `V` and start selecting, then press `D`.

## Versions of mu, mu4e/emacs, operating system etc.
mu (mail indexer/searcher) version 0.9.19
emacs 25.2
Archlinux

**Comment by bastibl** [comment]
I use this patch with evil, but I didn't test it with normal emacs:

```
diff --git a/mu4e/mu4e-mark.el b/mu4e/mu4e-mark.el
index 34582fd..5ed10fe 100644
--- a/mu4e/mu4e-mark.el
+++ b/mu4e/mu4e-mark.el
@@ -321,7 +321,7 @@ headers in the region. Optionally, provide TARGET (for moves)."
     (save-excursion
       (let ((cant-go-further) (eor (region-end)))
        (goto-char (region-beginning))
-       (while (and (<= (point) eor) (not cant-go-further))
+       (while (and (< (point) eor) (not cant-go-further))
          (mu4e-mark-at-point mark target)
          (setq cant-go-further (not (mu4e-headers-next))))))))
```

**Comment by amosbird** [comment]
thanks!
