### ISSUE TITLE
Mu4e treats plaintext attachments as though they were the message instead of an attachment

### ISSUE THREAD

**Issue by dakrone** [djcb/mu#1072]
## Expected or desired behavior

When I receive a message that has `Content-Type: text/html` for the body and a `Content-Type: text/plain` attachment, mu4e displays only the plaintext attachment, instead of the message. I expect either an interpreted version of the message (with `mu4e-shr2text`) to be shown.

## Actual behavior

Mu4e only displays the plaintext attachment, instead of the message. Pressing `h` toggles between the HTML message (actual email content) and the plaintext .txt attachment.

Additionally, when replying to the message, only the plaintext attachment is quoted, rather than the actual message.

## Steps to reproduce

Receive email with an HTML-only body and plaintext attachment, attempt to view and respond to the email (I can provide the output from `mu4e-view-raw-message` if you provide an email address to send it to, I'd rather not publicly post it)

## Versions of mu, mu4e/emacs, operating system etc.

Using 0.9.18 of both mu and mu4e
Emacs 25.2
Fedora 25 4.10.11-200.fc25.x86_64

## Any other detail

Thanks for mu4e!

**Comment by cody-addison** [comment]
Are there any workarounds for this issue? I constantly have to deal with this problem. It is very annoying when forwarding an email message because the original text is lost. I am using version 1.0

**Comment by djcb** [comment]
Okay, this works now with the new (experimental) view mode -- `(setq mu4e-view-use-gnus t)` (before starting mu4e). Finally!

**Comment by cody-addison** [comment]
Thanks! This does indeed solve the problem and overall the setting works well. For attachments that can open in emacs (text and pdf), the new view is great. For attachments like powerpoint the old mu4e-view-open-attachment doesn't work. It seems like I have to save the attachment somewhere (specified by me) and then open it manually. Is there a configuration I could set to get the old behavior or is this something that still needs to be implemented? I understand this is an experimental feature.

**Comment by djcb** [comment]
Well, there are certainly some rough edges, but it works surprisingly well already.

At least with latest git (and restart emacs!) + a suitable `/etc/mailcap` you should be able to open ppts (with `impress`). Just try right-clicking on the attachment (or the corresponding keyboard action).
