### ISSUE TITLE
Installation `--with-emacs` via homebrew broken

### ISSUE THREAD

**Issue by Gastove** [djcb/mu#1073]
## Expected or desired behavior

`brew install mu --with-emacs` should install mu + mu4e.

## Actual behavior

At time of writing, installation fails because `glib-sharp-2.0` is unavailable:

```sh
$ brew install mu --with-emacs
==> Using the sandbox
==> Downloading https://github.com/djcb/mu/releases/download/0.9.18/mu-0.9.18.tar.gz
Already downloaded: /Users/rossdonaldson/Library/Caches/Homebrew/mu-0.9.18.tar.gz
==> Downloading https://download.gnome.org/sources/gmime/2.6/gmime-2.6.23.tar.xz
Already downloaded: /Users/rossdonaldson/Library/Caches/Homebrew/mu--gmime-2.6.23.tar.xz
==> ./configure --prefix=/usr/local/Cellar/mu/0.9.18_1/gmime --disable-introspection
Last 15 lines from /Users/rossdonaldson/Library/Logs/Homebrew/mu/01.configure:
checking for GPGME pthread - version >= 1.1.6... no
checking for mcs... /usr/local/bin/mcs
checking whether /usr/local/bin/mcs is GNU Mono... yes
checking for gacutil... /usr/local/bin/gacutil
checking for GLIB_SHARP... no
configure: error: Package requirements (glib-sharp-2.0 >= 2.4.0) were not met:

No package 'glib-sharp-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GLIB_SHARP_CFLAGS
and GLIB_SHARP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

READ THIS: http://docs.brew.sh/Troubleshooting.html
```

## Steps to reproduce

`brew install mu --with-emacs`

## Versions of mu, mu4e/emacs, operating system etc.

OSX 10.12; no version of mu currently installed :P 

## Any other details

I write a lot of F#, and thus have a pretty current mono installation. Have not yet been able to find a good way to manually install that dep.

**Comment by benyomin** [comment]
also reported here https://github.com/Homebrew/homebrew-core/issues/11476   me too!  help!

**Comment by benyomin** [comment]
install from source fails with

    make
    ./mu-msg-priv.h:29:10: fatal error: 'gmime/gmime.h' file not found
    #include <gmime/gmime.h>

home-brew currently installs gimme 3 but ./configure wants gmime >2.6 and can't find the installed version.

    /usr/local/Cellar/gmime/3.0.0

**Comment by danielsmw** [comment]
I reported in https://github.com/Homebrew/homebrew-core/issues/11476#issuecomment-298896783 a solution (that worked for me at least) to @benyomin 's problem. I was also having trouble finding gmime. I didn't have any problems with glib, but maybe there's a similar fix (I simply had to add some environment variables in the formula).

**Comment by drielsma** [comment]
This workaround fixes the `gmime` build issue but I think (hope) what @Gastove is reporting is the fact that, once you're worked around that, brew hasn't installed `mu4e` at all.

**Comment by Gastove** [comment]
@drielsma huh. Actually, @danielsmw's work-around entirely fixed it for me -- after `brew edit`, `brew install mu --with-emacs` correctly installed mu and mu4e.

**Comment by neurolit** [comment]
Hi!

After having installed [Mono](http://www.mono-project.com/download/), this issue was solved for me.

**Comment by benyomin** [comment]
thanks @neurolit installed Mono 5.0 Beta 2 (5.0.0.94), http://www.mono-project.com/download/beta/ (1 GB)  then

    install mu --with-emacs
    success!

**Comment by Gastove** [comment]
N.B. @benyomin `mono` is also available from `brew`, if you'd rather manage it all in one place.

**Comment by djcb** [comment]
Ah, good to hear it works again; anyway, seems to be Homebrew issue, not a mu issue, so closing this.

**Comment by KryDos** [comment]
Here I tried to fix it without Mono installation - https://github.com/Homebrew/homebrew-core/issues/11476#issuecomment-299645313
I hope it can be helpful for someone

**Comment by anicholson** [comment]
I already had `mono` installed and still had issues; @KryDos 's solution appears to have worked for me.

**Comment by picaschaf** [comment]
It again seems to be broken ...
