### ISSUE TITLE
Improve mu4e-headers-advance-after-mark

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#1076]
I just updated and noticed we now have ``'mu4e-headers-advance-after-mark.``
What if we allow this to be t (advance), nil (do nothing) and implement -1 (go backwards)?

Even when sorting by reverse date, I usually start reading messages in chronological order (from the bottom). When marking or going to the next unread message, I'd love to move upwards.

Since it's not easy to determine the proper direction, I'd say this sounds the first step in this direction.

**Comment by djcb** [comment]
Not planning this right now, sorry!
