### ISSUE TITLE
mu4e clobbering ido

### ISSUE THREAD

**Issue by theophilusx** [djcb/mu#1078]
## Expected or desired behavior

It appears that mu4e is clobbering ido. After starting mu4e you get the following error when you try to use commands that use ido-completing-read

Error in post-command-hook (ido-exhibit): (args-out-of-range "" 0)

From this point onwards, you cannot use C-h v (which is configured to use ido).
Ido will report a LARGE number of completions i.e. over 13,000 and you cannot enter more than 2 characters (subsequent characters overwrite the 2nd character).. You also cannot move through the list of possible completions. From this point on C-h v will not work. Exiting mu4e does not help.

## Actual behavior

Should be no change to ido operation. 

The error we see is 

Error in post-command-hook (ido-exhibit): (args-out-of-range "" 0)

## Steps to reproduce
To reproduce

 
require ido

install following packages from melpa
ido-completing-read+-20170313.1603
ido-ubiquitous-20170313.1603

and activate them. 

Start mu4e

Do C-h v to lookup a variable.

At this point, the above error will be reported to the *Messages* buffer. Setting debug-on-error does not generate a backtrace. 

Try to type the name of a variable to lookup. You will only be able to type 2 characters and will not be able to do any variable name completion. 

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 25.2 on Linux (Ubuntu 17.04). 
mu and mu4e 0.9.18
ido-completing-read+-20170313.1603
ido-ubiquitous-20170313.1603

**Comment by djcb** [comment]
Hmm, does it happen with just plain `ido`? Otherwise, it's probably better to file an issue against of the `ido` extension packages you are using. There doesn't seem much `mu4e` can do about this.

**Comment by theophilusx** [comment]
Looks like it is a problem with ido-ubiquitous. I have quite a few packages, but only mu4e seems to trigger this issue. Not sure why - maybe leave this issue here in case other mu4e users run into it? Have referenced it in an ido-ubiquitous issue in case it helps them test/fix the issue.

**Comment by DarwinAwardWinner** [comment]
The underlying culprit a bug in ido, which I just reported here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=26997

So this is definitely not a mu4e bug.

**Comment by theophilusx** [comment]
Confirm that the fix proposed in the bug report logged against core ido does fix the issue and that the problem is with underlying ido in emacs 25.2 and not an issue with mu4e.
