### ISSUE TITLE
sent messages displayed in inbox w/ mu4e-headers-show-threads nil

### ISSUE THREAD

**Issue by bderembl** [djcb/mu#1079]
when using
(setq mu4e-headers-show-threads nil)
I now see sent messages in my inbox with mu4e 0.9.19 C
(this was not the case in 0.9.16)

**Comment by djcb** [comment]
You can change that with `mu4e-headers-include-related`. The default may have changed.

**Comment by bderembl** [comment]
thanks. sorry I missed that change
