### ISSUE TITLE
Messages without a Date header treated as 1970-01-01

### ISSUE THREAD

**Issue by yurkobb** [djcb/mu#1083]
## Expected or desired behavior

I've noticed that some messages (namely notifications from drupal about available updates) arrive without a Date field. Mu then treats them as having arrived on 1970-01-01. However, it would probably make more sense to infer the date from one of the `Received:` headers to display them among recent messages.

## Actual behavior
Mu treats `Date`-less messages as having arrived on 1970-01-01, and as a result they don't show up in recent mail views.

## Steps to reproduce

Put a message without a `Date:` field into your maildir's `new` folder. Update your INBOX header view.

## Versions of mu, mu4e/emacs, operating system etc.
mu4e 0.9.18 C

**Comment by djcb** [comment]
RFC 2822 specifies that messages should have a Date: to be proper messages (it's one of very view required fields), so I suppose Drupal is at fault here.

Of course mu *could* try to guess the date nevertheless, but it's a bit too much work for a corner-case. Probably best to complain with the Drupal folks.

**Comment by Chris00** [comment]
It was not said clearly by the @yurkobb but maybe the problem he faces is that such messages do not appear in his inbox as they are older than the 500 first ones.  If so, one solution would be to use a date in the future when the `Date` field is absent.

**Comment by yurkobb** [comment]
> RFC 2822 specifies that messages should have a Date: to be proper messages

I suspected that it is a violation of the standard. But should `mu` produce some kind of error then, instead of silently treating it as the unix epoch?

Currently, the behavior visible for the user is that some kind of interpretation still happens (date = 1970), although it may not be intentional. (An alternative interpretation of "no date" could be to always sort it newest, rather than oldest, although that is weird too).

**Comment by djcb** [comment]
We could add a warning in the log, but generally we try to show messages, correct or not (and the incorrect ones are a tiny subset, at least in the mails that I receive).

Anyway, instead of inventing fragile hacks, it's must preferable to fix the problem at the source, by getting Drupal to send messages with a Date: header. Do you have a link to the bug report?

**Comment by yurkobb** [comment]
I don't use Drupal anymore, so before submitting a bug report I would have to check the bug is still there.

I _think_ I got a couple other cases with messages arriving without a Date field, but have since deleted them.

Anyway, this is not a big deal, mu4e is highly usable for me as is.

A slightly related kind of UX issue / question (probably out of scope of this issue, but also maybe not too important yet to open a new discussion) - sometimes it is hard to identify a message if for some reason it arrived significantly later than its `Date` field (I've had this happen with some mailing list emails). In this case it appears somewhere between the 50 or so messages that fit on my screen, about 30% of which can be unread. This question is about a hypothetical "diff-like" highlighting the messages that appeared since the last `mu4e-update-mail-and-index` run. Just a thought / idea.

**Comment by berke** [comment]
I just ran into this issue, some bank changed their mail software and the Date: field is no longer there.  I see two solutions:
- When indexing, if the declared Date: is absent, use the file timestamp.
- Add a new indexing key, e.g. date-indexed or something like that, separate from the declared Date:, and add whatever is necessary to mu4e so that the mailbox view can be sorted by that date.
I tested the first solution it seems to work, will create a pull request.

**Comment by Deltafire** [comment]
I've just ran into this issue, found a bunch of email I'd not seen because mu was dating them incorrectly.

The issue is still present.

I think PR #2175 is a better solution than setting the date to 1970, which is effectively hiding the email for a lot of users.

**Comment by Deltafire** [comment]
Just noticed a few things:

1. mu displays the date as 1970-01-01, but the emails aren't shown by ```mu find date:1970``` or any date range that would cover it.
2. mu4e always displays the message as the current time in the header view, but won't show the message if filtered on ```date:today..```
