### ISSUE TITLE
mu4e marks PGP signature as verified even if the key doesn't match sender email

### ISSUE THREAD

**Issue by thblt** [djcb/mu#1084]
See## Expected or desired behavior

When displaying a PGP-signed message, mu4e should check that the signing key is valid for *this* message, ie verify that the e-mail associated with the key actually match the sender's email.

## Actual behavior

When displaying a PGP-signed message, mu4e marks the message as verified if it's correctly signed with a key in store, even if that key doesn't match the sender e-mail.  Eg, a message `From: alice@example.com` signed with a PGP key associated with `mallory@example.com` will appear verified.

## Steps to reproduce

Send a message to yourself, signing it with a key not matching the e-mail you're sending from.

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 25.2 on Debian Stretch, mu/mu4e 0.9.18 from official repositories.

Thanks!

**Comment by djcb** [comment]
Turns out that automatically using the From: address gives way too many false negatives; but, I've changed things so that the information about the signer is shown next to the "verdict", so users can easily check.

Fixed in git.

**Comment by thblt** [comment]
Thank you!
