### ISSUE TITLE
`mu4e-view-mark-for-untrash' bound but not defined.

### ISSUE THREAD

**Issue by joostkremers** [djcb/mu#1085]
`mu4e-view-mode-map` binds `=` to `mu4e-view-mark-for-untrash`, but this function is not defined. It seems that the necessary line

    (mu4e~view-defun-mark-for move)

is missing from `mu4e-view.el`.

Just pulled from the repo this morning.

**Comment by djcb** [comment]
Ah, good catch, thanks. Fixed.
