### ISSUE TITLE
enable auto-retrieve-key:true for mu server view process.

### ISSUE THREAD

**Issue by jamesrichardsonjr** [djcb/mu#1086]
## Expected or desired behavior

I would like for gpg keys to be automatically downloaded when reading messages.

## Actual behavior

Keys aren't being downloaded to be used for verification.

Would you accept a patch to enable this (with appropriate configuration, .e.g. should remain off unless user specifically enables such)?

**Comment by djcb** [comment]
That sounds useful -- can you give a brief outline of how you plan to implement this?

**Comment by djcb** [comment]
With the new (experimental) view mode -- `(setq mu4e-view-use-gnus t)` (before starting mu4e), this is part of gnus' article-mode. Anyway, not much activity on this issue; closing.
