### ISSUE TITLE
2.2.1 Dependencies for Debian/Ubuntu in the manual

### ISSUE THREAD

**Issue by gluesniffmonkey** [djcb/mu#1091]
On a new clean install of Debian Stretch I found I also needed to install autoconf-archive and dh-autoreconf. Uncertain if this would apply on Ubuntu. 

I recommend that the manual **2.2.1 Dependencies for Debian/Ubuntu** be updated to read:

`$ sudo apt-get install libgmime-2.6-dev libxapian-dev dh-autoreconf autoconf-archive
`

**Comment by djcb** [comment]
Oh sure, can you prepare a PR?
