### ISSUE TITLE
mu4e eats characters when marking and unmarking

### ISSUE THREAD

**Issue by amosbird** [djcb/mu#1092]
## Expected or desired behavior

correct rendering when doing marks.

## Actual behavior

As described in this screencast, 
https://la.wentropy.com/vmJy.webm

## Steps to reproduce

same as in the above screencast.

## Versions of mu, mu4e/emacs, operating system etc.

Archlinux 
emacs 25.2
mu (mail indexer/searcher) version 0.9.19

**Comment by edumerco** [comment]
Hi Amos.

> Actual behavior
> As described in this screencast,
> https://la.wentropy.com/vmJy.webm

I can confirm this in version 0.9..18 too.

-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by djcb** [comment]
Hmm, the video seems to have gone. Can you update it?

**Comment by amosbird** [comment]
ok, let me redo the screencast :smile: 

btw, there is another one that shows the link clicking issue   https://la.wentropy.com/lvJW.webm

**Comment by amosbird** [comment]
here you go   https://la.wentropy.com/NXAn.webm

**Comment by djcb** [comment]
Video has gone... if this is still an issue, please open a ticket with some steps to reproduce (no videos needed :))
