### ISSUE TITLE
Cannot build mu4e with GNU Emacs 25.2.1

### ISSUE THREAD

**Issue by Sbozzolo** [djcb/mu#1093]
Hello, I am using Arch Linux fully updated with GNU Emacs 25.2.1.
Indeed:
`echo $EMACS`
results in
`25.2.1 (term:0.96)`
When I run `.\autogen.sh` with the latest source code from GitHub I get this error
```
checking for emacs... 25.2.1 (term:0.96)
checking where .elc files should go... ./configure: line 18733: test: too many arguments
${datadir}/emacs/site-lisp
./configure: line 18766: 25.2.1: command not found
```
And indeed mu4e is not build. How can I solve?

I can provide other information if required.

Bye,
sbozzolo

**Comment by djcb** [comment]
Hmmm, `EMACS` is expected to contain name / path of emacs, not the version. I guess you should make sure that `EMACS` is a what's expected, or use e.g.
```
./autogen.sh EMACS=/usr/bin/emacs
```
