### ISSUE TITLE
start and stop something on mu4e and mu4e-quit

### ISSUE THREAD

**Issue by grauschnabel** [djcb/mu#1096]
Hi there,

I like that: https://martinralbrecht.wordpress.com/2016/05/30/handling-email-with-emacs/

Now I would like to do `(prodigy-start-service (prodigy-find-service "imapnotify"))` when `(mu4e)` is run (like a mode-hook maybe?)  and `(prodigy-stop-service (prodigy-find-service "imapnotify"))` when `(mu4e-quit)` is run.

How can I do that?

**Comment by djcb** [comment]
Yeah, a mode-hook should do the trick. 

Or create your own do-my-thing-and-start-mu4e function to combine the two. For quit, I suppose you can advise that function. Or bind your own do-my-thing-and-stop-mu4e function to the 'q' key in mu4e.
