### ISSUE TITLE
mu find: db version: 9.9, but we need 9.9

### ISSUE THREAD

**Issue by Quintus** [djcb/mu#1098]
## Expected or desired behavior

`mu find` should show some messages when I run a command like this:

~~~~
$ mu find --muhome=~/.cache/mu --clearlinks s:FooBar
~~~~

## Actual behavior

`mu find` prints an error message that does not make sense. It says the DB is version 9.9 while saying in the same moment that 9.9 is required.

~~~~
$ mu find --muhome=~/.cache/mu --clearlinks s:FooBar
database needs a rebuild; try 'mu index --rebuild'
mu: db version: 9.9, but we need 9.9; database rebuild is required (15)
~~~~

This index has been freshly created from my amount of >50000 mails in a maildir++ using this command:

~~~~
$ mu index --muhome=~/.cache/mu --maildir=~/.local/share/mail
indexing messages under /home/quintus/.local/share/mail [/home/quintus/.cache/mu/xapian]
\ processing mail; processed: 70800; updated/new: 70800, cleaned-up: 0
cleaning up messages [/home/quintus/.cache/mu/xapian]
| processing mail; processed: 70820; updated/new: 0, cleaned-up: 0
elapsed: 0 second(s)
/ processing mail; processed: 70820; updated/new: 0, cleaned-up: 0
elapsed: 292 second(s), ~ 242 msg/s
~~~~

The problem is 100% reproducible, it happens always.

## Steps to reproduce

1. Create a maildir with messages
2. Run `mu index --muhome=~/.cache/mu --maildir=~/.local/share/mail`
3. Run `mu find --muhome=~/.cache/mu --clearlinks s:FooBar`
4. Observe nonsense error message

## Versions of mu, mu4e/emacs, operating system etc.

~~~~
$ mu --version
mu (mail indexer/searcher) version 0.9.9.6
Copyright (C) 2008-2013 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
~~~~

mu4e was not involved; this is plain mu. Running on Gentoo Linux.

I usually use mu with mutt, but the above issue can be reproduced by just using the mu commandline as outlined.

## Any other detail

There is also #692, but that involved mu4e, which I do not use at all.

**Comment by Quintus** [comment]
Nevermind, the problem is gone in 0.9.18, which Gentoo does not ship yet. See https://bugs.gentoo.org/show_bug.cgi?id=618564

Sorry for the noise.

**Comment by namedtoaster** [comment]
Is that mu version 0.9.18? How do I upgrade to that?
