### ISSUE TITLE
Mailbox/Index inconsistency

### ISSUE THREAD

**Issue by f0086** [djcb/mu#1101]
## Expected or desired behavior

Display the correct number of mails

## Actual behavior

Some mails are missing.
This happens if I move a mail from one folder to another.

## Steps to reproduce

Move a mail from /INBOX to /ACTION
Update index
Move to the /ACTION mailbox

The search function also do not find the missing mails.

## Versions of mu, mu4e/emacs, operating system etc.

ArchLinux
Emacs 25.2.1
mu4e 0.9.18

## Any other detail

![s1498562054-24184](https://user-images.githubusercontent.com/121972/27585147-5bfc9704-5b3b-11e7-847c-01f7fb29ae3b.png)
![s1498562061-13081](https://user-images.githubusercontent.com/121972/27585148-5bff9576-5b3b-11e7-963e-b7e180eb8484.png)
![s1498562086-3247](https://user-images.githubusercontent.com/121972/27585149-5c015866-5b3b-11e7-8199-9177f7f190ac.png)

**Comment by f0086** [comment]
This problem still exists. Not only on the folders, but also on search results.
Any idea how to debug this?

**Comment by seanfarley** [comment]
I saw this behavior when using `mu4e-index-cleanup`. Do you have variable set?

**Comment by f0086** [comment]
I've found my problem: There was a .noindex file inside my mailbox root folder. I did not place this file on purpose here, so I think some mechanism put it in there -- which stopped the index process on the whole maildir.
