### ISSUE TITLE
The search doesn't find a message with a decimal number in subject

### ISSUE THREAD

**Issue by bmansurov** [djcb/mu#1102]
## Expected or desired behavior

I have a message with the subject "ORDER SHIPPED: 3.5mm Stereo Audio M...". When I search for "ORDER" I see this message is found. I'd like to see the message when I search for '3.5' or '3.5mm', for example.

## Actual behavior
When I run `mu find '3.5'` I see `mu: no matches for search expression (4)`. This happens every time.

## Steps to reproduce
Send yourself an email with the title "ORDER SHIPPED: 3.5mm Stereo Audio M..." and search for '3.5' and see if the search returns any results.

## Versions of mu, mu4e/emacs, operating system etc.
mu (mail indexer/searcher) version 0.9.19

## Other details
I've rebuilt the database with the command `mu index --rebuild -v --maildir=~/Mail` but the problem persists. I've also removed the ~/.mu folder and re-indexed the mail, but no luck.

Please let me know if I can help debug the issue more or if I'm doing the search the wrong way.

**Comment by jschwab** [comment]
See e.g., https://groups.google.com/d/msg/mu-discuss/fIysxHJDzSc/GIgMMaBQY3gJ for more information (but not a solution).

**Comment by kubajar** [comment]
Any hints how to search for date - for example 6.6.2017 in message body? Many countries do not use 2017-06-06. Thank You for answer.

**Comment by bmansurov** [comment]
@kubajar that doesn't seem possible. :(

**Comment by kubajar** [comment]
It seems there exists special version of xapian with extended wildcard support (https://github.com/xapian/xapian/compare/master...ojwb:extended-wildcards). * matches any or more character, ? matches any or one character. It should help us a bit (mu find '3?5'), I will try to port patches to current xapian and send result.

**Comment by djcb** [comment]
The xapian engine makes that a bit hard to do.

However, mu (git) has a new custom query parser now, which allows for regular expressions;  ie., you can now search for:
```
  mu find 'subject:/3\\\.5/'
```
