### ISSUE TITLE
Variable documentation fix

### ISSUE THREAD

**Issue by theophilusx** [djcb/mu#1103]
Documentation inconsistency. 

This is really just a note to let maintainers know about an inconsistency I
found between the Manual and variable documentation. 

It appears the variable documentation for mu4e-headers-actions still refers to
the old LIST format of (NAME SHORTCUT FUNC) rather than the newer association
list format of (DESC . FUNC) described in the manual. 

The doc string for mu4e-view-actions is correct, though it does say the format
is a list (NAME FUNC) when it is really an association list and NAME is probably
best referred to as DESC or DESCRIPTION to be consistent with the manual. 

The doc string for mu4e-view-attachment-actions is correct, though it also
refers to NAME rather than DESCRIPTION as done in the manual.

**Comment by djcb** [comment]
Ok, fixed, thanks.
