### ISSUE TITLE
mu4e-message-at-point fails during mu4e-view-mode-hook functions

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#1104]
## Expected or desired behavior

I expect the following to work

    (defun my-set-view-directory ()
      "Switch the `default-directory' depending mail contents."
      (interactive)
      (when (mu4e-message-at-point t)
        (setq default-directory (my-get-code-dir-from-email))))

    (add-hook 'mu4e-view-mode-hook 'my-set-view-directory)

## Actual behaviour

Attaching the debugger to the function shows mu4e-message-at-point returns nil during the hook function - hence the fail.

## Versions of mu, mu4e/emacs, operating system etc.

Currently running:

"GNU Emacs 25.2.50.3 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2017-06-06"

with HEAD of mu

**Comment by stsquad** [comment]
I can see two reasons it would fail at the moment in mu4e-view:

    (with-current-buffer buf
      (unless (eq major-mode 'mu4e-view-mode)
        (mu4e-view-mode))
      (setq mu4e~view-msg msg)

One is we only run the hooks if the buffer is not already up, secondly we only set mu4e~view-msg after the hooks. Should I be using another hook for when message contents change in the persistent buffer?

**Comment by thierryvolpiatto** [comment]
PR #1141 fixes this issue.
You can try the code by advising mu4e-view like this:

```elisp
(defun tv/advice--mu4e-view (msg)
  "Display the message MSG in a new buffer, and keep in sync with HDRSBUF.
'In sync' here means that moving to the next/previous message in
the the message view affects HDRSBUF, as does marking etc.

As a side-effect, a message that is being viewed loses its 'unread'
marking if it still had that."
  (let* ((embedded ;; is it as an embedded msg (ie. message/rfc822 att)?
	   (when (gethash (mu4e-message-field msg :path)
		   mu4e~path-parent-docid-map) t))
	  (buf
	    (if embedded
	      (mu4e~view-embedded-winbuf)
	      (get-buffer-create mu4e~view-buffer-name)))
         mode-enabled)
    (with-current-buffer buf
      (unless (setq mode-enabled (eq major-mode 'mu4e-view-mode))
        (let (mu4e-view-mode-hook) (mu4e-view-mode)))
      (setq mu4e~view-msg msg)
      ;; When MSG is unread, mu4e~view-mark-as-read-maybe will trigger
      ;; another call to mu4e-view (via mu4e~headers-update-handler as
      ;; the reply handler to mu4e~proc-move)
      (let ((inhibit-read-only t))
        (when (or embedded (not (mu4e~view-mark-as-read-maybe msg)))
	  (erase-buffer)
	  (mu4e~delete-all-overlays)
	  (insert (mu4e-view-message-text msg))
	  (goto-char (point-min))
	  (mu4e~fontify-cited)
	  (mu4e~fontify-signature)
	  (mu4e~view-show-images-maybe msg)
          (mu4e~view-make-urls-clickable)
	  (when embedded (local-set-key "q" 'kill-buffer-and-window))
          (unless mode-enabled (run-mode-hooks 'mu4e-view-mode-hook)))))
    (switch-to-buffer buf)))
(advice-add 'mu4e-view :override 'tv/advice--mu4e-view)

```

**Comment by djcb** [comment]
Okay, with that PR this is fixed now.
