### ISSUE TITLE
mu4e - BBDB interface errors on start

### ISSUE THREAD

**Issue by emacswatcher** [djcb/mu#1106]
## Expected or desired behavior
Functionality as described in the manual

## Actual behavior
M-x mu4e RET

produces in *Messages*:

error in process filter: bbdb-mua: BBDB: MUA ‘mu4e-view-mode’ not supported
error in process filter: BBDB: MUA ‘mu4e-view-mode’ not supported

after which any attempt to view a message produces in *Messages*:

error in process filter: BBDB: MUA ‘mu4e-view-mode’ not supported

## Steps to reproduce

  (use-package mu4e
    :load-path "/usr/local/share/emacs/site-lisp/mu4e"
    :commands (mu4e mu4e-headers-search mu4e-compose-new mu4e~proc-add)
    :config
    (progn
      (require 'bbdb-loaddefs)
    
    (setq mu4e-use-fancy-chars t
          mu4e-update-interval 900
          mu4e-get-mail-command "offlineimap"
          mu4e-attachment-dir (ensure-directory "~/Downloads")
          mu4e-context-policy 'pick-first

          mu4e-view-show-addresses t
          bbdb-mail-user-agent (quote mu4e-user-agent)
          mu4e-view-mode-hook (quote (bbdb-mua-auto-update visual-line-mode))
          mu4e-compose-complete-addresses nil
          bbdb-mua-pop-up t
          bbdb-mua-pop-up-window-size 5)

    (let* ((my-mu4e-data-dir "~/.emacs.d/mu4e")
           (context-file (concat my-mu4e-data-dir "/contexts.el")))
      (ensure-directory my-mu4e-data-dir)
      (if (file-exists-p context-file)
          (progn
            (message "Loading mu4e context file %s" context-file)
            (load-file context-file))
        (message "mu4e context file %s not found" context-file)))
    ))

## Versions of mu, mu4e/emacs, operating system etc.
Fedora 25
GNU Emacs 26.0.50
mu4e-mu-version "0.9.19"

**Comment by djcb** [comment]
Unfortunately, this seems like a `bbdb` problem -- there's not much `mu4e` can do about this. Please ask the `bbdb` authors.
