### ISSUE TITLE
Colorize diff

### ISSUE THREAD

**Issue by seanfarley** [djcb/mu#1107]
## Expected or desired behavior

For messages that have [PATCH], it'd be nice to use `diff-mode` to color them.

## Actual behavior

No colorization is done.

## Steps to reproduce

Open any of the emails that have a patch, here is a random link to one: https://www.mercurial-scm.org/pipermail/mercurial-devel/2017-February/092978.html

**Comment by eklitzke** [comment]
In general you can customize these types of things using hooks. For example I have a `'mu4e-view-mode-hook` set up to reformat long lines in emails I receive. I don't think what you want is straightforward though, as `diff-mode` itself is a major mode. I would recommend adding a keybinding to extract the mssage body and open it in `diff-mode` in another buffer.

**Comment by djcb** [comment]
With the new (experimental) gnus-based viewer, you should be able to use:
   https://github.com/orgcandman/emacs-plugins/blob/master/gnus-article-treat-patch.el
Please let us know if it works!

**Comment by seanfarley** [comment]
Oh snap, that works! For other people looking to enable this, it took me a while to figure out I needed to set something like this:

```elisp
(setq ft/gnus-article-patch-conditions
      '( "^@@ -[0-9]+,[0-9]+ \\+[0-9]+,[0-9]+ @@" ))
```

I must say, thanks for making my life even better with mu4e! As a follow-up, I quite like the colors of mu4e's view (as opposed to gnus), is there a reason that you're implementing using gnus? I might take a stab at implementing this into mu4e natively, if that's an option.

All in all, I think this issue can be closed as I know you already have done so much :-D

**Comment by djcb** [comment]
Ah, the idea is that the mu4e "native" message-view-mode is based on gnu's article view, so we can diverge where we want, but gnus does a quite good job at all the message handling (better than the existing mu4e-view-mode).

 we can easily set some of the header colors to what's default for mu4e right now, haven't done that yet -- patches are welcome :-); basically, the various gnus faces should be set to the corresponding mu4e values.

**Comment by seanfarley** [comment]
Oh, I see. Well, if I find something good, I'll submit some patches :-) Thanks again!

**Comment by seanfarley** [comment]
😄 As promised months ago, here is my attempt at coloring patches:

https://github.com/seanfarley/mu4e-patch
