### ISSUE TITLE
Do not cite on compose

### ISSUE THREAD

**Issue by Ambrevar** [djcb/mu#1110]
I might be missing something obvious, but is it possible not to cite the message when replying?
I see I can define a `message-cite-function` but that's a rather convoluted hack...

**Comment by djcb** [comment]
Best way is probably to customize `mu4e-compose-cite-function`.

**Comment by Ambrevar** [comment]
That's more or less the same thing, and still a hack: the `mu4e~draft-cite-original` function inserts the citation in all cases, so that would mean using `mu4e-compose-cite-function` to undo the work done by it?

An user option would be nice.

**Comment by guibor** [comment]
I agree it would be nice. It's hard to define which package should handle such configurations (see https://github.com/jeremy-compostella/org-msg/issues/104#issue-872326539) but perhaps it should indeed be defined in mu4e.

It's very useful when replying for example to document comments, or other special types of "reply" addresses that embed the reply text in an application.
