### ISSUE TITLE
Colons as delimiters in Maildir filenames

### ISSUE THREAD

**Issue by psmith1303** [djcb/mu#1112]
## Expected or desired behavior

Other programmes that work with Maildirs often allow one to change the character that is used as a separator (the colon), say, to a exclamation mark. For example, Dovecot allows one to change the MAILDIR_INFO_SEP.

## Actual behavior

The Maildir standard uses colons ":" as a separator. This is all well and good until one interacts with Windows-based systems, when things (understandably) get a bit messy (e.g. files don't get backed on by a Snyology NAS)..

Looking through the code for mu/mu4e, the colon seems to be hardcoded into a number of strings (and I'm not sure I have found them all).

It would be nice to have a variable or other option to use an alternative character as the delimiter.

E.g., A send message looks like
```
1501044667.i38j2hmrvnpoko3a0sbnakcfhhmgpvgeubvmokg1.mailbox.petersmith.org:2,S
```
and cannot be easily stored on a service that interacts with Windows. It would be nice if the option allowed it to be
```
1501044667.i38j2hmrvnpoko3a0sbnakcfhhmgpvgeubvmokg1.mailbox.petersmith.org!2,S
```

## Steps to reproduce

Just send a message and it will be flagged with a colon.

## Versions of mu, mu4e/emacs, operating system etc.

Applies to mu-0.9.18 under FreeBSD version 11.0-RELEASE-p9 FreeBSD 11.0-RELEASE-p9 #0: Tue Apr 11 08:48:40 UTC 2017

(I don't see anything in the ports files that is changing what I think is the default behaviour).

**Comment by djcb** [comment]
`mu` actually check for the exclamation mark as well (as the semi-standard colon alternative), so indexing should work.

However, `mu4e` doesn't allow changing this, and this isn't being planned, sorry...

**Comment by psmith1303** [comment]
I've reviewed the code, as best I can, and there are only a couple of places where the code needs changing so that mu4e uses an exclamation mark instead of a colon.  I wonder if it is worthwhile me putting that into the codebase as some kind of option.

(That said, I've using the modified code and it seems to be okay).
