### ISSUE TITLE
Names with punctuation chars couldn't be searched for

### ISSUE THREAD

**Issue by event** [djcb/mu#1113]
1. Have a database with email from Michael O'Leary
2. run 'mu find from:o'leary' or 'mu find from:oleary'
## Expected behavior
see a message from Michael O'Leary
## Actual behavior
no messages found

# Potential cause
The problem seems to be due to escaping of search queries in **handle_esc_maybe**(mu-str.c) called from **mu_query_preprocess**->**mu_process_query_term**->**process_str**:
```c
	if (g_unichar_ispunct(uc) || isblank(kar)) {
		g_string_append_c (gstr, '_');
		return TRUE;
	}
```
and not escaping during indexing in **cleanup_maybe**  (mu-msg-file) called from **new_doc_from_message**->**mu_msg_contact_foreach**->**msg_contact_foreach_doc**->**mu_msg_get_from**->**get_str_field**->**mu_msg_file_get_str_field**
```c
	if (!g_utf8_validate(str, -1, NULL)) {
		if (*do_free)
			s = mu_str_asciify_in_place ((char*)str);
		else {
			*do_free = TRUE;
			s = mu_str_asciify_in_place(g_strdup (str));
		}
	} else
		s = (char*)str;

	mu_str_remove_ctrl_in_place (s);
```

**Comment by djcb** [comment]
This is all gone now :-) with the new query parser.
```
mu find "charle's"
2013-01-07T18:40:03 EET  Charle’s Babbage’s Brain
```
