### ISSUE TITLE
mu4e doesn't see the Trashed flag for messages in 'new'

### ISSUE THREAD

**Issue by ecocode** [djcb/mu#1114]
## Expected or desired behavior
mu4e doesn't show the T flag for trashed items in 'new' folder

## Actual behavior
mails located in 'new' and flagged with 'T' appear as normal messages in the list.  The 'T' flag doesn't appear. The message is not appearing in 'strikethrough' characters

## Steps to reproduce
Manually move a message file into a 'new' maildir.  Set the 'T' flag by adding it to the filename.
Reindex mu
In mu4e jump to the maildir.

## Versions of mu, mu4e/emacs, operating system etc.
mu/mu4e 0.9.18
emacs 26.0.50

## Any other detail
nil

**Comment by djcb** [comment]
Yes -- because (as per Maildir specs), message in `new` don't _have_ any flags. So this is the expected behavior.
