### ISSUE TITLE
No way to set custom Message-Id header

### ISSUE THREAD

**Issue by dsx** [djcb/mu#1116]
## Expected or desired behavior

Be able to define a function to generate Message-Id.

## Actual behavior

Message-Id is generated using default message-make-message-id

## Steps to reproduce

Compose message, send it and observe Message-Id header of the received message.

## Versions of mu, mu4e/emacs, operating system etc.
mu4e 0.9.18-1 (Debian)
emacs25 25.1+1-4 (Debian)
Debian 9 (Stretch)

**Comment by djcb** [comment]
Hmmm, I'd recommend advising `message-make-message-id` if you want to change this. It's out of mu4e's direct control.

**Comment by dsx** [comment]
@djcb I'm quite new to Emacs. How to do that?

**Comment by jschwab** [comment]
if you're new to emacs, a good place to start is would be to read the docs about advising functions.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html

**Comment by dsx** [comment]
Thank you!
