### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by mekeor** [djcb/mu#1117]
Could we please just release a new version in order to make the new features available for more people?

**Comment by fintelkai** [comment]
I would really appreciate that. I can't seem to compile the current HEAD version (homebrew; macOS; gmime.h issue that I don't have the time to troubleshoot) so I've made do with just copying the most recent *.el files (while using the stable release version of the rest of mu) but that seems like a rather fragile state.

**Comment by mekeor** [comment]
@fintelkai did you take a look at the [build instructions for the git repository](https://github.com/djcb/mu/blob/master/HACKING#L110)?

**Comment by djcb** [comment]
Here's an alpha-release, which corresponds to the (almost) latest git version: https://github.com/djcb/mu/releases/tag/1.0-alpha0. 

The non-alpha should be in a few weeks.
