### ISSUE TITLE
Abbrevs not working in mu4e:compose

### ISSUE THREAD

**Issue by Ambrevar** [djcb/mu#1119]
## Expected or desired behavior

Expand the abbrev when composing an e-mail.

## Actual behavior

Nothing happens.

## Steps to reproduce

Define an abbrev in text-mode. Make sure it expands in text mode and text-derived modes (like org-mode or message-mode).

It does not expand in mu4e-compose mode, which is based on message-mode, which itself is based on text-mode.

Global abbrevs work however.
If I try to define a mode-specific abbrev in mu4e:compose, I get the following error:

> No per-mode abbrev table

## Versions of mu, mu4e/emacs, operating system etc.

- mu: 0.9.18
- Emacs: 25.2
- OS: Gentoo

**Comment by djcb** [comment]
Ah... fixed in git.
