### ISSUE TITLE
Can't open attachments in Attached mails

### ISSUE THREAD

**Issue by ecocode** [djcb/mu#1121]
[MAIL.zip](https://github.com/djcb/mu/files/1274414/MAIL.zip)
## Expected or desired behavior

Opening attachments in attached mails should work

## Actual behavior

Opening attachments in attached mails fails with message 
error in process filter: mu4e-error-handler: Error 3: unknown error

## Steps to reproduce

Attached is an email you can put in your maildir to test.  It is a spam mail, but it does work correctly on other mail clients.
Open the attached eml email then try opening the eml in that email.  That action fails.

## Versions of mu, mu4e/emacs, operating system etc.

mu/mu4e 0.9.18
emacs 26.0.50 from git compiled on 2017-07-30

**Comment by djcb** [comment]
It's an old problem... see #454.
