### ISSUE TITLE
Searching mail based on existence of header

### ISSUE THREAD

**Issue by arunisaac** [djcb/mu#1123]
## Expected or desired behavior

My mail server runs spamassassin and adds the X-Spam_score header to mails it thinks are spam. Something like

```
X-Spam_score: 16.9
```

I would like to find these mails using `mu find`. If `mu find` can shortlist mail which have the `X-Spam_score` header, that would be useful.

Though not absolutely required for my use case, it would also be nice if there is some way to perform numeric comparisons in search queries. Something like

```
mu find X-Spam_score > 5.0
```

## Actual behavior

Right now, as far as I know, there is no way to test for the existence of a header. And, there is no way to perform numeric comparisons.

**Comment by djcb** [comment]
mu does not store arbitrary headers, so unfortunately, this is not possible.

**Comment by arunisaac** [comment]
Is it not feasible to make mu store arbitrary headers?
