### ISSUE TITLE
mu4e-view buffer ( and others ) should use `disaply-buffer` for opening windows

### ISSUE THREAD

**Issue by naclander** [djcb/mu#1124]
## Expected or desired behavior

Customization on window sizes ( such as using [Shackle](https://github.com/wasamasa/shackle) ) should work on mu4e windows.

## Actual behavior

mu4e uses `switch-to-buffer` which relies on lower level manipulation of windows and thus doesn't enable customizations. From the `switch-to-buffer` docstring:

>> WARNING: This is NOT the way to work on another buffer temporarily
within a Lisp program!  Use ‘set-buffer’ instead.  That avoids
messing with the window-buffer correspondences.

A discussion of this was started [here](https://github.com/wasamasa/shackle/issues/44)

As mentioned in the Shackle issue, [here](https://github.com/djcb/mu/blob/2811370d7efecfc86031e1d736c0c08a3bcd59a5/mu4e/mu4e-view.el#L319) is an example of mu4e uses `switch-to-buffer`.

Is it possible to switch mu4e to use the recommended window switching API?

**Comment by naclander** [comment]
To provide a little more background.  I wanted to limit how big the `mu4e-view` window could get using Shackle. As a temporary workaround, I noticed mu4e [provides a vairable](https://www.djcbsoftware.nl/code/mu/mu4e/Split-view.html) to change the number of visible lines in mu4e-headers, so that alleviates some pain. Although I think the original issue is still important.

**Comment by djcb** [comment]
`switch-to-buffer` is necessary for mu4e's window-management, there's no easy way around that. Hopefully the split-view variables can get you what you want.
