### ISSUE TITLE
mu4e doesn't show BCC in sent messages

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#1125]
## Expected or desired behavior

When viewing a message I sent with `To:`, maybe a `Cc:`, and a `Bcc:` recipient, I would expect or desire to see the `Bcc:` list.

## Actual behavior

No `Bcc:` list is shown, unless I press `.` (period, bound to `mu4e-view-raw-message`).

## Versions of mu, mu4e/emacs, operating system etc.

mu: 0.9.18

**Comment by djcb** [comment]
What's in your `mu4e-view-fields`? Perhaps you need to add `:bcc` there.

**Comment by djcb** [comment]
Okay, checked this and this seems to work just fine.
