### ISSUE TITLE
mu4e should have the option to view mu4e-view buffers without leaving mu4e-headers buffer

### ISSUE THREAD

**Issue by naclander** [djcb/mu#1126]
## Expected or desired behavior

I scroll through `mu4e-headers` while ( in a splti view ) `mu4e-view` updates to whichever message my point is currently over. However, when I select a message ( using `mu4-headers-view-message` ) the focus gets moved to the `mu4e-view` buffer. 

I would like an option that would keep the focus on the `mu4e-headers` buffer, even though the `mu4e-view` buffer has been updated.

## Actual behavior

`mu4e-view` automatically gets focus if a message is opened using `mu4e-headers-view-message`.

## Steps to reproduce

stated above. 

## Versions of mu, mu4e/emacs, operating system etc.

Current stable version of mu and latest commit from master

**Comment by djcb** [comment]
Would recommend you create a keyboard binding for `RET y`, which should do the trick.
