### ISSUE TITLE
error in process filter: mu4e-error-handler: Error 70: error moving

### ISSUE THREAD

**Issue by gspe** [djcb/mu#1127]
## Expected or desired behavior

I'm trying to use mu4e with Gmail account with the setup of [Magnus Therning](https://groups.google.com/forum/#!topic/mu-discuss/BpGtwVHMd2E) since Gmail just use "All Mail" folder for every email and just apply label to simulate folder, in this way I don't have duplicate messages.

I've setup mu4e like this:
```lisp
(setq mu4e-maildir "~/.Mail"
        mu4e-get-mail-command "offlineimap -o"
        mu4e-update-interval nil
        mu4e-compose-signature-auto-include nil
        mu4e-view-show-images t
        mu4e-view-show-addresses t)

  (setq mu4e-contexts
        `( ,(make-mu4e-context
             :name "user@account.com"
             :enter-func (lambda () (mu4e-message "Switch to the user@account.com context"))
             ;; no leave-func
             ;; we match based on the maildir of the message
             :match-func (lambda (msg)
                           (when msg
                             (string= (mu4e-message-field msg :maildir) "/user@account.com")))
             :vars '( ( user-mail-address       . "user@account.com" )
                      ( user-full-name          . "User" )
                      ( mu4e-compose-signature  . nil)
                      ( mu4e-sent-folder   . "/user@account.com/AllMail")
                      ( mu4e-drafts-folder . "/user@account.com/AllMail" )
                      ( mu4e-trash-folder  . "/user@account.com/Bin")
                      ( mu4e-refile-folder . "/user@account.com/AllMail")
                      ))))

  ;; set `mu4e-context-policy` and `mu4e-compose-policy` to tweak when mu4e should
  ;; guess or ask the correct context, e.g.

  ;; This hook correctly modifies the \Inbox and \Starred flags on email when they are marked.
  ;; Without it refiling (archiving) and flagging (starring) email won't properly result in
  ;; the corresponding gmail action.
  (add-hook 'mu4e-mark-execute-pre-hook
            (lambda (mark msg)
              (cond ((member mark '(refile trash)) (mu4e-action-retag-message msg "-\\Inbox"))
                    ((equal mark 'flag) (mu4e-action-retag-message msg "\\Starred"))
                    ((equal mark 'unflag) (mu4e-action-retag-message msg "-\\Starred")))))
  )
```
with this configuration I'm expecting that when I refile a message mu4e remove the Inbox tag from it leaving the message in the "All Mail" folder

## Actual behavior

When I apply the refile tag I get this error:

```
error in process filter: mu4e-error-handler: Error 70: error moving /home/gspe/.Mail/user@account.com/AllMail/cur/1505374643_1.2827.jura,U=4881,FMD5=e5b16880bf86ed7af066aa97fb0288d8:2,S to /home/gspe/.Mail/user@account.com/user@account.com/AllMail/cur/1505374643_1.2827.jura,U=4881,FMD5=e5b16880bf86ed7af066aa97fb0288d8:2,S
```
I get the same error when I'm trying to delete a message
```
error in process filter: Error 70: error moving /home/gspe/.Mail/user@account.com/AllMail/cur/1505374643_1.2827.jura,U=4881,FMD5=e5b16880bf86ed7af066aa97fb0288d8:2,S to /home/gspe/.Mail/user@account.com/user@account.com/Bin/cur/1505374643_1.2827.jura,U=4881,FMD5=e5b16880bf86ed7af066aa97fb0288d8:2,ST
```
in practice it add the maildir folder "user@account.com" two times in the path.
 
## Steps to reproduce

Just use the configuration above.

## Versions of mu, mu4e/emacs, operating system etc.
I' using spacemacs 0.200.9@25.2.1 (spacemacs) with mu4e - mu for emacs version 0.9.18 C

**Comment by franciscovg** [comment]
I have the same issue.  Probably related to https://groups.google.com/forum/#!msg/mu-discuss/rTMr0FCEPIg/CnfWtj9OBgAJ?

**Comment by gspe** [comment]
I've found what cause the problem,
when I started to experiment with mu and mu4e I had one account and I indexed it with:

`mu index -m ~/.Mail/accountfolder`

and this is the cause of problem with mu4e dispaliyng Maildir as folder and not account/folder
so if you rerun mu with:

`mu index --rebuild -m ~/.Mail`

mu4e correctly dispay Maildir as account/folder and I don't have the problem with refile any more.

So to avoid problems mu index have to be run in the root of the maildir and not in any of the subfolders
