### ISSUE TITLE
Add a `mu4e-query-filter-function` to pre-process internal queries

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#1129]
If would be nice to have a place to filter/process the query as received by `mu4e~proc-find`.
This is a follow-up to: https://groups.google.com/d/msg/mu-discuss/9Qeag4sYCZM/kYVDhj84BgAJ
and: https://melpa.org/#/mu4e-query-fragments

The idea is to allow a function to pre-process the internal query before it reaches xapian. In mu4e-query-framents I'm adding advice to `mu4e~proc-find`, but hopefully `mu4e~proc-find` could itself check for a `mu4e-query-filter-function` (or similar) to call and replace the query just in the beginning. It shouldn't be higher-level, as query-rewriting creates complex queries that are basically unwatchable and uneditable, resulting in a bad UI.

I'm tempted to release a second extension to mu4e, but I'd like the extension to play nice with query-fragments as well (that is, I want to be able to perform the same expansion when calling mu manually). Handling mu4e-query-fragments as a special case would be quite ugly.

I could submit a PR, if the idea (and setting name) is vetted.

**Comment by djcb** [comment]
I've added `mu4e-query-rewrite-function` now, which should give you what you want.

**Comment by wavexx** [comment]
Timejacking old PRs -- sorry ;)

I'm _finally_ trying to update mu4e-query-fragments from using advice to use the current incantation as ``mu4e-search-query-rewrite-function`` since it broke with the changes in 1.7. Talk about lazyness ;)

Using the new method works, however it shows the rewritten query on the modeline, which (in my case) becomes both unreadable and, most importantly, uneditable as the rewritten query is also set as the current search.

To be useful for this extension the expanded query would need to be hidden from the user.
Not sure if changing the hook now though would be a good idea. The current behavior makes sense too.

Suggestions?

**Comment by djcb** [comment]
Note: it's called `mu4e-query-rewrite-function` again (without the `-search-` since it was annoyingly long).

Remembering  the un-rewritten query for editing seems like a good idea; but have to think a bit about the mode-line part.

**Comment by wavexx** [comment]
> Note: it's called `mu4e-query-rewrite-function` again (without the `-search-` since it was annoyingly long).

There's still one instance of the long name left in mu4e/mu4e.el:143
