### ISSUE TITLE
mu_store_new_writable: xapian error 'Expected block 4 to be level 1, not 0' (11)

### ISSUE THREAD

**Issue by tiktaaliki** [djcb/mu#1130]
## Desired behavior
opening mu4e when using m-x mu4e

## Actual behavior
I recently switched from offlineimap to mbsync. everything worked fine after the switch and i was able to open my inbox. however, once I closed emacs i haven't been able to start mu4e again.

now M-x mu4e in emacs results in: "error in process sentinel: Database is locked by another process"
Running "mu index" in terminal returns the error mu_store_new_writable: xapian error 'Expected block 4 to be level 1, not 0' (11)

In trying to solve the issue I found this: https://www.djcbsoftware.nl/code/mu/mu4e/Retrieving-mail.html
I run this: 
   pkill -2 -u $UID mu # send SIGINT
   sleep 1
   mu index

and nothing happens--I assume this is because I need to replace $UID with the actual number, but 
But I can't find the UID of the process. Running "ps", or "ps -aux" doesn't return any process with either xapian or mu in it. 

I've rebooted several times and for some reason this doesn't reset anything. 

## Versions of mu, mu4e/emacs, operating system etc.
linux mint cinnamon 18.2 'sonya'
emacs 25.3
I am not sure how to check the version of mu and mu4e

## Any other detail

I would appreciate any insight. Thank you!

**Comment by edumerco** [comment]
It looks like the xapian access is being blocked. Please check if you don't
have a .lock file remaining somewhere...

--
eduardo mercovich

Donde se cruzan tus talentos
con las necesidades del mundo,
ahí está tu vocación.

**Comment by djcb** [comment]
Seems to be something went wrong inside the xapian database. I'd recommand `mu index --rebuild` from the command-line. Or even `rm -rf ~/.mu/xapian && mu index`.
