### ISSUE TITLE
"D" in headers view acting unexpectedly

### ISSUE THREAD

**Issue by rumsant** [djcb/mu#1131]
## Expected or desired behavior

My expectation is that when I mark a message "D" and carry out the operation, it will be permanently deleted without being sent to the trash.

## Actual behavior

When I mark a message "D" and carry out that operation, the message is moved to a specific maildir.

Possibly relevant:
The specific maildir these messages are moved to is called "Local_Archive". This is a maildir that is not pushed to my mail server (Kolab), nor does it pull anything from the mail server. It exists to store archived messages which are 2 years or older. The purpose is so that I can save these older messages locally (Dropbox) without having to purchase additional storage space via Kolab.

## Versions of mu, mu4e/emacs, operating system etc.
Mu: 0.9.19
Emacs: 25.2.1
OS: Linux Mint

## Any other detail
I can definitely work around this behavior with no problems.
I just wanted to understand it to make sure that I'm not in danger of screwing something else up, and that I'm not misunderstanding the expected behavior of "D".

**Comment by djcb** [comment]
Hmmm, `D` should remove messages completely; the behavior you describe is (by default) bound to `d`. When you press `D` (or `<delete>`), at the start of the message it should say `delete`.

What does `C-h k D` say?

**Comment by rumsant** [comment]
Totally forgot about this issue.
In the time since I posted it, I've reset my entire system, and now when I try to replicate the problem, I can't  - i.e. it appears to be working as expected.
Great program!
