### ISSUE TITLE
regex search

### ISSUE THREAD

**Issue by mbunkus** [djcb/mu#1132]
Often enough I'm frustrated that mu (through Xapian) can only handle trailing wildcards. Coming from mutt this feels like going back to a less powerful search engine, even though mu is much faster.

Situations in which I've really wished for regex syntax searching include:

* matching long folder names (we use a deeply nested set of public folders on our company's IMAP server, e.g. 'Öffentliche Ordner/Projekte/Kundenprojekte/2017/…`, and I'd like to match all folders from 2017)
* not only remembering part of a word that turns out to be the second half (e.g. when I attempted to find an order from "unixstickers" and all I could remember was "sticker" — there's currently no way to filter for "sticker" or "sticker*" and have it list those by "unixstickers", too)

I fully realize Xapian puts limits on what can be implemented in mu, but as far as I understand it notmuch does have regex searching for certain fields and it's using Xapian, too. So maybe there is a way?

Thanks for considering it.

**Comment by djcb** [comment]
Hmm, do you have some more details how notmuch would be doing that?

**Comment by mbunkus** [comment]
Unfortunately I don't; I've never looked at notmuch's source. I've only read its [search terms manual](https://notmuchmail.org/manpages/notmuch-search-terms-7/) which states several times that regex searches are possible if the "Xapian field processor API" is available. Just search for `regex` in the linked page.

A very quick look at the [notmuch source repo](https://github.com/notmuch/notmuch/) turns up [`regexp-fields.cc`](https://github.com/notmuch/notmuch/blob/master/lib/regexp-fields.cc).

**Comment by djcb** [comment]
I was working on a new query-parser anyway, and I've added regexp queries, see git, and check the new `mu-query` man-page.

**Comment by mbunkus** [comment]
That's great news, thank you so much! Looking forward to it.
