### ISSUE TITLE
 Feature request: When MSGID is given to mu4e-headers-search, display the message first then populate the headers-view in the background

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#1133]
Currently we first briefly see headers-view being updated and then the message-view opens.  (I'm using the single-window configuration.) It would be better if the message would be displayed immediately, while the headers-view is being updated in the background.  Context: `mu4e-headers-search` is used to display messages selected in helm-mu.  The intermediate headers-view looks a bit like a graphical glitch.

**Comment by djcb** [comment]
I can seen it being somewhat useful, but it would require a few changes. So have to decline this. Sorry!
