### ISSUE TITLE
New option: reply to all without prompting

### ISSUE THREAD

**Issue by Ambrevar** [djcb/mu#1135]
When replying an e-mail with several recipients, mu4e bugs me to know whether I want to reply to all or the sender only.

mu4e should have an option that provides the user default (`sender` or `all`) which allows switching to the compose buffer directly.

**Comment by edumerco** [comment]
Hello. 

> When replying an e-mail with several recipients, mu4e bugs me to 
> know whether I want to reply to all or the sender only.
>
> mu4e should have an option that provides the user default 
> (sender or all) which allows switching to the compose buffer 
> directly.

Since "r" is for refile already... What about "R" to reply and 
"C-R" to reply to all?


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by djcb** [comment]
This is a dup of #542.
