### ISSUE TITLE
mu4e tries to flag too many messages

### ISSUE THREAD

**Issue by jgoerzen** [djcb/mu#1137]
## Expected or desired behavior

A given message exists in multiple folders on my system.  It is identical in each, and therefore will have the same Message-Id in each.

When I browse a copy of that message in folder A, mu4e attempts to set the Seen flag on it in folder B as well.  I can tell because my user has only read, not write, permissions to folder B, so it generates an error.

## Actual behavior

error in process filter: mu4e-error-handler: Error 70: error moving

## Steps to reproduce

Have a message exist in multiple places in the mu index.  mu4e appears to try to set a flag on all of them.

## Versions of mu, mu4e/emacs, operating system etc.

ii  emacs25            25.1+1-4+deb9u amd64          GNU Emacs editor (with GTK+ GUI support)
ii  mu4e               0.9.18-1       all            e-mail client for Emacs based on mu (maild

**Comment by jgoerzen** [comment]
The offending behavior is in mu4e~view-mark-as-read-maybe.  Changing the first parameter to mu4e~proc-move from msgid to docid fixes this issue.

Based on the comments, it looks like the current behavior was desired.  That's a bit odd in my book, but I can see it would give a more Google-like experience.  I think this should, at minimum, be configurable.

**Comment by djcb** [comment]
Thanks... it's indeed as planned; not planning a option for this.
