### ISSUE TITLE
mu 1.0alpha0 sets all message sizes to 4294965345 in index

### ISSUE THREAD

**Issue by mbunkus** [djcb/mu#1142]
I'm currently trying out mu 1.0alpha0. I've thrown away the old index and created a new one with mu 1.0alpha0.

## Expected or desired behavior

I have mu4e configured to show the message size in headers view. I expect the size to be shown and to be correct.

## Actual behavior

With mu 1.0alpha0 and mu4e from the same release a size is shown, but it is `4.295M` for all messages regardless of actual size.

## How to reproduce

Build an index with mu 1.0alpha0. Start Emacs with mu4e 1.0alpha0. Configure Emacs to include the message size column in headers view. Open a mu4e headers view.

**Comment by mbunkus** [comment]
Addendum: this is what I have in customization for headers:

```lisp
 '(mu4e-headers-fields
   (quote
    ((:human-date . 12)
     (:flags . 6)
     (:maildir . 50)
     (:from . 30)
     (:size . 7)
     (:subject))))
```

**Comment by mbunkus** [comment]
More information: the bug occurs during indexing. The result is that all message sizes end up being `4294965345` in the index:

```shell
[0 mosu@sweet-chili ~] ~/opt/mu-1.0alpha0/usr/bin/mu find --muhome=$HOME/mu-test/index --format=xml cenedra | grep -F '<size>' | sort | uniq -c
   2256                 <size>4294965345</size>
[0 mosu@sweet-chili ~]
```

**Comment by djcb** [comment]
It's a display issue - it wasn't properly updated. Fixed now.
