### ISSUE TITLE
Attachments with spaces cannot be handled

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#1144]
Likely some more breakage due to commit 457a0a17a2954959cee87bad285679d1fc85d7b4 and subsequent ones.

Trying to save attachments with spaces in mu4e results in files which are truncated *at* the space.
Likewise opening them fails because the full file name doesn't really exist.

**Comment by djcb** [comment]
This should work better with the latest.

**Comment by wavexx** [comment]
It does. Seems to be fixed. Could this be related to #1145 as well?
After a quick glance, it now seems to work correctly as well.

**Comment by djcb** [comment]
Guess so... both are quoting issues. Closing them for now at least. Thanks!

**Comment by wavexx** [comment]
On Tue, Oct 31 2017, Dirk-Jan C. Binnema wrote:
> Guess so... both are quoting issues. Closing them for now at least. Thanks!

Re-checking today, I can confirm they're both gone.
