### ISSUE TITLE
Mu broken on i386

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1147]
## Expected or desired behavior

- Make mu queries work as before
- Correct date on emails

## Actual behavior

All my bookmarks are not working anymore See https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/mu4e-config.el#L163

All mails are flagged to year 2038

Same configuration, same emails are flagged correctly on my other laptop (64b) and bookmarks are working as expected as well.

## Versions of mu, mu4e/emacs, operating system etc.

* mu4e - mu for emacs version 1.0-alpha0 C
Emacs-25.3

**Comment by djcb** [comment]
Seems an issue with the `time_t` being assumed to be 64-bit, while on some 32-bit platforms, it's only 32-bit. I've pushed a fix, which now makes us pass the unit tests at least. Can you try? It'll require a `--rebuild`.

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Seems an issue with the time_t being assumed to be 64-bit, while on
> some 32-bit platforms, it's only 32-bit. I've pushed a fix, which now
> makes us pass the unit tests at least. Can you try? It'll require a
> --rebuild.

Thanks, I will try on monday, I have no access to 32b computer until
then.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Seems an issue with the time_t being assumed to be 64-bit, while on
> some 32-bit platforms, it's only 32-bit. I've pushed a fix, which now
> makes us pass the unit tests at least. Can you try? It'll require a
> --rebuild.

Works fine now, all my email are flagged to 2017.

Thanks.

--
Thierry

**Comment by djcb** [comment]
Great, thanks.
