### ISSUE TITLE
Searching for words including apostrophes

### ISSUE THREAD

**Issue by fallisson** [djcb/mu#1150]
## Expected or desired behavior

I would like to be able to search for words including an apostrophe, by inserting either the whole word, or the part before or after the apostrophe.

## Actual behavior

Using mu 0.9.18, in an e-mail containing the word "d'études", it is not possible to find this e-mail using either "etudes", "études", "d'études" or "d'etudes" as a search word.

The same for the French word "aujourd'hui". Here, I can find them with "aujourd" or with "hui", but not with "aujourd'hui".

If this may help, it does not work when the word is in full-text or in from/to/cc/bcc, but it works well when the word is in the subject line.

## Steps to reproduce

Get an e-mail with the word "d'études" in the text. Search (with both mu find and mu4e search): etudes, études, d'études, d'études.

On the mu mailing list, someone reported that with the latest git version, only some of these four searches are problematic, while the other not.

## Versions of mu, mu4e/emacs, operating system etc.

Mu 0.9.18
Emacs 25.2.2
Debian Buster
Debian

## Any other detail

Thanks even if nothing can be done!

**Comment by djcb** [comment]
Can you attach a test message? Thanks.

**Comment by thierryvolpiatto** [comment]
François Allisson <notifications@github.com> writes:

> The same for the French word "aujourd'hui". Here, I can find them with
> "aujourd" or with "hui", but not with "aujourd'hui".

From the backend, "mu find aujourd\'hui" is working fine, note that
apostrophe is escaped, so I guess the problem comes from mu4e where
"aujourd'hui" is passed directly to the backend without using
`shell-quote-argument`.

    (shell-quote-argument "aujourd'hui") => "aujourd\\'hui"

--
Thierry

**Comment by fallisson** [comment]
Le 07 novembre 2017, Dirk-Jan C. Binnema <notifications@github.com> a écrit:
> Can you attach a test message? Thanks.

Here it is. Many thanks for investigating this.
François

**Comment by djcb** [comment]
Hmmm, I didn't find an attachment. Or is github hiding it somewhere?

Anyway, with current mu4e/mu, you can find `aujourd'hui`, and you cannot find it by searching for either `aujourd` or `hui`.
