### ISSUE TITLE
"Reply to all" replies to my email as well

### ISSUE THREAD

**Issue by sachdevaprash** [djcb/mu#1153]
## Expected or desired behavior
"Reply to all" should reply to everyone but my email id.

## Actual behavior
"Reply to all" replies to everyone AND me.

## Steps to reproduce
Reply to your own email sent to someone else.

## Versions of mu, mu4e/emacs, operating system etc.
version 1.0-alpha0 (Following git updates)

## Any other detail
Did not used to happen earlier. This seems to be a recent bug.

**Comment by djcb** [comment]
Can't reproduce this. Can you include a raw message where this happens + the contents of your `mu4e-user-mail-address-list`? Thanks.

**Comment by sachdevaprash** [comment]
You were right. The mu4e-user-mail-address-list was wrong. But is user-mail-address ignored for this purpose? I did not have this issue till a while back.

Shouldn't user-mail-address be assumed to be a part of mu4e-user-mail-address-list?

**Comment by djcb** [comment]
Indeed,  by default, `mu4e-user-mail-address-list` contains just `user-mail-address`.
