### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [djcb/mu#1154]
Based on https://github.com/djcb/mu/releases and https://github.com/djcb/mu/releases/latest I cannot tell if 0.9.18, 1.0-alpha0, 1.0-alpha1 is the current stable version.

Which version should be in Homebrew's stable spec? Thanks!

**Comment by mekeor** [comment]
1.0-alpha0 and 1.0-alpha1 are alpha-versions. As [this wikipedia article](https://en.wikipedia.org/wiki/Software_release_life_cycle#Alpha) describes, "[t]he alpha phase of the release life cycle is the first phase to begin software testing". So, the alpha version is not the current stable version.

The current stable version is 0.9.18.

**Comment by ilovezfs** [comment]
@mekeor and yet 1.0-alpha0 is marked as the latest release, not as a pre-release.

**Comment by mekeor** [comment]
Oh, right! Now I see what you mean! I guess it's a mistake.

**Comment by djcb** [comment]
Wouldn't take whatever github tag too serious; the alpha releases will lead up to the final 1.0 release; not much is expected to change, so you can use them (and report problems if found!).

**Comment by ilovezfs** [comment]
@djcb if 1.0-alpha0 is actually prerelease for 1.0, and 0.9.18 is the actual current release, can you please mark the tag 1.0-alpha0 as a prerelease tag? It's very confusing for our livecheck system in Homebrew to have alpha releases marked as a latest release not as a prerelease.
