### ISSUE TITLE
"error in process filter: No matches for this search query." (mu4e)

### ISSUE THREAD

**Issue by ursl** [djcb/mu#1155]
## Expected or desired behavior

mu4e should display 'all' email messages that I receive. It does not. 

## Actual behavior

If the (plain ASCII) email message contains a string of the form 

Message-ID: <"/generators/3721"@hypernews.cern.ch>

mu4e does not display such an email message. This string  is in the headers, before the main mail message starts. Rather I find in the *Messages* buffer: 

error in process filter: user-error: No matches for this search query.
error in process filter: No matches for this search query.

The problematic aspect are the two double quotes; if I remove both of them, I have no problems. 

## Steps to reproduce
Remove (or not) the double quotes in the email below (may require C-C C-U in the main view to see the change): 

Date: Mon, 20 Nov 2017 15:24:48 +0100
To: nowhere@universe.com
From: somebody@gmail.com
Subject: Re: Different cross section for the same sample in Mcm
Message-ID: <"/generators/3721/1"@hypernews.cern.ch>

bla

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 0.9.18

mu4e - mu for emacs version 0.9.18 C

Emacs 25.2 (from https://emacsformacosx.com)

MacOS 10.13.1

## Any other detail

I circumvent this problem with 

alias patchID    'perl -pi -e "s/Message-ID: \<(.*hypernews.cern.ch),\>/Message-ID: \<bla\>/g " '

(which is not the minimal tweak, but ... )

**Comment by djcb** [comment]
Hmmm, some quoting issue. Should work now (git), can you give it a shot?

**Comment by ursl** [comment]
Thanks, it fixes the problem indeed. (I tested against 1.0-alpha3.)

Apologies for the late notice (I had to find time to compile and learn how to satisfy the specific dependencies).
