### ISSUE TITLE
Search date: is not working with a simple date, must use a range

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1156]
## Expected or desired behavior

Search query "date:20171117" should return messages from this date.

## Actual behavior

Search query "date:20171117" is not working, I have to use "date:20171117..20171117" to find messages at this date.

For bug-reports, if applicable, include error messages, emacs stack
traces etc. Try to be as specific as possible - when do you see this
happening? Does it happen always?  Sometimes? How often?

## Steps to reproduce
From mu4e main, hit "s" and enter "date:20171117", if you have mails at this date mu should return them. 

## Versions of mu, mu4e/emacs, operating system etc.

Using here emacs-25.3 and last mu from git.

**Comment by thierryvolpiatto** [comment]
As a consequence bookmarking emails is no more working because `mu4e-view-bookmark-make-record` is recording a simple date, not a range, so I have to use this no make it working:

```diff
diff --git a/mu4e/mu4e-contrib.el b/mu4e/mu4e-contrib.el
index 95132773..dae66d62 100644
--- a/mu4e/mu4e-contrib.el
+++ b/mu4e/mu4e-contrib.el
@@ -72,7 +72,7 @@ emacs bookmark, not to be confused with `mu4e-bookmarks'."
   (let* ((msg     (mu4e-message-at-point))
          (maildir (plist-get msg :maildir))
          (date    (format-time-string "%Y%m%d" (plist-get msg :date)))
-         (query   (format "maildir:%s date:%s" maildir date))
+         (query   (format "maildir:%s date:%s..%s" maildir date date))
          (docid   (plist-get msg :docid))
          (mode    (symbol-name major-mode))
          (subject (or (plist-get msg :subject) "No subject")))
```

**Comment by djcb** [comment]
Ah yeah, that's a missing feature... I've implemented it now.
