### ISSUE TITLE
Update a single account 

### ISSUE THREAD

**Issue by vxcamiloxv** [djcb/mu#1158]
## Expected or desired behavior

Update a single account instead wait for update all accounts, similar to [j] (Jump to maildir) but for update a specific account.

## Actual behavior

Require update all account and need waits to finish all for see a single one.

## Steps to reproduce

Is a feature request.

## Versions of mu, mu4e/emacs, operating system etc.

- emacs 25
- mu4e 0.9.18
- Parabola (archlinux) GNU/Linux

## Any other detail

Could be a cool feature

**Comment by andersjohansson** [comment]
Wouldn’t this depend very much on what command you use for fetching email? It’s very easy to define your own updated commands though.

One of my email accounts is on an Exchange server, which I have to access through davmail, and syncing all my folders takes almost half a minute. To avoid this I use a custom call to mbsync to just fetch new messages in the inboxes. Than I can run a quick fetch (in headers view) with `C-S-u` and a full fetch with `C-u C-S-u`. 
````emacs-lisp
(setq mu4e-get-mail-command " mbsync -qqa")
(defvar aj/mu4e-get-mail-command-quick "mbsync --new -qq uu-inbox gmail-inbox")

(defun aj/mu4e-update-mail-and-index (full?)
  (interactive "P")
  (if full?
      (mu4e-update-mail-and-index t)
    (let ((mu4e-get-mail-command aj/mu4e-get-mail-command-quick))
      (mu4e-update-mail-and-index t))))

(bind-key "C-S-u" #'aj/mu4e-update-mail-and-index mu4e-headers-mode-map)
````
Maybe it is easiest for the user to define this kind of custom behaviour themselves? Or what kind of interface could mu4e concievably present? The individual fetching commands would still have to be defined by the user, or a kind of complex guessing algorithm (or for example parsing the user’s `.mbsyncrc` file) be developed.

**Comment by edumerco** [comment]
Dear Anders.

> Wouldn’t this depend very much on what command you use for 
> fetching email? It’s very easy to define your own updated 
> commands though. [...]

While this is totally true, I think that it would be great if it 
can be done easier for more people.

Just to clarify and add my 2 cents, what if mu4e allows the user 
to define mulitple (from 1 to N) mail-check commands, and shows 
them as options when called?

An imaginary (but quite realistic) example...
Let's assume we have 3 accounts.
1. personal
2. professional
3. old gmail used for google.

The user wants to check:
a. very frequently the inboxes of 1 and 2.
b. regularly the rest of 1 and 2. 
c. Every few hours, everything.

We could create 3 check mail commands, one for a, one for b and 
one for c.
Each could have it's regularity: a every 5 minutes, b every hour, 
c every 4 hours. Also, a letter/number to select it so when the 
User press "u" or "U" mu4e shows a list (like the one when you 
choose export from org-mode, a buffer with a letter for each 
option) that exposes the defined options.

In this example...
"u1" would check only the inboxes of accounts personal and 
professional.
"u2" would check all folders of accounts personal and 
professional.
"u3" would check all folders of all accounts.

In this way we give a mechanism to simplify a common case that 
-yes, we can always do it with lisk, this is the emacsverse- many 
people is doing already.

WDYT? :)

Best...



-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by djcb** [comment]
I wouldn't want to add all that extra complexity to `mu4e`, since it already allows users to relatively easily do that themselves, ie. something like:
```
(defun account1-update (run-in-background)
  "Update account1."
  (interactive "P")
  (let ((mu4e-get-mail-command "offlineimap -c account1.conf"))
    (mu4e-update-mail-and-index run-in-background)))
;; and similar for other accounts
```
and and then bind some key to that.

Alternatively, you could write a little shell script that executes the update commands for each account, based on the last time we updated that account.

**Comment by edumerco** [comment]
> I wouldn't want to add all that extra complexity to mu4e, since 
> it
> already allows users to relatively easily do that themselves, 
> ie.
> something like:

> (defun account1-update (run-in-background)
>   "Update account1."
>   (interactive "P")
>   (let ((mu4e-get-mail-command "offlineimap -c account1.conf"))
>     (mu4e-update-mail-and-index run-in-background)))
> ;; and similar for other accounts

Roger that Dirk. :)
Thanks for the code, it works beautifully.

Best...


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by vxcamiloxv** [comment]
For me the @andersjohansson 's solution works fine, should be documented?

**Comment by djcb** [comment]
Sure, if someone wants to make a PR to add it to the FAQ, that'd be welcome.
