### ISSUE TITLE
No automatic check for incoming mails

### ISSUE THREAD

**Issue by amirteymuri** [djcb/mu#1160]
## Expected or desired behavior

regular check for incoming mails every 30 minutes as specified in 
`(setq mu4e-update-interval 1800)`

## Actual behavior

No automatic update every 30 minutes in the *mu4e-headers* page, i should do `q` to go back to mu4e-main page, then from there `j` `i`

**Comment by notmgsk** [comment]
What version of mu/mu4e are you using?

**Comment by amirteymuri** [comment]
`apt-cach policy mu4e`:

mu4e:
  Installed: 0.9.18-1
  Candidate: 0.9.18-1
  Version table:
 *** 0.9.18-1 500
        500 http://httpredir.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by notmgsk** [comment]
I remember this being an issue for myself also. However, I can't reproduce this behaviour with the latest versions of mu.

Try installing one of the 1.0 alphas from source.

**Comment by amirteymuri** [comment]
Where can i get the source and how can i install it?

**Comment by notmgsk** [comment]
You will do something like

  `git clone https://github.com/djcb/mu.git`

Then read the HACKING file. It has instructions on how to build mu and
mu4e.

If you have more questions, I recommend you post on the mu-discuss
mailing list: https://groups.google.com/forum/#!forum/mu-discuss
