### ISSUE TITLE
error in process filter: Symbol’s value as variable is void: msgid

### ISSUE THREAD

**Issue by jschwab** [djcb/mu#1165]
After upgrading to 0d9d8d26d0828364927fce45c2b70466f784d72b from 9ad4a76eac8f7db66eb4fc99fb0aee70e0e0c983 I now see errors like the following in the `*Messages*` buffer each time after I send a message.

```
Saving file /home/jschwab/Mail/personal/[Gmail].Drafts/cur/1512808428.452cc45ab658c257.monolith:2,DS...
Wrote /home/jschwab/Mail/personal/[Gmail].Drafts/cur/1512808428.452cc45ab658c257.monolith:2,DS
[mu4e] Saved (16 lines)
Sending...
Mark set [2 times]
Sending via mail...
Sending...done
error in process filter: mu4e~compose-set-parent-flag: Symbol’s value as variable is void: msgid
error in process filter: Symbol’s value as variable is void: msgid
Quit
```

**Comment by jschwab** [comment]
This may be related to #1162.

**Comment by djcb** [comment]
Can you give it a shot with the latest? Thanks!

**Comment by jschwab** [comment]
Upgraded to e1c6fa4b and the messages are gone.  Thanks!

**Comment by thierryvolpiatto** [comment]
Josiah Schwab <notifications@github.com> writes:

> Upgraded to e1c6fa4 and the messages are gone. Thanks!

Same here, no error now, thanks.


-- 
Thierry
