### ISSUE TITLE
Don't get the new mails to see on the mu4e-headers page

### ISSUE THREAD

**Issue by amirteymuri** [djcb/mu#1167]
## Expected or desired behavior

To see new mails incoming on the mu4e-headers

## Actual behavior

Despite the retrieving goes on my mu4e-headers page doesn't get updated, so i can't see any new mails. I am using offlineimap in my init.el file: `(setq mu4e-get-mail-command "offlineimap")`

For bug-reports, if applicable, include error messages, emacs stack
traces etc. Try to be as specific as possible - when do you see this
happening? Does it happen always?  Sometimes? How often?

## Steps to reproduce

For bug-reports, please describe in as much details as possible how
one can reproduce the problem*.

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 1.0-alpha2

## Any other detail

It seems to me like an endless loop, even though i have quited from mu4e with `q`, the process `mu4e-update` still runs in the background (i get asked if i want to turn it off when i want to quit emacs), yet i don't get any new emails! If i click on `*mu4e-update*` in the `*Process List*` buffer i get this:

OfflineIMAP 6.6.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync Gmail:
 *** Processing account Gmail
 Establishing connection to imap.gmail.com:993
 XOAUTH2 authentication failed: AUTHENTICATE command error: BAD ['Client aborted AUTHENTICATE command. c184mb107396453wmd']. Data: KMDE2 AUTHENTICATE XOAUTH2

Enter password for account 'Remote':

**Comment by notmgsk** [comment]
Looks like your offlineimap is not configured correctly. If you run offlineimap directly (through a terminal) does it run correctly?

**Comment by amirteymuri** [comment]
Yes.

**Comment by djcb** [comment]
What happens when you do do `M-: (shell-command mu4e-get-mail-command) RET`?
