### ISSUE TITLE
error in process filter: Error 2: not a readable dir: ’%s’

### ISSUE THREAD

**Issue by gsmlg** [djcb/mu#1171]
## Expected or desired behavior
When running command  	* [u]pdate index & cache* (`mu4e-update-index`)

## Actual behavior

```
error in process filter: mu4e-error-handler: Error 2: not a readable dir: ’%s’
error in process filter: Error 2: not a readable dir: ’%s’
```

## Steps to reproduce

run function `mu4e-update-index`

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 0.9.18

## Any other detail

system: macos 10.13.2
mu is installed by homebrew
mu4e-maildir is set to **"/Users/joe/Library/Application Support/Mail"**

run command in shell can update mail index success
```
mu index -m "/Users/joe/Library/Application Support/Mail"
```

**Comment by gsmlg** [comment]
I'd  found out this `mu4e-maildir` can't include whitespace

**Comment by djcb** [comment]
I think this is fixed with the current (git) mu4e. Can you give it a try?

**Comment by gsmlg** [comment]
I've tried current mu4e, it still got errors.
I've move mu4e-maildir to ~/Maildir and this solved.
Thanks to your support.
