### ISSUE TITLE
Allow reverse date sorting in threads, so that newest emails are at top.

### ISSUE THREAD

**Issue by bradyt** [djcb/mu#1174]
## Expected or desired behavior

Would like to see threads spread upwards, that is, newest emails at top.

## Actual behavior

Newest threads are at top, but within threads, newest emails are at bottom.

## Steps to reproduce

I am using the default sorting.

## Versions of mu, mu4e/emacs, operating system etc.

```
mu (mail indexer/searcher) version 0.9.18
# mu4e.el
;; Version: 0.0
GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G1036)) of 2018-01-02
```

## Any other detail

As a possibly clarifying example, this is possible in `mutt`, with 

```
set sort=reverse-threads
set sort_aux=last-date-received
```

**Comment by djcb** [comment]
Great news! This is the way mu4e 1.3.x now works.

**Comment by bradyt** [comment]
I don't think this is implemented. Perhaps I should illustrate.

Say you have an email A, then another one AB as a reply to A. Then you get another email C, then an email CD in reply to C.

Then if you have threading enabled, and have oldest first, you get the following.

```
- A
  - AB
- C
  - CD
```

This is nice, because they are still roughly in order of viewing. But we are now more accustomed to having newest email at top of list. So if we select newest emails first, most email clients will do this:

```
- C
  - CD
- A
  - AB
```

But now they're a bit out of order, and you actually have to go down a bit to get to the most recent email, `CD`.

What `mutt` makes available, is another sort within the thread, so you get this:

```
  - CD
- C
  - AB
- A
```

Now you have your newest emails first. And you can still easily keep track of threads.

I don't believe this feature is available, I've just tried today's commits, with hash `58b462d`.

**Comment by bradyt** [comment]
The first screenshot here is what I am trying to describe: https://unix.stackexchange.com/questions/274281/sort-emails-by-time-in-mutt.

![VxS91](https://user-images.githubusercontent.com/6107051/75849264-4a879380-5d99-11ea-8c75-403793ce5367.png)

Another example can be found at http://fosshelp.blogspot.com/2014/05/how-to-mutt-configure-gmail.html.

**Comment by bradyt** [comment]
@djcb, are you leaving this closed intentionally?

**Comment by djcb** [comment]
Ah, yes, that's a bit different compared to what we have. Within threads, we always sort in ascending order (it changed quite recently).

There are no plans to implement another sort-order-within-threads for the time being - sorry! So no need to reopen.

**Comment by parisni** [comment]
too bad. This feature really makes thread more readable - in case of complex multi branch mails. 
Any hope to do this with elisp ?

**Comment by djcb** [comment]
There is always hope; it's software after all; it could be done in elisp, but that'd require quite a bit of rework. Anyway, if/when we do some big rearch of the headers-view, I'll keep this in mind.
