### ISSUE TITLE
Allow grouping in mu4e-headers-mode

### ISSUE THREAD

**Issue by bradyt** [djcb/mu#1177]
I would like to have sections in my headers view, so like sequence of sections like 

```
date:today..now
date:2d/00:00..1d/00:00
date:3d/00:00..2d/00:00
...
date:2w/00:00..1w/00:00
date:3w/00:00..2w/00:00
```

With rows in between denoting, `today`, `yesterday`, ..., `last week`, `2 weeks ago`, ...

I hate to admit where I've seen this, but it's in Outlook, an email client that allows grouping.

An abstraction might allow users to collect other searches and sequence them with clear delineators and titles in a single view, for example, grouping by folder.

**Comment by djcb** [comment]
This is not on the table in the foreseeable future, sorry!
