### ISSUE TITLE
Add support for numeric arguments in mark functions (mu4e-headers-mark-for-*)

### ISSUE THREAD

**Issue by Ambrevar** [djcb/mu#1178]
## Expected or desired behavior

Press, say, `M-7 d` to flag 7 e-mails for trash.

## Actual behavior

There is support for marking all e-mails within the active region though.

## Versions of mu, mu4e/emacs, operating system etc.

- mu 0.9.18
- Emacs 25.3
- Arch Linux

**Comment by djcb** [comment]
It's a two-step thing. First you select, `C-SPC M-7 C-n` and then do your action. You can of course add keyboard macros if there are specific ones you use a lot.

There are no plans to add it directly to all the commands, which would be quite a massive project!
