### ISSUE TITLE
Asterisk lost wildcard semantics in search expression

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#1180]
When searching the index, it used to be possible to enter an asterisk as a wildcard.  Helm-mu relies on this behavior to give a better user experience.  After a recent update the asterisk apparently lost it's special semantics is now matched literally.  Is this a bug or desired behavior?  If not a bug, what can we use instead as a wildcard?

**Comment by djcb** [comment]
Can you give an example of a search string where it doesn't work?

Note that the `*`  must be the last character of a term, that's true for both the new and old query-parser; though the old query parser would do _something_ if you put the `*` elsewhere while the new one treats it as just another character.

**Comment by djcb** [comment]
hmm... it should work and does so here.

Can you try from the command-line and compare e.g `mu find 'subject:hell*'` vs `mu find 'subject:hell`? You can also try with the option `--format=xquery`, which shows how the query was parsed.

**Comment by tmalsburg** [comment]
Oh, sorry. In all my test cases the `*` ended up being separated from the terms by a space (search query is generated).  So I just have to make sure that I only append the `*` when the last character in the search expression is not a whitespace.  Thanks for clarifying.
