### ISSUE TITLE
Support for subexpression distribution over fields

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#1185]
The original Xapian query parser supports distribution over fields if a field is immediately followed by a subexpression:

  field:(subexpr)

For example:

  field:(a OR b)

is equivalent to:

  field:a OR field:b

and

  field:("some phrase" OR (something else)

to:

  field:"some phrase" OR (field:something field:else)

I actually don't remember if this ever worked in mu4e, but it doesn't with the new query parser.
Distribution makes certain query patterns easier to make. This is especially true when mu4e is used with mu4e-query-fragments, as simple lists of terms can then be reused on different fields.

A primary example that prompted for this is lists of addresses in the recent request in the ML about matching yourself in a query. Surely (I thought) distribution and composition would make this easy:

````
(add-to-list 'mu4e-query-fragments-list
	     `("%me" . ,(mapconcat 'identity mu4e-user-mail-address-list " OR ")))
````

then search for ````from:%me````. The key point here, is that the term list sub-expression can be chained to arbitrary fields (such as ````to:%me````), making "%me" actually useful as a term in itself.

**Comment by djcb** [comment]
For the specific case (`%me`), see the mailing list snippet. An alternative would be to use `field:/<regexp>/`. 

For extending the parser to allow applying a field to a subexpression... that's something for post-1.0.

**Comment by wavexx** [comment]
> For the specific case (%me), see the mailing list snippet

Maybe I missed this, but I see no recent message from you except the mu 1.0 release?

As for the rest, I didn't want to put pressure. This is definitely a "nice to have" feature, but not critical.
I was pondering how much work would be to implement distribution in mu4e-query-fragments itself, but the idea of retokenizing the subexpression turned me off ;)

**Comment by djcb** [comment]
Sorry, I wasn't giving much context and seems my message didn't make it to the ML before... but now:
    https://groups.google.com/d/msg/mu-discuss/oX66KFJk3lM/yFe_RJtHAgAJ

**Comment by djcb** [comment]
This is not currently planned, so closing this ancient ticket...
