### ISSUE TITLE
Build fail on Cygwin

### ISSUE THREAD

**Issue by mkrusemark** [djcb/mu#1186]
Making all in parser
make[3]: Verzeichnis „/home/mkrusem/tmp/mu-1.0/lib/parser“ wird betreten
  CXX      parser.lo
  CXX      tokenizer.lo
  CXX      utils.lo
utils.cc: In Funktion »std::string Mux::format(const char*, ...)«:
utils.cc:187:44: Fehler: »vasprintf« wurde in diesem Gültigkeitsbereich nicht definiert
   const auto res = vasprintf (&s, frm, args);
                                            ^
utils.cc: In Funktion »std::string Mux::date_to_time_t_string(const string&, bool)«:
utils.cc:313:52: Fehler: »strptime« wurde in diesem Gültigkeitsbereich nicht definiert
  if (!strptime (date.c_str(), "%Y%m%d%H%M%S", &tbuf) &&
                                                    ^
make[3]: *** [Makefile:763: utils.lo] Fehler 1
make[3]: Verzeichnis „/home/mkrusem/tmp/mu-1.0/lib/parser“ wird verlassen
make[2]: *** [Makefile:647: all-recursive] Fehler 1
make[2]: Verzeichnis „/home/mkrusem/tmp/mu-1.0/lib“ wird verlassen
make[1]: *** [Makefile:523: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/mkrusem/tmp/mu-1.0“ wird verlassen
make: *** [Makefile:433: all] Fehler 2

Version 0.9.16 compiles fine.

**Comment by djcb** [comment]
Can you give it a try with the current `git`? That has some changes that should help with this.

**Comment by mkrusemark** [comment]
Build still fails.

Am 11.02.2018 11:03 schrieb Dirk-Jan C. Binnema: 

> Can you give it a try with the current git? That has some changes that should help with this. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/djcb/mu/issues/1186#issuecomment-364739106
[2]

**Comment by poulpoulsen** [comment]
hello,
i just start to compile with current git and newest cygwin.
But fails with same error.
utils.cc: In Funktion »std::string Mux::date_to_time_t_string(const string&, bool)«:
utils.cc:352:52: Fehler: »strptime« wurde in diesem Gültigkeitsbereich nicht definiert
  if (!strptime (date.c_str(), "%Y%m%d%H%M%S", &tbuf) &&
                                                    ^
Regards
Poul

**Comment by poulpoulsen** [comment]
hello,
i just did a git pull, but repo is actual.
Does anyone know a solution for this error?
Regards
Poul

**Comment by djcb** [comment]
I've done another update -- maybe that helps you. But I can't really test it, unfortunately.

**Comment by poulpoulsen** [comment]
Hello,
very good!!
It works. mu compiles fine now, starts and no error occur.

Regards
Poul

**Comment by poulpoulsen** [comment]
Hmmh, how could i cloes this issue?
There is no button "comment and close"

**Comment by djcb** [comment]
oh, great! I'll close it.
