### ISSUE TITLE
mu4e-headers buffer shows no emails and *Messages* is spammed

### ISSUE THREAD

**Issue by petergil** [djcb/mu#1188]
## Expected or desired behavior

mu4e-headers buffer should show result of query

## Actual behavior

mu4e-headers buffer shows only "Searching..." and the \*Messages\* buffer is spammed with

    error in process filter: mu4e~proc-filter: Symbol’s value as variable is void: mu4e~headers-buffer
    error in process filter: Symbol’s value as variable is void: mu4e~headers-buffer

This happens for any query.

## Steps to reproduce

start mu4e
open a search/bookmark/jump to maildir/...

## Versions of mu, mu4e/emacs, operating system etc.

emacs version is 25.3.1
mu version is 1.0

on gentoo

## Any other detail

redefining

        (defun mu4e-get-headers-buffer ()
            (setq  mu4e~headers-buffer (get-buffer mu4e~headers-buffer-name)))

seems to work as a workaround.

**Comment by djcb** [comment]
Hmm, the the name `mu4e~headers-buffer` doesn't seem to be present in mu4e, so it's unclear where the error comes from. Perhaps there's some older version lying around, or some third-party plugin/code?

**Comment by petergil** [comment]
Hmmm, this is very weird. I managed to reproduce the problem running under a newly created user with a fresh home directory and only loading mu4e in the emacsrc.

Running a grep in /usr/share/emacs I couldn't find any reference to `mu4e~headers-buffer`, so I have no idea where it came from.

Then I recompiled both emacs and mu just for the hell of it, and now the error disappeared (both for the newly created user and my actual user).

So, problem solved I guess.

**Comment by pmatos** [comment]
Interesting - I am getting this after upgrading from 0.9.18 to 1.3.5 and can't find where the problem could be coming from.

Sorry for the noise on old bug but I thought it would be an interesting data point.

**Comment by progo** [comment]
Likewise reporting in. Updated mu via gentoo portage and mail listings aren't working well, with the message `error in process filter: Symbol’s value as variable is void: mu4e~headers-buffer`

Updated from 0.9.18 to 1.3.6.

Workaround works.

**Comment by djcb** [comment]
Neither of those variables is used in current mu4e (check with `grep`), so if you get those errors means you have some older version lying around (or precompiled .elc) or perhaps some external package that uses them. And did you restart emacs?

**Comment by progo** [comment]
I just had the package recompiled, to no avail. Sure enough I restarted emacs at every opportunity. The ELC files (compiled by the emerge time) were all current, no old timestamps anywhere. 

To be sure, I re-emerged emacs and mu in that order again, it seems to have **solved the problem**. It was already mentioned in these comments so sorry about this spam!

**Comment by awerdx520** [comment]
Do you install mu4e-maildirs-extention package? possible it!
