### ISSUE TITLE
Support XDG basedir spec

### ISSUE THREAD

**Issue by alex-shpilkin** [djcb/mu#1191]
The [XDG base directory specification](https://developer.gnome.org/basedir-spec/) has many advantages to it; the most important one for me personally is that I can configure my backups without going mad because data and cache are cleanly separated. The latter is [what’s wrong](https://ploum.net/207-modify-your-application-to-use-xdg-folders/) with `MUHOME`, whether you like this particular spec or not.

I have only given the source code a cursory look, but I see that the C parts at least use Glib and are coded to Glib conventions. Glib has explicit support for the XDG directories—look for `g_get_user_*_dir` in [miscellaneous utility functions](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html).

**Comment by djcb** [comment]
Not planning that for the current mu... but I'll keep it in mind for the future. Thanks.
