### ISSUE TITLE
mu4e: maildir queries don't filter by maildir

### ISSUE THREAD

**Issue by tdavis** [djcb/mu#1194]
## Expected or desired behavior

Searching with `maildir:/foo/INBOX` only shows messages from foo's inbox.

## Actual behavior

Messages are shown from every foo mailbox. In my particular case, it shows a view of duplicate (threaded) messages because every message is present in both "INBOX" and "archive".

## Versions of mu, mu4e/emacs, operating system etc.

mu 1.0/1.1, Emacs 25.3.1, Arch Linux

## Any other detail

This behavior is not present in pre-1.0 versions of mu4e (I downgraded, rebuilt the index, and used mu4e 0.9.18). It is not present when using `mu find`; only one copy of each message is output.

P.S. mu/mu4e is the only thing that makes email tolerable. Thanks a million!

**Comment by jschwab** [comment]
The default for mu4e-headers-include-related changed in 1.0.  It sounds like this could be related.

You can check if this setting is the cause of your issue by toggling this option with W and then customize to your desired value.

**Comment by tdavis** [comment]
Thanks for the info, I'll go ahead and close this!
