### ISSUE TITLE
mu-find thinks February has 31 days (--format=links)

### ISSUE THREAD

**Issue by schoettl** [djcb/mu#1197]
## Expected or desired behavior

```
mu find --clearlinks --format=links --linksdir=/tmp/test date:2018-02
```

mu should find all messages from February 2018.

## Actual behavior

```
mu: invalid upper date '20180231235959'
```

I get this error only when using `--format=links`.

## Versions of mu, mu4e/emacs, operating system etc.

- Arch Linux
- mu (mail indexer/searcher) version 1.0

**Comment by djcb** [comment]
Hmm, the `20180231235959` is a remnant from when we stored dates/times in that format, and we could use that as an easy upper-limit (and `strptime` is fine what that).

However, now we use `time_t` values, and `g_date_time_new_local` raises the error; easiest fix is to massage things a bit.

**Comment by schoettl** [comment]
Nice. Thank you!
