### ISSUE TITLE
Error running mu-guile programs: db version: 0.99, but we need 9.9; database rebuild is required

### ISSUE THREAD

**Issue by sje30** [djcb/mu#1199]
## Expected or desired behavior

mu-guile programs should run.

## Actual behavior

```
/alt/applic/user-maint/sje30/mu/guile/examples/msg-graphs --what=per-year happy
Backtrace:
In ice-9/boot-9.scm:
 157: 5 [catch #t #<catch-closure a87c20> ...]
In unknown file:
   ?: 4 [apply-smob/1 #<catch-closure a87c20>]
In ice-9/boot-9.scm:
  63: 3 [call-with-prompt prompt0 ...]
In ice-9/eval.scm:
 432: 2 [eval # #]
In /alt/applic/user-maint/sje30/mu/guile/examples/msg-graphs:
 117: 1 [main #]
In unknown file:
   ?: 0 [mu:initialize #f]

ERROR: In procedure mu:initialize:
ERROR: Throw to key `MuError' with args `("mu_guile_init_instance" "db version: 0.99, but we need 9.9; database rebuild is require
```

## Steps to reproduce

Running any scm program that comes with mu triggers the error.

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 26.0.91
Ubuntu 16.04
Mu 1.0

## Any other detail

I tried recompiling mu using  https://github.com/djcb/mu/issues/469 but still the same error.  Mu itself and (mu4e) work fine.

**Comment by bravosierrasierra** [comment]
in my PATH i found old and new mu version. Calling old version give me same error. Remove old version.

**Comment by djcb** [comment]
Indeed, that's likely the problem. Can you try, @sje30?
