### ISSUE TITLE
Read /var/mail/username

### ISSUE THREAD

**Issue by phenix-factory** [djcb/mu#1200]
Hello,

I m trying to read (with mu4e) the mails "system" located in the /var/mail/my_username file. But I don't find any documentation on this. Is it possible ?

Thank you !

**Comment by sje30** [comment]
No, I don't think so.  mu expects your mail to be stored in a Maildir formatted folder:

https://en.wikipedia.org/wiki/Maildir

whereas it sounds like you have a regular mbox formatted file.

**Comment by djcb** [comment]
You can let your mail deliver in a maildir (using e.g. procmail; details depend a bit on your set up), or you can do it only once, with something like https://www.akadia.com/services/converting_mbox_mdir.html

Good luck!
