### ISSUE TITLE
Cannot reply to messages (problem with mu4e~view-msg)

### ISSUE THREAD

**Issue by tofgarion** [djcb/mu#1201]
## Expected or desired behavior

Select an existing message and reply to it.

## Actual behavior

When replying to a message, I can compose my reply but cannot send it. There is "No message at point" message even if the corresponding message appaears in the mu4e-view buffer. 

## Steps to reproduce

View a message and reply to it.

## Versions of mu, mu4e/emacs, operating system etc.

I am currently using the last git version of mu and the last version of emacs available in the emacs-26 branch of emacs official git repository.

## Any other detail

The error seems to be due to the `mu4e~view-msg` variable. Removing the fact that this variable is buffer local in mu4e-vars.el solves the problem.

**Comment by djcb** [comment]
Is this still happening?

**Comment by tofgarion** [comment]
Sorry, I have not investigated the bug any further. I will update my emacs-26 branch and my mu version and keep you informed.

**Comment by tofgarion** [comment]
Hi,

Problem solved with commit 9bf1670a of mu and commit 94e84a92fe of branch emacs-26 of emacs. I think we can close the issue!

Best,

Christophe
