### ISSUE TITLE
mu4e does not show correct count for folders with spaces

### ISSUE THREAD

**Issue by rmanne** [djcb/mu#1203]
## Expected or desired behavior

In main-mode, folders should have the correct count regardless of name.

## Actual behavior

If the folder has a space in it, count is always "0/0". This happens 100% of the time, for 100% of the folders that have spaces in them. Parent folder has the right count, but not the folder with the space, nor any children.

## Steps to reproduce

Make a folder in an email account that has a space in it (eg: "Deleted Items"). Sync it with offlineimap. Open mu4e and notice `Deleted Items (0/0)`.

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 1.0
GNU Emacs 25.3.1
macOS 10.12.6

**Comment by rmanne** [comment]
Adding nametrans in offlineimap fixes the problem although it's not an ideal situation (eg: `nametrans = lambda f: re.sub(' ', '', f)`)

**Comment by djcb** [comment]
That's not part of mu4e though -- I suppose it's https://github.com/agpchil/mu4e-maildirs-extension? So I'd recommend filing your issue there.
