### ISSUE TITLE
Sending mail on windows gives odd errors

### ISSUE THREAD

**Issue by ihdavids** [djcb/mu#1205]
## Expected or desired behavior
Sending email to work without errors.

## Actual behavior

When composing a new email under windows saving the buffer or attempting to send (which will save) will generate errors. This happens all the time for me using head.

The errors in question list the filename and that the file is not readable. Sadly I do not have an example of the error message anymore. I tracked the problem down to the generated buffer name. The name includes a colon and a comma which windows is taking exception to when attempting to save the file.

## Steps to reproduce

Build mu using cygwin on windows.
Use offlineimap and pull from any gmail account.

Setup smpt and start composing an email.
NOTE the errors when you attempt to send.

## Versions of mu, mu4e/emacs, operating system etc.
HEAD using spacemacs 26.0.90 emacs 25.3 build for windows.

## Any other detail

Removing the colon and comma will fix the issue. I am currently just providing my own version of the buffer name generation method:

; I removed the :2,DS that was being appended to the filename
; since that is invalid under windows and was causing all sorts of grief
(defun mu4e~draft-message-filename-construct (&optional flagstr)
  "Construct a randomized name for a message file with flags FLAGSTR.
It looks something like
  <time>-<random>.<hostname>:2,
You can append flags."
  (let* ((sysname (if (fboundp 'system-name)
		    (system-name)
		    (with-no-warnings system-name)))
	  (sysname (if (string= sysname "") "localhost" sysname))
	  (hostname (downcase
		    (save-match-data
		      (substring sysname
				 (string-match "^[^.]+" sysname)
				 (match-end 0))))))
    (format "%s.%04x%04x%04x%04x.%s"   <<<< NOTE THIS IS DIFFERENT
      (format-time-string "%s" (current-time))
      (random 65535) (random 65535) (random 65535) (random 65535)
      hostname (or flagstr ""))))

**Comment by djcb** [comment]
Yeah, Windows doesn't like the `:` in file-names that the Maildir-protocol specifies. I guess it's a holdover from the times of drive-letters. There's some support for using `!` instead, perhaps it would be good to make that the default on Windows.

**Comment by secomi** [comment]
I had kind of the same problem. 
1. Using cygwin + mbsync (isync)
2. in the isync-isync, src/main.c file replace the "char FieldDelimiter" with ':'  for WIN32, Cygwin etc
    This is the only place I changed. 
   When checking Mu4e sources I could see the field-delimiter was hard coded in multiple places as the the file path is generated with the `:' all the time when "moving" messages into the maildir (cur,tmp, etc). 

3. Then I have no particular issue compiling the mu/mu4e (still as of today)

When not using cygwin the maildir files cannot be easily read on windows 7 ntfs, but so far I didn't have any particular issue.

hope this helps﻿

**Comment by nathan-albin** [comment]
I also ran into this issue, but fixed it in a slightly different way.  I'm running offlineimap under cygwin and noticed that the `:` in my mail directory is replaced by another character (`0xf03a`).  It turns out, that's [cygwin's fix](https://cygwin.com/cygwin-ug-net/using-specialnames.html#pathnames-specialchars) for bad characters in filenames.  Replacing the `:` by `0xf03a` in `mu4e~draft-message-filename-construct` seems to have fixed the issue.  No more complaints from mu4e or offlineimap.

**Comment by djcb** [comment]
Unfortunately, we cannot really support windows, since don't have the necessary expertise in the team. So closing this one -- sorry!

**Comment by damon-kwok** [comment]
I think this issue needs to be marked as "help want". Let someone with expertise do it, open source is for that, isn't it?
