### ISSUE TITLE
test-mu-maildir does not pass reliably

### ISSUE THREAD

**Issue by eklitzke** [djcb/mu#1206]
I am trying to make an RPM package for mu (that's more up to date than the one in contrib) and I've come across a curious problem. My RPM runs "make check", and when I build locally it works fine. However, when I build it in a mock chroot it often fails in `test-mu-maildir`, specifically in test `mu-maildir-get-new-path-new`. I am using the `mu-1.0.tar.xz` release tarball for these builds.

The relevant part of the `make check` output looks like this:

```
TEST: test-mu-maildir... (pid=7369)
  /mu-maildir/mu-maildir-mkdir-01:                                     OK
  /mu-maildir/mu-maildir-mkdir-02:                                     OK
  /mu-maildir/mu-maildir-mkdir-03:                                     OK
  /mu-maildir/mu-maildir-mkdir-04:                                     OK
  /mu-maildir/mu-maildir-mkdir-05:                                     OK
BUILDSTDERR:   /mu-maildir/mu-maildir-walk-01:                                      mkdir: cannot create directory '/tmp/mu-test-1000/test-cd396aa7': File exists
OK
BUILDSTDERR:   /mu-maildir/mu-maildir-walk:                                         mkdir: cannot create directory '/tmp/mu-test-1000/test-ea678989': File exists
OK
BUILDSTDERR:   /mu-maildir/mu-maildir-walk-with-noupdate:                           mkdir: cannot create directory '/tmp/mu-test-1000/test-ea5a1866': File exists
OK
BUILDSTDERR:   /mu-maildir/mu-maildir-get-new-path-new:                             **
BUILDSTDERR: ERROR:test-mu-maildir.c:440:assert_matches_regexp: assertion failed: (0)
FAIL
GTester: last random seed: R02S109b9e3d0a6c39c0124b8c5ec7c02c35
BUILDSTDERR: /bin/sh: line 5:  7365 Terminated              gtester --verbose test-mu-util test-mu-str test-mu-maildir test-mu-msg-fields test-mu-msg test-mu-store test-mu-flags test-mu-container
BUILDSTDERR: make[2]: *** [Makefile:957: test] Error 143
make[2]: Leaving directory '/builddir/build/BUILD/mu-1.0/lib/tests'
make[1]: Leaving directory '/builddir/build/BUILD/mu-1.0/lib'
```

It seems to fail more often than not, but sometimes it passes.

Log from a build where the test did not fail: https://monad.io/mu-test-ok.log.gz
Log from a build where the test did fail: https://monad.io/mu-test-fail.log.gz

The "file exists" warnings appear to be harmless because I also get those errors even when the test passes. For now I am just forcing the RPM to proceed building even when this fails but it's a bit worrisome.

If you're interested you can find the spec file I'm working on here: https://github.com/eklitzke/copr-mu

And the RPMs I've built here: https://copr.fedorainfracloud.org/coprs/eklitzke/mu/ . This link also has build logs, but they're cleaned up up after a certain amount of time which is why I've copied them to my monad.io domain.

**Comment by djcb** [comment]
Not sure is you're still working on this, but is this still reproducible?

**Comment by djcb** [comment]
Stale.
