### ISSUE TITLE
mu4e incompatible with gnus message-insert-formatted-citation-line

### ISSUE THREAD

**Issue by TengenJulian** [djcb/mu#1213]
## Expected or desired behavior
As citation I use the following:

```
(setq message-citation-line-format "On %e, %B %Y %R, %N wrote:\n"
         message-citation-line-function 'message-insert-formatted-citation-line)
```

When you get a mail from Bob at 23-03-2018 08:11:14, and your local timezone is +0100, then when you reply you expect:

On 23, March 2018 08:11:14, Bob wrote:

## Actual behavior

Instead you get:

On 23, March 2018 07:11:14, Bob wrote:

## Steps to reproduce
Use the following with local timezone +0100.
```
(setq message-citation-line-format "On %e, %B %Y %R, %N wrote:\n"
         message-citation-line-function 'message-insert-formatted-citation-line)
```
And reply to some mail.

## Versions of mu, mu4e/emacs, operating system etc.
Os: Arch linux
emacs version: 25.3.1
mu: Arch pakage mu, version 1.0-1, build date Mon 05 Feb 2018 10:15:22 AM CET

## Any other detail
As far as I understand, mu represents the date of the mail as some integer representation, encoded using GMT (the timezone of sender is not stored?).

In the function mu4e~draft-cite-original in mu4e-draft.el, the date header is inserted with format string
"%Y-%m-%dT%T%z" using the local time zone. This uses the iso8601 format, which is a format that parse-format-string does not understand. 

This results in the weird situation that message-insert-formatted-citation-line is not able to infer what the timezone is in the date header, but is able to extract the time as gnus-date-get-time does support iso8601, which again results in time relative to GMT. Since it could not infer the timezone, it defaults to GMT, when it should be using the local time zone instead.

So in my case this means that it is off by an hour, because I use timezone +0100. A possible solution is
to insert date header with "%Y-%m-%d %T %z" as format string instead. Not sure if this breaks anything. Ideally, the time zone of the sender is also stored, and that time zone is used to format the date header.

**Comment by jpggithub** [comment]
I'm in the same situation (GMT+1h).

I tried the modifications written by TengenJulian but it does not work for me.

I modified 
      (let ((mu4e-view-date-format "%Y-%m-%dT%T%z"))
in the mu4e-draft.el by
       (let ((mu4e-view-date-format "%FT%T%z"))
I have evaluate the new form of the function mu4e~draft-cite-original.

In my personal configuration, I have:
    (setq message-citation-line-format "On %a %d %b %Y %R %Z%z , %f wrote:\n")

If i answered to a message, it is written "GMT+0000" instead of "CET+1000" and the indicated hour is false (for example 19:20 instead of 20:20, the real hour of the initial message).

So the workaround seems not to work, at least for me.

I hope that my message is clear enough! ;-)
Anyway, thanks for your attention.

mu4 version: 1.0.6
emacs: 25.2.2

**Comment by matthew-piziak** [comment]
i used to be able to use this to get properly collapsed email threads in Gmail:

```
(setq message-citation-line-format "On %a, %b %d, %Y at %H:%M %p %f wrote:")
```

The docs for `message-citation-line-format` say this:

```
%f   The full From, e.g. "John Doe <john.doe@example.invalid>".
```

But this no longer works. Instead I just get `John Doe`. If I try to do it manually with `<%n>`, I get `John Doe <John Doe>`, in contradiction of the documentation.

This means that I can no longer use `mu4e` to send emails.

**Comment by symbiont-matthew-piziak** [comment]
Okay, if I do this:
```
(setq message-citation-line-format "On %a, %b %d, %Y at %l:%M%p %f wrote:")
(setq message-citation-line-function 'message-insert-formatted-citation-line)
```
...and if I remove the extra space, and if I add the email address after the name, then it usually works. I might add a pre-hook for that. But that's hacky, so anyone have idea advice on how to simplify it?

**Comment by djcb** [comment]
Seems to work fine now (1.11.23); closing this.

Note: mu4e 1.11.23 has a new composer that is much closer to gnus' one, so various message- settings have better odds to work in mu4e as well.
