### ISSUE TITLE
[FEATURE request] add a face for duplicate

### ISSUE THREAD

**Issue by stardiviner** [djcb/mu#1218]
There is an option `mu4e-headers-duplicate-prefix`. I hope mu4e can add a face for this duplicated email. So used can use customize face to make it clear.

**Comment by stardiviner** [comment]
Gentle ping ...

**Comment by djcb** [comment]
Currently, it's a bit hard to _combine_ face aspects, so it's unclear if an unread duplicate message should get the unread or duplicate face. Perhaps in future that will changes.

But, if you want to put some extra emphasis on duplicate messages, I recommend customizing `mu4e-headers-thread-duplicate-prefix`; with new enough emacs you could even put some colorful Unicode thing there. Or "Ⓓ".

Closing this for now... Sorry!

**Comment by stardiviner** [comment]
Thanks for tips of `mu4e-headers-thread-duplicate-prefix`.
