### ISSUE TITLE
mu4e-headers-fields :thread-subject error on some emails

### ISSUE THREAD

**Issue by stardiviner** [djcb/mu#1219]
Here is a screenshot shows the wrong thread subjects:

![image](https://user-images.githubusercontent.com/378699/38172542-8ab967a4-35e0-11e8-90f8-6acf2a7990df.png)

And here is the email headliens:
![image](https://user-images.githubusercontent.com/378699/38172563-fd409360-35e0-11e8-9b7c-6cd6ed526e45.png)

Here is the config snippet cause this issue:
```elisp
(setq mu4e-headers-fields
      '((:flags .  6)
        ;; (:human-date  . 18)
        ;; (:from  . 18)
	(:mailing-list  .   10)
        (:thread-subject . 30)
        (:subject . nil)
        )
      )
```
The `:thread-subject` is wrong on those emails in screenshots.
You can see in upper two screenshots, the two selected threads, the `:thread-subject` title is not displayed, and `:subject` title is displayed correctly.

**Comment by djcb** [comment]
I suspect this is just a cosmetical issue, do you still see this with latest mu4e, where the rendering is a bit different?

**Comment by djcb** [comment]
thread-subject did get some updates, think this should work now.
