### ISSUE TITLE
Incorrect name decoding

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1222]
The header of the message contains `cc: =?utf-8?Q?=22St=C3=A9phanie?= B" <S.B@umons.ac.be>` which should be decoded to `Stéphanie B` but is displayed by _mu_ as `=?utf-8?Q?=22St=C3=A9phanie?=`.  [Message attached](https://github.com/djcb/mu/files/1875024/msg.txt).

**Comment by djcb** [comment]
Fixed with the new gnus-based message view.
