### ISSUE TITLE
Manual with code syntax highlighting

### ISSUE THREAD

**Issue by averter** [djcb/mu#1223]
As a new user of mu4e I think it would be very helpful to have a manual which has coloured code syntax highlight. Would this require a whole rewrite of the [manual](http://www.djcbsoftware.nl/code/mu/mu4e/index.html) (not familiar with texinfo) into something such as org-mode?
In any case I leave here my suggestion for future reference.

**Comment by bradyt** [comment]
Hello @averter, as a quick fix, you can do `M-x emacs-lisp-mode` for syntax highlighting, and `M-x Info-mode` to go back to navigating. Traversing command history with `M-x M-p` may make this convenient enough with little effort. Or you could bind keys

Maybe a strategy like `info-colors` could be used to add syntax highlighting in the Info pages.

I wonder if a conversion to LaTeX can be done with a tool at https://www.gnu.org/software/texinfo/. Then, perhaps using pandoc one could convert to org-mode. Then probably some cleaning up would need to be done. Looks like org-mode even has the option to export to info pages.

**Comment by djcb** [comment]
The existing TeXInfo manual has the advantage of being nicely integrated with emacs, but the html output looks a bit... archaic.

Indeed, perhaps using org-mode => TeXInfo (and org-mode => html) could work. Are there any projects that have done such a conversion?

**Comment by jschwab** [comment]
Org-mode itself has recently transitioned to maintaining its manual in org and exporting to texi.

**Comment by secomi** [comment]
If the reference is on the online HTML manual, maybe it could be generated using highlightjs and a custom css. 

the lisp code could be recognized with something like:

`<link class="codestyle" rel="stylesheet" href="styles/github.css">

<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script src="highlight.pack.js"></script>
<link rel="stylesheet" href="styles/github.css">
<script>
        $(document).ready(function() {
  $('div pre.lisp,div pre.example').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});
</script>
`

![mu4e-example](https://user-images.githubusercontent.com/29351844/42694647-656bb118-86b3-11e8-8202-0db154451fa1.PNG)

The css in the example is from https://bitbucket.org/sirgazil/texinfo-css/, and maybe it could be used/tune and added from the Makefile.am with AM_MAKEINFOHTMLFLAGS = --css-include=...
But maybe there is a deployment process on the website which would not make this change work.

**Comment by djcb** [comment]
Done. We're using the special css now that gives _some_ highlighting, and seems to be the best possible without doing big changes (such as moving away from from `texinfo`).
