### ISSUE TITLE
Support for gmime 3.x

### ISSUE THREAD

**Issue by jfkw** [djcb/mu#1224]
## Expected or desired behavior

autotools configure step detects gmime >= 3.0 and mu4e can use it. 

I am presuming a mostly backward compatible API is available, or that mu4e's use of gmime could support gmime 3.x API.

## Actual behavior

Installing mu4e from git using el-get as of b4cc67d:

```
...
checking for glib-2.0 >= 2.32 gobject-2.0 gio-2.0... yes
checking for gmime-2.6 >= 2.6.7... no
configure: error: Package requirements (gmime-2.6 >= 2.6.7) were not met:

No package 'gmime-2.6' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```

## Steps to reproduce

My system (Gentoo ~amd64) has only gmime-3.2.0 installed, no gmime installed from the 2.6 slot (2.6.23 is available). mu4e is the only program I have that requires gmime-2.x.

Using el-get recipe update mu4e from git upstream (this repo)

## Versions of mu, mu4e/emacs, operating system etc.

mu42e git b4cc67d, GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit) of 2018-04-07

**Comment by exsilium** [comment]
Trying to compile `mu` on Termux, I'm encountering the same issue. Package manager provides gmime 3.2.0 which is not detected by the autoconf

**Comment by djcb** [comment]
We've moved to gmime 3.x now

**Comment by Chris00** [comment]
The configure script does not seem to detect it automatically — or do I miss something?
