### ISSUE TITLE
Wrong charset when signing and encrypting mail

### ISSUE THREAD

**Issue by RiadVargas** [djcb/mu#1225]
## Expected or desired behavior
Setting right charset (the same as `prefer-coding-system`, `set-default-coding-systems`, so on) after encrypting mail.

## Actual behavior
Everytime I send a signed and encrypted mail the Contenty-Type is: `text/plain; charset=us-ascii`. Brazilian portuguese have a lot of accents and this behavior makes my mails unreadable.

## Steps to reproduce
Compose a new mail;
Write content;
Sign; (or just encrypt)
Encrypt;
Send (both direct and queued)

## Versions of mu, mu4e/emacs, operating system etc.
Currently using mu 1.0 C and GNU Emacs 24.5.1.

## Any other detail
If I overwrite `Content-Type` header with `text/plain; charset=utf-8` everything goes smoothly.

**Comment by djcb** [comment]
It's mentioned in the manual (in "Known issues"), mu4e really depends on emacs being in utf8 mode, so that's what I'd recommend. It would be nice _not_ to depend on utf8, but I don't see that change anytime soon.
