### ISSUE TITLE
mu4e not compatible with aquamacs-autoface-mode

### ISSUE THREAD

**Issue by larrydberg** [djcb/mu#1230]
## Expected or desired behavior

Reasonable rapidity in carrying out actions.

## Actual behavior

Everything (really: everything) is slow as molasses. Redisplaying a headers buffer, moving from message to message, jumping to a maildir, all can take 5--10 seconds. "top" reports that the problem is lots of time in fontd. Even if you stay in the same mailbox and just use "n" and "p" to toggle between display of two messages, fontd is invoked for several seconds each and every time.

## Steps to reproduce

Just use mu4e within Aquamacs. Normally site-start.el turns on aquamacs-autoface-mode (via aquamacs-aux, via aquamacs-setup). For minimum failing protocol, run Aquamacs with -Q  to stop all initialization, then
```
(add-to-list 'load-path "<location of mu4e>") 
(require 'mu4e)
(mu4e)
```
... and life is good. Now to make everything slow to a crawl, just

`(require 'aquamacs-autoface-mode)`

To avoid the slowdown in general use, just put 

`(aquamacs-autoface-mode 0)`

in some Aquamacs-specific portion of some init file, say site-start.el.

## Versions of mu, mu4e/emacs, operating system etc.

OS X 10.10.5 (14F2411)

Aquamacs 3.2 GNU Emacs 24.4.51.2 (x86_64-apple-darwin14.0.0, NS apple-appkit-1343.14) of 2014-11-07 (Aquamacs-3.2) on watson.local

mu4e 0.9.18; emacs 24.4.51.2

## Any other detail

I don't know where the issue is, or what should be done to fix it (if anything). Just trying to get it on the record for others who have the same slowness issue.

**Comment by djcb** [comment]
Hmm, this should probably be reported to the aquamacs  maintainers, but if you have a little blurb for the "Known issues" section in the manual, that would be useful. Thanks!

**Comment by larrydberg** [comment]
1. I will report this to Aquamacs. I really should first check whether the problem goes away with the latest Aquamacs and mu4e, though I doubt that anything will have changed. The issue [here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=19266) may be related.
2. For "Known Issues":  The default configuration of [Aquamacs](http://aquamacs.org/) can make mu4e very slow. If you use Aquamacs and find that actions take a long time, try turning off autoface mode by customizing variable aquamacs-autoface-mode.

**Comment by djcb** [comment]
Thanks! Do you have a link to some Aquamacs bug so we can track this? Thanks.

**Comment by larrydberg** [comment]
Dirk-Jan C. Binnema writes:
> Thanks! Do you have a link to some Aquamacs bug so we can track this? Thanks.

I wrote aquamacs-bugs@aquamacs.org; copy attached. Is that enough to
create a bug, or is there something else for me to do?

--
/Larry Denenberg
larry@denenberg.com
http://larry.denenberg.com/

**Comment by djcb** [comment]
Thanks.
