### ISSUE TITLE
Mail from the future: missing with "date:..now" & CPU hog

### ISSUE THREAD

**Issue by Ambrevar** [djcb/mu#1232]
## Expected or desired behavior
Receive e-mails with a timestamp that is always older than current time.

## Actual behavior

Please describe the behavior you are actually seeing. 
Around 23:30 IST April 23rd, I received an e-mail (possibly from another timezone) which 
was dated

> Tue 24 Apr 2018 12:52:43 AM IST

I don't think this should ever happen.

Using the "date:7d..now" filter, the e-mail would not display because "now" does not go that far.

Furthermore, the mu4e-headers window seemed to hog the CPU for a long while on every refresh.  The issue went after current time was ahead of the date of the offending e-mail.

I'm not sure how to reproduce this.

## Versions of mu, mu4e/emacs, operating system etc.

- mu 1.0
- Emacs 26 RC1
- OS: GuixSD

**Comment by djcb** [comment]
Mails can claim to have any date they want, including from the future, and mu4e will just display that date they claim to have. If you think it's not showing the correct date, perhaps you can attach the message (sufficiently censored)?

If you see the performance problem again, please file a separate issue with the precise details and include the details (`perf` reports and/or emacs benchmark.). Otherwise, there's not much we can do. Thanks.

**Comment by Ambrevar** [comment]
The header contains the following:
```
Received: by 2002:a9d:3fa8:0:0:0:0:0 with SMTP id r37-v6csp2385703otc;
        Mon, 23 Apr 2018 09:24:48 -0700 (PDT)
[...few more timestamps...]
Date: Mon, 23 Apr 2018 19:22:43 +0000
```
The date / timestamp is mentioned several times in the header for various time zones: they all match the approximate same moment.  Only the date in the "Date:" field is off by approximately 3 hours.
This was sent to the Guix mailing list.

I'll try to reproduce and benchmark.

**Comment by Ambrevar** [comment]
Precisions: the sender has some configuration issue with Rmail and the date is wrong indeed.  Nothing wrong on mu4e's side.

That said, two issues:
- I think "DATE..now" should not restrict up to the current time, it should rather include everything from DATE, including all messages from the future.
- As for the performance issue, I'm not sure, it's hard to reproduce.  I tried to profile but it returned the following which is not very informative I think:

```
- mu4e~proc-filter                                                 64   5%
 - mu4e~headers-header-handler                                     40   3%
  - mu4e~message-header-description                                32   2%
   - mapconcat                                                     32   2%
    - #<compiled 0x1b70055>                                        32   2%
     - mu4e~headers-field-handler                                  28   2%
      - mu4e~headers-field-apply-basic-properties                  24   2%
         truncate-string-to-width                                   4   0%
        mu4e~headers-field-truncate-to-width                        4   0%
```

**Comment by djcb** [comment]
Hmm, I think `now` shouldn't include the future, that'd be a bit confusing. I.e. compare
```
% mu find --format=xquery date:7d..now
Query(VALUE_RANGE 16 1582146521 1582751321)
% mu find --format=xquery date:7d..
Query(VALUE_RANGE 16 1582146525 9999999999)
```

Thanks for the backtrace -- I'll check.

Closing this issue for now.
