### ISSUE TITLE
Performance of wildcard matching

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#1238]
With earlier versions of mu, I used to be able to search with expressions containing wildcards, e.g. `(maildir:/INBOX OR maildir:/Sent) test*`, and get results almost instantly.  With the current, I get the following:

```
$ time mu find '(maildir:/INBOX OR maildir:/Sent) test*'
real	0m8.617s
user	0m8.348s
sys	0m0.248s
```

This makes wildcards pretty much unusable in most scenarios.  Is there any chance that this can be fixed?

Unfortunately I can't nail down when the current behavior started but it was at least a couple of months ago.

Tested with current master on Ubuntu 16.04. My index contains about 100K emails.

**Comment by Ambrevar** [comment]
I can confirm this.  It's also slow with small indexes.

**Comment by Ambrevar** [comment]
It makes helm-mu barely usable :(

**Comment by tmalsburg** [comment]
Yes, I changed the default in helm-mu to not using wildcard matching. You can also set `helm-mu-append-implicit-wildcard` to `nil`.

**Comment by Ambrevar** [comment]
Thanks!

That'll do for now, but we should fix this properly at some point, it's
too important a feature.

**Comment by Ambrevar** [comment]
Can you point at the code?

I believe speed it essential here.  I wonder if it's an algorithmic lower bound or if there is an implementation issue.

If it's a lower bound, then what about having two query types?  The old one and the new one?

Also see https://swtch.com/~rsc/regexp/regexp1.html.

**Comment by tmalsburg** [comment]
On my system it's not a bit slower but two to three orders of magnitude.  Wildcards are pretty much unusable now.

**Comment by djcb** [comment]
I've pushed some changes that special-case wildcard searches using the Xapian built-ins. This should speed things up a bit.

**Comment by tmalsburg** [comment]
Thank you, Dirk.  Unfortunately, I can't test the new code because I'm on Ubuntu 16.04 and it's Xapian package doesn't support `OP_WILDCARD` yet.   I will report back as soon as I have updated to 18.04.

```
xapian.cc: In function ‘Xapian::Query maybe_wildcard(const Mux::Value*, const string&)’:
xapian.cc:59:24: error: ‘OP_WILDCARD’ is not a member of ‘Xapian::Query’
   return Xapian::Query(Xapian::Query::OP_WILDCARD,
```

**Comment by djcb** [comment]
Oh, that's too bad... I've fixed the compilation at least. Perhaps you can get a backport of a newer Xapian?

**Comment by djcb** [comment]
Anyway, I'll close this now. I think it should fix the situation but does indeed require a newer Xapian.

**Comment by djcb** [comment]
Great, thanks.
