### ISSUE TITLE
mu4e: Single-buffer view of thread, a.k.a. conversation view

### ISSUE THREAD

**Issue by Ambrevar** [djcb/mu#1239]
I was thinking of a nice addition to mu4e and I'd like to implement it if nothing like it already exists:

In the headers buffer, add a command to wrap all e-mails of the same thread into one entry with a number indicating how many e-mails have been folded.
Pressing `RET` switches to the view of the entire thread.

This conversation view displays the subject in the header line followed by all e-mails separated by a customizable horizontal delimiter.  Each e-mail section would have a simplified header containing the `From`, `Signature` and `Date` fields (there is no point in repeating the `To` and `Subject` fields).

The obvious advantage of this conversation view is that it makes for easier reading and browsing while allowing to search the entire thread with Emacs facilities (`isearch`, `occur`, etc.).

Other planned features:
- Use per-author faces.
- Your own replies are indented (this mirrors the style commonly seen in smartphone messengers).
- Foldable messages.
- Quotes  (text starting with `>`s) can be colored in the author attributed face (a simple string distance measurement could do).

The main issue is that e-mail threads have a tree structure, they are not necessarily linear.
I see two possibilities here:

- Either we display the thread in and Org-like fashion where tree nodes are foldable.
- Or we simply keep it chronological.

The first seems ideal, the latter is probably simpler to implement.

What do you think?

**Comment by djcb** [comment]
I like the ideas, but I think the current header view is not really the right vehicle to express them (some other people tried to add thread collapsing / unfolding etc., but it's quite hard).

So, my vague plan would be to replace the header-view, and split it in two parts: 
1) a generic, non-mu4e-specific tree-view (something like `tabular-list-mode`, but with support for trees, collapsing, unfolding and all the "dired-like" selection/marking etc.)
2) a mu4e-specific model for this view.

1) would need some facilities for some of the ideas you describe (ie. custom sub-headers); perhaps also multi-line headers.

Anyway, this is a big job!

**Comment by Ambrevar** [comment]
I haven't dug into the code of the headers buffer yet, but considering that it already supports toggling thread display, I'm wondering why it would be so hard.

The sub-headers I mentioned target `mu4e-view-*`, they are not related to the headers buffer (maybe I was confusing here).

**Comment by djcb** [comment]
Here's an attempt: https://github.com/djcb/mu/pull/783

The header-view code is already quite complex, and that pull makes it even more so. Your ideas are interesting, but I wouldn't want to complicate it further, instead a bit of rework is needed first I think.

A "conversation mode" would also need to have the message contents in the headers-view, which is simply not available right now.

**Comment by jschwab** [comment]
That sounds quite a bit like `mu4e-action-show-thread`.

**Comment by Ambrevar** [comment]
Thanks for pointing out this function, I didn't know about it.  But that's only one step to the goal, most of the work consists in displaying the _content_ of all the resulting messages into one single mu4e-view buffer.

**Comment by djcb** [comment]
If you want to prototype this, probably best to just create a _new_ view (rather than changing mu4e-view) that shows the current header in "conversation mode". You wouldn't even need to change any existing code.

A challenge is that there's a fairly fundamental assumption that you're viewing only one message. The headers view doesn't have any details like body text, attachments etc., so you can't easily get those.

Don't want to discourage you :-) but like I said, it won't be very easy.

**Comment by Ambrevar** [comment]
Indeed, my intent was to create a new mode for the sake of backward compatibility at least (it should be trivial to switch from conversation view to regular view).

I'll try working on a prototype as soon as possible.

**Comment by Ambrevar** [comment]
Prototype inbound: #1240!

**Comment by djcb** [comment]
Nice work Ambrevar!

**Comment by Ambrevar** [comment]
Thanks!  Lots more is coming, like multiple conversation views and auto-updates (e.g. on incoming e-mails).
