### ISSUE TITLE
mu4e~mark-fringe-len 2 wrong for fancy-chars

### ISSUE THREAD

**Issue by cacology** [djcb/mu#1245]
## Expected or desired behavior

Deleting a message with fancy-chars enabled marks the message with a ❌ and no extra number.  Removing that mark and putting it back on repeatedly leaves the original line intact.

## Actual behavior

Marking a message for deletion gives a ❌ and a number.  Repeatedly removing and marking the line for deletion erases the characters in the line.

## Steps to reproduce

(setq mu4e-use-fancy-chars t)

Enter headers mode, go to a message, mark it for deletion with D, unmark it with u, repeat a few times.

## Versions of mu, mu4e/emacs, operating system etc.

mu for emacs version 1.0 C
Emacs 26.1 (9.0)
MacOS 10.13.4

## Any other detail

What seems to be happening is that the overlay is recruiting the characters in the time stamp and dropping them when changed.  This didn't happen for all the marks.

I think this happens because mu4e~mark-fringe-len 2 is wrong for only two of the mark characters CROSS MARK and HEAVY MINUS SIGN.  The format function counts these single glyphs as two characters, which is expected to my surprise, see my bug report: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31588 .

I've fixed this for my instance by manually setting `(setq mu4e~mark-fringe-format "%s ")` which works just fine, but breaks the planned flexibility of the mu4e~mark-fringe system.  I can't figure out how to fix that system in its current logic, since,

"r " is two characters and
"❌ " is three characters.

**Comment by joostkremers** [comment]
I'm currently seeing this behaviour as well, but with the markers for flag and unflag (which are 0x271A HEAVY GREEK CROSS and 0x2796 HEAVY MINUS SIGN, respectively).

**Comment by djcb** [comment]
Given the linked https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31588, seems this is unfixable from mu4e's side. So, I guess people have to pick characters where this doesn't happen... Sorry!
