### ISSUE TITLE
Unable to build mu with guile on Arch Linux

### ISSUE THREAD

**Issue by jschwab** [djcb/mu#1247]
After 426b9a50c7d84db21f20b4528413c7bd6cc2c0fc, I am unable to build mu on Arch Linux.  

The relevant part of error message that I receive is 

> o mu-guile.x mu-guile.c -DHAVE_CONFIG_H -I. -I.. -I../lib -pthread -I/usr/include/guile/2.2 -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -g -O0 -I. -I.. -I../lib -pthread -I/usr/include/guile/2.2 -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
make[4]: o: Command not found

which looks like the command is empty (leaving -o at the start of the line) and if I look at guile/Makefile, I see

> GUILE_BINARY = 
> GUILE_CFLAGS = -pthread -I/usr/include/guile/2.2
> GUILE_LIBS = -lguile-2.2 -lgc
> GUILE_SITEDIR = 
> GUILE_SNARF = 

I'm on ArchLinux, where guile 2.0 has 2.0 appended (e.g., guile-snarf2.0) but guile 2.2 is unsuffixed (e.g. guile-snarf).  Looking at configure.ac, it seems like this is the opposite of what is assumed.

------------------------------------------------
mu version                           : 1.1.0

Xapian version                       : 1.4.5
GLib version                         : 2.56.1
GMime version                        : 2.6.23
Guile version                        : 2.2.3
Emacs version                        : GNU Emacs 25.3.1

------------------------------------------------

**Comment by djcb** [comment]
Urgh, the naming is not too consistent between distros, and the installed guile.m4 doesn't seem to handle that. I've updated mu to use a custom version; pls let me know if it works for you.

**Comment by jschwab** [comment]
Looks like this fixed things for me as far as guile is concerned, though I seem to have hit another issue along the way.  Since the problem first appears for me in d8db74d4, I assume it is related to those changes.

I did a fresh clone of git HEAD. and then when I run `./autogen.sh`, I get

```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:41: installing 'build-aux/compile'
configure.ac:53: installing 'build-aux/config.guess'
configure.ac:217: error: required file 'build-aux/config.rpath' not found
configure.ac:53: installing 'build-aux/config.sub'
configure.ac:30: installing 'build-aux/install-sh'
configure.ac:30: installing 'build-aux/missing'
contrib/Makefile.am: installing 'build-aux/depcomp'
guile/Makefile.am:53: installing 'build-aux/texinfo.tex'
parallel-tests: installing 'build-aux/test-driver'
mu4e/Makefile.am:21: installing 'build-aux/mdate-sh'
autoreconf: automake failed with exit status: 1
```

If I do `touch build-aux/config.rpath` to get past this, then things compile fine without the guile problems I reported earlier.

**Comment by djcb** [comment]
Ah yeah, that's a bug (?) in autotools IIRC. I'll add a work-around, thanks!
