### ISSUE TITLE
Problem with image inlining

### ISSUE THREAD

**Issue by tobiasBora** [djcb/mu#1248]
Hello,

First, thank you for this great tool. I just have a problem with inlined images, not sure if it's a bug or if I missed something.

## Expected or desired behavior

I'd like to be able to see inlined images in view html mode.

## Actual behavior

When I enable inlined images with

```
(setq mu4e-view-show-images t)
;; use imagemagick, if available
(when (fboundp 'imagemagick-register-types)
  (imagemagick-register-types))

```
and press the `h` button in view mode to go into html view, it fails to display the images (I just see the alt text instead), while it works great when I open the email from thunderbird, a browser, gmail... In raw mode, I can see this code for the image `<img src=3D"cid:_tmp_f9a.jpg" alt=3D"f9a.jpg" />` (same problem when the image is online).

Fun fact: at the end of the email, I can see the images (when they are attached) without any trouble! 

## Steps to reproduce

Load the code above, for example using `C-x C-e`. Open an email containing an image (either on the web, or enclosed), press `h` to go the html mode.

## Versions of mu, mu4e/emacs, operating system etc.

Mu/mu4e version 1.0, installed on debian sid, on emacs 25.2.2.

**Comment by djcb** [comment]
HTML rendering is beyond mu4e's control, so sadly we can't easily support that. Sorry!

**Comment by tobiasBora** [comment]
I found a first solution (note that you may need to press T on w3m to toogle images):

```
;; Enable images in w3m
(setq w3m-default-desplay-inline-images t)
(defun mu4e-action-view-in-w3m ()
  "View the body of the message in emacs w3m."
  (interactive)
  (w3m-browse-url (concat "file://"
              (mu4e~write-body-to-html (mu4e-message-at-point t)))))
```

**Comment by tobiasBora** [comment]
Hello again,

Sorry to bother you, but I don't understand why it's not possible to deal with images? For example if you just change `shr-inhibit-images` to `nil` in the function `mu4e-shr2text`, I can load without any trouble online images:

```
(defun mu4e-shr2text (msg)
  "Convert html in MSG to text using the shr engine; this can be
used in `mu4e-html2text-command' in a new enough emacs. Based on
code by Titus von der Malsburg."
  (mu4e~html2text-wrapper
    (lambda ()
	(let (
	 ;; When HTML emails contain references to remote images,
	 ;; retrieving these images leaks information. For example,
	 ;; the sender can see when I openend the email and from which
	 ;; computer (IP address). For this reason, it is preferrable
	 ;; to not retrieve images.
	 ;; See this discussion on mu-discuss:
	 ;; https://groups.google.com/forum/#!topic/mu-discuss/gr1cwNNZnXo
	      (shr-inhibit-images t)) ;; <--- LINE TO CHANGE
	  (shr-render-region (point-min) (point-max)))) msg))
```
and to deal with attached images, I think we can do more or less the same thing, you just need to replace all `cid` links into a link towards temporary file... Which is exactly the goal of the function `my-mu4e~write-body-to-html`! The only thing I'm not sure is whether shr can handle local pictures (I tried and it fails but I need to investigate more).

Or if you prefer a cleaner approach based on the DOM, I guess you can use the function provided in the link in the documentation string of the above function (we can of course adapt it to use `mu4e~html2text-wrapper`):

```
 (defun mu4e-shr2text ()
   "Html to text using the shr engine; this can be used in
 `mu4e-html2text-command' in a new enough emacs. Based on code by
 Titus von der Malsburg."
   (interactive)
   (let ((dom (libxml-parse-html-region (point-min) (point-max)))
         (shr-inhibit-images t))
     (erase-buffer)
     (shr-insert-document dom)
     (goto-char (point-min)))) 
```

Then, we would look for all images in the `dom`, and replace all `src="cid:..."` into the position of the internal file... It shouldn't be that difficult I guess, so I'll try to do it tomorrow or next week.

NB: if it's the privacy that bother you, then we can just put the value of `shr-inhibit-images` into a variable that one could choose if needed...

PS: in order to solve my problem with w3m, I did a strange trick. I don't know why but w3m does not display well png images that have a special palette, so I added at the end of the file `my-mu4e~write-body-to-html` a call to `convert` so that the file is converted into a picture which is nice to display. But I'm not sure if it should be a default as it can take some additional time to convert all pictures (but in my case it absolutely worth it).

**Comment by djcb** [comment]
Indeed, when you assume using shr as the html->text there's a bit more you can do; however, I think resolving cid's might be tricky, as we don't have the mime data available there.  In general, we set `shr-inhibit-images` since it's so easy to for users to make their experience unsafe otherwise, without realizing. We could use something mu4e-specific, perhaps.

Another thing you could try (with git master), is `(setq mu4e-view-use-gnus t)`, which uses `gnus` to parse/show messages, and hence you can use whatever is used there.

And then there's the xwidget support which allows for showing messages in their full graphical glory _inside_ a (suitably equiped) emacs.

**Comment by mredaelli** [comment]
@tobiasBora Can I ask what you ended up doing for this issue? I'm also very interested.

**Comment by wedens** [comment]
notmuch somehow renders images inline instead of at the end of the message. AFAIK it also uses shr for rendering. perhaps some tricks they use can also be used in mu4e?

**Comment by yitang** [comment]
@djcb I'm using xwidget and the snippet you provided in https://groups.google.com/forum/#!msg/mu-discuss/JqHEGycEyKI/RyxZR_slCwAJ.

it works great for many emails. there are few emails from Ebay that the images are not shown. I guess it's not straight forward to get it working for all types of emails.
