### ISSUE TITLE
Reply to multiple messages

### ISSUE THREAD

**Issue by Profpatsch** [djcb/mu#1249]
According to [RFC 5322] https://tools.ietf.org/html/rfc5322` the `In-Reply-To` header can consist of multiple messages.

The `mutt` client supports marking multiple messages, adds both their IDs to the `In-Reply-To` header of the response and quotes both mail bodies.

I propose adding that feature to `mu4e` as well.

**Comment by djcb** [comment]
This is not currently planned, and seems like a bit tricky to implement; so unfortunately will need to decline this.
