### ISSUE TITLE
Completely disabling HTML is not trivial

### ISSUE THREAD

**Issue by Profpatsch** [djcb/mu#1250]
HTML generally has a rather crude interface and is very discouraged from a security standpoint.

I was very surprised that even though I had set `prefer-html` explicitely to `nil`, it was still displaying most mails as HTML.

![screenshot](https://user-images.githubusercontent.com/3153638/40620363-d529595e-6298-11e8-9eef-0035068d9d51.png)

Turns out the correct thing to do is to find a footnote in section `5.5` of the manual, or trace-debug the code like I did.

I suggest instead of having a `prefer-html` setting and a (very) crude, buried heuristic, there should be a ”text by default” policy and an easy way to switch to HTML if necessary.

**Comment by djcb** [comment]
I think the default is reasonable (and safe); it's all documented and you can tweak it to your heart's content. So, I'm not too eager too add extra complexity here. However, a (very small!) PR could be considered for this. Do you have something in mind?

**Comment by Profpatsch** [comment]
> Do you have something in mind?

My approach would be to throw out the heuristic alltogether (it was not working very well with most HTML mails, since when they include `CSS` styling they are often a *lot* bigger than the plaintext versions).

At the very least, give the user an “always use plaintext” setting and maybe set it by default, while keeping the ability to switch to HTML with `h`.

The manual switch to text didn’t work for me btw in cases where the heuristic decided it would rather show HTML.

**Comment by djcb** [comment]
In my experience, it works reasonably well (given the complexity budget available for this); and you can tweak the heuristic to effectively give you "text only" (if there is any). You can also manipulate text2html to do something clever.

Anyway, if you have a tiny PR, that could be considered!

**Comment by djcb** [comment]
Note, things are a bit different with the new gnus-backed view-mode, ie `(setq mu4e-view-use-gnus t)`; https://www.gnu.org/software/emacs/manual/html_node/gnus/FAQ-4_002d6.html#FAQ-4_002d6

So, disabling html is quite easy now. Closing this one.
