### ISSUE TITLE
Can not run mu4e under emacs 25.3.3: Invalid byte opcode: op=183, ptr=2

### ISSUE THREAD

**Issue by Jazzpilz** [djcb/mu#1252]
## Expected or desired behavior

Opening mu4e suceeds without issue.

## Actual behavior

When trying to open mu4e, I receive:

- Error message: 'Invalid byte opcode: op=183, ptr=2'
- Debugger is not entered
- Happens always in emacs 25.3.3 for me when trying to execute mu4e

- Configuration was used in daily operation sucessfully for months in earlier emacs versions
- Problem appeared after doing the switch to emacs 25.3.3. 
- Recompiling mu (and I guess therefore mu4e) did not solve the problem
- Trying emacs 25.3.2 did not solve the problem either.

## Steps to reproduce

- Use emacs 25.3.3 or 25.3.2
- Use spacemacs with the mu4e layer
- Follow mu installation guide (https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html)
- Follow mu4e configuration guide (see emacs manual for mu4e)
- Try to access e.g. mu4e-main-menu

## Versions of mu, mu4e/emacs, operating system etc.

- mu version 1.1.0
- mu4e 1.1.0.
- GNU Emacs 25.3.3 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2018-05-25
- Linux mint 18.3. Sylvia
- gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

## Any other detail

- As I found in the mu4e requirements emacs version 23 or 24 I am not sure how well mu4e is meant to work on emacs 25.x.x in the first place (yet)

**Comment by djcb** [comment]
I should work. 

It _sounds_ like a incompatibility in the emacs byte-code; ie., the emacs trying to run the code is not compatible with the one used for compilation. Perhaps you have some earlier compiled version lying around?

**Comment by Jazzpilz** [comment]
Ok that sounds reasonable, good to hear that. I will try with a complete cleanup of my setup and report back afterwards, thank you.

**Comment by Jazzpilz** [comment]
Error is fixed, thanks a lot once more. 

Steps:
- Fresh build mu from github repo
- Had to deinstall 'guile-2.0-dev' first as this caused in the make step an error: (could not find 'mu-guile.x')
- Removed '(mu4e/mail-account-reset)' from my '.init.el' as this threw an error
- '(add-to-list 'load-path "~/Maildir/mu/mu4e/")' instead of '(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")'
- 'mu index --rebuild'

... works!! :+1: 

Reason:
- I had '(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")' which probably caused the error
- Pointing to correct mu4e directory solved the issue
