### ISSUE TITLE
Bogus contact addresses

### ISSUE THREAD

**Issue by divansantana** [djcb/mu#1253]
## Expected or desired behavior

The learned emailed addresses should just work out the box and be the correct email addresses.

## Actual behavior

*Some* of the email addresses being learned are bogus/broken. And they are not the correct contact addresses.

## Explaining further

So, I compose a new email.

I type Jane<tab>

It completes to:

```
To: "Van der Watt, "Van der Watt, Jane" <Jane.VanderWatt@example.co.za>
```

I then hit sent email and it complains, correctly so, that the email address may be bogus.

It should have completed to:

```
To: "Van der Watt, Jane" <Jane.VanderWatt@example.co.za>
```

If I look at `~/.mu/cache/contacts` it only contains one entry for this user and it says:

```
[janeVvanderwattOexampleVcoVza]
name=Van der Watt, Jane
email=Jane.VanderWatt@example.co.za
personal=true
tstamp=1527773164
frequency=641
```

I think the above looks correct?

I'm not sure why it's doing this and how to go about fixing the issue.

Any ideas?

## Steps to reproduce

Not sure. It seems to only happen for some of my contacts.

## Versions of mu, mu4e/emacs, operating system etc.

GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.29) of 2018-05-29

mu	1.0

**Comment by divansantana** [comment]
How do I go about finding which raw email on the FS is causing this?

**Comment by djcb** [comment]
I guess with the `~/.mu/cache/contacts` info, we don't need the raw file. Anyway, as mentioned in the mailing list:

Can't reproduce the issue with contacts that have exactly that format.
Let's look at the internal representation... if you evaluate (ie., go to
just beyond the last ')', then C-x C-e) the following, you should get
the internal representation in the *Messages* buffer.
```
--8<---------------cut here---------------start------------->8---
(maphash (lambda (k v)
	   (when (string-match "Watt" k) (message "%S" k)))
  mu4e~contacts)
--8<---------------cut here---------------end--------------->8---
```

And check whether that includes
   `"\"Van der Watt, Jane\" <Jane.VanderWatt@domain.co.za>"`
or some incorrect version.

It could also be that something goes wrong with the inserting... what do
you use for completion? Or are you using any third-party packages that
might interact?

**Comment by divansantana** [comment]
@djcb thank you thank you :) lol. This was annoying.

Your hint helped. <tab> was running `orgtbl-hijacker-command-102` or something like that caused by:

```
(use-package org
   ...
  :hook ((message-mode . turn-on-orgtbl)
        (message-mode . turn-on-orgstruct++))
   ...
```

Disabling that solved the issue. Not sure why it was causing it, but I can look at that another time.

Thanks!
