### ISSUE TITLE
Guile Work Broke Build

### ISSUE THREAD

**Issue by gburch** [djcb/mu#1254]
Step 17/25 : RUN cd "${UHOME}" && git clone git://github.com/djcb/mu && cd mu && ./autogen.sh && make && cp mu/mu /usr/bin/mu && cp -R mu4e /usr/local/share/emacs/site-lisp/
 ---> Running in 8b0d4ba01fa4
Cloning into 'mu'...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
configure:22053: error: possibly undefined macro: AC_LIB_LINKFLAGS_FROM_LIBS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by gburch** [comment]
Worked before https://github.com/djcb/mu/commit/426b9a50c7d84db21f20b4528413c7bd6cc2c0fc

**Comment by djcb** [comment]
I've made a small change (git master) that should help. Can you give it a shot? Thanks!

**Comment by gburch** [comment]
Only had a moment to run the build so no additional information but the error looks valid:

configure:21571: error: possibly undefined macro: AC_LIB_PROG_LD
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:21606: error: possibly undefined macro: AC_LIB_PREPARE_MULTILIB
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by tpapp** [comment]
Note sure if it is related, but build is broken for me on `master` with
```bash
make[4]: Entering directory '/home/tamas/src/mu/guile'
o mu-guile.x mu-guile.c -DHAVE_CONFIG_H -I. -I.. -I../lib -pthread -I/usr/include/guile/2.0 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -g -O0 -I. -I.. -I../lib -pthread -I/usr/include/guile/2.0 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
/bin/bash: o: command not found
Makefile:1236: recipe for target 'mu-guile.x' failed
make[4]: [mu-guile.x] Error 127 (ignored)
```

**Comment by tpapp** [comment]
Thanks for the PSA on the mailing list, the error in my comment above is resolved by `guile-2.2`.

**Comment by djcb** [comment]
@gburch: do things work for you now too?

**Comment by gburch** [comment]
Works!
