### ISSUE TITLE
Isn't it too hard to configure handlers from Emacs init.el?

### ISSUE THREAD

**Issue by Ambrevar** [djcb/mu#1258]
## Expected or desired behavior

I'd like to configure the `mu4e-view-func` handler for htts://notabug.org/ambrevar/mu4e-conversation:

```
(setq mu4e-view-func 'mu4e-conversation)
```

I want to let the users free to do this from their init file so that when mu4e starts, the correct handler is properly configured.

## Actual behavior

`mu4e.el` is read a second time from `mu4e-compose`, which redefines `mu4e-view-func` each time.  Is it really necessary to require `mu4e` from `mu4e-compose`?
  This is rather misleading and makes it a bit inconvenient for users to organize their configuration files.  See the steps below.

## Steps to reproduce
* `init.el`
```
(with-eval-after-load 'mu4e
  (require 'my-mu4e-config))
```
* `my-mu4e-config.el`
```
(when (require 'mu4e-conversation nil t)
  (setq mu4e-view-func 'mu4e-conversation))
```

Start Emacs, then mu4e and check the value of `mu4e-view-func`: it's the default `mu4e~headers-view-handler`.

## Suggested fix

Use `(autoload 'mu4e~compose-mail "mu4e"...)` instead and remove the `(require 'mu4e)` from `mu4e-compose.el`.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e 1.0
Emac 26.1
OS: GuixSD

**Comment by djcb** [comment]
I'm setting the handlers using `defvar` now, rather than `setq`, which should help for this.

A word of warning, overriding these means messing around with various `mu4e` internals, which may change etc.

**Comment by Ambrevar** [comment]
Thanks!
