### ISSUE TITLE
mu4e~speedbar-render-maildir-list seems not updated when changing context

### ISSUE THREAD

**Issue by Dav1d23** [djcb/mu#1259]
## Expected or desired behavior

If I got it well, the context behavior is `half-broken`: we can use context for multiple mail addresses, but in order to make it work we need to quit mu4e.
Even in this situation, we expect the speedbar to be updated with the new folders and the new counters after we quit / reload mu4e.

## Actual behavior

This is not working actually, and It looks like a bug in the header view.
My account switch definition looks like this:

```
(setq mu4e-contexts
      `( ,(make-mu4e-context
           :name "perso"
           :enter-func (lambda () (setq
                                   mu4e-maildir "~/.mail-perso"
                                   mu4e-mu-home "~/.mu-perso"
                                   )
                         )
           :leave-func (lambda () (mu4e-clear-caches))
           :vars '( ( user-mail-address  . "perso" )
                    ( mu4e-drafts-folder . "/[Google Mail]/Drafts" )
                    ( mu4e-sent-folder   . "/[Google Mail]/Sent Mail" )
                    ( mu4e-trash-folder  . "/[Google Mail]/Trash" )
                    ( mu4e-sent-messages-behavior . 'delete )
                    )
           )
         ,(make-mu4e-context
           :name "work"
           :enter-func (lambda () (setq
                                   mu4e-maildir "~/.mail-work"
                                   mu4e-mu-home "~/.mu-work"
                                   )
                         )
           :leave-func (lambda () (mu4e-clear-caches))
           :vars '( ( user-mail-address   . "work" )
                    ( mu4e-sent-folder    . "/Sent Items" )
                    ( mu4e-drafts-folder  . "/Drafts" )
                    ( mu4e-trash-folder   . "/Trash" )
                    ( mu4e-refile-folder  . "/Archive" )
                    )
           )
         )
      )
```

When I start mu4e on a `new` emacs, it shows the correct account.
When I switch, the view stays on the first one.

If I try to call the functions directly, it looks like it works!
Example:
```
(mu4e-context-switch) ; choose work
(mu4e~speedbar-render-maildir-list) ; shows the good list
(mu4e-context-switch) ; choose perso
(mu4e~speedbar-render-maildir-list) ; shows the good list, so this is fine
```

Emacs 26.1, mu built on commit 67eea5fadd0f0ae240549ab6a6f1aa43aac9cb40

**Comment by Dav1d23** [comment]
I tested like this:
* open context A => good bar
* change to context B =>  not good
* exit mu4e, rerun mu4e again
* still not good, but "suddenly" (I maybe pressed `u`, I don't remember) the list changed, and it was good
* tried to switch from B to A again, exit, rerun mu4e => not good, and it is not changing anymore.

The desync is `strange` because using j is showing the right folders.

I have another issue (dunno if related): the counters are always (0/0) beside the folders.

**Comment by djcb** [comment]
Okay, it should work now... (git).
