### ISSUE TITLE
Accentued characters not encoded in subject with `mu4e-view-use-gnus` non nil

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1260]
## Expected or desired behavior

The subject should be like this:
`Subject: -30% sur les nouveautés, les Ventes Privilèges sont lancée`

## Actual behavior
```
It is actually like this:
Subject: =?ISO-8859-1?Q?-30%_sur_les_nouveaut=E9s,_les_?= =?ISO-8859-1?Q?Ventes_Privil=E8ges_sont_lanc=E9es?=
```

To reproduce you need a message with accentued characters in subject and `mu4e-view-use-gnus` non nil.

**Comment by djcb** [comment]
Is this with the latest git master? At least I can't reproduce that, and I have quite some messages with diacritics in the subject line. If you still see this with master, can you attach a (sufficiently censored) raw messages that shows this behavior? Thanks.

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Is this with the latest git master?

No, I have updated now to very last and can't reproduce, closing.

Thanks and sorry for the noise.

-- 
Thierry
