### ISSUE TITLE
Parse error regression in 6290e4ad ("query-parser: special-case wildcards", 2018-05-18)

### ISSUE THREAD

**Issue by avar** [djcb/mu#1261]
Maybe I should just change something on my side, but when using the latest master I get parse errors on some wildcard queries. Bisecting reveals this is due to 6290e4ad ("query-parser: special-case wildcards", 2018-05-18).

Looking at the code and playing around with different searches it turns out the failing search is:

    subject:"Cron <crontabs@*"

Which via experimentation I see can be reduced to:

    subject:"foo bar*"

Or more generally, anything that includes spaces in the query part, e.g.:

    body:"x y*"

This is on xapian 1.4.5 on Debian testing.

**Comment by djcb** [comment]
`subject:"foo bar*"` searches for messages with subject "foo" and a set of common fields for "bar*". I.e., the `"` does not take the thing as a unit.

In any case, we shouldn't have parser errors... what happens when you do `mu find subject:"foo bar*"  --format=xquery`? 
`

**Comment by avar** [comment]
I was testing this by having the query in a file and then doing `mu find $(cat file.txt)`, but didn't see that of course that includes the quotes too.

So a command-line reproduction is something like:

```
$ ~/g/elisp/mu/mu/mu find subject:"\"foo bar*\"" --format=xquery
mu: mu_query_internal_xapian: xapian error 'OP_NEAR and OP_PHRASE only currently support leaf subqueries'
mu: parse error in query (13)
```

With the patches reverted I get a query plan, but it spews out lots of tokens from my (work) mailbox, so I don't want to post it here.

**Comment by djcb** [comment]
Ah, thanks... seems some more `#ifdef` massaging is needed for this xapian version.

**Comment by avar** [comment]
@djcb : Been a while since I poked at this, but it's still broken on latest master, I tried with both xapian 1.4.3 and 1.4.7 (from Debian stable/testing). Doing:

git revert 7a8d43dc5f0568125cd41ebb74edd7b712ce7133 6290e4ad9a3f4c1101b49c90736d7f7e617ea1bf

Fixes it for me.

**Comment by djcb** [comment]
Looking at this now, ... `subject:"\"foo bar*\""` is not a valid wildcard expression since the wildcard is not the rightmost thing in the term.

I've pushed a change to avoid the parser error.

**Comment by avar** [comment]
Thanks, looks good.
