### ISSUE TITLE
Feature request: address groups

### ISSUE THREAD

**Issue by prosoitos** [djcb/mu#1263]
Thank you so much for `mu4e`! Been using it for several years and absolutely love it. Also, apologies if this feature already exists and I failed to find it. I did google and read the documentation, but could have missed something.

Is there a way to create an email address for a group of addresses? How could I do this? If not, is this something that could be implemented? There are countless ways around it using yassnippets, autocompletion, etc. or I could try to write a function for each group that would replace its address by the list of addresses. But it might make sense to have the actual feature.

Thank you!

**Comment by jschwab** [comment]
I use emacs built-in mail aliases for this:
https://www.gnu.org/software/emacs/manual/html_node/emacs/Mail-Aliases.html

**Comment by prosoitos** [comment]
Ah! Great! Thank you for your suggestion! `mu4e` is the only mail system I have used in emacs, so I never thought of exploring its built-in features. I will definitely explore this.

**Comment by prosoitos** [comment]
Ok, this works great. Thank you again @jschwab! It is very similar to what I was doing with yassnippet as a workaround (I hadn't thought of using abbrev).

One thing though: since it is simply an expansion mechanism, it reveals all the addresses. So it forces me to put the list in Bcc and send to "undisclosed recipients" if I want to preserve the privacy of people in the list.

**Comment by djcb** [comment]
I suspect what Outlook does is create a server-side group-address (e.g. on an MS Exchange server), since ultimately *somewhere* the group-address has to be expanded into a series of plain-old e-mail addresses.

@jschwab's idea is probably the reasonable thing to do for clients like mu4e. 

I suppose you could automate this a bit, a rudimentary version
```
(defun my-compose-group-mail (group subj)
  (interactive "sGroup: \nsSubject: ")
  (compose-mail nil subj `(("Bcc" . ,group))))
```
exercise to the reader: make the Bcc group expand as per the mail-aliases.

**Comment by prosoitos** [comment]
Thank you for your input @djcb (and thanks for `mu4e`!!!!).

The both of you were very helpful with my question! I guess I can close this issue now.

**Comment by prosoitos** [comment]
> exercise to the reader: make the Bcc group expand as per the mail-aliases.

The aliases actually get automatically expanded on send, which is nice.

I modified your function slightly so as not to have to worry about the "To:" line:

```elisp
(defun my-compose-group-mail (group subj)
  (interactive "sGroup: \nsSubject: ")
  (compose-mail to subj `(("Bcc" . ,group)
			                 ("To" . "Undisclosed recipients"))))
```

Now, it would be cool to make use of the function `mail-abbrev-insert-alias` which offers to choose amongst the aliases, rather than having to remember and type the alias. My elisp skills are very rudimentary however and if you had the time and could give me little hints on how I could get started with this, I would really appreciate. My attempts have so far not lead very far. If not no worries: this function, in combination with @jschwab's advice about abbrev are already great.

Thank you!!!

**Comment by jschwab** [comment]
My usual strategy would be to steal the part of the function I want.   So I'd do `C-h f mail-abbrev-insert-alias`, click on the link to mailabbrev.el, and read its source code.  That shows me how the interactive competing read happens, so I'd take that bit and graft it in.  Something like:

```elisp
(defun my-compose-group-mail (alias)
  (interactive (progn
		 (if (not (vectorp mail-abbrevs)) (mail-abbrevs-setup))
		 (list (completing-read "Alias: " mail-abbrevs nil t))))
  (compose-mail "Undisclosed recipients" nil `(("Bcc" . ,alias))))
```
which I think will roughly do what you want.

**Comment by prosoitos** [comment]
Thank you very much not only for giving a solution, but also for taking the time to explain how to get to it. I truly appreciate!
