### ISSUE TITLE
mu4e main print list of all maildirs in current-buffer on startup

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1264]
## Expected or desired behavior

Don't write in current-buffer

## Actual behavior

All the Maildir tree is printed in current-buffer, this on first call of `mu4e` after emacs startup.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e: 1.1.0
emacs: emacs-26.1
OS: Linux mint

**Comment by thierryvolpiatto** [comment]
I guess this was introduced by commit d98e785

Thanks.

**Comment by djcb** [comment]
Hmmm, should be fixed now.

**Comment by thierryvolpiatto** [comment]
Thanks for the quick fix! It is working now.
