### ISSUE TITLE
mu4e-view-use-gnus: add header for maildir

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1269]
When looking at the result of searches, it is convenient to have the information of the directory the message is in.  With the option `mu4e-view-use-gnus` set to `t`, it would be nice to have that information.

**Comment by brabalan** [comment]
I also need this information, which I include in the headers view:
``` emacs-lisp
(setq mu4e-headers-fields '((:maildir . 30)
                                              (:human-date . 12)
                                              (:flags . 4)
                                              (:from . 25)
                                              (:subject)))
```

**Comment by Chris00** [comment]
I use `mu4e-view-fields` to add additional headers not handled by Gnus.

**Comment by dmacvicar** [comment]
> I use `mu4e-view-fields` to add additional headers not handled by Gnus.

I can't get this to work

```elisp
  (setq mu4e-view-fields '(:maildir :mailing-list))
```
or

```elisp
  (setq mu4e-view-fields '(:subject :to :from :cc :bcc :from-or-to :date :attachments :maildir :mailing-list))
```

I only see the ones gnus handle internally (eg. _From_ _To_ _Subject_ _Cc_ _Date_ _Organization_ _Reply-To_).

**Comment by Chris00** [comment]
@dmacvicar You applied the PR https://github.com/djcb/mu/pull/1303 to your code and recompiled, right?

**Comment by dmacvicar** [comment]
Ah, did not realize the PR was open. Thanks, I applied the PR#1303 patch to my package and now it works.

https://build.opensuse.org/package/show/home:dmacvicar:mu/maildir-utils
