### ISSUE TITLE
Adding spook function as an email signature

### ISSUE THREAD

**Issue by averter** [djcb/mu#1270]
Hi,

I have been looking forward to this day since I have learned of the emacs spook function. Is it possible to add the M-x spook emacs output as an email signature in mu4e? If so how? I have tried adding `(add-hook 'mail-setup-hook 'fortune-to-signature)` or replacing `(mu4e-compose-signature nil)` by  `(mu4e-compose-signature 'fortune-to-signature)` in my init  file, but without any success. 
Thank you in advance.

**Comment by averter** [comment]
Ok, a quasi-working solution which I found goes like this
```elisp
     (mu4e-compose-signature (with-temp-buffer
     	 		       (spook)
			       (buffer-string)))
```
The only thing that needs a bit of tweaking is that this solution also adds an empty line between the `--` marks and the spook output:

--text follows this line--
-- 

SLIP Twister market Avian Soviet Indigo kilo class bomb DEVGRP SGC
SUSLO Federal Air Marshal Service White House VNET Vickie Weaver

**Comment by thierryvolpiatto** [comment]
Averter <notifications@github.com> writes:

> Ok, a quasi-working solution which I found goes like this
>
>      (mu4e-compose-signature (with-temp-buffer
>                                (spook)
>                                (buffer-string)))

Use instead:
  
    (setq mu4e-compose-signature 'spook)

> The only thing that needs a bit of tweaking is that this solution also
> adds an empty line between the -- marks and the spook output:

Guess that is what expected.

--
Thierry

**Comment by averter** [comment]
Hi,

Actually I already had tried that one and it didn't work. Nothing shows up if I do it that way.
I must add that I am using mu4e 0.9.11 C (yea, a quite old version, IK) and that the construct that I have described above is part of the (defvar my-mu4e-account-alist) setup.

**Comment by djcb** [comment]
Thanks to @thierryvolpiatto, indeed that is the correct way to do it. 

It works with current versions, and really should work with older versions as well, so I suspect some setup-problem. For troubleshooting, perhaps check if the hook is invoked at all. And perhaps disable extensions (if any) such as evil.

**Comment by averter** [comment]
@djcb I have now updated to 0.9.18C and so that is definitely not the problem. Due to my inexperience with elisp a setup-problem is likely. However signatures for the other context accounts work perfectly. Also, I found another setup which works semi-optimally. If I put this variable in the context account

```elisp
(mu4e-compose-signature  . (spook))
```

I get this output

```
--text follows this line--

keyhole Retinal Fetish Wave OAU Hezbollah Subway Meta-hackers Eco
terrorism Conficker FINCEN ninja Ionosphere nitrate Public Health FIS

-- 
```
where the string gets placed above the -- . The hooks that I am using, and where I think a problem is most likely, are:
```elisp
;; EMAIL COMPOSITION
(setq message-cite-reply-position 'above		;; set signature below reply
      mu4e-compose-dont-reply-to-self t)		;; exclude own e-mail address when “replying to all”
(add-hook 'message-mode-hook 'turn-on-orgtbl)		;; use org tables 
(add-hook 'message-mode-hook 'turn-on-orgstruct++)	;; and structures in message mode

;; HOOKS (THINGS TO DO BEFORE AND DURING EMAIL WRITING)
(require 'epa-file)					;; SIGNING AND ENCRYPTING
(add-hook 'mu4e-compose-mode-hook
	  (defun my-setup-epa-hook ()			;; SIGNING AND ENCRYPTING
	    (epa-mail-mode)))
(add-hook 'mu4e-view-mode-hook
	  (defun my-view-mode-hook ()			;; SIGNING AND ENCRYPTING
	    (epa-mail-mode)))
(add-hook 'mu4e-compose-mode-hook 'flyspell-mode)	;; spell check 
```

**Comment by averter** [comment]
That solution is equivalent to what I had before. The mentioned empty line is included in the spook function output. Is there a way to remove it from the temporary buffer? I have tried a few commands, but as an elisp noob, without luck.

**Comment by djcb** [comment]
Oh! Clearly I didn't read the whole thread. Anyway, what you see is the just what `spook` does, ie., and an extra newline at the start. You could try something like:

```
(setq mu4e-compose-signature
  (lambda ()
    (with-temp-buffer
      (spook)
      (goto-char (point-min))
      (kill-line)
      (buffer-string))))
```

**Comment by averter** [comment]
Brilliant. Thank you very much!
