### ISSUE TITLE
Index compressed Maildir

### ISSUE THREAD

**Issue by ddacunha** [djcb/mu#1272]
## Expected or desired behavior
Ability to index compressed Maildir (gzip/bzip2)

## Actual behavior
`mu` is ignoring messages with the following error message `mu: message seems invalid, ignoring `

## Steps to reproduce

Enable compression in Dovecot & restart:
```
mail_plugins = zlib

plugin {
  zlib_save_level = 9 # 1..9; default is 6
  zlib_save = bz2 # or gzip, bz2, xz or lz4
}
```

Try to run `mu index` after a new email has arrived.

## Versions of mu, mu4e/emacs, operating system etc.
`mu (mail indexer/searcher) version 1.0`

Ideally the four compression format supported by Dovecot should be supported, but gzip & bz2 seems to be the most used.

**Comment by djcb** [comment]
That would be quite difficult to seamlessly, esp. when including moving messages around. Frankly, it's a basic mu assumption that it gets the email in a normal Maildir format. Some filesystems transparently compress, than would be a better route. So, thanks for the suggestion, but going to decline this.
