### ISSUE TITLE
Get list of used tags

### ISSUE THREAD

**Issue by tobiasBora** [djcb/mu#1274]
Hello,
Thank for this great tool. I'd like to know, is it possible from mu4e to get the list of all tags used? It would be really nice to improve my ido-based completion search and tag assignment function.

Thanks!

**Comment by djcb** [comment]
Unfortunately, that's not really possible (well, feasible). Guess you could make a completion function and manually seed it with the tags you want to use.

**Comment by tobiasBora** [comment]
Thank you for your answer. But I'm curious to know, what makes it hard to implement ? It seems to me that as soon as you can search on a column in a database, you can always list all the different elements of that column… What's wrong with that ?

**Comment by djcb** [comment]
Xapian (mu's datastore) is not a relational database with columns, but a set of objects (documents). To get all the values for some document property (such a "tags"), you'd need to iterate over all of them. Even when you have those tags, you'd need to get them to the mu4e UI

Now, in principle perhaps an approach similar to what we do for contacts might work... but it would be too much work and extra complexity for this - sorry!

**Comment by tobiasBora** [comment]
Ok thank you for the explanations. I may give it a look later, but for now I think I'll stay with an offline list of tags. Thanks!
