### ISSUE TITLE
Missing newline after Subject on compose

### ISSUE THREAD

**Issue by baruchsiach** [djcb/mu#1282]
## Expected or desired behavior

The Subject header should be separated from its following header by a newline.

## Actual behavior

The header that follows Subject appears on the same line right after Subject, affectively being appended to the Subject text.

## Steps to reproduce

Compose a new email.
Hit C-c C-c to finish the email, while leaving the Subject line blank.
You will be prompted to enter Subject text.
Write the Subject text, and hit Enter to send the email.

## Versions of mu, mu4e/emacs, operating system etc.

I use mu4e and emacs from Debian testing.

mu4e version: 1.0-5
emacs version: 25.2+1-6+b2

## Any other detail

Not sure if this is actually related to mu4e, or something with the emacs message mode.

**Comment by djcb** [comment]
Hmm, `mu4e` does not ask you about an empty subject. Did you install something on `message-send-hook` perhaps?
