### ISSUE TITLE
mu4e-view-use-gnus: cannot open attachment after using gnus

### ISSUE THREAD

**Issue by tuxella** [djcb/mu#1283]
When using `mu4e-view-use-gnus`, I can open or view attachments without problem until I use gnus to read newsgroups.

## Steps to reproduce
- enable `mu4e-view-use-gnus`
- `M-x gnus` (for instance "news.gmane.org" over nntp) and then open a message
- Exit gnus
- Open mu4e and open a message with attachements.

## Actual behavior
Attachements links right under headers are not active (I cannot click them and hitting `o` with the cursor over them doesn't do anything).

Quitting mu4e doesn't fix it. I need to restart emacs to open attachments.

## Expected or desired behavior
Attachements should be active, just like they are before I ran gnus.

## Versions of mu, mu4e/emacs, operating system etc.

- mu and mu4e from git: 5ccd2617717599cdd2bc59f52d60cde85a417aeb
- macOS 10.13.4
- GNU Emacs 26.1

**Comment by djcb** [comment]
Interesting... seems gnus changes the environment in some way which interferes with mu4e's later.

If you can share any further details / analysis of what those changes that may be, that would be very useful! Thanks.

**Comment by dmacvicar** [comment]
This happens to me all the time. I was trying `mu4e-view-use-gnus` in 1.2 as a replacement for the standard message view.

I have an email with an attachment, ant it generates a link that you can click/enter, which triggers save.
However, 'o' shortcut says: `[mu4e] No attachments for this message`

**Comment by djcb** [comment]
@dmacvicar: I think that's a different issue, which has been fixed in 1.3

**Comment by A6GibKm** [comment]
I can open and save attachment but I don't see them on the headers of such email. I can only tell an email has an attachment from mu4e-view flag.

**Comment by averter** [comment]
Gnus is very deceitful. You only see that the `o` command works when you have the cursor OVER the attachment. Otherwise it states that `binding not supported with the gnus-based view`, which is untrue.  The Help info doesn't fare much better, where `??` shows as assigned to `o`. 
Incidentally, does anyone know if there is a keybinding to save all attachments? I know that there is such an option in the toolbar (yuck) so I assume that it is implemented and just difficult to find at the moment.

**Comment by djcb** [comment]
Does this still happen with the latest (>= 1.5.11, or git master)?

**Comment by mfauvel** [comment]
I can save one attachment at time with `e`, but not all attachments as before (the function is not available anymore). All the attachments are visible from the headlines and I can click on them.
I am using mu4e 1.5.11.

**Comment by djcb** [comment]
`mu4e-view-save-attachment` is available under `e` in gnus-mode.

You can select multiple attachments (see `completing-read-multiple`); if you're using `helm` you can type `M-a` to select all. It's a bit different from how it's done previously.

Anyway, this is a bit off-topic for this particular issue.

**Comment by mfauvel** [comment]
Thanks @djcb  and @averter 

I will open a new issues since I can't save multiple attachments (I am using Ivy) and my original comment was to respond to 
https://github.com/djcb/mu/issues/1283#issuecomment-801507172

**Comment by djcb** [comment]
You can save multiple attachments with Ivy, `e`. select part, then ",", next part etc.
