### ISSUE TITLE
Close *mu4e-raw-view* buffer on 'q' keypress

### ISSUE THREAD

**Issue by wilhelmy** [djcb/mu#1287]
Other buffers and windows close when 'q' is pressed. The \*mu4e-raw-view\* buffer is an exception.

**Comment by djcb** [comment]
Works for me. What does `C-h k q` say when you're in the raw-view buffer?

**Comment by wilhelmy** [comment]
Seems evil-mode's 'q' binding cancels out mu4e's. It doesn't do that in any of the other mu4e windows...

**Comment by djcb** [comment]
Hmm, please complain with the `evil` maintainers then... In general, it's a good idea to mention such details in bug reports, same for versions etc.
