### ISSUE TITLE
Add UI for List-* headers (RFC 2369)

### ISSUE THREAD

**Issue by wilhelmy** [djcb/mu#1288]
## Expected or desired behavior

Mailing lists are managed through List-{Id,Subscribe,Unsubscribe,Post,Archive,...} as described in https://www.ietf.org/rfc/rfc2369.txt

Typically, these are mailto- or http/https-URIs, which can be handled with 'browse-url'.

My idea would be to have an "L" prefix for quick access to the values of the list-related headers, with subcommands "p" for post, "u" for unsubscribe, "o" for managing list options, "a" for archive, etc.?

## Actual behavior
This is a feature request. At the moment, I press "." to get the raw-message and then copy-paste the relevant header value.

**Comment by djcb** [comment]
mu4e (git) has a setting `mu4e-view-use-gnus` (see the mailing list for the discussion); potentially,  https://www.gnu.org/software/emacs/manual/html_node/gnus/Mailing-List.html
might work (though perhaps not through the keybindings).

Can you check?

**Comment by wilhelmy** [comment]
Thanks for the hint, I'll check it out. I need to update to the git version first.

**Comment by wilhelmy** [comment]
The first time I view a mail with `mu4e-view-use-gnus` set to `t`, it complains that there is no buffer named `*Article*`, but apparently it manages to create it or at least continue anyway.

`(gnus-mailing-list-insinuate)` complains that there is no `List-Post` header, which is true for many newsletters, they often only have `List-Unsubscribe`, but apparently it also doesn't work in at least one case where there is a `List-Post` header... not sure if I need to do more than just call it like `M-: (gnus-mailing-list-insinuate)` on a mu4e-view buffer? I don't know how the insinuating mechanism works.

I'll investigate things further. Thanks for your continued effort developing mu and mu4e.

**Comment by djcb** [comment]
Oh, I haven't studied exactly how gnus does it... if you figure it out, let us know, and perhaps we can make it 'just work' with mu4e.

**Comment by omajid** [comment]
Gnus's implementations look like this: https://github.com/emacs-mirror/emacs/blob/d0e2a341dd9a9a365fd311748df024ecb25b70ec/lisp/gnus/gnus-ml.el#L118-L125

It doesn't seem too difficult to replicate in mu4e.

I tried doing it, but ran into an issue:

```elisp
  (defun my-mu4e-get-mail-header (msg header-name)
    (let ((path (mu4e-message-field msg :path)))
      (my-mu4e-get-mail-header-path header-name path)))

  ;; from https://etienne.depar.is/emacs.d/mu4e.html
  (defun my-mu4e-get-mail-header-path (header-name path)
    (replace-regexp-in-string
     "[ \t\n]*$"
     ""
     (shell-command-to-string
      (concat "/usr/bin/sed -n '/^" header-name ":/I{:loop t;h;n;/^ /{H;x;s/\\n//;t loop};x;p}' '" path "' | sed -n 's/^" header-name ": \\(.*\\)$/\\1/Ip'"))))

  (defun my-mu4e-unsubscribe-list (msg)
    ""
    (let* ((list-unsubscribe (my-mu4e-get-mail-header msg "list-unsubscribe")))
      (xxx-send-mail-xxx)))

  (add-to-list 'mu4e-view-actions
               '("xunsubscribe from mailing list" . my-mu4e-unsubscribe-list) t)
```

I don't know how to implement `xxx-send-mail-xxx`, which would send email programmatically. It doesn't look like `mu4e` provides a lisp api for this. Any suggestions?

**Comment by omajid** [comment]
Nevermind, List-Unsubscribe (via `my-mu4e-unsubscribe-list` below) turned out to be easier than I had expected:

```
  (defun my-mu4e-get-mail-header (msg header-name)
    (let ((path (mu4e-message-field msg :path)))
      (my-mu4e-get-mail-header-path header-name path)))

  ;; from https://etienne.depar.is/emacs.d/mu4e.html
  (defun my-mu4e-get-mail-header-path (header-name path)
    (message "%s" path)
    (replace-regexp-in-string
     "[ \t\n]*$"
     ""
     (shell-command-to-string
      (concat "/usr/bin/sed -En '/^" header-name ":/I{:loop t;h;n;/^( |\\t)/{H;x;s/\\n//;t loop};x;p}' '" path "' | sed -n 's/^" header-name ": \\(.*\\)$/\\1/Ip'"))))

  (defun my-mu4e-unsubscribe-list (msg)
    (let* ((list-unsubscribe (my-mu4e-get-mail-header msg "list-unsubscribe"))
           (mailto-start (string-match "<mailto:" list-unsubscribe)))
      (if mailto-start
          (let* ((mailto-end (string-match ">" list-unsubscribe (+ 1 mailto-start)))
                 (mailto-address (substring list-unsubscribe (+ mailto-start 1) mailto-end)))
            (url-mailto (url-generic-parse-url mailto-address))
            (goto-char (point-min))
            (re-search-forward "--\n")
            (delete-region (point) (point-max)))
        (let* ((url-start (or (string-match "<" list-unsubscribe) 0))
               (url-end (or (string-match ">" list-unsubscribe url-start) (length list-unsubscribe)))
               (unsubscribe-url (substring list-unsubscribe url-start url-end)))
          (browse-url unsubscribe-url)))))

  (add-to-list 'mu4e-view-actions
               '("xunsubscribe from mailing list" . my-mu4e-unsubscribe-list) t))
```

**Comment by Chris00** [comment]
@djcb How about to make possible to add those headers to [`mu4e-view-fields`](https://github.com/djcb/mu/blob/master/mu4e/mu4e-view.el#L62)—making them clickable?
