### ISSUE TITLE
What is the use of function org-mu4e-store-and-capture?

### ISSUE THREAD

**Issue by ericdanan** [djcb/mu#1289]
It seems to me that this function is not needed since `org-capture` itself calls `org-store-link`.

Indeed, if I call `org-capture` from a mu4e headers or view buffer and select a template with an `%a` element, then the mu4e link is correctly inserted.

Am I missing something?

Thanks.

**Comment by djcb** [comment]
It's just a small convenience function... not sure if it's still needed, but people might depend on it. Perhaps it could be deprecated.
