### ISSUE TITLE
List-ID is not decoded

### ISSUE THREAD

**Issue by xuchunyang** [djcb/mu#1292]
## Expected or desired behavior

Render

    List-ID: =?UTF-8?Q?<=E9=97=B2=E8=81=8A=E7=81=8C=E6=B0=B4.emacs-china.org>?=

as

    List: <闲聊灌水.emacs-china.org>

## Actual behavior

mu4e now displays it as

    List: =E9=97=B2=E8=81=8A=E7=81=8C=E6=B0=B4.emacs-china.org

## Versions of mu, mu4e/emacs, operating system etc.

Welcome to the Emacs shell

```
Welcome to the Emacs shell

~ $ mu --version
mu (mail indexer/searcher) version 1.1.0
Copyright (C) 2008-2018 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
~ $ (emacs-version)
GNU Emacs 26.1 (build 4, x86_64-apple-darwin17.6.0, Carbon Version 158 AppKit 1561.4)
 of 2018-06-10
~ $ 
```

## Any other detail

The Subject is using the same encoding, but mu4e renders it correctly.

**Comment by djcb** [comment]
Can you add a raw message where this happens? Thanks.

**Comment by xuchunyang** [comment]
https://gist.githubusercontent.com/xuchunyang/490038b7dfaf79a3fe8ea0dd2817b5bc/raw/c32e4a6dd4c32673269b415c466c86c7de1d9209/raw-message.txt

and mu4e renders it as the following (the red rectangle is added by me)

![screen shot 2018-08-05 at 3 55 01 pm](https://user-images.githubusercontent.com/4550353/43683918-5b1cd346-98c8-11e8-92e8-6e68eb6a7c18.png)

**Comment by djcb** [comment]
Should work now, after `--rebuild`.
