### ISSUE TITLE
mu server: Extreme hang when decrypting

### ISSUE THREAD

**Issue by Ambrevar** [djcb/mu#1293]
Some PGP-encrypted e-mails I received take a very long time to open.  One of 9.8K takes about 8s, another one of 25M (with attachments) takes about 20s.

It only happens with the same expedient.  The e-mails are not signeld, but mu4e display the `Signature: ...` header nonetheless.

- The 9.8K mail (without attachment) signature detail:
```
verdict: verification failed
	1: error
created:?, expires:06/28/2018, signer:?, key:XXXXXXXXXXXXXXXX (RSA,SHA-256), trust:none
``` 
- The 25M mail (with 3 attachments) signature detail:
```
verdict: verification failed
	1: error
created:?, expires:07/21/2018, signer:?, key:XXXXXXXXXXXXXXXX (RSA,SHA-256), trust:none
	1: error
created:?, expires:07/21/2018, signer:?, key:XXXXXXXXXXXXXXXX (RSA,SHA-256), trust:none
	1: error
created:?, expires:07/21/2018, signer:?, key:XXXXXXXXXXXXXXXX (RSA,SHA-256), trust:none
	1: error
created:?, expires:07/21/2018, signer:?, key:XXXXXXXXXXXXXXXX (RSA,SHA-256), trust:none
	1: error
created:?, expires:07/21/2018, signer:?, key:XXXXXXXXXXXXXXXX (RSA,SHA-256), trust:none
```
I've replaced the key so to not disclose the identity of the expedient.
Note the expiry date is actually the email date, not the real expiry date.  But I've noticed the same thing on all other e-mails.

In the past, the same expedient used to send me email to another address bound to the same PGP key: those e-mails display fine (in less than a second).

`*mu4e-log*` does not show anything abnormal.

## Versions of mu, mu4e/emacs, operating system etc.

mu: 1.0
Emacs 26.1
OS: GuixSD

**Comment by Ambrevar** [comment]
I think I found out the issue: it's because I had forgotten about the `keyserver-options auto-key-retrieve` option in my `gpg.cfg`.
The time it took to display the email matches the lookup time, which is absurdly long and I don't know why.

Conclusion: this might not be an mu4e issue, unless mu4e could override this option and prompt the user whether to auto-retrieve the key or not.

**Comment by djcb** [comment]
Okay, thanks for fixing that mystery!
