### ISSUE TITLE
Can't save attachment with non-ASCII characters

### ISSUE THREAD

**Issue by TeMPOraL** [djcb/mu#1294]
## Expected or desired behavior

I should be able to save attachments regardless of their filenames (as long as the filenames are correct, wrt. operating system requirements).

## Actual behavior

When I try to save an attachment, which name contains polish accented characters (actual example: `Przelew_Wzór_standard_20180731_15340052.PDF`), an error occurs and the attachment is not saved.

After executing "save" action on attachment, the following is shown in `*Messages*` buffer:

```
error in process filter: mu4e-error-handler: Error 1: error in quoting
error in process filter: Error 1: error in quoting
```
After retrying the same operation again, the following is shown:

```
error in process filter: mu4e-error-handler: Error 1: expected: '<alphanum>+:' (~/Downloads/Przelew_Wzór_standard_20180731_15340052.PDF)
error in process filter: Error 1: expected: '<alphanum>+:' (~/Downloads/Przelew_Wzór_standard_20180731_15340052.PDF)
```

## Steps to reproduce

Send yourself an e-mail with attachment containing diacritical characters, and try to save it from mu4e.

## Versions of mu, mu4e/emacs, operating system etc.
* Emacs - GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.25) of 2018-06-04
* mu4e - mu for emacs version 1.1.0 C

## Any other detail

N/A.

**Comment by djcb** [comment]
Hmm, this works fine for me. Do you happen to use a non-utf8 locale?

**Comment by TeMPOraL** [comment]
You mean system locale?

```
temporalgalactica~/t/kronospan@> locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```

I re-checked my workflow more carefully now; it seems that the process
of saving attachments confuses Ivy (it prompts me for a file name, but
if I type anything but the attachment name verbatim, it fails to
autocomplete, and after couple errors breaks out into normal Ivy-based
arbitrary path completion). If I try to press Enter without typing in
anything (with default `mu4e-attachment-dir` prefilled), it reports the
error I mentioned about quoting. If I then try to save it again, this
time giving it a proper file name, it echoes the error containing the
attachment name. If I try yet again, with a proper file name, it saves
successfully.

Bottomline, I think I mistakenly concluded this was caused by non-ASCII
characters; it's more likely caused by trying to save the attachment as
a directory, though it also seems to spill over to a subsequent attempt
to save it.

--
Jacek Złydach
http://jacek.zlydach.pl | http://temporal.pl

**Comment by djcb** [comment]
Do you have an example message where this happens? Or can we close this?
