### ISSUE TITLE
exited abnormally with code 19

### ISSUE THREAD

**Issue by damon-kwok** [djcb/mu#1295]
OS: windows10-Cygwin
offlineimap:7.2.1
emacs:26.1
mu:1.10 (git-master)
(mu4e)

Debugger entered--Lisp error: (error "Database empty; try indexing some messages")
  signal(error ("Database empty; try indexing some messages"))
  error("Database empty; try indexing some messages")
  mu4e~proc-sentinel(#<process  *mu4e-proc*> "exited abnormally with code 19\n")

PS:offlineimap is work, it's not empty

**Comment by djcb** [comment]
offlineimap synchronizes your maildir, but the error messages are about the mu database; . try `mu index` from the command-line (and with the right `--maildir` parameter, see the manpage).

**Comment by damon-kwok** [comment]
@djcb 
i use the same config on linux, it's work, but not work on cygwin

**Comment by djcb** [comment]
Did you try `mu index` from the command-line?

**Comment by djcb** [comment]
Okay, thanks!
