### ISSUE TITLE
Rename mu4e-meta.el.in to mu4e-meta.el

### ISSUE THREAD

**Issue by lawlist** [djcb/mu#1298]
A person on stackexchange recently asked for help installing just the `mu4e` Lisp libraries and it came to my attention that Emacs will throw an error when adding `(require 'mu4e)` to the `.emacs`/`init.el` file in that `mu4e-meta.el.in` needs to have the filename `mu4e-meta.el` in order for loading to occur successfully.  Many people, like myself, manually add Lisp libraries to the Emacs `load-path` and do not rely upon a particular build script to take care of everything.  Please consider renaming that file so that future users do not have this problem.

**Comment by lawlist** [comment]
It is not a very good design, in my opinion, to rely upon a build script to make the Lisp libraries fully functional.  A better design would be to have the lisp libraries query the `mu` executable, or whatever else is needed, when the Lisp libraries are loaded by Emacs.  Values can be set on a temporary basis whenever a user fires up `mu4e`.  For example, spelling in Emacs queries the `aspell` executable for its version number and stuff each time someone requires flyspell/ispell.

**Comment by djcb** [comment]
No lectures are needed; there's a hard dependency between mu versions and mu4e versions, so you must keep the two in sync. This is one way to enforce that; otherwise, I'd be swamped in bug reports because of incompatibilities.

**Comment by komali2** [comment]
Hello. I'm on Ubuntu 21.10 and installed `mu` by doing `sudo apt install maildur-utils`, as per instructions on djcb's website. Now, emacs can't find `mu4e-meta`. I see that I need to "run configure." I don't know how to do that. I see that there's a `configure.ac` file in this repo. I can't seem to run it, though. What do I do? I need to get a `mu4e-meta.el` so that emacs stops complaining.

**Comment by djcb** [comment]
Perhaps you didn't install the `mu4e` package?

**Comment by komali2** [comment]
Oh, right, so online various instructions said "install maildur-utils," and I assumed that since that didn't include mu4e, that I needed to grab the .el files elsewhere, not actually get a package or something or compile anything. But yes, the solution was to also on ubuntu `apt install mu4e`.
