### ISSUE TITLE
Unable to reply to a mail. Says error in process filter: Invalid function: mail-header-from

### ISSUE THREAD

**Issue by vinodhmj** [djcb/mu#1299]
## Expected or desired behavior

To be able to reply to a mail while hitting R in mu4e-view

## Actual behavior

error in process filter: Invalid function: mail-header-from

This happens always.

## Steps to reproduce
mu4e
ji
Click on a mail item
Hit R
error in process filter

## Versions of mu, mu4e/emacs, operating system etc.
mu 1.1.0, emacs 25.1.1
## Any other detail
Debian 9

**Comment by djcb** [comment]
That function is not used (drectly at least) in any of the mu4e source code. 

Are you perhaps using some third-party extension, or some specific setting/configuration?

**Comment by vinodhmj** [comment]
Not sure where that function is being called.
I need to investigate deeper to pinpoint the cause.

**Comment by vinodhmj** [comment]
Debugger entered--Lisp error: (invalid-function mail-header-from)
  mail-header-from([0 "RE: Are you sure emacs is not awesome?" "Nishad Nerurkar" "2018-11-26T13:20:57+0530" nil nil 0 0 ""])
  #[nil "\205

**Comment by djcb** [comment]
Hmm. Did you try with `emacs -Q` and a minimal mu4e configuration?

**Comment by vinodhmj** [comment]
Looks like it was an issue with the mail server. Sorry for the inconvenience. Closing the issue.
