### ISSUE TITLE
wrong-type-argument hash-table-p nil

### ISSUE THREAD

**Issue by seanfarley** [djcb/mu#1301]
## Expected or desired behavior

When visiting a link (stack trace attached) or opening an attachment there is an error given (instead of opening the link or attachment).

## Actual behavior

Visiting a link (by pressing 'g') or trying to save an attachment (by pressing 'e') give an error with `wrong-type-argument`.

## Steps to reproduce

Should be able to just try visiting a link or saving an attachment.

## Versions of mu, mu4e/emacs, operating system etc.

Using mu4e viewer (not gnus)
 
MacOS 10.13
mu 16619cb9a1e5235725d999d7c03d1e00a34276be

## Any other detail

Stack trace:
```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  hash-table-count(nil)
  mu4e~view-get-urls-num("URL to visit")
  mu4e~view-handle-single-url("URL to visit" #f(compiled-function (url) #<bytecode 0x633c2689>))
  mu4e~view-handle-urls("URL to visit" nil #f(compiled-function (url) #<bytecode 0x633c2689>))
  mu4e-view-go-to-url(nil)
  funcall-interactively(mu4e-view-go-to-url nil)
  call-interactively(mu4e-view-go-to-url nil nil)
  command-execute(mu4e-view-go-to-url)
```

**Comment by djcb** [comment]
Should be fixed now.

**Comment by seanfarley** [comment]
I appreciate your work on this (seriously!); thank you very much!

**Comment by jagrg** [comment]
I believe commit https://github.com/djcb/mu/commit/7dcb9087c2c9b2ec7e093c3f0b7363ada5bd4bb3 reintroduced the error. However, I'm only seeing it when trying to save attachments, either by pressing "e" or clicking with the mouse.

**Comment by jagrg** [comment]
Actually I meant commit https://github.com/djcb/mu/commit/abf02000ec845582a5e5aa8fec4cef350281f064. Also, both commands are throwing the error.

**Comment by ckelty** [comment]
Not sure if this is the same issue, but I get an error like this on any Attachment action (A) in message view:

Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  hash-table-count(nil)
  mu4e~view-get-attach-num... [details of the message]
 mu4e-view-attachment-action()
  funcall-interactively(mu4e-view-attachment-action)
  call-interactively(mu4e-view-attachment-action nil nil)
  command-execute(mu4e-view-attachment-action)

latest Mu master, emacs 26.1 on Mac OSX

**Comment by g4v4g4i** [comment]
I have the same problem as @ckelty 
(ver. 1.2.0, emacs 26.2 on arch linux)

**Comment by djcb** [comment]
Just fixed the (slighly different case) that @ckelty  & @g4v4g4i  mentioned.

**Comment by averter** [comment]
I think there is a third wave of this bug [here](https://github.com/djcb/mu/issues/1448)
