### ISSUE TITLE
Disable autofocus when selecting a message 

### ISSUE THREAD

**Issue by Nelyah** [djcb/mu#1308]
## Expected or desired behavior
When in headers calling `mu4e-headers-next`, the window with the selected message gets redrawn, but also gets focused (through  `mu4e-headers-view-message`). I would like it to not autofocus this message, simply show it.

## Actual behavior
As of now, `mu4e-headers-next` calls `mu4e-headers-view-message` and focuses the re-drawn window upon viewing a message. 

## Versions of mu, mu4e/emacs, operating system etc.
OS: Manjaro
Emacs: 26.1
mu: 1.0 
mu4e: 1.0 (retrieved from the manual)

## Any other detail
I tried adding  `(switch-to-buffer (mu4e-get-headers-buffer))` at the end of the `mu4e-headers-view-message` function, without success. I am still new to the whole emacs/lisp world, so I'm probably missing something here

I think a small hack would probably be very easy to set up (if anyone has a suggestion I'm open for it), but I think this would be nice to add as a feature.

**Comment by djcb** [comment]
This is not being  planned, sorry! Closing this.
