### ISSUE TITLE
Unknown option --help-index (or outdated man page)

### ISSUE THREAD

**Issue by dustinpaluch** [djcb/mu#1312]
## Expected or desired behavior

I expect `mu --help-index` to show help info for the index command, as described by the [man page](https://github.com/djcb/mu/blob/master/man/mu.1#L186).

## Actual behavior

I get `mu: Unknown option --help-index (0)` every time.

## Steps to reproduce

run `mu --help-index` from a shell

## Versions of mu, mu4e/emacs, operating system etc.
mu (mail indexer/searcher) version 1.0
OSX 10.13.6

**Comment by jschwab** [comment]
Yeah, something's wrong here.  I note that `mu index --help-index` does seem to work.

**Comment by dustinpaluch** [comment]
So it does.

**Comment by djcb** [comment]
The manpage was a bit outdated. You coul do e.g. `mu help index`.

**Comment by djcb** [comment]
Fixed that.
