### ISSUE TITLE
Unable to build mu without gmime-3.0

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1313]
## Expected or desired behavior

Build mu with gmime-2.6 as gmime-3.0 is not available as a package (linuxmint 18.3).

## Actual behavior
```
checking for GMIME... no
configure: error: Package requirements (gmime-3.0) were not met:

No package 'gmime-3.0' found
 ```

Introduced by commit 6134148

## Versions of mu, mu4e/emacs, operating system etc.

Building mu from git master branch, emacs-26 and linuxmint 18.3.

**Comment by Chris00** [comment]
If you want to build with gmime-2.6, you have to go back to an earlier revision than the HEAD.  The current development version builds with gmime ≥ 3.0.

**Comment by jschwab** [comment]
There was an announcement about this: https://groups.google.com/d/msg/mu-discuss/7UyrkR089mc/QkdhIHMQEAAJ

**Comment by Chris00** [comment]
> Of course it is what I am doing.
Then you should state what revision you are trying to compile.

**Comment by thierryvolpiatto** [comment]
Josiah Schwab <notifications@github.com> writes:

> There was an announcement about this: https://groups.google.com/d/msg/mu-discuss/7UyrkR089mc/QkdhIHMQEAAJ

Ok thanks.

-- 
Thierry

**Comment by djcb** [comment]
Yeah, we've moved to gmime 3.0;  sorry for the inconvenience... 

Building gmime should hopefully not be too hard; and perhaps it'll become part of Mint in the not too distant future.

**Comment by bigopensky** [comment]
A version dependency list could help really  ..sliding into a dependency hell to get some build tools to work
 gcc >= 8.0 
 python 3.8  ->  meson 
 pythohn      -> ninja
 xapian lib ahs to be compiled wit gcc-8
 gmime -> autoconf 2.71

..not patch able in Ubuntu 18.04
