### ISSUE TITLE
Dependencies for Fedora changed

### ISSUE THREAD

**Issue by nielsk** [djcb/mu#1315]
## Expected or desired behavior

The documentation on http://www.djcbsoftware.nl/code/mu/mu4e/Installation.html#Dependencies-for-Fedora says that "gmime-devel" is needed for compiling the software. That doesn't work anymore

## Actual behavior

You need "gmime30-devel" in Fedora 28

**Comment by djcb** [comment]
The documentation is for version 1.0. The dependency only changed in the development version (which has updated instructions).,
