### ISSUE TITLE
Previously archived parts of threads come back when thread is replied to

### ISSUE THREAD

**Issue by matthew-piziak** [djcb/mu#1317]
## Expected or desired behavior

When I have a thread of messages. I expect to be able to archive messages in the thread that I have already read, and have those not show up when I jump to maildir.

## Actual behavior

When I run `(mu4e~headers-jump-to-maildir "/Personal/INBOX")`, if there is a new message in a previously archived thread (archived in the sense that I have previously refiled previous messages to `/archive`) then all messages show up. The new message shows up as `Nu`, and the previous messages show up as `S`. For long-running threads this is actually quite inconvenient as it clogs up the header buffer.

If I remember correctly, this only happens in mu4e 1.0+, not mu4e 0.98.

## Steps to reproduce

Email yourself a few messages in a thread. Archive some of them. Run `mu4e~headers-jump-to-maildir` on the maildir with your thread. 

## Versions of mu, mu4e/emacs, operating system etc.

`mu (mail indexer/searcher) version 1.0`

`GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.28) of 2018-08-06`

**Comment by djcb** [comment]
This is likely due to the new default value for `mu4e-headers-include-related`, it's `t` now. So, the old behavior should return by setting it to `nil`. Does that work?

**Comment by matthew-piziak** [comment]
I think that's working. Thank you!
