### ISSUE TITLE
Show the encrypted subject from Enigmail

### ISSUE THREAD

**Issue by ArneBab** [djcb/mu#1321]
The new Enigmail replaces the subject line of emails with "Encrypted message" (or similar) and adds a header within the encrypted part with the real subject. It would be great if this could be extracted by mu so I could find encrypted mails by subject.

The source of an example encrypted message part looks like this (personal data replaced by …):

```Subject: =?iso-8859-1?q?Verschl=FCsselte?= Nachricht
From: Arne Babenhauserheide <…>
To: … <…>
Content-Type: multipart/mixed; boundary="WV0cqtUlEPoFt2RrE5JYYsBpu8xQVrIHW";
 protected-headers="v1"
From: Arne Babenhauserheide <…>
To: … <…>
Message-ID: <3c87f3fa-144f-f11c-c758-0e22baee9006@…>
Subject: Re: Vorlesungsunterlagen zu Verteilten Systemen
In-Reply-To: <…>

--WV0cqtUlEPoFt2RrE5JYYsBpu8xQVrIHW
Content-Type: multipart/mixed;
 boundary="------------1E0C660260B32E117EAD9FAF"
Content-Language: de-DE

This is a multi-part message in MIME format.
--------------1E0C660260B32E117EAD9FAF
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

…
```

The actual subject is the second subject header.

**Comment by djcb** [comment]
Ah, interesting... I guess this would be something for `gmime` though. Perhaps you can ask there? 

In any case, `mu` doesn't decrypt during indexing, so guess this will be hard to do.

**Comment by averter** [comment]
@ArneBab Did you find any workaround for this? I would also like to be able to have this integrated in mu4e.
