### ISSUE TITLE
msys2 compile error

### ISSUE THREAD

**Issue by damon-kwok** [djcb/mu#1323]
## Expected or desired behavior

Successfully compiled on the msys2 platform

## Actual behavior

configure: error: *** missing required function timegm

## Steps to reproduce
````
cd $HOME/.emacs.d/libs/mu-git/
./autogen.sh --prefix=$HOME/.local
make install
````
## Versions of mu, mu4e/emacs, operating system etc.
OS: Msys2
Emacs:26.1
mu4e:git-master (2018-0929)

## Any other detail
<details>
autoreconf: Entering directory `.'

autoreconf: configure.ac: not using Gettext

autoreconf: running: aclocal --force -I m4

autoreconf: configure.ac: tracing

autoreconf: running: libtoolize --copy --force

libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.

libtoolize: copying file 'build-aux/ltmain.sh'

libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.

libtoolize: copying file 'm4/libtool.m4'

libtoolize: copying file 'm4/ltoptions.m4'

libtoolize: copying file 'm4/ltsugar.m4'

libtoolize: copying file 'm4/ltversion.m4'

libtoolize: copying file 'm4/lt~obsolete.m4'

autoreconf: running: /usr/bin/autoconf --force

autoreconf: running: /usr/bin/autoheader --force

autoreconf: running: automake --add-missing --copy --force-missing

configure.ac:41: installing 'build-aux/compile'

configure.ac:30: installing 'build-aux/missing'

contrib/Makefile.am: installing 'build-aux/depcomp'

autoreconf: Leaving directory `.'

# Configure with parameters --prefix=/home/damon/.local

configure: loading site script /mingw64/etc/config.site

configure: creating cache config.cache

checking for a BSD-compatible install... /usr/bin/install -c

checking whether build environment is sane... yes

checking for a thread-safe mkdir -p... /usr/bin/mkdir -p

checking for gawk... gawk

checking whether make sets $(MAKE)... yes

checking whether make supports nested variables... yes

checking whether UID '197609' is supported by ustar format... yes

checking whether GID '197121' is supported by ustar format... yes

checking how to create a ustar tar archive... gnutar

checking whether make supports nested variables... (cached) yes

checking for g++... g++

checking whether the C++ compiler works... yes

checking for C++ compiler default output file name... a.exe

checking for suffix of executables... .exe

checking whether we are cross compiling... no

checking for suffix of object files... o

checking whether we are using the GNU C++ compiler... yes

checking whether g++ accepts -g... yes

checking whether make supports the include directive... yes (GNU style)

checking dependency style of g++... gcc3

checking for gcc... gcc

checking whether we are using the GNU C compiler... yes

checking whether gcc accepts -g... yes

checking for gcc option to accept ISO C89... none needed

checking whether gcc understands -c and -o together... yes

checking dependency style of gcc... gcc3

checking for gcc option to accept ISO C99... none needed

checking for gcc option to accept ISO Standard C... (cached) none needed

checking for gcc option to accept ISO C99... (cached) none needed

checking how to run the C preprocessor... gcc -E

checking for grep that handles long lines and -e... /usr/bin/grep

checking for egrep... /usr/bin/grep -E

checking for ANSI C header files... yes

checking whether g++ supports C++14 features by default... yes

checking for valgrind... no

checking build system type... x86_64-w64-mingw32

checking host system type... x86_64-w64-mingw32

checking how to print strings... printf

checking for a sed that does not truncate output... /usr/bin/sed

checking for fgrep... /usr/bin/grep -F

checking for ld used by gcc... C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe

checking if the linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) is GNU ld... yes

checking for BSD- or MS-compatible name lister (nm)... /mingw64/bin/nm -B

checking the name lister (/mingw64/bin/nm -B) interface... BSD nm

checking whether ln -s works... no, using cp -pR

checking the maximum length of command line arguments... 8192

checking how to convert x86_64-w64-mingw32 file names to x86_64-w64-mingw32 format... func_convert_file_msys_to_w32

checking how to convert x86_64-w64-mingw32 file names to toolchain format... func_convert_file_msys_to_w32

checking for C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe option to reload object files... -r
checking for objdump... objdump

checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL

checking for dlltool... dlltool

checking how to associate runtime and link libraries... func_cygming_dll_for_implib

checking for ar... ar

checking for archiver @FILE support... @

checking for strip... strip

checking for ranlib... ranlib

checking command to parse /mingw64/bin/nm -B output from gcc object... ok

checking for sysroot... no

checking for a working dd... /usr/bin/dd

checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1

checking for mt... no

checking if : is a manifest tool... no

checking for sys/types.h... yes

checking for sys/stat.h... yes

checking for stdlib.h... yes

checking for string.h... yes

checking for memory.h... yes

checking for strings.h... yes

checking for inttypes.h... yes

checking for stdint.h... yes

checking for unistd.h... yes

checking for dlfcn.h... no

checking for objdir... .libs

checking if gcc supports -fno-rtti -fno-exceptions... no

checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC

checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes

checking if gcc static flag -static works... yes

checking if gcc supports -c -o file.o... yes

checking if gcc supports -c -o file.o... (cached) yes

checking whether the gcc linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes

checking whether -lc should be explicitly linked in... yes

checking dynamic linker characteristics... Win32 ld.exe

checking how to hardcode library paths into programs... immediate

checking whether stripping libraries is possible... yes

checking if libtool supports shared libraries... yes

checking whether to build shared libraries... yes

checking whether to build static libraries... yes

checking how to run the C++ preprocessor... g++ -E

checking for ld used by g++... C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe

checking if the linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) is GNU ld... yes

checking whether the g++ linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes

checking for g++ option to produce PIC... -DDLL_EXPORT -DPIC

checking if g++ PIC flag -DDLL_EXPORT -DPIC works... yes

checking if g++ static flag -static works... yes

checking if g++ supports -c -o file.o... yes

checking if g++ supports -c -o file.o... (cached) yes

checking whether the g++ linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes

checking dynamic linker characteristics... Win32 ld.exe

checking how to hardcode library paths into programs... immediate

checking for gawk... (cached) gawk

checking for sort... sort

checking wordexp.h usability... no

checking wordexp.h presence... no

checking for wordexp.h... no

checking for special C compiler options needed for large files... no

checking for _FILE_OFFSET_BITS value needed for large files... 64

checking for makeinfo... yes

checking for emacs... emacs

checking where .elc files should go... ${datadir}/emacs/site-lisp

checking for dirent.h that defines DIR... yes

checking for library containing opendir... none required

checking for struct dirent.d_type... no

checking for struct dirent.d_ino... yes

checking for memset... yes

checking for memcpy... yes

checking for realpath... no

checking for setlocale... yes

checking for strerror... yes

checking for getpass... no

checking for setsid... no

checking for vasprintf... yes

checking for strptime... no

checking for timegm... no

configure: error: *** missing required function timegm
</details>

**Comment by panjie** [comment]
Seems mu compilation on mays/mingw is not supported yet. Please use cygwin to compile it.

**Comment by djcb** [comment]
Indeed... sadly, msys2 doesn't seem to have that function, so I'd recommend @panjie 's advise.

**Comment by juanjosegarciaripoll** [comment]
timegm() is not used at all in the code. Could you please remove this check from configure.ac ?

**Comment by damon-kwok** [comment]
@juanjosegarciaripoll  use msys2, not mingw.
See: https://github.com/msys2-unofficial/MSYS2-packages

**Comment by juanjosegarciaripoll** [comment]
Thanks for the hint and for the port. I tried it and it mostly works. Unfortunately the msys2 port does not work nicely with non-msys emacs and is broken because it tries to use file names with ':' in it.

Regarding the second issue, this pull request https://github.com/djcb/mu/pull/1808 is needed to allow mu4e using other Maildir info separators that are compatible with Windows' FAT and NTFS mbsync and other Maildir synchronizers automatically detect and use this file name format. Without this fix, mu4e breaks when trying to save sent files or even drafts.

I've also had to add some advices on mu4e to work with non-msys Emacs, reinterpreting paths: it transforms path into MSYS2 format when sending messages to 'mu' and transforms them back to Windows format when pulling information, such as maildir directories. It more or less seems to work now
````
  (defun jjgr-msys-to-windows-path (path)
    (replace-regexp-in-string "^/\\([c-e]\\)/" "\\1:/" path))

  (defun jjgr-mu4e-input-filter (args)
    (let* ((mu4e-args (car args))
           (mu4e-command (first mu4e-args))
           (mu4e-options (cdr mu4e-args)))
      (dolist (key '(:path :maildir))
        (let ((value (plist-get mu4e-options key)))
          (when (and (stringp value)
                     (> (length value) 2))
            (setq value (replace-regexp-in-string
                         "^\\([c-z]\\):[/\\]" "/\\1/"
                         value)
                  mu4e-options (plist-put mu4e-options key value)))))
      (list (cons mu4e-command mu4e-options))))

  (advice-add 'mu4e~call-mu :filter-args 'jjgr-mu4e-input-filter)
  (advice-add 'mu4e-root-maildir :filter-return 'jjgr-msys-to-windows-path)
  (advice-add 'mu4e-database-path :filter-return 'jjgr-msys-to-windows-path)
````

**Comment by damon-kwok** [comment]
Nice work!
