### ISSUE TITLE
functions on mu4e-index-updated-hook not being called on new email

### ISSUE THREAD

**Issue by shackra** [djcb/mu#1324]
## Expected or desired behavior

functions on `mu4e-index-updated-hook` should be called after running any command related to the database being updated.

## Actual behavior

I checked functions on mu4e source code and nothing seems to run the functions in `mu4e-index-updated-hook`, new email --as fetch by mbsync and then indexed by `mu4e-update-index`-- triggers nothing.

## Steps to reproduce

Write a lambda and inserted it into the hook: `(add-hook 'mu4e-index-updated-hook (lambda () (message "Mu4e was called")))` send yourself an email and wait to see if anything is printed at the \*Message\* buffer.

## Versions of mu, mu4e/emacs, operating system etc.

- mu4e - mu for emacs version 1.0
- GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05
- Arch Linux

## Any other detail

This was not present previous to version 1.0 of mu4e, but I could be wrong. This behavior was reported also at mu4e-alert https://github.com/iqbalansari/mu4e-alert/issues/25

**Comment by alandmoore** [comment]
I encountered this when I enabled bbdb contacts completion.  By any chance do you have this call in your config:

     (setq mu4e-compose-complete-addresses nil)

For some reason [the code checks something contacts-related](https://github.com/djcb/mu/blob/5ccd2617717599cdd2bc59f52d60cde85a417aeb/mu4e/mu4e-utils.el#L668) before running the hook.  I don't know the implications of this, but I found by defaulting my contacts auto-completion settings, the hook started running again.

**Comment by shackra** [comment]
Nope, my config is clean with no such statement!

**Comment by brabalan** [comment]
I have the same issue, as I use bbdb for contact completion (so I set `mu4e-compose-complete-address` to `nil`).

**Comment by djcb** [comment]
I've pushed a change for this, which should help at least for the issue related to `mu4e-compose-complete-addresses`. Does this fix the problem for you, @shackra, @alandmoore ?

**Comment by shackra** [comment]
El domingo 04 de noviembre del 2018 a las 1249 horas, Dirk-Jan C. Binnema escribió:

> I've pushed a change for this, which should help at least for the issue related to mu4e-compose-complete-addresses. Does this fix the problem for you, @shackra,
> @alandmoore ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Let me check and I'll be back with you in a couple of hours!
--
👋 Pax et bonum.
Jorge Javier Araya Navarro
http://www.esavara.cr

**Comment by shackra** [comment]
yes, 69ed3498bb840f734c11137ba888f49ebb190008 fixes this issue

**Comment by shackra** [comment]
waiting for @alandmoore feedback

**Comment by alandmoore** [comment]
Sorry for the delay; I'm unable at the moment to reproduce the conditions in which I had the problem originally, so I'm afraid I can't say for certain if my issue was fixed or not.

**Comment by shackra** [comment]
I will then close it for now, if you can reproduce the issue with the changes made by @djcb  please comment and I'll reopen it.
