### ISSUE TITLE
Sorting on :size header

### ISSUE THREAD

**Issue by bindernet** [djcb/mu#1325]
## Expected or desired behavior

Hi, new user, enjoying it so far
I added a :size header to mu4e-headers-fields, & appears OK 
Sorting on size header should work...

## Actual behavior
When I went to sort by this header it's somewhat haphazard, (in some cases alphabetically)
I also have an RTL (bidi) issue in the header which may be confounding, or I can open another issue if helpful. 

For bug-reports, if applicable, include error messages, emacs stack
traces etc. Try to be as specific as possible - when do you see this
happening? Does it happen always?  Sometimes? How often?

## Steps to reproduce
(setq mu4e-headers-fields '((:date . 12)
 (:flags . 6)
 (:mailing-list . 10)
 (:from . 22)
 (:size . 6)
 (:subject))
)

Click on size column to sort.

## Versions of mu, mu4e/emacs, operating system etc.
Arch Linux
mu --version
1.0
emacs 26.1

**Comment by djcb** [comment]
Thanks -- yeah, I can reproduce. This used to work. I'll take a look.

**Comment by djcb** [comment]
Ah, no. Got confused myself! The thing is, when you use threads in your mail, those will come first,  ie. size sorting will be per thread (level). You can toggle threading with `P`. Does that work for you?

**Comment by bindernet** [comment]
That was it. Thanks.
I was confused by the threading + a right-to-left language / bidi issue I'm also seeing, moving the columns around.
I'll open another issue for that ;-)
