### ISSUE TITLE
RFE: Multi-character bookmarks

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#1327]
From: https://groups.google.com/forum/#!topic/mu-discuss/y9E08B9TuWY

Practical reason: having more bookmarks:

<< As I add additional saved-search bookmarks to my mu4e config (normally for frequent correspondents and mailing list traffic), I have run out of mnemonic single-character shortcuts to associate with the queries. It would be nice if mu4e would accept a multi-character string for bookmark selection, e.g. "bmd" to select "bookmark, mu-discuss" >>

Second use case: bookmark grouping

<< I don't have many bookmarks, but I have some very similar ones that I would like to group in this way. For example, I have four variants of "unread" queries that select views in increasing level of broadness. I'd love to have that as "bu[1234]" for clarity. >>

**Comment by djcb** [comment]
I would recommend a package like `hydra` for this... but mu4e could use an example of setting that up for this.

**Comment by djcb** [comment]
```
(defhydra my-mu4e-bookmarks-work (:color blue)
  "work bookmarks"
  ("b" (mu4e-headers-search "banana AND maildir:/work") "banana")
  ("u" (mu4e-headers-search "flag:unread AND maildir:/work")   "unread"))

(defhydra my-mu4e-bookmarks-personal (:color blue)
  "personal bookmarks"
  ("c" (mu4e-headers-search "capybara AND maildir:/personal") "capybara")
  ("u" (mu4e-headers-search "flag:unread AND maildir:/personal")  "unread"))

(defhydra my-mu4e-bookmarks (:color blue)
  "mu4e bookmarks"
  ("p" (my-mu4e-bookmarks-personal/body) "Personal")
  ("w" (my-mu4e-bookmarks-work/body) "Work"))
```

Now, you can bind a convenient key to `my-mu4e-bookmarks/body`.

**Comment by djcb** [comment]
I've added some notes about this to the mu4e docs.
