### ISSUE TITLE
unable to enter password for offlineimap when updating email

### ISSUE THREAD

**Issue by tdhock** [djcb/mu#1329]
Hey @djcb I'm having the issue described here https://emacs.stackexchange.com/questions/45190/cant-enter-password-when-retrieving-mail-with-mu4e

I use offlineimap but I don't want to put my password in plain text in the config file.

Using offlineimap on the command line is fine... it prompts me for my imap password, I enter it, it downloads the new mail.

## Expected or desired behavior

When I press U to update email, I expected to be able to enter my password just as on the command line.

## Actual behavior

I press U, and I get a buffer *mu4e-update* which says:
```
Account sync NAU:
 *** Processing account NAU
 Establishing connection to iris.nau.edu:993 (Remote)
Enter password for account 'Remote': 
```
but I can't enter my password in that buffer. When I try, I get the error "p is undefined" in the minibuffer.

This is always happening.

## Steps to reproduce

Use offlineimap to get mail with no password in the config file.

## Versions of mu, mu4e/emacs, operating system etc.

I'm using the standard versions of mu4e/emacs on Ubuntu 18.04

```
tdhock@recycled:~/tdhock.github.io(master)$ emacs --version
GNU Emacs 25.2.2
Copyright (C) 2017 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
tdhock@recycled:~/tdhock.github.io(master)$ aptitude show mu4e
Package: mu4e                            
Version: 0.9.18-2build3
State: installed
Automatically installed: no
Priority: optional
Section: universe/lisp
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Uncompressed Size: 499 k
Depends: maildir-utils (>= 0.9.18-2build3), maildir-utils (< 0.9.18-2build3.1~),
         emacsen-common (>= 2.0.8), dpkg (>= 1.15.4) | install-info
Conflicts: maildir-utils (< 0.9.8.4)
Replaces: maildir-utils (< 0.9.8.4)
Description: e-mail client for Emacs based on mu (maildir-utils)
 mu4e (mu-for-emacs) is an e-mail client for GNU-Emacs version 23 and later,
 built on top of the mu e-mail search engine. mu4e is optimized for fast
 handling of large amounts of e-mail.
Homepage: http://www.djcbsoftware.nl/code/mu/


tdhock@recycled:~/tdhock.github.io(master)$ 
```

## OTher info

It seems that many people are having this issue, and they are resorting to hacks like encrypting their offlineimap config files using some other program (GPG) that will let you interactively enter a password.
https://unix.stackexchange.com/questions/44214/encrypt-offlineimap-password/48355#48355

To me that seems un-necessarily complicated -- shouldn't it be possible to simply enter my imap password interactively in mu4e when I press U?

Thanks

**Comment by djcb** [comment]
Running an interactive shell command in emacs isn't that simple... but you can play with`mu4e~get-mail-password-regexp` and see if you can find something that matches what you need.

**Comment by tdhock** [comment]
that solved the problem, thanks!

however, I think there is still an issue with the documentation -- I would suggest adding something about that variable to the intro doc pages. For example on http://www.djcbsoftware.nl/code/mu/mu4e/Gmail-configuration.html#Gmail-configuration it would be nice to have some discussion of "if you do not want to put your password in your config file, make sure to edit the `mu4e~get-mail-password-regexp` variable so mu4e knows when to prompt you for your password"

Thanks for the timely response.
