### ISSUE TITLE
Use ido/helm for contact completion

### ISSUE THREAD

**Issue by tobiasBora** [djcb/mu#1330]
## Expected or desired behavior

In the old mu4e release, I created my own function to complete the contacts using Ido fuzzy matching (and it was really practical). However, it seems that in the last mu4e version, the way contacts are handled changed. And I'm not sure yet to fully understand the new code, so you may be able to help me: is it possible to use helm/ido in order to complete the contact list of mu4e?

Thank you!

## Actual behavior

Pressing TAB gives a list of contacts, but it's not possible to use Ido/helm fuzzy matching to select them.

## Versions of mu, mu4e/emacs, operating system etc.

Mu4e 1.0-6, debian unstable

**Comment by djcb** [comment]
When pressing `<tab>`, emacs uses `completion-at-point-functions` to determine the completion using `mu4e~compose-complete-contact`.

The emacs default is to pop up a buffer, but if you use e.g. `helm-mode` or `ivy-mode`, it uses those to list candidates instead. Not sure if `ido` supports that too, but you can try.
