### ISSUE TITLE
[Feature Request] Support completing mu4e searching flags in minibuffer

### ISSUE THREAD

**Issue by stardiviner** [djcb/mu#1332]
When I press `[S]` to modify the search patterns, I hope mu4e can provide the searching flags like `from:` `to:` `flag:` etc. So user can interactive input from selecting. I don't know mu4e provide which flags for searching. With this completion mechanism will be helpful.

**Comment by djcb** [comment]
That might be useful, but is a _lot_ of work, and it's not planned. So I'd recommend reading the documentation instead.

**Comment by stardiviner** [comment]
I want to take a try, can you tell me some related API function names so that I can have a look to try? I might consider Emacs built-in `completion-at-point-functions` support in minibuffer.

**Comment by djcb** [comment]
Yeah, that would be the right way, but that's not the hardest part.

However, to do it correctly, you'd need to parse the query just like `mu` does it, taking into account escaping etc. It's hard to to get right. Not to discourage you of course :)
