### ISSUE TITLE
All messages from a thread shown in INBOX

### ISSUE THREAD

**Issue by rdiaz02** [djcb/mu#1333]
## Expected or desired behavior

1. Messages from a thread have been moved, using `m`, somewhere (e.g., Y/something)

2. A new message (from the same thread) is received in X/INBOX.

3. Only this new message is shown in the INBOX (though we know it belongs to some thread, because of the `\`, shown if we toggle showing threads, via `P`)

## Actual behavior

(Instead of 3, above, we see)
3'. All the  messages from the thread show up in X/INBOX.

Now, if one moves the newly received message to Y/something, and runs  `mu4e-update-mail-and-index`, then the complete thread is no longer  shown in X/INBOX.

## Steps to reproduce

- Go to any directory where a thread is stored (/something)
- Move (`m`) the last message to some /INBOX
- All of the thread shows in /INBOX  (but note that the thread is also shown in /something)
- Mark the last message to be moved to the directory where it was stored and excute that mark (`x`)
- Update (`C-S-u`)
- All are now again in the directory where they came from (/something)

## Versions of mu, mu4e/emacs, operating system etc.
The new behavior I see in v. 1.0-6 in Debian. The expected behavior I have seen at least until version 0.9.18-2 (Debian), included.

## Any other detail
I find this disconcerting (in particular for long threads). Is it possible for a user to use the old behavior?

**Comment by jschwab** [comment]
The default for mu4e-headers-include-related changed in 1.0.

You can check if this setting is the cause of your issue by toggling
this option with W and then customize to your desired value.

**Comment by rdiaz02** [comment]
Thanks a lot! Yes, that gives me the desired behavior, and the toggling on-the-fly is really nice.

(Sorry to have missed it; I read section 4.4 of the manual, https://www.djcbsoftware.nl/code/mu/mu4e/Sorting-and-threading.html#Sorting-and-threading, googled for "thread", but missed reading the NEWS or section 4.2 of the manual, https://www.djcbsoftware.nl/code/mu/mu4e/Keybindings.html#Keybindings).

I am closing this.
