### ISSUE TITLE
mu4e-view-mode-hooks have no message text available

### ISSUE THREAD

**Issue by seanfarley** [djcb/mu#1343]
## Expected or desired behavior

Desired behavior is to have the message body available when hooks are run. The reasoning is given in d5a4ba06.

## Actual behavior

When the `mu4e-view-mode-hook`s are run, there is no message text in the buffer yet.

## Any other detail

The culprit is 700e5e7 because it moves the `(insert (mu4e-view-message-text msg))` to after `(mu4e-view-mode)`, though the fix is not as simple because many maps and buffer-local variables are set in a fragile way which seems like more discussion is needed before trying to fix this.

**Comment by djcb** [comment]
I've pushed a change that should help -- does it work for you?

**Comment by seanfarley** [comment]
Yeah! That fixed it! Thanks so much 😄 As promised months ago, here is my attempt at coloring patches:

https://github.com/seanfarley/mu4e-patch
