### ISSUE TITLE
reply to sender with mu4e when message is received through a mailing-list

### ISSUE THREAD

**Issue by maxdantoni** [djcb/mu#1344]
## Expected or desired behavior

 When I receive an email in mu4e, with headers

     From: someone@etc
     To: mailing-list@etc

and I try to reply (by pressing R), mu4e gives me the option between "all" and "sender only".
I expect that, when I select sender only, the outcoming email is addressed To: someone@etc  

## Actual behavior

Whatever the option I choose (i.e. both with sender only and with all), the outgoing message I am composing has:

    To: mailing-list@etc

## Steps to reproduce

I attach a raw message that gives the described behavior
[email.txt](https://github.com/djcb/mu/files/2669439/email.txt)

## Versions of mu, mu4e/emacs, operating system etc.

mu4e - mu for emacs version 1.1.0 C
emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
ubuntu linux 18.04

## Any other detail

In case this is relevant, mu4e-user-mail-address-list is set with my email addresses

**Comment by brandoninvergo** [comment]
This bug is a result of discussion in #1278, commit e321d15.

**Comment by djcb** [comment]
This has been changed, mu4e now has special handling for replying to list/sender/all for mailing-list messages. Closing this, feel free to leave comments in issue #1491. Thanks!
