### ISSUE TITLE
set buffer-modified-p to nil when creating draft?

### ISSUE THREAD

**Issue by titaniumbones** [djcb/mu#1345]
## Expected or desired behavior

I often start message drafts and then realize immediately I should be addressing them to someone else, or replying to a different message, etc.  I do this often enough that the kill-buffer confirmation message is a bit of a drag. Is there a good place/hook to invoke `set-buffer-modified-p nil` on draft creation? 

## Actual behavior

draft buffer is marked as modified before user has starts to make modifications.

## Steps to reproduce

For bug-reports, please describe in as much details as possible how
one can reproduce the problem*.

## Versions of mu, mu4e/emacs, operating system etc.

mu 7c63fe65eb4e08b66a5dd0e345d4e5d9742c14d5 with a minor modification (see end of this message)

emacs git rom 2018-11-08
## Any other detail
Not a bug! a feature/clarification request.

here's the minor modification I made to accomodate some other stuff I was working on: 

``` diff
 don't hardocde sent handler in mu4e-compose

Also give a reasonable default for `mu4e-sent-func` in mu43-vars.el.
---
 mu4e/mu4e-compose.el | 2 +-
 mu4e/mu4e-vars.el    | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/mu4e/mu4e-compose.el b/mu4e/mu4e-compose.el
index 7fea7250..8dcc5b65 100644
--- a/mu4e/mu4e-compose.el
+++ b/mu4e/mu4e-compose.el
@@ -523,7 +523,7 @@ buffers; lets remap its faces so it uses the ones for mu4e."
     ;; when the message has been sent.
     (add-hook 'message-sent-hook
       (lambda () ;;  mu4e~compose-mark-after-sending
-	(setq mu4e-sent-func 'mu4e-sent-handler)
+	;;(setq mu4e-sent-func 'mu4e-sent-handler)
 	(mu4e~proc-sent (buffer-file-name) mu4e~draft-drafts-folder)) nil t))
   ;; mark these two hooks as permanent-local, so they'll survive mode-changes
   ;;  (put 'mu4e~compose-save-before-sending 'permanent-local-hook t)
diff --git a/mu4e/mu4e-vars.el b/mu4e/mu4e-vars.el
index 08726b7d..4a220e31 100644
--- a/mu4e/mu4e-vars.el
+++ b/mu4e/mu4e-vars.el
@@ -924,7 +924,7 @@ See `mu4e~proc-filter' for the format.")
 server process, when some message has been deleted. The function
 is passed the docid of the removed message.")
 
-(defvar mu4e-sent-func  'mu4e~default-handler
+(defvar mu4e-sent-func  'mu4e-sent-handler
   "A function called for each :sent sexp returned from the server
 process, when some message has been sent. The function is passed
 the docid and the draft-path of the sent message.")
-- 
```

**Comment by djcb** [comment]
Yeah, starting with unmodified message is the intended behavior, seems it got lost at some point... but I think I've fixed it (git). Can you try?

**Comment by titaniumbones** [comment]
just did it, and I'm pretty sure it's fixed. Will give it a stress test later on, but closing for now since I'm pretty sure it's solved. Thanks!
