### ISSUE TITLE
Can I use mu4e to view saved .eml files?

### ISSUE THREAD

**Issue by Alexander-Miller** [djcb/mu#1346]
I am currently trying to save some particularly important emails alongside the rest of my documents and org files. Thunderbird downloads them as .eml files, now I'd just like to use mu4e to display them without them being inside my indexed maildir.

I've looked around the codebase and got close by sending mu a command like `cmd:view path:%s`, but  `mu4e~view-mark-as-read-maybe` returns nil, so `mu4e-view` never even tries to display the message and I don't think digging even deeper is the right way to go.

So what am I missing, or is there a better alternative?

(Using mu 1.0 and emacs 26.1)

**Comment by djcb** [comment]
`mu4e` works with indexed messages, so you'll need to index them messages to see them. You can of course use `mu view <path>` from the command-line.

**Comment by Alexander-Miller** [comment]
> You can of course use mu view <path> from the command-line.

Yes, I found that option too, but what I'm after is getting that output into emacs with all of mu4e's bells and whistles - downloading attachments or viewing the email in the browser etc.

> mu4e works with indexed messages, so you'll need to index them messages to see them.

Tried that as well. Seemed to work for a hard copy, but symlinking did not. I take it mu does not like symlinks?

**Comment by djcb** [comment]
Indeed - mu avoids symlinks, as we got into all kinds of trouble with those. Haven't re-checked for years though...

You could try a bind mount, depending on your system.

**Comment by Alexander-Miller** [comment]
A hard link would do as well. Of course I'm also using encfs, meaning I can do neither, so I'll resort to a plain copy for now.
Either way I have what I need now.
