### ISSUE TITLE
Update date when flushing quueued mail

### ISSUE THREAD

**Issue by jschaeff** [djcb/mu#1347]
## Expected or desired behavior
When I flush the queued mails, I'd like the sent date to be the real time of mail sending and not the time of queuing. 

## Actual behavior
Compose and queue an email. Send it later, the mail will have the date when it was queued, not sent.
Setting mu4e-compose-auto-include-date to nil does not change this behaviour.

## Versions of mu, mu4e/emacs, operating system etc.
mu v1.0
emacs 26.1

**Comment by djcb** [comment]
Unfortunately, the queuing facilty is beyond mu4e's control, and it doesn't allow this.
