### ISSUE TITLE
Attachmet not recognized

### ISSUE THREAD

**Issue by manufactory** [djcb/mu#1348]
Hi,

I was searching for a specific mail with attachment, but could not find it. When I finally found it by manually searching for it I realized that mu does not detect the attachment in the headers view, even though it does detect it in the message view (see screenshot). I reproduced it with a minimal-test mail (attached). 

I use mu 1.0 on Arch Linux, Emacs 26.1

![screenshot](https://user-images.githubusercontent.com/4078266/50029057-007a8c80-fff2-11e8-9cdd-7e2b257c8e23.png)

[testmail.txt](https://github.com/djcb/mu/files/2681779/testmail.txt)

**Comment by manufactory** [comment]
Hi,

I was searching for a specific mail with attachment, but could not find it. When I finally found it by manually searching for it I realized that mu does not detect its attachment, at least not in the headers view (see screenshot)
![screenshot](https://user-images.githubusercontent.com/4078266/50029057-007a8c80-fff2-11e8-9cdd-7e2b257c8e23.png)
. I reproduced it with a minimal-test mail (attached). 

I use mu 1.0 on Arch Linux, Emacs 26.1
[testmail.txt](https://github.com/djcb/mu/files/2681779/testmail.txt)

**Comment by manufactory** [comment]
I did a --rebuild (still using mu 1.0), however the attachment is still not recognized.

Here is the test mail I'm using
```
User-agent: mu4e 1.0; emacs 26.1
Date: Fri, 7 Dec 2018 21:44:06 +0100
Content-Type: multipart/mixed; boundary="=-=-="
From: you@example.com
To: me@example.com
Subject: Test

Foo bar baz

--=-=-=
Content-Type: text/x-python
Content-Disposition: inline; filename="foobarbaz.py"

#!/usr/bin/env python

print("Hello Elisp")

--=-=-=
```

**Comment by djcb** [comment]
The thing is, the python thing is marked as "inline" (ie., not an attachment). In the message view we allow it as a pseudo-attachment, so you can save it. But in general "text/*" things that are also marked as "inline" are not considered attachments. I think overall  the experience would be worse if we did.

**Comment by djcb** [comment]
Actually, as part of #1380, the behavior is a bit different now, and now shows up as an attachment.
