### ISSUE TITLE
Duplicate messages in Gmail messes up thread view

### ISSUE THREAD

**Issue by sdycjsj** [djcb/mu#1349]
(Sorry for accidentally hitting Enter without finishing editing.)

I am using mu4e built from master branch 2 or 3 days ago on emacs 26, with a Gmail account.
Gmail folders: inbox, [gmail]/sent mail, [gmail]/all mail, [gmail]/starred are synced using mbsync.
I like the way mu handles emails, and thanks for this wonderful tool. I just have some problems with the thread view.

The thread view of Inbox with related-messages turned on and skip-duplicated turned OFF is:

![snipaste_2018-12-21_20-58-32](https://user-images.githubusercontent.com/8192780/50344355-9ae44e00-0565-11e9-9b67-dad1b61b2ed7.jpg)

I understand that there are duplicated emails because I sync the "All Mail" folder.
The issue is that  (1). Duplicated messages (messages with the same name in the pic above) are recognized as parent-child.
Threads are complete though. By "complete", I mean no open ends or disconnected entries (see below).

The thread view of Inbox with related-messages turned on and skip-duplicated turned ON is:

![snipaste_2018-12-21_20-59-32](https://user-images.githubusercontent.com/8192780/50344377-b0597800-0565-11e9-811c-0fe2d3f01a63.jpg)

This shows another issue (2). thread looks incomplete when skip-duplicates turned on.
 One can see that the upper thread has open ends.
The lower thread appears as it is child of some message above, which in fact has nothing to do with it.

**Comment by lockywolf** [comment]
I have the same problem.
I do synchronise the All Mail tag from GMail (for backup and completeness), and the following is observed:

I have a mailing list from Qatar Airways. 
When messages are unread, they are shown as being a response to a thread:
![image](https://user-images.githubusercontent.com/2077025/97423748-addabd00-194a-11eb-84b9-68e4eafa6b77.png)

When I read a message, it changes the colour in the headers and obtains the "seen" flag, but is still displayed as being a thread member. When I refresh the headers using the G key, it loses the "thread membership" status.

Seems to be a similar problem.

**Comment by djcb** [comment]
Can you still reproduce with `master` or the 1.8.14 release? I think some related things have changed.

**Comment by djcb** [comment]
This has gone stale, closing.
