### ISSUE TITLE
Support smtpmail-queue-dir as a context variable

### ISSUE THREAD

**Issue by pjones** [djcb/mu#1350]
## Expected or desired behavior

When sending mail that has been queued, mu4e should respect the context that each message was created in.  For example, each of my contexts uses a different SMTP mail server.  If I queue up mail from more than one context and then flush the queue, mu4e tries to send all mail through the active context's mail server.  This leads to send failures since the SMTP server in one context won't accept mail for other contexts.

## Actual behavior

mu4e sends all queued mail through the active context.

## Steps to reproduce

  1. Switch to your first context
  
  2. Enable mail queuing
  
  3. Create and send an email
  
  4. Switch to another context, send another email
  
  5. Flush the queue

## Versions of mu, mu4e/emacs, operating system etc.

GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-12-07

mu4e version 1.0

NixOS 18.09

## Any other detail

I tried setting `smtpmail-queue-dir` in each context to a different queue directory but that doesn't seem to work.  I think that supporting multiple queue directories would be the best solution.

Thank you very much for mu and mu4e.  I love this project!

**Comment by djcb** [comment]
`smtpmail-queue-dir` as a context-variable should probably 'work', but when you flush the queue, only the current smtpmail-queue-dir is affected... is that what you're seeiT

The queue mechanism is oblivious to contexts , so it'd be hard to add that.. perhaps a local caching stmp-server would be easier.

One half-solution would be iterate of the contexts and flush the context for each, assuming that none of the contexts share the queue-dir.

**Comment by pjones** [comment]
I've been experimenting and I've found that if I set `smtpmail-queue-dir` globally first, and then also set it in a context, things seems to work as expected.

All of my contexts have separate queue directories.  As long as I'm in the correct context when I flush the queue it seems to work.
