### ISSUE TITLE
Threading information in XML output

### ISSUE THREAD

**Issue by gspr** [djcb/mu#1351]
The `plain` and `sexp` output formats contain threading information when `mu find` is run with `--threads`. While I wouldn't mind parsing the `sexp` output format, have you considered adding threading information to the `xml` output format?

PS: Thanks for mu! It's saving my e-mail life.

**Comment by djcb** [comment]
The easiest way might be to use the (recent) json output and use some `json2xml` tool.

**Comment by gspr** [comment]
Ah, I was unaware of the JSON output format. If it has threading information, I'm happy with that. Thanks.

**Comment by clemtre** [comment]
I don't see any key related to thread information doing `mu find '' --format=json `, am I missing something ?

**Comment by djcb** [comment]
Ah, that feature didn't survive refactoring in the last 7 years...
