### ISSUE TITLE
mu script command not available

### ISSUE THREAD

**Issue by poulpoulsen** [djcb/mu#1353]
## Expected or desired behavior
hello,
i want to use guile scripts directly with the mu script <name> command.
mu is on verion 1.1.0
build from git clone and compile with guile 2.2 on system linux mint.
the examples from the mu-guile manual are working.

## Actual behavior
i insert command mu script in bash.
result:
mu: command 'script' not supported (2)

## Versions of mu, mu4e/emacs, operating system etc.
mu v1.1.0
build from source
guile 2.2.4 build from source
Linux Mint 
uname -a
Linux shinri 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

packages from linux mint are not working or too old.
mu v0.9.8
guile v.2.0

Regards
Poul

**Comment by poulpoulsen** [comment]
hello,
i read the issue #1354 about find-dups.scm. As far as i understand the scripts are in directory /usr/share/mu/scripts
The documentation said that GUILE_LOAD_PATH should be the same place,where mu.scm is. my location is /usr/share/guile/site/2.0
Is it possible, that this difference could be the reason for my problem?
if so, how could i change it?
as i mentioned, i installed from source.
Regards
Poul

**Comment by poulpoulsen** [comment]
hello,
i just run the script autogen.sh.
here is the output.
[mu.txt](https://github.com/djcb/mu/files/2730422/mu.txt)

as far as i see, guile 22 is found, but the following guiel depend checks are no. But no errors.
is this important?
when yes, how can i fix it?

Regards
Poul

**Comment by poulpoulsen** [comment]
Hello, any news about it? Is my provided text file helpful for you?
Regards
Poul

**Comment by djcb** [comment]
`mu script` is back with the latest mu, but that still leaves issue #1354. Anyway, some progress.

**Comment by poulpoulsen** [comment]
hello,
i just pulled the newest changes and compile. Now i can run scripts. I also create an environment variable with export LTDL_LIBRARY_PATH="/usr/lib" in my bashrc.
Thank you
Poul
