### ISSUE TITLE
find-dups.scm traceback

### ISSUE THREAD

**Issue by sje30** [djcb/mu#1354]
hi Dirk,
any clues trying to debug the traceback below?

## Expected or desired behavior

Running the find-dups.scm script

## Actual behavior

Please describe the behavior you are actually seeing. 
```
 ./find-dups.scm
Backtrace:
           4 (apply-smob/1 #<catch-closure 55b6b2113560>)
In ice-9/boot-9.scm:
    705:2  3 (call-with-prompt _ _ #<procedure default-prompt-handler (k pro…>)
In ice-9/eval.scm:
    619:8  2 (_ #(#(#<directory (guile-user) 55b6b21ce140>)))
In /home/stephen/./find-dups.scm:
     40:4  1 (find-dups #f _)
In unknown file:
           0 (_ #<procedure 55b6b2317aa0 at mu.scm:156:4 (msg)> #t -1)

ERROR: Wrong type to apply: #<unknown-type (0x24f . 0x7f5cb56e17e8) @ 0x7f5cb63950e8>
[stephen@light ~]$ guile --version
guile (GNU Guile) 2.2.4
Copyright (C) 2018 Free Software Foundation, Inc.

License LGPLv3+: GNU LGPL 3 or later <http://gnu.org/licenses/lgpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

## Steps to reproduce

find-dups.scm

## Versions of mu, mu4e/emacs, operating system etc.

Manjaro linux running "mu" from system (1.0.3) with Emacs 26.1
To run the script, I first needed to add:

    export GUILE_LOAD_PATH="/usr/share/guile/site/2.0"

to my .bashrc so that mu.scm and friends are found.

**Comment by poulpoulsen** [comment]
hello,
one question:
As far as i understand the scripts are in directory /usr/share/mu/scripts
The documentation said that GUILE_LOAD_PATH should be the same place,where mu.scm is. my location is /usr/share/guile/site/2.0
Is it possible, that this difference could be the a problem?

Regards
Poul

**Comment by sje30** [comment]
Thanks Poul for your reply.  I don't think this affects it, else I think the scripts like find-dups would have shipped in the same folder as mu.scm.  It used to work for me a couple of years ago on an older laptop, and I am pretty sure then I didn't need to change the directory.  Do any of the guile scripts work for you?

**Comment by poulpoulsen** [comment]
Hello,
if you mean the others in /usr/share/mu/scripts i must say no, because the mu command "script" is not available. if you mean guile script from within guile yes.
guile scripts work if i start them with guile <path to the script> or if they are located in GUILE_LOAD_PATH.

Because i dont know how to change the paths and the configure did it automatically, what could i do?
Any parameter to change this?

Regards
Poul

**Comment by sje30** [comment]
I think "script.scm" is available once you have loaded mu.  I did need to put the directory containing mu.scm into GUILE_LOAD_PATH ?

**Comment by poulpoulsen** [comment]
hello,
do you mean loading mu4e?
when not, how could i load mu?

Regards
Poul

**Comment by djcb** [comment]
It seems guile needs `LTDL_LIBRARY_PATH` these days; e.g..
```
LTDL_LIBRARY_PATH=/usr/local/lib   GUILE_LOAD_PATH=/usr/local/share/guile/site/2.0 mu find-dups
``` 
should work now, assuming things are installed under the default `/usr/local`.

**Comment by sje30** [comment]
hi Dirk,
no joy for me.  /usr/local/lib is empty on my manjaro box.  What files am I looking for to then create LTDL_LIBRARY_PATH accordingly?

**Comment by djcb** [comment]
After installing mu, _somewhere_ a file `libguile-mu.so.0.0.0`should appear  (name may be slightly different when not on Linux) should appear (by default this _somewhere_ is `/usr/local`). You should able to see from the `make install` output.

**Comment by sje30** [comment]
Thanks Dirk.  I see the lib (and mu4e version on the mu main screen reports `mu for emacs version 1.0 CG`.  Further I see the .so in /usr/lib:

```
ls -lh /usr/lib/libguile-mu.so*
lrwxrwxrwx 1 root root   20 May 31  2018 /usr/lib/libguile-mu.so -> libguile-mu.so.0.0.0
lrwxrwxrwx 1 root root   20 May 31  2018 /usr/lib/libguile-mu.so.0 -> libguile-mu.so.0.0.0
-rwxr-xr-x 1 root root 428K May 31  2018 /usr/lib/libguile-mu.so.0.0.0
```

but still no joy when adding /usr/lib to the library path:

```
LTDL_LIBRARY_PATH=/usr/lib find-dups.scm
Backtrace:
           4 (apply-smob/1 #<catch-closure 55743f58e560>)
In ice-9/boot-9.scm:
    705:2  3 (call-with-prompt _ _ #<procedure default-prompt-handler (k proc)>)
In ice-9/eval.scm:
    619:8  2 (_ #(#(#<directory (guile-user) 55743f649140>)))
In /home/stephen/./find-dups.scm:
     40:4  1 (find-dups #f _)
In unknown file:
           0 (_ #<procedure 55743f792aa0 at mu.scm:156:4 (msg)> #t -1)

ERROR: Wrong type to apply: #<unknown-type (0x24f . 0x7fcc103657e8) @ 0x7fcc110190e8>
[stephen@light ~]$ 
```

anything else you think might work?

**Comment by sje30** [comment]
Alternatively, I was thinking surely I could re-write this in elisp?  Is there anything in find-dups that requires scheme rather than elisp?  (Happy to code it myself if you think it doable, and point me to a starting point in the mu4e code base.)

**Comment by sje30** [comment]
okay, I'll close this for now.
