### ISSUE TITLE
Jumping to GMail inbox: Loading mu4e-headers slow

### ISSUE THREAD

**Issue by seanoreillyza** [djcb/mu#1356]
## Expected or desired behavior
Jumping to directly to the `mu4e-headers` view for my inbox should only take a few seconds (if that).

## Actual behavior
When jumping directly to `gmailmaildir/INBOX`  from the `mu4e` home screen, I'm prompted with a `Searching` method for ~40 seconds. This is slow every single time, and does not appear to get faster with subsequent jumps. 

Other bookmarked jumps (Today's messages etc.) and custom searches load instantly. 

I enabled logging and received the following output:

```
2019-01-04 16:22:47 logging enabled
2019-01-04 16:23:03 -> "cmd:find query:bWFpbGRpcjoiL3NlYW4ub3JseUBnbWFpbC5jb20vSU5CT1gi threads:true sortfield:date reverse:true maxnum:500 skip-dups:true include-related:true"
2019-01-04 16:23:42 * Received 14 byte(s)
2019-01-04 16:23:42 <- (:erase t)
2019-01-04 16:23:42 * Received 4096 byte(s)
...
<Messages listed here>
...
```

Also note that running the following on the command line returns instantly
```
mu find maildir:'/gmailmaildir/INBOX' "" -n 500 --reverse
```
 

## Steps to reproduce

This is how my jump command is configured:

```
;;; Mail directory shortcuts
(setq mu4e-maildir-shortcuts
      '(
        ("/gmailmaildir/INBOX" . ?f)
        ("/othermaildir/INBOX" . ?g)
        ))
```

Jumping to my `othermaildir` is instantaneous, but it also has much fewer messages. 

## Versions of mu, mu4e/emacs, operating system etc.
OS: macOS 10.14.2
mu: 1.1.0 (built from source)
mu4e: 1.0 
Emacs: 26.1

Thanks!

**Comment by djcb** [comment]
What happens when you run the same query from the commandline (using `mu find`)?

**Comment by seanoreillyza** [comment]
Wouldn't `mu find maildir:'/gmailmaildir/INBOX' "" -n 500 --reverse` be the equivalent?

**Comment by djcb** [comment]
Depends on your `mu4e` settings, but perhaps something like: `mu find "maildir:/gmailmaildir/INBOX" --include-related --threads -n 500 --reverse`

**Comment by seanoreillyza** [comment]
Yeah, so it turns out that this is slow:

```
time mu find "maildir:/sean.orly@gmail.com/INBOX" --include-related
--threads -n 500 --reverse
33.85s user 2.21s system 99% cpu 36.316 total
```

**Comment by seanoreillyza** [comment]
Yeah, so it turns out that this is slow:
```
time mu find "maildir:/gmailmaildir@gmail.com/INBOX" --include-related
--threads -n 500 --reverse
33.85s user 2.21s system 99% cpu 36.316 total
```

**Comment by djcb** [comment]
Wow! That's quite slow. 

How many messages do you have in your inbox? Can you try without `--include-related` and `--threads`, see if that makes a difference?

If you have access to profiling tools on MacOS that could show us where the time is spent, that would be even better.

**Comment by seanoreillyza** [comment]
Yup, the update definitely did the trick (from ~40s to ~0,1s) - see the below:

```
mu find "maildir:/gmailmaildir/INBOX" --include-related --threads -n    0.10s user 0.08s system 89% cpu 0.209 total
```

Awesome!

**Comment by djcb** [comment]
Oh great! Thanks for the quick test.
