### ISSUE TITLE
"Do what I mean" mu4e contexts

### ISSUE THREAD

**Issue by Ambrevar** [djcb/mu#1357]
Recently I helped out a friend to set up mu4e with multiple accounts.  This was
not my first time, but it was still rather difficult to go through the whole
process and to explain everything, even for a single account.

What felt most frustrating is that much of the initial configuration feels
unnecessarily picky and mu4e would surely benefit to have smarter default values
to ease migration for newcomers.

Since this is Emacs, I implemented a structure on top of "mu4e-contexts" so that
it fills the "configuration holes" automatically, leaving the user with only the
bare minimum to fill.

I've also added support for mailboxes which don't use the trash flag (like Gmail).

Here is the implementation:

https://gitlab.com/ambrevar/dotfiles/blob/master/.emacs.d/lisp/patch-mu4e-account.el

And here is an example user config (which removed about 100 lines from my
initial config):

```elisp
(setq user-full-name "Pierre Neidhardt")

;; https://docs.gandi.net/en/gandimail/standard_email_settings/index.html
(let ((gandi-smtp-vars '((smtpmail-smtp-server . "mail.gandi.net")
                         (smtpmail-stream-type . starttls)
                         (smtpmail-smtp-service . 587))))
  (make-ambrevar/mu4e-account
   :name "mail"
   :user-mail-address "mail@ambrevar.xyz"
   :sent-folder "Sent"
   :vars gandi-smtp-vars)
  (make-ambrevar/mu4e-account
   :name "work"
   :user-mail-address "pierre@work.place"
   :sent-folder "Sent"
   :condition (lambda (msg)
                (mu4e-message-contact-field-matches
                 msg '(:from :to) "boss@work.place"))
   :vars gandi-smtp-vars))
```

It's quite clear from the above implementation the the `ambrevar/mu4e-account`
structure does not add any new feature, it's just trying to be smarter and could easily merged into `mu4e-context`
structure.  Would you consider it?  I can send a patch.  Let me know!

## Versions of mu, mu4e/emacs, operating system etc.

mu: 1.0c
Emacs: 26.1
OS: GuixSD

**Comment by Ambrevar** [comment]
Sorry if I was unclear: we obviously don't want a separate data structure.  I
made it separate so that my local "hack" was clearly separate from mu4e's
codebase.

What I meant is that we could merge my "mu4e-account" into "mu4e-context".

Last but not least: do you like my "fix" for Gmail's trash?

Let me know and I'll submit a patch.

**Comment by djcb** [comment]
I like the overall approach, and your gmail-trash trick seems useful. Perhaps we can add some further reasonable defaults, based on the e-mail provider and/or the program used to fetch messages (but that's not really needed right now).

One critical feature would be an easy way to "export" the account to the textual representation of the corresponding mu4e-context, so in the inevitable case where someone's wishes good beyond the easy setup, we can give him/her a copy-pastable blob to start with.

Another thing would be documentation.

Do you have some ideas on how to add this to mu4e, code-wise? I think a good name would be `make-mu4e-context-account`, to clearly convey it's an easy to way to create a specific kind of account.

**Comment by Ambrevar** [comment]
> One critical feature would be an easy way to "export" the account to the textual
> representation of the corresponding mu4e-context, so in the inevitable case
> where someone's wishes good beyond the easy setup, we can give him/her a
> copy-pastable blob to start with.

I'm not sure I understand what you mean with "textual representation".  Isn't
`C-h v mu4e-contexts` enough?

> Another thing would be documentation.
> 
> Do you have some ideas on how to add this to mu4e, code-wise? I think a good
> name would be `make-mu4e-context-account`, to clearly convey it's an easy to way
> to create a specific kind of account.

No problem, I know the mu4e codebase reasonably well (I'm the author of
mu4e-conversation :p).

**Comment by djcb** [comment]
`C-h v mu4e-contexts` could be enough if the documentation explicitly mentions that -- ie. a small blurb "Migrating to manual contexts".

**Comment by Ambrevar** [comment]
Indeed, that's what I did in the pull request:

```
See the @code{M-x cl-describe-type RET mu4e-context} for more details.
```
