### ISSUE TITLE
All mails are sent with format=flowed. Can't disable it. 

### ISSUE THREAD

**Issue by loysollivier** [djcb/mu#1358]
## Expected or desired behavior

Send mails without `format=flowed` in the header when setting:
`  (setq mu4e-compose-format-flowed nil)`

## Actual behavior

When writing a mail if I look at `mu4e-compose-format-flowed` the variable is set to nil.
Once sent if I look in the header of the mail the `format=flowed` header is still present.

## Steps to reproduce

Write a mail and send it. Look into the header.

## Versions of mu, mu4e/emacs, operating system etc.
Ubuntu 16.04
Emacs 25.3.2
mu 1.0

**Comment by markk** [comment]
You have to also set the mml variable which controls this (yes, mu4e **should** do this).

`(setq mml-enable-flowed nil)`

**Comment by loysollivier** [comment]
Ah thanks @markk that works :)
