### ISSUE TITLE
Find by sender

### ISSUE THREAD

**Issue by marcbowes** [djcb/mu#1364]
## Expected or desired behavior

I would like to be able to find messages with a specific "Sender:". This is not the same as "From:", i.e. somebody can send an email on behalf of somebody else.
https://stackoverflow.com/questions/4367358/whats-the-difference-between-sender-from-and-return-path

## Actual behavior

I can't find anything in the manual that describes how to do this. "sender:foo" does not return any results.

## Steps to reproduce

In mu/mu4e, try query a mail where the from/sender are different. I can only find the sender using a plaintext search ("foo"), which finds too many results (e.g. subject/body contains foo).

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 1.1.0

**Comment by djcb** [comment]
That's not supported, and there are no plans to add it, sorry!

**Comment by marcbowes** [comment]
That's OK. My use-case is dealing with a large amount of unread email, i.e. after getting back from vacation. I wrote this to help cut down my backlog:

```
(defun marc/mu4e-mark-mails-from-sender (sender)
  "In the current headers view, find mails sent from SENDER and mark them.

This function exists because mu-find doesn't support searching by sender - https://github.com/djcb/mu/issues/1364.
To implement, we have to read each raw mail from disk because `mu4e-message-field' does not include Sender."
  (unless (eq 'mu4e-headers-mode major-mode)
    (user-error "must be in headers view"))
  (mu4e-headers-for-each
   (lambda (msg)
     (let ((path (mu4e-message-field msg :path)))
       (if (and path (file-readable-p path))
           (when (string-match (concat "Sender: " sender)
                               (with-temp-buffer
                                 (insert-file-contents path)
                                 (buffer-string)))
             (mu4e-mark-at-point 'something nil))
         (message "Not a readable file: %S" path))))))
```

I then implemented a wrapper around it that marks mails by a list of senders I don't consider high priority.

One of the best features of mu4e is exactly this - when you have a lot of email you can write code to deal with it!
