### ISSUE TITLE
mu4e-view-mode not respecting mu4e-view-fields

### ISSUE THREAD

**Issue by swananddhawan** [djcb/mu#1366]
## Expected or desired behavior

`mu4e-view-mode` should show `mu4e-view-fields`. It should show the fields as mentioned in the documentation. ![](http://www.djcbsoftware.nl/code/mu/mu4e-3.png)

## Actual behavior

`mu4e-view-mode` does not respects `mu4e-view-fields` and no fields are displayed in the buffer.
See the below screenshot for reference.

![](https://lh3.googleusercontent.com/FSpyWKXOQIkOJlJYw3P8JPEHcNBN6SHlGfWFwmh-0Of3gYlTalrgmQz81-glhOBDUF_bmSyFeuQ-XUY2sl4cFA08O4K-QbFIVItbQB5-NT8wHgOnfEuiW9EPKYbWUKK3N-9R-nKo0Ru4OGnnCVGsp9-CE9vahOVJuNNLQzXxktCZcmJqqlPNf7ZuRJLLl_0Ylk4_YG9T_4eWxYekea_RuRpPGSlJyPIYSpGB3yE23qunxkuPJvRKXR5kN1cIMxFPt67-7SGNHvvl0QWL4EiU97ZPUPsNi8dHkJmNF5zqwvAQxX0sqQprdpVBSYyjLpqyiQNwqJyu_IgMvrwmY_YeKWRrqSYF_5Rks9a7cvBrQVHpVUBjWHX6rqmUSzJ-1_3UnfaxANQmbWQsYKW66FKOrS0j-cQcEtBsU89sOv6W4Ptl3u747iN0BtwtByr2gmAb0ZLfUXmEnbMngaVezk4MC8xaTx-084AqHya3ZhM_oPAaWxI2QOyD6kPnuKuMADrvRq6RFfSjiBZKgxHQP4EUi-KEolNRm6dLZrz6GNX7cemmY9Y013A2lBjejC1e5sKGN9hIXMUt5ryHzT_159WGqPBRnguMYAHtOW1Az7wFHQ4KpoMvrFb7GYXNKXkN1M-qMpcQQJGQ3e2b26boK52CPU47mW0akzvSAear2aOIdWRay4ZUojolgo0zjs62ysYyeIqBYQDFcN9ij1TooJ4=w2154-h1220-no)

## My mu4e configuration
```elisp
(use-package mu4e
  :no-require t
  :load-path "/usr/local/Cellar/mu/1.0_1/share/emacs/site-lisp/mu/mu4e/"
  :config
  (setq mu4e-maildir "/Users/swanand/email"
        mu4e-sent-folder "/nestaway/[Gmail]/Sent Mail/"
        mu4e-drafts-folder "/nestaway/[Gmail]/Drafts/")

  (setq mu4e-confirm-quit nil)

  (setq mu4e-get-mail-command "killall --quiet mbsync; mbsync -V nestaway-gmail")
  (setq mu4e-update-interval 300)

  (define-key mu4e-headers-mode-map (kbd "o") 'mu4e-update-mail-and-index)

  (setq mail-user-agent 'mu4e-user-agent)

  (setq mu4e-view-show-addresses t)
  (setq mu4e-use-fancy-chars t)
  (setq mu4e-view-show-images t)

  (add-to-list 'mu4e-view-actions '("html in browser" . mu4e-action-view-in-browser) t)

  (add-hook 'message-mode-hook 'turn-on-orgtbl)
  (add-hook 'message-mode-hook 'turn-on-orgstruct++)
  (add-hook 'mu4e-compose-mode-hook 'flyspell-mode)

  (setq message-kill-buffer-on-exit t)

  ;; don't save message to Sent Messages, Gmail/IMAP takes care of this
  (setq mu4e-sent-messages-behavior 'delete)

  (setq mu4e-maildir-shortcuts
        '( ("/nestaway"          . ?i)
           ("/[Gmail]/Starred"   . ?t)
           ("/[Gmail]/Sent Mail" . ?s)
           ("/[Gmail]/Drafts"    . ?d)))

  (setq mu4e-view-fields '(:from :to :cc :subject :date)
        mu4e-headers-fields '((:flags         . 5)
                              (:human-date    . 12)
                              (:from          . 25)
                              (:size          . 6)
                              (:subject       . nil))))
```
## Versions of mu, mu4e/emacs, operating system
| Application/OS    | Version |
|-------------------|---------|
| mu                |     1.0 |
| Emacs             |    26.1 |
| OS(Mac OS Sierra) | 10.12.6 |

**Comment by djcb** [comment]
What does `C-h v mu4e-view-fields RET` say when you're in mu4e-view-mode?

**Comment by djcb** [comment]
Hmm, the view looks rather odd, are you using some extension  (such as `mu4e-conversation`)?

**Comment by swananddhawan** [comment]
@djcb : You are right! 👍 I am using `mu4e-conversation` and `mu4e-maildirs-extension`. The problem got solved after I removed `mu4e-conversation`. Looks like there is some issue with it.

**Comment by swananddhawan** [comment]
Noted. This was my first reported issue. Anyways, thanks for your time and effort. 👍  I really appreciate it.
