### ISSUE TITLE
Broken Build

### ISSUE THREAD

**Issue by Jebes** [djcb/mu#1367]
## Expected or desired behavior

The build builds

## Actual behavior

the build breaks with a syntax error

## Steps to reproduce
Checkout master and build

## Versions of mu, mu4e/emacs, operating system etc.
master

## Any other detail
fixed with attached patch file
[build.txt](https://github.com/djcb/mu/files/2776975/build.txt)

**Comment by djcb** [comment]
Oops! Fixed, thanks.
