### ISSUE TITLE
RFE: Hydra query bookmark integration

### ISSUE THREAD

**Issue by jfkw** [djcb/mu#1370]
## Expected or desired behavior

When using Hydras for multilevel bookmark trees as per #1327, it would be nice to register the hydras for display and single-key launch in the view mu4e-main.

It would be ideal to include an option in the registering function or data structure to display grouped with "Bookmarks", or optionally something user-defined and entirely different that Hydras can be used for, such as structured message move commands as a hypothetical example.

## Actual behavior

Per #1327, it is possible to define hydras for use as multilevel bookmarks. However, the recommended integration of binding a key does not give the user any prompt that the functionality is there.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e 9352219dcf75931ae877fd551af6c2a1cce29b25 v1.0-130-g9352219d

GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit) of 2019-01-22

**Comment by djcb** [comment]
It's mentioned in the docs, no plans to add it to the code.
