### ISSUE TITLE
Modal window asking user to check certificate prevents checking 

### ISSUE THREAD

**Issue by jsilence** [djcb/mu#1371]
## Expected or desired behavior

Message prompt to verify S/MIME certificate in non-modal pop-up window or minibuffer.

## Actual behavior

When a message in S/MIME format is received, mu4e tries to verify the sender. 
If the root certificate is unknown, the user is prompted to gauge the validity of the sender CA and asked to compare the fingerprint of the certificate.

Unfortunately the pop-up window is modal, so that at least in the I3wm window manager it is not possible to research the required information without closing the modal dialogue first. This makes is very hard to compare the fingerprints.

## Steps to reproduce

Receive/view a S/MIME formatted message lacking a signature from a trusted root CA.

## Versions of mu, mu4e/emacs, operating system etc.

GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
mu4e - mu for emacs version 1.1.0 C
Ubuntu 18.04 LTS

**Comment by djcb** [comment]
mu4e doesn't support S/MIME natively, so what sequence leads you to this dialog?  In any case, this seems like something that is outside the control of mu4e.

**Comment by jsilence** [comment]
It looks like the message is only signed, but not encrypted. The multipart segments contains base64 encoded versions of the message in text/plain and text/html. 

When I opened the message from the header view with RET, mu4e or some related component checked on the signature and prompted me for validating the root CA of the message signature against the fingerprint.

**Comment by markk** [comment]
This is `gpg-agent` running `/usr/bin/pinentry-gnome3` and it's insane default modal window. A workaround for this is to add:

```
pinentry-program /usr/bin/pinentry-gtk-2
```

to `~/.gnupg/gpg-agent.conf`, then reload configuration with:

```
gpg-connect-agent reloadagent /bye
```

Depending on your system you may have other pinentry options available, check with:

```
ls /usr/bin/pinentry*
```

**Comment by djcb** [comment]
Since this outside mu4e's control and with @markk 's workaround, closing this.
