### ISSUE TITLE
Duplicate draft messages

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1373]
## Expected or desired behavior

Writing a new draft, I expect to have a single draft message in my drafts folder

## Actual behavior

Duplicate draft messages are created. I am not sure why or when they are created but they seem to contain partial parts of my message.

## Versions of mu, mu4e/emacs, operating system etc.
Cloned from master.

## Other details
I looked this up and some were saying that auto-save mode is to blame (for some reason). I disabled this using

`(add-hook 'mu4e-compose-mode-hook #'(lambda () (auto-save-mode -1)))
`

But I still have the same issue. I have to admit that I constantly press `C-x C-s` without realizing. So I have a "manual" auto-save mode. But it doesn't seem to always create a new draft message and I am not even convinced that saving a message should create a duplicate (automatically or manually).

**Comment by Chris00** [comment]
I have this in my mu configuration file:
```elisp
(defvar mu4e-drafts-backup-directory "backup"
  "The directory for backup files of drafts.  It can be relative (in which
case it is understood as relative to `mu4e-drafts-folder') or absolute.
If `nil', the backup files are saved in the draft folder itself (and
will show up in the headers view).")

(when mu4e-drafts-backup-directory
  (let* ((drafts-dir (format "%s%s/" mu4e-maildir mu4e-drafts-folder))
         (drafts-cur-dir (file-name-as-directory (concat drafts-dir "cur")))
         (drafts-re (concat "^" (regexp-quote drafts-cur-dir)))
         (backup mu4e-drafts-backup-directory)
         (backup-dir (file-name-as-directory (if (file-relative-name backup)
                                                 (concat drafts-dir backup)
                                               backup))))
    (mkdir backup-dir t)
    (with-temp-buffer (write-file (concat backup-dir ".noindex")))
    (let ((bk (if (file-relative-name backup)
                  (concat (file-name-as-directory "..") backup)
                backup)))
      (push (cons drafts-re bk) backup-directory-alist))
    (let ((re (concat drafts-re "\\([^/]*\\)$"))
          (dir (concat backup-dir "\\1")))
      (push (list re dir) auto-save-file-name-transforms))))
```
Maybe something like that could be included in mu4e?

**Comment by haji-ali** [comment]
Thanks both. I already had the backups saved in a directory using `backup-directory-alist`, but the problem seem to be from some other source. Checking my cur folder inside the drafts folder, I can see that the different drafts have different IDs.
So I think something else is happening but I have no idea how to troubleshoot it.

**Comment by djcb** [comment]
Hmmm... that seems like something to take up with the mbsync people then.. not much we can do about that.

**Comment by Chris00** [comment]
@haji-ali Do you need to sync your drafts?  (I personally don't.)

**Comment by haji-ali** [comment]
Thanks all, I didn't know the reason of the duplicate drafts when I first posted the issue.
I now don't sync my drafts as @Chris00 suggested.

**Comment by kaz-yos** [comment]
I encountered a similar draft duplication issue with a setup with very frequent mbsync invocation via fswatch. Switching to mbsync's AltMap UID scheme (no UID in file names) seem to solve this issue while retaining the ability to sync the draft folder.

https://sourceforge.net/p/isync/mailman/message/35435686/

**Comment by haji-ali** [comment]
@kaz-yos, Thanks for posting this! This seems like a nice solution, although I am worried by the comment that "tracking is, indeed, necessary only to delete them" from the link you sent. I wonder if this means that deleting messages would not be possible without the UID in filenames.

Also, reading the link you sent, maybe mu should handle the UID change by revisiting the correct file (by checking if the stripped filename without the UID exists). I think I will implement this as a patch instead.

**Comment by kaz-yos** [comment]
If we hope to keep the usual mbsync U=* UID file naming scheme, we could try to find a matching file name (hopefully unique) and re-assigned the buffer-associated file like you said.

My rudimentary attempt is the following. Obtain the current buffer-associated file name, replace everything after ,U=... with a literal * and expand the wildcard * to find a list of matching file name(s).

```elisp
(file-expand-wildcards (replace-regexp-in-string ",U=.*$" "*" (buffer-file-name)) t)
```

**Comment by haji-ali** [comment]
Here's my attempt. 

```elisp
(defun my/mu4e-check-draft-rename nil
  "Check if the current file does not exist and if so, checks for another file
that has the same filename up to a ':' or ','. If a file is found, changes the buffer
filename to that file instead"
  (let ((buf-path (buffer-file-name)))
    (unless (file-exists-p buf-path)
      (let ((buf-file (file-name-nondirectory buf-path))
            (buf-dir (file-name-directory buf-path)))
        (when-let ((_ (string-match "^[^\\,\\:]*" buf-file))
                   (new-buf-name
                    (car (file-expand-wildcards
                          (concat buf-dir (match-string 0 buf-file) "*")))))
          (unless (string= new-buf-name buf-path)
            (let ((change-major-mode-with-file-name nil))
            (set-visited-file-name new-buf-name))))))))

(add-hook 'mu4e-compose-mode-hook
    (lambda nil (add-hook 'before-save-hook #'my/mu4e-check-draft-rename)))
```

There's of course a danger of overwriting a file that has the same message ID in the same directory but is for a different message.  I am personally OK with that risk and I think such a situation is incompatible with mbsync anyways.

**Comment by kaz-yos** [comment]
I settled on `mbsync`'s `AltMap yes` scheme. So the file names do not have `U=*`. This avoid draft message file duplication. However, saving with the same name also means no syncing to the IMAP server as `mbsync` does not see it as a new message. So I did the opposite. I created an interactive command that update the file name. When I want to sync the draft over IMAP, I interactively invoke this to update the file name (old file is kept) so that `mbsync` syncs this new file to the IMAP server.

```elisp
  (defun my-mu4e-update-draft-filename ()
    "Check if the current file exist and if so rename it.

Invoke this interactively to sync the current draft upon the next save.
This is useful when using mbsync with AltMap yes."
    (interactive)
    (let ((buf-path (buffer-file-name)))
      ;; When it's an existing file, assign a new name
      (when (file-exists-p buf-path)
        (let ((buf-dir (file-name-directory buf-path))
              (new-filename (mu4e~draft-message-filename-construct "DS")))
          (let ((change-major-mode-with-file-name nil))
            ;; Change name of file visited in current buffer to FILENAME.
            (set-visited-file-name (concat buf-dir new-filename)))))))
```
