### ISSUE TITLE
Can't build on Debian buster

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#1376]
## Expected or desired behaviour

For the build to complete

## Actual behavior

The build fails:
  Making all in guile
  make[2]: Entering directory '/home/alex/src/emacs/mu/mu.git/guile'
  o mu-guile.x mu-guile.c -DHAVE_CONFIG_H -I. -I.. -I../lib -pthread -I/usr/include/guile/2.2 -pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -g -O2 -I. -I.. -I../lib -pthread -I/usr/include/guile/2.2 -pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
  o mu-guile-message.x mu-guile-message.c -DHAVE_CONFIG_H -I. -I.. -I../lib -pthread -I/usr/include/guile/2.2 -pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -g -O2 -I. -I.. -I../lib -pthread -I/usr/include/guile/2.2 -pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
  /bin/bash: o: command not found
  /bin/bash: o: command not found
  make[2]: [Makefile:1250: mu-guile.x] Error 127 (ignored)
  make[2]: [Makefile:1250: mu-guile-message.x] Error 127 (ignored)
  make  all-recursive
  make[3]: Entering directory '/home/alex/src/emacs/mu/mu.git/guile'
  Making all in .
  make[4]: Entering directory '/home/alex/src/emacs/mu/mu.git/guile'
    CC       mu-guile.lo
    CC       mu-guile-message.lo
  mu-guile.c: In function ‘mu_guile_init’:
  mu-guile.c:251:10: fatal error: mu-guile.x: No such file or directory
   #include "mu-guile.x"
            ^~~~~~~~~~~~
  compilation terminated.
  mu-guile-message.c: In function ‘mu_guile_message_init’:
  mu-guile-message.c:623:10: fatal error: mu-guile-message.x: No such file or directory
   #include "mu-guile-message.x"
            ^~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  make[4]: *** [Makefile:633: mu-guile.lo] Error 1
  make[4]: *** Waiting for unfinished jobs....
  make[4]: *** [Makefile:633: mu-guile-message.lo] Error 1
  make[4]: Leaving directory '/home/alex/src/emacs/mu/mu.git/guile'
  make[3]: *** [Makefile:814: all-recursive] Error 1
  make[3]: Leaving directory '/home/alex/src/emacs/mu/mu.git/guile'
  make[2]: *** [Makefile:528: all] Error 2
  make[2]: Leaving directory '/home/alex/src/emacs/mu/mu.git/guile'
  make[1]: *** [Makefile:538: all-recursive] Error 1
  make[1]: Leaving directory '/home/alex/src/emacs/mu/mu.git'
  make: *** [Makefile:448: all] Error 2

## Steps to reproduce

On a freshly installed Debian Buster image.

  sudo apt-get build-dep maildir-utils
  ./autogen.sh
  ./configure --prefix=/home/alex/src/emacs/mu/install
  make -j9

## Versions of mu, mu4e/emacs, operating system etc.

Fresh git checkout @ 156c42111327ea6fa9d04112dfb186ab4745618e
Debian Buster (amd64)
Emacs 26.1

## Any other detail

It looks like the Debian maintainer had to work around the guile detection:

  https://salsa.debian.org/preining/maildir-utils/commit/7db53a897978553c19ba55308d547a39183185c4

but I wonder why the hard pegging of guile version. Shouldn't we just detect a minimum version of guile and the appropriate tools from there?

**Comment by stsquad** [comment]
So workaround is downgrading the system guile to 2.0. However this will only be possible on systems that package multiple versions (which Debian does currently).

**Comment by djcb** [comment]
Hmm, what seems to happen is that the guile.m4 macros half-detect guile 2.2. What's also needed is `guile-snarf2.2` but that's not detected because on Debian it's called just `guile-snarf`. That should be fixed at some point (probably through `guile.m4`, but for now at least we shouldn't try to build something that'll fail. Fixed in git.
