### ISSUE TITLE
Is it possible to match maildirs by wildcard?

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1377]
I know I can do `mu find maildir:/mail1/Inbox OR maildir:/mail2/Inbox` but is there away to do something lie `mu find maildir:*Inbox` to match all inboxes? I have many mailboxes and I would like to search for an email in all inboxes (or drafts... etc).

**Comment by djcb** [comment]
There are `*` wildcards, but they are only possible at the rightmost position of a term; you can however use a regular expression.

`man mu-query` describes the mu query language, including the above.
