### ISSUE TITLE
Establish some example folder/account for reproducing issues

### ISSUE THREAD

**Issue by bradyt** [djcb/mu#1378]
There are a number of issues where developer simply cannot reproduce the issue described by users. Would be nice if there were some sort of IMAP only public mailbox, or anyways some Maildir directory of emails, containing non-trivial emails, for example the sort of large html emails sent by larger companies, etc.

**Comment by djcb** [comment]
There are quite a few tests in mu (see eg. `lib/tests/testdir*`), more are welcome :)

**Comment by bradyt** [comment]
Hmm, those all seem to be quite small files.

**Comment by djcb** [comment]
There's nothing stopping you (or someone else) to add a unit-test for specific larger messages; in fact, such tests might be quite useful.

**Comment by bradyt** [comment]
Maybe a good way to proceed would be to use one of these anonymous email accounts available online, and use it to provoke some largish emails from any big corporation. Will try to execute this in some time.
