### ISSUE TITLE
Replies include plain text attachment instead of original message

### ISSUE THREAD

**Issue by cody-addison** [djcb/mu#1380]
## Expected or desired behavior

The expected behavior is to use the original message text instead of the attachment in the reply body.

## Actual behavior

The plain text attachment is used as well

## Steps to reproduce

I have mu4e-view-use-gnus set to 't', but I don't think that is the issue. I suspect this is related to https://github.com/djcb/mu/issues/1072 and that the problem is the reply is not using gnus, but instead the same mu4e framework which causes the attachment to be viewed instead of the original message

## Versions of mu, mu4e/emacs, operating system etc.

I'm on a mac and using the latest master

**Comment by djcb** [comment]
With problems like these, please include the raw messages; in any case, what is to be considered an attachment and what not is a fairly subtle issue, esp. for text parts.

**Comment by cody-addison** [comment]
Here are two files. The bad.txt file has the issue and the good.txt does not. The only difference is the size of the attachments. Let me know if you need any additional information.

[bad.txt](https://github.com/djcb/mu/files/2870570/bad.txt)
[good.txt](https://github.com/djcb/mu/files/2870573/good.txt)

**Comment by djcb** [comment]
There are a few cases where inlining attachment text parts is nice... but I guess we also run in the
issue mentioned here. I've pushed a change to master make mu a bit less eager to inline things.

**Comment by cody-addison** [comment]
Thanks! This seems to have fixed the issue. 

I noticed a change to org-mu4e.el that added DEPRECATED to org-mu4e-compose-org-mode. I recently stumbled upon this post: https://matt.hackinghistory.ca/2016/11/18/sending-html-mail-with-mu4e/ which seems to work well for sending html messages using org mode. I applied his branch to master and included his init.el code. Sending html or rtf would be a huge win for me since my company is primarily using outlook and html/rtf messages would look better to them. Additionally, the flexibility of composing with org mode would be great (I frequently compose mail with lists and tables). 

Is there a recommended way to compose email using org mode and have it exported to html/rtf?

**Comment by djcb** [comment]
If it works well, you're lucky :).

 The core of it is in `org-mime.el` and part might actually work quite well; however mu4e tries (tried) to integrate that somewhat 'transparently' with the editor, and that parts is rather fragile.

So, I guess your best bet is using `org-mime` directly.
