### ISSUE TITLE
mu4e child threading indicator wrong aligned

### ISSUE THREAD

**Issue by stardiviner** [djcb/mu#1383]
Here is the screenshot:

![mu4e-threading align](https://user-images.githubusercontent.com/378699/53549416-10c0f300-3b6f-11e9-8920-fd40bbd14a65.png)

I guess it's because of the recipient name contains non-UTF-8 characters. Like `é` in `Clément Pit-Claudel`

**Comment by anarchodin** [comment]
But there are lines there containing the letter å which are not getting messed up. Might it be a question of NFC versus NFD?

**Comment by djcb** [comment]
Is this still observed? Seems fine here.

**Comment by djcb** [comment]
Anyway, the development version has `mu4e-headers-precise-alignment` which avoids the misalignment, at the cost of some speed.
