### ISSUE TITLE
mu4e-action-view-in-browser doesn't show any headers

### ISSUE THREAD

**Issue by davidcsterratt** [djcb/mu#1385]
## Expected or desired behavior

I'd like the From, To, Subject and Date headers to appear in the HTML page opened with `mu4e-action-view-in-browser`

## Actual behavior

Only the body of the message appears.

**Comment by Chris00** [comment]
@davidcsterratt I guess this [can be closed now](https://github.com/djcb/mu/pull/1386).

**Comment by davidcsterratt** [comment]
Yes - there's a comment on the pull request, but I think this issue can be closed.
