### ISSUE TITLE
Problem with mu building “error while loading shared libraries: libxapian.so.30”

### ISSUE THREAD

**Issue by JuanPabloMF** [djcb/mu#1387]
## Expected or desired behavior

 I just tried building Mu 1.0. The build of mu didn't give any error, so the `mu server` command should be working fine.

## Actual behavior

When calling `mu server` in the command line I get the following error message:

```
mu: error while loading shared libraries: 
libxapian.so.30: cannot open shared object file: 
No such file or directory

```
## Steps to reproduce

I am on ubuntu 16.04.2. I installed GMIME 3.0 and Xapian 1.4. My GNU Make is version 4.1.

I tried symlinking a libxapian.so.30 to libxapian.so. When I do that I get another type of error:

`mu: symbol lookup error: mu: undefined symbol:_ZN6Xapian16WritableDatabaseC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii`

I also tried adding LD_LIBRARY_PATH to the path of the libxapian.so file with no results.

I managed to build version 0.9.18 and its working fine on my computer.

**Comment by djcb** [comment]
Guess this is either:
- perhaps there's some older version of mu lying around which expects an older xapian
- or perhaps you have multiple xapian versions installed 
- some path issue

The error message suggests that mu was compiled with another version of xapian compared to the one it finds when running.
