### ISSUE TITLE
Can't seem to get mu4e working with Emacs for OSX

### ISSUE THREAD

**Issue by BrandonShega** [djcb/mu#1388]
## Expected or desired behavior

Emacs finds mu4e and is able to open email.

## Actual behavior

Emacs can't seem to find mu4e, I get this error message on start and a similar one when I try to open mu4e in Emacs.

`Error (use-package): personal/:catch: Cannot open load file: No such file or directory, mu4e`

## Steps to reproduce

Install Emacs from https://emacsformacosx.com/
Build mu from source
Open mu4e in Emacs

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 26.1
Spacemacs 0.300.0
mu 1.1.0
mu4e ?
macOS 10.13.6

## Any other detail

I am building mu from source because I can't seem to get it to work with homebrew, I've tried
`brew install mu --with-emacs` and I get an error that says `invalid option: --with-emacs`

Let me know if any more information is required.

**Comment by BrandonShega** [comment]
So, fwiw, I got it to work by using a spacemacs configuration:
`mu4e-installation-path "path/to/mu/mu4e"` and it started working, but I'd like to not have this since I use Emacs on different machines.

**Comment by djcb** [comment]
This is more of an emacs configuration question than anything specific for mu4e;  guess what you should add to your emacs configuration: 
 ```
   (add-to-list 'load-path "<path-to-mu4e-installation>")
```
and perhaps
```
   (setq mu4e-mu-binary "<path-to-installed-mu-binary>")
```

**Comment by clyton** [comment]
> So, fwiw, I got it to work by using a spacemacs configuration:
> `mu4e-installation-path "path/to/mu/mu4e"` and it started working, but I'd like to not have this since I use Emacs on different machines.

How did you install mu4e. I am trying `brew install mu --with-emacs` and it says `Error: invalid option: --with-emacs`

**Comment by BrandonShega** [comment]
> > So, fwiw, I got it to work by using a spacemacs configuration:
> 
> > `mu4e-installation-path "path/to/mu/mu4e"` and it started working, but I'd like to not have this since I use Emacs on different machines.
> 
> 
> 
> @BrandonShega
> 
> How did you install mu4e. I am trying `brew install mu --with-emacs` and it says `Error: invalid option: --with-emacs`

I actually manually cloned mu into a folder in my Dropbox then I specify the path to that. That way as long as the Dropbox folder is at the same location on every machine, it just works.

**Comment by Chris00** [comment]
As @djcb said, you can use [`(add-to-list 'load-path ...)`](https://www.gnu.org/software/emacs/manual/html_node/elisp/List-Variables.html) to add several locations for your mu code.  Alternatively, you could set an environment variable, say `MU4EHOME` on each machine and use `(add-to-list 'load-path (getenv "MU4EHOME"))`.
