### ISSUE TITLE
Can't compose in mu4e 

### ISSUE THREAD

**Issue by antoine-levitt** [djcb/mu#1389]
mu4e-compose-new gets me "mu4e-compose-new: Symbol’s value as variable is void: mu4e~view-msg" from a clean config. Seems related to recent commits?

**Comment by antoine-levitt** [comment]
Confirmed: 9bffb465bdd1a4ba737d5977391717751f5beb07 works.

**Comment by djcb** [comment]
Seems you still have some (compiled?) code refering to a renamed variable. Grepping the mu4e code yields no hits for `mu4e~view-msg`.

`make clean; make` should do the trick.

**Comment by antoine-levitt** [comment]
Indeed that was the case. Sorry for the noise!
