### ISSUE TITLE
mu4e not showing emails on POP and IMAP

### ISSUE THREAD

**Issue by miguelmorin** [djcb/mu#1391]
## Expected or desired behavior

I expected mu4e to show all emails when I respond to one email in the thread or resend a sent email as a new mail
## Actual behavior

I have had trouble finding some emails. This happens with both POP and IMAP. With POP, I had one email I needed to answer, I got a second email from the same sender as a reminder, had both in my inbox, replied to the first, and the second disappeared from my inbox and I can no longer find it locally. 
I attach a picture of the search on the server and locally. The message of February 25th still exists on the server but mu4e cannot find it locally.

<img width="1183" alt="screenshot 2019-03-06 at 07 57 45" src="https://user-images.githubusercontent.com/32396311/53864934-aaf8bf00-3fe5-11e9-8930-518b5662ce6c.png">
<img width="1217" alt="screenshot 2019-03-06 at 07 58 00" src="https://user-images.githubusercontent.com/32396311/53864939-af24dc80-3fe5-11e9-880f-264a4354b71f.png">

With IMAP, on Monday I reused an email I had sent with `mu4e-compose-resend`. I am still able to see the original email but not the email I sent. Both still exist on the server but not locally.

I saw this happening every time I reused a sent email (5 times on Monday).

## Steps to reproduce

I do not know enough about mu4e to include a stack trace, but can run one to reproduce it if given directions.

## Versions of mu, mu4e/emacs, operating system etc.

`mu (mail indexer/searcher) version 1.0`
`Emacs: 26.1 (9.0)`
`macOS Mojave`

**Comment by djcb** [comment]
Most likely, this doesn't have much to do with mu/mu4e. but instead with the way you synchronize the local & remote mailboxes. So, best check the settings for e.g. offlinimap (or whatever you use). 

You might want to review  `mu4e-sent-messages-behavior`.

**Comment by miguelmorin** [comment]
I reviewed the documentation for that variable, which sets the behavior of sent messages. My problem occurs on a message that I received, which I was able to pull with POP from the server, and which disappeared once I replied to another email in the same thread.

**Comment by djcb** [comment]
Best to look at what happens on the mu / filesystem level then; ie. check if those mails are still present on your system

**Comment by miguelmorin** [comment]
I can see those emails when I pull IMAP email in another client. I did `mu --help` and found no entries about searching for email. Does `mu` come with a way to search for emails in the index?

**Comment by djcb** [comment]
`mu find` should do the trick. And you can check the filesystem if the files corresponding to the message are there.

One other thing that may play a role -- perhaps try setting mu4e-headers-skip-duplicates` to nil?

**Comment by miguelmorin** [comment]
I had the same issue today. I read the message yesterday and today it is no longer in my inbox nor in `mu` (with `mu find`), but is still on the server. I use `getmail`, not `offlineimap`, so I don't think fetching email would cause deletion of messages. The common characteristics of the two cases is that they were both a received message, the last message in a thread, and far apart (weeks or months).

**Comment by djcb** [comment]
Do you stil have this problem?

What you'd need to check is if the message is present in your filesystem (`getmail` will download the messages to files in your filesystem, somewhere under the maildir). Whether it's still on the server is not too relevant, it makes no difference for mu.

If you can read a message in mu, at least at that moment it must be present in the filesystem.

What's the value of `mu4e-sent-messages-behavior`?

**Comment by miguelmorin** [comment]
Yes, I still have the problem with the original email of `2019-02-25` in the sense that it is not showing on `mu` nor `mu4e`. The same email is on the server, which is not relevant for `mu` but relevant for me to ensure that I am reporting an actual bug!

I have not noticed other occasions of the same bug.

The value of `mu4e-sent-behavior` is `sent`.

**Comment by djcb** [comment]
Okay, so if the mail in not in your filesystem and mu/mu4e are not showing, that's just as expected. 

I'd recommend reviewing & testing how you get / synchronize your mail, and see what program is removing the mail. Good luck!

mu/mu4e can't really do anything there, so closing this.
