### ISSUE TITLE
mu4e - mu4e-action-show-thread Stops Working on Refresh

### ISSUE THREAD

**Issue by kevinjfoley** [djcb/mu#1392]
## Expected or desired behavior

Call `mu4e-action-show-thread` and get all messages from thread in `*mu4e-headers*`.  When `*mu4e-headers*` is refreshed, continue showing all messages irrespective of values for `mu4e-headers-show-threads` and `mu4e-headers-include-related`

## Actual behavior

When refreshing in `*mu4e-headers*`, the values of `mu4e-headers-show-threads` and `mu4e-headers-include-related` are used and if they are `nil` then only the original message shows up.

## Steps to reproduce
- Set the following:
```
(setq mu4e-headers-show-threads nil)
(setq mu4e-headers-include-realated nil)
```
- Call `mu4e-action-show-thread` on a message
- Verify the thread show in `*mu4e-headers*`
- Call `mu4e-headers-rerun-search` 
- Only original message is visible now

## Versions of mu, mu4e/emacs, operating system etc.
mu/mu4e version: 1.0_1
emacs version: 26.1

**Comment by djcb** [comment]
It's a limitation of the very simple way `mu-action-show-thread` works; don't see an any easy way to change that, unfortunately, closing this... Sorry!
