### ISSUE TITLE
autogen.sh requires libgmime 3.0 or greater, too new for stable distros

### ISSUE THREAD

**Issue by ian-kelling** [djcb/mu#1400]
Current debian 9.0 has libgmime-2.6-0. 

HACKING file also says libgmime-2.6-0 which is incorrect.

The responsible commit is 
61341486d2508f2ee924ceda0b90078f5a687c50

If I get libgmime-3.0.0 package from a newer distro, it has the problem that it
also requires libgpgme11 from a newer distro, and that has a lot of
reverse dependencies which might get broken.

**Comment by ian-kelling** [comment]
HACKING file should at least advise people how to get the newer gmime,
since their distro often won't have it. For example, debian 9.0 which
is the current stable release.

**Comment by ian-kelling** [comment]
I installed gmime-3.0.5 from source, which was pretty easy, just standard make install. mu built fine then, but then trying to decrypt an email, it failed with a standard brief error message. Looks like a bug.

**Comment by djcb** [comment]
I've updated the HACKING file.. 

Note, the commit is from mid-2017, mu/mu4e have been GMime-3.x -only for a while already. Crypto should work as well, if not please file an issue for that - thanks!
