### ISSUE TITLE
Enhancement: mu4e-compose-reply taking a msgid

### ISSUE THREAD

**Issue by malb** [djcb/mu#1404]
## Expected or desired behavior

It would be nice if `mu4e-compose-reply` would take an optional msgid instead of relying solely on `mu4e-message-at-point`. This would allow adding e.g. custom org-mode links that directly open a reply compose buffer instead of a message view.

**Comment by djcb** [comment]
This is not being planned... in fact I expect we'll use more of gnus for this in the future rather than the mu4e machinery. Sorry!
