### ISSUE TITLE
Improve modeline in headers mode

### ISSUE THREAD

**Issue by gusbrs** [djcb/mu#1410]
mu4e headers mode provides info on the current mode, on the current context and on the current query. The first one, by the `mode-name` variable, and the remaining two through `global-mode-string`. All three are actually handled by the function `mu4e~headers-search-execute` in `mu4e-headers.el`. I have some suggestions to kindly offer as to how this function presents this information.

- The `global-mode-string` presents the query first and then the context info. Care is taken that the context is not thrown out of the frame width with `mu4e-modeline-max-width`, which defaults to 30. This is important, as this is actually the only place where the information on the current context is given (except on change in the echo area). However, the context info is typically short, while the query string can very well be quite long (e.g. bookmarks). I also dare say that, for those who use contexts, this info is more important than the query. So a more convenient way to present this information would be to invert their order: context first, then the search query string. Then one could go with a much larger `mu4e-modeline-max-width`, and relax about it.

- Even better, a help echo to the search query could be added to the `global-mode-string` properties. This provides a convenient access to the full search string at any time, if need be.

I've been reaching very pleasing results with:

```
(setq mu4e-modeline-max-width 100)

(add-hook 'mu4e-headers-search-hook
          (lambda (query)
            (setq-local global-mode-string
                        '(:eval
                          (concat
                           ;; changed the order of context and query
                           (mu4e-context-label)
                           " "
                           (propertize
                            (mu4e~quote-for-modeline mu4e~headers-last-query)
                            'face 'mu4e-modeline-face
                            ;; and added a very convenient help echo
                            'help-echo (format "%s" mu4e~headers-last-query))
                           (if (and mu4e-display-update-status-in-modeline
                                    (buffer-live-p mu4e~update-buffer)
                                    (process-live-p (get-buffer-process
                                                     mu4e~update-buffer)))
                               (propertize " (updating)" 'face 'mu4e-modeline-face)
                             ""))))))
```

- Besides that, the same `mu4e~headers-search-execute` function hardcodes the mode-name with a `(setq mode-name "mu4e-headers")`. This means one cannot delight this mode's name, as is standard. I don't know the reasons why this is being set this way, but thus hardcoding it does seem overkill. So far I've been hijacking it with:

```
(add-hook 'mu4e-headers-search-hook
          (lambda (query)
            (setq mode-name "mu4e")))
```
but this clearly less than ideal.

Those are only two cents, meant as suggestions, of a happy and thankful user.

## Versions of mu, mu4e/emacs, operating system etc.
mu/mu4e 1.2, Emacs 26.2, Linux Mint 19.1

**Comment by djcb** [comment]
Modeline has been much improved in `master`; closing this.

**Comment by gusbrs** [comment]
Looking forward to it. Thank you!
