### ISSUE TITLE
Dynamic mu4e-headers-fields

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1411]
In some mail directories like "sent" or "draft", the default `:from` field is somewhat useless. I want to be able to dynamically show the `:to` field instead while keeping the `:from` field in all other directories.

Is there a way to do this? #281 seems to mention that, but I am not sure how `mu4e-header-info-custom` could help.

**Comment by djcb** [comment]
There's the `:from-or-to` field that can be useful for this. 

Alternatively, you could manipulate the headers list in `mu4e-headers-search-bookmark-hook` and special-case when we're search for sent or draft.
