### ISSUE TITLE
Inconsistency of viewing and composing messages

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1415]
I sometimes have an email open in mu4e and want to compose a new message to the same senders (or a subset of them). I thought I could simply copy the addresses and compose a new message and then paste the addresses there. However, that did not work because mu4e does not include the quotes around names so for example, the `From` field in `mu4e-view` has `Surname, Name <foo@example.com>`, copying this does and pasting it in the `To` field of a newly created message does not work because of the comma and I have to add quotes like this `"Surname, Name" <foo@example.com>"`.

Is there a way to make `mu4e-view` add these quote in the view?

**Comment by Chris00** [comment]
On  1 May 2019 at 15:14 CEST, Abdul-Lateef Haji-Ali <notifications@github.com> wrote:
>
> […] Is there a way to make mu4e-view add these quote in the view?

You can use Gnus article mode:

    (setq mu4e-view-use-gnus t)

(this is still in development but working well and with several advantages already).

**Comment by djcb** [comment]
Yes, @Chris00 is right - the gnus-view is your best option here.
