### ISSUE TITLE
How to send cc?

### ISSUE THREAD

**Issue by RidaAyed** [djcb/mu#1419]
## Expected or desired behavior

```
From: 
Reply-To: 
To: 
CC:
Subject: 
```

## Actual behavior

```
From: 
Reply-To: 
To: 
Subject: 
```

For bug-reports, if applicable, include error messages, emacs stack
traces etc. Try to be as specific as possible - when do you see this
happening? Does it happen always?  Sometimes? How often?

## Steps to reproduce

- Compose new email

For bug-reports, please describe in as much details as possible how
one can reproduce the problem*.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

**Comment by Chris00** [comment]
On  8 May 2019 at 09:38 CEST, Rida Ayed <notifications@github.com> wrote:
>
> Expected or desired behavior
>
> From:
> Reply-To:
> To:
> CC:
> Subject:

You can add the missing fields by hand or use the “Field” menu.

**Comment by djcb** [comment]
Indeed, thanks @Chris00
