### ISSUE TITLE
org-mu4e somehow conflicts with org-babel-tangle

### ISSUE THREAD

**Issue by japhir** [djcb/mu#1420]
## Expected or desired behavior

I want my `C-c C-v t`, which calls `org-babel-tangle` to work!

## Actual behavior

It doesn't, but it throws the message: `org-mu4e-store-link: Symbol’s function definition is void: mu4e-message-at-point`. So it looks like the keybinding that I set to `C-c c` somehow interferes with babel?

## Steps to reproduce

Use my [use-package config for mu4e](https://github.com/japhir/ArchConfigs/blob/master/myinit.org#mu4e). Open an org file with some tangled source code blocks, i.e.:

```
* export settings :ignore:
#+options: toc:nil ':t date:nil email:t tasks:t tex:t -:t tasks:nil
#+property: header-args:R  :session *R* :exports results :results output :eval no-export
#+language: en
# inline source blocks just print the value, not the value wrapped in ~=~'s.
 #+BEGIN_SRC emacs-lisp :exports none
  (setq org-babel-inline-result-wrap "%s")
#+END_SRC

* hoi
This comment should be incorporated in the =temp.R= file.
#+begin_src R :tangle temp.R :comments org
print("test")
#+end_src

#+RESULTS:
: test

* COMMENT commented out
This part is not exported, now testing whether the block is still tangled and this is still included.
#+begin_src R :tangle temp.R :comments org
print("comment")
#+end_src

* noexport heading :ignore:
this heading is not exported, but the contents are!

```
run `M-x org-babel-tangle` or hit `C-c C-v t`.

## Versions of mu, mu4e/emacs, operating system etc.

1.2.0, emacs 26.2, Arch linux

**Comment by sanklamm** [comment]
I have the same kind of issue. I observed this behaviour with `org-store-link`.
Same error.

I am also on emacs 26.2 using Arch.
But I'm using the Spacemacs configuration.

**Comment by sanklamm** [comment]
Addendum: It works as expected when mu4e is running. I only get the error when it is not.

**Comment by djcb** [comment]
It seems you try to use `org-mu4e` without having loaded mu4e proper.  So, put a `(require 'mu4e)` in your configuration.

**Comment by japhir** [comment]
This works, maybe [my specific `use-package` setup](https://github.com/japhir/ArchConfigs/blob/master/myinit.org#mu4e) is deferring loading mu4e until invoked, which I don't do that often.
