### ISSUE TITLE
Prefer e-mails from me as source when autocompleting e-mail addresses

### ISSUE THREAD

**Issue by malb** [djcb/mu#1426]
## Expected or desired behavior

mu(4e)'s autocompletion of e-mail addresses based on the mail database is an excellent time saver. It would be a nice enhancement if the parser extracting these e-mail addresses would prefer e-mails I sent over e-mails by other people. My contacts regularly misspell names of my other contacts, meaning that I cannot autocomplete on the correct spelling. 

## Actual behavior

mu(4e) will pick whatever e-mail was sent last. Say I sent an e-mail to "Firstname Lastname <email@host.com>"  and later a contact sent an e-mail to "Fristnme  <email@host.com>" then mu(4e) will offer "Fristnme" as autocomplete option but not "Firstname Lastname".

## Steps to reproduce

See above.

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 26.1, MU 1.2

**Comment by djcb** [comment]
Well, if apparently many people misspell names, it's probably not a good heuristic :-)  

For these cases, there's `mu4e-contacts-rewrite-function` (in 1.2) or `mu4e-contact-process-function` (>= 1.3). Doesn't that work for you?

**Comment by malb** [comment]
As far as I understand things, this won't work for my use case. Assume Alice sent an e-mail to "Bob Smith <bob@smith.com>" and Malory sent an e-mail to "Bbo mSith <bob@smith.com>". `mu` will pick the most recent of those as the contact for  the address "bob@smith.com" and send it to `mu4e`. Thus, if Malory sent after Alice, the name is wrong, but not otherwise. I can, of course, use `mu4e-contact-rewrite-function` to fix up "Bbo mSith" but this may or may not be possible depending on Malory's choices.

My heuristic is that I know how I want to spell my contacts' names. Thus, given the choice which contact to send to `mu4e` it'd be nice to have an option to get the one that has my address as from.

**Comment by djcb** [comment]
I understand it'd be useful for your parrticular situation; however, it's not really something we could enable in general; thus it'd require an option, documentation etc.. This would overstretch our complexity budget a bit, esp. since there's a rewrite/process so you could solve it that way.

(as a workaround, you could of course write yourself a mail with the correct address, with the date set to 2030...)
