### ISSUE TITLE
Keep context between mu shell commands like Mail Handler (mh)?

### ISSUE THREAD

**Issue by brianbartholomew** [djcb/mu#1430]
I'm new to mu, and I come from a Mail Handler (mh) background.  I'm
wondering what internal indexing features already exist in Xapian
which might enable bash wrappers around mu to work similarly to mh.
Mh messages are numbered with small integers, to refer to messages
with less typing than Maildir filenames.  The last message number and
email folder you've referred to are saved between mh commands as a
context.  Here is a comparison of commands:

mh: scan    mu: mu find "" | cat -n

where each row of listing has an index number for use by other mh
commands

mh: show    mu: mu view $(mu find -f l foo) | less

except instead of searching for foo, it takes index numbers

mh: next, prev

like show except first moves to next or previous index number

mh: rmm     mu: mu remove

then rename Maildir file for later purge

**Comment by djcb** [comment]
The `mu` invocations don't maintain state, so you can't really do that; you'd need to write a shell _on top of_ mu to handle that. You can use `message-ids` or perhaps Xapian docids if you want something like that.

**Comment by brianbartholomew** [comment]
Thank you!  In practice message-ids aren't unique, so Xapian docids is the name of the index number feature I was looking for.

**Comment by djcb** [comment]
Okay, happy to help!
