### ISSUE TITLE
Avoid periodic getting of mail with very little configuration

### ISSUE THREAD

**Issue by bradyt** [djcb/mu#1431]
## Expected or desired behavior

Would like to be able to easily configure mu4e (with just a few `setq`) in the following way.

I have an external utility to get mail periodically. So I would like mu4e to index periodically, but not get mail periodically. But I would like `C-S-u` to get mail and index.

## Actual behavior

If a user wants to get by with just setting a few variables, the following is the case.

If periodic indexing is enabled with `(setq mu4e-update-interval (* 60 5))`, then avoiding periodic getting of mail implies `(setq mu4e-get-mail-command "true")`, which implies that `C-S-u` will not get mail.

## Versions of mu, mu4e/emacs, operating system etc.

```
mu4e-mu-version ==> "1.3.1"
GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin18.6.0, NS appkit-1671.50 Version 10.14.5 (Build 18F132)) of 2019-06-02
```

## Any other detail

I think a hack solution for this might be something like the following, and bind it to a key in mu4e shortcuts.

``` elisp
(defun my-mu4e-refresh-all ()
  (interactive)
  (let ((mu4e-get-mail-command "mbsync -a"))
    (mu4e-update-mail-and-index t)))
```

**Comment by djcb** [comment]
Hmmm, you solved your problem yourself already, or?

**Comment by bradyt** [comment]
I was hoping for something like `(setq mu4e-get-mail-on-C-S-u-but-not-update-interval t)`.

**Comment by bradyt** [comment]
Hmm, maybe I can just rebind `U` and `C-S-u` to a function that does a `let` to set `mu4e-get-mail-command` (perhaps even using the Maildir of the message at point), and then call `mu4e-update-mail-and-index`? I should do it that way to solve my issue?

**Comment by bradyt** [comment]
Ah maybe this solves my problem. Maybe there's no important request of your software here? I should close it?

``` elisp
(setq mu4e-get-mail-command "true")
(setq mu4e-update-interval (* 60 5))

(defun my-mu4e-mbsync-current-maildir (msg)
  (interactive)
  (let* ((maildir (downcase (substring (plist-get msg :maildir) 1)))
         (mu4e-get-mail-command (format "mbsync %s" maildir)))
    (mu4e-update-mail-and-index t)))

(setq mu4e-view-actions '(("mbsync maildir of mail at point" . my-mu4e-mbsync-current-maildir)))
```

**Comment by djcb** [comment]
Ah, nice you were able to solve it... I guess this could be closed then. Thanks!
