### ISSUE TITLE
Trashed message shown only after index being rebuit

### ISSUE THREAD

**Issue by gongzhitaao** [djcb/mu#1433]
## Setup

I use `mbsync` with `mu`.

## Problems

1. If I trash a message on the server side via the web client, everything works fine (the only thing is that no trash flag is set, that's fine).
2. If I trash a message via mu4e (i.e., `d` in the message header view), then
    1. before `mbsync`, the trashed message **is** shown in the trash view.
    2. after `mbsync`, the trashed message **is not** shown anymore.  However,
        1. they still exist in the remote and local trash folder. 
        2. they just do not appear in the message header view.
        3. they will appear in the result if you search for them.

        The weird thing is that after I rebuild the index `mu index --rebuild`, everything works fine.

## Versions of mu, mu4e/emacs, operating system etc.

mu/mu4e: 1.0
emacs: 26.1
OS: ubuntu 18.04

**Comment by Chris00** [comment]
Do you have `(setq mu4e-change-filenames-when-moving t)`?

**Comment by gongzhitaao** [comment]
@Chris00 Yes.

**Comment by djcb** [comment]
Hmmm, do you happen to use a `.noupdate` file in the trash folder?

**Comment by gongzhitaao** [comment]
@djcb No.  The problem seems to be that whatever I do on other clients or through the web (e.g., trashing a mail, read a mail), that mail will not be updated in the database until I rebuilt the database.

**Comment by gongzhitaao** [comment]
I think I found the problem, the `mu4e-index-lazy-check`.
> When this is set to ‘t’, mu only uses the directory timestamps to decide on whether it needs to check the messages beneath it, **which would miss messages that are modified outside mu**.
