### ISSUE TITLE
mu4e-view-use-gnus: Loads external images, enabling tracking

### ISSUE THREAD

**Issue by hpdeifel** [djcb/mu#1434]
## Expected or desired behavior

Opening an email doesn't make any HTTP requests in the default configuration, whether `mu4e-view-use-gnus` is set or not.

## Actual behavior

Gnus loads external images in HTML emails.

This is controlled by the variable `gnus-blocked-images`, which is set to the function `gnus-block-private-groups` by default. This function seems to think that article buffers from mu4e belong to a public news group and thus allows image loading.

## Steps to reproduce

1. Set `mu4e-view-use-gnus` to `t`
2. Set `url-debug` to `t`
3. Open a HTML email which references external images
4. Watch HTTP requests going out in the `*URL-DEBUG*` buffer

## Versions of mu, mu4e/emacs, operating system etc.

- *mu*: 1.2.0
- *emcas*: 26.2
- *gnus*: v5.13

## Any other detail

The quickfix is

```
(setq gnus-blocked-images ".")
```

**Comment by MadEarl** [comment]
`(setq gnus-blocked-images "http")` 

Seems to do the right thing to me: Shows inline images and inhibits loading of external ones.
