### ISSUE TITLE
Can't open eml messages

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1436]
## Actual behavior

Just like issue #1077, I have a forwarded email as an eml attachment. Opening the message in `mu4e-viewer` I get the errors
```
error in process filter: user-error: No matches for this search query.
error in process filter: No matches for this search query.
error in process filter: mu4e-error-handler: Error 3: unknown error
error in process filter: Error 3: unknown error
``` 

I also get the exact same errors when I use the gnus-based viewer `(setq mu4e-view-use-gnus t)`.

## Versions of mu, mu4e/emacs, operating system etc.
Emacs 26.2
mu  1.3.2

**Comment by djcb** [comment]
Hmmm, can't reproduce that.. Are you sure `(setq mu4e-view-use-gnus t)` is set?

**Comment by haji-ali** [comment]
Yes, I am sure I set it correctly. The correct gnus viewer is also opened instead of the mu4e one. 
The attached message shows me the same problem. Does it work for you?

[tmp:2,S.tar.gz](https://github.com/djcb/mu/files/3329147/tmp.2.S.tar.gz)

**Comment by Chris00** [comment]
I tried it and when I press ENTER on the elm message, it display correctly.
![elm](https://user-images.githubusercontent.com/1255665/60386606-69f65000-9a97-11e9-8cdd-687645894466.png)

**Comment by haji-ali** [comment]
Oh. I just tried that and you are right, it does work. Even though I was using `gnus` I was opening the attachment by pressing `o` then selecting `1` which gave the errors I mentioned. I didn't know that opening attachments is different in gnus vs mu4e (I am still not sure sure how to save attachment without mu4e).

I will close the issue, but I think it would be good to unmap the mu4e keybindings when setting `mu4e-view-use-gnus` to `t`
