### ISSUE TITLE
Use special rather than fundamental, for raw view and loading

### ISSUE THREAD

**Issue by bradyt** [djcb/mu#1443]
Would be nice if `q`, `n`, `p`, worked in ` *mu4e-raw-view*` and ` *mu4e-loading*`. If I understand correctly, using special rather than fundamental may be more idiomatic. Perhaps that is enough justification?

**Comment by djcb** [comment]
The raw-view uses `view-mode`, and I update the loading-mode to derive from special-mode. Those keys are not supported though, and that's by design.

Thanks!
