### ISSUE TITLE
Mu's Xapian databse should be in XDG_DATA_HOME not XDG_CACHE_HOME

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#1446]
## Expected or desired behavior

Starting up mu4e or manually calling mu post the updates should not fail because my XDG_CACHE_HOME is pointing at my tmpfs mount.

## Actual behavior

mu fails asking for database to be re-indexed after a boot.

## Steps to reproduce

Update to latest HEAD
Set XDG_CACHE_HOME to /tmp/$USER/cache
Run mu

## Versions of mu, mu4e/emacs, operating system etc.

710b6daf1e5f6c484d9b9cd5918b7cfdd44efe27

## Any other detail

According to the freedesktop spec:

    $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored.
    
I don't think the database itself falls in this category as it is a) essential and b) should persist. The logs and cached lookups would be find there but the database can take some time to update from scratch. Mine for example is about 30G

    30G     /home/alex/.cache/mu/

**Comment by djcb** [comment]
The database _is_ cached data though; it can be recreated automatically and shouldn't be backed up etc.  

I agree that it doesn't work nicely if your cache-dir  lives on `tmpfs`, but when I look at my ~/.cache, it seems the expectation is that it's persistent. So perhaps putting it on tmpfs is a bit of a special case, for which mu allows you to override these dirs (`--muhome`)?

Anyway, we can change the location XDG_DATA_HOME if your setup is very common. Perhaps poll on the mailing-list?

**Comment by A6GibKm** [comment]
The folder `~/.mu` is installed by default in one of `XDG_{DATA,CACHE}_HOME/.mu`? Mine is at `~/.mu` even though I have set `XDG_DATA_HOME` to `~/.local/share`. Deleting it a running mu creates it again. 

For the momment I will just set `(setq mu4e-mu-home "~/.cache/mu")`

**Comment by jschwab** [comment]
This was a recent change (632f383c38b0cd0cdb22b36f9d2797fce20e0cb0), so if you're not running a development version of mu, you'll have the old behavior.

**Comment by djcb** [comment]
@stsquad: is this still an issue? I suppose we could make a compile-time setting for this.
