### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by jubalh** [djcb/mu#1447]
Hi!
I'm a bit confused about the releases right now.
On https://github.com/djcb/mu/blob/master/NEWS.org I can see 1.2 and then the unreleased 1.4. So I assume that 1.4 should be the next stable after 1.2?
On https://github.com/djcb/mu/releases I can also see the latest 'release' is 1.2. But tags have been made for 1.3.1 and 1.3.3.

Are they supposed to be packaged?

**Comment by djcb** [comment]
1.4 is the future stable release, 1.2 is the current stable release; 1.3 releases (tagged/packaged or not) are just for development

**Comment by jubalh** [comment]
Thanks for clarification!
