### ISSUE TITLE
mu4e creates PGP/MIME messages that appear broken to enigmail

### ISSUE THREAD

**Issue by averter** [djcb/mu#1449]
## Expected or desired behavior
To be able to exchange encrypted emails with thunderbird+enigmail users. 

## Actual behavior
When sending an encrypted email to myself I can read it with mu4e but not with enigmail. The same happens when sending it to another enigmail user. First, the message shows
"this is a broken pgp/mime message from MS-Exchange. If you cannot access the attachments or have problems with replying or forwarding, press the "repair message" button to fix the message". Second, after pressing the button a rather vague "Decryption incomplete" error log shows up and the message cannot be read.

## Steps to reproduce
just sending an encrypted message (even without any attachmentt) and reading it on thunderbird with enigmail should be enough. Relevant entries of my encryption setup are

````elisp
     (require 'epg-config)                           ; for mu4e
     (setq mml2015-use 'epg                          ;    "
	   mml2015-sign-with-sender t                ;    "
           mml2015-encrypt-to-self t
	   epg-user-id "gpg_key_id"                  ;    "
	   epg-gpg-program "gpg2"                    ; program for encryption
	   ;;auth-source-debug t                       ; debug
	   auth-sources '("~/.authinfo.gpg"))        ; Auth-source file

       (add-hook 'mu4e-view-mode-hook
		 (defun my-view-mode-hook ()         ;; SIGNING AND ENCRYPTING
		   (epa-mail-mode)))                 ;; SIGNING AND ENCRYPTING

````

## Versions of mu, mu4e/emacs, operating system etc.
Enigmail v 2.0.12, Thunderbird v 60.8.0
Emacs v 25.2.2 and mu4e v 0.9.18

## Any other detail
Messages sent with pgp/mime from within Thunderbird can be read by enigmail without any problem

**Comment by averter** [comment]
As usual it's a problem caused by the %#&!/ Microsoft. Can't even (and don't want to) imagine what they'll do to github.

**Comment by Chris00** [comment]
@averter Would you care giving some details?  That may help others stumbling on this issue.

**Comment by averter** [comment]
People are experiencing the same issue [elsewhere](https://social.technet.microsoft.com/Forums/en-US/c5059734-5031-4d82-96eb-c74fe60b5e9e/quotthis-is-a-broken-pgpmime-message-from-msexchangequot?forum=Exch2016MFSM). What really baffles me is that the email is decrypted correctly from within mu4e. Very strange. I couldn't find a perfect solution, but as a quick alternative one can use pgp-inline.
