### ISSUE TITLE
mu/mu4e: inconsistent phrase query behavior on from field

### ISSUE THREAD

**Issue by bsdf** [djcb/mu#1451]
## Expected or desired behavior

When searching with a phrase query on the `from:` field according to the documentation, I should be able to return phrase results containing spaces. The same queries run in `mu4e` should also return the same results as their `mu` equivalents.

## Actual behavior

Inconsistent behavior between `mu` and `mu4e`. Additionally, phrases with spaces don't appear to work at all in `mu4e`.

## Steps to reproduce

1. Execute the following `mu` invocations
```sh
mu find from:"Bank of America"
mu find from:Bank\ of\ America
mu find from:/Bank.*of.*America/
```
2. Observe that the expected results are returned.
3. Execute the following mu invocation
```sh
mu find from:/Bank.of.America/
```
4. Observe that the expected results are NOT returned
5. Execute the following queries in emacs with `M-x mu4e-headers-search`
```elisp
from:"Bank of America"
from:Bank\ of\ America
from:/Bank.of.America/
```
6. Observe that no results are returned.
7. Execute the following queries in emacs with `M-x mu4e-headers-search`
```elisp
from:/Bank.*of.*America/
```
8. Observe that the expected results are returned

## Versions of mu, mu4e/emacs, operating system etc.

OS: Debian sid
mu version: 1.2.0
emacs version: GNU Emacs 27.0.50

**Comment by djcb** [comment]
The shell handle spaces, `*`-expansion etc. in its own way (and the details are shell-specific, e.g. between bash and zsh), before mu sees it. in mu4e we get the query as you type it.

**Comment by bsdf** [comment]
So what exactly is `mu4e-headers-search` expecting to get the proper results? My real issue is that mu4e is not returning the results I expect, the `mu find` invocations are just there to confirm that I do have matching messages in my index.

**Comment by djcb** [comment]
Check the `mu-query` manpage. And note that `mu4e-headers-include-related` influences the messages you get in mu4e.

**Comment by bsdf** [comment]
I consulted the documentation before opening this ticket and according to it, `from:"Bank of America"` and `from:/Bank.of.America/` should return results containing the phrase `Bank of America` when executing `mu4e-headers-search`. They return *no* results despite having confirmed that there are messages in my index that match.

**Comment by djcb** [comment]
Okay, found this old ticket, sorry for the delay.  There have been many changes, but at least with 1.7.27 you can find it using quotes; 

```
mu find from:"Bank of America"
```
as per the unit-test:
    https://github.com/djcb/mu/blob/master/lib/tests/test-mu-store-query.cc#L132
careful with quoting.

Hence, closing this.
