### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by leafpile** [djcb/mu#1452]
## Actual behavior

Build stops with `libtool:   error: cannot build a shared library See the libtool documentation for more information. Fatal configuration error.`

## Steps to reproduce

Checkout at 1.3.3 and build

## Versions of mu, mu4e/emacs, operating system etc.

Arch Linux 5.2.2

```
mu version                           : 1.3.3
Xapian version                       : 1.4.11
GLib version                         : 2.60.5
GMime version                        : 3.2.3
Json-Glib version                    : 1.4.4
Guile version                        : 2.2
Emacs version                        : GNU Emacs 26.2
```

## Any other detail

[build log](https://gist.github.com/leafpile/97ea187f5fb29603cf236cca3bee8626)

I think I'm missing something here because I also failed to build mu 1.2, with
```
Making all in parser
make[3]: Entering directory '/home/xjc/mu/lib/parser'
  CXX      xapian.lo
  CXXLD    libmuxparser.la
  CXXLD    tokenize
/usr/bin/ld: tokenize.o: in function `main':
/home/xjc/mu/lib/parser/tokenize.cc:33: undefined reference to `Mux::tokenize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
```

Did I miss some dependencies?

**Comment by nils-schween** [comment]
Try to build it with the following command:
./autogen.sh && ./configure --enable-shared && make
I had the same problem:
https://groups.google.com/forum/#!topic/mu-discuss/iosQX8C5wzI

Greets, Nils

**Comment by leafpile** [comment]
That worked :)  Thanks Nils!!
