### ISSUE TITLE
mu4e~compose-mail doesn't implement switch-function

### ISSUE THREAD

**Issue by ra1nb0w** [djcb/mu#1454]
## Expected or desired behavior

Should be nice to respect `compose-mail-other-window` and `compose-mail-other-frame` and therefore compose the e-mail in a new window or frame respectively.
[mu4e~compose-mail](https://github.com/djcb/mu/blob/2beb2eda02ee91fdc15ddabf5b2d1780f2537447/mu4e/mu4e-compose.el#L815) doesn't implement the checks on `switch-function`.

## Actual behavior

The mail buffer is still in fundamental mode and not new window or frame is created.

## Steps to reproduce

Configure emacs with
```elisp
(setq  mail-user-agent 'mu4e-user-agent)
```
and then use one of the following command
- `compose-mail-other-window` for a new window (default keybind `C-x 4 m`)
- `compose-mail-other-frame` for a new frame (default keybind `C-x 5 m`)

## Versions of mu, mu4e/emacs, operating system etc.

- mu 1.2
- GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.5.0, NS appkit-1671.40 Version 10.14.4 (Build 18E226)) of 2019-04-13
- macOS 10.14.6 18G84
- Xcode 10.3 10G8 - Apple LLVM version 10.0.1 (clang-1001.0.46.4)

## Any other detail
The _upstream_ function is visible at this [link](http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/gnus/message.el#n6654) but I am not sure how to implement it into mu4e. Maybe some advice can help me to create the patch.

thanks

**Comment by sje30** [comment]
Can't this ticket be closed too if the code mentioned in #2184 also now works?

**Comment by djcb** [comment]
With the new (experimental) composer, `C-x 4 m` and `C-x 5 m` now work.

As for #2184, `mu4e-compose-in-new-window` has been generalized to `mu4e-compose-switch`.

Note: mu4e 1.11.23 has a new composer that is much closer to gnus' one, so various message- settings have better odds to work in mu4e as well.
