### ISSUE TITLE
fatal error: mu-store.hh: No such file or directory

### ISSUE THREAD

**Issue by tpapp** [djcb/mu#1457]
## Expected or desired behavior

Compiling from the git repo, as described in `HACKING` (incl `autogen.sh`).

## Actual behavior

Compilation fails with

```sh
In file included from mu-index.c:26:
mu-index.h: At top level:
mu-index.h:28:10: fatal error: mu-store.hh: No such file or directory
 #include <mu-store.hh>
```

## Versions of mu, mu4e/emacs, operating system etc.

Ubuntu 19.04, mu `master` (5c5716d3f03f977144cf4c07ddbb1be61f87f4b3), Emacs 26.2 (but this is just a compilation problem).

**Comment by djcb** [comment]
D'oh. Missing file.
