### ISSUE TITLE
travis CI build link in README

### ISSUE THREAD

**Issue by tpapp** [djcb/mu#1458]
I was surprised that #1457 was not caught by CI, but could not find the Travis log. Perhaps in include a clickable button like most repositories these days? The Travis interface can provide the link.

**Comment by tpapp** [comment]
Looking at the PRs, I am not even sure Travis is enabled.

@djcb: I am happy to help out with making CI work, but as the repo owner it is best if you do the initial setup.

**Comment by djcb** [comment]
I have no experience with Travis.. there's an existing `.travis.yml`, if you have the knowledge to make that work again, that'd be great. Do you want to do this?

(IIRC, it worked for a while, but then stopped worked when mu had some deps that were too new for travis. Perhaps that has changed)

**Comment by tpapp** [comment]
I would be happy to help out with this, but as the repo owner, can you check on Travis that it is enabled and link the badge in the README? The Travis interface provides markdown for this.

Generating the coverage info would also be nice, following 12b34be3cf, I can also help with that.

**Comment by djcb** [comment]
@tpapp: thanks, that's great! 

The build is currently not enable on Travis (since 2 years) because it wasn't working. Do you have some hints of what should change in `.travis.yml` to make it work?

**Comment by tpapp** [comment]
I don't see any obvious problems, so I think it would be best to re-enable it, and then link the Travis page which has the logs in this issue, so it could be investigated.

**Comment by djcb** [comment]
Note, we have the CI setup now, so you can track: https://github.com/djcb/mu/actions
