### ISSUE TITLE
Not compiling on Ubuntu 18.04 due to incompatible Xapian version

### ISSUE THREAD

**Issue by dochego** [djcb/mu#1459]
## Expected or desired behavior

Prior to the version bump to 1.3.4, mu compiled fine on Ubuntu 18.04 with the default xapian version (1.4.5)

## Actual behavior

Compilation fails:

    mu-store.cc: In function ‘MuStore* mu_store_new_readable(const char*, GError**)’:
    mu-store.cc:419:53: error: expected unqualified-id before ‘&’ token
             } catch (const Xapian::DatabaseNotFoundError& dbe) {

Installing Xapian  1.4.10 (via ppa:xapian-backports/ppa) allows it to compile fine.

It seems that mu 1.3.4 now requires a minimum Xapian version >1.4.5 (1.4.10?). At the moment only xapian >=1.4 is required.

**Comment by sachdevaprash** [comment]
I can confirm the compilation error, and the solution (using Xapian 1.4.10).

**Comment by dochego** [comment]
Commit 74f9f78  seems to have fix this.
