### ISSUE TITLE
mug.c not compiling due to missing mu-store.h

### ISSUE THREAD

**Issue by dochego** [djcb/mu#1460]
## Actual behavior

In mu 1.3.4, mug.c includes mu-store.h, but the file is not in the repro.

Compilation fails with

    mug.c: At top level:
    mug.c:29:10: fatal error: mu-store.h: No such file or directory
     #include <mu-store.h>

The rest of the code (except mug) compiles fine.

**Comment by djcb** [comment]
Does it help when you replace mu-store.h with mu-store.hh?

**Comment by dochego** [comment]
No, I now get an error in mug-msg-list-view.c

    mug-msg-list-view.c: In function ‘mu_result_to_mug_error’:
    mug-msg-list-view.c:312:7: error: ‘MU_ERROR_XAPIAN_DIR_NOT_ACCESSIBLE’ undeclared  (first use in this function); did you mean ‘MUG_ERROR_XAPIAN_NOT_UPTODATE’?
      case MU_ERROR_XAPIAN_DIR_NOT_ACCESSIBLE:

**Comment by djcb** [comment]
Hmm... I did a quick port to a the newer webkit2gtk... does that work for you? You'll need to have webkit2gtk installed

**Comment by dochego** [comment]
That works for me, brilliant! Thanks!
