### ISSUE TITLE
Error in new mu4e view using gnus

### ISSUE THREAD

**Issue by theophilusx** [djcb/mu#1461]
## Expected or desired behavior

This is just FYI and recording. As mu4e-view-use-gnus is an experimental setting, I would not consider this to be a production error.

While in the message view buffer, C-h b should show mode bindings. Discovered this when I tried entering 'c', which I thought was bound to a command and got a 'stringp nil' error.

## Actual behavior

Hitting C-h b should open a help buffer listing the major and minor mode key bindings. 

Backtrace of error -

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  gnus-article-describe-bindings()
  funcall-interactively(gnus-article-describe-bindings)
  #<subr call-interactively>(gnus-article-describe-bindings nil nil)
  apply(#<subr call-interactively> gnus-article-describe-bindings (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> gnus-article-describe-bindings nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (gnus-article-describe-bindings nil nil))
  call-interactively(gnus-article-describe-bindings nil nil)
  command-execute(gnus-article-describe-bindings)

## Steps to reproduce

Load mu4e
Set mu4e-view-use-gnus t
M-x mu4e
Go to inbox with ji
Hit return on message to get to message view buffer
Enter C-h b

## Versions of mu, mu4e/emacs, operating system etc.
mu version 1.3.4 from Git
Emacs version 26.2.90 and Emacs 27.0.50

## Any other detail

Also get error in emacs 27.0.50. Stripped my config to the minimum - only loading mu4e and my mu4e configuration and still got the error.  Issue does not occur if mu4e-view-use-gnus is nil.

**Comment by djcb** [comment]
There have been a bunch of fixes for this... closing this for now. Feel free to reopen if this still happens.
