### ISSUE TITLE
mu4e slow under MacOS

### ISSUE THREAD

**Issue by sroertgen** [djcb/mu#1464]
## Expected or desired behavior
Mails should be loading fast when cycling through the headers view.
Some are loading fast, others take about 5 to 15 seconds to load. During the "Waiting for message..." I'm not able to go to next or previous message.

## Actual behavior
Some mails take about 5-15seconds to load.

## Versions of mu, mu4e/emacs, operating system etc.
mu4e 1.3.2
mu 1.3.2
emacs 26.2
MacOS (Mojave 10.14.6)
offlineimap 7.4.2

## Any other detail
I installed emacs and mu4e with the exactly same setup on an Ubuntu (18.04) machine. There mu4e is fast and I can cycle through the messages without any problems.

On MacOS (Mojave 10.14.6) the `mu find "hello"` is incredibly fast. I already added 

```
(setq
   mu4e-headers-show-thread nil
   mu4e-headers-include-related nil
   mu4e-index-cleanup nil
   mu4e-index-lazy-check t)
```

to my emacs config. Didn't make any difference. 

Don't know what else I can try out.

**Comment by djcb** [comment]
Are the slow messages always the same? Or is that sometimes, loading any message is slow, while at other times, it is not? What's the value of `mu4e-update-interval`?

**Comment by sroertgen** [comment]
Hello,
thanks for the reply and I'm sorry for the late response.

Yes, it seems to be always the same messages. But it's quite a lot messages, just some are loading fast. `mu4e-update-interval` is set to `300`

**Comment by djcb** [comment]
Anything specific about those messages? It might be some html-rendering issue. Perhaps you can attach such a message (censored as needed, of course...)

**Comment by sroertgen** [comment]
I checked about this and it does not depend on the email itself nor on the sender. But it seems to be an issue with emails that are signed. Now that I paid attention it seems that not every signed email is loading slow, but if the email is loading slow it is a signed email. Sorry that I didn't notice that earlier.

**Comment by djcb** [comment]
Ah, perhaps it's trying to verify the signature using some external server?
`mu4e-auto-retrieve-keys` might be involved (if non-nil).

Also, does the behavior change with `(setq mu4e-view-use-gnus t)`?

**Comment by sroertgen** [comment]
sorry for late response (again)! `(setq mu4e-view-use-gnus t)` does not change the behaviour. `mu4e-auto-retrieve-keys` is set to nil. How comes it is slow under MacOS, but is working fast on Ubuntu?

**Comment by handstad** [comment]
I also experience sometimes on MacOS that it takes around 4-5 seconds to open an email. Nothing special about those emails that I can see (not signed, html or similar). But I have not investigated this systematically.

**Comment by djcb** [comment]
It could be that you open while indexing is underway. Are always the same messages slow?

**Comment by handstad** [comment]
I haven't seen any pattern to this. It does not happen super-often, so I have just accepted it. But I can try to note down if this slowness affects the same messages or if there is some other repeating pattern to this.

**Comment by djcb** [comment]
Note, with 1.4.5, reading signed messages should be quite a bit faster -- can you confirm?

**Comment by handstad** [comment]
I can at least say that all messages signed in the normal way with `signature.asc` file attached have no speed problems at all. I only see slowness with those signed with `smime.p7s`.  (I have limited competence in this area). You can probably close this ticket for my part. Thank you for maintaing this excellent software!

**Comment by djcb** [comment]
Okay, closing this then -- we have a few similar tickets anyway. If you still see slowness in specific case, feel free to open a new ticket of course.
