### ISSUE TITLE
Can I use mu to index old archived emails?

### ISSUE THREAD

**Issue by jtraer** [djcb/mu#1466]
## Expected or desired behavior

I have several folders full of .emlx messages, some of which are from mail accounts that no longer exist.  Can I index these with mu so that I can search these messages in mu4e, as I do with my active email accounts?

## Actual behavior

I placed these folders in '~/Maildir' and ran 'mu index' but 'mu find' did not return any data from them.

I restructured one folder as a test, and moved all the .emlx files to '~/Maildir/old_email/INBOX/cur/' and when I ran 'mu index' received the errors: 'mu: message seems invalid, ignoring (PATH/TO/FILE.emlx)' for every file.

I tried changing .emlx to .eml, and received the same error message when I tried to index.  

Any suggestions would be greatly appreciated.  

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 1.0-alpha0
GNU Emacs 27.0.50
Ubuntu 18.04.3

**Comment by djcb** [comment]
The files must be in proper email file, and I don't think emlx is... but apparently you can convert them: http://mike.laiosa.org/software/emlx2maildir/

**Comment by jtraer** [comment]
Thanks for this advice! I have been busy with other projects and have not yet fully implemented this but the .emlx converter has offered some hope. I ran it on a few folders and they are now recognized by mu, which is an improvement.
