### ISSUE TITLE
Mu server process ended with exit code 53 on Windows 10 cygwin

### ISSUE THREAD

**Issue by johanthoren** [djcb/mu#1467]
## Expected or desired behavior

When launching mu4e I would expect to see the overview.

## Actual behavior

After successfully installing mu through Cygwin, using this guide: https://frosch03.de/blog/2016/05/mu4e-within-cygwin.html

I was able to run `mu index --rebuild -m ~/.mail` without any problems. Works just as expected. However, launching mu4e gives the following backtrace in Emacs:
```
Debugger entered--Lisp error: (error "Mu server process ended with exit code 53")
  signal(error ("Mu server process ended with exit code 53"))
  error("Mu server process ended with exit code %d" 53)
  mu4e~proc-sentinel(#<process  *mu4e-proc*> "exited abnormally with code 53\n")
```

## Steps to reproduce

1. Compile and install mu using the guide linked above.
2. Do an initial index.
3. Launch mu4e from within Emacs.

## Versions of mu, mu4e/emacs, operating system etc.

mu version: mu (mail indexer/searcher) version 1.3.4
emacs version: GNU Emacs 26.2 (build 1, x86_64-w64-mingw32) of 2019-04-13
Windows 10 x64

## Any other detail
Relevant settings:
```
(add-to-list 'load-path "c:/cygwin64/usr/local/share/emacs/site-lisp/mu4e")
(setq mu4e-mu-binary "c:/cygwin64/usr/local/bin/mu.exe")
```

I would be very happy to hear that it's user error, since I've never before set this up on Windows. If so, please point me in the right direction.

Wouldn't want to be without mu4e.

**Comment by djcb** [comment]
Hmmm... what happens when you run `mu server` from the command-line?
