### ISSUE TITLE
Draft flag for draft not composed with mu4e

### ISSUE THREAD

**Issue by matzebond** [djcb/mu#1472]
## Expected or desired behavior

Messages in the draft folder as is set by `mu4e-drafts-folder` should automaticaly get the tag `draft` so that `mu4e-compose-edit` works on these files.

## Actual behavior

I can't edit messages with `mu4e-compose-edit` with were not started with mu

## Steps to reproduce

Make draft with an other mail client e.g. phone and try to `mu4e-compose-edit` this message in emacs.

## Versions of mu, mu4e/emacs, operating system etc.
latest mu4e on emacs and linux

**Comment by djcb** [comment]
The message file must have the 'D' flag as per the Maildir standard to be considered a Draft message; and mu only cares about that for the messages, not about in what folder it lives.

I can see it'd be useful for _something_ to add that flag... I guess the synchronization program could do it, or perhaps with a script...

There are no plans to add this to mu4e at this point, so closing this for now.

**Comment by miquelraynal** [comment]
Hello, I've seen several reports mostly leading to the conclusion that "mu4e does not care about the folder but cares about the Draft flag". While I understand the idea -strictly following the RFC-, it makes it very unpractical to use with external software that might fill-in some drafts and forget to set that flag. Very much like the "Seen" flag, would it be possible to have a solution that at least fixes the situation? Either a property allowing to edit messages without the "Draft" flag, or maybe something that modifies (perhaps even duplicates the message, adds the flag, and deletes the previous version) the message to allow editing? That would be very helpful.

**Comment by djcb** [comment]
@miquelraynal: there's `mu move`. Alternatively, fix the external software.

**Comment by djcb** [comment]
`man mu-move` works for me at least.
