### ISSUE TITLE
mu4e: removing signature seperator

### ISSUE THREAD

**Issue by lugubris** [djcb/mu#1475]
## Expected or desired behavior

I want the signature seperator to be disabled when composing a message.

## Actual behavior

`--` is used as a seperator.

## Steps to reproduce

compose a message with signature set and add signature.

## Versions of mu, mu4e/emacs, operating system etc.

GNU Emacs 26.2
mu (mail indexer/searcher) version 1.2.0
mu4e-1.2_2
Void Linux x86_64

**Comment by djcb** [comment]
You can do it manually in many different ways (this is emacs after all), but the mu4e facilities try to follow guidelines in the RFC 3676, as a bit of politeness to the recipient of the message. Practically, mu4e uses gnus' `mail-signature` facility for this, which always puts that in.

If you do _not_ want that, you can simply choose not to use mu4e's signature facility, and insert your own blob of text in e.g. `mu4e-compose-mode-hook`.
