### ISSUE TITLE
Address autocompletion does not work

### ISSUE THREAD

**Issue by jmburgos** [djcb/mu#1476]
Hi Dirk-Jan,

Thank you for mu4e! I have been using it for a long time and it is great.

Now I am having an issue.  After upgrading my machine to Fedora 30 and installing mu4e version 1.3.4 (from 0.9x), autocompletion in mu4e is not working.  Nothing happens when pressing TAB in the To: field.  A "No matches" message appears in the minibuffer.

On the other hand, mu finds the addresses with no problem.
I was able to do this by running emacs with a minimal configuration that only loads mu4e and sets the basics.

I am using mu version 1.3.4 and mu4e version 1.3.4. on Fedora 30.

Any help would be welcomed!

Julian

**Comment by jmburgos** [comment]
I went back to version 1.1 and autocompletion works.

**Comment by jschwab** [comment]
The most recent stable release is 1.2.  Does it work for you there?

(Version 1.3.X is a development version.)

**Comment by livnev** [comment]
I've experienced the same problem: I think it's related to #1016, and it does not appear to have been fixed. I am able to work around the issue by running `(mu4e~request-contacts)` whenever I come across it.

**Comment by jcguu95** [comment]
It's weird! I got into mu4e starting from yesterday, and was quite happy with the workflow -- at least autocomplete worked for me.

And then today it stopped working! I then rebooted my laptop, and nothing changed! I don't know what was wrong with it.

Also, some weird bug happened this morning (~9 hours ago). As I typed `M-x mu4e`, it refused to open with the reason that "my server is of version 1.2.0 but it needs 1.3.4". I got over it by rebooting my emacs. It still showed up a few more times, but never showed up this afternoon (~5 hours ago). I could not reproduce that bug.

@livnev would you mind telling me how you run `(mu4e~request-contacts)`? Is it by `M-x mu4e~request-contacts`? This did not work for me..

**Comment by djcb** [comment]
@jcguu95 the server version error happens when you mix different versions of mu / mu4e. You probably have some other version lying around; remove that or at least make sure the versions match.

There's no `mu4e~request-contacts` in current versions, and shouldn't be need now either, but you could try `M-: (mu4e~requests-contacts-maybe) RET`. What does it tell you?

**Comment by jcguu95** [comment]
It returns `[mu4e] Contacts updated: 1172; total 1`. I tried autocompletion immediately afterward, and it still did not work.

As for the version problem.. it seems to me that the newest version of `mu` is `1.2.0`. I got that from the released tarball. And if I am not mistaken, `mu4e` came with that tarball with version `1.3.4`.

**Comment by djcb** [comment]
This has changed since... can you check with the latest mu4e? There's also `M-x mu4e-contacts-info` now , which could shed a light on this...

**Comment by m-falconi** [comment]
Autocompletion works erratically for me in both 1.2.0 and 1.3.5 . In the latter version, invoking the command mu4e-contacts-info shows a (correct) list of contacts, as well as pressing TAB without any character in the To: field. However, if I try the first letters of some email addresses and then press TAB, such addresses are not found (even though they are present in the list).

**Comment by djcb** [comment]
That's likely due to the way helm is set up, in particular the matching method... perhaps you need fuzzy matching? But note that I don't use helm.

In any case, it seems helm does get all the matches, after that mu4e isn't really involved any more.

**Comment by livnev** [comment]
I had this issue previously on occasion, but running `(mu4e~request-contacts)` would fix it. I have upgraded to 1.2 and now `(mu4e~request-contacts)` is gone and I have the following (new) error:

```
In ‘completion-at-point’ source: ‘#[0 \307\300\301\305\306\304\203\0\303\204\0
\202\0\310%\311\302"\207 [#[771 \307\300\301\302\242\206\0G\304%\310!\211A\211\203\0\211\311\241\210\202 \0\312\262\313=\205-\0\314\304\315"\311\302\242\2037\0\302\311\240\210\306\242\204@\0\306\240\210\205E\0\316\317!\262\203[\0G\320X\203[\0\321\262\322\203f\0!\202g\0\303\305#\207 [mu4e~compose-complete-handler nil (maria) nil (metadata (display-sort-function . identity) (cycle-sort-function . identity)) t (nil) completion-all-completions last nil 0 emacs completion-metadata-get display-sort-function t copy-sequence 1 #[257 \300\301"\207 [sort string-lessp] 4 

(fn ALL)] helm-completion-in-region--initial-filter helm-completion-style helm-completion--sorting-done] 12 

(fn STR PREDICATE ACTION)] nil nil nil t nil t helm-comp-read-get-candidates  helm-cr-default helm-pattern] 6]’ 
 (wrong-number-of-arguments (1 . 1) 2)
```

`mu4e-contacts-info` seems to correctly display a list of contacts.

**Comment by m-falconi** [comment]
I have the same behavior with Helm as livnev describes. 

What is the function called by pressing TAB in mu4e-compose? 

I would like to disable Helm on it, but  I am not able to find the proper name.

**Comment by livnev** [comment]
@m-falconi I've discovered that downgrading `helm` to `v3.5.0` works, and I made an issue on the helm project to investigate further.

**Comment by m-falconi** [comment]
Thanks! Let me remark that the newest helm version screwed up other
completions: insert-char (C-x 8 RET) gives an error very similar to the one
given by address completion in mu4e.

**Comment by livnev** [comment]
`helm` [fixed](https://github.com/emacs-helm/helm/issues/2231) something which made this issue go away from me, though I can't speak to those earlier in this thread who may have been having a different issue.

**Comment by djcb** [comment]
Okay, this seems an helm issue then. Hope they get it fixed!

**Comment by chongchonghe** [comment]
Experiencing similar issue (driving me nuts) after I switched to multiple emails with contexts. 

### My solution
`(setq mu4e-compose-complete-only-personal nil)`

### Explaination
The default value for `mu4e-compose-complete-only-personal` changed to `t` somehow, and doing `mu cfind --personal | wc -l` on my computer returns 0, which means none of my contacts are identified by mu as personal.

**Comment by djcb** [comment]
Hmm, the default value for `mu4e-compose-complete-only-personal` is `nil`, there shouldn't be a need to change that.

**Comment by jmburgos** [comment]
I just switched to mu version 1.4.6. (I still was using 1.1) and autocompletion did not worked until I removed  
`(setq mu4e-compose-complete-only-personal t)
`
from my .init file.
