### ISSUE TITLE
Draft emails are indexed with Dec 31, 1969 (unix epoch)

### ISSUE THREAD

**Issue by situmam** [djcb/mu#1477]
## Expected or desired behavior
Draft messages should be listed in the configured drafts folder. 

## Actual behavior
Drafts are not listed in the drafts folder as expected. I did some investigation and found the cause.  Draft emails are indexed and tagged with the epoch unix time stamp so mu4e doesn't list them because the date is too old (there is a setting the prevents mu4e from showing emails before a certain date. Unfortunately, I can't find the variable's name)

It is important to note that drafts created by gmail (I'm using mbsync/gmail/mu4e combot) are showing up in the drafts folder because mu indexed them with the right date.

## Steps to reproduce

1. create a new email using mu4e
2. add some basic content then ctrl-c ctrl-d to postpone it.
3. jump to drafts folder and notice that this e-mail is missing

Launch a terminal and using mu find command locate the e-mail and notice the epoch unix time stamp on that draft.

## Versions of mu, mu4e/emacs, operating system etc.
mu4e and mu- 1.3.4
emacs - 26.1
OS: Debian buster

**Comment by situmam** [comment]
I noticed if I toggle  `set mu4e-auto-include-date` on, each draft has a date and that fixes the problem. I'm not sure if this is a bug now or just a misbahaviour caused by lack of dependency between configuration.

**Comment by djcb** [comment]
Messages can get their Date: header either when creating the draft (if `mu4e-compose-auto-include-date` is `t`), or when sending the message (which is the default); you can decide which one works best for you.
