### ISSUE TITLE
Error in process filter due to gnus article mode

### ISSUE THREAD

**Issue by averter** [djcb/mu#1478]
## Expected or desired behavior
Open and read emails from the mu4e-headers list.

## Actual behavior
When opening an email there are two recurrent errors:
`error in process filter: [mu4e] Cannot find message in headers buffer`
and
`error in process filter: mu4e-error-handler: Error 70: cannot read /home/myusername/Mail/myemail@gmail.com/new/1567700602.8404_1.mypcname,U=68:2,
error in process filter: Error 70: cannot read /home/myusername/Mail/myemail@gmail.com/new/1567700602.8404_1.mypcname,U=68:2,`

## Steps to reproduce
Steps
Simply opening a new email. 
Other notes:
- It seems to happen only on email which has not been read and only when gnus-article mode is active. 
-When I try to open the email a second time it sends another error
`error in process filter: mu4e~headers-docid-pos: Variable binding depth exceeds max-specpdl-size`
-when I close emacs and open it again the unopenable email disappears and I have to rebuild the mail tree from scratch.
- since it might have to do with how gnus sees html I am appending a relevant section of my init.el file below

````emacs-lisp
       (setq mu4e-maildir "~/Mail"                                                   ;; Mail directory where mu4e  finds accounts/emails
	     mu4e-attachment-dir "~/Downloads"                                       ;; save attachment directory (this can also be a function)
	     mu4e-get-mail-command "mbsync -cV ~/.mbsyncrc gmail"        ;; Get mail with mbsync
	     mu4e-change-filenames-when-moving t                                     ;; NEEDED FOR MBSYNC
	     ;; mu4e-html2text-command "w3m -dump -T text/html -cols 92 -o display_link_number=true -o auto_image=false -o display_image=false -o ignore_null_img_alt=true"
	     mu4e-shr2text "w3m -dump -T text/html -cols 92 -o display_link_number=true -o auto_image=false -o display_image=false -o ignore_null_img_alt=true"
	     mu4e-view-show-addresses t
	     mu4e-update-interval 120
	     mu4e-view-prefer-html t
	     mu4e-decryption-policy t		; decrypt automatically
	     mu4e-hide-index-messages t
	     w3m-default-desplay-inline-images t
	     mu4e-use-fancy-chars t          ;; use 'fancy' non-ascii characters in various places in mu4e
	     mu4e-view-show-images t)        ;; show images

````

## Versions of mu, mu4e/emacs, operating system etc.
mu4e v1.3.2, emacs v25.2.2

**Comment by theophilusx** [comment]
I also see key binding errors. When I hit 'g' in the mesage view to go to the url, I get the error 'wrong-tyupe-argument; hastable-p nil

Also, you cannot list the buffer key bindings i.e. try C-h b

I logged an issue on this in #1461

**Comment by theophilusx** [comment]
Forgot to also mention that you can follow a link in an email with 'v' and C-u v opens the link in your default browser.  Feels like there is some juble in keymaps between mu4e, gnus and eww.

**Comment by averter** [comment]
Yes, I confirm that I cannot list the buffer key-bindings. I think that it would be useful to share our mu4e init.el configuration files, because probably we must add something else aside from the code below. Then we could inform new users on what has to be added/removed for gnus article view to work

````emas-lisp
;; Use gnus article view
(setq mu4e-view-use-gnus t)
````

**Comment by Chris00** [comment]
> `error in process filter: mu4e~headers-docid-pos: Variable binding depth exceeds max-specpdl-size`

This may be produced by decoding complex HTML emails.  Set your value with `mu4e-view-max-specpdl-size` (default 4096).

**Comment by Chris00** [comment]
>  how gnus sees html

Gnus has its own way.  You must configure Gnus variables, mu4e ones are not relevant here (except those locally rebound such as the one in my previous comment).

**Comment by theophilusx** [comment]
@averter while my mu4e init is quite large, the only setting relating to message viewing is mu4e-view-use-gnus. I don't set any other gnus or mu4e variable setting relating to the viewing of messages.  Likewise, I don't do any key bindings. However, I'm also not seeing the errors (though I did see them at one point when doing some searches, but cannot reproduce now). HTML messages seem to be displaying fine for me.

**Comment by averter** [comment]
> > `error in process filter: mu4e~headers-docid-pos: Variable binding depth exceeds max-specpdl-size`
> 
> This may be produced by decoding complex HTML emails. Set your value with `mu4e-view-max-specpdl-size` (default 4096).

As suggested [here](https://www.djcbsoftware.nl/code/mu/mu4e/General.html) I've increased it to 5000 and still get the same error. Should I increase it more? If so how much? 
Today I got another email with the same issue. It is difficult to reproduce because after it happens the email disappears and I need to rebuild the mail tree. Only after that the email displays normally. 

Incidentally, which gnus variables need to be configured if one used only mu4e before?

**Comment by theophilusx** [comment]
Just FYI, I don't have any gnus settings and it is working OK for me, so
I don't think there are any which you have to set.  I'm also not setting
mu4e-view-max-specpdl-size either. So either the HTML messages I receive
are not complicagted enough or it is some other issue. I do set
mu4e-headers-include-related to nil, but I wouldn't expect that to
affect message viewing.

The only variable I needed to change to switch to use the gnus display
mode was mu4e-view-using-gnus and the only real difference observed
has been that some HTML messages take longer to render.

I did do mu index --rebuild after updating mu/mu4e from the git build.

Averter <notifications@github.com> writes:

>> > `error in process filter: mu4e~headers-docid-pos: Variable binding depth exceeds max-specpdl-size`
>> 
>> This may be produced by decoding complex HTML emails. Set your value with `mu4e-view-max-specpdl-size` (default 4096).
>
> As suggested [here](https://www.djcbsoftware.nl/code/mu/mu4e/General.html) I've increased it to 5000 and still get the same error. Should I increase it more? If so how much? 
> Today I got another email with the same issue. It is difficult to reproduce because after it happens the email disappears and I need to rebuild the mail tree. Only after that the email displays normally. 
>
> Incidentally, which gnus variables need to be configured if one used only mu4e before?  


-- 
Tim Cross

**Comment by averter** [comment]
Then maybe it is some problem in how I've build mu from git. I'm putting the configuration log [here](<script src="https://gist.github.com/averter/0c1e8a5cec754caa42de53329141403e.js"></script>). Hopefully someone can spot something that I couldn't.

**Comment by averter** [comment]
I am adding here all the warnings errors from the above gist:
Warnings
````
cc1: warning: command line option '-fno-rtti' is valid for C++/ObjC++ but not for C
conftest.c:51:6: warning: conflicting types for built-in function 'memset' [-Wbuiltin-declaration-mismatch]
conftest.c:52:6: warning: conflicting types for built-in function 'memcpy' [-Wbuiltin-declaration-mismatch]
 char memcpy ();
      ^~~~~~
configure:20988: WARNING:
   *** Developers: you do not seem to have the pmccabe tool installed.
   *** Please install it if you want to run the automated code checks
	G_DEBUG=fatal-warnings,fatal-criticals,gc-friendly
````
Errors
````
error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:3485: $? = 1
configure:3474: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'; did you mean '--version'?
g++: fatal error: no input files
````

**Comment by djcb** [comment]
Note, those are just the side-effect of the various tests that `configure` does, not errors.

**Comment by averter** [comment]
All good now with version 1.3.5. Closing
