### ISSUE TITLE
HTML only mail is not correctly converted to text

### ISSUE THREAD

**Issue by dschrempf** [djcb/mu#1481]
## Expected or desired behavior

The HTML mail is converted to text and shown in the view buffer.

## Actual behavior

Only the signature is shown. The mail is shown normally when activating the HTML (rich text) mode.

## Steps to reproduce

I searched for mail and opened one search result.

## Versions of mu, mu4e/emacs, operating system etc.

    mu (mail indexer/searcher) version 1.2.0
    Copyright (C) 2008-2018 Dirk-Jan C. Binnema
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

## Any other detail

This is how the view buffer looks when using text mode.

    From: xxx
    To: yyy
    Subject: zzz
    Flags: seen, list
    Date: Mon 02 Sep 2019 09:02:47 PM CEST
    Maildir: /Inbox
    List: hhh
    Attachments: [1]2.msgpart(503)

    _______________________________________________
    The signature is shown properly, but the main text is missing.

I am not sure how much I can show from the original message, but I can send it
to you personally, if you want to have a look at it!

**Comment by djcb** [comment]
One thing you could try is the gnus-based view, ie. `(setq mu4e-view-use-gnus t)`.

We can't do much without the message though; perhaps you can censor it and attach it here?
