### ISSUE TITLE
html links not opening, while plaintext does

### ISSUE THREAD

**Issue by ksjogo** [djcb/mu#1482]
## Expected or desired behavior

I would expect plaintext links to behave the same as shr rendered html links.

## Actual behavior

Plaintext links use the configured browser, whereas shr does apparently nothing.

## Steps to reproduce

Configure 
```
 '(browse-url-browser-function 'browse-url-generic)
 '(browse-url-generic-program "/usr/bin/www-browser")
 '(browse-url-secondary-browser-function 'browse-url-generic)  
```

## Versions of mu, mu4e/emacs, operating system etc.

Ubuntu 18.04 on WSL 2, with www-browser provided by wslu https://github.com/wslutilities/wslu

**Comment by djcb** [comment]
This works fine with current mu.
