### ISSUE TITLE
[mu4e] mu4e-action-view-in-browser behaviour in a container

### ISSUE THREAD

**Issue by A6GibKm** [djcb/mu#1483]
When using `mu4e-action-view-in-browser`, the file is created in `/tmp`, this is an issue if you are running inside as a container, as the browser from your machine doesn't have access to `/tmp` inside the container.

**Comment by A6GibKm** [comment]
Proposition: Use `muhome` or `XDG_CACHE_HOME` instead of `/tmp`

**Comment by jschwab** [comment]
The tmp file path isn't a mu4e specific setting.  It comes from emacs' `make-temp-file`. 
https://github.com/djcb/mu/blob/5c5716d3f03f977144cf4c07ddbb1be61f87f4b3/mu4e/mu4e-utils.el#L156

Perhaps you could considering customizing `temporary-file-directory` when you're running in a container.

**Comment by A6GibKm** [comment]
This fixes my issue. Thanks. Closing for now.
