### ISSUE TITLE
Polution of echo area

### ISSUE THREAD

**Issue by daphniz** [djcb/mu#1485]
I'm calling this function

	(defun mu4e*-index ()
	  (interactive)
	  (let ((mu4e-hide-index-messages t)
		(inhibit-message t))
		(mu4e-update-index)))
		
as a cronjob through `emacsclient` every minute.		

The problem is that every minute my echo area reads

	[mu4e] Indexing completed; processed x, updated x, cleaned-up x
	
As you can see, I have tried to avoid this, but unsuccessfully.

Is there a way to make `mu4e*-index` leave the echo area alone?

**Comment by djcb** [comment]
`mu4e-update-index` works asynchronously, so let-binding won't work for that. 

`(setq mu4e-hide-index-messages t)` should do the trick.
