### ISSUE TITLE
How to compile mu and mu4e on Windows

### ISSUE THREAD

**Issue by zickyls** [djcb/mu#1487]
So this is not really a bug report, but rather how I successfully compile and use mu4e for Spacemacs In Windows 10 and want to share it.

These steps are totally inspired by the tutorial:
[http://kimi.im/2019-04-01-emacs-offlineimap-mu4e-on-windows](http://kimi.im/2019-04-01-emacs-offlineimap-mu4e-on-windows)

Yes it was written in Chinese, and that's my mother tongue :)

These are the steps how I reproduced it:
1. Install the Cygwin (I used 64 bit version, so I recon it will work for 32 bit version).
2. Install apt-cyg using the tutorial from official github (see quick start section on the last of the page):
[https://github.com/transcode-open/apt-cyg](https://github.com/transcode-open/apt-cyg)
3. Install the dependencies:
```
apt-cyg install emacs-w32 git \
        autoconf automake libtool \
        gcc-g++ pkg-config make mingw64-x86_64-win-iconv \
        libglib2.0-devel libgmime3.0-devel \
        libxapian-devel python2 python27-pip offlineimap
```
4. Symbolic link iconv library to avoid compiling error
```
ln -s /usr/x86_64-w64-mingw32/sys-root/mingw/include/iconv.h /usr/include/iconv.h
```
5. Pull the mu repository and compile it. Note that I used the prefix for the installation path. It is for easier copying the files later when compilation is done. Doing so we could copy the whole folder to somewhere else (ex in "C:\Program Files\")
```
git clone https://github.com/djcb/mu.git
cd mu
autoreconf -i
./configure --prefix="$HOME/mu4e"
make
make install
```
6. Copy the folder "$HOME/mu4e" to anywhere you want (ex in "C:\Program Files\") and add "$HOME\mu4e\bin" in your path so that you could use it in elsewhere in your terminal.
7. Double click the "mu.exe" in the folder, copy the missing "*.dll" file to your bin folder that you copied to (ex "C:\Program Files\mu4e\bin\") until it works properly. Yes your binary will increase for about 12MB but.. who cares now :). In my case I copied the following:
```
cygassuan-0.dll
cygffi-6.dll
cyggcc_s-seh-1.dll
cyggio-2.0-0.dll
cygglib-2.0-0.dll
cyggmime-3.0-0.dll
cyggmodule-2.0-0.dll
cyggobject-2.0-0.dll
cyggpg-error-0.dll
cyggpgme-11.dll
cygiconv-2.dll
cygidn-11.dll
cygintl-8.dll
cygpcre-1.dll
cygstdc++-6.dll
cyguuid-1.dll
cygwin1.dll
cygxapian-30.dll
cygz.dll
```
8. Find "share/emacs/site-lisp/mu4e/" folder under your newly copied folder and modify "mu4e-meta.el" file. Change the correct path for both "mu4e-builddir" and "mu4e-doc-dir" (Remember to use the backslash). Delete "mu4e-meta.elc" and recomplile it using "byte-compile-file" to produce a new one.
9.  If your Emacs or Spacemacs is not recognizing your installation, check if your path using "getenv" function contains "mu" binary path or your "load-path" variable contains "C:/Program Files/mu4e/share/emacs/site-lisp/mu4e".

 I used Spacemacs, and I put the bin folder in environment variable for my user and added the "load-path" in "dotspacemacs/user-env". Then "SPC a M" opens the program perfectly.

PS: you only need to install the emacs-w32 to produce the mu4e, and when I copied the binary to another machine, it still works. 

Hope this will help, and if it bothers PR, feel free to remove it (and sorry for that :) ).

**Comment by djcb** [comment]
Thanks you for this! I wonder what's the best way to disseminate this information... perhaps write a mail to the mailing-list with this (so google can find it). Or perhaps we can put it in the manual?
