### ISSUE TITLE
Too much warnings for lisp files when building Mu

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1488]
## Expected or desired behavior

Less warnings for *.el files compilation.

## Actual behavior
For each ".el" file we have such warning:

```
if test "emacs" != "no"; then \
  am__dir=. am__subdir_includes=''; \
  case org-old-mu4e.elc in */*) \
    am__dir=`echo 'org-old-mu4e.elc' | sed 's,/[^/]*$,,'`; \
    am__subdir_includes="-L $am__dir -L ./$am__dir"; \
  esac; \
  test -d "$am__dir" || /bin/mkdir -p "$am__dir" || exit 1; \
  emacs --batch \
      \
    $am__subdir_includes -L . -L . \
    --eval "(defun byte-compile-dest-file (f) \"org-old-mu4e.elc\")" \
    --eval "(unless (byte-compile-file \"org-old-mu4e.el\") (kill-emacs 1))"; \
else :; fi
Warning (bytecomp): Changing ‘byte-compile-dest-file’ is obsolete (as of 23.2);
set ‘byte-compile-dest-file-function’ instead.
```
We could avoid this by using this:
```
--eval "(unless (let ((byte-compile-dest-file-function (lambda (f) \"$@\"))) (byte-compile-file \"$<\")) (kill-emacs 1))"; \
```
instead of 

```
    --eval "(defun byte-compile-dest-file (f) \"org-old-mu4e.elc\")" \
    --eval "(unless (byte-compile-file \"org-old-mu4e.el\") (kill-emacs 1))"; \
```

**Comment by thierryvolpiatto** [comment]
I don't understand though how Makefile.in is generated, so I can't make a PR.

**Comment by djcb** [comment]
Hmm, interesting... the actual compile code is generated by autotools (ie. `lisp_LISP`). Perhaps it can be overriden in some way.

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Hmm, interesting... the actual compile code is generated by autotools
> (ie. lisp_LISP). Perhaps it can be overriden in some way.

Thanks, but I don't understand which rules autoconf is using to provide
the emacs command line.  It states it is generated by Makefile.am but I
see no rules in there that could generate the code found in Makefile. 

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
This is not coming from Mu itself but from automake version which when < to 1.15.1 use this misfeature (see comment in emacs-lisp/bytecompile.el:167).
Perhaps my version is too old (1.15).
