### ISSUE TITLE
Different resultsets from same query from mu and mu4e

### ISSUE THREAD

**Issue by muihlinn** [djcb/mu#1490]
This somewhat relates to, but goes beyond, [#562](https://github.com/djcb/mu/issues/562).

I was just commenting [this question](https://emacs.stackexchange.com/questions/52747/mu4e-or-mu-cannot-find-a-search-term-with-a-period?noredirect=1) and once I figured what he was doing I ran into similar issues, further checking showed me differences in the resultset between asking mu and mu4e with the same query. I'll try to summarize various cases:

given these headers:

- `From: "Google.org Impact Challenge on Safety" <safety-challenge@google.com>`
   searching `from:google.org` returns empty resultset. `from:google org` finds the message

- `Subject: @wpfleider loved your post on Ello`
varies a lot, but any search string which starts with @ returns empty resultset

I thought that those could be related to xapian operators or issues I'm not aware of, so I tried something different with punctuation symbols. Just looking for Re: in subject.

- `subject:Re:`
mu4e seems to return me a correct resultset plus a couple of messages related to the resulted (in the same thread, often the root of it) but not matching the query except for some headers that contains re: (as in `X-Google-DKIM-Signature:`). Same query in mu seems to return the correct resultset. 

Tested on mu4e 1.3.4, 1.3.3  and 1.2.0

**Comment by muihlinn** [comment]
What kind of  extra information will be useful?

**Comment by djcb** [comment]
Basically, mu & mu4e run the exact same queries, so if you get different results, it's probably one of:
- The command-query is subject to whatever your processing your shell does (ie. with respect to '*' etc.
 - mu4e defaults to `mu4e-headers-include-related`, so if you use that, the shell should use `--include-related` as well.

Does that help?

**Comment by muihlinn** [comment]
`mu4e-headers-include-related` did it with  `Re:` issue.

still not able to tackle point #2,I'm not able to find a subject that starts with @, any suggestions?

**Comment by blaa** [comment]
I have similar problem - mu4e doesn't show a lot of messages when skip-duplicates is enabled, whereas mu shows more. I haven't pinpointed source of the problem, but consider this:

On a freshly compiled master (c22eb434) and after reindex I've also noticed that 

```
λ mu find --maxnum=500 --reverse --sortfield=date --include-related=true --skip-dups maildir:"/<my_maildir>" | wc -l
288
λ mu find --maxnum=500 --sortfield=date --include-related=true --skip-dups maildir:"/<my_maildir>" | wc -l         
497
```

The "reverse" option alters the result much more than I've guessed and is used (as indicated in logs) by mu4e.

For me mu4e showed even less than the 288 emails (around 4). No idea why though.

**Comment by djcb** [comment]
There are a couple of different issues here:
1) differences between query options in mu4e and mu - I've added some more notes to the FAQ about that (since it's indeed a common thing)
2) queries with special characters sometimes don't really work, and there's only so much mu/mu4e can do about that. If it bother you enough, perhaps you can file a ticket and attach a raw message you'd expect to be found but isn't? Then we can add it to the unit-tests etc.
3) the reverse option can indeed be a little surprising, because it also influences the related messages. Also, if the maxnum works _before_ the check for duplicates, so if you have a lot of those, the counts can differ.

**Comment by djcb** [comment]
So, I think there's no real bug here, though perhaps mu/mu4e should explain things a bit better. I have done so in the updated documentation.
