### ISSUE TITLE
Reply to email with List-Post header drops sender from To

### ISSUE THREAD

**Issue by baruchsiach** [djcb/mu#1491]
## Expected or desired behavior

Replying to email with List-Post header copies the sender address to the To header in the reply email.

## Actual behavior

The address from the List-Post header is copied to the To header. The address of the original sender is removed entirely. When replying to all recipients, all addresses other than the sender are copied to Cc.

## Steps to reproduce

Reply to email with List-Post header.

## Versions of mu, mu4e/emacs, operating system etc.

Version 1.2.0-2, Debian testing.

## Any other detail

This behaviour seems to be introduced in commit e321d15c2a062 ("mu: fake reply-to for mailing-list posts"). Refer also to pull request #1278.

**Comment by hpdeifel** [comment]
Today, I finally sent an email to a mailing that wasn't intended to be public because I didn't catch this and expected the sender to be `To: `. :frowning_face:

**Comment by MadEarl** [comment]
> Today, I finally sent an email to a mailing that wasn't intended to be public because I didn't catch this and expected the sender to be `To: `.

Same here ... embarrassing.

**Comment by djcb** [comment]
I've made a few changes to handle mailing-list replies a bit differently (git). I think that should handle this; please let me know what you think.

**Comment by MadEarl** [comment]
It seems like now I'm not getting asked whether I want to reply to sender or all, and the To: is just set to the list -- is that the behavior you would expect now?

**Comment by djcb** [comment]
No, you should get something like
```
   [mu4e] Reply to mailing [a]ll 3 recipients, [l]ist only (...), [s]ender only.
```
Are you using the git-version? If so, and this still happens, perhaps the message is not recognized as a mailing-list message. Can you attach a message where this happens?

**Comment by MadEarl** [comment]
Es schrieb Dirk-Jan C. Binnema <notifications@github.com> am 
2020-01-21T20:22:17+0100:

> No, you should get something like
> ```
>    [mu4e] Reply to mailing [a]ll 3 recipients, [l]ist only 
>    (...), [s]ender only.
> ```
> Are you using the git-version? If so, and this still happens, 
> perhaps the message is not recognized as a mailing-list message. 
> Can you attach a message where this happens?

It's quite possibly my error. I couldn't get the package to 
compile on Fedora 31, not enough time to investigate, so I tried 
to get only mu4e to work, and that was probably not a good idea. 
Please disregard.

This was the error, BTW:

configure:22090: error: possibly undefined macro: AC_LIB_PROG_LD
      If this token and others are legitimate, please use 
      m4_pattern_allow.
      See the Autoconf documentation.
configure:22125: error: possibly undefined macro: 
AC_LIB_PREPARE_MULTILIB

Regards,

Wolfgang

**Comment by MadEarl** [comment]
I was missing dh-autoreconfig. Now everything but msg2pdf compiled, and I can say that your fix did the trick for me. I can now choose to reply to list or sender, and that's perfect.

**Comment by djcb** [comment]
Okay thanks, closing this.
