### ISSUE TITLE
mu4e-headers-results-limit is confusing when mu4e-headers-include-related is on

### ISSUE THREAD

**Issue by mrvdb** [djcb/mu#1496]
This is perhaps similar to #335 

When searching with `mu4e-headers-result-limit` set to default (500) the search results returned with `mu4e-headers-include-related` set to `on` will return suprisingly little results. 

Increasing the limit helps, but it's not visibly related to the number of search results returned.

I suspect the counter for the limit gets increased searching for related messages too often.

Also, when the search reached the limit, can this be shown somewhere, for example below the search results?

Example I ran: (query was just flag:flagged)
-  2 results for limit set to 200
 - 2  results for limit set to 470
- 10 results for limit set to 480
 - 30 results for limit set to 500
 - 80 results for limit set to 550
 - 91 resutls for limit set to 561
 - 91 results for limit set to -1 

Given the default limit of 500, I guess 91 would be the expected result 

mu4e 1.3.5 CG / emacs 26.1.92 / arch linux

**Comment by djcb** [comment]
It's can be a bit surprising indeed, but it's a consequence of how this works. I've updated the `mu4e-headers-result-limit` docstring to hopefully clarify this.

**Comment by mrvdb** [comment]
Fair enough, any thoughts on this part?:

> Also, when the search reached the limit, can this be shown somewhere, for example below the search results?
