### ISSUE TITLE
Give an option to select behavior after marking a message for trash or deletion to jump to next message ou next unread message.

### ISSUE THREAD

**Issue by ellingtonsantos** [djcb/mu#1497]
## Expected or desired behavior

Please, create an option to select behavior after marking a message for trash or deletion to jump to next message ou next unread message.

## Actual behavior

After marking a message, headers view jumps to next message.

**Comment by djcb** [comment]
You can use `mu4e-headers-advance-after-mark`, but there are not further plans at this point.
