### ISSUE TITLE
Hide long recipient lines

### ISSUE THREAD

**Issue by davidcsterratt** [djcb/mu#1499]
## Expected or desired behavior

I sometimes get emails with ~50 email addresses in the `To:` line, meaning I always have to scroll down to read the message. I'd like some way of, by default, showing only the first _n_ messages, and then having the rest denoted by ellipsis. There would also be a way (like outline-mode or org-mode) of cycling the visibility of the full address list.

## Versions of mu, mu4e/emacs, operating system etc.
I'm currently on mu4e 1.0 C

**Comment by Chris00** [comment]
You can use Gnus-based viewer which positions the cursor (point) at the beginning of the message.  Put `(setq mu4e-view-use-gnus t)` in your init file.

**Comment by djcb** [comment]
Yes, @Chris00 is right.. I'd recommend using the gnus-based viewer for this, not planning on new features for the "old" viewer.

**Comment by jagrg** [comment]
This is what I use currently (version 1.3.4). It shows the first line only, but you can press TAB to unfold.

```
(add-hook 'mu4e-view-mode-hook
	  (lambda ()
	    (save-excursion
	      (goto-char (point-min))
	      (while (not (message-in-body-p))
		(forward-line 1)
		(unless (or (looking-at "Attachments")
			    (looking-at "Subject"))
		  (mu4e~view-header-field-fold))))))
```
