### ISSUE TITLE
mu server hangs indefinitely when trying to view a smime signed message

### ISSUE THREAD

**Issue by munen** [djcb/mu#1501]
## Expected or desired behavior

As a user, when within `*mu4e-headers*` and the cursor is on top of a smime signed message, and I hit RET, I want the message to be opened within `*mu4e-view*`. 

## Actual behavior

- The `*mu4e-view*` buffer openes and shows "Waiting for message..."
- Emacs stays like this indefinitely without further user interaction
- When killing the `*mu4e-view*` buffer, it is not possible to view any other email anymore

This happens with every smime signed email that I get.

I think it happened for some years even. I just never saw the pattern that it's S/MIME signed emails causing the trouble. With the recent update to iOS 13 (which runs my secondary mail client^^), I did finally catch it, because Mail.app there shows the signature in the email now.

To be clear: I'm not expecting mu or mu4e to validate the signature. According to the docs, mu4e doesn't support S/MIME, and as a GPG user I am very fine with that. It would be nice to still see S/MIME signed (not encrypted) emails within mu4e, though^^

## Steps to reproduce

- Get an email which has a S/MIME signature
- Try to open it with `mu view [pathToEmail]` works
- Try to open it how mu4e will open it within the `mu server` with `;; mu> cmd:view docid:24350 extract-images:false extract-encrypted:false use-agent:true` will fail

Here's a screenshot showing how it works with `mu view` and it doesn't work within `mu server`:

![image](https://user-images.githubusercontent.com/505721/67619356-da6d6d80-f7fa-11e9-8f1d-44f8417891f3.png)

To get the docid and the command that mu4e uses, I did some debugging and copied the string that mu4e was actually going to dispatch to the server.

If you need more information, I'll gladly provide it. If you want the raw email, I'll also share it, but I can't do so publicly, because it's always other peoples emails. I did some research on how I could send myself a S/MIME signed email, but gave up after 30min.

## Versions of mu, mu4e/emacs, operating system etc.

- OS: Debian bullseye

I observe the same behavior for Emacs 26.1 from the Debian package management and my self-compiled Emacs 27.0.50. It's also the same with mu/mu4e from the Debian package management (1.2.0-2) and with my self-compiled version (1.3.5).

## Any other detail

- My mu4e configuration is here: https://github.com/munen/emacs.d/#mu4e
- However I don't think it's relevant as the bug is reproducable just within `mu` without using Emacs

If that's of any relevance, according to iOS it seems to be a legit signature, too:

![signal-2019-10-26-141703](https://user-images.githubusercontent.com/505721/67619487-9da27600-f7fc-11e9-83cc-89f90f900acb.jpeg)
![signal-2019-10-26-141624](https://user-images.githubusercontent.com/505721/67619488-9ed3a300-f7fc-11e9-80d1-f4d856f3f59c.jpeg)

**Comment by djcb** [comment]
Can you share a message where this happens? Without that it'd be quite hard to reproduce/fix. Thanks!

**Comment by munen** [comment]
@djcb Sure, here's one: https://gist.github.com/munen/4e07566963df1db2e742761194088927

**Comment by Chris00** [comment]
After asking me to guarantee that the certificate is trusted (not accepting “cancel”), the message displays fine:
![Mu-smime](https://user-images.githubusercontent.com/1255665/68069737-b4991900-fd64-11e9-8556-081969353398.png)

I use the latest dev version of mu and Gnus view — `(setq mu4e-view-use-gnus t)` — and the following S/MIME config:
```
(setq mml-smime-use 'epg)
(setq smime-CA-directory (expand-file-name "~/.emacs.d/message-CA/mine"))
```
I added `disable-crl-checks' in `~/.gnupg/gpgsm.conf`.

**Comment by munen** [comment]
@Chris00 Thank you for testing and giving me feedback! :pray: :bowing_man: 

I confirm that after setting `disable-crl-checks` in `~/.gnupg/gpgsm.conf`, it works for me, too!

Personally, I am absolutely happy with this solution. For future readers: The trick is that `mu` tries to validate a S/MIME signed email, but it'll hang when `gpgsm` in turn checks if the used certificate has been revoked. 

Having said that, I'd like to ask if this is expected behavior from `mu`. According to the [docs chapter 5.6](http://www.djcbsoftware.nl/code/mu/mu4e/MSGV-Crypto.html#MSGV-Crypto): "only PGP/MIME is supported; PGP-inline and S/MIME are not." So it feels like a bug to me that mu tries to verify a S/MIME signature in the first place.

**Comment by Chris00** [comment]
This solution using the Gnus-based viewer, it must still be considered experimental.  @djcb will no doubt update the manual at some point (but one may indeed argue there should be a section about the Gnus-based viewer already as more and more people start using it).

**Comment by munen** [comment]
The solution for me required _only_ adding `disable-crl-checks` in `~/.gnupg/gpgsm.conf`. Said the other way around: 

- I do not need to use the gnus based viewer
- The whole problem/solution can be reproduced without mu4e at all - `mu server` is enough

**Comment by Chris00** [comment]
@munen Ah, thanks for the info.  Then I agree the manual should be updated.

**Comment by munen** [comment]
NB: I'm running Debian with `gpgsm` version 2.2.17.

Maybe this behavior is being introduced by a newer version of gpgsm.

In any case, @Chris00 thank you very much, again! I'm now able to read/reply to all my emails again from Emacs instead of my phone. I'm very grateful! :pray: :bowing_man:

**Comment by djcb** [comment]
It seems the gmime library that mu uses has gained s/mime support in the meantime, so yeah, the doc is outdated.

**Comment by djcb** [comment]
Thanks -- I have updated the documentation. Closing this.

**Comment by munen** [comment]
Thank you :pray:
