### ISSUE TITLE
Fails to display messages with Content-Type: text/x-markdown

### ISSUE THREAD

**Issue by alexmurray** [djcb/mu#1503]
## Expected or desired behavior

Should display as regular text/plain emails

## Actual behavior

No body is displayed at all

## Steps to reproduce

Try and display the attached mail

```
$ mu view /home/amurray/Maildir/INBOX/cur/1572999606.4463_1.slate,U=131586:2,S
From: Stefan Monnier <monnier@iro.umontreal.ca>
To: Dmitry Gutov <dgutov@yandex.ru>
Cc: Jo\303\243o T\303\241vora <joaotavora@gmail.com>, emacs-devel@gnu.org
Subject: Re: BIKESHED: completion faces
Date: Wed Nov  6 10:48:35 2019
[No body found]
```

## Versions of mu, mu4e/emacs, operating system etc.
1.2.0

**Comment by alexmurray** [comment]
[1572999606.4463_1.slate,U=131586:2,S.txt](https://github.com/djcb/mu/files/3811942/1572999606.4463_1.slate.U.131586.2.S.txt)

**Comment by Chris00** [comment]
With the Gnus-based viewer  — `(setq mu4e-view-use-gnus t)` in you init file — the body displays.

**Comment by djcb** [comment]
Okay merged & fixed. Thanks!
