### ISSUE TITLE
Problem opening attachments using sandboxed (snap) apps

### ISSUE THREAD

**Issue by dochego** [djcb/mu#1505]
## Expected or desired behavior

I am using libreoffice installed via snap as the default application for MS-Word documents. I would expect that opening an attachment from mu4e works fine with this configuration.

## Actual behavior

When opening such an attachment in mu4e, the attachment is saved to a temporary file in /tmp/ to which libreoffice doesn't have access due to snap's sandboxing, so it cannot open the file.
Setting the Emacs variable temporary-file-directory as suggested in https://github.com/djcb/mu/issues/1483 doesn't work in this case since attachments are handled directly by mu-server. It appears that g_get_tmp_dir() is used to determine the temp directory, which is derived from the environment variable TMPDIR. Setting this for emacs to somewhere in my home directory (using (setenv "TMPDIR" "/path/to/tmp")) works around the issue, but has the side effect that it is also used by emacsserver, so I would have to set it whenever I want to use emacsserver.

A workaround would be to have mu-server use the value set by temporary-file-directory when invoked via mu4e to extract an attachment.

## Steps to reproduce

See above.

## Versions of mu, mu4e/emacs, operating system etc.

mu: git-version
emacs: 26.3
OS: Ubuntu 18.04, libreoffice via snap

**Comment by djcb** [comment]
Did you try the gnus-based view? I.e., `(setq mu-view-use-gnus t)`. 

With that, the attachment-handling is all in emacs, so it might be easier to manipulate, e.g. through `mm-tmp-directory`.

**Comment by djcb** [comment]
Alternatively, you could start the mu server with that environment variable, using a shell-script.
