### ISSUE TITLE
Why no mu4e~proc-kill at context switch

### ISSUE THREAD

**Issue by gyps** [djcb/mu#1506]
When doing a context switch mu4e-mu-home cannot be set (this is expected and documented behaviour). This is because the background procedure is already running and not restarted. What speaks against doing a proc-kill at context switch so mu4e-mu-home can be set to a new value? This would make splitting mail into archives much easier.

**Comment by djcb** [comment]
I'm not quite convinced that would work correctly in all cases, there's a lot of state. So I wouldn't recommend that.

Of course, there's nothing stopping you from setting up your contexts to do that...
