### ISSUE TITLE
Attaching files with org-mu4e

### ISSUE THREAD

**Issue by A6GibKm** [djcb/mu#1508]
## Expected or desired behavior

When using `mml-attach-file` in a mu4e-compose buffer, a file should be attached after sending the mail.

## Actual behavior
`mml-attach-file` introduces a 
```html
<#part type="application/octet-stream" filename="~/Downloads/file" disposition=attachment>
<#/part>
```
block. If instead we had 
```org
#+BEGIN_EXPORT html
<#part type="application/octet-stream" filename="/var/home/msandoval/Downloads/file" disposition=attachment>
<#/part>
#+END_EXPORT
```

the file is correctly attached after conversion to html.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e 1.3.3
emacs 26.2
fedora 30

## Additional info

This was asked in [emacs.stackexchange.com](https://emacs.stackexchange.com/questions/40644/attach-files-using-org-mu4e/53702#53702).

**Comment by gambhiro** [comment]
Oh this would be a relief. The org-mode attachments have been a bit... I'm never sure what's going to happen, so I have been switching to the browser when having to send an email with both formatting (such as links) and attached files.

**Comment by Chris00** [comment]
It is because you use org-mode to compose your message, `<#part ...>` works perfectly with the default message mode.  Doesn't the org minor mode composition redefine the binding <kbd>C-c RET f</kbd>?

**Comment by WhatDothLife** [comment]
For me this 
```
#+BEGIN_EXPORT html
<#part type="application/octet-stream" filename="/var/home/msandoval/Downloads/file" disposition=attachment>
<#/part>
#+END_EXPORT
```
attaches the file twice, like I mentioned in [this](https://www.reddit.com/r/emacs/comments/f5u5rz/mu4e_how_to_attach_a_file_properly/) reddit post.

**Comment by A6GibKm** [comment]
> Please fix this soon!

I think org-mu4e is deprecated.

**Comment by djcb** [comment]
Yes, it's very deprecated, there are many issues like this, which are hard to fix (and beyond our time budget...). So, closing this, sorry...

**Comment by WhatDothLife** [comment]
Too bad, I've been enjoying org-mu4e so far, and this was the only issue I've experienced. Isn't there at least some workaround?

**Comment by gambhiro** [comment]
Perhaps naively, I was thinking that the attachment syntax could be parsed before org, then removed when passing the message body to be converted to html.
