### ISSUE TITLE
Gnus: Cannot open pdf attachment with external viewer

### ISSUE THREAD

**Issue by averter** [djcb/mu#1509]
## Expected or desired behavior
To be able to open pdf attachments with an external viewer (say, okular), when using gnus article view. 

## Actual behavior
When prompting the external viewer for the file with the `e` key, a `View as MIME type (default application/pdf):` prompt shows up, and pressing RET opens the PDF in a buffer with a lot of non-recognized characters: 

````
%PDF-1.5
%\320\324\305\330
99 0 obj
<<
/Length 1314      
/Filter /FlateDecode
````
Things I've tried: 

- create a .mailcap file as suggested [here](https://www.emacswiki.org/emacs/MimeTypesWithGnus) 
- checked that okular is my default pdf viewer (it works well with org-mode). 
Note: for other filetypes such as Word or Excel documents it calls libreoffice as expected.

## Steps to reproduce

1. Open an email with a pdf attachment
2. Press `e` on top of the attachment and then RET

## Versions of mu, mu4e/emacs, operating system etc.
mu4e v1.3.5, emacs 25.2.2 Linux Mint 19.2 Cinnamon

**Comment by Chris00** [comment]
I put this in my init file:
```elisp
;; Prefer evince to doc-mode as an external viewer
(push '((viewer . "evince %s 2> /dev/null")
        (type . "application/pdf")
        (test . window-system))
      mailcap-user-mime-data)
```

**Comment by averter** [comment]
When using your solution Emacs is returning `mu4e/:config: Symbol’s value as variable is void: mailcap-user-mime-data` at startup. Possibly I need to install something else.

**Comment by Chris00** [comment]
You must indeed upgrade to Emacs 26.  The doc says:
```
This variable was introduced, or its default value was changed, in
version 26.1 of Emacs.
```

**Comment by averter** [comment]
Can't do that at the moment but I'll get back to this issue when I update. BTW, is it possible to use the same shortcuts as mu4e to open links/attachments, i.e. `g` or `o` in gnus? (my brain is so used to them...)

**Comment by Chris00** [comment]
You may want to try with `mailcap-mime-data` instead of `mailcap-user-mime-data`.

For the shortcuts, IIRC it is planned but not fully implemented yet.

**Comment by averter** [comment]
Thank you for the suggestion. This is the current output when trying to open with the external viewer `gnus-treat-article: No buffer named *Article*`
`mapcar: Wrong type argument: listp, "application/pdf"`

**Comment by Chris00** [comment]
The structure of `mailcap-mime-data` is a bit different.  You have to push the structure at the right place in the tree.  Something like (untested):
```elisp
(push '("pdf"
        (viewer . "evince %s 2> /dev/null")
        (type . "application/pdf")
        (test . window-system))
      (cdr (assoc "application" mailcap-mime-data)))
```

**Comment by averter** [comment]
Ok, I've got no error during init now but the pdf still opens in a separate buffer. The output reads `pdf-info-encrypted-p: pdf-info-epdfinfo-program is not executable`

**Comment by djcb** [comment]
`e` works for me.

I'm using the system-wide `/etc/mailcap`, which contains ```
application/pdf; /usr/bin/xdg-open %s
```
which (in my case) triggers `evince`.

**Comment by averter** [comment]
Thank you both. I was able to install emacs 26 and it is working now. There are a few other problems though, but I'll list everything and open a separate thread. Closing now
