### ISSUE TITLE
Cannot view attached emails in mu4e

### ISSUE THREAD

**Issue by shashurup** [djcb/mu#1515]
## Expected or desired behavior

When in mu4e I try to make "o" on an attachment which is email message itself it must open.

## Actual behavior

Nothing happens. Just the "could not find message(s) for msgid" is shown.

## Steps to reproduce

Find an email with attached emails.
Try to open it via "o"

## Versions of mu, mu4e/emacs, operating system etc.
1.2.

## Any other detail
The reason is that mu4e~view-mark-as-read-maybe doesn't correctly detect that the message is an attachment itself and tries to mark it as read by moving it into another maildir folder.
(docid (mu4e-message-field msg :docid))) renders docid = 0 which is not correctly handled by 
      (when (and docid (or (member 'unread flags) (member 'new flags)))
it must be something like
      (when (and (> docid 0) (or (member 'unread flags) (member 'new flags)))

**Comment by djcb** [comment]
I'd recommend using the new gnus-based viewer (since 1.3.4 or so)
```
(setq mu4e-view-use-gnus t)
```

**Comment by shashurup** [comment]
I'm aware of this option, however, as far as i remember it experimental or something like this. Is it really better?

**Comment by djcb** [comment]
It's the way of the future :). 

It fixes quite a few bugs we have in the view, and adds a bunch of features, and should overall work fine, unless you depend on something specific from current view -- we're slowly adding things.

For this particular case, I don't think it will be fixed in the "old" view anytime soon.

**Comment by shashurup** [comment]
Hm.. It defenitely looks better. Thank you!
