### ISSUE TITLE
ability to choose nr of previous msgg to quote

### ISSUE THREAD

**Issue by daphniz** [djcb/mu#1516]
is it possible to choose not to quote previous messages when replying,
or to choose how many previous messages to quote?  if not --it doesn't
seem to be possible,-- mightn't this be a desirable feature?

**Comment by djcb** [comment]
You can change the reply style using `mu4e-compose-cite-function` (which is mu4e's version of `message-cite-function'`. 

But, quoting multiple messages at once is not possible, I don't see that happening. Sorry!

**Comment by daphniz** [comment]
What I meant was that by default ALL previous messages of the conversation will be quoted, but often one will only wish to quote the last message (excluding older messages quoted in that message).

**Comment by daphniz** [comment]
I meant one often wishes to exclude older messages quoted by the quoted message.
