### ISSUE TITLE
Invert meaning of prefix for mu4e-update-mail-and-index

### ISSUE THREAD

**Issue by sje30** [djcb/mu#1517]
## Expected or desired behavior

I'd like to propose a patch  for mu4e-update-mail-and-index such that if a separate variable is non-nil, the behaviour of C-u prefix args is inverted.    NOw that I'm using EXWM, the update buffer annoyingly grabs a large part of the window space, and actually I don't tend to read the contents of the buffer.

**Comment by sje30** [comment]
p.s. am happy to write the patch.

**Comment by djcb** [comment]
Thanks, but I think that would be a bit confusing... you can use a prefix-argument, or even use advise or your own function for your particular use-case.
