### ISSUE TITLE
Address autocompletion: rank candidates according to frequency 

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#152]
I have a 30k+ repository of emails and in many cases autocompletion offers a relatively large number of candidates (even if I limit autocompletion to messages from the last two years).  In order to single out the target address, I have to perform a larger number of keystrokes.  However, most of the candidates are people I rarely communicate with.  Another problem is that some people have many email addresses (one of my colleagues has nine) and sometimes I don't remember which address is their preferred one.  Both problems could be solved if candidates were ranked according to their frequency: contacts to which I send many emails should be ranked first.  My guess is that the contact ranked first would be the correct one in more than 90% of the cases.

I saw that somebody on mu-discuss proposed to use overall frequency of the contacts in the repository but I think this is slightly less useful as there are contacts from which I receive lots of email while I never send something back (automatic notifications, etc.).

**Comment by djcb** [comment]
Since 0.9.16, we have `mu4e~sort-contacts`, which favors personal, then recent contacts, then sorts by frequency.
