### ISSUE TITLE
Can't build mu in NetBSD

### ISSUE THREAD

**Issue by gigavinyl** [djcb/mu#1522]
## Expected or desired behavior

The make file completes and a mu binary is generated.

## Actual behavior

Running `gmake` after using the configure script yeilds this error
```
utils.cc:391:2: error: ‘snprintf’ was not declared in this scope
  snprintf (buf, sizeof(buf), SizeFormat, size);
  ^~~~~~~~
utils.cc:391:2: note: suggested alternative: ‘swprintf’
  snprintf (buf, sizeof(buf), SizeFormat, size);
  ^~~~~~~~
```

## Steps to reproduce

Run `./configure; gmake` on NetBSD

## Versions of mu, mu4e/emacs, operating system etc.
OS: NetBSD 9.0_RC1

**Comment by djcb** [comment]
Hmmm.... that's odd. `stdio.h` is included, that should work on netbsd as well.

**Comment by gigavinyl** [comment]
Yeah it seems really weird. Maybe I need to play with the LDFLAGS?

**Comment by djcb** [comment]
Hmm, this seems to be a compilation error, so LDFLAGS wouldnt be involved. I suspect it's some C++ namespacing thing. I've made some changes though, perhaps it works now?

**Comment by djcb** [comment]
Closing this, feel free to reopen if this still happens.
