### ISSUE TITLE
Jump to next thread/previous thread

### ISSUE THREAD

**Issue by agzam** [djcb/mu#1523]
What's the best way to jump to the next thread/previous thread? I can't find that in elisp code.

**Comment by djcb** [comment]
Not currently possible.

**Comment by agzam** [comment]
Sad. mu4e is amazing, but it's missing the fundamental piece - working in units of threads. Expanding/collapsing threads and jumping to next/previous are two basic features that could make it a lot more usable for user-groups.

_Sorry if that sounds like a pointless, ungrateful complain. I really like mu4e and I really appreciate the tremendous work you put into making it so awesome._

**Comment by Chris00** [comment]
Don't know the inner workings of the `*mu4e-headers*` but couldn't a hidden information be put on the first message of each thread and _goto-next-thread_ would just seek forward for it?
