### ISSUE TITLE
mu4e~draft-remove-mail-header-separator

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1525]
I am experiencing a couple of issues with `mu4e~draft-remove-mail-header-separator`. The first one is that it seems my undo list registers the action of removing and adding the separator as an action. 
So when if I am undoing some changes to the message buffer the the message separator disappears and appears again. Is there a way to not add this action to the undo history?

Also, every once in a while the message separator shows up inside the message header (before the Date field). I am sorry I cannot give more info on this, as I haven't been able to pin the issue down completely.

**Comment by djcb** [comment]
When you filed this issue, did you not get the issue-template? That would have helped gathering the crucial information like versions etc.

**Comment by haji-ali** [comment]
Apologies, please find the report below.

## Expected or desired behavior
When editing composing a message, I expected the line `--text follows this line--` to not interfere with my message writing.

## Actual behavior

If I am editing a message, the line `--text follows this line--` appears after the header but before the body. If I edit a message, save it, edit it again, then if I starting undoing my actions one by one at some point the line `--text follows this line--` disappears. If I continue undoing, the line appears again.

This is distributive because I am not expecting a change in the beginning of the message. More importantly, if I accidentally undo the line `--text follows this line--` (so that it's not in the message anymore) then save. The header/body becomes mangled.  

## Steps to reproduce

Compose new email. Edit message, save, edit again, then undo actions one by one until `--text follows this line--` disappears. Saving the message now mangles it.

## Versions of mu, mu4e/emacs, operating system etc.
mu 1.3.6
Emacs 26.2
