### ISSUE TITLE
Kill buffer and window of message replied to on sending a reply

### ISSUE THREAD

**Issue by mac230** [djcb/mu#1533]
## Expected or desired behavior

When I reply to an email, I almost always no longer need to view it.  Thus, I'd like mu4e to kill the buffer and window of the message I've just sent a reply to. 

## Actual behavior

mu4e keeps the buffer and window of the message open. 

## Steps to reproduce

Send a message with:

```
(setq message-kill-buffer-on-exit t)
```

Am I missing something that there's no pre-defined option to make this happen?

Looking at:

```
(defun mu4e-message-kill-buffer ()
  "Wrapper around `message-kill-buffer'.
It restores mu4e window layout after killing the compose-buffer."
  (interactive)
  (let ((current-buffer (current-buffer)))
    (message-kill-buffer)
    ;; Compose buffer killed
    (when (not (equal current-buffer (current-buffer)))
      ;; Restore mu4e
      (if mu4e-compose-in-new-frame
	  (delete-frame)
	(mu4e~switch-back-to-mu4e-buffer)))))

(defun mu4e~switch-back-to-mu4e-buffer ()
  "Try to go back to some previous buffer, in the order view->headers->main."
  (unless (eq mu4e-split-view 'single-window)
    (if (buffer-live-p (mu4e-get-view-buffer))
	(switch-to-buffer (mu4e-get-view-buffer))
      (if (buffer-live-p (mu4e-get-headers-buffer))
	  (switch-to-buffer (mu4e-get-headers-buffer))
	;; if all else fails, back to the main view
	(when (fboundp 'mu4e) (mu4e))))))
```

it looks like you'll always go back to the replied-to message per the precedence of 'mu4e~switch-back-to-mu4e-buffer'

I wrote the following that achieves my desired behavior based on the source:

```
(defun mu4e-send-and-kill-message-replied-to ()
  "Send a reply to a message, then kill the mu4e view buffer 
and window of the message replied to"
  (interactive)
  (let ((current-buffer (current-buffer)))
    (message-send-and-exit)
    (when (bufferp (get-buffer "*mu4e-view*"))
      (progn
	(set-buffer (get-buffer "*mu4e-view*"))
	(mu4e~view-quit-buffer)
	(mu4e~switch-back-to-mu4e-buffer)))))
```

but also want to make sure I'm not just duplicating (or worse, making an inferior version) of something that already exists in mu4e.  Thanks.

**Comment by djcb** [comment]
Great it works for you :)

Guess you could make it just a keybinding, `C-c C-c q` or something like that? That would also avoid using internal `mu4e~` functions.
