### ISSUE TITLE
Consider using fancy ellipsis (…) with fancy-chars

### ISSUE THREAD

**Issue by nivekuil** [djcb/mu#1539]
The unicode ellipsis looks much nicer to my eyes and saves 2 chars per column. This can be accomplished most easily now with `(setq truncate-string-ellipsis "…")`, but it could be nice to have this done automatically by setting mu4e-use-fancy-chars.

**Comment by djcb** [comment]
Wouldn't want to make that automatic, but there were a few places where we were _not_ hard-coding "...", and I've fixed those.

Closing this -- thanks.
