### ISSUE TITLE
Main buffer should show the correct number of unread mails

### ISSUE THREAD

**Issue by WhatDothLife** [djcb/mu#1540]
## Expected or desired behavior

I want mu4e to update it's main buffer on the number of unread mails.

## Actual behavior

It doesn't update, the old value is shown.

## Versions of mu, mu4e/emacs, operating system etc.

Version of mu/mu4e is 0.9.18

**Comment by djcb** [comment]
mu4e does not show the number of unread emails; this must be some extension. I'd recommend asking the developer of that extension.
