### ISSUE TITLE
search for from:name broken in mu4e

### ISSUE THREAD

**Issue by tobiasw1** [djcb/mu#1542]
## Expected or desired behavior

a search e.g. f:name should show only emails that are from 'name'

## Actual behavior
This works fine on the command line with "mu find f:name"

A search in emacs with mu4e e.g. "s, f:name" shows additional non-relevant results (also where 'name' is not in 'from', but anywhere else in the email recipient list)

## Versions of mu, mu4e/emacs, operating system etc.

linux kubuntu 19.10, emacs 26.3
mu and mu4e v 1.20 above bug
mu and mu4e v 0.9.18 works fine

**Comment by djcb** [comment]
mu4e by default also shows _related_ results. You can customize `mu4e-headers-include-related`.
