### ISSUE TITLE
Add date to message body when replying

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1543]
## Expected or desired behavior
Add date to reply header like this:

```
On 28/12/2019 Friend Mcfriendster <friend@web.com> writes:
```

## Actual behavior

Only 
```
Friend Mcfriendster <friend@web.com> writes:
```
is added before message body when replying.

## Versions of mu, mu4e/emacs, operating system etc.
mu 1.3.6
emacs 26.2

**Comment by jschwab** [comment]
Since mu4e derives from message mode, you should set `message-citation-line-format` to give whatever format you prefer.

**Comment by djcb** [comment]
Indeed -- something like
```
(setq
    message-citation-line-format "On %A %b %d %Y, %N wrote:\n"
    message-citation-line-function 'message-insert-formatted-citation-line)
should do the trick.

**Comment by haji-ali** [comment]
Thanks. That does exactly what I want. Thanks also for telling about message-mode, I will be sure to check it first in the future.
