### ISSUE TITLE
Restrict memory usage on old machines

### ISSUE THREAD

**Issue by manphiz** [djcb/mu#1549]
## Expected or desired behavior

I'm trying to use mu(4e) on a very old and slow machine (Loongson 2f) which has only 1GB of memory.  I would expect mu indexing can still provide a reasonable performance.

## Actual behavior

Indexing performs well initially (~20msg/s), but as I have a very large amount of emails, after reaching 50k messages mu's memory usage has exceeded 1GB and started using swap which resulted in very slow performance (<1msg/s).  Once the swapping is done it can recover to normal speed but it will happen again after a few thousand.

## Steps to reproduce

Reproducible when you have a large mailbox.

## Versions of mu, mu4e/emacs, operating system etc.

mu: 1.2.0
emacs: 26.3
OS: openbsd, mips64el/loongson

## Any other detail

This issue is probably expected as this box is pretty slow and limited on resource.  I just wonder whether there is a way to let mu restrict memory usage as I'd expect the indexing process to push updates to disk more often (through xapian I assume) so as to reduce memory usage.  Thanks!

**Comment by djcb** [comment]
what you could try is reducing the `--xbatchsize` (that's only on the command line though, and gone after 1.2.x). Set it it to 10000 or even lower, that should reduce memory-consumption (at the cost of speed).
