### ISSUE TITLE
mu4e mail messsage sorting in header view

### ISSUE THREAD

**Issue by theophilusx** [djcb/mu#1551]
## Expected or desired behavior

After upgrade to mu4e I would expect no change to the ordering of messages in the header view.

If I want to change the date order of messages in the header view, I can click on the Date header item and it will switch between ascending/descending date order. 

## Actual behavior

Updated to latest source from git repo. Ran configure, build and install. All good.

Started Emacs and started mu4e. Noticed that message sorting in the header view was now reversed. Previously, it was newest message first and oldest message last and now it is oldest message first and newest message last. There were no changes in my setup to alter this.  

No big deal, there is a 'Date' field at the top of the display with an upward or downward triangle which indicates the sort order. Clicking on this should switch  between ascending and descending. 

Click on the Date header element. Minibuffer reports the ordering change, but there is no change in the order of messages displayed in the header view. Clicking again will cycle through the ascending/descending choices and the 'indicator' triangle will change accordingly, but there is no actual change in the order of displayed messages in the header view.
 

## Steps to reproduce

Start mu4e, go to header view and click on the 'Date' header item.

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 27.0.60 (Git emacs 27 branch). Built from todays HEAD
mu4e 1.3.6 build from todays HEAD
Ubuntu 19.10

**Comment by djcb** [comment]
There are some changes in the mu <-> mu4e communication and the sortfield hadn't been ported yet. 

Anyway, fixed (git).
