### ISSUE TITLE
`mu4e-change-filenames-when-moving` ignored?

### ISSUE THREAD

**Issue by joostkremers** [djcb/mu#1552]
## Expected or desired behavior

mu4e should rename messages when it moves them to another mail folder if `mu4e-change-filenames-when-moving` is set.

## Actual behavior

It seems that the recent changes accidentally disabled this functionality, as I just got a duplicate UID error from mbsync.

Looking at the code in `mu4e-proc.el`, it seems something's gone wrong. In the function `mu4e~proc-move` a local variable `rename` is created in a `let*`-binding but is never used. (Actually, the same seems to be true of some of the other variables bound by the same `let*`. They appear to be left-overs from the older code.)

Could it be that the new call to `mu4e~call-mu` doesn't pass the right argument for the `:rename` keyword?

## Steps to reproduce

Move a message with some UID *n* to another mailbox that already has a message with UID *n*.

## Versions of mu, mu4e/emacs, operating system etc.

GNU/Linux, Emacs 26.3, mu/mu4e from git at 7e6353, mbsync 1.3.0.

**Comment by djcb** [comment]
I think this should be fixed now... can you confirm?

**Comment by joostkremers** [comment]
Well, it's not straightforward to trigger the bug intentionally, so I'll just close this issue, assuming everything's OK now. If I run into any problems, I'll reopen it.

Thanks!
