### ISSUE TITLE
Improve the improved mailing-list handling

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#1558]
## Expected or desired behavior

Suppose you have a message with a List-Id and a From which matches mu4e-compose-reply-ignore-addess.

When hitting "reply" on such a message I get:

``[mu4e] Replying to mailing-list [a]ll 1 recipient(s), [l]ist-only (list address), [s]ender-only (address matches by compose-reply-ignore-address)``.

In such case, I'd expect mu4e to reply directly to the list.

## Steps to reproduce

A common scenario here are github issues. Try to reply to a notification: I never want to reply to "notifications@github.com".

## Versions of mu, mu4e/emacs, operating system etc.

Using master as of 2020-01-28.

## Any other detail

Although I barely look at the main page, bookmark counts are awesome :)

**Comment by djcb** [comment]
mu4e has a new composer with "Reply" and "Wide reply" (reply-to-all, that's a new thing), which now handles these cases, we don't do anything special. If that's not enough, for ultimate control there's `message-reply-to-function`.

Note: mu4e 1.11.23 has a new composer that is much closer to gnus' one.
