### ISSUE TITLE
Replying with a long list of recipents adds newlines between double quotes

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1560]
## Expected or desired behavior

When replying to a message with a long list of recipients (in CC in my case), this list is split in incorrect places: newlines must not be added between double quotes.  Example (too short to trigger the bug but gives the idea):

```
Cc: "a" <a@domain.com>, "b
 c" <b.c@domain.com>
```

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 26.3
Mu: dev version (commit 9ba28bc4)

**Comment by djcb** [comment]
Does this still happen? If so, do you have an example message? Thanks!

**Comment by djcb** [comment]
Closing this for now; feel free to re-open with an example where this happens --  thank.
