### ISSUE TITLE
mu4e and mail aliases

### ISSUE THREAD

**Issue by kkylin** [djcb/mu#1561]
I keep a list of aliases in my .mailrc.  It works fine with mu4e: tabbing to expand in "To:" or "Cc:" lines works just fine.  But after editing the .mailrc (either adding a new alias or editing an existing one) and doing M-x build-mail-aliases, I do not see the new aliases, just the same old ones.  I have to restart emacs to see the new / updated aliases.

I don't have any reason to think that the ability to update aliases is a supported feature.  But it would be really useful to be able to edit and rebuild alises without needing to restart emacs (which I tend to leave running for as long as the machine is up).

I'm on mu 1.1.0 and GNU Emacs 26.3 (and mac os 10.15.2 FWIW).

Thanks!

**Comment by kkylin** [comment]
In the mean time a simple work-around is to rebind EXPAND-MAIL-ALIASES, which does work correctly after each BUILD-MAIL-ALIASES.  So not an urgent issue, but if there's a simple fix I'd appreciate knowing.

**Comment by djcb** [comment]
It _seems_ this is outside mu4e, since mu4e doesn't directly use mail-aliases but has it's own address completion. Do you have some specific settings to use mail-aliases instead?

**Comment by Chris00** [comment]
This is built in message mode (see https://www.gnu.org/software/emacs/manual/html_mono/message.html, section 2.10).

**Comment by djcb** [comment]
Ah, thanks, @Chris00. Looking at that code, it seems calling 
```
M-: mail-abbrevs-sync-aliases RET
``` 
should do the trick after you've updated your aliases (untested though).

**Comment by kkylin** [comment]
Thanks!  sorry I got swamped with work and didn't
respond to your request for more info.  I knew it was
outside mu4e; was just hoping someone knew a solution.

Cheers,
Kevin

-----Original Message-----
