### ISSUE TITLE
search emails

### ISSUE THREAD

**Issue by chenblueridge** [djcb/mu#1564]
Can mu search email headers as what's shown in this page https://wiki.zimbra.com/wiki/Zimbra_Web_Client_Search_Tips, by searching header fields like #FIELDNAME:string?

**Comment by chenblueridge** [comment]
Dug into it a bit, looks like that I can add the fields I want to index in the function get_tags() and search with tag:. It would be convenient to make it configurable via an external configuration file.

**Comment by djcb** [comment]
We don't index _all_ headers, just the subset that seems generally useful, so you cannot (easily) search for the ones that aren't. Don't think that will change anytime soon. Is there any particular header you need?

**Comment by chenblueridge** [comment]
I'm using mu4e to index/query emails generated by a web service. Emails generated by that web service have some unique fields in their message header. Now I understand that it's not possible to index these headers efficiently, but can we have a configuration file to allow users to customize what fields can be indexed?

**Comment by djcb** [comment]
That's not possible... the fields are hard-coded. Sorry!

**Comment by alexmurray** [comment]
I would also find it useful to be able to index arbitrary headers, would you be willing to accept a PR which adds this in a configurable way?

**Comment by djcb** [comment]
Not really, it would quite a fundamental change, since the message indexing, the querying etc. all depend on a predefined (small) set of predefined fields -- sorry.

**Comment by Chris00** [comment]
@alexmurray Maybe you can use a script (after fetching the mails but before indexing them) to add a new header gathering the information from the custom headers?  I guess no standard field will be suitable for that so, if @djcb agrees, a field `X-Mu4e` could be used for that?

**Comment by ecocode** [comment]
> @alexmurray Maybe you can use a script (after fetching the mails but before indexing them) to add a new header gathering the information from the custom headers? I guess no standard field will be suitable for that so, if @djcb agrees, a field `X-Mu4e` could be used for that?

That would do the job for me too..
