### ISSUE TITLE
C-S-a gets translated to C-a

### ISSUE THREAD

**Issue by kuba-orlik** [djcb/mu#1565]
## Expected or desired behavior

Pressing C-S-a should select all text from the current point position back to the beginning of the line

## Actual behavior

It only moves the point to the beginning of the line, without selecting 

## Steps to reproduce

When editing a message, move the point to a middle of a line and press C-S-a

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 26.3
mu version 1.2.0
GNU/Linux

**Comment by djcb** [comment]
That's the way message-mode works... and emacs itself (`emacs -Q`); so if you want to change that, either add the binding yourself, or lobby the `message-mode` folks to add it (it does seem useful behavior, but also the kind of thing emacs does _not_ default to...)

**Comment by kuba-orlik** [comment]
I've reported the issue to emacs maintainers, here's a link:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=39545
