### ISSUE TITLE
new installation,  Error 1: expected: '<alphanum>+:' ("0")), and "Error 1: error in quoting"

### ISSUE THREAD

**Issue by holtzermann17** [djcb/mu#1566]
## Expected or desired behavior

M-x mu4e should fire up my Mu4e client.

## Actual behavior

I get an error `mu4e-error-handler: Error 1: expected: '<alphanum>+:' ("0"))`

I ran edebug and traced it to this form:

`(unless mu4e~contacts (mu4e~request-contacts-maybe))`

I also see another error:

```
Debugger entered--Lisp error: (error "Error 1: error in quoting")
  signal(error ("Error 1: error in quoting"))
  error("Error %d: %s" 1 "error in quoting")
  mu4e-error-handler(1 "error in quoting")
  mu4e~proc-filter(#<process  *mu4e-proc*<1>> "\37627\377(:error 1 :message \"error in quoting\")\n")
```

## Steps to reproduce

This is an almost new installation, without much content to import:

```
~/mail$ find ./
find ./
./
./Sent
./Sent/new
./Sent/tmp
./Sent/cur
./Trash
./Trash/new
./Trash/tmp
./Trash/cur
./INBOX
./INBOX/new
./INBOX/new/1581072992_0.21468.Proteus,U=1,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
./INBOX/tmp
./INBOX/cur
./Drafts
./Drafts/new
./Drafts/tmp
./Drafts/cur
./Archive
./Archive/new
./Archive/tmp
./Archive/cur
./Spam
./Spam/new
./Spam/tmp
./Spam/cur
```

## Versions of mu, mu4e/emacs, operating system etc.

Configured to work with my Mail-in-a-box system:

*Offlineimaprc*

```
[general]
# List of accounts to be synced, separated by a comma.
accounts = main

[Account main]
# Identifier for the local repository; e.g. the maildir to be synced via IMAP.
localrepository = main-local
# Identifier for the remote repository; i.e. the actual IMAP, usually non-local.
remoterepository = main-remote

[Repository main-local]
# OfflineIMAP supports Maildir, GmailMaildir, and IMAP for local repositories.
type = Maildir
# Where should the mail be placed?
localfolders = ~/mail

[Repository main-remote]
# Remote repos can be IMAP or Gmail, the latter being a preconfigured IMAP.
type = IMAP
remotehost = box.xxx.yyy
remoteuser = joseph.corneli@xxx.yyy

# Necessary as of OfflineIMAP 6.5.4
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
```

*Mu4e* c707feb30f4fdf737490f216a13ec8b3c866076e
```
(add-to-list 'load-path "~/mu/mu4e/")
(require 'mu4e)
(setq mu4e-maildir "/home/joe/mail")
(setq mu4e-sent-folder "/Sent")
(setq mu4e-trash-folder "/Trash")
(setq mu4e-drafts-folder "/Drafts")
```

*Emacs*
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-02-04

**Comment by djcb** [comment]
Hmmm.... it seems the error is from code that's not being used anymore in 1.3.7 (and now removed). Could it be that you have some older version of mu lying around?

**Comment by holtzermann17** [comment]
Pretty sure not, because this is a new computer.  But, to simplify things, I started emacs with

```
emacs -Q -l mu4e-minimal.el
```

where the contents are like this:

```
;;; Mu4e

(add-to-list 'load-path "~/mu/mu4e/")
(require 'mu4e)
(mu4e-update-mail-and-index t)
(setq mu4e-get-mail-command "offlineimap -q")

(setq mail-user-agent 'mu4e-user-agent)
(setq mu4e-maildir "/home/joe/Maildir")
(setq mu4e-sent-folder "/Sent")
(setq mu4e-trash-folder "/Trash")
(setq mu4e-drafts-folder "/Drafts")
(setq mu4e-compose-complete-addresses nil)

(setq send-mail-function 'smtpmail-send-it)
(setq smtpmail-smtp-server "box.xxx.yyy")
(setq smtpmail-smtp-service 587)
(setq smtpmail-local-domain "xxx.yyy")

(setq user-mail-address "joseph.corneli@xxx.yyy")
(setq mu4e-user-mail-address-list '("joseph.corneli@xxx.yyy"))
```

Not only did that work -- I could start mu4e -- also, mu4e now works on my fully and standardly configured Emacs.  

From a user perspective this resolves my issue!  Still, it doesn't explain why this happened.  I might be able to replicate the problem if I create another new account on my mail server.

**Comment by CognDiss** [comment]
I had both these exact errors during my initial setup yesterday.  My case
was definitely due to running v1.2.0 of mu and 1.3.7 of mu4e.  Looks like
the communication format was changed dramatically sometime after 1.2.0.

mu4e-mu-binary was pointing to a pkg install version, whereas I was running
mu4e straight from my git clone.   Doing 'gmake install' and restarting
emacs fixed it.

*--tony*

**Comment by djcb** [comment]
Yeah, the error are from code that is not used anymore in the newer version, and I have removed it completely.
