### ISSUE TITLE
Changing mu home directory doesn't update root maildir

### ISSUE THREAD

**Issue by ravine-var** [djcb/mu#1569]
With master, the "--muhome" argument is not passed to mu-server when "mu4e-mu-home" is set to something other than the standard Maildir location. Since "mu4e-maildir" is obsolete now, this means that the root maildir is always the default.

Is there any other way to read a custom Maildir, or should "mu4e~proc-start" be fixed ?

Thanks.

**Comment by djcb** [comment]
I've made a few changes that should hopefully address this... can you check?

**Comment by ravine-var** [comment]
Yes, it works now. Thanks !
