### ISSUE TITLE
Problem after recent update

### ISSUE THREAD

**Issue by sewkokot** [djcb/mu#1570]
After today's git pull, when I start mu4e, I'm asked by mu4e:
[mu4e] ~/Maildir/sent does not exists. Create now?

The problem is that in ~/Maildir I have two directories: po and gmail

```
~/Maildir/po
spam
trash
drafts
sent
inbox
```
and
```
~/Maildir/gmail
starred
trash
sent
inbox
drafts
```

which are set according to mu4e-contexts
```
:enter-func (lambda ()
 (mu4e-message "Entering po inbox context")
 (my-mu4e-po-settings)
```
and in my-mu4e-po-settings function I have among others
```
    (setq user-mail-address "xx@yy.com")
    (setq mu4e-drafts-folder "/po/drafts")
    (setq mu4e-sent-folder   "/po/sent")
    (setq mu4e-trash-folder  "/po/trash")
```
and similarly for gmail.

What shall I do now to fix it?

**Comment by djcb** [comment]
Made some small changes that should help... can you check? Thanks!

**Comment by sewkokot** [comment]
Thank you! Now, it seems to work, and mu4e launches as before :) I will do more tests tomorrow when sending emails using various contexts.
