### ISSUE TITLE
Offer to cleanup indentation

### ISSUE THREAD

**Issue by tarsius** [djcb/mu#1571]
**Prelude:** I am excited that you have been working more on mu/mu4e recently and would like to help out with the elips side of things. Mu4e has been very stable for me in the past but recent changes brought some breaking changes with them. I'll investigate myself and if at all possible come up with solutions.

**And now:** While looking at recent changes I unfortunately ran into large accidental changes to whitespace. With your permission I would like to help out with that.

Currently the indentation is so inconsistent that I cannot even tell whether you want to use all spaces or the "tabs for indentation and spaces for alignment" style that is used in Emacs for elisp by default. I recommend you use only spaces, but the second approach works too, provided it is used consistently.

Once you have told me which indention style you intended to use, then I can:
1. ensure that you and all contributors will use that style going forward by setting `indent-tabs-mode` directory-locally, and
2. change all existing code to follow that style as well.

If you want I can also do something similar for other types of files.

**Comment by djcb** [comment]
Hey Tarsius,

There have been some quite big changes in the dev series recently, including a bit of breakage for use-cases that aren't mine; sorry about that! But I'm trying to follow-up quickly!

As for the indentation, I'm using the `.editorconfig` in the project root, which is a cross-editor way of specifying some of the settings. For elisp, there's:

```
[*.el]
indent_style                = space
indent_size                 = 2
max_line_length             = 100
```
we could _also_ add dir-locals, as these settings shouldn't change too often.

The indentation is indeed inconsistent, and in some case just _wrong_, but it's not always to see from PRs...

**Comment by tarsius** [comment]
> There have been some quite big changes in the dev series recently,
> including a bit of breakage for use-cases that aren't mine; sorry
> about that! But I'm trying to follow-up quickly!

No problem; I am happy to see you are actively working on this!

> [...] I'm using the `.editorconfig` in the project root, which is
> a cross-editor way of specifying some of the settings. For elisp,
> [...]

I think that *Emacs* lisp is almost always edited using Emacs, so configuring other editors is probably unnecessary in this case. ;-)

> The indentation is indeed inconsistent, and in some case just
> _wrong_, but it's not always to see from PRs...

I have some bad news for you.  The indentation is not wrong **despite** the use of `editorconfig` but **because** of the use of `editorconfig`.  Also its not the contributed changes that are intended wrong but the code that *you* write (because unlike most contributors you actually have `editorconfig' installed).

TODO link to pull-request

IMO the only reasonable course of action is to immediately stop using `editorconfig` for any Lisp code.  (Also this has shattered my trust in `editorconfig` completely, so personally I would stop using it for anything.)  I will raise this in the `editorconfig` repository, but I first have to calm down and I doubt it will ever be addressed properly.

**Comment by djcb** [comment]
That's not necessarily bad news :-) but it seems the editorconfig is much closer to the desired output, e.g., I guess something like:
```
(setq 
  indent-tags-mode nil
  lisp-indent-offset 2)
```
in the current changes, there are some big jumps (`lisp-indent-offset nil` I guess?) which don't look nice imho.

**Comment by tarsius** [comment]
I don't quite understand. Are you saying that you actually want to keep using this highly unusual indention style?

**Comment by djcb** [comment]
Hmmm... wasn't aware it was so unusual... but apparently it is.

**Comment by tarsius** [comment]
Thanks again!
