### ISSUE TITLE
Messages aren't decrypted

### ISSUE THREAD

**Issue by tarsius** [djcb/mu#1572]
## Expected or desired behavior

When viewing an encrypted mail, then the decrypted mail body should be displayed. If necessary I should be asked for my passphrase. In 1.3.6 that works and the header displayed in the view buffer ends with:

```
Decryption: 2 part(s) decrypted
```

## Actual behavior

When using `master`, then I am not prompted for my passphrase, no attempt is made to decrypt the encrypted part, and the header ends with:

```
Attachments: [1]1.msgpart(11), [2]2.msgpart(11.5K)
```

No message body is displayed.

## Steps to reproduce

As far as I can tell it is enough to use `master` and to try to view any encrypted mail.

## Versions of mu, mu4e/emacs, operating system 

The `master` branch. Last commit I tried was b77b536d8165cb154ce3f80bd29205ced5961c7d.

## Any other detail

I figured it might have something to do with the deprecation of `mu4e-user-mail-address-list`, but after setting my addresses directly in the database, the issue persisted.

**Comment by Chris00** [comment]
Do you have the Gnus based viewer enabled (`(setq mu4e-view-use-gnus t)`) or not?  If not, may you try enabling it and try again?

**Comment by tarsius** [comment]
Ups forgot to mention:

When I `(setq mu4e-view-use-gnus t)`, then the message is decrypted, however when I reply, then the message body isn't quoted (i.e. nothing follows after "So and so said:").

**Comment by tarsius** [comment]
Thanks! The body is being decrypted now.

> when I reply, then the message body isn't quoted (i.e. nothing follows after "So and so said:").

But this issue persists (regardless of the value of `mu4e-view-use-gnus`).
