### ISSUE TITLE
Error when no message is returned by the query

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1583]
## Expected or desired behavior

When a search returns no result, indicate it as such in `*mu4e-headers*`.

## Actual behavior

The following error is displayed.

error in process filter: Error 9: failed to run query: mu_msg_iter_new: xapian error 'The mset returned from the match does not contain the document at index 0' (line was:'(find :query "flag:unread AND NOT flag:trashed AND NOT maildir:/Spam" :threads t :sortfield :date :descending t :maxnum 500 :skip-dups nil :include-related nil)')

## Steps to reproduce

Leave no unread message and press <kbd>b u</bbd>.

## Versions of mu, mu4e/emacs, operating system etc.

Mu4e: commit 24ecceb1
Emacs 26.3 (Debian)

**Comment by djcb** [comment]
Hmm, are you still seeing this with all the latest?

**Comment by Chris00** [comment]
On 21 February 2020 at 21:21 CET, Dirk-Jan C. Binnema <notifications@github.com> wrote:
>
> Hmm, are you still seeing this with all the latest?

With the latest commits, it is fine.
