### ISSUE TITLE
mu4e-bookmark-query in mu4e-maildirs-extension

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1585]
## Expected or desired behavior

I just pulled the latest version of `mu` and the function `mu4e-bookmark-query` seems to be missing. The new function seems to be  `mu4e-get-bookmark-query`, although I haven't been able to find the previous definition of `mu4e-bookmark-query` to be able to replicate it.

This function is used in `mu4e-maildirs-extension` which is now broken.
I understand that this extension is not maintained by this repo, but can someone direct me to the old definition of `mu4e-bookmark-query` so I can fix it myself?

## Actual behavior
Broken `mu4e-maildirs-extension` due to missing `mu4e-bookmark-query`.

## Versions of mu, mu4e/emacs, operating system etc.
mu 1.3.8 (commit ac164b7e262af0d044714f5a6add71508cf5e5d9)
Emacs 26.3

**Comment by djcb** [comment]
` git log -S"mu4e-bookmark-query"` should do trick.

Anyway, the change is that the mu4e-bookmarks is now a list of plists, and you can query the `:query`. parameters for each of those.

**Comment by ayman** [comment]
@haji-ali I just submitted a (backwards compatible) pull request to fix it for mu 1.4 or greater. https://github.com/agpchil/mu4e-maildirs-extension/pull/54
