### ISSUE TITLE
`max-msg-size` has disappeared

### ISSUE THREAD

**Issue by norbusan** [djcb/mu#1591]
Commit f51846eefcdde72d1b70660a0e881d8cf0e0a013 removed support for the command line option `--max-msg-size`:
```
@@ -155,9 +164,6 @@ config_options_group_index (void)
                 "<address>"},
                {"nocleanup", 0, 0, G_OPTION_ARG_NONE, &MU_CONFIG.nocleanup,
                 "don't clean up the database after indexing (false)", NULL},
-               {"max-msg-size", 0, 0, G_OPTION_ARG_INT,
-                &MU_CONFIG.max_msg_size,
-                "set the maximum size for message files", "<size>"},
                {NULL, 0, 0, 0, NULL, NULL, NULL}
        };
 
```
but `max_msg_size` seems still to be used in several places, and is also mentioned in the man pages. Is this an oversight?

**Comment by norbusan** [comment]
Ah, so that option is gone. Thanks.

**Comment by djcb** [comment]
Yeah, the option is gone (and so should the manpage entry!), but we leave some of the infra in place, as it may come back in a different way.
