### ISSUE TITLE
mu4e-compose-resend wrong charset

### ISSUE THREAD

**Issue by grauschnabel** [djcb/mu#1593]
## Expected or desired behavior

When i use `mu4e-compose-resend` in the message buffer, a new message will be created, but the charset is wrong.

## Actual behavior

German view in the message buffer:  

> möglicherweise kommt die Antwort zu spät.

When using `mu4e-compose-resend` the new buffer looks like:

>  m=C3=B6glicherweise kommt die Antwort zu sp=C3=A4t.

## Versions of mu, mu4e/emacs, operating system etc.

Using the latest mu4e git, somewhere this week.

Thanks,
Martin

**Comment by djcb** [comment]
Yeah, `mu4e-compose-resend` is a rather blunt knife, which lets you edit the raw message as it is. This is as expected - though I can understand it's not as desired.

It would be a rather massive effort to make it "nice", but perhaps in the future we can piggy-back on the gnus backend.

**Comment by grauschnabel** [comment]
Can I add some hook for changing this behavior? On the other hand, I don't need it too much, so copy paste could do the job. The problem is, adding new umlauts sends the old one unchanged (and wrong) to the receiver.

**Comment by djcb** [comment]
See #1051, there are some ideas.
