### ISSUE TITLE
mu4e-compose-new fails to send email with non-empty subject

### ISSUE THREAD

**Issue by innerout** [djcb/mu#1595]
## Expected or desired behavior

Send successfully the email with a non empty subject.
## Actual behavior
When I attempt to send an email with some kind of subject Emacs throws an error instead of sending the email. The only way to send an email is to leave the subject empty. The error Emacs throws is Invalid regexp: "Class syntax is [[:digit:]]; missing brackets" .

## Steps to reproduce

Steps to reproduce
1) Call mu4e-compose-new
2) Fill the subject and the email sender sections
3) Attempt to send the email
## Versions of mu, mu4e/emacs, operating system etc.
Mu & Mu4e 1.3.9, Emacs 28.0.50.140437-1 ArchLinux

**Comment by djcb** [comment]
This is due to  `8d5e8cddab` in emacs, I think (might be fixed already).
