### ISSUE TITLE
Use gnus to handle decryption when composing reply if mu4e-view-use-gnus is t

### ISSUE THREAD

**Issue by alexmurray** [djcb/mu#1597]
## Expected or desired behavior
When replying to an encrypted message, it seems mu is used decrypt the message (which is currently being viewed) - since https://github.com/djcb/mu/commit/0465b273d37dd73f6f01dae9162cc1e13359e7f4 mu4e will use gnus to handle decryption when viewing a message so is it possible to also use gnus to handle decryption when composing a reply, that way mu should not have to try and decrypt the message at all.

## Actual behavior
When replying to a message, if `mu4e-decryption-policy` is `t`, mu is used to decrypt the message to form the reply but instead this has already been decrypted by gnus to view it so this is redudant.

## Versions of mu, mu4e/emacs, operating system etc.
mu/mu4e as of 0465b273d37dd73f6f01dae9162cc1e13359e7f4

**Comment by djcb** [comment]
We still need the decrypted message from mu though, we cannot _directly_ use gnus for that; at least not now, so the duplication is necessary.

It may be possible with a deeper integrated gnus-view, rest assured we'll avoid any mu-server work we can delegate to gnus instead. First thing will be viewing a message... but that will be post 1.4.

**Comment by alexmurray** [comment]
Ok no worries, thanks for the reply, will follow up post 1.4
