### ISSUE TITLE
*mu4e-loading* window doesn't disappear after *mu4e-view* is loaded

### ISSUE THREAD

**Issue by korayal** [djcb/mu#1598]
I am not entirely sure if this is directly related to mu4e or it is a Spacemacs-only issue. I've already [posted](https://github.com/syl20bnr/spacemacs/issues/13314) an issue there, but I think it makes sense to post it here too.

## Expected or desired behavior

When I select an email message from the headers buffer, I would expect a single window on my frame (or two if I want to be able to see the headers buffer too)

## Actual behavior

I get two windows in my frame, `mu4e-view` and `mu4e-loading`. and the latter (which is empty) fills up ~70-80% of the frame and never disappears.

## Steps to reproduce

* Start Spacemacs
* press SPC a M keys and select an email message

## Versions of mu, mu4e/emacs, operating system etc.
mu4e: latest revision available on master branch ( rev. 0465b273d37dd73f6f01dae9162cc1e13359e7f4 )

OS: gnu/linux
Emacs: 26.3
Spacemacs: 0.300.0
Spacemacs branch: develop (rev. 6d024e78930d4e53f7618b7d5c08f691e57b5bea)
Graphic display: t
Distribution: spacemacs
Editing style: hybrid
Completion: helm

**Comment by korayal** [comment]
I think I found the reason, this happens only when I enable `dotspacemacs-switch-to-buffer-prefers-purpose`.

**Comment by theophilusx** [comment]
Just FYI - running spacemacs develop and latest mu4e from git. I don't see this
issue. diffeences are emacs 27, spacemacs vim mode and using ivy rather
than helm. I have multiple 'contexts' (gmail, o365 and live.com). I see
2 windows - header view and *mu4e-loading* with the current message.

Koray AL <notifications@github.com> writes:

> I am not entirely sure if this is directly related to mu4e or it is a Spacemacs-only issue. I've already [posted](https://github.com/syl20bnr/spacemacs/issues/13314) an issue there, but I think it makes sense to post it here too.
>
> ## Expected or desired behavior
>
> When I select an email message from the headers buffer, I would expect a single window on my frame (or two if I want to be able to see the headers buffer too)
>
> ## Actual behavior
>
> I get two windows in my frame, `mu4e-view` and `mu4e-loading`. and the latter (which is empty) fills up ~70-80% of the frame and never disappears.
>
> ## Steps to reproduce
>
> * Start Spacemacs
> * press SPC a M keys and select an email message
>
> ## Versions of mu, mu4e/emacs, operating system etc.
> mu4e: latest revision available on master branch ( rev. 0465b273d37dd73f6f01dae9162cc1e13359e7f4 )
>
> OS: gnu/linux
> Emacs: 26.3
> Spacemacs: 0.300.0
> Spacemacs branch: develop (rev. 6d024e78930d4e53f7618b7d5c08f691e57b5bea)
> Graphic display: t
> Distribution: spacemacs
> Editing style: hybrid
> Completion: helm


--
Tim Cross

**Comment by theophilusx** [comment]
Actually, the *mue3-loading* buffer is only there when replying to a
message - otherwise it is *article*. Maybe your somehow triggering a
reply or something?

Koray AL <notifications@github.com> writes:

> I am not entirely sure if this is directly related to mu4e or it is a Spacemacs-only issue. I've already [posted](https://github.com/syl20bnr/spacemacs/issues/13314) an issue there, but I think it makes sense to post it here too.
>
> ## Expected or desired behavior
>
> When I select an email message from the headers buffer, I would expect a single window on my frame (or two if I want to be able to see the headers buffer too)
>
> ## Actual behavior
>
> I get two windows in my frame, `mu4e-view` and `mu4e-loading`. and the latter (which is empty) fills up ~70-80% of the frame and never disappears.
>
> ## Steps to reproduce
>
> * Start Spacemacs
> * press SPC a M keys and select an email message
>
> ## Versions of mu, mu4e/emacs, operating system etc.
> mu4e: latest revision available on master branch ( rev. 0465b273d37dd73f6f01dae9162cc1e13359e7f4 )
>
> OS: gnu/linux
> Emacs: 26.3
> Spacemacs: 0.300.0
> Spacemacs branch: develop (rev. 6d024e78930d4e53f7618b7d5c08f691e57b5bea)
> Graphic display: t
> Distribution: spacemacs
> Editing style: hybrid
> Completion: helm


--
Tim Cross

**Comment by djcb** [comment]
There's a recent change where the loading buffer got a dedicated mode (rather than "fundamental"). Apparently, spacemacs treats those differently?

**Comment by korayal** [comment]
@theophilusx do you have `dotspacemacs-switch-to-buffer-prefers-purpose` set in your init.el? By default it's set to `nil`, so if that's the case can you try it out with that set to `t`?

@djcb I've just started trying out mu4e again after a long while. I've started seeing this issue before your change from `fundamental` mode. I'm not sure if that's the case but it looks like spacemacs' use of [window purpose](https://github.com/bmag/emacs-purpose) messes with how mu4e interacts with buffers. In fact, if I turn on `purpose-mode` at the `*mu4e-headers*` buffer, I can replicate this exact behavior. When I turn it off, it works nicely.

**Comment by korayal** [comment]
Looks like the issue was caused by someone assigning the same purpose name ( `mail` ) on all mu4e buffers, which broke the 2-window-split layout of mu4e. (also the loading view didn't have any purpose assigned)) So when we're at the `*mu4e-headers*` buffer and select an e-mail, the *loading* buffer would grab the newly created lower window with a purpose name `general`, and when the e-mail is actually loaded in `*mu4e-view*`, it would take the window with the same purpose (`mail`) which is `*mu4e-headers*`.

I've [sent a PR](https://github.com/syl20bnr/spacemacs/pull/13331) to the Spacemacs project for this.
