### ISSUE TITLE
Regexp error when sending mail 

### ISSUE THREAD

**Issue by jtraer** [djcb/mu#1599]
## Expected or desired behavior

Up until yesterday mu4e in emacs worked great.

## Actual behavior

Beginning yesterday when I try to send a message (`C-c C-c`) nothing happens but the error:

`invalid regexp: "Class syntax is [[:digit:]]; missing brackets"` 

appears in the minibuffer.

Issue persists after restarts of both emacs and the computer. Any suggestions or advice would be greatly appreciated.

## Steps to reproduce

No idea. Not sure what changed.

## Versions of mu, mu4e/emacs, operating system etc.

mu 1.3.4
emacs 28.0.50
ubuntu 18.04.4

**Comment by jtraer** [comment]
Seems to have been fixed by updating emacs packages.  Nevermind...

**Comment by djcb** [comment]
See #1595.
