### ISSUE TITLE
compile error:  relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uuid_generate'

### ISSUE THREAD

**Issue by damon-kwok** [djcb/mu#1601]
## Expected or desired behavior

Please describe the behavior you expected / want

## Actual behavior

Please describe the behavior you are actually seeing. 

For bug-reports, if applicable, include error messages, emacs stack
traces etc. Try to be as specific as possible - when do you see this
happening? Does it happen always?  Sometimes? How often?

## Steps to reproduce

For bug-reports, please describe in as much details as possible how
one can reproduce the problem*.

## Versions of mu, mu4e/emacs, operating system etc.
mu configuration is complete.
------------------------------------------------
mu version                           : 1.2.0

Xapian version                       : 1.4.14
GLib version                         : 2.54.3
GMime version                        : 3.2.6
Emacs version                        : GNU Emacs 26.3

Have wordexp                         : yes
Build mu4e emacs frontend            : yes
Build 'mug' toy-ui (gtk+/webkit)     : no
McCabe's Cyclomatic Complexity tool  : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
------------------------------------------------

Now, type 'make' (or 'gmake') to build mu
## Any other detail

# make
make  all-recursive
make[1]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0'
Making all in m4
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/m4'
Making all in man
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/man'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/man'
Making all in lib
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/lib'
Making all in parser
make[3]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/lib/parser'
  CXX      tokenize.o
  CXX      parser.lo
  CXX      tokenizer.lo
  CXX      utils.lo
  CXX      xapian.lo
  CXXLD    libmuxparser.la
  CXXLD    tokenize.exe
  CXX      parse.o
  CXXLD    parse.exe
  CXX      test-tokenizer.o
  CXXLD    test-tokenizer.exe
  CXX      test-parser.o
  CXXLD    test-parser.exe
  CXX      test-utils.o
  CXXLD    test-utils.exe
make[3]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/lib/parser'
Making all in .
make[3]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/lib'
  CC       mu-bookmarks.lo
  CC       mu-contacts.lo
  CC       mu-container.lo
  CC       mu-date.lo
  CC       mu-flags.lo
  CC       mu-index.lo
  CC       mu-log.lo
  CC       mu-maildir.lo
  CC       mu-msg-crypto.lo
  CXX      mu-msg-doc.lo
  CC       mu-msg-fields.lo
  CC       mu-msg-file.lo
  CXX      mu-msg-iter.lo
  CC       mu-msg-part.lo
  CC       mu-msg-prio.lo
  CC       mu-msg-sexp.lo
  CC       mu-msg.lo
  CXX      mu-query.lo
  CC       mu-runtime.lo
  CC       mu-script.lo
  CXX      mu-store.lo
  CXX      mu-store-read.lo
  CXX      mu-store-write.lo
  CC       mu-str.lo
  CC       mu-threader.lo
  CC       mu-util.lo
  CXXLD    libmu.la
make[3]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/lib'
Making all in tests
make[3]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/lib/tests'
make  all-am
make[4]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/lib/tests'
  CC       test-mu-util.o
  CXX      dummy.o
  CC       test-mu-common.lo
  CCLD     libtestmucommon.la
  CXXLD    test-mu-util.exe
  CC       test-mu-str.o
  CXXLD    test-mu-str.exe
  CC       test-mu-maildir.o
  CXXLD    test-mu-maildir.exe
  CC       test-mu-msg-fields.o
  CXXLD    test-mu-msg-fields.exe
  CC       test-mu-msg.o
  CXXLD    test-mu-msg.exe
  CC       test-mu-store.o
  CXXLD    test-mu-store.exe
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../lib/libxapian.a(uuids.o):(.text+0xe): undefined reference to `uuid_generate'
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../lib/libxapian.a(uuids.o):(.text+0xe): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uuid_generate'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:659: test-mu-store.exe] Error 1
make[4]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/lib/tests'
make[3]: *** [Makefile:579: all] Error 2
make[3]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/lib/tests'
make[2]: *** [Makefile:708: all-recursive] Error 1
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0/lib'
make[1]: *** [Makefile:539: all-recursive] Error 1
make[1]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-1.2.0'
make: *** [Makefile:449: all] Error 2

**Comment by damon-kwok** [comment]
The same problem happened to 1.3.9 (git master 2020-02-29):

mu configuration is complete.
------------------------------------------------
mu version                           : 1.3.9

Xapian version                       : 1.4.14
GLib version                           : 2.54.3
GMime version                       : 3.2.6
Emacs version                         : GNU Emacs 26.3

Have wordexp                         : yes
Build mu4e emacs frontend            : yes
Build 'mug' toy-ui (gtk+/webkit)     : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
------------------------------------------------


Now, type 'make' (or 'gmake') to build mu

# make
make  all-recursive
make[1]: Entering directory '/home/Administrator/.emacs.d/libs/mu-git'
Making all in m4
make[2]: Entering directory '/home/Administrator/.emacs.d/libs/mu-git/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/Administrator/.emacs.d/libs/mu-git/m4'
Making all in man
make[2]: Entering directory '/home/Administrator/.emacs.d/libs/mu-git/man'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/Administrator/.emacs.d/libs/mu-git/man'
Making all in lib
make[2]: Entering directory '/home/Administrator/.emacs.d/libs/mu-git/lib'
make  all-recursive
make[3]: Entering directory '/home/Administrator/.emacs.d/libs/mu-git/lib'
Making all in utils
make[4]: Entering directory '/home/Administrator/.emacs.d/libs/mu-git/lib/utils'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/Administrator/.emacs.d/libs/mu-git/lib/utils'
Making all in query
make[4]: Entering directory '/home/Administrator/.emacs.d/libs/mu-git/lib/query'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/Administrator/.emacs.d/libs/mu-git/lib/query'
make[4]: Entering directory '/home/Administrator/.emacs.d/libs/mu-git/lib'
  CXXLD    test-mu-store.exe
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../lib/libxapian.a(uuids.o):(.text+0xe): undefined reference to `uuid_generate'
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../lib/libxapian.a(uuids.o):(.text+0xe): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `uuid_generate'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:1054: test-mu-store.exe] Error 1
make[4]: Leaving directory '/home/Administrator/.emacs.d/libs/mu-git/lib'
make[3]: *** [Makefile:1154: all-recursive] Error 1
make[3]: Leaving directory '/home/Administrator/.emacs.d/libs/mu-git/lib'
make[2]: *** [Makefile:965: all] Error 2
make[2]: Leaving directory '/home/Administrator/.emacs.d/libs/mu-git/lib'
make[1]: *** [Makefile:591: all-recursive] Error 1
make[1]: Leaving directory '/home/Administrator/.emacs.d/libs/mu-git'
make: *** [Makefile:501: all] Error 2

**Comment by djcb** [comment]
Seems you're using msys?

For the actual error, seems xapian needs a symbol `uuid_generate`, which is from a libuuid library which may not be present on your system. There's no need to explicitly mention it on the other platforms where mu compiles, so not quite sure what's different here.

I don't have msys so can't really help you any further... perhaps ask on the mailing if some else succeeded with msys, and how they did it.

**Comment by damon-kwok** [comment]
@djcb  yes, i using msys2-x86_64 , if i use the mu-1.0, it's ok, 1.2 and 1.3.9(git-master) failure. uuid_generate is exist, it includes in libutils-linux-devel.

·
# pacman -F uuid.h
msys/libutil-linux-devel 2.35-1 [installed]
    usr/include/uuid/uuid.h

·

**Comment by djcb** [comment]
Hmm... seems we need to mention it explicitly. I've made a small update so during configure we check for `xapian-core.pc`, which should provide the correct linking options.

Make sure you have `xapian-core.pc` from your Xapian installation in the directory `PKG_CONFIG_PATH` points to (or the default). Does that help?

**Comment by damon-kwok** [comment]
okay

**Comment by damon-kwok** [comment]
@djcb  aha!，we did it！

make
make  all-recursive
make[1]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git'
Making all in m4
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/m4'
Making all in man
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/man'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/man'
Making all in lib
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/lib'
make  all-recursive
make[3]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/lib'
Making all in utils
make[4]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/lib/utils'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/lib/utils'
Making all in query
make[4]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/lib/query'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/lib/query'
make[4]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/lib'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/lib'
make[3]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/lib'
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/lib'
Making all in mu
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/mu'
make  all-am
make[3]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/mu'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/mu'
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/mu'
Making all in mu4e
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/mu4e'
make[3]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/mu4e'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/mu4e'
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/mu4e'
Making all in contrib
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/contrib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/contrib'
Making all in toys
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/toys'
make[3]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/toys'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/toys'
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git/toys'
make[2]: Entering directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git'
make[2]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git'
make[1]: Leaving directory '/home/Administrator/.emacs.d/pkgs/mu/mu-git'

**Comment by damon-kwok** [comment]
#1602

**Comment by djcb** [comment]
Great!

**Comment by damon-kwok** [comment]
@djcb 
The build steps：
`
https://github.com/msys2-unofficial/MSYS2-packages/blob/master/mu/README.org

https://github.com/msys2-unofficial/MSYS2-packages`

**Comment by djcb** [comment]
Thanks! Update the docs.
