### ISSUE TITLE
Can mu server process use multiple cores?

### ISSUE THREAD

**Issue by bhanuvrat** [djcb/mu#1603]
## Expected or desired behavior

Use all available cores of the system for faster search results.

## Actual behavior

Only one of the cores of my machine were being choked at 100% while the rest were idle.

## Steps to reproduce

Search a fairly large mailbox.

## Versions of mu, mu4e/emacs, operating system etc.

mu 1.1.0
emacs 26.3

**Comment by djcb** [comment]
The searches are done using Xapian, which doesn't really support that (and would be a major effort to add, I suspect).

Still, most queries should be quite fast, and the mu server process is not doing anything most of the time (esp. when only doing searches). Do you have any specific queries that are slow? How many messages do you have?
