### ISSUE TITLE
Can't move refile/messages

### ISSUE THREAD

**Issue by m-ar-c** [djcb/mu#1609]
Table of Contents
─────────────────

1. Description of the issue
2. Additional information
.. 1. mu4e setup
..... 1. Appearance
..... 2. Smart refiling
..... 3. Encryption
..... 4. Attachments reminder
..... 5. mu4e contexts
..... 6. mu4e-alert
.. 2. Versions of the tools
..... 1. Emacs version
..... 2. maildir-utils
..... 3. mu4e
..... 4. Operating system

1 Description of the issue
══════════════════════════

  Hi, I can't move/refile messages anymore. I mark the message to be
  moved, execute the mark, then the mark disappear and the message is
  still there. No (error) message of any kind.

  I don't know if it is related, but It happened after I moved my whole
  emacs/mu4e setup to a new machine (not the first time I do so, first
  time I got this issue). I did index all my messages again.

  I retrieve my messages with fdm via pop.

 I suspected rigths issues but `chmod 777 -R /folderto/Maildirs` does
 not solve the  problem.

  Here is some technical information below. I'm willing to do tests/provide
  more information of course.

2 Additionnal information
═════════════════════════

2.1 mu4e setup
`──────────────`
```lisp
(require 'mu4e)
   
     (setq mu4e-maildir       "~/Maildirs"   ;; top-level Maildir
   	      ;; what follow is relative to the 'mu4e-maildir' path
   	      mu4e-sent-folder   "/my_box/sent"       ;; folder for sent messages
   	      mu4e-drafts-folder "/my_box/drafts"     ;; unfinished messages
   	      mu4e-trash-folder  "/my_box/trash"      ;; trashed messages
   	      mu4e-refile-folder "/my_box/Archives")   ;; saved messages
   
     (setq mu4e-view-show-addresses t
   	      mu4e~headers-sort-field :date
  	      mu4e-headers-show-threads nil)
   
   (setq message-send-mail-function 'message-send-mail-with-sendmail)
   (setq sendmail-program "/usr/bin/msmtp")
   
   (setq mu4e-get-mail-command "true"
   	    mu4e-update-interval 600)

   (setq mu4e-maildir-shortcuts
   	'(("/my_box/inbox"     . ?m)
   	  ("/my_box2/inboX"     . ?l)
   	  ("/my_box3/inbox"   . ?x)
   	  ("/IMAP"   . ?i)
   	  ("/mybox4/inbox"      . ?v)))
 
  
   (setq mail-user-agent 'mu4e-user-agent)` 
```

2.1.1 Appearance
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌

```lisp
     (setq mu4e-headers-fields
 	    '(
 	      (:human-date          .  25)    ;; alternatively, use :human-date
 	      (:flags         .   6)
 	      (:from          .  22)
 	      (:to          .  22)
 					      ;       (:message-id    .  nil)
 	      (:size . nil)
 	      (:subject       .  nil)
 	      )
 	    ) ;; alternatively, use :thread-subject
 
 (setq mu4e-view-fields '(:from :to :cc :subject :flags :date :maildir :mailing-list :attachments :signature))
 
 (setq mu4e-split-view 'horizontal)
 (setq mu4e-headers-visible-lines '25)
 (setq mu4e-view-use-gnus t)
 (setq  mu4e-hide-index-messages nil)
```

2.1.2 Smart refiling
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌

```lisp
(setq mu4e-refile-folder
  (lambda (msg)
    (cond
	;; messages to the mu mailing list go to the /mu folder
	((mu4e-message-contact-field-matches msg :to
	"string_here")
	 "/mybox/Archives/MMA")
	((mu4e-message-contact-field-matches msg :cc
	"another_string_here")
	 "/mybox/Archives/MMA")
	((mu4e-message-contact-field-matches msg :cc
	"mailhere")
	 "/mybox3/Archives/somefolder")
	((mu4e-message-contact-field-matches msg :to
	"another_mail_here")
	 "/mybox3/Archives/someotherfolder")
	((mu4e-message-contact-field-matches msg :to
	"yet_another_mail")
	 "/mybox3/Archives/another_folder")

	((find-if
	 (lambda (addr)
	   (mu4e-message-contact-field-matches msg :from addr))
	 mu4e-user-mail-address-list)
	mu4e-sent-folder)
	;; everything else goes to /archive
	;; important to have a catch-all at the end!
	(t  "/mybox/Archives"))))
```

2.1.3 Encryption
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
```lisp
(setq mm-sign-option 'guided)

  (add-hook 'message-send-hook
	    (lambda ()
	      (unless (yes-or-no-p "Sure you want to send this?")
		(signal 'quit nil))
	      )
	    )
```

2.1.4 Attachments reminder
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌

```lisp
 (set-face-attribute 'font-lock-warning-face nil :foreground "red" :weight 'bold :background "yellow")
 (add-hook 'mu4e-compose-mode-hook
 	  (defun bjm/mu4e-highlight-attachment ()
 	    "Flag attachment keywords"
 	    (font-lock-add-keywords nil
 				    '(("\\(attach\\|pdf\\|file\\|fichier\\|joint\\|veuillez trouver\\|pièce\\)" 1 font-lock-warning-face t)))))
```

2.1.5 mu4e contexts
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌

```lisp
(setq mu4e-contexts
    `( ,(make-mu4e-context
	  :name "Private"
	  :enter-func (lambda () (mu4e-message "Entering Private context"))
	  :leave-func (lambda () (mu4e-message "Leaving Private context"))
	  :match-func (lambda (msg)
			(when msg 
			  (mu4e-message-contact-field-matches msg 
			    :to "mybox@box.net")))
	  :vars '( ( user-mail-address      . "mybox@box.net"  )
		   ( user-full-name         . "mybox" )
		     ))
	 ,(make-mu4e-context
	  :name "Work"
	  :enter-func (lambda () (mu4e-message "Switch to the Work context"))
	  :match-func (lambda (msg)
			(when msg
			  (string= (mu4e-message-field msg :maildir) "/mybox4")))
	  :vars '( ( user-mail-address       . "mybox4@mybox4.ch" )
		   ( user-full-name          . "my box4" )
			 ))

	 ,(make-mu4e-context
	  :name "mybox3"
	  :enter-func (lambda () (mu4e-message "Switch to the mybox3 context"))
	  :match-func (lambda (msg)
			(when msg
			  (string= (mu4e-message-field msg :maildir) "/mybox3")))
	  :vars '( ( user-mail-address       . "mybox3@box.net" )
		   ( user-full-name          . "mybox3" )
		   ( mu4e-compose-signature  . nil)))))
```
2.1.6 mu4e-alert
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌

```lisp
(mu4e-alert-set-default-style 'libnotify)
(add-hook 'after-init-hook #'mu4e-alert-enable-notifications)
```

2.2 Versions of the tools
─────────────────────────

2.2.1 Emacs version
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌

  GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of
  2019-09-23, modified by Debian

2.2.2 maildir-utils
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌

  • Paquet : maildir-utils
  • Version : 1.2.0-2

2.2.3 mu4e
╌╌╌╌╌╌╌╌╌╌

  • Paquet : mu4e
  • Version : 1.2.0-2

2.2.4 Operating system
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌

  • Description: Ubuntu 19.10
  • Release: 19.10
  • Codename: eoan

**Comment by m-ar-c** [comment]
It turns out I _can_ move the recent emails and the messages stubbornly still staying in my inbox are also where I chose to move them to. mu4e lists 286 emails in (one of) my inbox(s), whereas there is only 216 files/emails in the maildir (number found with `find path/to/my/inbox/ -type f | wc -l`).

I tried to grep in the maildir the content of one of the message I can't move and indeed I got no result. It means mu4e show me messages that do not exists anymore. How is that possible ? What could I do to "update' mu4e. (mu4e just slowly re-indexed my 102000 emails, but nothing changed)

**Comment by djcb** [comment]
Note, mu4e shows _related_ messages as well (by default); is that perhaps what you are seeing?

**Comment by m-ar-c** [comment]
Indeed, after setting `(setq mu4e-headers-include-related nil)` the count of messages shrank to 216 ! Thanks.

Weird it's the first time I encounter this, after several years of using mu4e.

I must say it's rather confusing (at least for me) to have, by default, in my _inbox_, messages not really there.
