### ISSUE TITLE
Wrong count on bookmarks (how to force recalculation)

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1615]
## Expected or desired behavior

I expect the number next to a bookmark to be consistent with the number of messages that that bookmark shows. 

## Actual behavior

For some reason, all my bookmarks have inconsistent message numbers (read and unread) on one of my machines (Off by 3 to 6). I am not sure what the reason is and this behaviour is not exhibited by another machine that I have. 

I tried the following the reset the counts:
- Restart emacs
- Run `mu index`
- Update mu to latest version, delete the mu cache directory and run `mu init --maildir ~/.mail && mu index`

But the wrong message count persisted. I also checked duplicate messages (by pressing `V`) and the shown messages in the bookmark did not increase.

I am not sure what else to try and what other info would help troubleshoot this problem.

## Versions of mu, mu4e/emacs, operating system etc.
mu (mail indexer/searcher) version 1.3.9
Emacs 26.2
OS: CentOS 7

**Comment by theophilusx** [comment]
I believe I'm seeing the same. My unread bookmark shows 9 messages as
unread, but when I visit that bookmark, I only have 2. When I do read
one, the count does decrease by 1, but I don't know why it then says 8
unread when I have only 1.

mu version 1.3.9 (head of git repo)
Emacs 27.0.90 (from git head yesterday)
Linux ubuntu.

**Comment by theophilusx** [comment]
Just noticed that if I run mu index on command line, it appears to 'fix'
the issue. However, running update from within mu4e does not. Wonder if
this is related to recent change where cleanup is turned off when doing
update within mu4e to speed things up?

**Comment by haji-ali** [comment]
I am not sure it's the same issue since I tried re-indexing from the command line and I still had the wrong count.
I am also noticing that the number just seem to increase but not decrease. (So getting a new message increases the total and unread count but marking it read and refiling it does not decrease the counts).

**Comment by djcb** [comment]
For speed-reasons, the count does not check for duplicates, nor does it check if the file for a given message still exist; esp. the second can be quite slow on some systems (which is also why we're defaulting to `nil` now for `mu4e-index-cleanup`).

**Comment by haji-ali** [comment]
That's understandable, but how do I force a recount or cleanup my database so that I don't have the wrong counts?

**Comment by djcb** [comment]
Well, `g` in the main screen will re-query things. 

Apart from that, running `mu index` without any options to make it faster should clear out stale messages, as @theophilusx mentions 

(I've changed the default for `mu4e-index-cleanup` back to `t`)

**Comment by djcb** [comment]
Anyway, thanks for the report; I've update the docs / added to the FAQ to inform users.
