### ISSUE TITLE
Feature request: Prevent indexing from blocking mu4e

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1618]
## Expected or desired behavior
When indexing is running in the background, it would be great if mu4e was still responsive.

## Actual behavior

At the moment, indexing (which seems to run at semi-random times and take several seconds on my email setup), blocks mu4e and I get a lot of "Searching..." messages for several seconds (Incidentally a more informative message like "Indexing" would be helpful here). 

Couldn't mu work with two indices? One active one and one temporary?
So that when re-indexing happens on a temporary index, mu4e uses the active index and remains responsive. When indexing is done, the temporary index becomes active.

## Versions of mu, mu4e/emacs, operating system etc.
mu version 1.3.10
Emacs 26.2

**Comment by djcb** [comment]
we might make mu multi-threaded at some point in the future, which might help for this. But this is not planned at the current time.
