### ISSUE TITLE
Enable org links to search result (in addition to single message)

### ISSUE THREAD

**Issue by schoettl** [djcb/mu#1619]
## Expected or desired behavior

It would be nice to allow org links to a mu4e search:

```
[[mu4e:from:me subject:hi]]
[[mu4e:from:me+subject:hi]]
[[mu4e:from:me%20subject:hi]]
```
(I'm not sure about the URI/link syntax)

If mu finds multiple matching messages (instead of exactly one with `[[mu4e:msgid:xxx@yyy]]`), it should show the *mu4e-headers* view.

## Actual behavior

If I try one of the org links above, I get

```
[mu4e] mu4e: unrecognized link type '<search-query>'
```

**Comment by djcb** [comment]
This is already possible; see the org-mode links section in the  manual.
    file:///home/djcb/Sources/mu/mu4e/mu4e/Org_002dmode-links.html#Org_002dmode-links

**Comment by schoettl** [comment]
Oh, looks like I did not update the mu AUR package on Arch for a long time. I was still with version 1.2.

Thanks!
