### ISSUE TITLE
Sending email is not asynchronous and rather slow

### ISSUE THREAD

**Issue by zakkak** [djcb/mu#162]
I am running mu4e 0.9.9.5-dev6 (checked out from trunk) on emacs 24.3.1

When I send a message emacs blocks.
In the test case I am using the documentaion's configuration for gmail.

It wouldn't be much of a problem if the sending was fast, but it takes some time and it is really annoying to have emacs blocked until it ends.

Congrats for the great Job

**Comment by sje30** [comment]
hi @tmalsburg 
picking up this old thread... did you ever find a reliable solution to asynchronously sending emails in mu4e?  I note your comment from Nov 2013, which is worrying.  I'd like asynchronous sending of emails, but I'd also like to know for sure that they were sent!

**Comment by tmalsburg** [comment]
@sje30 I didn't investigate further.  E-mail is too important for me to experiment with this.

**Comment by sje30** [comment]
thanks.  that was my concern too.
