### ISSUE TITLE
decrypt-move messages

### ISSUE THREAD

**Issue by Quintus** [djcb/mu#1620]
I'm currently a mutt user and would like to handle my mail with Emacs instead, thus I'm considering mu4e. There's however one feature of mutt that I haven't found any equivalent for in mu4e which I use all the time: the [decrypt-save function](http://mutt.org/doc/manual/#index-map) in mutt's index menu. This function decrypts the message from PGP/MIME and stores it as an ordinary unencrypted message on disk. Since my hard drive is encrypted, this does not pose a problem in my threat model, and it allows me to properly search the content of the encrypted messages.

So, is there an equivalent feature in mu4e? If not, I'd like to request its addition.

**Comment by djcb** [comment]
There's no such function, and I'm not planning on adding it... it seems a little unsafe!

(Note: you could  probably concoct something using the gnus functionality in this area; might not even be very hard.)

**Comment by Quintus** [comment]
> There's no such function, and I'm not planning on adding it...

Too bad. What I am doing currently to work around the problem is to use this script which I finally found: https://github.com/mmehnert/maildir-decrypt/blob/master/decrypt-email.pl

It is written for notmuch, but I found out it can also work with mu4e. I defined a decryption action:

~~~~~~~~~~~~~ elisp
(add-to-list 'mu4e-headers-actions '("decrypt this message permanently" . quintus-mu4e-decrypt-message) t)
(add-to-list 'mu4e-view-actions '("decrypt this message permanently" . quintus-mu4e-decrypt-message) t)
~~~~~~~~~~~~~

`quintus-mu4e-decrypt-message` then shells out to the `decrypt-email` script:

~~~~~~~~~~~~~ elisp
(defun quintus-mu4e-decrypt-message (msg)
  "Decrypts `msg' and permanently overwrites it with the decrypted version."
  (with-temp-buffer
    (let* ((eml-path (mu4e-message-field msg :path))
           (result (call-process "decrypt-email" eml-path t nil)))
      (if (eq result 0)
          (progn
            (write-region (point-min) (point-max) eml-path)
            (message "Wrote decrypted version to `%s'" eml-path))
        (error "decrypt-email failed with status %d" result)))))
~~~~~~~~~~~~~

It is not pretty, but it does work. I have experienced no data loss with it so far.

> (Note: you could probably concoct something using the gnus functionality in this area; might not even be very hard.)

I tried to come up with something, but it turned out to be too complex for me. I have no real insights into how e-mail MIME handling works and at the moment I lack the time for reading the relevant RFCs.

> it seems a little unsafe!

I am unsure what you mean by this. As explained, this `decrypt-email` script I found has not caused data loss for me. Storing decrypted message on itself is a judgment I have made for me as reasonable, given my hard disk is encrypted. The advantage of searchability by far outweights the theoritical remaining risk.

  -quintus

**Comment by djcb** [comment]
Okay, cool. I meant "unsafe" in the sense that an encrypted message is being exposed, and depends on secondary measures (like an encrypted disk) for its security. I'd rather make that a conscious user-decision (like with your script).

Anyway, glad it works for you!

**Comment by Quintus** [comment]
> I'd rather make that a conscious user-decision (like with your script).

I see. Though, even with providing a function, binding it to an action would still be a conscious user measure. The functionality does not have to be enabled by default. That is how it is with mutt, for instance: it does provide `decrypt-save`, but it does not bind it to any keybinding by default. That is left to the user. Likewise, mu4e could provide such a function, but not bind it to any key by default.

> Anyway, glad it works for you!

It does. I would prefer a native elisp solution, though. But I can see your point.
