### ISSUE TITLE
mu server seems to pong a corrupted version of the ping

### ISSUE THREAD

**Issue by tarsius** [djcb/mu#1621]
## Expected or desired behavior

The command `mu4e` should bring up the main view.

## Actual behavior

It silently fails. After adding some debug statements (see below) I believe that is because `mu server`'s prints things that are not proper response sexps. Failing to parse the text results in the sexp being `nil` so the process filter does nothing. (If a response is expected and we get `nil` instead, then an error should probably be raised.

## Steps to reproduce

Add some more debug statements:

```diff
diff --git a/mu4e/mu4e-proc.el b/mu4e/mu4e-proc.el
@@ -148,7 +148,9 @@ (defun mu4e~proc-filter (_proc str)
   `mu4e-compose-func'."
   (mu4e-log 'misc "* Received %d byte(s)" (length str))
   (setq mu4e~proc-buf (concat mu4e~proc-buf str)) ;; update our buffer
+  (mu4e-log 'from-server "text: %S" mu4e~proc-buf)
   (let ((sexp (mu4e~proc-eat-sexp-from-buf)))
+    (mu4e-log 'from-server "sexp: %S" sexp)
     (with-local-quit
       (while sexp
         (mu4e-log 'from-server "%S" sexp)
```

Run `mu4e`:

```
emacs -Q -L /usr/local/share/emacs/site-lisp/mu4e -l mu4e \
  -f mu4e-toggle-logging -f mu4e-show-log -f mu4e
```

The output is:

```
2020-03-19 20:09:23 logging enabled
2020-03-19 20:09:23 -> (ping :queries ("flag:unread AND NOT flag:trashed" "date:today..now" "date:7d..now" "mime:image/*"))
2020-03-19 20:09:23 -> (contacts :personal nil :after "2014-01-01" :tstamp "0")
2020-03-19 20:09:23 * Received 271 byte(s)
2020-03-19 20:09:23 <- text: ";; Welcome to the mu 1.3.10 command-server
;; Use (help) to get a list of commands, (quit) to quit.
;; mu% (ping :queries (\"flag:unread AND NOT flag:trashed\" \"date:today..now\" \"date
e:7d..now\" \"mime:image/*\"))(contacts :personal nil :after \"2014-01-01\" :tstamp \"0\"
\"))"
2020-03-19 20:09:23 <- sexp: nil
```

The output contains `^M` and `^H`, which Github cannot display properly.

## Versions of mu, mu4e/emacs, operating system etc.

* mu (mail indexer/searcher) version 1.3.10
* mu4e-mu-version => Its value is "1.3.10"
* emacs-version => Its value is "26.3"

## Any other detail

I went back to the mu/mu4e version from before my latest pull, but the issue persisted. I also tried different Emacs versions and always made sure that the old byte-code was gone before recompiling.

**Comment by tarsius** [comment]
If I run  `mu server` in a terminal, things seem to work:

```$ mu server
;; Welcome to the mu 1.3.10 command-server
;; Use (help) to get a list of commands, (quit) to quit.
;; mu% (ping :queries ("flag:unread AND NOT flag:trashed" "date:today..now" "date:7d..now" "mime:image/*"))
�1a5�(:pong "mu" :props (:version "1.3.10" :personal-addresses ("jonas@bernoul.li" "jonasbernoulli@gmail.com" ) :database-path "/home/jonas/.cache/mu/xapian" :root-maildir "/home/jonas/Maildir" :doccount 110823 :queries ((:query "flag:unread AND NOT flag:trashed" :count 177 :unread 177)(:query "date:today..now" :count 0 :unread 0)(:query "date:7d..now" :count 596 :unread 260)(:query "mime:image/*" :count 227 :unread 9))))
```

**Comment by djcb** [comment]
Thanks for the detailed steps -- but I cannot reproduce the problem. The `sexp: nil` is expected (since it's the result of evaluating the comment text). Do

This is what I get:
```
2020-03-20 00:32:18 logging enabled
2020-03-20 00:32:18 -> (ping :queries ("flag:unread AND NOT flag:trashed" "date:today..now" "date:7d..now" "mime:image/*"))
2020-03-20 00:32:18 -> (contacts :personal nil :after "2022-01-01" :tstamp "0")
2020-03-20 00:32:18 * Received 208 byte(s)
2020-03-20 00:32:18 <- text: ";; Welcome to the mu 1.3.10 command-server
;; Use (help) to get a list of commands, (quit) to quit.
;; mu% (ping :queries (\"flag:unread AND NOT flag:trashed\" \"date:today..now\" \"date:7d..now\" \"mime:image/*\"))
"
2020-03-20 00:32:18 <- sexp: nil
2020-03-20 00:32:18 * Received 412 byte(s)
2020-03-20 00:32:18 <- text: ";; Welcome to the mu 1.3.10 command-server
;; Use (help) to get a list of commands, (quit) to quit.
;; mu% (ping :queries (\"flag:unread AND NOT flag:trashed\" \"date:today..now\" \"date:7d..now\" \"mime:image/*\"))
\376190\377(:pong \"mu\" :props (:version \"1.3.10\" :personal-addresses (\"djcb@djcbsoftware.nl\" ) :database-path \"/home/djcb/.cache/mu/xapian\" :root-maildir \"/home/djcb/Maildir\" :doccount 86300 :queries ((:query \"flag:unread AND NOT flag:trashed\" :count 31804 :unread 31804)(:query \"date:today..now\" :count 1 :unread 1)(:query \"date:7d..now\" :count 86 :unread 29)(:query \"mime:image/*\" :count 2365 :unread 304))))
;; mu% "
2020-03-20 00:32:18 <- sexp: (:pong "mu" :props (:version "1.3.10" :personal-addresses ("djcb@djcbsoftware.nl") :database-path "/home/djcb/.cache/mu/xapian" :root-maildir "/home/djcb/Maildir" :doccount 86300 :queries ((:query "flag:unread AND NOT flag:trashed" :count 31804 :unread 31804) (:query "date:today..now" :count 1 :unread 1) (:query "date:7d..now" :count 86 :unread 29) (:query "mime:image/*" :count 2365 :unread 304))))
2020-03-20 00:32:18 <- (:pong "mu" :props (:version "1.3.10" :personal-addresses ("djcb@djcbsoftware.nl") :database-path "/home/djcb/.cache/mu/xapian" :root-maildir "/home/djcb/Maildir" :doccount 86300 :queries ((:query "flag:unread AND NOT flag:trashed" :count 31804 :unread 31804) (:query "date:today..now" :count 1 :unread 1) (:query "date:7d..now" :count 86 :unread 29) (:query "mime:image/*" :count 2365 :unread 304))))
2020-03-20 00:32:18 * Received 106 byte(s)
2020-03-20 00:32:18 <- text: ";; mu% (contacts :personal nil :after \"2014-01-01\" :tstamp \"0\")
\37626\377(:contacts () :tstamp \"31657141961\")

;; mu% "
2020-03-20 00:32:18 <- sexp: (:contacts nil :tstamp "31657141961")
2020-03-20 00:32:18 <- (:contacts nil :tstamp "31657141961")
```
When did this start happening?

**Comment by tarsius** [comment]
> When did this start happening?

I am not sure.  As I mentioned going back to an earlier version did not fix the issue.

I do however know that it still worked after I updated to 58b462d4c3b19601bea21864103ed35e37942809 about two weeks ago.  It may also still have worked after I updated to 59fb7438515a5ab20df92c11f686aba5404efb1d about one week ago.  I am sure it did not work anymore after I updated to c3bb04150f5b8981fc93ceced843ae5b8e47ab87 to days ago.

But again, if I go back to 58b462d4c3b19601bea21864103ed35e37942809 or even 1.3.9 *now*, then it does not work.  It very much looks like this is *not* due to a change in mu4e, but I am completely lost as to what could cause this, so I have brought it up here, in case you have some idea.

---

Off topic: You often forget to push release tags.  Right now for example you still have not pushed 1.3.10 even though the "bump to 1.3.10" commit is five days old now.  Do you use Magit to push? If so I can give you instructions on how to avoid this in the future.

**Comment by tarsius** [comment]
Do you have any idea what could be wrong? Or what I could do to find out?

My uneducated guess is that it has something to do with the wrong coding systems being used but you seem to set those explicitly and playing around with that did not help.

**Comment by djcb** [comment]
It's weird... I have no idea at this moment; you're also using 26.3 and not e.g. emacs-from-git, so that can't explain it either. And your emacs -Q recipe also ensures a clean environment, so it's not like some other package could influence this... Also, it seems you're currently the only victim.

I want to get to the bottom of this. Hope I have some time in the next days to do a bit more analysis

**Comment by djcb** [comment]
Note that I don't see any 'corruption' in your log; e.g. `\376190\377` is a length-cookie preceding the blobs of data we get back from the server. 

Perhaps try to see if `mu4e~pong-handler` gets called, if so, with what parameters. E.g.,
```
@@ -777,6 +777,7 @@ nothing."
 
 (defun mu4e~pong-handler (data func)
   "Handle 'pong' responses from the mu server."
+  (message "PONG HANDLER %S %S" data func)
   (setq mu4e~server-props (plist-get data :props)) ;; save info from the server
   (let ((doccount (plist-get mu4e~server-props :doccount)))
     (unless (mu4e-context-current)
```
gives me (after starting mu4e):
```
PONG HANDLER (:pong "mu" :props (:version "1.3.10" :personal-addresses ("djcb@djcbsoftware.nl") :database-path "/home/djcb/.cache/mu/xapian" :root-maildir "/home/djcb/Maildir" :doccount 86380 :queries ((:query "flag:unread AND NOT flag:trashed" :count 31800 :unread 31800) (:query "date:today..now" :count 4 :unread 4) (:query "date:7d..now" :count 89 :unread 26) (:query "mime:image/*" :count 2367 :unread 304)))) mu4e~main-view
```

**Comment by tarsius** [comment]
> Perhaps try to see if `mu4e~pong-handler` gets called, if so, with what parameters. E.g.,

I've just done that and it does not get called. That's not much of a surprise; since the text cannot be read `sexp` is always nil, etc.

**Comment by djcb** [comment]
Okay, so at least we've isolated the problem a _little_ bit. So you never get the `(pong` ?
The first `nil` is expected at least.

**Comment by djcb** [comment]
Let's try to fix this!

When I try with emacs 26.3, and the exact recipe you sent, I cannot reproduce.
With logging enabled, what does the log `M-: (mu4e~proc-ping) RET` look like?

**Comment by tarsius** [comment]
```
emacs -Q -L /usr/local/share/emacs/site-lisp/mu4e -l mu4e \
   -f mu4e-toggle-logging -f mu4e-show-log --eval '(mu4e~proc-ping)'
```

```
2020-04-04 15:14:25 logging enabled
2020-04-04 15:14:25 -> (ping :queries nil)
2020-04-04 15:14:25 * Received 127 byte(s)
2020-04-04 15:14:25 <- text: ";; Welcome to the mu 1.3.10 command-server
;; Use (help) to get a list of commands, (quit) to quit.
;; mu% (ping :queries nil)"
2020-04-04 15:14:25 <- sexp: nil
```

**Comment by djcb** [comment]
Ah, thanks. The `sexp: nil` is expected, but what is unexpected is a missing `(pong ...)` after that. I get:

```
/usr/bin/emacs-26.3 -Q -L /usr/local/share/emacs/site-lisp/mu4e -l mu4e \
   -f mu4e-toggle-logging -f mu4e-show-log --eval '(mu4e~proc-ping)'
```

```
2020-04-04 16:49:22.934 logging enabled
2020-04-04 16:49:22.935 -> (ping :queries nil)
2020-04-04 16:49:22.980 * Received 127 byte(s)
2020-04-04 16:49:22.980 <- text: ";; Welcome to the mu 1.3.10 command-server
;; Use (help) to get a list of commands, (quit) to quit.
;; mu% (ping :queries nil)
"
2020-04-04 16:49:22.980 <- sexp: nil
2020-04-04 16:49:22.983 * Received 194 byte(s)
2020-04-04 16:49:22.983 <- text: ";; Welcome to the mu 1.3.10 command-server
;; Use (help) to get a list of commands, (quit) to quit.
;; mu% (ping :queries nil)
\376b7\377(:pong \"mu\" :props (:version \"1.3.10\" :personal-addresses (\"djcb@djcbsoftware.nl\" ) :database-path \"/home/djcb/.cache/mu/xapian\" :root-maildir \"/home/djcb/Maildir\" :doccount 86420 ))
;; mu% "
2020-04-04 16:49:22.983 <- sexp: (:pong "mu" :props (:version "1.3.10" :personal-addresses ("djcb@djcbsoftware.nl") :database-path "/home/djcb/.cache/mu/xapian" :root-maildir "/home/djcb/Maildir" :doccount 86420))
2020-04-04 16:49:22.983 <- (:pong "mu" :props (:version "1.3.10" :personal-addresses ("djcb@djcbsoftware.nl") :database-path "/home/djcb/.cache/mu/xapian" :root-maildir "/home/djcb/Maildir" :doccount 86420))
```

**Comment by djcb** [comment]
One obvious difference is the 
```
;; mu% (ping :queries nil)�"
```
 vs 

```
;; mu% (ping :queries nil)
"
```

...but why? 

Do you perhaps use a non-UTF8 locale? And what do you get when you a `describe-char` on that "�"?

(note that I  have _slightly_ newer mu4e, hence the millisec timestamps)

**Comment by tarsius** [comment]
As mentioned above it is a backspace character (8) that gets corrupted when posting it here on Github.

I use `utf-8-unix` and right after evaluating `(mu4e~proc-ping)`, then `last-coding-system-used` agrees that that is indeed the case.

**Comment by djcb** [comment]
Hmmm... so the byte-pattern sent by mu4e in your case use a `\b` (0x08) instead of an `\n` (0x0a).  Why would it do that? The code (`mu4e~proc-send-command`) sends a `\n`, how could that be possibly become a `b`?.

0x0a is 10 in decimal, and 0x08 is 10 in octal... but I guess that's just a coincidence.

**Comment by djcb** [comment]
So I'm a bit at a loss with this issue... are you able to bisect it?

**Comment by tarsius** [comment]
No. I went back to earlier versions that I know used to work but even with those versions I now get this issue. I don't think I made any relevant changes to my Emacs configuration but since I have also tried with `emacs -Q ...` that shouldn't matter anyway. I did `apt upgrade` a few times along the way, maybe that changed something.

This appears to be one of those mysterious issues that only affect a single user. I am fine with closing this issue. It doesn't some like there is anything that can be done at this point. If someone else starts getting the same issue then we should look again.

I am transitioning to Guix anyway and there I am not experiencing this issue. Beside GNU/Linux distributions I am also experimenting with different email clients and mu currently is not my primary client.

**Comment by djcb** [comment]
Thanks for the effort though. I'll keep the issue open for now in case it affects someone else, it's probably something silly once understood...

**Comment by aheays** [comment]
I provde a second case of this issue.  I get no mu4e main screen, and headers search hangs on "Searching...".  Following the steps to reproduce above I get:

```
2020-05-11 09:48:19.862 logging enabled
2020-05-11 09:48:19.864 -> (ping :queries ("flag:unread AND NOT flag:trashed" "date:today..now" "mime:image/*"))
2020-05-11 09:48:19.874 -> (contacts :personal nil :after "2014-01-01" :tstamp "0")
2020-05-11 09:48:19.897 * Received 251 byte(s)
2020-05-11 09:48:19.897 <- text: ";; Welcome to the mu 1.4.5 command-server
;; Use (help) to get a list of commands, (quit) to quit.
;; mu% (ping :queries (\"flag:unread AND NOT flag:trashed\" \"date:today..now\" \"mime:image/*\"))(contacts :personal nil :after \"2014-01-01\" :tstamp \"0\"))"
2020-05-11 09:48:19.898 <- sexp: nil
```
The nondisplaying character is in my case ^H in the log buffer.

This is on arch linux, emacs 26.3, mu 1.4.5-1.  I tried a cached arch package for mu 1.0.3 and that works fine. I haven't tried intervening versions.

**Comment by djcb** [comment]
Hmm, a common element between @tarsius and @aheays is the use of the (optional) `readline`; now I use that too with this prob, but I suspect this might play a role.

Have pushed a change that gets rid of readline for now. Does that help?

**Comment by tarsius** [comment]
That fixed it for me!

**Comment by tarsius** [comment]
Then I tried `1.4.5-0-g099d41f3` again and as expected the issue was back.

Minimal experimenting revealed that this line in `~/.inputrc` causes the issue in my case:

```
"\C-j": backward-char
```

I tried this as a workaround:

```
"\C-j": backward-char
$if mu
"\C-j": accept-line
$endif
```

But that did not work. I also tried `Mu` instead of `mu`.

From bash(1):

> The application construct is used to include application- specific settings.  Each program using the  readline  library  sets  the  application name, and an initialization file can test for a particular value.

Maybe mu doesn't do that?

**Comment by djcb** [comment]
Ah, thanks... we're not setting the application name, indeed.

`readline` isn't really needed (esp. not in the mu4e-case), it's just a little convenience for running mu-server as a repl. Guess it can come back for _just_ the `isatty`-case.

**Comment by aheays** [comment]
Also works for me disabling \C-j in inputrc.   An insightful leap!

**Comment by djcb** [comment]
Indeed, readline was turning the `\n` that the server was expecting into a `^H`...  

Great to have this resolved! In the future, this the readline support may come back, but _only_ for the interactive, repl case. Thanks all for getting to the bottom of this!

**Comment by tarsius** [comment]
Thanks a lot to you too!
