### ISSUE TITLE
Cannot reliably send attachments with mu4e-compose-new

### ISSUE THREAD

**Issue by rjhwelsh** [djcb/mu#1623]
## Expected or desired behavior
Want to use `mml-attach-file` to send file attachments, when working with `mu4e-compose-new`.

## Actual behavior
Checking email@example.com's inbox..
Instead of a structured email message with attachment, 
I get a plain/text of the entire MIME data in the plain/text portion of the message, which is rather strange. 
(Sent via Emacs's `smtpmail-send-it` function)

Checking email@example.com's sent folder..
Email looks as it should. With attachments structured separately from the plain/text body. 
(Sync-ed imap via offlineimap)

## Steps to reproduce
1. start `emacs`
2. Issue commands:
`M-x mu4e` `C` (Compose a new message) (`mu4e-compose-new`)
;; To: youremail@example.com
`C-c RET f`        (`mml-attach-file`)
;; .. Select test1.jpg ...
`C-c C-s`           (`message-send`)
3. Check email inbox, (can even use `M-x mu4e` to do this).
4. Check sent folder.

## Versions of mu, mu4e/emacs, operating system etc.
mu 1.2 OR 1.3.5-r1 OR 1.3.6-r1
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13)
Gentoo Linux

## Workaround
Users affected can use `M-x compose-mail` instead of `mu4e-compose-new` when attaching files. Attaching files works as intended here; albeit, without some of the comforts of mu4e. 

## Suspect
I had a little look at mu4e-compose.el. I suspect something different is happening with the saved-version and sent-version of the composed-message. Perhaps, to do with the `before-save-hook` and `after-save-hook`; used to adjust the `mail-header-separator`.

**Comment by djcb** [comment]
Hmmm, cannot reproduce, and use this all the time, as do many mu4e users. Likely, there's something special without your setup.

Do you have any compose hooks, third-party packages etc. installed? Can you reproduce with just emacs -q, loading mu4e with a bare-bones setup?

**Comment by rjhwelsh** [comment]
Ah! Bare-bones setup works.
Must be some third party application. 
My hunt continues. Thanks.
