### ISSUE TITLE
Moving message to another maildir makes it as a duplicate

### ISSUE THREAD

**Issue by vqhuy** [djcb/mu#1624]
## Expected or desired behavior

Moving a message from one maildir to another shouldn't mark the message as a duplicate.

## Actual behavior

When moving a message from one maildir to another (for example, by manually moving, or by setting `mu4e-sent-messages-behavior 'sent` etc, then updating the database, the message is marked as duplicate and isn't shown, unless `m4eu-headers-skip-duplicates` is disable.

## Versions of mu, mu4e/emacs, operating system etc.

I'm using `mu 1.2.0`, with `emacs 26.3` and `mbsync`.
Below is my `mbsync` config
```
[...]
Patterns *
# Automatically create missing mailboxes, both locally and on the server
Create Both
Remove Both
Expunge Both
CopyArrivalDate yes
Sync All
# Save the synchronization state files in the relevant directory
SyncState *
```

## Any other detail
I guess the problem is that when updating the email & database, the file name of the message is changed (something like the UID is append to the filename by either `mbsync` or `mu`), which causes the `docid` of the message is different.

**Comment by djcb** [comment]
This seems like an configuration issue with mbsync, there's not much mu/mu4e can do about that, I'm afraid.

**Comment by vqhuy** [comment]
But even if the filename is changed by mbsync, the indexing and database is maintained by mu, no?

**Comment by vqhuy** [comment]
Would like to re-open it, is that okay?

Could you tell me a bit how mu indexes a file: based on the file content or also its file name?

Thank you!

**Comment by vqhuy** [comment]
Reindexing seems fix the problem. Thanks for your help!

**Comment by lechner** [comment]
Hi, I switched from Notmuch a few days ago and also have this problem. I also get errors like

```
UID 39071 is beyond highest assigned UID 7944
```

Reindexing does not solve anything. Does `mu4e` strip the `UIDs` when refiling or moving messages? Thanks!

Kind regards
Felix

**Comment by lechner** [comment]
should have opened a new issue.  My issue is more basic than the one documented here.
