### ISSUE TITLE
Message with inline ICS

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1625]
## Expected or desired behavior

View the message

## Actual behavior

The [attached message](https://github.com/djcb/mu/files/4366483/test-ics.txt) (composed with Mu4e) triggers an error when displaying it with the Gnus mode (not the original one).
(I can send _privately_ the original message which also starts the debugger when “Enter Debugger on Error” is set.)

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 26.3
Mu: commit 441f0053

**Comment by Chris00** [comment]
Same with the latest Mu version (commit efd67102).

**Comment by Chris00** [comment]
The problem is with `gnus-icalendar-with-decoded-handle`: it does
```elisp
  (let ((charset (make-symbol "charset")))
    `(let ((,charset (cdr (assoc 'charset (mm-handle-type ,handle)))))
```
and this returns an invalid charset.

**Comment by djcb** [comment]
Any idea how to fix this?

**Comment by Chris00** [comment]
On 25 March 2020 at 07:47 CET, Dirk-Jan C. Binnema <notifications@github.com> wrote:
>
> Any idea how to fix this?

I'll try to find some time to investigate in the coming days.  I see two possibilities: one could try to add the charset information to the handle (we try to determine it in `mu4e~view-gnus`) or we could advise the function (using `mu4e~view-rendering` to only trigger it for mu4e).

**Comment by Chris00** [comment]
Temporary fix (a better solution must be found to use the charset in `mu4e~view-gnus`).
```elisp
(define-advice gnus-icalendar-event-from-handle
    (:filter-args (handle-attendee) fix-missing-charset)
  "Fix mu not passing the charset."
  (let* ((handle (car handle-attendee))
         (attendee (cdr handle-attendee))
         (buf (mm-handle-buffer handle))
         (ty (mm-handle-type handle))
         (rest (cddr handle)))
    ;; Put the fallback at the end:
    (setq ty (append ty '((charset . "utf-8"))))
    (setq handle (cons buf (cons ty rest)))
    (list handle attendee)))
```

**Comment by djcb** [comment]
Ah, thanks. But should the advise perhaps have a guard so it only works when used in mu4e? Otherwise it could affect people trying to use the 'real' gnus after this is defined. Or?

**Comment by Chris00** [comment]
I filed a bug against Emacs.  The following variant only apply the customization inside mu:
```elisp
(define-advice gnus-icalendar-event-from-handle
    (:filter-args (handle-attendee) fix-missing-charset)
  "Fix mu not passing the charset."
  (if (boundp 'mu4e~view-rendering)
      (let* ((handle (car handle-attendee))
             (attendee (cdr handle-attendee))
             (buf (mm-handle-buffer handle))
             (ty (mm-handle-type handle))
             (rest (cddr handle)))
        ;; Put the fallback at the end:
        (setq ty (append ty '((charset . "utf-8"))))
        (setq handle (cons buf (cons ty rest)))
        (list handle attendee))
  handle-attendee))
```

**Comment by Chris00** [comment]
[Emacs bug](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=40290).

**Comment by djcb** [comment]
Ah, thanks again. But shouldn't the check be wether we're currently in an mu4e buffer? Otherwise the advise would still kick in if you use gnus after mu4e?

**Comment by Chris00** [comment]
One should replace `(boundp 'mu4e~view-rendering)`by `(and (boundp 'mu4e~view-rendering) mu4e~view-rendering)`.  `mu4e~view-rendering` may indeed be known outside mu4e buffers but is supposed to be set to `t` only in the code using Gnus view.

**Comment by djcb** [comment]
Ah, thanks. Do you want to make a PR, or do you think we can do this post-1.4?

**Comment by Chris00** [comment]
I'll try to make a PR later today — it will not affect many people but it is annoying when this bug is triggered.
