### ISSUE TITLE
reply all adds user's email address (ie. my own email)

### ISSUE THREAD

**Issue by seanfarley** [djcb/mu#1626]
## Expected or desired behavior

Reply all shouldn't include my email (unless this is some standard I'm unaware of?)

## Actual behavior

When emailing just one person, I'm prompted with "reply all" or "reply sender" which seems a bit odd? If I choose "all" then my email address is also CC'd.

## Steps to reproduce

Try replying to an email that's from just one person and then 'reply all'. Your own email address should be in the CC.

## Versions of mu, mu4e/emacs, operating system etc.

mu: 17f38dc4
mu4e: 17f38dc4
os: macos

**Comment by djcb** [comment]
Hmm, cannot reproduce that. Perhaps your e-mail address is not recognized as your own? Note that with the current versions, that's something done with `mu init`.

You can check your settings with `mu info`.

**Comment by seanfarley** [comment]
Hmm, I thought I did that. Does it matter that it's not my first address listed (the address in question is my 'sean@farley.io')? Here is my output:

```
 ~/sandbox/local-mu/bin/mu info                                                                                                                             database-path      : /Users/sean/.cache/mu/xapian
messages in store  : 123548
schema-version     : 451
created            : Mon Mar  2 10:54:26 2020
maildir            : /Users/sean/.mail
personal-addresses : "sean.michael.farley@gmail.com"
                     "sean@seanfarley.org"
                     "sean@mcs.anl.gov"
                     "sean@macports.org"
                     "sean@lsmsa.net"
                     "sean@farley.io"
                     "sfarley@atlassian.com"
                     "me@smf.io"
                     "sfarley@iit.edu"
                     "sfarley@coiled.io"
```

**Comment by jschwab** [comment]
FWIW, reply all works for me here, but I note that `mu info` doesn't display my email addresses in quotes.

**Comment by seanfarley** [comment]
Thanks @jschwab! That was it >_<
