### ISSUE TITLE
cmd:move does not work between filesystems

### ISSUE THREAD

**Issue by ejpcmac** [djcb/mu#1628]
## Expected or desired behavior

I would expect that `cmd:move` still work when crossing a filesystem boundary.

## Actual behavior

I’ve recently split my Maildir in several ZFS filesystems—one per account. Since then, when I try to refile a message from one account to another—thus doing under the hood a `cmd:move` between different filesystems—it fails.

Trying to do it by hand in a `mu server` shell, I obtain the following error:

```
;; mu> cmd:move msgid:<some-msg-in-account1> maildir:/<account2>/Inbox
cb(:error 70 :message "error moving /home/jpc/Courriels/<account1>/Inbox/cur/1585440124.29561_6.saturne,U=959:2,S to /home/jpc/Courriels/<account2>/Inbox/cur/1585440124.29561_6.saturne,U=959:2,S")
```

## Steps to reproduce

1. Create a Mailhome split between different filesystems
2. Put a message in one of the filesystems
3. Try to move the message from one maildir to another on a different filesystem using `cmd:move`

## Versions of mu, mu4e/emacs, operating system etc.

* mu: 1.2.0
* Emacs: 26.3
* OS: NixOS 19.09 (GNU/Linux)

**Comment by theophilusx** [comment]
moving/renaming a file across partitions is a common limitation of many
file systems. I'm not familiar with ZFS, but would not be surprised if
it also has this limitation. Reason is that move/rename is typically
implemented (at a high level) at the directory meta-level - manipulating
the structures representing the file system layout (indexes). No data is
actually moved - only pointers to the data is changed. This is why
moving large files is often much faster than copying them.

If this is the case, there probably isn't much mu can do about it. It
could use copy operations instead of move, but that would potentially
have significant performance impact which would be difficult to justify
for this use case, which I would guess is less frequent than most setups
where all mail is on the same partition. .

**Comment by ejpcmac** [comment]
Yes, I know how move operations work in a filesystem, and why you cannot
do a low-level move operation between different filesystems. However,
high-level applications—including the Unix command mv—usually permit a
move between filesystems by doing a copy-then-delete operation when
appropriate.

Then, cmd:move could implement the move /semantics/ as follows:

1. if the destination is on the same filesystem, then use a low-level
   move operation;

2. if the destination is on a different filesystem, then use a copy
   operation, then delete the original file.

**Comment by djcb** [comment]
In the 1.3.x series (to become 1.4), the exact commands are a little different, but this still wouldn't work... 

I'll add a note to the docs. We can leave this open as an RFE, but in general I would recommend having your whole maildir in a single filesystem as it's so much faster.

**Comment by ejpcmac** [comment]
Thank you for letting this open as a RFE. I may also take a look on this
as soon as I have some time.

Speaking about performance issues: I’m not sure it would matter in this
case since (1) the performance cost would be only for cross-filesystem
cases, which are not the majority and (2) it would be generally for a
few emails at a time, when refiling them.

Regarding why I want to split : sometimes I want to add a new account,
then remove it after some time—a few months for instance. The biggest
interest I have in ZFS is the use of snapshots, which are taken
automatically by zfs-auto-snapshot. If I do this without splitting, the
then deleted account data will still be on my computer until the
snapshots are gone. With a filesystem per account, I can choose to
delete the filesystem from my computer, and maybe archive it somewhere
else. I have currently more than 180 filesystems on my computer to have
a modular handling on my data, and I’m sure other users of ZFS do the
same to get a fine-grained control over the things.

**Comment by ejpcmac** [comment]
Oh, thank you for this feature! I’ll try this soon.

**Comment by ejpcmac** [comment]
It works like a charm, thanks so much! By the way, it’s been the occasion to upgrade from mu 1.2.0. The work you’ve done for mu 1.4 is fantastic, mu4e feels more reactive, and I quite like the message counts in the bookmarks and other refinements like the date in drafts.
