### ISSUE TITLE
Cannot change default directory to insert an attachment

### ISSUE THREAD

**Issue by averter** [djcb/mu#1632]
## Expected or desired behavior

To choose the directory that mu4e uses by default to insert (not save) an attachment.

## Actual behavior

mu4e uses the directory `~/Mail/drafts/cur/` by default and I cannot change this.

## Steps to reproduce

1. Compose a new message
2. Move the cursor to the message body
3. Hit `C-c C-a`
4. The default directory will be displayed in the command prompt

## Versions of mu, mu4e/emacs, operating system etc.
mu4e v1.3.9, emacs v26.3, Linux Mint

**Comment by djcb** [comment]
Setting `default-directory` in `mu4e-compose-mode-hook` seems to work... does it not for you?

**Comment by averter** [comment]
Thanks. It is working now. I think that if using the non-compiled version of mu4e "~/" is set as the default-directory.
