### ISSUE TITLE
Own email added to Reply all option

### ISSUE THREAD

**Issue by averter** [djcb/mu#1638]
## Expected or desired behavior

Do not have my own email included when using the reply all option.

## Actual behavior

The opposite of the above, i.e., my email is added into the CC field. Happens all the time

## Steps to reproduce

1. Find any email sent to you by somone else

**Comment by djcb** [comment]
`mu4e-user-mail-address-list` is obsolete; see NEWS.org (`N` in the main view) on the new way to deal with this.
