### ISSUE TITLE
Own email is added to the CC field when replying to all

### ISSUE THREAD

**Issue by averter** [djcb/mu#1639]
## Expected or desired behavior

Do not have my own email included when using the reply all option.

## Actual behavior

The opposite of the above, i.e., my email is added into the CC field. It happens all the time but the problem only showed up after the upgrade from 1.3.9 to 1.3.10.
Furthermore, in my init.el I have 

```` elisp
(setq mu4e-compose-dont-reply-to-self t)                 ;; exclude own e-mail address when “replying to all”
````
and this after mu4e contexts

```` elisp
(setq mu4e-user-mail-address-list
      (delq nil
	    (mapcar (lambda (context)
		      (when (mu4e-context-vars context)
			(cdr (assq 'user-mail-address (mu4e-context-vars context)))))
		    mu4e-contexts)))    
````
## Steps to reproduce

1. Find any email sent to you by somone else
2. Hit `R` and then `a`

## Versions of mu, mu4e/emacs, operating system etc.

mu4e v1.3.10, emacs 26.3

**Comment by djcb** [comment]
`mu4e-user-mail-address-list` is obsolete; see NEWS.org (`N` in the main view) on the new way to deal with this.

**Comment by averter** [comment]
I accidentally created a duplicated issue without noticing-sorry for that. 
Thanks. All working now. Only now realized that mu init requires some parameters (such as personal mail addresses). Strangely, the main screen showed no warning even though my user-mail-address was obviously not in the "personal addresses".

**Comment by djcb** [comment]
Yeah, if you haven't provided any mail addresses to `mu init`, it won't complain. That's to avoid warnings for (the many?) people who don't really care about that.

But perhaps that's needs to updated. At least it should be documented.
