### ISSUE TITLE
msg2pdf returning error code 127 on cgywin on Windows 10

### ISSUE THREAD

**Issue by LW1800CGI6** [djcb/mu#1640]
## Expected or desired behavior

When called with a message, msg2pdf should convert the message
into a PDF and output a path to the generated PDF.

## Actual behavior

When I run msg2pdf from the cygwin terminal, for example
`msg2pdf <some message from my Maildir>`, msg2pdf outputs
nothing. When I check the return code using `$?`, I see that the
return code is 127, which leads me to wonder if I'm missing any 
packages (although I'm able to build everything correctly).

## Steps to reproduce

Download and build mu 1.2.0 from the Github release page, following
the instructions here: https://github.com/djcb/mu/issues/1487. After
building, run msg2pdf from cygwin. Even when msg2pdf is ran without
any arguments, the error code is 127 and nothing is outputted. On 
Linux, one would get the "usage..." line printed on screen.

## Versions of mu, mu4e/emacs, operating system etc.

I'm using Emacs 26.3 on Windows (not w32 from cygwin library) and
the version of mu is 1.2.0 from the Github release page. The installation
instructions I followed was the one given here: https://github.com/djcb/mu/issues/1487.

**Comment by djcb** [comment]
Sorry, I can't really help you with this. 

Perhaps use the equivalent of `gdb` or `strace` to see what's going on?

**Comment by LW1800CGI6** [comment]
This might be a basic question but how do I compile with debugging information?
I configured with `./configure CPPFLAGS=-DDEBUG CFLAGS="-g -O0" CXXFLAGS="-g -O0" LDFLAGS="-g"` on Cygwin and then built with `make clean && make`, but running GDB on
the generated msg2pdf.exe still shows "no debugging symbols found." When I check msg2pdf.exe
using `file msg2pdf.exe` it says `msg2pdf.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows`

**Comment by djcb** [comment]
Hmm, seems that should get you debug build, but the "stripped to external PDB" suggests that it's stripped at some point. But frankly I'm just guessing here.

**Comment by LW1800CGI6** [comment]
Using strace on Cygwin I got
```
   98  118358 [main] msg2pdf 275 dtable::delete_archetype: deleting element 0 for /dev/cons0(3/0)
  164  118522 [main] msg2pdf 275 getpid: 275 = getpid()
   92  118614 [main] msg2pdf 275 proc_terminate: nprocs 0
   92  118706 [main] msg2pdf 275 proc_terminate: leaving
   97  118803 [main] msg2pdf 275 pinfo::exit: Calling dlls.cleanup_forkables n 0x7F00, exitcode 0x7F
  102  118905 [main] msg2pdf 275 pinfo::exit: Calling ExitProcess n 0x7F00, exitcode 0x7F
--- Process 18356 (pid: 275) thread 17608 exited with status 0x7f
--- Process 18356 (pid: 275) thread 18360 exited with status 0x7f
--- Process 18356 (pid: 275) thread 17648 exited with status 0x7f
--- Process 18356 (pid: 275) thread 17652 exited with status 0x7f
--- Process 18356 (pid: 275) exited with status 0x7f
```
After looking more into "Calling dlls.cleanup_forkables n 0x7F00, exitcode 0x7F" I'm guess it's just because my Cygwin is broken. Marking this as closed.
