### ISSUE TITLE
Different sorting for different views

### ISSUE THREAD

**Issue by achempion** [djcb/mu#1642]
Hi Dirk-Jan,

Thank you for all the work done on that awesome project.

## Expected or desired behavior

I'm trying to figure out how to setup different sorting rules based on view content.

I would like to see newest first when I'm checking all email but when I'm viewing unread mails, I would like to see oldest first.

For now with `mu4e-headers-change-sorting` we can only choose one general rule for all views.

I guess it could be done with some sort of hook which will dynamically set the sorting based on requested view (unread, all emails, spam and so on).  

## Actual behavior

You can  only choose one general rule for all views.

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 1.2.0
emacs 26.2

mu4e-conversation  20190609.812  
mu4e-jump-to-list  20190419.1442 
mu4e-maildirs-e... 20200410.820  
mu4e-overview      20200218.546  
mu4e-query-frag... 20170923.1322

**Comment by djcb** [comment]
This can be achieved using `mu4e-headers-search-bookmark-hook`, by changing the sort-order there.

**Comment by achempion** [comment]
Thank you for the reply. After for some tinkering I've found a way how to implement this.

I've tried `mu4e-headers-search-bookmark-hook` but did'n find how to reset the variable `mu4e-headers-sort-direction` back to default for other searches.

Here is my solution
```lisp
(setq mu4e-headers-search-hook 'achempion-mu4e-search)

(defun achempion-mu4e-search (query)
  "Change default sorting for the unread bookmark QUERY."
  (cond ((string-equal query "flag:unread AND NOT flag:trashed")
         (setq mu4e-headers-sort-direction 'ascending))

        (t
         (setq mu4e-headers-sort-direction 'descending))))
```
