### ISSUE TITLE
Personal email adresses: case sensitive?

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1643]
I appreciate the new warning about personal addresses.  However I got the warning
```
[mu4e] Note: `user-mail-address' ('Xaaa.Ybbb@site.com') is not part of mu's addresses; add it with 'mu init --my-address='
```
while `xaaa.ybbb@site.com` is part of the list.  IIRC, that part of the email address is case insensitive.

**Comment by djcb** [comment]
Pedantically, the part _before_ the '@' actually _is_ case-sensitive, though I doubt anyone treated it as such this century... 

In any case, this has been updated to a case-insensitive check a long time ago, see `mu4e-personal-address-p`.
