### ISSUE TITLE
Separate mu4e-attachment-dir defaults for saving vs. composing?

### ISSUE THREAD

**Issue by nfleisher** [djcb/mu#1644]
In mu4e 1.4 composing a message now calls `mu4e~-get-attachment-dir` (as of [this commit](https://github.com/djcb/mu/commit/edd47ced712f14feb889dafe4428391dde917b56)). This is a nice way to get a sensible default attachment directory when composing. But I think it would be useful for there to be separate default attachment directories for saving vs. composing (e.g. `mu4e-attachment-dir` and `mu4e-compose-attachment-dir`).

Beyond enabling users to choose different default values for these two cases, keeping them separate would make it simpler to write custom functions for saving attachments. For example, for `mu4e-attachment-dir` I currently use the function below to prompt for a directory each time I save an attachment. The new behavior in mu4e 1.4 causes this prompt to come up each time I compose a message (and defaults to the drafts folder, recreating the problem that this commit is meant to overcome).
```
(defun nf-attachments (fname mtype)
  "Prompt for a directory when saving email attachments."
  (interactive)
  (read-directory-name "Save to directory: "))
```
Much of what I've described is the result of how my own custom function interacts with the new behavior in mu4e 1.4. But I wonder whether others might also find it useful to separate these two defaults. A sensible default value for the attachment directory when composing might simply be `"~/"`.

Thanks!

**Comment by djcb** [comment]
In the composition case, both fname and mtype will be `nil', so you can use that to separate the the two cases.

```
(defun nf-attachments (fname mtype)
  "Prompt for a directory when saving email attachments."
  (interactive)
  (if (or fname mtype) 
      (read-directory-name "Save to directory: ")
    (expand-file-name "~/")))
```

**Comment by nfleisher** [comment]
Fantastic, thanks very much!
