### ISSUE TITLE
Who's responsible for the homebrew build?

### ISSUE THREAD

**Issue by ndw** [djcb/mu#1648]
Sorry. I'm juggling about 10 things right now and I don't want to lose track of this. Feel free to punt it back to me if you have nothing to do with the Homebrew build.

It is 1.4, but:

```
$ mu init --maildir= /Users/ndw/Maildir ...

(process:34347): GLib-WARNING **: 20:01:29.593: ../glib/goption.c:2433: ignoring invalid short option '\xf5' (-11) in entry init:p\xbd`\xe4\xb3\u007f

(process:34347): GLib-WARNING **: 20:01:29.593: ../glib/goption.c:2450: ignoring no-arg, optional-arg or filename flags (32767) on option of arg-type 0 in entry init:p\xbd`\xe4\xb3\u007f

(process:34347): GLib-WARNING **: 20:01:29.593: ../glib/goption.c:2433: ignoring invalid short option '\xf8' (-8) in entry init:\u0012w\xc2\u0007\u0001

(process:34347): GLib-WARNING **: 20:01:29.593: ../glib/goption.c:2441: ignoring reverse flag on option of arg-type -402534656 in entry init:\u0012w\xc2\u0007\u0001

(process:34347): GLib-WARNING **: 20:01:29.593: ../glib/goption.c:2450: ignoring no-arg, optional-arg or filename flags (-5) on option of arg-type -402534656 in entry init:\u0012w\xc2\u0007\u0001

(process:34347): GLib-WARNING **: 20:01:29.593: ../glib/goption.c:2433: ignoring invalid short option '\xbe' (-66) in entry init:0\xd1\u0001\xe8\xfe\u007f

(process:34347): GLib-WARNING **: 20:01:29.593: ../glib/goption.c:2433: ignoring invalid short option '\x94' (-108) in entry init:\xd0\xd1\u0001\xe8\xfe\u007f

(process:34347): GLib-WARNING **: 20:01:29.593: ../glib/goption.c:2441: ignoring reverse flag on option of arg-type -402534560 in entry init:\xd0\xd1\u0001\xe8\xfe\u007f

(process:34347): GLib-WARNING **: 20:01:29.593: ../glib/goption.c:2450: ignoring no-arg, optional-arg or filename flags (32762) on option of arg-type -402534560 in entry init:\xd0\xd1\u0001\xe8\xfe\u007f
database-path      : /Users/ndw/.cache/mu/xapian

**Comment by ndw** [comment]
FWIW, my build doesn't do this.

**Comment by djcb** [comment]
Not sure who's responsible... I'm not at least. The problem looks very similar to the one in #1645. 

Anyway, I've pushed a change, does that help?

**Comment by telemachus** [comment]
@ndw This doesn't directly answer your question, but I filed a bug about this at homebrew earlier today.

https://github.com/Homebrew/homebrew-core/issues/53393

In general, in my experience, no one person is responsible for a homebrew formula. Different volunteers create formulas and update them. So if or when @djcb cuts a new release of mu to address the glib issues, then either of us (or someone else) will submit a PR with a new version of the homebrew formula.

**Comment by djcb** [comment]
New release: https://github.com/djcb/mu/releases/tag/1.4.1

**Comment by telemachus** [comment]
@djcb Thanks for letting us know. It turns out that homebrew only accepts PRs for even-numbered releases (see below [from the mu formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mu.rb)). For now, users can install via `--HEAD` though, and I'll keep my eye out for the next even-numbered release.

```ruby
# Note that odd release numbers indicate unstable releases.
# Please only submit PRs for [x.even.x] version numbers:
# https://github.com/djcb/mu/commit/23f4a64bdcdee3f9956a39b9a5a4fd0c5c2370ba
```

**Comment by djcb** [comment]
@telemachus: 1.4.1 matches x.even.x, or?

**Comment by Bo98** [comment]
Yes, that comment was because 1.3.x (and in the earlier days, 0.9.odd) are pre-releases and Homebrew only accepts stable releases.

Homebrew/homebrew-core#53438

**Comment by telemachus** [comment]
@djcb Whoops, yeah. I am a dope, and I misread that as "only releases with even final numbers" because I was careless.

**Comment by djcb** [comment]
Thanks all -- guess we can close this.
