### ISSUE TITLE
mu cfind odd display of unicode characters

### ISSUE THREAD

**Issue by guibor** [djcb/mu#1649]
## Expected or desired behavior

Please describe the behavior you expected / want

```
mu cfind EMAIL
>> CONTACT_NAME EMAIL
```

Where contact name is displayed with unicode characters

## Actual behavior

Instead I get the actual encodings 

L\303\251a lea@example.com

This also occurs in the contact completion in mu4e (not just mu)

**Comment by djcb** [comment]
Are you using a non-UTF8 locale? mu/mu4e depend on utf-8.

**Comment by guibor** [comment]
Which variable should I check?

locale-coding-system is set to utf-8-unix

**Comment by djcb** [comment]
It would be the locale of your shell, ie. the output of the `locale` command.
