### ISSUE TITLE
Opening signed messages is slow, cannot see signature checking result

### ISSUE THREAD

**Issue by kuba-orlik** [djcb/mu#1652]
## Expected or desired behavior

Signed messages open fairly quickly and viewing them allows to check signature verification verdict

## Actual behavior

Signed messages always open slowly (up to 30 seconds!), and no "Signature" header is added to the view, even though it's enabled in `mu4e-view-fields`. Pressing `v` to see more details shows:

```
verdict: no signature found
```

## Steps to reproduce

Try to view any signed message

## Versions of mu, mu4e/emacs, operating system etc.

* mu 1.4.1
* mu for emacs version 1.4.1
* GNU Emacs 26.3
* Operating system: Manjaro Linux
* gpg (GnuPG) 2.2.20
* libgcrypt 1.8.5

**Comment by djcb** [comment]
Can you attach a message where this happens?

**Comment by kuba-orlik** [comment]
Sure thing:


[2020-05-03_Saldo rachunku numer 71...8569 na dzień 2020-05-03.txt](https://github.com/djcb/mu/files/4573303/2020-05-03_Saldo.rachunku.numer.71.8569.na.dzien.2020-05-03.txt)

**Comment by djcb** [comment]
I've pushed a few changes... does it help?

Does it make a difference if you use `(setq mu4e-view-use-gnus t)`?

**Comment by kuba-orlik** [comment]
Thanks! 

I've tried with `(mu4e-view-use-gnus t`) on 1.4.1 and it is waay faster

I will try the newest version from git soon and will let you know the results

**Comment by djcb** [comment]
Closing this... if you have additional comments, please see #1536.
