### ISSUE TITLE
Root maildir unknown when using `make-mu4e-context-account`

### ISSUE THREAD

**Issue by vqhuy** [djcb/mu#1654]
## Expected or desired behavior

Create a new context using the helper function `make-mu4e-context-account`.

## Actual behavior

Using `make-mu4e-context-account` in my `.emacs.d` throws this error when starting emacs
```
(error #("[mu4e] root maildir unknown; did you start mu4e?" 1 5 (face mu4e-title-face)))
  signal(error (#("[mu4e] root maildir unknown; did you start mu4e?" 1 5 (face mu4e-title-face))))
  error("%s" #("[mu4e] root maildir unknown; did you start mu4e?" 1 5 (face mu4e-title-face)))
  mu4e-error("root maildir unknown; did you start mu4e?")
  mu4e-root-maildir()
```

## Steps to reproduce

Just put the provided example from [manual](https://www.djcbsoftware.nl/code/mu/mu4e/Account-setup-helper.html#Account-setup-helper) to my private config file.

## Versions of mu, mu4e/emacs, operating system etc.

I am using `mu` version `1.4.1` with doom emacs.

**Comment by Chris00** [comment]
`(mu4e-root-maildir)` requires mu to be started.  Not sure why you need the root directory in your config, but in that xase you want to put it in a hook:
```elisp
(add-hook
 'mu4e-loading-mode-hook
 (defun my/setup-mu4e-config()
   (setq mu4e-contexts
     ... )))
```

**Comment by djcb** [comment]
It seems the account-setup-helper doesn't quite work at the moment; I've pushed a few changes that should help.
