### ISSUE TITLE
mu: advanced field queries

### ISSUE THREAD

**Issue by muihlinn** [djcb/mu#1655]
After writting an approach to an answer to [this question](https://emacs.stackexchange.com/questions/57963/mu-query-for-finding-mails-with-a-single-and-specific-recipient-mu4e) , I couldn't figure how to do those edge-case after reading 1.3.10 manuals.

## How do I query for an empty field without using regexps?. 

I can pass a regexp which cannot be fulfilled ( like `not cc:/.+/`),  but looks like it'll be faster and cheaper to let the database filter the messages where the field is/isn't empty.

## How do I filter for any of the `recips:` fields which has/hasn't more than one recipient in it?

Let's say I want to search messages which were sent to someone but not to others using the same field i.e. `to:`, or that I want to match messages I've sent to more than one friend, without any particular recipient to match.

TIA.

**Comment by djcb** [comment]
It's not so easy to do searches like that; you cannot use something like SQL queries.

For such complex queries, regexp are probably the best way (but yeah, they are slower), or possibly guile (but that'll be slower too).

**Comment by djcb** [comment]
Can't think of any way without involving e.g. guile or `mu find` and grep etc. Sorry!
