### ISSUE TITLE
Inbox not showing all messages

### ISSUE THREAD

**Issue by davidgr2036** [djcb/mu#1659]
## Expected or desired behavior
Expected to see all my inbox messages
Please describe the behavior you expected / want
Same number (approximately) as the number of unique messages in the INBOX maildir folder
## Actual behavior
I'm missing 200 or so messages, the counts on the front page are correct but the headers show
are not
Please describe the behavior you are actually seeing. 
I can find the headers by searching, and when I look at the message it says it's in the Inbox.
When I just open the Inbox there is no evidence of it anywhere,
It happens for all folders, the archive folder only shows 300 out of 6000
messages. It happens all the time.

## Steps to reproduce
I followed the 1.4 version manual. I init the mu at the command line.
Then I have a minimal .emacs with only require and the path for the mu binary set.
Also the header limit is increased.
Then M-x mu4e. Thats all. This gives the same behaviour with the plain .emacs, and the doom framework.
## Versions of mu, mu4e/emacs, operating system etc.
mu 1.4.1
emacs from homebrew 
"GNU Emacs 26.3 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.60 Version 10.13.6 (Build 17G66))
OS X High Sierra 
## Any other detail
I didn't seem to remember this in the old version 0.98 I used a couple of years ago

**Comment by djcb** [comment]
For speed reasons, the counts do not exclude messages that no longer exist in the file-system, nor does it exclude duplicate messages.

You can also try what you get with `mu find`, and see file:///home/djcb/Sources/mu/mu4e/mu4e/General.html#Results-from-mu-and-mu4e-differ-_002d-why_003f

**Comment by davidgr2036** [comment]
I didn't know about the duplicate messages as I'm sure there are quite a few.
Murphy Laws is working because as soon as I read your message I saw that I had
(setq mu4e-header-results-limit -1) instead of
(setq mu4e-headers-results-limit -1)
Seems to work now, I'll just add in the archive folder now to confirm
