### ISSUE TITLE
mu4e fails to recognize MS-exchange calendar invitations 

### ISSUE THREAD

**Issue by uliw** [djcb/mu#1660]
## Expected or desired behavior
mu4e correctly displays calendar invitations generated by google calendar and shows the corresponding buttons (accept, decline, etc).

I was expecting that Calendar Invitations in vcal format as written by Microsoft Exchange would behave similarly.

## Actual behavior
Calendar Invitations in vcal format as written by Microsoft Exchange are shown as regular attachments. This happens always.

## Steps to reproduce
use the following vcal file
BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Eastern Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN=M Wo;SENT-BY="mailto:noreply@utoronto.ca":mail
 to:noreply@utoronto.ca
ATTENDEE;ROLE=OPT-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=wortmannul
 i1@gmail.com:mailto:wortmannuli1@gmail.com
ATTACH:CID:AE9F2AD7A2726A44BCDCEE8FE9638574@CANPRD01.PROD.OUTLOOK.COM
DESCRIPTION;LANGUAGE=en-US:
UID:040000008200E00074C5B7101A82E00800000000F0632AB29318D601000000000000000
 010000000B299D9A0EB3C5C4FA290378984925B5C
SUMMARY;LANGUAGE=en-US:Sectoral - Sciences
DTSTART;TZID=Eastern Standard Time:20200424T130000
DTEND;TZID=Eastern Standard Time:20200424T140000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20200424T125936Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:11
LOCATION;LANGUAGE=en-US:Microsoft Teams Meeting
X-MICROSOFT-CDO-APPT-SEQUENCE:11
X-MICROSOFT-CDO-OWNERAPPTID:-2118760476
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT15M
ACTION:DISPLAY
END:VALARM
END:VEVENT

## Versions of mu, mu4e/emacs, operating system etc.
mu4e - mu for emacs version 1.4.1
GNU Emacs 26.3 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.13)
Linux bonklt4 5.5.11-1-default #1 SMP Sat Mar 21 11:11:19 UTC 2020 (794b2e9) x86_64 x86_64 x86_64 GNU/Linux

## Any other detail

e-mail addresses etc have been modified in the above vcal. The original can be provided upon request

Thanks for looking into this

Cheers

Uli

**Comment by djcb** [comment]
There's experimental support for what with the gnus-based view, i.e., `(setq mu4e-view-use-gnus t)`

**Comment by uliw** [comment]
Hi Dirk,

thanks for the pointer! It seems to work, and I will play more with it.

Cheers

Uli

Dirk-Jan C. Binnema <notifications@github.com> writes:

> There's experimental support for what with the gnus-based view, i.e., `(setq mu4e-view-use-gnus t)`


-- 
Ulrich G. Wortmann          http://www.es.utoronto.ca/people/faculty/wortmann-ulrich/
Dept. of Earth Sciences     Fax  : 416 978 3938
University of Toronto       Phone: 416 978 7084
22 Russell Street, Toronto, ON, Canada M5S 3B1

**Comment by Chris00** [comment]
On 27 April 2020 at 20:15 CEST, Ulrich Wortmann <notifications@github.com> wrote:
>
> thanks for the pointer! It seems to work, and I will play more with it.

In addition to using the Gnus view, you need to explicitly turn it on with

(require 'mu4e-icalendar)
(mu4e-icalendar-setup)

and, if you want accepted events to be saved in Emacs calendar format, add (adjust the path to your liking)

(setq mu4e-icalendar-diary-file "~/.emacs.d/diary-ical")

**Comment by uliw** [comment]
Thanks Chris,

I had those already active :-)

Uli

Christophe Troestler <notifications@github.com> writes:

> On 27 April 2020 at 20:15 CEST, Ulrich Wortmann <notifications@github.com> wrote:
>>
>> thanks for the pointer! It seems to work, and I will play more with it.
>
> In addition to using the Gnus view, you need to explicitly turn it on with
>
> (require 'mu4e-icalendar)
> (mu4e-icalendar-setup)
>
> and, if you want accepted events to be saved in Emacs calendar format, add (adjust the path to your liking)
>
> (setq mu4e-icalendar-diary-file "~/.emacs.d/diary-ical")
>
>
>
>> Dirk-Jan C. Binnema <notifications@github.com> writes:
>>
>>> There's experimental support for what with the gnus-based view, i.e., `(setq
>> mu4e-view-use-gnus t)`


-- 
Ulrich G. Wortmann          http://www.es.utoronto.ca/people/faculty/wortmann-ulrich/
Dept. of Earth Sciences     Fax  : 416 978 3938
University of Toronto       Phone: 416 978 7084
22 Russell Street, Toronto, ON, Canada M5S 3B1

**Comment by uliw** [comment]
OK, I experimented with both views, but now I am confused. In the traditional view, if I click on the accept button, I am taken to a google page which states that I accepted the invitation. 
Using the gnus-view, clicking on the accept button, creates a new message which can be sent back to the person who sent the invite (which seems to confirm the invitation).  Is this the expected behavior? 
I was hoping (maybe naively so), that the invite would also be entered in my google calendar (similar to gmail), but I realize that this might be gmail specific thing?

Cheers

Uli

**Comment by djcb** [comment]
Indeed, that's the way it works.

It might be possible to integrate it with org-mode though, that's awaiting a kind volunteer I guess :)

**Comment by averter** [comment]
I think that I am experiencing a similar issue. Lately I have received invitations which do not generate buttons/extra headers; only an ical attached file. Is there any reason why this can happen? 

Side note: This feature is one of the jewels of mu4e and a much appreciated contribution from @djcb and @Chris00. Similarly to @uliw, when I click on the button it creates a new message to the person who sent the invite. In addition, it adds the invitation to my org-mode file in a "Calendar" header and synchronizes it with the agenda. So, @djcb this integration with org-mode is possible and should be as easy as using the below configuration (if anyone is interested in trying it out).
```` elisp
;; Use gnus article view
(require 'mu4e-icalendar)
(mu4e-icalendar-setup)

(require 'org-agenda)
(setq gnus-icalendar-org-capture-file "~/org/NOTES.org")
(setq gnus-icalendar-org-capture-headline '("Calendar"))
(gnus-icalendar-org-setup)
````
