### ISSUE TITLE
global-mode-string does not stay local after using mu4e-org-open

### ISSUE THREAD

**Issue by ndwarshuis** [djcb/mu#1665]
## Expected or desired behavior

Upon opening mu4e links in an org mode buffer, the modeline should show the mu4e context, and this context should disappear from the modeline after exiting mu4e.

## Actual behavior

When opening an mu4e link from org mode, the message will open as normal. The context will not be displayed correctly on the modeline but `global-mode-string` will have this value:

```
Its value is ((:eval (mu4e-context-label)))
Local in buffer *mu4e-view*; global value is nil
```
![image](https://user-images.githubusercontent.com/6629118/80623145-c7409200-8a17-11ea-86d1-ac53fa6c8b85.png)

When closing the message, the modeline will show the search query (in this case just the message id of the link that was opened) but not the context. `global-mode-string` has this value:

```
((:eval
   (concat
    (propertize
     (mu4e~quote-for-modeline mu4e~headers-last-query)
     'face 'mu4e-modeline-face)
    " "
    (mu4e-context-label)
    (if
        (and mu4e-display-update-status-in-modeline
             (buffer-live-p mu4e~update-buffer)
             (process-live-p
              (get-buffer-process mu4e~update-buffer)))
        (propertize " (updating)" 'face 'mu4e-modeline-face)
      ""))))
Local in buffer *mu4e-headers*; global value is nil
```
![image](https://user-images.githubusercontent.com/6629118/80623180-d293bd80-8a17-11ea-9a74-ccbfadb0e0ee.png)

When closing the headers view and going the the main mu4e buffer, the context is displayed correctly but the value of `global-mode-string` has become global (note the second line):

```
Its value is ((:eval (mu4e-context-label)))
Local in buffer  *mu4e-main*; global value is the same.
```
![image](https://user-images.githubusercontent.com/6629118/80623219-dde6e900-8a17-11ea-96fe-4fc7131856ef.png)

When closing the mu4e main buffer and going back to the original org buffer (or any other buffer) the mu4e context is still displayed in the modeline and the value of `global-mode-string` is totally global but still has the mu4e context function:

```
Its value is ((:eval (mu4e-context-label)))
```
![image](https://user-images.githubusercontent.com/6629118/80623463-3322fa80-8a18-11ea-9b09-a3a2d3cbd8b2.png)

When opening mu4e again and displaying messages in the `*mu4e-headers*` buffer, two contexts are shown and `global-mode-string` has this value:

```
((:eval
   (concat
    (propertize
     (mu4e~quote-for-modeline mu4e~headers-last-query)
     'face 'mu4e-modeline-face)
    " "
    (mu4e-context-label)
    (if
        (and mu4e-display-update-status-in-modeline
             (buffer-live-p mu4e~update-buffer)
             (process-live-p
              (get-buffer-process mu4e~update-buffer)))
        (propertize " (updating)" 'face 'mu4e-modeline-face)
      "")))
 (:eval
   (mu4e-context-label)))
Local in buffer *mu4e-headers*; global value is 
((:eval
   (mu4e-context-label)))
```
![image](https://user-images.githubusercontent.com/6629118/80623499-433ada00-8a18-11ea-820e-ece626cbbc75.png)

## Steps to reproduce

From a freshly launched instance of emacs:
1. open an mu4e link from org mode
2. close the message by pressing 'q'
3. close the headers view by pressing 'q'
4. close the mu4e main menu by pressing 'q'
5. open mu4e again (run `mu4e`)
6. open some messages in the headers view (search, jump to a maildir, etc)

## Versions of mu, mu4e/emacs, operating system etc.

Mu version: 1.4.1 (this did not happen on 1.2)
Emacs version: 26.3
OS: Arch Linux

## Any other detail

Configuration (with most extraneous bits taken out):
``` emacs-lisp
(require 'mu4e)

(defun nd/make-mu4e-context (name dir addr smtp-srv sent-behavior)
  (let* ((trash (format "/%s/trash" dir))
        (drafts (format "/%s/drafts" dir))
        (sent (format "/%s/sent" dir))
        (archive (format "/%s/archive" dir))
        (inbox (format "/%s/inbox" dir))
        (shortcuts (--map (list :maildir (car it) :key (cdr it))
                          `((,trash . ?t)
                            (,drafts . ?d)
                            (,sent . ?s)
                            (,archive . ?a)
                            (,inbox . ?i))))
         (mf (lambda (d msg)
               (-some--> msg
                        (mu4e-message-field it :maildir)
                          (string-prefix-p (concat "/" d) it)))))
      (make-mu4e-context
       :name name
       :match-func (-partial mf dir) ; use lexical scope here
       :vars `((mu4e-trash-folder . ,trash)
               (mu4e-drafts-folder . ,drafts)
               (mu4e-sent-folder . ,sent)
               (mu4e-refile-folder . ,archive)
               (mu4e-sent-messages-behavior . ,sent-behavior)
               (smtpmail-stream-type . starttls)
               (smtpmail-smtp-server . ,smtp-srv)
               (smtpmail-smtp-service . 587)
               (smtpmail-smtp-user . ,addr)
               (user-mail-address . ,addr)
               (mu4e-maildir-shortcuts . ,shortcuts)))))

(setq mail-user-agent 'mu4e-user-agent

      ;; misc
      mu4e-confirm-quit nil

      ;; contexts (multiple inboxes)
      mu4e-context-policy 'pick-first
      mu4e-contexts
      (list
       (nd/make-mu4e-context "personal"
                             "yavin4"
                             "ndwar@yavin4.ch"
                             "peart4prez.yavin4.ch"
                             'sent)
       (nd/make-mu4e-context "alpha"
                             "gmail"
                             "natedwarshuis@gmail.com"
                             "smtp.gmail.com"
                             'delete)
       (nd/make-mu4e-context "gatech"
                             "gatech"
                             "ndwarshuis3@gatech.edu"
                             "smtp.office365.com"
                             'sent)
       (nd/make-mu4e-context "emory"
                             "emory"
                             "ndwarsh@emory.edu"
                             "smtp.office365.com"
                             'sent)))
```

**Comment by djcb** [comment]
First of all, thanks for the detailed report, that helps debugging.

First, you write:
> When opening an mu4e link from org mode, the message will open as normal. The context will not be displayed correctly on the modeline

That would only happen when no context is set yet (at least I can't reproduce it otherwise); and in that case, it's the correct behavior I think.

As for the other issue, I was able to reproduce that.

**Comment by djcb** [comment]
Can you reproduce with >= 1.4.4?

**Comment by ndwarshuis** [comment]
1.4.4 works, thank you :)
