### ISSUE TITLE
cannot reply to message when opening from org-mode link before starting mu4e

### ISSUE THREAD

**Issue by ndwarshuis** [djcb/mu#1669]
## Expected or desired behavior

When opening an mu4e link from org-mode without first starting mu4e, I should be able to compose a reply message to the message that I just opened.

## Actual behavior

I get the following error when replying.

```
[mu4e] Found 2 matching messages
Invalid face reference: nil [20 times]
[mu4e] Switched context to personal
Wrote /tmp/mu4e-dpcJPX.html
Invalid face reference: nil [10 times]
error in process filter: mu4e-error: [mu4e] root maildir unknown; did you start mu4e?
error in process filter: [mu4e] root maildir unknown; did you start mu4e?
```

If I fully close mu4e and try opening the link again, I can reply to the message as normal.

## Steps to reproduce

From a freshly launched instance of emacs:
1. open an mu4e link from org mode
2. try compose a reply to the message that was just opened (should throw the error above)
3. close the message by pressing 'q'
4. close the headers view by pressing 'q'
5. close the mu4e main menu by pressing 'q'
6. open the link again
7. try to compose a reply message, it should work as normal

## Versions of mu, mu4e/emacs, operating system etc.

Mu version: 1.4.3 (this did not happen on 1.2)
Emacs version: 26.3
OS: Arch Linux

## Any other detail

Mu was initialized using the following:

```
mu init --my-address=ndwar@yavin4.ch --my-address=natedwarshuis@gmail.com --my-address=ndwarshuis3@gatech.edu --my-address=ndwarsh@emory.edu --maildir=/mnt/data/Mail
```

This agrees with the "info" section seen on the main menu for mu4e.

Could also be related to #1654

**Comment by djcb** [comment]
Restored the 1.2 behavior.

**Comment by michaelmrose** [comment]
Exact same issue on 1.4.10 trying to reply from header view. In fact I've been getting something similar at odd intervals since 1.4 but its previously been cured by killing and restarting mu4e and now its impossible to reply to mail. In view mode instead it hangs emacs.
