### ISSUE TITLE
bookmarks hiding unread items if query is not a string.

### ISSUE THREAD

**Issue by sje30** [djcb/mu#1675]
## Expected or desired behavior

I have a mu4e-bookmark like the following:

```
	(:name "3 days ago"
	       :query (concat "maildir:/INBOX AND date:" (n-days-to-date 3))
	       :hide-unread nil
	       :key ?3)


```

where

```
(defun n-days-to-date (n)
  "Convert N days ago to an absolute date"
  (format-time-string "%Y%m%d" (subtract-time (current-time) (days-to-time n))))
```
This is for "yesterbox" type behaviour, where I want to retrieve all emails sent 3 days ago (this is slightly different from the query "3d")

## Actual behavior

the query works, but on the main window of mu, when it lists the bookmarrk, it does not show the unread/total count because of the logic in mu4e~start which notes that the query is not a string.

The documentation does not currently mention this behaviour.

## Steps to reproduce

Add the above bookmark.

## Versions of mu, mu4e/emacs, operating system etc.

mu 1.4.3 on manjaro linux

## Any other detail

Would it be possible to change the logic in mu4e-start that allows non-strings to have a unread/total count if the :hide-unread is undefined or explicity set to some particular value?

**Comment by djcb** [comment]
The behavior was describe in the docstring, I've added a note to the manual as well. Perhaps we can make it looser at some point, but not right now in the 1.4.x series.

**Comment by sje30** [comment]
sure.  Thanks for documenting in the manual.
