### ISSUE TITLE
Mu4e messages not decoded

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1676]
## Expected or desired behavior

The messages sent by mu4e should be decoded.

Please describe the behavior you expected / want

## Actual behavior

After using `mu4e-view-open-attachment` I have this message:

![Capture d’écran_2020-05-05_07-59-20](https://user-images.githubusercontent.com/1533939/81038672-1fa7e180-8ea7-11ea-8bb7-1455e4bd6e72.png)

After applying this patch on `mu4e-message`:

```diff
@@ -226 +226,6 @@ echo area, don't show anything."
-    (message "%s" (apply 'mu4e-format frm args))))
+    (message "%s" (apply 'mu4e-format frm
+                         (mapcar (lambda (x)
+                                   (if (stringp x)
+                                       (decode-coding-string x 'utf-8)
+                                     x))
+                                 args)))))

```
I have this:

![Capture d’écran_2020-05-05_08-00-21](https://user-images.githubusercontent.com/1533939/81038742-685f9a80-8ea7-11ea-995e-09ee31f531df.png)

## Versions of mu, mu4e/emacs, operating system etc.
Mu 1.4.4 emacs-26.

Thanks.

**Comment by djcb** [comment]
Fixed, thanks.
