### ISSUE TITLE
Unmet dependencies compiling mu4e on Ubuntu 20.4

### ISSUE THREAD

**Issue by koendeheer** [djcb/mu#1677]
## Expected or desired behavior
Compiling latest version of mu4e on Ubuntu 20.4 out-of-the-box using the tarball.

## Actual behavior
The output of ./configure && make ends with:

```
_configure: error: Package requirements (glib-2.0 >= 2.38 gobject-2.0 gio-2.0) were not met:

No package 'glib-2.0' found
No package 'gobject-2.0' found
No package 'gio-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GLIB_CFLAGS
and GLIB_LIBS to avoid the need to call pkg-confi_g.
See the pkg-config man page for more details.
```

## Steps to reproduce

Ubuntu 20.4 and mu4e 1.4.4 out-of-the-box.

## Versions of mu, mu4e/emacs, operating system etc.

GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)
Mu4e 1.4.4 tarball

## Any other detail

Probably I am not proficient enough to compile my own software, but as I am hoping to use ORG-MSG with Emacs/mu4e to reply in HTML (and 1.3 supplied with Ubuntu 20.4 is not enough for ORG-MSG), I hope the problem is easily solvable and that someone is willing to help me to arrange the dependencies. Many thanks in advance!

**Comment by theophilusx** [comment]
Sounds like you don't have all the necessary packages installed. I'm
running on Ubuntu 20.4 and have had no problems installing from Git.

Probably easiest way to ensure you have all the necessary packages is to
use the command

sudo apt-get build-dep maildir-utils mu4e

This should install all the necessary dependencies to build mu4e. Once
that is done, you should be able to do

./autogen.sh
./make
./make-install

Note that this will install mu4e in
/usr/local/share/emacs/site-lisp/mu4e, so you may need to add that path
to the Emacs load-path. Make sure you don't have the Ubuntu version of
mail-utils and mu4e installed as this could cause issues with mixed
versions etc.

**Comment by koendeheer** [comment]
Dear Tim,

Many, many thanks for your quick reply! Still not there yet:

After:

sudo apt remove maildir-utils mu4e
sudo apt-get build-dep maildir-utils mu4e
./autogen.sh
./make
./make-install

mu4e installed itself perfectly

I added (add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e") to .emacs

However, then I get the following error after M-x mu4e
Wrong type argument: stringp, nil

The backtrace shows:
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-executable-p(nil)
  mu4e~proc-start()
  mu4e~call-mu((ping :queries ("flag:unread AND NOT flag:trashed" "date:today..now" "date:7d..now" "mime:image/*" "maildir:/mailf/INBOX OR maildir:/maila/INBOX")))
  mu4e~proc-ping(("flag:unread AND NOT flag:trashed" "date:today..now" "date:7d..now" "mime:image/*" "maildir:/mailf/INBOX OR maildir:/maila/INBOX"))
  mu4e~start(mu4e~main-view)
  mu4e()
  eval-region(576 582 t #f(compiled-function (ignore) #<bytecode 0x10d067d>))  ; Reading at buffer position 580
  elisp--eval-defun()
  eval-defun(nil)
  funcall-interactively(eval-defun nil)
  call-interactively(eval-defun nil nil)
  command-execute(eval-defun)

Best, Koen

**Comment by djcb** [comment]
Did you set `mu4e-mu-binary` to the path to the `mu` binary?

**Comment by koendeheer** [comment]
Solved.

Many thanks you both, works like a charm now. Truly great software! Now let's see if I can get org-msg to work...

**Comment by djcb** [comment]
Okay, good luck!
