### ISSUE TITLE
%:fromname in org capture template fails for some messages

### ISSUE THREAD

**Issue by ndwarshuis** [djcb/mu#1678]
## Expected or desired behavior

If I use :fromname in an org capture template like this:

``` emacs-lisp
(setq org-capture-templates
  ("e" "email" entry (file "~/Org/capture")
  "* TODO Respond to %:fromname;"))
```

Launching the capture selector and pressing "e" should open a new buffer with then name of the sender in place of :fromname like this (assuming the name of the sender is "Some Person"):

```
* TODO Respond to Some Person
```

## Actual behavior

Only a blank is inserted like this:

```
* TODO Respond to
```

Unfortunately I have not found a clear pattern, except that it only appears to affect certain addresses, and all messages from these "certain addresses" are affected. For me at least this is not rare. I just looked at one of my inboxes and this problem affects 5/14 messages.

## Steps to reproduce

1. open any headers view in mu4e (either *mu4e-headers* or *mu4e-view*)
2. run org-capture
3. select the email template (the one above should produce the result)
4. inspect the capture buffer, any affected sender email addresses (whatever that turns out to mean) will not have their name inserted into the template

## Versions of mu, mu4e/emacs, operating system etc.

This did not happen in mu 1.2 IIRC

Mu version 1.4.4
OS: Arch Linux
Emacs version: 26.3

## Any other detail

Will post a pattern to this behavior once I find/notice one...

**Comment by djcb** [comment]
Please attach a message where this happens, thanks.

**Comment by ndwarshuis** [comment]
Sure, here is one: [msg.zip](https://github.com/djcb/mu/files/4588024/msg.zip)

**Comment by djcb** [comment]
`:fromname` is a gnus-thing (see the `org-capture-templates` docstring), so the only surprise is that it _sometimes_ works. 

I'd recommend using `:from` instead, but I'll keep this open as an RFE.
