### ISSUE TITLE
mu4e-headers-mark-or-move-to-trash() doesn't switch context

### ISSUE THREAD

**Issue by gspe** [djcb/mu#1684]
## Expected or desired behavior

When I trash message with `mu4e-headers-mark-or-move-to-trash()` function I expect that this message will be moved to `maildir/trash` folder of the message's context

## Actual behavior

The message will be moved to `maildir/trash` folder of the current context

## Steps to reproduce

Set a contex with `:no-trash-flag t` properties and trash a message with `mu4e-headers-mark-or-move-to-trash()` function.

## Versions of mu, mu4e/emacs, operating system etc.
emacs: 27.0.91
mu4e: 1.4.4
operating system: Linux
 
## Any other detail

 With same configuration, `refile` action works correctly switching to right context

**Comment by djcb** [comment]
Does it work without the no-trash flag?

**Comment by gspe** [comment]
Yes without the `no-trash-flag` work correctly.

I think that the problem is that in this function: 
```
(defun mu4e-headers-mark-or-move-to-trash ()
  "Mark message for \"move\" to the trash folder if the message
maildir matches any regexp in `mu4e-move-to-trash-patterns'.
Otherwise mark with the \"trash\" flag.
Also see `mu4e-view-mark-or-move-to-trash'."
  (interactive)
  (let ((msg-dir (mu4e-message-field (mu4e-message-at-point) :maildir)))
    (if (not (seq-filter (lambda (re)
                           (string-match re msg-dir))
                         mu4e-move-to-trash-patterns))
        (mu4e-headers-mark-for-trash)
      (mu4e-mark-set 'move (if (functionp mu4e-trash-folder)
                               (funcall mu4e-trash-folder (mu4e-message-at-point))
                             mu4e-trash-folder))
      (mu4e-headers-next))))
 ```
the else branch:
```
(mu4e-mark-set 'move (if (functionp mu4e-trash-folder)
                               (funcall mu4e-trash-folder (mu4e-message-at-point))
                             mu4e-trash-folder))
```
get the `mu4e-trash-folder` from the current branch and not from the message match

**Comment by djcb** [comment]
It seems so... 

@Ambrevar: I think this part of the 'easy-account' setup, can you look into this? Thanks!

**Comment by Ambrevar** [comment]
Sadly I'm not using mu4e anymore and I haven't looked at the code since
I've submitted upstream :/

Let me know if you get stuck, maybe I'll remember something useful :p

**Comment by gspe** [comment]
I think I've found the solution, the else branch should be:
```
(mu4e-mark-set 'move (if (functionp mu4e-trash-folder)
                               (funcall mu4e-trash-folder (mu4e-message-at-point))
                             (mu4e-get-trash-folder (mu4e-message-at-point))))
```

**Comment by djcb** [comment]
@gspe: great! can you make a PR out of that? Thanks!

**Comment by gspe** [comment]
@djcb ok, I'll do it tomorrow

**Comment by djcb** [comment]
Merged -- thanks!
