### ISSUE TITLE
Wrong email context during compose-mail 

### ISSUE THREAD

**Issue by averter** [djcb/mu#1688]
## Expected or desired behavior

To compose email with the appropriate context.

## Actual behavior

When hitting `C-x m` I am asked which context to use to compose the email. No matter which one I select, my gmail account is always picked. It happens always at mu4e 1.4.5 (possibly previous). I've jumped from 1.4.1.

## Steps to reproduce

1. `C-x m`
2. Select one context other than a gmail
3. The From field will be your gmail acount, irrespective of your previous selection.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e 1.4.5 emacs 26.3

**Comment by djcb** [comment]
Can't reproduce that. Can you make a minimally reproducible example?

**Comment by averter** [comment]
Sorry but how can I make it reproducible? Have you tried in emacs 26.3? (just thinking that last time that was the trigger)

**Comment by djcb** [comment]
I can't reproduce with either version, it must be something specific. Can you reproduce with some simple/trivial context setup? What's the last version of mu4e where it did work? Thanks.

**Comment by averter** [comment]
This is my (edited) context setup. Previous to 1.4.5 I was at 1.4.1 were it worked fine.
````elisp
;; Multiple accounts (after 0.9.16)
(setq mu4e-contexts
      `(
	,(make-mu4e-context
	  :name "work"
	  :enter-func (lambda () (mu4e-message "Switch to the work context"))
	  :leave-func (lambda () (setq mu4e-maildir-list nil))
	  ;; we match based on the contact-fields of the message
	  :match-func (lambda (msg)(when msg
				     (or (mu4e-message-contact-field-matches msg '(:to :bcc :cc) "myname@work")
					 (string-prefix-p "/myname@work" (mu4e-message-field msg :maildir)))))
	  :vars '( (user-mail-address       . "myname@work" )
		   (user-full-name          . "My Name at work" )
		   (mu4e-sent-folder        . "/myname@work/Sent")
		   (mu4e-trash-folder       . "/myname@work/Trash")
		   (mu4e-drafts-folder      . "/drafts")
		   (mu4e-maildir-shortcuts .(("/myname@work/Inbox" . ?i);; setup some handy shortcuts
					     ("/myname@work/Sent"  . ?s)
					     ("/drafts"                      . ?d)
					     ("/myname@work/Trash" . ?t)))
		   ;; SMTP configuration
		   (starttls-use-gnutls . t)
		   (smtpmail-auth-credentials . '(("localhost" 1025 "myname@work" nil)))
		   (smtpmail-smtp-server . "localhost")
		   (smtpmail-default-smtp-server . "localhost")
		   ))
	,(make-mu4e-context
	  :name "Gmail"
	  :enter-func (lambda () (mu4e-message "Switch to the Gmail context"))
	  :match-func (lambda (msg) (when msg
				      (or (mu4e-message-contact-field-matches msg '(:to :bcc :cc) "myname@gmail.com")
					  (string-prefix-p "/myname@gmail.com" (mu4e-message-field msg :maildir)))))
	  :leave-func (lambda () (setq mu4e-maildir-list nil))
	  :vars '((user-mail-address       . "myname@gmail.com")
		  (user-full-name          . "My Name at Gmail")
		  (mu4e-sent-folder        . "/myname@gmail.com/[Gmail]/.Sent Mail")
		  (mu4e-drafts-folder      . "/drafts")
		  (mu4e-trash-folder       . "/myname@gmail.com/Trash")
		  (mu4e-maildir-shortcuts .(("/myname@gmail.com/INBOX" . ?i);; setup some handy shortcuts
					    ("/myname@gmail.com/[Gmail]/.Sent Mail"  . ?s)
					    ("/drafts"                            . ?d)
					    ("/myname@gmail.com/Trash" . ?t)))
		  (mu4e-compose-signature . nil)
		  ;; SMTP configuration
		  (smtpmail-starttls-credentials . '(("smtp.gmail.com" 465 "myname" nil)))
		  (smtpmail-smtp-user . "myname")                   
		  (smtpmail-stream-type . ssl)
		  (smtpmail-default-smtp-server . "smtp.gmail.com")
		  (smtpmail-smtp-server . "smtp.gmail.com")
		  (smtpmail-smtp-service . 465)))
	))
````

**Comment by djcb** [comment]
That seems to work just fine here, even with 26.3.  What mu4e-context-policy are you using? Does it work when you switch manually (with `;`)?

Otherwise, can you bisect the problem? (ie. try version until you find the one where it breaks for you?

**Comment by averter** [comment]
Very strange...now it is working normally, yet I didn't change anything.

**Comment by averter** [comment]
It is happening again. To reproduce:
1. Open an email message sent to the non-gmail account
2. reply all or sender
3. The from field will be the gmail email.
As soon as I switch context once the problem disappears until emacs is restarted. My context-policy is
````elisp
       (setq mu4e-context-policy 'pick-first)
````

**Comment by djcb** [comment]
If you're using `C-x m`, you must set `(setq mail-user-agent 'mu4e-user-agent)` or you'll get some generic emacs mail compose window.

If you have to set  `user-email-address` manually, it seems as if no context at all is chosen.

If I use the mentioned setup (slightly edited for my situation), and
`emacs -Q -l test-setup.el`, that seems to do the right thing.

```
(add-to-list 'load-path "/home/djcb/Sources/mu/mu4e")
(setq mu4e-mu-binary "/home/djcb/Sources/mu/mu/mu")

(require 'mu4e)

(setq mu4e-context-policy 'pick-first)
(setq user-mail-address "myname@gmail.com")

(setq mail-user-agent 'mu4e-user-agent)

(setq mu4e-contexts
      `(
	,(make-mu4e-context
	  :name "work"
	  :enter-func (lambda () (mu4e-message "Switch to the work context"))
	  :leave-func (lambda () (setq mu4e-maildir-list nil))
	  ;; we match based on the contact-fields of the message
	  :match-func (lambda (msg)(when msg
				     (or (mu4e-message-contact-field-matches msg '(:to :bcc :cc) "djcb@djcbsofware.nl")
					 (string-prefix-p "/myname@work" (mu4e-message-field msg :maildir)))))
	  :vars '( (user-mail-address       . "myname@work" )
		   (user-full-name          . "My Name at work" )
		   (mu4e-sent-folder        . "/myname@work/Sent")
		   (mu4e-trash-folder       . "/myname@work/Trash")
		   (mu4e-drafts-folder      . "/drafts")
		   (mu4e-maildir-shortcuts .(("/myname@work/Inbox" . ?i);; setup some handy shortcuts
					     ("/myname@work/Sent"  . ?s)
					     ("/drafts"                      . ?d)
					     ("/myname@work/Trash" . ?t)))
		   ;; SMTP configuration
		   (starttls-use-gnutls . t)
		   (smtpmail-auth-credentials . '(("localhost" 1025 "myname@work" nil)))
		   (smtpmail-smtp-server . "localhost")
		   (smtpmail-default-smtp-server . "localhost")
		   ))
	,(make-mu4e-context
	  :name "Gmail"
	  :enter-func (lambda () (mu4e-message "Switch to the Gmail context"))
	  :match-func (lambda (msg) (when msg
				      (or (mu4e-message-contact-field-matches msg '(:to :bcc :cc) "myname@gmail.com")
					  (string-prefix-p "/myname@gmail.com" (mu4e-message-field msg :maildir)))))
	  :leave-func (lambda () (setq mu4e-maildir-list nil))
	  :vars '((user-mail-address       . "myname@gmail.com")
		  (user-full-name          . "My Name at Gmail")
		  (mu4e-sent-folder        . "/myname@gmail.com/[Gmail]/.Sent Mail")
		  (mu4e-drafts-folder      . "/drafts")
		  (mu4e-trash-folder       . "/myname@gmail.com/Trash")
		  (mu4e-maildir-shortcuts .(("/myname@gmail.com/INBOX" . ?i);; setup some handy shortcuts
					    ("/myname@gmail.com/[Gmail]/.Sent Mail"  . ?s)
					    ("/drafts"                            . ?d)
					    ("/myname@gmail.com/Trash" . ?t)))
		  (mu4e-compose-signature . nil)
		  ;; SMTP configuration
		  (smtpmail-starttls-credentials . '(("smtp.gmail.com" 465 "myname" nil)))
		  (smtpmail-smtp-user . "myname")
		  (smtpmail-stream-type . ssl)
		  (smtpmail-default-smtp-server . "smtp.gmail.com")
		  (smtpmail-smtp-server . "smtp.gmail.com")
		  (smtpmail-smtp-service . 465)))
	))
```

**Comment by averter** [comment]
Thanks Dirk. It does work. I had `user-mail-address` defined as a custom-set-variable, which overwrote `setq user-mail-address`. Not entirely sure why, but previous to commit 0f5f6c4 mu4e was able to update the custom-set-variable and now not anymore. But it's an easy fix; just had to remove the command from the custom-set.  Closing for good.

**Comment by ChauhanT** [comment]
Hi @averter . I am facing a similar issue and instead of opening another one, I think some clarification from you will be enough to get me back on track. I have 3 email addresses (2 gmail and 1 non-gmail) and have set `user-mail-address` using `mu4e-contexts` for each email address (so 3 contexts). There is no `user-mail-address` set outside of the `mu4e-contexts`. 

Whenever I try to compose an email using the non-gmail context, I get all the fields (from, and to) as one would expect in the non-gmail context, but when I send (`C-c C-c`), it ends up using the gmail smtp. No idea what's happening. Is this similar to something you were facing?

Cheers!

**Comment by averter** [comment]
Hi @ChauhanT . Not really, the `From` field was incorrect as soon as I starting to compose the email; it might be worth opening a new issue. However and based on the above, what I had to change was to set `user-mail-address`  outside of the `mu4e-contexts` and remove it if set as a custom-set-variable, so that might do the trick?

**Comment by smalltimer** [comment]
@averter Thanks for the clarification. I'm not able to reliably predict when this issue will occur, but it is often enough to interrupt my workflow. So I'll try to figure out the right conditions and then open another issue on here.
