### ISSUE TITLE
mu4e: no trash flag is not respected for messages deleted from view

### ISSUE THREAD

**Issue by gspe** [djcb/mu#1699]
## Expected or desired behavior

Messages deleted from headers or view should be deleted with the same behavior.

With `no-trash-flag` enabled:
- delete a message from herders, message should be moved to trash folder without trashed flag applied.
- delete a message from view, message should be moved to trash folder without trashed flag applied.

## Actual behavior

With `no-trash-flag` enabled:
- delete a message from herders, the correct behavior is applied and message is moved to trash folder without trashed flag.
- delete a message from view, message is moved to trash folder with trashed flag applied.

## Steps to reproduce

Sent two messages to maildir with `no-trash-flag` enabled and try to delete one message from view and the other from headers

## Versions of mu, mu4e/emacs, operating system etc.
mu4e: 1.4.6.
emacs: 27.0.91

**Comment by djcb** [comment]
Hmm... can reproduce. I've removed the whole no-trash-flag business for now (for 1.4.x), will try again with 1.5.x (which should start soon).

So, turning this into an RFE for now. Sorry for the inconvenience!

**Comment by gspe** [comment]
Ok, so this also means that for now we can't use `make-mu4e-context-account`, right?

Can I ask you if you can post a comment here: https://github.com/emacs-evil/evil-collection/commit/d062cc206d671fb5aefb1e0e679a9cb1d6c73e33#commitcomment-39255922
Some days ago I've posted a commit to change the bind of `d` to `mu4e-headers-mark-or-move-to-trash` that now has to be reverted

**Comment by djcb** [comment]
Sure - have done so.

**Comment by djcb** [comment]
No chance for the flag coming back anytime soon, so closing this. Sorry!
