### ISSUE TITLE
mu4e-view-message-with-message-id opens two windows and three buffers

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1702]
## Expected or desired behavior

When I call `mu4e-view-message-with-message-id` with a message ID, I would expect the current selected frame to view that message.

## Actual behavior

Right now, when that function is called the following happens:
- An mu4e-main buffer is created and switched to
- An mu4e-headers buffer is created and switched to
- A mu4e-view buffer is created in a new frame and switched to.

I usually view the message, read something and kill the buffer or
switch back to the previous buffer expecting to switch back the
buffer that I was working on before calling
`mu4e-view-message-with-message-id`, instead I have to kill or
switch away from all the mu4e buffers and the new window that
were created .

## Versions of mu, mu4e/emacs, operating system etc.
mu, mu4e: 1.4.5
emacs: 26.3
OS: Ubuntu

## Any other detail
I understand that this would require some changes and I am glad to implement it if someone can give me some pointers.

**Comment by djcb** [comment]
Guess you could use `M-x mu4e-quit` when you want to close the message in that case?

**Comment by haji-ali** [comment]
Ah I didn’t know about this function. Yes, that would certainly be a good way. 

But is there a fundamental reason why the main and headers buffers can’t be opened in the background without being switched to? Do you think that, for example, adding a switch to prevent such buffer switches would be a good method to achieve this?

**Comment by djcb** [comment]
The headers-buffer part is 'fundamental' in this case, in the sense that the message view depends on it.

The functionality of the main-view (ie. hooking up with the mu server) is fundamental, but showing the UI is not; and at least I do not see the UI in the `mu4e-view-message-with-message-id` case. Do you?

**Comment by haji-ali** [comment]
Ok I see. The main-view is opened in the background and switched to, which misses up my MRU buffer list. In any case, I am closing this since ‘mu4e-quit’ does a good job of achieving what I want until I have time to look into the source code.

Thanks!
