### ISSUE TITLE
reindexing failure when mail server is accessed by other clients

### ISSUE THREAD

**Issue by maxdantoni** [djcb/mu#1708]
While mu4e is running on my computer, I often access email using other clients (my smartphone, Thunderbird etc.), marking new messages as read. When I return back to mu4e, I see the headers have not been correctly updated, some messages are missing.

As the problem could depend on lazy check, I disabled it and updated using the following:

(defun my-mu4e-update-index-non-lazy ()
  (interactive)
  (let ((mu4e-index-lazy-check nil))
    (mu4e-update-index)))

However,  this doesn't solve the problem. The only solution seems to be to quit mu4e, reindex and start mu4e again. I do it automatically with the following command, which makes the missing messages reappear:

(defun mu4e-reload () "Quit, reindex and reload mu4e" (interactive)
       (mu4e-quit)
       (sleep-for 1)
       (shell-command "mu index")
       (sleep-for 1)
       (mu4e)
       (delete-other-windows))

It is seems that reindexing outside mu4e is not equivalent to reindexing inside it with mu4e-index-lazy-check set to nil.

I'm using mu4e 1.4.6 with emacs 28.0.50 on ubuntu linux 18.04.2

**Comment by djcb** [comment]
To be able to debug this, I would need a bit more detail:
- how do you synchronize your local Maildir with whatever your smartphone, Thunderbird are doing?
- which messages are not synchronized? Only new ones? _Some_ new ones? _All_ new ones?
- if you run the manual `mu index`, but with `--lazy-check`, does that make a difference?
- what about setting changing the value of `mu4e-index-cleanup`?

Thanks.

**Comment by maxdantoni** [comment]
- I synchronize my local Maildir with mbsync: (mu4e-get-mail-command "mbsync -a"), while the other clients access the remote server independently
- only some new messages are not synchronized, those whose state hasn't been changed by the other client are shown, the problem is with (some of) those whose state has been changed to "read"
- if I quit mu4e and I run "mu index --lazy-check" outside emacs, when I restart mu4e everything seems to be alright (i.e. mu4e shows me all messages)

**Comment by maxdantoni** [comment]
A preliminary try with `mu4e-index-cleanup` set to t seems to solve the problem. However, I need to test it again

**Comment by maxdantoni** [comment]
Apparently, setting the variable `mu4e-index-cleanup` to `t` solves the problem. I have defined a function to do a thorough reindex only occasionally, to avoid slowing down normal email check:

```
(defun my-mu4e-thorough-index ()
  "Perform a thorough reindexing" (interactive)
  (let ((mu4e-index-cleanup t))
    (mu4e-update-index)))

```
or a thorough mail check:

```
(defun mu4e-thorough-check ()
  "Perform a thorough check" (interactive)
  (let ((mu4e-index-lazy-check nil)(mu4e-index-cleanup t))
    (mu4e-update-mail-and-index t)))

```

Thanks for the suggestion

**Comment by djcb** [comment]
Great! Thanks for testing. Closing this.
