### ISSUE TITLE
Mu4e fails to show some emails

### ISSUE THREAD

**Issue by tecosaur** [djcb/mu#1709]
## Expected or desired behaviour

I expect every email I receive to be shown by Mu4e. 

## Actual behaviour

_Most_ emails I receive are displayed by Mu4e. In the past few days, there have been two emails which just don't show up :disappointed:.

I have yet to discern any possible trigger, and there's no error message I can find, so I'll simply share the latest problematic email (it's from a public list, so this seems fine).

Looking manually ` ~/.mail/gmail-tecosaur/Inbox/cur/1590479815.2647212_1.tranquillity,U=9983:2,S` (downloaded by `mbsync`) does not show up in mu4e. In mailspring I see this:

![image](https://user-images.githubusercontent.com/20903656/82877011-3c967880-9f6c-11ea-8712-357982d5934e.png)

Mu4e:

![image](https://user-images.githubusercontent.com/20903656/82877107-6059be80-9f6c-11ea-932d-6f69d3735877.png)

Here's the file for the email in question, I just had to append a `.txt` to have GitHub successfully accept it.

[1590479815.2647212_1.tranquillity,U=9983:2,S.txt](https://github.com/djcb/mu/files/4680796/1590479815.2647212_1.tranquillity.U.9983.2.S.txt)

## Steps to reproduce

As mentioned, I am yet to notice any common factor with this, however perhaps the file above may help in this regard.

## Versions of mu, mu4e/emacs, operating system etc.

Mu4e 1.4.6
Emacs 26.3
Linux 5.6.13-153 on Solus

**Comment by tecosaur** [comment]
May be related, I'm also seeing stuff like this now and then
```
error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /home/tec/.mail/gmail-tecosaur/Org Mode/new/1590496521.2674833_1.tranquillity,U=298:2, (line was:'(move :docid nil :msgid "m2h7w250zg.fsf@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')
error in process filter: Error 2: failed to move message: cannot read /home/tec/.mail/gmail-tecosaur/Org Mode/new/1590496521.2674833_1.tranquillity,U=298:2, (line was:'(move :docid nil :msgid "m2h7w250zg.fsf@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')
```

**Comment by averter** [comment]
Just a thought, have you tried to run `mu index` and look for the email again? Or also try to run `mu find org-edit-special` and see if the email is listed.

**Comment by tecosaur** [comment]
I in fact tried `mu --init ...` followed by `mu index`, then searching for the email. No luck.

**Comment by djcb** [comment]
Nothing wrong with that message. 

Ultimately the problems is `mbsync` changing things behind mu4e's back... not much we can do about it, but there are some ways to mitigate this, see #1708.

**Comment by tecosaur** [comment]
@djcb might you know why I still don't see the message, even after re-initialising `mu`?

**Comment by djcb** [comment]
Can you find it in `mu`, but not `mu4e`? 

How did you search? 

Note that you might need e.g. to search for `mu find \"org edit special\"` (since you need a phrase search here).

**Comment by tecosaur** [comment]
I've only tried within mu4e. Running a very specific search it seems that email is now appearing. I'm not sure when this changed, but that's good. I'll try taking the advice of the other thread and using the cleanup flag. Thanks.

**Comment by averter** [comment]
I also confirm that setting `mu4e-index-cleanup` to `t` makes everything work again (thanks for the reference @djcb ). I am using mu4e 1.4.13 and isync 1.3.3.
