### ISSUE TITLE
Compose mail with (org-submit-bug-report) broken

### ISSUE THREAD

**Issue by nivekuil** [djcb/mu#1710]
## Expected or desired behavior

(org-submit-bug-report) works

## Actual behavior

Please describe the behavior you are actually seeing. 

1. `Wrong number of arguments: (8 . 8), 0` I think this can be fixed by making the lambda args added in https://github.com/djcb/mu/commit/a2d315df4ce903d967e4e63d1c223593ac85bcb0 `&optional`
2. The org bug report template is written to the buffer it was called from, not the mu4e compose buffer.

## Steps to reproduce

(org-submit-bug-report)
insert whatever for the prompts

## Versions of mu, mu4e/emacs, operating system etc.
mu 1.4.7 
emacs "27.0.91"

**Comment by alexmurray** [comment]
Similarly, `M-x report-emacs-bug` is also broken when using mu4e (1.4.6)

**Comment by djcb** [comment]
This is ultimately the same issue as: #1698; closing this one. Thanks for reporting.
