### ISSUE TITLE
Feature request: actuality of inbox

### ISSUE THREAD

**Issue by koendeheer** [djcb/mu#1711]
I was wondering whether it would be possible to add (the option to show) the actuality of the inbox in *m4e-main* and IMHO even better: in *mu4e-headers*. With other words, when the last successful synchronization took place, a date/time or even better **-15 min**. Besides the actuality this would also reveal problems with synchronization. (Other than the temporary error in the echo buffer.) I hope it did not miss this option in the manual!

**Comment by djcb** [comment]
Yeah, the main-view now shows the last updated time (and see `mu info`), in 1.7.27 and few versions before that.
