### ISSUE TITLE
Cant compile mu with the new mu-log.cc on Fedora

### ISSUE THREAD

**Issue by yp-warsaw** [djcb/mu#1713]
Hi,
With the commit 3e233cba9af8dd31852e81f0703e0c39e724ffb7, I can't compile mu on Fedora 32.
I got the following error :
`Making all in utils
make[4]: Entering directory '/git/mu/lib/utils'
make[4]: *** No rule to make target 'mu-logger.cc', needed by 'mu-logger.lo'.  Stop.
make[4]: *** Waiting for unfinished jobs....`

My glib packages are : 
`glib-networking.i686                       2.64.2-1.fc32             

glib-networking.x86_64                     2.64.2-1.fc32              

glib2.i686                                 2.64.3-1.fc32              

glib2.x86_64                               2.64.3-1.fc32               

glib2-devel.x86_64                         2.64.3-1.fc32

json-glib.i686                             1.4.4-4.fc32            
     
json-glib.x86_64                           1.4.4-4.fc32            
     
json-glib-devel.x86_64                     1.4.4-4.fc32              `

Btw  thanks you so much for all your work is this project : the couple Emacs+mu is the BEST mail client I ever used (and i tried a lot of them pine in the late 90's, eudora, claws mutt,..)!!!

If you need more informations for this issue, I will be happy to give you them :)
Take care

**Comment by djcb** [comment]
Ha, thanks! It was just a silly mistake, forgot to check in a few files.

**Comment by yp-warsaw** [comment]
Thanks for the quick fix :) I like very much the possibility to log directly to systemd. It's a very nice and handy feature
