### ISSUE TITLE
The recently commits on master breaks org-store-link in mu4e

### ISSUE THREAD

**Issue by stardiviner** [djcb/mu#1714]
This commit:
```
7ed8d509 * mu4e-org: support more attributes for capturing
```

It removed let-binding caused void variables.

**Comment by djcb** [comment]
Works for me... what are you seeing exactly?

**Comment by stardiviner** [comment]
I use `org-store-link` in mu4e headers mode. And have option `mu4e-org-link-query-in-headers-mode` enabled.

I'm seeing the function 
```elisp
(defun mu4e~org-store-link-query ()
   "Store a link to a mu4e query."
   (setq org-store-link-plist nil) ; reset
 (org-store-link-props
  :type        "mu4e"
  :query       (mu4e-last-query)
  :date        (format-time-string "%FT%T") ;; avoid error
  :link        (link (concat "mu4e:query:" query))
  :description (format "[%s]" query)))
```
The `link` and `query` is void.

**Comment by djcb** [comment]
Ah, now I see, it was the query storage... silly mistake. Fixed in master, thanks!

**Comment by stardiviner** [comment]
That's great, Thanks.
