### ISSUE TITLE
Maildir does not open after updating to 1.4.9

### ISSUE THREAD

**Issue by 00-matt** [djcb/mu#1717]
Every time I try to open a maildir by pressing <kbd>j</kbd> on the main screen, I get the following error message:

```
Symbol's value as variable is void: truncate-string-ellipsis
```

## Steps to reproduce

Update to mu 1.4.9 and try to jump to a maildir.

## Versions of mu, mu4e/emacs, operating system etc.

* Emacs 27.0.91
* mu 1.4.9

## Any other detail

Seems to be caused by 57d38aa.

Setting `truncate-string-ellipsis` to `"..."` makes everything work just fine, but it would be nice if it worked as it did before in the default configuration.

**Comment by djcb** [comment]
Hmmm, that's weird, that variable _should_ be defined by default (since emacs 25).  Can you try a full rebuild (`./autogen.sh && make`), and restart emacs?

**Comment by 00-matt** [comment]
Same issue with a clean build :(.

If I `(require 'mule-util)` before starting mu4e that seems to define the default value.

**Comment by phenix-factory** [comment]
I confirm this issue on Spacemacs

**Comment by djcb** [comment]
I've fixed this on the release branch, and this will be in 1.4.10.
