### ISSUE TITLE
sort messages by size in a query 

### ISSUE THREAD

**Issue by drdv** [djcb/mu#1718]
I have added `(:size . 10)` to `mu4e-headers-fields` so that I see message size.

## Expected or desired behavior

Sorting (`mu4e-headers-change-sorting`) by size should sort the messages in the query by size.
I expect this because in `mu4e-header-info` there is `:sortable t` corresponding to `:size`.

## Actual behavior

The messages are not sorted correctly.

**Does it happen always**: yes

## Versions of mu, mu4e/emacs, operating system etc.

1.4.9

**Comment by djcb** [comment]
This works fine in 1.5.9 at least; but note that you must disable threading for sorting by size to work.
