### ISSUE TITLE
`mu init` does not accept `--my-address` option

### ISSUE THREAD

**Issue by carrete** [djcb/mu#1719]
## Expected or desired behavior

I don't know. Perhaps "mu should behave as it says it does"?

## Actual behavior

I followed [these instructions](https://github.com/djcb/mu/blob/master/NEWS.org#how-to-upgrade):

    Make sure mu init points to the right Maildir folder and add your email
    address(es) the following way:
    `mu init –maildir=~/Maildir –my-address=jim@example.com –my-address=bob@example.com’

Except:

    $ mu init -maildir=~/Maildir –my-address=tvaughan@redacted.cl –my-address=tom@redacted.cl
    error: Unknown option -maildir=~/Maildir (0)

From here I went spelunking. The only related, open issue I found is #1664. Somehow I discovered:

    $ mu --help-init
    error: Unknown option --help-init (0)

    $ mu init --help-init
    Usage:
      mu [OPTION…] - mu general options

    Options for the 'index' command
      -m, --maildir=<maildir>     top of the maildir
      --my-address=<address>      my e-mail address; can be used multiple times

Note this says "Options for the **'index'** command", and shows two dashes versus one for the command-line options as is shown in NEWS.org. So I tried:

    $ mu init --maildir=~/Maildir -–my-address=tvaughan@redacted.cl -–my-address=tom@redacted.cl
    error: Unknown option -–my-address=tvaughan@redacted.cl (0)

Now it seems like the --maildir option has been accepted, and the --my-address options have been rejected.

Given the conflicting wording in the help output above, and the mixed acceptance of the command-line options, I don't know what the correct behavior should be, but it does seem as though there's something broken in the current implementation.

## Steps to reproduce

See above.

## Versions of mu, mu4e/emacs, operating system etc.

    $ mu --version
    mu (mail indexer/searcher) version 1.4.9

macOS Catalina, installed via brew

## Any other detail

    $ mu index --help-index
    Usage:
      mu [OPTION…] - mu general options

    Options for the 'index' command
      --lazy-check       only check dir-timestamps (false)
      --nocleanup        don't clean up the database after indexing (false)

**Comment by djcb** [comment]
It looks as if you're using `-my-address=` rather than `--my-address=`?

**Comment by carrete** [comment]
> It looks as if you're using `-my-address=` rather than `--my-address=`?

Oh wow:

    $ mu init -maildir=~/Maildir –my-address=tvaughan@redacted.cl –my-address=tom@redacted.cl
    error: Unknown option -maildir=~/Maildir (0)

and:

    $ mu init --maildir=~/Maildir –my-address=tvaughan@redacted.cl –my-address=tom@redacted.cl
    database-path      : /Users/tvaughan/.cache/mu/xapian
    messages in store  : 0
    schema-version     : 451
    created            : Sun Jun  7 11:12:49 2020
    maildir            : /Users/tvaughan/Maildir
    personal-addresses : <none>

So two dashes are require for maildir, and one dash is required for my-addresses. Except should I see the two email addresses listed in `personal-addresses`?

**Comment by djcb** [comment]
All long options start with `--`, so `--maildir`, `--my-address` etc.

**Comment by carrete** [comment]
> All long options start with --, so --maildir, --my-address etc.

This isn't the behavior shown above.

**Comment by djcb** [comment]
Hmm, seem github eats the double-dashes in its output; update that.

**Comment by djcb** [comment]
Does it work with the updated instructions?

**Comment by carrete** [comment]
Does what work exactly? In the issue description I show that —my-address (two dashes) isn’t accepted. An error is thrown. And -my-address (one dash) doesn’t thrown an error, but it seems as though there was no effect.

**Comment by djcb** [comment]
But it must be really `--my-address` -- the examples have single dashes, or .e.g. `-–my-address=tom@redacted.cl` which _looks_ like two dashes, but contains some unicode em-dash. You really need two plain-text ascii dashes, `--`.

**Comment by carrete** [comment]
Weird. I thought I did type the two dashes myself after I noticed that GitHub swallowed the dashes. Apparently not. I just tried again, making sure I typed everything this time, and yes now everything works as advertised. I see the two email addresses listed under personal-addresses. I should have caught my mistake sooner. Thanks for the help.
