### ISSUE TITLE
Please don't bind keys to anonymous functions

### ISSUE THREAD

**Issue by phil-s** [djcb/mu#1720]
## Expected or desired behavior

The likes of `C-h k h` in `mu4e-view-mode` tells me useful things.

## Actual behavior
```lang-none
h runs the command #[257 "\203\0\301\302!\207\211\203\0\303!\207\303 \207" [mu4e-view-use-gnus mu4e-warn "binding not supported with the gnus-based view" mu4e-view-toggle-html] 3 "

(fn PREFIX-ARGUMENT)" "P"] (found in mu4e-view-mode-map), which is an
interactive compiled Lisp function.

It is bound to h.

(anonymous PREFIX-ARGUMENT)

Not documented.

[back]
```

Similarly if I `describe-mode` and look at the keymap to see what is available, I get just `??` for these.  E.g.:

```lang-none
b               mu4e-headers-search-bookmark
d               mu4e-view-mark-for-trash
e               ??
f               ??
g               ??
h               ??
j               mu4e~headers-jump-to-maildir
k               ??
m               mu4e-view-mark-for-move
n               mu4e-view-headers-next
o               ??
p               mu4e-view-headers-prev
```

## Versions of mu, mu4e/emacs, operating system etc.

mu4e-mu-version is "1.4.9"

## Any other detail

Most of the examples are on account of `mu4e~native-def` being used like this:
```lang-el
(define-key map "h" (mu4e~native-def mu4e-view-toggle-html))
```

**Comment by djcb** [comment]
Indeed, we need to separate things between gnus-view / mu4e-view a bit better so this works again.

**Comment by djcb** [comment]
Yeah, the new view fixes this. Closing.
