### ISSUE TITLE
What is the replacement for  mu4e-org-link-desc-func

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1721]
## Expected or desired behavior

I call `org-store-link` on messages in the view or header-list to get a link to the message that I then can copy somewhere else (in fact I use that functionality everytime I need a link to something, like a file). Before I used `mu4e-org-link-desc-func` to customize the link to include the sender name in the link and this worked well.

## Actual behavior
With the recent commit   7ed8d509eea036f54, new fields were added to org links like `%:from` and other to get those customizations, but it seems that customizing `%a` was removed. Is there a way to get that customization back?

I did this at the moment:

```
(define-advice mu4e~org-store-link-message (:after () my/mu4e-link-append-desc)
    (org-add-link-props
     :description (my/mu4e-org-link-desc-func (mu4e-message-at-point))))
```

## Versions of mu, mu4e/emacs, operating system etc.
mu4e-info: `Wrong number of arguments: (1 . 1), 0`
mu: 1.5.1
Emacs: 26.3

**Comment by djcb** [comment]
Hmmm... that's not really a supported customization point currently. 

If you really need that, I suspect the defadvise could still work; ultimately `org-add-link-props` just does some `plist-put` which replaces the existing value. Not quite sure why it doesn't work for you.

I'll keep the feature request in mind ;)

**Comment by haji-ali** [comment]
Ah sorry. I meant to say that it does work as expected, but was wondering if mu4e has a better way so that I don’t use internal function names. 

Thanks for re-considering the feature.

**Comment by djcb** [comment]
`mu` 1.6.3 gained `mu4e-org-link-desc-func`, closing this.
