### ISSUE TITLE
any interest in setting up a GitHub action to run the tests?

### ISSUE THREAD

**Issue by benswift** [djcb/mu#1723]
Is there any interest in setting up a [GitHub action](https://github.com/features/actions) to run the test suite for every push to master? It's a nice way of easily identifying when things break the build, and you could also set it up to run for every pull request as a pre-check.

We could even set up a test matrix to try and build & test on Ubuntu and macOS. And it'd be free because mu's a public GH project.

If there was interest, I'd be happy to create the PR. But I wanted to check first.

**Comment by tpapp** [comment]
Some kind of CI would be great. Cf #1458.

**Comment by benswift** [comment]
Hey there, I've just pushed a commit to [my fork](https://github.com/benswift/mu/tree/pr-test-ci) which has a `.github/workflows/build-and-test.yml` file that specifies the CI test. You can see the results [here](https://github.com/benswift/mu/actions/runs/131859005) (ignore the ones from `master`, the `pr-test-ci` branch has a squashed commit which is cleaned up).

Now, it's currently broken on master; the test that's failing is:

    ERROR:test-mu-cmd.c:500:test_mu_extract_overwrite: assertion failed (erroutput != ""): ("" != "")

I don't actually know enough about mu's tests to know if this is a known issue, or if it's something like e.g. not having the right deps installed (easy to fix if so).

The `build-and-test.yml` file should be fairly self-explanatory, feel free to cherry-pick it and modify as appropriate. I can also add macOS to the test matrix (based on the homebrew formula) but will wait to see how this one goes first.

**Comment by benswift** [comment]
Ok, I've added macOS to the build matrix as well, the same test seems to be failing:

<https://github.com/benswift/mu/runs/760717286>

Sorry that the git history on my branch is a bit of a mess. If you like, I can go back to `djcb/mu:master` and format it nicely as one (or more) commits, then create the PR.

**Comment by djcb** [comment]
Sounds cool! If you can squash your commits I'd be happy to take a PR.

(Oh, I "fixed" the broken test (by temporarily turning it off, really fix soon).

**Comment by djcb** [comment]
Merged, thanks.
