### ISSUE TITLE
Feature request: Handling of related messages

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1724]
## Expected or desired behavior
It would be great if related message in the headers-view are distinguished both in appearance and in functionality. 

I have a view folder where I show messages in my inbox. I like to see related messages however they clutter my inbox and make it difficult to see and handle messages that are really in the inbox vs related ones. For this reason, I suggest the following:

- Related messages have a different face
- The keys `M-n` and `M-p` go to next and previous message, skipping related messages (`C-n` and `C-p` scroll through all messages as they do now).
- When `T` is pressed, the thread action should not be performed on related messages. Related messages include messages that I sent (in my sent folder) or other messages that I previously filed to a specific folder and right now when I archive a thread all of these messages are sent to my archive folder. Usually, when I archive a thread, I really mean archiving the messages that are causing that thread to appear in my inbox (this is the standard behaviour for mail clients, at least for sent emails).

## Actual behavior
See above.

## Versions of mu, mu4e/emacs, operating system etc.
mu: 1.5.1
emacs: 26.3

## Any other detail
I wanted to implement this as a pull request, but it seems that ":include-related" flag is passed to `mu` and the related message are indistinguishable in the `mu` output. So if I am not mistaken this would require changes in `mu` to include a flag `:is-related` or something. Please let me know if I am missing something.

**Comment by djcb** [comment]
I like the idea! 

I'm planning a few bigger changes in the way mu does querying, so now is probably not the best time for preparing PRs; but stay tuned :)

**Comment by djcb** [comment]
Good news: in the headers-view, there's the `mu4e-related-face` now (1.7.27) (and `:related`). For refiling, the trick is that to set it up dynamic refiling folders so that they do the right thing for all message; so e.g. my 'sent' messages just stay even when they in a related-thread where some go to another folder. 

That should also allow you to implement such key-bindings like `M-n`, `M-p` if you want.

So closing this - thanks!
