### ISSUE TITLE
Send email with attachment won't send

### ISSUE THREAD

**Issue by Nathoufresh** [djcb/mu#1726]
## Expected or desired behavior

Be able to send an email with an attachment.

## Actual behavior

When I try to send a mail with an attachment it does not send it but it opens the attachment in an external program.
send-mail-function is smtpmail-send-it.

## Steps to reproduce

Compose or forward a message with an attachment, try to send it with C-c C-c.

## Versions of mu, mu4e/emacs, operating system etc.

using aur package mu-git 1.4.7.51.gdd0cb311-1
manjaro-linux
emacs27-git 27.0.90.140235-1

It works well without an attachment!

**Comment by djcb** [comment]
Works fine here.

Can you reproduce with `emacs -Q`, then load a minimal mu4e setup and then try to send a mail?

**Comment by Nathoufresh** [comment]
Yeah it works with a minimal config, I found out that the openwith package was faulty

```
(when (require 'openwith nil 'noerror)
  (setq openwith-associations
        (list
         (list (openwith-make-extension-regexp
                '("mpg" "mpeg" "mp3" "mp4"
                  "avi" "wmv" "wav" "mov" "flv"
                  "ogm" "ogg" "mkv"))
	       "vlc"
	       '(file))
         (list (openwith-make-extension-regexp
                '("doc" "xls" "ppt" "odt" "ods" "odg" "odp"))
	       "libreoffice"
	       '(file))
         (list (openwith-make-extension-regexp
                '("pdf" "ps" "ps.gz" "dvi"))
	       "okular"
	       '(file))))
  (openwith-mode 1))

```
I will not abuse your kindness but do you know a workaround to open attachment in external program but still be able to send it?

**Comment by khourhin** [comment]
I got the same problem and found this fix to work for me:
https://stackoverflow.com/a/22946859/3561564

**Comment by Nathoufresh** [comment]
It's working, thanks a lot!
