### ISSUE TITLE
Accepting an Outlook invite doesn't mark as accepted

### ISSUE THREAD

**Issue by behaghel** [djcb/mu#1729]
## Expected or desired behavior

When I click the [ Accept ] button and send the response straightaway, on reception, I expect the organiser's calendar to update my status as invitee and mark me as accepted.

## Actual behavior

From a google calendar invite, this works. From an outlook (office 365) invite, this doesn't. The response is received with the attached ics marking attendance as accepted and yet outlook still keep me as "didn't respond".

## Steps to reproduce

open email, go on button [ Accept ], click enter, then send with C-c C-c, then check on outlook calendar.

## Versions of mu, mu4e/emacs, operating system etc.

- mu4e 1.4.1
- emacs 28.0.50

## Any other detail

I have tried to figure out if something was wrong with the text/calendar part by tweaking the `*CAL*` buffer but without being an expert, I don't think so. Tried also to figure how does outlook deal with it itself but it seems to deal with this through API and not attachment. I am more than happy to help in any way I can.

## Something I Discovered

Unrelated and may or may not be a bug. If both emails for organiser and attendee are listed as personal addresses in your mu, it then creates two ATTENDEE;PARTSTAT: lines one for each which then break the updating of the organiser calendar. In fact I have even managed to get 3+ of these lines by inviting more emails that I own.

**Comment by Chris00** [comment]
@djcb May you assign me to this issue?
@behaghel I you have more time to investigate what is wrong with outlook (maybe try to remove the multipart??), that will be helpful.  I only have easy access to OWA (Outlook Web Application); if you have too may you check whether the behavior differs?

**Comment by behaghel** [comment]
@Chris00 I am really keen to help. I suggest I start by inviting you on an email address of your choice. That would discard an issue with my setup. What do you think?

**Comment by Chris00** [comment]
Use christophe+troestler → umons+ac+be (replace `+` by `.` and ` → ` by `@`).

**Comment by Chris00** [comment]
I have tested with a colleague who uses Outlook and she says it works.

**Comment by behaghel** [comment]
<img width="1028" alt="Screenshot 2020-06-16 at 21 55 49" src="https://user-images.githubusercontent.com/251832/84832805-d611f100-b025-11ea-9cc0-f38248a0c61c.png">

Thanks for allowing this test. I have the same behaviour with your config as with mine: it doesn't work. Not sure where we go from there...

**Comment by Chris00** [comment]
Second reply sent.

**Comment by behaghel** [comment]
\o/ Victory! \o/

Indeed I had found on various Microsoft bug reports that the multipart could be an issue. I had in fact scanned the internet for clues and was about to add here a note to self listing all I found. But no need now! Well I wish this meeting could take to celebrate ;)

Did you have to manually tweak the content or did you change it through config?

**Comment by Chris00** [comment]
I pushed some changes on my branch.  By default, it only sends the ICAL file.  However, if you would like to add a message, the citation of the original message is in the kill-ring.  May you confirm that it works (with outlook and google) with and without a message?  @dmacvicar if you have some time to test this too, it will be appreciated.  Thanks.

**Comment by dmacvicar** [comment]
I need to wait until our mail system is reconfigured to send iCal appointments instead of Web links. I will report back then!

**Comment by dmacvicar** [comment]
I was never able to test before this got merged, but I can't get it to work (Office 365). Anyone else using a similar setup?
