### ISSUE TITLE
Slow rendering of S/MIME encoded messages

### ISSUE THREAD

**Issue by sje30** [djcb/mu#1733]
## Expected or desired behavior

When I open the message I expect to see it rendered within a couple of secnds.

## Actual behavior

It can take 20-30 seconds to render a message that has been encoded. 

Please describe the behavior you are actually seeing. 

For bug-reports, if applicable, include error messages, emacs stack
traces etc. Try to be as specific as possible - when do you see this
happening? Does it happen always?  Sometimes? How often?

## Steps to reproduce

An example of such a message, sent by @nuest to me, is available at:

https://gist.github.com/2077b7dcd18e5956dc2a17d5b311c7f3

## Versions of mu, mu4e/emacs, operating system etc.

mu4e 1.4.3 on manjaro linux stable.

## Any other detail

I notice that if I  add the following to my .emacs

```
(setq mu4e-view-use-gnus t)
```

then the rendering time is much quicker, e.g. 2-3 seconds.  Much better!  If the gnus backend for rendering messages is the future, as it seems from the docs, then this may be enough to solve my problem, but I thought I'd share with you the current example.

**Comment by djcb** [comment]
It's a known issue, see #1536. The later 1.4.x has some improvements, and 1.5.x some more, the gnus-view avoids of that in a different way.

What remains seems to be gpg/gpgme itself, perhaps experimenting with its options can help.
