### ISSUE TITLE
Opening a message messes up the thread prefixes in header-view

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1736]
## Expected or desired behavior

When opening a message in the header-view, I don't expect the thread view to change.

## Actual behavior

When I open a message from the header-view, the header is removed from the header-view and then it is inserted back (probably to update its face since the message is now read).

However, because of this the prefix which shows the thread tree is not rendered correctly on the newly inserted line.

This is because the function `mu4e~headers-thread-prefix` which is called on the current message assumes that `mu4e~headers-thread-state` has the previous prefixes which are obtained by rendering the messages in the header-view in order.

## Steps to reproduce
1. Open header view
2. View thread with multiple message and choose one that has multiple thread prefixes (e.g. `┃ ┗▶`). 
3. Open the message.
4. The header now shows a single prefix, i.e., `┗▶`.

## Versions of mu, mu4e/emacs, operating system etc.
mu: 1.5.3
emacs: 26.3
OS: Ubuntu

**Comment by djcb** [comment]
This is a very old issue, #474. That doesn't fix it of course but I'll try to do something about this during 1.5.x.
