### ISSUE TITLE
Emails missing in mu4e present in mu find

### ISSUE THREAD

**Issue by 2e0byo** [djcb/mu#1737]
## Expected or desired behavior

`mu find <query> | wc -l` should give the same number as there are lines in the buffer after running `(mu4e-headers-search "<query>")`

## Actual behavior

With only one maildir, added yesterday, `mu-find maildir:/yahoo/Inbox | wc -l` returns 6175, but running the same query inside Emacs (mu4e) returns only four messages.

mu4e works correctly with three other maildirs, and has for years (and I couldn't live without it, thank you!)

Not sure how to debug this but happy to chase it.  For starters, how does the mu-server syntax work?  I've tried
`cmd:find query:maildir:/yahoo/Inbox` at the mu server prompt (only running instance) but that and all queries don't find anything, so clearly I'm missing something about mu-server.

So far haven't spotted anything about the four messages found and those not found.

This happens whether the mu database is updated from within Emacs or outside of it.  Have tried removing `~/.cache/mu` and rebuilding the cache.

## Steps to reproduce

No idea.  This only happens with one maildir recently cloned from yahoo with offlineimap.  I'm obviously not going to provide the maildir ;)

## Versions of mu, mu4e/emacs, operating system etc.

mu/mu4e is 1.3.5, in archlinux, installed with mu4e-git

**Comment by djcb** [comment]
See https://www.djcbsoftware.nl/code/mu/mu4e/General.html#Results-from-mu-and-mu4e-differ-_002d-why_003f, does that help?

**Comment by 2e0byo** [comment]
ah, no thank you: mu4e is only seeing *four* messages, whilst mu gives loads (with `--maxnum 500` it gives 500 as expected, with `--include-related` it finds a good deal more).

I think I really need to dig into whether this is happening with the query to `mu server`, or somewhere inside my Emacs.  I'll have another look through `mu4e-proc.el` but what's the syntax for `cmd:find`?  I'm sure I'm doing something stupid.

**Comment by djcb** [comment]
I'd recommend getting the latest released version, i.e., see `https://github.com/djcb/mu/releases` (1.4.10 is the one right now), and see if you can reproduce there.

If you do and want to check `mu server`, that's a lot easier there as well

**Comment by 2e0byo** [comment]
Alright, I feel pretty stupid for not trying that.

Rebuilt database with mu 1.4.1, and the problem seems to have gone.  Mu4e has also improved a fair bit, thanks!

Mu server is indeed a lot easier to figure out as well :)
