### ISSUE TITLE
(mu4e-update-mail-and-index nil) gives wrong number of arguments error in progress-reporter-do-update

### ISSUE THREAD

**Issue by tpapp** [djcb/mu#1741]
## Expected or desired behavior

```emacs-lisp
(mu4e-update-mail-and-index nil)
```
should just run without error.

## Actual behavior

Instead, getting a wrong num of args error with the backtrace
```emacs-lisp
Debugger entered--Lisp error: (wrong-number-of-arguments (2 . 2) 3)
  progress-reporter-do-update((1 . [1593523587.0683994 nil nil #("[mu4e] Retrieving mail..." 1 5 (face mu4e-title-face)) 1 0.2]) nil nil)
  mu4e~get-mail-process-filter(#<process mu4e-update> "\015C: 0/2  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0")
```

This started happening recently, in the last few days. I am unable to pin it down though, mu4e code does not seem to be calling a 3-argument version.

## Steps to reproduce

See above.

## Versions of mu, mu4e/emacs, operating system etc.

Latest master (0355479b51c46fc8), Ubuntu 20.20, Emacs 26.3 from the kelleyk PPA.

**Comment by djcb** [comment]
Hmm, perhaps the mu4e files were compiled with a newer emacs version, and you try to use them with 26.3?

**Comment by tpapp** [comment]
Thanks, it turns out that I compiled using Emacs 27 when I was testing a package there, then ran in Emacs 26.3. Sorry for the noise.

Incidentally, what's the best way to use mu4e compiled from source in multiple Emacs versions? Compile the repo for each in separate directories?

**Comment by djcb** [comment]
Ideally, emacs should warn I guess. But, without that, keeping them separate should work. Or not compile at all.
