### ISSUE TITLE
HTML message in emacs 27.0.9

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1748]
## Expected or desired behavior

Correct display of HTML messages

## Actual behavior

I just updated to Emacs 27.0.9 and when I open HTML messages `span` and `script` HTML tags are displayed as text (including the tags beginning and end markers). I have `mu4e-view-use-gnus` set to true. Calling `mu4e-view-toggle-html` does not change the view at all.

## Steps to reproduce
In Emacs 27.0.9, display any html message.

## Versions of mu, mu4e/emacs, operating system etc.
Mu commit: c4e8a8f04c
Emacs: 27.0.9

**Comment by djcb** [comment]
Can you attach a message where this happens? Thanks.

**Comment by haji-ali** [comment]
Almost all HTML messages are showing this problem on Emacs 27.0.9, here is an example:
[1594110998.31646_7.thinkpad,U=1753:2,S.zip](https://github.com/djcb/mu/files/4883659/1594110998.31646_7.thinkpad.U.1753.2.S.zip)

This shows up as
```
This is a testThis is a testThis is a test<span style="background-color:rgb(255,0,0)">This is a test</span>
```

**Comment by djcb** [comment]
Cannot reproduce that with emacs 27 or any emacs version I tried, with either the gnus-based view or not.

**Comment by haji-ali** [comment]
Turned out that I did not have libxml2 enabled in my emacs compilation.
