### ISSUE TITLE
Mu server process ended with exit code 1

### ISSUE THREAD

**Issue by DiogoFerrari** [djcb/mu#1754]
## Expected or desired behavior
Start mu4e buffer using M-x mu4e 

## Actual behavior
It returns
error in process sentinel: mu4e~proc-sentinel: Mu server process ended with exit code 1
error in process sentinel: Mu server process ended with exit code 1
and do not open mu4e

## Versions of mu, mu4e/emacs, operating system etc.
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-12-02
mu4e 1.5.4.
Ubuntu 20.04

## Any other detail
"mu find <something>" is working normally on terminal

**Comment by DiogoFerrari** [comment]
I reinstalled and the issue was solved.

**Comment by 88-percent** [comment]
In case it helps anyone avoid a full reinstall after getting this error I reinitialized as suggested [here](https://github.com/djcb/mu/issues/2525) and that seems to solve it for me.
