### ISSUE TITLE
Time stamps on server are wrong after sync

### ISSUE THREAD

**Issue by oatmealm** [djcb/mu#1755]
I've ran into the problem caused when moving messages during sync where by now I have many old messages showing on the server (iCloud) with a wrong date. It's the date of the sync date rather than their original mtime !? ... is there a simple way to fix this and re-sync?

**Comment by djcb** [comment]
Seems it should use the message-date rather than the mtime? Perhaps you can "touch" the files with some older date?
Anyway, this is a question for your syncing program, not for mu4e, not much we can do about that.
