### ISSUE TITLE
mu4e-context-label is not spaced from display-time

### ISSUE THREAD

**Issue by Sbozzolo** [djcb/mu#1758]
Currently, `mu4e-context-label` returns a string of the form "[XXXXX]". When `display-time` is enabled, both `mu4e` and `display-time` write in the `global-mode-string` and following happens:
![2020-07-12:11:16:22](https://user-images.githubusercontent.com/9167485/87253609-6f6bd180-c431-11ea-8dab-31a9f1b9c22f.png)
There is no space between `mu4e` and `time`, which I believe is cosmetically unpleasant. 

The way I solved the problem is to redefine `mu4e-context-label` to
```emacs-lisp
(defun mu4e-context-label ()
  "Propertized string with the current context name, or \"\" if
  there is none."
  (if (mu4e-context-current)
      (concat "[" (propertize (mu4e~quote-for-modeline
                               (mu4e-context-name (mu4e-context-current)))
                              'face 'mu4e-context-face) "] ") ""))
```
That is, I added a space after the ']'. I wonder, why isn't this the default behavior?

**Comment by djcb** [comment]
Well, I think it's fine as it is :) Put feel free to add it in your local version of course.
