### ISSUE TITLE
docs broken link

### ISSUE THREAD

**Issue by pmatos** [djcb/mu#1760]
There's a broken link here:
https://www.djcbsoftware.nl/code/mu/mu4e/Signing-and-encrypting.html

The link https://www.djcbsoftware.nl/code/mu/emacs-mime/Composing.html#Composing from `(See (emacs-mime)Composing)` is broken.

**Comment by djcb** [comment]
The link works in emacs/info (when you have the docs for emacs-mime installed), but the texinfo->html generator translates that into a non-existing link. 

Not much we can do about that without worsening the emacs/info docs, so I'm going to have to close this as "WONTFIX". Sorry!
