### ISSUE TITLE
mu4e: Strange behaviour when searching by date

### ISSUE THREAD

**Issue by joukeHijlkema** [djcb/mu#1762]
## Expected or desired behavior
When using mu to find emails on a given date everything works fine. 

mu find date:20200507 finds all my 28 emails from the 7th of mai. 
I would expect the same behaviour using mu4e in emacs.

## Actual behavior

In emacs mu4e headers-view, hitting s followed by date:20200507 gives me 292 hits with dates ranging from 15/07/2020 to 28/10/2019
date:20200507..20200507 gives the same result.

## Steps to reproduce

see above

## Versions of mu, mu4e/emacs, operating system etc.

git describe --tags
1.4.7-119-g6cea9fcd
git rev-parse HEAD
6cea9fcd711a2ef33623e9f3cb41b0ff98323c79

I did a make distclean, make and make install

mu --version
mu (mail indexer/searcher) version 1.5.5
Copyright (C) 2008-2020 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

in emacs:
C-h v mu4e-installation-path gives "/usr/local/share/emacs/site-lisp/mu4e"
ls -alh /usr/local/share/emacs/site-lisp/mu4e gives all files of the correct date
C-h v mu4e-mu-version gives 1.5.5

GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)

**Comment by djcb** [comment]
See: https://www.djcbsoftware.nl/code/mu/mu4e/General.html#Results-from-mu-and-mu4e-differ-_002d-why_003f

**Comment by joukeHijlkema** [comment]
You are right ! Hitting W fixes the thing. Thank you.
