### ISSUE TITLE
Slow loading of messages

### ISSUE THREAD

**Issue by maneum1** [djcb/mu#1763]
## Expected or desired behavior

Opening messages quickly, lest say at most in a few seconds.

## Actual behavior

Many of my messages are taking 20 seconds and more to load in mu4e.
The messages with issues are html formatted newsletter emails.

For bug-reports, if applicable, include error messages, emacs stack
traces etc. Try to be as specific as possible - when do you see this
happening? Does it happen always?  Sometimes? How often?

## Steps to reproduce

What is a good way to send you one of the problematic messages?

## Versions of mu, mu4e/emacs, operating system etc.

I'm using 
Arch linux
MU 1.4.10
emacs 26.3
isync 1.3.1

## Any other detail

Here my mu4e-config.el
(require 'mu4e)

(setq mail-user-agent 'mu4e-user-agent)

(setq
  mu4e-sent-folder "/mlapt/martin/Sent"
  mu4e-drafts-folder "/mlapt/martin/Drafts"
  mu4e-trash-folder "/mlapt/martin/Trash")

(setq   mu4e-maildir-shortcuts
    '((:maildir "/mlapt/martin/Archives" :key ?a)
      (:maildir "/mlapt/martin/Inbox"    :key ?i)
      (:maildir "/mlapt/martin/Drafts"   :key ?d)
      (:maildir "/mlapt/martin/Junk"     :key ?j)
      (:maildir "/mlapt/martin/Sent"     :key ?s)
      ))

(setq mu4e-headers-fields
         '( (:date          .  25)    ;; alternatively, use :human-date
            (:flags         .   6)
            (:from          .  22)
            (:subject       .  nil))) ;; alternatively, use :thread-subject

(setq mu4e-get-mail-command "mbsync -a")
(setq mu4e-change-filenames-when-moving t)
(setq mu4e-attachment-dir "~/Downloads/EmailAttachments")

(setq mu4e-compose-reply-to-address "martin@example.com"
      user-mail-address "martin@example.com"
      user-full-name  "Martin")
(setq mu4e-compose-signature
   "Martin")

;; enable inline images
;;(setq mu4e-view-show-images nil)
;; use imagemagick, if available
;;(when (fboundp 'imagemagick-register-types)
;;  (imagemagick-register-types))

(setq mu4e-compose-in-new-frame t)
(add-hook 'mu4e-view-mode-hook #'visual-line-mode)
(setq mu4e-view-use-gnus nil)

(require 'smtpmail)
(setq
   message-send-mail-function 'smtpmail-send-it
   smtpmail-default-smtp-server "smtp.example.com"
   smtpmail-smtp-server "smtp.example.com"
   smtpmail-local-domain "example.com"
   smtpmail-smtp-service 587
   )

(setq message-kill-buffer-on-exit t)

(require 'org-mu4e)
(setq org-mu4e-convert-to-html t)

**Comment by djcb** [comment]
Can you attach message where this happens (ie., the raw message file that lives in the maildir)?

**Comment by maneum1** [comment]
This is one of those troublesome emails.

[realtor.com.example.txt](https://github.com/djcb/mu/files/4978189/realtor.com.example.txt)

**Comment by djcb** [comment]
In my case this message is slow (maybe 3sec?) probably due to the `shr` rendering, sadly not _so_ much that mu4e can do about that. Perhaps you have a slower machine, but I guess 20sec is not explained by that.

Does e.g.
```
(setq shr-inhibit-images t
      shr-blocked-images ".*")
```
help?

**Comment by maneum1** [comment]
I added those settings to my mu4e configuration but they don't help. Load times are still really bad.
I had it once when I extracted that email for you from my maildir, that when I came back to emacs the messages loaded quickly. But never was able to recreate that effect again. At that time the load times were as you said, about 3 seconds.
I'm using an Lenovo Ideapad 320. Which is not a rocket of a machine but handles typically quite well unless I open to many applications.

**Comment by djcb** [comment]
Does 
```
(setq mu4e-view-use-gnus t)
```
help?

**Comment by jfmc** [comment]
I am also having some troubles with very slow loading of messages. Some are large HTML mails from gitlab diffs. mu4e-view-use-gnus didn't help at all (I'd prefer some kind `[Long message, click here to view the rest of the message]`). 

I also experienced other random slowdowns, perhaps due to mu index running on background?

I'm running emacs 27.1 on macOS Big Sur, Apple M1.

**Comment by djcb** [comment]
The typical reasons for slowness are:
1) perhaps there's an indexing operation ongoing (this would happen _sometimes_ for _any_ message)
2) perhaps there's something special about the message (please attach an example message, anonymized as needed)
3) does it involve signed message (e.g. S/MIME)? If so, best double-check your crypto settings.

**Comment by jfmc** [comment]
> The typical reasons for slowness are:
> 
> 1. perhaps there's an indexing operation ongoing (this would happen _sometimes_ for _any_ message)
> 2. perhaps there's something special about the message (please attach an example message, anonymized as needed)
> 3. does it involve signed message (e.g. S/MIME)? If so, best double-check your crypto settings.

In my case it could be a combination of '1' and '2'. Do you think that something like these would help?

 - For large HTML (where something on the emacs side is the bottleneck) I'd prefer a 'click here to see the full message'.
 - Do not block during indexing (allow read operations while indexing is running). It seems that xapian db allows some kind of concurrent read only access (https://getting-started-with-xapian.readthedocs.io/en/latest/concepts/indexing/databases.html#concurrent-access)
 - Speedup indexing? I have a small inbox and around 400000 emails in archived folders with the `.noupdate` mark. It needs 10 secs everytime.
 
Overall I'm extremely happy with mu4e + mbsync but these random 10 seconds blocks are very annoying.

**Comment by djcb** [comment]
10s is a long time to scan a few folders, best to diagnose using the command-line mu, and perhaps some profiling tool. Don't think there's anything I can do on the mu side now, but feel free to (re)open if you have some specific profiling results (`perf`) or equivalent. Thanks!
