### ISSUE TITLE
Mu4e headers error: unexpected character '.

### ISSUE THREAD

**Issue by cbaines** [djcb/mu#1766]
## Expected or desired behavior

Can view a list of messages in Emacs.

## Actual behavior

No messages, just an error:

```
mu4e-error-handler: Error 8: 116: unexpected character '. (line was:'(find :query "(flag:unread OR flag:flagged) AND NOT flag:trashed" :threads t :sortfield :date :descending t :maxnum ...)')
```

## Steps to reproduce

Viewing messages fails consistently with this error.

## Versions of mu, mu4e/emacs, operating system etc.

1.4.10 from GNU Guix.

## Any other detail

Since I don't know how to debug things in Emacs, or really read Emacs lisp, this is the output from stracing the mu server process. My interpretation of this is that something is going wrong between emacs and the mu server, either the `...` shouldn't be being sent, or the server should support that value.

```
read(0, "(find :query \"flag:unread AND NOT flag:trashed\" :threads t :sortfield :date :descending t :maxnum ...)\n", 4096) = 103
write(2, ";; error: ", 10)              = 10
write(2, "98: unexpected character '.", 27) = 27
write(2, "\n", 1)                       = 1
write(1, "\376a8\377", 4)               = 4
write(1, "(:error 8 :message \"98: unexpected character '. (line was:'(find :query \\\"flag:unread AND NOT flag:trashed\\\" :threads t :sortfield :date :descending t :maxnum ...)')\")", 167) = 167
write(1, "\n", 1)                       = 1
write(1, ";; mu> ", 7)                  = 7
```

**Comment by djcb** [comment]
Hmm... what value do you have for `print-length`?

**Comment by cbaines** [comment]
M-x describe-variable print-length says:
```
print-length is a variable defined in ‘C source code’.
Its value is 10
```

**Comment by djcb** [comment]
Thanks - that explains. mu 1.4.12 has a fix for this.

**Comment by cbaines** [comment]
> Thanks - that explains. mu 1.4.12 has a fix for this.

Wonderful, thanks @djcb :1st_place_medal:
