### ISSUE TITLE
bbdb/gnus-view: No buffer named *Article* error

### ISSUE THREAD

**Issue by jagrg** [djcb/mu#1767]
## Expected or desired behavior

Open messages without errors when `mu4e-view-use-gnus` is set to t.

## Actual behavior

I'm trying the Gnus' article view and I get the following error after I

1. Restart Emacs
2. press M-x mu4e
3. go to any message in the headers buffer and press RET (after the first RET I get no more errors).

```
Debugger entered--Lisp error: (error "No buffer named *Article*")
  bbdb-mua-update-records(nil bbdb-select-message)
  bbdb-mua-auto-update()
  run-hooks(change-major-mode-after-body-hook gnus-article-mode-hook mu4e-view-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook gnus-article-mode-hook mu4e-view-mode-hook))
  run-mode-hooks(mu4e-view-mode-hook)
  mu4e-view-mode()
  mu4e~view-gnus((:docid 4695 :subject ...))
```

The issue is with BBDB. For example, using the configuration described [in the manual](https://www.djcbsoftware.nl/code/mu/mu4e/BBDB.html#BBDB) the line that causes the error is:
```
(setq mu4e-view-mode-hook 'bbdb-mua-auto-update)
```
For some reason `mu4e~view-buffer-name` changes to `*Article*`, so maybe that's the problem.

## Steps to reproduce

See above.

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 1.5.5
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian
Ubuntu 20.04

**Comment by jagrg** [comment]
One way around the error is with:

```
(with-eval-after-load "bbdb-mua"
  (setq mu4e~view-buffer-name "*mu4e-view*"))
```

but why are we changing `mu4e~view-buffer-name` in `mu4e~view-define-mode` to `gnus-article-buffer`?

**Comment by djcb** [comment]
Yeah, seems bbdb expects something that's not there. For now I would recommend simply not setting that hook. 
Mu4e reuses some of the gnus-functionality, but certainly not everything, so that's likely why bbdb gets.

**Comment by djcb** [comment]
Latest from `git` has some changes that might help... can you try?

**Comment by jagrg** [comment]
Yes, it's working now, thanks.

**Comment by felipeAH** [comment]
Hi,

i've just installed mu{,4e} 1.10.7 and hit this bug.

same culprit

 (setq mu4e-view-mode-hook 'bbdb-mua-auto-update)

Anyone?

Thanx.

**Comment by djcb** [comment]
@felipeAH: perhaps try with 1.10.8? It  has a change that may help.
