### ISSUE TITLE
Unable to sync read status to gmail after read and trash

### ISSUE THREAD

**Issue by tshu-w** [djcb/mu#1769]
## Expected or desired behavior

When you receive a new Gmail message, read it, trash it and `mu4e-update-mail-and-index`, this message should be mark as read on the remote.

## Actual behavior

After the above steps, the message is moved to the trash, but still unread. 

## Steps to reproduce

1. When a new email is received:
```
~/.mail/gmail/inbox/new
-rw-------  1 wangtianshu  staff   6.0K Jul 26 14:57 1595746679.50211_1.MacBook Pro,U=146:2,
```

2. read it:
```
~/.mail/gmail/inbox/cur
-rw-------  1 wangtianshu  staff   6.0K Jul 26 14:57 1595746679.50211_1.MacBook Pro,U=146:2,S
```

3. trash it:
```
~/.mail/gmail/trash/cur
-rw-------  1 wangtianshu  staff   6.0K Jul 26 14:57 1595746786.36059a3567727868.MacBook Pro:2,S
```

<img width="1038" alt="Screen Shot 2020-07-26 at 3 26 47 PM" src="https://user-images.githubusercontent.com/13161779/88473900-76780100-cf54-11ea-9434-3936ef9d0242.png">

4. `mu4e-update-mail-and-index` and open https://mail.google.com

This mail was trashed but not marked as read:

<img width="1617" alt="Screen Shot 2020-07-26 at 3 01 28 PM" src="https://user-images.githubusercontent.com/13161779/88473857-24cf7680-cf54-11ea-8b42-7c1eb5665c5f.png">

5. `mu4e-update-mail-and-index` again:

<img width="1036" alt="Screen Shot 2020-07-26 at 3 15 14 PM" src="https://user-images.githubusercontent.com/13161779/88473862-2b5dee00-cf54-11ea-86d5-2f5f921c7c60.png">

6. If I read this mail again and `mu4e-update-mail-and-index`, It was marked as read successfully.

```
~/.mail/gmail/trash/cur
-rw-------  1 wangtianshu  staff   6.0K Jul 26 14:57 1595746786.36059a3567727868.MacBook Pro,U=320:2,S
```

## Versions of mu, mu4e/emacs, operating system, etc.

mu 1.4.10
macOS 10.15.6
GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101))
 of 2020-06-30

## Any other detail
maybe related config:
```

  (setf (alist-get 'trash mu4e-marks)
        '(:char ("d" . "▼")
                :prompt "dtrash"
                :dyn-target (lambda (target msg) (mu4e-get-trash-folder msg))
                ;; Here's the main difference to the regular trash mark, no +T
                ;; before -N so the message is not marked as IMAP-deleted:
                :action (lambda (docid msg target)
                          (mu4e~proc-move docid
                                          (mu4e~mark-check-target target) "-N"))))
```
**If I only read it and `mu4e-update-mail-and-index` or trash it and `mu4e-update-mail-and-index`, mail will be marked as read successfully. I am using mbsync.** If you need more info, please me let me know.

**Comment by tshu-w** [comment]
By the way, the number of mail seen wrong.
<img width="364" alt="Screen Shot 2020-07-26 at 9 59 30 PM" src="https://user-images.githubusercontent.com/13161779/88480928-6596b200-cf8b-11ea-8a63-8efc8ff60c06.png">

**Comment by djcb** [comment]
Thanks for the detailed report. It seems mu4e sets the flags as expected, but then `mbsync` & gmail disagree? Not quite sure what mu4e can do about this.

As for the number of mails: by default "Unread" means "flag:unread AND NOT flag:trashed"; furthermore, For speed reasons, the counts do not exclude messages that no longer exist in the file-system, nor does it exclude duplicate messages.

**Comment by tshu-w** [comment]
> Thanks for the detailed report. It seems mu4e sets the flags as expected, but then `mbsync` & gmail disagree? Not quite sure what mu4e can do about this.

The strange thing is that if I only trash or read there is no such problem.

What the meaning of `U={number}` in the filename? It seems that the first time I trash it, the filename didn't have this field.

I will add +T back to see whether it help.

**Comment by djcb** [comment]
The U=... is added by mbsync (I think) for its internal bookkeeping. It's not used by mu.

You can also check the variable `mu4e-change-filenames-when-moving`, and see if it helps.

**Comment by tshu-w** [comment]
@djcb Thx for your reply. In fact, I have already set `mu4e-change-filenames-when-moving` to `t`. If it's nil, trashed mail will be moved to All Mail.
