### ISSUE TITLE
Adding text properties to header fields

### ISSUE THREAD

**Issue by jagrg** [djcb/mu#1771]
## Expected or desired behavior

I would like to change the look of header fields conditionally. For example, make mailing list X blue and mailing list Y green etc.

## Actual behavior

I used to be able to do this using [this solution](https://emacs.stackexchange.com/questions/26913/coloring-mu4e-headers-based-on-title-content), but the `mu4e~headers-line-handler-functions` variable was removed in https://github.com/djcb/mu/commit/3715bb0c5ee53c22b2940bd4d80f313df4e659ae. IIUC we should still be able to achieve this using the `mu4e-headers-field-properties-function` variable:

> Documentation:
> Function that specifies custom text properties for a header field.
> 
> The function takes a message-plist and a field-id, and is expected to
> return either nil or a property-list with text-properties to apply.
> 
> This allows for turning the list of message headers into an angry
> fruit salad. Note that this function is called for each relevant
> field of each message and thus should you should be careful to
> avoid slowdowns.

but I think there's code missing to make this work. An example would be nice too.

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 1.5.5
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian
Ubuntu 20.04

## Any other detail

I'm using the Gnus' article view.

**Comment by averter** [comment]
Possibly related/relevant thread https://github.com/djcb/mu/issues/1355

**Comment by rougier** [comment]
I've been using the same hack to insert SVG tags into the subject line (https://i.redd.it/n7goldmj3q161.png) and I would be interested in having a replacement method.

**Comment by djcb** [comment]
Yeah, closing this one in favor #1355 which is about the same.
