### ISSUE TITLE
Switching context on a message draft

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1772]
## Expected or desired behavior

When I am editing a message, if I switch context between accounts I expect the `From:` field to be updated accordingly and the message draft to be moved to the correct folder associated with the context.

## Actual behavior

The `From:` field is not updated and the message stays in the draft folder of the original context.

## Steps to reproduce

- Have multiple contexts in `mu4e-contexts`
- Create a new draft
- Call `mu4e-switch-context` and switch to a different context
- The context is switched (as evidenced by the modeline)
- The message stays in the original context draft folder and the `From` field is not updated.

## Versions of mu, mu4e/emacs, operating system etc.
Emacs: 26.3
mu: 1.5.5

**Comment by haji-ali** [comment]
Implemented in b094da8cd48f6489b4b599ed7427200c08f70d84

**Comment by djcb** [comment]
Thanks! Will be available in 1.6 (starting from 1.5.11, or current git master)
