### ISSUE TITLE
View actions - Move message

### ISSUE THREAD

**Issue by edkedk99** [djcb/mu#1773]
## Expected or desired behavior

I would like to create a function activated  by a view action like this:

`
(add-to-list 'mu4e-view-actions
	     '("hMove to folder a" . mu4e-move-msg-a) t)
`

Where *mu4e-move-msg-a* move the message I am viewing to folder *a*. I can do it for a *mu4e-header-action* using the function *(mu4e-mark-at-point 'move "/INBOX.a")*

## Actual behavior

I get the following error in the buffer line : [mu4e] Not in headers-mode

## Steps to reproduce

Please tell me if my elisp is necessary

## Versions of mu, mu4e/emacs, operating system etc.

- mu: 1.1.4-1
- emacs: 26.3-2
- OS: Manjaro (Recently updated)

## Any other detail

I want to be able to activate the same action regardless if I am on header or view screen, but now I can do it only for the action when I am seeing the headers. I have tried all function I could find with no success

**Comment by djcb** [comment]
You can use `mu4e-mark-at-point`, or (easier) use some keyboard macros.

**Comment by edkedk99** [comment]
Djcb,

Thank for your tip regarding keyboard macros, I will try. And since I have got a chance to talk to you, congratulations and thank you for the amazing software you developed
