### ISSUE TITLE
Subject not showing correctly

### ISSUE THREAD

**Issue by vnckppl** [djcb/mu#1774]
## Expected or desired behavior
I expect the email subject line under Subject

Please describe the behavior you expected / want
For (to me) random messages, mu4e shows

`└>=`

The subject line does show correctly in mu in the terminal for these messages.

See also this screenshot:
![mu4e_subject_lines](https://user-images.githubusercontent.com/15114746/88744046-7cf8ab00-d103-11ea-83c3-41328bb7f5b9.jpg)

## Steps to reproduce
My header settings for mu4e are:
```
(add-hook 'mu4e-headers-mode-hook
          (defun my/mu4e-change-headers ()
            (interactive)
            (setq mu4e-headers-fields
                  `((:human-date . 10) 
                    (:flags . 6)
                    (:from . 22)
                    (:thread-subject . 20)
                    (:size . 7)))))
```

## Versions of mu, mu4e/emacs, operating system etc.
mu version 1.4.12
emacs version 26.3
osx Mojave 10.14.6

**Comment by averter** [comment]
Does this do the trick?

````elisp
(add-hook 'mu4e-headers-mode-hook
          (defun my/mu4e-change-headers ()
            (interactive)
            (setq mu4e-headers-fields
                  `((:human-date . 10) 
                    (:flags . 6)
                    (:from . 22)
                    (:subject)
                    (:size . 7)))))
````

**Comment by vnckppl** [comment]
Thanks! I think this fixed itself in the latest update of mu4e.

**Comment by djcb** [comment]
This is just a misunderstanding of display, admittedly, it can be a little confusing.

Anyway, things looks rather different now (the thread-subject support changed quite a bit). Closing.
