### ISSUE TITLE
feature request: ordering of available folders when moving messages in multi-account setup

### ISSUE THREAD

**Issue by vnckppl** [djcb/mu#1775]
I have three mailboxes setup. When I move messages around from my inbox to a custom folder of that mailbox, the list of available folders always follows alphabetical order. I would like to first show folders for the mailbox that I am moving the message from.

Example where there are 2 mailboxes with certain subfolders:
maildir/account_A/folder1
maildir/account_A/folder2
maildir/account_B/folder1
maildir/account_B/folder2

If you move a message from inbox account_B, the order of available folders is { account_A/folder1 | account_A/folder2 | account_B/folder1 | account_B/folder2 }

I think in this case, it would make more sense to first display the folders of account_B and then the folders of all other accounts.

**Comment by djcb** [comment]
It would be complicated to get that working, so this won't be added in the foreseeable future. Sorry!
