### ISSUE TITLE
Read messages show up as unread when moving Maildir from OSX to Ubuntu

### ISSUE THREAD

**Issue by friskgit** [djcb/mu#1778]
## Expected or desired behavior

Read/Unread status of messages in the file system should be preserved when migrating messages to new computer.

## Actual behavior

All prior messages are marked unread.

Unread (old) messages that are opened in the new context have a :2,S appended to the existing 2,S:

1588316016.M38202P19056Q2R95d46906637f6787.hostname2,S:2,S

## Steps to reproduce

Maildir from HFS+ formatted harddrive transferred to a LVM2 formatted drive in Linux.

## Versions of mu, mu4e/emacs, operating system etc.

mu/mu4e (mail indexer/searcher) version 1.2.0
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian

**Comment by djcb** [comment]
As discussed on the mailding list, the problem was in the copying, which didn't preserve the ':'.
