### ISSUE TITLE
html rendering issue

### ISSUE THREAD

**Issue by vnckppl** [djcb/mu#1780]
## Expected or desired behavior
html will render without extra whitespace

## Actual behavior
When I open an HTML email in mu4e-view, the email is not nicely filled out over the display. Instead, extra lines are showing. When I make the window wider, the email is displayed correctly. However, when I close and reopen mu4e in the same window (same width), the extra whitespace is there again.

Example:
I open an HTML email. It is displaying like this:
<img width="888" alt="Screen Shot 2020-08-06 at 10 47 35" src="https://user-images.githubusercontent.com/15114746/89559432-e5feb380-d7d2-11ea-8924-287c24be8845.png">

When I increase the window width, the email shows normally:
<img width="1118" alt="Screen Shot 2020-08-06 at 10 48 02" src="https://user-images.githubusercontent.com/15114746/89559570-12b2cb00-d7d3-11ea-9404-b59e27c66735.png">

When I close mu4e, and reduce the window width to make it smaller than it was initially, the email will show the additional white space again:
<img width="490" alt="Screen Shot 2020-08-06 at 10 48 29" src="https://user-images.githubusercontent.com/15114746/89559674-3e35b580-d7d3-11ea-972c-6974e246a803.png">

When I increase the window-with again, but to a width that is still smaller than it was in the first screenshot, the email displays correctly again:
<img width="535" alt="Screen Shot 2020-08-06 at 10 48 42" src="https://user-images.githubusercontent.com/15114746/89559798-632a2880-d7d3-11ea-976c-663895efb761.png">

Why is my email not rendering correctly immediately? The issue does not seem to be related to the width of the window.

## Versions of mu, mu4e/emacs, operating system etc.
mu version 1.4.12
emacs version 26.3
MacOS Mojave 10.14.6

## Any other detail
I use the default html2text renderer: mu4e-shr2text

**Comment by Chris00** [comment]
With the Gnus viewer (`(setq mu4e-view-use-gnus t)`), I have
```elisp
(define-advice mm-shr (:around (oldfn &rest handle) delete-trailing-whitespace)
  "Delete unecessary whitespace in Gnus article buffer."
  (if (derived-mode-p 'gnus-article-mode)
      (save-restriction
        (narrow-to-region (point) (point))
        (apply oldfn handle)
        (delete-trailing-whitespace)
        ;;(whitespace-cleanup)
        ;; Several consecutive blank lines do not improve readability
        (goto-char 1)
        (while (re-search-forward "\n\\{3,\\}" nil t)
          (replace-match "\n\n")))
    (apply oldfn handle)))
```
Hope it helps.

**Comment by vnckppl** [comment]
It does. Bedankt!

**Comment by Chris00** [comment]
@djcb Would this be an interesting addition to `mu4e-contrib.el`?
