### ISSUE TITLE
Multipart mime messages leak buffers when mu4e-view-use-gnus is set to t.

### ISSUE THREAD

**Issue by hdasch** [djcb/mu#1781]
## Expected or desired behavior

Temporary buffers should be deleted after use.

## Actual behavior

After viewing html mail, I find an accumulation of buffers whose name is of the form " \*mm\*-nnnnn".  The leading space hides the buffers from switch buffer.  But running M-x ibuffer RET C-u g, displays all buffers.  When I first noticed this I had about a 256 MB in old temporary buffers.

## Steps to reproduce

(setq mu4e-view-use-gnus t)
Open an html mail message.
Quit the view
Look for \*mm\*-nnnn buffers in the buffer list.

I see three buffers per article, but that's probably just a reflection of the number of multiparts in the message.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e: 1.4.1
emacs: 27.1-rc2
os: Arch linux, kernel 5.7.2

## Any other detail

This doesn't happen with reading mail via gnus.

I notice that gnus-art.el keeps a list of mime section "handles" generated by `mm-dissect-buffer`.  These are accumulated in the variable `gnus-article-mime-handlers`.  These are later passed to `mm-destroy-parts` by `gnus-summary-exit`.  That is where these buffers are deleted in gnus.

I don't see anything like this in mu4e.

I can dig deeper.  But I'm surprised that this hasn't been reported before; at least as far as I've been able to search.

Do I have something misconfigured?  Or is this a real leak?

**Comment by djcb** [comment]
It was a real leak indeed, good catch! I've pushed a fix to the release/1.4.x branch, this will be part of the upcoming 1.4.13 release.

**Comment by hdasch** [comment]
I've tested f18044f5 and no longer see the leak.

Many thanks.
