### ISSUE TITLE
mu find doesn't return results if "=" character in matched string

### ISSUE THREAD

**Issue by markk** [djcb/mu#1786]
Searching for a string which contains "=", mu doesn't return any results.
 
```
$ mu find '/payment_id/' --exec="grep payment_id"
orders?payment_id=3D2428441884&amp;sig=3Ddd02c4eb4fad0f903898afd60=
$ mu find '/payment_id=/' --exec="grep payment_id"
error: no matches for search expression (4)
$ mu find '/payment_id\x3d/' --exec="grep payment_id"
error: no matches for search expression (4)
$ mu find '/payment_id./' --exec="grep payment_id"
error: no matches for search expression (4)
$ mu find =
error: no matches for search expression (4)
```

## Versions of mu, mu4e/emacs, operating system etc.

maildir-utils-1.4.10-1.fc32.x86_64
emacs-27.1-rc1.1.fc32.x86_64

**Comment by djcb** [comment]
This is a bit of a limitation of the way Xapian text-indexing works - you can't really find arbitrary phrases with non-word characters. mu tries to work around that a bit, but we can't really fix it (not easily at least)
