### ISSUE TITLE
mu4e does not display some emails

### ISSUE THREAD

**Issue by psamim** [djcb/mu#1787]
## Expected or desired behavior

When I search, or view a maildir, to display all messages the same as `mu find`.

## Actual behavior

I search for a query in mu4e, it shows nothing. I search the same in command line using `mu find` it displays an email.

## Steps to reproduce

Same as above.

## Versions of mu, mu4e/emacs, operating system etc.
Emacs 27.1
Archlinux
Doom Emacs Distribution 
mu4e version 1.4.13

**Comment by psamim** [comment]
The same exact email is not displayed anywhere, in any search or maildir.

**Comment by djcb** [comment]
This is usually because of the different settings for duplicate messages. See the manual (FAQ) for some details.
