### ISSUE TITLE
Replying from plus addresses

### ISSUE THREAD

**Issue by daphniz** [djcb/mu#1788]
When I give my address to companies, I usually given them `user+<scramble(company name)>@server`.  When they send me emails, and I reply, I would like the reply to be sent from that address (the to-address of the original message) and not my plain address.  Is there an easy way to do this automatically?

**Comment by djcb** [comment]
I guess the easiest might be writing a compose-hook, see: https://www.djcbsoftware.nl/code/mu/mu4e/Compose-hooks.html#Compose-hook

Whether that's "easy", I don't really know :-)
