### ISSUE TITLE
Error when starting mu : glass revision file

### ISSUE THREAD

**Issue by davd33** [djcb/mu#1789]
## Expected or desired behavior

Running `mu index` should index my mails.

## Actual behavior

I get the following error when running `mu index`:
```
error: failed to open store @ /home/pi/.cache/mu/xapian: /home/pi/.cache/mu/xapian/iamglass: Failed to open glass revision file for reading
```

It always happens. 

## Steps to reproduce

Just run `mu index` or `mu server`

## Versions of mu, mu4e/emacs, operating system etc.

Raspberry pi OS Buster
Emacs 26.1

mu version (built from source):
```
commit d1b0938187552fea70fc0cb4dff212545cfb0428 (HEAD -> master, origin/master, origin/HEAD)
Author: Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>
Date:   Sat Aug 15 11:04:36 2020 +0300

    mu-cmd-cfind: include <array>
```

**Comment by djcb** [comment]
Hmm...  there error comes from somewhere deep inside the Xapian database library we're using. Do you know what Xapian version is on your Rasperry Pi? Some other things you could check is whether the file in the error-message actually exist (and its permissions). 

Then, is there anything special about the `.cache` directory, i.e., is it not a tmpfs? You could try using another place (the `--mupath` parameter to `mu init`).

**Comment by davd33** [comment]
I'm using Xapian version:
```
pi@raspberrypi:~ $ xapian-config --version
xapian-config - xapian-core 1.4.11
```

Changing the mu home path did the trick! (to be documented I guess) See following commands:
```
mkdir .mu-cache
mu init --muhome .mu-cache/
mu index --muhome .mu-cache/
```

Thank you for you help! :)
