### ISSUE TITLE
Unable to save attachments with "X" when using mu4e-view-use-gnus

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1790]
## Expected or desired behavior

Being able to use "X" aka `mu4e-view-save-attachment-multi`.

Please describe the behavior you expected / want

## Actual behavior

I have now either two unrelated attached parts (my mail are all encrypted) or the error 
`mu4e-error: [mu4e] Not a valid attachment`.

Using "o" aka `gnus-mime-save-part` save the expected attachment.

## Versions of mu, mu4e/emacs, operating system etc.

I use last Mu from Git and emacs-27.1.

More infos as soon as possible.

Thanks.

**Comment by averter** [comment]
I've had to create a key binding to get this to work. I did it for `mu4e-view-save-attachment`, the alias of `mu4e-view-save-attachment-multi`, though: the end result is the same. Probably at some point a key binding will be implemented into gnus.

**Comment by thierryvolpiatto** [comment]
Averter <notifications@github.com> writes:

> I've had to create a key binding to get this to work. I did it for
> mu4e-view-save-attachment, the alias of
> mu4e-view-save-attachment-multi,

It is already bound to "X". It works only in simple cases when there is
no encrypted mime parts, otherwise it propose to save only the encrypted
parts which is not what is expected (all my mails are encrypted with my
own pub key which is on the mail server).

> though: the end result is the same. Probably at some point a key
> binding will be implemented into gnus.

It is implemented, it is `gnus-mime-save-part` bound to "o" but you have
to put your cursor on the mime part button, it is implemented as a
button command IIUC.


-- 
Thierry

**Comment by averter** [comment]
I've never been able to use "X" to save attachments; maybe there is some trick to it? "o" did work, but as you said, only when the cursor is over the mime part button and it only saves a single attachment at a time (for me at least). These commands seem to be somewhat limited.

**Comment by thierryvolpiatto** [comment]
Averter <notifications@github.com> writes:

> I've never been able to use "X" to save attachments; maybe there is
> some trick to it? "o" did work, but as you said, only when the cursor
> is over the mime part button and it only saves a single attachment at
> a time (for me at least). These commands seem to be somewhat limited.

Yes, "X" as well is not the best we can have, it propose to save a range
of attachements (when it is working, that is outside of gnus view) and
then prompt user for destination with a read-file-name.  Instead of a
range we could have a completing-read listing all attachments and the
destination should be predefined by user e.g. "~/download" (I think we
already have this), thus the expected value returned by the
completing-read may be a list (by marking candidates), in this case the
list of attachments would be saved at once (Only helm as backend for CR
allow this AFAIK). @djcb WDYT?

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I finally use this:

```elisp
(defun tv/mu4e-save-parts ()
  (interactive)
  (let ((handles '())
        (files '())
        (helm-comp-read-use-marked t)
        (compfn (if helm-mode
                    #'completing-read
                  ;; Fallback to `completing-read-multiple' with poor
                  ;; completion systems.
                  #'completing-read-multiple)))
    (save-excursion
      (goto-char (point-min))
      (while (not (eobp))
        (let ((handle (get-text-property (point) 'gnus-data)))
          (when handle
            (let ((fname (cdr (assoc 'filename (assoc "attachment" (cdr handle))))))
              (when fname
                (push `(,fname . ,handle) handles)
                (push fname files)))))
        (forward-line 1)))
    (setq files (funcall compfn "Save part(s): " files))
    (cl-loop for (f . h) in handles
             when (member f files)
             do (mm-save-part-to-file h (expand-file-name f mu4e-attachment-dir)))))
```
I will come back later to adapt it (if needed, let me know) for mu4e with a PR.
