### ISSUE TITLE
Feature request: flag for calendar invites in mu4e header view

### ISSUE THREAD

**Issue by andersjohansson** [djcb/mu#1792]
## Expected or desired behavior
With the preliminary support for responding to calendar invites, it would be nice if it was possible to see which messages were invites already in the header view. Ideally it could just be one of a messages flags.

## Actual behavior
Nothing indicates that a message contains an invite in the headers view. This is only seen when opening the message. Actually, it 

## Steps to reproduce
Receive a message with a calendar invite (an attached vcs-file with mime-type "text/calendar"). Look at headers view and see no indication of this :slightly_frowning_face: 

## Versions of mu, mu4e/emacs, operating system etc.
Mu/mu4e, built from git: 1.4.7.135.gd1b09381-1
Emacs built from git: 28.0.50.142294-1

## Any other detail

I actually tried to implement a custom header column for this:
```emacs-lisp
(add-to-list 'mu4e-header-info-custom
             '(:ajflags .
                        (:name "Flags"
                               :shortname "Flags"
                               :help "Flags"
                               :function aj/mu4e-headers-flags)))

(defun aj/mu4e-headers-flags (msg)
  (let* ((flags (mu4e-message-field msg :flags))
         (flags-str (mu4e~headers-flags-str flags))
         (cal (cl-loop for part in (mu4e-message-field msg :parts)
                       if (equal (plist-get part :mime-type) "text/calendar")
                       return "📅")))
    (propertize (concat flags-str cal)
                'help-echo (format "%S" flags))))
```
However. the `:parts` data for a message is only received after loading in the full message. So in my testing I got the calendar flag on all the messages I had viewed, but none else (every message here is a calendar invite):
![Screenshot of mu4e headers view with half functioning calendar flags](https://user-images.githubusercontent.com/846411/91458012-57d39580-e885-11ea-830f-11d9784d33cf.png)

I realized that this then has to be implemented in mu in some way, added as a new possible “content flag” (like `MU_FLAG_HAS_ATTACH`). Skimming the C sources for the attachment flag (`looks_like_attachment`) it doesn’t look to complicated to do something similar, but I’m not confident enough to just try it out now though, and I guess it is worth discussing if it is worthwhile first.

**Comment by djcb** [comment]
Implemented in 1.7.27.
