### ISSUE TITLE
Header Mode: Move Down is Laggy, but Move Up is not

### ISSUE THREAD

**Issue by YoshikiTakashima** [djcb/mu#1794]
Hello.

I am relatively new to EMACS, so if I am missing some information, please let me know.

## Expected or desired behavior

Moving down with arrow key should be responsive, not lagging.

## Actual behavior

In header mode, after moving down 10 lines or so with the down key, the cursor freezes, and after a few seconds, it appears way below where it was before. (i.e. laggy). If I jump around with the mouse, everything is fine. If I use EMACS' goto-line command and jump to some line, it is also fine. Also, the cursor is not laggy in any other mode than mu4e. **Most weirdly**, moving up is perfectly fine; down is not.

## Steps to reproduce
(Assuming you have a Raspberry Pi)
1. Download and install snap package mu: `sudo snap install maildir-utils`
2. Since the snap is on `1.4.10`, I install the corresponding version of `mu4e`
3. Initialize with the following code:
```
(package-initialize)
(add-to-list 'load-path "/usr/local/etc/mu4e/")
(require 'use-package)

(require 'mu4e)

;; use mu4e for e-mail in emacs
(setq mail-user-agent 'mu4e-user-agent)

(setq mu4e-drafts-folder "/[Gmail].Drafts")
(setq mu4e-sent-folder   "/[Gmail].Sent Mail")
(setq mu4e-trash-folder  "/[Gmail].Trash")

;; don't save message to Sent Messages, Gmail/IMAP takes care of this
(setq mu4e-sent-messages-behavior 'delete)

(setq mu4e-maildir-shortcuts
      '( (:maildir "/INBOX"              :key ?i)
	 (:maildir "/[Gmail].Sent Mail"  :key ?s)
	 (:maildir "/[Gmail].Trash"      :key ?t)
	 (:maildir "/[Gmail].All Mail"   :key ?a)
	 (:maildir "/[Gmail].Drafts"     :key ?d)
	 (:maildir "/[Gmail].Starred"    :key ?*)))

;; allow for updating mail using 'U' in the main view:
(setq mu4e-get-mail-command "/usr/bin/offlineimap"); adjust for your setup.

;; Speed up, especially for RPi
(setq
   mu4e-headers-show-thread nil
   mu4e-headers-include-related nil
   mu4e-index-cleanup nil
   mu4e-headers-results-limit 200)

(use-package smtpmail

  :config
  (setq message-send-mail-function 'smtpmail-send-it
	starttls-use-gnutls t
	smtpmail-starttls-credentials '(("smtp.gmail.com" 587 nil nil))
	smtpmail-auth-credentials
	'(("smtp.gmail.com" 587 "ytakashi@andrew.cmu.edu" nil))
	smtpmail-default-smtp-server "smtp.gmail.com"
	smtpmail-smtp-server "smtp.gmail.com"
	smtpmail-smtp-service 587)
  (setq message-kill-buffer-on-exit t))
```
I got the code from [https://www.djcbsoftware.nl/code/mu/mu4e/Gmail-configuration.html](https://www.djcbsoftware.nl/code/mu/mu4e/Gmail-configuration.html)
## Versions of mu, mu4e/emacs, operating system etc.
mu/mu4e: ver `1.4.10`, mu installed via snap packages to avoid compiling on a minicomputer.
EMACS: `26.1`
System: Raspbian GNU/Linux 10 (buster) armv7l
Hardware:Raspberry Pi 3 Model B Rev 1.2.

## Any other detail
I have two computers: a Raspberry Pi (Raspbian GNU/Linux 10 (buster) armv7l) and a relatively new Macbook Pro (OSX Catalina). I don't have this problem with the Macbook Pro, so I think it might be an issue with relatively low-powered computers. However, as far as I can tell from `htop`, I am not hitting any hardware issues with respect to CPU or RAM. I am yet to measure disk issues.

**Comment by YoshikiTakashima** [comment]
FYI: After using Mu4e for a few weeks, this issue feels not as significant as I thought it was.

So long as you are properly using the various features correctly (i.e. using `bu` instead of going to `INBOX` to read unread mail, searching instead of scrolling down to find mail, etc.), you are not likely to be bothered with this particular issue.

I suspect some of this is due to the hardware limitations, so this is likely low priority.

However, I am interested to know why it is slower going down than going up.

Thanks!

**Comment by djcb** [comment]
Could it be that the marking-as-read when moving down through unread mail? Or does the same happen when all the mail is read already?

**Comment by YoshikiTakashima** [comment]
It still happens when all the mail is read already. Also, even when it is not read, moving down with the arrow key does not make the headers "read" (as far as I can tell from the font).

**Comment by djcb** [comment]
Very weird! I can't reproduce this (and don't have a functioning Pi)... Apart from marking things as read, there's not special about what `mu4e` does that is different between up & down.

Perhaps you can do some profiling with the emacs profiler? https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html
