### ISSUE TITLE
[Feature request] support text-propertized marks

### ISSUE THREAD

**Issue by stardiviner** [djcb/mu#1795]
I propose a feature for mu4e, hope it can support display marks for headers with text-propertized stuff. So that user can display color and image for markers. It will make mu4e looks beautiful. WDYT?

**Comment by djcb** [comment]
You're not the first to ask; adding a lot of extra text-properties does tend to make the rendering visibly slower, so that needs to be solved first somehow.

**Comment by stardiviner** [comment]
Sounds reasonable. Thanks for reponse, @djcb .

**Comment by stardiviner** [comment]
I found the solution to display text-property icons without changing in mu4e.
Here is the solution:

```elisp
(setq mu4e-headers-unread-mark `("u" . ,(propertize
                                         "○"
                                         'face '(:foreground "red")
                                         'display (all-the-icons-faicon "diamond"))))
```

**Comment by stardiviner** [comment]
![image](https://user-images.githubusercontent.com/378699/103505159-8e08cd80-4e94-11eb-8efd-bb74038266af.png)

**Comment by alexmurray** [comment]
Have you thought of writing a separate package which encapsulates this (you could call it `mu4e-all-the-icons`)? Personally I think that would be an awesome addition.

**Comment by stardiviner** [comment]
Sure. I will write on. Thanks for suggestion.

**Comment by stardiviner** [comment]
Ok, I writed a small package now.

https://github.com/stardiviner/mu4e-marker-icons

**Comment by stardiviner** [comment]
@bovid-19 Yes, I deleted all GitHub repositories.
