### ISSUE TITLE
mu4e does not detect plain text version

### ISSUE THREAD

**Issue by achempion** [djcb/mu#1798]
## Expected or desired behavior

I expect to see plain text email version and toggle it with `h` key.

## Actual behavior

Only html version displayed.

## Steps to reproduce

Email example https://us-east-1.linodeobjects.com/achempion-com/share/postgres_weekly.txt.
Will be happy to provide any additional information.

## Versions of mu, mu4e/emacs, operating system etc.

macOS Catalina 10.15.4
GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2020-08-12
mu4e - mu for emacs version 1.4.12

## Any other detail

If I enable `(setq mu4e-view-use-gnus t)` I can see new line in headers section with a text 
```
Attachment: [2. text/plain]...
```
but can't really do anything about it because it seems `h` key isn't supported by this type of view.

**Comment by djcb** [comment]
You can click on the Attachment thing with RET or mouse, and you should be able to toggle html & text.

If you want to default to plain text, you can use something like the following in your config.

 ```
(with-eval-after-load "mm-decode"
  (add-to-list 'mm-discouraged-alternatives "text/html")
  (add-to-list 'mm-discouraged-alternatives "text/richtext"))
```

**Comment by husainaloos** [comment]
Why is this closed? Setting `  (setq mm-discouraged-alternatives '("text/html" "text/richtext"))` does in fact resolve it, but the typical user expects `(setq mu4e-view-prefer-html nil)` to do it automatically, unless that variable is on the path of deprecation or something.

**Comment by djcb** [comment]
We're slowly moving to the new gnus-based viewer indeed.
