### ISSUE TITLE
Mu says there is no option such as init?

### ISSUE THREAD

**Issue by simurgh9** [djcb/mu#1800]
I installed mu by doing `sudo apt install mu4e` and then ran `mu mkdir ~/Mail`. Then as [said in the manual](https://www.djcbsoftware.nl/code/mu/mu4e/Initializing-the-message-store.html#Initializing-the-message-store), I wanted to initialise a message store, like this:

```shell
mu init --maildir=~/Mail --my-address=jim@example.com --my-address=bob@example.com
```

However mu says:

```
see the mu manpage for commands, or 'mu script' for the scripts
mu: command or script not found (8)
```

`mu --version` returns `mu (mail indexer/searcher) version 1.2.0`.

**Comment by djcb** [comment]
The manual is for 1.4 and you are using 1.2. 

You can read the 1.2 manual locally; `info mu4e` (assuming you distro packaged the docs too). Or you can upgrade to 1.4.

**Comment by simurgh9** [comment]
How do I upgrade? I suppose the latest package at apt is what I got.

**Comment by djcb** [comment]
Unless you want to do it manually (the manual explains), guess you need to wait until the package is updated by your distribution. Note that mu/mu4e (should) come with all the man-pages, and/or try `info mu4e`.

Good luck!
