### ISSUE TITLE
Manual still refer to mu4e-compose-complete-ignore-address-regexp

### ISSUE THREAD

**Issue by snogge** [djcb/mu#1801]
`mu4e-compose-complete-ignore-address-regexp` is still described in the manual at 
https://github.com/djcb/mu/blob/d1b0938187552fea70fc0cb4dff212545cfb0428/mu4e/mu4e.texi#L1716
as the way to create custom address filters.  It is marked as obsolete in favor of `mu4e-contact-process-function`from mu 1.3.2.

**Comment by jschwab** [comment]
Duplicate of #1799
