### ISSUE TITLE
Why there are differences between outputs of "mu cfind" and "(mu4e-contacts-info)"

### ISSUE THREAD

**Issue by jpggithub** [djcb/mu#1804]
## Expected or desired behavior

When I compose a new message with mu4e, I expect that the adresses proposed by autocompletion for a given pattern for To: header is the same than for a "mu cfind pattern" command line in a terminal.

## Actual behavior

I have at least one contact that have two names for the same adress between autocomplete in mu4e compose buffer and `mu cfind` in a terminal. 
For example, I search "doe" : I  have "John Smith <john.doe@some.net> in mu4e and I have "John Doe <john.doe@some.net> with `mu cfind` in a terminal.

I have also a contact for whom I can't have the name in mu4e but for whom I have the name with "mu cfind".
For example, I search "nobody": I have "nobody@some.net" in mu4e and I have "Mister Nobody <nobodoy@some.net> with `mu cfind` in a terminal.

I also used (mu4e-contacts-info) for trying to solve the problem but I found the same items that for autocompletion (it is normal I suppose!). 

## Versions of mu, mu4e/emacs, operating system etc.
Debian testing 
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-17, modified by Debian
mu (mail indexer/searcher) version 1.4.13
mu4e - mu for emacs version 1.4.13

Edit: 11 nov. 2020 for enhancing the text

**Comment by pwinckles** [comment]
I am also experiencing the same issue. Where `mu cfind` correctly returns addresses in the format `John Doe <doe@example.com>` but mu4e autocomplete returns `"doe@example.com" <doe@example.com>`.

It looks like someone put together a PR that may address the problem: https://github.com/djcb/mu/pull/1696

**Comment by jpggithub** [comment]
Today I updated several packages on my emacs configuration (sorry for the lack of precision...).
Then I made a "mu init..." then a "mu index".
The issue seems now to be gone.

My configuration is now:
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2020-11-08, modified by Debian
mu (mail indexer/searcher) version 1.4.13
mu4e - mu for emacs version 1.4.13

**Comment by djcb** [comment]
Thanks, closing this.
