### ISSUE TITLE
Support for regular expressions or globs in --my-address?

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#1805]
## Expected or desired behavior

I am using a very simple date leaking trick. Every time I need to register with some website, I am registering with a different email of the form `%sitename%-spamtest-lockywolf@%my-sld%.%my-tld%`

All these emails are forwarded to my usual mail box any way, but if I later I receive a spam message directed to one of those addresses, I immediatey know who was the source of a leak.

Could regexps be implemented as in ` --my-address='.*-spamtest-lockywolf@example.example'` ?

## Actual behavior

MU interprets email addresses literally.

## Versions of mu, mu4e/emacs, operating system etc.

MU 1.4.13
xapian-core 1.4.17

**Comment by jhelberg** [comment]
same here. It has moved out of mu4e and moved into mu, but I think mu4e should still support something like this in the headers-view. Regexp then is not very hard to implement. I'm willing to help out of course.

**Comment by jhelberg** [comment]
I guess the predicate function mu4e-user-mail-address-p in mu4e-utils.el can be changed to also check some customization setting which then is a regexp.

**Comment by jhelberg** [comment]
or use a hook of course! a predicate hook which is or-ed with the mu4e-personal-addresses-function.

**Comment by jhelberg** [comment]
I use this for now, making all @burkburk.nl addresses my one:
```
(defun mu4e-user-mail-address-p (addr)
  "If ADDR is one of user's e-mail addresses return t, nil otherwise.
User's addresses are set in `(mu4e-personal-addresses)'.  Case
insensitive comparison is used."
  (when (and addr (mu4e-personal-addresses)
             (or (cl-find addr (mu4e-personal-addresses)
                      :test (lambda (s1 s2)
                              (eq t (compare-strings s1 nil nil s2 nil nil t))))
                 (string-match ".*@burkburk.nl" addr)))
    t))
```
generalizing this into some configurable variable is easy. But is it what we want? A hook is possible, a single variable too.

**Comment by djcb** [comment]
git master has an implementation of this now, basically use something like `--my-address='/foo.*@example.*/', and mu4e understands it too.
