### ISSUE TITLE
mu4e does not cooperate well with neither display-line-numbers-mode, nor linum-mode in the *mu4e-headers* buffers.

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#1806]
## Expected or desired behavior

I expect/desire the column names position to take into account the additional pseudo-column that appears when "display-line-numbers-mode" or "linum-mode" is on. It is very handy to have messages numbered, but it is not nice to see the actual columns be displaced relative to the column titles by the width of the numbers column.

Or, at least, the mu4e could prohibit turning them on, or warn agaist their usage.

## Actual behavior

![image](https://user-images.githubusercontent.com/2077025/94768859-2a798a80-03e3-11eb-907c-969bc8d40c42.png)

![image](https://user-images.githubusercontent.com/2077025/94769061-bd1a2980-03e3-11eb-90f0-f5ed27b1cb22.png)

## Steps to reproduce

Just turn on display-line-numbers-mode or linum-mode.

## Versions of mu, mu4e/emacs, operating system etc.

1.4.13, Emacs 27.1, Linux

## Any other detail

Not really.

**Comment by djcb** [comment]
The current alignment is a bit crude but relatively fast; in `master` you can set `mu4e-headers-precise-alignment` which gives you better (but slower) alignment.

**Comment by lockywolf** [comment]
Amazing, thank you.
