### ISSUE TITLE
Forwarded E-mail in OWA flagged es 'replied' in mu

### ISSUE THREAD

**Issue by sebhahn** [djcb/mu#1810]
## Expected or desired behavior

Forwarded E-mails from Outlook Web App are flagged as 'passed' in mu

## Actual behavior

E-mails are marked as 'replied'

## Versions of mu, mu4e/emacs, operating system etc.

emacs 26.3, mu 1.4.10

## Any other detail

Ist it possible to overwrite this manually?

**Comment by djcb** [comment]
mu uses https://cr.yp.to/proto/maildir.html:
```
Flag "P" (passed): the user has resent/forwarded/bounced this message to someone else. 
```
so the jargon is just a little different.

**Comment by sebhahn** [comment]
I still don't understand why they are marked as replied?

It also seems that if I'm using mu on PC2 the forwarded e-mails using mu on PC1 are not flagged (with P)? Are these flags just local?

**Comment by djcb** [comment]
Oh, I misread your report!

The flags correspond to the flags expressed in the message file name, as per https://cr.yp.to/proto/maildir.html. I suppose you use some program to get the OWA mails to your local maildir; that program is responsible for naming the files with the expected flags.

**Comment by sebhahn** [comment]
I'm using mbsync for this. Is there some way to control this?

Also, this means that the "P" flag is actually never synchronized back to OWA/mail server (since I don't see it on PC2)?

**Comment by sebhahn** [comment]
I just checked, the same e-mail is once marked as 2,PS on PC1 and 2,S on PC2, but why?
