### ISSUE TITLE
Switching contexts hotkey selection is a little naive.

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#1814]
## Expected or desired behavior

I have two accounts named **lockywolf** at two different servers. **lockywolf@server1.tld** and **lockywolf@server2.tld.**

When I type `;`, I want the minibuffer suggest the "l" button as the hotkey for the first account, and "o" for the second. 

## Actual behavior
![image](https://user-images.githubusercontent.com/2077025/95706245-eca11f80-0c88-11eb-9d66-0b2d248c60e8.png)

As can be seen on the picture, mu4e suggests "l" for both contexts, and therefore the second one is not selectable.

## Steps to reproduce

Create two contexts starting with the same letter.

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 27.1, mu 1.4.13

## Any other detail

An ad-hoc way to solve this seems to be to call a context "olockywolf" rather than by just an email address, but this is kinda a hack.

**Comment by theophilusx** [comment]
I think the context name can be anything, not just the email address. Mu
will use the first letter of the name for the hotkey shortcut. For
example, I have the contexts 'Private' (for my gmail account), 'Work'
for my work account and 'Outlook' for my MS Outlook account. This gives
me p, w and o as the hot keys.

Not precisely what you wanted, but is how I got around the fact all my
email addresses start with a 't'.

**Comment by djcb** [comment]
The "ad-hoc way" is in fact the way to do this, it has been like this since 2012 or so :-)
See the `mu4e-read-option` docstring.

**Comment by aaaawwWWWwwwwWWW** [comment]
Sorry, but this is bad UX AF. There's a need for a solution.
