### ISSUE TITLE
error in process filter: cond: Error 8: 3: trailing data starting with ':'

### ISSUE THREAD

**Issue by theblackfly** [djcb/mu#1816]
## Expected or desired behavior

When I run `M-x mu4e` from Emacs: 
```
[mu4e] /home/blackfly/Maildir/sent does not exist yet. Create now? (y or n) y
```
I expect the directory to be created when I say `y`.

## Actual behavior

But I get this error instead:
```
error in process filter: cond: Error 8: 3: trailing data starting with ':' (line was:'cmd:mkdir path:"/home/blackfly/Maildir/sent"')
```

## Steps to reproduce

1. Create and empty directory `~/Maildir`.
2. Open Emacs and run `M-x mu4e`.

## Versions of mu, mu4e/emacs, operating system etc.

I'm running GNU Emacs 26.3 + Spacemacs on Ubuntu 20.04 with mu version 1.4.13. I also tried GNU Emacs 26.3 without Spacemacs on Ubuntu 20.04 with mu version 1.5.5. The same problem occurs.

**Comment by djcb** [comment]
The error message suggests there's still an older version of mu on your system; the error comes from that.

**Comment by theblackfly** [comment]
I changed GNU Emacs from 26.3 to 28.0.50 and I don't get this error any longer.
