### ISSUE TITLE
Showing body snippets in headers view: add summary field to database?

### ISSUE THREAD

**Issue by ahttraga** [djcb/mu#1821]
## Desired behavior

Because I don't want to open short messages, especially those which do not require a response, I like to have a summary, or snippet, of the message body along with the subject in my headers view:

![image](https://user-images.githubusercontent.com/54644739/97019927-345d5c00-1551-11eb-8296-6a0fecc597fa.png)

The subject is shown in boldface, or alternatively the thread prefix, and a snippet of the message body follows in normal face.

For example in the first message of the thread, **testing everything** is the subject, and "Hello" is the body of the message. In the subsequent messages of the thread the message bodies ("Hello hello" and so on) are shown after the thread prefix.

## Current implementation

I implement this using a custom header, the [message function hack](https://www.djcbsoftware.nl/code/mu/mu4e/Message-functions.html), and the shell commands `mu view --summary-len` to obtain the body snippet along with `grep` and `cut` to process the snippet. [See code below.](#code)

## Proposed feature 

Although I don't observe a performance hit with this hack, a better solution would be to store a couple lines of the message summary, as obtained with `mu view --summary-len=3` for example, directly in the mu database, and then access this field with `mu4e-message-field` in headers view.

If this seems like a reasonable implementation I could try to code it but I would need to learn how `mu` populates the database.

Or perhaps a better way to do this exists already?

## Versions of mu, mu4e/emacs, operating system etc.
mu (mail indexer/searcher) version 1.4.13, emacs-snapshot, Debian GNU/Linux unstable kernel 5.6.7-1

## Code
```
(add-to-list 'mu4e-header-info-custom
  '(:thread-subject-body-snippet .
     ( :name "Thread or subject followed by body snippet"  ;; long name, as seen in the message-view
       :shortname "Subject Snippet"           ;; short name, as seen in the headers view
       :help "Thread or subject followed by body snippet" ;; tooltip
       :function (lambda (msg)
		   (my-mu4e~headers-thread-subject-body msg)))))

(defun my-mu4e~headers-thread-subject-body (msg)
  "Get the subject if it is the first one in a thread and make
bold face. Otherwise, return the thread-prefix without the
subject-text. In both cases, add snippet of body text."
  (let* ((tinfo  (mu4e-message-field msg :thread))
         (subj (mu4e-msg-field msg :subject))
	 (body-snippet (my-mu4e-message-body msg)))
    (concat ;; prefix subject with a thread indicator
     (mu4e~headers-thread-prefix tinfo)
     (if (or (not tinfo) (zerop (plist-get tinfo :level))
             (plist-get tinfo :empty-parent))
         (propertize (truncate-string-to-width (concat subj " ") 600) 'face 'bold) "") 	;; bold-face subject
     body-snippet)))

(defun my-mu4e-message-body (msg)
  "Quick & dirty way to get snippet of body of a message `msg'.
Requires 'grep' and 'cut' in addition to 'mu'."
  (replace-regexp-in-string "\n$" ""
    (shell-command-to-string
      (concat
       "mu view --summary-len=3 "
       (shell-quote-argument (mu4e-message-field msg :path))
       " | grep \"^Summary: \" | cut -c 10-"))))
```

**Comment by djcb** [comment]
Interesting idea. I'm working on some updates in the backend, so I'll keep this in mind.

**Comment by smalltimer** [comment]
Hi, I was also wondering that instead of one line per header, we could have multiple lines! This would allow to insert some sort of an 'excerpt'. Sort of like thunderbird (the way `mu4e` shows headers now) vs. outlook. Of course, if this is a design or an aesthetic decision, I understand!

**Comment by djcb** [comment]
Moving this old issue / RFE to IDEAS.org.
