### ISSUE TITLE
Should '(mu4e-update-index)' should fail if search process is already running?

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#1822]
## Expected or desired behavior

If mu4e is searching for something, the execution of `(mu4e-update-index)` should fail.

## Actual behavior

The index update is queued, and executed immediately after the first has finished.
Sometimes those two may deadlock (I do not know when exactly this happens).

## Steps to reproduce

I usually keep `mu4e` running in the background, by adding `(mu4e t)` into `.emacs`. I check mail by:

```
mbsync -aV
emacsclient --eval '(mu4e-update-index)'
```
I do that because running  `mu index` from the console fails due to `mu server` being run by Emacs.
This works fine if mu4e is available for indexing.
However, if a long search is running, this update sometimes gets into the queue, and sometimes deadlocks.

## Versions of mu, mu4e/emacs, operating system etc.

1.4.13, 27.1, Linux, xapian 1.4.17

**Comment by djcb** [comment]
Hmm, it shouldn't deadlock of course, but I'd recommend using the "official" way, running your update program from emacs. There's no reason why that couldn't work. Try running it by hand from emacs (`M-x shell-command`) and see if that works and if not, what the errors are. Perhaps some environment variables don't have the needed values.

**Comment by lockywolf** [comment]
Well, even with no update running through cron, it is possble to create a deadlock by, for example, running `(mu4e-update-index)` while another search is running.

**Comment by djcb** [comment]
```
(dotimes (n 5)
  (mu4e-headers-search "maildir:/bigfolder")
  (mu4e-update-index))
```
works for me at least, with 1.5.x.

**Comment by lockywolf** [comment]
I will close this and reopen if I find a reliable way to replicate the issue.
