### ISSUE TITLE
A way to show all "fields:", to show the original message (like Gmail does), or a shortcut to visit the original file in the maildir?

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#1824]
## Expected or desired behavior

I want to see the original message, including the headers and the base64-encoded files, either as a sub-mode of mu4e-message-mode, or by just visiting the original file.

## Actual behavior

I use Gmail.
I have written, sent (with smtpmail), and synchronised the mailbox (with mbsync).
Now I see three copies of this message, one in the "Sent Mail" maildir, and _two_ in the "All Mail".
I want to understand why. As far as I understand, there should be two copies, one in Sent, and one in All.
(I have `(setq mu4e-sent-messages-behavior 'delete)`, so the original draft should be expunged by now.)
If I press `V`, to show duplicates, then I actually see _five_ message, of which the first pair, All/Sent, seems legit, there is another All/All pair (which seems out of place), and there is also another All message without a pair.
I want to debug this, and see all the message fields, in particular, the message-id: or something like that. I am suspecting that they all should have the same message-id, but they do not.
Is there a button for that?

`.mbsyncrc` has `Expunge Both` set, and I synchronise all folders.

Gmail shows this batch as four messages, in which (I suspect), the first pair All/Sent is displayed as a single message, whereas the other three are marked as "draft", and Gmail cannot display the All/All pair at all, and displays the fifth one in an "editing" window.
Gmail IMAP has the following settings: 
- When I mark a message in IMAP as deleted: Auto-Expunge off - Wait for the client to update the server. (Because I understood the manual as if mbsync sends "expunge" rather than "delete" )
- When a message is marked as deleted and expunged from the last visible IMAP folder: Move the message to the Bin (Not sure whether this is correct, but I see no messages in [Gmail]/Bin anyway.)

## Steps to reproduce

Write a message, save a few times in process, long enough so that mbsync synchronisation runs. 

## Versions of mu, mu4e/emacs, operating system etc.

I use the last released versions of mu and emacs. 1.4.13/27.1

## Any other detail
This is the `mu` configuration form my ~/.emacs.
```
(setq message-kill-buffer-on-exit t)
(use-package mu4e
  :ensure nil
  :demand t
  :config
  (setq mail-user-agent 'mu4e-user-agent) ; [[info:emacs#Mail Methods][info:emacs#Mail Methods]]
  (setq read-mail-command 'mu4e) ; [[info:emacs#Mail Methods][info:emacs#Mail Methods]]
  (setq mu4e-headers-include-related t) ; Tree-view
  (setq mu4e-view-show-images t) ; ImageMagick
  (setq mu4e-view-scroll-to-next nil) ; Do not move past end of message.
  (setq mu4e-view-show-addresses t) ; Show not just names.
  ;;(setq mu4e-use-fancy-chars t)
  ;; (setq mu4e-get-mail-command "true")
  (setq mu4e-get-mail-command "flock --verbose --nonblock --exclusive ~/.mbsyncrc mbsync -aV") ; Shall it be flock ~/Mail-mbsync ?
  (setq mu4e-update-interval nil) ; We update by cron.
  (setq mu4e-sent-messages-behavior 'delete) ; Because Gmail copies to Sent by itself.
  (setq mu4e-change-filenames-when-moving t) ; For mbsync.
  (setq mu4e-compose-dont-reply-to-self t) ; If I am in the receivers.
  ;; (setq mu4e-headers-fields '((:human-date . 12) (:flags . 6) (:mailing-list . 10) (:from . 22) (:thread-subject)))
  (setq
   mu4e-sent-folder   "/sent-should-be-unused"       ;; folder for sent messages
   mu4e-drafts-folder "/drafts-should-be-unused"     ;; unfinished messages
   mu4e-trash-folder  "/trash-should-be-unused"      ;; trashed messages
   mu4e-refile-folder "/archive-should-be-unused")   ;; saved messages, not created
  (setq mu4e-headers-hide-predicate ; hide Gmail Spam
     (lambda (msg)
       (string-suffix-p "Spam" (mu4e-message-field msg :maildir))))
  (add-hook 'mu4e-headers-mode-hook ; wait for new version
	  (lambda () (display-line-numbers-mode -1)))
  (setq mu4e-context-policy 'ask-if-none) ; Hard to understand.
  (setq mu4e-contexts
     `( ,(make-mu4e-context
	  :name "lockywolf_at_gmail.com"
	  :match-func (lambda (msg) (when msg
				 (string-prefix-p "/lockywolf_at_gmail.com" (mu4e-message-field msg :maildir))))
	  :vars '(
		  (user-mail-address . "lockywolf@gmail.com")
		  (mu4e-sent-folder . "/lockywolf_at_gmail_com/[Gmail]/Sent Mail")
		  (mu4e-trash-folder . "/lockywolf_at_gmail_com/[Gmail]/Bin")
		  (mu4e-refile-folder . "/lockywolf_at_gmail_com/Refiled_by_mu")
		  (mu4e-drafts-folder . "/lockywolf_at_gmail_com/[Gmail]/Drafts")
		  ))
            <other contexts>)
  (mu4e-context-switch t "lockywolf_at_gmail.com")
  (mu4e t)
  )

(use-package smtpmail-multi
  :ensure t
  :demand t
  :config
  (setq smtpmail-multi-accounts
     (list (cons 'lockywolf-gmail (list "lockywolf@gmail.com"
					"smtp.gmail.com"
					465 ; 587
					'header
					'ssl ; 'starttls
					nil
					;(list "smtp.gmail.com" 587)
					nil
					nil) )
            <other contexts>)) 
  (setq smtpmail-multi-associations '(("lockywolf@gmail.com" lockywolf-gmail)
				                     <other contexts>))
  (setq smtpmail-auth-credentials "~/.netrc")
  (setq starttls-use-gnutls t)
  (setq send-mail-function 'smtpmail-multi-send-it)
  (setq smtpmail-debug-info t)
  (setq smtpmail-debug-verb t)
  )
```

**Comment by djcb** [comment]
There's `mu4e-view-raw-message`, by default bound to `.` in the message view.
