### ISSUE TITLE
Strange behaviour on ascending date sort

### ISSUE THREAD

**Issue by Xylon2** [djcb/mu#1826]
## Expected or desired behavior

Changing sort direction simply sorts in opposite direction

## Actual behavior

Sorting by date ascending completely changes which mails are being displayed.

## Steps to reproduce

Perform a sort by date:7d..now

Change sort direction to ascending.

Now I can see emails from 2018, 2019 and 2020. No emails from the last three days are shown. I turned off threading but it did not help.

## Versions of mu, mu4e/emacs, operating system etc.
mu4e 1.2
emacs 26.3

**Comment by Xylon2** [comment]
Alright I upgraded to mu 1.4.13 and this bug still exists.

**Comment by svictor9** [comment]
Maybe try `(mu4e-headers-toggle-full-search)` in the headers buffer ? It is bound to Q.  
By default mu4e only shows the first 500 messages of a search. Configure `mu4e-headers-results-limit` to change that.

**Comment by Xylon2** [comment]
Hm even with full-search on my filter for 7days returns many mails from a whole year ago and excludes many mails that arrived today. I wonder if the threading code is still activating behind the scenes and affecting which mails show up? Very strange.

**Comment by djcb** [comment]
It's likely due to the inclusion of related messages, see `mu4e-hdeaders-include-related`; that sometimes confuses users.
