### ISSUE TITLE
Add mixed mode sorting

### ISSUE THREAD

**Issue by telmich** [djcb/mu#1831]
## Expected or desired behavior

Sorting emails with oldest and newest mixed:

1. newest email
2. oldest email
3. 2nd newest email
4. 2nd oldest email
5.. ...
6. ...

## Motivation

Inboxes can be sorted by newest or oldest. If you try to do zero inbox and you go by ...

... oldest first, all new emails become old first and everyone gets late replies.
... newest first, some emails will never be answered

## Mixed mode sorting

In mixed mode sorting, when you work down your inbox, you first answer the newest message, archive it. This gives instant feedback to the latest mail you got.

Then the next mail you answer is the oldest one, thus ensuring your queue is also worked on from the back.

## Sticky mode

It's important that the first position can switch between oldest and newest to support this mode properly. This might require a state somewhere (can xapian / the mu backend support this?) to remember which state was last shown.

Alternatively a modulo based approach based on the number of messages might be used (0 == show oldest first, 1 == show newest first). This is not stable during updates, however on average the algorithm will be correct.

**Comment by djcb** [comment]
Note that if you go by "zero inbox" (I try to do that!), hopefully your inbox is never gets so full that the sorting order matters.

**Comment by telmich** [comment]
Unfortunately, 20+ are actually already quite a concern, depending on the "effort per answer" in my case - which is the motivation for the feature request.

**Comment by djcb** [comment]
Ah, but "zero inbox" doesn't mean handling them all, in just mean moving them to the right place (archive / delete / next action).

Anyway, adding more complicated sorting mechs are not on the table right now, sorry!
