### ISSUE TITLE
error: failed to open '/usr/share/mu/scripts/': No such file or directory

### ISSUE THREAD

**Issue by hughwilliams94** [djcb/mu#1833]
## Expected or desired behavior

mu scripts should return results

## Actual behavior
Calls to script fail with the message `error: failed to open '/usr/share/mu/scripts/': No such file or directory`

## Steps to reproduce
Install `mu-git` from the Arch Linux User Repository and run then run `mu msgs-count --query='flag:unread'`. The issue also occurs if I build `mu` from source and install. Seemingly the `/usr/share/mu/` folder is not created.

## Versions of mu, mu4e/emacs, operating system etc.
Mu version 1.5.7
Arch Linux

**Comment by progfolio** [comment]
same issue here

**Comment by djcb** [comment]
This might be an Arch packaging issue. If we you can reproduce with the "real" mu and a recent release, please file a new ticket. Thanks.
