### ISSUE TITLE
mu4e-view-save-url complains there is "no links for this message" (when links exists) (1.4.13)

### ISSUE THREAD

**Issue by m-ar-c** [djcb/mu#1841]
Hello,

when reading an email I should be able to use the function `mu4e-view-save-url` to copy an url inside the message.

Instead I got the error :
`mu4e-error: [mu4e] No links for this message`

It does not happen on all the messages (but on a lot of them). I can still hit 'enter' on the url and open it inside emacs, it works.

My setup:
Ubuntu 20.04.1 LTS
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2020-03-26, modified by Debian
mu (mail indexer/searcher) version 1.4.13 (I just compiled mu / mu4e from https://github.com/djcb/mu/releases/tag/1.4.13)

Please tell me which additional information is needed to debug this.

**Comment by m-ar-c** [comment]
As a workaround, I installed [link-hint](https://github.com/noctuid/link-hint.el). It not only allow me to copy or open any link in mu4e, but it also works anywhere and is a great way to act on any links visible on screen (thanks to [avy](https://github.com/abo-abo/avy) ) with a few keystrokes.

**Comment by tmplt** [comment]
I have the same problem. I only get the error when viewing HTML emails.

**Comment by djcb** [comment]
Are you using the gnus-derived view? There, `mu4e-view-save-url` is not supported.

**Comment by tmplt** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:
> Are you using the gnus-derived view? There, `mu4e-view-save-url` is 
> not supported.
I don't think so. How can I verify?

**Comment by djcb** [comment]
`C-h v mu4e-view-use-gnus RET`

But... perhaps more likely, the message are shown in the html-view which is not handled by mu4e directly, so the mu4e link handling doesn't work there. Somewhat ironically.

**Comment by djcb** [comment]
So yeah, that's with html mails, there we cannot easily do the links thing, sorry! However, things should improve with 1.6 (when it comes out).

**Comment by pedro-nonfree** [comment]
hitted by this

- looks like mu4e-view no longer does the html2text thing
- discarded the `mu4e-action-view-with-xwidget` from now ( src https://github.com/djcb/mu/blob/master/NEWS.org#reading-messages )

my scenario is that I have something like "click here", and I wanted to inspect it before clicking it and so on. So I did `(mu4e-view-raw-message)` or `.` and then I searched for the click here text, and I retrieved the URL
