### ISSUE TITLE
FR: stable API for counting number of hits to a query

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#1845]
## Expected or desired behavior

For 3rd party extensions to mu (such as https://github.com/agpchil/mu4e-maildirs-extension or https://github.com/rougier/mu4e-dashboard) currently have to shell out to the mu binary to count number of hits for a given search. It's been suggested (https://github.com/rougier/mu4e-dashboard/issues/5) that we could use `mu4e~proc-ping` to make the query although this would be using an "internal" mu4e function. What is really required is a stable public facing API, perhaps with a callback, which could be used by 3rd party extensions to make a query of the current running mu daemon.

## Actual behavior

Currently no such API exists, plugins are mostly shelling out to the mu command line with all the escaping issues that raises.

**Comment by djcb** [comment]
I've added `mu4e-last-query-result[s]` for this, see their doc-string.
