### ISSUE TITLE
Disabling the update of Message-ID on save in mu4e-compose  mode.

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#1846]
## Expected or desired behavior

I want mu4e-compose mode to keep the same message-id regardless of how many times I save this message.

## Actual behavior

Message-ID is updated with a different id every time I or auto-save-mode save the message.

## Steps to reproduce

0. Use Gmail-over-IMAP.
1.  `(setf mail-user-agent 'mu4e-user-agent)` is required. An ordinary message-user-agent does not seem to have this behaviour.
2. The drafts directory should be the gmail drafts directory: I set it through mu4e contexts: `(mu4e-trash-folder . "/lockywolf_at_gmail_com/[Gmail]/Bin")`
3. Then compose a new message, for example by typing C in the headers buffer.
4. Write something and save the message. Observer the message be assigned a Message-ID.
5. Write something else in the message body and save again. Observer the Message-ID change.

If there is one mail synchronization after the step4, and one after the step 5, you will end up having two messages in the Drafts directory. This is because at the synchronization 1 the message with the message-id 1 is uploaded to  Gmail, and at the synchronization 2, it is downloaded back, because it has never been "expunged", so Gmail thinks that it hasn't been downloaded yet; and the message with the second Message-ID is uploaded to Gmail.

You can repeat this as many times as you want, and get a fresh message draft every 5 minutes (or basically how often you sync your mail).

## Versions of mu, mu4e/emacs, operating system etc.

I am using mu4e 1.4.13 (the last release tagged at GitHub), Emacs 27.1, Linux 5.4.72.

## Any other detail

I would like mu4e to not update the Message-ID if it is already assigned. 
This is essentially a continuation of the issue https://github.com/djcb/mu/issues/1824

**Comment by lockywolf** [comment]
I tried to replace 

```
(message-generate-headers '(Date Message-ID))
 ```
with
```
 (message-generate-headers '(Date))  ; Message-ID
                (if (null (save-excursion (save-restriction
                                 (message-narrow-to-headers)
                                 (message-fetch-field "Message-ID" t))))
                   (progn (message-generate-headers '(Message-ID))
                          (message "LWF:new id. msgid=%s"  ))
                   (message "LWF: no need for new ID"))
```

But the `message-fetch-field` still returns `nil` even if the Message-ID already exists, the first time it is called. I'm missing something here.

**Comment by lockywolf** [comment]
Also `mu4e~draft-remove-mail-header-separator` kills my manually generated `(message-generate-headers '(Message-ID))`.

**Comment by lockywolf** [comment]
Sorry, this may be not a very good solution, but I did the following:

1. Added a hook to mu4e-compose-mode-hook: `(mu4e-compose-mode . (lambda () (message-generate-headers '(Date Message-ID))))`
2. Advised `message-make-message-id`:
```
(defun lockywolf/message-make-message-id ()
  "Do not update Message-ID if it already exists."
  (save-excursion (save-restriction
                   (message-narrow-to-headers)
                   (message-fetch-field "Message-ID" t))))
(advice-add 'message-make-message-id :before-until 'lockywolf/message-make-message-id)
```

This way Message-ID is generated at the file creation, and not updated unless it is accidentally (or intentionally) deleted.

**Comment by djcb** [comment]
I've pushed an update for this.

**Comment by lockywolf** [comment]
I commented on the commit. I think it won't work as expected due to message-mode peculiarity.
