### ISSUE TITLE
mu4e hangs showing message list

### ISSUE THREAD

**Issue by pmatos** [djcb/mu#1847]
## Expected or desired behavior

mu4e message list shows close to instantaneously

## Actual behavior

Message list hangs - emacs hangs - CPU at 100%.

## Steps to reproduce

Just showing any message list reproduces the problem.

## Versions of mu, mu4e/emacs, operating system etc.

This is mu4e 1.4.13 on archlinux
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.17.3) of 2020-12-01
Compiled with pgtk support and nativecomp.

## Any other detail

I have ran `strace -p <emacs pid>` and during the hang, I get the following:
```
strace: Process 1374566 attached
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
munmap(0x7f917492a000, 120284)          = 0
openat(AT_FDCWD, "/home/pmatos/.local/share/fonts/ofl/sourcecodepro/SourceCodePro-Bold.ttf", O_RDONLY) = 19
fcntl(19, F_SETFD, FD_CLOEXEC)          = 0
fstat(19, {st_mode=S_IFREG|0644, st_size=120172, ...}) = 0
mmap(NULL, 120172, PROT_READ, MAP_PRIVATE, 19, 0) = 0x7f917492a000
close(19)                               = 0
munmap(0x7f915c898000, 1173140)         = 0
openat(AT_FDCWD, "/home/pmatos/.local/share/fonts/ofl/sourcecodepro/SourceCodePro-Regular.ttf", O_RDONLY) = 19
fcntl(19, F_SETFD, FD_CLOEXEC)          = 0
fstat(19, {st_mode=S_IFREG|0644, st_size=120284, ...}) = 0
mmap(NULL, 120284, PROT_READ, MAP_PRIVATE, 19, 0) = 0x7f9174675000
```

When `munmap` happens, the process is not hanging any more. The hang is during the duration of the `access` to `AdobeBlank-Regular.ttf`. There's about an `access` per second and the process can easily hang for 30secs. 

This is definitely strange because the only font I have configured in my `.emacs` is "Source Code Pro-9", through `(set-frame-font "Source Code Pro-9")`.

**Comment by theophilusx** [comment]
Paulo Matos <notifications@github.com> writes:

> ## Expected or desired behavior
>
> mu4e message list shows close to instantaneously
>
> ## Actual behavior
>
> Message list hangs - emacs hangs - CPU at 100%.
>
> ## Steps to reproduce
>
> Just showing any message list reproduces the problem.
>
> ## Versions of mu, mu4e/emacs, operating system etc.
>
> This is mu4e 1.4.13 on archlinux
> GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.17.3) of 2020-12-01
> Compiled with pgtk support and nativecomp.
>
> ## Any other detail
>
> I have ran `strace -p <emacs pid>` and during the hang, I get the following:
> ```
> strace: Process 1374566 attached
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> access("/home/pmatos/.local/share/fonts/ofl/adobeblank/AdobeBlank-Regular.ttf", R_OK) = 0
> munmap(0x7f917492a000, 120284)          = 0
> openat(AT_FDCWD, "/home/pmatos/.local/share/fonts/ofl/sourcecodepro/SourceCodePro-Bold.ttf", O_RDONLY) = 19
> fcntl(19, F_SETFD, FD_CLOEXEC)          = 0
> fstat(19, {st_mode=S_IFREG|0644, st_size=120172, ...}) = 0
> mmap(NULL, 120172, PROT_READ, MAP_PRIVATE, 19, 0) = 0x7f917492a000
> close(19)                               = 0
> munmap(0x7f915c898000, 1173140)         = 0
> openat(AT_FDCWD, "/home/pmatos/.local/share/fonts/ofl/sourcecodepro/SourceCodePro-Regular.ttf", O_RDONLY) = 19
> fcntl(19, F_SETFD, FD_CLOEXEC)          = 0
> fstat(19, {st_mode=S_IFREG|0644, st_size=120284, ...}) = 0
> mmap(NULL, 120284, PROT_READ, MAP_PRIVATE, 19, 0) = 0x7f9174675000
> ```
>
> When `munmap` happens, the process is not hanging any more. The hang is during the duration of the `access` to `AdobeBlank-Regular.ttf`. There's about an `access` per second and the process can easily hang for 30secs.
>
> This is definitely strange because the only font I have configured in my `.emacs` is "Source Code Pro-9", through `(set-frame-font "Source Code Pro-9")`.

You are definitely pushing the boundaries here! While the native comp
feature is getting reasonably stable, the pure gtk feature is very raw.
This was only added to the Emacs git feature branches a week or so ago.
I found it had numerous, mostly minor, issues.

I would try building without pgtk support and see if you experience the
same issue. I'm not sure if mu4e can really do much until this feature
becomes a bit more mature.

Just my 2 cents, I'm not a mu4e maintainer, but I also found numerous
issues with pgtk and while I think it is an important imitative, it
isn't ready for prime time yet.


--
Tim Cross

**Comment by pmatos** [comment]
> You are definitely pushing the boundaries here! While the native comp feature is getting reasonably stable, the pure gtk feature is very raw. This was only added to the Emacs git feature branches a week or so ago. I found it had numerous, mostly minor, issues. I would try building without pgtk support and see if you experience the same issue. I'm not sure if mu4e can really do much until this feature becomes a bit more mature. Just my 2 cents, I'm not a mu4e maintainer, but I also found numerous issues with pgtk and while I think it is an important imitative, it isn't ready for prime time yet.
> […](#)
> -- Tim Cross

Totally understand and agree with what you are saying here. I think that people shouldn't need to spend time trying to fix stuff that breaks in unstable branches, like the ones I have been using. In any case, I created the issue as it might be relevant to others attempting to use the same setup. I will keep investigating this by myself and posting updates. This seems to be certainly related to something mu4e is doing since I don't see these hangs while coding - only during mu4e usage.

**Comment by kepi** [comment]
I'm using `nativecomp` branch but not `pgtk` (at least not intentionally :D ). I didn't upgrade emacs since July 13th but this problem hits me today anyway (restarted computer after longer time).

Currently I'm not sure if problem was caused by update of mu4e or by installing new fonts (I installed a lot of fonts in last two days). There is no way I would suspect the fonts if not seeing this issue. **Thanks for opening it!**

I tried to use emacs-git without native-comp but it didn't make any difference.

I resolved (or better workarounded) the problem by removing google fonts directory (cloned from google/fonts git) from `~/.local/share/fonts` and running `fc-cache -r -v`. Sidenote: I installed it manually because `ttf-google-fonts-git` from AUR is conflicting with `adobe-source-code-pro-fonts` which is required by multiple system apps. Maybe this is the reason for conflict ;)

**Comment by pmatos** [comment]
A backtrace at time of hang shows:
```
0x00007f917f9aa104 in ?? () from /usr/lib/libfontconfig.so.1
(gdb) bt
#0  0x00007f917f9aa104 in  () at /usr/lib/libfontconfig.so.1
#1  0x00007f917f98d20e in FcCharSetSubtractCount () at /usr/lib/libfontconfig.so.1
#2  0x00007f917f99a7df in  () at /usr/lib/libfontconfig.so.1
#3  0x00007f917f99ac05 in  () at /usr/lib/libfontconfig.so.1
#4  0x00007f917f99afa7 in  () at /usr/lib/libfontconfig.so.1
#5  0x00007f917f99b0b4 in  () at /usr/lib/libfontconfig.so.1
#6  0x00007f917f99bef8 in FcFontMatch () at /usr/lib/libfontconfig.so.1
```

Definitely font related. I should rebuild emacs with debug symbols though.

**Comment by djcb** [comment]
Seems like a generic emacs / fontconfig problem, so I would recommend reporting this upstream; I don't think mu4e can do much about this.

**Comment by pmatos** [comment]
I have reverted to a stable emacs and all is ok now. Closing.
