### ISSUE TITLE
Regex in query strings

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1848]
## Expected or desired behavior

I just updated mu to the development version and my query searches that include regex don't work anymore. In particular, I have the string `maildir:/.*Inbox$|.*Drafts/` which now returns nothing.

I am sorry if this is a change that is mentioned somewhere. I checked `NEWS.org` and couldn't find a reference to it.

## Steps to reproduce
Simply search for something like `mu find maildir:/.*Inbox$`.

## Versions of mu, mu4e/emacs, operating system etc.
emacs: 27.1
mu: commit 4eed851

**Comment by djcb** [comment]
It's a bug... thanks for reporting.
