### ISSUE TITLE
Remove extra lines in overview

### ISSUE THREAD

**Issue by rommeswi** [djcb/mu#1849]
## Expected or desired behavior
I would like my maildirs be displayed like this:

- INBOX
  | Subfolder
| Drafts
| Sent

(Ideally, the colors could also be prettier, haha)

## Actual behavior
Maildirs are displayed like this:

`
- INBOX

  | Subfolder

| Drafts

| Sent`

## Steps to reproduce
Install, sync maildirs, and run :)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp git bibtex spell-checking latex pdf-tools mu4e)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by djcb** [comment]
That's part of the Spacemacs "layer", so best ask there.
