### ISSUE TITLE
[MSYS2] mu4e never starts 

### ISSUE THREAD

**Issue by claritystorm** [djcb/mu#1851]
## Expected or desired behavior

mu4e starts.

## Actual behavior

mu4e never starts.

## Steps to reproduce

Use `M-x mu4e`.

## Versions of mu, mu4e/emacs, operating system etc.

Development version (git master rev. 4eed85187) [built on MSYS2](https://github.com/msys2-unofficial/MSYS2-packages/tree/master/mu). This issue does not occur on the stable version (1.4.10).

mu (mail indexer/searcher) version 1.5.7

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0291e9eb5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html javascript
      (c-c++ :variables c-c++-lsp-enable-semantic-highlight 'rainbow c-c++-default-mode-for-headers 'c++-mode c-c++-enable-google-style t c-c++-enable-google-newline t c-c++-enable-auto-newline t)
      (cmake :variables cmake-enable-cmake-ide-support t)
      windows-scripts dap templates bibtex latex pdf finance
      (mu4e :variables mu4e-installation-path "/msys64/usr/share/emacs/site-lisp/mu4e" mu4e-use-maildirs-extension t)
      (auto-completion :variables auto-completion-minimum-prefix-length 1 auto-completion-idle-delay 0.0 auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
      emacs-lisp git helm lsp markdown multiple-cursors org
      (shell :variables shell-default-full-span nil)
      spell-checking syntax-checking
      (version-control :variables version-control-diff-side 'left)
      treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP

## Any other detail

Workaround:

Add the following to `.emacs` / `dotspacemacs/user-config` in `.spacemacs`.

```elisp
(defun adv/mu4e~call-mu (form)
  (process-send-eof mu4e~proc-process))

(advice-add #'mu4e~call-mu :after #'adv/mu4e~call-mu)
```

**Comment by djcb** [comment]
Can you reproduce with 'vanilla' mu4e (without the spacemacs layer)? And can you explain how your workaround helps for this? Thanks.

**Comment by djcb** [comment]
BTW, this maybe be #1827, for which there's a candidate fix in `master` now. Can you confirm?

**Comment by claritystorm** [comment]
Build failure occurs with 0ef88af34.
```
$ makepkg -sf
```
...
```
Making all in mu
make[2]: Entering directory '/c/Users/User/MSYS2-packages/mu/src/mu/mu'
  GEN      mu-help-strings.h
make  all-am
make[3]: Entering directory '/c/Users/User/MSYS2-packages/mu/src/mu/mu'
  CXX      mu.o
  CXX      mu-cmd-cfind.o
  CXX      mu-config.o
  CXX      mu-cmd-extract.o
  CXX      mu-cmd-find.o
  CXX      mu-cmd-index.o
  CXX      mu-cmd-script.o
  CXX      mu-cmd.o
  CXX      mu-cmd-server.o
In file included from /usr/lib/gcc/x86_64-pc-msys/9.3.0/include/c++/cstdio:42,
                 from /usr/lib/gcc/x86_64-pc-msys/9.3.0/include/c++/ext/string_conversions.h:43,
                 from /usr/lib/gcc/x86_64-pc-msys/9.3.0/include/c++/bits/basic_string.h:6493,
                 from /usr/lib/gcc/x86_64-pc-msys/9.3.0/include/c++/string:55,
                 from mu-cmd-server.cc:22:
mu-cmd-server.cc: In function ‘MuError mu_cmd_server(const MuConfig*, GError**)’:
mu-cmd-server.cc:118:28: error: expected id-expression before ‘(’ token
  118 |                 ::fflush(::stdout); // Needed for Windows, see issue #1827.
      |                            ^~~~~~
  CXX      test_mu_query-test-mu-query.o
  CXX      test_mu_cmd-test-mu-cmd.o
make[3]: *** [Makefile:898: mu-cmd-server.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CXX      test_mu_threads-test-mu-threads.o
  CXX      test_mu_cmd_cfind-test-mu-cmd-cfind.o
make[3]: Leaving directory '/c/Users/User/MSYS2-packages/mu/src/mu/mu'
make[2]: *** [Makefile:756: all] Error 2
make[2]: Leaving directory '/c/Users/User/MSYS2-packages/mu/src/mu/mu'
make[1]: *** [Makefile:590: all-recursive] Error 1
make[1]: Leaving directory '/c/Users/User/MSYS2-packages/mu/src/mu'
make: *** [Makefile:500: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by claritystorm** [comment]
> 
> 
> Can you reproduce with 'vanilla' mu4e (without the spacemacs layer)? And can you explain how your workaround helps for this? Thanks.

The same occurs without the `mu4e` Spacemacs layer.

The `*mu4e-log*` and ` *mu4e-proc*` buffers never show any response from the mu server.

Emacs documentation for [`38 Processes`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Processes.html#Processes), specifically [`38.7 Sending Input to Processes`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Input-to-Processes.html#Input-to-Processes) states the following.

> Some operating systems have limited space for buffered input in a pty. On these systems, Emacs sends an EOF periodically amidst the other characters, to force them through. For most programs, these EOFs do no harm. 

The same page shows,

> Function: process-send-eof &optional process
> 
>     This function makes process see an end-of-file in its input. The EOF comes after any text already sent to > it. The function returns process.
> 
>     (process-send-eof "shell")
>          ⇒ "shell"

So, I tried it.

**Comment by djcb** [comment]
Thanks... so I suspect the candidate fix comes down to the same - when you can compile it at least... I've updated it, so hopefully it should compile now.

**Comment by claritystorm** [comment]
It now compiles. However, it has no effect.

**Comment by djcb** [comment]
but sadly, sending `process-send-eof` doesn't work too well with the mu-server when sending commands in quick succession.

**Comment by djcb** [comment]
After some questions on the ML it seems we don't have the necessary expertise/interest to support MSYS. Sorry about that! Perhaps in the future this can be revived. Closing this...
