### ISSUE TITLE
email display does not match between mu4e:compose and mu4e:view with format=flowed

### ISSUE THREAD

**Issue by tmplt** [djcb/mu#1854]
I have 
```emacs
(setq mu4e-compose-format-flowed t)
(add-hook 'text-mode-hook #'auto-fill-mode)
```
and I compose a mail with the paragragh
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
reprehenderit in voluptate velit esse cillum dolore eu fugiat
nulla pariatur. Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum.
```
but when I review the sent email with mu4e:view the paragraph is formatted to
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
ex ea
commodo consequat. Duis aute irure dolor in reprehenderit in
voluptate
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
occaecat cupidatat non proident, sunt in culpa qui officia
deserunt
mollit anim id est laborum.
```
The paragraph looks as it should in other email clients (K-9 tested).

I'm using mu4e v1.4.13

---

Perhaps related to #1600, but I'm unsure. I'm enabling format-flowed as per recommendations on https://useplaintext.email/#mu4e.

**Comment by tmplt** [comment]
This issue is resolved by setting `(setq fill-flowed-encode-column 998)`. I do not know why.

**Comment by tmplt** [comment]
A perhaps more sane setting would be
```elisp
(setq fill-column 72)
(setq fill-flowed-encode-column fill-column)
```

**Comment by maasdorp** [comment]
> This issue is resolved by setting `(setq fill-flowed-encode-column 998)`. I do not know why.

Did you figure out why this is the case? Why does one need to set this in addition to setting mu4e-compose-format-flowed true?

**Comment by yusi1** [comment]
> > This issue is resolved by setting `(setq fill-flowed-encode-column 998)`. I do not know why.
> 
> Did you figure out why this is the case? Why does one need to set this in addition to setting mu4e-compose-format-flowed true?

I don't know either, format=flowed only works if I set `(setq fill-flowed-encode-column 998)`.

**Comment by yusi1** [comment]
> > This issue is resolved by setting `(setq fill-flowed-encode-column 998)`. I do not know why.
> 
> Did you figure out why this is the case? Why does one need to set this in addition to setting mu4e-compose-format-flowed true?

I found a bit in the manual section for `format=flowed` that explains this actually:
`For this to happen properly, you should write each paragraph of your message of as a long line (i.e. without carriage return).`

So for `format=flowed` to work properly, if you write a paragraph, it all has to be a long line and not multiple lines.

**Comment by djcb** [comment]
I just tried with the "Lorem ipsum..." and it works fine. Not sure when this got fixed, but seems to work fine with `master` and only ` mu4e-compose-format-flowed`, not other changes.

Closing...
