### ISSUE TITLE
Forgetting a wrong contact

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1855]
## Actual behavior
I have (once) sent an email to `Person <wrong-email@gmail.com>` instead of `Person <correct-email@gmail.com>`. 
Now, every time whenever I search `mu cfind Person`, I get back the two emails addresses (correct and wrong). How can I get mu to forget "wrong-email"?

Note that I made sure that when I type `mu find "wrong-email@gmail.com"` I get no hits (I deleted all emails that mention that email). So I am not sure where mu is getting the wrong email address from.

## Steps to reproduce
As described above

## Versions of mu, mu4e/emacs, operating system etc.
mu:  1.5.7 (3ff8fd1)
Emacs: 27.1
OS: CentOS 7

**Comment by djcb** [comment]
A full database rebuild (i.e., mu init and index) should do the trick. The contact info is stored separately in the database, so that explains. Alternatively, https://www.djcbsoftware.nl/code/mu/mu4e/Contact-functions.html#Contact-functions
