### ISSUE TITLE
Can't search for email address (and some other patterns) in the body

### ISSUE THREAD

**Issue by ov** [djcb/mu#1856]
## Actual behavior

Say I have an indexed email which has `foo@bar.com` email in its body, simply as a text. If I do queries like this:

```
mu find foo@bar.com
mu find \"foo@bar.com\"
mu find /foo.bar.com/
mu find foo@bar
mu find bar.com
...etc... I tried it many ways
```

I get `error: no matches for search expression (4)`. However, if I do it like this:

```
mu find "foo bar com"
```

I get the proper message found. Note that the `bar` word is unique and never appears in the message body except for that place where it is a part of the email text. If I open the message file with `mu view` it clearly shows the email text there.

Searching for other data from that email works well. For instance, the message in question contains both email and ip addresses (say 1.2.3.4) in its body text, and `mu find bar.com` doesn't work, while `mu find 1.2.3.4` works well, so it is not about the dots...

I'm getting a similar behaviour for other cases below:

- for texts like `12345-678-9AB` I can find it using `mu find 12345 678 9AB`, but can't find using `mu find 12345-678-9AB` or `mu find /12345.678.9AB/`;
- same for dates in message body like `01/18/2010`. The only way to find them is to use `mu find 01 and 18 and 2010` which returns way too many messages from 2010 which happen to have 01 and 18 somewhere.

## Expected or desired behavior

I expect `mu find` to be able to find messages by email text containing in the body. Same for other patterns mentioned above.

## Versions of mu, mu4e/emacs, operating system etc.

```
$ mu --version
mu (mail indexer/searcher) version 1.4.13
```

**Comment by markk** [comment]
Perhaps related to https://github.com/djcb/mu/issues/1786

**Comment by djcb** [comment]
This is a bit of a limitation of the way Xapian text-indexing works - you can't really find arbitrary phrases with non-word characters. mu tries to work around that a bit, but we can't really fix it (not easily at least)

**Comment by ov** [comment]
The minimal fix could simply display a message if the query contains the symbols that cannot be there. This way we could at least see that the input is wrong.

Another relatively simple solution is to split the query using the non-word characters, so "foo@bar.com" becomes "foo AND bar AND com", or maybe even "foo THEN bar THEN com", depending on what Xapian is capable to digest. That's what I am doing manually at the moment, but it looks like an easy task to automate at the mu level.
