### ISSUE TITLE
[Feature request] Contact list can be sorted by frequency

### ISSUE THREAD

**Issue by rhgg2** [djcb/mu#1857]
## Expected or desired behavior

Mu4e contact list can be sorted in a manner which favours frequency of contact

## Actual behavior

Mu4e contact list is sorted in a manner which favours most-recent contact.

## Versions of mu, mu4e/emacs, operating system etc.

mu/mu4e 1.4.13, Emacs 26.2

## Any other detail

I just upgraded from mu 1.0.x. The contact handling has changed substantially, and in particular, it seems that mu now only passes to mu4e a list of pre-sorted contacts, rather than passing data allowing mu4e to do the sorting itself.

However, the sorting algorithm which mu uses is less useful than the one which mu4e used previously. The current sorting algorithm is, I think, in ContactInfoLessThan in mu-contacts.cc and is that:

(1) personal comes first  
(2) then more recent comes first  
(3) then more frequent comes first  
(4) then alphabetical

On the other hand, mu4e (in the removed function mu4e~sort-contacts) used to sort as follows:

(1) personal comes first  
(2') then, if one contact was last mentioned in the last 15 days, and the other was not, that one comes first  
(3) then more frequent comes first

Now (2') is much superior to (2), because (2) makes it almost impossible for (3) to be triggered, unless you happened to receive an email from two different contacts at exactly the same time. 

Would it be possible to implement (2') in mu-contacts.cc as an alternative sorting algorithm for contacts in mu-server and mu-clist (maybe with the hard coded 15 days made into an option?)

**Comment by djcb** [comment]
I think it's bit arbitrary whether "more recent" or "more frequent" is more important; and the way completion in emacs works is that many of the completion methods completely ignore the order provided by mu4e, so many users don't even notice.

Anyway, i'm not against 2', but it would become the one and only sorting method, we have too many options already.

**Comment by rhgg2** [comment]
Thanks for the reply. I use helm, which quite definitely takes the list in the order it is provided and matches the first item which fits in that order. The upshot is that my email completion has become rather less useful with the new version (though lots of other things have become much better.) With the old mu4e sort algorithm I didn't even have to check whether the autocomplete was correct, as it would always get the intended contact first time. Now it only gets it right about 50% of the time.
