### ISSUE TITLE
Deal with Emacs auto-saves and Emacs backups somehow when composing messages?

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#1858]
## Expected or desired behavior

I expect Emacs' auto-saves and numbered backups to not get uploaded to GMail when doing mbsync on mu4e's maildir.

## Actual behavior

So, the problem is the following: Emacs allows making "real-time" backups to protect users from crashes (those start with #) and from mis-editing (those end with _number_.~). By default, those are made inside the directory where the file is. If using mu4e to compose mail, backup files are created inside the maildir's "Drafts" directory, and then mbsync diligently uploads those files to Gmail and creates a mess. 

Perhaps `(setq auto-save-list-file-prefix "~/.mu/autosave/")` and/or `(setq backup-directory-alist '((".*" . "~/.emacs.d/backup")))` could be set buffer-locally in the `mu4e: compose`mode, to prevent this kind of situation?

Alternatively, maybe just mentioning this kind of situation in the manual could be a possibility?

## Steps to reproduce

For auto-saves, run mbsync (or mu4e-check-mail) when an auto-save file is present in the Drafts directory.
For numbered backups, `(setq version-control t)`.

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 27.1, mu 1.4.13

## Any other detail

I have backups and auto-saves saved in a separate directory automatically. (I.e, I set those variables globally and I don't need this feature. But to be on the safe side, for the users not doing that, it might be worth being a little user-friendly.)

**Comment by djcb** [comment]
It seems it'd be better to have some exclusion rule for mbsync than add yet more workaround-complexity to mu4e. But, I'd take a PR to add a note about backups / auto-saves to the FAQ. Are you volunteering? :-)

**Comment by lockywolf** [comment]
Sure I can add it to the FAQ, but I do not really think this is an mbsync error, because mbsync does exactly what it does, it synchronizes maildirs, and everything inside a maildir is expected to be a message, as far as I understand. It is Emacs who is treating maildirs as ordinary directories.

But insofar I will make an FAQ patch when time permits.

**Comment by djcb** [comment]
I'm not saying this is an `mbsync` error, it's just some functionality that would find a natural place there (perhaps it has? I remember `offlineimap` having something like it).
