### ISSUE TITLE
Error 11 when sending an email and maildir is a symlink

### ISSUE THREAD

**Issue by Sbozzolo** [djcb/mu#1860]
I am using version 1.4.10 and I am migrating my system to a new setup (from Gentoo to Fedora, dual booting). I mount my old home in `/home/sbozzolo/gentoo/home`, so instead of creating a new maildir, I symlinked the old one: `/home/sbozzolo/.mail` is a link to `/home/sbozzolo/gentoo/home/.mail` (which is where I've been using mu for the past years). 

When I send an email with mu4e, I get Error 11:
```
error in process filter: mu4e-error-handler: Error 11: failed to add path: root '/home/sbozzolo/.mail' is not a proper suffix of path '/home/sbozzolo/gentoo/home/sbozzolo/.mail/sbozzolator/[Gmail].Drafts/cur/1607959810.02bc9947c5589319.maxwell:2,DS' (line was:'(sent :path "/home/sbozzolo/gentoo/home/sbozzolo/.mail/sbozzolator/[Gmail].Drafts/cur/1607959810.02bc9947c5589319.maxwell:2,DS")')
error in process filter: Error 11: failed to add path: root '/home/sbozzolo/.mail' is not a proper suffix of path '/home/sbozzolo/gentoo/home/sbozzolo/.mail/sbozzolator/[Gmail].Drafts/cur/1607959810.02bc9947c5589319.maxwell:2,DS' (line was:'(sent :path "/home/sbozzolo/gentoo/home/sbozzolo/.mail/sbozzolator/[Gmail].Drafts/cur/1607959810.02bc9947c5589319.maxwell:2,DS")')
```

It looks like symlinks are not properly resolved somewhere.

**Comment by djcb** [comment]
Symlinks are not supported in the 1.4.x series (or older), so the error is not surprising.

The 1.5.x development series do have support for this.
