### ISSUE TITLE
Modification of contact info

### ISSUE THREAD

**Issue by baracunatana** [djcb/mu#1861]
Is there a way to modify the information of a contact?

The problem is that, for some reason, some of my contacts are stored in the "Name Lastname <email@example.com>" form while others are in the "email@example.com" form. The later are much harder to remember for autocompletion.

I looked at functions or variables (I'm using mu4e) that allowed for that, but came up empty so far.

Any help is appreciated.

**Comment by djcb** [comment]
https://www.djcbsoftware.nl/code/mu/mu4e/Contact-functions.html#Contact-functions
