### ISSUE TITLE
Sometimes hangs at the "Loading message..." stage.

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#1862]
## Expected or desired behavior

I want mu to fail when message to display cannot be found, instead of hanging

## Actual behavior

At certain times, hard to predict when, viewing a message in mu4e breaks with mu displaying 
"Loading message..." indefinitely, instead of anything else.
The `*Messages*` buffer has:

```
error in process filter: mu4e-error-handler: Error 11: failed to find message for view: something went wrong (line was:'(view :docid 278402 :msgid nil :extract-images t :decrypt nil :verify t)')
error in process filter: Error 11: failed to find message for view: something went wrong (line was:'(view :docid 278402 :msgid nil :extract-images t :decrypt nil :verify t)')
```

I suspect that his happens at synchronisation time, after the message has been expunged by mbsync, but  before the index is update. But I am no very sure

## Steps to reproduce

Not very sure how to reproduce this. Perhaps, a timeout before a message is selected in the headers view, and is is displayed, needs to be added, and while the timeout is in process, a message should be deleted.

## Versions of mu, mu4e/emacs, operating system etc.

Emacs 27.1, mu4e 1.4.13

## Any other detail

Not at the moment.
I will try to test and make this error stabely reproducible.
However, I guess, just adding some recovery procedure to the q-binding in the major mode of *mu-loading* buffer could help.

**Comment by theophilusx** [comment]
I had a very similar problem after an upgrade. I deleted the database
from ~/.cache/mu, then did a mu init followed by a mu index and this
problem went away. I only started to see this issue after I had upgraded
mu to a newer version.

My guess is that sometimes the xapian db might get corrupted. Building
it again seems to fix the issue.


--
Tim Cross

**Comment by djcb** [comment]
This is likely a problem of messages changing/being moved behind mu's back (e.g. `mbsync` could do that). That's beyond `mu`'s purview, but you can try:
```
(setq 
  mu4e-index-lazy-check nil 
  mu4e-index-cleanup t)
```
(i.e. their default values) to attempt to avoid that problem.
