### ISSUE TITLE
Missing faces for all buffers

### ISSUE THREAD

**Issue by WhatDothLife** [djcb/mu#1863]
Since a few weeks my mu4e buffers have no face applied. They are just plain like you can see in this picture. 

![mu4e](https://user-images.githubusercontent.com/33008303/102487502-fa996500-406a-11eb-8f88-3b7990f33a71.png)

Sometimes, after startup the faces are applied like usual, but after switching views for a few times, it stops working. 

## Versions of mu, mu4e/emacs, operating system etc.
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.9.11-3-MANJARO #1 SMP PREEMPT Sat Nov 28 09:08:57 UTC 2020 x86_64
        path       (/home/$USER/.emacs.d/bin/ ~/.local/bin /usr/local/bin /usr/local/sbin /usr/bin /var/lib/flatpak/exports/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running)
MU 1.4.13
```

## Any other detail
I installed mu from the AUR. Also I'm using Doom Emacs, but I could replicate this without my private config, so it's most likely a mu4e issue.

**Comment by djcb** [comment]
Hmmm, can you reproduce without using doom etc.? Does this only affect mu4e? What does `M-x describe-char` say for a character you'd expect to have to special face, but doesn't?
