### ISSUE TITLE
Thunderbird loses attachments after opening with mu4e

### ISSUE THREAD

**Issue by CodesByChris** [djcb/mu#1864]
## Expected or desired behavior

Here, mu indexes a maildir folder from Thunderbird. Email attachments should open in Thunderbird also after opening them in mu4e.

## Actual behavior

When an attachment is opened in mu4e, Thunderbird can no longer open it afterwards. In particular, the external viewer (e.g. evince) called for displaying the attachment reports an error such as:
```Unable to open document “file:///tmp/mozilla_USER/test.pdf”.```

There is indeed a file at this location, but it is empty (i.e. of size 0 bits).

The attachment is not lost entirely, because the mail server still has it. Just Thunderbird can not open it anymore.

## Steps to reproduce

1. Assuming an IMAP email account in Thunderbird configured with maildir storage (i.e., https://support.mozilla.org/en-US/kb/maildir-thunderbird).
2. Send a test email with an attachment to the configured email account. Do not open this email attachment in Thunderbird at this point, to be sure that the file is not yet in a cache.
3. Index the maildir folder from mu:
    ```
    mu init --maildir=~/.thunderbird/PROFILEFOLDER
    mu index
    ```
    where PROFILEFOLDER has to be replaced by the local profile folder's name.
4. Open the attachment of the test email in mu4e.
5. Open the attachment of the test email in Thunderbird.
6. The viewer now yields the mentioned error message.

If, instead, I'm opening the file in Thunderbird at step 2 above, then the external viewer opens the file as expected.

## Versions of mu, mu4e/emacs, operating system etc.

- mu: 1.4.13 (the one from `sudo apt install maildir-utils`)
- mu4e: 1.4.13 (the one from `sudo apt install mu4e`)
- Operating System: Ubuntu 20.10
- Thunderbird: 78.5.0

## Any other detail

Thanks a lot for developing mu and mu4e. They are really helpful tools!

**Comment by djcb** [comment]
Hmmm, mu/mu4e don't know about this Thunderbird temporary file:///tmp/mozilla_USER/test.pdf, and so couldn't remove it even if they wanted to (and similarly in the opposite direction: Thunderbird cannot know about the temp-files that mu/mu4e create for showing the attachments).

Perhaps Thunderbird clears its temp files automatically after a while?

**Comment by CodesByChris** [comment]
Yes, Thunderbird clears its temp files after a while (or the OS does it). For example, after a restart of the computer, the folder `/tmp/mozilla_USER/` is gone. However, when trying to open the file from inside Thunderbird again, it can still not open the file. It re-creates the tmp-file `file:///tmp/mozilla_USER/test.pdf`, which is empty (i.e. 0 bits in size).

**Comment by djcb** [comment]
When mu4e opens a new message the first time, it'll move the file to to another directory (as per the maildir spec)... perhaps Thunderbird gets confused by that?

**Comment by CodesByChris** [comment]
Yes, this might be the reason why Thunderbird gets confused. Is Thunderbird not correctly implementing the maildir spec concerning the handling of attachments?

**Comment by speedball2001** [comment]
Thunderbird's maildir is not maildir. 

Thunderbird's [wiki ](https://wiki.mozilla.org/Thunderbird/Maildir) says this: "Thunderbird's maildir implementation allows a single unique filename per email (EML). HOWEVER, note this is NOT full maildir in the sense that most people, particularly linux users or mail administrators, know as maildir. You cannot point a Thunderbird account to a mail server directory. You do not get message flags stored with emails. You only get a single file per message, and nothing more."

**Comment by CodesByChris** [comment]
I see. Then, I assume that compatibility with Thunderbird isn't achievable at the moment, at least not before Thunderbird implements full maildir, right?

**Comment by speedball2001** [comment]
@CodesByChris Your assumption is right. mu wont be compatible with Thunderbird as long as Thunderbird doesn't implement maildir completely and correctly. I don't know, though, if true maildir compliance is on Thunderbird's agenda at the moment. Taking into account that the current "maildir-lite" implementation has been in development for 10 years, I wouldn't hold my breath.

**Comment by CodesByChris** [comment]
Then, I guess there is not much that can be done about it. Still, I'm quite impressed by how well mu already supports Thunderbird's maildir version in general, despite it not yet being standard-conformant. I can also understand Thunderbird's decision to focus on other components at the moment, when these are more urgent. Still, for safety, I conclude that one should use mu/mu4e with maildir-tools that implement the full standard.

Thanks for your help! From my side, this issue can be closed.

**Comment by djcb** [comment]
Indeed... I guess we can't do much about this then, unfortunately.
