### ISSUE TITLE
message-insert-screenshot on macos not working

### ISSUE THREAD

**Issue by fab6** [djcb/mu#1870]
Hi,
## Expected or desired behavior

on a macos I try to insert a screenshot to the message with "message-insert-screenshot"

Emacs version 28.05
![image](https://user-images.githubusercontent.com/3047695/102988837-df1fd580-4514-11eb-9b58-933b8a38523d.png)

## Actual behavior
Unfortunately I get only this tiny picture:

![image](https://user-images.githubusercontent.com/3047695/102988276-0033f680-4514-11eb-9ff2-7110b115aaa5.png)

and have this messages: 
```
Unable to load image (image :type png :data import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1297.
Version: ImageMagick 7.0.10-48 Q16 x86_64 2020-12-10 https://imagemagick.org
Copyright: \302\251 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib
Usage: import [options ...] [ file ]

Image Settings:
  -adjoin              join images into a single multi-image file
  -border              include window border in the output image
  -channel type        apply option to select image channels
  -colorspace type     alternate image colorspace
  -comment string      annotate image with comment
  -compress type       type of pixel compression when writing the image
  -define format:option
...
```

## Any other detail
I could not find any direct information
In org-mode I can insert a screenshot e.g. with something like (call-process "screencapture" nil nil nil "-s" filename)

Do you have an idea?

**Comment by djcb** [comment]
This is not really within the purview of mu/mu4e, it seems like a limitation of the libimagemagick that your emacs links with. Maybe try `M-x report-emacs-bug`?

**Comment by fab6** [comment]
Ok, thank, I just figured out that this is a function from gnus. Maybe I find more in this direction.
