### ISSUE TITLE
[mu4e] Is there a way to filter new messages based on its contents and do automatic actions?

### ISSUE THREAD

**Issue by pedrormjunior** [djcb/mu#1872]
Is there a way to filter new messages based on its contents (From, Subject, etc.) and do automatic actions (moving to certain maildir, change the flag [e.g., unread flag])?

## Expected or desired behavior

What I expect is to filter each new message (synced in the last sync) to be processed based at least on the information from the "From" field and maybe also from "Subject". Based on these information, I would like to automatically move some of those incoming messages out of the INBOX and mark them as read.*

\* I use Gmail, then, although the messages are removed from the inbox, it will be around the All Mail in case I want to find them.

## Actual behavior

I did search in the manual and here in this Github repo for a way of performing this task but I could not find a "provided" way of doing it nor any other way.

## Steps to reproduce

N/A

## Versions of mu, mu4e/emacs, operating system etc.

Partially N/A. mu4e 1.5.7.

## Any other detail

I appreciate if you let me know if I'm doing it wrong and if there is an alternative mindset for this kind of organization.

**Comment by djcb** [comment]
This is not currently easily possible, you'd need something like `procmail`. I have some ideas to one day implement is for `mu`, but... don't hold your breath.
