### ISSUE TITLE
icu v 68.2 / arch

### ISSUE THREAD

**Issue by nicolas-graves** [djcb/mu#1873]
## Expected or desired behavior

Using mu as expected.

## Actual behavior

Before any kind of other output (even with option --debug) 

`mu: error while loading shared libraries: libicuuc.so.67: cannot open shared object file: No such file or directory
`
## Steps to reproduce

Install mu from source with icu to date (v 68.2)

## Versions of mu, mu4e/emacs, operating system etc.

mu version                           : 1.5.7

Xapian version                       : 1.4.17
GLib version                         : 2.66.4
GMime version                        : 3.2.7
GTK+ version                         : 3.24.24
Webkit2/GTK+ version                 : 2.30.4
Guile version                        : 2.2.6
Build mu4e                           : yes
Emacs version                        : GNU Emacs 27.1
Build 'mug' toy-ui (gtk+/webkit)     : yes
Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
Arch to date 
icu v 68.2 (*cannot downgrade else emacs won't work*) 

## Any other detail

First contribution, please tell me if I'm doing anything wrong ;) Thanks for your outstanding work !

**Comment by nicolas-graves** [comment]
Temporary fix by : 
1) Downgrading to icu 67.1
2) Copying /usr/lib/libicu* files to a temporary folder 
3) Upgrading to icu 68.2
4) Linking the files from the temporary folder back to /usr/lib/libicu*

**Comment by djcb** [comment]
`mu` doesn't require or link to `icu` directly, and in my case, not even indirectly: 
```
% ldd /usr/local/bin/mu
	linux-vdso.so.1 (0x00007ffc15583000)
	libxapian.so.30 => /lib64/libxapian.so.30 (0x00007fa137502000)
	libgmime-3.0.so.0 => /lib64/libgmime-3.0.so.0 (0x00007fa137484000)
	libguile-3.0.so.1 => /usr/local/lib/libguile-3.0.so.1 (0x00007fa13733b000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007fa137330000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007fa1371ad000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fa137108000)
	libltdl.so.7 => /lib64/libltdl.so.7 (0x00007fa1370fa000)
	libcrypt.so.2 => /lib64/libcrypt.so.2 (0x00007fa1370c0000)
	libgc.so.1 => /lib64/libgc.so.1 (0x00007fa136e40000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007fa136c73000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007fa136c19000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fa136ae7000)
	libreadline.so.8 => /lib64/libreadline.so.8 (0x00007fa136a8f000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fa1368a7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fa136761000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa136746000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa136724000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa136559000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fa13654c000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fa136532000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fa136529000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007fa136523000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007fa13651e000)
	libgpgme.so.11 => /lib64/libgpgme.so.11 (0x00007fa1364cb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa137723000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fa1364c2000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007fa136480000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fa136453000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fa136439000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fa1363c0000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007fa136391000)
	libassuan.so.0 => /lib64/libassuan.so.0 (0x00007fa136379000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007fa136354000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007fa136320000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fa136289000)
```
so it seems to be a problem between (some specific version of) one of the dependencies... that probably something arch-specific, can't really help with that. Perhaps use the 1.4.x version from arch?

**Comment by nicolas-graves** [comment]
I have it appearing in my ldd. Also I've forgotten to say that I use Doom Emacs. I had the same error with the version from the Arch User Repository. 
The temporary fix is actually fine for me and everything works well.
