### ISSUE TITLE
mu4e-error-handler: Error 11: mu_msg_iter_new: xapian error 'Key too long:..'

### ISSUE THREAD

**Issue by faaafo** [djcb/mu#1876]
## Expected or desired behavior

Opening a specific email in the overview should open the email

## Actual behavior

On opening one specific mail I see `error in process filter: mu4e-error-handler: Error 11: mu_msg_iter_new: xapian error 'Key too long: length was 418 bytes, maximum length of a key is 255 bytes'`

## Steps to reproduce

Alas, I've never encountered this error, thus can't really tell how to reproduce. It only happens with that single email.

## Versions of mu, mu4e/emacs, operating system etc.

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28

mu (mail indexer/searcher) version 1.0

**Comment by djcb** [comment]
Can you reproduce with the current stable release (1.4.x)?

**Comment by djcb** [comment]
Closing this, feel free to (re)open if you can reproduce with 1.4.x, and include the message where this happen, thanks.
