### ISSUE TITLE
[Feature request]: the ability to remove attachments from mail

### ISSUE THREAD

**Issue by derek-zhou** [djcb/mu#1878]
## Expected or desired behavior

I frequently need to remove certain attachments (too big or obnoxious) from emails while keeping text and other parts intact. I can do this easily with mutt but sadly not with mu/mu4e. I guess this functionality is useful to others as well. Is this already planned? If not, I am willing to work on it and make a PR. I am not familiar with this codebase so it could take a while though.

**Comment by djcb** [comment]
Modifying messages is not really something for core `mu`, but if you want this, I'd recommend checking out the "actions" / "attachment actions" in the reference manual, and add a custom action that calls out an external tool like `altermime`.

**Comment by derek-zhou** [comment]
Thanks. will look into the altermime route. Another useful thing I can think of is to repair or breakup threading.
Can you reconsider your stance of not modifying messages at all in mu? There are a couple of reasons:

- I am not sure that altermime is actively maintained
- mu has this nice client/server architecture, it will be nice to fully encapsulate the Mairdir/mu database in the backend, to ensure the consistency and integrity of everything. 

Alternatively, how about to offer the core mu functionality in a library, so people can build richer tools on top of it?
