### ISSUE TITLE
Reply to everyone else

### ISSUE THREAD

**Issue by rommeswi** [djcb/mu#1880]
## Expected or desired behavior
When replying, it should be possible to reply to everyone else except for myself. Since users may have multiple email addresses, there should be a configurable list of addresses that I do not want to reply to.

## Actual behavior
Currently, "Reply all" includes my own email address, resulting in emails sent to myself.

## Steps to reproduce
Receive an email, reply to all.

## Versions of mu, mu4e/emacs, operating system etc.

mu 1.2.0

**Comment by ayman** [comment]
Is `mu4e-compose-dont-reply-to-self` set to `t`?

**Comment by djcb** [comment]
It's possible with 1.2 (think it was called `mu4e-user-mail-address-list` or something like that), but would recommend using 1.4.x, which is the supported version, and you pass your addresses to `mu init`,
