### ISSUE TITLE
How to use msg2pdf with mu on macOS Catalina?

### ISSUE THREAD

**Issue by kllale** [djcb/mu#1881]
## Expected or desired behavior

I am trying to build mu with msg2pdf enabled. From what I understand, I need WebKitGTK for the same. I am on macOS Catalina and thus the only way to acquire WebKitGTK is to build it, as far as I am aware. Any alternatives exist? Also how do I "enable" msg2pdf in mu while building it using ./autogen.sh and the subsequent steps. 

I expect that msg2pdf is installed so I can do something along the lines of 

```
(setq mu4e-msg2pdf "/usr/local/bin/msg2pdf")
```

## Actual behavior
When I run ./autogen.sh in my mu directory I get "Build 'mug' toy-ui (gtk+/webkit)     : no" . 

## Versions of mu, mu4e/emacs, operating system etc.

macOS Catalina, latest version of mu ( git clone git://github.com/djcb/mu.git), GNU Emacs 28.0.50

**Comment by kllale** [comment]
Thanks @djcb . Love mu. Hope you can help with this issue

**Comment by djcb** [comment]
Yeah, you need webkitgtk. Not sure if that's shipped with e.g. homebrew, but yeah, if not you'll need build yourself I suppose. Note that with mu4e >= 1.4 (and the new WebkitGtk), msg2pdf is not built (because it doesn't work), so perhaps it's not worth the effort.

**Comment by kllale** [comment]
Thank you. Hope in the near future you find a way for coding the msg2pdf feature again even if it is made differently.

**Comment by kllale** [comment]
Also webkitgtk, do I need to build it on mac only or will Debian Linux and other linux distros it can be installed (as it is prebuilt) ?

**Comment by djcb** [comment]
Yeah, `msg2pdf` worked with the older version of webkitgtk, but since linux distros moved to webkit2-gtk-4.x, we needed to update the `mug` & `msg2pdf` toys; the latter doesn't work yet, haven't had the time to check why.

**Comment by kllale** [comment]
So with Debian Linux and other linux distros it can be installed (as it is prebuilt) ? @djcb  Oh and Happy New Year!
