### ISSUE TITLE
Accents in view mode

### ISSUE THREAD

**Issue by myravian** [djcb/mu#1886]
Hi there,

## Expected or desired behavior

In the view-mode, the accents should be properly displayed. 

## Actual behavior

The accents are not shown properly in text view-mode (non html). All the possible UTF-8 settings in .emacs have been enabled, and accents show up when writing emails or using html-mode view. The problem is just with text view-mode. 

Is this solved by the fix to https://github.com/djcb/mu/issues/1823 maybe?

## Steps to reproduce

For bug-reports, please describe in as much details as possible how
one can reproduce the problem*.

## Versions of mu, mu4e/emacs, operating system etc.

Ubuntu 19.04, mu/mu4e 1.10

**Comment by Chris00** [comment]
@myravian Solutions [are being discussed](https://github.com/djcb/mu/issues/1823).  May you please chime in and let us know whether they fix your examples too?  Thanks.
