### ISSUE TITLE
[Feature request] Mark to send

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1888]
## Expected or desired behavior
When having multiple draft messages, I would like to be able to send multiple messages quickly.

Ideally, I would like to mark multiple messages for sending then executing the mark would actually send the messages.

## Actual behavior

At the moment, I have to open the message, press E to enter compose-mode then press C-C C-C to send a single message.

## Versions of mu, mu4e/emacs, operating system etc.
mu: 1.5.7
OS: Ubuntu

## Any other detail
Another way is implement the feature is to expose marking and execution functionality so that users can extend it with their own marks and actions. Then I would extend it with a "Send" mark.

**Comment by averter** [comment]
@haji-ali I am not sure of why this is not implemented, but **my guess** is that you can achieve the same result with a simple [keyboard macro](https://www.emacswiki.org/emacs/KeyboardMacros) which is a default feature in emacs. The developers of mu4e might presume that macros offer enough flexibility to automate sending of any kind of message(s). However, I would like to hear others people opinion as well.

**Comment by djcb** [comment]
This would be quite tricky to implement since sending mail is currently inherently an interactive process.
Anyway, the suggestion to use some keyboard macros is a good one.

Closing this, as we have no plans to implement this.
