### ISSUE TITLE
Selected message after performing action

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1889]
## Expected or desired behavior
After marking messages and executing the actions, I expect the currently selected message to stay selected.

## Actual behavior

The currently selected messages stays selected visually, but if I press enter to open that message or down to go to the message below, I find that the first message in the message view is actually selected.

## Steps to reproduce

1. Open a message header view with multiple messages
2. Select a message (MessageA) in the middle and mark to be read (for example). The next message (MessageB) is automatically selected.
3. Execute the action by pressing `x`, MessageA is marked as read and the message view is refreshed. MessageB remains selected (visually). But the point is at the beginning of the buffer.
4. Press enter to open MessageB. The first displayed message is instead opened. Alternatively, press `C-p` to select MessageA (above MessageB) and find that the first displayed message is instead selected.

## Versions of mu, mu4e/emacs, operating system etc.
mu: 1.5.7 (4dbc6ac399)
Emacs: 27.1
OS: Ubuntu

## Other details
This also happens when sending a reply. That is the previously selected message remains selected visually but the point is at the first message.

I believe this behaviour (message remains selected after executing actions) was correct before a recent update. But I am unable to find the working commit.

**Comment by haji-ali** [comment]
I think I found the reason in `mu4e~headers-found-handler` [here](https://github.com/djcb/mu/blob/086999c2d1b71f00f2235a473c900287bac9ee9c/mu4e/mu4e-headers.el#L812) where the point is supposed to jump to the previously selected message `mu4e~headers-msgid-target`. However, the point jump is inside a `save-excursion` hence the point is restored at the end. By commenting the `save-excursion` call, I am getting a better behaviour. Although I am not sure if this breaks anything else.

**Comment by djcb** [comment]
Yeah, that makes sense. Fixed.
