### ISSUE TITLE
mu daemon gets stuck cleaning up

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#1891]
## Expected or desired behavior

mu4e hangs waiting on the mu daemon to finishing cleaning up

## Actual behavior

The mu daemon is stuck in Mu::Server::Private::index_handler with index().is_running() constantly reporting true even though no other threads are running.

## Steps to reproduce

So far I haven't nailed it down to a cause, it seems to happen after some time. Possibly after a large number of large number of messages are removed from the store:

    Jan 08 14:38:08 zen mu[18553]: cannot read /home/alex/Maildir/linaro/Inbox/cur/1610057056.26814_1.zen,U=27396:2, (id=5523497); queueing for removal from store
    Jan 08 14:38:08 zen mu[18553]: remove 13906 message(s) from store
    Jan 08 14:38:08 zen mu[18553]: been waiting 85277376 μs
    Jan 08 14:41:12 zen mu[18553]: finished in 184197146 μs
    Jan 08 14:41:12 zen mu[18553]: cleanup finished in 212322893 μs
    Jan 08 14:41:12 zen mu[18553]: committing 14367 modification(s)
    Jan 08 14:43:05 zen mu[18553]: changing indexer state cleaning->idle
    Jan 08 14:43:05 zen mu[18553]: been waiting 382771581 μs
    Jan 08 14:43:06 zen mu[18553]: been waiting 383771707 μs

This continues for ever...

    Jan 08 15:13:47 zen mu[18553]: been waiting 2224305948 μs
    Jan 08 15:17:50 zen mu[18553]: been waiting 2467006978 μs

It seems the indexer is idle but the queue isn't empty:

    (gdb) bt
    #0  0x000055b6116b84b6 in Mu::Indexer::is_running() const (this=0x55b614169350) at mu-indexer.cc:357
    #1  0x000055b61168c0a6 in Mu::Server::Private::index_handler(std::vector<Mu::Sexp, std::allocator<Mu::Sexp> > const&) (this=0x55b61400a230, params=std::vector of length 5, capacity 8 = {...}) at mu-server.cc:826
    #2  0x000055b61168219c in Mu::Server::Private::<lambda(const auto:9&)>::operator()<std::vector<Mu::Sexp> >(const std::vector<Mu::Sexp, std::allocator<Mu::Sexp> > &) const (__closure=0x55b61402d170, params=std::vector of length 5, capacity 8 = {...}) at mu-server.cc:207
    #3  0x000055b611690b2a in std::_Function_handler<void(const std::vector<Mu::Sexp, std::allocator<Mu::Sexp> >&), Mu::Server::Private::make_command_map()::<lambda(const auto:9&)> >::_M_invoke(const std::_Any_data &, const std::vector<Mu::Sexp, std::allocator<Mu::Sexp> > &) (__functor=..., __args#0=std::vector of length 5, capacity 8 = {...}) at /usr/include/c++/8/bits/std_function.h:297
    #4  0x000055b6116d5205 in std::function<void (std::vector<Mu::Sexp, std::allocator<Mu::Sexp> > const&)>::operator()(std::vector<Mu::Sexp, std::allocator<Mu::Sexp> > const&)
    const (this=0x55b61402d170, __args#0=std::vector of length 5, capacity 8 = {...}) at /usr/include/c++/8/bits/std_function.h:687
    #5  0x000055b6116d409b in Mu::Command::invoke(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Mu::Command::CommandInfo, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Mu::Command::CommandInfo> > > const&, Mu::Sexp const&) (cmap=std::unordered_map with 14 elements = {...}, call=...) at mu-command-parser.cc:94
    #6  0x000055b61168689b in Mu::Server::Private::invoke(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55b61400a230, expr="(index :cleanup t :lazy-check nil)") at mu-server.cc:303
    #7  0x000055b61168fa44 in Mu::Server::invoke(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x7ffe1d924560, expr="(index :cleanup t :lazy-check nil)") at mu-server.cc:1158
    #8  0x000055b61164b4d8 in mu_cmd_server(MuConfig const*, GError**) (opts=0x55b61172ef00 <MU_CONFIG>, err=0x7ffe1d924678) at mu-cmd-server.cc:125
    #9  0x000055b61164e684 in mu_cmd_execute(MuConfig const*, GError**) (opts=0x55b61172ef00 <MU_CONFIG>, err=0x7ffe1d924678) at mu-cmd.cc:738
    #10 0x000055b61164374b in main(int, char**) (argc=1, argv=0x7ffe1d924778) at mu.cc:130
    (gdb) info threads
      Id   Target Id                              Frame
    * 1    Thread 0x7fcdd79f38c0 (LWP 18553) "mu" Mu::Indexer::is_running (this=0x55b614169350) at mu-indexer.cc:357
    Thread 1 "mu" hit Breakpoint 1, Mu::Indexer::is_running (this=0x55b614169350) at mu-indexer.cc:357
    357             return !(priv_->state_ == IndexState::Idle) || !priv_->fq_.empty();
    (gdb) p priv_->state_
    $4 = {state_ = IndexState::Idle}
    (gdb) p priv_->fq_.empty()
    $5 = false

## Versions of mu, mu4e/emacs, operating system etc.

Current HEAD of mu (4dbc6ac39907216dda04a39df467c403f590dc46). Debian Buster, Current native-comp branch of Emacs devel.

## Any other detail

I though this might be #1749 but I think the failure is different.

**Comment by djcb** [comment]
Hmmm, the latest code has some changes in this area... does this still happen?

**Comment by stsquad** [comment]
Not seen it since the latest update, keeping debug turned on and an eye out.

**Comment by stsquad** [comment]
I'm closing this as "no longer occurs due to re-factoring and clean-up".
