### ISSUE TITLE
Org-store-link to query not available

### ISSUE THREAD

**Issue by faaafo** [djcb/mu#1892]
## Expected or desired behavior

Can store link to search query in mu4e headers view

## Actual behavior

Instead the link to the message below the cursor is stored into the kill ring

## Steps to reproduce

1. In init.el `(setq mu4e-org-link-query-in-headers-mode t)`
1. Open mu4e
1. Search e.g. `search: from:..now`
1. Org-store-link on first result in headers view

## Versions of mu, mu4e/emacs, operating system etc.
mu (mail indexer/searcher) version 1.0

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28

mu4e-org-link-query-in-headers-mode’s value is t

**Comment by djcb** [comment]
Can you reproduce with 1.4.x?

**Comment by faaafo** [comment]
Upgrading was the solution. Thank you so much :rocket:
