### ISSUE TITLE
3rd argument required in define-obsolete-function-alias

### ISSUE THREAD

**Issue by olaf-rogalsky** [djcb/mu#1893]
The definition of `define-obsolete-function-alias' has changed recently:

> commit 32c6732d16385f242b1109517f25e9aefd6caa5c
> Author: Stefan Monnier <monnier@iro.umontreal.ca>
> Date:   Sun Jan 3 15:43:31 2021 -0500
>
>     * lisp/emacs-lisp/byte-run.el (make-obsolete): Make `when` mandatory
>     
>     (define-obsolete-function-alias, make-obsolete-variable)
>     (define-obsolete-variable-alias): Adjust similarly.

As far as I can tell, only `mu4e-interrupt-update-mail' in mu4e-utils.el is missing the WHEN parameter.

**Comment by djcb** [comment]
This has been updated.
