### ISSUE TITLE
How an alias (~/.mailrc) can appear in the completion list of the To:/Cc:/Bcc: headers ?

### ISSUE THREAD

**Issue by jpggithub** [djcb/mu#1897]
## Expected or desired behavior

When I create a new mail, I want to use  aliases of ~/.mailrc without typing all the letters of each alias.
With the first letters, the alias could appear in the completion list. Then I would be able to select it as a standard adress and expand it.

## Actual behavior

To use a given alias, I have to type all the letters of this alias so I have to remember the exact spelling of each alias.
To make no mistake, I have to look at ~/mailrc to see the exact spelling to type it. 

I have several alias so it is not very convenient !

## Versions of mu, mu4e/emacs, operating system etc.
mu4e v1.4.13
emacs 27.1
Debian Linux

**Comment by djcb** [comment]
That's a bit outside mu4e, I think... guess you'll need to tweak the way emacs deals with `~/.mailrc`.

**Comment by averter** [comment]
A duckduckgo search reveals [this solution](http://pragmaticemacs.com/emacs/using-email-address-lists-in-mu4e/)

**Comment by djcb** [comment]
Yeah, `mailrc` aliases are completed using the `abbrev`-system, so you'd need to look there, or perhaps someone else already has done that. Out of scope for mu4e....

**Comment by stevenbagley** [comment]
@jpggithub Partial solution: you can bind the function `mail-abbrev-complete-alias` in `mu4e-compose-mode-map`.

**Comment by jpggithub** [comment]
Sorry for my late reaction.
I tested today, it works very well. 
It would be better if it could be integrated in the standard interface but it works! :+1: 
Many thanks.

**Comment by student-sx** [comment]
> Sorry for my late reaction. I tested today, it works very well. It would be better if it could be integrated in the standard interface but it works! 👍 Many thanks.

Please could you describe more in detail what I have to add to my `init.el` file to test it?

What behavior should I expect with this partial solution?

**Comment by jpggithub** [comment]
Nothing special here ;-)

```
(add-hook 'message-mode-hook #'(lambda ()
				 (define-key message-mode-map (kbd "<s-return>") 'mail-abbrev-complete-alias)))
```

Then you hit `s-return` you can complete an alias. It works but it is a not so great workaround because you have to know the first letters of the alias that is in your `.mailrc`. I would prefer a better integration in the normal behaviour for completing the mail adresses but I'm not expert enough in Emacs lisp :/
