### ISSUE TITLE
[Feature request?] Splitting name,email in From: field

### ISSUE THREAD

**Issue by apiraino** [djcb/mu#1902]
Hi,

thanks for mu4e!

## Expected or desired behavior

When a received an email has the From field in the form of
```
Abbey Sender <abbey@sender.org>
```

I'd like the `:from` field in `mu4e-view-fields` to render it as:
```
From: Abbey Sender <abbey@sender.org>
```

## Actual behavior

The From: field is rendered as
```
From: Abbey Sender
```

## Versions of mu, mu4e/emacs, operating system etc.

Debian 10.7 bullseye, mu4e 1.4.14, emacs 27.1

## Any other detail

I've tried hacking a `:custom-from` by following the guide about [HV fields](https://www.djcbsoftware.nl/code/mu/mu4e/HV-Custom-headers.html) but I wasnt able to go further than this snippet:
```
  (add-to-list 'mu4e-header-info-custom
               '(:custom-from .
                            ( :name "From"      
                                    :shortname "From"              
                                    :function (lambda (msg)
                                                (format "%s"
                                                        (mu4e-message-field msg :from)
                                                        )))))
```

which just render something like:
```
From: ((Abbey Sender . abbey@sender.org))
```

I'm sure there a way to improve, but my poor elisp skills can't separate the pair

thanks

**Comment by djcb** [comment]
Dup.
