### ISSUE TITLE
[feature?] mu4e: splitting name,email in From field

### ISSUE THREAD

**Issue by apiraino** [djcb/mu#1903]
Hi,

thanks for mu4e!

## Expected or desired behavior

When a received an email has the From field in the form of
```
Abbey Sender <abbey@sender.org>
```

I'd like the `:from` field in `mu4e-view-fields` to render it as:
```
From: Abbey Sender <abbey@sender.org>
```

## Actual behavior

The From: field is rendered as
```
From: Abbey Sender
```

## Versions of mu, mu4e/emacs, operating system etc.

Debian 10.7 bullseye, mu4e 1.4.14, emacs 27.1

## Any other detail

I've tried hacking a `:custom-from` by following the guide about [HV fields](https://www.djcbsoftware.nl/code/mu/mu4e/HV-Custom-headers.html) but I wasnt able to go further than this snippet:
```
  (add-to-list 'mu4e-header-info-custom
               '(:custom-from .
                            ( :name "From"      
                                    :shortname "From"              
                                    :function (lambda (msg)
                                                (format "%s"
                                                        (mu4e-message-field msg :from)
                                                        )))))
```

which just render something like:
```
From: ((Abbey Sender . abbey@sender.org))
```

I'm sure there a way to improve, but my poor elisp skills can't separate the pair

thanks

**Comment by djcb** [comment]
It's a list (like all the contact fields). In the from case, just pick the first cell with `(car ...)` and you can get the name and address from the cell with `(car ...)` and `(cdr ...)`.

But there's also `mu4e-view-show-addresses`... and it's automatic in the gnus-view.

**Comment by apiraino** [comment]
> But there's also `mu4e-view-show-addresses`... and it's automatic in the gnus-view.

thank you so much, I missed that settings, it solves my question effortlessy :)

(sorry for the double issue)
