### ISSUE TITLE
org-capture stopped working

### ISSUE THREAD

**Issue by cryoguy** [djcb/mu#1905]
## Expected or desired behavior

This worked fine for me for a long time.  When I evoke org-capture with `C-c c`, the list of templates shows up in another buffer. I can pick one related to emailing defined as follows:

`  ("e" "Respond to Email" entry
      (file+headline "todo.org" "Emails")
      "* TODO Respond to %:from on %:subject :EMAIL:
:SCHEDULED: %t
%U
%a" :immediate-finish)`

## Actual behavior

This is what got right now in both views.

`command-execute: Wrong type argument: commandp, org-mu4e-store-and-capture` 

## Versions of mu, mu4e/emacs, operating system etc.

mu4e  1.5.5 and 1.5.7, org-mode 9.4, emacs 27 and Current Arch Linux

## Any other detail

Capturing from other buffer works fine including org-roam and other HTML capture. I am aware of the issue https://github.com/djcb/mu/issues/1840.

**Comment by djcb** [comment]
The function you need is `mu4e-org-store-and-capture`, I've added an alias.

**Comment by cryoguy** [comment]
@djcb Thanks for the prompt update.  Any thoughts on  why the same error after I pulled and reinstalled mu. I confirmed that the `mu4e-org.el` is updated.

**Comment by djcb** [comment]
`mu4e` itself didn't call the old method.... but perhaps something else? It might be something in your configuration, and iirc, there was an old example in the manual that used the old name...

**Comment by cryoguy** [comment]
found it https://www.djcbsoftware.nl/code/mu/mu4e/Org_002dmode-links.html#Org_002dmode-links, thanks.

change the default from this:

    `(define-key mu4e-headers-mode-map (kbd "C-c c") 'org-mu4e-store-and-capture)
     (define-key mu4e-view-mode-map    (kbd "C-c c") 'org-mu4e-store-and-capture)`

to:

    `(define-key mu4e-headers-mode-map (kbd "C-c c") 'mu4e-org-store-and-capture)
     (define-key mu4e-view-mode-map    (kbd "C-c c") 'mu4e-org-store-and-capture)`
