### ISSUE TITLE
Slow opening of messages compared to gnus

### ISSUE THREAD

**Issue by fab6** [djcb/mu#1906]
## Expected or desired behavior
Opening mails with same speed as in gnus (using same maildir directories).

## Actual behavior
Opening messages is much slower for html emails with mu4e compared to gnus.
The difference is about 2 to 3 seconds.

## Steps to reproduce
These are my settings
```
       mu4e-view-use-gnus t
       mu4e-enable-async-operations t
       mu4e-enable-notifications t
       mu4e-enable-mode-line t
       mu4e-spacemacs-layout-name "@Mu4e"
       mu4e-spacemacs-layout-binding "m"
       mu4e-spacemacs-kill-layout-on-exit t
```
and
```
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu/mu4e")
(setq mu4e-mu-binary "/usr/local/bin/mu")
(require 'mu4e)
(require 'mu4e-contrib)
(require 'smtpmail)
(setq mu4e-maildir "/Users/fbraenns/98_Maildir")
(setq mu4e-view-use-gnus t)
(setq mu4e-use-maildirs-extension t)

```

## Versions of mu, mu4e/emacs, operating system etc.
mu version 1.5.7, emacs 27.01, spacemacs development

**Comment by Chris00** [comment]
Your HTML settings are not shown.  Do you have `(setq mm-text-html-renderer 'shr)` or...?

**Comment by djcb** [comment]
Please test without 3rd-party extensions, such as spacemacs, maildirs-extension etc., and please attach a message where this happens. Thanks.

**Comment by fab6** [comment]
I actually did not have anything set for the html renderer, but just tried.
It seems that this does not have any impact on the opening of the messages.
Thank you for your help!

**Comment by fab6** [comment]
ah, sorry, did not see the new comment... yes, I will check

**Comment by theophilusx** [comment]
Just in case it helps, I'm running the same versions of mu, spacemacs
and emacs (though just upgraded to emacs 28), but am not noticing the
slow behaviour you mentioned.

Some noticeable differences in setup are

- I don't set mu4e-enable-async - I found this option caused various
issues for me, so I do not enable it
- I don't enable mu4e-enable-notifications
- I don't require mu4e-contrib
- I don't enable mu4e-maildir-extensions
- I have 3 different contexts, one gmail, one offic365 and one MS
Exchange. All the required setup is in a email.el file I load in my
dotemacs/user-config section.

Opening messages, both HTML and plain text is fast, with only slight
delays on very large html messages (which even then is only a couple of
seconds, if that). I'm using the shr library for parsing html with no
special configuration.

HTH

Tim


fab6 <notifications@github.com> writes:

> ## Expected or desired behavior
> Opening mails with same speed as in gnus (using same maildir directories).
>
> ## Actual behavior
> Opening messages is much slower for html emails with mu4e compared to gnus.
> The difference is about 2 to 3 seconds.
>
> ## Steps to reproduce
> These are my settings
> ```
>        mu4e-view-use-gnus t
>        mu4e-enable-async-operations t
>        mu4e-enable-notifications t
>        mu4e-enable-mode-line t
>        mu4e-spacemacs-layout-name "@Mu4e"
>        mu4e-spacemacs-layout-binding "m"
>        mu4e-spacemacs-kill-layout-on-exit t
> ```
> and
> ```
> (add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu/mu4e")
> (setq mu4e-mu-binary "/usr/local/bin/mu")
> (require 'mu4e)
> (require 'mu4e-contrib)
> (require 'smtpmail)
> (setq mu4e-maildir "/Users/fbraenns/98_Maildir")
> (setq mu4e-view-use-gnus t)
> (setq mu4e-use-maildirs-extension t)
>
> ```
>
> ## Versions of mu, mu4e/emacs, operating system etc.
> mu version 1.5.7, emacs 27.01, spacemacs development


--
Tim Cross

**Comment by fab6** [comment]
when turning off the spacemacs and maildirs-extension settings in combination with (setq mm-text-html-renderer 'shr) it is 'much' faster. Though it is not clear which exact setting was reducing the speed.
Thank you!
