### ISSUE TITLE
make mu-server contacts same as mu cfind

### ISSUE THREAD

**Issue by tshu-w** [djcb/mu#1915]
## Issue description
I changed the names of some of my email accounts, but `mu server` still returns the old names, which affects the completeness in `mu4e`. I would like `mu server` to return contacts names as `mu cfind` does. This issue also occurs with other email addresses that have updated their names.

## Steps to reproduce

- my old mail name: `oldname`
- my new mail name: `newname`
- mu cfind | grep <my mail address> return like: `newname <my mail address>`
- mu server and enter `(contacts :personal nil :after nil :tstamp "0")` return: `("oldname <my mail address>" . rank)`

## Versions of mu, mu4e/emacs, operating system, etc.

- mu (mail indexer/searcher) version 1.4.15
- macOS 11.1

**I sincerely hope that this pull request https://github.com/djcb/mu/pull/1696 can be merged or that the results of `mu server` contacts will be like `mu cfind`.**

**Comment by tshu-w** [comment]
BTW, set `mu4e-compose-complete-only-after` to the time the name changed doesn't help either.

**Comment by Chris00** [comment]
Did you run `mu init --maildir=~/Maildir --my-address=... --my-address=... ...` followed by `mu index`?

**Comment by tshu-w** [comment]
@Chris00 Yes, I tried to add my-address when init, but the results are still different between mu server and mu cfind.

**Comment by tshu-w** [comment]
Although it seems that some of the `mu cfind` results also do not match the current email names, it has updated or better results.

**Comment by djcb** [comment]
Is still seen with the develop (soon-to-be-stable) 1.5.x?

**Comment by tshu-w** [comment]
@djcb I'm a little busy recently. Will check when it releases.

**Comment by djcb** [comment]
Release is available!

**Comment by tshu-w** [comment]
@djcb Thanks for your efforts. I have migrated to fastmail and so far have not noticed this issue. Closed this issue for now and I will keep my eye on it.
