### ISSUE TITLE
mu4e~draft-cite-original: Wrong number of arguments: (1 . 1), 2

### ISSUE THREAD

**Issue by MatthewZMD** [djcb/mu#1918]
## Expected or desired behavior

Please describe the behavior you expect or want

Able to reply to an email

## Actual behavior

Please describe the behavior you are actually seeing.

```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  generate-new-buffer(" *temp*" t)
  mu4e~draft-cite-original((:docid 55067 :subject "...
  mu4e~draft-reply-construct((:docid 55067 :subject "...
  mu4e-draft-open(reply (:docid 55067 :subject "...
  mu4e~compose-handler(reply (:docid 55067 :subject "...
  mu4e~proc-filter(#<process  *mu4e-proc*> "\376188b\377(:compose reply :original (\n\11:docid 55067\n\11:...")
```

For bug-reports, if applicable, include error messages, emacs stack traces, example messages
etc. Try to be as specific as possible - when do you see this happening? Does it happen always?
Sometimes? How often?

## Steps to reproduce

For bug-reports, please describe in as much detail as possible how one can reproduce the problem.

Go to any email, press `R` to reply, and this error occurs.

If there's a problem with a specific (type of) message, please attach such a message to the report.

## Versions of mu, mu4e/emacs, operating system etc.

- mu 1.4.15
- Emacs 27.1
- Manjaro KDE
- config: https://github.com/MatthewZMD/.emacs.d#mu4e

## Any other detail

E.g. are you using the gnus-based message view?

**Comment by MatthewZMD** [comment]
A similar error occurs when trying to view some email:
```
generate-new-buffer(" *temp*" t)
  mu4e~view-construct-header(:attachments #("[1]2.msgpart(429)" 0 3 (face mu4e-attach-number-face) 3 12 (face mu4e-link-face keymap (keymap (S-return . mu4e~view-save-attach-from-binding) (mouse-2 . mu4e~view-save-attach-from-binding) (27 keymap (13 . mu4e~view-open-attach-from-binding)) (mouse-1 . mu4e~view-open-attach-from-binding)) mouse-face highlight help-echo "[mouse-1] or [M-RET] opens the attachment\n[mouse-2..." mu4e-msg (:docid 55550 :subject "...
  mu4e~view-construct-attachments-header((:docid 55550 :subject "...
  mu4e-view((:docid 55550 :subject "...
  mu4e~headers-view-handler((:docid 55550 :subject "...
```

**Comment by djcb** [comment]
I bet you are mixing compiled files (.elc) from different emacs versions.

**Comment by MatthewZMD** [comment]
Hah, I did switch emacs versions recently. You're right, I forgot to rebuild mu.

Everything is working now. :-)
