### ISSUE TITLE
Wrong number of arguments: (3 . 4), 2

### ISSUE THREAD

**Issue by azzamsa** [djcb/mu#1920]
## Expected or desired behavior

mu4e should open/show its dashboard.

## Actual behavior

Getting `Wrong number of arguments: (3 . 4), 2` error.

```
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
define-obsolete-function-alias: Wrong number of arguments: (3 . 4), 2
```

I can't open mu4e, every time I invoke `M-x mu4e` I get this error. For the time being, I use my webmail.

## Steps to reproduce

1. Open Emacs
2. Invoke `M-x mu4e`

## Versions of mu, mu4e/emacs, operating system, etc.

mu version:
```
❯ mu --version
mu (mail indexer/searcher) version 1.4.15
Copyright (C) 2008-2020 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

last commit:
```
76734e9d (HEAD -> release/1.4.x, tag: 1.4.15, origin/release/1.4.x) 8 days ago configure: bump version to 1.4.15 (Dirk-Jan C. Binnema)
```

OS:
```
OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-13-amd64
Shell: fish 3.0.2
```

Emacs version:

```
GNU Emacs 28.0.50 (build 7, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2021-01-25
```

## Any other detail

I get this error after I do `straight-pull-all` which then pulls all the latest revision and build them. I think the error is because I am using `maildir-utils 1.0-6` on buster, and my mu repo is `master`. So I try manually compile `mu 1.4` and check out the corresponding branch for `straight.el` to use. Sadly the problem persists.

I have tried [this](https://github.com/djcb/mu/issues/1907#issuecomment-763703479) solution, and rebuild the package according to [this fix](https://github.com/djcb/mu/issues/1918). Both don't work.

My manual build config:

```
mu configuration is complete.
------------------------------------------------
mu version                           : 1.4.15

Xapian version                       : 1.4.11
GLib version                         : 2.58.3
GMime version                        : 3.2.1
GTK+ version                         : 3.24.5
Webkit2/GTK+ version                 : 2.28.4
Emacs version                        : GNU Emacs 28.0.50

Have wordexp                         : yes
Build mu4e emacs frontend            : yes
Build 'mug' toy-ui (gtk+/webkit)     : yes

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
------------------------------------------------


Now, type 'make' (or 'gmake') to build mu
```

**Comment by theophilusx** [comment]
I was seeing a very similar error with latest head of master branch. In
my case, it is an incompatibility with mu4e-alert package. Removing that
package fixed the issue and I am able to use mu4e, but now without the
mode-line count of unread messages.

I've not dug into it further. Turning on debug-on-error is what pointed
me to where the error occurred. Try turning on debug-on-error and adding
the backtrace to the message. This will tell us whee the error is being
generated.

HTH

**Comment by azzamsa** [comment]
I have disabled all mu4e add-ons, including mu4e-alert.

Turning on debug-on-error gives me:

```elisp
Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 4) 2)
  #f(compiled-function (obsolete-name current-name when &optional docstring) "Set OBSOLETE-NAME's function definition to CURRENT-NAME and mark it obsolete.\n\n(define-obsolete-function-alias \\='old-fun \\='new-fun \"22.1\" \"old-fun's doc.\")\n\nis equivalent to the following two lines of code:\n\n(defalias \\='old-fun \\='new-fun \"old-fun's doc.\")\n(make-obsolete \\='old-fun \\='new-fun \"22.1\")\n\nWHEN should be a string indicating when the function was first\nmade obsolete, for example a date or a release number.\n\nSee the docstrings of `defalias' and `make-obsolete' for more details." #<bytecode -0xd02fb0fd08453cc>)('mu4e-interrupt-update-mail 'mu4e-kill-update-mail)
  (define-obsolete-function-alias 'mu4e-interrupt-update-mail 'mu4e-kill-update-mail)
  load-with-code-conversion("/usr/share/emacs/site-lisp/mu4e/mu4e-utils.el" "/usr/share/emacs/site-lisp/mu4e/mu4e-utils.el" nil t)
  require(mu4e-utils)
  load-with-code-conversion("/usr/share/emacs/site-lisp/mu4e/mu4e-headers.el" "/usr/share/emacs/site-lisp/mu4e/mu4e-headers.el" nil t)
  require(mu4e-headers)
  load-with-code-conversion("/usr/share/emacs/site-lisp/mu4e/mu4e.el" "/usr/share/emacs/site-lisp/mu4e/mu4e.el" nil t)
  command-execute(mu4e record)
  execute-extended-command(nil "mu4e" #("mu" 0 2 (ws-butler-chg chg)))
  funcall-interactively(execute-extended-command nil "mu4e" #("mu" 0 2 (ws-butler-chg chg)))
  command-execute(execute-extended-command)
```

Previously I've changed this function:

```elisp
(define-obsolete-function-alias 'mu4e-interrupt-update-mail
  'mu4e-kill-update-mail "1.0-alpha0")
```

to

```elisp
(define-obsolete-function-alias 'mu4e-interrupt-update-mail
  'mu4e-kill-update-mail)
```

and vice-versa. But no result

**Comment by djcb** [comment]
```
git show 1.4.15:mu4e/mu4e-utils.el | grep 'define-obsolete-function' -A 2
(define-obsolete-function-alias 'mu4e-interrupt-update-mail
  'mu4e-kill-update-mail "1.0-alpha0")
```
but the error you get is:
```
(wrong-number-of-arguments (3 . 4) 2)
```
i.e. the compiled version is outdated. Clean & rebuild.

so seems your pre-compiled emacs (.elc) files are outdated and/or done with different emacs versions -- I'd recommend clea

**Comment by azzamsa** [comment]
I have deleted:

- `/.emacs.d/eln-cache`
- `/.emacs.d/straight/build`
- `/.emacs.d/straight/build-cache.el`

I even clean & build them multiple times:

![image](https://user-images.githubusercontent.com/17734314/106440587-98c27c80-64ab-11eb-96c6-d6665ac420d3.png)

But, no luck.

Maybe next time, I need to pin a package that depend on external program.

Thank you. I will use my webmail till I find a fix.

**Comment by djcb** [comment]
Read backtrace:
```
  load-with-code-conversion("/usr/share/emacs/site-lisp/mu4e/mu4e-utils.el" "/usr/share/emacs/site-lisp/mu4e/mu4e-utils.el" nil t)
```
_that's_ the one that needs cleaning up.

**Comment by azzamsa** [comment]
aha. 

Now I am turning on `debug-on-error` to get the backtrace again. It's very stange. I have set:

```elisp
:straight (mu4e :type git :host github :repo "djcb/mu" :files ("mu/mu4e/*" (:exclude ".git")))
```

So that straight.el pickup the repo in `/.emacs.d/straight/repos/mu` instead of in the global installation. But, the backtrace always gives a global path `/usr/share`.

I look in straight.el issue, and it still [fresh](https://github.com/raxod502/straight.el/issues/491#issuecomment-760150634). So now I need to use `pre-built` and `:custom` command to point to mu binary.

This resolved my issue. I just need to delete `~/.mu` and `~/.cache/mu`. rebuilt my packages. done.
