### ISSUE TITLE
Adding indicator that message is displayed for being related

### ISSUE THREAD

**Issue by Jdogzz** [djcb/mu#1925]
## Expected or desired behavior

Please describe the behavior you expect or want:

When messages are included for being related, it would be nice if there was a flag to indicate the message is being pulled in for being related.

## Actual behavior

Please describe the behavior you are actually seeing:

Currently I see no difference between a message displayed that's truly in my inbox maildir and one that's displayed because it is related.

## Versions of mu, mu4e/emacs, operating system etc.

mu 1.5.7
mu4e 1.5.7
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0)
 of 2021-02-01
Turnkey Core 16.0

**Comment by djcb** [comment]
Dup of #1724. And yes, this features is on the roadmap.
