### ISSUE TITLE
Spewing "can't find document [X]" when query is limited

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#1926]
After #1919 (and to be specific, commit https://github.com/djcb/mu/commit/936fd3f48590903649885b8c318551c66db6633f), it seems that a query which is both limited by number of message,, threads=on related=off generates a ton of warnings of the form:

```
Feb 12 13:05:07 host mu[3071]: can't find document 54872
Feb 12 13:05:07 host mu[3071]: can't find document 54873
Feb 12 13:05:07 host mu[3071]: can't find document 54874
Feb 12 13:05:07 host mu[3071]: can't find document 54875
```

To reproduce:

mu find [some query] -t -n 1

**Comment by wavexx** [comment]
I'm afraid this fixed one case, but in the same scenario (-t -n 1) now I get "could not find [id]" from ``lib/mu-query-match-deciders.cc:226``

**Comment by djcb** [comment]
Thanks... the latest version has some additional changes that should fix that one as well.
