### ISSUE TITLE
C-x 4 m doesn't open in new window using mu4e-user-agent

### ISSUE THREAD

**Issue by sje30** [djcb/mu#1928]
## Expected or desired behavior

With 

    (setq mail-user-agent 'mu4e-user-agent)
    (compose-mail-other-window)

should open *draft* in new window.  (The desired behaviour is observed with
message-user-agent .)

## Actual behavior

*draft* appears in current window.

## Any other detail

1.4.13 with Emacs 27.1

The problem is that mu4e/mu4e-compose.el is defined as follows

    (defun mu4e~compose-mail (&optional to subject other-headers _continue
                                        _switch-function yank-action _send-actions _return-action)

where you can see _switch-function (and several other parameters) are
ignored.  Would it make sense to make mu4e~compose-mail more similar
to message-mail in this regard?

**Comment by djcb** [comment]
Sure, that'd be useful.
