### ISSUE TITLE
Strange symbols on ESC in switching context

### ISSUE THREAD

**Issue by Lenin1917** [djcb/mu#1929]
## Expected or desired behavior

In my opinion escape button, as any other, should be ignored or interpreted as C-g. At least get error via `message` function.

## Actual behavior

Strange stuff
```
map-keymap: Wrong type argument: arrayp, (keymap (75498577 . [209715296]) (67109969 . [201326688]) (8389713 . [142606432]) (1105 . [134217824]) (75498553 . [142606353]) (67109945 . [134217745]) (8389689 . [142606449]) (1081 . [134217841]) (75498566 . [142606359]) ...)
```

## Steps to reproduce
1. Type ";" in *mu4e-main* 
2. Press escape button
3. Strange stuff.

## Versions of mu, mu4e/emacs, operating system etc.

OS: GNU GUIX
emacs: 28.0.5
mu4e: 1.4.15

## Any other detail

I have only one context

**Comment by djcb** [comment]
Can you include the elisp backtrace?

**Comment by Lenin1917** [comment]
How can I get backtrace?

**Comment by djcb** [comment]
`M-x toggle-debug-on-error`
and reproduce.

**Comment by Lenin1917** [comment]
https://paste.debian.net/1185591/

**Comment by djcb** [comment]
The bug template explicitly asks for turning off any 3rd party extensions,  but I see:
```
reverse-im-read
```
sorry, but I don't have time to debug the mu4e and interaction with 3rd-party extensions.
