### ISSUE TITLE
mu4e-headers-mark-subthread no longer works

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1930]
## Expected v.s. actual behavior & steps to reproduce

When pressing, say, <kbd>t</kbd><kbd>m</kbd><kbd>o</kbd> in `*mu4e-headers*` (or any other key combination starting with <kbd>t</kbd> i.e., `mu4e-headers-mark-subthread`), only the current message is marked, not the whole thread.  

Workaround: Marking several messages with an active region works.

## Versions of mu, mu4e/emacs, operating system etc.

Mu commit 45655da9
Emacs 27.1
OS: Debian GNU/Linux

**Comment by djcb** [comment]
Is that still happening with `master`?

**Comment by Chris00** [comment]
It does.
