### ISSUE TITLE
Wrong prefix for messages without a parent

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1933]
## Expected or desired behavior

I expect the thread view to be displayed correctly when a message is part of a thread but does not have a parent.

## Actual behavior
See the attached screen shot (of partially redacted message).
![Screenshot from 2021-02-19 18-27-20](https://user-images.githubusercontent.com/17233936/108557847-0a465b80-72f1-11eb-9f10-e80f79db42d1.png)

The message `Re: vacation` is completely unrelated to the message above. 

## Steps to reproduce

Have an orphan message (which is part of a thread) but without a parent and enable thread view.

## Versions of mu, mu4e/emacs, operating system etc.
mu: 1.5.8
Emacs: 27.1
OS: Ubuntu

## Any other detail

When I select the first message "Re: vacation..." above and call `(mu4e-message-field (mu4e-message-at-point) :thread)`, I get back
`(:path "02:ff:z" :level 1 :date "" :empty-parent t)` (I was expecting to get `:first-child t`).

and when I call `(mu4e~headers-thread-prefix (mu4e-message-field (mu4e-message-at-point) :thread))`, I get back `"│ "`.

**Comment by theophilusx** [comment]
Just confirming I am seeing the same behaviour with latest HEAD from
repository with Emacs 27.1.91
