### ISSUE TITLE
mu4e can't find mailbox folders under windows

### ISSUE THREAD

**Issue by baracunatana** [djcb/mu#1936]
## Expected or desired behavior

Mu4e works in windows systems (under MSys2)

## Actual behavior

Mu4e can't move messages because it can't find mailbox folders. It keeps asking to create folders (that are already created) and is unable to move messages between folders.

## Steps to reproduce

Compile emacs, isync, and mu/mu4e under MSys2. Use mbsync to pull messages. Use mu4e to move a message to the archive folder and it'll ask to create the folder. Say "yes" and try again. Mu4e will ask to create the folder again.

## Versions of mu, mu4e/emacs, operating system etc.
Vanilla Emacs 27 on windows 10 (Using MSys2)
Mu 1.4.10 (Using MSys2)

## Any other detail
Apparently, the problem is that the function `mu4e-root-maildir` returns a path starting with "/c/Users/....", which is wrong for windows systems. It is just a matter of replacing the "/c/" with "c:/". The following lines in the .emacs files fixes the issue:
```
  (when (eq window-system 'w32)
    (defun j/mu4e-maildir-hack (maildir-path)
      (replace-regexp-in-string "/c/" "c:/" maildir-path))
    (advice-add 'mu4e-root-maildir 
                :filter-return #'j/mu4e-maildir-hack))
```

My question now is, is there a better way of fixing this problem? 
Also, this has work fine for now (after very light testing), but are there any side effects to this?

**Comment by djcb** [comment]
Guess the replace-regex could replace too much ('/c' elsewhere in path), and wouldn't handle e.g. `d:`. Ideally, the mu server would give the windows-style path.

What does `mu info` give you? And did you pass `--maildir=c:/Users ..` etc. to `mu init`?

**Comment by pRot0ta1p** [comment]
Similar problem, what I use is [cygwin-mount.el](https://www.emacswiki.org/emacs/cygwin-mount.el), but even with this, mu4e still complians about not finding correct path when sending mail.

And  after init mu with `mu init --maildir=e:/home/.maildir`, mu info give me:
```
maildir           : /e/home/.maildir
database-path     : /e/home/.cache/mu/xapian
schema-version    : 451
max-message-size  : 100000000
batch-size        : 250000
messages in store : 0
created           : Fri, Mar 19, 2021  3:36:00 PM
...
```

**Comment by djcb** [comment]
Unfortunately we don't have much Windows experience in the `mu` team, so we cannot support this... Perhaps this can change if someone steps up for this. 

At least for now, closing this, Sorry!
