### ISSUE TITLE
Invalid search bound (wrong side of point) when sending message, depending on content of message

### ISSUE THREAD

**Issue by plantarum** [djcb/mu#1938]
## Expected or desired behavior

I can normally compose and send messages without problem. Sometimes this fails:

## Actual behavior

Sometimes sending the message (via `C-c C-c`) fails with the error `(error "Invalid search bound (wrong side of point)")`. This happens with replies or new messages, but not consistently. It may depend on the content of the message.

## Steps to reproduce

The most recent time this happened, I narrowed it down to the following minimal failing message: 

```
User-agent: mu4e 1.5.8; emacs 28.0.50
From: XXXXX
To: XXXXXX
Subject: test a
Date: Mon, 01 Mar 2021 21:49:57 -0500
Fcc: XXXXX
 Items/cur/1614653419.80bb70b9458c5757.XXXXXX:2,S
Message-ID: <xlzfceegynuac.fsf@XXXXXX>
--text follows this line--
grid <- dyn(glob = flip,
                                         sp = flip(scores.test, 1))
```

This fails with the following trace:

```
Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
  re-search-backward("[ \11]\\|\\c|.\\|.\\c|" 108 0)
  fill-move-to-break-point(108)
  fill-region-as-paragraph(26 #<marker (moves after insertion) at 93 in  *temp*-216680> t nosqueeze)
  fill-region(26 93 t nosqueeze to-eop)
  fill-flowed-fill-buffer()
  fill-flowed-encode()
  mml-generate-mime-1((part (type . "text/plain") (contents . #("grid <- dyn(glob = flip,\n                         ..." 24 25 (hard t) 92 94 (hard t)))))
  mml-generate-mime(nil nil)
  message-encode-message-body()
  message-send-mail(nil)
  message-send-via-mail(nil)
  message-send(nil)
  message-send-and-exit(nil)
  funcall-interactively(message-send-and-exit nil)
  call-interactively(message-send-and-exit nil nil)
  command-execute(message-send-and-exit)
```

I can send the message by deleting a single space in the second line:

```
grid <- dyn(glob = flip,
                                        sp = flip(scores.test, 1))
```

This message goes out as expected.

I have had similar errors with different messages, so I don't know that it's always an excess of spaces that causes the problem. This is just the first time I narrowed it down to a single character difference between success and failure.

## Versions of mu, mu4e/emacs, operating system etc.
User-agent: mu4e 1.5.8; 
emacs 28.0.50
Ubuntu 18.04

**Comment by djcb** [comment]
Ah, this is specific for `mu4e-compose-format-flowed`. Don't think this is mu4e-specific, but we can add a workaround.

**Comment by djcb** [comment]
Pushed a work-around (to silence the error)
