### ISSUE TITLE
Treating everythin in mu4e-drafts-folder as drafts. (For Gmail)

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#1939]
## Expected or desired behavior

I am writing a draft message in GMail and _not_ sending it. By default Gmail places it into the [Gmail]/Drafts IMAP folder, but does _not_ tag as a "draft". Then I synchronize mailboxes using mbsync. Mbsync obediently places this message into mu4e-drafts-folder, but does _not_ set the "draft" tag, because the server copy does not have one. I go to the Drafts directory by typing j drafts RET, find my message, open with RET, and type E for Edit. Then I edit the message and send it as usual. When sending this message, I am not sure whether I should expunge the message, or GMail expunges the draft itself on the completion of the sending operation.

## Actual behavior

In the simplest case, when I write a message in the web interface, and leave it unsent, it gets synchronised by mbsync into `mu4e-drafts-folder`, but this message is not editable. I cannot, therefore, check whether mu4e should delete the draft after sending.

Moreover, as far as I understand, if mbsync runs while I am editing the message, there will be _two_ copies of the message in the "Drafts", one with the drafts flag, and one without.

## Steps to reproduce

1. Write a message in the Gmail web interface.
2. Synchronise with mbsync.
3. Try to edit with mu4e.

## Versions of mu, mu4e/emacs, operating system etc.

1.4.15, xapian 1.4.18, Linux 5.10.19, Glibc 2.33.

## Any other detail

E.g. are you using the gnus-based message view? No, I don't.

**Comment by djcb** [comment]
This is something for your syncing program, I think. It should mark draft messages as such, as per the Maildir spec.

Mu trying to second-guess is error-prone (draft-folders are runtime-decided, context-specific etc.), and draft folders does not have to be distinct from other folders.

**Comment by lockywolf** [comment]
Fair point. What's the correct mu (or sed) incantation to mark everything in the drafts folder as drafs? Not a competing complaint, just maybe you know?
