### ISSUE TITLE
Emacs 27.1 + mu4e  Undefined variables

### ISSUE THREAD

**Issue by cfenell** [djcb/mu#1940]
# I am running mu4e in Emacs 27.1 on Debian testing, and encounter issues with undefined variables etc now and then.
This may be a local configuration issue but I have not been able to find any answers in the documentation or by searching support forums, thus I ask here.
Best regards Carl-Fredrik

1. Fails to open .eml attachments.

## Expected or desired behavior
Decrypts and opens .eml attachment.

## Actual behavior
Symbol's value as variable is void: verify

## Steps to reproduce
Try to open .eml attachment: o -> Number.
A -> e -> Number may work.

2. Fails to save attachments over Tramp / ssh.

## Expected or desired behavior

Save attachments as /ssh:path.to,server:file
This works fine in other Emacs buffers at tested location.

## Actual behavior
Claims that path does not exist.
Traceback (actual location changed to "my.server"; the location is writable): 

Debugger entered--Lisp error: (error "Error 2: failed to save part: could not open '/ssh...")
  signal(error ("Error 2: failed to save part: could not open '/ssh..."))
  error("Error %d: %s" 2 "failed to save part: could not open '/ssh:my.server...")
  (cond ((eql errcode '4) (user-error "No matches for this search query.")) (t (error "Error %d: %s" errcode errmsg)))
  mu4e-error-handler(2 "failed to save part: could not open '/ssh:my.server....")
  funcall(mu4e-error-handler 2 "failed to save part: could not open '/ssh:my.server...")
  (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func sexp)) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts) (plist-get sexp :tstamp))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move) (plist-get sexp :maybe-view))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp)))
  (while sexp (mu4e-log 'from-server "%S" sexp) (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func sexp)) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts) (plist-get sexp :tstamp))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move) (plist-get sexp :maybe-view))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp))) (setq sexp (mu4e~proc-eat-sexp-from-buf)))
  (let ((inhibit-quit nil)) (while sexp (mu4e-log 'from-server "%S" sexp) (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func sexp)) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts) (plist-get sexp :tstamp))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move) (plist-get sexp :maybe-view))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp))) (setq sexp (mu4e~proc-eat-sexp-from-buf))))
  (condition-case nil (let ((inhibit-quit nil)) (while sexp (mu4e-log 'from-server "%S" sexp) (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func sexp)) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts) (plist-get sexp :tstamp))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move) (plist-get sexp :maybe-view))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp))) (setq sexp (mu4e~proc-eat-sexp-from-buf)))) (quit (setq quit-flag t) (eval '(ignore nil))))
  (let ((sexp (mu4e~proc-eat-sexp-from-buf))) (condition-case nil (let ((inhibit-quit nil)) (while sexp (mu4e-log 'from-server "%S" sexp) (cond ((plist-get sexp :date) (funcall mu4e-header-func sexp)) ((plist-get sexp :found) (funcall mu4e-found-func (plist-get sexp :found))) ((plist-get sexp :view) (funcall mu4e-view-func (plist-get sexp :view))) ((plist-get sexp :erase) (funcall mu4e-erase-func)) ((plist-get sexp :sent) (funcall mu4e-sent-func (plist-get sexp :docid) (plist-get sexp :path))) ((plist-get sexp :pong) (funcall mu4e-pong-func sexp)) ((plist-member sexp :contacts) (funcall mu4e-contacts-func (plist-get sexp :contacts) (plist-get sexp :tstamp))) ((plist-get sexp :update) (funcall mu4e-update-func (plist-get sexp :update) (plist-get sexp :move) (plist-get sexp :maybe-view))) ((plist-get sexp :remove) (funcall mu4e-remove-func (plist-get sexp :remove))) ((plist-get sexp :compose) (funcall mu4e-compose-func (plist-get sexp :compose) (plist-get sexp :original) (plist-get sexp :include))) ((plist-get sexp :temp) (funcall mu4e-temp-func (plist-get sexp :temp) (plist-get sexp :what) (plist-get sexp :docid) (plist-get sexp :param))) ((plist-get sexp :info) (funcall mu4e-info-func sexp)) ((plist-get sexp :error) (funcall mu4e-error-func (plist-get sexp :error) (plist-get sexp :message))) (t (mu4e-message "Unexpected data from server [%S]" sexp))) (setq sexp (mu4e~proc-eat-sexp-from-buf)))) (quit (setq quit-flag t) (eval '(ignore nil)))))
  mu4e~proc-filter(#<process  *mu4e

## Steps to reproduce

Save attachment to Tramp path /ssh:...

## Versions of mu, mu4e/emacs, operating system etc.
Debian testing (bullseye)
mu (mail indexer/searcher) version 1.4.15
mu for emacs version 1.4.15
IMAP maildir sync with   
  mbsync --version 
  isync 1.3.0

## Any other detail

I have disabled mu4e-org settings.

**Comment by djcb** [comment]
Files are save by `mu`, not `mu4e`, so `tramp` paths won't work, that's as expected.

However, you can use the new experimental gnus-based viewer which does things on the emacs side.
```
(setq mu4e-view-use-gnus t)
```
