### ISSUE TITLE
Mu4e open mail in raw form only and error with no message at point

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1943]
## Expected or desired behavior

Beeing able to read mails.

## Actual behavior

When pressing RET from headers view, the message is displayed in raw form and not formatted properly ending with a mu4e error "no message at point".

For bug-reports, if applicable, include error messages, emacs stack traces, example messages
etc.

No error and no traces for now.

## Versions of mu, mu4e/emacs, operating system etc.

last from git, emacs-28.0.50 build with native-compile but the bug is reproductible as well in emacs-27.
## Any other detail

E.g. are you using the gnus-based message view?

yes. (I figured out I had to require mu4e-view-gnus, this not done by default even if gnus view is now the default).

No more infos for now, I will investigate further and tell you if I find something new.

Thanks.

**Comment by djcb** [comment]
Hmm, how do you load mu4e? Do you have a backtrace?

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema ***@***.***> writes:

> Hmm, how do you load mu4e?

As Usual, M-x mu4e

> Do you have a backtrace?

Not yet, only a message something like "Mu4e:no message at point".
Sending now from a older mu4e version.
I will try to bissect ASAP to tell you exactly when it break (pretty
sure it break after splitting mu4e-view-gnus).
 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

**Comment by theophilusx** [comment]
Just FYI, I'm not seeing this issue with latest version under Emacs 27.
It could be something related to native-comp?

One thing I do when there has been a fair bit of file refactoring is to
actually delete the /usr/local/share/emacs/site-lisp/mu4e directory before
running make install rather than just running make install. Probably not
needed, but I have been burnt by old files being left around in the past
(usually because something in my setup was doing an explicit require).

--
Tim Cross

**Comment by thierryvolpiatto** [comment]
Tim Cross ***@***.***> writes:

> [1. PGP/MIME version information --- application/pgp-encrypted]...


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I think I found what's wrong, this is in `mu4e~view-gnus`, this is fixing it:

```diff
diff --git a/mu4e/mu4e-view-gnus.el b/mu4e/mu4e-view-gnus.el
index c1b9272e..96fb0b27 100644
--- a/mu4e/mu4e-view-gnus.el
+++ b/mu4e/mu4e-view-gnus.el
@@ -30,6 +30,9 @@
 (require 'mu4e-view-common)
 (require 'calendar)
 (require 'gnus-art)
+(defvar-local mu4e~view-message nil
+  "The message being viewed in view mode.")
+(put 'mu4e~view-message 'permanent-local t)
 
 ;;; Variables
 
@@ -75,11 +78,12 @@
           (gnus-display-mime-function (mu4e~view-gnus-display-mime msg))
           (gnus-icalendar-additional-identities
            (mu4e-personal-addresses 'no-regexp)))
-      (mu4e-view-mode)
+      ;; (mu4e-view-mode)
       (gnus-article-prepare-display))
     (setq mu4e~gnus-article-mime-handles gnus-article-mime-handles)
     (setq mu4e~view-message msg)
     ;; `mu4e-view-mode' derive from `gnus-article-mode'.
+    (mu4e-view-mode)
     (mu4e~view-make-urls-clickable)
     (setq gnus-article-decoded-p gnus-article-decode-hook)
     (set-buffer-modified-p nil)

```

The reason is that mu4e-view-mode is called before mu4e~view-message is set, now it is working.

**Comment by djcb** [comment]
Thanks, @thierryvolpiatto 

Hmmm, that can't be the whole explanation, since it works for me as-is. Are you using some `mu4e-view-mode-hook`?

 `mu4e~view-message` is defined in `mu4e-vars.el`, which is required from `mu4e-view-common.el` and that one from `mu4e-view.el`, so we don't need the extra defvar.

But, when hooks are involved, indeed we should set `mu4e~view-message` before invoking that. I pushed some commits that do that... does that help?

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema ***@***.***> writes:

> Thanks, @thierryvolpiatto
>
> Hmmm, that can't be the whole explanation, since it works for me
> as-is. Are you using some mu4e-view-mode-hook?

Yes:
    (add-hook 'mu4e-view-mode-hook 'smiley-buffer)
    (add-hook 'mu4e-view-mode-hook 'mu4e-mark-region-code)

> mu4e~view-message is defined in mu4e-vars.el, which is required from
> mu4e-view-common.el and that one from mu4e-view.el, so we don't need
> the extra defvar.

Ah, yes, was unsure so I declared it here to be sure, thanks.

> But, when hooks are involved, indeed we should set mu4e~view-message
> before invoking that. I pushed some commits that do that... does that
> help?

Yes that fixed it, thanks.

However I have several more issues (will make separate bug reports),
just a summary here:

- mu4e-view-gnus is not declared, so I have errors if I don't declare it
before starting mu4e (I put (require 'mu4e-view-gnus) in mu4e-view.el to
fix it for now).

- When replying reference to the email I am replying to is not inserted
(I am not using Master branch to reply to this email)

- When replying the .gnus.el is loaded! and if the gnus.el file is not
at its place .emacs.d for me I have an error (I thing this issue is much
older and not related to recent changes).

- In mu4e-view-common.el the header is mu4e-view-utils.el but this is a
minor issue not affecting mu4e usage.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Tim Cross ***@***.***> writes:

> Just FYI, I'm not seeing this issue with latest version under Emacs 27.
> It could be something related to native-comp?

No, same with emacs-27.

> One thing I do when there has been a fair bit of file refactoring is to
> actually delete the /usr/local/share/emacs/site-lisp/mu4e directory before
> running make install rather than just running make install. Probably not
> needed, but I have been burnt by old files being left around in the past
> (usually because something in my setup was doing an explicit require).

Normally make is handling this, generally there is a rule in makefile
telling make to delete old .el and .elc file before copying new ones
@djcb correct me if I am wrong.

Thanks.

-- 
Thierry

**Comment by djcb** [comment]
@thierryvolpiatto:
- what error do you get because "mu4e-view-gnus is not declared"?
- when I reply to messages, the message-id of the replied-to message appears as "In-reply-to:" here... do you see something else?
- I don't have a `.gnus.el`, and it's not being loaded; could there be something in your config that triggers loading it?

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> @thierryvolpiatto:
>
>   • what error do you get because "mu4e-view-gnus is not declared"?

mu4e-view-mode-map is not defined when I bind some keys there from my
config file, I have to require mu4e-view-gnus before doing that.

>   
>   • when I reply to messages, the message-id of the replied-to message
>   appears as "In-reply-to:" here... do you see something else?

I found what's wrong here, see bug #1945.

>   • I don't have a .gnus.el, and it's not being loaded; could there be
>   something in your config that triggers loading it?

Yes, in gnus config, forget it, sorry.


-- 
Thierry

**Comment by djcb** [comment]
Ah, thanks. Pushed a change for the decryption thing (might change it a bit later, but let's make it at least roughly work for now).

The keymap is interesting... it is only decided whether we use the one for "view-old" or "view-gnus" during runtime, we may need to do something special so it works with adding bindings.

**Comment by Chris00** [comment]
> mu4e-view-mode-map is not defined when I bind some keys there from my config file, I have to require mu4e-view-gnus before doing that.

I stumbled on the same “problem”. I guess it is the intended way of selecting Gnus given the two modes are now incompatible — [no way to switch between the two](https://github.com/djcb/mu/blob/master/mu4e/mu4e-view.el#L59) anymore.

**Comment by thierryvolpiatto** [comment]
Christophe Troestler ***@***.***> writes:

>     mu4e-view-mode-map is not defined when I bind some keys there from my config file, I have to require mu4e-view-gnus before doing that.
>    
> I stumbled on the same “problem”. I guess it is the intended way of
> selecting Gnus given the two modes are now incompatible — no way to
> switch between the two anymore.

Yes, but mu4e-view-mode-map is defined in mu4e-gnus-view.el.

>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

**Comment by Chris00** [comment]
I concur—I needed to adapt my settings too.

**Comment by djcb** [comment]
That shouldn't be necessary with the latest (`2437dc27`).
