### ISSUE TITLE
Wrong display in header-view when viewing the message

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1944]
## Expected or desired behavior

The email should only take one line in `*headers-view*`.

## Actual behavior

![mu4e](https://user-images.githubusercontent.com/1255665/111219142-f59b7180-85d7-11eb-8c06-bfaacea816bb.png)

The line should not show the newline between the names in the `To:` field.

## Steps to reproduce

Use the [following message](https://github.com/djcb/mu/files/6144337/test-header.txt) and change the `From:` field to one of your emails so that the `To:` field is displayed.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e: commit cbda30ef
Emacs 27.1

**Comment by djcb** [comment]
Oh, interesting case... I'll prepare a fix.

While you are here... I've fixed most non-"obsolete function" compiler warnings in the build, but I'm still seeing: 
```
In mu4e-icalendar-reply:
mu4e-icalendar.el:104:60: Warning: Unused lexical variable
    `gnus-icalendar-find-if'

In mu4e~icalendar-setup-sent-hook-fn:
mu4e-icalendar.el:177:39: Warning: reference to free variable ‘original-msg’
```
and idea on how to best fix those? Thanks!

**Comment by Chris00** [comment]
> While you are here... I've fixed most non-"obsolete function" compiler
> warnings in the build, but I'm still seeing:
>
> In mu4e-icalendar-reply:
> mu4e-icalendar.el:104:60: Warning: Unused lexical variable
>     `gnus-icalendar-find-if'
>
> In mu4e~icalendar-setup-sent-hook-fn:
> mu4e-icalendar.el:177:39: Warning: reference to free variable ‘original-msg’
>
> and idea on how to best fix those? Thanks!

I'll try to take a look ASAP.  Probably just tweaking some `require`.

**Comment by Chris00** [comment]
> While you are here... I've fixed most non-"obsolete function" compiler warnings in the build, but I'm still seeing:

[Fixed](https://github.com/djcb/mu/pull/1950).
