### ISSUE TITLE
When replying from an encrypted email, reference is no more inserted as plain text

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1945]
## Expected or desired behavior

Actually when replying the body of previous email is inserted as a mime type button:

![Capture d’écran_2021-03-16_07-29-59](https://user-images.githubusercontent.com/1533939/111265637-b5fd7580-8629-11eb-9a83-9af5e35e8e38.png)

I expect the reference to previous email decrypted and inserted:

![Capture d’écran_2021-03-16_07-31-24](https://user-images.githubusercontent.com/1533939/111265743-db8a7f00-8629-11eb-83ae-4d7c8ef67cae.png)

The reason is that `mm-decrypt-option` is let-bounded to 'never in `mu4e-view-message-text`, commenting it is fixing bug:

```diff
diff --git a/mu4e/mu4e-view-gnus.el b/mu4e/mu4e-view-gnus.el
index e335f41c..174aa208 100644
--- a/mu4e/mu4e-view-gnus.el
+++ b/mu4e/mu4e-view-gnus.el
@@ -375,7 +375,7 @@ Gnus' article-mode."
   (with-temp-buffer
     (let ((path (mu4e-message-field msg :path))
           (inhibit-read-only t)
-          (mm-decrypt-option 'never)
+          ;; (mm-decrypt-option 'never)
           (gnus-article-emulate-mime t))
       (buffer-disable-undo)
       (insert-file-contents-literally path nil nil nil t)

```

**Comment by djcb** [comment]
This has been fixed, thanks.
