### ISSUE TITLE
Some Gnus article mode bindings don't work anymore on the current master

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#1946]
I use the gnus-based viewer (­­­`mu4e-view-use-gnus`is `t`) and the current `master` branch of mu4e (commit 931cfe5d8670f04767c920c65285fd2a0027a589).

Probably since 44d801e2b0bb854b3e2557178e7dab801bbb6e64, some commonly used bindings don't work anymore in a message view buffer.  The two I've found until now are:
* TAB used to move point between clickable items like mail addresses, URLs, and attachments.  Now it is bound to `indent-for-tab-command` signalling that the buffer is read-only.
* RET on an attachment used to be bound to `gnus-article-push-button` which opened the URL or attachment at point.  Now it is bound to some anonymous mu4e function which scrolls up but errors on a link:
```
Debugger entered--Lisp error: (wrong-type-argument consp t)
  widget-apply(t :active)
  widget-apply-action(t nil)
  widget-button-press(254)
  #f(compiled-function () (interactive nil) #<bytecode -0x407f2d3cab4644a>)()
  funcall-interactively(#f(compiled-function () (interactive nil) #<bytecode -0x407f2d3cab4644a>))
  call-interactively(#f(compiled-function () (interactive nil) #<bytecode -0x407f2d3cab4644a>) nil nil)
  command-execute(#f(compiled-function () (interactive nil) #<bytecode -0x407f2d3cab4644a>))
```

There are probably more bindings which don't work anymore and which I haven't encounterd yet.  I'll update the report when I find more.

**Comment by djcb** [comment]
Yeah, mu4e-view-gnus no longer inherits the keymap from gnus-article-mode; this avoids getting a bunch of bindings (and menu items) that don't work, but it also removes some useful ones.

I'll repair the ones that are b0rked now.

**Comment by tsdh** [comment]
Yep, works again using `M-RET` instead of `RET` which is actually better given that previously I frequently had the issue that I scrolled with `RET` until point was on a link and the next `RET` opened the URL although I just wanted to scroll further up.
