### ISSUE TITLE
Error building mu4e (HEAD)

### ISSUE THREAD

**Issue by lbolla** [djcb/mu#1947]
## Expected or desired behavior

Running `make` succeeds.

## Actual behavior

When I run `make`, I get this compilation error when compiling ".el" files:
```
make[3]: Entering directory '/home/lbolla/src/github.com/djcb/mu/mu4e'
if test "emacs" != "no"; then \
  am__dir=. am__subdir_includes=''; \
  case mu4e-actions.elc in */*) \
    am__dir=`echo 'mu4e-actions.elc' | sed 's,/[^/]*$,,'`; \
    am__subdir_includes="-L $am__dir -L ./$am__dir"; \
  esac; \
  test -d "$am__dir" || /bin/mkdir -p "$am__dir" || exit 1; \
  emacs --batch \
      \
    $am__subdir_includes -L . -L . \
    --eval "(defun byte-compile-dest-file (f) \"mu4e-actions.elc\")" \
    --eval "(unless (byte-compile-file \"mu4e-actions.el\") (kill-emacs 1))"; \
else :; fi
Warning (bytecomp): Changing ‘byte-compile-dest-file’ is obsolete (as of 23.2);
set ‘byte-compile-dest-file-function’ instead.
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-writable-p(nil)
  byte-compile-file("mu4e-actions.el")
  (if (byte-compile-file "mu4e-actions.el") nil (kill-emacs 1))
  (unless (byte-compile-file "mu4e-actions.el") (kill-emacs 1))
  eval((unless (byte-compile-file "mu4e-actions.el") (kill-emacs 1)) t)
  command-line-1(("-L" "." "-L" "." "--eval" "(defun byte-compile-dest-file (f) \"mu4e-actions.el..." "--eval" "(unless (byte-compile-file \"mu4e-actions.el\") (kil..."))
  command-line()
  normal-top-level()

Makefile:716: recipe for target 'mu4e-actions.elc' failed
make[3]: *** [mu4e-actions.elc] Error 255
```

## Versions of mu, mu4e/emacs, operating system etc.

Using latest mu from git (commit b7660ed33de0612dbf695ee07605c01efa9c7b6e)
Emacs version is: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-12-16
OS: Ubuntu 18.04

**Comment by thierryvolpiatto** [comment]
Lorenzo Bolla ***@***.***> writes:

> When I run make, I get this compilation error when compiling ".el" files:

Did you run ./autogen.sh before make ?


-- 
Thierry

**Comment by lbolla** [comment]
@thierryvolpiatto I did, yes. It's weird because I can see the right Emacs function mentioned in `meson.build` but `mu4e/Makefile` contains the obsolete one. I also tried to `rm mu4e/Makefile mu4e/Makefile.in` and then do `./autogen.sh` and the Makefiles have been recreated with the obsolete function. I am not sure where it's coming from...

**Comment by djcb** [comment]
The obsolete function warning is expected, it's an artifact of the autotools elisp-compilation machinery. 

Something might be wrong with your setup (perhaps emacs or autotools).

Perhaps try a stable emacs version, or build with meson if you have that installed, `meson build && ninja -C build`.

**Comment by tsdh** [comment]
@djcb I've just tried building with `meson build && ninja -C build` from a clean checkout but that fails because `mu4e-meta.el` is not generated from `mu4e-meta.el.in`.  You still have to run `./autogen.sh` to have that.  And then the info generation fails with:
```
[27/27] Generating mu4e_info with a custom command
FAILED: mu4e/mu4e.info
/usr/bin/makeinfo -o /home/horn/Repos/el/mu/build/mu4e/mu4e.info /home/horn/Repos/el/mu/mu4e/mu4e.texi
/home/horn/Repos/el/mu/mu4e/mu4e.texi:3: @include: could not find version.texi
/home/horn/Repos/el/mu/mu4e/mu4e.texi:6: warning: undefined flag: VERSION
/home/horn/Repos/el/mu/mu4e/mu4e.texi:29: warning: undefined flag: VERSION
/home/horn/Repos/el/mu/mu4e/mu4e.texi:29: warning: undefined flag: UPDATED
/home/horn/Repos/el/mu/mu4e/mu4e.texi:55: warning: undefined flag: VERSION
ninja: build stopped: subcommand failed.
```
Normal `./autogen.sh && make` works, though.

**Comment by djcb** [comment]
Ah, indeed the meson build was relying on some autotools things... fixed.

**Comment by djcb** [comment]
It should look like:
```make[1]: Entering directory '/home/djcb/Sources/mu/mu4e'
if test 'emacs' != no; then \
  am__dir=. am__subdir_includes=''; \
  case mu4e-actions.elc in */*) \
    am__dir=`echo 'mu4e-actions.elc' | sed 's,/[^/]*$,,'`; \
    am__subdir_includes="-L $am__dir -L ./$am__dir"; \
  esac; \
  test -d "$am__dir" || /usr/bin/mkdir -p "$am__dir" || exit 1; \
  emacs --batch \
      \
    $am__subdir_includes -L . -L . \
    --eval '(if (boundp (quote byte-compile-dest-file-function)) (setq byte-compile-dest-file-function (lambda (_) "mu4e-actions.elc")) (defun byte-compile-dest-file (_) "mu4e-actions.elc") )' \
    -f batch-byte-compile 'mu4e-actions.el'; \
else :; fi
Warning (bytecomp): Changing ‘byte-compile-dest-file’ is obsolete (as of 23.2);
```

**Comment by lbolla** [comment]
@djcb I am using `automake (GNU automake) 1.15.1`.

**Comment by djcb** [comment]
Okay, that explains the (slightly different) elisp compilation output, there's a snippet 
```
/usr/share/automake-1.16/am/lisp.am
```
that does the compiling.

Anyway, I'm sure it should work with 1.15.1 as well. I'm suspecting it has something to do with emacs 28.1 and perhaps some elc mixup between versions. So, unfortunately, I don't think there's anything we can do from mu4e's perspective... emacs 28.1 works here, but this may be some rough edge.

Note that you can try the released emacs version (27.x) or use the `meson` recipe mentiond.
