### ISSUE TITLE
No sent folder set with mails initiated by clicking on a mail address in some header with current master

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#1949]
I'm running the current master (2437dc27c99c86f5f8e64628114475a96c9cb1d9) with the gnus-based viewer.  I'm not sure if this is a regression with the latest changes around the gnus-based viewer or a long-standing issue which I simply didn't notice until now.

When initializing a new mail by just hitting `RET` on an email address in some message header (calls `push-button`), my `mu4e-sent-folder` function is not consulted (when sending), thus this mail will not be archived somewhere which I consider as a kind of data loss.

Before someone says one should use contexts instead of function-valued `mu4e-*-folder` variables; I know and do for all other `mu4e-*-folder` variables but not for `mu4e-sent-folder` where I need a bit more flexibility because I want different sent folders in the same context in order to implement a "usually keep replies in the same folder as the replied-to message except for mailinglists" feature.  And also, the context `:match-func`s aren't called in the above situation, too.

The `action` property of the button-ized mail address in the header is `gnus-button-reply` which obviously has no mu4e-specific bits considering contexts and `mu4e-*-folder` variables.

**Comment by djcb** [comment]
What happens is that the reply is done in _gnus_ rather than in mu4e, so your mu4e sent folder etc. don't apply. I've turned it off now.
