### ISSUE TITLE
Gnus-based view and plaintext ratio heuristic

### ISSUE THREAD

**Issue by nbarrientos** [djcb/mu#1958]
Hi,

I'd like to apologise in first place as this is not a bug report per se, although it might end up in a patch for the documentation, I don't know ;)

I'm using mu4e 1.4.15-1 and as I read that the Gnus view mode will be default in the next release I decided to switch it on to see if I could get used to it by setting `mu4e-view-use-gnus` to `t`. I realised though that it was not honouring my settings to prefer HTML, at least the ones that I had for the standard view. I've got this:

```emacs-lisp
  (setq mu4e-view-html-plaintext-ratio-heuristic most-positive-fixnum)
  (setq mu4e-view-prefer-html nil)
```
These settings helped to get the text/plain version of most of my multipart e-mails displayed using the standard view, as unfortunately I was getting many e-mails with a valid text version but exceeding the default ratio defined in `mu4e-view-html-plaintext-ratio-heuristic` which were wrongly displayed as HTML.

So my question is, what's the equivalent to `mu4e-view-html-plaintext-ratio-heuristic` for the Gnus view? Is there one? If so, would it make sense to add it to mu4e's documentation?

I have to confess I have not dug into the source code to see how the Gnus view is actually implemented so if mu4e is just relying on something implemented by Gnus as a library and this configuration should be done on that side perhaps adding just a link would help too.

Thanks.

**Comment by djcb** [comment]
It works a little different with the gnus-based view, but to prioritize the plain-text parts, you can use something like 
```
(with-eval-after-load "mm-decode"
  (add-to-list 'mm-discouraged-alternatives "text/html")
  (add-to-list 'mm-discouraged-alternatives "text/richtext"))
```
(and see the `mm-discouraged-alternatives` docstring for the details)
