### ISSUE TITLE
Please add texinfo as build dependency in the docs

### ISSUE THREAD

**Issue by tinloaf** [djcb/mu#1964]
I'm building mu from git on a current Ubuntu (on WSL2, so the distro might slightly differ from 'plain' Ubuntu). The `texinfo` package is not installed by default, but is a build dependency for `mu` (see also #1210). The docs have [a list of build dependencies on Ubuntu](https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html#Installation), I think that list should include `texinfo`. 

Thanks!

**Comment by tinloaf** [comment]
I just went ahead and created a PR. See #1965.

**Comment by djcb** [comment]
Hmm, what error do you get? `texinfo` is a big dependency, so I'd like to avoid making that a hard dependency.

At least on Fedora, building works fine without it; `configure` says:

```
* You do not seem to have the makeinfo program; if you are building from git
  you need that to create documentation for guile and emacs. It is in the
  texinfo package in debian/ubuntu/fedora/... 
```

**Comment by tinloaf** [comment]
I just reproduced the problem with a clean checkout of the repository. I ran:

```
./autogen.sh 
./configure.sh --prefix=~/opt/mu
```

After that, I also see the message about the missing `makeinfo` program. I then run `make`. This is the relevant part of the output:  

```
[…]
Making all in mu4e
make[2]: Entering directory '/home/lba/src/mu/mu4e'
make[3]: Entering directory '/home/lba/src/mu/mu4e'
  MAKEINFO mu4e.info
/home/lba/src/mu/build-aux/missing: line 81: makeinfo: command not found
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <https://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <https://www.gnu.org/software/make/>
make[3]: *** [Makefile:555: mu4e.info] Error 127
make[3]: Leaving directory '/home/lba/src/mu/mu4e'
make[2]: *** [Makefile:789: all-recursive] Error 1
make[2]: Leaving directory '/home/lba/src/mu/mu4e'
make[1]: *** [Makefile:580: all-recursive] Error 1
make[1]: Leaving directory '/home/lba/src/mu'
make: *** [Makefile:490: all] Error 2
```

I did not see the error after running `make clean ; make` in the directory in which I previously (successfully, after installing `texinfo`) built mu.

My guess is: `makeinfo` is only supposed to be run after `mu4e.texi` has been changed. For some reason, the build process thinks I changed this file. This *could* be a file system quirk. I'm building inside a WSL2 container, which has some funny file system surprises. On the other hand I guess that the build process needs to somehow compare `mu4e.texi` and the generated `mu4e.info` files to check whether a rebuild is necessary - and I don't have a `mu4e.info` file anywhere inside the repository.

**Comment by djcb** [comment]
I've pushed a commit that should remove that hard dependency.
