### ISSUE TITLE
Viewing messages in a browser

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1966]
I just updated to the latest mu version and noticed that `mu4e~write-body-to-html` and `mu4e-action-view-in-browser` were moved to `mu4e-view-old`. Is html view of messages dropped? or is there a new way of viewing messages in a browser?

**Comment by Chris00** [comment]
I guess one could build something based on `gnus-article-browse-html-article` but it does not work out of the box.

**Comment by Chris00** [comment]
I hacjed the following and it seems to work quite well.  There is a part that should be factored out of `mu4e~view-gnus`.  There is also the problem of temporary files (maybe hacking around `make-temp-name` will allow to collect them and delete them).
```elisp
(defun mu4e-view-browse-html-message (msg)
  "View \"text/html\" parts of the MSG with a WWW browser.
Inline images embedded in a message using the cid scheme, as they are
generally considered to be safe, will be processed properly.

Warning: Spammers use links to images (using the http scheme) in HTML
articles to verify whether you have read the message.  As
`mu4e-view-browse-html-message' passes the HTML content to the
browser without eliminating these \"web bugs\" you should only
use it for mails from trusted senders.  See `mm-w3m-safe-url-regexp'."
  ;; Based on `gnus-article-browse-html-article'.
  (interactive)
  (with-temp-buffer
    (let ((path (mu4e-message-field msg :path)))
      (buffer-disable-undo)
      (insert-file-contents-literally path nil nil nil t)
      (mm-enable-multibyte)
      (let* ((ct (mail-fetch-field "Content-Type"))
             (ct (and ct (mail-header-parse-content-type ct)))
             (charset (mail-content-type-get ct 'charset))
             (charset (and charset (intern charset)))
             (gnus-newsgroup-charset
              (if (and charset (coding-system-p charset)) charset
                (detect-coding-region (point-min) (point-max) t))))
        (run-hooks 'gnus-article-decode-hook))

      (let ((header (concat "From: " (message-fetch-field "from")
                            "\nTo: " (message-fetch-field "to")
                            "\nDate: " (message-fetch-field "date")
                            "\nSubject: " (message-fetch-field "subject")))
            parts)
        (setq parts (mm-dissect-buffer t t))
        ;; If singlepart, enforce a list.
        (when (and (bufferp (car parts))
		   (stringp (car (mm-handle-type parts))))
	  (setq parts (list parts)))
        ;; Process the list
        (unless (gnus-article-browse-html-parts parts header)
	  (mu4e-warn "Mail doesn't contain a \"text/html\" part!"))
        (mm-destroy-parts parts)))))
```

**Comment by haji-ali** [comment]
Yep, this does work for me!

The now defunct `mu4e-action-view-in-browser` was also working for me, so I am not sure if there are cases that are trickier that the ones I tested.

**Comment by djcb** [comment]
Was experimenting along those same lines, but need refactor a bit (as mentioned) between this and `mu4e~view-gnus` and `mu4e-view-message-text`. There's also the case of non-html messages... not sure if that's important enough.

The reason `mu4e-action-view-in-browser` is defunct is that it needed a lot of the "old" view code as well as the "body" text of the message. With that eliminated, we can open messages directly from `mu4e`, without having to call back into `mu`.

**Comment by djcb** [comment]
Okay, implemented mu4e-view-action-in-browser for the gnus-based view; a bit of refactoring and some inspiration from @Chris00's code.

**Comment by djcb** [comment]
BTW, @Chris00, hopefully this doesn't affect the icalendar support, which I can't easily test... in particular the `mu4e~view-rendering`.

**Comment by Chris00** [comment]
> BTW, @Chris00, hopefully this doesn't affect the icalendar support,
> which I can't easily test... in particular the mu4e~view-rendering.

I tested minimally.  Seems to work fine.

**Comment by averter** [comment]
> Okay, implemented mu4e-view-action-in-browser for the gnus-based view; a bit of refactoring and some inspiration from @Chris00's code.

Did you mean `mu4e-action-view-in-browser` instead of `mu4e-view-action-in-browser`? 
In [this thread](https://github.com/djcb/mu/issues/1689) I was able to filter safelinks into regular urls for mu's current incarnation, but I cannot get the same effect in the browser view, hence why I landed here. The problem is that when I use `(thing-at-point-url-at-point)` it does not bounds the urls of the temp buffer properly; instead it stops at each new line of the buffer, resulting in these malformed strings
```
"https://e="

"https://ww="

"https://www.scopus.="

"http://orcid.="

"https://us01.safelinks.protection.outlo="
```
Does anyone have any idea of why this strange behaviour of `thing-at-point` happens? I did not open a separate thread for this because it is probably not worth it. Thank you in advance for any help
