### ISSUE TITLE
Searching for messages with an actual attachment

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1968]
I know that I can use `flag:attach` to find all emails that have an attachment. However, this also includes messages that have embedded attachments like images or the actual email text (shown in gnus viewer as `text/plain`).
Is there a way to search for images with actual non-embedded attachments?

**Comment by djcb** [comment]
mu attempts to be match only things that are "really" attachments, but it's just some heuristics; the disposition (attachment /inline etc.) is not really good enough, and there are things like crypto signatures etc.

If you look for specific things, e.g. `mime:image/*` may be useful.
