### ISSUE TITLE
Automatically switch context when composing new message

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#1969]
[Not following template because this is not a bug report.  Hope that's okay.]  It's super useful that mu4e can automatically determine the context when replying to a message via `match-func`.  However, it would be equally useful if mu4e could also use a similar mechanism to select a context when composing a new message via `mu4e~compose-mail`.  Current behavior is that mu4e always asks which context should be used for any new message.  Needless to say, if no extra info is passed to `mu4e~compose-mail` mu4e still needs to ask the user.

**Comment by peterhoeg** [comment]
I think you're looking for `mu4e-compose-context-policy`.

**Comment by tmalsburg** [comment]
Thank you. I realize that I didn't explain this well enough. What I want is the following: When composing a new message, I'd like mu4e to automatically determine the context based on the adressee's address (if provided). `mu4e-compose-context-policy` doesn't allow me to do this as far as I can see.  Ideally, I'd be able to handle this in the contexts match-funcs but, I think, these don't have access to the e-mail addresses.

**Comment by djcb** [comment]
There's `mu4e-compose-context-switch` (1.5.11) which lets you switch when already composing a message. 

You can either do that manually, or use a hook and some code to map the 'To' address to a context; perhaps even the very mu4e-context functions for that (you'd need to create a message-plist for that)

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg ***@***.***> writes:

> Thank you. I realize that I didn't explain this well enough. What I want is the following: When composing a new message, I'd like mu4e to automatically determine the context based on the
> adressee's address (if provided).

Hello Titus, did you try to provide a function in :match-func slot in
each mu4e-context? e.g.

     :match-func (lambda (msg)
                   (when msg
                     (string-match-p "^/Posteo" (mu4e-message-field msg :maildir))))

-- 
Thierry

**Comment by tmalsburg** [comment]
>  use a hook and some code to map the 'To' address to a context; perhaps even the very mu4e-context functions for that (you'd need to create a message-plist for that)

Thanks.  I'll look into it.  But it would be cool to have a standard solution since this is such a common scenario.

> Hello Titus, did you try to provide a function in :match-func slot in each mu4e-context? e.g.

@thierryvolpiatto, yes, I defined match functions and they are great. But they do not help when creating new messages that are not replies.  The msg argument to the match-func is the message that you're replying to but since this is nil when composing a non-reply message, I don't have the access to the address and therefore no basis to decide which context to use.

**Comment by djcb** [comment]
I agree this would be useful in some cases, but I think it's a bit beyond mu4e's complexity budget, esp. since users could do this themselves. So closing this...

**Comment by maikol-solis** [comment]
> There's `mu4e-compose-context-switch` (1.5.11) which lets you switch when already composing a message.
> 
> You can either do that manually, or use a hook and some code to map the 'To' address to a context; perhaps even the very mu4e-context functions for that (you'd need to create a message-plist for that)


Hi @djcb! 

I'm very interested in this option too. Could you please provide an example or pointer about how to make something like this? I'm not very good with lisp, though.

**Comment by djcb** [comment]
@maikol-solis:  I would actually recommend doing it manually, using `mu4e-compose-context-switch`.

If you are concerned about the case where you forget doing that, you could use a send-hook (https://www.djcbsoftware.nl/code/mu/mu4e/Confirmation-before-sending.html#Confirmation-before-sending), and perhaps change the context there; easiest is just using `mu4e-compose-context-switch` there.

That brings the whole process back to typing a single character. If that's still too much to type, you could create a message-plist and pass it to `mu4e-context-determine`. You don't really need a full plist, just the fields needed for your matching functions, i.e. just,
```
   (:to  (("Mickey Mouse" . "mickey@example.com")))
```
And fill in the values from the current message (using  the  `message-` functions for that). This does require a bit of elisp, no way around that.

A fully-general solution as part of mu4e would be considerably more work, and really seems not worth it given that it's all about save one keystroke.

**Comment by maikol-solis** [comment]
I solve it doing something like this, 

```
  (add-hook 'mu4e-compose-pre-hook
            (defun my-set-from-address ()
              "Set the From address based on the To address of the original."
              (let ((msg mu4e-compose-parent-message)) ;; msg is shorter...
                (when msg
                  (mu4e-context-switch
                   nil
                   (cond
                    ((mu4e-message-contact-field-matches msg :to "firs@gmail.com")
                     "gmail1")
                    ((mu4e-message-contact-field-matches msg :to "second@gmail.com")
                     "gmail2")
                    (t nil)))))))
```
