### ISSUE TITLE
Is it possible to add/remove my-address without init

### ISSUE THREAD

**Issue by derek-zhou** [djcb/mu#1971]
I recently upgraded from 1.2 to 1.4. In 1.2, I can supply my-address in `mu index`, however in 1.4 I can only do so in `mu init`. 
It looks intentional. However, I have many email addresses and I have a ton of emails. I'd really like to have a way to add/remove my-address without going through a full from scratch index run.

**Comment by djcb** [comment]
That's not possible, unfortunately. The indexing actually uses your e-mail addresses to decides which messages are "personal". Anyway, full re-indexing should be a rather _rare_ operation.

**Comment by derek-zhou** [comment]
So in 1.2 if I change my-addresses on `mu index`, it only appears to work, it did not really take into account of the changed my-adresses to categorize pass email addresses?

**Comment by djcb** [comment]
Exactly, it was a source of subtle surpises.
