### ISSUE TITLE
Sorting problems

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1972]
## Expected or desired behavior

Sort  messages with the newer at the top.

## Actual behavior

![Mu4e-sorting](https://user-images.githubusercontent.com/1255665/114263104-e398cd00-99e3-11eb-8f9b-96d04e12f8d3.png)

## Steps to reproduce

No idea why it happens — I may investigate later but the behavior may change as new message come in or I read those.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e: commit 5d414cff
GNU Emacs 27.1

**Comment by Chris00** [comment]
It seems the second copy was the problem.  At some point (after reading the message), it got merged and the problem disappeared...

**Comment by Chris00** [comment]
I confirm the duplicate (≡) messages trigger that problem.

**Comment by djcb** [comment]
Ah, interesting... still tracking some message-threading in #1924.

**Comment by djcb** [comment]
Is this still happening with the latest?
