### ISSUE TITLE
gnus-article-mode with CRLF

### ISSUE THREAD

**Issue by hughwilliams94** [djcb/mu#1975]
[test-message.zip](https://github.com/djcb/mu/files/6295472/test-message.zip)

## Expected or desired behavior

Read a message from a Thunderbird-created maildir that contains `^M` linebreaks with `mu4e-view-use-gnus t`.

## Actual behavior

Only the headers of the message are shown with no content being displayed. Switching to raw message show the full content.

## Steps to reproduce

Open a message (see attached example) that contains `^M` line breaks.

## Versions of mu, mu4e/emacs, operating system etc.

mu 1.4.15
emacs 27.2
Arch Linux

## Any other detail

Without `mu4e-view-use-gnus t` the message is shown fine. Using `mu view` from the command line works fine too. I am not sure where in the process the `^M` line breaks are being added to the message, as even messages I compose to myself from emacs on linux contain them.

**Comment by Chris00** [comment]
On my side, the absence of empty line (because of the `^M`) before the text body has the consequence that the message is not shown.  Once [this is removed from the message](https://github.com/djcb/mu/files/6295892/Thunderbird-created.txt), one sees that the `^M` also prevent `quoted-printable` to be properly decoded.

```
MIME-Version: 1.0
^M
CAUTION:
```

**Comment by Chris00** [comment]
The above patch works — but CRLF seems to be valid according to [RFC 822](https://www.w3.org/Protocols/rfc822/) so it is not clear why Gnus does no handle them.

**Comment by hughwilliams94** [comment]
Thanks for this

**Comment by Chris00** [comment]
@hughwilliams94 Could you send me an email from Thunderbird (email in [profile](https://github.com/Chris00)) to see whether it really is Thunderbird which creates the CRLF or some tool in between?

Could you also describe your configuration?  Do you, say, use offlineimap or mbsync to retrieve your message from an “outlook server”?

**Comment by hughwilliams94** [comment]
I've sent you a test email. In terms of fetching emails, I am only having issues with this particular account. It is an institutional account with IMAP, but they are using OAUTH2, so I can only fetch with Thunderbird. I'm using the maildir storage feature in thunderbird (https://support.mozilla.org/en-US/kb/maildir-thunderbird) and then indexing that maildir with mu. I have various other accounts that I fetch with mbsync, all of these work fine.

**Comment by Chris00** [comment]
@hughwilliams94 Thanks.  I received your email and there were no `\r` (CR) altogether.

**Comment by hughwilliams94** [comment]
Yes I think it is Thunderbird that adds the line breaks as it seems to occur with all emails received on this account, irresoective of sender.

**Comment by Chris00** [comment]
Ah! What happens if you suppress the CR in your email — is it still recognized by Thunderbird (and are CR reintroduced)?

**Comment by hughwilliams94** [comment]
How can I do this?

**Comment by Chris00** [comment]
If removing CR does not mess up with Thunderbird, a simple script (set to `mu4e-get-mail-command`) may fix things.

Alternatively, have you tried to do something like [How to use Google G suite OAuth2 with mbsync](http://blog.onodera.asia/2020/06/how-to-use-google-g-suite-oauth2-with.html)?

**Comment by Chris00** [comment]
> How can I do this?

Just quit Thunderbird and edit with Emacs the file you attach at the beginning of this issue.

**Comment by Chris00** [comment]
Then restart Thunderbird and see whether you can fetch more email, have access to the previously downloaded one,...

**Comment by hughwilliams94** [comment]
Ah I see, editing the .eml file directly to remove ^M doesn't seem to affect how thunderbird views it, even after a restart and the ^M breaks are not added back. So I suppose I can something to the get mail command, I'll give it a go thanks. Annoyingly, I have looked at the the oauth2 mbsync options as well as Davmail, but the institution uses a whitelist for accepted Oauth application, which blocks programs other than Thunderbird. I've asked to have some other applications added to the whitelist, so we shall see

**Comment by Chris00** [comment]
> the institution uses a whitelist for accepted Oauth application

With a script, you probably can _pretend_ to be Thunderbird setting the appropriate header  — I am not really versed in oauth but other people [on the mailing list](https://groups.google.com/g/mu-discuss) may be.

**Comment by Chris00** [comment]
>  I can add something to the get mail command

You can do something like the following, assuming Thunderbird puts new mail in `new` as it should (untested, use at your own risk):
```bash
#!/bin/bash

MAILDIR=$HOME/Maildir
INBOX="$MAILDIR/thunderbird/new"

FILES=$(ls "$INBOX")
for f in $FILES; do
  sed -e 's/\r//' --in-place $f
done

if [ -n "`command -v timeout`" ]; then
    timeout 60s mbsync -a
else
    mbsync -a
fi
```

**Comment by hughwilliams94** [comment]
Thanks, I suppose I can close this. Do you think it is worth filing an issue with gnus regarding their implementation?

**Comment by Chris00** [comment]
You can close it.  For Gnus, you may want to ask on [their mailing list](http://www.gnus.org/resources.html) first to see what they say (please report here).
