### ISSUE TITLE
error in process sentinel: Database empty; try indexing some messages

### ISSUE THREAD

**Issue by mhofert** [djcb/mu#198]
When I start `mu4e` via `M-x mu4e`, I obtain

```
error in process sentinel: Database empty; try indexing some messages
```

and I don't know why. I set up `mu4e` in `~/.emacs` like this:

```
;; general settings
(add-to-list 'load-path "~/.emacs.d/mu/mu-0.9.9.5/mu4e")
(require 'mu4e)
(setq mu4e-maildir "~/mail"); set top-level mail directory
(setq mu4e-get-mail-command "fetchmail"); command to retrieve mail
(setq mu4e-update-interval 120); update interval in s

;; default account (see Appendix D of the mu4e manual)
(setq mu4e-sent-folder "/uni/sent"
      mu4e-drafts-folder "/uni/drafts"
      mu4e-trash-folder "/uni/trash"
      mu4e-refile-folder "/uni/archive"
      user-mail-address "first.last@uni.edu"
      message-signature-file ".signature"
      smtpmail-default-smtp-server "mail.uni.edu"
      smtpmail-smtp-server "mail.uni.edu"
      smtpmail-smtp-service "smtp")

;; list of all accounts (see Appendix D of the mu4e manual)
(defvar my-mu4e-account-alist
  '(("uni"
     (mu4e-sent-folder "/uni/sent")
     (mu4e-drafts-folder "/uni/drafts")
     (mu4e-trash-folder "/uni/trash")
     (mu4e-refile-folder "/uni/archive")
     (user-mail-address "first.last@uni.edu")
     (message-signature-file ".signature")
     (smtpmail-default-smtp-server "mail.uni.edu")
     (smtpmail-smtp-server "mail.uni.edu")
     (smtpmail-smtp-service "smtp")
     )
    ("gmail"
     (mu4e-sent-folder "/gmail/sent")
     (mu4e-drafts-folder "/gmail/drafts")
     (mu4e-trash-folder "/gmail/trash")
     (mu4e-refile-folder "/gmail/archive")
     (user-mail-address "first.last@gmail.com")
     (smtpmail-default-smtp-server "smtp.gmail.com")
     (smtpmail-smtp-server "smtp.gmail.com")
     (smtpmail-smtp-service 587)
     )
))
```

My `~/mail` contains the folders `uni` and `gmail` which both contain the subfolders `inbox`, `sent`, `drafts`, `trash`, `archive`. `inbox` contains the mails which fetchmail/procmail fetched. Assuming `mu4e` needs the messages to be indexed, I executed:

```
$ mu index --maildir=~/mail
indexing messages under /home/mylogin/mail [/home/mylogin/.mu/xapian]

cleaning up messages [/home/mylogin/.mu/xapian]
\ processing mail; processed: 0; updated/new: 0, cleaned-up: 0
elapsed: 0 second(s)
| processing mail; processed: 0; updated/new: 0, cleaned-up: 0
elapsed: 0 second(s)
```

... but this doesn't change anything. 

This is with Emacs 24.3.50.1 under Ubuntu 13.04. 

Please note: This might be easy to solve for someone who is more experienced with mu4e. I post/submit it here since I couldn't find a mailing list specific to mu4e and stack/unix/linux overflow has only a handful of (mostly unanswered) questions related to mu4e. If there is a more adequate help forum, please let me know.

**Comment by mandarvaze** [comment]
@mhofert Can you explain the following ?

> I had not set up the mail directory correctly in Maildir format

I'm currently facing the same problem (emacs 25, mu 0.9.18, macOS sierra)

**Comment by RJTK** [comment]
I also had this issue.  Steps that worked for me:

(1) create maildir with `mu mkdir ~/Maildir`.
(2) (assuming you are using offlineimap) setup your `~/.offlineimaprc` file and run the program `offlineiamp` to download your email.
(3) run `mu index`
(4) Now in emacs `M-x mu4e' should work.

The problem seems to be simply that the Maildir can't be empty.

**Comment by mandarvaze** [comment]
@RJTK Thanks for the detailed steps.

Can you confirm that the first step is `mu mkdir` and not just `mkdir` ?

**Comment by RJTK** [comment]
Yes, `mu mkdir`.  It creates a particular directory format called maildir: https://en.m.wikipedia.org/wiki/Maildir
