### ISSUE TITLE
Display mu4e attachment overview in header as list with one attachment per line

### ISSUE THREAD

**Issue by vnckppl** [djcb/mu#1983]
I would like to have a more at-a-glance overview of email attachments when there are multiple attachments. An example of how multiple attachments are currently displayed in the header of an email is the following:

`Attachments: [2. text/plain]... [4. some_pdf_file.pdf --- application.pdf; some_pdf_file.pdf]... [5. yet_another_document.sav --- application/octet-stream; yet_another_document.sav]... [6. okay_here_is_one_more_attachment.sps --- text/plain; okay_here_is_one_more_attachment.sps]...`

I am wondering if it is possible to:
a) Distribute the attachments to show only one attachment per line
b) Disable the repetition of the file name

So, ideally, the output would like like:

`Attachments:`
`[2. text/plain]`
`[4. some_pdf_file.pdf --- application.pdf]`
`[5. yet_another_document.sav --- application/octet-stream]`
`[6. okay_here_is_one_more_attachment.sps --- text/plain]`

An unrelated question that I have: I assume that attachment 1 is the html version of the message, but what is going on with attachment number 3?

**Comment by djcb** [comment]
It'll be tricky to change, unless gnus has some way to change that (I'm not aware of one, but that doesn't say much). Closing this for now, we can reopen if someone figures out a way to do it in gnus.

Also, next time please use the ticket-templates.

**Comment by thierryvolpiatto** [comment]
If you use Helm, hitting "e" (`mu4e-view-save-attachments`) will show a list of attachments to save , you can either mark some candidates to save or hit C-g to quit if it was just to have an overview.

BTW @djcb I added a comment in the last commit you did related to this function but it seems you didn't see it.
It was about "you forget to remove the `or` clause now unneeded ".

**Comment by timmli** [comment]
Since Gnus removes line breaks with `skip-chars-backward`  when "buttonizing" attachments, the following disables `skip-chars-backward` locally. Not optimal, but it works for me.

```
(defun tl/advice-gnus-mime-buttonize-attachments-in-header (orig-fun &rest args)
  "Advice for `gnus-mime-buttonize-attachments-in-header` that locally disables `skip-chars-backward`."
	(cl-letf (((symbol-function 'skip-chars-backward)
						 (lambda (&rest args) nil)))
		(apply orig-fun args)))

(advice-add 'gnus-mime-buttonize-attachments-in-header
            :around #'tl/advice-gnus-mime-buttonize-attachments-in-header)
```
