### ISSUE TITLE
mu crash during error printing

### ISSUE THREAD

**Issue by derek-zhou** [djcb/mu#1984]
I am seeing segfaults in mu, and I traced it down to this line:
https://github.com/djcb/mu/blob/11fc99168b5c28313af884f6b80ea526e1dc1b30/lib/utils/mu-error.hh#L96
Supposedly, it should call:
https://github.com/djcb/mu/blob/11fc99168b5c28313af884f6b80ea526e1dc1b30/lib/utils/mu-utils.cc#L202
but on my machine (ia32 linux), it is calling:
https://github.com/djcb/mu/blob/11fc99168b5c28313af884f6b80ea526e1dc1b30/lib/utils/mu-utils.cc#L214
Therefore, it crashes. 
This problem only happens in ia32, not in AMD64. It is likely the `va_list` type is not a pointer type in AMD64. This issue can be simplified to the following example:
``` c++
#include <stdio.h>
#include <stdarg.h>

void format(const char *fmt, ...) {
  va_list args;
  va_start (args, fmt);
  vprintf(fmt, args);
  va_end (args);
}

void format(const char *fmt, va_list args) {
  vprintf(fmt, args);
}

int main() {
  format("%s\n", "hello");
}
```
The above program will crash in ia32 Linux, and will work fine in AMD64 Linux. 
Using C++ function overloading together with `va_list` has high risk. I propose to change second `format` to `vformat` to avoid any confusion. I can make a PR for this.

**Comment by djcb** [comment]
Oh, good catch! Yes, a PR would be great.

**Comment by derek-zhou** [comment]
I would love to; however, I have trouble building mu at git HEAD. automake does not work anymore, so I use meson. `meson builddir` went smoothly, but `meson compile` gives me this:
```
derek@roastidious:~/projects/mu$ cd builddir/
derek@roastidious:~/projects/mu/builddir$ meson compile
ninja: Entering directory `.'
[36/110] Compiling C++ object lib/libmu.a.p/mu-store.cc.o
../lib/mu-store.cc: In member function ‘void Mu::Store::set_dirstamp(const string&, time_t)’:
../lib/mu-store.cc:484:71: warning: format ‘%zx’ expects argument of type ‘size_t’, but argument 4 has type ‘time_’ {aka ‘long int’} [-Wformat=]
         const std::size_t len = g_snprintf (data.data(), data.size(), "%zx", tstamp);
                                                                       ^~~~~  ~~~~~~
[80/110] Generating mu4e_context_el_el with a custom command
FAILED: mu4e/mu4e-context.elc 
/usr/bin/emacs --no-init-file --batch --eval '(setq byte-compile-dest-file-function(lambda(_) "/home/derek/projects/mu/builddir/mu4e/mu4e-context.elc"))' --directory /home/derek/projects/mu/mu4e --funcall batch-byte-compile ../mu4e/mu4e-context.el
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...

In toplevel form:
../mu4e/mu4e-context.el:31:1:Error: Cannot open load file: No such file or directory, mu4e-meta
[82/110] Generating mu4e_compose_el_el with a custom command
FAILED: mu4e/mu4e-compose.elc 
/usr/bin/emacs --no-init-file --batch --eval '(setq byte-compile-dest-file-function(lambda(_) "/home/derek/projects/mu/builddir/mu4e/mu4e-compose.elc"))' --directory /home/derek/projects/mu/mu4e --funcall batch-byte-compile ../mu4e/mu4e-compose.el
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...

In toplevel form:
../mu4e/mu4e-compose.el:75:1:Error: Cannot open load file: No such file or directory, mu4e-meta
[85/110] Compiling C++ object lib/test-contacts.p/mu-contacts.cc.o
ninja: build stopped: subcommand failed.

```
Prior to this, I did `pip3 install meson ninja`. We may need some documentation on how to build.

**Comment by derek-zhou** [comment]
btw, automake gives me this:
derek@roastidious:~/projects/mu$ automake
configure.ac:56: error: required file 'build-aux/ltmain.sh' not found
configure.ac:20: error: required file 'config.h.in' not found

**Comment by djcb** [comment]
No need to run `automake` by hand, you can use `./autogen.sh && make`.  

`meson` should work too, even it's still experimental for `mu`; it does here at least. `meson build && meson compile -C build` from the toplevel.

**Comment by derek-zhou** [comment]
Thanks, I got it working. So Meson replaced make but not autotool. The PR was sent; all test passed.

**Comment by djcb** [comment]
> Thanks, I got it working. So Meson replaced make but not autotool. The PR was sent; all test passed.

Thanks for the PR, it's merged.

Anyway, `meson` _does_ replace autotool / make. Roughly, `ninja` does for meson what `make` does for autotools.

**Comment by derek-zhou** [comment]
> meson does replace autotool / make

However, from my trials before, nothing in meson is converting `mu4e/mu4e-meta.el.in` to `mu4e/mu4e-meta.el`, which is required in compilation?

**Comment by djcb** [comment]
> > meson does replace autotool / make
> 
> However, from my trials before, nothing in meson is converting `mu4e/mu4e-meta.el.in` to `mu4e/mu4e-meta.el`, which is required in compilation?

There's a specific rule for that in `mu4e/meson.build`; and after the initial `meson build`, you should find a `build/mu4e/mu4e-meta.el`.

**Comment by derek-zhou** [comment]
I have build/mu4e/mu4e-meta.el. however, the flow seems to expect mu4e/mu4e-meta.el, which is only generated from autotools. The log is:
```
[79/110] Generating mu4e_context_el_el with a custom command
FAILED: mu4e/mu4e-context.elc 
/usr/bin/emacs --no-init-file --batch --eval '(setq byte-compile-dest-file-function(lambda(_) "/home/derek/projects/mu/build/mu4e/mu4e-context.elc"))' --directory /home/derek/projects/mu/mu4e --funcall batch-byte-compile ../mu4e/mu4e-context.el
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...

In toplevel form:
../mu4e/mu4e-context.el:31:1:Error: Cannot open load file: No such file or directory, mu4e-meta
```
I think the problem is emacs is not told to look at that dir. The following simple patch seems to fix it:
``` diff
diff --git a/mu4e/meson.build b/mu4e/meson.build
index 2cc3d9a1..d8fb0db3 100644
--- a/mu4e/meson.build
+++ b/mu4e/meson.build
@@ -65,6 +65,7 @@ foreach src : mu4e_srcs
                          '--no-init-file',
                          '--batch',
                          '--eval', target_func,
+                         '--directory', meson.current_build_dir(),
                          '--directory', meson.current_source_dir(),
                          '--funcall', 'batch-byte-compile', '@INPUT@'])
 endforeach

```

**Comment by djcb** [comment]
Strange... I have:

```
Sources/mu % ls mu4e/mu4e-meta.el
ls: cannot access 'mu4e/mu4e-meta.el': No such file or directory
Sources/mu % meson build && meson compile -C build
[...] (build works)
Sources/mu % ls mu4e/mu4e-meta.el
ls: cannot access 'mu4e/mu4e-meta.el': No such file or directory
Sources/mu % ls build/mu4e/mu4e-meta.el
build/mu4e/mu4e-meta.el
```

So here it works at least.  I'm using meson 0.57.1.

Anyway, your change is a good idea regardless, since it makes explicit that the builddir should be searched *first*, even if there's an old mu4e-meta.el lying around in the source dir; do you want to make a PR for that? Otherwise, I can make that change.

**Comment by derek-zhou** [comment]
Please make the change. It is usually better to be explicit rather than relying on some implicit default hidden somewhere.

**Comment by djcb** [comment]
Okay, will do. Thanks.
