### ISSUE TITLE
Symbol’s function definition is void: mu4e-action-view-in-browser

### ISSUE THREAD

**Issue by Indy2222** [djcb/mu#1985]
I have added view action:

```
(add-to-list 'mu4e-view-actions '("bview in browser" . mu4e-action-view-in-browser))
```

which worked well in 1.4.x version. Recently I upgraded to the version from master branch (commit 11fc99168b5c28313af884f6b80ea526e1dc1b30) and it stopped working. I get this error:

```
mu4e-view-action: Symbol’s function definition is void: mu4e-action-view-in-browser
```

the same happens if I try to render the message as a PDF:

```
mu4e-view-action: Symbol’s function definition is void: mu4e-action-view-as-pdf
```

I am using default message view (gnus based in the new version, not gnus based in the 1.4.x version).

It happens in `GNU Emacs 27.2` on Arch Linux.

**Comment by djcb** [comment]
Please use the issue template; anyway, this is a dup of #1966.
