### ISSUE TITLE
[mu4e rfe] Warn in case of no subject

### ISSUE THREAD

**Issue by peterhoeg** [djcb/mu#1988]
**Is your feature request related to a problem? Please describe.**
I sometimes forget to put in a subject and it would be great to have a warning before sending thus giving the user an option to rectify it.

**Describe the solution you'd like**
A simple warning that subject is blank would be great.

**Describe alternatives you've considered**
Can't really think of any.

**Comment by peterhoeg** [comment]
I did do my own using a `message-send-hook` . Would you accept a PR that formalizes this?

**Comment by djcb** [comment]
There's already a note about that in the manual, if you want to extend the example that would be good. But would like to avoid adding a built-in hook.
