### ISSUE TITLE
switch to gnus loses link labeling when there is an html part

### ISSUE THREAD

**Issue by seanfarley** [djcb/mu#1990]
**Describe the issue**
Using the (now default) gnus-based view, emails that have html parts don't have links label (even their text parts). Screenshot attached to show.

<img width="1433" alt="Screen Shot 2021-04-25 at 8 12 47 PM" src="https://user-images.githubusercontent.com/20887/116016610-033e1100-a5f2-11eb-9cbf-a91841f7989c.png">

**Environment**
```
generated    Apr 25, 2021 20:14:22
distro       MacOS 11.2.3 Darwin 20.3.0 x86_64
emacs        28.0.50 ~/.emacs.d/ -> ~/projects/doom-emacs/
doom         2.0.9 HEAD -> develop, seanfarley/develop, origin/develop, origin/HEAD f621ff804 2021-04-21 21:45:04 -0400 ~/.doom.d/ -> ~/projects/dotfiles/doom/
shell        /usr/local/bin/bash
features     ACL DBUS GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM ZLIB
traits       gui server-running envvar-file
modules      :completion (company +auto +childframe) (ivy +childframe +icons +prescient) :ui deft doom doom-dashboard fill-column hl-todo indent-guides ligatures minimap modeline nav-flash ophints (popup +all +defaults) (treemacs +lsp) vc-gutter vi-tilde-fringe window-select workspaces zen :editor file-templates fold multiple-cursors (objed +manual) rotate-text snippets word-wrap :emacs (dired +icons) electric ibuffer undo vc :term vterm :checkers (syntax +childframe) spell :tools ansible biblio debugger docker editorconfig eval gist (lookup +docsets +dictionary) lsp (magit +forge) make pdf prodigy taskrunner upload :os macos :lang (cc +lsp) clojure data emacs-lisp json (javascript +lsp) (latex +latexmk) lua markdown (org +brain +dragndrop +gnuplot +hugo +journal +jupyter +pandoc +pdf +pomodoro +present +roam) (python +cython +lsp) rest rst sh (swift +lsp) web yaml :email mu4e :app everywhere :config (default +bindings +smartparens +snippets)
packages     (ace-jump-zap) (banner-comment) (bitwarden :recipe '(:host github :repo seanfarley/emacs-bitwarden)) (col-highlight :recipe '(:host github :repo emacsmirror/col-highlight)) (counsel-ffdata) (counsel-jq) (counsel-world-clock) (discover-my-major) (dot-mode) (easy-hugo) (elisp-slime-nav) (embrace) (emr) (fancy-narrow) (flycheck-package) (focus) (goto-chg) (grip-mode) (ialign) (lsp-focus :recipe '(:host github :repo emacs-lsp/lsp-focus)) (lsp-origami) (lsp-treemacs) (mpdel) (ivy-mpdel) (mu4e-alert) (mu4e-patch :recipe '(:host github :repo seanfarley/mu4e-patch)) (nerd-font :recipe '(:host github :repo twlz0ne/nerd-fonts.el)) (nov) (org-ref) (org-noter-pdftools) (org-roam-bibtex) (org-sidebar) (org-web-tools) (package-lint) (page-break-lines) (pipenv :disable t) (resize-window) (simple-httpd) (shrface) (simple-mpc) (sly-quicklisp) (sphinx-doc) (srefactor) (ssh-config-mode) (sx) (tree-sitter) (tree-sitter-langs) (unfill) (webpaste) (xwwp) (xwwp-follow-link-ivy) (whole-line-or-region) (which-key-posframe) (xonsh-mode :recipe '(:host github :repo seanfarley/xonsh-mode)) (ztree) (mu4e-thread-folding :recipe '(:host github :repo rougier/mu4e-thread-folding))
elpa         tracking s request rainbow-identifiers ov matrix-client ht frame-purpose f esxml dash-functional dash anaphora a
```

**Comment by seanfarley** [comment]
Thanks for the quick commit! Unfortunately, I still see the error. In general, the things I miss from the old view are:

- 'g' for going to a numbered link (faster than tab cycling)
- 'e' for downloading a numbered attachment (gnus doesn't seem to number them)

**Comment by djcb** [comment]
Hmm, I comment here from clicking `g 1` from your message. I _could_ reproduce the problem before. So not even in the github  message you get the links?

`gnus` numbers links as well, and you doesn't even require C-u. So, e.g. `2 A s` would save attachment number 2.

And toggling works as well, though not with a direct key binding.
`(setq gnus-unbuttonized-mime-types nil)`
makes it even more obvious.

**Comment by seanfarley** [comment]
> Hmm, I comment here from clicking g 1 from your message. I could reproduce the problem before. So not even in the github message you get the links?

That's right; for emails without anchor tags (e.g. just text of the url), the links seem to be numbered. But anything `shr` handles is not numbered.

This is what I see:
<img width="1387" alt="Screen Shot 2021-04-26 at 4 12 24 PM" src="https://user-images.githubusercontent.com/20887/116152395-b6fadb80-a69a-11eb-9678-02184c7473b9.png">

And a raw, text url that got numbered:
<img width="412" alt="Screen Shot 2021-04-26 at 4 30 46 PM" src="https://user-images.githubusercontent.com/20887/116153347-0392e680-a69c-11eb-8f51-e9ed169b28a1.png">

I've tried unsetting most my customizations (besides the most basic ones to get the maildir set correctly). Am I missing something?

> gnus numbers links as well, and you doesn't even require C-u. So, e.g. 2 A s would save attachment number 2.

(I assume you meant "attachments") Ah, I missed that before but can now see it; ok, a little different but I think it works for me.

> And toggling works as well, though not with a direct key binding.
> (setq gnus-unbuttonized-mime-types nil)
> makes it even more obvious.

This one confuses me because it seems `'shr` is still being used? By toggling the mime part from the header, the view will display the text part, and the html part after it.

**Comment by djcb** [comment]
Ah, that's an important qualification. 

I think for the html version, it's the expected behavior; by the time mu4e sees it, it's hypertext already. Might be a useful feature, but probably something for `shr` / `eww`.

**Comment by seanfarley** [comment]
After stepping through the `mu4e~view-activate-urls' function, I see that it's impossible to number the html rendered part.

**Comment by seanfarley** [comment]
I also noticed that when I click / hit return on the `text/plain` part that `mu4e~view-activate-urls` is not triggered again.

**Comment by djcb** [comment]
That's actually in the manual :)

**Comment by djcb** [comment]
And yeah, there are still a few rough edges.

**Comment by seanfarley** [comment]
> That's actually in the manual :)

Curse me, and my inevitable non-reading of the manual!

**Comment by seanfarley** [comment]
I've fully switched now and will report back any more edges!

**Comment by djcb** [comment]
> > That's actually in the manual :)
> 
> Curse me, and my inevitable non-reading of the manual!

Haha... added it only a few days back.
