### ISSUE TITLE
messages with similar but distinct References headers being threaded together

### ISSUE THREAD

**Issue by nicolasavru** [djcb/mu#1994]
Messages with the following References headers (redacted some digits with #) are being put into the same thread:
References: <+1646#######.0de1dfc5259c49347621104b1bee58fc0197a0b9@txt.voice.google.com>
References: <+1646#######.@txt.voice.google.com>

Expected behaviour is for the second message to not be pulled into the thread of the first message.

Additional details that might be worth mentioning but probably aren't related:
1. In both cases, I don't actually have a message with  referenced message id, so a different (mostly correct, I'll file a seperate bug about that) parent is selected.
2. I have a bunch of messages with each of the aforementioned References headers and they are all being put into a single thread.
3. The messages have different subjects and different senders (From headers).

**Comment by djcb** [comment]
Note, this is only a cosmetic effect, where unrelated children are decorated in the same ways as actual thread-children. Doesn't make much difference for the end-user of course.

Also: please use the issue templates the next time.

**Comment by nicolasavru** [comment]
Sorry about not using the template, I missed the "Open a blank issue" link at the bottom and only noticed the big green buttons for the other other (in this case inapplicable) templates. Doesn't help that the link mentioning a "blank issue" actually has the necessary template (i.e., isn't blank).

**Comment by nicolasavru** [comment]
I see how #1995 is a cosmetic effect, but I'm not sure this one is. I played around with this some more and noticed that while the messages with the second References header are being put into a separate thread (they have path 0000:####:z while the first References header messages have path 0001:####:z), they are being pulled in by include-related. When include-related is off, only the messages with the first References header appear.

**Comment by nicolasavru** [comment]
/sigh, found the problem. A single message with the second References header was matching my query, which got (correctly) threaded with every other message with that References header and all of those got pulled in by include-related. This is all WAI. 

I suggest closing this bug and reopening the other one for the cosmetic issue. Sorry for the noise.
