### ISSUE TITLE
[mu4e rfe] searching within text/plain attachments

### ISSUE THREAD

**Issue by nicolasavru** [djcb/mu#1997]
It would be nice to search within text/plain (and maybe text/*) attachments, at the very least with a regex search if there are xapian limitations here.

Currently, given a message with this content, searching for "normal body text" would find the message, but searching for "special attachment text" would not:

> MIME-Version: 1.0
> Content-Type: multipart/mixed; boundary="===============8099362135024052965=="
> X-TUID: ybtdPgTzSysr
> 
> --===============8099362135024052965==
> Content-Type: text/plain; charset="utf-8"
> Content-Transfer-Encoding: 7bit
> 
> normal body text
> 
> --===============8099362135024052965==
> Content-Type: text/plain; charset="utf-8"
> Content-Transfer-Encoding: quoted-printable
> Content-Disposition: attachment; filename="message.txt"
> MIME-Version: 1.0
> 
> special attachment text
> 
> --===============8099362135024052965==--
> 

More generally, if I can find the message by grepping in my maildir, I would expect to be able to find it with a mu query.

**Comment by djcb** [comment]
There's the `embed:` search prefix for that.  It's not quite the same as grep; grep works different for literal blobs (text with space, special chars etc.) and doesn't handle encoded text.
