### ISSUE TITLE
mu4e-update-index isn't indexing mail folder

### ISSUE THREAD

**Issue by josarlo84** [djcb/mu#1999]
## Expected or desired behavior

Running `mu4e-update-index` behave like `mu index` and index mail folder

## Actual behavior

Running `mu4e-update-index` finishes with message:

`Indexing completed; processed 0, updated 0, cleaned-up 0`

## Steps to reproduce

For bug-reports, please describe in as much detail as possible how one can reproduce the problem.

If there's a problem with a specific (type of) message, please attach such a message to the report.

### mu
master branch (5103f4614ec1e)

### Emacs
GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw scroll bars) of 2021-04-24

### OS
Linux Mint 20.0

## Any other detail

Feature works on release/1.4.x branch, but I haven't been successful in getting to work on master branch.  I wonder if I am missing a configuration step :/

This is my output from `mu init`

```
maildir           : /home/user/.mail
database-path     : /home/user/.cache/mu/xapian
schema-version    : 451
max-message-size  : 100000000
batch-size        : 250000
messages in store : 0
created           : Mon 26 Apr 2021 03:18:22 PM MDT
```
This is my output from `mu index`
```
indexing maildir /home/user/.mail -> store /home/user/.cache/mu/xapian
| indexing messages; processed: 4746; updated/new: 4749; cleaned-up: 0
```

This is the output of *mue4-log* after sending an email to myself, running offlineimap, and then `mu-update-index`
```
2021-04-26 15:22:48.980 -> (index :cleanup nil :lazy-check t)
2021-04-26 15:22:49.981 * Received 152 byte(s)
2021-04-26 15:22:49.981 <- (:info index :status running :processed 0 :updated 0 :cleaned-up 0)
2021-04-26 15:22:49.982 <- (:info index :status complete :processed 0 :updated 0 :cleaned-up 0)
```

**Comment by djcb** [comment]
Does a manual `mu index` do what you expect after you retrieved mail using `offlineimap`?

**Comment by josarlo84** [comment]
Yes, it does. My current work around is to close mu4e in emacs and run `mu index` in a bash shell. When I run mu4e again I see my new messages.

**Comment by djcb** [comment]
Then, I'd recommend turning off the lazy/cleanup check settings, i.e. leave 
```
    (setq mu4e-index-lazy-check nil
             mu4e-index-cleanup t)
```
(or leave at their default values)

**Comment by theophilusx** [comment]
I have also observed similar behaviour if there has been some time
between updates of mu4e and mu. Wiping away the xapian db and doing a mu
init followed my mu index has always fixed the issue for me.

I'm running Emacs 28.0.50 on Ubuntu 20.10 and running from mu repo
master HEAD.

"Dirk-Jan C. Binnema" ***@***.***> writes:

> Then, I'd recommend turning off the lazy/cleanup check settings, i.e. leave
>
>     (setq mu4e-index-lazy-check nil
>              mu4e-index-cleanup t)
>
> (or leave at their default values)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
Tim Cross

**Comment by djcb** [comment]
Another `mu init` would be a rather big hammer!

The command-line `mu index` does the equivalent of the mu4e update (with the lazy-check/cleanup values as mentioned). So if that works, it should presumably work from mu4e as well.

**Comment by josarlo84** [comment]
Thanks Dirk-Jan, resting the lazy-check/cleanup settings to their default value fixed the issue.  

Tim, thanks for you suggestion.  After wiping the Xapian db with an `mu init` and `mu index`, mu4e still wouldn't bring in new mail.
