### ISSUE TITLE
[mu4e rfe] mu4e-update-index is slow

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2002]
**Is your feature request related to a problem? Please describe.**

Executing `mu4e-update-index` takes time to update the `*mu4e-headers*` is slow.  On my machine, with `mu4e-headers-report-render-time` set to `t`, I get:
```
Found 268 matching messages (rendering took 1549.1 ms, 5.78 ms/msg)
```
The problem is that, when we read messages at the same time we update mail, on has time to move the cursor between the beginning of the update and the time the cursor is repositioned on the current message.

**Describe the solution you'd like**

Would it be possible, say, to render the new headers in a temporary buffer and then copy it all to `*mu4e-headers*` so it is almost instantaneous?

**Comment by djcb** [comment]
Yeah, that's fairly slow... The way it's done is because we get the mails incrementally; "double-buffering" would defeat that. 

Anyway, something to look at post-1.6... I have some performance ideas I'd like to explore.
