### ISSUE TITLE
Searches that add to the headers view rather than replacing it

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#2009]
## Problem description

I've set `mu4e-headers-include-related` to `nil` because I read several high-traffic mailing lists where always including full threads in the headers view would make things much less overseeable.

Now consider reading the unread bookmark (`b u`).  There is some new mail I need to reply to but I need some more context from an older message in the same thread.  To get that context, I execute `mu4e-headers-toggle-include-related` (`W`) and the result is that the mail I started writing a reply to is gone, and the full thread doesn't show up, too.

That's obviously because `mu4e-headers-toggle-include-related` first applies all marks (making the message I'm replying to read) and then does a new search (for unread messages including related) which doesn't help me anymore.

## Wanted behavior

In general, I'd like a way to execute a search which just adds more messages to the current headers view without applying marks first and generating a completely new headers view from scratch.  That is, consider my current headers view contains the messages 1, 2, and 3 and the new search would find the messages 2, 3, and 4, the headers view would show 1, 2, 3, and 4.  If 1, 2, or 3 had marks not yet applied before the search, they'd still have them now.

This new search could then be used in all `mu4e-headers-toggle-*` commands (and maybe also in `mu4e-headers-rerun-search`).

## Versions of mu, mu4e/emacs, operating system etc.

The current git master versions of Emacs and mu/mu4e.

**Comment by djcb** [comment]
Not quite sure what you mean by 'applying marks, but the easiest way is to add a few messages, press `S` (`mu4e-headers-search-edit`), and then specify some criterion for the new message, e.g. ` OR banana`.

**Comment by djcb** [comment]
(and please use the ticket templates, thanks!)

**Comment by tsdh** [comment]
What I mean is this:
1. Search for `flag:unread` (aka the `b u` bookmark)
2. Select some message which assigns it the `read` mark
3. Press `S` and edit the search to `flag:unread AND from:sender-of@that-message.com`
4. Mu will then
  4.1. Apply the `read` mark to the message
  4.2. Execute the new, edited search which will not contain the read message because it hasn't the `unread` flag anymore

You can say that I just need to generate a query which actually finds what I want, and indeed that would be feasible, e.g., it should look like `<original-query> OR msgid:<1st-msg-in-headers-view> OR msgid:<2nd-msg-in-headers-view> OR ...`.  Not sure if mu can handle queries with hundreds of conjunctions, though.

Anyway, that would still not be exactly what I imagine: my prime scenario is re-executing the current search with the toggled setting of `mu4e-headers-include-related`.  What I might imagine is:
1. I'm in some headers view and already have read/flagged/whatever some messages so that they have some marks which would be applied if I'd press `x` or exited the headers view.
2. I hit `W` and mu4e would...
2.1. save all messages marks (like with a hash-map of message-id to mark)
2.2. re-execute the search with the toggled value of `mu4e-headers-include-related`
2.3. in the resulting headers view assign the marks anew that have been captured in step 2.1

Of course, there would still be a risk of losing marks, e.g., when going from "with related messages" to without.

**Comment by tsdh** [comment]
Issue #1981 is basically a special-case of this issue where `mu4e-headers-auto-update` causes the message you are currently reading to vanish from the headers view.  That's also a case where I'd prefer if the auto-update would just extend rather than replace the current headers view.

**Comment by djcb** [comment]
"Incremental" headers view doesn't really fit in the mu/mu4e design, so I have to decline that idea. There shouldn't be a problem making big queries (mu does that a lot internally), but, doesn't `mu4e-action-show-thread`, i.e., `a s` in the headers buffer, do what you want?
