### ISSUE TITLE
[mu4e rfe] multi-key maildir shortcuts

### ISSUE THREAD

**Issue by joostkremers** [djcb/mu#2010]
**Is your feature request related to a problem? Please describe.**
I use maildirs to organize my e-mail and with several different e-mail addresses to manage, I'm running out of meaningful keys to use as maildir shortcuts.

**Describe the solution you'd like**
I think it would be practical if it were possible to have maildir shortcuts that use more than one key. That way I could, for example, assign the spam folder of e-mail account A to `as` and the spam folder of e-mail account B to `bs`, instead of having to use `s` for one of them and `S` for the other (and not knowing what to do with the spam folder in account C...).

**Describe alternatives you've considered**
Bookmarks don't really help here, because they are also limited to one key. (Perhaps multi-key bookmarks should also be considered?) And using `j o` + typing the name of the maildir is also more cumbersome (despite completion), because a single key is not sufficient to select the correct maildir.

**Comment by djcb** [comment]
You can fairly easy do it yourself though, by hand or using something like `hydra`; e.g. use your `a` or `b` and then let-bound `(mu4e-bookmarks)` with the _second_ letter.

**Comment by joostkremers** [comment]
Hmm, I just noticed you even mentioned this case in the manual... I hadn't thought about hydras before, thanks for pointing out that option.

Still, would you consider a PR that implements this in mu4e? Or is it not something you'd be interested in?

**Comment by marcSoda** [comment]
This would be a very useful feature.

**Comment by djcb** [comment]
Not a adding multi-key bookmarks / shortcuts (it's a bit beyond the complexity budget...), but what I _did_ add is `mu4e-search-query`, which lets you auto-complete queries by name; so if you name name them "as", "bs", "cs" etc. you get what you want (esp. with some completion framework, such as "vertico" or "helm" etc.)
