### ISSUE TITLE
Getting error in process filter ... No such file or directory.

### ISSUE THREAD

**Issue by simurgh9** [djcb/mu#2011]
**Describe the issue**

Sometimes when I send mail in emacs using `mu4e`, I get these kinds of errors,

```
error in process filter: cond:
    Error 70: cannot read file /home/username/Maildir/Drafts/cur/1630476890.84dde0cb4899f5c6.smrgh:2,DS:
        No such file or directory
error in process filter:
    Error 70: cannot read file /home/username/Maildir/Drafts/cur/5310278690.84dde0cb4899f5c6.smrgh:2,DS:
        No such file or directory
```

The email still goes through. It is just annoying to see these, I get these especially when I take too long to type in an email. After it is sent, I see a draft of it saved even though the email was sent. 

Could it be due to the fact that I move the backups (of files being currently edited that) emacs makes to a directory somewhere else? But I can't find anything mu related in that directory even if something got moved there.

**Environment**

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
 `mu` is at `1.2.0` and `apt list mailutils` returns `mailutils/focal 1:3.7-2.1 amd64`. I am on emacs 27.1.

**Comment by djcb** [comment]
That's likely the result of files moving behind mu's back indeed. When you get the chance, does this happen with 1.4 as well?

**Comment by simurgh9** [comment]
> does this happen with 1.4 as well

I installed everything using `apt`. I have no idea how to upgrade.

Do you have any idea about what files maybe getting moved? I have the following in my configs,

```lisp
(setq   ;; putting backup and auto-save files at one place
  auto-save-file-name-transforms `((".*" "~/.emacs.d/backup/" t))
  backup-directory-alist '(("." . "~/.emacs.d/backup/"))
  backup-by-copying t         ; don't delink hardlinks
  version-control t           ; use version numbers on backups
  delete-old-versions t       ; automatically delete excess backups
  kept-new-versions 20        ; how many newest and old versions to keep
  kept-old-versions 5)

**Comment by djcb** [comment]
The moving-behind-mu4e's-back would be through some external program, e.g. the one you use to synchronize your mail with (offlineimap mbsync etc.).

**Comment by simurgh9** [comment]
I use offlineimap. Do you have any suggestions about where I should start looking?

**Comment by djcb** [comment]
Don't do syncs from local->remote while mu4e is running. And I'd upgrade mu and see if that helps; it's in the manual.

**Comment by simurgh9** [comment]
Updated to `1.4.15` and the issue persists. If the compose buffer is kept open for a while (about 30 seconds) you get,

```
error in process filter:
    Error 11: failed to add path: cannot read file
        /home/tfn/Maildir/Drafts/cur/1621675237.ac054df420b4a7cb.smrgh:2,DS:
            No such file or directory (line was:'(sent :path
                "/home/tfn/Maildir/Drafts/cur/1621675237.ac054df420b4a7cb.smrgh:2,DS")')
```
However, like I said before, the mail is still sent. I also updated my Emacs to 28.

**Comment by djcb** [comment]
Yeah, that's offlneimap working behind mu4e's back; not so much mu4e can do about that, unfortunately.

**Comment by simurgh9** [comment]
Okay I've had time to take a look, I do think this is a mu issue. Each time I send a mail, a draft is made in `~/Maildir/Drafts/cur/` and since I have `(setq mu4e-sent-messages-behavior 'delete)`, I think that is what fails. The draft that is made in there is not what the attempt to delete tries to delete, instead it tries to delete a file that already does not exist in `~/Maildir/Drafts/cur/`.
