### ISSUE TITLE
Issue with defcustom re: bookmarks 

### ISSUE THREAD

**Issue by jsilve24** [djcb/mu#2012]
On this page: 
https://www.djcbsoftware.nl/code/mu/mu4e/Bookmarks.html

it says that custom bookmarks can be set with a `defcustom` command. At least in spacemacs this just was ignored and I needed to change it to `setq` to have the changes take effect. 
Not sure if this is just a documentation issue, I am just too dense to read the documentation correctly, or this is a spacemacs issue, either way figured it might help someone else for me to report this. 

Thanks for all the hard work!

**Comment by jsilve24** [comment]
So apparently its not as simple as setting to setq. If you do that then the docstring and the `:type` and `:group` arguments are not valid / not supposed to be with setq (duh). 

So I am acctually fairly confused. Where is this defcustom? Why was mu4e not throwing an error originally but just ignoring my attemtp at setting custom bookmarks? And How badly have I screwed things up by changing to setq and removing the `:type` and `:group` arguments :)?


Here is what that section of my config looks like currently (in spacemacs `user-config`)
```
(setq mu4e-bookmarks
    '(( :name  "Unread messages"
               :query "flag:unread AND NOT flag:trashed AND (maildir:/gmail/INBOX OR maildir:/psu/INBOX)"
               :key ?u)
      ( :name "Today's messages"
              :query "date:today..now AND NOT flag:trashed AND (maildir:/gmail/INBOX OR maildir:/psu/INBOX)"
              :key ?t)
      ( :name "Last 7 days"
              :query "date:7d..now AND NOT flag:trashed AND (maildir:/gmail/INBOX OR maildir:/psu/INBOX)"
              :hide-unread t
              :key ?w)
      ( :name "Messages with images"
              :query "mime:image/*"
              :key ?p))
    ;; :type '(repeat (plist))
    ;; :group 'mu4e)
    )
```

**Comment by djcb** [comment]
The documentation shows the `defcustom` definition for bookmarks because "Their definition may be instructive"; not because _you_ need to use defcustom.

You use either emacs' system (Through the 'Customize emacs') or by hand, using setq. The type/group don't belong there; just read the docstring for `setq`.
