### ISSUE TITLE
[mu4e rfe] Toggle html view / part in new gnus backend

### ISSUE THREAD

**Issue by seanfarley** [djcb/mu#2013]
With the old `mu4e-view-mode`, pressing `h` would toggle the html (using `shr` / `eww`) of the email. That seems to be missing with the gnus backend.

I did a little spelunking of the gnus code but I couldn't wrap my head around how it displays the html part.

**Comment by djcb** [comment]
You can toggle it by clicking on the mime part in "Attachments:". A patch for hooking up `h` with that would be welcome.

**Comment by seanfarley** [comment]
> You can toggle it by clicking on the mime part in "Attachments:". A patch for hooking up `h` with that would be welcome.

I tried but have no idea how to do it :-(

**Comment by seanfarley** [comment]
🎉
