### ISSUE TITLE
mu4e-view-save-attachments gives Wrong type argument: char-or-string-p, nil[misc]

### ISSUE THREAD

**Issue by jsilve24** [djcb/mu#2014]
**Note**: for questions, please use the mailing-list: https://groups.google.com/g/mu-discuss

**Describe the issue**
A clear and concise description, i.e. what you expected/desired to happen and what actually happened.
Trying to download 7 attachments in the same email at once. Looked it up online and it seems that mu4e-view-save-attachments is what I want. I am using spacemacs + helm. 
However when I try to save even a single attachment  (pressing RET in the helm minibuffer on the attachment I want)  I get an error: 

`Wrong type argument: char-or-string-p, nil`

Here is what is listed in *messages*
```
helm-M-x-execute-command: Wrong type argument: char-or-string-p, nil
mm-save-part-to-file: Wrong type argument: char-or-string-p, nil
```

**Environment**
If applicable, please describe the versions of OS, Emacs, mu etc. you are using.\

Spacemacs 0.300
Emacs version 26.3
mu4e version 1.5.13

Thanks for the help!
Justin

**Comment by jsilve24** [comment]
Well this is werid and I am willing to chalk it up to my fault. I had cloned the article buffer (so that I could veiw two messages at once) and that seemed to be the issue. 

Not going to close as I am not sure if this should be expected behavior or a bug. Also, any advice on a better message of open two messages at once? Not sure if cloning the buffer is a good or bad idea. 

Best

**Comment by djcb** [comment]
You can't really open two messages at once. Or well, you can _attempt_ (like cloning), but it doesn't quite work.
