### ISSUE TITLE
[documentation]  Document configuration & tweaks to compose in HTML

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2015]
I have been using [org-msg](https://github.com/jeremy-compostella/org-msg)  — reply/compose in HTML using org-mode — for some months now and I was wondering whether there is interest in documenting special _mu4e_ tweaks about it.  If so should they be in the manual or as an _org_ file in [contrib/](https://github.com/djcb/mu/tree/master/contrib)?

**Comment by djcb** [comment]
Oh, we have an 'Other tools' appendix in the manual, that would be a good place for this.

**Comment by djcb** [comment]
@Chris00, any plans for this? Or should I close this? Thanks!

**Comment by Chris00** [comment]
Unfortunately, I will not have time to do this in the coming months.  Let's close it for now.

**Comment by djcb** [comment]
Okay, thanks!
