### ISSUE TITLE
[misc] where to start debugging reply mu4e-compose-reply

### ISSUE THREAD

**Issue by sje30** [djcb/mu#2017]
**Describe the issue**

If I am reading a message in the *Article* buffer, and hit R (bound to mu4e-compose-reply), then the reply buffer is created, but the point is left at start of buffer.  It used to go to the start of body of message.  If however I hit R from the headers buffer, point correctly goes to the start of body of message.

How might I start debugging this?  It started happening after I upgraded yesterday to Emacs 28.0.50 (the head of Emacs as of yesterday).  I think before yesterday, the point was left at start of body of message.

For now, I can try to workaround by putting message-goto-body in a suitable hook.

**Environment**

Emacs 28.0.50; mu4e 1.4.15

**Comment by djcb** [comment]
Cannot reproduce that with 1.5.13 at least.

Perhaps cleaning & rebuilding mu4e helps, if it's some prob with a .elc incompatibility.

**Comment by djcb** [comment]
Can you reproduce with 1.5.x?

**Comment by sje30** [comment]
So, after a re-make,  I can't reproduce this on my 1.4.15 setup, so I'll clsoe this.  Thanks for the tips.
