### ISSUE TITLE
mu4e not updating marks immediately, causing trouble for mu4e-alert

### ISSUE THREAD

**Issue by antoine-levitt** [djcb/mu#2023]
In mu master, my mu4e-alert modeline is out of sync whenever I read or mark mail as unread, and only updates properly when the get-mail job runs. I think this is because in previous versions of mu, whenever I marked in mu4e a mail as being read or unread, the change was propagated to mu immediately. As a result mu4e-alert was able to pick it up and my alerts were synchronized. Is my diagnostic correct, and if yes what can be done to mitigate it?

**Comment by djcb** [comment]
It's updated immediately for me. 

Anyway, not much I can do here -- if you have probs with some 3rd party package, please file an issue there; if it's ultimately something in mu4e, at least the 3rd-party maintainers can give some details about that what's expected/happening.

And please use the issue templates.

**Comment by antoine-levitt** [comment]
> And please use the issue templates

[misc] did not seem appropriate. Can you add a category "bug report"?

> It's updated immediately for me.

Meaning if you read an email or make it unread and then immediately afterwards run "mu find flag:unread" it immediately updates? Then I'm running into a bug. I'll try reducing it to the maximum but I really don't see anything in my configuration that could cause it.

**Comment by antoine-levitt** [comment]
> I'll try reducing it to the maximum but I really don't see anything in my configuration that could cause it

I can confirm the issue from a clean emacs configuration. Set an email as unread, it doesn't display in `mu find flag:unread`. Run mu4e-update-index, it does.

**Comment by djcb** [comment]
> > And please use the issue templates
> 
> [misc] did not seem appropriate. Can you add a category "bug report"?

Hmmm... those should be there already... I've refreshed them.

> > It's updated immediately for me.
> 
> Meaning if you read an email or make it unread and then immediately afterwards run "mu find flag:unread" it immediately updates? Then I'm running into a bug. I'll try reducing it to the maximum but I really don't see anything in my configuration that could cause it.

> > I'll try reducing it to the maximum but I really don't see anything in my configuration that could cause it
> 
> I can confirm the issue from a clean emacs configuration. Set an email as unread, it doesn't display in `mu find flag:unread`. Run mu4e-update-index, it does.

Ah, but this is why I always ask not to involve third-party extensions, since I have no idea what those are doing. If you're trying to use the database while mu4e is running, you might run into caching issue where the database is not written to disk yet.

**Comment by antoine-levitt** [comment]
> If you're trying to use the database while mu4e is running, you might run into caching issue where the database is not written to disk yet.

That's exactly what mu4e-alert is doing: https://github.com/iqbalansari/mu4e-alert/blob/master/mu4e-alert.el#L238. Any way to force the cache being written to disk?

**Comment by antoine-levitt** [comment]
So I don't think the cache is the problem here. The only way I have of making this work is to call manually mu4e-update-index then mu4e-alert-update-mail-count-modeline (after the update process has finished).  

It looks like the recent mu4e versions has removed / changed the way a certain hook is called. Essentially, what mu4e-alert needs is 1) for the `mu find` command to be up to date wrt what's going on in mu4e 2) a hook to be run whenever the command `mu find` has updated results. mu4e-alert tries to plug into all the hooks it can find, but none of them actually do this (in particular, mu4e-index-updated-hook doesn't, at least in recent mu4e versions). I have opened an issue at mu4e-alert, but that package seems unmaintained and I don't think there is anything mu4e-alert can do on its own. I'm willing to try and fix it if given a bit of guidance.
