### ISSUE TITLE
[mu4e rfe] Revisit org-mode support

### ISSUE THREAD

**Issue by peterhoeg** [djcb/mu#2024]
**The problem**

Writing emails in org-mode is a wonderful way to have a nice, high-level clean,
text format and while it works fine in org-msg, it doesn't in mu4e-compose mode.

The use case is this: I want to always write emails in org-mode. Even if they are
being sent as plain text, we can still export from org to plain text or even
markdown (which is perfectly readable) and ensure that the output looks fine in
most cases. Tables will obviuosly be screwy if the recipient doesn't use a monospace font
for plain text.

org-mode allows syntax highlighting inside source blocks and while the plain
text export obviously doesn't have colors, it would still be nice to have when
writing the email to begin with.

**Describe the solution you'd like**

Have mu4e-compose-mode support org-mode syntax and then export on send to multiple formats.

**Describe alternatives you've considered**

org-msg sort of does this, but it has its own set of problems:

1. enforces an Outlook type workflow
2. always sends html
3. top posting
4. inability to remove quoted mail

**Additional context**

Having a single source format regardless of what the output is would be awesome.

**Comment by Chris00** [comment]
> org-msg sort of does this, but it has its own set of problems:
> 
>  1.   enforces an Outlook type workflow
>   2.  always sends html
>   3.  top posting
>   4.  inability to remove quoted mail

This is only true with the default configuration.  For example:
```elisp
  (setq org-msg-default-alternatives '((new		. (text html))
				       (reply-to-html	. (text html))
				       (reply-to-text	. (text))))
```
configures when to send HTML or text (and you can open the `:PROPERTIES:` drawer with <kbd>TAB</kbd> to change it for specific emails).  With
```elisp
  (setq org-msg-posting-style nil)
  (setq org-msg-convert-citation t)
```
you disable top-posting (first line) and ask org-msg to convert citation lines (starting with `>`) to `<blockquote>`.  To remove the quoted email (with top posting), you have to open the  `:PROPERTIES:` drawer.  With the above, you can edit the quoted email.

**Comment by djcb** [comment]
Not planning to add this mu4e; so I'd recommend `org-msg` instead, and configure that or ask the developers to improve it.
