### ISSUE TITLE
[mu4e bug] document the appropriate hooks to use for post message display tweaks (as mu4e-view-mode-hook occurs before gnus ariticle display)

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#2029]
**Describe the bug**

I was running mu4e-patch-highlight from the mu4e-view-mode-hook but something in the render chain resets the  buffer contents voiding any changes it makes. I can't quite follow the order but is there a hook that is called when everything is done?

**To Reproduce**

with a checkout of https://github.com/seanfarley/mu4e-patch

(use-package mu4e-patch
  :load-path  "~/src/emacs/mu4e-patch.git"
  :config (add-hook 'mu4e-view-mode-hook #'mu4e-patch-highlight))

**Environment**

Debian 10 Linux, emacs master branch, mu master branch

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [ ] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

Obviously didn't tick without 3rd party extensions because this is an interaction with one.

**Comment by djcb** [comment]
Guess this is with the gnus viewer? You could try hooking to `gnus-article-prepare-hook` instead.

**Comment by stsquad** [comment]
Yeah - the patch stuff is removed after (run-hooks 'gnus-article-decode-hook)

**Comment by stsquad** [comment]
I can't use gnus-article-prepare-hook as it doesn't seem to get called. Currently I've hacked a run-with-idle-timer as described in: https://github.com/seanfarley/mu4e-patch/issues/4

**Comment by djcb** [comment]
Can you attach a message where this happens?

**Comment by djcb** [comment]
Stale -> Closing.
