### ISSUE TITLE
[mu4e bug] Text after signature mark -- disappears from mu4e-compose buffer (gnus)

### ISSUE THREAD

**Issue by averter** [djcb/mu#2031]
**Bug description**
When replying to an email which contains the signature symbol `--` this bug filters it out along with all subsequent text from the compose buffer. My guess is that this bug is related with two factors:
- use of gnus
- how my signature is inserted, see my latest solution [here](https://github.com/djcb/mu/issues/706), 

When replying to an email, I would expect for all visible text to be prepended by a new `>` and included in my reply. 
Notes: When I hover the mouse over the `--` symbol in mu4e-view mode it is displayed as a link.

**To Reproduce**
1. Using gnus, apply the above solution to insert a signature at the top of a message and above the quoted reply
2. Exchange 3-4 emails between two mu4e-contexts accounts (one of which containing the signature of point 1)
2. When replying to the created email thread the text after and including the `--` symbol is deleted.

**Environment**
Linux Mint 20.1, Emacs 26.3, mu4e 1.4.15.

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by ChauhanT** [comment]
I don't think this is a bug. Given the specifications and definitions, this is how one would expect signatures to work.

But someone consistently corresponding with people using exchange, gmail and all kinds of service provides, it is definitely something that occurs often enough to be an issue. Perhaps this could be a feature request of sorts? I totally agree with the OP that it would be very nice to be free from the -- signature convention which is now quite outdated imo.

**Comment by averter** [comment]
> this is how one would expect signatures to work.

how come? To delete all text after the `--` symbol? Thunderbird allows to put the signature above the quoted reply and does not delete any of the quoted text. I find this behaviour quite disturbing. Is there any work around? Thanks.

**Comment by djcb** [comment]
Yeah, it seems that it works according to various standards / conventions. I guess you work around it by _not_ using the message-separator? For mu4e it's defined as `"^-- *$"`.

If that's not good enough, you can configure `mu4e-compose-cite-function` and do what you want.

**Comment by smalltimer** [comment]
> > this is how one would expect signatures to work.
> 
> how come? To delete all text after the `--` symbol? Thunderbird allows one to put the signature above the quoted reply and does not delete any of the quoted text. I find this behaviour quite disturbing. Is there any work around? Thanks.

Yeah, I agree. The `--` is definitely outdated now. I also face the issue you are facing, and was trying to find a solution - which is how I ended up reading this thread.  Software for displaying emails have become more sophisticated and can handle more complex rules for identifying signatures (thunderbird, outlook, even gmail-online have more complicated rules to identify signatures). I have not been able to find a workaround. 

I'm going to try @djcb 's suggestion and attempt to turn off the message separator. 

Also, @djcb , thank you for creating and sharing this fantastic software with the community <3

**Comment by djcb** [comment]
So closing this.... a PR for a note in doc on how to get a different `--` behavior would be welcome.

**Comment by smalltimer** [comment]
I got too snowed under this week and still haven't resolved it. Gonna try and look at it this w/e, and if I succeed I'll do a PR for the doc. And hyvää juhannusta ;)

**Comment by djcb** [comment]
:+1:

**Comment by nxtruong** [comment]
At least for me, the easiest solution is to add the following line to my init, which completely disables removing text below any signature in a reply message. This makes mu4e behave similarly to other email clients (i.e., keeping all the text in the original message).
```
(setq mu4e-compose-cite-function 'message-cite-original)
```
