### ISSUE TITLE
[mu4e rfe] Permit the archiving / moving / deleting of multiple messages while a message is being viewed

### ISSUE THREAD

**Issue by aheays** [djcb/mu#2033]
**Is your feature request related to a problem? Please describe.**
Including multiple messages in the active region in headers view permits them to be archived  (or some other action ) with a single key press, but this does not work when a message is begin viewed (an error message "user-error: [mu4e] No message at point" is generated).  It is then necessary to first close the view message or perform the action on each message in header-view individually.

**Describe the solution you'd like**
To permit multi-message headers-view actions while a message-view window  is open.

**Additional context**
mu4e FTW

**Comment by djcb** [comment]
What happens is that when you mark a message in the headers view when there's also a message view open, it'll open the _next_ message and leave focus in the message view (I see some slightly different errors, but we're two years later!).
