### ISSUE TITLE
[mu bug] Segmentation fault on mu find with link format

### ISSUE THREAD

**Issue by bratekarate** [djcb/mu#2035]
**Describe the bug**
`mu find format=links linkdir <query>` causes segmentation fault.

**To Reproduce**
Execute `mu find format=links linkdir <query>` with commit 035a10ab49439bd1d2e250d87d369307d86a31b3 or newer. The last working commit for me was 86e1515c71ca628456e3f1957f69c60433f1bd6c. The commits in between those two commit cause build errors for me, so I cannot precisely pinpoint the commit that actually causes this issue for me.  

**Environment**
Arch Linux
Kernel 5.12.9-arch1-1
mu devel, commit 035a10ab49439bd1d2e250d87d369307d86a31b3 or newer

**Checklist**
- [x] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Thanks - fixed.

**Comment by bratekarate** [comment]
Thank you for this great piece of software and the quick fix!
