### ISSUE TITLE
mu4e always loads html part of email no matter what

### ISSUE THREAD

**Issue by NinKenDo64** [djcb/mu#2037]
## Expected or desired behavior

1. After making sure that `mu4e-view-prefer-html` is `nil` and having set `mu4e-view-html-plaintext-ratio-heuristic` to `most-positive-fixnum`, I expect that when opening an email that has both a plaintext and html part, mu4e would display the plaintext part by default.

2. When changing the value of `mu4e-html2text-command` to something other than the default, I expect the rendering of these html emails to change.

## Actual behavior

1. Instead mu4e renders the html part of the email, with the plaintext part as an attachments, and I must manually move to the attachment and hit `<return>` to load the plaintext version of the email.

2. Instead, mu4e seems to ignore this variable entirely. I even changed it to a nonsense value and nothing was effected.

## Steps to reproduce

Open any message that has both a plaintext and html part in mu4e-view.

## Versions of mu, mu4e/emacs, operating system etc.

Linux infoOS 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux

GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29) of 2021-05-06

mu4e - mu for emacs version 1.5.13

## More detail

I've included these two behavours in one report as I suspect they are related somehow, mu4e seems to be ignoring any customised render settings.

**Comment by djcb** [comment]
Those variables are only relevant for the old message view, not the gnus-based one (which is the default on 1.5.x). See the sections `Reading rich-text messages` in the info manual.

**Comment by NinKenDo64** [comment]
Thanks, I had started to wonder about a couple mentions of gnus view mode here and there. For some reason I couldn't load the info until I did so indirectly through a describe-variable page I loaded up as I was browsing the source, so I wasn't aware there was a new manual available. Thanks for your help, I will be reading through it now.
