### ISSUE TITLE
With thread-folding mu4e doesn't go to next visual message 

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#2038]
This is not a mu4e bug in itself, but an improvement to allow third party package https://github.com/rougier/mu4e-thread-folding
to work properly.

## Expected or desired behavior

Go to next visual message when thread is fold.

## Actual behavior

Go to an invisible message when thread is fold.

PR #2036 is fixing this.

Thanks.

**Comment by djcb** [comment]
That one has been merged.
