### ISSUE TITLE
[mu4e bug] mu4e-view-show-addresses lost in transition to gnus-based viewer

### ISSUE THREAD

**Issue by antoine-levitt** [djcb/mu#2040]
I liked the behavior of mu4e-view-show-addresses nil in the old mu4e viewer, which now appears to be lost with the gnus viewer. Is there any way of getting it back?
(opposite issue as https://github.com/djcb/mu/issues/1903)

**Comment by antoine-levitt** [comment]
Another feature lost in transition is the nice coloring of the headers that the old mu4e viewer had

**Comment by djcb** [comment]
It works a bit different in gnus view; I don't know a direct way to do that (which doesn't mean there isn't -- at least you have various hooks); anyway, if you really depend on that, the old view should be around for a while still.
