### ISSUE TITLE
[mu4e bug] mu4e-view-fields ignored by gnus viewer

### ISSUE THREAD

**Issue by antoine-levitt** [djcb/mu#2041]
mu4e-view-fields appears to be only partially respected by the gnus viewer. In particular I couldn't get it to not show the Reply-To header without removing it from gnus-visible-headers. Is the intent that only the latter variable should be modified?

**Comment by djcb** [comment]
indeed, `mu4e-view-fields` can only _add_ fields to the gnus article views', not remove them. I've updated the docstring.

**Comment by antoine-levitt** [comment]
OK, thanks! The ordering is still a bit mysterious to me (it does From, then Subject, then To, which is a bit weird), I'll try to see if I can figure it out
