### ISSUE TITLE
[mu4e rfe] Add pipe ("|") support

### ISSUE THREAD

**Issue by telmich** [djcb/mu#2042]
**Is your feature request related to a problem? Please describe.**

I want to pipe emails to external programs like procmail for taking specific actions

**Describe the solution you'd like**

Key binding of "|" to pipe the raw message to an external progrem

**Describe alternatives you've considered**

None suitable in the mu4e context

**Additional context**

This would be very much in line with how emacs works in other modes and allows to extend mu4e easily.

**Comment by thierryvolpiatto** [comment]
Nico Schottelius ***@***.***> writes:

> Key binding of "|" to pipe the raw message to an external progrem

Did you try "|" from view mode?

-- 
Thierry

**Comment by telmich** [comment]
I feel stupid. I only tried from the headers view. Would it be possible to add `|` to headers view, acting on the currently selected messages? Flow wise this would allow something like:

* pipe to something
* wait
* archive maill if process exists 0

**Comment by thierryvolpiatto** [comment]
Nico Schottelius ***@***.***> writes:

> Would it be possible to add | to headers view, acting on the currently
> selected messages?

It is bound as well in `mu4e-headers-mode-map` the command is `mu4e-view-pipe`.

-- 
Thierry

**Comment by djcb** [comment]
Great.
