### ISSUE TITLE
[mu4e rfe] Thread gathering cutoff interval

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#2043]
**Is your feature request related to a problem? Please describe.**
It would make sense in the headers view to limit how far threads are reassembled, by using a cutoff.

I have this common issue where people reply to an existing thread just to find my address.
As a result I do occasionally see threads-from-the-dead being resurrected from 5 years ago just for a completely new message.

**Describe the solution you'd like**
If the time between replies is higher than a specified threshold (say, 3 months), I don't want to include these messages when "related" is enabled. On the other hand, when using mu4e-action-show-thread, I'd like the entire thread to be shown without a cutoff applied.

It would also be fine (and actually nice), logically speaking, if threads that have been split like this to be shown as separate roots if the query happens to match messages from both sides of the threads.

**Describe alternatives you've considered**
Not sure there's any, but I remember using some similar feature in gnus eons ago =)

**Comment by djcb** [comment]
That sounds complicated! Perhaps just remove the References: header from such messages?

**Comment by wavexx** [comment]
I'm not sure how I achieved that at the time in gnus (likely a custom thread-gathering function), but I remember that I was using several strategies to cut threads, with cutoff being the simplest, and subject simplification+match was another.

Do you think that it would be complicated to implement? I never looked at the threading code in mu/mu4e, but it shouldn't be that different than regular behavior. When fetching the parent(s), simply ignore any whose interval is larger than the cutoff.

**Comment by djcb** [comment]
There are few things where the word 'simply' applies here :)

Threading is non-trivial, and I'm not really looking forward to adding any options there, as it complicates (future) maintenance, even if it's just about user-misconfiguration.

**Comment by wavexx** [comment]
Ehehe, I see. But can I ask for a pointer on where to look if I wanted to give this a shot? I kind of lost track if threading is now done in mu or mu4e.

I'd like to make a crude implementation and see if that's actually worth pursuing.
