### ISSUE TITLE
mu4e-view-headers-next in mu4e-view-mode is broken with visual-line-mode

### ISSUE THREAD

**Issue by DiGitHubCap** [djcb/mu#2044]
When visual-line-mode is enabled, it is impossible to view the next message from the message view buffer when the current header is visually wrapped. I believe this problem was introduced by c3c8e534 where forward-line was changed to line-move (which moves by visual lines by default, whereas the former does not).

**To Reproduce**
1. Enable visual-line-mode or global-visual-line-mode in the mu4e-headers buffer.
2. Resize your window so that the headers are wrapped.
3. Open a message.
4. Try to use mu4e-view-headers-next to switch to the next message.
5. Observe that the cursor moves to the next visual line, which is still the same message, and then jumps back to the beginning of the previous line.

**Environment**
OS: Arch Linux / Debian 11 (reproduced on both)
Emacs: 27.2 / 27.1
mu/mu4e: 1.5.13 r7034556a

**Comment by thierryvolpiatto** [comment]
DiGitHubCap ***@***.***> writes:

> When visual-line-mode is enabled, it is impossible to view the next message from the message view buffer when the current header is visually wrapped. I believe this problem was introduced
> by c3c8e53 where forward-line was changed to line-move (which moves by visual lines by default, whereas the former does not).
>
> To Reproduce
>
>  1. Enable visual-line-mode or global-visual-line-mode in the mu4e-headers buffer.
>  2. Resize your window so that the headers are wrapped.
>  3. Open a message.
>  4. Try to use mu4e-view-headers-next to switch to the next message.
>  5. Observer that the cursor moves to the next visual line, which is still the same message, and then jumps back to the beginning of the previous line.

A possible fix is moving to eol before trying to go to next-line:

    diff --git a/mu4e/mu4e-headers.el b/mu4e/mu4e-headers.el
    index 4663e1c6..6530eec3 100644
    --- a/mu4e/mu4e-headers.el
    +++ b/mu4e/mu4e-headers.el
    @@ -1846,7 +1846,9 @@ docid. Otherwise, return nil."
       (cl-flet ((goto-next-line
                  (arg)
                  (condition-case _err
    -                 (and (line-move arg) 0)
    +                 (progn
    +                   (move-end-of-line 1)
    +                   (and (line-move arg) 0))
                    ((beginning-of-buffer end-of-buffer)
                     1))))
         (let* ((_succeeded (zerop (goto-next-line lines)))

> Environment
> OS: Arch Linux / Debian 11 (reproduced on both)
> Emacs: 27.2 / 27.1
> mu/mu4e: 1.5.13 r7034556a
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

**Comment by DiGitHubCap** [comment]
> A possible fix is moving to eol before trying to go to next-line: diff --git a/mu4e/mu4e-headers.el b/mu4e/mu4e-headers.el index 4663e1c6..6530eec3 100644 --- a/mu4e/mu4e-headers.el +++ b/mu4e/mu4e-headers.el @@ -1846,7 +1846,9 @@ docid. Otherwise, return nil." (cl-flet ((goto-next-line (arg) (condition-case _err - (and (line-move arg) 0) + (progn + (move-end-of-line 1) + (and (line-move arg) 0)) ((beginning-of-buffer end-of-buffer) 1)))) (let* ((_succeeded (zerop (goto-next-line lines)))

That seems to break mu4e-view-headers-prev instead. Also, using a prefix argument for moving to the Nth next header does not work correctly, since it still moves by visual lines.

**Comment by thierryvolpiatto** [comment]
DiGitHubCap ***@***.***> writes:

>     A possible fix is moving to eol before trying to go to next-line: diff --git a/mu4e/mu4e-headers.el b/mu4e/mu4e-headers.el index 4663e1c6..6530eec3 100644 --- a/mu4e/mu4e-headers.el
>     +++ b/mu4e/mu4e-headers.el @@ -1846,7 +1846,9 @@ docid. Otherwise, return nil." (cl-flet ((goto-next-line (arg) (condition-case _err - (and (line-move arg) 0) + (progn +
>     (move-end-of-line 1) + (and (line-move arg) 0)) ((beginning-of-buffer end-of-buffer) 1)))) (let* ((_succeeded (zerop (goto-next-line lines)))
>    
> That seems to break mu4e-view-headers-prev instead. Also, using a
> prefix argument for moving to the Nth next header does not work
> correctly, since it still moves by visual lines.

Ah indeed yes, another solution would be to prevent users turning on
visual-line-mode in headers view...

-- 
Thierry

**Comment by DiGitHubCap** [comment]
> Ah indeed yes, another solution would be to prevent users turning on visual-line-mode in headers view...

That is one option, but it's not ideal, because using visual-line-mode in the headers view is a valid preference, and mu4e probably shouldn't override this. The variable `line-move-visual` seems to configure whether `line-move` moves by visual lines or not, so I tested setting it to nil in a let block around `line-move`, and it seems to be working so far. I'll try to submit a PR for it later today.

**Comment by thierryvolpiatto** [comment]
DiGitHubCap ***@***.***> writes:

>     Ah indeed yes, another solution would be to prevent users turning on visual-line-mode in headers view...
>    
> That is one option, but it's not ideal, because using visual-line-mode
> in the headers view is a valid preference, and mu4e probably shouldn't
> override this. The variable line-move-visual seems to configure
> whether line-move moves by visual lines or not, so I tested setting it
> to nil in a let block around line-move, and it seems to be working so
> far.

Of course it is working, but what I mean is it is strange to enable
visual-line-mode and want to move by logical line.

> I'll try to submit a PR for it later today.

Thanks, I guess what you want is something like: 

    (let ((line-move-visual (not visual-line-mode))) [...])


> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

**Comment by DiGitHubCap** [comment]
> Of course it is working, but what I mean is it is strange to enable visual-line-mode and want to move by logical line.

Well, the issue for me personally is that I use global-visual-line-mode to use visual lines *everywhere* by default, and it's difficult to opt-out of that on a per-mode basis. Other modes shouldn't break just because this is enabled. Also, though it may seem counter-intuitive, enabling visual-line-mode doesn't necessarily mean you want to *move* by visual lines. visual-line-mode is also the simplest way to wrap text by default in Emacs. For example, evil-mode moves by logical lines by default regardless of whether visual-line-mode is enabled or not (and it seems to use the same trick of binding line-move-visual in a let block). When I'm in the mu4e headers view, j and k (the vi keys to move up and down) are not the keys for moving across lines, they are the keys for moving across headers, so it makes perfect sense that this should disregard visual lines.

> Thanks, I guess what you want is something like: (let ((line-move-visual (not visual-line-mode))) [...])

I think just binding it to nil should work, just like evil-mode does. I can't think of any reason why you would want it to be non-nil.

**Comment by thierryvolpiatto** [comment]
DiGitHubCap ***@***.***> writes:

>     Of course it is working, but what I mean is it is strange to enable visual-line-mode and want to move by logical line.
>    
> Well, the issue for me personally is that I use
> global-visual-line-mode to use visual lines everywhere by default, and
> it's difficult to opt-out of that on a per-mode basis.

    (defun my-disable-visual-mode ()
      (visual-line-mode -1))
    (add-hook 'mu4e-headers-mode-hook 'my-disable-visual-mode)

> I think just binding it to nil should work, just like evil-mode
> does.

No, it makes no sense to bind it to nil, better time in this case to use
forward-line as before.

> I can't think of any reason why you would want it to be non-nil.

The purpose of using line-move instead of forward-line is to skip
invisible lines with mu4e-thread-folding-mode and yes we need a non nil
value for line-move-visual.


-- 
Thierry

**Comment by DiGitHubCap** [comment]
> (defun my-disable-visual-mode () (visual-line-mode -1)) (add-hook 'mu4e-headers-mode-hook 'my-disable-visual-mode)

I tried doing that, of course, but visual-line-mode was somehow toggled back on anyway. Regardless, mu4e should not break when visual-line-mode is enabled.

> No, it makes no sense to bind it to nil, better time in this case to use forward-line as before.

If we switch back to forward-line, won't that break mu4e-thread-folding-mode, as you said? Although there is a function called forward-visible-line. I wonder if that could work. line-move-visual *needs* to be nil when visual-line-mode is enabled in order for header navigation to work.

> The purpose of using line-move instead of forward-line is to skip invisible lines with mu4e-thread-folding-mode and yes we need a non nil value for line-move-visual.

If line-move-visual is non-nil, then navigating the headers will break when visual-line-mode is enabled. Not breaking mu4e with very common stock modes should come before ensuring compatibility with any 3rd-party mu4e add-ons.

**Comment by djcb** [comment]
So, what can we do to resolve this? Some alternatives:

1) Revert c3c8e53
2) Disable visual-line-mode in headers-mode
3) Something else?

I'm fine with either, but I'm leaning towards 2). Can't say I fully understand all the nuances though! What do you think?

**Comment by DiGitHubCap** [comment]
@djcb I opened PR #2045 to fix this. It seems to be working fine for me.

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> So, what can we do to resolve this? Some alternatives:
>
>  1. Revert c3c8e53
>  2. Disable visual-line-mode in headers-mode
>  3. Something else?

The PR #2045 from @ DiGiHubCap is working fine as well for me.

-- 
Thierry

**Comment by djcb** [comment]
Great, thanks! Merged that.

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> Great, thanks! Merged that.

Thanks, I will have to submit a little change on top of this which fix
mu4e-view-headers-prev with invisible lines (need to skip invisible
cookie at bol with move-to-column), will submit a PR soon.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry
