### ISSUE TITLE
[mu4e bug] Contact completion uses old/no alias

### ISSUE THREAD

**Issue by matzebond** [djcb/mu#2047]
**Describe the bug**
I have a contact whom I would like to complete via the alias because it is easier to remember. The completion candidates only show an entry without the alias.

A possible cause could be that the very first mail with this contact did not include the alias and is only addressed `To: person@mail.com` later mails have the alias like `From: alias <person@mail.com>` and the backend `mu cfind` also shows the entry with the alias.

`(mu4e-contacts-info)` only shows the `person@mail.com` entry. I also tried `(mu4e-clear-cache)` followed by `(mu4e~request-contacts-maybe)` with the same result.

Any ideas what i could try next or is this a bug?

Could be similar to https://github.com/djcb/mu/issues/2000

**Environment**
Linux, Emacs 27.2, mu4e 1.4.13

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Can you reproduce with 1.5.x?

**Comment by matzebond** [comment]
I have the same problem with the development version build from the master branch which reports the version number 1.5.13.
Btw I will publish a `mu-git` package to the Arch Linux AUR :-)

**Comment by matzebond** [comment]
After being on 1.5.13 for a while now I have the desired entry in `(mu4e-contacts-info)`. I can't say exactly when/how it happened but consider this issue solved.
There is still some junk left in the contacts list most likely from messages in the trash. But after deleting those messages updating the index an the mu4e-contacts it still shows up in `mu cfind` and mu4e. Any tips which commands i have to run to update?

**Comment by djcb** [comment]
Guess you can search for the unwanted contacts, and see what messages they belong to?

**Comment by matzebond** [comment]
I did that e.g. with the accidental "To: mailto:<adress>" mail removed it via `(mu4e-headers-mark-for-delete)` then `(mu4e-update-mail-and-index)` but the "mailto:..." contact still shows up in `mu cfind` and `(mu4e-contacts-info)` (after refreshing mu4e's cache).

**Comment by djcb** [comment]
If there are no more occurrences of the unwanted contact in your mail corpus, `mu init` etc. should to the trick (merely removing the mails won't remove the (cached) addresses).

**Comment by matzebond** [comment]
That worked. Thank you very much for your help and mu(4e) in 
general!!!
