### ISSUE TITLE
[mu4e bug] mu4e-view-show-images not respected when using gnus-based message view

### ISSUE THREAD

**Issue by manufactory** [djcb/mu#2051]
**Describe the bug**
When `mu4e-view-show-images` is set, attached images are not shown automatically in the gnus-based message view. All you see is something like `[1. image/png; cats.png]...` at the bottom of the message. When you press return on that, the picture is shown. This happens in mu4e 1.4.15 and 1.5.13, for HTML mails as well as for plain text mails. Images are shown as expected in mu4e 1.4.15, when the old message view is used, i.e. `mu4e-view-use-gnus` is set to `nil`.

**To Reproduce**
`emacs  -Q`
```
(add-to-list 'load-path "<path to>/mu/mu4e")
(require 'mu4e)

(setq mu4e-mu-binary "<path to>/mu/mu") ;; if using a
(setq mu4e-contexts ...)
(setq mu4e-view-use-gnus  t) ;; if using 1.4.15
(setq mu4e-view-show-images t)
```

**Environment**
Arch Linux, Emacs 27.2, mu 1.4.15/1.5.13 (I tried with both versions)

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by djcb** [comment]
See the manual (the one for the new version!), and the recent discussion in the mailing list on this for some more info on how to do this with the new new. `mu4e-view-show-images` doesn't do anything there, I've updated the docstring.
