### ISSUE TITLE
[misc] [mu4e] Tip: `user-mail-address' ('???@gmail.com') is not part of mu's addresses; add it with 'mu init                         --my-address='

### ISSUE THREAD

**Issue by zw963** [djcb/mu#2056]
**Describe the issue**
I always get the the above message when i start mu4e.
I tried to run command follow the tips

```sh
 ╰─ $ 1  mu init
error: failed to open store @ /home/zw963/.cache/mu/xapian: Unable to get write lock on /home/zw963/.cache/mu/xapian: already locked
```

**Environment**
arch linux, with self compiled mu 1.5.14, mu4e 1.5.13, emacs self compiled 27.2

Thank you.

**Comment by Chris00** [comment]
On 24 July 2021 at 23:51 -07, "Billy.Zheng" ***@***.***> wrote:
> Describe the issue I always get the the above message when i start mu4e.  I tried to run command follow the tips
>
>  ╰─ $ 1 mu init error: failed to open store @ /home/zw963/.cache/mu/xapian: Unable to get write lock on /home/zw963/.cache/mu/xapian: already locked

After being careful that no instance of mu is running (in particular, quit mu4e if launched), you may want to remove `/home/zw963/.cache/mu/xapian/flintlock'

**Comment by zw963** [comment]
Thank you, it works after remove that file.

so, can i know what is the purpose of run `mu init --my-address='my_email@gmail.com'`?

**Comment by thierryvolpiatto** [comment]
"Billy.Zheng" ***@***.***> writes:

> [[PGP Encrypted Part:OK]]
> Thank you, it works after remove that file.
>
> so, can i know what is the purpose of run mu init ***@***.***'?

Try mu help init.

-- 
Thierry

**Comment by zw963** [comment]
> Try mu help init.

Yes, thank you, i check it, it say setting up mu database, i an wonder why before init it, it's seem like works too
