### ISSUE TITLE
[misc] xapian/mu hangs on macos when run mu index/init

### ISSUE THREAD

**Issue by yqrashawn** [djcb/mu#2057]
This is not a mu bug but more like a xapian problem. Cause notmuch has the same problem. I searched for this multiple times online. Can find the solution. 

Single core hit 100% even there's only 5 mails in the mail dir.

stack trace generated by /usr/bin/sample

http://ix.io/3u5K

**Comment by djcb** [comment]
Oh, that's annoying... did you report it to the Xapian people?

**Comment by yqrashawn** [comment]
Just found that there're two mu processes every time i run index or init. Is it the desired behavior?
<img width="1582" alt="Screenshot-2021-07-31-16 03 01@2x" src="https://user-images.githubusercontent.com/15090582/127733374-ead0317f-1632-4884-9b3e-072f88981046.png">

**Comment by djcb** [comment]
Likely those are different threads, check your htop display options.

**Comment by djcb** [comment]
Anyway, I don't think I can do anything about this from `mu`... please report to the Xapian people.
