### ISSUE TITLE
[mu bug] `mu index` with 1.6 does always report 0 messages

### ISSUE THREAD

**Issue by norbusan** [djcb/mu#2058]
**Describe the bug**

With the latest release it seems to me that `mu index` always reports 0 messages:
```
$ mu index
indexing maildir /home/norbert/Maildir -> store /home/norbert/.cache/mu/xapian
/ indexing messages; processed: 0; updated/new: 0; cleaned-up: 0
```

But in the meantime there have been definitely messages added.

**To Reproduce**
Run mu index from 1.4 version, then from 1.6.

**Environment**
Debian/unstable, I am the maintainer of mu in Debian and am preparing 1.6 for upload.

**Checklist**
- [x] you are running either the latest ~~1.4.x~~ 1.6.x release ~~, or a 1.5.11+ development release (otherwise, please upgrade).~~ (template needs update!)

**Comment by theophilusx** [comment]
It is likely this is due to updates in Xapian. I would delete the .cache/mu
directory, then run mu init and mu index. I was running the dev version (1.5.x) and have had no problems since updating to 1.6.0 (Ubuntu 21.04). However, I do recall having to wipe out the old .cache files and re-init when I moved from 1.4 to 1.5.


Regards,

Tim

--
*Tim Cross*

/For gor sake stop laughing, this is serious!/

**Comment by norbusan** [comment]
Hi @theophilusx 
thanks, indeed. Removing `.cache/mu` and reinitializing it did work and started counting immediately.

It would be great if mu could determine such a situation automatically and either clear the xapian index automatically or at least give a warning - at least that is what I would like to see for users in Debian who might get caught by surprise.

**Comment by norbusan** [comment]
Ok, there are more strange things going on with mu index ...

Running it the first time after removing the cache:
```
[~] mu index
indexing maildir /home/norbert/Maildir -> store /home/norbert/.cache/mu/xapian
\ indexing messages; processed: 210748; updated/new: 210007; cleaned-up: 0
```

Waiting an hour or so, and rerunning mu index
```
[~] mu index
indexing maildir /home/norbert/Maildir -> store /home/norbert/.cache/mu/xapian
- indexing messages; processed: 53500; updated/new: 53505; cleaned-up: 0
```

Huuu, 53505 new/updated ... no way

Immediately rerunning mu index after the previous:
```
[~] mu index
indexing maildir /home/norbert/Maildir -> store /home/norbert/.cache/mu/xapian
| indexing messages; processed: 3280; updated/new: 3282; cleaned-up: 0
```

Another 3000?

After that I can run mu index repeatedly for about 10 times, always got
```
 [~] mu index
indexing maildir /home/norbert/Maildir -> store /home/norbert/.cache/mu/xapian
\ indexing messages; processed: 0; updated/new: 0; cleaned-up: 0
```
despite having deleted files from Maildir.

Then, a few minutes later, again:
```
[~] mu index
indexing maildir /home/norbert/Maildir -> store /home/norbert/.cache/mu/xapian
/ indexing messages; processed: 8542; updated/new: 8542; cleaned-up: 0
```

I am running `mbsync` in the background that syncs imap accounts to maildirs below ~/Maildir. This has worked great till 1.4, but now it seems that index is behaving very strangly.

**Comment by theophilusx** [comment]
that does sound unusual. The first thing I would try is turn of mbsync and then
run mu index multiple times over an exended period and see if your still seeing
changes. If you don't, then perhaps there is something in your mbsync
configuration which is causing changes to the maildir layout which is triggering
the need for mu index to update things. If you still see new indexing when
mbsync is not running and your not modifying anything with mu4e, there might be
something needing more investigation.

Regards,

Tim

--
*Tim Cross*

/For gor sake stop laughing, this is serious!/

**Comment by ricma** [comment]
Morning!

not sure whether related but I get similar issues: Only a few of the 40,000 messages in the Maildir get indexed.

When running `mu index --debug` I get this via `journalctl -xe`

```
Jul 28 08:53:59 hostname mu[782113]: scan takes too long; dropping 24522 file(s) from queue 
```

If I run `mu index --quiet` it will add a few more messages each time to the store.

**Comment by djcb** [comment]
Hmmm.... I suspect I know what's going on, pushed a fix. Can you try?

**Comment by ricma** [comment]
You are ace! That works.

I build the current `master` (71b9c7f59874b36b8be3f5cda3ceae527320113d) and the indexing went through without any problems on my side:

Did not abort, no errors in the logs.


Thank you very much!

**Comment by norbusan** [comment]
Thanks @ricma it looks better now. There are other issues but I open a new ticket.

**Comment by djcb** [comment]
Okay, great. Closing this one.
