### ISSUE TITLE
Make it possible to disable the message in the minibuffer when index/mails are updated

### ISSUE THREAD

**Issue by steckerhalter** [djcb/mu#206]
It's quite annoying to have the messages from mu4e about "index running" etc. obstruct any prompts in the minibuffer so that I can't even see what I should have answered with with "y" or "n"

There should be at least a variable to disable that behavior...

**Comment by edumerco** [comment]
Maybe we could indicate mail fetching and/or indexing in the modeline... in this way we could look at it if it's important, but there be no blocking or hiding of important messages or interaction. 
WDYT?
