### ISSUE TITLE
[misc] v1.6.0 compilation error on Windows 10 + Cygwin : ‘strerror’ was not declared in this scope; did you mean ‘g_strerror’?

### ISSUE THREAD

**Issue by vchouraki** [djcb/mu#2060]
**Describe the issue**
1. git clone mu
2. launch Cygwin64 terminal
3. go to mu folder
4. run autogen.sh (no error)
5. run make
6. Following error is displayed : 
```bash
mu-indexer.cc:341:70: error: ‘strerror’ was not declared in this scope; did you mean ‘g_strerror’?
  341 |                 g_critical("'%s' is not readable: %s", mdir.c_str(), strerror (errno));
```

**Environment**
Results from ./autogen.sh on Windows 10 21H1 + Cygwin setup 2.909 + gcc-g++ 10.2.0-1
```bash
mu configuration is complete.
------------------------------------------------
mu version                           : 1.6.0

Xapian version                       : 1.4.5
GLib version                         : 2.54.3
GMime version                        : 3.0.5
Build mu4e                           : yes
Emacs version                        : GNU Emacs 27.2
Build 'mug' toy-ui (gtk+/webkit)     : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
------------------------------------------------
```
**Comments**
- With the same setup, I can build v1.4.15 without any error
- Noticed that v1.6.0 .cc files use a lot more strerror than v1.4.15
- I replaced all strerror with g_strerror and could build v1.6.0 without any error (but I don't know anything about c++ so I don't know if this is legit)
- Could it be some missing "include" statement (again I don't know anything about c++) ?

**Comment by djcb** [comment]
Yeah, it's a missing `#include <string.h>` or `#include <cstring>`. In the non-Cygwin build that gets included indirectly, but on Cygwin apparently it doesn't.

Using `g_strerror` is a good alternative as well.

I'll prepare a change.
