### ISSUE TITLE
[mu bug] (1.6.0) --lazy-check does not find new messages

### ISSUE THREAD

**Issue by lordpretzel** [djcb/mu#2064]
**Describe the bug**
When  `--lazy-check` is used with `mu index`, then new / updated messages are not found. I am using `mbsync` on Mac OS to sync my Maildir. I updated from `1.4.15` where this worked. This problem already happens on the commandline, so probably unrelated to `mu4e`

**To Reproduce**
- update maildir with `mbsync`
- send yourself an email
- update maildir with `mbsync`
- run `mu index --lazy-check`
- the indexer does not show any new / updated messages
- using `mu find` the new message does not show up
- running `mu index` without `--lazy-check` does then find the new messages

**Environment**
- OSX Big Sur (11.5)
- Emacs 28.0.50 (emacs-plus)
- mu 1.6.0 (homebrew)
- Maildir is synced with `mbsync`

**Checklist**
- [X] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by stormbr** [comment]
I found the same problem. I am using emacs 27.1.

**Comment by djcb** [comment]
Can you try with 1.6.1? it has some changes that might make a difference here.

**Comment by lordpretzel** [comment]
absolutely. BTW, in #2066 people mentioned they had to rebuild the index. Should I rebuild the index from scratch after the  update to 1.6.1?

**Comment by lordpretzel** [comment]
Hi, I should have had a closer look before filing the issue, but better late then never. 1.6.1 does not resolve the issue. The problem is that my maildir is structured like this:

~~~
~/Maildir/email-account1/INBOX
~/Maildir/email-account1/Spam
...
~/Maildir/email-account2/INBOX
...
~~~

Now the issue is that when `mbsync` does update the individual folders, the 2nd level folders modification timestamps are updated, but not the first level ones. I checked and I can see in the `mu` log, it shows that it it skips all 1st level folders:

```
2021-07-30 21:05:10 ** (mu:40040): DEBUG: 21:05:10.426: skip /Users/lord_pretzel/Maildir/email-account1 (seems up-to-date)
```

I've checked the mu source code and I believe the right way to fix this is to only skip actual mail dirs and never skip other folders. This probably should not really impact performance, because the costly part is to check the files storing mails. I did implement a fix and tested it. If you think this is reasonable I can open a pull request.

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> [[PGP Encrypted Part:OK]]
> Can you try with 1.6.1? it has some changes that might make a difference here.

Also using a recent xapian version helps.

-- 
Thierry

**Comment by djcb** [comment]
@lordpretzel: note, The lazy-check works the way it does because people have _very_ slow filesystems, and I got a bit bored with the complaints , so I don't want it to become a `--semi-lazy-check`, even if the current is not optimal for this specific case as it would break others.

Anyway, you can of course set `mu4e-get-mail-command` to a shell-script that takes care of `touch`-ing `email-account-1` if any of its children has a newer date. Or, easier, you can turn off the lazy check. How much is the difference in your case?

**Comment by lordpretzel** [comment]
@djcb thanks for the quick response and this great piece of software that I am using as my daily mail driver. In my use case  (~700k emails) the difference is quite significant. Without `--lazy-check` it takes 50 seconds and with `--lazy-check` it takes 0.5 seconds if there are no updates and a few sec if there are. Since I have mu4e setup to check mail every 10 min, without this option mu4e would be unusable ~10% of the time because of reindexing. I was also considering a shell script as a workaround. 

I can understand that you are between a stone and a hard place here, because either behavior would cause complaints from some users. If you are hesitant to introduce a new `--only-a-bit-lazy-check` option with this behavior, then I think the documentation of `--lazy-check` could be improved to reduce confusion for users with multi-level maildirs. Something like: "Note that the mail client, e.g., mbsync, that you are using to update your Maildir's content may not update the modification timestamp of parent directories when modifying the content of a directory. This can cause false negatives, because `--lazy-check` does skip directories based on their modification timestamp."

**Comment by djcb** [comment]
I _hope_ that in the next dev series (1.7.x) we can change things so that mu4e is still usable while indexing, so we can avoid trickery. 

That said, 50 sec sounds like a very, very long time. ~90K messages, and a non-lazy check takes just a fraction of a sec. Do you have some profiling software to see where the 50 sec is spent?

**Comment by lordpretzel** [comment]
yes, looking forward for the async indexing in the future! Since I have a fast drive, it sounds there is something going wrong. I'll do some profiling and will let you know the result.

**Comment by lordpretzel** [comment]
ok, 75% of the time is spend in `stat`. and ~10% in `read` (from xapian). 

![Untitled](https://user-images.githubusercontent.com/2989731/127951298-3654e0bd-ed54-4406-a0c3-723e89b107bd.jpg)

Reading up on this, it seems that apple's APFS implementation is CPU intensive and not very parallel (saw some people complaining about git performance on OS X that is also slow in `stat`). I've seen some general recommendation to move from `stat` to `fstatat`. I tried this and on just reading the directory entries it improves performance by 50%:

~~~c
#include <stdlib.h>
#include <stdio.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <fcntl.h>
#include <unistd.h>

int main(int argc, char *argv[])
{
    char *dirstr = "/Users/lord_pretzel/Maildir/account1/AllMAil/cur";
    struct stat statbuf;
    DIR *dir;
    int numf = 0;
    const struct dirent *dentry;
    struct timeval st;
    unsigned long start, end;

    dir = opendir(dirstr);
    int dirfd = open(dirstr, O_RDONLY);

    while((dentry = readdir(dir)))
    {
        int r = fstatat(dirfd, dentry->d_name, &statbuf, 0);
    }

    close(dirfd);
    closedir(dir);

    gettimeofday(&st, NULL);
    start = st.tv_sec * 1000000 + st.tv_usec;

    dir = opendir(dirstr);

    while((dentry = readdir(dir)))
    {
        char *fullpath = (char *) malloc(1024);
        sprintf(fullpath, "%s/%s", dirstr, dentry->d_name);

        if(stat(fullpath, &statbuf))
        {
            printf("couldn't stat %s\n", fullpath);
        }
        numf++;
    }

    closedir(dir);

    gettimeofday(&st, NULL);
    end = st.tv_sec * 1000000 + st.tv_usec;
    printf("[stat] time: %lu\n", end - start);

    // fstatat
    gettimeofday(&st, NULL);
    start = st.tv_sec * 1000000 + st.tv_usec;

    dir = opendir(dirstr);
    dirfd = open(dirstr, O_RDONLY);

    while((dentry = readdir(dir)))
    {
        int r = fstatat(dirfd, dentry->d_name, &statbuf, 0);
    }

    close(dirfd);
    closedir(dir);

    gettimeofday(&st, NULL);
    end = st.tv_sec * 1000000 + st.tv_usec;
    printf("[fstatat] time: %lu\n", end - start);

    return 0;
}
~~~

 and implementing it in `mu` I see an improvement from 50 to 40 sec.

**Comment by MarcvdSluys** [comment]
I got here because of the same issue.  I also have more than one email account and use the same directory structure.  I have ~200k emails and mu index takes ~1.79s, with --lazy-check 0.73s, so I can live with this.  I am reporting this merely to indicate to @lordpretzel that it looks like the cause of his 50s indeed lies outside mu.

However, I agree that a remark in the manual (and release notes? - it took me a bit of experimenting to figure this one out after updating to v1.6) might be useful.  In addition, I could imagine more people opt for 'our' directory structure, because it basically allows you to sync multiple addresses without renaming your mailboxes (without these subdirectories, there would be many "INBOX"es).

And while I'm here I'd like to thank @djcb and the other devs for this great piece of software, which I'm using every day (at least once every 15 minutes, syncing and indexing in the background ;-)).

**Comment by djcb** [comment]
@lordpretzel: thanks for the analysis, very interesting! that certainly points at some of the pain points on macos...; I'll have a look at using `fstatat` once the new 1.7 dev series start. One other thing I'm considering is using file-system monitoring instead (or in addition to) explicit scanning.

@MarcvdSluys: thanks for the nice words! I've added a few notes to the lazy-check docs. I'll see how to document it a bit better.... but hopefully it can be made to "just work".

**Comment by lordpretzel** [comment]
@djcb thanks, monitoring would probably be a great idea. To verify a bit further whether there is something specific to my Maildir, I tried on linux / ext4 with the same Maildir on a slightly slower SSD. A full `mu index` with cleanup ran in 9 sec for ~700k emails and 1.3 sec with `lazy-check` and `--nocleanup` on mu 1.4.15. I also tried with 1.6.12 and the number
@MarcvdSluys: out of curiosity what OS / file system are you on.

**Comment by MarcvdSluys** [comment]
@lordpretzel Oops, I wanted to mention that: Gentoo Linux, mu 1.6.1, emacs 27.2, xapian 1.4.18, isync (mbsync) 1.3.6.

**Comment by djcb** [comment]
I did make the "lazy-check" a bit less lazy, which should hopefully allow for using that flag (1.6.3)

**Comment by lordpretzel** [comment]
thanks, that is great!
