### ISSUE TITLE
[misc] Increment version numbers after updates

### ISSUE THREAD

**Issue by theophilusx** [djcb/mu#2065]
**Describe the issue**

would it be possible to ensure the version number is incremented after changes? For example, since the release of 1.6.0, there has been at least 2 updates to the code base, but the version is still being reported as 1.6.0. 

As an example of why this would be useful. One of the updates has been to fix an issue with mu index. While it appears that issue has now been fixed, if someone encounters the same issue, they will report it, referencing version 1.6.0. At this point, we don't know if what they are reporting is because they are still running the original 1.6.0 release code or if the problem is because the fix introduced after the release of 1.6.0 has not completely resolved the problem. If on the other hand, the current head version was (for example) 1.6.2, we would know straight away which version of the code the user is running and therefore whether they should just update or we should look at the fix more closely. 

I would also highly recommend using the github release feature so that the repository is tagged with new versions. Currently, the last version tag was for 1.4.15.

**Comment by djcb** [comment]
In general, agree. But _just_ after a .0 release a bunch of new issues / fixes tend to accumulate... so don't want to increase the number for each one, esp. with fixes unconfirmed. Anyway, 1.6.1 will be soon.

Regarding the tags, my Github shows a "Release 1.6.0" as the latest, and it has a 1.6.0 git version tag. Do you mean something else?

**Comment by theophilusx** [comment]
Hi Djcb,

I think you may need to push your branches up to github. When I do a git branch -a all I get is

master
release/1.4.x
remotes/origin/HEAD -> origin/master
remotes/origin/master
remotes/origin/release/1.4.x

and when I check on github using the web UI, only master and release-1.4.x are
listed. If you have created the branches locally, you have to tell github about
them before they will be pushed up i.e. add as a remote.

Up to you re: version numbers. While I do agree it can be good to 'bundle' some
changes, in general, I tend to just increment the number when the code changes.
I use semantic versioning and find the patch number rarely gets very high before
there is an API change, requiring a sub-version increment and I find larger path
numbers are worth it if it helps narrow down the version of code someone is
using. It also helps ensure updated code gets picked up - especially relevant
for automated build/packaging systems like brew, which I think uses version
numbers to determine when to package up a new version.

I guess it is all about getting the balance right!

Regards,

Tim

--
*Tim Cross*

/For gor sake stop laughing, this is serious!/

**Comment by djcb** [comment]
There's 1.6.1 now :). I'll start the 1.6.x branch as soon as we start the 1.7 dev in master.

**Comment by djcb** [comment]
Anyway, closing this now. Thanks for your thoughts -- hope the current method is not too annoying!
