### ISSUE TITLE
[mu4e bug] mu4e-headers-field-properties-function not working/implemented

### ISSUE THREAD

**Issue by OlMon** [djcb/mu#2067]
**Describe the bug**
There is a variable `mu4e-headers-field-properties-function` but there is no code using it. Changing the value does nothing.
This is related to #1771 and #1355 but one issue is already closed and the second is more general with outdated solutions and the above mentioned variable is only inside a comment [written by me].

**To Reproduce**
- Change the value of the variable `mu4e-headers-field-properties-function`
- See no changes in header view

**Environment**
mu/mu4e 1.6.0

**Checklist**
- [ x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [ x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [ x] you are running the latest 1.6.x release

**Comment by djcb** [comment]
Yeah, I'll remove the entry, it's an old leftover.

**Comment by OlMon** [comment]
Does this mean, there is no direct way to colorize the headers?

**Comment by djcb** [comment]
It's emacs, so there's always a way... but not through this function. It tends to slow down the rendering quite abit.
