### ISSUE TITLE
[mu bug] Incorrect message when schema version is not up-to-date

### ISSUE THREAD

**Issue by norbusan** [djcb/mu#2069]
**Describe the bug**

Run `mu index` without upgrading/reinitializing the database:

```
$ mu index
error: expected schema-version expected schema-version %s, but got %s; please use 'mu init', but got 452
```

The error message is a but strange ...

- [X] you are running either the latest 1.6.x release, namely 1.6.1

**Comment by djcb** [comment]
Ugl, that's clumsy! Thanks for reporting.

**Comment by norbusan** [comment]
Uups, that was a trivial fix, should have sent a PR ... thanks for quick reaction!
Uploading 1.6.1 plus this fix now to Debian (experiment, until bullseye is released)

**Comment by DarkBuffalo** [comment]
I have the same problem and yet I have version 1.6.1
`mu init` and `mu index` does not change anything
