### ISSUE TITLE
[mu4e bug] Mark as read Inbox + Archive in Google

### ISSUE THREAD

**Issue by danielfleischer** [djcb/mu#2071]
Using V1.6.0, I've noticed a different behavior than v1.4.15: using Google, each new message is both in Inbox and in Archive (All Mail). When viewing unseen messages, I used to see only the Inbox ones (toggle skip duplicates) and upon reading them, the archive ones were marked as read as well. Now the archive messages are unchanged with viewing the Inbox ones. Thanks!

**Comment by djcb** [comment]
Yeah, that changed...

**Comment by danielfleischer** [comment]
Can you provide some guiding? I can use diffs to find it and recreate this feature. Is it mu or mu4e related?

**Comment by djcb** [comment]
I've added a few lines that should help for this... does it fix the problem?

**Comment by danielfleischer** [comment]
Pulled the new changes; unfortunately, it still doesn't mark the the other message as read.
