### ISSUE TITLE
Gnus-based message view loads external images, enabling tracking

### ISSUE THREAD

**Issue by jturner314** [djcb/mu#2072]
**Describe the bug**
The [docs say](https://www.djcbsoftware.nl/code/mu/mu4e/MSGV-Rich_002dtext-and-images.html#Inline-images) that mu4e does not load external images in HTML messages by default. However, it actually loads external images. I see #1434, which was fixed, but that was a couple of years ago. I'm guessing that the bug was reintroduced in 6f206f0f7edea078b10db687e5dff3b708aa0c56.

**To Reproduce**
1. Remove `~/.emacs.d/url/cache`.
1. Set `url-debug` to `t`.
2. Open an HTML email with external images in mu4e.
3. Watch HTTP requests going out in the `*URL-DEBUG*` buffer.

I do have various customizations to my config, but nothing which should affect external image loading. If you're not able to reproduce the issue, I'll work on minimizing my config to determine if there's a specific config option which causes the issue.

**Environment**
- OS: Arch Linux
- Emacs: 27.2
- mu/mu4e: 1.6.1. I'm using the gnus-based viewer, which is the default for this version.
- gnus: 5.13 (built-in)

**Workaround**
Adding either of these lines to my config fixes the issue:
```elisp
(setq gnus-inhibit-images t)
(setq gnus-blocked-images ".")
```

**Comment by djcb** [comment]
Ah, good catch... yeah, gnus blocks by default, but that blocking doesn't work for mu4e (depends on gnus-specifics).

Changed that, so the default does its thing, and update the docs as well.

**Comment by jturner314** [comment]
Thanks!
