### ISSUE TITLE
[mu4e bug] Regression: mail body appears as empty

### ISSUE THREAD

**Issue by malb** [djcb/mu#2073]
**Describe the bug**

When I open e-mails (work emails so presumably written in Outlook) I see an empty mail body instead its text.

I tried to bisect a for a bit and got this far:

| `1.6.0~54` | broken |
| `1.6.0~123` | works, I used to run this |

**To Reproduce**

Open mu4e on an e-mail, observe empty mailbody

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

- GNU/Linux
- Emacs 28.0.50, commit: e77bd6e8bf0601029465f1af11bbef97ba2d1f49

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by Chris00** [comment]
A (curated) email example that triggers the bug would be useful — I also receive lots of emails composed with Outlook and I have no problem seeing them.

P.S.  Emails sent by Outlook tend to have `Content-Type: text/html; charset="utf-8"` without a plain text counterpart.  The default `mm-text-html-renderer` is `shr` which requires Emacs to be compiled with `libxml2` support.

**Comment by malb** [comment]
Hi there,

Here's an [example email](https://github.com/djcb/mu/files/6917693/example.txt). Sorry, should have done this directly. libxml2 is available. That said *some* but not all e-mail are rendered when I use: `(setq mm-text-html-renderer 'gnus-w3m)`.

**Comment by Chris00** [comment]
This is what I see when opening the example email (I can click on the text part and see it as well):
![image](https://user-images.githubusercontent.com/1255665/127880720-26ba9944-f0e4-466b-8b74-e3352e3aa031.png)

**Comment by malb** [comment]
Right, so (unsurprisingly) this seems to be a local problem then. Thanks!

**Comment by Chris00** [comment]
I am at commit 793eca15 (version 1.6.1) BTW.

**Comment by malb** [comment]
FYI: I had https://emacs.stackexchange.com/questions/58268/mu4e-gnus-ms-safelinks-decoder in my config … sorry for the noise.

**Comment by Chris00** [comment]
If you find what's wrong with it, you may want to post an updated version on the [above mentioned page](https://emacs.stackexchange.com/questions/58268/mu4e-gnus-ms-safelinks-decoder) as it may be useful to others.

**Comment by averter** [comment]
Ahh, great that you flagged that the issue comes from the unsafelinks function (recently updated to 1.6.2). 
Did you manage to solve the issue while filtering MSsafelinks? I echo Chris comment, in that it would be very useful to collaboratively update that function.

**Comment by malb** [comment]
I hacked together a solution like this:

```emacs-lisp
(defun malb/unsafelinks (&optional vmode)
  "This function filters MS safelinks from a message buffer"
  (interactive)
  (save-excursion
    (beginning-of-buffer)
    (let ((inhibit-read-only t)
          (simple-url-regexp "https?://") urls)
      ;; edit text URLs
      (while (search-forward-regexp simple-url-regexp nil t)
        (when-let ((url (thing-at-point 'url))
                   (bounds (thing-at-point-bounds-of-url-at-point)))
          (delete-region (car bounds) (cdr bounds))
          (insert (malb/decode-safelink url))))
      ;; edit widget URLs
      (beginning-of-buffer)
      (while (not (eobp))
        (goto-char (next-overlay-change (point)))
        (when-let (link (get-text-property (point) 'shr-url))
          (and (string-match simple-url-regexp link)
               ;; change overlay url echo
               (when (overlay-put (car (overlays-at (point))) 'help-echo (malb/decode-safelink link)) t)
               ;; change url text-properties
               (add-text-properties (point) (next-overlay-change (point))
                                    (list 'shr-url (malb/decode-safelink link) 'help-echo (malb/decode-safelink link)))
               ))
        (goto-char (next-overlay-change (point))))
      (when vmode
        (remove-overlays)
        (mu4e~view-activate-urls)
        (set-buffer-modified-p nil)))))

 (defun malb/unsafelinks-advice (msg)
  (malb/unsafelinks t))
       
(advice-add #'mu4e~view-render-buffer :after #'malb/unsafelinks-advice)        
```

**Comment by averter** [comment]
Thanks @malb. I've updated my [original post](https://github.com/djcb/mu/issues/1689) on github with your function and updated some other functions: to see filtered links in the web-browser and when creating an org-mode entry based on an icalendar invitation. Hopefully some of those functions will turn out to be useful to other users.
