### ISSUE TITLE
[mu4e] `:thread-subject` looks worse in 1.6.x

### ISSUE THREAD

**Issue by joostkremers** [djcb/mu#2078]
**Describe the bug**

I just updated to the latest commit (dadd3062; before I was on a11008de), and it seems that `:thread-subject` has stopped working. All messages in a thread now have the subject shown in the headers view.

[edit] As it turns out, this only seems to happen with messages from mailing lists. Personal conversations are fine. Also, the arrows that indicate the threading structure are still there.

**Environment**

Emacs 27.1, latest mu/mu4e.

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

(I guess the checklist isn't entirely up-to-date. :slightly_smiling_face: )

**Comment by djcb** [comment]
It might show some more headers in some cases (ie. each level), but that's intentional. Only the first of siblings would be shown though. Do you see something else?

**Comment by joostkremers** [comment]
Well, this is what I see now:

![Screenshot from 2021-08-08 13-19-27](https://user-images.githubusercontent.com/191630/128630279-30ae3aa1-754f-485b-b1b9-57a118f0b9ca.png)

While before, I would see something like this (this is an old screenshot from a different maildir, but it shows the difference well enough):

![mu4e-46bd705-full-search-off](https://user-images.githubusercontent.com/191630/128630352-02748966-91ba-4cda-9e18-0948e9de740c.png)

I don't know if what I see corresponds to what you intended, but I definitely prefer the earlier display...

**Comment by djcb** [comment]
It's indeed working as "intended" (I think there's some ML discussion even), but admittedly in your example it doesn't look great.

I'll see if there's some better way...

**Comment by joostkremers** [comment]
> It's indeed working as "intended" (I think there's some ML discussion even), but admittedly in your example it doesn't look great.
> 
> I'll see if there's some better way...

I missed that ML discussion (haven't been following the ML very closely lately), but yeah, a little less clutter would be nice. :slightly_smiling_face:

**Comment by joostkremers** [comment]
Thanks! With the latest changes, it definitely looks better. :slightly_smiling_face:
