### ISSUE TITLE
[mu4e rfe] Allow to exclude certain mail directories from `mu cfind` results

### ISSUE THREAD

**Issue by gusbrs** [djcb/mu#2080]
**Is your feature request related to a problem? Please describe.**

It is not a "problem", but a possibility of improvement. I find the way `mu(4e)` handles contact completion pretty clever, and love "not having to worry" about a contact list for email address completion. But it is sometimes hard to avoid a degree of unwanted results in the completion list.

Of course there is a compromise to be met in the automatism `mu cfind` offers and some degree of noise. But, to my unhappiness, I have fallen trap of some pretty aggressive spammers recently, and the level of "noise" has come to a point where it is becoming counterproductive. And, I can't see a situation where I'd like to complete a spammer's email address, and I'd love to be able to exclude my Junk/Spam folder from the results of `mu cfind`.  And that's the feature request I make.

**Describe alternatives you've considered**

I'm aware of `mu4e-compose-complete-only-personal`, of `mu4e-compose-complete-only-after` and of `mu4e-contact-process-function`. In particular, `mu4e-compose-complete-only-personal` does not quite handle the situation many (most?) spam mail we receive is directed explicitly to our email address. Also, as far as I can tell, `mu4e-contact-process-function` also cannot handle the situation, since we cannot know where that contact came from at that point. Of course, from there we could filter results by means of a "blacklist" of addresses, but that seems like an uphill battle, and would certainly count as duplicate work, since we already flagged the message as spam.

**Describe the solution you'd like**

I'm suggesting some means to exclude certain maildirs from the results of `mu cfind` would be very welcome. Naturally, with the corresponding "handle" on `mu4e`'s side, I'd presume in the form of an user option.

PS: Btw, v1.6 is pretty sweet, thank you!

**Comment by djcb** [comment]
It'd be useful to have a bit more control over those cached addresses, but using the target folder is a little tricky; since `mu cfind` has no idea what message a certain address came from. Doing it before/during indexing has a some challenges as well.

Until we find a good way, one workaround is to periodically clear your spam mailbox, and rebuild the database (with `mu init` etc.). Or you can decide _not_ to index the spam mailbox at all in mu (see `.noindex` in the mu-index manpage), and do that with some other program (or perhaps on the web, if your mail is synced with that).

**Comment by gusbrs** [comment]
@djcb , thank you for your answer, and for the workaround tips. And I'm glad you find the suggestion interesting in principle even if tricky to implement in practice. I'll be thankful if a way can be found eventually.

**Comment by djcb** [comment]
There's no plan to implement this, I'll close this for now. I hope the workarounds are sufficient. Sorry!

**Comment by gusbrs** [comment]
@djcb No problem, and thanks for considering. Cheers! :smile:
