### ISSUE TITLE
[mu4e rfe] :thread-subject should not distinguish between Re: and RE:

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2083]
As a folloup to https://github.com/djcb/mu/issues/2078, some mailers (e.g. Outlook web application) change the preceding `Re:` in subjects to `RE:`.  It would be nice if this modification was ignored by `:thread-subject`.

**Comment by djcb** [comment]
Don't want to make that too complex, (.e.g. `Re/Fwd`, possible sequences of those, now repeat for many languages... would be overkill), but anyway the check is already fuzzy: we see if the previous subject is a suffix of the current on (with diff length max 5).

Anyway, Re:/RE: shouldn't make a diff. Does it?

**Comment by Chris00** [comment]
> Anyway, Re:/RE: shouldn't make a diff. Does it?

It seems it does (I haven't examined the algo).  Not sure what the “right” decision is.  Maybe case insensitiveness on a 2–3 letters prefix (preceding `:`)?

![image](https://user-images.githubusercontent.com/1255665/128986865-1ad5d081-2f5c-4667-b46b-5b2e1ea917ff.png)

**Comment by skyler544** [comment]
What about making this a configurable variable and leaving it up to the user to set which string needs to be matched? I have this same problem as I regularly send messages in two languages and threads can end up with more than one RE:/Re:/AW:/Aw: preceding the subject.

**Comment by djcb** [comment]
I'll add add a heuristic that ignores everything up until the first ':'.  It's not configurable, it's in c++.

**Comment by Chris00** [comment]
The old version displayed some header as
![image](https://user-images.githubusercontent.com/1255665/129076224-dca79fb6-0485-4df5-ae3d-4a29605665a7.png)
The new one does
![image](https://user-images.githubusercontent.com/1255665/129078179-0f2d8b8c-a0a4-45e1-9746-24268d7041cc.png)

The first thread image is now much better:
![image](https://user-images.githubusercontent.com/1255665/129078560-67ceac4f-36a9-410b-b40c-c841dc18a359.png)
