### ISSUE TITLE
[mu4e bug] mu4e-index-lazy-check is too lazy in v1.6 (was not the case with v1.4)

### ISSUE THREAD

**Issue by prosoitos** [djcb/mu#2084]
**Describe the bug**

Since the update to v1.6, I have been unable to update the index without killing mu server.

Until v1.4, because I am running an Emacs sever, I could update my index by running:

```el
emacsclient -e '(mu4e-update-index)'
```

Or by running `mu4e-update-index` from within Emacs.

Since the update to v1.6, `mu4e-update-index` has no effect (and does not trigger any error). The synced messages are in `Maildir` (so this is not a problem with my syncing tool), but they just don't show in mu4e.

The only way I currently have to update the index is to kill mu server, then run `mu index`.

Note: I deleted .mu, re-initialized mu and re-run `mu index` and that did not help. 

**To Reproduce**

I don't know whether this is reproducible as it could be something liked with my system (v1.6 has been around for some time now and it is suspicious that nobody else has complained about this...).

Reverting to v1.4 solved the problem though, so, while it may be in part caused by something in my init file, v1.6 is clearly what is triggering this.

**Environment**

OS: Arch Linux 5.13.9-arch1-1
Emacs: 27.2-1
mu: 1.4.15-1 (works fine) or 1.6.2-1 (can't update the index)

**Checklist**

- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by djcb** [comment]
So indexing works with `mu index` from the command-line, but not when running from emacs? And apart from indexing, mu4e works as well?

The (default) message view is quite different from the one in 1.4, it's now Gnus-based, hence the different faces. There are some notes about that in NEWS.org.

**Comment by prosoitos** [comment]
> The (default) message view is quite different from the one in 1.4, it's now Gnus-based, hence the different faces. There are some notes about that in NEWS.org.

Ah, that explains that 🙂 Sorry I missed it in the release news. I thought this was probably not related, but threw it in in case.

> So indexing works with mu index from the command-line, but not when running from emacs?

If I kill mu server first (since there can only be one process and the lock will prevent to run this when mu server is running), yes, it works. So I could set a kbd to kill mu server then run `mu index` as a workaround. But I'd rather figure out why `mu4e-update-index` doesn't work.

> And apart from indexing, mu4e works as well?

Yes. Other than this indexing issue, everything works normally.

**Comment by Chris00** [comment]
Did you try to turn debug on: `(setq mu4e-debug t)`?  The output is in the `*mu4e-log*` buffer.

**Comment by prosoitos** [comment]
I had not. Thank you for the suggestion.

Here is what I get in the log buffer when I run `mu4e-update-index`:

```el
2021-08-11 15:56:25.746 * Received 152 byte(s)
2021-08-11 15:56:25.746 <- (:info index :status running :processed 0 :updated 0 :cleaned-up 0)
2021-08-11 15:56:25.747 <- (:info index :status complete :processed 0 :updated 0 :cleaned-up 0)
```

**Comment by prosoitos** [comment]
And indeed, that corresponds to what I am experiencing: no error message, but nothing is actually happening (for info, just before running `mu4e-update-index`, I sent myself an email and that email is in Maildir. It just does not get indexed).

**Comment by Chris00** [comment]
Is the value of `mu4e-mu-binary` the same as `which mu`?

**Comment by prosoitos** [comment]
Yes. In my system, they both are `/usr/bin/mu`.

**Comment by prosoitos** [comment]
I found the cause of the problem!!!

I have `mu4e-index-lazy-check` set to `t`.

While this worked just fine with v1.4, somehow (at least for me), this doesn't work with v1.6. Returning that variable to the default fixed the problem.

**Comment by prosoitos** [comment]
Ah! We thought of  `mu4e-index-lazy-check` at the same time lol. I wrote my comment above before reading yours (we posted pretty much at the same time).

So ya, that's the problem.

Now... is it just for me or can you reproduce the problem by setting it to `t`???

**Comment by prosoitos** [comment]
If that can help, I can run mu with the debug flag and post back. But now that I have pinpointed the problem to lazy checking, maybe that isn't necessary anymore.

Just let me know.

**Comment by prosoitos** [comment]
The fact that the problem is with lazy checking also explains why I wasn't getting any error message. It's just a question of identifying what needs to be re-indexed (rather than something more serious).

**Comment by djcb** [comment]
Ah, great!

In general its better _not_ to lazy-check unless that makes things unbearably slow. Even more so if it turns out to be _too_ lazy (as in this particular case).

I'll think a bit about how to detect the 'too lazy' case, to at least _warn_ users.

**Comment by prosoitos** [comment]
OK. Happy to close this issue if you think it wise as I am happy with the default (I had set this on a previous computer which was very slow but it isn't an issue with the one I currently use).

So I am sorted.

Now, for some reason, v1.4 and v1.6 behave very differently with that option. Not sure whether or not it is worth digging into why.

**Comment by prosoitos** [comment]
Anyhow, thanks everyone for your inputs (and thanks for mu and mu4e!!! ❤️ )

**Comment by djcb** [comment]
I've made it a bit less lazy, it seemed the current behavior tripped up more users, and it's not obvious what's wrong. So let's make it a bit less lazy!

Thanks for the inputs!

**Comment by deerpig** [comment]
I had the same problem.  running vanilla emacs on clean debian install, latest emacs and mu 1.6 stopped working.  set lazy check to nil and the problem went away.   Thank you all, this was driving me nuts.
