### ISSUE TITLE
[mu4e bug] -- maybe? How do I automatically remove drafts/stop making them?

### ISSUE THREAD

**Issue by plantarum** [djcb/mu#2085]
**Describe the bug**

I don't know if this is actually a bug. My Drafts folder is full of messages that I've actually sent. This seems similar to what's reported in #1479. I expect there's a way to fix this with my Emacs back-up config, but I'm not sure how to proceed. Looking for suggestions as to how to set up Emacs' backup options to eliminate the problem.

**To Reproduce**

Here is the content of my /Drafts/cur folder:

```
ls -ht | head
#1628778509.b0e6f0159832fdef.onottra696862xl,U=383:2,DS#
#1628721767.3e5bc88d3b6b5ee5.onottra696862xl,U=382:2,DS#
#1628531584.d662865a8388a846.onottra696862xl,U=377:2,DS#
#1628520818.320292841bfa4088.onottra696862xl,U=376:2,DS#
#1628519653.5fe057f85fa223bc.onottra696862xl,U=375:2,DS#
#1628352246.3574d24e26083205.onottra696862xl,U=374:2,DS#
1628199508.21620_1.ONOTTRA696862XL,U=373:2,DST
#1628186766.ba99d0293d497492.onottra696862xl,U=372:2,DS#
#1627567784.4eeeadaf6b2c1f13.onottra696862xl,U=371:2,DS#
#1627566951.9f66b3245879d3b5.onottra696862xl,U=370:2,DS#
```

Most of the files are 'backups', i.e., with the `#` pre/suffixes. The top/most recent message is one I just sent, the original of which is found in /Sent Mail/cur (without `#`). It took me a few minutes to compose; I didn't deliberately save a draft, I think it was only Emacs backup system that created it.

**Environment**

I have set `backup-by-copying` to `t` in my Emacs config, otherwise all backup settings are default. 

I'm using Emacs 28.0.50, mu4e 1.6.0, on Ubuntu 18.04.

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by theophilusx** [comment]
Do you have things setup so that mu4e runs your syncing program (e.g.
mbsync) automatically at regular intervals? If this is the case, the
issue could simply be that mu4e is running mbsync when your in the
middle of writing an email. This can result in the message your writing
being picked up and synced to the remote server. When you send the
message you are composing, the draft is removed, but because it has been
synced, it is brought back next time mbsync runs.

The only way I found to reduce this was to increase the interval between
mu4e running my sync program. Now I only see these drafts appear if I
spend longer editing a message than the sync interval.

**Comment by djcb** [comment]
You can set `backup-directory-alist` to let emacs write the backup files in some different places.

**Comment by plantarum** [comment]
Thanks!

From the Emacs manual, I can use the 'invisible directory'  `.~` for backups, which creates a subdirectory in the same directory of the directory of the original file. If I did that, will mu ignore it when indexing, or would it cause problems?

**Comment by djcb** [comment]
Yeah, dotdirs are ignored.

**Comment by plantarum** [comment]
Perfect, thanks again!

**Comment by averter** [comment]
I think that the side-effect of the proposed solution is lots of backup emails in the created (and invisible) directory?
As long as auto-saving messages during composition is not required, a better solution would be instead to add the following hook to `init.el`
```` elisp
(add-hook 'mu4e-compose-mode-hook #'(lambda () (auto-save-mode -1)))
````
Source is [here](https://emacs.stackexchange.com/questions/21723/how-can-i-delete-mu4e-drafts-on-successfully-sending-the-mail)
