### ISSUE TITLE
[mu bug] mu fails to build on macOS 10.10 and 10.11 (only)

### ISSUE THREAD

**Issue by ra1nb0w** [djcb/mu#2086]
**Describe the bug**
Hi,
I am the maintainer of mu on macports and I am noticing the following build failures on macOS [10.10](https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/152312/steps/install-port/logs/stdio) and [10.11](https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/150942/steps/install-port/logs/stdio). 
But, I can't figure out what is the problem.

**To Reproduce**
```
autoreconf
./configure
make
```
This is the [macports file](https://github.com/macports/macports-ports/blob/3464e112c9cdeee39d11d91ff49c0ec97c9e38fd/mail/mu/Portfile)

**Environment**
You find everything in the logs.

thank you very much

**Comment by ra1nb0w** [comment]
Fixed with blacklisting old clang.

**Comment by DaviRaubach** [comment]
Hi there. How one can blacklist old clang? Thanks
