### ISSUE TITLE
[mu4e bug] On the splash screen, the number of unread messages is always double the actual number.

### ISSUE THREAD

**Issue by marcSoda** [djcb/mu#2088]
**Describe the bug**
When I enter mu4e, under the `Bookmarks` secrion, the number of `Unread Messages` is always double the number of actual unread messages. When I type `[bu]' to view unread messages, the number of messages in the buffer is half the number of messages I was told there would be.

**To Reproduce**
Described above.

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.
Arch Linux. Emacs 27.2. mu4e 1.6.3.

**Checklist**
- [ x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [ x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [ x] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by djcb** [comment]
From the FAQ (in the manual):
```
C.1.2 The unread/all counts in the main-screen differ from the ’real’ numbers - what’s going on?
------------------------------------------------------------------------------------------------

For speed reasons, the counts do not exclude messages that no longer
exist in the file-system, nor does it exclude duplicate messages
```
does that describe your case?

**Comment by marcSoda** [comment]
I do not believe so. I have never seen a case in which the count was not double on the splash screen. 

This may be relevant: I set
` (setq mu4e-headers-skip-duplicates t)
  (setq mu4e-headers-include-related t)
`
And the result is the same.

**Comment by djcb** [comment]
What about setting both those to `nil`?

**Comment by marcSoda** [comment]
Hi, so sorry for the late reply.

I did that and it appears to be working fine now. 

Thanks !
