### ISSUE TITLE
[mu rfe] Support indexing PDF attachments

### ISSUE THREAD

**Issue by manojm321** [djcb/mu#2095]
mu search is great, only thing that Is missing is searching the attachments like pdf. For this I fallback to gmail search.

For PDFs - text can be extracted using ghostscript.

**Comment by djcb** [comment]
Don't expect `mu` to evolve into a general document indexer. But perhaps it could be done, the multi-core indexing (1.6.x) would help here.

**Comment by djcb** [comment]
I've added this to IDEAS.org, for longer-term research projects, closing here. Thanks!
