### ISSUE TITLE
[mu4e bug] Date header field is not set to message submission time (violates RFC 5322)

### ISSUE THREAD

**Issue by manufactory** [djcb/mu#2096]
**Describe the bug**
When `mail-user-agent` is set to `'mu4e-user-agent`, a time stamp gets added to the message's `Date` header. This timestamp is the timestamp that's used once the message gets submitted. [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.1) explicitly specifies:

> The origination date specifies the date and time at which the creator of the message indicated that the message was complete and ready to enter the mail delivery system.  For instance, this might be the time that a user pushes the "send" or "submit" button in an application program.  In any case, it is specifically not intended to convey the time that the message is actually transported, but rather the time at which the human or other creator of the message has put the message into its final form, ready for transport.  (For example, a portable computer user who is not connected to a network might queue a message for delivery.  The origination date is intended to contain the date and time that the user queued the message, not the time when the user connected to the network to send the message.)

**To Reproduce**
set `mail-user-agent` to `'mu4e-user-agent`, compose a message to yourself, wait some time, check the `Date` header.

**Environment**
mu4e 1.6.3, Emacs 27.2, Arch Linux

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by djcb** [comment]
As a user, I want to be able to control the date; this may not be the same as the submission date. So we can "indicate" some arbitrary date... (so technically even following the letter of the RFC :)) 

I did update the code so you can simply remove the Date: field and mu4e will update it for you when saving.

If you want to _enforce_  updating the date when submitting, there's `message-send-hook`.

**Comment by theophilusx** [comment]
There are also variables you can access under customize, which can
control which headers are injected into the message and when. It should
be possible to get the behaviour you want by tweaking these (see
the customize group for message). Probably easier than writing a hook.

**Comment by evilham** [comment]
As another user, I hate forgetting about the `Date` header being automatically set and then sending the email that I spent 90 minutes carefully crafting with the wrong time in the Date header.

I am certain this is useful for certain people and, in fact, I think it solves a previous issue with Drafts that were saved without a date (thanks, mu4e is indeed great and gets better over time), but having a simple, documented way to disable this, which is counter-intuitive for some of us would likely be much better than not.

Since search engines have bumped this issue, and it will be the de-facto landing page for anyone using mu4e who is surprised by this behaviour, this is the in-configuration hack for those looking for a quick solution:

```elisp
(with-eval-after-load 'mu4e
; Fix for automatic Date header as documented in:
;   https://github.com/djcb/mu/issues/2096
; Judging from:
; https://github.com/djcb/mu/blob/3a39eff1dfc0ffaa663709c3f44b41ce57026eed/mu4e/mu4e-compose.el#L187
; it doesn't look like disabling the Date header injection is possible via
; variables, so we override the function
; Note: Having the Date header "hidden" does not mean it is not generated and
;       sent. So mu4e-compose-hidden-headers won't help.
;       Having the Date header visually set and modifiable, but then removed
;       in a hook is counter-intuitive and removes power from the user, but it
;       is the best thing I came up with without heavily redefining mu4e
;       functions.
;       This relies on your MTA handling the missing header, form msmtp(1):
;        - A Date header will be added if the mail does not have one. This can
;        be changed with the set_date_header command and --set-date-header
;        option.

  (add-hook 'message-send-hook 'mu4ex-override-date-header)
  (defun mu4ex-override-date-header()
    (message-remove-header "Date")))
```
