### ISSUE TITLE
[mu4e rfe] Some interface when waiting for mu4e main

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#2098]
**Is your feature request related to a problem? Please describe.**
When opening mu4e-menu, I sometimes have to wait 1 to 5 seconds sometimes even more (I assume while the database is being indexed). 
This is somewhat frustrating because I am never sure if my key press was ignored. Also, when I give up on mu4e to do something else my current window switches to mu4e when it becomes eventually ready.

**Describe the solution you'd like**
It would be good to show the menu immediately with an "Updating" or even indicating progress on indexing.
Similar to how the "Searching" text does when showing the headers.

**Describe alternatives you've considered**
I am not aware of any available alternatives.

**Comment by djcb** [comment]
Hmm, it should start instantly (less than a second); it may start some background tasks, but already the main screen should be visible.

The only thing that _might_ take a bit of time is if you have many maildirs / bookmarks, and mu4e running 2 queries for each (to get the count / unread number) may take a bit of time. So, add `:hide-unread` to all but the few you're interested in (see the docs).

Otherwise, I don't know, please find what's causing the delay.

**Comment by haji-ali** [comment]
Most of the times it is instant, but after receiving a message going to the main menu is a bit slow for me.
I do have 6 bookmarks that get counted. I will trying adding `:hide-unread` to all to see if it is the source of the latency.

Note that Emacs is not unresponsive while waiting for the menu to come up. So I suspect that the buffer switching is done after receiving the output of some process which is why it is slow sometimes.

**Comment by djcb** [comment]
Thanks for checking... yeah, if you have only a few bookmarks/maildirs in the main menu, that shouldn't be a problem (well, unless you have some very expensive bookmark), anyway that doesn't to be the problem.

Another case could be that you're indexing when bringing up the menu; the menu needs to communicate with the backend, so if the latter is busy, that can take a while.

**Comment by haji-ali** [comment]
> Another case could be that you're indexing when bringing up the menu; the menu needs to communicate with the backend, so if the latter is busy, that can take a while.

Yes, I think that's exactly the issue. My suggestion that the interface should be brought up immediately with an "Updating" marker if needed.

**Comment by haji-ali** [comment]
As an alternative to this rfe. 
I think some way of interrupting a backend update when an action in mu4e is performed would greatly enhance my (and I suspect others') experience. Having a large database and a (somewhat) frequent update cycle means that I frequently have to wait several seconds to perform basic actions in mu4e, like searching for a message or even opening my inbox.

**Comment by djcb** [comment]
Hmm, I never face that problem, but I understand some other people do. 

However, often it comes down to just making the db upgrade faster. Does it take longer than 1-2 sec in your case (i.e., just an update, without mail retrieval)? Even with `mu4e-index-lazy-check`?

If so, are you able to do some profiing with e.g. `perf` on Linux, similar on other systems?

**Comment by haji-ali** [comment]
Yes, I don't mean the message retrieval, just the db update.
It takes about 7-8 seconds. It is not prohibitive, but can be frustrating when I want to get to an email.

I just tried setting `mu4e-index-lazy-check` to t. A new message still seems to cause a full update and takes about 7-8 seconds. But perhaps I will have less updates and less interruptions (I have a busy email address). Is there a non-lazy version of `mu4e-update-mail-and-index` so I can make sure that a deliberate mail update in the background will be followed by an non-lazy index?

I will try profiling with `perf` (need to read up on it) and post the details.

**Comment by djcb** [comment]
What would be useful to see is the the perf report that show where the time is spent. It might that your disk is rel. slow.

**Comment by haji-ali** [comment]
> What would be useful to see is the the perf report that show where the time is spent. It might that your disk is rel. slow.

Does the attached file in my previous answer not contain this info? I never used perf before, so I am not 100% sure.
I will check my disk reading/writing speed.

**Comment by djcb** [comment]
In the 1.7.x series, database updating / indexing is now a background operation, and doesn't fully block mu4e anymore; that should help for this. Anyway, I don't want a "Waiting..." thing, that's something to avoid :-)

Closing this; thanks.
