### ISSUE TITLE
[mu4e bug] `mu find…` doesn't reflect changes done in mu4e until mu4e-update-index is run (e.g. during next automatic update)

### ISSUE THREAD

**Issue by mbunkus** [djcb/mu#2100]
**Describe the bug**

I'm using a script based on two calls to `mu find … | wc -l` in order to display the number of unread & flagged messages in my tmux status line. Before I upgraded to mu 1.6.x, mu4e this worked pretty well.

With v1.6.x the external `mu find flag:unread` command will continue to find messages that have already been read with mu4e in the meantime until mu4e fetches mail or I press `u` (`mu4e-update-index`) manually. As my fetch interval is rather high with something like 10 minutes, this means that tmux continues to show the wrong number of unread mails for a very long time, which makes this method completely useless to me now.

I don't remember how v1.4.x behaved exactly, but it definitely wasn't that big of a delay between changes in mu4e being reflected in search results with `mu`.

For me personally it would suffice if `mu4e-update-index` could be run automatically after changing the header view (e.g. by quitting it back to the main screen or by changing the current search terms) after changes to the index were done inside mu4e (e.g. unflagging, reading an unread mail, deleting one etc.). I'd also be OK (maybe even more so) if `mu4e-update-index` ran after each change to the index; it wouldn't impact me performance-wise. I'd be totally fine with all of that being optional.

**To Reproduce**

1. Switch fetching mail to manual, if currently automatic.
2. Send yourself a mail or two.
3. Fetch mail.
4. Run `mu find flag:unread | wc -l` and remember this number.
5. In mu4e, read the unread mails & quit the header view back to the main screen.
6. Wait two minutes or so.
7. Re-run `mu find flag:unread | wc -l` and observe that the number hasn't changed.
8. Inside mu4e run a search for `flag:unread` and observe that it will not show the messages you've read in step 5.
9. Inside mu4e run `mu4e-update-index` and wait a couple of seconds.
10. Run `mu find flag:unread | wc -l` again. Its number has now changed.

**Environment**

Emacs 27.2
mu/mu4e 1.6.2-1 (Arch Linux package's version)

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Yeah, `mu4e` caches the changes.  Perhaps could be made shorter, or some other method to notify changes. 

As a workaround, you could just run `mu4e-update-index` periodically, `run-at-time` etc.

**Comment by mbunkus** [comment]
I will do that for the time being. Thanks.

**Comment by djcb** [comment]
If you're using `emacsclient`, you could also just tell it to update the index just before you grab your numbers.

**Comment by mbunkus** [comment]
I am, and yes, I've thought about that. However, wouldn't that require using `mu4e-index-update-in-background` `nil`? Otherwise `emacsclient` would exit right after initiating it & the following `mu find…` might still be working on old data.

If so, would this block Emacs (as it isn't multi-threaded) while the update is running? I would find it very annoying if Emacs was blocked even for a small amount of time very 15s or whatever my tmux update interval is.

**Comment by djcb** [comment]
Indexing happens in the `mu` server process, in parallel with `mu4e` /  `emacs`, so it doesn't block it. The index time should be fairly consistent, so you could just wait a few secs...  every 15 sec seems excessive, but you could do it every _n_-th tmux update interval with a little shell scripting.

**Comment by mbunkus** [comment]
Alright, thanks.

For the time being I've settled on a different approach: binding `q` in the header view to my own little function calling `mu4e-update-index` & then the original quit buffer function. That matches my workflow pretty well as quitting the header view is something I consider to be somewhat of an "end of current work" type of activity. As a workaround this suffices.

**Comment by Flinner** [comment]
Can confirm I have this bug

however, `mu find 'flag:unread'` doesn't update to changes in  mu4e unless i kill mu4e

steps to replicate:

1. open mu4e
1. recieve email, and update `mu4e-update-mail-and-index`
2. run  `mu find flag:unread` **it updates and shows correct results**
3. mark email as read/delete it
4. run `mu find flag:unread`, the message remains forever
    - removed in mu4e
    - shows in `mu find flag:unread`
6. try `mu4e-update-index`, and re-run `mu find...`, message remains
7. quit `mu4e`
8. run `mu find flag:unread`, finally the message doesn't show up

**Comment by djcb** [comment]
At least for 1.6.x this is the expected behavior, not a "bug" (externally you won't see the updates until it is committed to the mu/xapian database).

That's still the case on 1.7.x (development series), but it's a bit more aggressive saving things, so the times should be much shorter.

**Comment by Flinner** [comment]
thanks for the fast reply!

appreciate your work :D, can't  wait for 1.7.x

**Comment by Flinner** [comment]
@mbunkus I found (actually squirrelken helped me on doom discord server) a simpler command to count unread messages

```
( ls -l ~/.mail/*/*/new/* 2> /dev/null | wc -l ) || echo 0
```

you might need to change the `mail/*/*/` regex, in mine it counts all `/new/` in all inboxes, in all accounts

```
# only new in Inbox
( ls -l ~/.mail/*/Inbox/new/* 2> /dev/null | wc -l ) || echo 0

# only Inbox in account xx@yy.zz
( ls -l ~/.mail/xx@yy.zz/Inbox/new/* 2> /dev/null | wc -l ) || echo 0

```

**Comment by djcb** [comment]
So in 1.7.x (upcoming 1.8), the updates should be much faster; in many cases almost immediately; but during indexing (transactions) it'll take until the end of that.

Side-note, `ls` (or something like `find ~/Maildir -wholename '*/new/*' -type f -printf '.' | wc -c`) matches _new_ messages, which is not quite the same as unread messages.

Anyway, closing this. Thanks.
