### ISSUE TITLE
[mu4e bug] "Wrong type argument: commandp, mu4e-view-attachment-action" when running `mu4e-view-attachment-action`.

### ISSUE THREAD

**Issue by marcSoda** [djcb/mu#2101]
When I run `mu4e-view-attachment-action` it errors with "Wrong type argument: commandp, mu4e-view-attachment-action". It did not always do this. This started a few days ago. I have not changed my configuration file.

**Environment**
Arch Linux
Emacs 27.2
mu4e 1.6.3

**Comment by djcb** [comment]
That function is not available in gnus-mode.

**Comment by marcSoda** [comment]
How do I disable gnus -ode?

**Comment by djcb** [comment]
You likely don't want to do that... but see NEWS.org.

**Comment by marcSoda** [comment]
So is there a way for me to fix this issue without disabling gnnus-mode?

**Comment by djcb** [comment]
Simple: don't call that function :-) Note, gnus-view has `mu4e-view-mime-part-actions`.
