### ISSUE TITLE
[mu4e rfe] Add --cafter=$(date) in addition to --after

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#2102]
**Is your feature request related to a problem? Please describe.**

Emails have many dates. For a typical user, three may be important:
1. Sent date -- that is the one in the headers, fetched with `mu find date:2021-08-21`
2. Received date -- that is the one fetched with `mu find subject:snow --after=$(date +%s --date='5 min ago')`, usually kept in the stat mtime field
3. Delivered to maildir date -- that is when the message got from the IMAP server to the mu maildir. It is kept in the stat ctime field. 

I am arguing that the third parameter is the most useful for the practical usage of the tool, because it lets the user understand the "bytewise changes" in the maildir. After all, timestamps 1 and 2 may be broken, due to misconfigured clocks on the server and the sender, but the ctime parameter is the end user's and the end user's only responsibility.

**Describe the solution you'd like**

Add a `--cafter="$date"` parameter to `mu find`.

**Describe alternatives you've considered**

There is an easy alternative: 
```
$(find "$MBSYNC_DIR" -cnewer "$REPORTS_DIR"/notify-timestamp -a -type f -not -iname '.uidvalidity' -exec mu view --summary-len=1 {} \; )
```
There is one problem, however, that this search does not  avoid duplicates, whereas `mu find` has the `-u` option.

**Additional context**

Not much.

**Comment by djcb** [comment]
Good news, >= 1.7.18 has the `changed` message field, which tracks the changes (basically, the `ctime`) which you can query for, just like `date`

Closing this.

**Comment by lockywolf** [comment]
I am not sure is is working the way I expect it to work.

```
mu find --after=`date +%s --date='1 days ago'` 'and'
```

find, expectedly, files received yesterday and today, more or less

```
mu find changed:`date +%s --date='1 days ago'`..
``` 

semingly, does not do what I am expecting it to do.

As a simpler example:
```
mu find changed:1658725057..
```
(the time stamp 1658725057 is more or less 2022-07-25T12:57:37+08:00)
does not do what I would expect it to do. I also tried adding a + and a @ (BSD-style?) prefixes to the expression to try and convince `mu` that this is, indeed, a UNIX timestamp, but I haven't actually found a good way to do so.

**Comment by djcb** [comment]
The date format is described in the mu-query man-page; in your query, use `k`, not `changed` (try `mu fields`).

**Comment by lockywolf** [comment]
I have read the mu-query man-page, and it says quite clearly `The shortcut character can be used instead of the full name: <snip> For queries that are not one-off, we would recommend the longer name for readability.` . The full name is `changed`, what is wrong with the query?

**Comment by djcb** [comment]
`--fields "d f s changed"` is not a query
