### ISSUE TITLE
[mu4e bug] - (minus key) not bound to mu4e-view-mark-for-unflag in view mode

### ISSUE THREAD

**Issue by nsc-kronberg** [djcb/mu#2108]
**Describe the bug**

When in mu4e-view-mode, you used to be able to press "+" to flag an email and "-" to unflag it. After upgrading from 1.4.x to 1.6.4, "-" is no longer bound to mu4e-view-mark-for-unflag.

This is strange, since mu4e-view-gnus.el tries to map both + and -:
```
(defvar mu4e-view-mode-map
  (let ((map (make-sparse-keymap)))
[...]
    (define-key map (kbd "+") #'mu4e-view-mark-for-flag)
    (define-key map (kbd "-") #'mu4e-view-mark-for-unflag)
[...]
```

I have verified this in a very minimal configuration (same as in https://github.com/djcb/mu/issues/2107).

When in mu4e:view mode, "C-h k" reports this for "+" and "-":

```
+ runs the command mu4e-view-mark-for-flag (found in
mu4e-view-mode-map), which is an interactive compiled Lisp function in
‘~/pkg/mu/git-1.6.4/share/emacs/site-lisp/mu4e/mu4e-view-common.el’.

It is bound to +.

(mu4e-view-mark-for-flag)

Mark the current message for flag.
```

```
- runs the command negative-argument (found in mu4e-view-mode-map),
  which is an interactive compiled Lisp function in ‘simple.el’.

It is bound to -, M--, C-M--.

(negative-argument ARG)

Begin a negative numeric argument for the next command.
C-u following digits or minus sign ends the argument.
```

C-h v mu4e-view-mode-map returns:
```
mu4e-view-mode-map is a variable defined in ‘mu4e-view-gnus.el’.
Its value is shown below.

  This variable may be risky if used as a file-local variable.

Documentation:
Keymap for mu4e-view mode.

Value:
(keymap
[...]
 (45 . negative-argument)
 (43 . mu4e-view-mark-for-flag)
[...]
```

I worked around the problem by adding this line to my init file, but I don't understand why it is needed.

`(define-key mu4e-view-mode-map    (kbd "-") 'mu4e-view-mark-for-unflag)`

**Comment by djcb** [comment]
This has been fixed.
