### ISSUE TITLE
[mu4e rfe] Allow users to set an organization header with the help of the variable `message-user-organization`

### ISSUE THREAD

**Issue by nils-schween** [djcb/mu#2112]
**Is your feature request related to a problem? Please describe.**
When I was reading my emails, I noticed that some people have the field "Organization" in their email headers. This is nicely displayed by gnus article mode and looks quite professional.  I was wondering if I could do the same and did a quick search and I found the following variable `message-user-organization`. It is described in Section 3.4 of https://www.gnu.org/software/emacs/manual/html_mono/message.html and allows users of gnus to set their organization. 

**Describe the solution you'd like**
I tried to set this variable inside one of my contexts. But unfortunately, it is not used when mu4e-compose is called. 
It would be great if mu4e-compose.el was adapted in a way such that the header field "Organization" is set, if the variable `message-user-organization` is set. (It should be the same as for the variable `user-email-address`. ) And of course, when switching the context in compose-mode, the organization header should be adapted accordingly.

**Describe alternatives you've considered**
For the moment, I am using a compose-mode-hook (as desribed in the mu4e manual https://www.djcbsoftware.nl/code/mu/mu4e/Compose-hooks.html) to add the header field.
```elisp
  (add-hook 'mu4e-compose-mode-hook
  (lambda()
    (let* ((ctx (mu4e-context-current))
            (name (if ctx (mu4e-context-name ctx))))
      (when name
        (cond
          ((string= name "MyContextName")
            (save-excursion (message-add-header "Organization: MyOrganization\n")))
          ;; ((string= name "account2")
          ;;   (save-excursion (message-add-header "Bcc: account2@example.com\n")))
	  )))))
```
This does not automatically adapt when I am switching the context.

**Comment by djcb** [comment]
Implemented.

**Comment by nils-schween** [comment]
Thank you!
