### ISSUE TITLE
[mu4e bug] 

### ISSUE THREAD

**Issue by benmezger** [djcb/mu#2115]
**Describe the bug**

Ocasually (at least once or twice per day), get the following error when marking a message for deletion. 

`error in process filter: mu4e-error-handler: Error 102: failed to move message: cannot read /Users/seds/mail/personal/archives/new/1630078654.16465_5.seds,U=15772:2`
`error in process filter: Error 102: failed to move message: cannot read /Users/seds/mail/personal/archives/new/1630078654.16465_5.seds,U=15772:2`

I've found similar issues in the mailing list and in the Github issues, however, I believe my problem differs a little bit: I don't have `mbsync` running in the background, `mu4e` is the only place it fetches and indexes the e-mails. 

Hopefully this is not related to `mu4e` and instead something in my configuration, but I've changed som much stuff in order to overcome this issue, but the problem remains. 

**To Reproduce**
1. Check for unread messages
2. Open a message -> Either it already fails or.. go to step 3.
3. Mark to archive or delete mail
4. Continue working
5. Close Mu4e
6. Go back to the unread email, if the deleted e-mail is still there, the error will occur. 

**Environment**
I am using `mu4e` version `1.6.4` on Doom Emacs. Here is my configuration:

```elisp
(after! mu4e
  :defer t
  :config
  (setq mu4e-hide-index-messages nil
        mu4e-update-interval (* 5 60)
        mu4e-org-contacts-file "~/workspace/org/contacts.org"
        mu4e-change-filenames-when-moving t
        mu4e-compose-dont-reply-to-self t
        mu4e-get-mail-command "mbsync -a"
        mu4e-index-cleanup t
        mu4e-index-lazy-check nil
        ;; don't need to run cleanup after indexing for gmail
        mu4e-index-cleanup nil
        ;; because gmail uses labels as folders we can use lazy check since
        ;; messages don't really "move"
        mu4e-index-lazy-check t
        +mu4e-gmail-accounts '(("REDACTED" . "personal")
                               ("REDACTED" . "work"))
        mu4e-maildir-shortcuts
        '((:maildir "/personal/archive" :key ?a)
          (:maildir "/personal/inbox"   :key ?i)
          (:maildir "/personal/work"    :key ?w)
          (:maildir "/personal/sent"    :key ?s)))

  (defun benmezger/mu4e-mode-hook ()
    (when (featurep! :completion company)
      (message "Disabling company-mode while in mu4e...")
      (company-mode -1)))
  (add-hook 'mu4e-compose-mode-hook 'benmezger/mu4e-mode-hook)

  (add-to-list 'mu4e-headers-actions
               '("org-contact-add" . mu4e-action-add-org-contact) t)
  (add-to-list 'mu4e-view-actions
               '("org-contact-add" . mu4e-action-add-org-contact) t)

  (setq sendmail-program "/usr/local/bin/msmtp"
        send-mail-function 'smtpmail-send-it
        message-sendmail-f-is-evil t
        message-sendmail-extra-arguments '("--read-envelope-from")
        message-send-mail-function 'message-send-mail-with-sendmail)
  
  (set-email-account! "personal"
                      '((mu4e-sent-folder       . "/personal/sent")
                        (mu4e-drafts-folder     . "/personal/drafts")
                        (mu4e-trash-folder      . "/personal/trash")
                        (mu4e-refile-folder     . "/personal/archives")
                        (user-mail-address      . "REDACTED")
                        (smtpmail-smtp-user     . "REDACTED)
                        (smtpmail-smtp-server   . "smtp.gmail.com")
                        (smtpmail-smtp-service  . 587)
                        (mu4e-compose-signature . (with-temp-buffer
                                                    (insert-file-contents "~/.config/neomutt/signature.personal")
                                                    (buffer-string)))))
  (set-email-account! "work"
                      '((mu4e-sent-folder       . "/work/sent")
                        (mu4e-drafts-folder     . "/work/drafts")
                        (mu4e-trash-folder      . "/work/trash")
                        (mu4e-refile-folder     . "/work/archives")
                        (smtpmail-smtp-user     . "REDACTED")
                        (user-mail-address      . "REDACTED")
                        (smtpmail-smtp-server   . "smtp.gmail.com")
                        (smtpmail-smtp-service  . 587)
                        (mu4e-compose-signature . "---\nBen Mezger")))

  (add-to-list 'mu4e-bookmarks
               '( :name  "Notes"
                  :query "maildir:/personal/notes from:REDACTED"
                  :key   ?b) t)

  (add-to-list 'mu4e-bookmarks
               '( :name  "University"
                  :query "maildir:/personal/archives AND univali OR UNIVALI OR from:univali"
                  :key   ?x) t)

  (add-to-list 'mu4e-bookmarks
               '( :name  "UNIVALI"
                  :query "from:univali"
                  :key   ?h) t)

  (add-to-list 'mu4e-bookmarks
               '( :name  "Sent"
                  :query "maildir:/personal/sent"
                  :key   ?s) t)

  (add-to-list 'mu4e-bookmarks
               '( :name  "Drafts"
                  :query "maildir:/personal/drafts"
                  :key   ?d) t)

  (add-to-list 'mu4e-bookmarks
               '( :name  "Github"
                  :query "from:github"
                  :key   ?g) t)

  (add-to-list 'mu4e-bookmarks
               '( :name  "Me to me"
                  :query "from:REDACTED AND to:REDACTED"
                  :key   ?y) t)

  (add-to-list 'mu4e-bookmarks
               '( :name "Messages with pdfs"
                  :query "mime:application/pdf"
                  :key ?a) t))
```

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by theophilusx** [comment]
"Ben Mezger (seds)" ***@***.***> writes:

>         ;; don't need to run cleanup after indexing for gmail
>         mu4e-index-cleanup nil
>         ;; because gmail uses labels as folders we can use lazy check since
>         ;; messages don't really "move"
>         mu4e-index-lazy-check t

I don't think your logic is correct here. How gmail works or uses tags
is largely irrelevant to what mu is doing. In fact, mu has no knowledge
about gmail at all - it only knows about a set of maildirs on your local
file system. If you make changes on that file system - like deleting,
moving, marking etc, it needs to know about it and therefore needs to
update mu's index. Also, mu4e-index-lazy-check should only be enabled
when you know there is a performance problem with running index.

Remove both those settings and see if it fixes the issue.
