### ISSUE TITLE
[mu4e bug] meson/ninja not installing mu4e-contacts.el and mu4e-search.el

### ISSUE THREAD

**Issue by yp-warsaw** [djcb/mu#2119]
Hello,
**Describe the bug**
After compiling and installing mu from the git repo (at commit f92326d498566b34a4f8f1bf5232658e1398e923), Emacs complains about not finding mu4e-contacts.el and mu4e-search.el.  Copying manually thoses files in /usr/local/share/emacs/site-lisp/mu4e/ solves the problem.
Adding them in mu4e_srcs section of mu4e/meson.build do the trick too.

**To Reproduce**
./autogen.sh && ninja -C build && sudo ninja -C build install

**Environment**
OS: Fedora 34
Emacs : 28.5 (git + native-comp)
mu/mu4e: f92326d498566b34a4f8f1bf5232658e1398e923

**Checklist**
- [X ] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by cantao** [comment]
**Describe the bug**
Same as the OP, but copying the files results in `Symbol's function definition is void: mu4e~start` (probably some incompatibility with my Doom setup, but worth mentioning I guess).

**Environment**
OS: Archlinux
Emacs: 27.2, configured with Doom
mu/mu4e: [f92326d](https://github.com/djcb/mu/commit/f92326d498566b34a4f8f1bf5232658e1398e923)
