### ISSUE TITLE
[mu bug] unicode codepoints used for modeline

### ISSUE THREAD

**Issue by sje30** [djcb/mu#2121]
**Describe the bug**

Two of the fancy unicode characters in mu4e-headers.el
*mu4e-headers-threaded-label*
 and
*mu4e-headers-related-label* 
seem to use unicode characters that are not in a few of the fonts I tried within Emacs; are they popular codepoints?

**To Reproduce**

View mu4e-headers.el in Emacs (lines 232 and 236).  In Chrome, both unicode fancy chars eval as a small square box (see attached)
![2021-08-31-20-53-02](https://user-images.githubusercontent.com/1095067/131568071-d437a934-840b-42eb-bbde-0134d613cf7c.png)

**Environment**

Emacs 28.0.50 on arch linux.

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by Chris00** [comment]
For me they are rendered by the fonts `ftcrhb:-PfEd-Unifont Upper-normal-normal-normal-*-20-*-*-*-d-0-iso10646-1` and `ftcrhb:-Free-Symbola-normal-normal-semicondensed-*-20-*-*-*-*-0-iso10646-1`.  On Debian, you can install them with `apt install fonts-unifont fonts-symbola`.

**Comment by djcb** [comment]
In any case, not a bug.... you can pick a char that works for you, that's why there's a `defvar`.

**Comment by sje30** [comment]
thanks (and Chris, thanks, your suggestions solved the problem for me).
