### ISSUE TITLE
[misc] NEWS.org is not copied with the new build system and install instructions seem to be wrong

### ISSUE THREAD

**Issue by nils-schween** [djcb/mu#2122]
**Describe the issue**
I newly cloned the mu repository and executed the command `meson build && ninja -C build`.
Afterwards I used the command `sudo ninja -C build install`
The command updated the mu binary, all the mu4e files and also the man pages, but it do **not** copy the NEWS.org file. 

Furthermore if you take a look at the Section 2.2.5 in the mu4e manual, the command to install the current build of mu is `sudo ninja -C install` and **not** `build install`. Using this command produces the following error message:
```
ninja: Entering directory `install'
ninja: fatal: chdir to 'install' - No such file or directory
```
Probably, the install instructions need to be updated.
Thanks for looking into this,
Nils

**Comment by djcb** [comment]
Fixed.
