### ISSUE TITLE
"Current group does not support deleting of parts [mu4e bug]

### ISSUE THREAD

**Issue by dschwilk** [djcb/mu#2123]
**Describe the bug**
The new gnus message view allows right-click actions on mime parts such as "Save" or "Delete part" but deleting parts does not work and results in message: Current group does not support deleting of parts

**To Reproduce**
Attempt "Save and strip" or "Delete part" action on a mime part attachment

**Environment**
Kubuntu 20.10, Emacs 27.1, mu4e 1.6.3

Perhaps this is in fact a feature request for some way to delete or strip mime-parts. mu4e-detach was my past method and I would switch to the old message view to use that, but that seems to no longer work even with the old message view.

**Comment by djcb** [comment]
Yeah, that's not a bug... don't really want to get in the business of mutilating message. But I suppose if you really need this you can add an custom action (see the docs) for this, involving some 3rd party prog.

**Comment by dschwilk** [comment]
Yes, I tried that unsuccessfully and found no examples in a web of someone who was successful although I'm sure it is possible. Thanks.

**Comment by mankoff** [comment]
Deleting gnus attachment with this code works for me: https://emacs.stackexchange.com/questions/23812/remove-attachments-from-emails
