### ISSUE TITLE
[mu4e bug] mu4e-bookmarks french encoding issue ?

### ISSUE THREAD

**Issue by pseudomyne** [djcb/mu#2130]
Hi. Been « setquing » `mu4e-bookmarks `and found that `:query  "maildir:/[Gmail].Messages envoyés"` won’t work, neither `:query "maildir:/[Gmail].Testés"` nor `:query "maildir:/[Gmail].Te st" `, while `:query "maildir:/[Gmail].Brouillons"` works (as do many others).

Seems like there's an encoding issue here, with accents and spaces.
Thanks for your help.

**Comment by djcb** [comment]
Please use the bug template for any tickets, thanks.
