### ISSUE TITLE
[mu4e rfe] A hook to process new messages upon receiving them

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#2136]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a problem, but I think it would increase the power of `mu4e` significantly if I can run arbitrary code on receiving messages. 
For example, to move message to other folders or display alerts when certain messages are received or even add tasks to my org files.

**Describe the solution you'd like**
A hook that get called once for every new message that is received. Such a hook should allow getting data from the message including its header and text. Messages can then be moved/deleted... etc.

**Describe alternatives you've considered**
I am not sure how to implement this currently since `mu4e` does not seem to have a concept of new (or old) messages. 

`mu4e-alert` does a similar thing by adding a hook to `mu4e-index-updated-hook` which then gets a list of message in the Inbox by calling an `mu` process directly to get a list of messages.

**Additional context**
A similar feature was implemented in #2026 but was rejected because it forks calls to `mu`. I wonder if it is possible to implement such a feature without those additional forks. For example if the indexing command could output the newly processed messages to create a header-view out of them and then be able to process them.

**Comment by djcb** [comment]
This is not a job for `mu4e` I think, but (perhaps, one day) could be done by `mu` directly (using the guile scripting interface). But that's for the future, perhaps.

For now, I'd recommend using a tool like `procmail`.
