### ISSUE TITLE
mu server interface backward compatibility

### ISSUE THREAD

**Issue by derek-zhou** [djcb/mu#2148]
My project, [maildir_commander](https://github.com/derek-zhou/maildir_commander) is using `mu server` in the background. I've been following from 1.2 onward to latest git head. There were usually some incompatibility between versions, which is ok. However, I want to detect the API version and quit before going too far. I see I can do a `(ping)` command, and it will give me

```
(:version "1.7.0" ...
``` 

Can I use it to detect API version? Then the problem is 1.7 is actually compatible with 1.6, however 1.6 is not compatible with 1.4, or 1.4 to 1.2. Can I assume that for now that any 1.x where x is even  and 1.(x+1) must be compatible to each other, but to nothing else, either forward or backward?

**Comment by djcb** [comment]
Hmm, the mu <-> mu4e protocol is internal to mu, so it's not really meant for external use, and so I cannot give any guarantees for forward compatibility. 

For <=1.6, it's unlikely the protocol will ever change, but 1.7 is the development release so changes can be there at any point. `ping` should work though (or alternatively, something like `% mu --version | head | awk '/mu.*version/{print $NF}'`)

**Comment by derek-zhou** [comment]
the `mu server` interface is great; and I appreciate the gradual cleanups since 1.2. I've already got a webmail based on mu working and I use it everyday myself. It has a upper half [liv](https://github.com/derek-zhou/liv) for the web interface, and a lower half [maildir_commander](https://github.com/derek-zhou/maildir_commander) to interface with mu. 

Liv exposes major mu functionalities through the web interface, and also solves a major pain point that I had, which is displaying html mails. It also run side by side with mu4e so I can have the best of both worlds.

Can I propose in the future anytime should mu introduce incompatibility, be it the database ABI or `mu server` API, the second digit of the version must be incremented? The "stable" version are numbered in even number, such as 1.4, 1.6, and within the stable version, neither the database ABI or `mu server` API can break backwards incompatibility?  It seems to match your practices already, I just want the policy to be formalized.

On my side, I can use ping to detect version and quit if the version does not match expectation. Odd number will be disabled unless development flag is set.

**Comment by derek-zhou** [comment]
Thanks, that match up with my expectations. Again, thank you for the wonderful program.
