### ISSUE TITLE
Window #<window 0x2bfe9f0 on *mu4e-headers*> too small for splitting

### ISSUE THREAD

**Issue by mhofert** [djcb/mu#215]
1) In _mu4e-headers_, hit return while the point is on message A
2) hit 'R' to reply to A
3) put the point in _mu4e-headers_ again, now on message B. Hit return to display B
4) Instead of seeing B, I get the message in the title of this post (unfortunately not correctly displayed in this body)

**Comment by tiagosab** [comment]
This has been biting me ever since I started using mu4e. It is not just with compose-mode, but everytime the message-view is not visible. I am submitting a pull request which traps the error and open the message replacing message-headers.
