### ISSUE TITLE
[mu4e bug] mu4e-meta.el seems to be generated at the wrong place

### ISSUE THREAD

**Issue by thibautbenjamin** [djcb/mu#2151]
I tried to install mu to get mu4e running, but every time I launch emacs, I would get an error saying that `mu4e-meta` was missing. I reproduced the following steps both on the master and the 1.6.6 release branch.

After a bit of exploration, I found that indeed there was no file `mu4e-meta.el` in the folder `mu4e/`, albeit there is the file `mu4e-meta.el.in` which is supposed to be used to generate the aforementioned file. So I decided to keep looking, and I found a file named `mu4e-meta.el` inside the `build/mu4e/` directory, among a bunch of `*.elc`. Since this seemed kind of out of place, tried copying this file in the `mu4e/` directory instead, and emacs did load normally.

I don't know if it's something weird I am doing and I just misunderstood some parts on how this should be used, or if that's a bug with mu4e building.

If that matters, I am running Ubuntu 20.04 and GNU Emacs 28.0.50

**Comment by djcb** [comment]
What matters is the installation directory, but the above are source/build directories. How did you attempt to install mu?

In future reports, please follow the bug template.

**Comment by djcb** [comment]
`mu4e-meta.el[c]` should be installed in the same place as all the other mu4e files. From the `build/` in your recipe it seems you are *not* using the installed version (as per the the manual), but the uninstalled build artifacts.
