### ISSUE TITLE
[mu4e bug] new version is very slow after indexing

### ISSUE THREAD

**Issue by ArneBab** [djcb/mu#2155]
**Describe the bug**

Since the latest update (a few weeks ago) mu4e stops an "Searching…" for minutes after updating. 

**To Reproduce**
Use a mailbox with around 400k emails. 

- Hit U in mu4e-main to start the update. 
- Hit bt (for searching).

**Environment**

mu4e-mu-version is a variable defined in ‘mu4e-meta.el’.
Its value is "1.6.6"

mu is installed via guix:

mu            	1.6.6  
emacs               	27.2

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
In any case, it seems this is a dup of #2089, so please add further comments/analysis there, thanks!
