### ISSUE TITLE
missing scripts

### ISSUE THREAD

**Issue by permezel** [djcb/mu#2158]
**Describe the bug**
Per the `man mu-scripts` document, `mu` ships with a number of scripts.  In my case, that number appears to be zero, which would be fine, except for the error messages complaining of that fact, and the vague hollow feeling of being denied something...

**To Reproduce**

```
z8% find /usr 2>/dev/null | grep /mu/
z8% mu script
error: failed to open '/usr/share/mu/scripts/': No such file or directory
z8% ls ~/.mu/scripts
test
z8% mu script -v test
error: failed to open '/usr/share/mu/scripts/': No such file or directory
z8% mu test
error: failed to open '/usr/share/mu/scripts/': No such file or directory
```
**Environment**
```
z8% uname -a
Linux z8.zepherin.com 5.13.16-200.fc34.x86_64 #1 SMP Mon Sep 13 12:39:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
z8% mu --version
mu (mail indexer/searcher) version 1.6.6
```

**Checklist**
- [ X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
I get: ```
 dnf info maildir-utils
[...]
Name         : maildir-utils
Version      : 1.4.15
Release      : 2.fc35
[...]
```
anyway, it shouldn't really matter for this.

Obviously BUGS applies to cases where the build instructions were followed.

It seems like a Fedora packaging issue; apparently they're packaging the main package _with_ guile support, but _without_ the scripts;  we rely on the users of respective distros to report bugs there.
