### ISSUE TITLE
[mu4e rfe] Ability to search through header fields

### ISSUE THREAD

**Issue by pmatos** [djcb/mu#2160]
ML related message: https://groups.google.com/g/mu-discuss/c/cstrHCTYRC4/m/7C17RLTcBAAJ

**Is your feature request related to a problem? Please describe.**
Gandi.net adds a header categorizing an email under the header field `X-Gnd-Status`. I would like to be able to search for the header value to create category bookmarks.

**Describe the solution you'd like**
I would like to be able to say for example `mu find header:X-Gnd-Status:LEGIT`. Although the syntax is not really important.

**Describe alternatives you've considered**
Another solution could be using tags, but that would require implementing #2136. This was suggested by @tsdh on the thread above.

**Comment by djcb** [comment]
This has been asked before, but those fields are not stored in the mu database and hence are not available for searching. There's no plan for changing that -- so closing this -- sorry!

**Comment by pmatos** [comment]
Thanks @djcb , guess I should hope for #2136 to work out. :)
