### ISSUE TITLE
mu find with dashes in subject fail

### ISSUE THREAD

**Issue by c3d** [djcb/mu#2167]
**Describe the bug**

On my system, `mu find` does not find anything in a subject if the query contains a dash sign (`-`). I could not find anything in `man mu-query` suggesting that the dash sign would have any special meaning.

The following shows some of the queries I just ran:

```
% mu --version
mu (mail indexer/searcher) version 1.7.3
[...]
% mu find "s:kata" | grep "kata-containers" | wc
   89290 1585726 13579143
% mu find "s:/kata.containers/" | wc
   93076 1659167 14116532
% mu find "s:/kata[-]containers/" | wc
   89290 1585726 13579143
% mu find kata-containers | wc
   42146  753417 6657244
% mu find "s:kata-containers" | wc
error: no matches for search expression
       0       0       0
```

The messages are found with a regexp like `kata.containers` or `kata[-]containers`, but they are not found with the straight `kata-containers` text.

**To Reproduce**

See the commands above.

**Environment**

Tested on macOS (BigSur 11.6.1) and Linux (Fedora 34). In both cases, `mu` had been built from source.

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by lockywolf** [comment]
I tried regexps, but still failed to find anything with dashes.

This is a critical bug for me, because, like... a quarter of search queries I am doing are for dashed constructions. In particular:
```
Signed-off-by: Random J Developer <test@example.com>
```

Is there _any_ way I can work around this bug now?

**Comment by djcb** [comment]
I'd just search without the dashes.

**Comment by stsquad** [comment]
I use the ADJ keyword to match stuff close by:

```
              (:name "Mail addressed to me with git tags"
               :query "recip:/alex.bennee/ AND \( \(reviewed ADJ by\) OR \(signed ADJ off ADJ by\) \)"
               :hide-unread t
               :key ?g)
```

**Comment by djcb** [comment]
There's no `ADJ` keyword though (`mu` doesn't use Xapian's query parser). You can just leave them out.

**Comment by djcb** [comment]
Note, this case works with the new query parser (mu 1.11.20 and a bit before):
```
$ mu find subject:kata-containers
```
works just fine. It does _not_ work with the same word in the body-text though, since we only have the indexed form there.
