### ISSUE TITLE
[mu bug] Build fails on Mac

### ISSUE THREAD

**Issue by danielfleischer** [djcb/mu#2170]
Based on master 2c432013d1e5e5f293cd0a9714787598aaa3628e, building fails with the error

 ```error: invalid argument '-std=gnu11' not allowed with 'C++'```

I had this error for quite some time, I thought that 88f5f92b7221b10a879b97691c60ddf609be00d3 fixed that. 

**To Reproduce**
Pull master, run `./autogen.sh` and then `ninja -C build`. 

**Environment**
gcc 11.2, Mac 11.6.

**Comment by danielfleischer** [comment]
Thanks, it compiles and installs correctly. 

Sorry, I didn't think about using that line from the github testing workflow. 

Is this a mac specific issue? is it general and guile should be disabled from now on? 
Maybe there should be an INSTALL file?

**Comment by djcb** [comment]
I think the guile codegen injects a compiler flag specific for a c-compiler, but the code is actually c++, and while some/most(?) only issue a warning. apparently on Mac at least clang errors out.

Best(tm) would be some upstream fix, but perhaps we can massage the flags locally. Or make the -D automatic based on a configure-time check.

**Comment by djcb** [comment]
Since this is really an upstream issue, closing this; but adding an entry to NEWS.org to warn users.
