### ISSUE TITLE
Error when changing contexts

### ISSUE THREAD

**Issue by CGenie** [djcb/mu#2171]
**Describe the bug**

I have multiple mailboxes. Whenever I change contexts, the emails don't get updated and when I try to jump to inbox, I'm getting emails from the previous mailbox and an error message
```
[mu4e] Tip: `user-mail-address' ('...') is not part of mu's addresses; add it with 'mu init
                        --my-address='
```

From what I can tell this was always the case for me since starting with mu4e. The usual way is to quit mu4e then start it again in emacs.

**To Reproduce**

I'm using vanilla emacs. My mu4e config looks like this:
```
    (require 'mu4e)
  
    (setq mail-user-agent 'mu4e-user-agent)
    (setq mu4e-change-filenames-when-moving t)
    (setq mu4e-compose-signature <something>)
    (setq mu4e-attachment-dir "~/Downloads")
    (setq mu4e-contexts
	  `(,(make-mu4e-context
	      :name "<name1>"
	      :match-func (lambda (msg)
			    (when msg
			      (mu4e-message-contact-field-matches
			       msg :to "<email1>)))
	      :enter-func '()
	      :leave-func (lambda () (mu4e-clear-caches))
	      :vars '((mu4e-mu-home . "~/.mu/<name1>")
		      (user-mail-address . "<email1>")))
  
	    ,(make-mu4e-context
	      :name "<name2>"
	      :match-func (lambda (msg)
			    (when msg
			      (or (mu4e-message-contact-field-matches
				   msg :to "<email2>")
				  (mu4e-message-contact-field-matches
				   msg :to "<email2-alt>"))))
	      :enter-func '()
	      :leave-func (lambda () (mu4e-clear-caches))
	      :vars '((mu4e-mu-home . "~/.mu/<name2>")
		      (user-mail-address . "<email2>")))
  
  )))
  
    ;; make life easier
    (setq mu4e-maildir-shortcuts
	  '(("/inbox" . ?i)))
    ;; refresh index every 2 minutes
    (setq mu4e-update-interval 120)
  
    ;; sending email
    (setq mu4e-compose-dont-reply-to-self t)
    (setq message-send-mail-function 'message-send-mail-with-sendmail)
    (setq sendmail-program "/usr/bin/msmtp")
    (setq message-sendmail-extra-arguments '("--read-envelope-from"))
    (setq message-sendmail-f-is-evil t)
```

Steps:
- fire up `mu4e` in emacs
- initially I'm asked about the context I want to use, say I use `name1`
- I can go to inbox and view messages
- I press `;` to switch contexts
- I choose `name2`
- mail count isn't refreshed and when I go to inbox I get:
  ```
  [mu4e] Tip: `user-mail-address' ('...') is not part of mu's addresses; add it with 'mu init
                        --my-address='
  ```
- I quit `mu4e` (with `q` key)
- I start `mu4e` again (I'm not asked about context as it was done during first run)
- My context is now properly at `name2` and I can view the email

**Environment**

I'm using Emacs 27.2 and mu 1.6.9 (on ArchLinux).

**Comment by djcb** [comment]
Your report is very low on detail, and I really can't do anything with this.We'd need recipe starting with with `emacs -q` and the exact steps of what you're trying to do.

Why didn't you use the mu4e bug template?

**Comment by CGenie** [comment]
Sorry, I updated the description now, is this ok?

**Comment by djcb** [comment]
It's not an error message, it's just a tip: add _all_ your email addresses (from all contexts) when initializing mu (`mu init`), and the tip won't appear again. 

You cannot change `mu4e-mu-home` in a context or while running mu,  it requires a restart, this is the expected behavior. This is mentioned in the Context part of the manual, and I have now added an extra note to the docstring as well.
