### ISSUE TITLE
[mu4e bug] Header line disappears form *mu4e-headers* and shows up in *Article* buffer

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#2172]
**Describe the bug**

I have a split frame where the `*mu4e-headers*` is on the left and the `*Article*` buffer on the right.  I reply to the current message in the `*Article*` buffer.  As soon as I send it off and the compose buffer is killed, the `*Article*` buffer now **contains the header line** of the current message which is removed from the `*mu4e-headers*` buffer.

See this screenshot:
![Screenshot-2021-10-30_230342](https://user-images.githubusercontent.com/103854/139558421-7578c5bc-0ea0-483b-a7df-fe0e0a2abe74.png)

In the article buffer on the right, there's the line
```
  15:42:42   RS     EmacsDev   Daniel Martín        \- Re: Merging release branch
```
which belongs to the `*mu4e-headers*`.  It used to be there but moved to the article buffer after sending off my reply.

I suspect when sending off a reply, mu4e wants to replace the header line of the replied-to message with a new line where the `R` flag has been inserted.  It removes the line from the correct buffer but inserts it again into the wrong buffer.

**To Reproduce**

This happens for every reply I make.  I'm not sure, but if mu4e would make any assumptions about where the headers and article buffers' windows are located relative to each other, then probably this config might be the trigger:

```elisp
      (defun th/mu4e-split-view ()
        (let* ((headers (mu4e-get-headers-buffer))
               (headers-win (and headers (get-buffer-window headers)))
               (view (mu4e-get-view-buffer))
               (view-win (and view (get-buffer-window view))))
          (cond
           (view-win view-win)
           ((one-window-p) (split-window-sensibly))
           ;; Use the tallest window.
           (t (car (sort (delq headers-win (window-list))
                         (lambda (a b)
                           (> (window-height a) (window-height b)))))))))
      (setq mu4e-split-view #'th/mu4e-split-view)
```

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

- OS: Arch Linux
- GNU Emacs 29.0.50
- Mu/mu4e: current master branch (892b9ce1fa1cc55bac69e9fa3c46fb7f9cacbe7a)

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
The way we fill the headers buffer changed a bit (much faster now). but this now requires some explicit `save-excursion` for updating the message view.

**Comment by tsdh** [comment]
@djcb I can confirm that it works fine again.  Thanks!

**Comment by gyps** [comment]
I have the same problems now (and don't know what changed on my system, maybe the last update caused this). What do I need to do to make it work again? Reinstall mu4e from github?

**Comment by tsdh** [comment]
@gyps What version of mu/mu4e are you using?  Dirk fixed it on master (which is version 1.7).  Maybe the fix (or a similar fix) also needs to be in 1.6?

**Comment by gyps** [comment]
I use 1.7.4. Is the git repo the right place to go then?

**Comment by gyps** [comment]
Just reinstalled the git version and not it works fine again.
