### ISSUE TITLE
[mu4e rfe] allow users to download inline images/attachments

### ISSUE THREAD

**Issue by plantarum** [djcb/mu#2173]
**Is your feature request related to a problem? Please describe.**
When I receive an email with attachments, I can select some or all of those attachments to be saved. However, if there is an inline image, there is no mechanism for saving that image.

**Describe the solution you'd like**
Either include the inline image in the list of 'attachments' that I can save, or alternatively provide some mechanism for saving the inline image as a stand-alone image file.

**Describe alternatives you've considered**
If I open the email in my webmail client (Fastmail), I have the option to click a button to 'display inline image', which creates a link I can click to download the image. This is fine, it would be nice to have something similar in mu4e.

**Comment by djcb** [comment]
Can you attach such an email?

**Comment by Chris00** [comment]
@plantarum If, as I understand you problem, this happens with HTML email, a workaround is to view the email in the browser (`M-x mu4e-action-view-in-browser`) and save it from there.

P.S. You may want to add this action to those available with the `a` key.  I personally have:
```elisp
(setq mu4e-view-actions
      '(("sMark as spam" . mu4e-view-register-msg-as-spam)
        ("hMark as ham" . mu4e-view-register-msg-as-ham)
	("bViewInBrowser" . mu4e-action-view-in-browser)
	("capture message" . mu4e-action-capture-message)
	("tShow this thread" . mu4e-action-show-thread)))
(setq mu4e-headers-actions mu4e-view-actions)
```

**Comment by djcb** [comment]
I think this helps:
```
(setq gnus-inhibit-mime-unbuttonizing t)
```
This causes _all_ MIME-parts to be enumerated, so the "actions" apply to them.

**Comment by plantarum** [comment]
Thanks Dirk!

That option adds a toggle that I can use to switch from text/plain 
to text/html, but the inline image remains unavailable.

I've attached an email I created in MSOutlook with an inline 
image, hopefully that will make it into this thread intact.




- Tyler

**Comment by plantarum** [comment]
That didn't work. Silly question, but how do I save an email as a file from mu4e? Or just find the filename for the message on disk. I suppose I could upload the message directly from my maildir, if I knew the filename

**Comment by plantarum** [comment]
Here's the raw message, saved as a txt file

[mu4e-message.txt](https://github.com/djcb/mu/files/7588743/mu4e-message.txt)

**Comment by telmich** [comment]
I am running into this quite a lot of times since we switched to the gnus view, it wasn't an issue before. `e` does not list any attachments, however there are images in an s/mime part. There seems to be no `M-x mu4e-action-view-in-browser` anymore in mu 1.7.5 (compiled from git) - is there any other workaround to save the images at the moment?

**Comment by djcb** [comment]
@plantarum: ah, so that's a slightly different problem: the image is not a top-level MIME-part, but part the html. You can still save it by using the HTML view, selecting it and `M-x image-save`.

@telmich: view in browser is an _action_, by default accessible through `a v`.

**Comment by ugurbolat** [comment]
> (setq gnus-inhibit-mime-unbuttonizing t)
like Dirk suggested, after enabling gnus-mime, all mime links are visible and you can press 'o' (gnu-mime-save-part) to save the inline images

**Comment by djcb** [comment]
Guess there's not much more to do here; closing this one.

**Comment by jgoerzen** [comment]
Hi,

So I'm just coming to mu4e 1.8.14 from 1.4.15 due to the upgrade from Debian bullseye to bookworm.

There are some missing things still:

- There is no way to save all images like we used to have in the mu4e view.

- M-x image-save does not preserve the filename.  I see no way to even access the filenames of inline images.

gnus-inhibit-mime-unbuttoning did not resolve these issues for me.

Thanks!
