### ISSUE TITLE
[mu bug] Compilation fails because of missing xapian dependency for some targets

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#2174]
**Describe the bug**
Compiling a newly cloned version of mu fails

**To Reproduce**
This is difficult to reproduce. Basically I have two version of xapian installed, one old and one new.
The new one is the one returned by `pkg-config` and should be used. However, compiling fails because `mu` is using the old version for some targets (but not all).

The reason is that `meson.build` in some directories does not list  `xapian_dep` as a dependency for `mu-utils` along with `test-option`, `test-utils`, `test-command-parser`, `mu-scanner`, `text_sexp`, `test_flags`, `test-mu-maildir`, `test-mu-flags`, `test-mu-msg`, `test_cmd` (among others)  which all include `xapian.h` through `mu-utils.hh`.

Adding these dependencies resolves the issue.
I am happy to provide a patch or a pull request for these changes.

**Environment**
OS: CentOS 7
Emacs: 27.2

**Checklist**
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Right.. so the xapian include dir should be added to `link_mu_dep`, somehow if we could extract that from `xapian_dep`?

**Comment by haji-ali** [comment]
That could be enough. 

You can get the include directory using 

```
xapian_dep.get_pkgconfig_variable('includedir')
```

although I think adding `xapian_dep` as a dependency adds all of the cflags (which in the case of latest version of Xapian seems to be just the include directory )

**Comment by djcb** [comment]
So, something like:
```
modified   lib/meson.build
@@ -80,11 +80,12 @@ lib_mu=static_library(
   ],
   install: false)
 
+# some of the libme headers include xapian
+xapian_incs = xapian_dep.get_pkgconfig_variable('includedir')
 lib_mu_dep = declare_dependency(
   link_with: lib_mu,
-  include_directories: include_directories(['.', '..'])
-)
-
+  include_directories:
+    include_directories(['.', '..', xapian_incs]))

```
works for you?

**Comment by haji-ali** [comment]
Yes and no. The compilation no longer fails, but I still get warnings that the wrong `xapian.h` is included when compiling targets like `mu-scanner.cc.o`, `mu-indexer.cc.o` (which include xapian directly), `mu-logger.cc.o`, `mu-utils.cc.o`, `mu-command-parser.cc`, `tests_test-mu-cmd-cfind.cc`, `tests_gmime-test.c.o`, `test-sexp.cc.o`.

**Comment by haji-ali** [comment]
The following patch seems to fix all warnings/errors, not sure if the added dependencies makes sense

<details>

```diff
diff --git a/lib/index/meson.build b/lib/index/meson.build
index 01c90b1..1af282f 100644
--- a/lib/index/meson.build
+++ b/lib/index/meson.build
@@ -22,7 +22,7 @@ index_srcs=[
 ]

 lib_mu_index_inc_dep = declare_dependency(
-  include_directories: include_directories(['.', '..']))
+  include_directories: include_directories(['.', '..', xapian_incs]))
 lib_mu_index=static_library('mu-index', [index_srcs],
 			    dependencies: [
 			      config_h_dep,
diff --git a/lib/meson.build b/lib/meson.build
index bd661b4..ffc1f93 100644
--- a/lib/meson.build
+++ b/lib/meson.build
@@ -14,6 +14,7 @@
 ## along with this program; if not, write to the Free Software Foundation,
 ## Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

+xapian_incs = xapian_dep.get_pkgconfig_variable('includedir')

 subdir('utils')
 subdir('index')
@@ -82,7 +83,7 @@ lib_mu=static_library(

 lib_mu_dep = declare_dependency(
   link_with: lib_mu,
-  include_directories: include_directories(['.', '..'])
+  include_directories: include_directories(['.', '..', xapian_incs])
 )


diff --git a/lib/utils/meson.build b/lib/utils/meson.build
index eb40ff3..d5ca510 100644
--- a/lib/utils/meson.build
+++ b/lib/utils/meson.build
@@ -42,14 +42,15 @@ lib_mu_utils=static_library('mu-utils', [
 		 dependencies: [
 		   glib_dep,
 		   config_h_dep,
-		   readline_dep
+		   readline_dep,
+                  xapian_dep
 		 ],
 		 include_directories: include_directories(['.','..']),
 		 install: false)

 lib_mu_utils_dep = declare_dependency(
   link_with: lib_mu_utils,
-  include_directories: include_directories(['.', '..'])
+  include_directories: include_directories(['.', '..', xapian_incs])
 )


diff --git a/mu/meson.build b/mu/meson.build
index e7e3638..2d45129 100644
--- a/mu/meson.build
+++ b/mu/meson.build
@@ -62,7 +62,7 @@ test('test_cmd_cfind',
 		cpp_args: ['-DMU_PROGRAM="' + mu_binary + '"',
 			   '-DMU_TESTMAILDIR="'+ join_paths(testmaildir, 'testdir') + '"',
 			  ],
-		dependencies: [glib_dep, lib_test_mu_common_dep, config_h_dep]))
+		dependencies: [glib_dep, lib_test_mu_common_dep, config_h_dep, lib_mu_dep]))
 test('test_cmd_query',
      executable('test-cmd-query',
 		'tests/test-mu-query.cc',
```
</details>

The only warning left is an `implicit declaration of function ‘fileno’`, but that might because of my setup.

**Comment by djcb** [comment]
Okay, I've pushed a slightly different change, so we avoid having the xapian dependency (and linking) in so many places.

**Comment by djcb** [comment]
With that, are any warnings left (except for the 'fileno' warning)?

**Comment by haji-ali** [comment]
Still two warnings from `mu-indexer.cc` and `test-mu-cmd-cfind.cc`.

```
...
In file included from /usr/include/xapian.h:40:0,
                 from ../lib/index/mu-indexer.cc:34:
...
In file included from /usr/include/xapian.h:40:0,
                 from ../lib/mu-store.hh:31,
                 from ../mu/tests/test-mu-cmd-cfind.cc:31:
...
```

PS: the glib 2.58 requirement is too much for my old computer (I have glib 2.56.1 and cannot update... admin rule). 
I am able to test the compilation process but won't be able to update to the latest mu for a while.

**Comment by haji-ali** [comment]
PPS: The `fileno` warning seems to caused by the lack of defining the correct pre-processor keyword (` _POSIX_C_SOURCE >= 1` or `_XOPEN_SOURCE` or ` _POSIX_SOURCE`). See [here](https://helpmanual.io/man3/fileno/).

**Comment by djcb** [comment]
Okay, hopefully those warnings are now gone, too.

Re: glib 2.58... I guess if you really want, you could compile your own glib; but indeed it's a bit inconvenient :-(

**Comment by haji-ali** [comment]
Mmm. There's still one warning on `mu-indexer.cc.o`.

Also defining `_POSIX_C_SOURCE` without a number makes the compilation fails. One either has to 
```
#define _POSIX_C_SOURCE 1
```
or
```
#define _POSIX_SOURCE
```

**Comment by djcb** [comment]
Thanks -- updated.

**Comment by haji-ali** [comment]
Yep, all warnings gone.
