### ISSUE TITLE
[mu4e rfe] an alternative solution for `mail-header-separator`

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#2176]
**Is your feature request related to a problem? Please describe.**
When saving a message, my undo history gets polluted by the addition and removal of the text `--text follows this line--`.

**Describe the solution you'd like**
I want to suggest a different treatment for the `mail-header-separator` that I have been using for a while now.

In `mu4e~draft-insert-mail-header-separator`, I removed the code that sets `mail-header-separator` locally (this code leads to empty emails being sent when the global value of `mail-header-separator` is different from `--text follows this line--`).
I also added a `'display --text follows this line--` property to the separator so that the same text is still displayed (this also makes it impossible to change the text).

Finally, I set `mail-header-separator` to simply `\n`, so that this is what is saved on disk. This seems to work when sending emails because in `sendmail.el`, `(concat "^" (regexp-quote mail-header-separator) "$")` is always used to search for the mail separator (effectively searching for the first empty line just like `message.el` does when displaying messages).

This does break the address completion in mu4e, but it can be fixed by correctly searching for `mail-header-separator` in `mu4e~compose-complete-contact` like this

```
(search-forward-regexp (concat "^" (regexp-quote mail-header-separator) "$") nil t)
```

Using this, `mu4e~compose-before-save-hook-fn` and `mu4e~compose-after-save-hook-fn` can be modified to no longer remove and add the separator.

**Comment by djcb** [comment]
Hmm, wouldn't setting`mail-header-separator` to `\n` match _any_ end of line in the header?

Anyway, since we inherit the setting from `message.el`, I'd be reluctant to change the mechanism -- the chances are too high that something depends on it. Note that the `mail-header-separator` should never make it to the on-disk message file, since we remove it before saving.

If the only reason is because of the undo not working across saves, I think it's better to focus on just that. I've pushed a change to that effect to `master` - does it work for you?

**Comment by haji-ali** [comment]
> Hmm, wouldn't setting`mail-header-separator` to `\n` match _any_ end of line in the header?

No, because the text is matched after concatenating `^` at the beginning and a `$` at the end. So it matches the first empty line.

> If the only reason is because of the undo not working across saves, I think it's better to focus on just that. I've pushed a change to that effect to `master` - does it work for you?

Yep. Just tested it and it works.

Nevertheless, you might want to consider the other two "problems" that I included:
- Setting `mail-header-separator` locally in `mu4e~draft-insert-mail-header-separator` leads to empty emails being sent when the global value of mail-header-separator is different from `--text follows this line--`.
- `mu4e~compose-complete-contact` should match `mail-header-separator` similarly to how `message.el` does it, i.e., after concatenating `^` at the beginning and a `$` at the end.

These are not crucial problems since as long as header separator is `--text follows this line--` they won't cause any problems.
