### ISSUE TITLE
Build failure because unable to find xapian.h

### ISSUE THREAD

**Issue by c-wicklein** [djcb/mu#2178]
Greetings,

Upgrading from 1.4.14 to 1.6.9, I encountered build failures where certain translation units (beginning with `lib/index/mu-indexer.cc`) could not find `xapian.h`.  I fixed these problems for myself with the patch
[mu.patch.txt](https://github.com/djcb/mu/files/7500712/mu.patch.txt) which is hopefully now attached to this issue.

I'm building on CentOS 8 Stream and using Xapian 1.4.12 and GMime 3.2.3 built from source and installed at `/opt/xapian` and `/opt/gmime` respectively.  These are found by setting environment variables as follows before running `configure`.

```
GMIME_CFLAGS='-I/opt/gmime/include/gmime-3.0'
GMIME_LIBS='-L/opt/gmime/lib -lgmime-3.0 -lz -lidn2 -Wl,-rpath=/opt/gmime/lib'

XAPIAN_CFLAGS='-I/opt/xapian/include'
XAPIAN_LIBS='-L/opt/xapian/lib -lxapian -Wl,-rpath=/opt/xapian/lib'
```

 I just sprinkled e.g. `$(XAPIAN_CFLAGS)` into the involved `Makefile.am` where ever it was absent and `$(GMIME_CFLAGS)` was present until there were no more build failures.

At the time I started building Xapian in support of building mu, there was not an Xapian package for my system  or the available package was too old.  At this point, it looks like I could get `xapian-core-devel` 1.4.18 from the `Stream-PowerTools` repository, but after diagnosing the problem this much, I have a working build.

**Comment by djcb** [comment]
Thanks, merged the changes. In future cases, a PR would be appreciated.
