### ISSUE TITLE
Build fails on macOS Monterey on iMAC 24" with M1 chip

### ISSUE THREAD

**Issue by algon-ns** [djcb/mu#2179]
**Describe the bug**
Cannot compile "mu", missing apian.h loaded fresh from GitHub

**Environment**
In GNU Emacs 29.0.50 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559))
of 2021-11-09 built on macal.local
Repository revision: 5e393e2a97398ac4c6335d83d04b94ba8a74982a
Repository branch: master
Windowing system distributor 'Apple', version 10.3.2113
System Description:  macOS 12.0.1

Configured using:
'configure --with-native-compilation --with-xwidgets --with-mailutils'

Configured features:
ACL DBUS GLIB GNUTLS JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY
KQUEUE NS PDUMPER PNG RSVG THREADS TOOLKIT_SCROLL_BARS WEBP XIM XWIDGETS
ZLIB

Important settings:
  value of $LC_ALL: da_DK.UTF-8
  value of $LANG: da_DK.UTF-8
  locale-coding-system: utf-8

**Comment by djcb** [comment]
How did you try to build `mu`, and what was the exact error you got?

**Comment by algon-ns** [comment]
Just loaded it in by straight which compiles I wrote the backtrace and the compiler error
missing  include the apian.h file, which I have loaded and is on my system

mvh
Niels
 <applewebdata://64B0743A-4454-4F5C-BAA9-F8E07F078394>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45 4052 2789>+45 4052 ***@***.*** ***@***.***>
Ultra posse nemo obligatur.

**Comment by djcb** [comment]
I'd recommend filing an issue with this 'straight' then; we don't handle that here, can't help you with that.

**Comment by algon-ns** [comment]
I got the same error, when I tried to compile manual, you error is that Apple puts the “homebrew” files another place than for Intel CPU’s
I got the same error on compiling emacs (with another module).

So, this is your build on the APPLE SILICON.

MVH
Niels
 <applewebdata://278FB901-DAEE-463B-97A5-99196FF887A6>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45 4052 2789>+45 4052 ***@***.*** ***@***.***>
Ultra posse nemo obligatur.

**Comment by djcb** [comment]
Okay then  please include the precise commands you used to compile, and the compiler output until the error.

**Comment by christian-smith** [comment]
I have it building on MacOS (Apple Silicon) with straight

(use-package mu4e
    :straight ( :type git :host github :repo "djcb/mu"
    :pre-build (("./autogen.sh" "-Dguile=disabled") ("make"))
    :files (:defaults "mu4e/*.el")))

**Comment by djcb** [comment]
This just seems a setup problem on the Mac, and even if not, the requester didn't provide the needed/requested details. So closing this.

**Comment by algon-ns** [comment]
That’s fine, but it’s still not working, and the problen is that you’ve forgot to look for “xapian" for several of you modules, which require it.

I’ve postponed "mu" until it works.

Kind regards
Niels
 <applewebdata://C06447D3-F52D-40EB-AD95-42FFA54DCE9E>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45%204052%202789>+45 4052 2789 ***@***.*** ***@***.***>
Ultra posse nemo obligatur.

**Comment by djcb** [comment]
Without detailed reported (as requested multiple times) I cannot do anything.

**Comment by algon-ns** [comment]
Sorry, I know those unsatisfied customers, and you’re doing this voluntarily


I know that xipian is installed, and the include file is in /opt/homebrew/include/ 
However you compilation does not find apian.h as in this picture of my screen


mvh
Niels
 <applewebdata://A639B9C6-D998-4C32-ACA6-D3D481E48847>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45%204052%202789>+45 4052 2789 ***@***.*** ***@***.***>
Ultra posse nemo obligatur.

**Comment by Chris00** [comment]
There is no picture.  (You cannot just attach it to your mail, please use the Github interface.)

**Comment by algon-ns** [comment]
this is what my config in emacs says:

*** Email
#+begin_src emacs-lisp :tangle yes
  (straight-use-package 'mu4e)
  (require 'smptmail)
  ;; we installed this with homebrew
(setq mu4e-mu-binary (executable-find "mu"))

;; this is the directory we created before:
(setq mu4e-maildir "~/.maildir")

;; this command is called to sync imap servers:
(setq mu4e-get-mail-command (concat (executable-find "mbsync") " -a"))
;; how often to call it in seconds:
(setq mu4e-update-interval 300)

and this is the output with "emacs --debug-init":

<img width="2122" alt="Skærmbillede 2021-12-19 kl  08 15 34" src="https://user-images.githubusercontent.com/58687687/146667345-9d8e2ffc-a992-4b28-997d-fbbdcfc842ea.png">

**Comment by Chris00** [comment]
Did you run `./autogen.sh` first?  It should print a line like
```
Dependency xapian-core found: YES 1.4.18 (cached)
```

**Comment by algon-ns** [comment]
Yes I did:

Compiler for C++ supports arguments -Wswitch-default: YES (cached)
Checking for function "setsid" : YES (cached)
Checking for function "wordexp" : YES (cached)
Dependency glib-2.0 found: YES 2.70.1 (cached)
Dependency gobject-2.0 found: YES 2.70.1 (cached)
Dependency gio-2.0 found: YES 2.70.1 (cached)
Dependency gmime-3.0 found: YES 3.2.7 (cached)
Dependency xapian-core found: YES 1.4.18 (cached)
Dependency threads found: YES unknown (cached)
Dependency guile-3.0 found: YES 3.0.7 (cached)
Program awk found: YES (/usr/bin/awk)
Program emacs found: YES 29.0.50 (/usr/local/bin/emacs)
Program makeinfo found: YES (/usr/bin/makeinfo)
Configuring version.texi using configuration
Configuring mu4e-meta.el using configuration
Program cp found: YES (/bin/cp)
Configuring compile-scm using configuration
Program guile-snarf found: YES (/opt/homebrew/bin/guile-snarf)
Program pkg-config found: YES (/opt/homebrew/bin/pkg-config)
Configuring config.h using configuration
Build targets in project: 79

Found ninja-1.10.2 at /opt/homebrew/bin/ninja
*** Now run 'ninja -C build' to build mu
*** Or check the Makefile for some useful targets

However now I got problem with exclude guile, I’m trying, and will come back later

Kind regards
Niels

 <applewebdata://5715203E-F4A7-420B-8E71-E41F144F6587>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45%204052%202789>+45 4052 2789 ***@***.*** ***@***.***>
Ultra posse nemo obligatur.
