### ISSUE TITLE
helm interferes with address autocompletion

### ISSUE THREAD

**Issue by hsseung** [djcb/mu#2181]
**Describe the bug**
Autocompletion does not work for email addresses containing punctuation.
(or equivalently email addresses delimited by double quote marks)

**To Reproduce**
Such addresses are found by `mu cfind` but not by autocompletion in mu4e-compose-mode.

The problem is solved by turning off helm completion:
`(setq helm-mode-no-completion-in-region-in-modes '(mu4e-compose-mode))`

Presumably there is a bug somewhere? I saw some previous issues concerning helm.

**Environment**
mu4e 1.6.9 in Spacemacs, Arch Linux

**Comment by thierryvolpiatto** [comment]
hsseung ***@***.***> writes:

> Describe the bug
> Autocompletion does not work for email addresses containing punctuation.
> (or equivalently email addresses delimited by double quote marks)
>
> To Reproduce
> Such addresses are found by mu cfind but not by autocompletion in mu4e-compose-mode.

Can't reproduce, helm completion on such candidates is working, try with
a clean install of Helm (i.e. no Spacemacs).

> The problem is solved by turning off helm completion:
> (setq helm-mode-no-completion-in-region-in-modes '(mu4e-compose-mode))
>
> Presumably there is a bug somewhere? I saw some previous issues concerning helm.
>
> Environment
> mu4e 1.6.9 in Spacemacs, Arch Linux

Note that Helm is not responsible of what Spacemacs does with it.

-- 
Thierry

**Comment by hsseung** [comment]
I got rid of Spacemacs and still have the same problem.

First I tried installing Helm through MELPA.
Then I tried installing Helm from source.

In both cases, autocompletion only works properly when I exit helm-mode

My `init.el` has been stripped down to:
```
(require 'helm-config)
(helm-mode 1)
(require 'mu4e)
```

I'm using Emacs 27.2

**Comment by thierryvolpiatto** [comment]
hsseung ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> I got rid of Spacemacs and still have the same problem.
>
> First I tried installing Helm through MELPA.
> Then I tried installing Helm from source.
>
> In both cases, autocompletion only works properly when I exit helm-mode
>
> My init.el has been stripped down to:
>
> (require 'helm-config)
> (helm-mode 1)
> (require 'mu4e)

Can you show me some names of candidates that don't show up and the
pattern you are using so that I can reproduce.

Thanks.

> I'm using Emacs 27.2
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. *


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto ***@***.***> writes:

> hsseung ***@***.***> writes:
>
>> 1.  ( ) text/plain          (*) text/html           
>>
>> I got rid of Spacemacs and still have the same problem.
>>
>> First I tried installing Helm through MELPA.
>> Then I tried installing Helm from source.
>>
>> In both cases, autocompletion only works properly when I exit helm-mode
>>
>> My init.el has been stripped down to:
>>
>> (require 'helm-config)
>> (helm-mode 1)
>> (require 'mu4e)
>
> Can you show me some names of candidates that don't show up and the
> pattern you are using so that I can reproduce.
>
> Thanks.

I finally could reproduce, for some reasons some contacts have name
double quoted and helm doesn't match such candidates, probably mu4e
should cleanup contacts:

    (setq mu4e-contact-process-function
          (lambda (addr) ;; filter-out no-reply addresses
            (unless (string-match-p "no[t]?[-\\.]?repl\\(y\\|ies\\)" addr)
              (replace-regexp-in-string "[\"]"  "" addr))))

This fixes it for me.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Don't forget to restart emacs for this to work (I don't know how to refresh the contact list without restarting emacs).
@djcb perhaps we could use such a function as default ?

**Comment by hsseung** [comment]
Thanks, glad you could reproduce this! Indeed now autocompletion works with your fix.
But removing the double quotes may cause a problem when you actually send the mail.
When I tried the experiment, email to a name containing a period (John Q. Doe) worked fine.
But email to a name containing a comma (Doe, John) gave a warning, and then could not be delivered.

**Comment by thierryvolpiatto** [comment]
Another fix is to use another helm style for mu4e-compose-mode:

```elisp
;; This one uses default completion-styles
(add-to-list` 'helm-completion-styles-alist '(mu4e-compose-mode . emacs))
;; This one specify the completion-styles to use, here helm and fuzzy.
(add-to-list 'helm-completion-styles-alist '(mu4e-compose-mode . (emacs helm flex)))
```
Use one or the other, not both snippets above.

**Comment by thierryvolpiatto** [comment]
If this is working fine for you, we could add it by default in helm.

**Comment by hsseung** [comment]
Thanks so much...this works great! I didn't think to modify helm settings.
I've had problems off and on with autocompletion for years I think.
What a relief that it's working properly now.
And more generally, I really appreciate your fantastic work with helm.

**Comment by thierryvolpiatto** [comment]
hsseung ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Thanks so much...this works great! I didn't think to modify helm settings.
> I've had problems off and on with autocompletion for years I think.
> What a relief that it's working properly now.
> And more generally, I really appreciate your fantastic work with helm.

Glad it works now, thanks!

-- 
Thierry
