### ISSUE TITLE
RFE: Set up external links for HTML manual

### ISSUE THREAD

**Issue by josephmturner** [djcb/mu#2182]
There's a broken link in the online manual:
[6.5 Signing and encrypting](https://www.djcbsoftware.nl/code/mu/mu4e/Signing-and-encrypting.html#Signing-and-encrypting) links to [(emacs-mime)Composing)](https://www.djcbsoftware.nl/code/mu/emacs-mime/Composing.html#Composing), which is broken.

Apologies if this is not the correctly place to report this.

**Comment by djcb** [comment]
It's a link to an external manual, which sadly does not automaticallywork for the generated html docs. I suspect it could be fixed by setting up something like this:
  https://www.gnu.org/software/texinfo/manual/texinfo/html_node/HTML-Xref-Configuration.html

Volunteers welcome :)

**Comment by josephmturner** [comment]
There no longer appears to be a broken link [here](https://www.djcbsoftware.nl/code/mu/mu4e/Signing-and-encrypting.html#Signing-and-encrypting). Shall we close this issue?

Thank you for mu4e! Great daily driver. :)
