### ISSUE TITLE
mu can't updated and stuck in v1.6.6

### ISSUE THREAD

**Issue by AbdeltwabMF** [djcb/mu#2183]
**Bug Description**
I Can't update mu v1.6.6 to a higher version. building fails with the error
```
...
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... -std=c++17
configure: error: in `/home/amf/.cache/yay/mu/src/mu-1.6.10':
configure: error: C preprocessor "-std=c++17" fails sanity check

==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: mu
```

**What I expected to happen**
It gets updated to the latest version!

**To Reproduce**
```shell
yay -Syyuu aur/mu
```

**Environment**
Linux 5.15.2-artix1-1  
x86_64 GNU/Linux
gcc version 11.1.0 (GCC)

**Comment by djcb** [comment]
Did you try the mu build instructions as per the manual?  Otherwise, this may not be the right place to file your complaints....

**Comment by djcb** [comment]
In any case, the line should look something like:
```
checking how to run the C preprocessor... gcc -E
```
so, I bet you (or "yay") have some funny environment variable somewhere.

**Comment by AbdeltwabMF** [comment]
I did't try to build it my self. but I've used the AUR package and here is the compilation flags
```
autoreconf -i
./configure --prefix=/usr --disable-webkit --disable-gtk --enable-mu4e --enable-guile
```
I think this is the funny environment variable that I have
```shell
export CPP="-std=c++17"
```

Anyway, thank you I appreciate your support.

**Comment by djcb** [comment]
`export CPP="-std=c++17"` is not correct I think -- perhaps you meant `CPPFLAGS`? (or `CXXFLAGS`)? Which isn't really a good idea to set globally anyway.
