### ISSUE TITLE
Add mu4e-compose-in-new-window [mu4e rfe]

### ISSUE THREAD

**Issue by jsilve24** [djcb/mu#2184]
**Is your feature request related to a problem? Please describe.**
Switched to EXWM and now composing in new frames is less desirable. That said, I still want a new window open so I can see images inline in the original message that I am replying to -- or browse for other emails side by side as I compose a response. Seems like `mu4e-compose-in-new-window` as a new option is a bit of a no brainer. 

I have acctually implemented this feature and I am just asking if there is general interest such that I should put together a pull requrest or just keep it to myself. 

**Describe the solution you'd like**
Really exactly like `mu4e-compose-in-new-frame` but in `other-window`. 
Only two non-trivialities are (1) corner case where user specified both compose in new frame and compose in new window: I figure compose-in-new-frame should just take precedence and (2) I imagine some users will want different versions of a "new window" (e.g., some want to reuse an existing "other window" and other uses may want to create a new window). For the second one I figure can just add a new variable called `mu4e-compose-in-new-window-switch-function` which defaults to `switch-to-buffer-other-window` but allows users to customize. 

**Describe alternatives you've considered**
see above

**Additional context**
Happy to provide if there is interest.

**Comment by djcb** [comment]
Sure, patch is welcome; probably best to create a new `defcustom` like `mu4e-compose-target` that takes a symbol, either `nil` (default behavior), `frame`, `other-window`.

**Comment by sje30** [comment]
Does `C-x 4 m` work for you if you have the following setting

    (setq mail-user-agent 'mu4e-user-agent)

That should hook mu4e into the standard mechanism so that `C-x m`, `C-x 4 m` and `C-x 5 m` DTRT.

**Comment by djcb** [comment]
Yes, this is basically what #1454 asks for, so closing this one, one ticket is enough :-)
