### ISSUE TITLE
[mu bug] Mu displays wrong UTF8-characters

### ISSUE THREAD

**Issue by hertell** [djcb/mu#2185]
mu seems to handle wrong encoded utf8 characters. In my test-message that looks like this

```
From: René <rene@example.com>
Subject: test åäö
Body: test åäö
```

```
# mu view /root/Maildir/cur/1234567.xxxx
From: Ren\303\251 <rene@example.com>
To: foo@example.com
Subject: test \303\245\303\244\303\266
Date: Tue Nov 23 12:39:55 2021
test \303\245\303\244\303\266
```

And here is the same part of the physical file opened with an editor

```
To: foo@example.com
From: =?UTF-8?B?UmVuw6k=?= <rene@example.com>
Subject: =?UTF-8?B?dGVzdCDDpcOkw7Y=?=
Date: Tue, 23 Nov 2021 14:39:55 +0200

test åäö
```

This is tested with both the package from debian stable and by compiling from the latest 1.6.10 source. In both cases the result is the same.

**Comment by Chris00** [comment]
With the latest (commit 3001c783) of mu, I get:

![image](https://user-images.githubusercontent.com/1255665/143061777-efacc6e3-2c9e-456d-9041-dde902f15fab.png)

**Comment by hertell** [comment]
Fantastic! I'll will test that right away!

**Comment by djcb** [comment]
I think the problem depends on having a non-UTF8 LANG for the terminal, ie. try

```
LANG=en_DK mu view ....
```
vs
```
LANG=en_DK.utf8 mu view .... 
```

**Comment by hertell** [comment]
@djcb You are right. I'm runnig mu in a custom docker container, and forgot to take care of this part. Now it works as expected! Thanks!
