### ISSUE TITLE
[mu4e bug] mark as read use `!` or `(mu-headers-mark-all-unread-read)`, and exeucte (mu4e-mark-execute-all), still keep unread status.

### ISSUE THREAD

**Issue by zw963** [djcb/mu#2187]
**Describe the bug**
marked as read message still keep unread status.

**To Reproduce**
In fact, i have another confusing issues, maybe relative to this issue.

  1.  enter unread messages
  2.  pressing `/` and then filter by from:some_keyword
  3.  mark all message as read use `!` hotkey.
  4.  execute those mark with `x` hotkey.
  5.  pressing `\` back to unread view

**What to expected**
those marked as read messages status change to unread, should not appear again.

**Actually**
those message still appear there as unread, i often have to mark those message
one more time (even seveal times), to mark those message(or several of them) as read

This issue happen when do mark use ! or (mu-headers-mark-all-unread-read), and exeucte (mu4e-mark-execute-all), 
I curious if this cause by backend running offlineimap, but, it happen even never run offlineimap on the backend

thank you.

**Environment**
Arch linux, Emacs 28.0.60, mu 1.6.9, mu4e 1.6.9 (master)

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [ ] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by zw963** [comment]
https://user-images.githubusercontent.com/549126/143910594-4056d645-06eb-4392-b02c-667b047bfb66.mp4

I create a video for reproduce this on a  vanilla emacs.

**Comment by zw963** [comment]
It seem like mp4 can't play, right? i will upload some screenshot.

1. I mark those messages as read.

![image](https://user-images.githubusercontent.com/549126/144029572-33ba3efb-ce29-428b-8c56-341df26acb38.png)

2. then execute it.
![image](https://user-images.githubusercontent.com/549126/144029710-6af95dff-362d-4f4b-8538-6dc8a65a30f9.png)

3.  Pressing `q` to quit headers-view, and then `bu` enter unread message, filter again, i can still see those unread message there.

**Comment by zw963** [comment]
In fact, i even can reproduce on headers view, with following keybinding.

1. mark several mails with `!`
2. execute mark with `x`
3. refresh current view with `g`
4. those mail appear again.

**Comment by djcb** [comment]
Cannot reproduce.  What _could_ be the case is that you have multiple copies of the same message, and one of them gets marked-as-read. This can easily happen when e.g. using GMail. You can check by comparing the path names of the message, e.g. with
```
  M-: (mu4e-message-field-at-point :path)
```

**Comment by zw963** [comment]
> Cannot reproduce. What _could_ be the case is that you have multiple copies of the same message, and one of them gets marked-as-read. This can easily happen when e.g. using GMail. You can check by comparing the path names of the message, e.g. with
> 
> ```
>   M-: (mu4e-message-field-at-point :path)
> ```

Yes, i am have chance to test it path finally today.

"/home/zw963/Maildir/gmail/INBOX/new/1639136877_0.1967.lggram,U=151738,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,"
"/home/zw963/Maildir/gmail/[Gmail].All Mail/new/1639136872_0.1967.lggram,U=357955,FMD5=844bb96d088d057aa1b32ac1fbc67b56:2,"

Yes, they seem like have different path.

So, how should i solve it?

**Comment by djcb** [comment]
Ah, but that's expected behavior. It's unclear if changing flags for a specific message should imply changing it for _all_ messages with the same message-id. 

It could perhaps make sense for the read-flag, changing the read flag can be intrusive (i.e., moving message files from `new/` to `cur/`), so not really something to do automatically.

Instead, perhaps avoid having duplicate messages? You could put a `.noindex` in ".All Mail".
