### ISSUE TITLE
[mu4e rfe] Support HTML width parameter

### ISSUE THREAD

**Issue by moyamo** [djcb/mu#2188]
**Describe the bug**

*A clear and concise description of what the bug is*

When I upgraded mu4e I noticed that the lines in HTML emails were very long. This seems to be caused by the GNUS based mu4e-view to ignore the `shr-width` variable. Setting `shr-width`  to `80` tells `shr` to render HTML emails as if the "viewport" is only 80 columns wide (or something like that).

*what you expected to happen*

In the GNUS-based mu4e-view HTML emails should be wrapped at 80 columns when `shr-width` is set to `80` like in the just like in the old mu4e-view.

This is how HTML emails look in the old mu4e-view:

![old mu4e-view with (setq shr-width 80)](https://user-images.githubusercontent.com/5392783/144701086-d987c450-026f-4ce6-a3c5-4558cdb62b3d.png)

*what actually happened.*

The GNUS-based mu4e-view HTML emails are not wrapped even though `shr-width` is set to `80`

![gnus-based mu4e-view with (setq shr-width 80)](https://user-images.githubusercontent.com/5392783/144701142-6e74d987-ab73-4034-bf7e-0293386a81b6.png)

**To Reproduce**

Any HTML message with long paragraphs.

**Environment**

- **OS** Nix-on-Arch Linux Hybrid
- **Emacs** 27.2 from nixpkgs
- **mu** 1.6.10 from nixpkgs

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
  ![thing](https://user-images.githubusercontent.com/5392783/144701415-89fcbef8-5362-4523-ae83-27856e7ad24f.png) ran with `emacs -Q -l test.el`. With `test.el`:
  ``` elisp
  (setq shr-width 80)
  ; (setq mu4e-view-use-old t)
  (require 'mu4e)
  (setq
    mu4e-sent-folder   "/Sent"       ;; folder for sent messages
    mu4e-drafts-folder "/Drafts"     ;; unfinished messages
    mu4e-trash-folder  "/Trash"      ;; trashed messages
    mu4e-refile-folder "/misc")      ;; saved messages
  ```
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Would be nice to support that, indeed. But the value to track would probably be `gnus-html-frame-width`. 
Anyway, patch would be welcome.

**Comment by moyamo** [comment]
> the value to track would probably be gnus-html-frame-width.

So `gnus-html-frame-width` is in `gnus-html.el` which doesn't seem to be loaded in my emacs (`(featurep 'gnus-html)` returns `nil`). Adding `(require 'gnus-html) (setq gnus-html-frame-width 80)`  to my `init.el` didn't help. As far as I can tell `gnus-html-frame-width` is used for the `w3m` backend not the `shr` backend. Am I missing something?

>  Anyway, patch would be welcome.

I'm more than happy to try to fix this myself. I'm just a bit stumped as to what is going wrong. My understanding is the `mu4e-view` is using `gnus-art` which is rendering using `shr` which can be configured using the `shr-width` parameter. So there is some bug in `mu4e` that's causing `shr` to not respect `shr-width`.

I see you've changed this from a bug to a enhancement. Is there something wrong in my understanding (e.g. are we not using `shr` or `gnus-art` or something)?

(although it could be a bug in `gnus-art`, but I searched the emacs bug tracker and no one seems to have reported anything...)

**Comment by thierryvolpiatto** [comment]
Yaseen Mowzer ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
>     the value to track would probably be gnus-html-frame-width.
>    
> So gnus-html-frame-width is in gnus-html.el which doesn't seem to be loaded in my emacs ((featurep 'gnus-html) returns nil). Adding (require 'gnus-html) (setq gnus-html-frame-width 80) to
> my init.el didn't help. As far as I can tell gnus-html-frame-width is used for the w3m backend not the shr backend. Am I missing something?
>
>     Anyway, patch would be welcome.
>    
> I'm more than happy to try to fix this myself. I'm just a bit stumped
> as to what is going wrong. My understanding is the mu4e-view is using
> gnus-art which is rendering using shr which can be configured using
> the shr-width parameter. So there is some bug in mu4e that's causing
> shr to not respect shr-width.

Remember when fixing this that not everybody use shr (I don't for one).

-- 
Thierry

**Comment by djcb** [comment]
So, yeah, that was idea -- `gnus-html-frame-width` as the backend-independent value... but looking at the code it seems to be _only_ used for w3m. 

Anyway, when I check with the long-line message from github for this very issue, and switch to html-mode (`h`), it's rendered 80 cols (or whatever). Can you attach an example message that's not rendering correctly for you?

**Comment by moyamo** [comment]
I don't think it depends on the email. But here is the message you just sent: [email_from_maildir.txt](https://github.com/djcb/mu/files/7656022/email_from_maildir.txt); and this is how it renders for me
![rendering of email from maildir](https://user-images.githubusercontent.com/5392783/144750320-f55e4574-2c1a-4f13-adc1-50e325d641dd.png)


>  and switch to html-mode (h)

So interestingly when it's defaulting to html-mode for me and when I press <kbd>h</kbd>,   in `*Messages*`, I get:
> gnus-summary-select-article: This is a pseudo-article

I wonder if that's related.

**Comment by moyamo** [comment]
Okay, I don't think this is a bug in mu4e anymore. This seems to be an issue in emacs/gnus. This line https://github.com/emacs-mirror/emacs/commit/656caef3505e11b073d59b9c18d3fd21e199d77c#diff-c58d725eb12503fac78cea9c7b0d539db6483f6dc7e8d6c6d08c485d435db93fR1826 sets `shr-width` to `nil` if `shr-use-fonts` is `t` (`shr-use-fonts` is `t` by default https://github.com/emacs-mirror/emacs/commit/26d87ff86c4c64a8ca45bca1bbfd467b2c063a86).

@larsmagne Do you remember why you set `shr-width` to `nil` here?

**Comment by larsmagne** [comment]
Yaseen Mowzer ***@***.***> writes:

> @larsmagne Do you remember why you set shr-width to nil here?

Sorry -- this is a change from 2015?  I don't recall.

**Comment by Chris00** [comment]
Does it have to do with the fact that _proportional_ fonts are usually used with `shr`?

**Comment by moyamo** [comment]
I sent a patch to upstream Emacs. I'm going to close this issue, since it isn't a bug with `mu4e`.

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=52825
