### ISSUE TITLE
Package rfc2368 is deprecated

### ISSUE THREAD

**Issue by joostkremers** [djcb/mu#2190]
I compiled and installed the pretest for Emacs 28 recently and one of the issues that pops up is the following warning showing up in `*Messages*` when I open mu4e:

    Package rfc2368 is deprecated
    
The NEWS file has this to say about it:

> ** The rfc2368.el library is now obsolete.
> Use rfc6068.el instead.  The main difference is that
> `rfc2368-parse-mailto-url` and `rfc2368-unhexify-string` assumed that
> the strings were all-ASCII, while `rfc6068-parse-mailto-url` and
> `rfc6068-unhexify-string` parse UTF-8 strings.

Perhaps you're already aware of the issue, but I thought I'd mention it.

**Comment by djcb** [comment]
I can't reproduce... can you pin-point the call / `require` that triggers this?

**Comment by joostkremers** [comment]
Well, simply doing `(require 'rfc2368)` in a fresh Emacs 28 session (`emacs -Q`) will trigger the warning. As for mu4e, it's in `mu4e-compose.el`.

**Comment by djcb** [comment]
Yes, but `mu4e-compose.el` (or mu4e in general) doesn't require it (directly) so what package is doing that?

**Comment by joostkremers** [comment]
Oh, my bad. I'm running the `release/1.6` branch, where `mu4e-compose.el` still has `(require 'rfc2368)`. I see now it's been removed from `master`.

Sorry for the noise. 😕
