### ISSUE TITLE
[mu4e bug] mu4e complain about Found mu version nil with mu4e-mu-binary set correctly

### ISSUE THREAD

**Issue by tshu-w** [djcb/mu#2193]
**Describe the bug**
After I open emacs for a long time. I cannot open mu4e with error `mu4e-error: [mu4e] Found mu version nil, but mu4e needs version 1.6.10; please set mu4e-mu-binary accordingly`. I confirm my `mu4e-mu-binary` was set correctly and If I restart Emacs, everything works fine again. 

I tried to set `mu4e-debug` and `mu4e-mu-debug` to `t` or `toggle-debugg-on-error`, but cannot got more information. 

**To Reproduce**
Since it take a lot of time for this issue to happen, I cannot find a stable way to reproduce it.

**Environment**
macOS 12.1
GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.2.0, NS appkit-2113.20 Version 12.1 (Build 21C52)) of 2021-12-14
mu: stable 1.6.10

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Hmm, when this occurs, can you try to replicate "by hand", i.e. by evaluating
```
(shell-command-to-string (concat mu4e-mu-binary " --version"))
```
and see what you get?

**Comment by tshu-w** [comment]
@djcb Yes, I got 
```
"mu (mail indexer/searcher) version 1.6.10
Copyright (C) 2008-2021 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
"
```

**Comment by djcb** [comment]
The code that does the check is:
```
  ;; sanity-check 2
  (let ((version (let ((s (shell-command-to-string (concat mu4e-mu-binary " --version"))))
                   (and (string-match "version \\([.0-9]+\\)" s)
                        (match-string 1 s)))))
    (unless (string= version mu4e-mu-version)
      (mu4e-error
       (concat
        "Found mu version %s, but mu4e needs version %s; please set `mu4e-mu-binary' "
        "accordingly") version mu4e-mu-version)))
```

So it seems in your case, the `version` is `nil`, but it's unclear to me how that could happen

Can you try to evaluate this when you see the problem, and at that point also  include the output from `(shell-command-to-string (concat mu4e-mu-binary " --version"))` again?  

And how often does this happen? Any specific circumstances?

Thanks.

**Comment by tshu-w** [comment]
@djcb Sorry, this issue doesn't happen recently.

**Comment by tshu-w** [comment]
> And how often does this happen? Any specific circumstances?

Hi, I find this happen when I using tramp to edit remote file, which make `shell-command-to-string` try to use remote `mu`

**Comment by tshu-w** [comment]
I'm still using Homebrew version 1.6.10, so I can't test 1.7.x at the moment, but I have no problem modifying it locally, so I'll close this issue for now.

**Comment by tshu-w** [comment]
@djcb Hi, this issue appears in 1.10.0 again.

**Comment by djcb** [comment]
Hmmm, this seems like a tramp issue really, it poisons the well... anyway does the attached patch fix it for you?
[0001-mu4e-server-attempt-to-avoid-tramp-error.patch.txt](https://github.com/djcb/mu/files/11093495/0001-mu4e-server-attempt-to-avoid-tramp-error.patch.txt)

Thanks.

**Comment by tshu-w** [comment]
Hi, why not move `mu4e--version-check` to `let`:
```emacs-lisp
@@ -1,8 +1,8 @@
   (defun mu4e--server-start ()
     "Start the mu server process."
+    (mu4e--version-check)
     (let ((default-directory temporary-file-directory)) ;;ensure it's local.
       ;; kill old/stale servers, if any.
-      (mu4e--version-check)
       (mu4e--kill-stale)
       (let* ((process-connection-type nil) ;; use a pipe
              (args (mu4e--server-args)))
```
Here is the full version of `mu4e--server-start`
```emacs-lisp
  (defun mu4e--server-start ()
    "Start the mu server process."
    (let ((default-directory temporary-file-directory)) ;;ensure it's local.
      ;; kill old/stale servers, if any.
      (mu4e--version-check)
      (mu4e--kill-stale)
      (let* ((process-connection-type nil) ;; use a pipe
             (args (mu4e--server-args)))
        (setq mu4e--server-buf "")
        (mu4e-log 'misc "* invoking '%s' with parameters %s" mu4e-mu-binary
                  (mapconcat (lambda (arg) (format "'%s'" arg)) args " "))
        (setq mu4e--server-process (apply 'start-process
                                          mu4e--server-name mu4e--server-name
                                          mu4e-mu-binary args))
        ;; register a function for (:info ...) sexps
        (unless mu4e--server-process
          (mu4e-error "Failed to start the mu4e backend"))
        (set-process-query-on-exit-flag mu4e--server-process nil)
        (set-process-coding-system mu4e--server-process 'binary 'utf-8-unix)
        (set-process-filter mu4e--server-process 'mu4e--server-filter)
        (set-process-sentinel mu4e--server-process 'mu4e--server-sentinel))))
```

**Comment by djcb** [comment]
Okay, thanks for testing!
