### ISSUE TITLE
[misc] XAPIAN_CJK_NGRAM is deprecated

### ISSUE THREAD

**Issue by l2dy** [djcb/mu#2195]
**Note**: for questions, please use the mailing-list: https://groups.google.com/g/mu-discuss

**Describe the issue**
Environment variable `XAPIAN_CJK_NGRAM` is deprecated in Xapian 1.4.11, but still referenced in mu test code and mu4e docs https://www.djcbsoftware.nl/code/mu/mu4e/General.html#Does-mu4e-support-searching-for-CJK-_0028Chinese_002dJapanese_002dKorean_0029-characters_003f.

| Deprecated | Remove | Feature name                            | Upgrade suggestion and comments                                                                                                                     |
|------------|--------|-----------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------|
| 1.4.11     | 1.7.0  | Environment variable `XAPIAN_CJK_NGRAM` | Specify via the flags `Xapian::QueryParser::FLAG_CJK_NGRAM`, `Xapian::TermGenerator::FLAG_CJK_NGRAM` and `Xapian::MSet::SNIPPET_CJK_NGRAM` instead. |

(table from https://github.com/xapian/xapian/blob/v1.4.18/xapian-core/docs/deprecation.rst)

**Environment**
Xapian 1.4.18

**Comment by djcb** [comment]
1.11.20 (and a bit before) explicitly unset `XAPIAN_CJK_NGRAM`, and use `FLAG_CJK_NGRAM` / `FLAG_NGRAMS`; so closing this.
