### ISSUE TITLE
Git: tag 1.6.10 does not belong to any branch

### ISSUE THREAD

**Issue by cpbotha** [djcb/mu#2196]
When I go to https://github.com/djcb/mu/commit/77f10379cb42e3a41805efed8a15c7c2db46fb68 -- github warns me that the tag 1.6.10 does not belong to any branch on this repository. (It is currently listed on the releases page)

Indeed, 1.6.10 does not show up amongst the list of tags when I do `git tag`, and `git checkout tags/1.6.10` yields the error "error: pathspec 'tags/1.6.10' did not match any file(s) known to git".

1.6.9 and all previous 1.6 tags are on the release/1.6 branch, and all of the above commands work as expected.

**Comment by djcb** [comment]
Fixed, thanks.
