### ISSUE TITLE
[mu bug] Usage Regex queries for `from` field not supported 

### ISSUE THREAD

**Issue by thisch** [djcb/mu#2197]
**Describe the bug**

I've just tried calling 

`mu find 'From:*@mydomain.com'` and `mu` didn't find any matches even though there are mails that are sent from the `mydomain.com` domain.

**To Reproduce**

```
> mu find 'From:*@mydomain.com'                                                                                                                                                         
error: no matches for search expression
```

```
> mu find 'From:*@*.mydomain.com'                                                                                                                                                         
error: no matches for search expression
```

**Environment**

Fedora 34, mu 1.6.6

**Checklist**
- [ ] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by markk** [comment]
You must use:

`mu find 'from:/.*@mydomain.com/`

See man mu-query:

REGULAR EXPRESSIONS AND WILDCARDS

Wildcards  are  an  older mechanism for matching where a term with a rightmost * **(and only in that position)** matches any term that starts with the part before the * ; they are supported for backward  compatibility  and  mu  translates them to regular expressions internally:
              foo*
       is equivalent to
              /foo.*/

**Comment by thisch** [comment]
Thx a lot for the comment. This works for me. Thx and sry for the noise.
