### ISSUE TITLE
[misc] mu4e upgrade from 1.4.15 to 1.6.10 changed From/To header field behaviour

### ISSUE THREAD

**Issue by livnev** [djcb/mu#2199]
**Describe the issue**
After upgrading from 1.4.15 to 1.6.10, I noticed that the `:from-or-to` header, which used to display the From address _unless_ it was from me, in which case it displayed the To address (this is what makes the most sense when browsing sent emails, drafts, etc.). After the upgrade, it seems to always display the From address. I couldn't see anything in News.org that mentioned what changed. Is `mu4e-user-mail-address-list` deprecated? Do I need to re-`init` with `--my-address=`? Do any other configuration variables need to be changed? Incidentally I also noticed that Reply-all is now suggested even for emails where I am the only recipient, making me suspect that the my address configuration is wrong now.

**Environment**
mu 1.6.10

**Comment by djcb** [comment]
Yes, `mu init` is the only way to specify your own addresses, using one or more `--my-address`. The switch happened with 1.4 though.

**Comment by livnev** [comment]
@djcb got it. Not sure how I missed that when upgrading to 1.4, because I'm sure that on 1.4.15 I still get the right `From/To` header field behaviour (for example) even though I am positive that I never  passed `--my-address` to `mu index` and only have them in `mu4e-user-mail-address-list`. I can also confirm that on 1.4.15 `describe-variable` tells me that `mu4e-user-mail-address-list` is obsolete since 1.3.8, so how it was working is unclear to me...
