### ISSUE TITLE
[mu bug] inconsistent mu init behaviour for top maildir

### ISSUE THREAD

**Issue by paddy-hack** [djcb/mu#2200]
**Describe the bug**

Per `mu-init` manual page
```
ENVIRONMENT
       mu init uses MAILDIR to find the user's Maildir if it has not been  specified  explic‐
       itly with --maildir=<maildir>. If MAILDIR is not set, mu init uses ~/Maildir.
```
I expect `mu init` to behave the same for all three scenarios: 

- `~/Maildir` default,
-  `MAILDIR` environment variable set, or
-  `<maildir>` passed via option.

when the directory does not exist already.

Now one has to create `~/Maildir` or `$MAILDIR` in advance or use `--maildir=$MAILDIR` or `--maildir=~/Maildir` explicitly.  However, this is not particularly clear from the error message that is given
```
error: missing --maildir parameter and could not determine default
```
The defaults are documented, hence are determined.
```
error: missing --maildir option or default directory does not exist
```
would be clearer but I believe that there are additional checks on the directory (read/write access).

Note that using the `--maildir` option does *not* create the directory that has been passed as an argument.

**To Reproduce**

Make sure the `~/Maildir` and `$MAILDIR` directories do not exist.
``` sh
unset MAILDIR
mu init              # error: missing --maildir parameter and could not determine default
export MAILDIR=$HOME/some-silly-location
mu init              # error: missing --maildir parameter and could not determine default
mu init --maildir=$MAILDIR
```
The last command succeeds.  It does not create the directory specified.

**Environment**

- Devuan GNU+Linux (daedalus), think Debian GNU/Linux (bookworm) without `systemd`
- GNU Emacs 27.1
- mu (mail indexer/searcher) version 1.6.10

**Checklist**

- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Thanks, I've updated the manpage.
