### ISSUE TITLE
[mu4e bug]  Inconsistency between `mu find` and mu4e (mu4e~headers-search-execute)

### ISSUE THREAD

**Issue by thisch** [djcb/mu#2202]
**Describe the bug**

I'm a new mu4e user (thx for your work on this project, it's amazing!) and I
noticed that some messages, which are explicitly filtered out in the search
query are shown in mu4e-headers buffer, but are not output by `mu find`.

This is the query string, which I'm using

(string-join '(
"maildir:/INBOX"
"NOT from:gerrit@srv-vct-02.example.com"
"NOT from:jira.rnd@example.com"
"NOT from:jira.service@example.com"
"NOT from:mattermost@example.com"
"NOT from:quarantine@example.com"
) " AND ")

Some mails from from:gerrit@srv-vct-02.example.com are shown in my mu4e-headers buffer.

**To Reproduce**
Detailed steps to reproduce the behavior. If this is about a specific (kind of) message, **always**
attach an (anonymized as need) example message.

By using the following commands I can easily "reproduce" the issue:

```elisp
  (plist-get (nth 1 mu4e-bookmarks) :name)
  (plist-get (nth 1 mu4e-bookmarks) :query)
  (shell-command-to-string (concat "mu find --reverse -n 20 '" (plist-get (nth 1 mu4e-bookmarks) :query) "'"))
  (mu4e~headers-search-execute (plist-get (nth 1 mu4e-bookmarks) :query) t) ;; I see all the mails from the output of shell-command-to-string but I also see some filtered mails from :gerrit@srv-vct-02.example.com.
```

I tried reordering the query a bit and somtimes I see the mails from gerrit and sometimes I don't see them. I haven't yet found a pattern.

```elisp

(mu4e~headers-search-execute "maildir:/INBOX AND NOT from:gerrit@srv-vct-02.example.com AND NOT from:jira.rnd@example.com" t)  ;; no gerrit mails
(mu4e~headers-search-execute "maildir:/INBOX AND NOT from:gerrit@srv-vct-02.example.com AND NOT from:jira.rnd@example.com AND NOT from:jira.service@example.com" t) ;; no gerrit mails
(mu4e~headers-search-execute "maildir:/INBOX AND NOT from:gerrit@srv-vct-02.example.com AND NOT from:jira.rnd@example.com AND NOT from:jira.service@example.com AND NOT from:mattermost@example.com" t) ;; gerrit mails
(mu4e~headers-search-execute "maildir:/INBOX AND NOT from:gerrit@srv-vct-02.example.com AND NOT from:jira.rnd@example.com AND NOT from:jira.service@example.com AND NOT from:quarantine@example.com" t) ;; no gerrit mail
(mu4e~headers-search-execute "maildir:/INBOX AND NOT from:gerrit@srv-vct-02.example.com AND NOT from:mattermost@example.com AND NOT from:quarantine@example.com AND NOT from:jira.rnd@example.com" t) ;; no gerrit mails
(mu4e~headers-search-execute "maildir:/INBOX AND NOT from:gerrit@srv-vct-02.example.com AND NOT from:mattermost@example.com AND NOT from:quarantine@example.com AND NOT from:jira.rnd@example.com AND NOT from:jira.service@example.com" t) ;; gerrit mails
```

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

fedora 36, emacs 28,  mu4e 1.6.6

**Checklist**
- [ ] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [ ] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [ ] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
This likely just due to `mu4e-headers-include-related` (on by default in `mu4e`), and `--include-related` with `mu`.

**Comment by thisch** [comment]
Thx @djcb, you're right! Setting `mur4-headers-include-related` to `nil` removes the explicitly filtered mails from my query. I think it is not very intuitive that this mu4e variable is considered if the threaded view is disabled.
