### ISSUE TITLE
Can't send email on macOS

### ISSUE THREAD

**Issue by fuzunspm** [djcb/mu#2205]
**Describe the bug**
I can't send mail on macOS. Same/Similar config and accounts are working fine on other systems. Receiving, searching, indexing everything is working except composing message. 

**Environment**
macOS 12.2, emacs 27.2, mu4e 1.6.10

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Error Messages**

```
Sending...
Sending via mail...
apply: Wrong type argument: stringp, nil
```

**Debug Log**

```
call-process-region(1 414 nil "/var/folders/t7/cn7q24tn1k59hdqbqwc3gxlc0000gn/T/emacsIZGNrj" #<buffer  sendmail errors> nil "-oi" "--read-envelope-from" "-t")
  apply(call-process-region (1 414 nil nil #<buffer  sendmail errors> nil "-oi" "--read-envelope-from" "-t"))
  message-send-mail-with-sendmail()
  message-multi-smtp-send-mail()
  message--send-mail-maybe-partially()
  message-send-mail(nil)
  message-send-via-mail(nil)
  message-send(nil)
  message-send-and-exit(nil)
  funcall-interactively(message-send-and-exit nil)
  call-interactively(message-send-and-exit nil nil)
  command-execute(message-send-and-exit)
```

**Comment by djcb** [comment]
That seems like some MacOS smtp setup problem, not much `mu4e` can do about that.

I'd recommend checking that `#<buffer  sendmail errors>` and reading e.g. https://www.gnu.org/software/emacs/manual/html_mono/smtpmail.html

**Comment by fuzunspm** [comment]
you were right, it was a permission error for msmtp config file
