### ISSUE TITLE
[mu bug] unbalanced locks in the current HEAD

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#2207]
**Describe the bug**

```
Feb 06 18:40:50 zen mu[2351934]: ran query 'maildir:"/Inbox"'; related: yes; threads: yes; max-size: 500: finished after 104.5 ms
Feb 06 18:53:42 zen mu[2354457]: logging initialized; debug: yes, stdout/stderr: no
Feb 06 18:53:42 zen mu[2354457]: server caught exception: failed to open store @ /home/alex/.cache/mu/xapian: Unable to get write lock on /home/alex/.cache/mu/xapian: already locked
Feb 06 19:07:30 zen mu[2357166]: logging initialized; debug: yes, stdout/stderr: no
Feb 06 19:07:30 zen mu[2357166]: server caught exception: failed to open store @ /home/alex/.cache/mu/xapian: Unable to get write lock on /home/alex/.cache/mu/xapian: already locked
Feb 06 19:20:46 zen mu[2359804]: logging initialized; debug: yes, stdout/stderr: no
Feb 06 19:20:46 zen mu[2359804]: server caught exception: failed to open store @ /home/alex/.cache/mu/xapian: Unable to get write lock on /home/alex/.cache/mu/xapian: already locked
Feb 06 19:34:07 zen mu[2362897]: logging initialized; debug: yes, stdout/stderr: no
Feb 06 19:34:07 zen mu[2362897]: server caught exception: failed to open store @ /home/alex/.cache/mu/xapian: Unable to get write lock on /home/alex/.cache/mu/xapian: already locked
```

After a while running I start seeing these in the logs and searches stop working.

**To Reproduce**

Detailed steps to reproduce the behavior. If this is about a specific (kind of) message, **always** attach an (anonymized as need) example message.

**Environment**

mu: HEAD (3f163e65e0c91afec01c09878432bd9e11925c0f)
Emacs: 28-branch
OS: Linux Debian Buster

**Checklist**
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Hmm... so it appears you are starting mu while still an older instance is holding on to the database. So when you see this error, can you still see a `mu` process on your system? If so, can you attach `gdb` (with `gdb -p $(pidof mu)`) and get a backtrace (`thread apply all bt`)?

**Comment by stsquad** [comment]
I think it's all one instance (e.g. there where no mu processes running before I started Emacs). I shall try and capture a BT once it happens again.

**Comment by stsquad** [comment]
I'm closing this as I haven't seen the problem re-occur. I suspect I was running in an in-between state (8493e864 to 6c482804) when it occurred. Will re-open if it happens again.
