### ISSUE TITLE
[mu4e bug] Lines having 238 or more character are reformated when sending a message

### ISSUE THREAD

**Issue by jpggithub** [djcb/mu#2209]
**Describe the bug** 
When I send a message, lines that have 238 or more characters are reformated to paragraph with 70 character max per line.
The other are not reformated.

**To Reproduce**
Send the following line in a message (note that the end is "9"):
123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789

The line is reformated as (70 characters long max for each line):
123456789 123456789 123456789 123456789 123456789 123456789 123456789
123456789 123456789 123456789 123456789 123456789 123456789 123456789
123456789 123456789 123456789 123456789 123456789 123456789 123456789
123456789 123456789 123456789

Send the following line in a message (note that the end is "8", so it's one character less than the previous one):
123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 12345678

The line is NOT reformated.

I don't want any reformating.

I search in the previous bugs of `mu4e` in github and didn't found anything.

The only workaround that I have found is to use something like `(setq fill-flowed-encode-column 1000)`.
This original value was "66".

**Environment**
Debian/Linux/Emacs 27.1/mu version 1.6.10

**Comment by djcb** [comment]
Unless you specifically tell it so (e.g., `mu4e-compose-format-flowed`), mu4e does not change the formatting of your message.

**Comment by jpggithub** [comment]
You are right, thank you.
