### ISSUE TITLE
[mu4e rfe] Query API for third-party extensions

### ISSUE THREAD

**Issue by xzz53** [djcb/mu#2210]
**Is your feature request related to a problem? Please describe.**
Since mu 1.6, [mu4e-alert](https://github.com/iqbalansari/mu4e-alert) turned effectively unusable, because query results obtained by calling mu executable and those reported in mu4e fell out of sync (at least read/unread status).

**Describe the solution you'd like**
It would be good to have an API for executing queries which could be used by third-party extensions. Basically something along the lines of `mu4e~headers-search-execute`, but passing results to a user-provided callback instead of displaying them in a buffer.

**Describe alternatives you've considered**
At present a gross hack is used: `mu4e~proc-find` is called directly and handlers are overridden for the duration of the call. This is obviously far from ideal.

**Comment by djcb** [comment]
I'll consider it, but I'm reluctant to do so, since it makes future development much harder (having to consider third-party packages and whatever details they depend on).

**Comment by djcb** [comment]
Note, at least mu4e (10.x) has much of the mu4e-alert functionality built-in now. 
Anyway, such an API is not planned for the foreseeable future, so closing this.
