### ISSUE TITLE
[mu4e bug] mu version and mu4e version do not match since mu/mu4e 1.7.9

### ISSUE THREAD

**Issue by nils-schween** [djcb/mu#2213]
Hi everyone,

I just pulled and compiled the newest version of mu/mu4e (namley 1.7.9). After installing it, I got the following error messages.
`Found mu version 1.7.0 , but mu4e needs version 1.7.8`. Futhermore in the `*Messages*` buffer, I found a message that the byte compiled version of a file and it's elisp version did not match. 

To fix the problem I had to manually recompile mu4e-meta.el in the folder `/usr/share/emacs/site-lisp/mu4e`.

I suspect that this file is not byte-compiled when calling `ninja -C build`.
Thanks for taking care of this,
Nils

**Comment by theophilusx** [comment]
Just for added context, I ran into the same error (though it said it
found 1.7.9 but was expecting 1.7.7 in my case). Anyway, I deleted
/usr/local/share/emacs/site-lisp/mu4e and ran the install step again and
all worked fine.

**Comment by djcb** [comment]
Ah, yes... that's a side-effect of no longer compiling `mu4e-meta.el`, so an older version might remain... 
No longer compiling `mu4e-meta.el` is to avoid some `meson` build warning (with very new meson) for byte-compiling a generated file.

So, it's "expected", but admittedly a little inconvenient / error-prone if you have an older mu4e. Perhaps there's some better way...

**Comment by nils-schween** [comment]
Hmm... For me it looks like there are two different kind of things involved here. 1. There is the error message `Source file ‘/usr/local/share/emacs/site-lisp/mu4e/mu4e-meta.el’ newer than byte-compiled file; using older file` in the \*Messages\* buffer and secondly there is the dependence on the the variables defined in mu4e-meta.el (as for example in mu4e-proc.el in the function mu4e~proc-start() ). If I understand you correctly, the latter will be removed in the long term, since meson will keep on creating this warning. And I am wondering if the first error message can be dealt with by setting up meson in a way that it checks the mu/mu4e version and in case it is older than, say, x, it removes the mu4e-meta.el while `ninja install` is called. (Assuming that the mu4e-meta.el file is no longer needed by then.)

**Comment by djcb** [comment]
> Hmm... For me it looks like there are two different kind of things
> involved here.

> 1. There is the error message `Source file
> ‘/usr/local/share/emacs/site-lisp/mu4e/mu4e-meta.el’ newer than
> byte-compiled file; using older file` in the \*Messages\* buffer

That's not an error though; just emacs explaining what it does;
see `load-prefer-newer`.

> secondly there is the dependence on the the variables defined in
> mu4e-meta.el (as for example in mu4e-proc.el in the function
> mu4e~proc-start() ). If I understand you correctly, the latter will be
> removed in the long term, since meson will keep on creating this
> warning. And I am wondering if the first error message can be dealt
> with by setting up meson in a way that it checks the mu/mu4e version
> and in case it is older than, say, x, it removes the mu4e-meta.el
> while `ninja install` is called. (Assuming that the mu4e-meta.el file
> is no longer needed by then.)

The current behavior is not a bug; people should clear the installation
dir before installing a new version.

I understand that the extra step can be inconvenient (and trigger more
bug reports) so I'll try to convince meson to install that file again.

**Comment by nils-schween** [comment]
@djcb I think I misunderstood you. I thought that you were planning to remove the file mu4e-meta.el in the future to avoid the Warning created by meson. But this does not seem to be the case. 

> The current behavior is not a bug; people should clear the installation
> dir before installing a new version.
> I understand that the extra step can be inconvenient (and trigger more
> bug reports) so I'll try to convince meson to install that file again.

For me it is fine, to delete the installation folder every time before I call ninja install. But of course, it is nice if I do not have to do it. So thanks for trying to convince meson to install it automatically.

**Comment by theophilusx** [comment]
I think this was just a 'transition error' which only occurs when you
first install the new version over an older version. In previous
versions, the mu-meta file was compiled, so when you did the install you
had both an *.el and a *.elc versions installed. However, after this change, the
file is not compiled, so there is no *.elc version. When you do the
install, the *.el file is copied over, but because there is no *.elc
file, the old *.elc does not get over written. When you next start
mu, you get the error because by default, Emacs will load the *.elc file
if it exists (unless you have the setting to prefer newer enabled, which
isn't by default).

The good news is that once you have removed the *.elc file, you won't
see this error anymore and if your installing for the first time, you
won't see this error. It only affects those upgrading from an earlier
version and once you have fixed the issue, you won't see it in further
updates/upgrade.

**Comment by djcb** [comment]
True, a clean re-install avoid the problem... but for now I've restored (most of) the old behavior, to avoid confusion. Still need to find a better solution to avoid the `meson` warning.
