### ISSUE TITLE
[mu4e bug] Commit a0ec982 breaks mbsync seen flag handling

### ISSUE THREAD

**Issue by markk** [djcb/mu#2214]
**Describe the bug**
This commit "mu4e/server: honor rename-move for view-message, too" seems to have broken the behaviour of mbsync regarding seen messages. Previously, an email flagged as seen by mu4e would keep its seen flag on the next run of mbsync. Now mbsync removes the seen flag (presumably because it hasn't seen the message before?)

This means that messages that have been marked read keep reappearing as unread each time the maildir is synced.

Perhaps this is actually a bug of mbsync, but it worked correctly prior to this change.

**To Reproduce**

`(setq mu4e-change-filenames-when-moving t)`

- mail arrives with mbsync: `new/1645697891.133916_1.localhost,U=2745:2,`
- view in mu4e, renamed to: `cur/1645697956.5617ed40d1ee259d.localhost.localdomain:2,S`
- sync again with mbsync:   `cur/1645697956.5617ed40d1ee259d.localhost.localdomain,U=2746:2,`

`(setq mu4e-change-filenames-when-moving nil)`

- mail arrives with mbsync: `new/1645698642.137452_1.localhost,U=2749:2,`
- view in mu4e, moved to:   `cur/1645698642.137452_1.localhost,U=2749:2,:2,S`
- sync again with mbsync:   `cur/1645698642.137452_1.localhost,U=2749:2,:2,S`

**Environment**
Linux Fedora 35
Emacs 29.0
mu/mu4e 1.7.9

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
I've rolled-back this part of the change, perhaps in the future we can dig into the details of the `mbsync` interaction, but since I'm not even using that, it's better to leave the existing behavior in place.
