### ISSUE TITLE
[mu4e bug] Error when moving message

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2215]
**Describe the bug**
Error when trying to move messages.

**To Reproduce**
Not clear how to reproduce.  Quitting and restarting mu4e usually solves the problem (I can mark the message again “to be moved” and press <kbd>x</kbd>).

```
Debugger entered--Lisp error: (error #("[mu4e] Error 102: failed to move message: somethin..." 1 5 (face mu4e-title-face)))
  signal(error (#("[mu4e] Error 102: failed to move message: somethin..." 1 5 (face mu4e-title-face))))
  error("%s" #("[mu4e] Error 102: failed to move message: somethin..." 1 5 (face mu4e-title-face)))
  mu4e-error("Error %d: %s" 102 "failed to move message: something went wrong")
  mu4e--error-handler(102 "failed to move message: something went wrong")
  mu4e--server-filter(#<process *mu4e-server*> "\37645\377(:error 102 :message \"failed to move message: ...")
```

**Environment**
Linux
Emacs 27.1
Mu: commit 285185aa

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by Chris00** [comment]
I turned on debug and I'll report it next time the problem happens.

**Comment by Chris00** [comment]
```
2022-02-24 22:27:03.947 -> (move :docid 172542 :msgid nil :flags "+T-N" :maildir "/trash" :rename t :no-view nil)
2022-02-24 22:27:03.949 -> (move :docid 172543 :msgid nil :flags "+T-N" :maildir "/trash" :rename t :no-view nil)
2022-02-24 22:27:04.019 * Received 160 byte(s)
2022-02-24 22:27:04.019 <- (:error 102 :message failed to move message: something went wrong)
2022-02-24 22:27:04.019 !! [mu4e] Error 102: failed to move message: something went wrong
```
Let me know what kind of further debugging I can do.

**Comment by Chris00** [comment]
Just `mu4e-update-mail-and-index` fixed the problem (I could select the messages and delete them).

**Comment by Chris00** [comment]
Before `mu4e-update-mail-and-index`, the messages are still visible in `*mu4e-headers*` but mu4e thinks they are no longer there:
```
user-error: [mu4e] No message at /home/user/Maildir/XXX/inbox/cur/1645738014.a86894577a2b2449.home:2,S
```
*Feels* like a race condition where mu updates the message in its database before moving it (and thus trying to access the wrong filename).

**Comment by Chris00** [comment]
I upgraded to commit 3b205dacffc67d0f7e3f392ccea3ea2097949527 and have not hit this problem so far.

**Comment by djcb** [comment]
Thanks. Closing thing for now...
