### ISSUE TITLE
[mu bug] mu error message with contact name

### ISSUE THREAD

**Issue by markk** [djcb/mu#2216]
**Describe the bug**
Since updating to 1.7.9 (from 1.7.6) I have noticed repeated errors from mu in my journal logs. They are of the form:

```
DATETIME localhost.localdomain mu[PID]: error: 'NAME'
```

where NAME is usually a first name. I tracked these down to specific email messages and the error seems to be triggered by a email with headers of the form:

```
To: Joe Bloggs <joe@bloggs.com>, An Other <an@other.com>, 
 Jane Smith <jane@smith.com>, Crusty
 Clown <crusty@clown.com>
```

i.e. where a name is broken by a line break in the source message. In this instance the name in the error would be 'Crusty'.

**To Reproduce**
Run `mu index` on a message store containing such a message.

**Environment**
Linux Fedora 35
Emacs 29.0
mu 1.7.9

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
This should be fixed now; probably requires a fresh `init` to get rid of that warning though.
