### ISSUE TITLE
[mu4e rfe] Being able to reply to multiple "*" marked messages at once

### ISSUE THREAD

**Issue by P-EB** [djcb/mu#2217]
**Describe the solution you'd like**
Sometimes I would like to be able to reply to multiple mails in one shot like mutt's ';g' command to reply to multiple tagged emails.

**Describe alternatives you've considered**
What I currently do is create a draft mail with mutt and then edit it in mu4e to be able to still have this feature. :D

**Comment by pymander** [comment]
I also miss this feature and would love to see it implemented in mu4e!

**Comment by djcb** [comment]
This would be hard to implement, unfortunately. So I'll have to decline this. Sorry!
