### ISSUE TITLE
Maildir shortcuts (on mu4e-main)  not displaying mailbox number count

### ISSUE THREAD

**Issue by mclearc** [djcb/mu#2219]
**Describe the bug**
A clear and concise description of what the bug is, what you expected to happen and what actually happened.

On setting `mu4e-maildir-shortcuts` I'd expect the dirs to show, along with a mailbox count and a keybind. What I'm actually seeing is that the dirs and the keybinds show up (and the dirs, when clicked, generate the right search query), but there is no maildir count (not even "0/0").

Screenshot:

<img width="744" alt="Screen Shot 2022-03-03 at 16 57 20" src="https://user-images.githubusercontent.com/1502422/156659826-b32bb7ba-e6e3-4d76-96c8-ab1657d018ec.png">

**To Reproduce**
Detailed steps to reproduce the behavior. If this is about a specific (kind of) message, **always**
attach an (anonymized as need) example message.

Just set `mu4e-maildir-shortcuts`.

Note that it is very possible that I'm not setting this correctly. Here is what I have:

```emacs-lisp
  (setq   mu4e-maildir-shortcuts
          '((:maildir "/Fastmail/Archive"    :key ?a)
            (:maildir "/Fastmail/Inbox"      :key ?i)
            (:maildir "/Fastmail/Starred"    :key ?w)
            (:maildir "/Fastmail/Sent Items" :key ?s)
            (:maildir "/UNL/Inbox"           :key ?I)
            (:maildir "/UNL/Archive"         :key ?A)
            (:maildir "/UNL/Archive1"        :key ?1)
            (:maildir "/UNL/Sent"            :key ?S)))
```

I've tried futzing with the `mu4e~maildirs-with-query` function but haven't seen any improvement (though again maybe I'm just setting this up wrong?)

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.
M1 Mac running MacOS 12.2.1, Emacs 29, and mu 1.6.10.

I've checked this problem both with my own config and with vanilla emacs. 

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Hmmm... it should work I think... can you reproduce with a minimal setup (i.e., one maildir and one bookmark, and no further customizations? You can also try (esp. with that minimal setup with `M-x mu4e-toggle-logging`) and see the traffic in the corresponding buffer.

**Comment by mclearc** [comment]
Looks like in the end this was a conflict with another package I had loaded in my mu4e config -- [mu4e-goodies](https://github.com/panjie/mu4e-goodies). I use it for tagging and attachment checking. I'm not sure what the source of the conflict is. But in the meantime I pulled out the code I needed and junked the rest and all seems to be working well. Thanks for your help (and for mu of course)!
