### ISSUE TITLE
[mu4e bug] Bookmarks find no messages anymore after recent commits on master (currently 0368a48149eabfb5b125a71e7a2327c8df60b8d5)

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#2220]
**Describe the bug**
My normal `unread` bookmark (just as an example) executes the following query: `flag:unread AND maildir:"/^/Fastmail/\(mailinglists/\|GNU$\|Archive$\|Drafts\)/" AND NOT maildir:"/\(?:/\(?:Deleted Items\|Junk Mail\|Papierkorb\|Spam\|Trash\|training/\)\)/"`

With the last commits on master, that query finds no messages anymore although there are plenty of unread messages, e.g. in `/Fastmail/mailinglists/emacs-devel`.

Basically, the bookmark is just `flag:unread` and the maildir restrictions are added by a context-aware `mu4e-query-rewrite-function`.

When I execute the query manually, I also get no results.  However, when I remove the `AND NOT maildir:"/\(?:/\(?:Deleted Items\|Junk Mail\|Papierkorb\|Spam\|Trash\|training/\)\)/"` part ("don't show messages from boring maildirs), then I get the expected results.

**To Reproduce**

Execute the above query with `maildir` regexes suitable for your maildir structure.

**Environment**

Emacs master, Mu master, Arch Linux

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Ay ay... should have a unit-test for that. I've pushed a provisional fix.

**Comment by tsdh** [comment]
Works again, thanks a lot.

**Comment by djcb** [comment]
Great, thanks!
