### ISSUE TITLE
[mu4e rfe] refile a thread *without* moving my sent messages

### ISSUE THREAD

**Issue by plantarum** [djcb/mu#2221]
**Is your feature request related to a problem? Please describe.**

I have a custom action for moving a message or thread to the archive:

```
(add-to-list 'mu4e-marks
  '(archive
     :char       "A"
     :prompt     "Archive"
     :show-target (lambda (target) "Archive")
     :action      (lambda (docid msg target)
                    ;; must come before proc-move since retag runs
                    ;; 'sed' on the file
                    (mu4e-action-retag-message msg "-\\Inbox")
                    (mu4e~proc-move docid "/Archive" "+S-u-N"))))
```

This works fine. But if I'm reading a thread with 'include-related' on, and I select a thread to move to the archive, it moves emails that I sent (i.e., they're in my /Sent folder) to the Archive. That's not what I'd like: I want to sent messages from my Inbox to the Archive, but leave related messages in the /Sent folder. 

**Describe the solution you'd like**

I'm asking for advice, I don't think this would require a new feature (probably). What would be the most sensible approach to accomplish this?  Is there a function I can use to detect the current folder of an email, in order to only move a message conditional on it not being in /Sent?

**Comment by djcb** [comment]
Basically this is "refiling", and you can use a "dynamic folder" for that, i.e., I have
```
  (setq mu4e-refile-folder
	(lambda (msg)
	  (cond
	   ;; all messages sent by me go to /sent
	   ((mu4e-message-sent-by-me msg) "/sent")
         .... other rules ..., perhaps returning "/Archive"
```
That doesn't retag though, if you insist on that you can add a `mu4e-message-sent-by-me` guard to your solution.

**Comment by plantarum** [comment]
Perfect, thanks!
