### ISSUE TITLE
[msys] mu index shows indexing and nothing indexed.

### ISSUE THREAD

**Issue by haoisli9** [djcb/mu#2223]
**Describe the bug**
mu init success, but when I use mu index to index maildir, it shows indexing but nothing indexed.

**To Reproduce**
$ mu mu init --muhome=~/Maildir/139
maildir           : /d/Users/home/Maildir
database-path     : /d/Users/home/Maildir/139/xapian
schema-version    : 452
max-message-size  : 100000000
batch-size        : 250000
messages in store : 0
created           : 2022年03月25日 16:36:11
personal-address  : <none>

store created; use the 'index' command to fill/update it.

$ mu index --muhome=~/Maildir/139
indexing maildir /d/Users/home/Maildir -> store /d/Users/home/Maildir/139/xapian
/ indexing messages; processed: 0; updated/new: 0; cleaned-up: 0

here it indexing forever, but no message indexed. processed always 0.

**Environment**
Please describe the versions of OS, Emacs, mu etc. you are using.
Msys2 in win10
$ mu --version
mu (mail indexer/searcher) version 1.6.10
Copyright (C) 2008-2021 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ mbsync --version
isync 1.4.4

$ xapian-check --version
xapian-check - xapian-core 1.4.19

**Checklist**
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).
yes I'am running 1.16.10.

**Comment by djcb** [comment]
Hmm, not sure. I would not put the database (i.e., `--muhome`) inside the maildir though. Perhaps it tries to index that? Or something specific to Windows?

**Comment by haoisli9** [comment]
I use --muhome to special maildir xapian database directory. or it will create in ~/.cache. But mu index can not work correctly even I do not use --muhome flag.
mu 1.14.15 can work correctly in Msys2 in Win10.  but mu4e 1.14.15 can not show inline image in my emacs. so I want update mu to 16. maybe I miss something in 1.14.15? 
Thanks.



***@***.***
 
From: Dirk-Jan C. Binnema
Date: 2022-03-29 04:32
To: djcb/mu
CC: haoisli9; Author
Subject: Re: [djcb/mu] [mu bug] mu index shows indexing and nothing indexed. (Issue #2223)
Hmm, not sure. I would not put the database (i.e., --muhome) inside the maildir though. Perhaps it tries to index that? Or something specific to Windows?

**Comment by djcb** [comment]
Having the database somewhere else is fine of course (that's why there is `--muhome`). I was just wondering if perhaps having it in the Maildir might cause problems. 

I'd recommend running indexing with some extra more logging, with `--debug`, and check the various `.log` files that should appear in your mu directory.

**Comment by haoisli9** [comment]
Hi,

    Thanks for your replay. I have run mu index 1.4.15/1.6.0 successfully. but mu version 1.6.10 still has index problem. It has different schema-version, maybe schema-version 452 did not compatible with Msys2 on win11?
    I use mu 1.14.15, now I can read mails. But I found another problem:
    When I mark the mail as read, mu always change the mail file name, even when I set the mu4e-change-filenames-when-moving to t. The file name was changed like "1648704212.420_292.notebook-699,U=292;2,S:2,S" here ":" in file name on windows can not be handled and cause error. Can I fix it?

    Thanks a lot.



***@***.***
 
From: Dirk-Jan C. Binnema
Date: 2022-03-31 14:52
To: djcb/mu
CC: haoisli9; Author
Subject: Re: [djcb/mu] [mu bug] mu index shows indexing and nothing indexed. (Issue #2223)
Having the database somewhere else is fine of course (that's why there is --muhome). I was just wondering if perhaps having it in the Maildir might cause problems.
I'd recommend running indexing with some extra more logging, with --debug, and check the various .log files that should appear in your mu directory.

**Comment by djcb** [comment]
There are only minor changes in the 1.6.x series (i.e. after 1.6.0).

1.4.x may indeed have problems with Msys, likely because of the Windows file system of the the `:` as you say. 1.4.x is so old that it's not  supported anymore. 

I don't have a Windows machine or MSys, so it's untested. If you can debug it, you are very welcome :), perhaps you can try 1.7.x (git `master`)?

**Comment by haoisli9** [comment]
hi. i have tried 1.6.10, it works after i rebuilt it. but it seems still have the file name problem. and 1.7.x can not be built on msys, it says "can not find fileno defination", maybe 1.7.x use new function that does not be supported by windows system?
do you mean 1.6.10 should not have the file name problem? i will try it again.

thank you.



***@***.***
 
From: Dirk-Jan C. Binnema
Date: 2022-04-05 12:24
To: djcb/mu
CC: haoisli9; Author
Subject: Re: [djcb/mu] [mu bug] mu index shows indexing and nothing indexed. (Issue #2223)
There are only minor changes in the 1.6.x series (i.e. after 1.6.0).
1.4.x may indeed have problems with Msys, likely because of the Windows file system of the the : as you say. 1.4.x is so old that it's not supported anymore.
I don't have a Windows machine or MSys, so it's untested. If you can debug it, you are very welcome :), perhaps you can try 1.7.x (git master)?

**Comment by djcb** [comment]
Okay, so some more work is needed. I've asked on the Mu mailing list if there's someone who can work on this.

**Comment by djcb** [comment]
Seems we don't have the necessary expertise on MSys, so we can't really help with this.  I've added a note about this to NEWS.org. Closing.

(Hopefully in the future we can make it work again, but right now we can't claim to support MSYS)
