### ISSUE TITLE
[mu4e bug] Error 105: invalid property name ('')

### ISSUE THREAD

**Issue by pbeliveau** [djcb/mu#2226]
**Describe the bug**
Any filter/header view results in this error and a blank result:
```
error in process filter: [mu4e] Error 105: invalid property name ('')
```

**To Reproduce**
Build latest commit (5a28cdfba4743d9d771fc5ee432ce23ca834b38a), and use in mu4e in Emacs. Open any headers view.

**Environment**
Linux 5.16.16-zen1-1.1-zen
GNU Emacs 29.0.50 (commit 2dfeea8)
mu4e - mu for emacs version 1.7.11

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by markk** [comment]
I am getting this error also, but only with one of my bookmarks (actually my spam folders). I can't see anything different about that query that is triggering it, I wonder if it is a particular message. Will attempt to investigate further. 

```
2022-03-28 10:32:28.744 -> (find :query "maildir:\"/account1/[Gmail]/Spam\" OR maildir:\"/account2/[Google Mail]/Spam\"" :threads t :sortfield :date :descending t :maxnum 500 :skip-dups t :include-related nil)
2022-03-28 10:32:28.777 * Received 76 byte(s)
2022-03-28 10:32:28.777 <- (:erase t)
2022-03-28 10:32:28.777 <- (:error 105 :message invalid property name (''))
2022-03-28 10:32:28.777 !! [mu4e] Error 105: invalid property name ('')
```

**Comment by djcb** [comment]
Thanks... I think this should be fixed with the latest. Can you confirm?

**Comment by pbeliveau** [comment]
Confirmed fixed! :+1:

**Comment by markk** [comment]
Confirmed. Thanks @djcb
