### ISSUE TITLE
Update website?

### ISSUE THREAD

**Issue by c0dev0id** [djcb/mu#2228]
Hello,
just a quick question: Is github considered the main "homepage" for mu now?
In our OpenBSD port, we still link to http://www.djcbsoftware.nl/code/mu. But this page lists mu versions up to 1.2 only.

**Comment by djcb** [comment]
Yeah, I should update the website :-) Thanks for the reminder.

**Comment by c0dev0id** [comment]
Okay, then we keep linking to it. I leave it up to you to close the issue or keep it open as a reminder. :-)

**Comment by djcb** [comment]
Sure! I have updated it now. Always a pain to when you don't do it so often :)
