### ISSUE TITLE
[mu4e bug] Ignores Reply-to header when replying

### ISSUE THREAD

**Issue by theophilusx** [djcb/mu#2229]
**Describe the bug**
When replying to a message which includes a Reply-to: header, mu4e only uses the From: header to set the address. This seems to be a recent change in v1.7.12. 

Previously, when I replied to a github issue email, the reply would be sent back to github and added to the issue because github issue emails have a custom Reply-to: header which creates a unique email address for each issue.  This no longer works.

Another change which I've noticed, but which may or may not be related, is in how mu4e responds when replying to messages from a mail list. Previously, when you 1st replied to a message from a mail list, mu4e would ask if you wanted to reply just to the list, to the sender or to everyone. Now it does not offer the option to just reply to the list. 

**To Reproduce**

Attempt to reply to a github issue message. The To: header should be an email addrfess of the form <reply+XXX@reply.github.com> where XXX is a unique hash used to identify the issue. The actual address used by mu4e is <notifications@github.com>, which I suspect is just directed to /dev/null

I suspect you can also reproduce this by just replying to any message with a Reply-to: header and seeing if the To: address used by mu4e is taken from the reply-to header or the from header. 

**Environment**

GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0) of 2022-04-05

Mu version 1.7.12 Commit: 100b41b257e295f94a086fede004333d87349406

Ubuntu MATE 21.10

**Comment by djcb** [comment]
Yeah, it's some fallout from the (ongoing) rework of the mu internals. This will be fixed shortly.

**Comment by djcb** [comment]
Fixed in `master`.
