### ISSUE TITLE
Consider removing deprecated lib   rfc2368 [misc]

### ISSUE THREAD

**Issue by rwilson-lib** [djcb/mu#2231]
**Note**: for questions, please use the mailing-list: https://groups.google.com/g/mu-discuss
When will the team consider removing the deprecated rfc2368 lib
**Describe the issue**
A clear and concise description, i.e. what you expected/desired to happen and what actually happened.
Below are the line that still uses the package
mu4e-compose.el:73:1: Warning: Package rfc2368 is deprecated
mu4e-headers.el:41:1: Warning: Package rfc2368 is deprecated
mu4e-view-common.el:32:1: Warning: Package rfc2368 is deprecated
mu4e-view-gnus.el:30:1: Warning: Package rfc2368 is deprecated
mu4e-view.el:35:1: Warning: Package rfc2368 is deprecated
mu4e-icalendar.el:57:1: Warning: Package rfc2368 is deprecated
mu4e-org.el:31:1: Warning: Package rfc2368 is deprecated
mu4e.el:30:1: Warning: Package rfc2368 is deprecated

**Environment**
If applicable, please describe the versions of OS, Emacs, mu etc. you are using.

**Comment by djcb** [comment]
Thanks. Note: this a dup of #2190 and in fact we're not using that package any more in `master`. So, closing this.
