### ISSUE TITLE
mu4e failing to load some spam messages

### ISSUE THREAD

**Issue by orbitz** [djcb/mu#2232]
**Describe the bug**
Some spam I'm getting on gmail is failing to open in mu4e with the following error:

```
error in process filter: mu4e-error-handler: Error 107: could not find
message(s) for msgid
6BTxn8V9hfgdHVRxNs1=èñÅ}øTq6Íu5977454261629007905639494259214.7777@sandboxsyndicate.biz
error in process filter: Error 107: could not find message(s) for msgid
6BTxn8V9hfgdHVRxNs1=èñÅ}øTq6Íu5977454261629007905639494259214.7777@sandboxsyndicate.biz
```

The message view just sits there saying "loading" when I try to open it.  I can close the window and read other email though.

**To Reproduce**
I don't really have a way to reproduce it.  I'm guessing just a message with those characters in it would work.

**Environment**
FreeBSD on mu4e 1.6.4

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Can you attach such a message? Thanks.

**Comment by orbitz** [comment]
How can I access it?  I can't open it in mu4e.

**Comment by djcb** [comment]
There should be a file for this message in one of your Maildirs; i.e. search your maildirs for a file containing the string "454261629007905639494259214.7777@sandboxsyndicate.biz"

```
$ grep -r 454261629007905639494259214.7777@sandboxsyndicate.biz ~/Maildir
``` 
(change as needed).

When it finds this file, attach it here. Thanks.

**Comment by orbitz** [comment]
Unfortunately I marked the mail as spam and now I can't seem to find it in the gmail spam folder.  I don't sync my gmail spam folder.  Hopefully I'll get another piece of Spam that I can send you.  Apologies for not collecting more data.

**Comment by bjc** [comment]
I have the same issue, but simpler to repro, and I assume it's something with escaping the `Message-ID`:

```
error in process filter: mu4e-error-handler: Error 107: could not find message(s) for msgid 3144HPOJ0VC77.3H1XTAG2AMTLH@"@WILSONB.COM
error in process filter: Error 107: could not find message(s) for msgid 3144HPOJ0VC77.3H1XTAG2AMTLH@"@WILSONB.COM
```

Interestingly, I cannot use that Message ID on the command line, either:
```
% mu find i:'3144HPOJ0VC77.3H1XTAG2AMTLH@"@WILSONB.COM'                                                                             
error: no matches for search expression
```

It does show up when not used as a search query argument:
```
mu find --fields 'msgid from' f:wilsonb.com                                                                                                                                                                                                                                     
/INBOXShepherd erroring on guix system reconfigureSl3144HPOJ0VC77.3H1XTAG2AMTLH@"@WILSONB.COMSun Apr 17 04:34:24 2022 "B. Wilson" <elaexuotee@wilsonb.com>o/INBOX
```

So it appears this is a `mu` problem, not an `mu4e` problem.
[wilson-msg.txt](https://github.com/djcb/mu/files/8501477/wilson-msg.txt)


I've attached the full message for you to look at.

**Comment by djcb** [comment]
Ah, thanks... yeah, the message is correctly indexed but the message-id contains an `"` (which is not allowed afaik), which screws up the searching... in xapian you cannot really search for things with an embedded `"`.

Some workarounds are possible.... I've pushed one.

**Comment by djcb** [comment]
Okay forgot to close this :) Let's do so now.
