### ISSUE TITLE
Deadlock in mu 1.6.10

### ISSUE THREAD

**Issue by thomasthiriez** [djcb/mu#2233]
## Expected or desired behavior

The mu server should not freeze, and answer the requests sent my mu4e.

## Actual behavior

From time to time, the mu server freezes, and the mu4e interface becomes unresponsive, showing "Searching..."

Both the main thread and the indexer threads are blocked in sleep loops. The main thread is stuck there:

https://github.com/djcb/mu/blob/77f10379cb42e3a41805efed8a15c7c2db46fb68/lib/mu-server.cc#L878

And the indexer thread is stuck there:

https://github.com/djcb/mu/blob/77f10379cb42e3a41805efed8a15c7c2db46fb68/lib/index/mu-indexer.cc#L284

This does not happen every day, but certainly at least once a week.

## Steps to reproduce

I don't know of a way to reliably reproduce the problem, but it happens often enough to be annoying.

## Versions of mu, mu4e/emacs, operating system etc.

mu 1.6.10
Emacs 28.1
macOS 11.6.5

**Comment by djcb** [comment]
I've put a small workaround / fix for this in the 1.6.x branch... does it solve the problem for you?

**Comment by haruo31** [comment]
I have same problem.
On my Mac, deadlock does not occur after set Indexer::Config::max_threads = 1.

```
diff --git a/lib/mu-server.cc b/lib/mu-server.cc
index c472ea00..38fe4c3c 100644
--- a/lib/mu-server.cc
+++ b/lib/mu-server.cc
@@ -873,6 +873,7 @@ Server::Private::index_handler (const Parameters& params)

         indexer().stop();

+        conf.max_threads = 1;
         indexer().start(conf);
         while (indexer().is_running()) {
                 std::this_thread::sleep_for(std::chrono::milliseconds(1000));
```

## Versions of mu, mu4e/emacs, operating system etc.
mu 1.6.10 + db1a5c6 patch
emacs 28.1
macOS 12.3.1 (21E258)

**Comment by thomasthiriez** [comment]
> I've put a small workaround / fix for this in the 1.6.x branch... does it solve the problem for you?

Thanks a lot. I have installed it, and will let you know if I see the problem again.

**Comment by djcb** [comment]
Well, `conf.max_threads = 1` may work around the problem, yes.

If possible, can you reproduce with `master`?

**Comment by djcb** [comment]
Going to close this now; feel free to re-open if you can reproduce with `master`. Thanks!
