### ISSUE TITLE
[mu4e bug] mu4e~headers-move doesn't return nil on failure

### ISSUE THREAD

**Issue by Zetagon** [djcb/mu#2239]
https://github.com/djcb/mu/blob/d0619b1db297b86540319c2c051cc9977ec2e090/mu4e/mu4e-headers.el#L1608

**Describe the bug**

I might be reading the code wrong, but it looks like `mu4e~headers-move` doesn't return `nil` when it doesn't succeed as the docstring says it should.  

I have this code on [sourcehut](https://git.sr.ht/~zetagon/el-secretario/tree/78a811f02c7104a39b908f9e4c8436abde4b9620/item/el-secretario-mu4e.el#L116) that's a couple of months old that I think fixed the issue at the time (can't remember :sweat_smile: ).  I don't fully understand how it has changed since then, but it looks like it's just wrapping the first `when` form with an `(if succeeded ... nil)` form.

**To Reproduce**
Call `mu4e~headers-move` such that `goto-next-line` fails (i.e tries to go outside the buffer boundaries).

**Environment**

openSUSE, Emacs 28.1

**Checklist**
- [ ] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

(By the way, I opened this issue from the line menu [https://github.com/djcb/mu/blob/d0619b1db297b86540319c2c051cc9977ec2e090/mu4e/mu4e-headers.el#L1608](here), but it seems like it didn't open the issue template)

**Comment by djcb** [comment]
Fixed in `master`.
