### ISSUE TITLE
Bookmarks do not filter correctly

### ISSUE THREAD

**Issue by M-Stenzel** [djcb/mu#2244]
**Describe the bug**
The definition of the bookmarks does not apply, for example the mails from today, which should be displayed with "bt" yields
8218 mails. This is mad. As you can see, filtering does not get applied, since the list includes mails from 2021, not from today.

![Screenshot_20220501_155445](https://user-images.githubusercontent.com/76916440/166149238-09d22c76-dfd8-4d6b-89ed-b6d95ccd88b6.png)

As you can see from the screenshot, the filter says "date:today..now"

I verified with: mu find maildir:/ AND date:today..now | wc -l, which yields a correct number of 59.

The "bw" bookmark yields 8765 messages, again many many older than 7 days.

**To Reproduce**
This happens always

**Environment**
Linux openSUSE
Emacs: 28.1 (official rpm)
mu4e: 1.6.10 (official rpm, no patches applied)
xapian: 1.4.19 (official rpm)

These are the modifications I made to .emacs.d/init.el:

----

;;
  (prefer-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-language-environment 'utf-8)
;;
  (menu-bar-mode -1)
;;
  (require 'mu4e)
;;
  (setq mail-user-agent 'mu4e-user-agent)
;;
  (setq
    mu4e-sent-folder   "/.Sent"
    mu4e-drafts-folder "/.Drafts"
    mu4e-trash-folder  "/.Trash"
    mu4e-refile-folder "/.Archive")
;;
  (setq mu4e-maildir-shortcuts
    '( (:maildir "/"         :key  ?i)
       (:maildir "/.Archive" :key  ?a)
       (:maildir "/.Drafts"  :key  ?d)
       (:maildir "/.Trash"   :key  ?t)
       (:maildir "/.Sent"    :key  ?s)))
;;
  (setq message-send-mail-function 'smtpmail-send-it)
  (setq smtpmail-smtp-server "mail.xy-space.de")
  (setq smtpmail-local-domain "xy-space.de")
;;
  (setq
    user-mail-address "m.stenzel@mail.xy-space.de"
    user-full-name  "Martin Stenzel"
    mu4e-compose-signature
    (concat
      "Martin Stenzel"))
;;
  (setq mu4e-headers-results-limit '65536)
;;
  (add-hook 'dired-mode-hook 'turn-on-gnus-dired-mode)
;;

I needed to insert the header-results-limit, otherwise the 500 mail number limit would apply. Of course the problem is somewhere else...

----

This is my Maildir directory layout

drwxr-xr-x  5 m.stenzel users    4096 Jan 25 22:42 .Actalis
drwxr-xr-x  5 m.stenzel users    4096 Aug  7  2021 .Archive
drwxr--r--  2 m.stenzel users  319488 May  1 16:53 cur
drwxr-xr-x  5 m.stenzel users    4096 May  1 13:55 .DeltaChat
-rw-r--r--  1 m.stenzel users   93392 May  1 16:13 dovecot.index
-rw-r--r--  1 m.stenzel users 5809732 May  1 16:53 dovecot.index.cache
-rw-r--r--  1 m.stenzel users   19680 May  1 16:54 dovecot.index.log
-rw-r--r--  1 m.stenzel users   32800 Apr 30 22:38 dovecot.index.log.2
-rw-r--r--  1 m.stenzel users   21099 Feb 12  2019 dovecot.index.thread
-rw-r--r--  1 m.stenzel users      47 Jun  2  2019 dovecot-keywords
-rw-r--r--  1 m.stenzel users    1416 Apr 30 23:32 dovecot.list.index
-rw-r--r--  1 m.stenzel users    3616 May  1 13:55 dovecot.list.index.log
-rw-r--r--  1 m.stenzel users    1296 Feb  9 11:21 dovecot.mailbox.log
-rw-r--r--  1 m.stenzel users  240666 May  1 16:53 dovecot-uidlist
-rw-r--r--  1 m.stenzel users       8 Feb  9 11:21 dovecot-uidvalidity
-r--r--r--  1 m.stenzel users       0 Jan 24  2018 dovecot-uidvalidity.5a68f92c
drwxr-xr-x  5 m.stenzel users    4096 May  1 13:00 .Drafts
drwxr-xr-x  5 m.stenzel users    4096 Feb 15 20:28 .INBOX.edudip
drwxr-xr-x  5 m.stenzel users    4096 Jun  3  2021 .INBOX.pEp
drwxr-xr-x  5 m.stenzel users    4096 Mar 18 11:45 .Junk
drwxr--r--  2 m.stenzel users   20480 May  1 16:53 new
drwxr-xr-x  5 m.stenzel users    4096 Jan 27  2020 .Notes
drwxr-xr-x  5 m.stenzel users    4096 May  1 13:00 .Sent
-rw-r--r--  1 m.stenzel users      68 Feb  2 18:53 subscriptions
drwxr--r--  2 m.stenzel users    4096 May  1 16:53 tmp
drwxr-xr-x  5 m.stenzel users    4096 May  1 13:13 .Trash

Note that both postfix and dovecot run on the same machine. I do not need to retrieve the mails since they are in the Maildir
directly. Same applies to sending mails. Composing, sending & reading mails with mu4e works perfectly.

**Checklist**
- [x ] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x ] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x ] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

![Screenshot_20220501_154326](https://user-images.githubusercontent.com/76916440/166149353-d3a26804-0670-4a28-9cf4-707ce728ec55.png)

Are the numbers of the mails plausible? As you can see there are no numbers in the 7 day bookmark - why?
The number of "in store messages" is way higher than the numbers above.

Thank you for your support. I already love this software,

Wishes,

Martin.

P. S. I checked the logs, too, but there are no warnings nor any errors.
P.P.S. I deleted and reinitialised the xapian database and run "mu index" periodically, this did not help either.

**Comment by M-Stenzel** [comment]
Hi team,

this is interesting.
As explained in my post there is a subdirectory ".DeltaChat" in "Maildir" which gets created by DeltaChat [https://delta.chat/en/](https://delta.chat/en/).
After putting a ".noindex" file in this subdirectory and reinitialising the xapian database the problem went away!
Now, could the problem be caused by the number of mails (in my case 13.095) in this subfolder?

Does anyone use a combination of DeltaChat and mu4e to verify?

Martin.

**Comment by djcb** [comment]
By default, mu4e includes _related_ messages as well, but mu find does not. That sometimes confuses new users.

**Comment by djcb** [comment]
I.e., https://www.djcbsoftware.nl/code/mu/mu4e/General.html#Results-from-mu-and-mu4e-differ-_002d-why_003f
