### ISSUE TITLE
Issues with umlauts (ö, ü, ä, ß) and cyrillic characters

### ISSUE THREAD

**Issue by M-Stenzel** [djcb/mu#2245]
**Describe the bug**
Umlauts and cyrillic characters are not displayed properly in the mail list view

**To Reproduce**
When new messages are displayed in the list, sender and/or subject are not displayed correctly, however, after opening the message the characters are displayed correctly, see these images. Two mails should show the "Ö", not "\303"

![Screenshot_20220501_184416](https://user-images.githubusercontent.com/76916440/166156811-8aad46da-3687-42b0-801c-0748bbda4537.png)

![Screenshot_20220501_184504](https://user-images.githubusercontent.com/76916440/166156822-53d35729-05d8-4256-bcf0-6b9c6ab1b630.png)

![Screenshot_20220501_184545](https://user-images.githubusercontent.com/76916440/166156827-2a133b15-12c1-4670-880d-079754aeb99c.png)

![Screenshot_20220501_184747](https://user-images.githubusercontent.com/76916440/166156837-d3d50923-deb7-4df4-9afe-b6a9896c3912.png)

See below examples with cyrillic characters, again, after opening they show as expected

![Screenshot_20220501_180720](https://user-images.githubusercontent.com/76916440/166156905-70cff3c2-2ebe-4404-8e81-359395b2d152.png)

![Screenshot_20220501_180813](https://user-images.githubusercontent.com/76916440/166156913-57ec6b51-610d-4f76-b75b-6358ba81f9fe.png)

**Environment**
openSUSE Linux, Emacs 28.1, mu/mu4e 1.6.10

locale:
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"

snippet from .emacs/init.el

----
;;
  (prefer-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-language-environment 'utf-8)
;;
----

**Checklist**
- [*] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [*] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [*] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

Oddly, mu4e seems to "remember" the right display, after reopening emacs and mu4e the characters are displayed correctly.

Thanks for any help,

Martin.

**Comment by djcb** [comment]
Hmm, can't reproduce that (albeit with the `master` version). Can you reproduce with the graphical version?

**Comment by M-Stenzel** [comment]
Hi,
well, I only use the console version, since I do not have X installed, thereby I cannot verify.
So it will take me a little longer, but will investigate further.

Martin.

**Comment by djcb** [comment]
Hmm, your screenshots suggest that you _do_ have X installed? In any case, I couldn't reproduce with either X or console... so can't immediately think of what could be causing this.

**Comment by M-Stenzel** [comment]
Yes, I run X on my Laptop but use emacs/mu4e directly on the server. 

I installed emacs-x11 on the server (alongside X) but the results are the same - no difference between terminal and X.
As to the subject of a mail - for example: only after opening the mail the umlauts of the subject get displayed correctly.
Well, anyway, it is not much of a problem and maybe caused by my local installation...

Martin.

**Comment by Chris00** [comment]
Did you try with `emacs -Q` (loading mu4e “by hand”)?

**Comment by djcb** [comment]
Ah, so I guess running emacs _remotely_ may be a factor here. If you can reproduce with X too, we're looking for something that applies to both. Hmmm...

Did you already try some ssh-related changes, e.g.,
https://askubuntu.com/questions/144235/locale-variables-have-no-effect-in-remote-shell-perl-warning-setting-locale-f/144448#144448 ?

**Comment by djcb** [comment]
Looking at the first screenshot, it's also odd that _Köln_ is shown correctly, but the rest is not.

**Comment by djcb** [comment]
In any case, I don't know what mu/mu4e can do about this, it seems like some setup issue... so don't think I can you help your further here... sorry!
