### ISSUE TITLE
[mu4e bug] :list header entry not handled

### ISSUE THREAD

**Issue by alarsyo** [djcb/mu#2246]
**Describe the bug**

`mu4e-header-info` contains a `:list` entry that (I'm guessing) should show a mailing list id, as opposed to the `:mailing-list` entry that shows a simplified mailing list name through `mu4e-get-mailing-list-shortname`. However this entry isn't recognized anywhere, attempting to set `mu4e-headers-fields` or `mu4e-view-fields` to a list containing `:list` results in the following error being shown:

for `mu4e-headers-field`:
```
error in process filter: [mu4e] field :list not found
```

and for `mu4e-view-fields`:
```
error in process filter: [mu4e] Custom field :list not found
```

Additionally, attempting to call `(mu4e-message-at-point)` on a mailing list email shows a plist without the `:list` value anyway.

**To Reproduce**

Eval

```elisp
(setq mu4e-headers-fields '((:list . 10) (:mailing-list . 10) (:from-or-to . 25) (:subject)))
```

and try to open any mu4e headers buffer.

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

Emacs: 29.0.50
mu/mu4e: 1.6.10
OS: NixOS unstable

**Checklist**
- [ ] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

I'm using Doom emacs, I'll try and reproduce without it, but I believe this should be reproducible on a vanilla config: it looks like the `:list` option is never handled anywhere in the code, [for instance here](https://github.com/djcb/mu/blob/b686c9da25a77f5db1385748f3442d2a769ddcb4/mu4e/mu4e-view.el#L778-L795) it goes to the default case which looks for it in `mu4e-header-info-custom`.

**Comment by djcb** [comment]
This should be fixed with the latest; there's `:list` and `:list-post`... but not `:mailing-list`; e.g.,
```
(:size 10130
 :list-post ((:email "hostap@lists.infradead.org"))
 :date (25205 32416 0)
 :from  ((:name "Matt Harvey" :email "mharvey@miovision.com"))
 :list "hostap.lists.infradead.org" :message-id "CAD-X4u3mCn9UVqdTp8u138BcnavuPZkmPnMZxYH3iJ-rtg1MJg@mail.gmail.com"
 :priority low
 :subject "wpa_supplicant WPA-EAP hashed password over dbus"
 :to  ((:email "hostap@lists.infradead.org"))
 :path "/home/djcb/Maildir/bulk/cur/1651868059.142065_1.evergrey:2,S"
 :changed (25205 33201 0)
 :flags (seen list)
 :maildir "/bulk"
 :docid 86115
 :meta  (:path "0:z" :level 0 :date "n62757ea0" :date-tstamp (0 0 0)
		:root t :thread-subject t))
```

**Comment by alarsyo** [comment]
@djcb Thanks. I still think there's a problem [here](https://github.com/djcb/mu/blob/ca08443f0517778e15c57d4f60591d7253d3eb61/mu4e/mu4e-view.el#L780-L795), where only `:mailing-list` is recognized, not `:list`? Unless I've misunderstood something about the usage of `mu4e-view-fields`, I thought anything from `mu4e-header-info` could go there.

**Comment by djcb** [comment]
Okay, I see what you mean... there's another update that uses `:mailing-list` throughout.

**Comment by alarsyo** [comment]
Shouldn't `:list` be removed from `mu4e-header-info` [here](https://github.com/djcb/mu/blob/26f943957950fda5cbf3d47439ffe73c029683f6/mu4e/mu4e-vars.el#L249-L253) in that case? What I meant with my last comment was that using `:list` in `mu4e-view-fields` leads to an error right now.

Sorry if I'm not making myself clear :sweat_smile: and thanks for your work on mu!

**Comment by djcb** [comment]
Don't worry, it makes sense :). I'll update it.
