### ISSUE TITLE
[mu4e rfe] Improved treatment of received  attachments (specifically MS Outlook signature attachments)

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#2247]
Emails from MS Outlook often have attached images that are part of the signature. This is frustrating, because it is not a 'real' attachment, but mu4e flags it as one.

There should be support for these pseudo-attachments. Automatic removal would be nice, but at least not flagging the message as having an attachment, so that the `flag:attach` search remains useful and not polluted.

I currently remove them, manually, with,

```elisp
(defun remove-attachment (msg num) 
  "Remove attachment." 
  (let* ((attach (mu4e~view-get-attach msg num))
	 (path (mu4e-msg-field msg :path))
	 (filename (and attach (plist-get attach :name)))
	 (cmd (format "altermime --input=%s --remove='%s'"
		      path filename)))
    (when (and filename
	       (yes-or-no-p
		(format "Are you sure you want to remove '%s'?" filename)))
      (shell-command cmd)
      (message cmd)
      )))
(add-to-list 'mu4e-view-attachment-actions
	     '("remove-attachment" . remove-attachment))
```

But I wouldn't mind keeping-but-ignoring them. It appears these signature-images have `X-MS-Has-Attach: yes` in the header. But so do emails with 'normal' attachments. It appears (not certain) that real attachments have `Content-ID: <hex_values>` while sig-only attachments have `Content-ID: <image001.ext@hex_values>`. But that small string difference seems fragile. Is there some other way to flag these attachments and treat them differently so that searching still works?

**Comment by djcb** [comment]
Can you attach a minimal example message? 

Are you saying that  the `X-MS-Has-Attach: yes` is not a good indicator? We already use some heuristic based on the mime-type to decide if something is a "real" attachment, but perhaps it can be made smarter. But we'd need some rules for this. What does outlook do itself?

**Comment by djcb** [comment]
In particular (in `master`), look for a function called `looks_like_attachment`. If you have better heuristics, we could add them there.

**Comment by mankoff** [comment]
I am waiting for a colleague to mail me the same simple message 2x, once w/ and once w/o email sig, so that I can run a diff and collect the information you ask for above.

**Comment by mankoff** [comment]
I have two emails from my Org, one with and one without the signature. The only difference I note is 

+ with: `X-MS-Has-Attach: yes`
+ without: `X-MS-Has-Attach:`

When I search my Maildir with `grep` I see a lot of `X-MS-Has-Attach: yes`. But I cannot use `mu` to search for this header tag. Is there a way to do that? I would like to check this in more detail before we include a filter like this. It would be bad to not show an attachment when there really is one.

**Comment by djcb** [comment]
You can't _directly_ search for that field with the `mu` command-line tools, but you can of course use `grep` etc.

In general, we can never really trust such header-tags, since anyone can add them and use whatever value. So it's always going to be a heuristic.  So using `X-Ms-Has-Attach: <empty>` as a sign that there's no attachment? Perhaps...  Guess the reason they have that header is because it's hard to guess without it.

**Comment by mankoff** [comment]
Right. My test was incomplete. When an image is attached *not as a signature*, it still has `X-MS-Has-Attach: yes`. I'm not sure how to distinguish these signature-attachments :(.

**Comment by mankoff** [comment]
A heuristic for auto-removing or not-flag-as-attached might be to save a copy of the signature graphic, and then compare attachments against a list of saved images. This seems like a horrible hack.

**Comment by djcb** [comment]
In `master`, `mu` now honors `X-MS-Has-Attach`. Hope that helps!

**Comment by mankoff** [comment]
I'm unable to test this for the next week, but [per my comment here](https://github.com/djcb/mu/issues/2247#issuecomment-1121510873) the `X-MS-Has-Attach` is set to yes both for real attachments and signature attachments. 

I can't see what change you made associated with your comment immediately above this that caused closure, nor do I know what 'honors' means in this context.

**Comment by djcb** [comment]
Ah, I misread... so then `X-MS-Attach` is indeed not a good heuristic. I'll remove it - thanks.

**Comment by stefanv** [comment]
It looks like this solution no longer works with the current version of mu4e.

An [updated version](https://groups.google.com/g/mu-discuss/c/-4RznzpiMAA/m/EtU6VUvsBAAJ) was posted on the mailing list:

```lisp
  (defun bjm/mime-part-filename (num)
    "Filename of MIME part numbered num in gnus-article-mode."
    ;; Check whether the specified part exists.
    (when (> num (length gnus-article-mime-handle-alist))
      (error "No such part"))
    ;; Move point to MIME part
    (when (gnus-article-goto-part num)
      ;; Get handle for MIME part at point
      (let ((handle (get-text-property (point) 'gnus-data)))
        (when handle
          ;; Return file name of handle
          (mm-handle-filename handle)))))

  (defun bjm/mu4e-delete-attachment (num)
    "Remove email attachment from mu4e using altermime."
    (let* ((path (mu4e-message-field (mu4e-message-at-point) :path))
           (filename (bjm/mime-part-filename num))
           (cmd (format "altermime --input='%s' --remove='%s' --xheader='X-Attachment-Removed: %s'" path filename filename)))
      (when (and filename
                 (yes-or-no-p
                  (format "Remove '%s'?" filename)))
        (shell-command cmd)
        (mu4e-message cmd))))

  ;; get custom header field
  (defun bjm/mu4e-fetch-field (msg hdr)
    "Find the value for an arbitrary header field HDR from MSG."
    (with-temp-buffer
      (insert-file-contents (plist-get msg :path))
      (message-fetch-field hdr)))

  ;; display attachmment removed field
  (add-to-list 'mu4e-header-info-custom
               '(:xremoved . (:name "X-Attachment-Removed"
                              :shortname "XAR"
                              :help "Name of attachment removed"
                              :function (lambda (msg) (or (bjm/mu4e-fetch-field msg "X-Attachment-Removed") "")))))

  ;; display this header field in message view
  (add-to-list 'mu4e-view-fields :xremoved t)

  (add-to-list 'mu4e-view-mime-part-actions
             '(:name "delete-attachment"
               :handler bjm/mu4e-delete-attachment
               :receives index))
```
