### ISSUE TITLE
[mu bug] Fancy unicode characters not displayed correctly

### ISSUE THREAD

**Issue by theophilusx** [djcb/mu#2248]
**Describe the bug**

Just updated to the latest 1.7 version. In the header view, the fancy unicode characters used for flags and thread marks are not being displayed correctly i.e. 

> 05/05/22 \342\234             Fred Flintstone        \342\224\224 Re: Bowling

This was working with previous version. No changes to Emacs version, font, OS packages etc. 

Note that when I tried to cut and past an example message, this web interface interprets the threading character correctly. Seems Emacs is not seeing these strings as unicode charctgers but as just strings of '\' and digits. 

I did do a make clean, rm -rf build and removed the old mu4e installation before installing the new version. Did have to do a mu init to update to latest schema version. All seems OK at that level. 

**To Reproduce**

git pull
make clean
rm -rf build
meson build && ninja -C build
cd build
sudo meson install

emacs
M-x mu4e
<jump to inbox>

**Environment**
GNU Emacs 28.1.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2022-05-06

commit 26f943957950fda5cbf3d47439ffe73c029683f6 (HEAD -> master, origin/wip/message, origin/master, origin/HEAD)
Author: Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>
Date:   Fri May 6 22:53:52 2022 +0300

    build:bump version to 1.7.16 / 460

Ubuntu 22.04 (Mate). 

**Checklist**
- [ ] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by theophilusx** [comment]
This is looking like some sort of encoding problem with the mu4e-headers.el file, though I'm out of my depth here! I looked at the file in emacs and looked at the same file from a much older clone of mu4e I still have on my system. The two files have different coding systems and I'm at a loss as to know why. In the current HEAD, emacs reports 

```
= -- no-conversion (alias: binary)

Do no conversion.

When you visit a file with this coding, the file is read into a
unibyte buffer as is, thus each byte of a file is treated as a
character.
Type: raw-text (text with random binary characters)
EOL type: LF

```

but when I look at the same file from an older commit I see 

```
U -- utf-8-unix (alias: mule-utf-8-unix cp65001-unix)

UTF-8 (no signature (BOM))
Type: utf-8 (UTF-8: Emacs internal multibyte form)
EOL type: LF
This coding system encodes the following charsets:
  unicode

```

In the former file, the unicode characters used for flags and thread markers are displayed as escaped unicode numbers i.e. \xxx\xxx while in the later file, they are displayed as the unicode character those numbers define. 

So why is Emacs seeing the current version as a raw binary file and the older version as a utf-8 with unicode characters. 

I also noticed that if I try to do a grep on the current mu4e-headers.el file - for example, looking for new-marker, it reports "matches found in binary file". If I do the same grep on an older version of that file, it shows the matching lines. 

My LANG variable is set to en_AU.UTF-8 and I see the same with emacs -Q and my normal emacs. If I try to force a utf-8-unix encoding to save the file, emacs informs me it cannot because it cannot map some of the characters - namely the ones used for marks/threading.

**Comment by djcb** [comment]
Yeah, was using non-fancy chars, but I can reproduce. I think you're on to something... let me try to fix it.

**Comment by theophilusx** [comment]
Thanks. I feel bad logging this one given all the great work you have been putting into fixing up other issues, like honoring reply-to and mail list info, building on fedora 36 etc. Good news is, all those other issues appear to be resolved, so your hard work is paying off, but I bet it feels a little like wack-a-mole at times! 

As someone who also maintains a couple of open source projects, I can appreciate the time and effort it takes. I really like mu4e and very much appreciate all your hard work.

**Comment by djcb** [comment]
No worries, thanks for the report!

There's quite a bit of new stuff (I'll write a bit about that soon), so a few rough edges were expected; still I think I should have caught this one :)

Anyway, I've pushed a fix, it was indeed related tot the file encoding. That "noise" in the mode-line ("U" vs "=") is useful after all!

**Comment by theophilusx** [comment]
Just in case it was overlooked as you say you have pushed a fix, but mu4e-use-fancy-chars is still disabled in mu4e-headers-mode definition.

**Comment by djcb** [comment]
Thanks -- fixed now. Got a bit confused between magit and a children's birthday party :-)
