### ISSUE TITLE
Replying by Email to github issues seems broken

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#2249]
**Describe the bug**

I am not sure it is a mu4e bug or a github bug.

Replying by email to a github issue seems to have changed, before I was prompted to reply to all etc... now the email reply popup with no choice and the To: field is filled with "name <notifications@github.com>" and the reply is no more appearing on github.
Is it only me or you can reproduce?

**To Reproduce**

Reply to this bugreport by email and see if the reply show up here.

**Environment**

GNU/Linux emacs-28.1

**Checklist**
- [x ] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by thierryvolpiatto** [comment]
Just tried with Version 1.6.6 (1.6 branch) and indeed I am prompted to reply to all etc..., when I choose all, the To: field is filled with something like this:

"emacs-helm/helm <reply+AALWP44DYNYZWP6CX6AF4ZWAQPM25EVBNHHESPAY3Y@reply.github.com>"

instead of

"name <notifications@github.com>"

**Comment by theophilusx** [comment]
This has been fixed in the most recent github repo version. I'm using it
to reply right now!

Problem was, mu4e was not honoring the reply-to header.

**Comment by theophilusx** [comment]
I've just noticed that some of my replies have shown up and some have
not. I suspect there might also be a github issue at play here as well.
Looking tat the headers of both messages I sent, there is no difference
in the one which worked and the one which appears not to have worked.

**Comment by thierryvolpiatto** [comment]
Tim Cross ***@***.***> writes:

> This has been fixed in the most recent github repo version. I'm using it
> to reply right now!
>
> Problem was, mu4e was not honoring the reply-to header.

Thanks, looks it is working now, trying to reply now to test.

However with very last commit from master I have an error (unrealted to
this bugreport) when calling bookmarks (bu):

error in process filter: Wrong number of arguments: #<subr mapconcat>, 2

This is coming from `mu4e~headers-flags-str` which call mapconcat
without SEPARATOR arg.

    diff --git a/mu4e/mu4e-headers.el b/mu4e/mu4e-headers.el
    index 6341c20f..1c335771 100644
    --- a/mu4e/mu4e-headers.el
    +++ b/mu4e/mu4e-headers.el
    @@ -488,7 +488,9 @@ while our display may be different)."
     			     (format "mu4e-headers-%s-mark" (symbol-name flag))))
     		      (cell (symbol-value mark)))
     		(if mu4e-use-fancy-chars (cdr cell) (car cell))
    -	      ""))) flags) ""))
    +	      "")))
    +        flags "")
    +       ""))
     
     ;;; Special headers



-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Here the formatted version of the patch:

```diff
diff --git a/mu4e/mu4e-headers.el b/mu4e/mu4e-headers.el
index 6341c20f..1c335771 100644
--- a/mu4e/mu4e-headers.el
+++ b/mu4e/mu4e-headers.el
@@ -488,7 +488,9 @@ while our display may be different)."
 			     (format "mu4e-headers-%s-mark" (symbol-name flag))))
 		      (cell (symbol-value mark)))
 		(if mu4e-use-fancy-chars (cdr cell) (car cell))
-	      ""))) flags) ""))
+	      "")))
+        flags "")
+       ""))
 
 ;;; Special headers
```

**Comment by thierryvolpiatto** [comment]
@djcb Do you want a PR?

**Comment by djcb** [comment]
Ah, thanks, but no need: I committed the above ^^ under your name. Hope you don't mind!

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> Ah, thanks, but no need: I committed the above ^^ under your name.

Great, thanks.

> Hope you don't mind!

No problems ;-)

-- 
Thierry

**Comment by djcb** [comment]
Okay, then I consider this fixed, thanks all!
