### ISSUE TITLE
[mu4e bug] list-bookmarks doesn't work with bookmarks created in mu4e-headers/view-mode

### ISSUE THREAD

**Issue by ilupin** [djcb/mu#2255]
**Describe the bug**

`list-bookmarks` cannot show bookmarks created in mu4e-headers/view-mode

**To Reproduce**

1. `(require 'mu4e)` & `(require 'mu4e-contrib)`
2. open a message in mu4e and press `C-x r m` to create a bookmark
3. Press `C-x r l` to list bookmarks, and the following error occurs
  `tabulated-list-print-col: Wrong type argument: listp`

**Environment**

Emacs 28.1, mu 1.6.10

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Ah, some `mu4e-contrib` code and I don't think I ever used it!Might be interesting to get to work; I'll mark it as an RFE. 
For now, note that you can use org-mode links instead.

**Comment by djcb** [comment]
Re-implemented in `master`.
