### ISSUE TITLE
[mu4e bug] mu4e-compose-complete-max takes top random users

### ISSUE THREAD

**Issue by danielf-amobee** [djcb/mu#2259]
Recently, it was mentioned that contacts are not being ranked anymore. The variable `mu4e-compose-complete-max` is set to 2000 for performance reasons, but without ranking we get random results and missing users. 

I set mine to `nil` to remove the constraint but as a default behavior it's not doing what it's suppose to be doing. 

Thanks!

**Comment by djcb** [comment]
Especially with dev releases, please be very precise in what version you are using, and always check with the latest before reporting issues.

`mu4e-compose-complete-max` is set to `nil` by default, and you won't get "random" contacts if set to some other value.

**Comment by danielf-amobee** [comment]
Oops, this was fixed 3 days ago. Thanks anyway!
