### ISSUE TITLE
[mu bug] Flags are appended to filenames in the wrong way

### ISSUE THREAD

**Issue by andersjohansson** [djcb/mu#2268]
**Describe the bug**
In a recent build from master (built today):
When moving messages or adding flags (mainly just when viewing), the flags are added to the maildir filenames in the wrong way, with multiple colons appended.
For example, I have these files in my inbox cur Maildir:
```
1653988152_2.47233.ajla,U=13251,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,:2,S
1653889235_0.37995.ajla,U=13209,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,:::2:2::2,S
```
which should be:
```
1653988152_2.47233.ajla,U=13251,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
1653889235_0.37995.ajla,U=13209,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
```

Both mu and offlineimap have trouble parsing this, leading to messages that being labeled unread that are actually read.

**To Reproduce**
This happens both in mu4e and when using "mu server".
Starting with this mail in my maildir:
```
1653988152_2.47233.ajla,U=13251,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
```
Starting `mu server` and executing:
```
mu> (move :msgid "0838A757-267F-41AF-82DB-37AF4DCC550E@chalmers.se" :flags "S")
[26f](:update (:size 3740 :date (25237 55343 0) :from REDACTED  :message-id "0838A757-267F-41AF-82DB-37AF4DCC550E@chalmers.se" :priority normal :references ("b6964ffa-2054-fe3f-d60f-c9ff84686944@chalmers.se") :subject REDACTED :to REDACTED) :path "/home/aj/Maildir/chalmers/INBOX/cur/1653988152_2.47233.ajla,U=13251,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,:2,S" :changed (25237 58572 0) :flags (seen) :maildir "/chalmers/INBOX" :docid 9121) :maybe-view t)

```
I get (as seen in the response from the server above, and in the file system):
```
1653988152_2.47233.ajla,U=13251,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,:2,S
```

**Environment**
Arch linux, Emacs built from master (commit 1a6def02cd1), mu built from master (commit ce1fea63, with some minor changes to mu4e on top).

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by andersjohansson** [comment]
By the way, I started noticing this happening with recent builds from a few weeks ago, where I reckon some large changes were made to the server code.

**Comment by andersjohansson** [comment]
I guess this may have to do with the changes in 9f062ae, but I cant wrap my head around how that works.

**Comment by djcb** [comment]
Oh, that's ugly! I'll take a look.

**Comment by djcb** [comment]
Ah, great, thanks for checking! I'll add a script to fix up some of the older mishaps.
