### ISSUE TITLE
[mu4e rfe] Bounce message to someone else

### ISSUE THREAD

**Issue by P-EB** [djcb/mu#2269]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to do what one can do with mutt/neomutt with "b" (bounce). It's a bit like the `mu4e-compose-resend`, the main difference is that I'd rather not alter the message at all, which is what mutt does. With `mu4e-compose-resend` I need to change the To: header which alters the message.

**Describe the solution you'd like**
bounce as in mutt/neomutt.

**Comment by P-EB** [comment]
@djcb do you have an opinion on this feature? :)

I can understand if you don't have the time to work on it, but your input on the relevance of it would be appreciated.

**Comment by djcb** [comment]
Ah, it sounds useful; my plan is to change the message composition so that it's reusing the "gnus" machinery for that, rather than having mu4e doing it. When that's in place, we can reuse the existing functionality for bouncing.

I have some code, but it will take a while!

**Comment by genegoykhman** [comment]
While @djcb is working on a more comprehensive solution, I've come up with a small implementation of my own `mu4e-compose-resend` that preserves the original message as closely as possible, including in-line attachments.

https://gist.github.com/genegoykhman/482a6d0b05ee5abe7327dc7d4042133d

I also noticed that both my and the default `mu4e-compose-resend` did something unusual with window splits after the message is sent, so I have a crude workaround for that too.

https://gist.github.com/genegoykhman/af213bdf94b276496f02b965ec62e223

**Comment by djcb** [comment]
Thanks @genegoykhman!

In the meantime, behold, the _new_ `mu4e-compose-resend` (`master`) re-uses Gnus' code for doing the same, and it behaves like `mutt` (as far as I can remember, at least!). So closing this.

**Comment by P-EB** [comment]
Thanks, I'll give it a try as soon as it lands in my environment! :D
