### ISSUE TITLE
[mu4e rfe] Propagate read mark to duplicate messages

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#2277]
I've set `mu4e-headers-skip-duplicates` to `t` so when someone replies to a mail of mine on a mailinglist with the list in the To and a Cc to myself, I'll just see one of those mails in my unread bookmark headers view.

(BTW, is there a way to influence which mail is suppressed?  One mail will reside in my INBOX maildir and the other in some mailinglists/whatever maildir.  I'd prefer to see the one in my inbox which seems to be the case but might as well be pure luck and obviously others might prefer it the other way round.)

Anyway: while this feature is nice in general, it has the problem that when I read the mail, its duplicate(s) won't be marked as read.  So the following situation happens quite often to me:

1. I see I have 2 unread mails.
2. I enter the unread bookmark and get presented just one mail which I read.
3. I exit the headers view and see that I have 1 unread mail.
4. I enter the unread bookmark and get presented the basically same mail, i.e., the duplicate of the one I've read in step 2.

**I'd very much like the read mark to be propagated to all duplicates of the marked mail.**

And to make that clear, I only want the read mark propagated, not flagging, moving, deletion, etc.

I've already brought up this topic on the mu-discuss list on June, 3rd in the message `<878rqerxkh.fsf@gnu.org>` where at least Yuri confirmed that the current behavior is inconvenient and read-marking should propagate to all duplicates.

**Comment by djcb** [comment]
Makes sense, yeah.

**Comment by tsdh** [comment]
Seems to work fine.  Thanks a lot, Dirk!
