### ISSUE TITLE
[mu bug] regression: `format=links` doesn't create any symlinks at all since 1.8

### ISSUE THREAD

**Issue by freswa** [djcb/mu#2279]
## Expected or desired behavior

`mu find --clearlinks --format=links --linksdir=~/.mail/search test` creates links to search results in the mentioned directory.

## Actual behavior

The directory stays empty (besides maildir folders).

## Steps to reproduce

Issue a simple search to check if it finds something.
`mu find test`
Then try to create symlinks for them.
`mu find --clearlinks --format=links --linksdir=~/.mail/search test`

## Versions of mu, mu4e/emacs, operating system etc.
ArchLinux
mu 1.8

**Comment by djcb** [comment]
Oh, that's not good. I'll take a look.

**Comment by freswa** [comment]
Do you have an idea what commit is the culprit? Otherwise I would start a bisect :)

**Comment by djcb** [comment]
Ah, was just something silly, apparently this is not used much.

Fixed in 1.8.2.
