### ISSUE TITLE
[misc] Inconsistency between the texinfo and the online documentation regarding the mu4e-org-link-query-in-headers-mode variable

### ISSUE THREAD

**Issue by dariuskramer** [djcb/mu#2280]
The online documentation use the `org-mu4e-link-query-in-headers-mode` variable:
- https://www.djcbsoftware.nl/code/mu/mu4e/Org_002dmode-links.html
- https://www.djcbsoftware.nl/code/mu/mu4e/Creating-org_002dmode-links.html

But the texinfo documentation use the `mu4e-org-link-query-in-headers-mode`.

**Comment by djcb** [comment]
The online documentation was rather _old_, which explains. I have now updated it.
