### ISSUE TITLE
[mu bug] Search by 'username' part of email address no longer works, regression

### ISSUE THREAD

**Issue by markk** [djcb/mu#2281]
**Describe the bug**

Prior to version 1.8 a search for the portion of an email address before @ returned results, this no longer works.

**To Reproduce**

```
$ mu find f:username@domain.com | wc -l
7826
$ mu find f:username | wc -l
no matches for search expression
0
```

With earlier 1.7 versions, the second query would return (roughly) the same results as the first.

**Environment**

Fedora 35, Emacs 27.2, mu 1.8.1

**Comment by djcb** [comment]
I've re-added email component searching; available in 1.8.2.
