### ISSUE TITLE
[mu4e bug] 1.8.2 site-lisp now in `mu4e` instead of `mu/mu4e`

### ISSUE THREAD

**Issue by wnka** [djcb/mu#2287]
**Describe the bug**
With the new build system, `mu4e` gets installed in `emacs/site-lisp/mu4e` instead of `emacs/site-lisp/mu/mu4e`

**To Reproduce**
```
mkdir build
meson ..
ninja -v
ninja install -v
```

**Environment**
macOS 12.4
Emacs 28.1

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by wnka** [comment]
actually, I guess the question is how do you specify a custom `site-lisp` directory?

**Comment by eli-schwartz** [comment]
--with-lispdir comes from an automake builtin macro. In the new build system it is simply: https://github.com/djcb/mu/blob/98b0353c004e7f8c5325042679f7915a52005de7/mu4e/meson.build#L17-L18

So this is not currently configurable, though an option could be added in meson_options.txt for it.

There's also for example https://github.com/djcb/mu/blob/06891488d178b49a88b1786e40d3e3063256621c/mu4e/mu4e.texi#L359-L360 which indicates it is currently using the default without any specific handling of customizations.

**Comment by djcb** [comment]
Indeed, there's no `site-lisp` anymore.  Not sure why the default location isn't sufficient?

**Comment by wnka** [comment]
I'm trying to update the version of `mu` in the Homebrew package manager. They prefer having `site-lisp` be under the name of the package, so for package `mu` it would be `emacs/site-lisp/mu/mu4e`. In 1.6 they passed in `--with-lispdir` to create that, now there's some moving of files that has to happen post install that's a little weird. It would be better to just pass in the desired dir.

I created the pull request to update to `1.8.2` which is [here](https://github.com/Homebrew/homebrew-core/pull/104851) and has some context. I don't think it's a blocking issue, but this is my first time updating Homebrew so not sure. Just wanted to get the new `mu` on my Mac!

**Comment by djcb** [comment]
I've pushed a `lispdir` option now which should help for this; it'll appear in 1.8.4.

**Comment by wnka** [comment]
thank you!
