### ISSUE TITLE
[mu4e bug] build error

### ISSUE THREAD

**Issue by phenix-factory** [djcb/mu#2288]
**Describe the bug**
I got this error when using make:
```
Found ninja-1.10.0 at /usr/bin/ninja
*** Now run 'ninja -C build' to build mu                                                            
*** Or check the Makefile for some useful targets
ninja -C /home/phenix/Téléchargements/mu-1.8.3/build 
ninja: Entering directory `/home/phenix/Téléchargements/mu-1.8.3/build'
[1/1] Generating mu4e_info with a custom command.
FAILED: mu4e/mu4e.info 
/usr/bin/makeinfo -o '/home/phenix/Téléchargements/mu-1.8.3/build/mu4e/mu4e.info' '/home/phenix/Téléchargements/mu-1.8.3/mu4e/mu4e.texi' -I '/home/phenix/Téléchargements/mu-1.8.3/build/mu4e/..'
/home/phenix/Téléchargements/mu-1.8.3/mu4e/mu4e.texi:4568: @include: could not find fdl.texi
ninja: build stopped: subcommand failed.
make: *** [Makefile:42 : all] Erreur 1
```

**To Reproduce**
I just compile 1.8.3

**Environment**
linux mint 20.3

**Comment by phenix-factory** [comment]
All right it look like an issue with the "Téléchargements" folder. The path doesn't like that I use "é".
It compile when I change the folder. Still a bit annoying since it's the default on Linux Mint french.

**Comment by djcb** [comment]
Ugh, that's ugly. It seems to be something in the makeinfo/texinfo programs, i.e., see https://github.com/riscv-collab/riscv-gnu-toolchain/issues/673

**Comment by djcb** [comment]
Well, for you it may be trivial, but it may be hard to find for someone else!

Anyway, I've notified the texinfo maintainers, hopefully something can be done... closing this here.

**Comment by djcb** [comment]
The texinfo folks tell me this should be fixed in the development release.
