### ISSUE TITLE
[mu4e rfe] tnef support

### ISSUE THREAD

**Issue by wwlytton** [djcb/mu#2289]
**Is your feature request related to a problem? Please describe.**
I can't open attachments sent to me via microsoft tnef (application/ms-tnef; winmail.dat]...)

**Describe the solution you'd like**
detach attachments; in some cases main email text is there in some cases hidden so would like to read

**Describe alternatives you've considered**
`tnef` app in linux can be used

**Additional context**

**Comment by djcb** [comment]
Does the `tnef` program work for your attachments? If so, you should be be able to use it from mu4e as well.
