### ISSUE TITLE
[mu4e bug] 'b' key is not bound in the initial mu4e menu

### ISSUE THREAD

**Issue by jeromebrunet** [djcb/mu#2296]
**Describe the bug**

Cannot get to bookmarks from the initial menu.
The b is not bound

**How to Reproduce**

* Fire up emacs
* `M-x mu4e`
It shows the shortcut menu int the minibuffer, including `[b]ookmarks`
* hit `b`
=>  `[mu4e] key b not bound to a command`

This only fails from the minibuffer menu.
Hitting b from `*mu4e-headers*` works, so does `M-x mu4e-search-bookmark`

I have limited lisp knowledge but I see that
```
    (define-key map "b" 'mu4e-headers-search-bookmark)
```
is no longer in the `mu4e-main-mode-map`. 
Maybe it is an issue with this change: https://github.com/djcb/mu/commit/3cd127d8ae9214f20375ecdca6c2622b033f3eb8

**Environment**

* Debian unstable
* emacs 27.1
* mu4e 1.8.3-1 (packaged by debian)

**Checklist**
- [x] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [x] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [x] you have read all of the above

**Comment by jeromebrunet** [comment]
The same thing happens with search, `s` key

**Comment by djcb** [comment]
Not quite sure what you mean by "menubar menu".. can you add the exact keystrokes you're using? Thanks.

**Comment by rougier** [comment]
I get the same behavior. Starting mu4e (using `M-x mu4e`), I got a minibuffer message (I forgot the option to have this instead of the regular buffer) and when I hit `b` (bookmark) or `;` (switch context), it failed.  I think the line:

```
(let ((mu4e-command (lookup-key mu4e-main-mode-map (string key) t)))
```

in `mu4e-main.el` failed at finding the key since it not bound in `mu4e-main-mode-map`

**Comment by jeromebrunet** [comment]
> Not quite sure what you mean by "menubar menu".. can you add the exact keystrokes you're using? Thanks.
Sorry I meant the menu which appears in the minibuffer after `M-x mu4e`
I believe it comes from this: https://github.com/djcb/mu/blob/master/mu4e/mu4e-main.el#L405

https://github.com/djcb/mu/blob/master/mu4e/mu4e-main.el#L90 no longer has map for `b` or `s`  but maybe I'm missing something

**Comment by jeromebrunet** [comment]
> I got a minibuffer message (I forgot the option to have this instead of the regular buffer)

Ah same here - I remember adding an option to get the minibuffer instead of the full regular buffer. Can remember want it was either :smile:

**Comment by rougier** [comment]
@jeromebrunet Thanks, I've been searching how did I end up with the minibuffer menu (quite convenient)

**Comment by djcb** [comment]
Ah, right... had all forgotten about that one --  don't think I ever used it!
Anyway, I've updated it and push a fix to the release branch; to be include in 1.8.6.

**Comment by jeromebrunet** [comment]
> Ah, right... had all forgotten about that one -- don't think I ever used it! 
:smile: no worries.
I like this mode a lot

> Anyway, I've updated it and push a fix to the release branch; to be include in 1.8.6.
Thx ! I'll revert to classic view until this sinks in Debian unstable. Thanks for fixing this so quickly !
