### ISSUE TITLE
[mu4e bug] completions don't work with eudc

### ISSUE THREAD

**Issue by chinmayanagpal** [djcb/mu#2297]
**Describe the bug**

mu4e completions break when `~/.emacs.d/eudc-options.el` is present.
I am trying to make completions source from both the mu index and from a local LDAP server. 

**How to Reproduce**

1. make file `~/.emacs.d/eudc-options.el` with the following content:

```
(provide 'eudc-options-file)
(eudc-set-server "ldap://localhost:1389" 'ldap t)
(setq eudc-server-hotlist '(("ldap://localhost:1389" . ldap)))
```

2. Compose message in mu4e, and attempt to complete address in `To:` header. 

Only an LDAP query is performed, and the echo area says `Parsing results... done`. 
No mu4e completion is performed. 

**Environment**
Emacs 29 (from [AUR](https://aur.archlinux.org/packages/emacs-pgtk-native-comp-git)) on GNU/Linux. mu also from AUR (version 1.8.2).

**Comment by djcb** [comment]
If you replace mu4e's completion by something else then obviously mu4e's completion won't work anymore, that's not a bug I think :-)

If you want to combine both, you probably need to write something clever, but that's  bit outside mu4e's purview.... still if there's something specific you need from mu4e, feel free to open an RFE ticket.

**Comment by chinmayanagpal** [comment]
> 

The thing is, I haven't changed any options--so even if I don't want to combine mu4e's completion with anything else, if I am trying to use eudc to make ldap queries elsewhere and have placed this file in my init directory, mu4e's completion breaks.

**Comment by chinmayanagpal** [comment]
fixed by adding the following:
```
(add-hook 'mu4e-compose-mode-hook (lambda () (remove-hook 'completion-at-point-functions #'eudc-capf-complete t)))
```
to .emacs, but since this resumes expected behaviour, I think it is a bug @djcb.

**Comment by djcb** [comment]
mu4e cannot really control what people put in the completions functions.... _but_ seems it should work as expected then, and consult mu4e's completions when eudc-capf-complete fails? At least I think that is how it's supposed to work.

**Comment by chinmayanagpal** [comment]
I suppose so, if the behaviour that you want is for eudc-capf-complete to be preferred over mu4e's completion function by default.
