### ISSUE TITLE
[mu4e bug] Error message `mail_accountA/Archives/ is not a valid maildir` when refiling.

### ISSUE THREAD

**Issue by m-ar-c** [djcb/mu#2298]
I use [smart refiling](https://www.djcbsoftware.nl/code/mu/mu4e/Smart-refiling.html) to archive my messages. Since some time (after an update ?) I get the following error when I try to refile some messages :

`error in process filter: mu4e-error: [mu4e] Error 32818: '/mail_accountA/Archives/' is not a valid maildir`

The folder seems a valid maildir to me and the message is correctly moved to it anyway (at least each time I did check).

So far It happens only on `/mail_accountA/Archives/` folders, not on `/mail_accountA/Archives/subfolder` folders.

It happens on most accounts (it does not on one account) and on most messages.

Here is my smart refiling setup (I changed accounts names and emails for privacy reasons) :
``` lisp
  (setq mu4e-refile-folder
        (lambda (msg)
          (cond
           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountA/Archives/MMA")
           ((mu4e-message-contact-field-matches msg :cc "mail@mail.com")
            "/accountA/Archives/MMA")

           ((mu4e-message-contact-field-matches msg :cc "mail@mail.com")
            "/accountB/Archives/Politique")
           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountB/Archives/Politique")
           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountB/Archives/Politique")

           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountC/Archives/Autre")

           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountC/Archives/Lautre_net")
           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountC/Archives/Lautre_net")
           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountC/Archives/Lautre_net")

           ((mu4e-message-contact-field-matches msg :cc "mail@mail.com")
            "/accountD/Archives")
           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountD/Archives")
           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountD/Archives")
           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountD/Archives")
           ((mu4e-message-contact-field-matches msg :from "mail@mail.com")
            "/accountD/Archives")
           ((mu4e-message-contact-field-matches msg :from "mail@mail.com")
            "/accountD/Archives")

           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountA/Archives/")
           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountB/Archives/Autre")

           ((mu4e-message-contact-field-matches msg :to "mail@mail.com")
            "/accountE/Archives/")

           ((mu4e-message-contact-field-matches msg :to ".*@mail.com")
            "/accountE/Archives/")

           ((find-if
             (lambda (addr)
               (mu4e-message-contact-field-matches msg :from addr))
             (mu4e-personal-addresses))
            mu4e-sent-folder)

           (t  "/accountB/Archives/Autre"))))
```

What can I do to further investigate ?

> Debian sid
> GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0) of 2021-11-27, modified by Debian
> mu (mail indexer/searcher) version 1.8.1
> mu4e - mu for emacs version 1.8.1

**Comment by djcb** [comment]
Remove the final `/`.

I.e., `/accountE/Archives/` means `<empty>` under `Archives` under `account`, and maldirs must have a non-empty name.

**Comment by m-ar-c** [comment]
Indeed, no more error message now, thanks!

But then I wonder why the emails were moved correctly regardless. What is the point of an error message if things works anyway as expected :) ?

**Comment by djcb** [comment]
Yeah, the error is in the "update maildir name" _after_ the "move file" part. So, the name won't be properly updated (but later indexing will probably correct that). Probably could add another check.
