### ISSUE TITLE
[mu4e bug] `mu4e-headers-view-message` opens "some" message on a search with no results

### ISSUE THREAD

**Issue by gusbrs** [djcb/mu#2299]
**Describe the bug**

Currently, a call to `mu4e-message-at-point` made at the last line of a search reading "End of search results" or, in case of an empty query "No matching messages found" does not warn of "No message at point", but rather returns some message, which I think is the last message to have been opened.

As a result, `mu4e-headers-view-message` on a search with no results will open the message returned by `mu4e-message-at-point`, when it shouldn't.

**How to Reproduce**

Start with `emacs -Q`, do some setup:

```lisp
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")
(require 'mu4e)
(setq mu4e-mu-home "/path/to/muhome")
(setq mu4e-sent-folder "/path/to/sent")
(setq mu4e-drafts-folder "/path/to/draft")
(setq mu4e-trash-folder "/path/to/trash")
```
Call `M-x mu4e`. Go to some query with no results, in my case "unread" with `b u`. Call `mu4e-headers-view-message` with `RET` on the line "No matching messages found". The result is the expected warning "[mu4e] No message at point". Now go to some search with results, in my case the week messages with `b w`. Open one of these messages. Now go again to the unread empty search with `b u`. Call again `mu4e-headers-view-message` with `RET` on the line "No matching messages found". Now, instead of a warning, the message you had opened (I think it is the last one you had opened), will open instead of the due warning of no message at point.

`M-: RET (mu4e-message-at-point) RET` will indeed return that message instead of erroring with the warning.

**Environment**

Linux Mint 20.3 Cinnamon, Emacs: GNU Emacs 28.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-04-04, mu/mu4e: 1.8.6, built and installed from the latest released tarball.

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [X] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [X] you have read all of the above

PS: I'm using the latest release 1.8.6 and it's great. Speed is indeed much improved. And also the `mu` process running in the background smooths things out. No more clashes with weird error messages when I try to open `mu4e` and some `mu` process happened to be running. This is off-topic in this report, of course. I'm just saying: Thank you very much! :-)

**Comment by djcb** [comment]
Yeah, an old issue... finally fixed.

**Comment by gusbrs** [comment]
Hi @djcb , thank you!
