### ISSUE TITLE
[mu4e bug] Some mail does not move to archive with Outlook

### ISSUE THREAD

**Issue by GregorySchwartz** [djcb/mu#2300]
**Describe the bug**

I attempt to move a collection of emails to the archive folder, but there are some emails and threads which refuse to move. I noticed, using the mu4e log, that it will "move" the email `(move :docid $NUM :msgid nil :flags "-N" :maildir "$MAIL/Archive" :rename nil :no-view nil)`, but then DavMail will immediately read it back I think `(:update (:docid etc...`. Does this mean that it was never moved or that it didn't move on the server? Again, many emails are moved, but many are not, no matter how many times I try.

**How to Reproduce**

Move cursor over mail, mark with `m a` then execute with `x y`

**Environment**
Emacs 28.1
mu 1.6.10

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [X] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [X] you have read all of the above

**Comment by djcb** [comment]
There are a lot of programs involved here, making it hard to see what's going on.

Best start with the basics -- just mu/mu4e and without any syncing/davmail/outlook involved. Verify that this works as expected. If not, report here :), then, try with davmail and see what's different.

**Comment by djcb** [comment]
This has gone a little stale, closing this. Feel free to reopen / file a new ticket if you can provide the requested info. Basically, turn off davmail/... and file an issue if `mu`/`mu4e` is not doing what's expected.
