### ISSUE TITLE
[mu4e bug] mu4e-view-mode-map having error message

### ISSUE THREAD

**Issue by thyeun** [djcb/mu#2301]
**Describe the bug**
```Getting an error message on mu4e-view-mode-map, after manually upgrade spacemacs packages. ```

Please provide a clear and concise description of what you expected to happen
and what actually happened.
```Before manually upgrade spacemacs packages, the error never pop-up```

**How to Reproduce**
```Manually upgrade spacemacs packages```

Include the exact steps of what you were doing (commands executed etc.). Include
any relevant logs and outputs.
![2022-07-17T17:42:28,952803796+08:00](https://user-images.githubusercontent.com/1939446/179394019-0b688ea1-1df0-44c6-8204-1118e6a1ef9b.png)

If this is about a specific (kind of) message, attach an example message. (Open
the message, press `.` (`mu4e-view-raw-message`), then `C-x C-w` and attach.
Anonymize as needed, all that matters is that the issue still reproduces.

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.
OS : Arch linux 5.18.12-arch1-1
Emacs : 28.1
Spacemacs : 0.999.0
Mu4e : 1.8.6

**Checklist**
- [ X ] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [ ] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [ ] you have read all of the above

**Comment by djcb** [comment]
In general, please don't file bugs that are spacemacs etc. specific.

Anyhow, I've added a change that should hopefully avoid it (in 1.8.7 when it's released).  Until then, you can put a `(require 'mu4e-view)` in the start of the `:config` section for mu4e (wherever spacemacs does that).

**Comment by thyeun** [comment]
@djcb in general, pls make a clear description for each of the ```new issue ``` format, because i didn see any general report to be open, and the so call ```misc``` description is ```share```, and i'm not sharing anything also.

secondly, error message pop up should be consider as a bug???

**Comment by djcb** [comment]
Not quite sure what you mean -- but the `mu4e bug` description has something like:
```
- [ ] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
```
so in this case spacemacs would be an extension. Want to be helpful, but really don't have time to try all special setups that people have. Anyway, hopefully in this case I guessed correctly.

Error message pop is a bug; but not necessarily in mu4e; it could be in another package or user's setup as well. In case, you can check if my change helped.

**Comment by thyeun** [comment]
@djcb Really not sure what mean also, but in this case, are you consider this as a bug or not??
