### ISSUE TITLE
[mu bug] Get error messages when mark message to read.

### ISSUE THREAD

**Issue by zw963** [djcb/mu#2303]
**Describe the bug**
I have  many unread message in my Maildir.

I want mark all don't care message as read, following is my process:

1. pressing `s` in mu4e
2. Set filter in minibuffer.(filter to show only unread messages with others condition)
3. search result. 
4. pressing `W` disable show threads
5. run `(mu4e-headers-flag-all-read)`, mark all result as read.
6. pressing `g` to rerun this.
7. repeat step 5, 6

After i repeat several times, special, when current mixin with read + unread, always get error like this:

error in process filter: [mu4e] Error 32818: '' is not a valid maildir
error in process filter: mu4e-error: [mu4e] Error 32814: target maildir must be empty or start with / ()
error in process filter: [mu4e] Error 32814: target maildir must be empty or start with / ()
error in process filter: mu4e-error: [mu4e] Error 32818: '' is not a valid maildir
error in process filter: [mu4e] Error 32818: '' is not a valid maildir
error in process filter: mu4e-error: [mu4e] Error 32814: target maildir must be empty or start with / ()
error in process filter: [mu4e] Error 32814: target maildir must be empty or start with / ()

Even, it will broken my mu index, which cause following error:

```
 ╰─ $ mu index
error: Expected block 48951 to be level 2, not 0
```

But, those issue i remember not happen when i use 1.6.X (at least, seledom happen)

i have to init and reindex all messages. (0.2 million)

The really big issue is,  when error happening, all error message will output to minibuffer continously, which cause for a long time, any mu query command failed, i have to wait for several minutes for all error is output done, then i can continue the above process, but same error happen again quickly.

**Environment**
Arch, mu + mu4e 1.8.6

**Comment by djcb** [comment]
Hmm, I'm unable to reproduce this.

**Comment by djcb** [comment]
Does this still happen with 1.10.x?

**Comment by zw963** [comment]
I use 1.8.9 for a while, though, check email frequency not high anyway.

never found this issue again.

I doubt this issue only happen when work with offlineimap, but i switch to use getmail.timer systemd service for a while, this is a single method email retriever.

I compiled a 1.10.0 just now, and do a quick test, it seem like works, thanks very much!

**Comment by djcb** [comment]
Great - thanks!

**Comment by zw963** [comment]
> Great - thanks!


Hi, @djcb , i get new error message when update to 1.10.0, please check following screenshot.

![image](https://user-images.githubusercontent.com/549126/231181785-70d36af2-c886-424f-9f53-b82d3c05ae8d.png)

It will keep happen when mark as read for some special message, that is, if this error raise on one message, it keeping error.

It happen several times when i try to use 1.10.0 several days ago.

BTW: this error never happen when use old 1.8.9.

Thanks

**Comment by zw963** [comment]
Hi, i update to newest master (b41955b), but this issue not happen for now, i will give feedback when i meet it.

Thanks
