### ISSUE TITLE
mu4e fails to recognize any calendar invitations

### ISSUE THREAD

**Issue by averter** [djcb/mu#2305]
## Expected or desired behavior
mu4e correctly displaying calendar invitations and showing the corresponding buttons (accept, decline, etc). This used to work until I have recently changed email accounts +  moved to version 1.8.x.

## Actual behavior

Similarly to issue #1660 Calendar Invitations in vcal format are shown as regular attachments. This happens always. 

## Steps to reproduce

This is the relevant part of my mu4e configuration

```` lisp
;; Use gnus article view
(setq mu4e-view-use-gnus t)
(require 'mu4e-icalendar)
(mu4e-icalendar-setup)

(require 'org-agenda)
(setq gnus-icalendar-org-capture-file "~/org/NOTES.org")
(setq gnus-icalendar-org-capture-headline '("Calendar"))
(gnus-icalendar-org-setup)

````
## Versions of mu, mu4e/emacs, operating system etc.

I am using mu4e 1.8.6 and emacs 27.1. 

## Any other detail

I am using the gnus-based message view and have tried all the solutions suggested in #1660 .

**Comment by djcb** [comment]
@Chris00, any idea?

(Note, `mu4e-view-use-gnus` is long gone, no need to set it.)

**Comment by Chris00** [comment]
An example of message exhibiting the problem (an attached file, bit a copy/paste) would be good.  In the past, as I remember it, the problem was that messages were retrieved with Thunderbird which was adding `^M` at the end of lines.

**Comment by averter** [comment]
> An example of message exhibiting the problem (an attached file, bit a copy/paste) would be good.

Thanks for the quick reply. I've created a gist of an edited email available [here](https://gist.github.com/averter/e0d98f740c53cac3e85842b522978167)

The message might look a bit weird/distorted, since it has been sent to my work email and then I've used a thunderbird filter to automatically move it to my protonmail account.

**Comment by Chris00** [comment]
Your attachment is declared with the type
```
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=calendar.ics
Content-Type: text/calendar; name=calendar.ics
X-Pm-Content-Encryption: on-import
```
It is not a request to know whether you are attending or not, contrarily to the following *calendar invitation*
```
Content-Type: text/calendar; charset="utf-8"; method=REQUEST
Content-Transfer-Encoding: base64
```
Importing such a file into Emacs calendar would be nice but this is an additional effort w.r.t. the current implementation (which heavily uses what Gnus provides).  I do not have time for that right now — maybe after the 16th of August.

**Comment by averter** [comment]
I am already able to import the ical file using ical2org, and I am happy to share my setup if anyone is interested :-). 
Regarding the strange format, when opening these emails using Thunderbird I am prompted to press the accept/decline buttons, and I am clearly in the attendees list. What is it then that changes the method of invitation from `REQUEST` to the other "spurious" one? I have tried creating invitations, both using Teams and Thunderbird, and inside mu4e the buttons never show up, although as mentioned everything seems normal when using Thunderbird. This used to work before so I am really confused O_O.

**Comment by Chris00** [comment]
You are right, I just added `; method=REQUEST` and the buttons do not show up.  I'll try to investigate that (but I likely will have no time before August 16, sorry); it may well require to (re)investigate how Gnus triggers the buttons (it probably doesn't either in your situation).

**Comment by averter** [comment]
That is absolutely fine and thank you very much. I have been learning elisp lately, so I will also do some separate/minor investigations of my own on how Gnus handles the buttons. Cheers.

**Comment by kthu** [comment]
Possibly not the same issue, but I too have experienced problems with ical invitations (mostly from ms teams) misbehaving after recently upgrading to mu 1.8.  The problem I am seeing is that the `To:` field in the generated reply emails are no longer pre-populated, requiring me to manually fill it in every time.

The other functionality seems to work as before - The action buttons still show up in the invitations, a reply mail is still composed, and events are still added to my org calendar.

This is using Spacemacs/Emacs 28.1, mu 1.8.6, and the same mu/gnus config lines listed in this issue.

**Comment by averter** [comment]
Possibly related [issue](https://github.com/nextcloud/server/issues/21189) on nextcloud...
