### ISSUE TITLE
[mu4e rfe] Enable users to add more completion-at-point functions to `mu4e-search-read-query`

### ISSUE THREAD

**Issue by meliache** [djcb/mu#2307]
**Is your feature request related to a problem? Please describe.**
I'm using the [`mu4e-query-fragments`](https://gitlab.com/wavexx/mu4e-query-fragments.el) which allows me to define fragments like `%software` which I can use in `mu4e-search-read-query`. However, there's no completion for those fragments, so I decided to try to write my own completion-at-point function ("capf") for that. That itself was easy, but I couldn't find an easy way to add this completion function, because `mu4e-search-read-query` is overriding `completion-at-point-functions` locally via

``` emacs-lisp
	(setq-local completion-at-point-functions
		    #'mu4e--search-query-completion-at-point)
```

So to add further completion-at-point functions, the user needs to either override `mu4e--search-query-completion-at-point`, which is a private function, or needs to redefine `mu4e-search-read-query`, which is what I did.

**Describe the solution you'd like**

I'd prefer a customizable public hook of capfs that the user can add functions to via `add-hook`, e.g.

``` emacs-lisp
  (defcustom mu4e-search-query-capfs nil
    "Completion-at-point functions for mu4e search queries."
    :group 'mu4e
    :type 'hook)
    
  ;; we initialize the hook to `nil' and then add the default value via
  ;; `add-hook' instead of initializing it with the default value so that when
  ;; the user adds his own capfs via `add-hook' before the package is
  ;; loaded, the default is not overridden
  (add-hook 'mu4e-search-query-capfs #'mu4e--search-query-completion-at-point)
  
  (defun mu4e-search-read-query (prompt &optional initial-input)
    "Read a query with completion using PROMPT and INITIAL-INPUT."
    (minibuffer-with-setup-hook
        (lambda ()
	      (setq-local completion-at-point-functions my-mu4e-search-query-capfs)
	      (use-local-map mu4e-minibuffer-search-query-map))
      (read-string prompt initial-input 'mu4e--search-hist)))

```

**Describe alternatives you've considered**

I first thought that instead of `setq-local`, I could just call `(add-hook ... 'local)` to only *add* local capfs instead of overriding the variable completely, since the mu4e search query is so specific that it's unlikely that other capfs would make any sense in this context. 

Alternatively we could also just make `mu4e-search-query-completion-at-point` public, then the user could use advices to e.g. override it without fearing his advice breaking in the future. 

Of course, I can't think of many users-cases of people wanting to add their own completion to that function. 

**Additional context**

Following this I'll think about opening a PR or issue for adding completions to `mu4e-query-fragments`. In case anybody is interested, the first draft of my completion function (my first ever) looks like the following:

``` emacs-lisp
  (defun my-mu4e-query-fragments-complete ()
    (let ((bounds (bounds-of-thing-at-point 'symbol)))
      (when (and bounds
                 (char-equal (char-after (car bounds)) '?%))
        (list
         (car bounds)
         (cdr bounds)
         (completion-table-dynamic
          (lambda (_)
            (mapcar #'car mu4e-query-fragments-list)))
         :exclusive 'no))))
```

**Comment by tsdh** [comment]
I'd say although `mu4e--search-query-completion-at-point` is private, I doubt it will be removed in the next decade.  So the following should do what you want, i.e., add your completion function as another case which gets a chance if the built-in completions didn't trigger.

```elisp
(advice-add #'mu4e--search-query-completion-at-point
            :filter-return
            (lambda (ret)
              (unless ret
                (my-mu4e-query-fragments-complete))))
```
I wouldn't object to making `mu4e--search-query-completion-at-point` public, too.  I've just introduced it as private because it looked like an implementation detail nobody would want to call from a addon package.  But a query extension like that fragments thingy will naturally want to do so...

Another way would be to have a `mu4e-search-query-completion-functions` variable which could be added to where `mu4e--search-query-completion-at-point` just calls those one by one until one returns candidates.  That would have the additional benefit of being able to control the order of "rules".

I don't have a strong opinion here.  @djcb, @meliache, comments & decisions, please! ;-)
I'd volunteer to implement it.

**Comment by meliache** [comment]
Both your suggestions after fine with me, in hindsight I'm also okay with the status quo as this is not a major mode and therefore there will probably never be much demand for customization. Having a variable for that is similar to my first suggestion, there I for some reason just made the variable a hook, not sure what's more idiomatic.

While debugging your advice snippet I also realized that it's also possible to add to `mu4e--search-query-keywords`, which might be enough for most customization use-cases. That's not exactly the same as my own capf-backends, because the keywords are even shown when completing whitespace, while my capf only completes when the query string starts with a `%`, but that might be good enough for me personally. With the caveat of editing a private and (`const`!) variable again. 

Btw, in the advice above on needs to replace the `unless` with an `or` to make sure we return the original return-value if the built-in completion returns, or alternatively use an `:after-until` advice keyword. However, in this order this still doesn't work because if the candidate string doesn't start with a colon, then the above-mentioned list of query keywords is _always_ returned, even if completing a `%` for example. This is not a bug but idiomatic, because the filtering should happen not in the capf but later on the list of candidates returned by the capf based on the users `completion-styles`. Anyway, when trying my custom mu4e-query-fragments completion first it works:
``` emacs-lisp
  (advice-add #'mu4e--search-query-completion-at-point :before-until #'my-mu4e-query-fragments-complete)
```

**Comment by Cerebus** [comment]
Is this issue the underlying reason why I can't seem to get vertico working with search completion?

**Comment by tsdh** [comment]
@Cerebus Nope, see my reply on the mailing list.

**Comment by meliache** [comment]
@tsdh Fine with me :)
