### ISSUE TITLE
[mu4e bug] `smtpmail-queue-dir' does not exist

### ISSUE THREAD

**Issue by gour** [djcb/mu#2314]
**Describe the bug**
When I try to compose a new message I get the "smtpmail-queue-dir' does not exist" error, although I'm using `msmtp` with the
```
(setq message-send-mail-function 'sendmail-send-it
      sendmail-program "/usr/bin/msmtp"
      mail-specify-envelope-from t
      mail-envelope-from 'header
      )
```

**Environment**
The problem has appeared after last update on Debian/Sid with Emacs-27.1 and mu43-a.8.7.2.

Here is the trace:

```
Debugger entered--Lisp error: (error #("[mu4e] `smtpmail-queue-dir' does not exist" 1 5 (face mu4e-title-face)))
  signal(error (#("[mu4e] `smtpmail-queue-dir' does not exist" 1 5 (face mu4e-title-face))))
  error("%s" #("[mu4e] `smtpmail-queue-dir' does not exist" 1 5 (face mu4e-title-face)))
  mu4e-error("`smtpmail-queue-dir' does not exist")
  mu4e--main-toggle-mail-sending-mode()
  funcall-interactively(mu4e--main-toggle-mail-sending-mode)
  call-interactively(mu4e--main-toggle-mail-sending-mode nil nil)
  command-execute(mu4e--main-toggle-mail-sending-mode)
```

Any hint?

**Comment by husainaloos** [comment]
Do you have `smtpmail-queue-mail` set to `t` and do you queue outgoing mail? If you do not queue outgoing mail, set it to `nil`.

**Comment by gour** [comment]
> Do you have `smtpmail-queue-mail` set to `t` and do you queue outgoing mail?

Nope.

>  If you do not queue outgoing mail, set it to `nil`.

Thank you – now it does work! :smile: 

It looks that this is something new, since before the update I never had to explicitly set it to `nil`.
