### ISSUE TITLE
[mu4e bug] Cannot write emails to `user@address.com <user@address.com>`

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#2318]
**Describe the bug**

TLDR:  Send email  to `user@address.com <user@address.com>` and mu4e seems to rewrite it to `"user@" <address.com user@address.com>`

** Details:

mu4e auto-fills a from the address. Often the format is: 

`user@address.com <user@address.com>`.

In this case, the email is bouncing and undeliverable. The error is:

> Delivery has failed to these recipients or groups:
> 
> user@<mailto:address.com%20user@address.com>
> The format of the email address isn't correct. A correct address looks like this:
> someone@example.com. Please check the recipient's email address and try to resend the message.
> 

And then at the bottom,

> From: Some One <Some.One@foo.edu>
> Subject: test
> To: "user@" <address.com user@address.com>
> Date: 2022-08-09 07:06:13 -0700 [PDT] (Tue 07:06:13 AM)
> Flags: seen, personal
> Maildir: /foo
> 
> test
> ----------

**Environment**

Version 1.8.7 built from source.

**Comment by djcb** [comment]
Can't reproduce.... does this happen with all such addresses? Perhaps you can try a few variations.
Please use `(setq smtpmail-debug t)` and add the `* trace of SMTP...` to this ticket. 

Are you using anything but just emacs and mu4e? It seems you removed that part from the bug template.

**Comment by mankoff** [comment]
I have two different MS Outlook/Office365 work emails and this bug occurs with both of them, but not when I send through GMail.

I use DavMail for the MS setup. This may be another MS-specific bug? Can someone else with Outlook and/or DavMail confirm this?

**Comment by mankoff** [comment]
Ah - I think I see the problem. These are both valid email addresses: `user@domain.com <user@domain.com>` so the real problem is that there needs to be a comma between them. Anyway, I have a lot of these types of addresses from mu indexing emails. Not sure why. The bug may not be in how mu4e sends email, it may be in the addressbook behavior?

**Comment by mankoff** [comment]
As an example,  this works (note the quotes, which makes the first part not an email address): `"user@domain.com" <user@domain.com>`

**Comment by djcb** [comment]
You can use `mu4e-contact-process-function`  rewriting.

**Comment by mankoff** [comment]
I do use that function sometimes. But I have 100s of email address in my mu4e addressbook of the format `user@domain.com <user@domain.com>` because **other** people send messages to me and CC people in that format. Should mu4e be importing these (invalid?) email addresses? Or can you recommend a global way of handling these? Does `mu4e-contact-process-function` work with regex?

**Comment by djcb** [comment]
Not sure if these are addresses are technically _invalid_ (check RCF2822), but they're widely used so it seems strange some mail server doesn't support them. The smtp trace may say more. In any case, this seems to be outside mu4e's purview; still, there's `M-h h v mu4e-contact-process-function RET` if you need it.
