### ISSUE TITLE
[mu4e bug] Getting "Invalid face attribute :inherit mu4e-header-key-face [12 times]" with Flyspell hooked.

### ISSUE THREAD

**Issue by simurgh9** [djcb/mu#2321]
**Bug Description**

When `flyspell-mode` is added to the `mu4e-compose-mode-hook` as demonstrated in the documentation section [6.4 Compose hooks](https://www.djcbsoftware.nl/code/mu/mu4e/Compose-hooks.html) and then `mu4e-compose-new` or `S-c` is called , the following,

```
Invalid face attribute :inherit mu4e-header-key-face [12 times]
```
logs in the `*Messages*` buffer.

Nothing is broken and the mail gets sent. Still--maybe there is a fix for this?

**How to Reproduce**

Run `emacs -Q --load test.el` with the contents of the test file (after making the necessary chagnes) as,

```lisp
(package-initialize)
(require 'use-package)
(use-package mu4e
  :load-path "/opt/homebrew/Cellar/mu/1.8.9/share/emacs/site-lisp/mu/mu4e"
  :commands mu4e
  :custom
    (mu4e-drafts-folder "/Drafts")
    (mu4e-refile-folder "/Archive")
    (mu4e-sent-folder "/Sent Items")
    (mu4e-trash-folder "/Deleted Items")
  :hook (mu4e-compose-mode . flyspell-mode)
  )
```

Now, `Mx mu4e`, `S-c` and `C-x b *Messages*`.

**Environment**
Running are macOS Monterey 12.5, GNU Emacs 29.0.50 and mu (mail indexer/searcher) version 1.8.9.

**Comment by djcb** [comment]
From the commit message:

By default, mu4e-header-key-face inherits from message-header-name; this
leads to warnings when we later remap the latter to the former in
mu4e-compose.el.

We don't want to change the definition of mu4e-header-key-face (it's
used widely in mu4e); so we add a new face mu4e-header-field-face
for *just* mu4e-compose and which does not inherit.

(note: this changes behavior, master only)
