### ISSUE TITLE
[misc] Is the buffer *mu4e-server* suppose to be visible?

### ISSUE THREAD

**Issue by simurgh9** [djcb/mu#2322]
I've used mu4e for quite a while now and I have never noticed it opening a buffer by the name `*mu4e-server*`. Maybe I have just been in oblivion? Has this buffer been recently made visible? Can I hide it or only show on some sort of error?

**Environment**
macOS Monterey 12.5, GNU Emacs 29.0.50 and mu (mail indexer/searcher) version 1.8.9.

**Comment by djcb** [comment]
It's used by mu4e internally; nothing to worry about.

**Comment by simurgh9** [comment]
Right but has it been made visible recently? Can I hide it?

**Comment by djcb** [comment]
It's been visible for a long time, but I suppose most users don't need it. It's invisible now in `master`.

**Comment by simurgh9** [comment]
Is this change ever going to be released? Sorry--I am not sure what being invisible in master implies. I am on 1.8.11.

**Comment by djcb** [comment]
Can't really fit a full explanation of `git` branches here, but...

- `master` refers to the "master" git branch where all the new development happens (all the latest code)
- `release/1.8` refers to the branch from which releases (like 1.8.11) are created

The `release/1.8` branch has been split off from `master` and the only changes are bugfixes and zero-risk stuff (typically, we "cherry-pick" such fixes from `master` into the release branch. Not quite sure this fix qualifies for that, so it hasn't made it to the release-branch.

**Comment by simurgh9** [comment]
> Can't really fit a full explanation of git branches here, but...

No worries, I do understand git. I was under the impression that master is released whenever stable enough etc but did not know that the changes that migrated from master to release were hand picked.

So if one wants this feature, and the zero-risk stuff, there is no way? Could a option perhaps be introduced for those who want this? Or maybe you can show me some quick lisp that I can put in my init.

**Comment by djcb** [comment]
With emacs-lisp there's always a way :)  

See the  commit - although `mu4e--server-name` is defined with `defconst`, you can `setq` it to your wanted value in your config.

**Comment by simurgh9** [comment]
I put `(setq mu4e--server-name " *mu4e-server*")` under the `:config` section of my `(use-package mu4e ...`. It worked. However, putting `:custom (mu4e--server-name " *mu4e-server*")` in the same use-package declaration did not. *Shrugs*

**Comment by djcb** [comment]
Okay, great if works. I think `:custom` is for `defcustom` settings, which `mu4e--server-name` is not.
