### ISSUE TITLE
[mu] Issue with search

### ISSUE THREAD

**Issue by tgrigera** [djcb/mu#2333]
I have recently moved to reading/sending mail with mu/mu4e and I'm very happy with the experience.

Today I experienced the following problem with search.  I'm not sure whether it's actually a bug, but I can't figure this out so I ask here.

I received a mail like in this [gist](https://gist.github.com/tgrigera/6aa8065cbf29653914e38889852baec3) and I cannot find it when searching for terms in the body of the message.  I can find it with Gmail search, as well as doing grep in the mail directory.

This is not a mu4e issue, as I have the same trouble with mu in the command line.  This also happens with other mails from the same sender, so maybe it is something related to the sender user agent? I don't know, but it seems to me that mu should be able to find this message.

I repeatedly updated the index just in case, with no success.  mu does find it when searching the from: field.

I am using mu 1.9.0

**Comment by localauthor** [comment]
I am having a similar issue with search, in both 1.9.0 and 1.8.9.

I can find certain messages by from: and subject:, but not when searching terms in the body of the message

I think it only occurs when there are special characters in the "from" field, for example: `ė` or `ū`.

On such messages, when I do "mu find ~/path/to/message", it returns From, To, CC, Subject and Date as expected, but then ["No body found"].

**Comment by tgrigera** [comment]
Thank you for the comment.  I confirm special characters are not to blame.  It seems then the mu fails to find the body of some messages, and thus cannot search them.

**Comment by djcb** [comment]
I can reproduce... and I have a fix. Seems it was an encoding issue after all.

**Comment by tgrigera** [comment]
Great, Dirk, thank you for the fix!  I'll get the fixed version asap

**Comment by djcb** [comment]
Okay! Note that you'll need to re-index for it to work with current messages.

**Comment by localauthor** [comment]
Thanks for your attention to this issues. Unfortunately I still experience the problem. I have re-indexed, as you suggest. I'm not sure what could be the issue, but I would be happy to help pinpoint it. Just let me know how I might be of help.

Does the issue persist for you, @tgrigera?

**Comment by tgrigera** [comment]
Hi @localauthor , I tried Dirk's fix and it seems to work for me: I now can find the pinpointed email and a bunch of others from the same family.  I cannot recall at this point that I had issues with any other messages, but I will keep an eye open in case something strange happens.

**Comment by localauthor** [comment]
Thank you for the reply. I'm pleased to hear things are working for you.

It seems that mu cannot find the body of messages sent from Microsoft Exchange accounts to my Microsoft Exchange account.

**Comment by tgrigera** [comment]
I don't know how to check for the presence of the body of messages.  However, with the fix up to now I haven't noticed mails slipping out of the database.  I dont use Exchange, if the issue is specific to that maybe you should open another issue?

**Comment by djcb** [comment]
@localauthor: that may be a different problem then; I'd recommend opening a new ticket for that, and, critically, attach a raw message where this happens - thanks.

**Comment by localauthor** [comment]
Thanks. Reported in #2349.
