### ISSUE TITLE
[mu4e bug] Duplicated docstring for `mu4e-headers-thread-first-child-prefix` and `mu4e-headers-thread-last-child-prefix`

### ISSUE THREAD

**Issue by bertulli** [djcb/mu#2334]
**Describe the bug**

Hi, this is actually a very minor bug. The docstrings for the two variables you see in the title (`mu4e-headers-thread-first-child-prefix` and `mu4e-headers-thread-last-child-prefix`) are actually the same: "`Prefix for messages in sub threads that do not have a following sibling.`", where of course they shouldn't.
Which one is right? And what is the other?

**How to Reproduce**
Evaluate in Emacs:
```emacs-lisp
(describe-variable 'mu4e-headers-thread-last-child-prefix)
(describe-variable 'mu4e-headers-thread-first-child-prefix)
```

**Environment**
 - Emacs: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-07-31`
 - Mu: `mu 1.8.9-1`
 - OS: `Linux 5.19.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Sep 2022 18:09:09 +0000 x86_64 GNU/Linux`

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [X] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [X] you have read all of the above

**Comment by djcb** [comment]
Thanks -- fixed.
