### ISSUE TITLE
[mu4e bug] "This is a pseudo-article" error shown when toggling HTML view

### ISSUE THREAD

**Issue by david-alvarez-rosa** [djcb/mu#2337]
**Describe the bug**

Toggling to HTML view by pressing `h` in `mu4e-view` that triggers `(mu4e-view-toggle-html)` function does not work, and a "This is a pseudo-article" is shown.

**How to Reproduce**

1. Open any multi-part email (text and HTML) 
2. Press `h` to toggle HTML view `(mu4e-view-toggle-html)`
3. View echo area, it will display a "This is a pseudo-article" error message

**Environment**

Bug discovered on macOS Monterey, GNU Emacs 28.2, mu (mail indexer/searcher) version 1.8.10.

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [X] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [X] you have read all of the above

**Comment by djcb** [comment]
Works for me -- can you attach a raw message where this happens?

**Comment by david-alvarez-rosa** [comment]
Yes sure, attaching one: [email-example.txt](https://github.com/djcb/mu/files/9596931/email-example.txt), hope it helps.

And adding one screenshot of what I see after pressing `h`:
<img width="1510" alt="Screenshot 2022-09-19 at 09 38 57" src="https://user-images.githubusercontent.com/77437099/190970671-f9f95a51-f4d4-4f82-9458-cded17677b78.png">

Let me know if I can help with anything else :) Thank you!

**Comment by bergheim** [comment]
Just wanted to add that this has never (several years) worked for me - I always get "This is a pseudo-article".

**Comment by FrustrumCode** [comment]
Just got this.  All latest as of yesterday installed from homebrew on mac BigSur.

**Comment by tausen** [comment]
FWIW, I've been having this issue since forever and seem to have solved it by switching to using plaintext by default with:

```
  (with-eval-after-load "mm-decode"
    (add-to-list 'mm-discouraged-alternatives "text/html")
    (add-to-list 'mm-discouraged-alternatives "text/richtext"))
```

Pressing `h` now toggles between html and plaintext nicely.

**Comment by djcb** [comment]
There are some different problems here:
- some messages simply don't _have_ a plain-text part. The "pseudo-article" warning isn't very useful, so that's been improved in `master`
- For many other messages,  indeed the `mm-discourage-alternative` settings helps, which is why it's in the manual
- For the particular message that @david-alvarez-rosa attached, even that is not enough, but you _also_ have to add:
   ` (add-to-list 'mm-discouraged-alternatives "multipart/related")`; that not improve some other messages, ymmv.

So:
```
(with-eval-after-load "mm-decode"
  (add-to-list 'mm-discouraged-alternatives "text/html")
  (add-to-list 'mm-discouraged-alternatives "text/richtext")
  (add-to-list 'mm-discouraged-alternatives "multipart/related"))
```

Any, thanks for the dicussion, closing this now.

**Comment by david-alvarez-rosa** [comment]
Thank you all. Checked today and it's working :)
