### ISSUE TITLE
[mu4e bug] documentation: variable rename: (void-variable mu4e-view-attachment-actions) -> mu4e-view-mime-part-actions

### ISSUE THREAD

**Issue by hrehfeld** [djcb/mu#2351]
**Describe the bug**
`(void-variable mu4e-view-attachment-actions)` 

**How to Reproduce**

while trying to add to it per https://www.djcbsoftware.nl/code/mu/mu4e/Attachment-actions.html :

```
		(add-to-list 'mu4e-view-attachment-actions
					       '("remove attachment" . my-remove-attachment))
```

Also happens  after `mu4e`.

This is a regression, was working fine before.

**Environment**
mu4e-mu-version is a variable defined in mu4e-config.el.
"1.8.9"

GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-12

archlinux

**Checklist**
- [x] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [x] you have read all of the above

**Comment by djcb** [comment]
It's been obsoleted by `mu4e-view-mime-part-actions` , but the documentation hadn't been updated yet.

**Comment by djcb** [comment]
Doc has been updated.
