### ISSUE TITLE
[mu bug] Impossible to search a compound noun

### ISSUE THREAD

**Issue by jpggithub** [djcb/mu#2354]
**Describe the bug**
I'm trying to find some mails that I don't they exist.
A research with a command line like `mu find jean-philippe` gives 0 result but `mu find jean*`"succeeds.
The problem seems to come from the fact that I'm searching for a compound noun.
I also tried `mu find jean\-philippe` with no success.

**To Reproduce**
Try searching a compound name that exist in some mail, you won't find them.

**Environment**
Emacs 27.1
mu 1.8.10
Debian Linux bookworn/testing version
Gnu Bash 5.2.0

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Yeah, that's a know limitation... not super easy to fix. This is handled with #2167, closing as a dup.
