### ISSUE TITLE
[mu RFE] new format for `mu cfind`:  `John Doe <john.doe@server.net>`

### ISSUE THREAD

**Issue by jpggithub** [djcb/mu#2355]
Can you add a new format for `mu cfind format` similar to the `plain` format but with the "< >" signs for the mail adress?

The ouput would be:

`John Doe <john.doe@server.net>`

instead of

`John Doe john.doe@server.net`.

I use this very useful function to use "mu cfind" from Emacs in several ways:

`(defun my/mu-cfind ()
  (interactive)
  (insert (completing-read "mu: " (split-string (shell-command-to-string "mu cfind") "\n"))))`

Thanks

**Comment by djcb** [comment]
Ah, I try to avoid adding more "special" formats, but I did add `--format=json` in `master` that should allow you to get the data you want; you could use e.g. `jq` and do something like:
```
   mu cfind --format=json | jq -r '.[] | .display'  
```
(and seen the manpage).
