### ISSUE TITLE
[mu bug] Regular expressions don't behave as expected

### ISSUE THREAD

**Issue by maxchaos** [djcb/mu#2360]
**Describe the bug**
Special characters like `^` don't seem to have any effect inside regular expressions. Also escaping characters like `(`, `[` etc does not literally match them, rather causes the search to fail.

**To Reproduce**
Example of the first case (as executed in bash):
```
mu find 'subject:/^failed/'
```
Expected behavior: match only messages the subject of which begins with the word "failed".
Actual behavior: match all messages the subject of which contains the word "failed" anywhere.

Example of the second case (as executed in bash):
```
mu find 'subject:/\(/'
```
Expected behavior: match all messages the subject of which contains an opening parenthesis.
Actual behavior: Search fails (return code 4) with output "no matches for search expression"

**Environment**
GNU Guix, mu v1.8.9
Void Linux, mu v1.6.1

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
Neither of those are expected to work -- `mu` (it's the underlying Xapian full-text db, really) matches against separate words (in general we err on the side of "more matches are better")

Special-characters can't be matched like that; a bit outside mu's control.

**Comment by maxchaos** [comment]
Thanks for the reply. I got the impression they would work because the man pages (section "Regular Expressions and Wildcards" of "mu-query") mention a compatibility with ECMAScript but didn't clarify the extend. It makes sense now.

**Comment by djcb** [comment]
Yeah, the documentation could be a bit more precise...
