### ISSUE TITLE
[mu4e bug] Buffer "*mu4e-update*" has a running process

### ISSUE THREAD

**Issue by breadncup** [djcb/mu#2362]
**Describe the bug**

From time to time, there are multiple questions like "Buffer "*mu4e-update*" has a running process; kill it? (y or n)", and I should answer 'n' multiple times (about 10 or 20 times)

**How to Reproduce**

1. Running mbsync every 5 minutes
2. Close the MacBook Pro for a few hours
3. Open the MacBook Pro
4. Go to the Emacs.app
5. The message of "*mu4e-update*" has a running process; kill it? (y or n)."
6. You should answer multiple times.

**Environment**
- macOS 12.5
- GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.5 (Build 21G72)) of 2022-09-25
- mu/mu4e 1.8.11

**Checklist**
- [YES] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [YES] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [YES] you have read all of the above

**Comment by djcb** [comment]
Fixed in master.

**Comment by breadncup** [comment]
It looks like here is the change in mu4e: https://github.com/djcb/mu/commit/b0fad6d763b7659a86e902f30bbe3940af77f30e

Thanks
