### ISSUE TITLE
Compose: address completion stopped working

### ISSUE THREAD

**Issue by joukeHijlkema** [djcb/mu#2363]
**Describe the bug**

After upgrading emacs and mu to the latests' origin/master (git pull), address completion (TAB in the To: field) stopped working. I get "no matches" for whatever first characters I enter. I don't think anything else has changed.

I notice that when I hit TAB for the first time that : 
Loading eudcb-ecomplete...done
Loading eudcb-mailabbrev...done
I've never seen this before, so I wonder if this might be the root of the problem. If I remember correctly, it used to be abbrev that did the completion thing.

**How to Reproduce**
shift-c in the headers window to open a compose window then type the beginning of an address in the To:  fields then hit TAB

**Environment**
- Ubuntu 22.04.1 LTS
- GNU Emacs 29.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2022-11-14
- mu4e-mu-version = 1.9.2
- 
**Checklist**
- [ x] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [ x] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [ x] you have read all of the above

**Comment by djcb** [comment]
This is new behavior in emacs 29; can you check what changed there? Otherwise, please file a bug there and report back here - thanks!

**Comment by thesamesam** [comment]
Any idea how to revert to the old behaviour?

**Comment by joukeHijlkema** [comment]
I think it boils down to this (message.el)
```(defun message-expand-name ()
  (cond (message-expand-name-standard-ui
	 (let ((beg (save-excursion
                      (skip-chars-backward "^\n:,") (skip-chars-forward " \t")
                      (point)))
               (end (save-excursion
                      (skip-chars-forward "^\n,") (skip-chars-backward " \t")
                      (point))))
           (when (< beg end)
             (list beg end (message--name-table (buffer-substring beg end))))))
	((and (memq 'eudc message-expand-name-databases)
		    (boundp 'eudc-protocol)
		    eudc-protocol)
	 (eudc-expand-inline))
	((and (memq 'bbdb message-expand-name-databases)
	      (fboundp 'bbdb-complete-name))
         (let ((starttick (buffer-modified-tick)))
           (or (bbdb-complete-name)
               ;; Apparently, bbdb-complete-name can return nil even when
               ;; completion took place.  So let's double check the buffer was
               ;; not modified.
               (/= starttick (buffer-modified-tick)))))
	(t
	 (expand-abbrev))))```

So you have to make sure that you fall into the last condition.

**Comment by joukeHijlkema** [comment]
I got something working, and it is actually rather nice. You can easily manage your addresses by editing the bbdb file, and you have access to ldap completion.
I added this to my config files
```
(use-package bbdb
  :init
  (setq bbdb-allow-duplicates t)
 )
(use-package eudc
  :init
  (customize-set-variable 'eudc-server-hotlist
                          '(("" . bbdb)
                            ("ldap://my.ldap.server" . ldap)))
  (setq ldap-ldapsearch-args (quote ("-tt" "-LLL" "-x")))
  )
```
And I wrote a small function to move the mu4e contacts to bbdb
```
;;|--------------------------------------------------------------
;;|Description : convert mu4e contacts to bbdb
;;|NOTE : 
;;|-
;;|Author : jouke hylkema
;;|date   : 15-26-2022 11:26:31
;;|--------------------------------------------------------------
(defun myContacts2Bbdb ()
  "convert mu4e contacts to bbdb"
  (interactive)
  (save-excursion
    (mu4e-contacts-info)
    (switch-to-buffer "*mu4e-contacts-info*")
    (goto-line 6)
    (cl-loop until (eobp) do
             (let ((line (buffer-substring (point)
                                           (progn (forward-line 1) (point)))))
               (bbdb-snarf line 'mail t)
               )
             )
    (bbdb-save)
  )
)
```

**Comment by presnell** [comment]
FWIW, there is a variable called message--old-style-completion-functions.  It defaults to nil, but setting it to t seems to have no effect on this problem.  I realize that there's a very good chance that everyone here knew that this variable existed, but I thought that I should mention it just in case.

I don't really want to use an LDAP server and I stopped using BBDB a while back after many, many, many years.  So I just want to get mu4e's auto-completion working again.  Any hints on that?

**Comment by theophilusx** [comment]
FYI, I just saw a message on emacs devel list reporting that ebdb
and bbdb people experiencing problems in Emacs 29 due to changes in
message-mode. Looks like this could be related to an Emacs bug?

**Comment by djcb** [comment]
Yeah, and the very latest seems to have fixed.... so closing this.

**Comment by thesamesam** [comment]
Thanks all. For completeness, I think https://debbugs.gnu.org/cgi/bugreport.cgi?bug=59314 was the bug and the relevant thread was https://lists.gnu.org/archive/html/emacs-devel/2022-11/msg00989.html.
