### ISSUE TITLE
[mu bug] Term splitting borks regular expression search

### ISSUE THREAD

**Issue by dcolascione** [djcb/mu#2365]
**Describe the bug**
Suppose I have a message with subject `foo’s bar` --- note the non-ASCII `’` character. If I do a regular expression search for `subject:/bar/`, then Mu will enumerate all subject terms in the database, find one called `Sfoo’s bar`, split it on spaces, and do a phrase search in Xapian for the terms `foo’s` and `bar`. This search always fails, because Xapian, inside `TermGenerator`, normalizes `’` to `'` (i.e. converts the fancy apostrophe to a regular apostrophe), and so indexes `Sfoo's` and `Sbar`. The former doesn't match our search term `Sfoo’s`, and so the whole query fails to produce a match.

There are two possible problems here: 

  1. We're word-splitting for regular expression matches when generating Xapian terms even though we could matching "atomically" instead (i.e. searching for `Sfoo’s bar`, since that's what `std::regex` literally matched), and
  2. We're not apostrophe-normalizing in mu-document.cc when we "also add [the indexable term] as a 'normal' term" to the index, which means that _some_ terms in the Xapian database have regular apostrophes and some have fancy apostrophes.

To fix this issue, can we 1) not word-split when feeding results of regular expression matches to Xapian, and 2) do our own apostrophe normalization in `utf8_flatten`?

**To Reproduce**
See above.

**Environment**
Git master

**Checklist**
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
This is fixed with the new query parser that landed a while ago; in fact, I added "foo’s bar" added as a unit test.
Regarding the regexp with spaces, that works (now), the regexp must be quoted so, e.g `subject:"/foo’s bar/"`
