### ISSUE TITLE
[mu4e rfe] more control on duplicated messages in Gmail

### ISSUE THREAD

**Issue by sdycjsj** [djcb/mu#2367]
**Is your feature request related to a problem? Please describe.**
I updated mu from 1.6.x to 1.8.10 and just noticed a subtle change about duplicated messages in Gmail.
I am talking specifically about duplicated messages in "Inbox" and "All mail".
Previously, the copies in "All mail" were considered as duplicates and what "mu find -u" gives are those in "Inbox".
In the latest version (1.8.11), it is the other way around, i.e., among duplicated messages, those in "Inbox" are considered as duplicates and are hidden in "mu find -u".

I also run mu (1.8.10) on a Mac, where it shows the opposite behavior. i.e., duplicated messages in "All mail" are hidden.
I am wondering whether the hidden messages are chosen randomly.

This matters because in mu4e, I would like to operate on those in the "Inbox", while I treat copies of messages in "All mail" as archived ones which I rarely touch.

**Describe the solution you'd like**
So is it possible to specify which are hidden among duplicated messages?
Naively, it will be good to be able to specify some sort of a priority list of maildirs according to which the one non-hidden duplicated message are picked.

Actually, some customizable variables on the mu4e side would be sufficient. However, I understand that mu4e just displays results returned by mu, so this might not be straightforward.

**Comment by djcb** [comment]
What _should_ happen is that  whatever matches the "primary" search has priority over "related" messages. So if you explicitly search for message in Inbox, a match there would have precedence over a duplicate in 'All mail'.  Does it not work like that for you?

**Comment by sdycjsj** [comment]
I am not sure whether I understand "search for a message in inbox" correctly. 
If I specify "inbox" in the search query, there will be no duplicates in the result (duplicates are in "All mail"), so in this case there are no duplicates to hide in the result and this is not related to the issue. 

So I guess you mean duplicates in the result when `mu4e-headers-toggle-include-related` is turned on? This case works as expected -- related duplicates have lower priority, but I usually turn related messages off and this is not relevant.

I tried the following:
In mu4e, jump to the folder "/Gmail/Inbox" and do `mu4e-search`. The message in the result is from "All mail". 

In one of my use cases, in the headers view of all inboxes (there are several accounts), with the point on a message I do `mu4e-action-show-thread`. Then I get a headers view with all messages in the conversation, but all messages are from "All mail".

**Comment by djcb** [comment]
Yeah, apart from related-or-not, you cannot specify a preference, and whether the ones Inbox or All Mail are considered "the originals" or "the dups" is essentially outside mu's purview, and that hasn't changed.

Can't immediately think of a nice way to generically implement that, but perhaps there's a way to do it.

**Comment by sdycjsj** [comment]
Just downgrade to 1.6.10. Surprisingly, it has the same behavior as 1.8.10. Sorry for giving wrong information.
Now I am confused why my use case does not work anymore. Anyway, I will stop here and close this issue.

**Comment by djcb** [comment]
I think the ordering is beyond mu's control - influenced by the order in which things indexed etc.. so it might occasionally/accidentally work the way you want.

**Comment by djcb** [comment]
However, what you _can_ do with existing mu/mu4e when doing a "related" query is to explicitly add something like  `AND NOT maildir:/other-maildir`, that ensures those are _not_ in the primary set.

Don't think there's some other way within the complexity-budget, so hope that works.... closing now, thanks!
