### ISSUE TITLE
[mu bug] Can't sort by date

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#2368]
**Describe the bug**
The ``date`` field cannot be used for sorting on the command line:

```
% mu find --sortfield date
error: --sortfield: Check date value in {to->20,thread->19,tags->18,subject->17,bcc->0,body->1,list->10,message-id->11,cc->2,mime->12,flags->7,maildir->9,path->13,embed->5,file->6,from->8,priority->14} OR {20,19,18,17,0,1,10,11,2,12,7,9,13,5,6,8,14} FAILED
```

**Environment**
linux/debian unstable

**Checklist**
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

At commit d2a3a1324216238cab2c076830255caf8a81dfa7

**Comment by djcb** [comment]
It's actually the default ;), but yeah, it should be a valid sortfield.

**Comment by wavexx** [comment]
> It's actually the default ;)

Yup, but I had some scripts I noticed broke as they always specified the sorting field (default or not).
Similarly, --reverse/-z is not currently implemented.

Should I file a bug for that?
