### ISSUE TITLE
[mu4e bug] Marking duplicate messages as read automatically doesn't work anymore

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#2370]
**Describe the bug**

I have `mu4e-headers-skip-duplicates` set to `t` so when someone on a mailinglist replies to a message of mine to the list and puts me also in the Cc, I'll get two mails.  My unread bookmark shows 2 unread mails.  I visit the bookmark and see only one mail.  I mark it as read and exit the headers view.

Now my bookmark shows 1 unread mail.  When I visit it again, I see basically the same message again.

This propagation of read mark to duplicates has been implemented in #2277 just recently and used to work.  Now it has stopped working again, maybe some days ago.

**How to Reproduce**

Set `mu4e-headers-skip-duplicates` set to `t`  and send a mail to yourself which will be received twice, e.g., send a test mail to the mu mailinglist where I will answer to the list and add you to the Cc, too.

**Environment**
GNU/Linux, Emacs & Mu git masters

**Checklist**
- [X] you are running the latest mu master
- [X] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [X] you have read all of the above

**Comment by djcb** [comment]
Yeah, seeing this too.

**Comment by djcb** [comment]
Working on this.

**Comment by djcb** [comment]
Fixed in `master`.
