### ISSUE TITLE
[mu4e bug] Some contacts trigger a 550 error

### ISSUE THREAD

**Issue by rjekker** [djcb/mu#2374]
**Describe the bug**

Sending a message to a contact with the format "my-contact@myserver.com \<my-contact@myserver.com\>" will cause an error: "smtpmail-send-it: Sending failed: 550 header syntax in response to ."

The error seems to be caused by the part in brackets being the same as the actual email. The problem here is that that is how "mu cfind" gave me the contact. When I remove the bracketed part, the message is sent without problems.

My smtp server is exim4 and that is returning the message; it seems that mu does not create a valid SMTP message?

**How to Reproduce**

Compose a message to "x@y.z \<x@y.z\>" and send. The actual address does not seem to matter, as long as the part in brackets is the same as the actual email. 

Example:

    From: Reindert-Jan <info@xxx.com>
    To: info@yyy.zz <info@yyy.zz>
    Subject: test
    Date: Tue, 06 Dec 2022 14:28:41 +0100
    Message-ID: <m2tu28ek52.fsf@xxx.com>
    --text follows this line--
    test

Traceback:

      Debugger entered--Lisp error: (error "Sending failed: 550 header syntax in response to .")
      signal(error ("Sending failed: 550 header syntax in response to ."))
      error("Sending failed: %s" "550 header syntax in response to .")
      smtpmail-send-it()
      message-use-send-mail-function()
      message--default-send-mail-function()
      message-multi-smtp-send-mail()
      message--send-mail-maybe-partially()
      message-send-mail(nil)
      message-send-via-mail(nil)
      message-send(nil)
      message-send-and-exit(nil)
      funcall-interactively(message-send-and-exit nil)
      call-interactively(message-send-and-exit nil nil)
      command-execute(message-send-and-exit)

**Environment**

Emacs 28.2 on mac (homebrew: emacsplus)
mu 1.8.13

Issue occurs when I run "emacs -Q" and only load mu4e.

**Checklist**
- [x] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [x] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [x] you have read all of the above

**Comment by djcb** [comment]
I suspect it's some server-side issue; closing this. but feel free to open this if you think this is a mu4e bug.
