### ISSUE TITLE
[mu4e bug] Errors and major behavioral changes on recent master

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#2375]
**Describe the bug**

I'm on 5acb824181d2667010ce2d983d651db482e4f438.  When I am in a headers buffer and select a message using `RET` (`mu4e-headers-view-message`), I get the following error:

```
Debugger entered--Lisp error: (error #("[mu4e] Cannot get a message view" 1 5 (face mu4e-title-face)))
  error("%s" #("[mu4e] Cannot get a message view" 1 5 (face mu4e-title-face)))
  mu4e-error("Cannot get a message view")
  mu4e-view((:size 59520 :list-post ((:email "emacs-devel@gnu.org")) :date (25494 59286 0) :from ((:email "stefankangas@gmail.com" :name "Stefan Kangas")) :list "emacs-devel.gnu.org" :message-id "CADwFkmnN6DRtqdpnD-9LHyEDsWooeDx4WDV-thHPT5NEA_2Rm..." :priority low :references ("167080394233.4339.5863353994038854528@vcs2.savanna..." "20221212001223.E9A9DC004BE@vcs2.savannah.gnu.org") :subject "Re: emacs-29 9c0d7bb73b 2/2: Add automated tests f..." :to ((:email "joaotavora@gmail.com" :name "João Távora") (:email "emacs-devel@gnu.org")) :path "/home/horn/.mail/Fastmail/mailinglists/emacs-devel..." :changed (25494 60258 0) :flags (seen attach list) :maildir "/Fastmail/mailinglists/emacs-devel" :docid 63394 :meta (:path "2:z" :level 0 :date "n6396e796" :data-tstamp (0 0 0) :root t :thread-subject t)))
  mu4e~headers-view-handler((:size 59520 :list-post ((:email "emacs-devel@gnu.org")) :date (25494 59286 0) :from ((:email "stefankangas@gmail.com" :name "Stefan Kangas")) :list "emacs-devel.gnu.org" :message-id "CADwFkmnN6DRtqdpnD-9LHyEDsWooeDx4WDV-thHPT5NEA_2Rm..." :priority low :references ("167080394233.4339.5863353994038854528@vcs2.savanna..." "20221212001223.E9A9DC004BE@vcs2.savannah.gnu.org") :subject "Re: emacs-29 9c0d7bb73b 2/2: Add automated tests f..." :to ((:email "joaotavora@gmail.com" :name "João Távora") (:email "emacs-devel@gnu.org")) :path "/home/horn/.mail/Fastmail/mailinglists/emacs-devel..." :changed (25494 60258 0) :flags (seen attach list) :maildir "/Fastmail/mailinglists/emacs-devel" :docid 63394 :meta (:path "2:z" :level 0 :date "n6396e796" :data-tstamp (0 0 0) :root t :thread-subject t)))
  mu4e--server-filter(#<process  *mu4e-server*> "\37630d\377(:view (:size 59520 :list-post ((:email \"emac...")
```
The message will be displayed anyhow.

Next to the error, the behavior has drastically changed.  In the past, `RET` in the headers buffer selected the article buffer so that hitting `RET` again resulted in `mu4e-scroll-up` there.  Now the headers buffer stays current, so to scroll, one has to manually make the article buffer current.  (BTW, I don't say the article buffer should be current, just that there must be a convenient way to scroll it.  Gnus, for example, won't select the article buffer but still the "view this message" command in the summary buffer also scrolls the article buffer if that's visible.)

Also `n` and `p` used to select (in the headers buffer) and view the next message.  Now they just select the next/prev message in the headers buffer without viewing it.

**How to Reproduce**

Just operating `RET`, `n`, and `p` in an arbitrary headers buffer suffices.

**Environment**

Current emacs from git master, current mu/mu4e from git master

**Checklist**
- [ ] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [X] you are using the current git master mu/mu4e 
- [X] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [X] you have read all of the above

**Comment by tsdh** [comment]
You are right, I've commented most parts of my config and the issues are gone.  Hm, I'll report back what caused the issue.

**Comment by tsdh** [comment]
Ok, I found which setting seems to cause the issue now:

```elisp
(defun th/mu4e-split-view ()
  (let* ((headers (mu4e-get-headers-buffer))
         (headers-win (and headers (get-buffer-window headers)))
         (view (mu4e-get-view-buffer))
         (view-win (and view (get-buffer-window view)))
         (fit-window-to-buffer-horizontally t))
    (cond
     (view-win view-win)
     ((one-window-p) (split-window-sensibly))
     ;; Use the tallest window.
     (t (car (sort (delq headers-win (window-list))
                   (lambda (a b)
                     (> (window-height a) (window-height b)))))))))

(setq mu4e-split-view #'th/mu4e-split-view)
```
If I change to `'vertical`, it immediately works again.  That said, I've used that function for a long time without issues.

**Comment by djcb** [comment]
Interesting.... I'll take a look.

**Comment by mickeynp** [comment]
Tassilo, do you have any customized window functions?

**Comment by djcb** [comment]
I've turned off the functionp case (fallback to 'horizontal) for now, since users could (would?) otherwise end-up with a non-functional mu4e.  The split-window handling was indeed a bit messy; but we never used it for e.g. the main-window.

**Comment by tsdh** [comment]
@mickeynp @djcb Ah, alright.  Feel free to remove the function case from the defcustom and issue a warning if it's still set to a function.  It was me who added it and I'm probably the only user.

I've originally added it because setting vertical/horizontal statically didn't fit the bill for me because the right value depends on the current emacs frame's geometry.  A value `sensibly` for `split-window-sensibly` would also have made sense at that time but I decided to add the most flexible case of an arbitrary function.

And Mickey, how do `mu4e-split-view` and `display-buffer-alist` interact?  Should I set `mu4e-split-view` to `:foobarbaz` so that mu4e doesn't split itself and `display-buffer-alist` takes over?

**Comment by mickeynp** [comment]
Yeah I understand completely. You can still do all of this, but you have far more "control" now in the function, which is perhaps unwarranted?

So what happens is this: `mu4e-display-buffer` looks at a bunch of settings and decides on an action for `display-buffer`. But anyone can override it with `display-buffer-alist`; that means if there's no overrides that match in that alist the default `mu4e-split-view` kicks in. I.e., you can set it to horizontal and then customize only the view buffer and it'll get its own treatment -- everything else does what `mu4e-split-view` says.

**Comment by tsdh** [comment]
@mickeynp That's great, so I'm all for removing the function possibility of `mu4e-split-view` while at the same time describing its interplay with `display-buffer-alist` there.

@djcb Feel free to close this issue or keep it open for some time for easy findability in case others hit the same problem.

**Comment by tsdh** [comment]
@mickeynp Hi Mickey, I've now tried to adapt my `display-buffer-alist` to arrange for mu4e article buffers to be shown in a left side window which should be 80 chars wide, and `mu4e-split-view` is `vertical`.  (Of course, I'd rather go for a right side window but this is just for testing purposes.)

```elisp
(setq display-buffer-alist
      `(((derived-mode . mu4e-view-mode)
         . (display-buffer-in-side-window
            (window-width . 80)
            (side . left)
            (slot . 0)))
        ...)
```
It basically works, i.e., the article is shown in a left side window.  However, the `window-width` doesn't seem to be honored.  The window is much wider (100 chars), exactly as wide as it is without `display-buffer-alist` customization.

[long debugging story elided]

Ah, I found the culprit: there's `mu4e-after-view-message-hook` which contains `mu4e-resize-linked-headers-window` which shrinks the headers buffer to `mu4e-headers-visible-columns` which I've had set to 72 but which apparently never had an effect with my custom `mu4e-split-view` function.  I've now removed it from the hook and am satisfied.

Still it's a pity that the claim that `mu4e-display-buffer` can be customized with `display-buffer-alist` is invalidated in parts by such an "after action".  But I know, backwards compatibility and such...

My personal preference is headers as wide as possible (in order to be able to still see the thread structure) and the article as slim as possible.  But probably that works out for me only because I'm mostly on "civilized" parts of the web where there is no HTML mail and everybody breaks hard at 72 columns. ;-)

**Comment by mickeynp** [comment]
Hi Tassilo,

The after action is unfortunately an established feature -- but easy to remove: `mu4e-after-view-message-hook` is called when a view is shown and the function in that hook does the resizing.

(I anticipated this and made it replaceable.) So just remove the hook (set in defcustom) and you're good to go.

**Comment by mickeynp** [comment]
Apropos using side windows: try typing `C-x w s` with the side window visible: it toggles side windows on or off in Emacs. A nifty benefit :)

**Comment by tsdh** [comment]
@mickeynp Yes, as said, I've removed the resizing function from `mu4e-after-view-message-hook` and now it all works as intended.  It just took me a while of debugging because first I've debugged `mu4e-display-buffer` and `display-buffer` before realizing the resizing happens afterwards.

**Comment by djcb** [comment]
I've officially retired the `mu4e-split-view` function now, and updated the documentation, NEWS etc. Hopefully this won't affect too many users. Renamed `mu4e-after-view-message-hook` into ``mu4e-view-rendered-hook` for consistency; and added a note to the manual so `display-buffer-alist` tweakers know about it!

Oh, there is a  `display-buffer-alist` example in the manual, but we could use another one, perhaps the one @tsdh mentioned? 

Finally, added a bunch of tweaks to the manual / NEWS.org, because it seems many existing users may need to update the `mu4e-view-mode-hook` in their configuration `mu4e-view-rendered-hook`. I _think_ that hook is fairly widely used.

**Comment by tsdh** [comment]
@djcb Is the "obsolete since 1.6.7" correct for `mu4e-after-view-message-hook`?  Aren't we at 1.9.x already?

And would you change the `mu4e-after-view-message-hook` in the comment from my merged PR at the bottom of `mu4e-view.el` to also suggest the new name `mu4e-view-rendered-hook`?

**Comment by djcb** [comment]
@tsdh: Oh yeah, you are right. Fixed.

**Comment by djcb** [comment]
Thanks for all the comments; closing this one, please file new ones if needed (others have done so!)

**Comment by djcb** [comment]
The problem seems to be in `mu4e~headers-move`... ; when you're looking at the headers view  `mu4e~headers-view-win` should be nil, but seems it is not (it points at the headers view window) and hence `mu4e-headers-move` decides to show the message.

Seems something is setting  `mu4e~headers-view-win`  incorrectly.

**Comment by djcb** [comment]
Ah, seems mu4e-view-quit must reset `mu4e~headers-view-win`; I've pushed a fix for that.
