### ISSUE TITLE
[mu4e bug] Wrong type argument: commandp mu4e~view-quit-buffer

### ISSUE THREAD

**Issue by theophilusx** [djcb/mu#2381]
**Describe the bug**

This error is with latest HEAD of git repo. Using Emacs 29 (HEAD of emacs-29 branch). Fedora 37 xfce spin.

When in the mu4e-article view buffer, hitting 'q' or selecting "Quit View" fro the mu4e menu generates the below error. 

```
Debugger entered--Lisp error: (wrong-type-argument commandp mu4e~view-quit-buffer)
  call-interactively(mu4e~view-quit-buffer nil nil)
  command-execute(mu4e~view-quit-buffer)

```
**How to Reproduce**

To reproduce, just select a mailbox and then select a message from the header view 
Hit enter to open the message and move cursor into the *mu4e-article* buffer. 
Hit 'q' or select "Quit View" from the mu4e menu.

**Environment**

GNU Emacs 29.0.60 (build 2, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.6, Xaw3d scroll bars) of 2022-12-15

I notice the following in mu4e-view.el

```
(define-key menumap [quit-buffer]
                  '("Quit view" . mu4e~view-quit-buffer))

```

but I don't see any definition for mu4e~view-quit-buffer

**Checklist**
- [ ] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [ ] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [ ] you have read all of the above

**Comment by theophilusx** [comment]
BTW The binding of q to vm~miew-quit-buffer seems to be from evil-collection. I've fixed that in my version by changing that binding to quit-window. The binding for the menu is the one which needs to be updated in mu4e.

**Comment by djcb** [comment]
Yeah, `mu4e~view-quit-buffer` was removed, but we had one remaining user.... fixed in `master`. Thanks for reporting.
