### ISSUE TITLE
mu4e--main-view forces full frame window

### ISSUE THREAD

**Issue by mickeynp** [djcb/mu#2382]
I missed this change, but `mu4e--main-view` now calls `delete-other-windows` --- which completely decimates the existing window layout. It is not possible to configure it with `display-buffer-alist` and any customisation a user may have is ignored.

**Comment by averter** [comment]
I am experiencing this, and I have the latest version from master... Could it be emacs version-related? For reference I am using 
emacs 27.1, mu 1.10.1 and Linux mint 21.1.

**Comment by mickeynp** [comment]
Emacs 27 should work fine, and the change should work fine. Are you possibly using other packages to interfere or change how Emacs buffers are displayed?

**Comment by averter** [comment]
@mickeynp Perhaps... I have a very long mu4e configuration so it would be great to know if there are any plausible culprits and avoid me having to post a very large portion of elisp code. On the other hand, a `debug-on-entry` of `delete-other-windows` looks like this:
```` lisp
* delete-other-windows(#<window 67 on *mu4e-main*>)
  display-buffer-full-frame(#<buffer *mu4e-main*> ((direction)))
  display-buffer(#<buffer *mu4e-main*> ((display-buffer-reuse-window display-buffer-reuse-mode-window display-buffer-full-frame) (direction)))
  pop-to-buffer(#<buffer *mu4e-main*> ((display-buffer-reuse-window display-buffer-reuse-mode-window display-buffer-full-frame) (direction)))
  mu4e-display-buffer(#<buffer *mu4e-main*> t)
  mu4e--main-view()
  mu4e--pong-handler((:pong "mu" :props (:version "1.10.1" :personal-addresses ("email1@hello.com" "email2@gmail.com" "email3@work.com") :database-path "/home/username/.cache/mu/xapian" :root-maildir "/home/username/Mail" :doccount 1708)) mu4e--main-view)
  #f(compiled-function (info) #<bytecode 0x1562d51f8f39>)((:pong "mu" :props (:version "1.10.1" :personal-addresses ("email1@hello.com" "email2@gmail.com" "email3@work.com") :database-path "/home/username/.cache/mu/xapian" :root-maildir "/home/username/Mail" :doccount 1708)))
  mu4e--server-filter(#<process  *mu4e-server*> "\3761ab\377(:queries ((:query \"flag:unread AND NOT flag:...")

````

**Comment by mickeynp** [comment]
That looks correct. `display-buffer-full-frame` says as much:

`Display BUFFER in the current frame, taking the entire frame.`

**Comment by averter** [comment]
How can it be correct? Doesn't your PR prevents mu4e from calling `delete-other-windows`?

**Comment by mickeynp** [comment]
It is correct. mu4e's main window is full frame by default. This PR merely fixes the issue where that wasn't *overridable* by `display-buffer-alist`.

**Comment by averter** [comment]
@mickeynp , ok great,  so I am just seeing the default behavior and there should be a way to change it over using display-buffer-alist. 

The documentation [here](https://www.djcbsoftware.nl/code/mu/mu4e/Buffer-display.html) goes over the headers and message views but there is nothing about the main view. After surfing the web for some time in search for answers, and reading the documentation about display-buffer-alist, I still cannot figure out how I can set mu4e-main back to how it was before... 

Are you able to add such an example to the doc? This would be a great help to mu4e users who need to customize this new variable to their needs. Thanks

**Comment by mickeynp** [comment]
I'm pretty sure mu4e's main view has always preferred a full frame, but @djcb can correct me if I am wrong here.

**Comment by averter** [comment]
> I'm pretty sure mu4e's main view has always preferred a full frame, but @djcb can correct me if I am wrong here.

:-O. Just to do a sanity check, I've reverted back to mu 1.8.14 and I can confirm that with my current configuration mu4e-main does not gets displayed as a full frame; this has been a constant setting for as far as I can remember. 

If this has always been the default behavior the only option left will be to go over my whole mu4e configuration...

**Comment by djcb** [comment]
@mickeynp is right, mu4e always tried to be full-fframe; maybe @averter succeeded in convincing it otherwise, and likely that no longer works... 

But sure, try something like:
```
   (setq display-buffer-alist
	 '(("\\*mu4e-main\\*" display-buffer-at-bottom)))
```
(am a `display-buffer-alist` newbie though)

**Comment by averter** [comment]
Got it. It's 

```` lisp
   (setq display-buffer-alist
	 '(("\\*mu4e-main\\*" display-buffer-same-window)))
````
Hope this is helpful to others. 

The mystery of previous mu versions not deleting other windows will remain though. :-). Thanks both.

**Comment by djcb** [comment]
@averter This was just an example to show that you influence the way the main-buffer is shown, but great to see you found what's needed in this case! I've added some version of this to the manual too,
```
(add-to-list 'display-buffer-alist
             `(,(regexp-quote mu4e-main-buffer-name)
               display-buffer-same-window))
```

**Comment by bhankas** [comment]
@djcb this is unrelated, but is there a way to get a window config for mu4e as magit has? By which I mean, the default view is occupying the other half and every subsequent window uses the alternately previous half of the frame? Apologies if this isn't the right place, I would be happy to ask this elsewhere if so.

**Comment by djcb** [comment]
@bhankas: I suspect you can do that with customization of `display-buffer-alist`, I'd start there... there is a bit of a learning curve, but it's a powerful system.

**Comment by 88-percent** [comment]
Is there a specific point in my config I should be adding the elisp above to get the mu4e window to stop decimating the existing window layout? The value seems to be getting properly assigned but the main view still takes over all windows in frame.

```
display-buffer-alist is a variable defined in ‘window.el’.

Its value is
(("\\*mu4e-main\\*" display-buffer-same-window)
 ("^ \\*org-contact\\*" display-buffer-below-selected)
 ("^\\*Ilist\\*$" imenu-list-display-buffer))
Original value was nil

```

**Comment by averter** [comment]
> Is there a specific point in my config I should be adding the elisp above to get the mu4e window to stop decimating the existing window layout? The value seems to be getting properly assigned but the main view still takes over all windows in frame.
> 
> ```
> display-buffer-alist is a variable defined in ‘window.el’.
> 
> Its value is
> (("\\*mu4e-main\\*" display-buffer-same-window)
>  ("^ \\*org-contact\\*" display-buffer-below-selected)
>  ("^\\*Ilist\\*$" imenu-list-display-buffer))
> Original value was nil
> ```

@88-percent If you lookup my above mu4e configuration with use-package, the elisp code was placed in the BASICS section. Not sure if there are other places where it would not work.

**Comment by 88-percent** [comment]
@averter Thanks for the direction. I've tried adding the elisp in the same place in my config but still can't get this working. I'm on Spacemacs, so I'm thinking there must be something I'm missing in my config. 

I was hoping I might be able to work around this by creating links to searches as the links open in their own window as expected. I can get these searches opening in the window they were called, but unfortunately quitting out of these windows also brings up the `main-view`, killing my window set up.

Can anyone help me to understand the use case for this feature? I'm relatively new to this, but from my experience so far a mode wiping all windows in a frame just seems kind of un-Emacs-like to me. Maybe my workflow is wrong?

**Comment by 88-percent** [comment]
I've been able to get this [working for Spacemacs](https://github.com/syl20bnr/spacemacs/issues/16507#issuecomment-2269316477). Turns out it _was_ an issue with my workflow, just not in the way I expected: the trick is to never quit mu4e and let it run in the background.
