### ISSUE TITLE
[mu4e bug] Unable to read mails, "no message at point"

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#2387]
**Describe the bug**

From mu4e headers buffer, pressing RET on an email does nothing and mu4e emit a message (not an error) "no message at point".
This is not reproductible from 1.9.4, it appears just after at the introduction of mu4e-window.el.

**How to Reproduce**

My guess is some check is done on an empty buffer (not already feeded) but I have not the time right now to give more infos.
I will try to look into this as soon as possible.
For now I must use 1.9.4 as last mu is unusable for now.

**Environment**
System:    Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: N/A Desktop: Xfce 4.16.0 Distro: Linux Mint 20.3 Una
           base: Ubuntu 20.04 focal
Emacs 28.2.

**Checklist**
- [ X] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [ X] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [ X] you have read all of the above

**Comment by djcb** [comment]
Just a guess, do you have a custom `mu4e-view-mode-hook` defined? That one now fires early, before the message is rendered; and there's `mu4e-view-rendered-hook` that fires _after_ the message has been rendered. See NEWS.org.

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> Just a guess, do you have a custom mu4e-view-mode-hook defined? That
> one now fires early, before the message is rendered; and there's
> mu4e-view-rendered-hook that fires after the message has been
> rendered. See NEWS.org.

Thanks for this, I used indeed mu4e-view-mode-hook, I have changed in my
config to mu4e-view-rendered-hook but it changed nothing, I have same
error, thus you are now using display-buffer-full-frame in last commits
which is not available in Emacs-28 but it is another problem easy to
fix.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto ***@***.***> writes:

> "Dirk-Jan C. Binnema" ***@***.***> writes:
>
>> Just a guess, do you have a custom mu4e-view-mode-hook defined? That
>> one now fires early, before the message is rendered; and there's
>> mu4e-view-rendered-hook that fires after the message has been
>> rendered. See NEWS.org.
>
> Thanks for this, I used indeed mu4e-view-mode-hook, I have changed in my
> config to mu4e-view-rendered-hook but it changed nothing, I have same
> error, thus you are now using display-buffer-full-frame in last commits
> which is not available in Emacs-28 but it is another problem easy to
> fix.

I finally found what's wrong, it was indeed with the mu4e-view-mode-hook
which is used by the autocrypt package (it should use instead
mu4e-view-rendered-hook).

I had to use `error` instead of `user-error` in mu4e-warn to have a
backtrace, then it was easy to find what was going on.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto ***@***.***> writes:

> Thierry Volpiatto ***@***.***> writes:
>
>> "Dirk-Jan C. Binnema" ***@***.***> writes:
>>
>>> Just a guess, do you have a custom mu4e-view-mode-hook defined? That
>>> one now fires early, before the message is rendered; and there's
>>> mu4e-view-rendered-hook that fires after the message has been
>>> rendered. See NEWS.org.
>>
>> Thanks for this, I used indeed mu4e-view-mode-hook, I have changed in my
>> config to mu4e-view-rendered-hook but it changed nothing, I have same
>> error, thus you are now using display-buffer-full-frame in last commits
>> which is not available in Emacs-28 but it is another problem easy to
>> fix.
>
> I finally found what's wrong, it was indeed with the mu4e-view-mode-hook
> which is used by the autocrypt package (it should use instead
> mu4e-view-rendered-hook).

I have reported the bug and it should (partially) be fixed:

https://git.sr.ht/~pkal/autocrypt/commit/dd400cbbdfa14e6127f29cf9b562a8948ff3fafd#autocrypt-mu4e.el-1-5

-- 
Thierry

**Comment by djcb** [comment]
@mickeynp: would it be possible to invoke `(mu4e-view-mode)` later, after we've fully created message? I suspect `mu4e-view-mode-hook` is fairly widely used, and it'd be nice if users don't have to update to some other hook.

**Comment by mickeynp** [comment]
It probably is, the only rules we need to abide are:

1. We cannot display a buffer until we feel it's ready -- i.e., after the text is ready, as the display code a user has might resize it depending on its contents.
2. We cannot display a mode-less buffer, as we cannot rely on its name (it might have a name different from the one we gave it.)

Provided we meet those two goals, it should be fine.

**Comment by djcb** [comment]
@thierryvolpiatto:  with the current master, (with `mu4e-view-rendered-hook`, and the back-ported `display-buffer-full-frame`) do things now work as expected?

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> @thierryvolpiatto: with the current master, (with
> mu4e-view-rendered-hook, and the back-ported
> display-buffer-full-frame) do things now work as expected?

Yes, all right. Thanks.

>
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by djcb** [comment]
Thanks! Closing this one.
