### ISSUE TITLE
[mu4e rfe] Make indexing not block reading

### ISSUE THREAD

**Issue by dcolascione** [djcb/mu#2388]
Often, I find myself waiting for tens of seconds on mu indexing my inbox when browsing emails in mu4e. I have large mailboxes, and sometimes mu takes a few tens of seconds to scan them after updates. If mu's index update operation happens to coincide with my browsing email, I'm forced to wait for indexing to complete, causing mu4e to appear to hang on "loading message".

I'd like to be able to read email without long delays. Could mu4e somehow interrupt a background indexing operation if a higher-priority interactive request comes through to the daemon? True concurrent indexing and querying would be even better, but sounds harder to implement.

**Comment by djcb** [comment]
In fact `mu4e` (or the mu4e server) does run the indexing process in a worker thread (1.8+), but there can indeed be a bit of latency.... 10s of seconds sounds extreme though!

**Comment by djcb** [comment]
This is the same issue as in #2320, so closing this one.
