### ISSUE TITLE
[mu bug] build system is broken, breaking my system

### ISSUE THREAD

**Issue by gnusupport** [djcb/mu#2397]
Your build system is broken in the sense that you are changing maybe to meson, but that breaks stuff on my system.  I cannot normally use ./configure, make, make install, and make -n does not show me what would be done, then finally everything get installed in /usr/local which I did not choose, totally surprising, without me being in control.

**Comment by djcb** [comment]
We've moved to use `meson`, and that's not a bug. It works a little different from autotools, but you are still in control, just pass the desired parameters to meson instead.

Frankly, I'm not quite sure what you intend to accomplish with this "bug report".

**Comment by theophilusx** [comment]
I don't think that your unfamiliarity with the chosen build system for mu/mu4e is a bug. The README.org file seems to cover the build process accurately and includes details regarding the alternative build process via a supplied makefile which 'simulates' the old build process. It even includes a pointer to the meson documentation which details the additional options, such as setting the prefix to control where the software is installed. 

If you feel the README.org file is lacking in details or needs further clarification, I'm sure djc would welcome a PR aimed at improving it!

**Comment by gnusupport** [comment]
Thanks, I found it now in README.
