### ISSUE TITLE
[mu4e bug] mu4e-headers-prev-unread and mu4e-headers-next-unread don't work anymore

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#2398]
**Describe the bug**

The commands `mu4e-headers-prev-unread` and `mu4e-headers-next-unread` bound to the keys `[` and `]` could be used to select the previous/next unread message in the headers buffer.  With the latest master (b9841942), they move point to the prev/next unread message but don't select it.  From an article view, they don't move point in the headers buffer and seem to re-load the current message again.

I think they used to move point in the headers buffer and also used to select the prev/next message for viewing but I'm not entirely sure.  Until now, my unread bookmark contained only unread messages so I mostly used `n` and `p` but it seems now includes also all/some seen messages from the threads that have unread messages. (What is the cause for that?)

**How to Reproduce**

Open a bookmark / shortcut with unread messages and hit `[` and `]` in the headers and the article views.

**Environment**

mu & emacs git masters

**Checklist**
- [X] you are running either an 1.8.x release or the latest 1.9.x development release
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [X] you have read all of the above

**Comment by djcb** [comment]
I'll take a look.

**Comment by tsdh** [comment]
The part
```
Until now, my unread bookmark contained only unread messages so I mostly used n and p but it seems now includes also all/some seen messages from the threads that have unread messages. (What is the cause for that?)
```
is caused by me having customized `mu4e-headers-include-related` to `nil` but now that variable is `mu4e-search-include-related` and so my customizations don't apply anymore.  So that part is related to #2399.  I guess you should really use `define-obsolete-variable-alias` and make sure that `mu4e-obsolete` is loaded before anything else so that customizations for the old variables are applied correctly.

**Comment by djcb** [comment]
Sure -- I moved things around a bit and use `define-obsolete-variable-alias` now; and `mu4e-obsolete` comes as the very first in `mu4e.el`. Does that help?

**Comment by tsdh** [comment]
Yeah, it does help.  I've changed my config to the old name again, and now my customization is appropriately set for the new name, the old name being an alias.  Thanks.

The main issue of `[` & `]` not selecting the next/prev message for viewing in headers and only re-loading the current message in the article buffer still stands.

**Comment by djcb** [comment]
Yeah, I can reproduce that.

**Comment by tsdh** [comment]
Works, thank you!
