### ISSUE TITLE
[mu4e bug] Storing org-links to messages no longer works in article view

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#2400]
**Describe the bug**

`org-store-link` works in headers view but no longer in article view.  In article view, I get the following message with debug mode on:

```
Debugger entered--Lisp error: (void-variable mu4e~view-message)
  #f(compiled-function (&optional noerror) "Get the message s-expression for the message at point.\nEither the headers buffer or the view buffer, or nil if there is\nno such message. If optional NOERROR is non-nil, do not raise an\nerror when there is no message at point." #<bytecode 0x1591f7796e64970a>)()
  mu4e--org-store-link-message()
  mu4e-org-store-link()
  org-store-link(nil 1)
  funcall-interactively(org-store-link nil 1)
  call-interactively(org-store-link nil nil)
  command-execute(org-store-link)
```

A bit strange because I can't find `mu4e~view-message` anywhere mu4e's code.

Not sure whether it is relevant but I'm using single-window mode.

**How to Reproduce**

1. Open a message.
2. `org-store-link`.

I confirmed that I can reproduce the problem with vanilla Emacs and just mu4e loaded (no other packages) and org 9.6-g30314c from MELPA.

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

- Ubuntu 22.04
- Emacs 29.0.50 from git
- Current mu/mu4e from git
- Org from MELPA

**Checklist**
- [X] you are running either an 1.8.x release or the latest 1.9.x development release
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [X] you have read all of the above

**Comment by djcb** [comment]
Sounds like a byte-compilation problem. Can you try with a clean rebuild?

**Comment by tmalsburg** [comment]
I thought that I had rules this possibility out, but no.  It works now.  Sorry for the noise.
