### ISSUE TITLE
Can't read any message

### ISSUE THREAD

**Issue by duksosleepy** [djcb/mu#2405]
**Describe the bug**
I can't see any messages with mu4e in emacs. When I tap on the message, emacs says something like this:
mu4e-warn: [mu4e] No message at /c/cygwin64/home/THAY PHACH/.mail/G/INBOX/new/1673174404_1.1680.DESKTOP-STCK637,U=28225,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
Although I can still view messages with bash command from shell: mu view.
Now what do I need to do to fix this?

**How to Reproduce**
- M-x mu4e
- Type j-i to see inbox
- Press Enter in any header

**Environment**
MS Windows 10
mu version 1.9.2
emacs version 28.2

**Checklist**
- [ x] you are running either an 1.8.x release or the latest 1.9.x development release
- [x ] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [ x] you have read all of the above

**Comment by djcb** [comment]
Mu doesn't really support Windows (although @damon-kwok was successful with it). Likely, it's a problem with the `:` character not being supported on Windows filesystems. So I'm afraid we can't help here.

**Comment by duksosleepy** [comment]
Okay, i mean. Thank you so much !!!

**Comment by damon-kwok** [comment]
@duksosleepy I haven't used cygwin. I've been using MSYS. Usually I encounter some strange problems under Windows, most of which are related to directory habits and need to be set up in ELISP. This requires some Linux and ELisp knowledge.

**Comment by duksosleepy** [comment]
@damon-kwok I built mu based on github.com/msys2-unofficial/MSYS2-packages and using Offlineimap build from Cygwin. Because mu supports exclamation points as mentioned in #1112, I changed the filename structure to be able to use mu. However I think the only problem here is that mu4e still doesn't support the exclamation point, I'm still hoping for something.

**Comment by damon-kwok** [comment]
Have you tried mbsync?
[isync.sf.net](https://isync.sourceforge.io/)

**Comment by duksosleepy** [comment]
I will try it  👍 Thank you so much !
