### ISSUE TITLE
[mu4e bug] Mu4e menu appears twice 

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#2406]
**Describe the bug**

The Mu4e menu appears twice when menu-bar-mode is on.  Sometimes both menus have the same entries (refresh, search bookmark, narrow search, previous query, next query), but sometimes the second menu is empty.  Can't reconstruct the conditions under which each is the case.  I think the second menu is consistently populated with entries at first, but later emptied.

Not sure the following is a bug: The Mu4e menu used to have many more entries covering most of Mu4e's functionality.  Now it's really stripped down to a small set of functions.

**How to Reproduce**

- Open headers view.
- Activate menu-bar-mode if necessary.
Result: Two "Mu4e" menus.

**Environment**
- Ubuntu 22.04
- Current Emacs from source
- Current mu/mu4e from source
- I'm using single-window mode in Mu4e.

**Checklist**
- [X] you are running either an 1.8.x release or the latest 1.9.x development release
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [X] you have read all of the above

**Comment by djcb** [comment]
Yeah, that's broken, can reproduce.

**Comment by djcb** [comment]
Okay, fixed... the menus could be improved further (but not sure how much they are used...), but that's for another day!

**Comment by tmalsburg** [comment]
Just tried it but now I get no Mu4e menu at all.

**Comment by tmalsburg** [comment]
Oh, sorry, I see that the names of the menus have changed ("Headers" and "View").  Great.  Thank you!
