### ISSUE TITLE
seen flag and unread flag are not mutually exclusive

### ISSUE THREAD

**Issue by derek-zhou** [djcb/mu#2409]
**Describe the bug**
In 1.6.x, if I set a mail with `"+S"` the `unread` flag will be cleared automatically. However, in 1.8.x (tested with 1.8.13), `"+S"` will add the `seen` flag only without clearing the `unread` flag, resulting in the inconsistent both `seen` and `unread` set at the same time. I have to do `"+S-u"` instead.

**Comment by djcb** [comment]
This are mu internals, so I wouldn't depend on such details. Anyway, I've updated  things.

**Comment by derek-zhou** [comment]
Thanks. I am using `mu server`, which I understand is internal to mu/mu4e. However, I see no alternative: invoking mu each time and parse the output is both much slower and harder. I really like the client/server architecture and the simple S-exp interface of `mu server`.
