### ISSUE TITLE
[mu bug] mu find --format=plain --fields "x" truncates output lines to 79 characters

### ISSUE THREAD

**Issue by ddoherty03** [djcb/mu#2410]
**Describe the bug**
I use a script to write a file of all labels (or tags) in my email corpus after each sync with offlineimap.  The starting point of the script is this mu-find query:

```
  mu find --format=plain --fields="x" 'not g:l' |
  grep -v '^ *$' |
  awk -F',' 'BEGIN{OFS="\n";} {for (i=1; i <= NF; i++) print $i}' |
  grep '^[\[A-Za-z\\]' |
  sort -u
```
I noticed, however, that I was getting some strange labels in the file, like '\Importan' and '\Importa', etc.  However, if I search my emails for those labels, the result is no messages.

It appears that the output from the `mu find` command is truncating the list of labels to 79 characters, so I get a lot of spurious labels in the output.

**To Reproduce**
Run

```
mu find --format=plain --fields="x" 'not g:l' |
awk 'length > 79'
```
You should get some output if you use labels ala gmail extensively.  Replacing 79 with something like 20 should almost always result in output.

**Environment**
Running mu version 1.78

**Checklist**
- [X ] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).
Ubuntu 22.04.1 LTS

**Comment by djcb** [comment]
Can you attach a single raw message where this happens? I.e.,. one with such a long tag?

**Comment by ddoherty03** [comment]
Sure.  Here is one, it gives me flags of:

```
Cases/AytuBioscience---ArmisticeCapital,Cases/ReviveJDoherty,CategoryPrimary,\I
```
[long-key-email.txt](https://github.com/djcb/mu/files/10418722/long-key-email.txt)

I had to delete the attachments and other comment, as they are confidential, but all the headers are there.

**Comment by djcb** [comment]
I get:
```
% mu find maildir:/inbox --fields=x
Cases/AytuBioscience---ArmisticeCapital,Cases/ReviveJDoherty,CategoryPrimary,\Important
```
and
```
% mu view ~/Maildir/inbox/cur/long-key-email.txt:2,S
From: James Doherty <jim@jdoherty.net>
To: Daniel E. Doherty <ded@ddoherty.net>
Subject: STATEMENT REQUEST
Date: 2021-09-02T23:54:53 EEST
Tags: Cases/AytuBioscience---ArmisticeCapital, Cases/ReviveJDoherty, CategoryPrimary, \Important
```

perhaps test without `awk`? If you're really using mu 1.7.8, I recommend upgrading to the latest release.

**Comment by ddoherty03** [comment]
Thanks for testing.  I will try the upgrade.

**Comment by ddoherty03** [comment]
OK.  I updated to 1.8.11 and the issue seems to be solved there.  I no longer see the truncation.  I will close this issue.  Many thanks.

**Comment by djcb** [comment]
Don't think anything relevant changed on the mu/mu4e side, but good to hear that the problem is gone now.
