### ISSUE TITLE
[mu4e bug] Wrong unread count in bookmark

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#2412]
**Describe the bug**

Since very, very recently on mu master, my `bu` bookmarks shows wrong unread count.  Right now it shows
![image](https://user-images.githubusercontent.com/103854/212531729-e4add25c-f842-4edd-acaa-1bd12fd995fa.png)
but executing it with `b u` gives an empty headers buffer with `No matching messages found` (which I think is correct).

I've re-indexed all my mail but that didn't help.

The bookmark has the following (generated) definition:

```elisp
(:name "Unread messages (w/m)"
       :query "flag:unread AND (contact:XXX@gnu.org OR contact:XXX@fastmail.fm OR contact:/XXX\\+.*@fastmail\\.fm/ OR contact:YYY@fastmail.fm OR contact:XXX@fastmail.de ...)"
       :key 117)
```
Searching for the `:query` gives no result as expected.

I also have some quite involved `mu4e-query-rewrite-function` which restricts queries to maildirs belonging to my current context.

```elisp
  (defun th/mu4e-query-rewrite-function (query)
    (cond
     ;; No rewriting if we have a maildir restriction.
     ((string-match-p "\\<maildir:" query) query)
     ;; No rewriting if we have a !g (global) marker (just remove it).
     ((string-match "\\(!g\\)" query)
      (replace-match "" nil nil query 1))
     ;; Otherwise, restrict to context maildirs and remove delete-boring groups.
     (t (let ((q (concat
                  query
                  (when th/mu4e-context-maildir-regexp
                    (format " AND maildir:\"/%s/\""
                            th/mu4e-context-maildir-regexp))
                  ;; Don't consider delete-boring groups such as trash and spam.
                  (format " AND NOT maildir:\"/%s/\""
                          (regexp-opt '("/Junk Mail" "/Spam" "/Trash"
                                        "/Papierkorb"
                                        "/Deleted Items" "/training/"))))))
          ;;(message "Rewritten query: %s" q)
          q))))

  (setq mu4e-query-rewrite-function
        #'th/mu4e-query-rewrite-function)
```
I think that is the culprit.  When I execute the query with `!g` prefix which, as you can see, deactivates rewriting, I get a headers view with 632 lines.  Not exactly 638 as the main buffer shows but close.

So can it be that the `mu4e-query-rewrite-function` isn't considered anymore for the message counts in main?  Oh, yeah, that seems likely because I get the same counts in every context.  So clearly my maildir restrictions stopped working.

**How to Reproduce**

See above: define a  `mu4e-query-rewrite-function` restricting searches automatically.  It seems to be not considered anymore for the message counts.

**Environment**

GNU/Linux, Emacs and Mu master

**Checklist**
- [X] you are running either an 1.8.x release or the latest 1.9.x development release
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [X] you have read all of the above

**Comment by djcb** [comment]
Yes, rewrite functions are not considered for the query items/baseline counts, it gets rather complicated / unreliable otherwise since query are _also_ used to identify what queries they belong to... which has gotten a lot more complicated recently.

But I'll see what I can do...

**Comment by djcb** [comment]
I'm working on this.

**Comment by tsdh** [comment]
@djcb At first glance, it seems to work, thank you. :-)

**Comment by djcb** [comment]
Oh, that's great. I put a candidate fix in, but didn't fully test it yet.
