### ISSUE TITLE
[mu4e bug] mu4e--view-gather-mime-parts empty when

### ISSUE THREAD

**Issue by progfolio** [djcb/mu#2416]
**Describe the bug**

`mu4e--view-gather-mime-parts` contains a `when` form with an empty body. Likely the result of a missing paren. This prevents the function from ever returning any parts.

```emacs-lisp
(when (and part (numberp index) (not (assoc index parts))
           (push `(,index . ,part) parts)))
```

VS

```emacs-lisp
(when (and part (numberp index) (not (assoc index parts)))
  (push `(,index . ,part) parts))
```

**Comment by djcb** [comment]
Hmm,. indeed likely a misplaced bracket, but seems the `push` would still take place since its evaluate as part of the `and`.

**Comment by progfolio** [comment]
Ah, yes. By side effect. In that case I suggest dropping the when altogether.
