### ISSUE TITLE
[mu bug] Cannot use dashes in search

### ISSUE THREAD

**Issue by tangential-info** [djcb/mu#2418]
**Describe the bug**

Tried to search `mu find -f t to:"foo-bar", but get

```
no matches for search expression
```

**To Reproduce**

Have an email in Maildir with a to field like `To: foo-bar <x@y.z>`.

**Environment**

```
mu --version                                                                                    ~
mu (mail indexer/searcher) version 1.8.11
Copyright (C) 2008-2022 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Checklist**
- [ ] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

Not sure how to assess if that checklist is still correct.

**Comment by djcb** [comment]
Known limitation, unfortunately; #2167

**Comment by tangential-info** [comment]
Ah, apologies, had too many tabs open, will track that issue, thank you.
