### ISSUE TITLE
Why is mu4e-modeline-mode global?

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#2419]
**Describe the bug**

When switching to another buffer than mu4e, the mu4e mode-line is still there hiding important infos. I must turn off manually `mu4e-modeline-mode`.

**How to Reproduce**

M-x mu4e
then switch to another buffer, the mu4e mode-line is still here occupying most of the mode-line which is annoying.

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.
Emacs-28.2, LinuxMint, mu4e 1.9.15.

**Checklist**
- [X] you are running either an 1.8.x release or the latest 1.9.x development release
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [X] you have read all of the above

**Comment by djcb** [comment]
What do you exactly see in your modeline when in/outside of `mu4e`?

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> What do you exactly see in your modeline when in/outside of mu4e?

More or less the same as what I have when I am in Mu4e.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Also the unread email counter is no more updated, I have to quit[1] the
mu4e main buffer and back to it to have the unread counter updated.

[1] I quit mu4e main buffer with:

    (defun tv/mu4e-quit-window ()
      (interactive)
      (quit-window)
      (mu4e-modeline-mode -1))


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Another thing, what does  "Unread  messages (1(+1)/1)" means, why is "(+1)" needed?

**Comment by djcb** [comment]
The modeline is partly local (the context/current header parts), and partly global (the "favorite" bookmark counts); you probably hit some caching issue.   The (+1) is the "delta unread from baseline; see NEWS.org / and the manual it links to.

**Comment by djcb** [comment]
I've a bunch of changes (0.9.16) that should help; but this is still experimental.

**Comment by djcb** [comment]
Note, the above complaints should be addressed now... closing this.

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> Note, the above complaints should be addressed now... closing this.

Ok thanks, will have a look soon.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry
