### ISSUE TITLE
Send Error: "message-send: No methods specified to send by" [mu4e bug]

### ISSUE THREAD

**Issue by mclearc** [djcb/mu#2427]
**Describe the bug**
I've just updated to the most recent version of mu/mu4e. I was previously on mu 1.6.x.
I cannot send email, though I can receive emails fine. Whenever I send an email, I get the message "message-send: No methods specified to send by" and the message fails to send. 

**Please provide a clear and concise description of what you expected to happen
and what actually happened.**

I expected to be able to send email messages. I was not able to send the message. 

**How to Reproduce**

Include the exact steps of what you were doing (commands executed etc.). Include
any relevant logs and outputs.

1. Compose email
2. Try and send email
3. Get error message

I have `(setq message-send-mail-function #'smtpmail-send-it)` and the proper smtp server settings for my two contexts. 

If this is about a specific (kind of) message, attach an example message. (Open
the message, press `.` (`mu4e-view-raw-message`), then `C-x C-w` and attach.
Anonymize as needed, all that matters is that the issue still reproduces.

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

MacOS Ventura 13.2. Emacs 29. mu/mu4e 1.8.14

I would place the blame most likely on Ventura (bc Ventura is terrible). I doubt it is emacs 29. Thank you for any help you can provide!

**Checklist**
- [X] you are running either an 1.8.x release or the latest 1.9.x development release
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [X] you have read all of the above

**Comment by djcb** [comment]
This seems like a configuration issue that the `message-send` function is complaining about.
Perhaps `message-send-method-alist` is empty? Is there any other information in the Messages buffer?

**Comment by mclearc** [comment]
> Perhaps message-send-method-alist is empty? 

Here's what I have: 

```lisp
((news message-news-p message-send-via-news)
 (mail message-mail-p message-send-via-mail))
```

Unfortunately there isn't any other info in the messages buffer (nor in any other buffers, warning, etc) that I can see.

**Comment by mclearc** [comment]
Just as an FYI -- it looks like a hook I had set to make sure that message frames closed after sending was causing the problem. I deleted `(add-hook 'message-send-hook (lambda () (delete-frame)))` and send mail worked as expected.
