### ISSUE TITLE
[mu bug] Subject field from some emails show only first line

### ISSUE THREAD

**Issue by altwazar** [djcb/mu#2429]
**Describe the bug**

With some emails when subject field in email file folded into multiple lines mu find (and mu4e in mu4e-headers-mode) show (and search) only text from first line in mail list.

**How to Reproduce**
Example of same subject text with different folding.
Bad (only first line is displayed):
```
Subject: =?UTF-8?B?0JTQtdC90LjRgSwg0L7QsdC90L7Qsg==?=
 =?UTF-8?B?0LjRgtC1INGA0LXQt9GO0LzQtSDigJQg?=
 =?UTF-8?B?0L/QvtGP0LLQuNC70LjRgdGMINC90L4=?=
 =?UTF-8?B?0LLRi9C1INCy0LDQutCw0L3RgdC40Lgh?=
```
Good :
```
Subject: =?utf-8?B?0JTQtdC90LjRgSwg0L7QsdC90L7QstC40YLQtSDRgNC10LfRjtC8?=
 =?utf-8?B?0LUg4oCUINC/0L7Rj9Cy0LjQu9C40YHRjCDQvdC+0LLRi9C1INCy0LDQutCw?=
 =?utf-8?B?0L3RgdC40Lgh?=
```

**Environment**
OS: Gentoo
Mu: 1.8.13

**Comment by djcb** [comment]
I get:
```
   Subject:  Денис, обновите резюме — появились новые вакансии!
```
in both cases, with `mu view` or `mu4e`. Are you seeing something different?

I'm using mu 1.9 with gmime 3.2.7.

**Comment by altwazar** [comment]
> Are you seeing something different?

`Денис, обнов` in `mu4e-headers` and `mu find`. With  mu i cant even find this message by full word `обновите`, but can by `обнов`. In `mu4e-view` Subject shown correctly.

Another example:
```
Subject: =?UTF-8?B?0YPQstC10LTQvtC80LvQtdC90LjQtSDQv9C+INC60LDQv9C40YLQsNC70Yw=?=
 =?UTF-8?B?0L3QvtC80YMg0YDQtdC80L7QvdGC0YMg0LrRgNGL0YjQuCDQnNCa0JQg0YM=?=
 =?UTF-8?B?0Lsu0Jwu0KLQvtGA0LXQt9CwLDIw?=

```
Instead of `уведомление по капитальному ремонту крыши МКД ул.М.Тореза,20` i get `уведомление по капиталь`.

**Comment by djcb** [comment]
I get ` Subject: уведомление по капитальному ремонту крыши МКД ул.М.Тореза,20` . What version of `gmime` are you using? (it should should in the output the build process, a line like:
```
Run-time dependency gmime-3.0 found: YES 3.2.7
```
)

**Comment by altwazar** [comment]
>What version of `gmime` are you using?
Thank you, problem was with gmime version in gentoo (3.2.13 from https://github.com/jstedfast/gmime).
After recompiling mu with 3.2.7 version from https://download.gnome.org/sources/gmime/3.2/gmime-3.2.7.tar.xz and recreating index "subject" shown as expected. If i recreate index with 3.2.13 version problem returns.

**Comment by xzz53** [comment]
I also faced this issue on Arch (mu 1.8.9, gmime3 3.2.13). Looks like it was introduced in gmime v3.2.10 (https://github.com/jstedfast/gmime/issues/133), and fixed in https://github.com/jstedfast/gmime/commit/1a33a55baafc73b0a6d7f83cf4c30ad9e169669f (if I'm not mistaken, not in any tagged release yet).

I confirm that building gmime from https://github.com/jstedfast/gmime/commit/1a33a55baafc73b0a6d7f83cf4c30ad9e169669f and reindexing mail fixes the issue.

**Comment by djcb** [comment]
Thank you for checking this. 

I suppose there's not much we can do about this except for with for the new gmime release.
