### ISSUE TITLE
expose API for removing lockfile (command line, also Emacs)

### ISSUE THREAD

**Issue by tpapp** [djcb/mu#2433]
**Is your feature request related to a problem? Please describe.**

After an unexpected shutdown (eg using an unstable Emacs that has a bug unrelated to mu and having to kill it fix xkill), the lockfile remains.

**Describe the solution you'd like**

Expose the API in `mu` (command line) and `mu4e` for removing the lockfile. The advantage is that the user does not have to be aware of its path.

**Describe alternatives you've considered**

One can just `rm ~/.cache/mu/xapian/flintlock` or equivalent, but then the user needs to be aware of the path (which may change etc).

**Comment by djcb** [comment]
The lockfile is a Xapian implementation detail, which `mu` doesn't own (and the precise name may depend on the Xapian version / configuration etc.); it could also be dangerous to delete.

I'm also not quite sure why the lockfile is a problem; I've seen quite a few crashes with emacs and other "unclean" exits from the database, but I can't remember ever having to manually remove the lockfile, at least not in the last 5 years.

**Comment by djcb** [comment]
So, I'm afraid I have to decline this. Sorry!
