### ISSUE TITLE
[rfe] "half-cooked" mode for `mu extract` for attachment-names

### ISSUE THREAD

**Issue by benblank** [djcb/mu#2434]
**Describe the bug**

When using `mu extract` to save MIME parts as files, the filename from the email is used, but all spaces are replaced with dashes. In order to restore the original file names, each created file must have its name compared with that in the email, which is tedious when working with large numbers of attachments.

**To Reproduce**

1. Save the message below as `spaces.eml`.
2. In the same directory, run `mu extract --save-all "$(realpath spaces.eml)"`.
3. Observe that the file created for the attachment is named "foo-bar.js" (with a dash) rather than "foo bar.js" (with a space), as specified in the email.

```plaintext
MIME-Version: 1.0
Date: Wed, 15 Feb 2023 14:23:44 -0800
Subject: Transport
From: Ben Blank <ben.blank@gmail.com>
Content-Type: multipart/mixed; boundary=001a1142dd60b87bd10516af7e4f

--001a1142dd60b87bd10516af7e4f
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Just a quick example.

--001a1142dd60b87bd10516af7e4f
Content-Type: application/-xjavascript; charset=US-ASCII; name="foo bar.js"
Content-Disposition: attachment; filename="foo bar.js"
Content-Transfer-Encoding: base64
X-Attachment-Id: 0.1

Y29uc29sZS5sb2coImZvbyBiYXIiKTsK
--001a1142dd60b87bd10516af7e4f--
```

**Environment**

* Ubuntu 22.10 (Linux kernel 5.19.0)
* bash 5.2.2(1)-release
* mu 1.8.7 (installed via apt from <https://packages.ubuntu.com/kinetic/maildir-utils>)

**Checklist**

- [ ] you are running either the latest 1.8.x release, or a 1.9.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
It's not a bug, it's a feature. `mu extract` saves the "cooked" filename.

**Comment by benblank** [comment]
Is there an option to disable that feature? A file's name can be pretty important information. And having to parse the original file yourself to extract and compare file names seems to run contrary to mu's purpose. Are other characters removed, as well?

**Comment by djcb** [comment]
In mu those are  called "cooked" filenames (see `cooked_filename` in the source code for details. I prefer the cooked ones, (filenames with spaces are annoying), but sure a "half-cooked" version may be useful (i.e., you _still_ want to strip paths etc.). I'll turn this into an RFE.
