### ISSUE TITLE
[mu4e bug]  mu server process ended with exit code 1 mu 1.9.20

### ISSUE THREAD

**Issue by slyfr** [djcb/mu#2435]
**Describe the bug**

I installed mu 1.9.20, and I get the following error when launching mu4e in spacemacs : 

error in process sentinel: mu4e--server-sentinel: mu server process ended with exit code 1
error in process sentinel: mu server process ended with exit code 1

**How to Reproduce**

I removed all .el .elc files from previous mu4e installation

I did mu init and mu index

mu find works in the terminal

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

GNU Emacs 28.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2023-01-30

Spacemacs develop

**Checklist**
- [x] you are running either an 1.8.x release or the latest 1.9.x development release
- [ ] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [x] you have read all of the above

**Comment by slyfr** [comment]
I switched to mu 1.8.14 and things work again. It is a 1.9.20 issue.

**Comment by djcb** [comment]
1.9.21 (`master`) has the command `M-x mu4e-server-repl`, which may not be very useful in itself, but it should give you some clearer error on what's going on. Can you try that? Thanks.

**Comment by slyfr** [comment]
The message I obtain is :  ~invoked: ’/usr/local/bin/mu server --muhome=~/.cache/mu’~

**Comment by djcb** [comment]
Thanks... and did you see the repl (mu command line)?  If so, that shows that the basic setup works, and the problem is not there.

Another thing that may give some hint (after killing the repl buffer), 
```
(setq mu4e-mu-debug t)
```
Then,  `M-x mu4e-toggle-logging` and `M-x mu4e`. After that, check the `*mu4e-log*` buffer and see what it says. Thanks!

**Comment by slyfr** [comment]
When I try `M-x mu4e-server-repl` there is no repl showing up. Only the message I mentionned earlier.

However the repl `mu server` seems to work in the terminal (I tried the `view` command and got feedback about the corresponding message).

The message I get in *mu4e-log* is the following : 

2023-02-18 08:44:25.495 logging enabled
2023-02-18 08:44:30.524 * invoking '/usr/local/bin/mu' with parameters '--debug' 'server' '--muhome=~/.cache/mu'
2023-02-18 08:44:30.525 -> (queries :queries ("flag:unread AND NOT flag:trashed" "date:today..now" "mime:image/*"))
2023-02-18 08:44:30.525 -> (ping)
2023-02-18 08:44:30.525 -> (contacts :personal nil :after "2018-01-01" :tstamp "0" :maxnum nil)
2023-02-18 08:44:30.534 * Received 83 byte(s)
2023-02-18 08:44:30.534 * famous last words from server: 'error: ~/.cache/mu/xapian/iamglass: Failed to open glass revision file for reading
'
Note that the file ~/.cache/mu/xapian/iamglass does exist on my computer.

**Comment by djcb** [comment]
Aha... so I suspect it'll work if you _don't_ set `mu4e-mu-home`, just leave it at `nil`. Does that help?

**Comment by slyfr** [comment]
Now I get another error concerning the schema version of the database

2023-02-18 10:34:52.579 logging enabled
2023-02-18 10:34:58.712 * invoking '/usr/local/bin/mu' with parameters '--debug' 'server'
2023-02-18 10:34:58.713 -> (queries :queries ("flag:unread AND NOT flag:trashed" "date:today..now" "mime:image/*"))
2023-02-18 10:34:58.713 -> (ping)
2023-02-18 10:34:58.713 -> (contacts :personal nil :after "2018-01-01" :tstamp "0" :maxnum nil)
2023-02-18 10:34:59.897 * Received 115 byte(s)
2023-02-18 10:34:59.898 * famous last words from server: 'error: expected schema-version 466, but got 465
Please (re)initialize mu with 'mu init' see mu-init(1) for details
'
I have re-init an re-indexed the database several times.
I have checked ther version of mu I use to be sure there is no trouble with older install of mu/mu4e.

**Comment by djcb** [comment]
What does:
`$ mu info`
say?

**Comment by djcb** [comment]
...and what exact command did you use for `init`? Did it include `--muhome`?

**Comment by slyfr** [comment]
`mu info` says that the schema version is 466.

I did not include `--muhome` in the `init` command.

**Comment by slyfr** [comment]
The exact init command was `mu init --maildir=path-to-maildir --my-address=address1 --my-address=address2 && mu index`

**Comment by djcb** [comment]
But, the complete output for `mu info` would be useful (you can remove your email address of course).
And/or does `/usr/local/bin/mu info` give some different output?

It seem mu4e and mu are not looking at the same database.

**Comment by slyfr** [comment]
The oubput is 
+-------------------+--------------------------------+
| maildir           | ~/Maildir                      |  //changed /home/.../ to ~/
+-------------------+--------------------------------+
| database-path     | ~/.cache/mu/xapian             |  // same change as above
+-------------------+--------------------------------+
| schema-version    | 466                            |
+-------------------+--------------------------------+
| max-message-size  | 100000000                      |
+-------------------+--------------------------------+
| batch-size        | 250000                         |
+-------------------+--------------------------------+
| created           | sam. 18 févr. 2023 10:46:48    |
+-------------------+--------------------------------+
| personal-address  | xxxxx                          |
+-------------------+--------------------------------+
| messages in store | xxxxx                          |
+-------------------+--------------------------------+
| last-change       | sam. 18 févr. 2023 10:50:59    |
+-------------------+--------------------------------+
| last-index        | sam. 18 févr. 2023 10:51:00    |
+-------------------+--------------------------------+

**Comment by djcb** [comment]
That all looks good. 

What about the output of `/usr/local/bin/mu info` , is it the same?
And what's the output of `$ tree ~/.cache/mu`?

**Comment by slyfr** [comment]
The output of `/usr/local/bin/mu info` is the same.
As for `tree ~/.cache/mu` I get

~/.cache/mu
└── xapian
    ├── docdata.glass
    ├── flintlock
    ├── iamglass
    ├── position.glass
    ├── postlist.glass
    └── termlist.glass

**Comment by djcb** [comment]
Hmmm, and I guess you get:
```
$ xapian-metadata get ~/.cache/mu/xapian schema-version
466
```
The 465 must be coming from somewhere, seems you still  have a database with the _old_ schema, and that's the one `mu server` finds, but only when called from `emacs`, not from the command line...   perhaps try:
```
$ find ~/ -type d -a -name xapian 2>/dev/null
```
to find them.

Or maybe it's somewhere in the current structure; you could try remove `~/.cache/mu`, re-init/index.

**Comment by slyfr** [comment]
You are right there is another xapian db. It is in ~/snap/common/.cache/mu

I removed it but emacs seems to still look into this directory instead of the ~/.cache/mu/xapian one.

FYI, I use the snap package for emacs on ubuntu.

**Comment by slyfr** [comment]
I set the mu4e-mu-home variable to the xdg file path and it now works.
Instead of using ~/.cache/mu path as it was set earlier, I use its expanded version.
The way paths and default paths are used in emacs always puzzles me.
