### ISSUE TITLE
[mu4e rfe] Allow switching context as part of a bookmark

### ISSUE THREAD

**Issue by peterhoeg** [djcb/mu#2437]
**Is your feature request related to a problem? Please describe.**
1. I have multiple bookmarks defined which show an unread count. 
2. I have multiple accounts (and multiple contexts as a consequence)
3. I have bookmarks that jump to a specific "folder" in given account 

```
  Bookmarks

	⚫ bh hoeg inbox
	⚫ bc hoeg action             (8/25)
	⚫ bf hoeg drafts             (0/0)
	⚫ bs foobar inbox
	⚫ ba foobar action           (7/33)
```

My issue is that for the inboxes, I have defined my query as a function that also switches context, but now the unread count is not showing.

**Describe the solution you'd like**
The switching of contexts is separate from the query that runs (and doing the unread counts), so ideally I would like to be able to just tag a bookmark with a context and have mu4e switch to the given context when using the bookmark. This would allow auto-switching and give me a normal unread count.

**Describe alternatives you've considered**
Alternatively, still have the unread count returned when `:query` is a function, but that just seems ugly as it mixes concerns that shouldn't be.

**Comment by djcb** [comment]
Having a context-switch as the side-effect of a bookmark query? 

That sounds confusing to me! But not to your, obviously.  

I guess  I'd recommend using `mu4e-search-bookmark-hook` if you want  that, no need to (further!) complicate the built-in search mechanism  (but perhaps it's not even needed to switch context; perhaps that's only needed when composing mail? And you can easily handle the context then).
