### ISSUE TITLE
[mu bug]

### ISSUE THREAD

**Issue by Airwan** [djcb/mu#2438]
**Describe the bug**
Error at compilation on Freebsd : 

```
../lib/message/mu-mime-object.ccmu-mime-object.cc:543:6: error: use of undeclared identifier 'S_IRUSR'
                                        S_IRUSR|S_IWUSR,
                                        ^
../lib/message/mu-mime-object.cc:543:14: error: use of undeclared identifier 'S_IWUSR'
                                        S_IRUSR|S_IWUSR

```

**To Reproduce**
Run
meson build && ninja -C build

**Environment**
Freebsd 13.1 & mu 1.9.21 

**Possible solution**

Added **#include <sys/stat.h>** to mu-mime-object.cc seems to solve the problem.

**Comment by djcb** [comment]
Pushed a change for this.. does it compile now?

**Comment by Airwan** [comment]
This works fine now! Thanks.
