### ISSUE TITLE
[misc/code change discussion] Remove special characters from query before handing it to Xapian

### ISSUE THREAD

**Issue by ShayAgros** [djcb/mu#2444]
**Note**: for questions, please use the mailing-list: https://groups.google.com/g/mu-discuss

Hi,
This is a great package, and after digging a little into the source code I've got to say that it's quite and achievement to write something as impressive as this.

**Describe the issue**
I'm using mu + mu4e. Part of my job involves going over mailing lists for the Linux kernel which often have emails with the following format:
`[Patch KERNEL_TREE VERSION patch_nr/total_patches] subsystem_delimited_with_colon: patchset title`

For example
`[PATCH net v1 0/6] net: dsa: microchip: ksz8: fixes for stable`

Unfortunately searching for strings containing the characters `[]/:` doesn't end up finding up anything. E.g.
`mu find subject:\"PATCH net v1 0/6 net: dsa: microchip: ksz8: fixes for stable\"`
returns zero results.

At first I was hopeful that it's a mu issue with tokenizing the string, but unfortunately it seems like Xapian ends up receiving this string and fails to find anything. I'm currently not willing to dive into Xapian source code and I couldn't find documentation describing why these characters are special.

Trial and error showed that when removing the special characters, the correct results are returns:
```
$ mu find subject:\"PATCH net v1 0 6 net dsa microchip ksz8 fixes for stable\"   
Wed 22 Mar 2023 04:31:24 PM IST Oleksij Rempel <o.rempel@pengutronix.de> [PATCH net v1 0/6] net: dsa: microchip: ksz8: fixes for stable
```

**Suggested change**
Assuming that the user prefers to get less accurate results than nothing at all `mu` could remove such special characters before passing the query to Xapian. E.g. something like this (I apologize for my lousy CPP skills... I haven't touched it since college \\=):
```diff
diff --git a/lib/mu-parser.cc b/lib/mu-parser.cc
index 5f710ed7..92180afc 100644
--- a/lib/mu-parser.cc
+++ b/lib/mu-parser.cc
@@ -248,7 +248,12 @@ Parser::Private::value(const FieldInfoVec& fields,
                        size_t              pos,
                        WarningVec&         warnings) const
 {
-       auto val = utf8_flatten(v);
+       std::string val{v};
+
+       val.erase(std::remove(val.begin(), val.end(), ':'), val.end());
+       val = utf8_flatten(val);
 
        if (fields.empty())
                throw BUG("expected one or more fields");
```

Here I just remove colon characters, but a more robust solution is needed since terms like `1/4` need to be translated into `1 4` rather than `14`.

I don't mind writing a more wholesome and robust solution but wanted to consult here fist

**Environment**
I'm using Ubuntu 20.04 with `master` branch `mu`. Don't think the issue is environment dependent.

**Comment by djcb** [comment]
Basically  the same issue as in #2167 which has some more discussion, so closing this one. Thanks!
