### ISSUE TITLE
[mu4e bug] Notification not always triggered

### ISSUE THREAD

**Issue by OlMon** [djcb/mu#2447]
**Describe the bug**

Notifications are not always triggered because the variable `mu4e--last-delta-unread` is not properly updated.

**How to Reproduce**
I hope this is correct:
Start Mu4e.
Get an E-Mail in your favorite bookmark. Notification is present.
Check Bookmark without reading the mail.
Get E-Mail in your favorite bookmark, notification will not trigger.

Checking some code I notice the following:
```
(plist-get (mu4e-bookmark-favorite) :delta-unread)
```
Will evaluate to 0, but `mu4e--last-delta-unread` is still 1.
So after getting the E-Mail the `when` condition `(not (= delta-unread mu4e--last-delta-unread))` 
inside `mu4e--default-notification-filter` will evaluate to nil and the notification will not trigger. 

As far as I can see `mu4e--last-delta-unread` is never changed back to zero. This should probably  happen when the *mu4e-main* buffer is visited.

**Environment**
Arch Linux
Emacs current 29 Build.
mu/mu4e 1.10.0

**Checklist**
- [X] you are running either an 1.8.x release or the latest 1.9.x development release (1.10 old template?)
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [X] you have read all of the above

Thanks for the  great work and have a nice day.

Cheers!

**Comment by djcb** [comment]
"Check Bookmark without reading the mail."' note, that's enough to "defuse" the notification and that's by design.

Are you seeing something else?

**Comment by OlMon** [comment]
It should "defuse" the notification for this particular E-mail but it defuses it for the next coming e-mail. 
I tested a little bit more and i am pretty sure my guess above is correct. Sorry for not describing it more clearly, so I try again:

Get 1st E-Mail:
- Notification is fired
- `:delta-unread` of favorite bookmark is 1
- `mu4e--last-delta-unread` is also 1 after notification is shown
- Read the 1st E-Mail / Visit mu4e-main / Visit bookmark etc.
- `:delta-unread` of favorite bookmark is updated to 0
- `mu4e--last-delta-unread` is still 1 **[This should cause the error]**
- Getting 2nd E-Mail `:delta-unread` of favorite bookmark jumps to 1 what is the same as `mu4e--last-delta-unread`, what causes to not fire a notification, because of this check: https://github.com/djcb/mu/blob/master/mu4e/mu4e-notification.el#L55 

Not getting a notification will always happen if you get the same amount of e-mail twice in a row.

I think it should be fixed, when `mu4e--last-delta-unread` is set to 0, when `:delta-unread` is set to 0 or the "baseline" is set.

Hope this explains it more clearly.

**Comment by OlMon** [comment]
Hej Hej,

This should fix it:
```diff
diff --git a/mu4e/mu4e-query-items.el b/mu4e/mu4e-query-items.el
index ef0ff5b8..5556005f 100644
--- a/mu4e/mu4e-query-items.el
+++ b/mu4e/mu4e-query-items.el
@@ -122,7 +122,8 @@ With RESET-BASELINE, reset the baseline first."
     (setq mu4e--query-items-baseline nil
           mu4e--query-items-baseline-tstamp nil
           mu4e--bookmark-items-cached nil
-          mu4e--maildir-items-cached nil))
+          mu4e--maildir-items-cached nil
+          mu4e--last-delta-unread 0))
   (mu4e--server-queries
    ;; note: we must apply the rewrite function here, since the query does not go
    ;; through mu4e-search.
```

I am not sure if this is ok to use the `mu4e--last-delta-unread` variable in `mu4e-query-items.el` 

If someone wants a temporary fix:
```elisp
(defun ol/reset-mu4e-last-mail-count (fn &optional reset-baseline)
  (when reset-baseline
    (setq mu4e--last-delta-unread 0))
  (funcall fn reset-baseline))
(advice-add 'mu4e--query-items-refresh :around 'ol/reset-mu4e-last-mail-count)
```

**Comment by djcb** [comment]
I've a slightly different version of this; thanks.
