### ISSUE TITLE
[mu bug] regression: format=links doesn't create any symlinks at all since 1.10

### ISSUE THREAD

**Issue by freswa** [djcb/mu#2448]
## Expected or desired behavior

`mu find --clearlinks --format=links --linksdir=~/.mail/search test` creates links to search results in the mentioned directory.

## Actual behavior

The directory stays empty (besides maildir folders).

## Steps to reproduce

Issue a simple search to check if it finds something.
`mu find test`
Then try to create symlinks for them.
`mu find --clearlinks --format=links --linksdir=~/.mail/search test`

## Versions of mu, mu4e/emacs, operating system etc.
ArchLinux
mu 1.10

Similar issue as #2279

**Comment by freswa** [comment]
Same commands in `1.8.14` work as expected. Will try a bisect now.

**Comment by djcb** [comment]
I brushed off an old format=links unit tests,pushed to `master`; and it passed in CI (Ubuntu and MacOS latest). Does it pass for you too? I.e., `make check`?

**Comment by freswa** [comment]
Unfortunately it passed :/
```
ninja: no work to do.
ninja: Entering directory `/home/frederik/mu/src/mu/build'
ninja: no work to do.
 1/26 test-sexp                    OK              0.03s
 2/26 test-regex                   OK              0.03s
 3/26 test-command-handler         OK              0.03s
 4/26 test-utils-file              OK              0.03s
 5/26 test-option                  OK              0.03s
 6/26 test-mu-utils                OK              0.03s
 7/26 test-contact                 OK              0.02s
 8/26 test-document                OK              0.02s
 9/26 test-fields                  OK              0.02s
10/26 test-flags                   OK              0.02s
11/26 test-priority                OK              0.02s
12/26 test-message-file            OK              0.02s
13/26 test-message-part            OK              0.01s
14/26 test-threads                 OK              0.01s
15/26 test-contacts-cache          OK              0.03s
16/26 test-maildir                 OK              0.02s
17/26 test-msg                     OK              0.02s
18/26 test-tokenizer               OK              0.02s
19/26 test-parser                  OK              0.01s
20/26 test-cmd                     OK              0.01s
21/26 test-message                 OK              0.05s
22/26 test-cmd-cfind               OK              0.55s
23/26 test-query                   OK              1.01s
24/26 test-store                   OK              1.33s
25/26 test-cmd-query               OK              3.11s
26/26 test-store-query             OK              3.64s

Ok:                 26
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0

**Comment by freswa** [comment]
So I `strace`'ed this thing. I see that the good version resolves `~/.mail` to `/home/user/.mail` on it's own, while `1.10.0` doesn't. Although the `symlink()` call returns 0, the file isn't created.
I'm fine with just closing or fixing - up to you @djcb. Thanks for helping me with the investigation :+1:

**Comment by djcb** [comment]
The behavior or `--linksdir=...` (and similar) depends on your shell (and their configuration); i.e., `zsh` seems to do the tilde-expansion (~/mail etc), while bash does not; in fact when I tried bash create a directory with a literal `~`.

IIRC, older mu may have tried to use `wordexp`, but that adds its own magic. So I'm going to close this... maybe I'll think of some better solution, but for now I suppose the least amount of 'magic' is the best. Thanks for testing.
