### ISSUE TITLE
[mu4e rfe] mu should recursively consider In-Reply-to in --include-related query

### ISSUE THREAD

**Issue by husainaloos** [djcb/mu#2450]
**Is your feature request related to a problem? Please describe.**

When a thread of emails only have `In-Reply-To` header set, but not `References` header set, `mu find --include-related 'msgid:<leaf_msgid>` does not find the whole thread.

**Describe the solution you'd like**

I would like `mu find` to find the whole thread from `In-Reply-To` recursively.

**Describe alternatives you've considered**

None.

**Additional context**

N/A.

**Comment by husainaloos** [comment]
[root_email.txt](https://github.com/djcb/mu/files/11095401/root_email.txt)
[parent_email.txt](https://github.com/djcb/mu/files/11095404/parent_email.txt)
[leaf_email.txt](https://github.com/djcb/mu/files/11095405/leaf_email.txt)

These are emails that can be used for tests. I am not able to ensure that they are producing the issue (because I am not sure how to test a selected list of emails). 

The command that should produce this issue is 

```
mu find --include-related 'msgid:877cxjlfz9.fsf@duckling'
```

**Comment by djcb** [comment]
I created testmaildir and moved those test-messages there; when I search with the above command I get 22 hits (because the test messages referred to actual mailing list message), and I can see the threads.

A message is supposed to have the message-id of its immediate parent in `In-Reply-To`, and grandparents etc. in `References`. Roughly, for a "related" search, `mu` does a first query and takes all the references/in-reply-to it find from those matches, and then does a _second_ query that includes messages that match those references/in-reply-to.

Are you seeing something different? Or do you have "broken" messages in a way?

**Comment by husainaloos** [comment]
Thank you.

I probably should generate another set of testing emails (the ones I provided are generated from the mailing list) that use randomly generated IDs. The original emails that I have problems with are work-related emails and I cannot use them here.

What you described is right. Some systems/clients apparently only set the "In-Reply-To" header to the parent Message-ID but do not set the "References" header. Because of this, mu does not find the full list of related emails. To do that, the only way is to continue recursively search for the "In-Reply-To" if it has Message-IDs not included in the "References" header.

Btw, is there a way (script maybe) to quickly setup an mu testing environment for test emails?

**Comment by djcb** [comment]
For testing, I usually just use add some "tests"-submaildir, and put test messages there. Could fully isolate that, but that's not usually needed.

Anyway, so we're talking about some misbehaving messages wrt to their In-Reply-To/References setup; at least in my world that seems to be a fairly rare problem. Is it common for you? 

Right now we find "related" messages by doing _two_ queries, and it's a bit non-trivial process; I'm a bit hesitant to complicate it further.

**Comment by husainaloos** [comment]
> Is it common for you?

No. There is a system at work that generates emails which sets `In-Reply-To` but not `References` to build a thread.

**Comment by djcb** [comment]
Okay, thank you. Then it's probably a bit out-of-scope for mu/mu4e, it'd be expensive to calculate the threads when the references info is not available. So closing this, sorry!
