### ISSUE TITLE
"loading..." make everything very jumpy

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#2451]
**Describe the bug**

I just upgraded to 1.10. I now see `Loading...` flash at the top line of each article. I think this is a new behavior. It makes everything very jumpy (unpleasant to view) because even though it says `Loading...`, the buffer is full of text, and then after ~1/10th of a second everything shifts up by a line when it is done loading. Perhaps this should be in the modeline? Or can it be disabled?

Note that I *cannot* replicate this with `emacs -Q`. It may be a `gnus` issue, but I have not seen it before this upgrade, and I cannot find mention of it when searching for "gnus" and "loading..."

**How to Reproduce**

I cannot replicate this (yet) with a clean install.

**Environment**

mu4e 1.10.0

**Checklist**
- [X] you are running either an 1.8.x release or the latest 1.9.x development release
- [ ] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [X] you have read all of the above

**Comment by mankoff** [comment]
Ah! Checked the old version - 1.8.13. It says `Loading message...` but the message is not displayed while it says that. A flash of a blank buffer, then the text, is reasonable. 1.10 seems to display the text while it reports `loading...`, and then everything shifts by 1 line.

**Comment by djcb** [comment]
Try setting `mu4e-dim-when-loading` to `nil` on `master`.
