### ISSUE TITLE
[mu4e bug] Canot filter message content using mu4e~view-render-buffer

### ISSUE THREAD

**Issue by averter** [djcb/mu#2452]
**Describe the bug**

I use certain functions to filter unwanted content out of emails (examples below) but these are not working since I've updated to 1.10.0.

**How to Reproduce**

1. Upgrade to the latest version 1.10.0
2. Send an email to yourself containing `** THIS MESSAGE ORIGINATED FROM AN EVIL SOURCE **`
3. Define a function which uses `mu4e~view-render-buffer` to filter content out of emails, e.g. see the example below or the "Post version 1.6.0~54" code in this issue https://github.com/djcb/mu/issues/1689#issuecomment-899096624 
```` lisp
(defun header_remover (msg)
  "This function removes header text warnings from mu4e-view"
  (save-excursion
    (goto-char (point-min))
    (let ((case-fold-search nil)
          (inhibit-read-only t))
      (when (search-forward "** THIS MESSAGE ORIGINATED" nil t) ; <<< beginning of text to be filtered
        (let ((pos1 nil)
              (pos2 nil))
          (if (search-backward "<div style" nil t)
              (progn (setq pos1 (point))
                     (setq pos2 (search-forward "</div>" nil t)))
            (progn (setq pos1 (search-backward "** THIS MESS" nil t))	; <<< beginning of text to be filtered
                   (setq pos2 (search-forward ". **" nil t))))		; <<< end of text to be filtered
          (delete-region pos1 pos2)))
      (mu4e~view-activate-urls)
      (remove-overlays)
      (set-buffer-modified-p nil)))
  )

(advice-add #'mu4e~view-render-buffer :after #'header_remover)
````
4. The above functions will not work, i.e. `** THIS MESSAGE ORIGINATED FROM AN EVIL SOURCE **` will not be removed from mu4e-view.

My question: is there an alternative way to achieve the same result in this new version of mu4e (v1.10.0)?
Possibly related to this commit https://github.com/djcb/mu/commit/453c7f84e89f498768586eae38c96cc9ce3b6072

**Environment**

mu4e v1.10.0, emacs 27.1, Linux Mint 21.1

**Checklist**
- [ ] you are running either an 1.8.x release or the latest 1.9.x development release
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [x] you have read all of the above

**Comment by OlMon** [comment]
Hej Hej,

It seems you just need to use the proper function. As the new.org stated:
> "more mu4e~ internals have been renamed/reworked in to mu4e--."

So in your case change the advice to:
```
(advice-add #'mu4e--view-render-buffer :after #'header_remover)
```

Cheers!

**Comment by averter** [comment]
Thanks. Worked like a charm.
