### ISSUE TITLE
`display-buffer-reuse-window` is set unconditionally

### ISSUE THREAD

**Issue by malb** [djcb/mu#2458]
**Describe the bug**

When creating a new, second e-mail draft and `mu4e-compose-in-new-frame` is set then a new frame should be created instead of the existing reused.

**How to Reproduce**

Create two e-mail drafts with `mu4e-compose-in-new-frame`  set.

The root cause is that `display-buffer-reuse-window` and `display-buffer-reuse-mode-window` is set unconditionally, but it should not be used when creating new frames for composition.

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

Debian, Emacs 29, mu/mu4e 1.10

**Checklist**
- [X] I am running 1.10
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil etc.)
- [X] you have read all of the above

**Comment by djcb** [comment]
@mickeynp: should we update `mu4e-display-buffer` for this?

**Comment by malb** [comment]
FWIW, this worked for me:

```diff
@@ -285,22 +285,30 @@ for BUFFER-OR-NAME to be displayed in."
             ('(view . vertical) '((window-min-width . fit-window-to-buffer)))
             (`(,_ . t) nil)))
          (window-action (cond
-                         ((eq buffer-type 'main) '(display-buffer-full-frame))
+                         ((eq buffer-type 'main) '(display-buffer-reuse-window
+                                                   display-buffer-reuse-mode-window
+                                                   display-buffer-full-frame))
                          ((and (eq buffer-type 'compose) mu4e-compose-in-new-frame)
                           '(display-buffer-pop-up-frame))
                          ((memq buffer-type '(headers compose))
-                          '(display-buffer-reuse-mode-window display-buffer-same-window))
+                          '(display-buffer-reuse-window
+                            display-buffer-reuse-mode-window
+                            display-buffer-same-window))
                          ((memq mu4e-split-view '(horizontal vertical))
-                          '(display-buffer-in-direction))
+                          '(display-buffer-reuse-window
+                            display-buffer-reuse-mode-window
+                            display-buffer-in-direction))
                          ((memq mu4e-split-view '(single-window))
-                          '(display-buffer-same-window))
+                          '(display-buffer-reuse-window
+                            display-buffer-reuse-mode-window
+                            display-buffer-same-window))
                          ;; I cannot discern a difference between
                          ;; `single-window' and "anything else" in
                          ;; `mu4e-split-view'.
-                         (t '(display-buffer-same-window))))
-         (arg `((display-buffer-reuse-window
-                 display-buffer-reuse-mode-window
-                 ,@window-action)
+                         (t '(display-buffer-reuse-window
+                              display-buffer-reuse-mode-window
+                              display-buffer-same-window))))
+         (arg `((,@window-action)
                 ,@window-size
                 ,direction
                 )))
```

**Comment by mickeynp** [comment]
@djcb updating the function makes sense. Ideally, people would write their own display buffer actions to handle window display --- but that horse has bolted already. 

Malb's patch seems like a good fit too. We'll just need to watch out for regressions in other areas.

**Comment by malb** [comment]
Is there a way to replace the display buffer actions, i.e. override the choices made in `mu4e-display-buffer`?

**Comment by mickeynp** [comment]
Yes, with `display-buffer-alist`. That is the purpose of the new display logic in mu4e: to facilitate complete customisation by the user.

**Comment by malb** [comment]
Ah, I didn't get that! I thought a user can only add to but not supersede what is hardcoded in `mu4e-display-buffer`. But reading the documentation of `display-buffer` (sorry for failing to do that properly earlier), I see that `display-buffer-alist` takes precedence over `ACTION`. So perhaps the "correct fix" is to add a documentation entry showing how to achieve what e.g. I want above?

**Comment by mickeynp** [comment]
No worries. We should continue support the window/frame switches in mu4e as `display-buffer-alist` is a bit too complex, IMO, to expect people to set up out of the box. 

Thanks for raising this issue. I think the diff you posted would work out OK. Can you raise a PR with it?

**Comment by djcb** [comment]
I guess a few more examples in the documentation would help, and some mu4e-specific predicate functions to match various buffer types. I'm only slowly learning the magic of `display-buffer-alist`...

**Comment by mickeynp** [comment]
You can pass a function to `display-buffer-alist` so it uses that to determine eligibility.

I've written about how to do that here for Magit (a million modes and different buffer names) and how to make windows "project-specific" using Emacs's project.el:

https://www.masteringemacs.org/article/demystifying-emacs-window-manager

So I agree with DJ that a simple `mu4e-buffer-p` function that checks if it's any one of mu4e's modes would be useful. If only to save people some typing.
