### ISSUE TITLE
[mu bug] Wrong parsing of base64-encoded subjects

### ISSUE THREAD

**Issue by danielfleischer** [djcb/mu#2461]
**Describe the bug**
When subject is encoded using base64, `mu` doesn't parse all the chunks, resulting in a partial sentence. This impacts mostly searching but also messages display in mu4e-headers view.

**To Reproduce**
For example, in the following message snippet:
```
Subject: =?UTF-8?B?16LXldeR15M=?= =?UTF-8?B?INeX15PXqQ==?=
```

mu will parse the first chunk `=?UTF-8?B?16LXldeR15M=?=` so a partial sentence will be stored and indexed in mu, not the full subject. A longer example:

```
Subject: =?UTF-8?B?15DXpNep16gg15zXlNeo15LXmdeiLCDXnteS?=
 =?UTF-8?B?15bXmdefINeX15PXqSDXlNeS15nXoiEg15vXoA==?=
 =?UTF-8?B?16HXlSDXnNeb15wg15TXoteT15vXldeg15nXnQ==?=
 =?UTF-8?B?INeU15vXmSDXntei16DXmdeZ16DXmdedID4+?=
```

In this example, only the first two chunks are parsed. 

**Environment**
mu master 547ef634. 
Emacs 28.2.

**Comment by djcb** [comment]
In future reports of this kind, please include a minimal example message (not just a snippet) + the expected result (my Hebrew (?) is a bit rusty) - thanks.

Anyway, this is an upstream issue, see #2429; it's already fixed I think.

**Comment by danielfleischer** [comment]
Thanks. Just for completeness, `gmime` latest version is 3.2.13, while the bug is fixed after that, so one needs to clone locally, build it, and compile mu with this `gmime` version. Finally, need to recreate the index with `mu init` and `mu index`.

**Comment by djcb** [comment]
Indeed, GMime could use a new version!

**Comment by danielfleischer** [comment]
For homebrew users - until gmime gets a new version - I added an option to install code from master. Just run:
```brew install --head gmime```
