### ISSUE TITLE
[mu4e bug] mu4e 1.10 or later delete split window setting of Emacs 28.2

### ISSUE THREAD

**Issue by wwzhang** [djcb/mu#2465]
**Describe the bug**
mu4e 1.10 or later delete split window setting of Emacs 28.2

**How to Reproduce**
set emacs with window splitted using Ctrl-X 2 or Ctrl-X 3, then start mu4e, then only the window with mu4e exists

**Environment**
OS: Mac Ventura
Emacs: 28.2 installed with brew
mu: 1.10.1 and 1.10

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [ ] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X ] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
This not a bug, this is just the default behavior (and has been for a long time I think)

In 1.10.x you should be able to override it though, by customizing `display-buffer-alist`....but the manual could use an example for that.

**Comment by djcb** [comment]
E.g., 
```
(setq display-buffer-alist
	 '(("\\*mu4e-main\\*" display-buffer-at-bottom)))
```

**Comment by nickanderson** [comment]
Setting display-buffer-alist as described seems to work on 1.12.x but on my main workstation where I have 1.10.8 it doesn't seem to have any effect.
