### ISSUE TITLE
[mu4e bug] address autocompletion

### ISSUE THREAD

**Issue by pmenair** [djcb/mu#2466]
autocompletion creates address that Microsoft will not accept

where there is no name, instead of ```name <address@domain.com>``` or just ```address@domain.com``` I get ```address@domain.com <address@domain.com>```

MSFT refuses to send this

**Environment**
Up to date Emacs and MacOS

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

**Comment by djcb** [comment]
Yeah, that's an invalid address, so that's my it's rejected.  

Anyway, does this happen with _all_ such addresses, or one in particular? Please attach an email with the address where this happens. You can remove any information and/or change the email as long as the problem is still reproducible. 

Also, what mu version?

**Comment by pmenair** [comment]
version is 1.8.14

Not sure I can give you anything that will reproduce it. The problem is in wherever autocomplete is pulling addresses from, so it must be something arising from the email the address was originally located in, not the one I'm trying to insert it in, right?

It only happens with some addresses, it's rare enough that I forget to look for it. But it's not just one address.

**Comment by djcb** [comment]
Indeed; the addresses are harvested from the messages you received. You can get their "display names" (use for completion) through `M-x mu4e-contacts-info` (which is meant for such debugging). Once you've located a problem case, please find the message where it originated from, and attach it here, thanks.

It must be something special / rare, or it would affect more people.

**Comment by pmenair** [comment]
problem is I'm not comfortable attaching email, it's from a law firm

When I run M-x mu4e-contacts-info it shows ```name@domain.com <name@domain.com>```. When I look at email with that sender/recipient, it shows BOTH ```"name@domain.com" <name@domain.com>``` and ```"fname lname" <name@domain.com>```, but there is only one entry in the contacts info output. This is programmatically generated on the fly, so there's no "address book" to edit, right?

**Comment by djcb** [comment]
I'd never ask to attach anything contain private information, but as mentioned,  you can remove any information and/or change the email as long as the problem is still reproducible. 

Anyway, this may be moot since apparently the correct data is mu4e's contact info.

So you have 
   `Foo Bar <foo@example.com>`
in `mu4e-contacts-info`, yet when you try to auto-complete that, the final `>` is not included? And this happens _always_ what this particular address and not with others?

**Comment by pmenair** [comment]
No, angle brackets always seem correct. In the email that it's pulling addresses from, alll I'm seeing is either ```name <address>``` or ```"address" <address>```. In ```mu4e-contacts-info``` *and* when I autocomplete, there is only one option and it is ```address <address>```, ie., the address repeated outside the angle brackets *without* quotes, which seems to be what MSFT is choking on.

**Comment by pmenair** [comment]
fwiw, here is a heavily redacted copy of one of the emails it is getting the address from, the cc: address is the problem one:

[received headers redacted]
From: name <address>
To: "address" <address>
CC: [addresses redacted]
	"address" <address>
Subject: [redacted]
Thread-Topic: [redacted]
Thread-Index: [redacted]
Date: Wed, 4 Jan 2023 15:19:30 +0000
Message-ID:
  [redacted]
Accept-Language: en-US
Content-Language: en-US
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 04
X-MS-Exchange-Organization-AuthSource: [redacted]
X-MS-Has-Attach:
X-MS-Exchange-Organization-Network-Message-Id:
 [redacted]
X-MS-Exchange-Organization-SCL: [redacted]
X-MS-TNEF-Correlator:
x-ms-publictraffictype: Email
X-Microsoft-Antispam-Mailbox-Delivery:
 [redacted]
X-Microsoft-Antispam-Message-Info:
 [redacted]
MIME-Version: 1.0
 [redacted]
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

[redacted]

**Comment by djcb** [comment]
Hmmm, so in your original description you had:
```
where there is no name, instead of "name <address@domain.com>" or just
"address@domain.com" I get "address@domain.com <address@domain.com"
```
so that was typo? 

Perhaps the broken address have commas or quotes?

Anyway, I then recommend  you upgrade to the new 1.10.1, there have been some tweaks to the display-address handling in the 1.10 branch that are not in 1.8.

**Comment by pmenair** [comment]
It was a typo, yeah. I'll upgrade, thanks.

**Comment by pmenair** [comment]
Did not fix. I tried to email myself at ```name@address.com <name@address.com>``` and this lack of quotes is the issue, when the part outside the bracket is not in quotes MSFT interprets it as ```name@<mailto:address.com%20name@address.com>```

**Comment by djcb** [comment]
Hmmm, that format works just fine for me, and, I think it is valid. 

So, then I can only recommend patching up such addresses using `mu4e-contact-process-function`,
https://www.djcbsoftware.nl/code/mu/mu4e/Contact-functions.html

**Comment by pmenair** [comment]
Weird. If I figure out what's going on I'll let you know. Didn't happen before we switched to Outlook, fwiw.

**Comment by pmenair** [comment]
Actually, spoke too soon. 1.10 fixed this by identifying the address as invalid when I tried to send, that solves the issue for me anyway. Thank you!

**Comment by pmenair** [comment]
```Remote server returned '550 5.1.3 STOREDRV.Submit; invalid recipient addres=
s'```

I entered what you gave me exactly but in the return from MSFT it shows the To: line in source of the attempted send as 

```To: "example@" <example.com example@example.com>```

And the html message returned to me by MSFT explains that delivery failed to 

```example@<mailto:example.com%20example@example.com>```

I suspect that MSFT's preference for html mail may be part of the problem?

Anyway, 1.10 is catching these and making me reenter, which is really all I need.

**Comment by djcb** [comment]
Okay, then I guess there's not much to do there, and there's a work-around with `mu4e-contact-process-function`.
Still weird how the mail server handles such address though!
