### ISSUE TITLE
[mu rfe]  Reintroduce --after for mu cfind

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#2470]
**Is your feature request related to a problem? Please describe.**
`helm-mu-contacts` uses `mu cfind` and allows the user to set a cutoff date. This was previously done using the `--after` parameter.  However, this parameter has been removed.  I understand that I can request JSON output and filter entries in helm-mu, but this seems wasteful as mu cfind may have to generate a huge amount of JSON most of which may have to be discarded in Elisp after JSON parsing.

**Describe the solution you'd like**
Reintroduce the `--after` parameter for `mu cfind`.

**Describe alternatives you've considered**
- Requesting JSON and filtering it in Elisp. Seems wasteful and may be too slow for incremental search via Helm. 
- Removing the after-date filter from `helm-mu-contacts`.  I'm reluctant to do that because this feature considerably increases the usefulness of `helm-mu-contacts`.  I don't need to see contacts from 20+ years ago in the search results.

**Additional context**
None. But happy to provide it on request.

**Comment by tmalsburg** [comment]
Thank you Dirk-Jan!!

**Comment by djcb** [comment]
The feature was still there... but de-activated.
