### ISSUE TITLE
[mu4e rfe] allow users to customize the notification icon

### ISSUE THREAD

**Issue by jian-lin** [djcb/mu#2471]
**Is your feature request related to a problem? Please describe.**
In version 1.10.2, the notification icon cannot be customized when the default value of `mu4e-notification-function` is used.

**Describe the solution you'd like**
Add an option to customize the notification icon for the default value of `mu4e-notification-function`.

**Comment by djcb** [comment]
Sorry, no :)

We'll use the generic one (for emacs) until we have a specific one for mu/mu4e; it's really meant to be be customized, so I won't add an explicit customization point. But you have the code of course, if you really want to change.
