### ISSUE TITLE
[mu4e bug] mu does not update the index when called from emacs

### ISSUE THREAD

**Issue by cgohla** [djcb/mu#2472]
**Describe the bug**

In mu4e I've not been able to see new emails for a few weeks. I can see them after quitting emacs and running `mu index` from the shell. 

Behavior has not changed after upgrading OpenBSD from 7.2 to 7.3 .

**How to Reproduce**

In mu4e header view, press `g`.

mu4e-log buffer shows
```
2023-04-13 22:04:40.658 -> (index :cleanup nil :lazy-check t)
2023-04-13 22:04:40.660 * Received 7 byte(s)
2023-04-13 22:04:42.662 * Received 141 byte(s)
2023-04-13 22:04:42.662 <- (:info index :status running :checked 0 :updated 0 :cleaned-up 0)
2023-04-13 22:04:42.664 <- (:info index :status complete :checked 0 :updated 0 :cleaned-up 0)
```

Similarly, when typing `C-c C-u` in header view, I see new emails being fetched, but they don't show up in the header view without manually triggering indexing from the shell.

**Environment**

Running
 - mu 1.8.13
 - emacs 28.2
 - OpenBSD 7.3
 - 
**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment]
Hmm, that's an odd problem. What changed since "a few weeks"? Can you go back to the mu4e you uses a few weeks ago and see if the problem persists?

**Comment by cgohla** [comment]
> Hmm, that's an odd problem. What changed since "a few weeks"? Can you go back to the mu4e you uses a few weeks ago and see if the problem persists?

I honestly have no clue what changed, that might have provoked this. When I first noticed the issue, I thought it was a problem of exhausted disk space, but that was not the case.

**Comment by djcb** [comment]
Guess something must have changed, but it's hard to guess with so little information.
Can you reproduce with a minimal configuration? And leave `mu4e-index-lazy-check` at is default `nil`?

**Comment by djcb** [comment]
There are some cases where 'lazy' doesn't work which is why it's not the default, e.g with mbsync, or perhaps some details some details of how the filesystem behaves on OpenBSD.  If you have some interesting insights into that, please share of course. But there's nothing wrong with keeping mu4e-index-lazy-check at its default.
