### ISSUE TITLE
[misc] compilation error with mu/mu4e v 1.10.2 (and development v. 1.11.1)

### ISSUE THREAD

**Issue by gooksin** [djcb/mu#2473]
**Describe the issue**
mu/mu4e cannot be compiled from sources without the compile option:
MESON_FLAGS="-Db_sanitize=thread"
To reproduce:
1. Download the latest source package or clone from github
2. cd into de sources directory
3. run: ./autogen.sh
4. run: make (or ninja -C build)
5. The error shown in the attached file appears (the same error appears whatever of gcc or clang is used)

[mu_compilation_error.txt](https://github.com/djcb/mu/files/11230562/mu_compilation_error.txt)

Alternatively:
4. run: make clean all MESON_FLAGS="-Db_sanitize=thread"
5. run: make install
6. mu/mu4e compiles and links but at running time (mu index) there plenty of warnings summarised at the end of the run by:
“ThreadSanitizer: reported  106 warnings”  (the number varies, but is always >100)

**Environment**
+ GNU/Linux Debian 11 (bullseye)
+ Emacs 27.1 (as packaged by Debian: 27.1+1-3.1+deb11u2)
+ mu/mu4e latest release (1.10.2) and current development branch (1.11.1)
+ meson: 0.56.2
+ ninja: 1.10.1
+ gcc/g++: (Debian 10.2.1-6) 10.2.1 20210110
+ clang: 11.0.1-2 (Target: x86_64-pc-linux-gnu, Thread model: posix)

**Comment by djcb** [comment]
Thanks; pushed a fix.
