### ISSUE TITLE
[mu4e bug] Can't bind key to quit message view and apply mark

### ISSUE THREAD

**Issue by toothbrush** [djcb/mu#2474]
**Describe the bug**

I have a few keybindings defined in `mu4e-view-mode-map` that allow me to hit a shortcut to close the view and then do something, e.g., mark the message for deletion.  I want to then be back at the headers view, with the mark applied and point moved to the next message in header-view.  However, i don't want the next message to be opened or marked Seen unless i press `RET`.  This was fine basically since i started using mu4e in ±2014.  

EDIT: on my other computer where it still works, i'm on mu 1.8.14, so i can start narrowing down what changed in the meantime.

I recently upgraded mu4e to 1.10.2, and these "combination" bindings stopped working.  I have tried looking at the mu4e-view source code and Git diffs, but i can't quite work out why it should now be broken.

Here's an example of something that used to work:

```elisp
(defun paul/quit-message-mark-refile ()
  (interactive)
  (mu4e~view-quit-buffer)
  (mu4e-headers-mark-for-refile))
(define-key mu4e-view-mode-map "d" 'paul/quit-message-mark-refile)
```

I went digging and i see that probably this is more like what i should do today:

```elisp
(defun paul/quit-message-mark-refile ()
  (interactive)
  (mu4e-view-quit)
  (mu4e--view-in-headers-context
   (mu4e-headers-mark-for-refile)))
```

However when i do this, the view correctly closes (placing me back in headers-view), but i get an error "[mu4e] No message at point" – even though that's false, and if i press `RET`, the same message (the one i was trying to refile) reopens.  I get the same behaviour if i leave out the `mu4e--view-in-headers-context` bit.

**Environment**
Using GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.6.0, Carbon Version 165 AppKit 2113.6) from Homebrew.  Mu is version 1.10.2, also from Homebrew.

**Comment by djcb** [comment]
Using mu4e internals (`mu4e~` or `mu4e--`) for your customizations is not supported.

Anyway, something like this should work:
```
(defun mark-and-quit ()
  (interactive)
  (let ((mu4e-headers-advance-after-mark nil))
    (mu4e-view-mark-for-refile)
    (mu4e-view-quit)))
```

**Comment by toothbrush** [comment]
Thank you for the reply!  Indeed i'm trying to get what i want without messing with internals.

I tried you snippet – it works better than what i had, but unfortunately, the headers view leaves the marked message highlighted.  Ideally i'd like it to advance to the next line.  I tried the following:

```elisp
(defun mark-and-quit ()
  (interactive)
  (let ((mu4e-headers-advance-after-mark nil))
    (mu4e-view-mark-for-refile)
    (mu4e-view-quit)
    (mu4e-headers-next)))
```

But unfortunately that, again, opens the next message in the list, which i'd like to avoid (i'd prefer it to remain unread until i expressly hit `RET` on it).

Is there a way to modify that behaviour to how it used to be?

**Comment by djcb** [comment]
You can push `C-n`, perhaps with a keyboard macro? Need to make sure you're i the headers view when doing that though.

I pushed a small change to `master` to make it easier; with that you can just do:
```
(defun mark-and-quit ()
  (interactive)
  (let ((mu4e-headers-open-after-move nil))
    (mu4e-view-mark-for-refile)
    (mu4e-view-quit)))
```

**Comment by toothbrush** [comment]
That was really useful, thanks – i was able to get it sufficiently working that way 🙌
