### ISSUE TITLE
[mu4e rfe] Add functionality to go to online archive page of a mailing list

### ISSUE THREAD

**Issue by RuijieYu** [djcb/mu#2476]
Usually mailing lists have online archives, and I want to be able to open up that archive (for example, to copy its link elsewhere). 

I envision having a customizable alist holding pairs of list-ids vs either a format string (taking in something like the message id) or a function that takes a full message structure (I believe mu4e already has something like that), and produces a URL string.  The second case helps for cases like emacs bug list, where one might want to use the bug number to derive the archive URL.

Then, a command that consults this alist and opens the online archive if possible. 

**Describe alternatives you've considered**

Copy message id manually, and try to remember the archive URL's format, etc.

**Comment by djcb** [comment]
Not sure this needs to be part of mu4e; and there's nothing stopping you from implementing that today I think; start with a function that just handles your favorite mailings lists. Do you want to work on that?
