### ISSUE TITLE
[mu4e rfe] - bring back support for mu4e-split-view using a function

### ISSUE THREAD

**Issue by peterhoeg** [djcb/mu#2480]
**Is your feature request related to a problem? Please describe.**

With 1.8 it was possible to set it as follows:
```lisp
(setq mu4e-split-view #'split-window-sensibly)
```
This was super convenient as it allowed the split to happen dynamically based on a standardized functionality and configuration. Basically `mu4e` would just "do the right thing" based on already configured user preferences.

Now with 1.10, it's either statically set `'vertical` or `'horizontal` or via `display-buffer-alist` which is not dynamic.

**Describe the solution you'd like**
Bring back the old functionality.

**Describe alternatives you've considered**
FIddle with `display-buffer-alist` but this would be in addition to how `split-windows-sensibly` which already does the right thing.

**Comment by djcb** [comment]
With the `display-buffer-alist` setup, we gain a lot of flexibility, but we can't easily support functions for `mu4e-split-view`, so I don't think that will come back. 

I'd be happy to add an example for `display-buffer-alist` to the docs though; but that will require a bit little "fiddling" on your side I'm afraid.
