### ISSUE TITLE
[mu bug] error: failed to create store

### ISSUE THREAD

**Issue by igajsin** [djcb/mu#2481]
**Describe the bug**
When I try to use mu it complains
```
error: failed to create store
```
for every mu command and the flag `-d` dosn't provide more informathion. The exit code is 1.

It worked before, probably something was upgraded in the background, but I can't say what exactly.

**To Reproduce**
for instance
```
$ mu cfind -d
error: failed to create store
$ echo $?
1
```

**Environment**
GNU Guix, mu version 1.10.2

**Checklist**
- [X] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
Did you try `mu init`?

**Comment by igajsin** [comment]
yes, but it's the same
```
$ mu init --reinit -d
error: failed to create store
```

**Comment by djcb** [comment]
You can try `mu init --debug --log-stderr` 

If we can't open the store in the first place, `--reinit` won't work either. Does it work without that? Otherwise, can you run `strace mu init` and add the last 30 or so lines? Thanks.

**Comment by igajsin** [comment]
yes, that helped, thanks
