### ISSUE TITLE
[mu4e bug] Customizing `mu4e-user-mailing-lists` has no effect with existing (and even quitted) mu4e sessions

### ISSUE THREAD

**Issue by RuijieYu** [djcb/mu#2483]
**Describe the bug**
Please provide a clear and concise description of what you expected to happen
and what actually happened.

I tried to modify `mu4e-user-mailing-lists` but the modification didn't take effect even after restarting `mu4e`. 

I have an idea of how to fix it, so I'll send a PR within a few days.

Steps:

1. Open a mu4e session. 
2. Run `(setopt mu4e-user-mailing-lists '(("bug-gnu-emacs.gnu.org" . "EmacsBug")))`.  Equivalent actions within customize view also suffices. 
3. Notice that nothing changes in the mail listings.
4. Restart mu4e and try again, notice (3) again. 
5. Try restarting Emacs. 
6. (Didn't try, but after (5) everything should work as expected.)

**Comment by djcb** [comment]
This has been fixed in master, with `mu4e-mailing-list-info-refresh`
