### ISSUE TITLE
[mu4e rfe] Support headers mail-followup-to and mail-reply-to

### ISSUE THREAD

**Issue by RuijieYu** [djcb/mu#2486]
Messages from the mailing list `emacs-diffs@gnu.org` always contain the header `mail-followup-to:` specifying two recipient addresses on follow-up.

When I hit "reply all", I expect the response mail be set up such that whenever available, addresses listed in the `mail-followup-to:` header should be in the reponse's `to:` header, falling back to the old behavior(s) when this header is not found.

Similarly for hitting "reply" and trying to use the "mail-reply-to" header if available, although I don't have a concrete use-case for it. 

See this article, which describes the expected behavior of these two headers: https://cr.yp.to/proto/replyto.html

Comments welcome.  I'll try to start implementing it within a week if no-one else does.

**Comment by djcb** [comment]
My plan, hopefully for the current dev series, is to rework `mu4e-compose` to use gnus' machinery for creating drafts; I think that would automatically get us support for these headers.

**Comment by djcb** [comment]
Plan has landed :-) (master/1.11.23), and those headers are supported now.
