### ISSUE TITLE
[mu4e bug] mu4e-thread-mode being applied to non-mu4e buffers

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#2493]
**Describe the bug**

Tab completion keeps breaking in non-mu4e related buffers. Inspecting the bindings shows mu4e-thread-fold-toggle-goto-next bound to tab and mu4e-thread-mode is reported as a minor mode. Running mu4e-thread-mode to disable the minor mode in the buffer restores functionality.

**How to Reproduce**

I have been unable to reproduce exact steps but I suspect its the asynchronous nature of when mu4e~headers-found-handler is called. Likely the enabling of the minor mode should be within the with-current-buffer sexp.

**Environment**

Debian Bookworm, locally built mu4e from git (eafc81f16891332bedb5c871d6425391fdb28283)

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [ ] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Hmmm... I'd swear I'd already fixed this... but apparently not in `master` at least.
I've pushed a candidate fix.

**Comment by djcb** [comment]
Let me know if you still see this, thanks!
