### ISSUE TITLE
[mu4e bug] mu4e-view-headers-prev, mu4e-headers-view-message caused misplaced folded thread overlay

### ISSUE THREAD

**Issue by progfolio** [djcb/mu#2498]
**Describe the bug**
Calling `mu4e-view-headers-prev`  within a \*mu4e-article\* buffer corrupts the folded thread overlay placement.
Similarly, calling `mu4e-headers-view-message` from within the \*mu4e-headers\* buffer
causes the folded thread overlay to eat the first message.

**How to Reproduce**
1. Open a search with folded threads: 

![image](https://github.com/djcb/mu/assets/44036031/ee3cee26-f493-4305-b6d6-6d745cb0fa46)

2. Call  `mu4e-headers-view-message`: 

![image](https://github.com/djcb/mu/assets/44036031/deeb8d2c-005b-49c5-bb48-d3a349bb9c1b)

Note the first message has been hidden by the overlay.

Similar behavior can bee seen by calling `mu4e-view-headers-prev` from a \*mu4e-article\* buffer.

**Environment**
Arch Linux
 GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8))
mu4e @ c5f9f9f

**Checklist**
- [ x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment]
@rougier: as the domain expert, any idea what could cause this? Thanks!

**Comment by rougier** [comment]
Sorry for late answer. Do you know if the overlay is really changed or is it because something changes in the headers view that make overlay obsolete ?

**Comment by progfolio** [comment]
"Nicolas P. Rougier" ***@***.***> writes:

> Sorry for late answer. Do you know if the overlay is really 
> changed or is it because
> something changes in the headers view that make overlay obsolete 
> ?

I believe there's something off with the positioning of the 
overlays when the problem occurs.
See my comment here:

https://github.com/djcb/mu/pull/2497#issuecomment-1582698824

**Comment by djcb** [comment]
I wasn't able to repro the #2496 problem when I tried @progfolio's recipe... (or perhaps I am misunderstand it) is it reproducible with `emacs -q`?

**Comment by rougier** [comment]
Sorry for late answer. I cannot reproduce it either. Just to be sure of the situation, can you confirm this is the 

<pre>
13/10/2023 Mail 1
..........  [3 Hidden]
<b>13/10/2023  Mail 5</b>_
13/10/2023 Mail 6
</pre>

Then you look at mail 5 and coming back to headers view, you get:

<pre>
13/10/2023 Mail 1
..........  [3 Hidden]
13/10/2023 Mail 6_
</pre>

In my case, I get 

<pre>
13/10/2023 Mail 1
..........  [3 Hidden]
13/10/2023  Mail 5
13/10/2023 Mail 6
</pre>

and if I fold/unfold again, I get 

<pre>
13/10/2023 Mail 1
..........  [4 Hidden]
13/10/2023 Mail 6
</pre>

**Comment by djcb** [comment]
Ah, I can repro now.. I'll push a fix to avoid the problem soon (basically we need to unfold when treating threads from the article buffer).
