### ISSUE TITLE
plistp only available on latest Emacs

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#2499]
**Describe the bug**

`plistp` only available in emacs-29+.

**How to Reproduce**

Use mu4e under Emacs-28.

**Environment**

LinuxMint, emacs-28.3

**Checklist**
- [ X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [ X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [ X] you have read all of the above

**Comment by djcb** [comment]
Ah, good catch. I'll push a fix.
