### ISSUE TITLE
[mu4e rfe] set "Date" header of sent mail to time of composing, not sending when resuming editing

### ISSUE THREAD

**Issue by federvieh** [djcb/mu#2502]
**Is your feature request related to a problem? Please describe.**
I've noticed that the "Date" header in my mails sometimes corresponds to the time when I started writing the message, not the time when the message is actually sent.

I've narrowed it down that this only happens in case I kill the compose buffer before sending (i.e. longer mails that I need to come back to at a later time).

Also, I noticed that I can work around this by deleting the 'Date' line in the header and when I save the buffer it is set to "now". But this is error prone and I tend to forget to do this before sending a mail.

**Steps to reproduce the behavior**
- Compose mail (`C` on my system) 
- Type mail
- Save mail (note that that the `Date` header gets a new timestamp)
- Edit some more
- Save mail (note that that the `Date` header still gets a new timestamp)
- kill buffer
- Navigate to drafts folder
- Continue editing the previously saved draft (`E` on my system)
- Make changes to the mail
- Save the mail and observe that the `Date`header no longer gets updated
- (workaround: Manually delete the `Date` header and save the mail, which fixes the issue also for subsequent saves until the buffer gets killed again)

**Describe the solution you'd like**
When continuing to edit a mail, I'd expect the `Date` to be updated as if I never closed the mail.

The problem seems to be that message.el expects the message-deletable text-property to be set for deletable headers (such as `Date`).

**Describe alternatives you've considered**
One alternative is the workaround I described above. 

Another alternative is to set the following function as a `mu4e-compose-mode-hook`:
```
(defun fraolt-mu4e-mark-deletable-headers ()
  "Set deletable headers as deletable."

  (save-restriction
    (message-narrow-to-headers)
    (let ((headers message-deletable-headers))
      (unless (buffer-modified-p)
        (setq headers (delq 'Message-ID (copy-sequence headers))))
      (while headers
        (goto-char (point-min))
        (if (re-search-forward
             (concat "^" (symbol-name (car headers)) ": *") nil t)
            (add-text-properties
             (match-beginning 0) (match-end 0)
             '(message-deletable t face italic) (current-buffer))
          )
        (pop headers)))))
```

**Additional context**
The relevant parts in message.el are
https://github.com/emacs-mirror/emacs/blame/90047c38ce98af4ac7d0fa9d59ba0d668e4ae902/lisp/gnus/message.el#L6290
and
https://github.com/emacs-mirror/emacs/blame/90047c38ce98af4ac7d0fa9d59ba0d668e4ae902/lisp/gnus/message.el#L6387

**Comment by prbuen** [comment]
For me this happens irrespective of killing the compose buffer? The way I deal with this is by automatically removing the Date: field in the compose hook. I don't need to see the date when I compose a message - there used to be an option to remove it but it's now obsolete.

Note that if you save the compose buffer, it puts a copy in Drafts, and the date reappears, but it updates each time you save (not sure if it updates once more when actually sending?)

```
(add-hook 'mu4e-compose-mode-hook  
	(lambda()  
		(message-replace-header "Date" "" t) ;; remove so date is that of sending  
		(save-excursion (message-add-header "Cc: \n")) ;; add a Cc field. See also message-goto-cc bound to C-c C-f C-c  
		(message-sort-headers) ;; uses message-header-format-alist but shows hidden headers  
		(mu4e~compose-hide-headers)
	)  
)
```

It would be great if the default mu4e behaviour would be to update the date upon sending.

**Comment by nbarrientos** [comment]
Personally I want the date to be set to the moment I recalled the draft and continued editing it so I do also something similar to the comments above:

```elisp
(use-package mu4e
...
  :hook (mu4e-compose-mode
         . (lambda ()
             (when (eq mu4e-compose-type 'edit)
               (message-replace-header "Date" (message-make-date) "Subject"))))
...
)
```
Maybe it makes sense to have this functionality built-in in mu4e behind a `defcustom`.

**Comment by larrydberg** [comment]
I have nothing to add except a vote of agreement that the current behavior is confusing suboptimal. I'd like the "Date" of an outgoing message to be the date it was actually sent, not the date I started composing it, which might be days or weeks earlier as I revise.

**Comment by djcb** [comment]
With new message-composer (master/1.11.23) this Date: is now auto-updated. So closing this.

**Comment by metaspace** [comment]
I am on 1.12.2 and I am still having this issue. For me, the date is only ever set on draft creation time. If I delete the date field, I get an updated value when I save the buffer.

**Comment by djcb** [comment]
Hmm, with Emacs 27 it indeed does not work, though it _does_ with Emacs 29.3 at least.
