### ISSUE TITLE
[mu bug] can't build on windows

### ISSUE THREAD

**Issue by rgkirch** [djcb/mu#2504]
**Describe the bug**
I see that windows support is experimental. After failing to build mu from this repository I tried to build the mu package from msys2-unofficial but the xapian-core build fails. I opened an [issue there for that](https://github.com/msys2-unofficial/MSYS2-packages/issues/13) but I wanted to let you know about my experience here.

After cloning the repo and running either `./autogen.sh` or `meson build` I see some info printed to the terminal and then nothing happens. Task manager shows 20% cpu used for ccache.exe but that's all. I left it there for a whole day and nothing interesting happened.

    $ ./autogen.sh
    *** meson build setup
    /c/Users/me/Apps/msys64/mingw64/bin/meson
    The Meson build system
    Version: 1.1.1
    Source dir: C:/Users/me/notMyCode/djcb/mu
    Build dir: C:/Users/me/notMyCode/djcb/mu/build
    Build type: native build
    Project name: mu
    Project version: 1.11.6

    $ meson build
    The Meson build system
    Version: 1.1.1
    Source dir: C:/Users/me/notMyCode/djcb/mu
    Build dir: C:/Users/me/notMyCode/djcb/mu/build
    Build type: native build
    Project name: mu
    Project version: 1.11.6

**To Reproduce**
see above

**Environment**
Windows 10 with msys2 mingw64.

**Checklist**
- [x] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Thanks!**

**Comment by djcb** [comment]
The command to build is `ninja -C build`, not `meson build`. `make` should work as well (at least on Unix systems).

**Comment by baracunatana** [comment]
I've been down this road before and all I can recommend is to use WSL2. Specially if your intention is to use mu4e

**Comment by rgkirch** [comment]
Ok. Thanks.
I was getting `meson build` from:
> Alternatively, you can run meson directly:
> 
> $ meson build && ninja -C build
I'll see if a mu4e alternative will work for me and then I'll come back and try WSL2.
Thanks again!

**Comment by djcb** [comment]
Unless someone steps in, I'm afraid I can't help you further here, sorry!

**Comment by rgkirch** [comment]
No problem! I’ll follow up here if there’s any news. Thanks!
