### ISSUE TITLE
error: failed to create database dir /home/martin/.cache/mu/xapian: Permission denied

### ISSUE THREAD

**Issue by grauschnabel** [djcb/mu#2505]
**Describe the bug**
I accidentally removed `.cache` from my home directory recursively. Now I try to recreate the mu index.  

`mu init`  cannot create the database dir:

**To Reproduce**
```
martin@martin-ubuntu:~$` mu init --my-address martin@private.tld --maildir /home/martin/Maildir/
error: failed to create database dir /home/martin/.cache/mu/xapian: Permission denied
martin@martin-ubuntu:~$ ls -ld /home/martin/.cache/
drwxrwxrwx 18 martin martin 4096 Jun 22 18:43 /home/martin/.cache/
martin@martin-ubuntu:~$ mkdir -p /home/martin/.cache/mu/xapian
martin@martin-ubuntu:~$ mu init --my-address martin@kaffanke.info --maildir /home/martin/Maildir/
error: Unable to get write lock on /home/martin/.cache/mu/xapian: Couldn't open lockfile: Permission denied
Perhaps mu is already running?
martin@martin-ubuntu:~$ rmdir /home/martin/.cache/mu/xapian/
martin@martin-ubuntu:~$ mu init --my-address martin@kaffanke.info --maildir /home/martin/Maildir/
error: failed to create database dir /home/martin/.cache/mu/xapian: Permission denied
```

**Environment**
Ubuntu latest.

```
martin@martin-ubuntu:~$ uname -a
Linux martin-ubuntu 6.2.0-23-generic #23-Ubuntu SMP PREEMPT_DYNAMIC Wed May 17 16:55:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
martin@martin-ubuntu:~$ mu --version
version 1.10.3
martin@martin-ubuntu:~$ emacs --version
GNU Emacs 28.2
```
Emacs and maildir-utils is the latest today installed using snap

Thanks for help.

**Comment by djcb** [comment]
Hmmm... Perhaps mu is already running? That could lock the database.

**Comment by grauschnabel** [comment]
Nothing in `ps ax`  and there is no xapian directory. Is there an other way to look for?

**Comment by grauschnabel** [comment]
Even `reboot` and logging in via tty and just running that `mu` command does not work. And I cannot see a permission problem. When I try it with `sudo` it works and tells me using directory: `/root/snap/maildir-utils/629/.cache/mu/xapian` so maybe it should use `/home/martin/snap/...` instead of my `/home/martin/.cache/...`   ? 

Maybe there is just a configuration mistake ant the `snap` is not allowed to write to `~/.cache` ?

**Comment by djcb** [comment]
Another error message?

Anyway, you can try to see if it works for some other dir:
```
mu init --muhome=/tmp/bla --maildir=~/Maildir
```

and you could try to run `mu init` with `strace`, to see if there's some underlying error.

**Comment by grauschnabel** [comment]
`mu init --muhome=/home/martin/foo --maildir=~/Maildir` works fine.
`mu init --muhome=/home/martin/.foo --maildir=~/Maildir` gives the error.

Using `strace` on both commands the main difference is that on the later with the error the line

```
recvmsg(3,` {msg_namelen=112}, 0)        = -1 EAGAIN (Resource temporarily unavailable)
```

But I don't really understand that.

**Comment by grauschnabel** [comment]
on the other hand `--muhome="/home/martin/snap/maildir-utils/current/.cache/mu"` works fine, but then I have to do that witch all the time. Shouldn't it be there by default?

**Comment by grauschnabel** [comment]
`unset XDG_CACHE_HOME` before running `mu init` seems to solve the problem now `mu` uses `/home/martin/snap/maildir-utils/629/.cache/mu/xapian` and even `mu index` works fine. But in emacs mu4e would not start seems it loads the variable from somewhere. :(

Now I need to find out what is setting this variable on startup or login and why.  Do you have any further ideas about that, otherwise it seems not to be related to this github repo.

**Comment by djcb** [comment]
I don't use snap, but yeah likely it stops you from writing outside some specific dirs. You can use a custom `--muhome` (or `MUHOME`); see manpage and `mu4e-mu-home` for `mu4e` (see the manual). Or you can just build `mu` yourself, and things should work with the defaults.

Good luck!

**Comment by grauschnabel** [comment]
Thanks for your time!
