### ISSUE TITLE
mu4e-search-change-sorting not working? [mu4e bug]

### ISSUE THREAD

**Issue by joegilder** [djcb/mu#2507]
**Describe the bug**
When I run `mu4e-search-change-sorting`, I get the option in the minibuffer to choose the Sortfield (date, from, list, etc.), but nothing happens. The only thing I can change is the date order (ascending vs descending), but I can't sort by any other column/field.

**How to Reproduce**
Pressing O brings up options for sort, but Date is the only one that works. When I choose another field and press enter, it toggles the sort order for date, but never switches to that field. 

**Environment**
Mac OS 12.6.3
Emacs 28.2 (from macports)
mu 1.10.3
I launched from a clean init with only my mu4e config, and was still getting the problem.

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Are you using message threads? With threading enabled, you can only sort by date; see the section on "Sorting and threading" in the manual.

**Comment by joegilder** [comment]
That fixed it. Thank you!

Joe Gilder
Home Studio Corner

**Comment by djcb** [comment]
Thanks -- it could be made a bit clearer in the UI, so that's what I've done now.
