### ISSUE TITLE
[mu4e bug] base64 decoding fails for text/plain DOS-encoded messages

### ISSUE THREAD

**Issue by foudfou** [djcb/mu#2508]
**Describe the bug**
Base64 decoding fails in mu4e:view for received messages when (1) DOS-encoded (i.e. CRLF line terminators), (2) 
```
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64
```
I would expect these messages to be decoded to plain text.
Sounds similar to #1262.

**Additional information**
I noticed messages with an additional `format=flowed` get decoded properly:
```
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: base64
```

Also decoding succeeds when the message is unix-utf8 encoded (i.e. with CR line terminators).

**How to Reproduce**

1. drop [raw2.txt](https://github.com/djcb/mu/files/11867506/raw2.txt) to your mailbox
2. open mu4e
3. observe the body still displayed in base64

**Environment**
mu/mu4e 1.10.4, emacs 28.2, arch linux

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment]
It works with `mu view`, but not in the mu4e viewer; the latter is based on the venerable gnus code, I suspect the problem/limitation is there.

**Comment by djcb** [comment]
Well, in Gnus it shows correctly.... so there should be hope for `mu4e` as well

**Comment by djcb** [comment]
This is actually a duplicate of #2260, and I've pushed a fix to `master`. Thanks!
