### ISSUE TITLE
Responding to email removes "Seen" flag away from email.

### ISSUE THREAD

**Issue by shamiv** [djcb/mu#2511]
The full filename (in the underlying Maildir) of an email I have already seen, ends with an "S" (the "S" of "Seen").

Sometimes (not always) when I use mu4e to reply to an email (that I of course have already seen), the act of responding to the email adds an "R" to the filename (the "R" of "replied") but it takes away this "S" from the filename.

As a result mu4e gives that email an "unread" flag. This is annoying.

I would be happy to explore the underlying elisp, but I can't find which part of the mu4e code adjusts the filename of the underlying mail. 

Does anyone recognize this issue? How to approach this?

mu version: 1.11.3
emacs version: 30.0.5
Spacemacs version:  v.0.999.0

**Comment by djcb** [comment]
Checklist says:
- you are running either an 1.8.x/1.10.x release or master (otherwise please upgrade)
- you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- you have read all of the above

Can you reproduce with `master` and _without_ spacemacs (or at least without the mu4e layer)?

**Comment by shamiv** [comment]
Sorry yes, of course.

Unfortunately the same (sometimes) happens when using mu 1.10.4 and without the mu4e layer.

It's a bit difficult to experiment without Spacemacs, because I am not comfortable enough with the clean Emacs and it only sometimes happens (maybe 1 out of 10 emails).

I will first see if less advanced versions of Emacs make a difference (will try with 28.2).

**Comment by shamiv** [comment]
Unfortunately, moving to Emacs 28.2 or moving to mu 1.10.3, 1.10.4 or 1.10.5 does not change anything. 

I have also made sure that 3rd-party add-ons are off (like [mu4e-goodies](https://github.com/panjie/mu4e-goodies) and [mu4e-folding](https://github.com/rougier/mu4e-folding)).

The behaviour stays the same: every now and then (let's say for one out of four emails) responding to a message strips that message of its flags, including for instance the "seen" flag (making the message "unread"), but also the

**Comment by djcb** [comment]
The changing of flags happens in the `mu` server program, no elisp involved. What I could imagine is that you have multiple copies of that same message, and not all flags are applied to all copies. You can test by _not_ hiding duplicate messages, i.e., by `P u` in the headers-view.

Also, you could try `M-x mu4e-toggle-logging` and see what goes on.

(Oh, side-note: replying to an unread message from the headers-view does _not_ mark it as seen)
