### ISSUE TITLE
[mu4e bug] `mu4e-main-quit-or-bury` always buries and never quits

### ISSUE THREAD

**Issue by tsdh** [djcb/mu#2512]
**Describe the bug**

`mu4e-main-quit-or-bury` says it would bury the main buffer when a prefix arg is provided and otherwise quit mu4e.  In reality, it will always just bury because its interactive spec is `(interactive "p")` where `p` is a prefix arg converted to a number which means no prefix arg means 1.  So the `bury` argument can never be `nil` unless called from Lisp, of course.

I guess you wan't `P` instead of `p`.

BTW, I'd rather would like to have a `mu4e-main-bury-or-quit` with reversed semantics because I want to bury the buffer many times a day but quit it only once.  (Of course, I can do that on my own.)

**How to Reproduce**

Hit `q` in the main buffer and check with `C-x b` that the buffer is still there which contradicts the docstring.

**Environment**

GNU/Linux, master emacs, master mu

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Oops! Fixed, thanks.
