### ISSUE TITLE
Empty mail store

### ISSUE THREAD

**Issue by stefanhusmann** [djcb/mu#2513]
**Describe the bug**
No mails in store, even after a mu --init and mu index

**To Reproduce**
* mu4e - mu for emacs version 1.11.9

  Basics

	* [j]ump to some maildir
	* enter a [s]earch query
	* [C]ompose a new message

  Bookmarks

	* [bu] Unread messages      0/0
	* [bt] Today's messages     0/0
	* [bw] Last 7 days          
	* [bp] Messages with images 0/0

  Maildirs

  Misc

	* [;]Switch context
	* [U]pdate email & database

	* [N]ews
	* [A]bout mu4e
	* [H]elp
	* [q]uit

  Info

	* last updated        : Thu Jul  6 12:33:34 2023
	* database-path       : /home/haawda/.cache/mu/xapian
	* maildir             : /home/haawda/Maildir/
	* in store            : 0 messages
	* personal addresses  : none

**Environment**
Please describe the versions of OS, Emacs, mu etc. you are using. Arch Linux, both emacs and mu freshly built from git masters. 

emacs --version
GNU Emacs 30.0.50
Copyright (C) 2023 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

$ mu --version
version 1.11.9

**Checklist**
- [x ] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
Can you include the precise `mu init` and `mu index` commands, and their output? Thanks.

**Comment by stefanhusmann** [comment]
```
$ mu init --maildir /home/haawda/Maildir/ --my-address=stefan-husmann@t-online.de
+------------------------+--------+
| mu version             | 1.11.9 |
+------------------------+--------+
| store schema-version   | 500    |
+------------------------+--------+
| guile-support:         | yes    |
+------------------------+--------+
| readline-support:      | no     |
+------------------------+--------+
| cld2 language support: | no     |
+------------------------+--------+

other available info topics ('mu info <topic>'):
  store  - information about the message store (database)
  fields - information about message fields
database created; use the 'index' command to fill/update it.
```
mu index is currently running again.
``` 
$ mu index
indexing maildir /home/haawda/Maildir/ -> store /home/haawda/.cache/mu/xapian
```

**Comment by stefanhusmann** [comment]
yes
```
/ indexing messages; checked: 168577; updated/new: 0; cleaned-up: 0
```

**Comment by djcb** [comment]
Did it say the same (ie., `updated/new: 0`) immediately after updating? What does `mu info store` say?

**Comment by stefanhusmann** [comment]
Yes immediately after updating.
```
$ mu info store
+-------------------+-------------------------------+
| maildir           | /home/haawda/Maildir/         |
+-------------------+-------------------------------+
| database-path     | /home/haawda/.cache/mu/xapian |
+-------------------+-------------------------------+
| schema-version    | 500                           |
+-------------------+-------------------------------+
| max-message-size  | 100000000                     |
+-------------------+-------------------------------+
| batch-size        | 250000                        |
+-------------------+-------------------------------+
| created           | Do 06 Jul 2023 12:53:17 CEST  |
+-------------------+-------------------------------+
| personal-address  | stefan-husmann@t-online.de    |
+-------------------+-------------------------------+
| messages in store | 0                             |
+-------------------+-------------------------------+
| last-change       | never                         |
+-------------------+-------------------------------+
| last-index        | Do 06 Jul 2023 13:22:09 CEST  |
+-------------------+-------------------------------+
```

**Comment by djcb** [comment]
`Last change: never`... so it seems the index process didn't complete successfully. Do you get anything error / suspicious looking things with `mu --log-stderr index --debug`?

**Comment by stefanhusmann** [comment]
Hm, lots of messages like this:
```
(process:3804388): mu-DEBUG: 19:56:59.879: could not detect language

(process:3804388): mu-WARNING **: 19:56:59.879: failed to add message @ /home/haawda/Maildir/cur/msg.dyKLF: root '/home/haawda/Maildir/' is not a root for path '/home/haawda/Maildir/cur/msg.dyKLF'
```

**Comment by djcb** [comment]
Aha... so the problem is likely with the Maildir ending in a slash. You can try without that (new `mu init`), or pull from master, which has a change to make mu a bit less picky.
