### ISSUE TITLE
[mu4e bug] Regressions with saving images

### ISSUE THREAD

**Issue by jgoerzen** [djcb/mu#2516]
**Describe the bug**

After upgrading from mu4e 1.4.15 to mu4e 1.8.14, I am encountering these issues:

1. There is no way to save all images like we used to have in the mu4e view.
2. While I can use the action menu to save attachments, I must use M-x image-save to save inline images.
3. M-x image-save does not preserve the filename.  In fact, I can no longer even access the filenames of inline images.

There are some related issues:

- #2173 suggested `(setq gnus-inhibit-mime-unbuttonizing t)` but that did not help me.
- #758 discusses viewing in browser not working with inline attachments, but viewing in browser is something I highly wish to avoid due to the privacy implications.  (And it's a number of years old and might have been resolved by #750 anyhow)

**How to Reproduce**

Receive a message with inline image attachments.

Observe they are not available for save in the action menu, and filenames are not preserved with M-x image-save.  Also there is no way to save all attachments, regardless of type, anymore.

**Environment**
Debian bookworm with Doom emacs and mu4e 1.8.14.

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Yeah, with the move to the gnus-based viewer we gained many features, and lost a few, which are slowly coming back...
I'm planning to update the mime-handling code for the next stable release (1.11.x --> 1.12)

**Comment by djcb** [comment]
A first version of this has landed in `master`, and it does bring back saving for disposition "inline" attachments and some other improvements; so closing this.

But note, unfortunately this is too big to be back-merged into the release branches for 1.10 (let alone 1.8).

**Comment by jgoerzen** [comment]
Hi, Thanks for your work on this!

I've updgraded to 1.12.2 and still having difficulties.  I looked at https://www.djcbsoftware.nl/code/mu/mu4e/MSGV-Attachments-and-MIME_002dparts.html and tried:

- M-x image-save: does appear to work, though it doesn't preserve the filename.  Doesn't let me save all of them (have to do this for each)
- M-x mu4e-view-save-attachments: says no attachments for this message
- M-x mu4e-view-mime-part-action: only lists the text/html and text/plain parts, not the inlined jpegs

So I must be missing something?

Also it initially displays the images way too big, but if I click on the text/html at the top -- even though it is already displaying that -- it will zoom them out to fit in the window.

**Comment by djcb** [comment]
Can you attach a message where this happens? Thanks!

**Comment by djcb** [comment]
Ah, yeah, that's a tricky message. I'll reopen this.

**Comment by djcb** [comment]
I've added `M-x mu4e-view-mime-parts` for cases like that; we need to enable everything in Gnus to show "buttons", which you can use to save (with `o` etc.)
