### ISSUE TITLE
[mu4e bug] mu4e-view-save-attachments doesn't honor mu4e-attachment-dir with a function value

### ISSUE THREAD

**Issue by sleepyMonad** [djcb/mu#2518]
**Describe the bug**

According to the documentation, mu4e-attachment-dir can be a function. If that is the case the function is not evaluated and passed into expand-file-name which doesn't support a function as dir argument.

(Verified by tracing version 1.10.3)
 
PS: verified on vanilla emacs on NixOS 23.05

**Comment by djcb** [comment]
Yeah, that got lost a _long_ time ago it seems; I'll re-implement it for 1.11 / next stable release (which will see some more changes in that area).

**Comment by djcb** [comment]
I pushed an implementation for this this to `master`.
