### ISSUE TITLE
When-let not available in Emacs-28

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#2519]
**Describe the bug**

You have to require `subr-x` in Emacs-28, in Emacs-29+ it is in subr.el and there is nothing to do.
See warnings when compiling.

**How to Reproduce**

**Environment**

**Checklist**
- [X ] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [ X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [ X] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Hmm, couldn't reproduce. Can you share the exact error messages you got? Thanks.

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Hmm, couldn't reproduce. Can you share the exact error messages you got? Thanks.

Not error, warnings at compile time because subr-x is not required.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by djcb** [comment]
I tried:
```
make clean; meson setup '-Demacs=/usr/bin/emacs-28.2' build; meson compile -C build  
```
but saw neither warnings nor errors. What warnings did you see? 

I also checked the CI, which builds with emacs 27 (ubuntu) and emacs 28 (MacOS), and both are silent on this as well.

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> I tried:
>
> make clean; meson setup '-Demacs=/usr/bin/emacs-28.2' build; meson compile -C build  
>
> but saw neither warnings nor errors. What warnings did you see?

Indeed after make clean and recompiling, oddly I have no more warnings,
however I didn't installed and used this mu version.  I guess you may
have errors (as we have generally with when-let in such situation) if no
other package or code is requiring subr-x before running mu code using
when-let, IOW it may work only by chance if you don't require it.  I
quickly grepped mu4e directory and didn't find any subr-x requirement,
did I miss something?


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto ***@***.***> writes:

> "Dirk-Jan C. Binnema" ***@***.***> writes:
>
>> I tried:
>>
>> make clean; meson setup '-Demacs=/usr/bin/emacs-28.2' build; meson compile -C build  
>>
>> but saw neither warnings nor errors. What warnings did you see?
>
> Indeed after make clean and recompiling, oddly I have no more warnings,
> however I didn't installed and used this mu version.  I guess you may
> have errors (as we have generally with when-let in such situation) if no
> other package or code is requiring subr-x before running mu code using
> when-let, IOW it may work only by chance if you don't require it.  I
> quickly grepped mu4e directory and didn't find any subr-x requirement,
> did I miss something?

Hoops, my bad I confuse with previous emacs versions, when-let is
autoloaded in emacs-28 so it should work as expected.
Sorry for the noise.

-- 
Thierry

**Comment by djcb** [comment]
Ah, thanks for checking!
