### ISSUE TITLE
[mu4e bug] mu4e-view-headers-next not working in view buffer after an update in headers buffer 

### ISSUE THREAD

**Issue by whame** [djcb/mu#2523]
**Describe the bug**

After `mu4e-update-mail-and-index` has run in the background, the functions `mu4e-view-headers-next` and `mu4e-view-headers-prev` doesn't work correctly. One can see that in the headers buffer the next/previous message is highlighted, but the message in the view buffer is not updated correspondingly.

It looks like the view buffer gets detached after an update? Because after all this, calling `mu4e-view-attach`, it works again. I believe this is a regression in 1.10 (after the attach/detach functionality), since I remember this working in previous versions.

**How to Reproduce**

Set `mu4e-update-interval` to something small (for faster reproduction), e.g.:

```lisp
;;; bug.el ---                                       -*- lexical-binding: t; -*-

(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")
(require 'mu4e)

(setq mu4e-get-mail-command "mbsync -a -c ~/.mbsyncrc")

(setq mu4e-update-interval 10)
```

Start `mu4e` (e.g. `emacs -Q -l bug.el` then `M-x mu4e` ). Then open a message from the headers buffer. While focus is in the newly opened view buffer, wait until an update happens (the headers buffer will refresh). Now press `n`/`p` and watch the headers buffer highlight the next/previous buffer but the message view buffer still has the old message.

**Environment**

Linux 5.15, emacs 28.3 and mu/mu4e 1.10.5.

**Comment by djcb** [comment]
We no longer update headers when looking at a message; so this problem should be gone (in `master`).
