### ISSUE TITLE
[mu4e bug] Incorrect TO and CC lists when reply-all to a message I sent

### ISSUE THREAD

**Issue by danielfleischer** [djcb/mu#2524]
**Describe the bug**
Given an email I previously sent with **TO** and **CC** lists, I want to reply all in order to "continue" the thread, choosing replying to all recipients. 

What I expect: new email draft with the **same** TO: and CC: lists. 

What I get: **all** recipients are now in the TO: list. 

**Environment**
Mac, Emacs 29.0.2. Mu Version 1.11.8. `mu4e-compose-dont-reply-to-self` is set to t. 

**Comments**
TO and CC lists are reconstructed correctly when I am not the original sender so it has something to do with the fact that the sender is self.

**Comment by djcb** [comment]
Merged: https://github.com/djcb/mu/pull/2530
Thanks.
