### ISSUE TITLE
[mu bug] memory consumption dramatically higher with 1.10.5 than with 1.8.14

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#2529]
**Describe the bug**
Same database of 300 000 messages. mu 1.8.14 can index it in under 10 minutes, using less that 8 Gb of RAM. However, 1.10.5 eats 8Gb at about half, and then becomes painfully slow, while still consuming RAM. Eventually all the RAM is not enough. I think, memory consumption is about 3 times 1.8.14, but I haven't managed to wait for completion with all the swaping-in.

**To Reproduce**
Re-index the same database and measure memory consumption.

**Environment**
Linux, xapian-core 1.4.19

**Checklist**
- [x] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
I think it's because mu indexes a lot more, in particular html mail; however, you can reduce memory consumption with the `--batch-size` parameter to `mu init`. Try e.g., `--batch-size=10000`.
