### ISSUE TITLE
[mu bug] mu4e 1.11 can't find my contacts

### ISSUE THREAD

**Issue by freesteph** [djcb/mu#2532]
**Describe the bug**
After upgrading to 1.11 `mu4e-contacts-info` can only find two contacts in my maildir, whereas `mu cfind` outputs 4088 of them.

**To Reproduce**
- run `mu4e-contacts-info` from Emacs ;
- compare with `mu cfind` output.

**Environment**
Mac OS
`GNU Emacs 29.1 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.5.1 (Build 21G83))
 of 2023-07-25`

**Checklist**
Running `1.11.14`
- [X] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

I'm aware it's a bit slim of a bug report but hopefully you can help me debug on my side first. Thank you!

**Comment by danielfleischer** [comment]
Noticed this already at 6dfb2aae.

**Comment by djcb** [comment]
I noticed it too; pushed a fix.

**Comment by freesteph** [comment]
Thank you very much for the prompt fix, it works for me ✅
