### ISSUE TITLE
[mu4e bug] orphan page section 9.5 'some context tricks'

### ISSUE THREAD

**Issue by sleepyMonad** [djcb/mu#2533]
**Describe the bug**

I discovered https://www.djcbsoftware.nl/code/mu/mu4e/Some-context-tricks.html by accicent, it's not linked into the hierarchy (table of contents, 'next page' link from 9.4.)

Or perhaps it's obsolete?

**Comment by djcb** [comment]
It's a leftover html page of an older version. Anyway, I clean it up - thanks.
