### ISSUE TITLE
[mu4e bug] No maildir completion after refile

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2537]
**Describe the bug**
The completion list after a refile is empty

**How to Reproduce**

Start mu, mark a message to be refiled (`mo`).  Next time you refile or just want to jump to a different maildir, there are no completions.

**Environment**
Debian testing
mu commit 0b626409

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by Chris00** [comment]
The same holds true (no maildir completions anymore) after marking a message for deletion *and* executing the mark.

**Comment by Chris00** [comment]
After these operations `(mu4e-get-maildirs)` returns `nil`.  (BTW `mu4e-cache-maildir-list` is unused.)

**Comment by Chris00** [comment]
The following modification
```diff
@@ -242,6 +242,7 @@ to create it; otherwise return nil."
       ;; when the maildir is totally new.
       (mu4e--server-mkdir dir (not seems-to-exist))
       (setq mu4e-maildir-list nil) ;; clear cache
+      (mu4e--server-data 'maildirs) ;; Request the list again
       t)))
```
fixes the bug but I'm not sure it has the desired efficiency...

**Comment by markk** [comment]
It looks like this promise:

```
If you do so, you can set `mu4e-maildir-list' to nil to force
regenerating the cache the next time `mu4e-get-maildirs' gets
called.
```

is not fulfilled by `mu4e-get-maildirs':

https://github.com/djcb/mu/blob/0b62640962a5adc60f85e88d5b7512a333e577d6/mu4e/mu4e-folders.el#L247

which just returns `mu4e-maildir-list` without checking it.

**Comment by markk** [comment]
Maybe:

``` elisp
(defun mu4e-get-maildirs ()
  "Get maildirs under `mu4e-maildir'."
  (unless mu4e-maildir-list
    (setq mu4e-maildir-list (mu4e--server-plist-get sexp :maildirs)))
  mu4e-maildir-list)
```

**Comment by markk** [comment]
Maybe:

``` elisp
(defun mu4e-get-maildirs ()
  "Get maildirs under `mu4e-maildir'."
  (unless mu4e-maildir-list
    (mu4e--server-data 'maildirs))
  mu4e-maildir-list)
```

**Comment by Chris00** [comment]
I thought of that but the problem is that the call is asynchronous so `mu4e-maildir-list` is returned before the call is completed.
