### ISSUE TITLE
[mu bug] type of mu4e-compose-complete-max is wrong

### ISSUE THREAD

**Issue by jian-lin** [djcb/mu#2544]
**Describe the bug**
defcustom specifies that the type of mu4e-compose-complete-max is string.  However, if you set it to a string, mu4e errors:
```
[mu4e] Error 102: parameter :maxnum expects type number, but got string in command '(contacts :personal t :after "2000-01-01" :tstamp "0" :maxnum "111")'
```

**Environment**
mu 1.10.6

**Checklist**
- [X] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

edit:
Sorry, I chose the wrong tag.  This is a mu4e bug.

**Comment by djcb** [comment]
This was fixed in master, now backported to 1.10.7
