### ISSUE TITLE
Search results won't display if another frame is already visible, but out of sight

### ISSUE THREAD

**Issue by mrvdb** [djcb/mu#2545]
Executing a search (or visiting a bookmark) will not display search results if an existing result-headers window is visible somewhere, either minimized or on another workspace as is the case for me.

This gets confusing sometimes, as it seems as though nothing is happening when there is a frame on another workspace that happens to display (old) search results.

This particular situation can be remedied quite easily by this tiny patch:

```diff --git a/mu4e/mu4e-headers.el b/mu4e/mu4e-headers.el
index 425760b6..e9347bd4 100644
--- a/mu4e/mu4e-headers.el
+++ b/mu4e/mu4e-headers.el
@@ -808,7 +808,7 @@ defun mu4e--search-execute
 
     ;; when the buffer is already visible, select it; otherwise,
     ;; switch to it.
-    (unless (get-buffer-window buf 0)
+    (unless (get-buffer-window buf nil)
       (mu4e-display-buffer buf t))
     (run-hook-with-args 'mu4e-search-hook expr)
     (mu4e~headers-clear mu4e~search-message)
```

which will only consider the active frame for visibility checks.  (see doc below of get-buffer-window)

```
Signature
(get-buffer-window &optional BUFFER-OR-NAME ALL-FRAMES)

Documentation
Return a window currently displaying BUFFER-OR-NAME, or nil if none.

BUFFER-OR-NAME may be a buffer or a buffer name and defaults to
the current buffer.

The optional argument ALL-FRAMES specifies the frames to consider:

- t means consider all windows on all existing frames.

- visible means consider all windows on all visible frames.

- 0 (the number zero) means consider all windows on all visible
    and iconified frames.

- A frame means consider all windows on that frame only.

Any other value of ALL-FRAMES means consider all windows on the
selected frame and no others.
```

This would suffice for my usecase, i.e. display search results on the selected frame always, but I can imagine other usecases.

**Comment by djcb** [comment]
Ah, good catch, thanks

**Comment by djcb** [comment]
Ah, so I have a frame somewhere with the headers view; I'm working in the same emacs on something else; now when I receive a message, my "something else" is replaced by the headers-view.

I didn't have time to debug, but it was a bit annoying, so I reverted. I think your change is a step in the right direction though!

**Comment by mrvdb** [comment]
I think `mu4e-headers-auto-update` is the cause. I have that set to `nil`. If I set it to `t` I get the headers view in my face as soon as my inbox is updated.

Tested as such:
- opened bookmark INBOX on frame 
- switched to another workspace, other frame in same emacs
- send email with separate machine to self and wait for it to arrive

with mu4e-headers-auto-update set to nil (my setting), nothing happens

**Comment by mrvdb** [comment]
Taking the effect of auto updating headers into account this could be sufficient to eliminate the side-effect of the first patch:

```diff --git a/mu4e/mu4e-headers.el b/mu4e/mu4e-headers.el
index 425760b6..2158efd8 100644
--- a/mu4e/mu4e-headers.el
+++ b/mu4e/mu4e-headers.el
@@ -808,7 +808,11 @@ defun mu4e--search-execute
 
     ;; when the buffer is already visible, select it; otherwise,
     ;; switch to it.
-    (unless (get-buffer-window buf 0)
+    (unless (get-buffer-window
+             buf (if mu4e-headers-auto-update
+                     0  ; get buffer from  all frames
+                   nil  ; get buffer from active frame only
+                   ))
       (mu4e-display-buffer buf t))
     (run-hook-with-args 'mu4e-search-hook expr)
     (mu4e~headers-clear mu4e~search-message)
```

**Comment by djcb** [comment]
That avoids the side-effect, but does a bit too much, I think. 

The criterion is not really if user has `mu4e-headers-auto-update` _enabled_, but instead whether `mu4e--search-execute` call is 'automatic' or user initiated. In the latter case, it should follow the `nil` behavior regardless of the value of `mu4e-headers-auto-update`, I think.

**Comment by mrvdb** [comment]
agreed, that would be better. It's not apparent to me how that needs to be done though. Seems a bit more surgery would be needed for it.

**Comment by djcb** [comment]
I'll try to cook something up.

**Comment by mrvdb** [comment]
Thanks!
