### ISSUE TITLE
[mu4e rfe]

### ISSUE THREAD

**Issue by brittAnderson** [djcb/mu#2549]
Update the mail database when quitting mu4e.

I suspect this functionality exists, I just can't find the description. I was looking for a hook when mu4e-quit is run so that I could run mbsync --all right before quitting (others might use offlineimap) to make sure that I did not leave anything hanging that had not been synced with the main locations of my mail.

Maybe advising the function `mu4e-quit` to run the command line `mbsync --all` would be the way to go?

Appreciate being guided to how others are handling this or adding to the list of feature requests if it does not exist. 

Thanks

**Comment by djcb** [comment]
Yeah, I think advising that function is the best way to do it for now.
