### ISSUE TITLE
[mu bug] mu does not index very large message?

### ISSUE THREAD

**Issue by wilderjds** [djcb/mu#2550]
**Describe the bug**
A clear and concise description of what the bug is, what you expected to happen and what actually happened.

I receive occasionally very large email messages (ugh, >100Mb); one of them is present in the maildir, but does not show up in the index.  Is there a hard limit on the size of messages and larger files are silently ignored? 

**To Reproduce**
Detailed steps to reproduce the behavior. If this is about a specific (kind of) message, **always** attach an (anonymized as need) example message.

**Environment**
Please describe the versions of OS, Emacs, mu etc. you are using.
Gentoo linux, emacs 28.2, mu 1.10.3

**Checklist**
- [ ] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
Yes, there's the `--max-message-size=<size>` parameter to `mu init`.
