### ISSUE TITLE
[mu4e rfe] How to get :body-html and :body-txt

### ISSUE THREAD

**Issue by ST-Saint** [djcb/mu#2551]
I was expecting to use mu4e-message-field and get `:body-html` and `:body-txt` for rendering, but I noticed that `mu fields` don't have these two fields now. Is there still a way to get the contents of the message now?

Thanks

**Comment by djcb** [comment]
No, those have gone quite some time ago; we don't have those available anymore (for speed reasons).
You can get the full raw message text with `mu4e-view-message-text` though, and extract the parts you need from there.
