### ISSUE TITLE
[mu4e bug] Compatibility with emacs 31's eldoc

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#2553]
**Describe the bug**
It seems that the prototype of eldoc documentation functions has changed in emacs 30.0.50, and now enabling `(setf mu4e-eldoc-support 1)` makes eldoc complain in the *Messages* buffer: 
```
eldoc error: (wrong-number-of-arguments (4 . 4) 5)
```

**To Reproduce**
Run emacs from master, say tag `f13b08be11533c546fed257dcf8e3812a53b672a`.

**Environment**
Emacs f13b08be11533c546fed257dcf8e3812a53b672a , mu4e 1.10.7

**Checklist**
- [x] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by lockywolf** [comment]
Sorry, the label is wrong, and I do not know how to change it.

**Comment by djcb** [comment]
If you want to use an unreleased emacs and even file bugs for that, you really have to spend some time on getting all the details, elisp stack traces, functions that changed etc.

**Comment by lockywolf** [comment]
So, basically, looking at the documentation for `eldoc-documentation-functions` hook-variable.

>Each hook function is called with at least one argument CALLBACK,
>a function, and decides whether to display a short doc string
>about the context around point.
>- If that decision can be taken quickly, the hook function may
>  call CALLBACK immediately, following the protocol described
>  below.  Alternatively, it may ignore CALLBACK entirely and
>  return either the doc string, or nil if there’s no doc
>  appropriate for the context.
>- If the computation of said doc string (or the decision whether
>  there is one at all) is expensive or can’t be performed
>  directly, the hook function should return a non-nil, non-string
>  value and arrange for CALLBACK to be called at a later time,
>  using asynchronous processes or other asynchronous mechanisms.

So, the part about 
>Alternatively, it may ignore CALLBACK entirely and
>  return either the doc string, or nil if there’s no doc
>  appropriate for the context.
is called "Old Protocol" in the new emacs, and is broken by default.
I have reported a bug about it, but it seems, since it is called "old", this way of getting documentation will be soon decommissioned.

I suggest returning `t` from `mu4e-headers-eldoc-function`, and calling that `CALLBACK` immediately with the docstring.

Maybe this will work, at least  I have patched that function myself and it seems to work:
```
(defun mu4e-headers-eldoc-function (callback &rest _args)
  (let ((msg (get-text-property (point) 'msg)))
    (when msg
      (let ((retval (format-spec
                     mu4e-headers-eldoc-format
                     `((?s . ,(mu4e-message-field msg :subject))
                       (?f . ,(mu4e~headers-contact-str (mu4e-message-field msg :from)))
                       (?t . ,(mu4e~headers-contact-str (mu4e-message-field msg :to)))
                       (?c . ,(mu4e~headers-contact-str (mu4e-message-field msg :cc)))
                       (?d . ,(mu4e~headers-human-date msg))
                       (?p . ,(mu4e-message-field msg :priority))
                       (?m . ,(mu4e-message-field msg :maildir))
                       (?F . ,(mu4e-message-field msg :flags))
                       (?M . ,(mu4e-message-field msg :message-id))))))
        (funcall callback retval)
        t))))
```

**Comment by lockywolf** [comment]
Okay, this issue is actually due to my setup, not mu4e. Things should continue working with Emacs 31, at least.

However, the adaptation to the "new" protocol should be still valid. I don't know if it is reasonable to merge it.

**Comment by djcb** [comment]
PR is welcome, but please ensure that it doesn't break older Emacs, thanks. Closing this one.
