### ISSUE TITLE
[mu bug] Excluding several maildirs no longer works

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2557]
**Describe the bug**
```
mu find "NOT flag:trashed AND NOT maildir:/Spam AND NOT maildir:/WORK/Junk"
```
returns messages in both excluded folders and even trashed messages.

**To Reproduce**
Run a query excluding several maildirs.

**Environment**
Emacs 29.1
Debian GNU/Linux
mu commit #5bda8c32

**Checklist**
- [x] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
For now, use: 
```
mu find "(NOT flag:trashed) AND (NOT maildir:/Spam) AND (NOT maildir:/WORK/Junk)"
```

**Comment by djcb** [comment]
Can you try with the latest? Thanks.

**Comment by Chris00** [comment]
Back to normal.  Thanks!
