### ISSUE TITLE
[mu bug] Cannot Initialize more than one directory

### ISSUE THREAD

**Issue by opensource-philosophy** [djcb/mu#2558]
**Describe the bug**
I have configured two separate email addresses in `.mbsyncrc`. I have one overarching `maildir`, whose subfolders are `maildir1` and `maildir2`; one for each email address. When trying to add them both using `mu init`, only the mail account added last is considered. 

**To Reproduce**
```
mu init  --my-address=<mail1> --maildir=maildir1
mu index
mu init  --my-address=<mail2> --maildir=maildir2
mu index 
mu info
```
Same problem with
```
mu init  --my-address=<mail1> --maildir=maildir1
mu init  --my-address=<mail2> --maildir=maildir2
mu index 
mu info
```
The problem about this is that `mu4e-personal-addresses` will only find the mail address initialized last; you always get a one-element list.  `mu4e-root-maildir` also returns `maildir2` instead of the superfolder `maildir`. Thus, I cannot access mails from both accounts.

**Environment**
I am on (Garuda) Arch Linux, Emacs Version 29.1, mu 1.10.5.

**Comment by djcb** [comment]
`mu init` can take `--my-address` multiple times (see the manpage).  And a specific mu database (`mu init`) can take only _one_ root maildir; so just make your maildir1/maildir2 subdirs of that one.
