### ISSUE TITLE
[mu bug] Improper NOT operator handling

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#2559]
**Describe the bug**
In the query parser of 1.11.15, "a NOT b" would be equivalent to "a AND NOT b", following the logic that each token is implicitly ANDed together, and NOT associating with higher precedence "a AND (NOT b)".

This is no longer the case in the current master as of 8fc13ab8f31ba56efc88a2df66259594b5b7c3af, where it's not clear what "a NOT b" does (seems "a OR NOT b"?).

Although explicitly querying either "a AND NOT b" or "a (NOT b)" works as intended.

**To Reproduce**
As above.

**Environment**
Debian unstable.

**Checklist**
- [x] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by Chris00** [comment]
Have a look to https://github.com/djcb/mu/issues/2557  (in particular, you can see how your query is parsed with `--analyze`).

**Comment by wavexx** [comment]
Seems still broken:

```
* query:
  a NOT b
* parsed query:
  (_ "a")
```

**Comment by wavexx** [comment]
Looking good now, I couldn't spot regressions at the moment.
