### ISSUE TITLE
[mu4e rfe] Display the URL in the quotation when forwarding or answering to an HTML message

### ISSUE THREAD

**Issue by jpggithub** [djcb/mu#2563]
When I want to forward an HTML mail with hyperlinks to someone, the quotation of the original mail contains only the text of the links, not the URLs. 

So the person will not be able to access to the links given in the original mail.

When I reply to a mail, the same thing happens.

I searched the mu4e documentation and also on the web, I did not find a way to achieve that.

**Comment by djcb** [comment]
Please use the bug template the next time... anyway, the good news is that the new message composer (in `master`) handles this correctly. So closing this...
