### ISSUE TITLE
[mu4e bug] "Recursive load" error while bytecompiling .elc

### ISSUE THREAD

**Issue by ahttraga** [djcb/mu#2565]
**Bug Description**
Compile fails with "Recursive load" error during bytecompile of emacslisp files using developmental emacs v30.0.50

**How to Reproduce**
During standard ninja compile, byte compilation of .el files gives the following error:

```
/Users/cog/bin/emacs --no-init-file --batch --directory /Users/cog/src/mu/build/mu4e --directory /Users/cog/src/mu/mu4e --eval '(setq load-prefer-newer t)' --eval '(setq byte-compile-warnings '"'"'(not obsolete))' --eval '(setq byte-compile-dest-file-function(lambda(_) "/Users/cog/src/mu/build/mu4e/mu4e-draft.elc"))' --funcall batch-byte-compile ../mu4e/mu4e-draft.el
>>Error occurred processing ../mu4e/mu4e-draft.el: error (("Recursive load" "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz" "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz" "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz" "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz" "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz" "/Applications/Emacs.app/Contents/Resources/lisp/emacs-lisp/icons.el.gz" "/Users/cog/.emacs.d/eln-cache/30_0_50-528dc109/warnings-28e75f4d-9f48f568.eln"))
```

**Workaround**
This error may be due to use of `(setq load-prefer-newer t)` flag when compiling, which is known to produce recursive load errors with `jka-compr`:

- [Prelude](https://github.com/bbatsov/prelude/issues/1134)
- [GNU Emacs mailing list archives](https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-12/msg02365.html)
- [airy-docker-emacs](https://github.com/jgkamat/airy-docker-emacs/issues/1)

Uncompressing `jka-compr.el.gz` in the Emacs lisp directory allows compilation to succeed.

**Environment**
MacOS, emacs development branch 30.0.50

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Seems like an emacs bug... but I think I can work around it; simply removing `load-prefer-newer` is not enough, since it  yields byte-compiler warnings.
