### ISSUE TITLE
[mu bug] mu init -m won't accept spaces on the name

### ISSUE THREAD

**Issue by MinallW** [djcb/mu#2566]
**Describe the bug**
When trying to do a mu init -m targeting a folder with a space, it will break the variable and only get the first part as expected when the space is not escaped, however, using "" around the directory path and escaping won't work either. So there's not much option to put a directory with a space in it.

I was putting my mail directory to be specifically in:
/Users/Minall/Library/Mobile Documents/com~apple~CloudDocs/メール

So it gets /Users/Minall/Library/Mobile <- A directory which I cannot change its name since it is from my iCloud directory. I wanted to sincronise my saved mails.

For a fix on this, I created a symlink which allows me to put HOME/.mail to that directory. With that I can read and send messages. Now sending mail works, the message goes through but, this error appears:

`mu4e-error: [mu4e] Error 107: root '/Users/Minall/.mail' is not a root for path '/Users/Minall/Library/Mobile Documents/com~apple~CloudDocs/メール/drafts/cur/1696539002.02cb8b8db04530c3.miguels-macbook-air:2,DS'
`

**To Reproduce**
`
mu init -m /Users/Minall/Library/Mobile Documents/com~apple~CloudDocs/メール --my-address xxxxx@xxxx.com
`
Also tried enclosing with "" and Mobile\ Documents/com...

**Environment**
MacOS Sonoma 14.0
Emacs 29.1
mu 1.10.7
**Checklist**
- [X] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
Ah... I suspect the file name expansion doesn't like the ' '.  I'll see if I can fix that... in the meantime, you can try something like:
 `-m '/Users/Minall/Library/Mobile\ Documents/com~apple~CloudDocs/メール'`
(note the `\` after 'Mobile')

**Comment by MinallW** [comment]
Thank you very much, this solution works perfectly and, it solved my 'is not a root path' issue.
