### ISSUE TITLE
Starting mu4e causes mu core dump after 1.11.17 

### ISSUE THREAD

**Issue by mrvdb** [djcb/mu#2567]
After revision 080cf43b4a206d1c9010f89759b4dc04bdf540a5 (version 1.11.17) mu crashes on my machine.

I am on a talos II machine, so this might be `ppc64le` specific.

Observed behaviour:
- mu compiles cleanly, passes all tests
- mu cli works, find/index etc. all work fine
- starting mu4e causes errors:

```
error in process sentinel: mu4e-error: [mu4e] server process received signal 6
error in process sentinel: [mu4e] server process received signal 6

and dumps core with the following backtrace:

```
Process 1007981 (mu) of user 1000 dumped core.
                                                   
 Module libblkid.so.1 without build-id.
 Module ld64.so.2 without build-id.
 Module libuuid.so.1 without build-id.
 Module libffi.so.8 without build-id.
 Module libmount.so.1 without build-id.
 Module libgpg-error.so.0 without build-id.
 Module libassuan.so.0 without build-id.
 Module libgpgme.so.11 without build-id.
 Module libz.so.1 without build-id.
 Module libgthread-2.0.so.0 without build-id.
 Module libgmodule-2.0.so.0 without build-id.
 Module libpcre.so.1 without build-id.
 Module libc.so.6 without build-id.
 Module libgcc_s.so.1 without build-id.
 Module libm.so.6 without build-id.
 Module libstdc++.so.6 without build-id.
 Module libxapian.so.30 without build-id.
 Module libgobject-2.0.so.0 without build-id.
 Module libgio-2.0.so.0 without build-id.
 Module libgmime-3.0.so.0 without build-id.
 Module libglib-2.0.so.0 without build-id.
 Module mu without build-id.
Stack trace of thread 1007981:
 #0  0x00003ffff701f90c __pthread_kill_implementation (libc.so.6 + 0xaf90c)
 #1  0x00003ffff6fbfdac raise (libc.so.6 + 0x4fdac)
 #2  0x00003ffff6fa04d4 abort (libc.so.6 + 0x304d4)
 #3  0x00003ffff7486bc8 _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x106bc8)
 #4  0x00003ffff7481f84 n/a (libstdc++.so.6 + 0x101f84)
 #5  0x00003ffff7480398 n/a (libstdc++.so.6 + 0x100398)
 #6  0x00003ffff748137c __gxx_personality_v0 (libstdc++.so.6 + 0x10137c)
 #7  0x00003ffff71f8c0c n/a (libgcc_s.so.1 + 0x18c0c)
 #8  0x00003ffff71f99a8 _Unwind_Resume (libgcc_s.so.1 + 0x199a8)
 #9  0x000000001010062c n/a (mu + 0x10062c)
 #10 0x0000000010111c68 n/a (mu + 0x111c68)
 #11 0x000000001011570c n/a (mu + 0x11570c)
 #12 0x00000000101159c0 n/a (mu + 0x1159c0)
 #13 0x0000000010115b1c n/a (mu + 0x115b1c)
 #14 0x00000000100f2ec8 n/a (mu + 0xf2ec8)
 #15 0x000000001012ed8c n/a (mu + 0x12ed8c)
 #16 0x000000001012f2ac n/a (mu + 0x12f2ac)
 #17 0x000000001015f14c n/a (mu + 0x15f14c)
 #18 0x00000000101301fc n/a (mu + 0x1301fc)
 #19 0x000000001013085c n/a (mu + 0x13085c)
 #20 0x00000000100d6534 n/a (mu + 0xd6534)
 #21 0x00000000100e4814 n/a (mu + 0xe4814)
 #22 0x00000000100255f4 n/a (mu + 0x255f4)
 #23 0x00003ffff6fa0898 __libc_start_call_main (libc.so.6 + 0x30898)
 #24 0x00003ffff6fa0a78 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x30a78)
 ELF object binary architecture: PowerPC64

**Comment by djcb** [comment]
"After 1.11.17", so you cannot reproduce with 1.11.16?

In any case, would need a backtrace with symbols, and/or try reproduce with `gdb`, like... 
```gdb  --args mu server``` 
and then `run`. Thanks.

**Comment by mrvdb** [comment]
[Dirk-Jan C. Binnema]:
> "After 1.11.17", so you cannot reproduce with 1.11.16?

Indeed, 1.11.16 works fine

> ```gdb  --args mu server```

How would that work from within emacs, set mu-binary to run the 
above command?

**Comment by djcb** [comment]
I suspect that if it aborts immediately, that will also happen if you just start `mu server` from gdb directly, without emacs.

**Comment by mrvdb** [comment]
It does not, running mu from a shell outside of emacs works fine.

**Comment by djcb** [comment]
Ah, so then it's probably something that mu4e asks mu to do... so can you create a backtrace with symbols? 
And there may be something in the logs (either the systemd log, or a log file in the mu4e directory). Thanks.

**Comment by mrvdb** [comment]
Getting the backtrace with symbols needs some local config apparently, working on getting that to work properly

In the meantime in the mu4e log: 

```
2023-10-09 07:52:00.862 * invoking '/home/mrb/dat/src/emacs/packages/mu/build/mu/mu' with parameters 'server'
2023-10-09 07:52:00.862 -> (queries :queries ("flag:unread and not flag:trashed" "(flag:unread or flag:new or maildir:/INBOX) and not (flag:draft or flag:flagged or flag:deleted or maildir:/Trash or flag:trashed)" "flag:flagged and not flag:trashed" "date:today..now" "maildir:/Trash or flag:trashed" "maildir:/Junk"))
2023-10-09 07:52:00.862 -> (ping)
2023-10-09 07:52:00.863 -> (data :kind maildirs)
2023-10-09 07:52:00.863 -> (contacts :personal nil :after nil :tstamp "0" :maxnum nil)
2023-10-09 07:52:01.058 * Received 108 byte(s)
2023-10-09 07:52:01.086 * Received 108 byte(s)
2023-10-09 07:52:01.197 * famous last words from server: ';; Welcome to the mu 1.11.22 command-server
;; Use (help) to get a list of commands, (quit) to quit.
;; mu> terminate called after throwing an instance of 'std::logic_error'
  what():  no bare strings should be here
'
2023-10-09 07:52:01.197 !! [mu4e] server process received signal 6

**Comment by djcb** [comment]
Ah, that's useful; no need for a symbol backtrace then, I think. 

The problems is that the (new) query-parser barfs on the 'flag:deleted' in one of the queries (there's no such flag, see `mu info fields`).Anyway, we should handle a bit more gracefully.

**Comment by mrvdb** [comment]
Removing the `flag:deleted` solves the crash indeed. Thanks.
