### ISSUE TITLE
[mu4e rfe] Support for `message-alternative-emails`

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#2571]
**Is your feature request related to a problem? Please describe.**

`message-mode`, which mu4e's "send message" function is based upon, supports "alternative emails", which is very similar to mu's `--my-address`  option. If an email arrives to an address which matches a pattern, a response to this message will be using the same address. You are going to respond From: the address in To:. This pattern is listed in the `message-alternative-emails` variable.
mu4e by default seems to override this variable, and set the From: address unconditionally to `user-email-address` (which can depend on the mu4e-context, but is otherwise static). I would like mu4e to not do this, and just follow message's default behaviour.

**Describe the solution you'd like**
Effectively, make mu4e use `message-reply`.

**Describe alternatives you've considered**
I considered adding some trickery to `message-setup-hook`, or just calling `message-reply` directly, but I am thinking that it would still be cleaner if `mu4e-compose-reply` would do that instead.

**Additional context**
Not really. I saw that `mu4e-compose-mode` is based on `message-mode`, and thought that such a function would be relatively simple to implement.

**Comment by djcb** [comment]
Currently, that's quite far from "relatively simple" since mu4e has its own machinery from drafts. 
But, there's ongoing work on moving mu4e's composer closer to `message`.
