### ISSUE TITLE
[mu4e bug] Compose/reply switch contexts but does not open a message buffer

### ISSUE THREAD

**Issue by pierreaoquadrado** [djcb/mu#2575]
**Describe the bug**
When trying to compose or reply a message with `mu4e-compose-context-policy` set to `'always-ask`, the "Select context:" message is displayed and I can select one of them. The context changes in the modeline, but that's it. The message buffer is not created.

**How to Reproduce**
Hit "C" for compose or "R" to reply, select a context (bound to "G" for personal mail, "U" for work mail), the context changes on the modeline and... nothing else.

**Environment**
Archlinux, with mu (git master branch) updated today. Emacs 29.1 with nativecomp and Doom.

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [ ] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

Sorry, I have no idea how to reproduce it without all Doom machinery 😢, but reverting to Release 1.10.7 fixes the problem. Can it be something related to d923890e2b4633659e3df5d923aae400f8212e41?

Thank you very much!

**Comment by djcb** [comment]
Doom does a "remix" of mu4e, depending on various internals, `advice` etc., which is rather fragile, in particular the combination with the 1.11.x development mu4e.

So I'd recommend using 1.10.x until Doom updates things (perhaps they should wait for the next stable release); perhaps file a ticket there. Or you start using the non-Doom mu4e. 

There's little we can do here, so closing this. Good luck!
