### ISSUE TITLE
[mu4e bug] mu4e-compose-dont-reply-to-self broken

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#2584]
**Describe the bug**
In master as of 5b29ad8b6d279d7abc3b665234bfe5aac282564c, replying to one's self with `mu4e-compose-dont-reply-to-self` no longer works.

**How to Reproduce**
Reply to an email, then reply to the reply with `mu4e-compose-dont-reply-to-self` set to t. The reply is addressed to yourself instead of the original recipient.

**Environment**
emacs (master) on debian unstable

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above
- [x] added one for free

**Comment by djcb** [comment]
This has slightly changed I think -- this uses `message-dont-reply-to-names` now... does that not work for you? Note that this only does anything with `mu4e-compose-reply-wide` `W` wide replies.

**Comment by wavexx** [comment]
> This has slightly changed I think -- this uses message-dont-reply-to-names now... does that not work for you?

It does use (mu4e-personal-addresses) and message-dont-reply-to-names together looking at the code right?. Note that I had already customized dont-reply-to-names to ignore bogus addresses when doing replies. These are not "self". message-alternative-emails seems to be the proper "message" equivalent, which is already overridden for this purpose.

> Note that this only does anything with mu4e-compose-reply-wide W wide replies

A-ha, that does indeed work, but I would still consider this a bug. A non-wide reply should also behave like before IMHO. In addition, in the wide reply, I'm cc-ed even though the cc is one of my personal addresses too.

**Comment by djcb** [comment]
Yeah, it's a bit confusing. But basically we'll follow what `message` does for the replies, even it's a little different from what `mu4e` used to do

I'll remove `mu4e-compose-dont-reply-to-self` as you can achieve the same effect with `message-dont-reply-to-names`. There's also `message-prune-recipient-rules`. All that is for wide-replies. 

For further fine-tuning, there's `message-reply-to-function`, and hooks.

**Comment by djcb** [comment]
While we're still ironing out some rough edges in the new composer implementation, it would be interesting if there's something you need that is not covered somehow, i.e., if you have an example message, and how you'd expect the reply / wide-reply to look like.

**Comment by wavexx** [comment]
I didn't have too much time to fiddle with my current message-* vars, but I still think we should try to respect the old behavior.

I found this my ooold thread while searching for gnus/message configuration and replicate this feature in gnus at the time:

  https://lists.gnu.org/archive/html/info-gnus-english/2010-12/msg00543.html

I can't recall right now though if the "Followup" behavior is actually implemented by gnus on _top_ of message.

I'm somewhat partial to somehow either keep or reimplement the old behavior of reply-to-self. If any of your addresses is seen in From, then the first To: should be used as a recipient. message-dont-reply-to-names doesn't seem to fit the purpose here, I already prefilled this var to skip stuff such as "noreply" and similar addresses. It also seems like we should leverage message-alternative-emails instead of hooking into it, but I'm not sure about the implications.

Also, reply/wide reply should be independent from reply-to-self. A wide reply to self should replicate also the Ccs into the reply.

**Comment by djcb** [comment]
Reading the ML thread, perhaps `message-followup` could help? (we don't currently currently expose that). 

I don't want to re-implement things, but surely we can hook up existing functionality in Gnus/message, or even add an example hook in the documentation. Do you want to work on that?

**Comment by thierryvolpiatto** [comment]
AFAIU `mu4e-compose-reply-ignore-address` counterpart is now `message-dont-reply-to-names` and `mu4e-compose-dont-reply-to-self` is no more needed if your address(es) is/are in `message-dont-reply-to-names`.
But maybe I am wrong... The entry in NEWS is unclear and perhaps wrong as `message-prune-recipient-rules` seems to be something else and its Gnus documentation is not clear either.  Seems really complicated to use anyway.

**Comment by djcb** [comment]
`message-dont-reply-to-names` works for weeding addresses from wide-replies; however I think the OP is after the behavior that any reply to a message you sent would be like a follow up with the same recipients (as in the linked ML thread).

**Comment by wavexx** [comment]
Just adding my lazy 2c here (sorry, didn't even have time to fiddle with message vars yet). From an ergo point of view, I still prefer the old behavior, which is what a follow-up to a post to self would do in nntp (gowd, I'm old).

Following up to yourself makes it clear you're adding info to an existing context and doesn't require support in the client. I guess most email clients will just show you the same message twice.. so you're pretty much forced to point out what's new in the new message, which is what a reply to self always makes clear due to quoting.

supersede is nice to have, but once a message has been sent, I really don't see the "value" for the reader/s.

**Comment by djcb** [comment]
Something like this is a bit rought but get closer?
```

;;;###autoload
(defun mu4e-compose-supersede (&optional cite)
  "Supersede message at point.

That is, send the message again, with all the same recipients;
this can be useful to follow-up on a sent message. The message
must be from current user, as determined through
`mu4e-personal-or-alternative-address-p'.

With prefix-argument CITE, cite the message and remove
attachments."
  (interactive "P")
  (mu4e--compose-setup
   'reply ;; it's a special kind of reply.
   (lambda (parent)
     (insert (mu4e--decoded-message parent))
     (set-buffer-modified-p nil)
     (message-supersede)
     (when cite
       (save-excursion
         (message-goto-body)
         (remove-overlays (point) (point-max))
         (kill-region (point) (point-max))
         (insert (mu4e--compose-cite parent)))))))```

**Comment by wavexx** [comment]
Went through the rabbit hole... A wide reply does what I want when customizing message-dont-reply-to-names, so I decided to go with this piece of advice:

```
(setq message-wide-reply-to-self t)

;; improve handling of reply-to-self
(defun message--reply-custom (fn &optional to-address wide switch-function)
  ;; seed message-dont-reply-to-names with our address/es
  (let* ((user-regex (if (not wide)
			 (regexp-quote user-mail-address)
		       (mapconcat (lambda (elt) (concat "\\(" (regexp-quote elt) "\\)"))
				  (mu4e-personal-addresses) "\\|")))
	 (message-dont-reply-to-names (concat user-regex "\\|" message-dont-reply-to-names))
	 (from (message-field-value "from")))
    ;; are we replying to ourself?
    (when (and message-wide-reply-to-self (string-match user-regex from))
      ;; perform a wide reply instead
      (setq wide t))
    (apply fn to-address wide switch-function)))

(advice-add 'message-reply :around 'message--reply-custom)
```

This is not foolproof: it assumes message-dont-reply-to-names is already defined as a single regex, which I already had populated with several noreply patterns over time.

When replying, we dynamically append our address (or addresses) in the list, then set the reply to be wide if the "from" address is "us". The logic is that if I'm following up to myself, I'm already ok to have the same previous recipient list. The difference between regular and wide in this case becomes if we want to also suppress duplicates to ourselves from other accounts or not.

If you're interested, I can give feedback after using this for a while...

**Comment by djcb** [comment]
Oh, sure, would be interested in the feedback.

If we can make it a little easier / expose things in mu4e we can do that of course; I'd just like to avoid having diverge from the gnus behaviors too much.
