### ISSUE TITLE
[mu4e bug] Incorrect decoding when replying

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2587]
**Describe the bug**
When replying to the attached message, one gets `To: =?iso-8859-1?Q?Micka=EBl?= <Mickael@be>`.  The subject is decoded correctly if one answers `y` to the question

```
Decoded Subject "=?iso-8859-1?Q?frais_imput=E9s?="
contains a valid encoded word.  Decode again? (y or n)
```

Note that the quoted message is not decoded.

**How to Reproduce**
Reply to the attached message.

**Environment**
Debian GNU/Linux
Emacs 29.1
Mu commit #c3bc50bd

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

[Decode1.txt](https://github.com/djcb/mu/files/13257333/Decode1.txt)

**Comment by djcb** [comment]
Fixed.
