### ISSUE TITLE
[mu4e bug]  Image resizing does not work as the window width is not known

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2589]
**Describe the bug**
In order to resize images, `shr-rescale-image` queries the window in which the message is rendered.  At the moment  `(get-buffer-window (current-buffer) t)` returns `nil` (I guess because it is done in a temporary buffer not attached to a frame?) and so the resizing code is not called.

**How to Reproduce**
Enable displaying images (e.g. `(setq gnus-blocked-images nil)`) and display an email with an image larger than the windows width.

**Environment**
Linux
Emacs 29.1
mu commit #dfe28f03

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment]
Don't think this can be easily implemented we do all the preparations off-screen; that's needed so the whole mu4e-window mechanism works. Ideally, we'd can do the resizing _after_ showing (including auto-resizing after the window size changes).

**Comment by djcb** [comment]
Guess this needs to be an RFE for Emacs/Gnus; couldn't find anything we can use for this (and note taht it's not just shr), so it sounds useful, but not really doable within the mu4e context... so closing this.
