### ISSUE TITLE
[mu4e bug] Improper decoding when forwarding

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2590]
**Describe the bug**
When forwarding the attached message, its content is not properly decoded.

**How to Reproduce**
<kbd>F</kbd> on the attached message.

**Environment**
Linux
Emacs 29.1
Mu commit #ea7c05c1

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

[Forward1.txt](https://github.com/djcb/mu/files/13294244/Forward1.txt)

**Comment by Chris00** [comment]
When forwarding  [this Github message](https://github.com/djcb/mu/files/13294313/Forward2.txt), I get
```
References: <djcb/mu/issues/2588@github.com>
	<djcb/mu/issues/2588/1801283645@github.com>
User-Agent: mu4e 1.11.24; emacs 29.1
Fcc: /home/trch/Maildir/sent/cur/1699432628.bc73ef5820475e2e.poincare:2,S
To: 
Subject: Fwd: Re: [djcb/mu] [mu4e bug] When replying to a message, many recipents & CC addresses are stripped (Issue #2588)
From: Christophe Troestler <christophe@be>
Date: Wed, 08 Nov 2023 09:37:08 +0100
Message-ID: <87sf5gabez.fsf_-_@poincare.be>
--text follows this line--

-------------------- Start of forwarded message --------------------
Date: Wed, 08 Nov 2023 00:09:45 -0800
From: "Dirk-Jan C. Binnema" <notifications@github.com>
To: djcb/mu <mu@noreply.github.com>
Cc: Christophe Troestler <christophe.Troestler@umons.ac.be>, 
 Mention <mention@noreply.github.com>
Subject: Re: [djcb/mu] [mu4e bug] When replying to a message, many recipents &
 CC addresses are stripped (Issue #2588)

<#multipart type=alternative>
<#/multipart>
-------------------- End of forwarded message --------------------
```
Then empty _multipart_ will not forward the body.  (It may be possible to forward as attachement to avoid that but I have not yet investigated how to do that.)

**Comment by djcb** [comment]
Fixed in `master`.
