### ISSUE TITLE
[mu4e bug] Current repository HEAD fails to build 

### ISSUE THREAD

**Issue by theophilusx** [djcb/mu#2595]
**Describe the bug**
[164/205] Generating mu4e/mu4e_contrib_el_el with a custom command
FAILED: mu4e/mu4e-contrib.elc
/usr/local/bin/emacs --no-init-file --batch --directory /home/tim/git/mu-new/mu4e --directory /home/tim/git/mu-new/build/mu4e --eval '(setq byte-compile-warnings '"'"'(not obsolete))' --eval '(setq byte-compile-dest-file-function(lambda(_) "/home/tim/git/mu-new/build/mu4e/mu4e-contrib.elc"))' --funcall batch-byte-compile ../mu4e/mu4e-contrib.el

In toplevel form:
../mu4e/mu4e-contrib.el:27:2: Error: Invalid read syntax: ")", 670, 61
[165/205] Generating mu4e/mu4e_el_el with a custom command
FAILED: mu4e/mu4e.elc
/usr/local/bin/emacs --no-init-file --batch --directory /home/tim/git/mu-new/mu4e --directory /home/tim/git/mu-new/build/mu4e --eval '(setq byte-compile-warnings '"'"'(not obsolete))' --eval '(setq byte-compile-dest-file-function(lambda(_) "/home/tim/git/mu-new/build/mu4e/mu4e.elc"))' --funcall batch-byte-compile ../mu4e/mu4e.el

In toplevel form:
../mu4e/mu4e.el:37:2: Error: Invalid read syntax: ")", 670, 61
[185/205] Compiling C++ object mu/mu.p/mu-options.cc.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:59: all] Error 1

**How to Reproduce**
git pull
git clean -dxf
meson bu9ild && ninja -C build

**Environment**
Fedora 38 
Emacs 29 (from git)

Issue introduced in last week or so as I successfully built only a week or so ago.

**Comment by djcb** [comment]
Yes, silly typo snuck in :-(. Fixed.

**Comment by theophilusx** [comment]
Yes, that fixed it.  Thanks.
