### ISSUE TITLE
[mu4e bug] Infinite loop when composing new message

### ISSUE THREAD

**Issue by progfolio** [djcb/mu#2596]
**Describe the bug**

Attempting to compose a new message enters an infinite loop.

**How to Reproduce**

`M-x mu4e-compose-new` with multiple contexts.
If `mu4e-compose-context-policy` is set so that a context will be prompted for, that prompt is presented infinitely. If not, (e.g. `pick-first`) the following error is signaled:

```
Lisp nesting exceeds `max-lisp-eval-depth'
```

git bisect points to commit 85bfe763362b95935a3967f6585e14b3f9890a70 as the first bad commit.

<details><summary>Backtrace when quitting infinite loop:</summary>

```emacs-lisp
Debugger entered--Lisp error: (quit)
  mu4e--read-choice-builtin("Select context: " ((#("[p]ersonal" 1 2 (face mu4e-highlight-face)) REDACTED) (#("[w]ork" 1 2 (face mu4e-highlight-face)) REDACTED)))
  mu4e-read-option("Select context: " (("personal" . #s(mu4e-context REDACTED)) ("work" . #s(mu4e-context REDACTED))))
  mu4e--context-ask-user("Select context: ")
  mu4e-context-determine(nil always-ask)
  mu4e--context-autoswitch(nil always-ask)
  mu4e--compose-setup(new #f(compiled-function (parent) #<bytecode 0x1d46a04f6ee2549d>) nil)
  mu4e-compose-mail("" "" nil nil nil nil nil nil)
  compose-mail("" "" nil nil nil nil nil)
  message-setup(((To . "") (Subject . "")) nil nil nil nil nil)
  message-mail("" "" nil nil nil nil nil nil)
  #f(compiled-function (parent) #<bytecode 0x1d46a04f6ee2549d>)(nil)
  mu4e--compose-setup-buffer(new #f(compiled-function (parent) #<bytecode 0x1d46a04f6ee2549d>) nil)
  mu4e--compose-setup(new #f(compiled-function (parent) #<bytecode 0x1d46a04f6ee2549d>) nil)
  mu4e-compose-mail("" "" nil nil nil nil nil nil)
  compose-mail("" "" nil nil nil nil nil)
  message-setup(((To . "") (Subject . "")) nil nil nil nil nil)
  message-mail("" "" nil nil nil nil nil nil)
  #f(compiled-function (parent) #<bytecode 0x1d46a04f6ee2549d>)(nil)
  mu4e--compose-setup-buffer(new #f(compiled-function (parent) #<bytecode 0x1d46a04f6ee2549d>) nil)
  mu4e--compose-setup(new #f(compiled-function (parent) #<bytecode 0x1d46a04f6ee2549d>) nil)
  mu4e-compose-mail("" "" nil nil nil nil nil nil)
  compose-mail("" "" nil nil nil nil nil)
  message-setup(((To . "") (Subject . "")) nil nil nil nil nil)
  message-mail()
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_22>(nil)
  mu4e--compose-setup-buffer(new #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_22> nil)
  mu4e--compose-setup(new #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_22>)
  mu4e-compose-new()
  funcall-interactively(mu4e-compose-new)
  command-execute(mu4e-compose-new)
  ```

</details>

**Environment**
OS: arch linux
emacs-version: 
GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0) of 2023-11-02
mu/mu4e @ 08ebe87f

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment]
So you have e.g., 
```
  (setq mu4e-compose-context-policy 'always-ask)
```
and then you press `C` in `mu4e` and you get into this loop?

In the backtrace, there's a unexpected call from `compose-mail` -> `mu4e-compose-mail`; also, `mu4e--compose-setup` should trigger the `Select context:` the first time it's called but in the backtrace it only happens the third time. Huh?

I'm unable to reproduce, and nobody else has, so perhaps there's something special in your setup?
E.g. are you doing something in your `mu4e-compose-pre-hook`?

**Comment by progfolio** [comment]
Apologies. It's hard to isolate mu/mu4e in a way that actually functions without using most of the configuration to set up the mail accounts/etc. How do you personally go about testing in a minimal working environment?

> I'm unable to reproduce, and nobody else has, so perhaps there's something special in your setup?
E.g. are you doing something in your mu4e-compose-pre-hook?

Nothing in that hook.

The loop seems to be due to `message-mail-user-agent` being set to `mu4e-user-agent`. This must've not mattered before the change (it's been in my init since at least 2018 according to git blame), but now causes the loop. I also have `mail-user-agent` set to `mu4e-user-agent`, which I see the mu4e manual recommends. 
Removing the `message-mail-user-agent` setting seems to fix things.
