### ISSUE TITLE
mu4e-contacts.el issue

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#2598]
**Describe the bug**
mu4e-contacts.el contains null char and header doesn't respect convention.
Using ^@ instead of \0 corrupt emacs-lisp buffers, see (emacs bug#44486), though this one had been added by error IMO, it is not used in regexp. As a result, ripgrep for example refuse searching in mu4e-contacts.el.
For the header it is "---" instead of "--" you should use as separator.

```diff
diff --git a/mu4e/mu4e-contacts.el b/mu4e/mu4e-contacts.el
index e63057cf..eb5b5d59 100644
--- a/mu4e/mu4e-contacts.el
+++ b/mu4e/mu4e-contacts.el
@@ -1,4 +1,4 @@
-;;; mu4e-contacts.el -- Dealing with contacts -*- lexical-binding: t -*-
+;;; mu4e-contacts.el --- Dealing with contacts -*- lexical-binding: t -*-
 
 ;; Copyright (C) 2022-2023 Dirk-Jan C. Binnema
 
@@ -278,7 +278,7 @@ For testing/debugging."
 (declare-function mu4e--server-contacts  "mu4e-server")
 
 (defun mu4e--request-contacts-maybe ()
-  "Maybe update the set of contacts for autocompletion.\0
+  "Maybe update the set of contacts for autocompletion.
 
 If `mu4e-compose-complete-addresses' is non-nil, get/update the
 list of contacts we use for autocompletion; otherwise, do

```

**Environment**
LinuxMint and emacs-29.1

**Checklist**
- [ X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [ X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [ X] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by thierryvolpiatto** [comment]
As you can see in the diff the null char copied from mu4e-contacts had been converted to "\0" by firefox automatically to avoid weird things to happen.

**Comment by djcb** [comment]
Seems to be some fat-fingering... I'll fix it.

**Comment by thierryvolpiatto** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Seems to be some fat-fingering... I'll fix it.

Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>

-- 
Thierry
