### ISSUE TITLE
[mu4e bug] Reference leak from last reply to forwarded message

### ISSUE THREAD

**Issue by markk** [djcb/mu#2603]
**Describe the bug**

Somehow a message id from the last email I replied to is added to the References header when I forward another unrelated email.

**How to Reproduce**

1. Reply to **MESSAGE_A** using either `mu4e-compose-reply` or `mu4e-compose-wide-reply`. Note References header in compose buffer.
2. Forward another unrelated **MESSAGE_B** using `mu4e-compose-forward`. References header in compose buffer consists *only* of the message ID of **MESSAGE_A**, and none of the references in the headers of **MESSAGE_B**.

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

- Fedora 38
- Emacs 28.3
- mu/mu4e 08ebe87

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Huh, weird. I'll look into this.

**Comment by malb** [comment]
I'm on the most recent master but it seems I'm still seeing this bug, did it reappear?

**Comment by djcb** [comment]
@malb: I don't see it.. can you detail the steps to reproduce including the messages (censured as needed, but still reproducing the problem). Thanks.

**Comment by malb** [comment]
FWIW If I replace the `setq-local` call with

```
       (setq message-reply-headers
             (make-full-mail-header
              0
              (or (message-fetch-field "subject") "none")
              (or (message-fetch-field "from") "nobody")
              (message-fetch-field "date")
              (message-fetch-field "message-id" t)
              (message-fetch-field "references")
              0 0 ""))
```

then it seems to work. Not saying this a fix, but perhaps a data point?

**Comment by malb** [comment]
I'll see if I can reproduce it cleanly somehow

**Comment by malb** [comment]
I think I worked it out:

```diff
@@ -690,9 +690,11 @@ Based on the value of `mu4e-compose-switch'."
 This is a little glue to use `message-reply', `message-forward'
 etc. We cannot use the normal `message-pop-to-buffer' since we're
 not ready yet to show the buffer in mu4e."
-  (set-buffer (get-buffer-create name))
-  (erase-buffer)
-  (current-buffer))
+  (let ((reply-headers message-reply-headers))
+    (set-buffer (get-buffer-create name))
+    (setq-local message-reply-headers reply-headers)
+    (erase-buffer)
+    (current-buffer)))
```

`mu4e--fake-pop-to-buffer` creates a new buffer, so the `setq-local` call for `message-reply-headers` has no effect. The above patch copies it over.

**Comment by djcb** [comment]
@malb: I can't really repro, but your code seems reasonable; I've added something like that. Thanks!

**Comment by malb** [comment]
Thanks!
