### ISSUE TITLE
mu4e--get-current-buffer-type does not return correct value for  view type buffers

### ISSUE THREAD

**Issue by progfolio** [djcb/mu#2608]
`derived-mode-p` declared the modes as a `&rest` parameter up until 11 days ago on Emacs master.
Passing the argument as a single list here:

https://github.com/djcb/mu/blob/730bd13ea20243b48d43d494be3bb1448ae83247/mu4e/mu4e-window.el#L155

will break not work on any Emacs version prior to that change.
The old calling convention is  still supported according to:

https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=e6556db4200ccf28bd9bb033be0d5ce3cd2316a9

**Comment by djcb** [comment]
Fixed already. Thanks!
