### ISSUE TITLE
Different emails found between 'mu find ...' and `(mu4e--server-call-mu `(find...))` on changing flags on emails

### ISSUE THREAD

**Issue by Dima-369** [djcb/mu#2610]
**Describe the bug**

I notice how `mu find ...` does not report all emails (the emails are always there, not deleted). This happens to me after changing email flags, for instance in the example in the screenshot, I untrashed those 4 emails and then slowly they disappear from `mu find`. I don't know why but after a time they come back, I suppose it is something with the database update?

My use-case is that I am using `mu find ...` for an external application and it returns inconsistent results after flag modification which is quite annoying.

Here I run `mu find` multiple times (I only untrashed 4 emails) about every second or faster. This also happens on trashing emails, I think regardless what flag change is done.

![CleanShot 2023-12-08 at 10 06 35](https://github.com/djcb/mu/assets/15002298/4867cd5e-d1bf-4c4a-90bf-c3176604ce73)

In mu4e they are correctly visible.

Is this a bug or a limitation to the database communication? Is there some way to circumvent this?

**Environment**

Emacs 30.0.50
mu/mu4e: 1.10.7

**Comment by djcb** [comment]
How much delay are you seeing? In most cases it shouldn't take more than a few seconds, but if you're indexing as well, it can take a bit longer.

**Comment by djcb** [comment]
Ah, so for speed reasons, Xapian batches up writes to disk...  if you want make sure results are written to disk (and visible by external processes), you can do something like `pkill -SIGUSR1 mu` when you need it. This will terminate the `mu` process but mu4e restarts it automatically when needed.
