### ISSUE TITLE
[mu4e rfe] Sort by tags

### ISSUE THREAD

**Issue by cpence** [djcb/mu#2611]
**Is your feature request related to a problem? Please describe.**
I'm not an expert in the mu4e internals, but it's currently impossible to sort by the `:tags` header field (`:sortable` is `nil`; `:tags` is not included in any of the sorting options). I'd love to do this, because I use it to categorize mailing list (and other bulk) mails as they come in, and it'd be great to be able to look over messages "per-list" in a headers buffer.

**Describe the solution you'd like**
Obviously with multiple tags things would get weird, but at least alphabetical sorting by the string present in the `:tags` field would be a great start.

**Describe alternatives you've considered**
I wish I could use `:list` for this, as there *is* already built-in support for that, but too many of the "list" messages that I receive don't actually get `List-Id` headers...

**Comment by djcb** [comment]
I'll add sorting for tags (well, the _first_ tag), that's not too hard.

Note,  depending on your setup, you can use a tool like `procmail`; I use `fetchmail` to grab mails, then deliver them to `procmail`, which directs the messages to various maildir folders.

**Comment by cpence** [comment]
Fantastic, thanks so much!
