### ISSUE TITLE
[mu4e bug]

### ISSUE THREAD

**Issue by hwpplayer1** [djcb/mu#2613]
I followed [https://f-santos.gitlab.io/2020-04-24-mu4e.html](https://f-santos.gitlab.io/2020-04-24-mu4e.html) this article, I builded mu from source and I am able to run ```mu index``` command. But I can't install mu4e package within GNU Emacs. Because I can't see that package there. I installed GNU Emacs via snap package manager on Ubuntu 22.04 LTS with Ubuntu Pro. I have  elpa and melpa repositories.

I see that output when I config .emacs with f-santos manual :

```
⛔ Warning (initialization): An error occurred while loading ‘/home/hwpplayer1/.emacs’:

File is missing: Cannot open load file, No such file or directory, mu4e

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

When I install mu4e with apt package manager I see this output:

```
⛔️ Warning (initialization): An error occurred while loading ‘/home/hwpplayer1/.emacs’:

error: Eager macro-expansion failure: (error "Misplaced t or ‘otherwise’ clause")

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Thanks for your effort. happy hacking !

**Comment by djcb** [comment]
If the instructions at that f-santos link don't work, I can't help you with that; best ask its author.

For mu4e, best just follow the instructions in the manual:
  https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html

or install mu/mu4e through the Ubuntu package manager. Good luck!

**Comment by hwpplayer1** [comment]
I followed completely your documentation and now I can run mu/mu4e. I was confused sorry. Thanks for your effort. Happy hacking !

**Comment by djcb** [comment]
Great! Happy mu4e'ing!
