### ISSUE TITLE
mu index: cannot dec transaction-level

### ISSUE THREAD

**Issue by dcolascione** [djcb/mu#2615]
**Describe the bug**

When I attempt `mu index` on a brand-new (reinitialized) mail store, mu emits an error message that it can't decrement the transaction count if I kill indexing with SIGINT after at least one batch or if I let `mu index` run to completion. On next run of `mu index`, `mu` re-checks all mail. If I kill `mu index` before it finishes a batch, I don't get the error message.

**To Reproduce**
1. `mu index`
2. Let `mu index` run to completion or wait for a whole batch to finish

**Environment**
Ubuntu 22.04; latest mu master branch (commit b222a8a3f54d78d98cbf49f80040df91f5618468)

**Checklist**
- [X] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
Yeah, I see what's going on. I'll add a fix + unit test. Thanks.
