### ISSUE TITLE
[mu bug] init command requires --maildir parameter (man page says the opposite)

### ISSUE THREAD

**Issue by jman-schief** [djcb/mu#2616]
**Describe the bug**
`man mu-init` explains the `-m, --maildir=<maildir>` parameter: _starts searching at \<maildir\>. By default, mu uses whatever the MAILDIR environment variable is set to; if it is not set, it tries ~/Maildir if it already exists._

However it seems it doesn't search for $MAILDIR?
```
$ echo $MAILDIR
/home/user/.local/mail
$ mu init
missing --maildir parameter and could not determine default
```

Running `mu init -m $MAILDIR` works. Unsure if I am missing anything, though.

Thanks!

**Environment**
mu 1.10.8 from Debian packaging

**Checklist**
- [x] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
Yeah, the functionality got lost when we changed the command-line handling... fixing in master. Thank!
