### ISSUE TITLE
[mu4e bug] Can't search for messages with subjects that include a hyphen "-" character

### ISSUE THREAD

**Issue by genegoykhman** [djcb/mu#2618]
**Describe the bug**
This might be a mu thing or even a Xapian thing, or maybe I just can't find the right way to escape the hyphen, but when I hit s (search) in a headers list, then type 2023-12 and hit RET, the search results are blank even though I definitely have emails whose subject line starts with that string. In fact, any query string that includes a hyphen returns an empty result list. I've tried several different ways of escaping the hyphen but it doesn't seem to help.

**How to Reproduce**
Start mu4e, jump to any mailbox
Hit s to search
Search for: (any string that includes a hyphen)
Expected: a list of headers of messages whose subject line (at least) includes the query string
Actual: "No matching messages found."

**Environment**
macOS 14.2.1 on Apple Silicon (aarch64)
Emacs 29.1
mu4e 1.10.8

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Good news, this works in `master`, see #2167.
