### ISSUE TITLE
[mu4e bug] Wrong variable name in docstring of `mu4e-org-link-desc-func`

### ISSUE THREAD

**Issue by timmli** [djcb/mu#2622]
**Describe the bug**
Bug in docstring of `mu4e-org-link-desc-func`:

`(setq org-mu4e-link-desc-func \\='my-link-descr)` should be 
`(setq mu4e-org-link-desc-func \\='my-link-descr)`.

**Environment**
- mu4e v1.10.7

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

**Comment by djcb** [comment]
Fixed in `master`.
