### ISSUE TITLE
[mu4e rfe] Support List-Unsubscribe header

### ISSUE THREAD

**Issue by jgoerzen** [djcb/mu#2623]
**Is your feature request related to a problem? Please describe.**

A lot of time, people get automated emails from various things.  Shops that start sending you stuff after you buy from them, nonprofit newsletters, etc.

Many times, they include a clickable link to unsubscribe.  This isn't great because:

1. It can leak the client's IP address
2. It requires an active Internet connection to process, and someone may be reading email while offline
3. It is sometimes buried in complex HTML that isn't rendered will by shr

The List-Unbuscribe header is defined in RFC 2369 and is ideal for this.

It is, however, difficult to use manually.

It might look like:

1. `List-Unsubscribe: <mailto:email@example.com>` -- that's easy enough to handle manually.  Sometimes it also has a `?subject=unsubscribe` indicated.
2. `List-Unsubscribe: <https://...blah...>, <mailto:..blah...>` -- also easy enough to handle manually  (these may appear in any order)
3. `List-Unsubscribe: =?utf-8?....` or `=?us-ascii?` -- encoded and difficult to handle manually

**Describe the solution you'd like**

It would be nice to have a command to run in header or view mode to unsubscribe a person from the currently-selected message.  It could:

1. Check if List-Unsubscribe is present, and if not, display an error
2. If it is present, prompt the user for confirmation, and send an appropriate email if confirmation is given

If run non-interactively, it could skip the prompt for confirmation.

Flagging a message as spam might also want to invoke this if List-Unsubscribe is present.  (Some webmail programs make this offer).

**Describe alternatives you've considered**

Discussed above

**Additional context**

It is a common feature of other MUAs

**Comment by djcb** [comment]
With the 1.11.x at least, it should be possible to implement most of this as an "action" using `mu4e-fetch-field` (and that should take care of the number 3 in the above).

Anyway getting the cases right seems like a bit tricky / require a lot of testing. Do you want to work on this?

**Comment by jgoerzen** [comment]
Unfortunately, my elisp-foo probably isn't up to this, but I would suggest the general algorithm would be:

1. Is there a List-Unsubscribe header?  If no, abort with error.
2. Decode the contents of List-Unsubscribe if needed.
3. Is there a mailto: link in List-Unsubscribe?  If so, offer to use it, and if confirmed, stop processing.
4. Is there a http(s) link in List-Unsubscribe?  If so, offer to open it in a browser.
5. Error

**Comment by djcb** [comment]
I fear it'll work like that in many cases, and then I'll get reports for cases where it does _not_ work, e.g. when there's something wrong on the mailing-list side. "I clicked this and I'm still getting email from that list!"

Anyway, it's a useful idea, so I've added it to the IDEAS.org file, maybe somebody is interested in working on this. Closing it here, thank you!
