### ISSUE TITLE
[mu bug] inline images shouldn't be considered attachments

### ISSUE THREAD

**Issue by molok** [djcb/mu#2625]
**Describe the bug**
Most of the people in my company send emails with an inline image at the bottom (the company logo), mu flags all these emails with the flag "attach", rendering effectively useless the flag "attach"

**To Reproduce**
See the attached message
[newmann-test.txt](https://github.com/djcb/mu/files/14036736/newmann-test.txt)

**Environment**
linux, mu 1.10.8

**Checklist**
- [X] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by molok** [comment]
is the logic on image/* done for performances?
I understand mu needs to be fast but the behavior for inline images seems wrong , which are quite common nowadays.

``` cpp
bool /* heuristic */
MessagePart::looks_like_attachment() const noexcept
{
	auto matches=[](const MimeContentType& ctype,
			const std::initializer_list<std::pair<const char*, const char*>>& ctypes) {
		return std::find_if(ctypes.begin(), ctypes.end(), [&](auto&& item){
			return ctype.is_type(item.first, item.second); }) != ctypes.end();
	};

	const auto ctype{mime_object().content_type()};
	if (!ctype)
		return false; // no content-type: not an attachment.

	// we consider some parts _not_ to be attachments regardless of disposition
	if  (matches(*ctype,{{"application", "pgp-keys"}}))
		return false;

	// we consider some parts to be attachments regardless of disposition
	if  (matches(*ctype,{{"image", "*"},
			     {"audio", "*"},
			     {"application", "*"},
			     {"application", "x-patch"}}))
		return true;

	// otherwise, rely on the disposition
	return is_attachment();
}
```

**Comment by djcb** [comment]
In the past we had cases where attachments were _not_ recognized as such when users expected it (ie. some `inline` case), so the current behavior is an heuristic/compromise.

**Comment by djcb** [comment]
Since this is not easily actionable, closing thisfor now.. However, I have added this to the IDEAS.org, perhaps we can come up with something smart in the future. Thanks.
