### ISSUE TITLE
[mu bug] replying to own email mu creates new email with all the "Cc" addressee in the "To" field

### ISSUE THREAD

**Issue by molok** [djcb/mu#2627]
**Describe the bug**
When I send an email with several addressee in the Cc and then reply to the same email (usually for a followup) I expect the Cc addressee to remain in the Cc field, they are all moved to the "To" field instead. This is inconsistent with any other mail client I've ever used.

**To Reproduce**
Create an email with an addressee in the To field and another one in the Cc field. Reply to that email, observe how there is no Cc field and the Cc addressee is now in the To field

**Environment**
Linux Ubuntu 20.04, Emacs 29.1, mu 1.10.8

**Checklist**
- [X] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
Thanks for the report.

This works as it works in 1.10.x (and  IMHO it works fine), but in any case won't change in the 1.10 series

However, 1.11.x (soon to be the  new 1.12) has a completely new implementation using the Gnus machinery for this; so hopefully the 1.12 version matches what you want (and can be configured further if needed). 

So, there's nothing actionable here, closing this.
