### ISSUE TITLE
mu not looking for variables in ~/.config/ [mu bug]

### ISSUE THREAD

**Issue by n0542344** [djcb/mu#2628]
First of all, thanks for the amazing piece of free software! I'm using `mu` (currently without `Emacs`) for quite some time now and I'm very happy with it! Only the inability to use a `config`-file (or the lack of documentation on that topic; or at least my inability to get it to run the way I want) is what is bugging me.

**Describe the bug**
I'm using a specific location for my root mail directory, which I can specify by using `MAILDIR=~/path/to/my/maildir mu init` or `mu init --maildir=~/path/to/my/maildir`. It would be convenient to also specify the `MAILDIR`-path in the configuration file, which should be possible since `mu` is following the `XDG Base Directory Specification` (therefore `mu` should be reading a file (which - if any?) in `~/.config/mu/`). But I have the impression this is not happening.

**To Reproduce**
When running `strace mu init 2>&1 | grep "/.config"`, I don't see it accessing any file in there.

```
user@host:~$ strace mu init 2>&1 | grep "/.config"
newfstatat(AT_FDCWD, "/home/user/.config", {st_mode=S_IFDIR|0700, st_size=260, ...}, 0) = 0
access("/home/user/.config", R_OK|W_OK) = 0
mkdir("/home/user/.config", 0700)       = -1 EEXIST (File exists)
newfstatat(AT_FDCWD, "/home/user/.config", {st_mode=S_IFDIR|0700, st_size=260, ...}, 0) = 0
```

**Environment**
```
user@host:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
user@host:~$ mu --version
mu (mail indexer/searcher) version 1.8.13
Copyright (C) 2008-2022 Dirk-Jan C. Binnema
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Checklist**
- [x] I'm running the version of mu currently being shipped with Debian Stable.

**Comment by djcb** [comment]
Glad you like it!

Note: `mu` doesn't have a configuration file; the settings are stored in `mu`` database, and `mu init` places them  there. You cannot change those after `mu init`.
