### ISSUE TITLE
Action added to mu4e-view-mime-part-actions but not processing icalendar file [mu4e bug]

### ISSUE THREAD

**Issue by averter** [djcb/mu#2629]
**Describe the bug**
I've added the following to my init.el
````lisp
(add-to-list 'mu4e-view-mime-part-actions ' (:name "ics to calendar" :handler "~/go/bin/ical2org -count -a ~/org/calendar.org -" :receives pipe))
````
source [here](https://github.com/rjhorniii/ical2org/issues/25), and I expect to be able to access this action when clicking a ics file in a message, but instead I get an error from the apply function 
````lisp
apply: Wrong type argument: char-or-string-p, nil
````
and `C-h-v mu4e-view-mime-part-actions` suggests that the action was added to the actions list. I don't understand what I could be doing wrong.

**How to Reproduce**

1. Open a message with an ics file attached.
2. [RET] the ics file

The debug log is
````
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  #f(compiled-function (handle &optional attendee-name-or-email) #<bytecode 0x158a2f74a0b9>)((#<buffer  *mm*-738369> ("text/calendar") base64 nil ("attachment" (filename . "wfd248602Tpvr.ics")) nil nil nil) ("My Username" "myusername@gmail\\.com" "myusername@mylaptop"))
  apply(#f(compiled-function (handle &optional attendee-name-or-email) #<bytecode 0x158a2f74a0b9>) ((#<buffer  *mm*-738369> ("text/calendar") base64 nil ("attachment" (filename . "wfd248602Tpvr.ics")) nil nil nil) ("My Username" "myusername@gmail\\.com" "myusername@mylaptop")))
  gnus-icalendar-event-from-handle((#<buffer  *mm*-738369> ("text/calendar") base64 nil ("attachment" (filename . "wfd248602Tpvr.ics")) nil nil nil) ("My Username" "myusername@gmail\\.com" "myusername@mylaptop"))
  gnus-icalendar-mm-inline((#<buffer  *mm*-738369> ("text/calendar") base64 nil ("attachment" (filename . "wfd248602Tpvr.ics")) nil nil nil))
  mm-display-inline((#<buffer  *mm*-738369> ("text/calendar") base64 nil ("attachment" (filename . "wfd248602Tpvr.ics")) nil nil nil))
  gnus-mm-display-part((#<buffer  *mm*-738369> ("text/calendar") base64 nil ("attachment" (filename . "wfd248602Tpvr.ics")) nil nil nil))
  gnus-article-press-button()
  funcall-interactively(gnus-article-press-button)
  call-interactively(gnus-article-press-button nil nil)
  command-execute(gnus-article-press-button)
````

**Environment**
Linux Mint Cinnamon, Emacs 27.1, mu4e 1.10.8

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment]
What you're seeing has nothing to do with actions; those are invoked through `A` etc. But it seems opening / displaying an ICS attachment has a problem. Can you attach the offending message?

**Comment by averter** [comment]
I've created a gist of the raw message with some edits [here](https://gist.github.com/averter/aacc964b6c0941443633452ae3ae3d11.js). Would this work?

**Comment by djcb** [comment]
> I've created a gist of the raw message with some edits [here](https://gist.github.com/averter/aacc964b6c0941443633452ae3ae3d11.js). Would this work?

Not quite, that seems to be a blob of Javascript. When you have the raw message on your screen, can you copy-paste it into a text file?  Or just from mu4e, you can `mu4e-copy-message-path` and attach the message at that path?

**Comment by averter** [comment]
Well, that was a copy of the raw message. I've attached the file here. Please let me know if you still cannot open it
[message.zip](https://github.com/djcb/mu/files/14228690/message.zip)

**Comment by djcb** [comment]
The link was to some Javascript that may have written the message on your screen; but it was not the message. Anyway, the zip worked.

I get:
```
[2. text/calendar; wfd550084Tpvr.ics]...

[ Uninvited Accept ]    [ Uninvited Tentative ]    [ Uninvited Decline ]    

Summary:    Loughborough Supervisor Development Programme: Recruitment and Selection for Research Degrees: event invitation
Location:   Microsoft Teams
Time:       <2024-02-08 13:30-16:30>
Organizer:  Hronline-noreply@lboro.ac.uk
Attendance: You are not listed as an attendee
Method:     REQUEST

Click accept to see the course appear in your Outlook calendar. 

If this calendar booking does not contain a link to Teams below, please keep this as a date reminder and look out for a further Teams meeting link from the event administrators

Teams link: https://teams.microsoft.com/l/channel/19%3a524567beb74a4c4f8751699392df51c4%40thread.tacv2/Workshops?groupId=5b9a7c96-d001-4e36-ba8a-b6a0ebab5136&tenantId=cf264fc0-aeb8-449f-9054-82ce4454084b
```

Seems to work fine with 1.11.28 (and 1.12 shouldn't be far off). So guess you'll have to wait for that, if you don't want to switch now.

**Comment by averter** [comment]
Interesting... So you see those buttons as part of gnus? I'm asking this because I had to install [ical2org](https://github.com/rjhorniii/ical2org) to be able to send it to my calendar.

**Comment by djcb** [comment]
That display is from `mu4e`, but indeed that uses the Gnus code. Don't think too much changed there compared to 1.10. And it wouldn't really depend on whether `ical2org` is installed (the display doesn't relate to org-mode at all).

There's the related https://github.com/djcb/mu/issues/2482 though

**Comment by averter** [comment]
> That display is from `mu4e`, but indeed that uses the Gnus code. Don't think too much changed there compared to 1.10. And it wouldn't really depend on whether `ical2org` is installed (the display doesn't relate to org-mode at all).
> 
> There's the related #2482 though

Thanks @djcb I've tried reduced mu4e to it's bare bones, to rule out problems due to my configuration setup, but I still could not see those buttons displayed... I conclude that it is actually a version problem. I will either try out the master branch or use a new version when it's released, and I'll report back here.
