### ISSUE TITLE
[mu bug] mu init --reinit-ing a DB from mu-1.10.8 results in a crash

### ISSUE THREAD

**Issue by ArsenArsen** [djcb/mu#2633]
**Describe the bug**
when attempting to `mu init --reinit` after an update, `mu` crashes before reaching the `error: caught std::exception: old schema (466) is too old to re-initialize from` check because `mu-store.cc:remove_slash` does not handle empty strings.  The empty string got there in the first place as the `maildir` metadata key was renamed to `root-maildir`.

applying the following patch makes mu reach the old schema error above:

```patch
diff --git a/lib/mu-store.cc b/lib/mu-store.cc
index 1f2f43f7..eff05e34 100644
--- a/lib/mu-store.cc
+++ b/lib/mu-store.cc
@@ -52,7 +52,7 @@ static std::string
 remove_slash(const std::string& str)
 {
 	auto clean{str};
-	while (clean[clean.length() - 1] == '/')
+	while (!clean.empty() && clean[clean.length() - 1] == '/')
 		clean.pop_back();
 
 	return clean;

```

**To Reproduce**
1. run mu 1.10.8
2. update to mu 1.12.0
3. run `mu init --reinit`
4. see `/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/basic_string.h:1269: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; reference = char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.`

**Environment**
Gentoo GNU/Linux on x86_64-pc-linux-gnu with mu 1.12.0 now.

**Comment by djcb** [comment]
Thanks, fixed.

**Comment by ArsenArsen** [comment]
thanks!
