### ISSUE TITLE
[misc] clarification about MIME parts in 1.12

### ISSUE THREAD

**Issue by bderembl** [djcb/mu#2639]
In NEW.org,  I read

> improved support for dealing with attachments and other MIME-parts in the message view; they gained completions support with annotations in the minibuffer 

and indeed I now see radio buttons between the header and message body that look like

1.  ( ) text/plain          (*) multipart/mixed     

[2. text/html]

I have been trying to remove these buttons with
`gnus-buttonized-mime-types` or `gnus-unbuttonized-mime-types`
https://www.gnu.org/software/emacs/manual/html_node/gnus/MIME-Commands.html

I really can't find how to disable these buttons. Is it possible to remove these buttons?

thank you

**Comment by djcb** [comment]
It's not currently possible, unfortunately. It's in the code outside our direct control.

**Comment by Airwan** [comment]
The reason of this behaviour is  gnus-inhibit-mime-unbuttonizing is hardcoded and set to t in mu4e-view.  Set to nil will remove all buttons! 

By the way, the function hardcodes  gnus-unbuttonized-mime-types and gnus-buttonized-mime-types which, to my opinion should be user defined.  

Best.

**Comment by djcb** [comment]
It hard-codes that because `mu4e`'s MIME support depends on it -- and there seems to be me no standard way to remove the visual part while keeping the functional part.

**Comment by antoine-levitt** [comment]
The display is pretty annoying... Removing the gnus-inhibit-mime-unbuttonizing in mu4e-view, it appears that everything works correctly?
