### ISSUE TITLE
[misc] [mu4e] Why does (mu4e-headers-mark-pattern) ask for a field to match?

### ISSUE THREAD

**Issue by dkogan** [djcb/mu#2640]
Hi. I'd like to have the ability in mu4e to search for some messages, and then to apply some mark to ALL the messages displayed in the *mu4e-headers*. mu4e sorta has this already with (mu4e-headers-mark-pattern); this is mapped to the "%" key. This function asks for the mark that should be applied, but it ALSO asks for a field to match. It isn't clear if this extra field-match applies on top of what is already displayed in the *mu4e-headers*, or it's a new condition. Furthermore, it feels like there should be a function to apply marks to everything displayed in *mu4e-headers*, without any extra field matches. Does that exist already? If not, should (mu4e-headers-mark-pattern) do that?

Thanks

**Comment by djcb** [comment]
I think it behaves as expected: you ask mu4e to apply some pattern for matching messages, and to do so, mu4e needs to ask you about the pattern and the message field.

And you can apply to all headers in the headers buffer as well, simply `C-x h` to select all, and then apply whatever mark you want to apply.
