### ISSUE TITLE
[mu4e bug] switch context in 1.12  not working

### ISSUE THREAD

**Issue by bderembl** [djcb/mu#2646]
Hello,

In the latest version (1.12) I cannot switch context when writing a draft.
I get `C-c ; is undefined`

or when I do 
 
M-x mu4e-context-switch

I can select a context but then nothing happens (the 'From' field does not change  and the email is sent in the original context)

(used to work well in previous versions)

thank you

**Comment by n2o4** [comment]
From the v1.12.0 [NEWS](https://github.com/djcb/mu/blob/v1.12.0/NEWS.org) file:

> mu4e-compose-context-switch is gone; it was a little too fragile. Best change when creating the message (mu4e asks you by default, see mu4e-compose-context-policy).

**Comment by djcb** [comment]
Indeed; switching context while in the composer has been removed... sorry about.

**Comment by bderembl** [comment]
It was actually extremely useful: It happens many times that I receive an email on an account and have to reply with another account. Do you know how to do that with the new version?

Thanks a lot

**Comment by djcb** [comment]
Easiest is probably to use `mu4e-compose-context-policy`  wtih `always-ask`.

**Comment by bderembl** [comment]
I guess so yes, thank you.

this sentence in https://www.djcbsoftware.nl/code/mu/mu4e/Context-policies.html

> nil: don’t change the context; this is useful if you don’t change contexts very often, and e.g. manually changes contexts with M-x mu4e-context-switch. 

was actually precisely my case...

thanks anyway, this was useful.

**Comment by bderembl** [comment]
Maybe a function "reply in a different context" could be useful here?
