### ISSUE TITLE
[mu4e bug] `mu4e-headers-mark-thread-using-markpair` does not respect `mu4e-headers-advance-after-mark`

### ISSUE THREAD

**Issue by stefanv** [djcb/mu#2648]
(Unsure whether this is a feature request or a bug? :eyes:)

I am trying to mark a thread without moving to the next message. I use `mu4e-headers-mark-thread-using-markpair` for that, and its last lines are:

```lisp
    (when last-marked-point
      (goto-char last-marked-point)
      (mu4e-headers-next))
```

Thus, the `mu4e-headers-advance-after-mark` variable is ignored.

The docstring of that variable does state "With this option set to non-nil, automatically advance to the
next mail after **marking a message** in header view.", but since `message` doesn't occur in the variable name, it feels like the intent could have been to apply it to threads as well?

### Context

I'm trying to bind a key to refile an entire thread from within message view, and to close the message after refiling. My attempt so far:

```lisp
  (keymap-set mu4e-view-mode-map "y" (lambda () (interactive) (let ((mu4e-headers-advance-after-mark nil)) (mu4e-view-mark-thread `(refile . ,mu4e-refile-folder)) (mu4e-view-quit))))
```

**Comment by djcb** [comment]
Filing a bug because you think the intention of a docstring is not what it  say goes a bit far :)
Anyway, it could be changed of course, PR welcome; but note that it'd be for the next development series after 1.12.x.

**Comment by stefanv** [comment]
I'm happy to start discussions elsewhere; do you prefer the mailing list?

**Comment by djcb** [comment]
If you want to work on this and discuss here, we can of course reopen this ticket.
