### ISSUE TITLE
mu4e-headers-skip-duplicates and read messages duplicates

### ISSUE THREAD

**Issue by NicolasPetton** [djcb/mu#265]
when setting `mu4e-headers-skip-duplicates` to `t`, duplicated messages are nicely hidden.

When applying read marks(with `mu4e-headers-mark-for-read`) through `mu4e-mark-execute-all` though, duplicated are omitted.

**Comment by semente** [comment]
@djcb perhaps handling the commands based on message id instead the file. So if I move/delete/whatever a message, that has duplicates (in the same folder--so it avoid some unexpected results), the command will act on all these messages.

But I understand if you prefer avoid this behaviour if it will add too much complexity in the code.
