### ISSUE TITLE
[mu bug] mu server error: expected schema-version 500, but got 466

### ISSUE THREAD

**Issue by Ziqi-Yang** [djcb/mu#2650]
**Describe the bug**
After updating mu4e to the latest one `1.12.0`, I cannot run `mu4e` on my Emacs, so I try run `mu server` in the command line. It failed, showing this error:
```
❯ mu server
error: caught std::exception: expected schema-version 500, but got 466
``` 

**To Reproduce**
run `mu server`

**Environment**
mu version `1.12.0` built from source code included in v1.12.0 release, I also tried `mu-git` aur package, which is built from the current git repo. Both of them failed when I run `mu server`.

**Comment by rdiaz02** [comment]
I got the same message (mu built from source under Debian).  You can try running `mu init` from the command line. If you do that you will probably see something like

```
someone@somewhere:~/bin$ mu init
mu has been created with the following properties:
+-------------------+------------------------------+
| property          | value                        |
+-------------------+------------------------------+
| maildir           |/home/someone/Maildir         |
+-------------------+------------------------------+
| database-path     |/home/someone/.cache/mu/xapian|
+-------------------+------------------------------+
| schema-version    | 500                          |

```

Notice the *schema-version*.

Then run `mu index`.

**Comment by Ziqi-Yang** [comment]
Thanks, it works. It may not be a bug, but lacks a user-friendly err message. :)

**Comment by david-jankoski** [comment]
Thank you for sharing the fix @rdiaz02 - i had today the same problem with `mu v.1.12.1` and `GNU Emacs 29.2`. When i tried to start `mu4e` i was getting:
```
[mu4e] Found mu version 1.12.1
error in process sentinel: mu4e--server-sentinel: mu server process ended with exit code 1
error in process sentinel: mu server process ended with exit code 1
```
your suggested commands fixed it 🙇
