### ISSUE TITLE
[mu4e bug] Sent messages not stored.

### ISSUE THREAD

**Issue by jewelion** [djcb/mu#2651]
**Describe the bug**
When I reply to an email I expect the reply to be stored in folder given by mu4e-sent-folder.
I also expect the replied to message to be updated as "replied to" and appear in the headers view as such.

_This all worked before on 1.10_

**How to Reproduce**
 - Start emacs, 
 - M-x mu4e
 - Pick an email, hit R to reply
 - Type the reply
 - Hit C-c C-c to send

Message sent - recipient receives email. 
Sent Mail folder not updated. Replied to message appears not replied to.

**Environment**
GNU Emacs 29.2
mu version 1.12.0

Whereas I use Doom, I have tested this on a vanilla non-doom config

**Checklist**
- [*] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [*] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [*] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Can't reproduce. 

Might be something specific to your setup. Are you using some mail sync program (such as fetchmail / mbsync etc.)? If so, turn that off and see if that changes anything. Check the debug logs `(setq mu4e-debug t mu4e-mu-debug t)` etc. Thanks

**Comment by jewelion** [comment]
Thanks for the response. I have created a new user and set up mu4e afresh on a virgin Emacs and it all works fine. I guess this is where I shuffle off muttering quietly to myself :blush: 

Thank you for all the work you do on this project - you are very much appreciated!
