### ISSUE TITLE
[mu bug] Mu not recognising updated/new emails

### ISSUE THREAD

**Issue by Amolith** [djcb/mu#2658]
Apologies if there's a more correct place to ask for help; happy to move there if necessary.

### Describe the bug
mu has the correct maildir, correct store location, and has been initialised, and there are zero emails currently indexed. When I run `mu index`, it doesn't seem to actually do anything.
```
$ mu index
indexing maildir mail -> store /home/amolith/.cache/mu/xapian
\ indexing messages; checked: 24070; updated/new: 0; cleaned-up: 0
$
```

### To Reproduce
I wish I knew how to reproduce it, but I don't exactly know what happened. The database was at schema v466 while mu expected v500. I ran `mu init` followed by `mu index`. There was still some issue, I don't remember what it was now, so I just deleted `/home/amolith/.cache/mu/` to start over, then ran `mu init` and `mu index`. The schema version error is gone, but now the store is empty and mu won't populate it.

I'm more than happy to provide whatever logs or config files would help.

### Environment
- **OS**: Arch Linux
- **mu version**: 1.12.0-1

### Checklist
- [ ] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
What does `mu info store` say?

**Comment by djcb** [comment]
Ah, so you need to init  with the _absolute_ path to your maildir (1.12.1 enforces this)

**Comment by djcb** [comment]
Yeah,  you get an error with newer versions.
