### ISSUE TITLE
[mu4e rfe] HTML Reply and Forward messages have completely different processing

### ISSUE THREAD

**Issue by danielfleischer** [djcb/mu#2659]
Question regarding new v1.12 (d9390159); when replying to an HTML message, it's cited as cleanly as when viewing it but when forwarding the message you can see HTML tags, CSS, JS, multipart tags. Why is that? in both cases, the cited message is part of the message so we can edit it but when forwarding there is no "washing" of the message, if that makes sense. Thanks!

**Comment by djcb** [comment]
The short version is that it's the difference's between Gnus' `message-reply` and `message-forward`; the first is more concerned with what you  may _add_ in your reply (and hence make it easier editable); the latter tries harder to send things as-is.

You can influence the way the forward-body is created, with options like `message-forward-as-mime`, and see the  `(message) Forwarding` info  node for more tweaks.

**Comment by ifinkelstein** [comment]
Seconding this (closed) issue. Can you suggest how we can tweak the forwarding behavior to mimic reply buffers for HTML-formatted messages?

I haven't been able to reproduce the reply-like buffer after playing with `message-forward-*` settings.

**Comment by djcb** [comment]
`message-forward-as-mime` helps with avoiding seeing HTML/CSS etc. as per OPs question. For the rest, this 
is just  the way gnus works (`message-reply` vs `message-forward`); not sure if it can be tweaked further; I guess you could advise `message-forward-make-body`.
