### ISSUE TITLE
[mu4e bug] Editing a draft mangles text on Emacs <= 28

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#2661]
**Describe the bug**

If I save a draft and then try to edit it (`E` or `mu4e-compose-edit`), the text is messed up.

My config is

```elisp
(use-package mu4e
  :if (string= (system-name) "t480")
  :load-path "/home/kdm/local/mu/share/emacs/site-lisp/mu4e/"
  :ensure nil
  :defer 1
  :commands (mu4e-headers-search-bookmark mu4e)
  :demand t)
```

A sample message:

```
To: Someone <someone@test.com>
Subject: foo
From: Someone <someone@test.com>
Message-ID: <87ttlbqsln.fsf@gmail.com>
--text follows this line--

hello, world
```

I then create a draft with `C-c C-d` or `message-dont-send`. I can view the message in my `drafts` folder and I see

```
From: Someone <someone@test.com>
Subject: foo
To: Someone <someone@test.com>
Date: 2024-03-12 10:18:52 -0700 [PDT] (Tue 10:18:52 AM)
Fcc: /home/kdm/Maildir/archive/cur/1710263732.d101e78da0b345f8.t480:2,S
Flags: draft, seen
Maildir: /drafts


hello, world
```
 
So it is saved correctly. If I `E` to edit it, it works well, but if I edit-draft-edit, then I see

```
Subject: 
ct: foo
From: Someone <someone@test.com>
Message-ID: <87r0gfqsf2.fsf@gmail.com>
--text follows this line--

hello, world
```

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

+ Linux
+ mu4e 1.12.0
+ GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2022-05-30

**Checklist**
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

**Comment by djcb** [comment]
You mean the "Subject:/ct"? 

Please describe exactly (in terms of the keys you type) what edit-draft-edt means; and when the "messed up" happen. Does that happen each time?

Thanks.

**Comment by mankoff** [comment]
`edit-draft-edit` means `E` then `C-c C-d` then `E` again. Yes it happens each time.

Here is my view of replying to your email `R`, sending to draft `C-c C-d`, and then viewing it by refreshing, moving down a line, and viewing `g n <enter>`:

```
From: Ken Mankoff <kdm@t480.mail-host-address-is-not-set>
Subject: Re: [djcb/mu] [mu4e bug] (Issue #2661)
To: djcb/mu <reply+AABDNXOOVEM3G7OZ3UC4BYOD7SAEJEVBNHHIEFBMIU@reply.github.com>
Date: Tue, 12 Mar 2024 11:41:23 -0700 (4 seconds ago)
Fcc: /home/kdm/Maildir/sent/cur/1710268881.8a9d3ca4846145da.t480:2,S
Flags: draft, seen
Maildir: /drafts

"Dirk-Jan C. Binnema" <notifications@github.com> writes:

> You mean the "Subject:/ct"?
>
> Please describe exactly (in terms of the keys you type) what edit-draft-edt means; and when the "messed up" happen. Does that happen each time?
>
> Thanks.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
```

If I then hit `E` to edit, and then `C-c C-d` to send to draft, each time the text gets more munged. Soon it looks like:

```
is line----text follows this line--is line----text follows this line--is line----text follows this line--is line----text follows this line--is line----text follows this line--ff <kdm@t480.mail-host-address-is-not-set>
In-Reply-To: <djcb/mu/issues/2661/1992299434@github.com> (Dirk-Jan
	C. Binnema's message of "Tue, 12 Mar 2024 11:30:28 -0700")

"Dirk-Jan C. Binnema" <notifications@github.com> writes:

> You mean the "Subject:/ct"?
>
> Please describe exactly (in terms of the keys you type) what edit-draft-edt means; and when the "messed up" happen. Does that happen each time?
>
> Thanks.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
Date: Tue, 12 Mar 2024 11:44:47 -0700
Message-ID: <87h6hbxpb4.fsf@t480.mail-host-address-is-not-set>
```

**Comment by djcb** [comment]
On Tuesday Mar 12 2024, Ken Mankoff wrote:

Hello

> **Describe the bug**
>
> If I save a draft and then try to edit it (`E` or `mu4e-compose-edit`), the text is messed up.
>
> My config is
>
> ```elisp
> (use-package mu4e
>   :if (string= (system-name) "t480")
>   :load-path "/home/kdm/local/mu/share/emacs/site-lisp/mu4e/"
>   :ensure nil
>   :defer 1
>   :commands (mu4e-headers-search-bookmark mu4e)
>   :demand t)
> ```
>
> A sample message:
>
> ```
> To: Someone ***@***.***>
> Subject: foo
> From: Someone ***@***.***>
> Message-ID: ***@***.***>
> --text follows this line--
>
> hello, world
> ```
>
> I then create a draft with `C-c C-d` or `message-dont-send`. I can view the message in my `drafts` folder and I see
>
> ```
> From: Someone ***@***.***>
> Subject: foo
> To: Someone ***@***.***>
> Date: 2024-03-12 10:18:52 -0700 [PDT] (Tue 10:18:52 AM)
> Fcc: /home/kdm/Maildir/archive/cur/1710263732.d101e78da0b345f8.t480:2,S
> Flags: draft, seen
> Maildir: /drafts
>
>
> hello, world
> ```
>  
> So it is saved correctly. If I `E` to edit it, it works well, but if I edit-draft-edit, then I see
>
> ```
> Subject: 
> ct: foo
> From: Someone ***@***.***>
> Message-ID: ***@***.***>
> --text follows this line--
>
> hello, world
> ```
>
> **Environment**
> Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.
>
> + Linux
> + mu4e 1.12.0
> + GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2022-05-30
>
> **Checklist**
> - [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
> - [X] you have read all of the above

-- 
Dirk-Jan C. Binnema                  Helsinki, Finland
***@***.***           w:www.djcbsoftware.nl
gpg: 6987 9CED 1745 9375 0F14 DA98 11DD FEA9 DCC4 A036

**Comment by mankoff** [comment]
This was labeled `cannotreproduce` and `needsinfo`. I then provided some. Is this reproducible? I can provide my full config (it's extremely minimal) and do further testing if this still `needsinfo`.

**Comment by djcb** [comment]
I removed the `needsinfo`... but I still can't repro this. Maybe something Emacs 28 specific.

**Comment by mankoff** [comment]
What version are you using? I assume emacs29 and not 27? I just installed emacs29 (via `flatpak`... probably not the idea way to test things). I'm using this as my minimal config, with `emacs -Q`:

```elisp
  (use-package mu4e
    :load-path "/home/kdm/local/mu/share/emacs/site-lisp/mu4e/"
    :ensure nil
    :defer 1
    :config   (setq mu4e-drafts-folder "/drafts"))
(setq mu4e-mu-binary "/home/kdm/local/mu/bin/mu")
```

And when I invoke `(mu4e)` I get this error message:

```
mu4e-error: [mu4e] Found mu version nil, but mu4e needs version 1.12.0; please set `mu4e-mu-binary' accordingly
```

But I have set it, and at the command line `/home/kdm/local/mu/bin/mu --version` reports 1.2.0.

**Comment by mankoff** [comment]
I built emacs29 from source. Bug not present there.

**Comment by djcb** [comment]
Ah, thanks for checking... I tried emacs 27 and I _could_ reproduce ... I'll reopen this to see if we can do anything about this from the mu4e side.

**Comment by djcb** [comment]
Still present with the latest.

**Comment by djcb** [comment]
I've pushed a fix, the problem was with Gnus' `message-hide-headers` in older emacs versions; we use a (copy of) a newer one now.
