### ISSUE TITLE
[mu4e bug] reply to sender with accented character

### ISSUE THREAD

**Issue by bderembl** [djcb/mu#2662]
Hi,

I want to share a strange behavior that is hard to reproduce, yet happens from time to time.

I am trying to reply to some named "Benoît"
his name appears well in mu4e everywhere
however, in the source of his mail, his name looks like

`From: =?utf-8?B?QmVub8OudCAoTS4p?= <benoit@...>`

If I reply and try to send the message, I get the following error from msmtp

`msmtp: recipient address =?utf-8?Q?Beno=C3=AEt?= not accepted by the server`

(so far looks like a msmtp issue but keep reading)

Now if redo the reply procedure and I edit the name"Benoît", **do not touch the "î"** but for instance simply add a "t" at the end, then, the email is sent normally

and indeed, if I look at the source of the mail that has just been sent, I see

To: Benoîtt <benoit@...>

From what I remember, I have never had the issue before Mu4e 1.12. (And I have sent mails to Benoît before...)

This is not a catastrophic issue but if I send a email to a long list of people, the probability of getting an error is very high (and checking the names one by one is relatively cumbersome).

If anyone knows a way to curate the names in the "To:" list before generating the draft template, that would be great!
Thank you

**Comment by djcb** [comment]
Can you attach a message where this happens? Thanks.

**Comment by bderembl** [comment]
Just sent you the problematic email in a private message. Thank you!

**Comment by djcb** [comment]
I tried to reproduce.... I took the message and replied (kept the name, but changed the e-mail address to myself); no problem.

Perhaps try with 
```
(setq smtpmail-debug-info t
      smtpmail-debug-verb t	
      smtpmail-debug t)
```
and then check the `*trace of SMTP session..` buffer, and compare a  successful Benoît  and and unsuccessful one.

The error you get is a little puzzling though; `msmtp: recipient address =?utf-8?Q?Beno=C3=AEt?= not accepted by the server` since that is of course  the  name, not the address of the recipient.

**Comment by bderembl** [comment]
Thank you for your attempt.
Yes I did the same test as you did and got the same conclusion: if you modify anything in the From field, it works. I have just tried again without modify anything and still got the same error. 

I cannot do the debugging you are asking because I am using msmtp. 
I send you the log of msmtp in a private message. From what I see, msmtp believes there are 2 emails adresses: `=?utf-8?Q?Beno=C3=AEt?=` and `benoit@...`. I actually realize that I am keeping msmtp logs since 4 years. Searching "utf-8" shows me this type of error only since march 14. 

Something else I just tried:
Start the reply, save the email as a draft. then in a terminal send the mail with msmtp. That worked.
now  test 2
Start the reply, save as draft. edit the draft. send it: that didn't work

sorry, I know this is really confusing

**Comment by bderembl** [comment]
This is so weird. There are many emails where the From field contains a sender with an accented character. They do not pose any problem...

**Comment by djcb** [comment]
Yeah, it's weird... don't think mu4e does anything special here (and with 1.12.x we're just reusing the Gnus facilities). Can you reproduce with something that is not `mstmp`?

I tried once again, creating a reply, then outside mu4e/emacs, change the address part in the To:, then open the draft and send; that worked; here's the log (cleaned up for sensitive info)
```
220 out.smtp.xx ESMTP Postfix
250-out.smtp.xx
250-PIPELINING
250-SIZE 78643200
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 CHUNKING
220 2.0.0 Ready to start TLS
250-out.smtp.cz
250-PIPELINING
250-SIZE 78643200
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 CHUNKING
AUTH PLAIN <omitted>
235 2.7.0 Authentication successful
MAIL FROM:<xxxx@gmail.com> SIZE=1123
250 2.1.0 Ok
RCPT TO:<djcb@djcbsoftware.nl>
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
From: "Dirk-Jan C. Binnema" <xxxx@gmail.com>
To: ABC (M.) <djcb@djcbsoftware.nl>
Subject: Re: YYY
In-Reply-To: <1058741479.9469909.1710410529101.JavaMail.zimbra@zimbra.polytechnique.fr>
	("ABC (M.)"'s message of "Thu, 14 Mar 2024
 11:02:09 +0100
	(CET)")
Date: Wed, 20 Mar 2024 23:23:23 +0200
Message-ID: <87h6h0ha2i.fsf@gmail.com>
References: <1058741479.9469909.1710410529101.JavaMail.zimbra@zimbra.polytechnique.fr>
User-Agent: mu4e 1.12.2; emacs 30.0.50
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
[SNIP]

--=20
.
250 2.0.0 Ok: queued as 4D66A40150
QUIT
221 2.0.0 Bye

Process smtpmail deleted
```

**Comment by bderembl** [comment]
Thank you so much for your patience. 
I guess this issue is really not satisfactory and deserves to be closed. Just before giving up, could you advise me on how to do an automatic harmless operation on the `To` field when replying? (maybe something like use a different encoding and then back to utf-8)? (or something similar to what has been proposed for the message content in #1823)

Thanks again.

**Comment by bderembl** [comment]
I sent you another email where this occurs; hopefully you should be able to reproduce the issue.

**Comment by djcb** [comment]
Hmm, are you by chance using a non-UTF8 setup? (i.e., `set-language-environment`)... and can you reproduce with just a very bare-bones setup (i.e, `emacs -Q` then just load mu4e and your smtp settings`? That might shed some light.

**Comment by bderembl** [comment]
Yes, I am using utf-8; and emacs -Q with only mu4e exhibits the same behavior.

I actually suspect this issue is related to https://github.com/djcb/mu/issues/2680 because of the apostrophe character in the sender list  ("D'Antoni" which can be a weird character depending on the system)

**Comment by bderembl** [comment]
Here is a small example that hopefully someone else could reproduce:

```
From: =?iso-8859-1?Q?First_N=E1me=2C_Last_Name?=
	<toto@toto.com>
To: Toto <toto@toto.com>
Subject: test
Date: Mon, 15 Apr 2024 17:31:40 +0000
Content-Type: text/plain; charset="iso-8859-1"

Thank you
```

Replying to this email produces the following header:

```
To: First Náme
Cc: Last Name <toto@toto.com>
Subject: Re: test
```

instead of 

```
To: First Náme Last Name <toto@toto.com>
```

**Comment by ahttraga** [comment]
I'm using mu 1.12.2 and I have a similar problem.  When I forward *non-mime* emails with `mu4e-compose-forward`, I get garbled text in the inline attached message, below
"-------------------- Start of forwarded message --------------------" with lots of slash escaped characters, for example
\350 = � \340 = �.

Looking into the code, this happens when the `message-forward-make-body-plain` function is used to insert the body of the forwarded message.  This function is called by `message-forward-make-body` which is called by `message-forward`, all of which are in `message.el.gz` and are ultimately invoked by `mu4e-compose-forward`.

This does not happen if I forward a mime-encoded message, in which case another function is called, `message-forward-make-body-mime` which handles the charset properly.

I want non-mime emails to still be forwarded correctly.  How can I achieve this?

Here is code to `message-forward-make-body-plain`.  I'm not sure how it loses the encoding.

```lisp
(defun message-forward-make-body-plain (forward-buffer)
  (insert
   "\n-------------------- Start of forwarded message --------------------\n")
  (let ((b (point))
	(contents (with-current-buffer forward-buffer (buffer-string)))
	e)
    (unless (multibyte-string-p contents)
      (error "Attempt to insert unibyte string from the buffer \"%s\"\
 to the multibyte buffer \"%s\""
             forward-buffer
	     (buffer-name)))
    (insert (mm-with-multibyte-buffer
	      (insert contents)
	      (mime-to-mml)
	      (goto-char (point-min))
	      (when (looking-at "From ")
		(replace-match "X-From-Line: "))
	      (buffer-string)))
    (unless (bolp) (insert "\n"))
    (setq e (point))
    (insert
     "-------------------- End of forwarded message --------------------\n")
    (message-remove-ignored-headers b e)))
```

**Comment by bderembl** [comment]
I confirm (even though this is probably a separate issue than the one I was mentioning). This does not happen when you `reply` instead of `forward`.

**Comment by ahttraga** [comment]
Here is an example below.  Note that the header is ok, only the main body of the message has issues, it appears.  

If I reply instead of forward it's fine as @bderembl remarks.

```
-------------------- Start of forwarded message --------------------
...
Date: Mon, 29 Apr 2024 13:35:36 +0800
Cc: Çağlar
...

Dear Calar,


> On Apr 24, 2024, at 9:21/PM, �� <*******> wrote:
> 
> Dear Calar,
> 
> 
>> -----�ˮ�-----
>> ���: "Calar ...." <*>
>> ���:2024-04-18 16:43:01 (�)
>> 6��: �� <>
>> �: "
>> ;�: Re:
>> 
>> Dear ��,
>> 
```

**Comment by djcb** [comment]
@ahttraga: what I meant was the message file, i.e., open the message you tried to forward, do `M-x mu4e-copy-message-path` and attach the file at  that path (you can of course remove any personal information from that file). Thanks!

**Comment by djcb** [comment]
@ahttraga: got your message, thanks. I've pushed a candidate fix.

@bderembl: indeed, the above problem/fix is specific for forwarding, so we need something else for replying (which uses some quite different code paths)

**Comment by djcb** [comment]
@bderembl: but looking at that example,
```
From: =?iso-8859-1?Q?First_N=E1me=2C_Last_Name?=
	<toto@toto.com>
To: Toto <toto@toto.com>
Subject: test
Date: Mon, 15 Apr 2024 17:31:40 +0000
Content-Type: text/plain; charset="iso-8859-1"

Thank you
```
I get: 
```
First Náme, Last Name <toto@toto.com>
```
and the comma is just taken as the separator, ie., parsed as _two_ addresses. I think this is correct as per email specs.
For this to work correctly, the sender should send 

```
"First Náme, Last Name" <toto@toto.com>
```
instead. I don't think the accent makes any difference. But this also seems different from the problem this ticket started with?

**Comment by bderembl** [comment]
agree.
this is however the mail I got... i.e. the sender is sending without `"`...

**Comment by ahttraga** [comment]
> @ahttraga: got your message, thanks. I've pushed a candidate fix.
> 
This fixed it!  Thanks!

**Comment by djcb** [comment]
@jman-schief @ahttraga 

As requested, please attach raw messages where this happens. Not the result, but the message you want to forward; remove personal information as needed. Thanks.

**Comment by djcb** [comment]
When you have the original message (before pressing `F`), you can use e.g. `M-x mu4e-copy-message-path` and attach that file.

**Comment by djcb** [comment]
Forwarding that, I get:
```
To: 
Subject: Fwd: Test 2
From: "djcb" <djcb@example.com>
Date: Tue, 21 May 2024 23:22:25 +0300
Message-ID: <87ikz63ofy.fsf@example.com>
--text follows this line--

-------------------- Start of forwarded message --------------------
Subject: Test 2
Date: Tue, 21 May 2024 22:07:24 +0200


Lorem ipsum ist ein pseudo-Lateinischer Text für Webdesign, Typografie, Layout und Printmedien. Er
ersetzt Deutsch um Designelemente gegenüber dem Inhalt hervorzuheben, hat also die Funktion als
Platzhalters in Layouts um dem Betrachter eine vorläufige Vorstellung der endgültigen Fassung zu
vermitteln. Buchstaben, Worte, Wort- und Satzlängen bilden ungefähr das Schriftbild eines
lateinischen Texts wieder. Latein war in früheren Jahrhunderten eine häufig genutzte Sprache
verschiedener Textgattungen, z. B. wissenschaftlicher Werke, Ratgeber, oder auch der sogenannten
Erbauungsliteratur. Um die Aufmerksamkeit des Lesers ausschließlich auf das Schriftbild zu lenken
wird auch ein zufälliger Sinn durch Wort- oder Satzkombinationen vermieden.
-------------------- End of forwarded message --------------------
````
so seems this is _already fixed_ (1.12.5)

**Comment by djelenc** [comment]
I'm having similar issues but with accented Slovenian characters, but only when receiving messages from a user that uses MS Exchange server (such cases received from GMail senders work fine). 

If I try to reply to the sender that has an accent and a comma in their friendly name, the sender friendly name and email address are broken into two lines, creating a faulty `To:` and `Cc:` fields.

This is the message that breaks the reply address. (I omitted many fields but when testing the error persists.)

```
From: =?iso-8859-2?Q?XXX=C8Y=C8=2C_GEORG?= <xxxxx@yyyyyyyyyyyyyy.zz>
To: "Not, Accented" <xxxxxxxxxxxx@yyyyyyyyyy.zz>
Subject: Something
Date: Tue, 4 Jun 2024 10:45:30 +0200
Accept-Language: sl-SI, en-US
Content-Language: sl-SI
Content-Type: text/html; charset="iso-8859-2"
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

Message contents.
```

When replying, the following appears in the compose view.

```
To: XXXČYČ
Cc: GEORG <xxxxx@yyyyyyyyyyyyyy.zz>
Subject: Re: Something
From: David Jelenc <david.jelenc@fri.uni-lj.si>
Date: Tue, 04 Jun 2024 11:27:00 +0200
Message-ID: <87cyox5a8r.fsf@fri.uni-lj.si>
--text follows this line--
XXXČYČ, GEORG <xxxxx@yyyyyyyyyyyyyy.zz> writes:

> Message contents. 
```

It appears that the message breaks a new line at the place of the comma (`,`) symbol denoting `Last, First name` from the sender.

If I manually fix the address into `Last, First <first.last@domain.com>` I get a malformed email address error.

But this can be fixed by putting double quotes around the friendly name, e.g. `"Last, First" <first.last@domain.com>`.

I'm using version 1.12.5 (NixOS 24.05).

**Comment by djcb** [comment]
@djelenc : Yeah, problem is with the comma in the `From:`;  it's not the first time somebody hits this problem (2005) https://inbox.vuxu.org/ding/v9sm4n6ls5.fsf@marauder.physik.uni-ulm.de/T/#u

Which points to a solution:
 ```
(setq rfc2047-quote-decoded-words-containing-tspecials t)
```
not sure why it's no enabled by default.

**Comment by djelenc** [comment]
Thank you, works perfectly.

**Comment by bderembl** [comment]
> Which points to a solution:
> 
> ```
> (setq rfc2047-quote-decoded-words-containing-tspecials t)
> ```
> 
> not sure why it's no enabled by default.

works for me too. thank you for the tip!
