### ISSUE TITLE
[mu4e rfe] Switch between "Reply" and "Wide Reply"

### ISSUE THREAD

**Issue by mickesv** [djcb/mu#2665]
**Is your feature request related to a problem? Please describe.**
With the recent update the way to select between a reply and a wide reply has changed. While I'm sure I'll get used to this soon enough, at the moment I find myself hitting [R]eply, typing a bit, realising that there may have been more recipients, copying the text, discarding the message (yes, discard draft too), and then select a [W]ide reply and start over again.

**Describe the solution you'd like**
Some key combination to switch from a "narrow" reply to a wide reply from inside the message buffer.

**Describe alternatives you've considered**
Make wide reply the default, add a commented out Cc: field with all other possible recipients, or at least a warning that I'm about to do something stupid.

**Comment by djcb** [comment]
Switching between the two isn't easy or even possible in the general case, so I'll have to decline that idea.

However,  you _can_ get back the question  if you want, with something like:
```
(defun compose-reply-wide-or-not-please-ask ()
  "Ask whether to reply-to-all or not."
  (interactive)
  (mu4e-compose-reply (yes-or-no-p "Reply to all?")))

(define-key mu4e-compose-minor-mode-map (kbd "R")
  #'compose-reply-wide-or-not-please-ask)
```
also added this to the documentation. Thanks!

**Comment by markk** [comment]
Just as a follow-up I added some more logic to:

1. Supersede rather than reply to my own emails.
2. Only ask whether to reply to all if there are more than one recipients

``` elisp
(defun supersede-or-compose-reply-ask-wide ()
  "Supersede own messages or ask whether to reply-to-all."
  (interactive)
  (if (mu4e-message-contact-field-matches-me (mu4e-message-at-point) :from)
      (mu4e-compose-supersede)
    (let ((tos (length (mu4e-message-field-at-point :to)))
          (ccs (length (mu4e-message-field-at-point :cc))))
      (mu4e-compose-reply
       (and (> (+ tos ccs) 1)
            (yes-or-no-p "Reply to all?"))))))

```

**Comment by markk** [comment]
> @markk I get the question "Reply to all?" even if there is no CC in the message...

Are there multiple To recipients?

**Comment by munterkalmsteiner** [comment]
No.
