### ISSUE TITLE
Calendar invite stopped working

### ISSUE THREAD

**Issue by joukeHijlkema** [djcb/mu#2666]
**Describe the bug**
Emails with a calendar invite give the error when clicking on Accept. This worked until I upgraded to the latest version (1.12.0)

`Debugger entered--Lisp error: (error "This is a pseudo-article")
  signal(error ("This is a pseudo-article"))
  error("This is a pseudo-article")
  gnus-summary-select-article()
  gnus-summary-reply()
  gnus-icalendar-send-buffer-by-mail("*CAL*" "Accepted: Lunar Islands - Discussion on Test Defin..." "xxx.xxx@xxx.xx")
  gnus-icalendar-reply(((#<buffer  *mm*-736088> ("text/calendar" (method . "REQUEST") (charset . "utf-8")) base64 nil nil nil nil nil) accepted #<gnus-icalendar-event-request gnus-icalendar-event-request-17a852db3894>))
  gnus-article-push-button((mouse-2 (#<window 13 on *mu4e-article*> 761 (53 . 355) 849592659 nil 761 (6 . 19) nil (5 . 10) (8 . 18))))
  funcall-interactively(gnus-article-push-button (mouse-2 (#<window 13 on *mu4e-article*> 761 (53 . 355) 849592659 nil 761 (6 . 19) nil (5 . 10) (8 . 18))))
  call-interactively(gnus-article-push-button nil nil)
  command-execute(gnus-article-push-button)
`
**How to Reproduce**
open an email with an inviter and click [Accept]
[error.txt](https://github.com/djcb/mu/files/14637016/error.txt)

**Environment**
- endeauvourOS
- GNU Emacs 29.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.40, cairo version 1.18.0)
- mu/mu4e 1.12.0

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Does this happen with _all_  invitation or only some? And do the ones failing still work with 1.10?

**Comment by djcb** [comment]
@Chris00 any idea?

**Comment by joukeHijlkema** [comment]
I'll check asap.

**Comment by Chris00** [comment]
As coincidence has it, I replied to an invitation today (with mu commit 0b68afe9) and it went fine.  A specific message would be helpful.

**Comment by joukeHijlkema** [comment]
I uploaded one with the bug report.

**Comment by Chris00** [comment]
Ah, I got mistaken with the name of the file and text around it.   As I was not in the liste I got an “Uninvited Accept” but I could replay to it without problem — you (or theodor) should have received the message.

**Comment by joukeHijlkema** [comment]
I checked and for me it bugs with other invites as well. I went back to
1.10.8 and it still won't work so maybe it is something on my side
eventhough I don't think I touched anything.
I'll make a clean init file this as soon as I have some time to test.
Will keep you posted.

Jouke

**Comment by joukeHijlkema** [comment]
Just found this in my warnings:
Error (use-package): mu4e/:init: Symbol’s function definition is void:
mu4e-icalendar-setup

This is in my init file:
(use-package mu4e
  :straight (:host github
                   :files ("build/mu4e/*.el")
                   :repo "djcb/mu"
                   :branch "release/1.10"
                   :pre-build (("./autogen.sh")
                               ("/usr/bin/meson" "setup" "--reconfigure"
"build")
                               (shell-command (concat "echo "
(shell-quote-argument (read-passwd "root password? ")) " | sudo -S
/usr/bin/ninja -C build install"))))
  :commands mu4e
  :config (message "=== my mu4e config ===")
  (setq mail-user-agent 'mu4e-user-agent)
  (setq mu4e-get-mail-command "/usr/bin/offlineimap -o")
  (setq mu4e-sent-folder "/Work/INBOX.Sent")
  (setq mu4e-mu-binary "/usr/local/bin/mu")

  (mu4e-bookmark-define "maildir:/Work/INBOX NOT flag:trashed"
            "Inbox"        ?i)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND flag:unread"
           "Inbox unread" ?u)
  (mu4e-bookmark-define "maildir:/Work/INBOX.Sent"
            "Sent"         ?s)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND date:today..now AND NOT
flag:trashed" "Today"        ?t)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND date:1w..now AND NOT
flag:trashed"    "Last week"    ?w)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND date:5w..now AND NOT
flag:trashed"    "Last month"   ?m)
  (mu4e-bookmark-define "maildir:/Spam AND flag:unread"
           "Spam"         ?z)

  (setq message-send-mail-function 'smtpmail-send-it
        smtpmail-default-smtp-server "imap-mip.onecert.fr"
        smtpmail-smtp-server "imap-mip.onecert.fr"
        smtp-local-domain "onera.fr")

  ;; Calendar events
  (setq mu4e-icalendar-diary-file
"/home/hylkema/Documents/Org/Calendar/Test.org")
  (mu4e-icalendar-setup)
  (setq gnus-icalendar-org-capture-file
"/home/hylkema/Documents/Org/Calendar/Test.org")
  (setq gnus-icalendar-org-capture-headline '("Calendar"))
  (gnus-icalendar-org-setup)
  )

**Comment by Chris00** [comment]
You are correct, [`mu4e-icalendar-setup` is in `mu4e-obsolete.el`](https://github.com/djcb/mu/blob/master/mu4e/mu4e-obsolete.el#L273) but the instructions were not updated.  You should use `(gnus-icalendar-setup)`.

**Comment by joukeHijlkema** [comment]
Debugger entered--Lisp error: (void-function gnus-icalendar-setup)
  (gnus-icalendar-setup)

**Comment by Chris00** [comment]
Did you do `(require 'mu4e-icalendar)` first?

**Comment by joukeHijlkema** [comment]
I do feel stupid now .... It works, thanks.

**Comment by djcb** [comment]
Thanks, the instruction have been updated. I also added an alias  for `mu4e-icalendar-setup`.

**Comment by averter** [comment]
hmmm... 
I'm experiencing a strange and possibly related issue. I'm able to export an invitation to org normally via the export to org button, but when I click any of the accept/tentative/decline buttons the template message that is created is different than what it used to be before 1.12.x. (example below). The subject is `Re:none` instead of the original message subject, and the `in-reply-to` field is now `nobody's message of "(unknown date)"` which is different than what it used to be... 
````
To: Recipient@myworkplaceemail.com
Subject: Re: none
From: My username <myusername@myworkplaceemail.com>
Date: Fri, 12 Apr 2024 13:39:38 +0100
Message-ID: <87cyqu21rp.fsf@myworkplaceemail.com>
In-Reply-To: nobody's message of "(unknown date)"
--text follows this line--
<#multipart type=alternative>
<#part type="text/plain">
<#/part>
<#part type="text/calendar; method=REPLY; charset=UTF-8" buffer="*CAL*">
<#/part>
<#/multipart>
````
My init.el contains simply
````elisp
    ;; Use gnus article view
    (require 'mu4e-icalendar)
    (mu4e-icalendar-setup)
    (setq mu4e-icalendar-diary-file "~/.diary") ;new

    (require 'org-agenda)
    (setq gnus-icalendar-org-capture-file "~/org/NOTES.org")
    (setq gnus-icalendar-org-capture-headline '("Calendar"))
    (gnus-icalendar-org-setup)
````

**Comment by djcb** [comment]
@averter: can you share the raw message you received? (anonymize as needed of course, as long as it still reproduces.. thanks!)

**Comment by djcb** [comment]
Oh, and I did a small change (`master`)... does that help?

**Comment by averter** [comment]
> @averter: can you share the raw message you received? (anonymize as needed of course, as long as it still reproduces.. thanks!)

[raw_message.zip](https://github.com/djcb/mu/files/14960602/raw_message.zip)

**Comment by averter** [comment]
> Oh, and I did a small change (`master`)... does that help?

Aha, indeed it does!

**Comment by averter** [comment]
@djcb I've noticed two things worth reporting.

1. Unlike regular replies, clicking the buttons does not update the mu4e-context, and so one could by mistake reply accept/decline/tentative with the incorrect email address
2.   The reply email ends up in a separate email thread than the one from which the invitation message, neither it includes accept, decline, tentative in the subject. 

Let me know if any of the above is not reproducible. Thanks.

**Comment by martinarielhartmann** [comment]
Hi,

I'm having the same problem as @averter  

With 1.12.7-st: Let's say I get a calendar invite (anonymized):

```
1.  ( ) text/plain          ( ) text/html           (*) text/calendar       

[ Accept ]    [ Tentative ]    [ Decline ]    

[ Show Agenda ]    [ Export to Org ]    

Summary:    Teacher Meeting
Location:   X
Time:       <2025-02-11 09:05-10:00 +1m>
Organizer:  X@X.X
Attendance: Required
Method:     REQUEST
Status:     Not replied yet
```

If I click Accept, Tentative, or Decline, it will store the information in my notes.org. I'm sent to a mu4e:compose buffer that looks like this:

```
To: X@X.X
Subject: Re: [name of the meeting]
From: foo bar <my@email.X>
Date: Fri, 29 Nov 2024 09:44:16 +0200
Message-ID: <m1h67qwkkv.fsf@x.x.x>
--text follows this line--
<#multipart type=alternative>
<#part type="text/plain">
<#/part>
<#part type="text/calendar; method=REPLY; charset=UTF-8" buffer="*CAL*">
<#/part>
<#/multipart>

```
This e-mail doesn't seem to contain anything about my acceptance. 

Any help with this would be greatly appreciated. I have been enjoying mu4e for years, had to stop using it due to calendar invites, but now I would love to be back since it's soooooo fast and useful. BTW I don't speak elisp.

GNU Emacs 29.3 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.6 (Build 21G646)) of 2024-03-24
Macos 15.0 (24A335)

**Comment by Chris00** [comment]
﻿On 29 November 2024 at 22:06 +01, martinarielhartmann ***@***.***> wrote:
> […]
> To: ***@***.***
> Subject: Re: [name of the meeting]
> From: foo bar ***@***.***>
> Date: Fri, 29 Nov 2024 09:44:16 +0200
> Message-ID: ***@***.***>
> --text follows this line--
> <#multipart type=alternative>
> <#part type="text/plain">
> <#/part>
> <#part type="text/calendar; method=REPLY; charset=UTF-8" buffer="*CAL*">
> <#/part>
> <#/multipart>
>
> This e-mail doesn't seem to contain anything about my acceptance.

The acceptance (or not) is in the *CAL* buffer.
