### ISSUE TITLE
[mu4e bug] mu4e does not skip duplicates in bookmark search

### ISSUE THREAD

**Issue by bhankas** [djcb/mu#2669]
**Describe the bug**
I have Gmail account configured in mu4e with doom-emacs. This is the relevant config:

```emacs-lisp
(use-package mu4e
  :commands (mu4e)
  :config
  (setq! user-full-name "Name"
         user-mail-address "mail@gmail.com"
         mm-discouraged-alternatives '("text/html" "text/richtext" "image/.*")
         mail-user-agent 'mu4e-user-agent
         mu4e-index-cleanup nil ;; either t or nil does not change unread count
         mu4e-search-full t
         mu4e-headers-visible-columns 60
         mu4e-headers-fields '((:human-date . 12)
                               (:flags . 6)
                               (:from-or-to . 25)
                               (:subject)))

  (advice-add 'mu4e-mark-execute-all :after #'mu4e-update-index-nonlazy))
```

Relevant bookmark:

```emacs-lisp
(add-to-list 'mu4e-bookmarks
                 `(:name "Unread messages"
                   :query "flag:unread AND NOT flag:trashed AND NOT maildir:/Gmail/[Gmail]/Spam AND NOT maildir:/Gmail/[Gmail]/Trash"
                   :key ?u)
                 t))
```

This is what `mu4e` shows:
![image](https://github.com/djcb/mu/assets/24254289/135d9af8-d193-4c08-b5be-11dc0be04d73)

However, when same search is performed via CLI, this is the result, note the only difference between two searches is presence of `--skip-dups` flag:

```fish
~ ❱ mu find "flag:unread AND NOT flag:trashed AND NOT maildir:/Gmail/[Gmail]/Spam AND NOT maildir:/Gmail/[Gmail]/Trash" --include-related=false
Mon Feb 19 23:08:51 2024 Sender1 <> FOO
Mon Feb 19 23:08:51 2024 Sender1 <> FOO
Thu Feb 29 17:47:47 2024 Sender2 <> BAR
Thu Feb 29 17:47:47 2024 Sender2 <> BAR

~ ❱ mu find "flag:unread AND NOT flag:trashed AND NOT maildir:/Gmail/[Gmail]/Spam AND NOT maildir:/Gmail/[Gmail]/Trash" --include-related=false --skip-dups
Mon Feb 19 23:08:51 2024 Sender1 <> FOO
Thu Feb 29 17:47:47 2024 Sender2 <> BAR
```
 
The FAQ already address this: https://www.djcbsoftware.nl/code/mu/mu4e/General.html

However, as I understand, despite ensuring `mu4e-headers-include-related` is `nil` AND both `mu4e-search-skip-duplicates` as well as `mu4e-headers-skip-duplicates` are set to `t`, the discrepancy in results is still exactly same as if `mu4e-*-skip-duplicates` is `nil`. I went through relevant code for doom-emacs module as well as mu4e, and this shouldn't be happening.

**How to Reproduce**
1. Set `mu4e-headers-include-related` to `nil` 
2. Set `mu4e-search-skip-duplicates` as well as `mu4e-headers-skip-duplicates` to `t`
3. M-x `mu4e` # note the unread count
4. [in terminal] `$ mu find "flag:unread AND NOT flag:trashed AND NOT maildir:/Gmail/[Gmail]/Spam AND NOT maildir:/Gmail/[Gmail]/Trash" --include-related=false --skip-dups`

**Environment**
- Emacs 29.2
- mu/mu4e 1.12.2

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by bhankas** [comment]
@djcb The checklist asks for v1.9/1.10, but since 1.12 is the latest stable, I deemed it to be eligible for bug report

**Comment by djcb** [comment]
This is expected behavior: https://www.djcbsoftware.nl/code/mu/mu4e/General.html#The-unread_002fall-counts-in-the-main_002dscreen-differ-from-the-_0027real_0027-numbers-_002d-what_0027s-going-on_003f

**Comment by bhankas** [comment]
Hi, @djcb . Yes, I read the relevant section. I understand why that is so. But, may I ask why, even after explicitly asking `mu4e` to skip duplicates, it does not?

From my reading of the code, setting `mu4e-search-skip-deplicates` should set the same flag as the cli `--skip-dups`.

**Comment by djcb** [comment]
That setting applies to normal queries, not to the count queries we use to get the unreads.

**Comment by bhankas** [comment]
Oh that explains it! Thanks! 

So if I want the same behavior in bookmark counts, what are the choices? `advice-add`?

**Comment by djcb** [comment]
No easy options, you'd have to patch the server code. I'd recommend just getting used to it :)

**Comment by bhankas** [comment]
:) :(

Would you be interested in a PR for making this user configurable?

**Comment by bhankas** [comment]
Is this what you mean? --> https://github.com/djcb/mu/blob/3caa04fc2b5547611bb88022cb2aba0cc29bb894/lib/mu-store.cc#L629C1-L636C2

If yes, then I understand why this won't be a small change :(
