### ISSUE TITLE
[mu4e rfe] gnus message mode ruins everything!

### ISSUE THREAD

**Issue by legalnonsense** [djcb/mu#2670]
**Is your feature request related to a problem? Please describe.**
Everything was great at 1.10. Further migration to gnus message mode has caused many things I like to break. This includes the wonderful org-msg, and various custom composition functions that I've written. 

**Describe the solution you'd like**
Some way to revert to the previous compose method. 

**Describe alternatives you've considered**
Staying at 1.10 for the rest of my life, learning to customize message-mode (seems very difficult), creating a separate package that avoids message-mode, giving up and switching to gnus (not seriously considered). 

**Additional context**
I can write elisp, have witten packages, contributed a tiny bit of code to mu4e, but I was hoping I could avoid losing many hours with a simple solution that has not occurred to me.

**Comment by djcb** [comment]
This is not a very useful ticket and the hyperbole doesn't help either.

There is no magical setting; but we're using message-mode as before, so your customizations may need some changes; best ask on the mailing list, for best results be concrete and consise
