### ISSUE TITLE
No empty line when replying [mu bug]

### ISSUE THREAD

**Issue by averter** [djcb/mu#2686]
**Describe the bug**
This is a minor thing but, since the upgrade to 1.12.x whenever I reply to an email the message body has this form
````
To: xxxxxxxxx <xxxxxxx@email.com>
Cc: yyyyyyyyy <yyyyyy@email.com>
Subject: Re: a test message
From: zzzzzzzzz <zzzzzzz@email.com>
Date: Tue, 09 Apr 2024 10:54:15 +0100
Message-ID: <87cyqyamk8.fsf@email.com>
In-Reply-To: <GV1PR04MB951566BCB80BDE25DD118CBFBF072@plasdp,as.neoz.prod.kasdas.com>
	(xxxxxx's message of "Tue, 9 Apr 2024 09:47:39 +0000")
--text follows this line--
On 09 Apr 2024 at 09:47, xxxxxxxxxxx <xxxxxxxxx@email.com> wrote:

> Hi yyyyyyyyy
>
>  
>
> Thanks for letting us know. I have re-sent the invitation for 19th at 9am. 
>
>  
>
> Best wishes
>
> xxxxxxxxxxx
````
and the cursor is at the "On 09 Apr..." line, where I would expect to be an empty line. Is this behavior normal? Can it be changed?

**To Reproduce**

1. Open an email
2. Reply to it (can be wide reply as well)

**Environment**
Linux mint, Emacs 28.1, mu 1.12.3

**Checklist**
- [x] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
It's not really a bug, it's just the default behavior; but: see #2675 to get the extra line inserted automatically.

**Comment by averter** [comment]
Indeed, I thought so, just a minor cosmetic thing. Adding `(message-goto-body)(open-line 1)` to `mu4e-compose-mode-hook` solved it right away.
