### ISSUE TITLE
[mu4e bug] Error in message-send / message-send-and-exit

### ISSUE THREAD

**Issue by theophilusx** [djcb/mu#2688]
**Describe the bug**

Wrong type argument stringp, nil thrown when sending a message. 

The message seems to be sent successfully, but the above error is generated and the compose buffer is not cleaned up and closed afterwards.  This is with latest HEAD from git

Stacktrace 

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  find-file-noselect(nil)
  mu4e--set-parent-flags(nil)
  #f(compiled-function () #<bytecode -0xd83f5e16dbbfc65>)()
  run-hooks(message-sent-hook)
  message-send(nil)
  message-send-and-exit(nil)
  funcall-interactively(message-send-and-exit nil)
  call-interactively(message-send-and-exit nil nil)
  command-execute(message-send-and-exit)

**How to Reproduce**

Send a message. No special setup required. Occurs whether I send the message from the mu4e home screen buffer or from within a mailbox header buffer. 

M-x mu4e

C <enter>

Fill in To: Subject: etc and type a message 

C-c C-c to send it

Error generated. 

Error also occurs when replying to a message 

**Environment**

GNU Emacs 30.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-04-12

commit 32d73260d349cfaff1cb4ef64acf4eede8f12e09 (HEAD -> master, origin/master, origin/HEAD)
Author: Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>
Date:   Fri Apr 12 19:59:34 2024 +0300

    mu4e.texi: add diary example action

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by theophilusx** [comment]
Tested and fix appears to have worked. Issue no longer reproducible. 

Thanks for the quick fix. 

Closing issue as resolved.

**Comment by djcb** [comment]
On Saturday Apr 13 2024, Tim Cross wrote:

> Tested and fix appears to have worked. Issue no longer reproducible. 
>
> Thanks for the quick fix. 
>
> Closing issue as resolved. 

Ah, I pushed just a quick workaround, slightly better solution should be
on its way...
