### ISSUE TITLE
[mu bug] mu 1.12.3 stops indexing mails

### ISSUE THREAD

**Issue by telmich** [djcb/mu#2689]
**Describe the bug**

For a few days mu does not index mails anymore. It still displays existing mails, but does not add new ones.

**To Reproduce**
Run `mu index` either directly from mu4e or from the command line. Result is:

```
% mu index
indexing maildir /home/nico/Maildir -> store /home/nico/.cache/mu/xapian
- indexing messages; checked: 1592795; updated/new: 25; cleaned-up: 0
(process:277366): mu-CRITICAL **: 17:05:18.485: xapian_try: xapian error 'Attempted to delete or modify an entry in a non-existent posting list for B08'
| indexing messages; checked: 1592795; updated/new: 25; cleaned-up: 7
[17:05] nb3:~% mu --version
version 1.12.3

```

**Environment**

```
# apk list -I | grep -e ^musl -e ^mu4e -e ^emacs
emacs-29.3-r0 x86_64 {emacs} (GPL-3.0-or-later) [installed]
emacs-x11-29.3-r0 x86_64 {emacs} (GPL-3.0-or-later) [installed]
mu4e-1.12.3-r0 x86_64 {mu} (GPL-3.0-or-later) [installed]
musl-1.2.5-r0 x86_64 {musl} (MIT) [installed]
musl-dbg-1.2.5-r0 x86_64 {musl} (MIT) [installed]
musl-dev-1.2.5-r0 x86_64 {musl} (MIT) [installed]
musl-fts-1.2.7-r6 x86_64 {musl-fts} (BSD-3-Clause) [installed]
musl-utils-1.2.5-r0 x86_64 {musl} (MIT AND BSD-2-Clause AND GPL-2.0-or-later) [installed]
```

**Checklist**
- [ ] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

Running mu4e from package repository.

**Comment by djcb** [comment]
The Xapian database got corrupted. Not much I can do about that... you can restore things by starting from scratch, with `mu init`.

**Comment by telmich** [comment]
@djcb thanks for the quick reply.

Deleting ~/.cache/mu/xapian and restarting with `mu init && mu index` indeed does fix the error. Wonder how it broke, but probably out of scope for mu.
