### ISSUE TITLE
mu4e-headers-toggle-include-related returns to the top of headers buffer

### ISSUE THREAD

**Issue by mylese** [djcb/mu#269]
While looking through search results, it is useful to be able to see the other messages in a thread, however turing on mu4e-headers-toggle-include-related causes the first mail in the buffer to be selected thus losing my place.  It would be nice if the selected message remained selected after turning on mu4e-headers-toggle-include-related.

**Comment by djcb** [comment]
Have added this now -- after re-searching some query, we try to move point to the message it was on before.

**Comment by mylese** [comment]
Thanks!
