### ISSUE TITLE
[mu4e bug] bbdb tab completion broken in 1.12.3

### ISSUE THREAD

**Issue by jgoerzen** [djcb/mu#2691]
**Describe the bug**

Hello,

Thanks again for mu and mu4e!

After upgrading from 1.10 to 1.12.3, I can no longer complete email addresses in the composition screen by pressing TAB.  It simply inserts whitespace.

**How to Reproduce**

On the To: line, I used to be able to start typing an address and hit Tab and have it completed with bbdb.  I have verified my bbdb setup matches the manual, and it does.

I observe via the emacs debugger that `message-tab` is being called, but somehow the `completion-at-point` call isn't doing anything for bbdb.  Manually running `M-: (message-expand-name)` does the right thing.

My elisp-foo isn't good enough to track this further.  However, I believe bbdb is set up and working (since message-expand-name) works.

**Environment**
Debian bookworm, Emacs 29.3, mu 1.12.3

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [ ] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.).  (My configuration is tied into Doom so is difficult to run without, but I see no evidence of Doom inserting itself here)
- [X] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
I don't use `bbdb`, but I think this might be a problem beyond mu4e; see https://inbox.vuxu.org/ding/87r0y42vnh.fsf@a16n.net/

That thread does suggest a solution:

```
(add-hook 'message-mode-hook
          (lambda ()
            (add-to-list 'completion-at-point-functions
                         #'eudc-capf-complete)))
```

**Comment by jgoerzen** [comment]
Thank you!  I don't use eudc, but a small tweak made it work again:


(add-hook 'message-mode-hook
          (lambda ()
            (add-to-list 'completion-at-point-functions
                         #'message-expand-name)))

- John
