### ISSUE TITLE
mu4e composer no longer picks the right email address from where to send messages or reply to them

### ISSUE THREAD

**Issue by Adocentyn** [djcb/mu#2708]
**Describe the bug**

Give the bug a good title.
Since the 1.12.5 it is no longer possible for a setup using several email accounts and no contexts to choose which email with which to compose messages and it is no longer possible to reply to emails using the email address that the message was sent to. 

**How to Reproduce**

WIth mu/mu4e 1.12.5, have a setup with several email accounts and the ability to have each email account available as a potential sender - plus the rule that replying to an email is done by default with from the account the message was sent to. 

Try to compose an email and try to reply from an existing email.

** Results ** 
mu4e has picked the first email account in the init file and treats it as the default and sole sender of emails even when replying to messages in other inboxes. 

**Environment**

ArchLinux
Emacs 29.3
mu4e 1.12.5

**Comment by djcb** [comment]
I'd recommend using contexts, but it should work without. I think we were missing a call to `mu4e-compose-pre-hook`, which I have added.

The gnus-based composer depends on  `message-alternative-emails` to decide if it should use the To: address as a From: for replies; but I suppose mu4e could try to set that for you. 

I'll push some changes.
