### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by jonascant** [djcb/mu#2709]
I am using mu4e 1.10.8-2~bpo12+1 and Emacs 30.0.50

mu4e-contacts-info returns all my contacts properly. However hitting TAB when composing a message returns "No Match"

Running (mu4e--request-contacts-maybe)  returns nil. 

I am using mu4e-contexts.

How can i debug this further?

Thanks!

**Comment by djcb** [comment]
Check `mu4e-compose-complete-addresses` and see what's the value of `completion-at-point-functions`.
Check what's bound to `TAB`. Try with a minimal setup (just load emacs & mu4e and minimal configuration).

**Comment by djcb** [comment]
So, ^^^ this is how you can debug this further. This should generally work, many people use this every day.
