### ISSUE TITLE
[mu4e bug] Broken quoted message formatting in mu4e 1.12.4

### ISSUE THREAD

**Issue by jman-schief** [djcb/mu#2710]
In some cases mu4e breaks the formatting when showing the part of an email that is quoting a previous email.

**How to Reproduce**

- Compose a new email, add a few looong lines (e.g. a few lorem ipsums on a single line, setting `set-fill-column` to 2000)
- send this email to myself
- After receiving the email, hit "R" to compose a reply, quote part of it, send the reply to myself again
- Open the reply. the email shows the quoted part of the previous email not clearly readable because all newlines are removed

however if I "R" again to reply to that reply, the layout of the quoted part looks fine. See the attached message and a screenshot to be sure it's clear what I see:

**Environment**

* Doom emacs
* mu/mu4e 1.12.4 (Debian packaging - cannot test latest mu4e upstream)
* Emacs 29.1

**Checklist**

- [x] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [ ] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

[email.txt](https://github.com/djcb/mu/files/15490045/email.txt)

<details><summary>
How I currently see this email</summary>
<p>

![screenshot-20240529-213938](https://github.com/djcb/mu/assets/82455740/6b4920e2-4757-4cad-9337-5f01684dabd9)

</p>
</details>

**Comment by djcb** [comment]
Can you include the source message, ie. the one on which you press `R`. Thanks.

**Comment by djcb** [comment]
Hmm, thanks. It works just fine for me. 

Some things to double-check:
- is this with the doom-flavored mu4e or the real one?
- can you reproduce with just a default settings or do you have something special with auto-filling, "flow" etc.
- you say "quote part of it", does it also happen when you just reply to the whole?
- best retry with >= 1.12.5 once that is available for you.

**Comment by djcb** [comment]
I guess the algorithm that tries to recognize quoted text can be fooled.

Anyway, try again with >= 1.12.5 and if you can still see it there, please how this message looks like after you "added some text". I'd also recommend adding newlines between quoted text and text you added. Thanks.
