### ISSUE TITLE
[mu bug] Wrong type argument: char-or-string-p, nil with SOME attachments

### ISSUE THREAD

**Issue by telmich** [djcb/mu#2712]
**Describe the bug**

Sometimes when I want to save an attachment using "e<tab><return>" , mu4e replies with:

Wrong type argument: char-or-string-p, nil

**To Reproduce**

Receive an email containing the filename "Rechnung-1035990, Schottelius Nico, 8775 Luchsingen.pdf"

Saving files that are named "2023-12 RBJR ungleich glarus ag (dig. unterz).pdf" does work (so it seems not to be a whitespace issue)

I can privately forward this email, if it helps.

**Environment**

Alpine Linux

```
nb3:~# apk list -I | grep -e ^mu4e -e ^emacs
emacs-29.3-r1 x86_64 {emacs} (GPL-3.0-or-later) [installed]
emacs-x11-29.3-r1 x86_64 {emacs} (GPL-3.0-or-later) [installed]
mu4e-1.12.5-r0 x86_64 {mu} (GPL-3.0-or-later) [installed]
nb3:~# 
```

**Checklist**
- [x ] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

I am running mu for emacs version 1.12.5

**Comment by djcb** [comment]
Best to create a reproducer you can attach here; if that's too hard, you can send it to me. I won't pay your bills though!
Also, please provide backtrace (i.e., `M-x toggle-debug-on-error`, then reproduce; add the backtrace that's printed to this ticket.

**Comment by djcb** [comment]
Any update? Can you attach the problematic message? Thanks.

**Comment by djcb** [comment]
Closing.. feel free to (re)open with the needed info.
