### ISSUE TITLE
[mu4e rfe] Save all attachments in one time

### ISSUE THREAD

**Issue by jpggithub** [djcb/mu#2717]
It would be convenient to save all attachments in one time instead of repeating the saving process for each file or (with vertico, push the "e" key, select one file, push the "," key, then select the following file, etc.).

I would like to have a specific function to save all the attachments in one time. 
`C-u C-u e` could be a kind of natural shortcut.

**Comment by djcb** [comment]
You can type `e` and then `C-c C-a`

**Comment by jpggithub** [comment]
Thanks a lot!
My bad! I looked at the function `mu4e-view-save-attachments` documentation and searched on the web, searched about vertico, etc. but didn't look at the info documentation :/
I suggest to add some words about `mu4e-view-complete-all` in the function  `mu4e-view-save-attachments` documentation as it is a very useful feature.
