### ISSUE TITLE
Unable to set bookmark from mu4e view

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#2718]
**Describe the bug**

C-x r m is not working from view, however it is working from headers.
The reason is that `bookmark-make-record-function` is set from `mu4e-view-mode` but for some reasons the local variables set from there are killed afterward.
As a work around I set the variable from `mu4e-view-rendered-hook`.

**How to Reproduce**

C-x r m from mu4e view buffer.

**Environment**

LinuxMint and Emacs-31.0.50 or 29.4

**Checklist**

- [X ] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [ X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [ X] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket.

Thank you!

**Comment by djcb** [comment]
Thanks. A little weird, but can repro. And I have a fix :-)
