### ISSUE TITLE
[misc] [mu4e] [documentation] Incomplete sentence on section `5.6.2 MIME-part actions`

### ISSUE THREAD

**Issue by CyberFox001** [djcb/mu#2723]
On the online documentation of mu4e, section `5.6.2 MIME-part actions`, the last sentence is incomplete.

It say:

> For now, these actions are defined and documented in mu4e-view-mime-part-actions and see 

And the sentence end here.

URL to this section: 
https://www.djcbsoftware.nl/code/mu/mu4e/MSGV-Actions.html#MIME_002dpart-actions-1

**Comment by CyberFox001** [comment]
I have found other errors on the documentation.

Do I create an issue for each one, or do I report them on this issue ?

**Comment by djcb** [comment]
Even better, create a PR :-)

**Comment by CyberFox001** [comment]
I will, but later. For now, I have my last work to do for school.

But I have added a task to my todo list to come back here.
