### ISSUE TITLE
[mu4e rfe] Adding mailing list commands

### ISSUE THREAD

**Issue by CyberFox001** [djcb/mu#2724]
**Is your feature request related to a problem? Please describe.**

Before mu4e, I was using Gnus. I prefer mu4e, but there is one feature that miss me: The Mailing list commands.

It's a simple set of commands, that let you subscribe/unsubscribe, fetch help, post new message, contact the list owner and brows the list archive.

More information on Gnus manual:
https://www.gnu.org/software/emacs/manual/html_mono/gnus.html#Mailing-List

As I am subscribed to a lot of mailing lists, these commands are really useful for me.

**Describe the solution you'd like**

Adding a set of commands related to a mailing list to :
- Subscribe, if a `List-Subscribe` field is present on an e-mail
- Unsubscribe, if a `List-Unsubscribe` field is present on an e-mail
- Post a new message, if a `List-Post` field is present on an e-mail
- Fetch  help, if a `List-Help` field is present on an e-mail
- Send a message to list owner, if a `List-Owner` field is present on an e-mail
- Browse the list archive, if a `List-Archive` field is present on an e-mail
- Show mailing list infos, who resume all the list addresses (help, post, etc)

All the action could be done from a message view or from a headers view, with a keyboard key binding like:
- `lh`: Fetch list help
- `lp`: Post on the list
- `li`: Show list infos
- etc

And from the list info buffer, we could also call commands with a simple letter. Like `a` to browse archive, `p` to post a new messages, etc 

Another useful feature would be, we you reply to a message received from a mailing list, that mu4e ask the user if she/he want to reply to the mailing list or to the message sender.

**Describe alternatives you've considered**

I've considered creating a mailing list action to do that. But it could be useful to other users to having it included into mu4e.

**Comment by djcb** [comment]
It's in our `IDEAS.org` file, I've updated it for your RFE. Seems useful, need to check whether the Gnus code can be re-used for this. So closing it here now. Thanks!
