### ISSUE TITLE
[mu4e rfe] Way to jump between fields in compose mode

### ISSUE THREAD

**Issue by jonascant** [djcb/mu#2727]
It would be great, if there was a way to quickly jump between the different headings (FROM:, TO:, etc) with a keybinding. 
I know TAB is already used to complete addresses, but maybe there is a smart way to use TAB after having entered the TO: address to jump to the next fields and finally to the message body.

**Comment by djcb** [comment]
It's already there :). See the various `message-goto...` commands;  find them in the "Field" menu, or in the mode help (`C-h m`). And you can use `C-p` / `C-n` of course.
