### ISSUE TITLE
[misc] [mu4e] [documentation] install instructions for 

### ISSUE THREAD

**Issue by 88-percent** [djcb/mu#2729]
**Describe the issue**
A clear and concise description, i.e. what you expected/desired to happen and what actually happened.

The manual at https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html says that to build mu the commands should be:

```
$ ./configure && make
$ sudo make install
```
I couldn't find a configure file. I was able to install using:

```
meson build && ninja -C
ninja -C build install
```

I'm new at this, so I'm not sure if I missed a step or if the documentation needs an update.

**Comment by djcb** [comment]
Yes, those instructions are outdated; I'll update them; thanks.
