### ISSUE TITLE
mu4e-compose-pre-hook not triggering anymore

### ISSUE THREAD

**Issue by RidaAyed** [djcb/mu#2731]
I'm setting my account by a custom function named `my-mu4e-set-account` attached to `mu4e-compose-pre-hook`

`(add-hook 'mu4e-compose-pre-hook 'my-mu4e-set-account)`

Since updating my system, the mentioned hook is not triggering anymore.  
No error is raised.

Did I miss a breaking change?

P.S. Posting to groups.google.com leads lead to nothing > I'm unable to find any posting from me
P.S.S. I'll gladly consider migrating to the recommended `context` mechanism another time

**Comment by djcb** [comment]
Seems you message got suspended by gmail. Are you subscribed to the list?

Anyway,  `mu4e-compose-pre-hook` was indeed broken, but already fixed in `master` and the upcoming version 1.12.6, which should be available soon.
