### ISSUE TITLE
[mu4e bug] How to silence tip on `user-mail address`

### ISSUE THREAD

**Issue by kflak** [djcb/mu#2733]
**Describe the bug**

First of all, thanks for a _fantastic_ email client!

And now that this is out of the way: not exactly a bug, more of an annoyance, but I keep getting the message:
```
[mu4e] Tip: `user-mail-address' ('kf@t480s') is not part of mu's addresses; add it with 'mu init --my-address='
```
This is not my email address, and I would like to silence the warning, as it's getting quite annoying. Is there a simple way of getting rid of this?

**How to Reproduce**

Run mu4e in emacs after initializing the mu database and run the indexing command.

**Environment**
Arch Linux, emacs 29.4, mu 1.12.5

**Checklist**

- [ x] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [ x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [ x] you have read all of the above

**Comment by djcb** [comment]
Either set `user-mail-address` to one of your actual addresses (i.e. one you passed as `--my-address` to `mu init`)., or set `mu4e-main-hide-personal-addresses` to `t`.

**Comment by kflak** [comment]
Thanks!
