### ISSUE TITLE
[mu4e rfe] Opening attachments directly in external programs

### ISSUE THREAD

**Issue by tmplt** [djcb/mu#2739]
**Is your feature request related to a problem? Please describe.**
I record and send audio logs to myself in order to postpone tasks/notes/thoughts, listening to these attachments via mu4e is a bit of a hassle: save each file, dired to download location, and invoke vlc/mpv on them.

**Describe the solution you'd like**
I'd like to open an attachment directly (without copying it under `~/` somewhere) with a program of my choosing: press bind, select attachment, and spawn process.

**Comment by djcb** [comment]
That's already possible, using attachment-actions, under `A` by default. See `(mu4e) MSGV Attachments and MIME-parts` in the manual for details.

**Comment by aloispichler** [comment]
I am struggling to write a function which
* opens the url in default browser, if point is on url, or
* opens the pdf, if point is at pdf, or
* opens libreoffice (the default application), if point is at .doc, etc.
upon hitting `enter` as in any other mail program.
I did not manage. Any help is highly appreciated – thanks!
