### ISSUE TITLE
[mu4e bug] when the captured message's subject is emtpy `mu4e-compose-attach-captured-message` inserts a tag without a value for the description

### ISSUE THREAD

**Issue by RyanGibb** [djcb/mu#2746]
Using `mu4e-compose-attach-captured-message` inserts a tag with an empty description which fails to send due to `Scan error: "Containing expression ends prematurely"`. Adding a description seems to fix this issue. NB `mu4e-compose-attach-captured-message` is used after using the capture action on a message.

**Environment**

Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

NixOS 24.05
mu version 1.12.5
GNU Emacs 29.4

**Checklist**

- [x] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment]
Cannot reproduce... is this one particular message you try to capture? If so, please attach it (or anything that reproduces the problem). Also what does the "tag" look like? Thanks.

**Comment by RyanGibb** [comment]
Ah, it looks like this only occurs when the subject of the message being captured is empty. For example, this is what is normally inserted (which works):
```
<#part type="message/rfc822" filename="path" disposition=attachment description="subject">
<#/part>
```

But when the captured message subject is empty it is instead:
```
<#part type="message/rfc822" filename="path" disposition=attachment description=>
<#/part>
```

**Comment by djcb** [comment]
Cannot reproduce still, if there's no subject the code explicitly uses the string "No subject" as the subject. Can you attatch the message where this happens for you?

**Comment by RyanGibb** [comment]
This is a minimal viable message that exhibits this behaviour for me:

```
From: Ryan Gibb <ryan@freumh.org>
To: ryan@freumh.org
Subject: 
Date: Wed, 21 Aug 2024 08:27:36 +0100
Message-ID: <871q2i72tz.fsf@freumh.org>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii


```

Also attached as a file: [message.txt](https://github.com/user-attachments/files/16687703/message.txt)

Which when captured and using `mu4e-compose-attach-captured-message` inserts:

```
<#part type="message/rfc822" filename="/home/ryan/mail/ryan@freumh.org/Sent/cur/1724225244.49993ad54b5e2832.gecko,U=169:2,S" disposition=attachment description=>
<#/part>
```

**Comment by RyanGibb** [comment]
When the subject is omitted instead of just being empty it exhibits the behaviour you describe:

```
From: Ryan Gibb <ryan@freumh.org>
To: ryan@freumh.org
Date: Wed, 21 Aug 2024 08:27:36 +0100
Message-ID: <871q2i72tz.fsf@freumh.org>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii


```

```
<#part type="message/rfc822" filename="/home/ryan/mail/ryan@freumh.org/Sent/cur/1724225244.49993ad54b5e2832.gecko,U=169:2,S" disposition=attachment description="No subject">
<#/part>
```

**Comment by djcb** [comment]
I could reproduce with that message, thanks. Not quite sure what was different... anyway I'll push a fix. Thanks.

**Comment by RyanGibb** [comment]
Thanks for taking the time address this @djcb! This is a great bit of software.
