### ISSUE TITLE
mu4e-error: [mu4e] Found mu version 1.12.0, but mu4e needs version 1.9.0; please set `mu4e-mu-binary' accordingly

### ISSUE THREAD

**Issue by guillaumegeri** [djcb/mu#2758]
I used to use mu4e with the 1.9.0 mu version and it worked fine.
Since I installed the latest version (1.12.0) (and after mu init) it does not work anymore in my emacs with the following message: 
```
mu4e-error: [mu4e] Found mu version 1.12.0, but mu4e needs version 1.9.0; please set `mu4e-mu-binary' accordingly [2 times]
```

I did not change the path to the binary (which is the same).
I reinstalled my emacs and mu from scratch bu I get the same issue.
Any hint?

**Comment by djcb** [comment]
It means that the `mu` binary has version 1.12.0, but mu4e is a much older version (1.9.0) you still having lying around somewhere.

 So after installation, make sure that the new version of mu4e is found in your `load-path`. And/or scan your system check where the older mu4e was installed, remove it and install the newer version, as per the doc.

Note that the latest version is 1.12.6, with quite a few improvement / fixes.

Good luck!
