### ISSUE TITLE
[mu bug] --debug does not generate the mu.log file expected

### ISSUE THREAD

**Issue by husainaloos** [djcb/mu#2762]
When running mu with `--debug` flag, the mu.log file is not generated in the `$HOME/.cache/mu` directory. However, when running mu with `--log-stderr`, it shows the logs in stderr.

**How to Reproduce**

All of the following commands should create `mu.log` file per the `man mu` page. But none of them create the log file.

```
$ mu index --debug
$ mu --debug index
$ mu find "hi" --debug
$ mu --debug find "hi"
```

This issue happens every time.  There is no warning associated with the output.

When I run with `--log-stderr`, I see that mu is setting the debug flag correctly, just without the log file:

```
$ mu -v -d --log-stderr find "hihihi"
** Message: 16:45:04.771: logging initialized; debug: yes, stdout/stderr: yes
(process:36243): mu-DEBUG: 16:45:04.771: created Database() @ /home/husain/.cache/mu/xapian
(process:36243): mu-DEBUG: 16:45:04.778: sw: query: 'hihihi'; (related:no; threads:no; ngrams:no; max-size:∞): finished after 206 us
(process:36243): mu-DEBUG: 16:45:04.778: closing store @ /home/husain/.cache/mu/xapian
(process:36243): mu-DEBUG: 16:45:04.779: closing db
```

**Environment**
Please describe the versions of OS, Emacs, mu etc. you are using.

Opensuse Tumbleweed. mu version 1.12.6.

**Checklist**
- [x] you are running either the latest 1.10.x/1.12.x release or `master` (otherwise, please upgrade).

Thank you!

**Comment by markk** [comment]
The logs are probably in the system journal. Try running:
```
journalctl --since today $(which mu)
```

**Comment by djcb** [comment]
Indeed, the logging likely goes to the journal or syslog; the manpage is outdated there; I'll push a fix.
