### ISSUE TITLE
[mu4e bug] `user-mail-address' is not part of mu's addresses

### ISSUE THREAD

**Issue by formbi-kupiec** [djcb/mu#2764]
**Describe the bug**

I have a couple accounts in mbsync and mu, but mu4e picks up only one and says «`user-mail-address' is not part of mu's addresses»

**How to Reproduce**
- I set up several accounts on hydroxide ( https://github.com/emersion/hydroxide )
- modeled my mbsync and mu4e config after this: https://systemcrafters.net/emacs-mail/managing-multiple-accounts/
- ran `mu init --maildir=~/Mail --my-address=[john.doe]@protonmail.com` for all the accounts
- ran `mu index`
- started mu4e
- upon starting and when I try to switch context, I get «[mu4e] Tip: `user-mail-address' ('[john.doe]@protonmail.com') is not part of mu's addresses; add it with 'mu init --my-address='». Only the account init-ed as the last one (doesn't matter which one it is) works properly.

This also occurs with `emacs -Q`. Other e-mail clients (Claws-mail, Thunderbird) don't have a problem with hydroxide and mbsync does save messages.

`mu.log`:
```
2024-09-25 16:59:11 ** Message: 16:59:11.177: logging initialized; debug: yes, stdout/stderr: no
2024-09-25 16:59:11 (process:30526): mu-DEBUG: 16:59:11.177: created WritableDatabase() @ /home/formbi/.cache/mu/xapian
2024-09-25 16:59:11 mu-Message: 16:59:11.179: created server with store @ /home/formbi/.cache/mu/xapian; maildir @ /home/formbi/Mail; debug-mode yes;readline: no
2024-09-25 16:59:11 (process:30526): mu-DEBUG: 16:59:11.239: starting scan @ /home/formbi/Mail
2024-09-25 16:59:11 (process:30526): mu-DEBUG: 16:59:11.245: finished scan of /home/formbi/Mail in 6 ms
```

**Environment**
`mu info`:
```
+------------------+--------+---------------------------------------+
| property         | value  | description                           |
+------------------+--------+---------------------------------------+
| mu-version       | 1.12.6 | Mu runtime version                    |
+------------------+--------+---------------------------------------+
| xapian-version   | 1.4.19 | Xapian runtime version                |
+------------------+--------+---------------------------------------+
| gmime-version    | 3.2.14 | GMime runtime version                 |
+------------------+--------+---------------------------------------+
| glib-version     | 2.78.0 | GLib runtime version                  |
+------------------+--------+---------------------------------------+
| schema-version   | 500    | Version of mu's database schema       |
+------------------+--------+---------------------------------------+
| cld2-support     | no     | Support searching by language-code?   |
+------------------+--------+---------------------------------------+
| guile-support    | yes    | GNU Guile 3.x scripting support?      |
+------------------+--------+---------------------------------------+
| readline-support | no     | Better 'm server' REPL for debugging? |
+------------------+--------+---------------------------------------+
```

OS: Guix
Emacs: 29.4
isync: 1.5.0
hydroxide: 0.2.29
all listed programs are installed through Guix

**Checklist**

- [ +] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [ +] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [ +] you have read all of the above

**Comment by djcb** [comment]
You need to tell `mu` about all your e-mail address with `mu init --my-address=address1 --my-address=address2` etc; you can see them with `mu info store` (`personal address`). Is that not working?

Mbync/hydroxide etc., are not relevant for this.

**Comment by formbi-kupiec** [comment]
Ahh, I wouldn't have guessed that you need to put all the addresses in one line, thanks!
