### ISSUE TITLE
strange behaviour using mu4e-marks

### ISSUE THREAD

**Issue by joukeHijlkema** [djcb/mu#2771]
**Describe the bug**

When I hit t and then + in the header view with threads showing,  the thread gets flagged as expected. However, when I do the same thing with threads off all 500 messages get flagged. I'd expect only the highlighted message to be flagged.

This is a follow-up from an email exchange with Dirk. The 

**How to Reproduce**

- Start emacs with option -Q
- use the following configuration
```(use-package mu4e
  :straight (:host github
                   :files ("build/mu4e/*.el")
                   :repo "djcb/mu"
                   :branch "release/1.10"
                   :pre-build (("./autogen.sh")
                               ("/usr/bin/meson" "setup" "--reconfigure" "build")
                               (shell-command (concat "echo " (shell-quote-argument (read-passwd "root password? ")) " | sudo -S /usr/bin/ninja -C build install"))))
  :commands mu4e
  :config (message "=== my mu4e config ===")
  (setq mail-user-agent 'mu4e-user-agent)
  (setq mu4e-get-mail-command "/usr/bin/offlineimap -o")
  (setq mu4e-sent-folder "/Work/INBOX.Sent")
  (setq mu4e-mu-binary "/usr/local/bin/mu")
  
  (mu4e-bookmark-define "maildir:/Work/INBOX NOT flag:trashed"                         "Inbox"        ?i)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND flag:unread"                          "Inbox unread" ?u)
  (mu4e-bookmark-define "maildir:/Work/INBOX.Sent"                                     "Sent"         ?s)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND date:today..now AND NOT flag:trashed" "Today"        ?t)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND date:1w..now AND NOT flag:trashed"    "Last week"    ?w)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND date:5w..now AND NOT flag:trashed"    "Last month"   ?m)
  (mu4e-bookmark-define "maildir:/Spam AND flag:unread"                                "Spam"         ?z)
  )
```
- start mu4e (M-x mu4e)
- In the inbox hit t and then +. The thread gets flagged. Hit U to remove marks
- Hit P then t to disable threads
- Hit t then +. All messages get flagged. Hit U to remove marks

**Environment**

GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43,cairo version 1.18.0)
mu4e - mu for emacs version 1.12.6-st

**Checklist**

- [ x] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [ x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [ x] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket.

Thank you!

**Comment by djcb** [comment]
Hmm, `:branch "release/1.10"`?

**Comment by joukeHijlkema** [comment]
ahhhhh :-( 
Sorry !

**Comment by joukeHijlkema** [comment]
False hope. With the following it does the same.

```
(use-package mu4e
  :straight (:host github
                   :files ("build/mu4e/*.el")
                   :repo "djcb/mu"
                   :pre-build (("./autogen.sh")
                               ("/usr/bin/meson" "setup" "--reconfigure" "build")
                               (shell-command (concat "echo " (shell-quote-argument (read-passwd "root password? ")) " | sudo -S /usr/bin/ninja -C build install"))))
  :commands mu4e
  :config (message "=== my mu4e config ===")
  (setq mail-user-agent 'mu4e-user-agent)
  (setq mu4e-get-mail-command "/usr/bin/offlineimap -o")
  (setq mu4e-sent-folder "/Work/INBOX.Sent")
  (setq mu4e-mu-binary "/usr/local/bin/mu")
  
  (mu4e-bookmark-define "maildir:/Work/INBOX NOT flag:trashed"                         "Inbox"        ?i)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND flag:unread"                          "Inbox unread" ?u)
  (mu4e-bookmark-define "maildir:/Work/INBOX.Sent"                                     "Sent"         ?s)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND date:today..now AND NOT flag:trashed" "Today"        ?t)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND date:1w..now AND NOT flag:trashed"    "Last week"    ?w)
  (mu4e-bookmark-define "maildir:/Work/INBOX AND date:5w..now AND NOT flag:trashed"    "Last month"   ?m)
  (mu4e-bookmark-define "maildir:/Spam AND flag:unread"                                "Spam"         ?z)
  )
```

**Comment by djcb** [comment]
Can't reproduce with emacs 30 or 29, with something like:
```
emacs-29.4 -Q --eval "(progn (add-to-list 'load-path \"~/Sources/mu/build/mu4e\") (setq mu4e-mu-binary \"~/Sources/mu/build/mu/mu\") (require 'mu4e))"
```
Anyway, I don't know exactly what "straight" does, nor is it part of mu, so can you reproduce the "normal'" way? Thanks.

**Comment by joukeHijlkema** [comment]
Hello Dirk,

Using:
emacs-29.4 -Q --eval "(progn (add-to-list 'load-path \"./mu4e\") (setq
mu4e-mu-binary \"./mu/mu\") (require 'mu4e))"

and:

(setq mail-user-agent 'mu4e-user-agent)
(setq mu4e-get-mail-command "/usr/bin/offlineimap -o")
(setq mu4e-sent-folder "/Work/INBOX.Sent")
(setq mu4e-mu-binary "/usr/local/bin/mu")

(mu4e-bookmark-define "maildir:/Work/INBOX NOT flag:trashed" "Inbox" ?i)

I have the same problem. Fagging (t and +) works fine with threads on but
flags everything with threads off. However, hitting + flags only the
selected message for both cases.

Let me know if I can do anything else.

Jouke

**Comment by djcb** [comment]
Ah, now I finally get what you mean, you use the `t` when there are no separate threads. Sorry for being slow!

But when there are no separate threads, I guess it's not unreasonable to consider all the messages in the same thread. I suppose some may find it "strange behavior", but it seems okay to me. I'll add a note to the docs, thanks for pointing this out.

**Comment by joukeHijlkema** [comment]
Hey Dirk-Jan,

I'm trying to get my head around this, but I can't seem to make it work. Is
there a way to tag just one single message independent of threads?
Preferably, from the view buffer.

Jouke

**Comment by djcb** [comment]
I never use that functionality, but I think you can mark with `*`, then `x` then your action (such as `g` for tagging).
