### ISSUE TITLE
[mu4e bug] `user-mail-address' is not part of mu's addresses

### ISSUE THREAD

**Issue by samueltardieu** [djcb/mu#2772]
I know there was an issue with the very same title from someone else a few weeks ago, but it looks like we don't have the same problem.

mu 1.12.6 knows about my mail addresses, as shown in the output of `mu info store` which lists 7 addresses + 2 `/regex/` adresses in personal-address entries:

```
$ mu info store
+-------------------+-------------------------------------+
| property          | value                               |
+-------------------+-------------------------------------+
| maildir           | /home/sam/Mail                      |
+-------------------+-------------------------------------+
| database-path     | /home/sam/.cache/mu/xapian          |
+-------------------+-------------------------------------+
| schema-version    | 500                                 |
+-------------------+-------------------------------------+
| max-message-size  | 100000000                           |
+-------------------+-------------------------------------+
| batch-size        | 50000                               |
+-------------------+-------------------------------------+
| created           | Mon Apr  8 15:26:52 2024            |
+-------------------+-------------------------------------+
| personal-address  | sam@REDACTED                     |
+-------------------+-------------------------------------+
| personal-address  | sam@REDACTED                     |
+-------------------+-------------------------------------+
…
```

However, I get the "Tip" to add my address to mu. Indeed `(mu4e-server-properties)` evals to: 

```elisp
(:version "1.12.6" :personal-addresses nil :database-path "/home/sam/.cache/mu/xapian" :root-maildir "/home/sam/Mail" :doccount 130944)
```

**Environment**
I'm using mu4e 797ca3e37fe74f081c16540b8c25a34a4e4276a4 (using straight), mu 1.12.6, on NixOS.

**Checklist**
- [X] you are running either the latest 1.10.x/1.12.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment]
Please follow the check-list:
```
**Checklist**

- [ ] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [ ] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [ ] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket.
````
You can use `straight` or whatever you want, but please do a reproducible steps with a normal build when you file a ticket as described in the manual, thanks.

**Comment by djcb** [comment]
Gotten stale, closing this. But please reopen or open a new ticket if you have steps with a normal build setup. I'd suspect the problem may be some mixup of versions on your system, but I have no bandwidth to track alternative setups like '"straight". Sorry!
