### ISSUE TITLE
[mu4e bug] mu4e-search-rerun does not update modeline for bookmark query.

### ISSUE THREAD

**Issue by fuyu0425** [djcb/mu#2775]
**Describe the bug**

mu4e-search-rerun does not update modeline for bookmark query.

**Reproduce step**
Just hit `mu4e-search-rerun` when in a bookmark query.

**Root cause I dig into**

`mu4e-search-bookmark` will called `(mu4e--query-items-refresh 'reset-baseline)`
so, the modeline is updated

However, `mu4e-search-return` does not update mode-line, is it intended or not for some reason or a bug?

Should we test whether last query is a favorite bookmark query or not (in `mu4e-search` or `mu4e-search-rerun`) and invalidate the cache? 

   `mu4e-search-rerun`
-> `mu4e-search`
-> `mu4e--modeline-update`
-> `force-mode-line-update`
-> `(:eval (mu4e--modeline-string)`
-> `mu4e--bookmarks-modeline-item`
-> `mu4e-query-items`
-> `mu4e--bookmark-items-cached` is not invalidated, so return old value

**Environment**

Emcas: 29.4
mu: 1.12.6 (single thread branch)

**Checklist**

- [x] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket.

Thank you!

**Comment by djcb** [comment]
Hmmm, not quite sure what you mean. What do you expect the modeline to look like after a re-query, and how does it actually look?

**Comment by fuyu0425** [comment]
So my normal workflow is as follows:
I normally never left the `mu4e-headers` view. 
For example, the headers list all unread mails. (Which is my favorite bookmark query)
Then I just mark/read some mails and hit `mu4e-search-rerun` to update the headers view.
Then, I expected the modeline updated to reflect that but it did not.

**Comment by djcb** [comment]
I still don't understand. I show unread message (`b u`). Modeline says "[Unread message]". I read some, delete some. Press `g` (`mu4e-search-rerun`). Get refreshed result, Modeline says "[Unread message]" as before, but I think that's expected? Or what are you seeing?

**Comment by fuyu0425** [comment]
Can your number also be refreshed?  These numbers.
<img width="161" alt="圖片" src="https://github.com/user-attachments/assets/50fb34e0-94aa-46b2-b2c7-5754c1a23ffc">

**Comment by djcb** [comment]
Thanks, I see what you mean now... let me see if we can improve this particular case....

**Comment by djcb** [comment]
I changed the code to try harder to update the baseline, if the query matches the favorite's, regardless how we do the query (bookmark, search or rerun).
