### ISSUE TITLE
[mu4e bug] Cannot handle command while indexing, please retry later.

### ISSUE THREAD

**Issue by peterhoeg** [djcb/mu#2778]
**Describe the bug**

I am constantly seeing `mu4e-warn: [mu4e] Cannot handle command while indexing, please retry later.` - effectively every other action I do since upgrading to `1.12.7-st`. 

In the 6 weeks or so using `1.12.6-st` I didn't see once or at least don't recall having seen it.

**How to Reproduce**

Pretty much any action will trigger it.

**Environment**
- emacs: 29.4
- mu: 1.12.7-st
- xapian: 1.4.26

**Checklist**

- [x] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [ ] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

I have *not* tried with `emacs -Q` but going back to `1.12.6-st` makes the problem go away again.

**Comment by djcb** [comment]
Not a bug, the warning is expected behavior, it tells you when the action cannot be performed. In 1.12.6st, there was no warning (but the command still wouldn't work).

If you see it _a lot_, I guess indexing takes quite a bit of time.

You could  try:
```
modified   mu4e/mu4e-server.el
@@ -547,12 +547,12 @@ You cannot run the repl when mu4e is running (or vice-versa)."
   (unless (mu4e-running-p)
     (mu4e--server-start))
   ;; in single-threaded mode, mu can't accept our command right now.
-  (when (and (mu4e--server-xapian-single-threaded-p) mu4e--server-indexing)
-    (mu4e-warn "Cannot handle command while indexing, please retry later."))
-  (let* ((print-length nil) (print-level nil)
-         (cmd (format "%S" form)))
-    (mu4e-log 'to-server "%s" cmd)
-    (process-send-string mu4e--server-process (concat cmd "\n"))))
+  (if (and (mu4e--server-xapian-single-threaded-p) mu4e--server-indexing)
+      (mu4e-message "Cannot handle command while indexing, please retry later.")
+    (let* ((print-length nil) (print-level nil)
+           (cmd (format "%S" form)))
+      (mu4e-log 'to-server "%s" cmd)
+      (process-send-string mu4e--server-process (concat cmd "\n")))))
 ```

and see if that irmproves things.

**Comment by djcb** [comment]
I've demoted the warning to a mere message. As I said, if you see the message a lot, it means you're indexing much of the time, which is not good. 

I've made the "lazy check" for mu indexing even lazier (see commit `b0d8d42d`); this should help if the slow indexing is due to new messages popping up in big maildirs (and a rel. slow fs). 

For  mu4e, that's ` (setq mu4e-index-lazy-check t)` or ` --lazy-check` on the command-line for `mu index`.

**Comment by benthamite** [comment]
Hi, I am also experiencing this. It is pretty disruptive: half of the times I want to go to my inbox, I get a "Cannot handle command while indexing, please retry later" message. I experienced no issues before, so it doesn't seem like "there was no warning (but the command still wouldn't work)". Is there anything I can do to help diagnose the issue?

**Comment by djcb** [comment]
The "there was no warning (but the command still wouldn't work)" referred to the experimental branch vs 1.12.7-st; but I can imagine things changed compared to say. 1.12.6.  See the discussion here:
   https://groups.google.com/g/mu-discuss/c/hV7WwwkX1Lg

`master` has a few changes, in particular I'd recommend using `mu4e-index-lazy-check`, which has seen some updates as well.

**Comment by benthamite** [comment]
Thank you. Do you have any suggestions on how to go about diagnosing why indexing happens so often?

**Comment by benthamite** [comment]
I see, thanks. `mu4e-update-interval` is set to `300`. I’ll increase it to `1500` (15 minutes); that should reduce the incidence of the issue to one-fifth, I assume.

`mu index` takes 28 seconds. `mu index --lazy-check` takes 17 seconds. I have a total of 335k messages.

**Comment by djcb** [comment]
Yeah, if you set `mu4e-index-lazy-check` to `t` and increase the interval a bit, you shouldn't see the warnings less often. 
Still, 28 or 17 seconds is _really_ long, it's about 10x faster here (with ~120K messages). I wonder why that is.

**Comment by stsquad** [comment]
As I have a massive mailbox (91G) with a huge index (76G) I'm super sensitive to update times. This is the workaround I currently have in my config:

```
(defun my-set-mu4e-index-params ()
  "Set the index parameters for the current update.

This is dependant on if I'm active (hence wanting a quick update) or
away (in which case it can take its time). Ideally we would do this
right before the index but currently there is no hook for that."
  (let ((idle (time-convert (current-idle-time) 'integer))
        (old-lazy mu4e-index-lazy-check)
        (old-cleanup mu4e-index-cleanup))
    (if (and (current-idle-time)
             (> idle mu4e-update-interval))
      (setq mu4e-index-lazy-check nil
            mu4e-index-cleanup t)
    (setq mu4e-index-lazy-check t
          mu4e-index-cleanup nil))
    (when (not (and (equal old-lazy mu4e-index-lazy-check)
                    (equal old-cleanup mu4e-index-cleanup)))
      (message (format "my-set-mu4e-index-params: idle:%s lazy:%s cleanup:%s"
                       idle mu4e-index-lazy-check mu4e-index-cleanup)))))

(use-package mu4e-update
  :after mu4e
  :hook (mu4e-update-pre . my-set-mu4e-index-params)
  :config (setq mu4e-index-lazy-check t             ; faster sync when t
                mu4e-index-cleanup nil))                ; faster cleanup when nil
```

**Comment by benthamite** [comment]
Thanks, @stsquad! `mu index --lazy-check --nocleanup` executes instantly, so this should do the trick.

**Comment by telmich** [comment]
Hello,

I am on 1.12.7-st and it seems that mu is stuck (not displaying the inbox search result) in about 80% of the time.

I have shrunken my inbox significantly down to ca. 900k messages and a `mu index` run takes about 5 seconds (very fast computer) vs. 10 seconds (regular notebook), however still causing an almost complete lockout of the messages.

The `mu index --lazy-check` version takes about 2 seconds on the very fast machine, vs. 5 seconds on the regular notebook.
