### ISSUE TITLE
search is rerun, discarding marks, when updating in background

### ISSUE THREAD

**Issue by bcc32** [djcb/mu#2779]
mu4e-mu-version is "1.12.5"

## Expected or desired behavior

Headers buffer should not be modified if it has any marks, when the index update
process finishes.

## Actual behavior

mu4e-headers buffer's marks are cleared and the search is re-run without user
intervention.  This happens when mu reindexing has non-zero updates and
`mu4e-headers-auto-update` is non-nil.

I have seen the buggy behavior both when manually reindexing and when
`mu4e-update-interval` is configured for automatic updating in the background.

## Steps to reproduce

1. `emacs -q`
2. `M-x package-initialize` if necessary
3. `M-x mu4e`
4. Open an arbitrary search, that has at least one message in it
5. Mark some messages (just `*` is sufficient)
6. In a different window in the same Emacs instance, switch to some buffer that
   isn't `*mu4e-headers*`.  `*scratch*` suffices.  Keep this buffer current.
7. Send email to self, run `offlineimap`, etc. to make it so that the next
   reindex will have an update.
8. `M-x mu4e-update-index`

## Versions of mu, mu4e/emacs, operating system etc.

``` shell
$ mu --version
version 1.12.5
```

mu4e version is 1.12.5

GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.18.0, Xaw3d scroll bars)

This is running on NixOS, but I have observed the buggy behavior on macOS too.

**Comment by djcb** [comment]
Ah, I see what's going on, I'll prepare a fix.
