### ISSUE TITLE
[RFE] Toggle multiple search properties at once

### ISSUE THREAD

**Issue by Gallipo** [djcb/mu#2781]
**Is your feature request related to a problem? Please describe.**
I regularly toggle the `mu4e-search-threads` variable via the "P"-key-binding. But for me, threads only make sense, if `mu4e-headers-include-related` is also true (which I don't like if no threads are shown). So I always have to toggle those two together.

**Describe the solution you'd like**
The introduction of a config-variable like `toggle-threads-with-related`, that if non-nil keeps `mu4e-search-threads` and 
`mu4e-headers-include-related` in sync.

**Describe alternatives you've considered**
As of now, I use a function I wrote, that just toggles both variables and calls `mu4e-search-rerun`, but it's not possible to integrate it to the default key-binding ("P"). And it won't help anybody with the same problem.

Another solution would be to be able to add some custom-toggles into the "P"-key-binding. Like it is possible to add your own marks, for message-handling

**Comment by djcb** [comment]
I'd recommend you use a keyboard macro for this (and you can bind that to a binding of your choice). No need to complicate `mu4e` any further :-) Thanks.
