### ISSUE TITLE
[misc] Status of djcbsoftware.nl ?

### ISSUE THREAD

**Issue by phil-s** [djcb/mu#2783]
http://www.djcbsoftware.nl/ is no longer what it once was.  I'm seeing some kind of hosting company template, I think (not entirely sure, as my browser is blocking most of it, but the URL https://page.active24.cz/unknown.hosting.cz/ is visible).

Is that site still intended to be valid?

I thought perhaps there would be mention of any change in the readme here if it was intentional, but I don't see anything, and https://github.com/djcb still links to it.

**Comment by djcb** [comment]
It was just some temporary problem, thanks for noticing :)
