### ISSUE TITLE
[mu4e bug] No encrypted flag for more Outlook S/MIME message types

### ISSUE THREAD

**Issue by Cerebus** [djcb/mu#2784]
Unlike #2745, this one is doesn't carry `smime-type`.  

```
> mu find subject:"XXXX" -o json | jq '.[] | [.[":path"], .[":flags"]]'
[
  "/Users/xxxxxx/Maildir/INBOX/cur/1730987617.1304_1.xxxxxx,U=2477:2,RS",
  {
    "replied": "seen",
    "attach": "personal"
  }
]
```

Message content headers:

```
Content-Type: application/pkcs7-mime; name="smime.p7m"
Content-Disposition: attachment; filename="smime.p7m"
Content-Transfer-Encoding: base64
MIME-Version: 1.0
```

The attachment is:
```
> cat 1730987617.1304_1.xxxxxx,U=2477:2,RS | openssl smime -pk7out | openssl pkcs7 -print
PKCS7:
  type: pkcs7-envelopedData (1.2.840.113549.1.7.3)
  d.enveloped:
    version: 0
```

**How to Reproduce**
Get someone on Outlook to send you S/MIME emails, I guess?  I'm even sure which version b/c there's no MUA identifier in the headers.  I *think* in this case it's Outlook/Mac but not sure.

And people wonder why MUA authors hate S/MIME.  :( 

**Environment**
mu version 1.12.7
Emacs 29.4
macOS 14.7.1

**Checklist**

- [x] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment]
Can you please attach a message where this happens? Otherwise we can't do anything with this, thanks.

**Comment by djcb** [comment]
Thanks... I'll put a work-around in place.
