### ISSUE TITLE
[RFE] Search by MSGID mentioned in raw messages

### ISSUE THREAD

**Issue by wehlutyk** [djcb/mu#2787]
IDEAS.org: checked.

**Is your feature request related to a problem? Please describe.**
As many threads grow, and many emails keep all previous messages quoted in the current one (quoted from the start of the thread -- except in e.g. developer mailing lists), I usually remove previous emails up to the latest. In which all history is quoted below.

Now, in org-mode, emails can be kept track of using `mu4e:msgid:`. But if I delete earlier emails in a thread, the `mu4e:msgid:` link fails.

**Describe the solution you'd like**
Kept emails still contain the msgid of the first email referred to in org, in the `References` section of the raw email. It would be great to have a mu4e search taking the References.

**Describe alternatives you've considered**
Updating my org reference to a thread each time I delete earlier emails. Or `rg <MSGID> ~/Maildir`.

**Additional context**
None.

Thanks for comments!

**Comment by djcb** [comment]
There are some different aspects to this:

1) search for messages by their references - this was _almost_ working, I've added the final bits (see `NEWS.org` for details)
2) make a org link for this... you'd need 1) but additionally you need to find the first of the references in a message (or perhaps _old_ references) and create a query for that, and create a `mu4e:query:...` for that.

I think the ingredients are there, can even be done outside mu4e. So you're invited :)

Moving this to `IDEAS.org`.
