### ISSUE TITLE
[mu4e bug] Base64 multipart body decoding failing in compose mode 

### ISSUE THREAD

**Issue by miquelraynal** [djcb/mu#2788]
[My final goal is to push already formatted e-mails with attachments to my draft Imap folder from external software. Pushing the messages there works, I can display them correctly in mu4e, but editing them before sending is not working. Here is a very simple approach without external software to reproduce the issue I am facing which I believe is a bug.]

**Describe the bug**

Composing a multipart message with base64 encoded text is correctly displayed in the viewer but is not decoded correctly when the message is re-opened for editing.

**How to Reproduce**

Press `C` to compose a message.

Manually add MIME meta-data like below (I used `M-x base64-encode-region` for the base64 conversion):
```
To: <you@you.com>
Subject: Test
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="=-=-="
--text follows this line--
--=-=-=
Content-Type: text/plain;
Content-Transfer-Encoding: base64
Content-Disposition: inline;

VGhpcyBpcyB0ZXh0IDEuCg==
--=-=-=--
```

Save and quit the view. Select the message again in the (draft) headers list, output (as expected) is:

```
[...]
Flags: draft, seen, personal
Maildir: /drafts                                                                             

[1. text/plain]
This is text 1.
``` 

Press `E` to enter edition mode, the message is not decoded.

Even more disturbing:
- Sending this e-mail to a gmail address will render garbage when done though mu4e/emacs.
- The same e-mail content sent using git-send-email outside of mu4e/emacs renders correctly.

Finally, if I compose the same mail using mu4e with eg. `mml-attach-file`, then when I am in compose mode the look is different (with `<#!part type="text/plain"` tags) but once actually sent, if I show the raw message with `.` from the sent folder, I see no difference with the crafted mail (besides of course things like Fcc or the date field).

**Environment**

Fedora 40, mu/mu4e 1.12.7, Emacs 29.4.

**Checklist**

- [x] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment]
Don't think that's a supported scenario. The draft message format is not the actual format that is sent; so what you're trying to do is not really expected to work, sorry!

So my advise would be to do exactly what `mml-attach-file` does instead

**Comment by miquelraynal** [comment]
I gave mml-attach-file a try, and indeed it works. It's fine because I have the file available locally, but otherwise for a remote operation (computer A pushes draft on IMAP, computer B retrieves the draft with the attachment) it would not.
