### ISSUE TITLE
[mu4e bug] Issue with responding to calendar invites and exporting them to org

### ISSUE THREAD

**Issue by martinarielhartmann** [djcb/mu#2789]
Hi,

I haven't tried the "`emacs -Q`" approach yet, but I want to mention a problem that I get all the time with 1.12.7-st. Let's say I get a calendar invite (anonymized):

```
1.  ( ) text/plain          ( ) text/html           (*) text/calendar       

[ Accept ]    [ Tentative ]    [ Decline ]    

[ Show Agenda ]    [ Export to Org ]    

Summary:    Teacher Meeting
Location:   X
Time:       <2025-02-11 09:05-10:00 +1m>
Organizer:  X@X.X
Attendance: Required
Method:     REQUEST
Status:     Not replied yet
```

If I click Accept, Tentative, or Decline, it will store the information in my notes.org, but I'm sent to a mu4e:compose buffer that looks like this:

```
To: X@X.X
Subject: Re: [name of the meeting]
From: foo bar <my@email.X>
Date: Fri, 29 Nov 2024 09:44:16 +0200
Message-ID: <m1h67qwkkv.fsf@x.x.x>
--text follows this line--
<#multipart type=alternative>
<#part type="text/plain">
<#/part>
<#part type="text/calendar; method=REPLY; charset=UTF-8" buffer="*CAL*">
<#/part>
<#/multipart>

```
This e-mail doesn't seem to contain anything about my acceptance. 

Any help with this would be greatly appreciated. I have been enjoying mu4e for years, had to stop using it due to calendar invites, but now I would love to be back since it's soooooo fast and useful. BTW I don't speak elisp.

GNU Emacs 29.3 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.6 (Build 21G646)) of 2024-03-24
Macos 15.0 (24A335)

**Comment by martinarielhartmann** [comment]
This issue has also been reported here: https://github.com/djcb/mu/issues/2666#issuecomment-2058908982

**Comment by martinarielhartmann** [comment]
And I guess here as well: https://github.com/djcb/mu/issues/1729#issuecomment-1110888804

**Comment by djcb** [comment]
@Chris00: any idea?

**Comment by Chris00** [comment]
The acceptance (or not) is in the `*CAL*` buffer.

**Comment by Chris00** [comment]
Not sure to understand you question.  You are just supposed to send the mail and the distant system should read the `text/calendar` attachment and record your reply.

**Comment by martinarielhartmann** [comment]
It works perfectly in the latest mu4e! I tried in Exchange and Gmail. I'm not sure why it wasn't working before. My apologies. But I noticed that even if I decilne the meeting, it still adds something to my .org file:  

```
** other invite ()
CLOSED: [2024-12-04 Wed 22:02]
:PROPERTIES:
:ICAL_EVENT: t
:ID:       040000008200E00074C5B7101A82E00800000000916592738646DB01000000000000000010000000BC4F4233A590DA4190590FBFAD5923CB
:ORGANIZER: X@X.com
:LOCATION:
:PARTICIPATION_TYPE: required
:REQ_PARTICIPANTS: X.X@X.com
:OPT_PARTICIPANTS:
:RRULE:
:REPLY:    Declined
:END:

  <2024-12-05 08:00-08:30>
```

I'm using this config:
```
(setq mu4e-icalendar-diary-file "~/Dropbox/org/notes.org")
(setq gnus-icalendar-org-capture-file "~/Dropbox/org/notes.org")
(setq gnus-icalendar-org-capture-headline '("Calendar"))
(gnus-icalendar-org-setup)
```

**Comment by Chris00** [comment]
﻿On  4 December 2024 at 21:10 +01, martinarielhartmann ***@***.***> wrote:
> […] I noticed that even if I decilne the meeting, it
> still adds something to my .org file:

Yes, the idea is that you keep a trace of which invitations you responded to.  That said, one could define a variable to define which actions trigger a mention to cal/org files.

**Comment by djcb** [comment]
Thanks for your assistance, @Chris00!

Closing this, seems all is working as expected. Of course improvement PRs for documentation or further customization are welcom.
