### ISSUE TITLE
[mu4e bug] modeline does not consider `mu4e-search-skip-duplicates`

### ISSUE THREAD

**Issue by fuyu0425** [djcb/mu#2791]
**Describe the bug**
As title,
The query underline used to update modeling does not consider `mu4e-search-skip-duplicates`.

**How to Reproduce**

Favorite bookmark query with the duplicated messages.

The header view will show only one message because `mu4e-search-skip-duplicates` is set to `t`.

But the modeling will show `[2/2]` instead of `[1/1]`

**Root cause diagnosis**

`mu4e--server-queries` does not pass `:skip-dups` flag to the mu server (and mu server now cannot handle it though).

`Server::Private::queries_handler` use `count_query` which underlying uses `Query::count` cannot handle flags like `:skip-dups`

```
size_t
Query::count(const std::string& expr) const
{
  return xapian_try(
      [&] {
        const auto enq{priv_->make_enquire(expr, {}, {})};
        auto       mset{enq.get_mset(0, priv_->store_.size())};
        mset.fetch();
        return mset.size();
      },
      0);
}
```

**Possible resolution**
make `Query::count` accept `QueryFlags qflags` (although I think now only skip-dups will make final results different?) like `Query::run`

**Environment**

OS: macOS 13.6
mu version: 1.12.7
emacs version: 30.0.92

**Checklist**

- [x] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

BTW, here still uses obsolete variables `mu4e-headers-skip-duplicates`
https://github.com/djcb/mu/blob/1b2d9d3847ca879e92455d06b433a212506a16f8/mu4e/mu4e-search.el#L498
https://github.com/djcb/mu/blob/1b2d9d3847ca879e92455d06b433a212506a16f8/mu4e/mu4e-server.el#L595

**Comment by djcb** [comment]
This works as is currently expected, as per the mu4e manual/FAQ:
```For speed reasons, the counts do not exclude messages that no longer exist in
the file-system, nor does it exclude duplicate messages```

Don't plan on changing this, but I'll add another note to the manual to make this more obvious.
