### ISSUE TITLE
[mu bug] `mu init` prints a mismatched maildir if `~` is used

### ISSUE THREAD

**Issue by xuhdev** [djcb/mu#2793]
**Describe the bug**

Give the bug a good title.

Please provide a clear and concise description of what you expected to happen
and what actually happened, and follow the steps below.

**How to Reproduce**

Include the exact steps of what you were doing (commands executed etc.). Include
any relevant logs and outputs.

Does the problem happen each time? Sometimes?

If this is about a specific (kind of) message, please attach an example message
(anonymized as needed)

**Environment**
Debian Trixie, mu 1.12.7.

**Checklist**
- [x] you are running either the latest 1.10.x/1.12.x release or `master` (otherwise, please upgrade).

After running `mu init --maildir=~/a`, I got this table printed:

```
mu has been created with the following properties:
+-------------------+-----------------------------+
| property          | value                       |
+-------------------+-----------------------------+
| maildir           | /home/hong/~/a              |
+-------------------+-----------------------------+
```

Note the value includes the `~` itself.

**Comment by djcb** [comment]
Ah, yeah, bash & friends... I'll push a fix.
