### ISSUE TITLE
[mu4e bug] Saved draft, if synced to the server, is not deleted after sent

### ISSUE THREAD

**Issue by xuhdev** [djcb/mu#2796]
**Describe the bug**

If I save a draft with `C-x C-s`, then wait long enough such that a sync occurs (or manually do this outside Emacs), then sending the message won't delete the draft.

I'm aware of https://github.com/djcb/mu/issues/2719, but it doesn't seem to be the same issue.

**How to Reproduce**

1. Start mu4e.
2. Compose a new message. Fill the to, subject fields and a few words in the body. Use `C-x C-s` to save the message.
3. Stay in the compose buffer. Don't close it. Wait long enough until a Maildir sync occurs.
4. Send the message.
5. Force sync with the server.

Inspect the draft folder. The message is still there.

- If I modify Step 3 by closing the composing buffer, wait until a sync, and then edit the draft, this issue doesn't happen.

- If I modify Step 3 to not wait until a sync, this issue doesn't happen.

**Environment**

Debian Trixie, Emacs 30, mu/mu4e 1.12.7.

**Checklist**

- [x] you are running either an 1.10.x/1.12.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment]
I would recommend against syncing the draft folder; the draft messages are not even necessarily in a format other clients can handle (ie.,. some mime parts).

In any case, the sync changes things behind mu/mu4e's back, we cannot feasibly handle that.

**Comment by xuhdev** [comment]
If mu4e can't handle this situation, perhaps we can document this...

**Comment by djcb** [comment]
Yes, I had already  added a few notes to the manual. Thanks!
