### ISSUE TITLE
Can't verify signature on encrypted mail

### ISSUE THREAD

**Issue by pstch** [djcb/mu#280]
If I receive a mail that is encrypted AND signed with PGP/Mime, I can see the decrypted version without problems.

However, the signature does not appear anywhere. The signature seems to be combined with the encrypted version, and when I decrypt it using gpg, it gives a signature confirmation.

    ~ ❯ mu view me
    ...
    [No body found; message has encrypted parts]

mu view --decrypt works well, but does not show anything about the decryption process. 

Decrypting using gpg will work, and it will show signature verification directly after decryption.

I think this is bug.

I use 0.9.8.4-3+deb7u1, with libgmime2.6.

**Comment by cocreature** [comment]
So I finally spent a bit of time looking into this and I think I found the problem:

There are two ways to sign & encrypt messages using gpg/mime. One is the one you described where you first sign it and then encrypt it. I don't have any message here using that to verify it, but as you describe not having problems, I guess that works. The other way (see [rfc](https://tools.ietf.org/html/rfc3156#section-6.2)) is a combined mode which seems to be what my emacs and afaik enigmail by default as well are using. So I guess the latter is not taken into account.

I'm not very good with C so if anybody else wants to tackle this I would be very happy.

**Comment by zakkak** [comment]
OK, I see.

So how do we know it is a signed message after decrypting it? 
I can't find any hint in the headers you provide above (maybe it is dropped in the process).

If you find some more time to look into those specifications and provide more information, I can try to fix it.

**Comment by cocreature** [comment]
[g_mime_multipart_encrypted_decrypt](https://developer.gnome.org/gmime/stable/GMimeMultipartEncrypted.html#g-mime-multipart-encrypted-decrypt) has a third option that is a [GMimeDecryptResult](https://developer.gnome.org/gmime/stable/GMimeCryptoContext.html#GMimeDecryptResult). This contains a list of signatures found during decrypting. From a quick look (throwing a printf in mu_msg_crypto_decrypt_part) it looks like this is the correct thing to look at. Not quite sure how to best fit this into the current architecture.

**Comment by zakkak** [comment]
Could you please review https://github.com/zakkak/mu/commit/4efda2154da6af738779c27acce56396cd8a4d7a?w=1 .

I am using the decrypt result but I do not seem to get it working.  Any kind of help is welcomed.

**Comment by cocreature** [comment]
Thanks, I'll look into it when I have time. (Exams coming up, so it might take me a bit.)

**Comment by zakkak** [comment]
I managed to fix it. I created a new branch with squashed all the commits to make it cleaner.

FTR: the problem was at the check after decryption at https://github.com/zakkak/mu/commit/4efda2154da6af738779c27acce56396cd8a4d7a?w=1#diff-01b99e70e9bd30d5563dcb88944e7025R449. After decryption the subtype is no longer "pgp-encrypted".

**Comment by cocreature** [comment]
I am sure it's me doing something wrong but I can't get your change to work. `mu view --decrypt` doesn't show a signature, `mu verify` says no signature found and in mu4e it also doesn't seem to work.

**Comment by cocreature** [comment]
For mu4e I only changed mu4e-mu-binary, but I don't think your change targets anything else?

**Comment by zakkak** [comment]
Are you sure you checked out the correct branch? It is https://github.com/zakkak/mu/tree/fix_for_280

TBH I did not check the command line, only mu4e.

**Comment by cocreature** [comment]
You are right, it works for mails encrypted with emacs (just tested that myself). However I still have mails (afaik send from Thunderbird) where it doesn't work. Epa and gpg directly are however able to find signatures. Also a printf in the `if (sigs)` part you inserted gets triggered twice during `mu view --decrypt`.
The (censored as this is an actual mail) headers look like this
```
Date: 
From: 
User-Agent: Mozilla/5.0 (Windows NT 6.0; rv:31.0) Gecko/20100101 Thunderbird/31.3.0
MIME-Version: 1.0
To:
Subject: OS
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="FTh5V9GG8d4hWICjqABRx7Qtv2ApNldT6"
X-Provags-ID:  V03:K0:0fG4y9YhJdFe7OnmKveBBsivwHLZocebd4HGxQevRaX1man9gbF
 wnsIpj/RaeHcdl9P4btdgU8IO32F4EB11z35DUMR/ATubTkque1yJyTae52n/ltJfXdKQw7
 xNC7nirjl0AkUILUYKtm7NahW6CEzMZ+SfkiYgDpNIgI1V+FzyjUIsO4ELAY5KQxJ1QUvaH
 IwfkE25X4kTR0uI83EOfg==
X-UI-Out-Filterresults: notjunk:1;
X-TUID: 79C3yKV538Rk

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--FTh5V9GG8d4hWICjqABRx7Qtv2ApNldT6
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--FTh5V9GG8d4hWICjqABRx7Qtv2ApNldT6
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v1.4.13 (MingW32)
…
-----END PGP MESSAGE-----
```
and the decrypted one
```
Content-Type: multipart/mixed; boundary="LGdOq5xhDP5uhq4ardCgDu8oE2ETVCnra"

--LGdOq5xhDP5uhq4ardCgDu8oE2ETVCnra
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
--LGdOq5xhDP5uhq4ardCgDu8oE2ETVCnra--
```

**Comment by zakkak** [comment]
Could you (or a friend of yours) send me such an encrypted email, to work ok?

My gpg keyID is 03F04EA1

**Comment by cocreature** [comment]
done

**Comment by zakkak** [comment]
OK it was a problem with nesting not being able to trace back the signature report.

Now it seems OK here.
Can you please check https://github.com/zakkak/mu/tree/fix_for_280 ? (please `git pull --force` or perform a fresh `git clone`, since I recreated it)

**Comment by cocreature** [comment]
Working perfectly, thanks so much for fixing this!

**Comment by zakkak** [comment]
Nice, however I think I broke the verification for simply signed messages.  Can you reproduce this?

**Comment by cocreature** [comment]
Hehe, yep can reproduce.

**Comment by zakkak** [comment]
I think I fixed that as well. Please pull, test and report any defects here :)

**Comment by cocreature** [comment]
Seems to work just fine, thanks again.
