### ISSUE TITLE
[misc] Unable to subscribe to mu-discuss@

### ISSUE THREAD

**Issue by husainaloos** [djcb/mu#2800]
**Note**: for questions, please use the mailing-list: https://groups.google.com/g/mu-discuss

**Describe the issue**
I am unable to subscribe to mu-discuss@. Because of that, I am unable to post.

I do not have a gmail account. I simply send an email to mu-discuss+subscribe@googlegroups.com. I receive an email indicating that I can either click on a link provided or reply to it to confirm my subscription. 

- When I click on the link, it simply leads to https://groups.google.com/g/mu-discuss and it does not confirm my subscription.
- When I reply, I get a delivery failure notification indicating "Unexpected DFS AddMemberships membership status".

Hence, I cannot confirm my subscription.

Any help is appreciated.

**Environment**
N/a

**Comment by djcb** [comment]
IIRC you don't need to have a Gmail address, but you do need to have a Google Account.
https://support.google.com/groups/answer/1067205?hl=en

Does it work if you do create such an account?

**Comment by husainaloos** [comment]
This is not the ideal solution for me, but it should work for now.
