### ISSUE TITLE
Closing parenthesis included in hyperlink

### ISSUE THREAD

**Issue by cbilson** [djcb/mu#284]
Hi,

I love mu4e (thanks!), but I have a small issue that I'd like to find out about: I get a weekly email (from [here](http://www.clojuregazette.com/)) which includes a number of hyperlinks, each enclosed in parenthesis. The raw text looks like this:

``` txt
** E. W. Dijkstra Archive (http://www.cs.utexas.edu/~EWD/welcome.html)
------------------------------------------------------------
These memos written by Dijkstra are definitely worth a read. He would circulate them (photocopied, of course) back in the day. This is an archive of those that are still around. Many fine gems of thought and definitely a repository of insight into this amazing mind.
```

When it's fontified in mu4e-view mode, the closing parenthesis gets included in the hyperlink, so that the link ends up being: `http://www.cs.utexas.edu/~EWD/welcome.html)`

On a whim I removed the parenthesis at the end of the outer capture from the regular expression mu4e~view-url-regexp and I get the correct hyperlink:

``` lisp
;; (defconst mu4e~view-url-regexp
;;   "\\(\\(https?\\://\\|mailto:\\)[-+\[:alnum:\].?_$%/+&#@!*~,:;=/()]+\\)"
;;   "Regexp that matches http:/https:/mailto: URLs; match-string 1
;; will contain the matched URL, if any.")

(defconst mu4e~view-url-regexp
  "\\(\\(https?\\://\\|mailto:\\)[-+\[:alnum:\].?_$%/+&#@!*~,:;=/]+\\)"
  "Regexp that matches http:/https:/mailto: URLs; match-string 1
will contain the matched URL, if any.")
```

Are those final open and close parenthesis necessary? If not, is it safe to just remove them?

**Comment by mankoff** [comment]
Can someone advise what happened to `mu4e~view-url-regexp` ? I can only find 

https://github.com/djcb/mu/blob/191f0f478de9ff9fbc8677c019c092f0c16f2222/mu4e/mu4e-view.el#L443-L446

And would like to implement the fix suggested above by @cbilson.

**Comment by djcb** [comment]
There's `mu4e~view-beginning-of-url-regexp`, but the actual matching is done using emacs' `thing-at-point-bounds-of-url-at-point`. 

To match ambiguous cases, like `(http:://example.com/foo/)` you need some heuristic I suppose.
