### ISSUE TITLE
FR: add a method of applying actions to multiple messages

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#301]
This is a follow-up to the discussion on the Google Group: https://groups.google.com/forum/#!topic/mu-discuss/APAa4rADFB4

It would be really useful to send a whole batch of messages to a single action. The obvious example is when applying a series of patches to a tree. At the moment you can to select the action for an individual message but not for a whole set. To be useful it should probably pass the whole list of message to the function so it can apply some basic filtering/sorting to ensure things are applied in the right order.

I would envision a workflow in the headers view of: T->a->g (Thread, Action, apply Git patches).

**Comment by djcb** [comment]
Moves 10+ years old ticket to `IDEAS.org`. It would be nice still, but it's not very easy to implement.
