### ISSUE TITLE
mu4e: problems with update-window

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#303]
After 1fca0be45165e95265e8faa7cacae7f0f0eaf932, I observe the following behaviour:
- First update works fine.
- After the second update, the update window doesn't close automatically.
- When I run a third update, a second update-window is opened.
- Every further update opens a new update-window in addition to those that are already open.

When I close the update-window manually (`C-x 0`) and run update again, the update-window is opened with the old buffer from the previous update.  The update runs, but the window doesn't follow the output of the update process.

I get this message every time I start an update expect when I run it the first time:

```
mu4e-update-mail-and-index: Buffer is read-only: #<buffer *mu4e-update*>
```

**Comment by yurkobb** [comment]
Hm, recently started experiencing the same issue, with mu4e 1.0, emacs 26.1, exactly the behavior described.

**Comment by yurkobb** [comment]
Ah, and also after the calling `mu4e-update-mail-and-index` I have to call `mu4e-update-index` manually since the index is not updated.
