### ISSUE TITLE
Non consistent indexing between command line and mu4e, if maildir is under symlink.

### ISSUE THREAD

**Issue by MassimoLauria** [djcb/mu#324]
My file configuration is the following

/STORAGE/maildir
/STORAGE/mu-index

and in my home directory I have symlinks

~/maildir/ -->  /STORAGE/maildir
~/.mu/      --> /STORAGE/mu-index

I do this in order to save space in the home directory which is under quota.

When I index with the command 'mu index --maildir ~/maildir' the messages appear
(in mu4e-view) to be located in /STORAGE/maildir/<whathever>. 
Instead if index from emacs/mu4e the messages appear to be located in ~/maildir/<whathever>. 

My mu4e-maildir is set to (concat (getenv "HOME) "/maildir")

If I do indexing/update from both, then I get double messages everywhere, since mu4e believes that the two file system entry points to a message file are actually two distinct messages.

A workaround would be to hardcode in mu4e-maildir the actual path "/STORAGE/maildir", but I share the configuration on other computers where the maildir is actually in "~/maildir".

Does it depend on the shell executing 'mu index --maildir ~/maildir'? This happens both when the indexing command is launched by offlineimap, and when I launch it from the command line.

Best,

**Comment by djcb** [comment]
Obsoleted....
