### ISSUE TITLE
mu oddness on mac 10.9

### ISSUE THREAD

**Issue by sje30** [djcb/mu#332]
With today's git (installed using the mac 'brew' method), the Emacs interface works fine, but when I try something from the command line, I don't have much joy:

```
$ mu --version
mu (mail indexer/searcher) version 0.9.9.6pre2
$ mu find apple
database needs a rebuild; try 'mu index --rebuild'
mu: db version: wqP?, but we need 9.9; database rebuild is required (15)
```

After a rebuild, still doesn't work, although every time I call mu, the "db version" reported changes:

```
mu find apple
database needs a rebuild; try 'mu index --rebuild'
mu: db version: ??U?, but we need 9.9; database rebuild is required (15)
```

**Comment by danieroux** [comment]
@sje30 @djcb  I believe this bug can be closed because of https://github.com/Homebrew/homebrew/commit/3f91fb10150b5cb6f6f7495e90b7b1a80f5377a2

**Comment by djcb** [comment]
@danieroux: thanks!
