### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by ghost** [djcb/mu#346]
At least one unit test failed:

TEST: test-mu-store... (pid=76605)
  /mu-store/mu-store-new-destroy:                                      test-mu-store(76605) malloc: *** error for object 0x7fff75121860: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
FAIL
GTester: last random seed: R02S7e3da0dff3e21cbdf14c4e1

This same failure happens at runtime when running mu from the command line:

mu(76684) malloc: *** error for object 0x7fff75121860: pointer being freed was not allocated

Here is the version of mu:
mu (mail indexer/searcher) version 0.9.9.6pre2

I am on a Macbook Pro with OS X Lion.

**Comment by djcb** [comment]
Is this still reproducible?
