### ISSUE TITLE
mu-verify man page: examples

### ISSUE THREAD

**Issue by jeroentbt** [djcb/mu#348]
This is what I get as examples in `man mu-verify`:

````
EXAMPLES
       To display aggregated (one-line) information about  the  signatures
       in a message:
          $ mu verify --verbose msgfile

       To display information about all the signatures:
          $ mu verify --verbose msgfile

       If you only want to use the exit code, you can use:
          $ mu verify --verbose msgfile
       which does not give any output.
````

They look all the same to me :)
Also output is the same with or without the `--verbose` option.

(mu version 0.9.9.5)

**Comment by epichub** [comment]
bump, verbose would be nice to debug verify functionality.

**Comment by djcb** [comment]
Fixed in master (and I would recommend updating to something newer than 0.9.9.5, which is getting rather old).
