### ISSUE TITLE
Docs: 6.5 Signing and encrypting: dead link

### ISSUE THREAD

**Issue by jeroentbt** [djcb/mu#349]
> Signing and encrypting of messages is possible using emacs-mime (see [Composing](http://www.djcbsoftware.nl/code/mu/emacs-mime/Composing.html#Composing)), most easily accessed through the `Attachments-menu` while composing a message, or with `M-x mml-secure-message-encrypt-pgp`, `M-x mml-secure-message-sign-pgp`.

Dead link behind "Composing". (on [this](http://www.djcbsoftware.nl/code/mu/mu4e/Signing-and-encrypting.html) page)

**Comment by djcb** [comment]
The link works when you read the documentation inside emacs, but the html-export does preserve the links to other docs... Not much I can easily do about that, rather than referring you to the embedded docs.
