### ISSUE TITLE
Duplicated names in TO-field in mu4e-view.

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#363]
When there are several people in the TO field, all but the first and last are listed twice:

    To: John Doe, Jane Doe Jane Doe, Peter Johnson

Note that there's no comma between `Doe` and `Jane`.  Also `Jane Doe Jane Doe` has only one overlay.

I checked in the raw message: no duplicated names there, so it is a display problem.

I'm using the development version of mu4e from a few days ago and GNU Emacs 24.3.50.1.

**Comment by djcb** [comment]
Okay -- this should be long fixed.

**Comment by tmalsburg** [comment]
Yes, it is.  Thank you!
