### ISSUE TITLE
How to create installable snapshots of mu4e?

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#370]
I've been spending some time trying to set-up auto testing of my .emacs to keep it semi-portable and prevent thinkos breaking on other platforms. One of the stumbling blocks has been my mu4e customisation as I tend to run the latest version straight out of the git repository. The version available to install on Travis VM is way out of date and currently due to the build process it's not possible to add mu4e to something like MELPA.

Would it be possible to set-up and autobuild of mu so a snapshot of the mu4e elisp could be imported via other mechanisms?

**Comment by djcb** [comment]
@stsquad: I have no experience with Travis; but it seems we'd need a travis.yml file for the mu-build. Would you be able to create one?

**Comment by stsquad** [comment]
@djcb I can have a go - they are fairly simple. I'll submit a pull request when ready.

**Comment by stsquad** [comment]
@djcb Actually I've just noticed I submitted one last year that's already there. The first step is to get your build enabled on travis-ci.org so it runs each time you update (go to travis-ci.org, login via github and you'll be able to flip a switch on their control panel).

Also it seems "make check" has regressed. This happens for me locally as well.

**Comment by djcb** [comment]
`make check' should pass... and the travis build is being done. Is anything else needed for this?

**Comment by stsquad** [comment]
Nope, all seems to be running fine:
  https://travis-ci.org/djcb/mu/builds

**Comment by stsquad** [comment]
Re-reading the actual title of the RFE we now we have Travis running we need to add a deployment phase. I'll look into it.

**Comment by djcb** [comment]
Any update on this?

**Comment by stsquad** [comment]
Probably the easiest/cheapest is to setup the GitHub releases:

    https://docs.travis-ci.com/user/deployment/releases

Unfortunately they only work for tagged releases which doesn't help the snapshot case.  I guess we need to look through:

    https://docs.travis-ci.com/user/deployment

For options that have free OSS hosting. Bintray maybe?

**Comment by A6GibKm** [comment]
I would like to add that the new `native-comp` branch of emacs requires either the elisp files available at compile time to generate `.eln` files for mu4e, or root permissions and manually run `cd /usr/local/share/emacs/site-lisp/mu4e/; sudo emacs -Q -batch -L . -f batch-native-compile *.el` for example. In my personal, albeit convoluted, setup I can't run `sudo emacs` as I run emacs inside a container.

This awkward procedure would be needed every time there is a change in the source `.el` files to avoid getting errors when running `mu4e`. This would be not be an issue if either `mu4e` lisp files were installed in the user's home or it was available in, say, melpa.

**Comment by djcb** [comment]
We do have the CI setup: https://github.com/djcb/mu/actions, and there are installable releases: https://github.com/djcb/mu/releases

For development-release, you'd really need to compile yourself, there's not much we can do.
