### ISSUE TITLE
Add the function mu4e-compose-reply-all

### ISSUE THREAD

**Issue by philc** [djcb/mu#373]
It would be helpful to have a single shortcut in headers mode for "reply all". mu4e doesn't expose this as a single function. If you invoke `mu4e-compose-reply-all`, a menu is shown and you must type another character to select "reply all".

Having it available as a single function makes it easy to bind, which is helpful for people migrating from Gmail, where Reply All is a single keystroke.

**Comment by incandescentman** [comment]
Agreed.

**Comment by sineer** [comment]
Please :+1:

**Comment by incandescentman** [comment]
This would be a super useful function to add.

**Comment by edumerco** [comment]
:+1: 

Maybe with r to reply and R to reply to all. 
Or r & a (mnemonic for "a"ll). :)

**Comment by gaydenko** [comment]
@edumerco , `r` is used for `refile` (that is to archive) already.

I don't understand so massive new +1s. On `R` we already get a choice to reply to sender (`s`) or to all (`a`) when appropriate.
