### ISSUE TITLE
mu not finding related message via message id

### ISSUE THREAD

**Issue by adamrt** [djcb/mu#380]
version: mu 9.9.5 stable installed via homebrew --with-emacs
osx mavericks

I'm unable to use the include related feature successfully. Anytime I use the feature I get no messages returned. Am I missing something. I didnt find anything special I needed to do during indexing. Here's the steps I'm taking. 

And thank you.

Rebuild index just to start fresh

```
%: mu index --rebuild
indexing messages under /Users/adam/Maildir [/Users/adam/.mu/xapian]
/ processing mail; processed: 4650; updated/new: 4650, cleaned-up: 0
cleaning up messages [/Users/adam/.mu/xapian]
| processing mail; processed: 4666; updated/new: 0, cleaned-up: 0
elapsed: 0 second(s)
/ processing mail; processed: 4666; updated/new: 0, cleaned-up: 0
elapsed: 14 second(s), ~ 333 msg/s
```

Search for both messages by messageid and find them

```
%: mu find -u i:m2sir7t8bm.fsf@mydomain.com
Tue Feb 25 09:23:41 2014 My Name <adam@mydomain.com> tests
%: mu find -u i:CACj_FnCdd2sxoWrMnQaFF9_jFTCqX4TeNP11A2WDOW_427oC2Q@mail.gmail.com
Tue Feb 25 09:23:55 2014 My Friend <myfriend@gmail.com> Re: tests
```

Search for both messages by message id and `include-related` and Dont find them

```
%: mu find -u -r i:m2sir7t8bm.fsf@mydomain.com
mu: no matches for search expression
%: mu find -u -r i:CACj_FnCdd2sxoWrMnQaFF9_jFTCqX4TeNP11A2WDOW_427oC2Q@mail.gmail.com
mu: no matches for search expression
```

Search for both messages by message id and `include-related` dont remove duplicates

```
%: mu find -r i:m2sir7t8bm.fsf@mydomain.com
mu: no matches for search expression
%: mu find -r i:CACj_FnCdd2sxoWrMnQaFF9_jFTCqX4TeNP11A2WDOW_427oC2Q@mail.gmail.com
mu: no matches for search expression
```

**Comment by danieroux** [comment]
For me, `CXXFLAGS='-std=c++11'` and the fix in  https://github.com/djcb/mu/commit/17dbee957a126e89b35e47f2cef342f6465234f0 sorted it out (finally).
