### ISSUE TITLE
mu4e-sent-messages-behavior & org-mu4e-compose-org-mode

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#392]
The option `(setq mu4e-sent-messages-behavior 'sent)` is ignored when composing with `org-mu4e-compose-org-mode`

**Comment by djcb** [comment]
`org-mu4e-compose-org-mode` has been deprecated for a while, we probably need something new. So closing this one.

**Comment by tobiasBora** [comment]
For people interested by this issue, there is a solution [here](https://matt.hackinghistory.ca/2016/11/18/sending-html-mail-with-mu4e/) (thank you very much for you great work !).

In a nutshell, just add this code to your .emacs:

```
;; https://matt.hackinghistory.ca/2016/11/18/sending-html-mail-with-mu4e/
;; this is stolen from John but it didn't work for me until I
;; made those changes to mu4e-compose.el
(defun htmlize-and-send ()
  "When in an org-mu4e-compose-org-mode message, htmlize and send it."
  (interactive)
  (when (member 'org~mu4e-mime-switch-headers-or-body post-command-hook)
    (org-mime-htmlize)
    (org-mu4e-compose-org-mode)
    (mu4e-compose-mode)
    (message-send-and-exit)))

;; This overloads the amazing C-c C-c commands in org-mode with one more function
;; namely the htmlize-and-send, above.
(add-hook 'org-ctrl-c-ctrl-c-hook 'htmlize-and-send t)

;; Originally, I set the `mu4e-compose-mode-hook' here, but
;; this new hook works much, much better for me.  
(add-hook 'mu4e-compose-post-hook
          (defun do-compose-stuff ()
            "My settings for message composition."
            (org-mu4e-compose-org-mode)))
```
Then once you began to compose a new mail, run `M-x org-mu4e-compose-org-mode`, type your email using `org-mode`, and send it, as usually, using `C-c C-c`. Enjoy!

**Comment by averter** [comment]
Thanks. Still working in mu4e v1.4.1
