### ISSUE TITLE
mu4e-headers-toggle-include-related causes "no matching messages found"

### ISSUE THREAD

**Issue by philc** [djcb/mu#397]
Toggling this option to true results in no messages being found when I open my inbox.

This was also referenced by a few people recently [in this thread](https://groups.google.com/forum/#!msg/mu-discuss/ZG0trF0reZk/4oumdIMvijoJ).

I have mu 0.9.9.6pre2 and Emacs 24.4 on OSX 10.9. Let me know if there's more diagnostic info I can provide.

**Comment by d12frosted** [comment]
I am on 0.9.11 and still happening.

**Comment by danieroux** [comment]
@d12frosted Which OS and how did you install it?

**Comment by djcb** [comment]
Is this still seen with 0.9.16?

**Comment by d12frosted** [comment]
I don't remember having this issue anymore.

**Comment by djcb** [comment]
Thanks, closing this.
