### ISSUE TITLE
Handle URLs enclosed in brackets correctly

### ISSUE THREAD

**Issue by jezcope** [djcb/mu#408]
When a message contains a URL enclosed in brackets, like so:

```...blah blah (http://github.com/) blah...```

as is commonly the case when `mu4e-html2text-command` converts HTML to Markdown, the closing bracket gets picked up as part of the URL, as does any other punctuation immediately following the bracket. This means that to actually visit the URL involves the sequence `g <number> <edit URL in browser location bar and try again>` instead of just `g <number>`.

**Comment by djcb** [comment]
This has been fixed as part of the URI parsing updates.
