### ISSUE TITLE
mu4e saves encrypted mails as plaintext into the drafts folder

### ISSUE THREAD

**Issue by attila-lendvai** [djcb/mu#425]
i have a pretty common gmail setup, and once i've seen a unencrypted mail in my gmail draft folder that contained the encrypt marker (because it was meant to be encrypted):

```
<#secure method=pgpmime mode=signencrypt>
```

i've briefly looked into google and the mu4e code, but it looks like it's not a misconfiguration on my part, just a feature waiting for implementation.

**Comment by zabbal** [comment]
I actually like this behavior - I use full disk encryption so I prefer things in plaintext unless they are transmitted outside. Although I agree that this should be clearly documented - a word of caution could not hurt.

**Comment by attila-lendvai** [comment]
FTR, i've reported this as an emacs bug: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=19585

**Comment by djcb** [comment]
Thanks -- we'll have to wait for that then, I suppose...
