### ISSUE TITLE
most recent address from mu cfind

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#426]
`mu cfind` man page says `In case the same e-mail address is used with different names, the most recent non-empty name is used.` I find it uses the oldest not most recent non-empty email. Most recent would be preferred.

**Comment by djcb** [comment]
Can you check `~/.mu/cache/contacts` (a text file that stores the contact cache) and paste the entries for the expected and actual contacts here? Feel free to redact the address for anonimity :-) Thanks.
