### ISSUE TITLE
Encoding error of the downloaded attachment's filename in mu4e

### ISSUE THREAD

**Issue by panjie** [djcb/mu#427]
- mu+mu4e running on cygwin(32bit)+ Windows7(ChineseVersion, 64bit)
- Mail's encoding(telling from the mod-line of message buffer)  is chinese-gbk-unix(not unicode)
- Attachment's filename seems OK in the message buffer
- When openning/downloading attachments, the filename goes  wrong(in Word/Exce or Explorer)

**Comment by djcb** [comment]
Hmmm, not sure if we can solve this in mu4e, seems an emacs / cygwin / windows encoding problem.
