### ISSUE TITLE
Segfault with gcc version 4.4.7 20120313 (Red Hat 4.4.7-3)

### ISSUE THREAD

**Issue by davidcsterratt** [djcb/mu#436]
`make check` now works (see #435), I can build an index, but `mu find` gives a segfault. This can be worked around by setting `CFLAGS="-fno-inline"`, like this:
```
CFLAGS="-fno-inline" ./configure
```
Running gdb showed that the segfault happened at the start of the for loop in  [output_plain()](https://github.com/djcb/mu/blob/d3122a8927c8cf8fcbdc2fc8ec9bab102cdb3176/mu/mu-cmd-find.c#LC463) .

**Comment by djcb** [comment]
Is this still reproducible? There have been a number of changes in this area.

**Comment by davidcsterratt** [comment]
This is no longer reproducible. I can now compile without setting `CFLAGS="-fno-inline"` and the example above doesn't give a segfault.

**Comment by djcb** [comment]
Thanks! I think the actual problem was some problematic use of C++ `std::string::c_str()`, which has been corrected.
