### ISSUE TITLE
No contacts when mu4e-compose-complete-only-personal is true

### ISSUE THREAD

**Issue by davidcsterratt** [djcb/mu#438]
With the latest master branch, I get no contacts when `mu4e-compose-complete-only-personal` is true. The problem seems to be the logic in [each_contact_sexp()](https://github.com/djcb/mu/blob/293282cf7671c3c42573f726ce777fe8f9cfaa45/mu/mu-cmd-server.c#LC552), which seems set up to return nothing at all if `personal` is true.

**Comment by djcb** [comment]
Old bug, but is this still seen with the current mu4e (the git version, in particular)?

**Comment by davidcsterratt** [comment]
Hmm... I've been using BBDB, so I've not tested this recently. However, I've tried removing my BBDB code temporarily and cleared the contacts cache. It seems that  `mu4e-compose-complete-only-personal` is working. However, I'm only finding that 4 contacts in total are added to the contact list - there should be 100s. I think this is a separate issue though.

**Comment by davidcsterratt** [comment]
Actually, I suspect the problem I've just noted isn't a problem; more addresses are appearing from messages as they come in, so I suspect the default behaviour is to add contacts only when messages arrive.

**Comment by djcb** [comment]
Thanks! The addresses are added when the mail is indexed - indeed, typically when it arrives, but could also happen e.g. when re-indexing your messages.

Okay, closing this now then. Finally!
