### ISSUE TITLE
FR: visual indication of update status and runtime

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#444]
It would be really useful to have an indication of the update status some where in mu4e (the main page or status bar) along with the time it's been running. The time this is most useful to me is Monday morning as typically there is a lot of mail to sync and when I go to my ML folder I'm confused as to why there are no emails there. When I hit [U]pdate it craps out because the update process is already running. To add to the confusion it seems my update can hang so it would be useful if there was a warning if the update has been running for some time without outputting anything to the process buffer.

**Comment by zabbal** [comment]
I think ideal place for such notification would be a speedbar.

**Comment by stardiviner** [comment]
How to show the new unread emails in the speedbar(or sr-speedbar) beside the maildir mailbox label?

**Comment by djcb** [comment]
You can watch the mail downloading process (in the buffer at the bottom). Perhaps you can pass some options to fetchmail/offlineimap/... to be more verbose. And there is the progress update for the indexing progress. 

If you update hangs.. that seems something to fix there.
