### ISSUE TITLE
Update date when sending

### ISSUE THREAD

**Issue by sbfnk** [djcb/mu#452]
Commit fdbc1d6f9a7f82f422809af2942264f9c6a061b4 adds a "Date" field in a new drafts header -- to me, this causes problems because a message being sent will now always have the time of first creation as its "Date" field. E.g., I start composing a message at 10:00, send it at 10:30, it'll show up in people's inboxes with 10:00 as timestamp. This gets worse if I create a draft and come back to it, e.g., the next day, because the email will be sent with a "Date" field of the previous day and could easily get lost in an inbox. Would it be a solution to update the date field upon sending (with some sort of hook?)?

**Comment by peterwvj** [comment]
Commit 9bd6556 doesn't ensure that the date is updated when the draft is sent. All this commit does is to add an option that allows you to include the date in the draft when it is created. If `mu4e-compose-auto-include-date` is set to `t`, I would still expect the date to be updated once the draft is sent.
