### ISSUE TITLE
Editing drafts doesn't work anymore.

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#453]
When I move point to a draft message and press `E`, I get the following error messages:

```
error in process filter: mu4e~guess-maildir: Wrong type argument: number-or-marker-p, nil
error in process filter: Wrong type argument: number-or-marker-p, nil
```

The message is not opened for editing.

I'm using the current git version of mu/mu4e and the current development version of Emacs.

**Comment by ptpt** [comment]
Pull request #610 can fix the problem.
