### ISSUE TITLE
Russian Doll Problem

### ISSUE THREAD

**Issue by wmzook** [djcb/mu#454]
Scenario: a message is received that contains a forwarded message as an rfc822 MIME attachment.  The forwarded message itself contains a MIME attachment.

Opening the forwarded message correctly displays the message in a buffer named _mu4e-embedded-view_ with it's attachment(s) listed.  However, attempts to open or save the inner attachment fail with the message "error in process filter: Error 3: unknown error".

**Comment by wmzook** [comment]
Still exists in 0.9.15.  Is there any chance of getting this fixed?

**Comment by djcb** [comment]
It's not really *expected* to work right now, and I suspect it requires changes both on the mu-server and mu4e side.

Can you attach a (raw) message that exposes this problem?

**Comment by wmzook** [comment]
Sure.  I hope this works.
[testMsg.txt](https://github.com/djcb/mu/files/93571/testMsg.txt)

**Comment by wmzook** [comment]
Sorry, didn't mean to hit the close button.

**Comment by Chris00** [comment]
It is neither possible to reply to the attached message.  This is a problem for mailing lists delivered as digest messages.

**Comment by Chris00** [comment]
Here is a message displaying the problem.
[cairo.txt](https://github.com/djcb/mu/files/295573/cairo.txt)

**Comment by Ambrevar** [comment]
Any update on this?

**Comment by djcb** [comment]
Okay, this works now with the new (experimental) view mode -- `(setq mu4e-view-use-gnus t)`. Finally!
