### ISSUE TITLE
mu find fails for messages with utf and numbers in subject

### ISSUE THREAD

**Issue by glogiotatidis** [djcb/mu#465]
Given two messages with subjects

 1. `κουμπαράς` 
   - raw email header `Subject: =?utf-8?B?zrrOv8+FzrzPgM6xz4HOrM+C?=`
 2.  `κουμπαράς 2014`
   - raw email header `Subject: =?utf-8?B?zrrOv8+FzrzPgM6xz4HOrM+C?= 2015`

mu indexes both but when I search for `κουμπαράς` only the first one gets returned.

**Comment by djcb** [comment]
Sadly, this is not really solvable with Xapian query parser :/, which does some magic with some of the punctuation characters...

**Comment by glogiotatidis** [comment]
:| Thanks for the update.
