### ISSUE TITLE
mu4e locks up emacs 24.3 with compose and flyspell turned on

### ISSUE THREAD

**Issue by timotheosh** [djcb/mu#467]
As the subject suggests, here is how to repeat it. (I have repeated this on Ubuntu 14.04, CentOS 7, and NixOS 14.04).
emacs version 24.3
mu versions 0.9.9.5 and 0.9.9.6
latest flyspell  from melpa
using aspell

How to repeat:

Start emacs
Start mu4e within emacs
Compose a new message
go to the message body and type "the 4th" without quotes.
Emacs is now locked solid, tacking the CPU at 100%

Flyspell does not do this in org-mode, or regular text mode, only under mu4e:compose

I discovered this bug while trying to compose multiple emails wishing people in my contacts list a happy 4th of July this year. I had to compose my messages in webmail.

**Comment by vlevit** [comment]
I found that this flyspell enters an infinite loop only if we apply text property `intangible` for `mail-header-separator` (in `mu4e~draft-insert-mail-header-separator`). This first possible workaround would be to avoid applying this property. Another one is to inhibit the use of `intangible` property.

    (setq inhibit-point-motion-hooks t)

Yet another one is to tell flyspell to use only the algorithm for large regions.

    (setq flyspell-large-region 0)

There was a [long discussion][1] on similar bug in flyspell back in 2006 on Emacs mailing list and there was even a [mention][2] of that `intangible` is a misfeature causing problems.

[1]: https://lists.gnu.org/archive/html/emacs-devel/2006-10/threads.html#00328
[2]: https://lists.gnu.org/archive/html/emacs-devel/2006-10/msg00494.html

**Comment by vlevit** [comment]
This flyspell bug is fixed in pretest of Emacs 25.1.

**Comment by djcb** [comment]
On Tuesday Mar 01 2016, Vyacheslav Levit wrote:

> I found that this flyspell enters an infinite loop only if we apply
> text property `intangible` for `mail-header-separator` (in
> `mu4e~draft-insert-mail-header-separator`). This first possible
> workaround would be to avoid applying this property. Another one is to
> inhibit the use of `intangible` property.
>
>     (setq inhibit-point-motion-hooks t)
>
> Yet another one is to tell flyspell to use only the algorithm for
> large regions.
>
>     (setq flyspell-large-region 0)
>
> There was a [long discussion][1] on similar bug in flyspell back in
> 2006 on Emacs mailing list and there was even a [mention][2] of that
> `intangible` is a misfeature causing problems.
>
> [1]: https://lists.gnu.org/archive/html/emacs-devel/2006-10/threads.html#00328
> [2]: https://lists.gnu.org/archive/html/emacs-devel/2006-10/msg00494.html

This seems like a bug in flyspell and/or emacs... I'm afraid we can't do
much about it in mu4e. If you have some reproducible case, please file a
bug there, as it seems a serious problem -- thanks!
