### ISSUE TITLE
mu: db version: 9.9, but we need 9.9; database rebuild is required (15)

### ISSUE THREAD

**Issue by derekschrock** [djcb/mu#469]
On FreeBSD 10.0p7 amd64 with mail/mu installed after creating an index of a Mail-dir directory and trying to run 'mu find test' I get the following error message:

```
$ mu find test
database needs a rebuild; try 'mu index --rebuild'
mu: db version: 9.9, but we need 9.9; database rebuild is required (15)
```

Rerunning index and rerunning find I get the same message.

mail/mu mu 0.9.9.6
databases/xapian-core  1.2.18,1

**Comment by ReneFroger** [comment]
I have the same issue.
I get the error:

    database needs a rebuild; try 'mu index --rebuild'
    mu: db version: 9.9, but we need 9.9; database rebuild is required

After rebuilding the index, I try it again and then I still get the same error message.
