### ISSUE TITLE
mark unread email, open email, mark lost

### ISSUE THREAD

**Issue by rekado** [djcb/mu#474]
I often delete unread emails.  In the headers view I mark them for deletion (`D`).  Sometimes I move up the email list again and accidentally open one of these emails.  At this moment the deletion mark is lost as the unread flag is removed.

**Comment by Chris00** [comment]
This is not the only situation where marks are lost.  Here is another one.  Mark the message for, say, deletion (moving to trash).  Then reply to it and send the reply.  The mark is then removed.

**Comment by djcb** [comment]
Good news, somewhere between 2014 and now this got fixed.
