### ISSUE TITLE
emails with org-mode, mm-insert-file-contents can't find LaTeX temp files

### ISSUE THREAD

**Issue by gambhiro** [djcb/mu#479]
I'm trying to reproduce this awesome email from [this blog post](http://www.brool.com/index.php/using-mu4e) for the fun of it. Emacs, mu4e, org-mode Rich-text HTML email.

He sends an email from Emacs with mu4e, with LaTeX formulas and R plots, relying on org-mode to export the message to HTML and shell out rendering the images.

The org-mode HTML conversion works, if I have the cursor in the header and press `C-c C-c`, it converts the org format and sends a HTML message.

But when I try to include the LaTeX formulas, the rendered LaTeX .png fragments are removed before mu4e sends the email, and so aborts saying:

    mm-insert-file-contents: Opening input file: no such file or directory, /tmp/ltxpng/...png

How can I delay removing the temporary files, until mu4e finishes sending the email?

**Comment by djcb** [comment]
Sorry, can't help you with that -- better ask the blog post author. Seems that post has gone...

**Comment by gambhiro** [comment]
No worries, I enjoy using mu4e without R plots too :)
