### ISSUE TITLE
Sent items are not sync'ed by offlineimap

### ISSUE THREAD

**Issue by sanderboer** [djcb/mu#508]
Hi,

I've sent some emails with mu4e using msmtp. emails arrive, copies in ofllineimap's Sent folder, all is grand.

But when I check the Sent folder on the mail server, no dice.
A quick look reveals a strange naming difference:
Mail created by courier imap look like:
```
1414613165.M579368P32122V0000000000000900I0000000001E600B4_0.zorn,S=819:2,S
```
But a mail created by mu4e looks like:
```
20141029-9ffdc9-sun-ra:2,S
```
That looks a lot shorter.
Offlineimap does not register an error which leads me to believe there may be an issue with the naming convention here, a setting perhaps, pebkac ?

kind regards,
Sander

**Comment by sanderboer** [comment]
You're right, it turns out it is related to offlineimap's "maxage" directive. Apparently, when maxage is set (at anything, I had it at 365), these messages get overlooked. When maxage is not set, all is synced.

**Comment by sanderboer** [comment]
Alas, the offlineimap people responded that the filename convention used by mu4e is not standard, it uses a date  as opposed to the unix timestamp breaking the maxage directive:

Janna Martl wrote:
Hi,

On Wed, Aug 26, 2015 at 10:32:30PM +0200, Nicolas Sebrecht wrote:
>
> CC'in Janna. ,-)
>
> On Wed, Aug 26, 2015 at 08:11:05AM +0200, Sander Boer wrote:
>> Mail created by courier imap look like:
>>
>> 1414613165.M579368P32122V0000000000000900I0000000001E600B4_0.zorn,S=819:2,S
>>
>> But a mail created by mu4e looks like:
>>
>> 20141029-9ffdc9-sun-ra:2,S

Maxage determines the date of a local message by parsing the filename;
in particular, the time is the first string of numbers at the beginning
of the filename, and is assumed to be a unix timestamp. This is
consistent with the maildir spec[0] and is not behavior I changed when
messing with this feature. So you're right, the timestamp format in the
filename is causing offlineimap to ignore these messages (since it
thinks they're 20141029 seconds-since-the-epoch old!).

Not sure what the mu4e folks told you at the time, but you could try
asking them to change the filename format.

-- J.M.

[0] http://cr.yp.to/proto/maildir.html

**Comment by djcb** [comment]
[0] states that: "Unless you're writing messages to a maildir, the format of a unique name is none of your business. A unique name can be anything that doesn't contain a colon (or slash) and doesn't start with a dot. Do not try to extract information from unique names."

So it seems maxage tries to determine the timestamp by parsing the name, even if it shouldn't. Better use the mtime of the file -- which is a better judge of whether a file needs to be synchronized anyway.
I read the rest of the doc as some advice on how to create sufficiently unique names; mu4e doesn't follow that advice to the letter, e.g we start with an ISO-8601 date, which are a bit easier to read for humans. 

Now, obviously you're not helped much by offlineimap <=> mu4e passing blame around... so I have the changed the format a bit (in git), so they start with a unix timestamp followed by a dot.
