### ISSUE TITLE
Sending emails with attached PDFs doesn't work when openwith is used to configure an external viewer for PDFs. 

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#510]
I prefer to use an external viewer for opening PDFs and used openwith.el to configure Emacs to do that.  Now I can't send emails with attached PDFs.  Instead of sending the email, `C-c C-c` opens the attached PDF in an external viewer and the message isn't sent. No error message in _Messages_.  I filed an [issue for openwith](https://bitbucket.org/jpkotta/openwith/issue/1/openwith-breaks-sending-emails-with-pdf) but the author suggests that the problem might rather be in mu4e.

**Comment by thisirs** [comment]
Use

    (add-to-list 'mm-inhibit-file-name-handlers 'openwith-file-handler)

**Comment by a-schaefers** [comment]
I ran into this (not using mu), but simply using gnus + openwith-mode enabled. Fixed it simply using @thisirs method above.
