### ISSUE TITLE
feature request: pausing updating while inbox is open

### ISSUE THREAD

**Issue by seanfarley** [djcb/mu#514]
This is a minor annoyance that when reading email emacs 'hangs' (due to, I'm guessing, emacs being single threaded) when the mu index is being rebuilt. Perhaps there could be a setting for not running update while in reading mode?

**Comment by djcb** [comment]
emacs is not really hanging, but it's waiting for the output from the mu process, which is waiting for the indexing to complete. Not easy to change, I'm afraid.
