### ISSUE TITLE
Is it possible to disable automatic "mark as read" when opening an email with mu4e?

### ISSUE THREAD

**Issue by halbtuerke** [djcb/mu#515]
Hi,

is it possible to disable automatically marking emails as read when viewing them in mu4e?
I already had a look at the customizations for mu4e but haven't found anything which looks promising. 

After that I had a look at the source code which pointed to `mu4e-headers-view-message ` in mu4e-headers.el which calls `mu4e~proc-view ` in mu4e-proc.el which in turn calls `mu4e~proc-send-command `. From this code journey I unfortunately was not able to understand where exactly the email will be marked as read.

Thanks in advance

**Comment by toothbrush** [comment]
Another reason you might want this: my work flow is perhaps broken too, but my "very old" email account has its Maildir marked read-only on the file system, meaning that in practice i cannot read such emails in mu. Mu tries to move the mail from `new` to `cur`, which breaks, but i don't want it to even try on certain folders.
