### ISSUE TITLE
Add `mu4e-headers-next-unread`

### ISSUE THREAD

**Issue by stefanv** [djcb/mu#516]
In Mutt, the TAB key jumps to the next unread message, and I think this would be a useful addition.

If someone would give me some pointers, I'd be happy to give it a try myself.

**Comment by stefanv** [comment]
Here's my attempt at a next thread function:

```elisp
(defun stefan/mu4e-next-thread ()
  (interactive)
  (mu4e-headers-find-if-next
   (lambda (msg)
     (let ((thread (mu4e-message-field msg :thread)))
        (or
         (eq 0 (plist-get thread :level))
         (plist-get thread :empty-parent))))))

(define-key 'mu4e-headers-mode-map (kbd "TAB") 'stefan/mu4e-next-thread)
```

**Comment by zakkak** [comment]
I have tested the above and works fine for me.

I would also like to comment that this issue should be closed since it has been fixed.  Maybe we should create a new issue for `mu4e-next-thread`.
