### ISSUE TITLE
Action for opening GitHub pull requests

### ISSUE THREAD

**Issue by stefanv** [djcb/mu#517]
I often get GitHub pull request notifications, so I wrote an action to open the PR url.  Not sure if this would be useful to anyone, but if so I'd be happy to submit a PR:

```elisp
(defun stefan/mu4e-action-view-pull-request (msg)
  "Locate a GitHub pull request URL and open in the browser.
The browser used is specified in `browse-url-generic-program'."
  (let* ((txt (mu4e-message-field msg :body-txt))
         (pr-re "^https://github.com/.*[[:digit:]]+$"))
    (unless txt
      (mu4e-error "No text part for this message"))

    (set-match-data nil)

    (while (and
            ;; search for the next url, starting from the position of
            ;; the last one found
            (string-match mu4e-view-url-regexp txt (match-end 0))
            ;; we use save-match-data to protect the last search
            ;; position, which is needed for the string-match call
            ;; above
            ;;
            ;; abort the loop if a matching url is found
            (save-match-data
              (not (string-match pr-re (match-string 0 txt))))))

    (let ((url (match-string 0 txt)))
      (if (string-match pr-re url)
          (browse-url url)
        (mu4e-error "No pull request URL found")))))
```

Install using:

```
(add-to-list 'mu4e-view-actions
   '("pull request" . mu4e-action-view-pull-request) t)
```

**Comment by stefanv** [comment]
@djcb Recently, the internal structure for matching URLs while viewing changed.  The public ``mu4e-view-url-regexp`` disappeared.  As such, the above code no longer works.

**Comment by djcb** [comment]
Yes -- things were cleaned up a bit, so sadly that code no longer works. We now use the emacs built-in regexps for URIs. You can use `mu4e-view-for-each-uri` instead, which should allow for simplifying the action code.

**Comment by stefanv** [comment]
Perhaps we can add this to mu4e-actions as you mentioned earlier, so that it will be maintained with the project?  I see that nowadays gmail also provides a quick link to a URL, so that's at least proof of popularity!

**Comment by stefanv** [comment]
@djcb Any ideas about this?

**Comment by djcb** [comment]
@stefanv: right now it doesn't seem to add too much over mu4e's built-in jump-to-url functionality; but perhaps it could be the start of some more extensive github action.
