### ISSUE TITLE
No public variable to customize the sort direction nor sort field

### ISSUE THREAD

**Issue by seanfarley** [djcb/mu#526]
It seems commit f957a9ca89dc2dea320a9d6d14a0ddc08d2493eb dropped the public facing `mu4e-headers-sort-revert` variable. This makes it impossible to customize the sort direction or field without accessing `mu4e~headers-sort-direction`. It would be nice if there was an "official" way to do this with a `defvar`.

**Comment by djcb** [comment]
Both are back now (and have been for a while)
