### ISSUE TITLE
error in msgs-count script  

### ISSUE THREAD

**Issue by che2** [djcb/mu#533]
I get the same problem on both the head of master and 0.9.9.6 when running the msgs-count script:

$ mu msgs-count
Backtrace:
In ice-9/boot-9.scm:
 157: 7 [catch #t #<catch-closure f653e0> ...]
In unknown file:
   ?: 6 [apply-smob/1 #<catch-closure f653e0>]
In ice-9/boot-9.scm:
  63: 5 [call-with-prompt prompt0 ...]
In ice-9/eval.scm:
 432: 4 [eval # #]
In unknown file:
   ?: 3 [call-with-input-string "(main '(\"msgs-count\" \"--muhome=/home/che/.mu\" ))" ...]
In ice-9/command-line.scm:
 180: 2 [#<procedure f7dd40 at ice-9/command-line.scm:175:6 (port)> #<input: string d43270>]
In unknown file:
   ?: 1 [eval (main (quote #)) #<directory (guile-user) f59c60>]
In /home/che/local/share/mu/scripts//msgs-count.scm:
  29: 0 [count "" #f]

/home/che/local/share/mu/scripts//msgs-count.scm:29:0: In procedure count:
/home/che/local/share/mu/scripts//msgs-count.scm:29:0: Wrong number of arguments to #<procedure count (expr)>

Other scripts work fine.

**Comment by hexmode** [comment]
this should be closed
