### ISSUE TITLE
Headers view: pressing n causes line number showing up, all headers shift

### ISSUE THREAD

**Issue by xuhdev** [djcb/mu#536]
When pressing n in headers view, the line number on the left shows up, which pushes all messages to the right, thus they are not aligned with the header titles.

Here is the problem:

- If linenum should be disabled, why does it show up after pressing `n`?
- If linenum should not be disabled (which can be useful to show the number of messages), headers are displaced.

**Comment by djcb** [comment]
Is this still happening? If it does, can you try 'C-h k n' while in the headers view?
