### ISSUE TITLE
bad multipart mail display

### ISSUE THREAD

**Issue by xmaillard** [djcb/mu#538]
Here is message I have recently received. It is just not displaying correctly and is nearby unreadable.

Is there anything I have done incorrectly ?

Regards

Return-Path: <virginie.greniernrc@laposte.net>
Received: from compute1.internal (compute1.nyi.internal [10.202.2.41])
	 by sloti32d2t06 (Cyrus git2.5+0-git-fastmail-9890) with LMTPA;
	 Tue, 09 Dec 2014 07:18:30 -0500
X-Sieve: CMU Sieve 2.4
X-Spam-known-sender: yes
X-Spam-score: 0.0
X-Spam-hits: BAYES_00 -1.9, FREEMAIL_FROM 0.001, HTML_MESSAGE 0.001,
  RCVD_IN_DNSWL_LOW -0.7, SPF_PASS -0.001, T_RP_MATCHES_RCVD -0.01,
  LANGUAGES fr, BAYES_USED global, SA_VERSION 3.3.2
X-Spam-source: IP='194.117.213.173', Host='smtpoutz12.laposte.net', Country='FR',
  FromHeader='net', MailFrom='net', XOriginatingCountry='FR'
X-Spam-charsets: subject='utf-8', plain='utf-8', html='utf-8'
X-Resolved-to: xavier@maillard.im
X-Delivered-to: xavier@maillard.im
X-Mail-from: virginie.greniernrc@laposte.net
Received: from mx3 ([10.202.2.202])
  by compute1.internal (LMTPProxy); Tue, 09 Dec 2014 07:18:30 -0500
Received: from smtp.laposte.net (smtpoutz12.laposte.net [194.117.213.173])
	(using TLSv1.1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by mx3.messagingengine.com (Postfix) with ESMTPS id 4E1FCC0074
	for <xavier@maillard.im>; Tue,  9 Dec 2014 07:18:19 -0500 (EST)
Received: from smtp.laposte.net (localhost [127.0.0.1])
	by lpn-prd-vrout002 (Postfix) with ESMTP id 4C4244C007C4
	for <xavier@maillard.im>; Tue,  9 Dec 2014 13:18:17 +0100 (CET)
Received: from smtp.laposte.net (localhost [127.0.0.1])
	by lpn-prd-vrout002 (Postfix) with ESMTP id 122934C012EE
	for <xavier@maillard.im>; Tue,  9 Dec 2014 13:18:17 +0100 (CET)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=laposte.net; s=mail1;
	t=1418127497; bh=SY8pEAxLMIMomnaHd539BZ3uBVlAabiWVyOf51xGFCc=;
	h=Date:From:To:Cc:In-Reply-To:References:Subject;
	b=jwMi80oBlHar5Mh2pzXP64XNVl94fojF0edz+hbTtA8JTRmxIdGna8Q5AehZZj5Pz
	 iG3tptlDNa+NLSZkPOyRAPum5wcjALWWiCMg/LHHu3B9MtsNpESP/ErR2yqP+aVMLJ
	 QfZt9X8Cea8yYzXI+r+O6QCXy6lm1vjGb5LUFsdzTlsuPZoLLWCwRaeHCSZK/xczML
	 qF7+FYH/plGmCV6LXe9qclmQe+lekDAno6sOzIvtpz7X8Iex4SNvyi+e4A2xPHKxAg
	 3F/IiZmSgs+Q7hrGIZTxtt8hIT+quby3KyDtK8xEjMy/kbdX7FBcQ+zQbUf+QudDO0
	 j0t4VzGaRnc1A==
Received: from lpn-prd-mstr028.laposte (lpn-prd-mstr028.laposte [10.128.59.29])
	by lpn-prd-vrout002 (Postfix) with ESMTP id E4BC44C012D1;
	Tue,  9 Dec 2014 13:18:16 +0100 (CET)
Date: Tue, 9 Dec 2014 13:18:16 +0100 (CET)
From: virginie.greniernrc@laposte.net
To: emeline marguerie <bebechou51@hotmail.fr>
Cc: Xavier Maillard <xavier@maillard.im>, Stacie JAN <ps.jan51@gmail.com>, 
	poncet virginie <virginieponcetmathieu@gmail.com>, 
	Emilie <mimizou51@yahoo.fr>, lrprieur@orange.fr
Message-ID: <317220786.10379276.1418127496655.JavaMail.zimbra@laposte.net>
In-Reply-To: <DUB128-W3AA1697F467709AA15D4DAF700@phx.gbl>
References: <CAFMf+XayM0+E-TCzVuTVPMA3Qh7g1=+9eqUf2qfpfuwfpxO7wA@mail.gmail.com> <m0k32ikj15.fsf@kcals.intra.maillard.im> <DUB128-W3AA1697F467709AA15D4DAF700@phx.gbl>
Subject: =?utf-8?Q?Re=C2=A0:_RE:_Re_:_RE:_PETITION?=
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_10379275_596464026.1418127496655"
X-Originating-IP: [109.219.160.194]
X-Mailer: Zimbra 8.0.6_GA_5922 (zclient/8.0.6_GA_5922)
Thread-Topic: =?utf-8?B?UmXCoDo=?= RE: Re : RE: PETITION
Thread-Index: M0bWvJ8m+ZtMWL/VjAdhim7sUepJ5Q==
X-VR-FullState: 0
X-VR-Score: -100
X-VR-Cause-1: gggruggvucftvghtrhhoucdtuddrfeejiedrfeejgddtudcutefuodetggdotefrucfrrhhofhhilhgv
X-VR-Cause-2: mecunfetrffquffvgfenuceurghilhhouhhtmecuhedttdenucesvcftvggtihhpihgvnhhtshculddq
X-VR-Cause-3: uddttddmnecujfgurhepfffhvffkjghfufggtghiofhtsegrtdersgertdejnecuhfhrohhmpehvihhr
X-VR-Cause-4: ghhinhhivgdrghhrvghnihgvrhhnrhgtsehlrghpohhsthgvrdhnvght
X-VR-AvState: No
X-VR-State: 0

------=_Part_10379275_596464026.1418127496655
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

Bonjour a tous,

Mme Lache m'a donn&eacute; un courrier de la mairie, UN repr&eacute;sentant de parent d'&eacute;l&egrave;ve est invit&eacute; &agrave; la r&eacute;union qui se d&eacute;roulera le 17 d&eacute;cembre a 16h salle des assembl&eacute;es de l'h&ocirc;tel de ville. Une tr&egrave;s bonne nouvelle mais qui peu y aller?

Bonne apres midi

Virginie

----- Mail d'origine -----De: emeline marguerie <bebechou51@hotmail.fr>&Agrave;: Xavier Maillard <xavier@maillard.im>, Stacie JAN <ps.jan51@gmail.com>Cc: Virginie GRENIER <virginie.greniernrc@laposte.net>, poncet virginie <virginieponcetmathieu@gmail.com>, Emilie <mimizou51@yahoo.fr>, lrprieur@orange.frEnvoy&eacute;: Wed, 26 Nov 2014 14:17:46 +0100 (CET)Objet: RE: Re : RE: PETITION

Coucou vous tous, Pendant la manifestation je serais bien &eacute;videmment pr&eacute;sente mais si des photos sont prises ou interview donn&eacute; je vous laisserai la parole ou le premier plan je ne peux malheureusement pas trop me montrer m&ecirc;me si cela a lieu en dehors des heures de mon arr&ecirc;t maladie.  Si je parle ce sera au nom des parents d'&eacute;l&egrave;ves et pas mon nom &eacute;videmment j'esp&egrave;re que cela vous convient ? Sinon tout est charg&eacute; dans la voiture en attente de 16h 
> From: xavier@maillard.im> To: ps.jan51@gmail.com> CC: virginie.greniernrc@laposte.net; virginieponcetmathieu@gmail.com; bebechou51@hotmail.fr; mimizou51@yahoo.fr; lrprieur@orange.fr> Subject: Re: Re : RE: PETITION> Date: Tue, 25 Nov 2014 23:33:10 +0100> > Je me demande si cela ne s'apparente pas a de l'entrave cette histoire.> > Cdt> Xavier

------=_Part_10379275_596464026.1418127496655
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<div>Bonjour a tous,</div>
<div></div>
<div>Mme Lache m'a donn&eacute; un courrier de la mairie, UN repr&eacute;sentant de parent d'&eacute;l&egrave;ve est invit&eacute; &agrave; la r&eacute;union qui se d&eacute;roulera le 17 d&eacute;cembre a 16h salle des assembl&eacute;es de l'h&ocirc;tel de ville. Une tr&egrave;s bonne nouvelle mais qui peu y aller?</div>
<div></div>
<div>Bonne apres midi</div>
<div></div>
<div>Virginie</div>
<div></div>
<div>----- Mail d'origine -----<br />De: emeline marguerie &lt;bebechou51@hotmail.fr&gt;<br />&Agrave;: Xavier Maillard &lt;xavier@maillard.im&gt;, Stacie JAN &lt;ps.jan51@gmail.com&gt;<br />Cc: Virginie GRENIER &lt;virginie.greniernrc@laposte.net&gt;, poncet virginie &lt;virginieponcetmathieu@gmail.com&gt;, Emilie &lt;mimizou51@yahoo.fr&gt;, lrprieur@orange.fr<br />Envoy&eacute;: Wed, 26 Nov 2014 14:17:46 +0100 (CET)<br />Objet: RE: Re : RE: PETITION</div>
<div></div>
<div dir="ltr">Coucou vous tous,<br />&nbsp;<br />Pendant la manifestation je serais bien &eacute;videmment pr&eacute;sente mais si des photos sont prises ou interview donn&eacute; je vous laisserai la parole ou le premier plan je ne peux malheureusement pas trop me montrer m&ecirc;me si cela a lieu en dehors des heures de mon arr&ecirc;t maladie.&nbsp; Si je parle ce sera au nom des parents d'&eacute;l&egrave;ves et pas mon nom &eacute;videmment j'esp&egrave;re que cela vous convient ?<br />&nbsp;<br />Sinon tout est charg&eacute; dans la voiture en attente de 16h<br />&nbsp;<br />
<div>&gt; From: xavier@maillard.im<br />&gt; To: ps.jan51@gmail.com<br />&gt; CC: virginie.greniernrc@laposte.net; virginieponcetmathieu@gmail.com; bebechou51@hotmail.fr; mimizou51@yahoo.fr; lrprieur@orange.fr<br />&gt; Subject: Re: Re : RE: PETITION<br />&gt; Date: Tue, 25 Nov 2014 23:33:10 +0100<br />&gt; <br />&gt; Je me demande si cela ne s'apparente pas a de l'entrave cette histoire.<br />&gt; <br />&gt; Cdt<br />&gt; Xavier</div>
</div>
<div></div>
------=_Part_10379275_596464026.1418127496655--

**Comment by djcb** [comment]
It seems the message itself is bit broken, so the mail parser can't handle it correctly. Don't mu/mu4e can do much about this.
