### ISSUE TITLE
Option for automatically reply-to-sender vs. reply-to-all

### ISSUE THREAD

**Issue by toothbrush** [djcb/mu#542]
Hey! Recent mutt convert here. I've been digging through the mu4e source code, but it seems like i cannot do what i want to do:

When pressing some key, say `R`, i want to automatically reply to the person in the `From:` field. When i press some other key, say `g`, i want to automatically reply-to-all. I don't so much like prompts, you see :)

In the meantime perhaps i will try and write a pull request, but i'm not sure that my ELisp-fu is powerful enough to do it The Right Way™.

Thanks for a great MUA!

**Comment by mallet** [comment]
Having the option to reply to the sender only or to all without the prompt would be very welcomed, indeed. @djcb did not want to give a quick access to the reply-to-all, but it does not have to be available by default. Just a function to bind in .emacs would do.

I find the current approach annoying: when you activate "mu4e-compose-dont-reply-to-self", sometimes you get a prompt, sometimes not, depending on whether you were the only receiver. In addition, like @toothbrush, I am not particularly keen on prompts, especially for such a basic operation as replying to a message.

**Comment by semente** [comment]
What a about a "reply to mailing list only" feature? Some email clients has this handy feature.

**Comment by cpaulik** [comment]
@semente This is possible by using the functions from https://groups.google.com/forum/#!topic/mu-discuss/9ZbUu0wGxU0 but I think it should be included in mu4e.

**Comment by semente** [comment]
thank you very much @cpaulik

**Comment by djcb** [comment]
It's a conscious decision, having been the victim of too much reply-to-all. So, you need to take the millisecond/1 keypress to make a decision. Perhaps it can be automated with a keyboard macro, but I'll leave it as it is in mu4e.
