### ISSUE TITLE
Finding CJK text is failed

### ISSUE THREAD

**Issue by YukiChiba** [djcb/mu#544]
I set an environment variable XAPIAN_CJK_NGRAM to 1 in order to handle Japanese text for finding messages.
http://xapian.org/docs/sourcedoc/html/namespaceCJK.html
http://trac.xapian.org/ticket/180

However, it is failed to find Japanese text when no filed is specified. The followings are examples of output for a message containing "手続き" in subject and body:
```
% mu find s:手続き date:today..now
2014年12月18日 14時40分12秒 Yuki Chiba <chiba@******> 手続き
2014年12月18日 14時40分12秒 Yuki Chiba <chiba@******> 手続き
```
```
% mu find 手続き date:today..now
mu: no matches for search expression (4)
```

I think this is related to this closed issue:
https://github.com/djcb/mu/issues/123

The issue above is closed because of no reply for a long time. This bug is still remained.

I highly appreciate if mu supports Japanese text for finding messages.
Thank you.

**Comment by YukiChiba** [comment]
I changed the title because this is not only related to Japanese but also Chinese.
I guess that Korean is influenced, too.

**Comment by declanqian** [comment]
+1. I am having problems finding mail with Chinese text.

**Comment by djcb** [comment]
Sadly, no much mu/mu4e can do about this.... perhaps ask the Xapian people?

**Comment by YukiChiba** [comment]
I think that this is not Xapian related issue,
because notmuch, which is another mail client using Xapian for indexing, can search Japanese words in messages when
the environment variable XAPIAN_CJK_NGRAM to 1.

@djcb Could you please re-open this issue?

**Comment by djcb** [comment]
@YukiChiba: oh, perhaps you can create a new one? And can you attach a raw email file with some body-text and a subject in Japanese,so we can test it? Thanks.

**Comment by djcb** [comment]
Oh actually, just reopened this one -- anyway, having an example message would be great.

**Comment by YukiChiba** [comment]
@djcb Thank you for reopening this issue.

The following is an example of message in Japanese:
```
Return-Path: <yuki.from.akita@gmail.com>
Received: from ldl-02 ([2001:df0:2ed:4271:5604:a6ff:fe17:f6cb])
        by smtp.gmail.com with ESMTPSA id r26sm22467237pfa.45.2015.12.10.22.30.53
        for <yuki.from.akita@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 10 Dec 2015 22:30:54 -0800 (PST)
User-agent: mu4e 0.9.15; emacs 24.5.1
From: Yuki Chiba <yuki.from.akita@gmail.com>
To: Yuki Chiba <yuki.from.akita@gmail.com>
Subject: =?utf-8?B?5ryi5a2X44KS5ZCr44KAbXU0ZeOBruODhuOCueODiOODoeODvA==?=
 =?utf-8?B?44Or?=
Date: Fri, 11 Dec 2015 15:30:43 +0900
Message-ID: <muzh9jp4hv0.fsf@gmail.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

これは漢字を含むテストメールです．
```

**Comment by YukiChiba** [comment]
The following query is succeeded to find:
```
% mu find s:漢字
2015年12月11日 15時30分43秒 Yuki Chiba <yuki.from.akita@gmail.com> 漢字を含むmu4eのテストメール
```

But, the following is failed even though "漢字" appears in the body:
```
% mu find 漢字 date:today  
mu: no matches for search expression (4)
```

**Comment by djcb** [comment]
Thanks, I tried this, and `mu find 漢字` seems to work just fine with that env variable.

`mu find 漢字 date:today` does not find anything because the message is not from today, e.g `mu find 漢字 date:20151211` works.

So closing, this once more.
