### ISSUE TITLE
mu4e-view-message-with-msgid shows completely empty *mu4e-view* for unread messages

### ISSUE THREAD

**Issue by IvanMalison** [djcb/mu#547]
This typically happens for very new messages. I have been careful to make sure that the index is updated before the call to `mu4e-view-message-with-msgid`, but I sort of still suspect that this is some type of timing issue.

I'm assuming that the index update operation is complete when output like
```
[mu4e] Indexing completed; processed 24471, updated 2, cleaned-up 0
```

The asynchronous nature of mu4e makes it sort of hard to figure out what is going on. Any ideas about what might be going on here would be appreciated.

**Comment by IvanMalison** [comment]
Cool. I'm happy to contribute a fix, but I'm not really sure which approach is best. It took me a second to recall what the issue was when I read my own exposition above, so let me reiterate what the problem is:

When `mu4e-view-message-with-msgid` is invoked on a message which is not displayed in the current headers buffer for an unread message, nothing is displayed because this function (actually `mu4e-view`) relies on a callback (is this the appropriate term here?) to update the view of the message from the background mu process when the message is unread. The relevant condition in `mu4e-view` is

```elisp
(or embedded (not (mu4e~view-mark-as-read msg)))
```

I think that the reason that it does this is because displaying it upfront would (incorrectly) display that the message is unread since this function marks the message as read. As mentioned previously, the reason that the update callback doesn't work is that there is a check that the message is present in the current headers buffer (in `mu4e~headers-update-handler`) that determines whether any action is taken at all:

```elisp
(with-current-buffer mu4e~headers-buffer
      (let* ((docid (mu4e-message-field msg :docid))
	     (initial-message-at-point (mu4e~headers-docid-at-point))
	     (initial-column (current-column))
	     (point (mu4e~headers-docid-pos docid)))
	(when point ;; is the message present in this list?
```

Which prevents the code that causes display from ever being called:

```elisp
;; if we we're actually viewing this message (in mu4e-view mode), we
	  ;; update it; that way, the flags can be updated, as well as the path
	  ;; (which is useful for viewing the raw message)
	  (let ((viewbuf (get-buffer mu4e~view-buffer-name)))
	    (when (and viewbuf (buffer-live-p viewbuf))
	      (with-current-buffer viewbuf
		(when (eq docid (plist-get mu4e~view-msg :docid))
		  (mu4e-view msg mu4e~headers-buffer)))))
```

I tried to move this block outside of the `(when point` condition, but I vaguely recall that that did not work.

What I'm doing right now is changing `mu4e-update` condtion for doing display to:

```elisp
(when (or (mu4e~view-mark-as-read msg) t)
```

which is almost definitely wrong.

It seems like there are some subtlties to `mu4e~headers-update-handler` that might make straightforward fix somewhat difficult (threading etc.).

I hope this all makes sense! Let me know if anything is unclear.

**Comment by IvanMalison** [comment]
@djcb Any chance you can take a look at this anytime soon? I'm mainly looking for an opinion about where this should be fixed. i.e. in `mu4e-view` or in `mu4e~headers-update-handler`. Or would it be appropriate to force a refresh of the headers view in `mu4e-view-message-with-msgid` if the relevant message is not found so that the issue never materializes?

**Comment by IvanMalison** [comment]
@djcb sorry to keep pestering, but I'd really love to get this fixed. Like I said, I'm happy to do the work, I'm just hoping for you to comment about any possible implications of the two solutions that I am considering. I have a feeling there is something I am not understanding.

**Comment by IvanMalison** [comment]
@djcb ping.

**Comment by choppsv1** [comment]
I too would like this to get fixed somehow. The ability to open the message using emacsclient (signaled from a external notification program), would be very nice.

**Comment by IvanMalison** [comment]
ping

**Comment by djcb** [comment]
@IvanMalison: can you give me some steps to reproduce? I.e., how do even search for a certain message-id if the message hasn't been seen yet?

**Comment by IvanMalison** [comment]
I was triggering it by executing some elisp using emacsclient but you could trigger it within emacs using elisp as well.

Something like:
```
(mu4e-view-message-with-msgid \"$1\")
```

you can get the message id from the file with something like

```
function mu4e_get_msg_id_from_file {
    mu view $1 -o sexp | grep "message-id" | get_cols ' -1' | sed 's/"//g'
}
```

**Comment by djcb** [comment]
Hmmm, so I have an unread message (in inbox/new). I extract its message-id from the command-line, then call `(mu4e-view-message-with-msgid "87lh7xjjgr.fsf@djcbsoftware.nl")`, and I get the message as expected.

Does that not work for you?

**Comment by djcb** [comment]
Closing; if you can still reproduce, please file a new issue with steps-to-reproduce.
