### ISSUE TITLE
Compose mail in new frame

### ISSUE THREAD

**Issue by davidcsterratt** [djcb/mu#554]
When I used the VM mailer, I found the `vm-mail-new-frame` function very useful. When composing a new email or writing a reply, this opens up a new frame for the composition buffer. When the email is sent, the frame is killed. 
I would find this particularly useful in mu4e. Very often I try replying to an email, which then occupies the pane previously occupied by the buffer of the email to which I'm replying. To look at this buffer then requires me to switch buffers, or open a new frame.
I've tried using `message-mail-other-frame` to achieve the desired effect, but this opens the buffer in the same frame, and doesn't display the mail buffer in another frame.
I've looked at the mu4e code, and come to the tentative conclusion that changes might be needed there - but my emacs-fu and time is too limited to make progress.

**Comment by djcb** [comment]
You could try to do something with `mu4e-compose-mode-hook`

**Comment by zakkak** [comment]
If you find a nice way to achieve this behavior please share it with the rest of us!  Or even better add it as an example in the documentation.

**Comment by panjie** [comment]
Simplest way is that you can define a global key to make a frame from a window like:
    (global-set-key "\C-\M-p" (lambda () (interactive) (make-frame) (delete-window)))

Or you can check out my fork of mu which added a switch to mu4e so that it will open compose window in a new frame:
https://github.com/panjie/mu

**Comment by davidcsterratt** [comment]
The following code in my `.emacs` does start mail being composed in a new frame, but the frame doesn't disappear when I send the email, and I've not worked out how I can achieve this (despite some experimenting with `set-window-dedicated-p`):
```   
(defun my-mu4e-other-frame ()
         (set (make-local-variable 'message-return-action) 'delete-frame)
         (switch-to-buffer-other-frame (buffer-name))
         ;(set-window-dedicated-p (get-buffer-window (current-buffer)) t)
         )
 (add-hook 'mu4e-compose-pre-hook 'my-mu4e-other-frame)
```
 I may well have a go with panjie's patch.

**Comment by davidcsterratt** [comment]
Thanks for this Pan. I've tried your patch, and it seems to work fine
for opening the new frame for the email. However, when I send the email,
the frame remains, and a version of the email that I've sent (seemingly
without line breaks) appears in the frame. 

However, I've observed replacing the compose frame by the same type of
garbled email in my normal setup, so perhaps this isn't to do with your
patch. Have you seen the same behaviour?

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by davidcsterratt** [comment]
It turns out that the garbled messages were due to using `longlines-mode` in `'mu4e-view-mode-hook`. When I remove  `longlines-mode` from  `'mu4e-view-mode-hook` I don't get garbled messages any more. 

However, I still have the problem with the frame not disappearing when I send a mail (using C-c C-c), using the branch  panjie/master.

**Comment by panjie** [comment]
@davidcsterratt It works fine for me(emacs-w32, cygwin on windows7). If you are sure that mu4e-compose-in-new-frame is set to t, maybe you will have to check the code in mu4e-compose.el/mu4e-set-handler.

**Comment by davidcsterratt** [comment]
My attempt to link pull request #615 to this issue failed - so I'm mentioning it here.
