### ISSUE TITLE
When split-view disabled, can't move to next message from message view

### ISSUE THREAD

**Issue by adam353** [djcb/mu#557]
Directions to reproduce:

- Disable split-view with (setq mu4e-split-view nil)
- View a message
- Press "n" to invoke mu4e-view-headers-next.

Expected behavior: View next message.
Displayed behavior: Error message "mu4e-view-headers-next: Wrong type argument: window-live-p, nil"

[I'm running mu4e 0.9.11 C on emacs 24.3.1.]

**Comment by zickzackv** [comment]
Same problem here too! Build is  6d4fe6434fbaf1c23fa6f7e8fe314559fceff3df

**Comment by stardiviner** [comment]
me too.

And also similar situation:
open a split view window from mu4e to show the message.
And when I switch to another window not about mu4e.
Then switch back to the message window, then can't move to next message. Untile I close the split message window, then in the open the split message window again.

**Comment by jaksz** [comment]
Me too!

**Comment by djcb** [comment]
Fixed in git.

**Comment by adam353** [comment]
Thanks so much!

Best,
Adam
