### ISSUE TITLE
combining maildirs in query

### ISSUE THREAD

**Issue by ksjogo** [djcb/mu#559]
Hello,
is it somehow possible to combine mails from different named maildirs in a query?

**Comment by djcb** [comment]
Sure, you can use {{OR}} in queries; see the docs for some examples.

**Comment by ksjogo** [comment]
Oh, I made a mistake in the shell.
mu find maildir:/X1/INBOX OR maildir:/X2/INBOX works, while mu find "maildir:/X1/INBOX OR maildir:/X2/INBOX" does not.
