### ISSUE TITLE
If executing trashing when the viewing the email to be trashed, the headers view is refreshed to be the trashed email

### ISSUE THREAD

**Issue by xuhdev** [djcb/mu#560]
To reproduce, first enter headers view. Then

    1. trash any message
    2. move the cursor to the trashed message using `p`
    3. press `x` to execute the trashing action

You'll see the headers view became the content of the trashed email

**Comment by djcb** [comment]
Can't reproduce that... are you using some non-standard keybindings?

**Comment by xuhdev** [comment]
No, I never changed mu4e's keybinding.

**Comment by xuhdev** [comment]
Sorry I missed an important step. You have to open the message first. That is:

    1. open the message you need to delete
    2. trash the message
    3. move the cursor to the trashed message using `p`
    4. press `x` to execute the trashing action

**Comment by djcb** [comment]
This is fixed as a side effect of 972678b6be0
