### ISSUE TITLE
How to flag all my email as read from mu?

### ISSUE THREAD

**Issue by shackra** [djcb/mu#561]
I downloaded all my emails on my new machine and then indexed them with `mu index`, the thing is that mu thinks that all those emails are not read, which is false because I have already read them.

Is there a way to mark all my emails on my machine as read?

**Comment by djcb** [comment]
Hmmm, mu does not change your mails, so it cannot do it directly; but you can use some script (a google search turns up http://www.aoakley.com/articles/2009-01-11-markallread.php), and the run {{mu index}} again.
