### ISSUE TITLE
Search strings containing dots & slashes

### ISSUE THREAD

**Issue by metaclassing** [djcb/mu#562]
In searching I came across this older issue: https://code.google.com/p/mu0/issues/detail?id=78 and suspect I am running into the same thing.

Searching for domain names "abc.domain.com" or IP addresses "10.20.30.40" fails even though the messages are indexed and can be found by searching for other english words in them. It seems searching for strings containing dots, slashes, etc. fail without error (just return no results)

Searching for literals with spaces "abc domain com" seems to return some results, curious to know if there is a better way to format my searches or use some kind of regex/wildcard for dots/unsupported characters, or if there is a patch in the works to maybe improve this behavior?

**Comment by djcb** [comment]
Sadly, due to the way the Xapian indexing / querying works (which mu uses), searches for such strings are problematic... not much I can do about that.

**Comment by djcb** [comment]
Using spaces might help indeed; xapian sees the '.' as a word-separator.
