### ISSUE TITLE
--muhome interferes with --maildir option

### ISSUE THREAD

**Issue by technomancy** [djcb/mu#565]
```
$ mu --muhome=.c-mu/ index --maildir=c-maildir
mu: Unknown option --maildir=c-maildir (0)
```

Omitting the `--muhome` argument allows this to succeed, but it seems impossible to specify both at the same time. (This is on ce5905f pulled today.)

**Comment by djcb** [comment]
% mu help index
usage:
	mu index [options]

Ie., the options must follow the subcommand.
