### ISSUE TITLE
Sort by date, but show flagged messages on top?

### ISSUE THREAD

**Issue by leoc** [djcb/mu#567]
First, let me thank you for this awesome project. I use mu4e as sole email solution.

I usually just work in a headers view via searching an empty string. 
Can I sort this view by date but still keep the flagged messages on top, so I do not forget those messages?

**Comment by djcb** [comment]
Hmmm, you can only sort by a single field at a time, and that's not likely to change... but perhaps you can simulate things by searching for flagged or unread-messages. Or have a query where you search for e.g. messages from the last 7 days OR flagged.

**Comment by bradyt** [comment]
This could be solved by a grouping feature request https://github.com/djcb/mu/issues/1177
