### ISSUE TITLE
Save all attachments in the same directory

### ISSUE THREAD

**Issue by mardukbp** [djcb/mu#568]
When a message contains multiple attachments I would like to be able to save all of them in the same directory. Currently (`C-u e a`), I have to navigate to the same directory for every attachment that I want to save. Using the N and P registers gives me the correct path but the wrong filename. Is there currently a way to achieve what I want?

**Comment by djcb** [comment]
You can customize `mu4e-attachment-dir`; maybe even with function or macro... But I guess what you want is some emacs-completion that cycles through directory, but does not change the filename. Not sure if there is something like that.

**Comment by mardukbp** [comment]
Thanks. Good to know. Probably a function will do. I will try it and if I am successful, I will post the solution here. Therefore, I am not closing this issue yet.

**Comment by stardiviner** [comment]
+1

**Comment by ardpp** [comment]
I'm curious if there is some progress on that. I would need this functionality quite often. 
Would it be possible to have a function called with `C-u C-u e a` say that asks for a directory and sets 
temporarily `mu4e-attachment-dir` to that directory? Then after saving it should be reset to the default directory.

**Comment by ardpp** [comment]
I think that setting the variable `mu4e-save-multiple-attachments-without-asking` to `t` in combination with `C-u e` almost does the trick for me. The only thing is that if files with the same names exist in the chosen directory I am asked if they should be overwritten. Pressing `n` seems to do nothing.

**Comment by mardukbp** [comment]
Thank you! `mu4e-save-multiple-attachments-without-asking` is
precisely what I needed.

This issue is solved for me. Feel free to close it when it is
solved for you.

**Comment by djcb** [comment]
Ok, thanks!

**Comment by antoine-levitt** [comment]
Just ran into this. The default behavior is very counter-intuitive, and I originally believed that there was a bug and that my attachments were not saved at all before I understood that it was asking for every one individually. Could mu4e-save-multiple-attachments-without-asking default to t? Otherwise, could the file name to save be displayed?
