### ISSUE TITLE
Support format=flowed on outgoing mails

### ISSUE THREAD

**Issue by cpbotha** [djcb/mu#569]
Plain text emails with "Content-Type: text/plain; format=flowed" can be reflowed (i.e. hard line endings removed, paragraphs refilled) by receiving clients that support this standard. Clients that don't support this, show them as is, which means this feature is truly non-invasive.

Here's an explanatory blog post which also shows why this is a desirable feature: https://mathiasbynens.be/notes/gmail-plain-text (if you don't have it, your mails mostly look quite crappy especially on mobile devices) and here's the RFC with all the details: http://www.ietf.org/rfc/rfc2646.txt

As far as I can see, implementation means that lines should be hard-wrapped as now (preferably at 72 chars), but they should end with a space before the CRLF (see 4.1 in the RFC), so that the receiving client, if it supports this feature, can correctly refill the paragraph.

It would be great if mu4e could do this. What do you think?

**Comment by cpbotha** [comment]
Whooo, super happy!

Went through the mu4e source, found where it called gnus to actually send the mail, and then found http://www.gnus.org/manual/emacs-mime_16.html and http://www.gnu.org/software/emacs/manual/html_node/emacs/Hard-and-Soft-Newlines.html

In short, if you activate `use-hard-newlines` and fill paragraph for your paragraphs, Emacs will indicate intra-paragraph breaks with soft newlines and inter-paragraph breaks with hard newlines. When gnus sees these on outgoing emails, it will automatically set `format=flowed`. I've just tested, and my text/plain mails are beautifully reflowed on the receiving side. No more ugly emails on mobiles!

You can use something like this in your init.el:

``` emacs-lisp
(add-hook 'mu4e-compose-mode-hook
          (defun cpb-compose-setup ()
            "Use hard newlines, so outgoing mails will have format=flowed."
            (use-hard-newlines t 'guess)))
```

It would make a lot of sense to add this to the documentation, no?

**Comment by zakkak** [comment]
That is nice!

Yes, please add this to the documentation.

**Comment by djcb** [comment]
Oh yes, if you can write something down (perhaps in the FAQ?), I'll merge it.

**Comment by mankoff** [comment]
Seems like it should maybe be default on, with FAQ for turning it off?

**Comment by cpbotha** [comment]
@djcb PR with explanation in the FAQ just created: https://github.com/djcb/mu/pull/570

(perhaps you could take a look at my other small PR while you're at it? https://github.com/djcb/mu/pull/566 -- fix bug with org-mu4e putting html in the text/plain part)

**Comment by mankoff** [comment]
This feature now flows signatures too. My signature is based on this string:

```
  (setq kdm/mu4e-sig-uniqID (concat "My Name\n"
                                  "http://www.com\n"
                                  "Position\n"
                                  "Institution\n"))
```

Is there a way to change this (something other than `\n`?) so that it does not get reflowed? I realize that hard linebreaks don't reflow, while soft ones do.

**Comment by justmytwospence** [comment]
This isn't working for me.  I'm using the example hook precisely.  In the compose buffer, my message visually wraps itself at column 72, as expected (I think), because auto-fill minor mode is on. The value of `use-hard-newlines` is `t`, so the hook successfully ran. Despite this, none of my messages are actually being reflowed properly on my mobile device. Any advice for debugging this?

**Comment by justmytwospence** [comment]
For anyone else with the same problem that I had: this was an issue with msmtp. msmtp was always sending emails with `Content-Type: text/plain`, even when trying to manually override this. Switching from msmtp to smtpmail-send fixed the problem.

**Comment by Chris00** [comment]
See also https://github.com/djcb/mu/issues/836
