### ISSUE TITLE
Plain text flow messed up when sending HTML emails

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#571]
When I send an HTML email from in Org following the instructions from http://vxlabs.com/2015/01/28/sending-emails-with-math-and-source-code/ and @cpbotha the plain text version that I seen in mu (because I have `(setq mu4e-view-prefer-html nil)`) is not flowed correctly.

I compose this:
```
And some more text

  + [ ] Foo
  + [ ] Bar
  + [ ] Baz

And some more text
```

If I send that as plain text, that is what I see in my inbox. But if I send that as HTML, the HTML version is displayed correctly (as seen on my phone, in gmail, or by viewing the HTML version explicitly in mu), but the plain text version displayed in mu looks like this:

```
  + [ ] Foo  + [ ] Bar  + [ ] Baz
```

**Comment by djcb** [comment]
Are you using 'format=flowed'?

**Comment by mankoff** [comment]
Yes I am. But it isn't just that, because plain-text sending with flow doesn't flow them (since those lines are indented). Only the plain-text with HTML has them flowed, even though indented.

**Comment by djcb** [comment]
Can you attach the raw message that is not showing correctly?

**Comment by dato** [comment]
The symptom sounds as if your plaintext body is going an overly aggressive conversion to flowed. `use-hard-newlines` might help.

But, honestly, in my experience you gain very little with HTML + format=flowed: most people will view the HTML version and, whoever doesn’t, are probably on a terminal with 60-80 columns at least (so they don’t need flowing for the mail to look alright).

My 2¢.

**Comment by djcb** [comment]
As discussed in #770, there's not much we can do about it in mu4e, sorry...
