### ISSUE TITLE
Reading encrypted sent messages

### ISSUE THREAD

**Issue by zakkak** [djcb/mu#576]
Currently mu4e encrypts, sends, and finally stores encrypted messages in the Sent folder.  The problem is if you need to later access the content of such messages, it fails (since you do not own the corresponding private key).

I believe that such messages should be stored encrypted with the sender's key in the Sent folder so that he could later decrypt them.  What are your thoughts on that?

**Comment by djcb** [comment]
Hmmm, I think the Sent-folder should contain what is sent; perhaps a copy (encrypted with sender's key) could be made. Or you could encrypt for yourself, too, and add yourself in Cc.

**Comment by kpachnis** [comment]
You need to encrypt outgoing emails with your key

```elisp
(require 'epg-config)
(setq mml2015-use 'epg
      epg-user-id "gpg_key_id"
      mml2015-encrypt-to-self t
      mml2015-sign-with-sender t)
```

I hope this helps

**Comment by zakkak** [comment]
Nice, thanks!

I'll add it to the documentation when I find some spare time. Please do not close this Issue till then.
