### ISSUE TITLE
FR: don't repeat thread text after first in message list

### ISSUE THREAD

**Issue by edumerco** [djcb/mu#577]
As discussed in the mu-discuss list, please make mu4e list view doesn't repeat the subject line in a threaded view. 

Rationale:
+ the repeated line doesn't add more information, but more clutter.
+ it is clearer how many "issues" (threads) we have open, even if a big one takes a lot of screen space, it's only one "block".
+ subject lines act as information and at the same time, block separators.

As an example, please see the screen capture in http://www.davep.org/mutt/screenshots/index.png

The idea it's not not original, nor mine, but something Mutt does (among other thread display options). 

Thanks. 

--
e

**Comment by zakkak** [comment]
FTR, I am appending screenshots of different indentation styles as posted by Ken Mankoff on the mu-discuss list:

##### Mutt Like
![mutt_like](https://groups.google.com/group/mu-discuss/attach/1ffed50adb520746/mutt-like.png?part=0.2&authuser=0&view=1)  

##### Show Thread Structure
![show_thread_structure](https://groups.google.com/group/mu-discuss/attach/1ffed50adb520746/show_thead_structure.png?part=0.1&authuser=0&view=1)  

##### Indent Subject 1
![indent_subject1](https://groups.google.com/group/mu-discuss/attach/1ffed50adb520746/indent-subject-1.png?part=0.3&authuser=0&view=1)  

##### Indent Subject 2
![indent_subject2](https://groups.google.com/group/mu-discuss/attach/1ffed50adb520746/indent-subject-2.png?part=0.4&authuser=0&view=1)  

##### Indent From 1
![indent_from1](https://groups.google.com/group/mu-discuss/attach/1ffed50adb520746/indent-from-1.png?part=0.5&authuser=0&view=1)

##### Indent From 2
![indent_from2](https://groups.google.com/group/mu-discuss/attach/1ffed50adb520746/indent-from-2.png?part=0.6&authuser=0&view=1)

##### Show Structure In From
![show_structure_in_from](https://groups.google.com/group/mu-discuss/attach/1ffed50adb520746/show-structure-in-from.png?part=0.7&authuser=0&view=1)

**Comment by mankoff** [comment]
Implemented in https://github.com/djcb/mu/commit/910e41e2fe1c8241b73161f1114a5410a3b52ebd. Works well for threaded view, but all sorts of errors get thrown when I type "P" or toggle `mu4e-headers-show-threads`

**Comment by djcb** [comment]
This has been implemented, see ``:thread-subject``.
