### ISSUE TITLE
Query contact-fields with more than one contact

### ISSUE THREAD

**Issue by cbourjau** [djcb/mu#578]
Hello,

I think I might have stumbled over a bug in mu/mu4e, or at least unexpected behaviour. I pointed it out in the mailing list where the behaviour was confirmed[1]. Thus, I open a issue here at github.

It seems that the contact fields of mails with more than one contact per contact field (eg. "To: aaa@example.com, bbb@example.com") are excluded from queries. So a mail with a "To:" field does not show up when I search for "to:aaa". nor just "aaa". Other fields like subject or body are not affected.

This behaviour really got me when I thought that I had searched for all correspondences with a specific contact.

[1] https://groups.google.com/forum/#!topic/mu-discuss/kq9bhZ0asMw

**Comment by djcb** [comment]
This seems to work just fine now. Note, in the test case, the field should be "to:", not "To:"
