### ISSUE TITLE
FR: Add new date query options

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#582]
Is it possible to search for yesterdays messages? Right now it seems like I can find messages dated today with "d:today" or "d:today..now". I'd like to find messages dated yesterday and the day before. I tried "d:1d..today" and "d:2d..1d" but those options operate in increments of 24 hours *from present time*. In order to keep backward compatibility I thought capital letters could be used to move in increments of 24 hours from `00:00`, so "d:2d..1d" is yesterday, not the past 24 hours.

I see this code is implemented here: https://github.com/djcb/mu/blob/master/lib/mu-date.c#L109

And I hoped a simple change like adding this line might be all that is needed:

```
	case 'D': /* day */
		delta = num * 24 * 60 * 60 - (now % 86400); break;
```

Where `now` is defined above the switch statement instead of below. However, adding that and recompiling does not seem to have any effect. Print statements show that the letters are all lowercase at this point. Modifying the `d` line (instead of adding a `D` line) seems to have the effect I want, but I don't want to make changes that break backward compatibility.

A quick search and I can't find where the lowercase change happens.

Before I dig farther, I thought I'd see if there is any interest in this feature, and if anyone can point to where the lowercase change is happening, or has other implementation suggestions.

**Comment by jschwab** [comment]
I would use this feature.  I think it would be great to do something analogous for every date code.  I want to find messages from /this/ week or /this/ year with relative frequency.

I didn't have any time to look into where the case change happens.

**Comment by djcb** [comment]
I've made some changes, so the date-characters are no longer being lower-cased. 
A patch implementing HDWMY would be welcome -- but please add a few unit tests -- thanks.

**Comment by jschwab** [comment]
Thanks Dirk.  I will work on this and submit a pull request when I'm done.  I should get to it this week.

**Comment by jschwab** [comment]
I scratched out a potential solution.  I am a novice C programmer and I don't know very much about time and date handling, so I wanted some feedback before I prepare a patch.

By convention, I defined `0[HDWMY]` to be the current hour, day, week, month, year.  `0[hdwmy]` are equivalent to `now`. That means that the code `date:0Y..now` would find all messages from the current year and `date:1Y..0Y` would find all messages from the last year (2014).

Here's a standalone c program that calculates the following date ranges.

https://gist.github.com/jschwab/685d91f2669924192994

Its output is:

    1h..0h:  Sun Mar 22 09:48:18 2015 .. Sun Mar 22 10:48:18 2015
    1H..0H:  Sun Mar 22 09:00:00 2015 .. Sun Mar 22 10:00:00 2015

    1d..0d:  Sat Mar 21 10:48:18 2015 .. Sun Mar 22 10:48:18 2015
    1D..0D:  Sat Mar 21 00:00:00 2015 .. Sun Mar 22 00:00:00 2015

    1w..0w:  Sun Mar 15 10:48:18 2015 .. Sun Mar 22 10:48:18 2015
    1W..0W:  Sun Mar 15 00:00:00 2015 .. Sun Mar 22 00:00:00 2015

    1m..0m:  Sun Feb 22 10:48:18 2015 .. Sun Mar 22 10:48:18 2015
    1M..0M:  Sun Feb  1 00:00:00 2015 .. Sun Mar  1 00:00:00 2015

    1y..0y:  Sat Mar 22 10:48:18 2014 .. Sun Mar 22 10:48:18 2015
    1Y..0Y:  Wed Jan  1 00:00:00 2014 .. Thu Jan  1 00:00:00 2015

This would slightly change the behavior of the lowercase strings.  Since I'm directly manipulating the dates, a year ago now means "decrement the year by 1" and not "365\*24\*60\*60 seconds before the present".

Questions, comments, thoughts?

**Comment by mankoff** [comment]
I'm not sure what coding is happening here. Are you coding up the test cases?

I thought that

        delta = num * 24 * 60 * 60 - (now % 86400); break;

Would be all that is needed for the 'd' case. If 'D' is previous day from *now*, and 'd' is then previous day from 00h00m (that is, yesterday), then the above should work.

Similar for week and etc. Is the more complex code you are writing to deal with edge cases of time zone changes and leap-years, etc.?

**Comment by jschwab** [comment]
@mankoff The code I posted is an outline of what the main switch statement in a revised `mu_date_parse_hdwmy` would look like.

Yes, the intent of the more complex code is to correctly handle timezones and leap years.  Your code is OK  for days (except I think the - should be a + ?).  But you can't do the same thing for years because of leap days since the epoch.

**Comment by jschwab** [comment]
@mankoff I should add, that since you proposed this and may have a clearer idea how it should work, I'm happy to let you whip up the patch.

**Comment by mankoff** [comment]
@jschwab I'm happy to help but it'll be a while until I have time to work on this, especially beyond a trivial implementation which we agree won't work for interesting cases.

**Comment by djcb** [comment]
The GDateTime family of functions (in GLib) can be quite useful for this, and they already have support for time-zones, leap-years and all that.

**Comment by jschwab** [comment]
I'm fighting a big deadline, so I'm not going to get to this for at least another week.  The GDateTime functions look nice, though there doesn't appear to be a way to find the number of seconds from the start of the current month, year, etc. other than doing bookkeeping similar to the code snipped I posted.

For example, I didn't see a way simpler than something like:

```c
    now = g_date_time_new_now_local();

    /* begin with current time to nearest minute */
    then_second = 0;
    then_minute = g_date_time_get_minute (now);
    then_hour = g_date_time_get_hour (now);
    then_day = g_date_time_get_day (now);
    then_month = g_date_time_get_month (now);
    then_year = g_date_time_get_year (now);

    /* this is the start of the current year */
    then_month = 1;
    then_day = 1;
    then_hour = 0;
    then_minute = 0;
        now = g_date_time_new_now_local();

    /* begin with current time to nearest minute */
    then_second = 0;
    then_minute = g_date_time_get_minute (now);
    then_hour = g_date_time_get_hour (now);
    then_day = g_date_time_get_day (now);
    then_month = g_date_time_get_month (now);
    then_year = g_date_time_get_year (now);

    /* this is the start of the current year */
    then_month = 1;
    then_day = 1;
    then_hour = 0;
    then_minute = 0;
    
    /* make then into a date */
    then = g_date_time_new_local (then_year,
                                  then_month,
                                  then_day,
                                  then_hour,
                                  then_minute,
                                  then_second);

    /* g_date_time_difference is in microseconds */
    delta = 1000000 * g_date_time_difference(now, then)

    /* make then into a datetime */
    then = g_date_time_new_local (then_year,
                                  then_month,
                                  then_day,
                                  then_hour,
                                  then_minute,
                                  then_second);

    /* g_date_time_difference is in microseconds */
    delta = 1000000 * g_date_time_difference(now, then)
```

**Comment by jschwab** [comment]
This hasn't yet made it to the top of my list -- and doesn't look like it will soon.  So I retract my previous commitment whip up a patch.  I never found a way to do this without a lot of bookkeeping.
