### ISSUE TITLE
assert fails when checking directories

### ISSUE THREAD

**Issue by sje30** [djcb/mu#585]
hi Dirk, with a recent (yesterday) pull of mu4e, "make check" fails at:

    /mu-util/mu-util-dir-expand-01:                                      **
    ERROR:test-mu-util.c:61:test_mu_util_dir_expand_01: assertion failed (got == expected): ("/mhome/damtp/cbi/sje30/Desktop" == "/home/sje30/Desktop")            
    FAIL

My home directory appears normally as /home/sje30  but it looks like "underneath" on the server it is actually /mhome/damtp/cbi/sje30 (damtp being the name of my department, and cbi my group name).

Anyway around this?  Changing the server is out of my control.

Best wishes, Stephen

**Comment by sje30** [comment]
Ok, I did it the old-fashioned way by removing the test!  the rest of mu passes.

**Comment by djcb** [comment]
I have de-activated the test-case for now... it's a bit non-trivial to fix the test case, while the code should still do the right thing.
