### ISSUE TITLE
Documented email selection hook lacks support for newly composed messages

### ISSUE THREAD

**Issue by stefanv** [djcb/mu#586]
In the documentation, a compose-hook is provided for setting the "From" address based on the message  responded to:

http://www.djcbsoftware.nl/code/mu/mu4e/Compose-hooks.html

However, this hook does not take into account composition of new messages, so that the address for *newly composed messages* will not always be the *default* email.

Here is one potential workaround:

```elisp
(add-hook 'mu4e-compose-pre-hook
  (defun my-set-from-address ()
    "Set the From address based on the To address of the original."
    (let ((msg mu4e-compose-parent-message)
          (default-address "default@mydomain.com"))
      (setq user-mail-address default-address)
      (when msg
        (setq user-mail-address
              (cond
               ((mu4e-message-contact-field-matches msg :to "other@other.com")
                "other@other.com")
               (t default-address)))))))
```

**Comment by djcb** [comment]
Hmm... since `user-mail-address` must be set anyway, there's not much use in overriding it in this hook, or?

**Comment by stefanv** [comment]
This is just adapting the hook from the documentation, which is meant to switch email addresses based on the email you are replying to, so I'm not sure what you mean?

**Comment by djcb** [comment]
So, in case we're not replying to anything, we'll use `user-mail-address`, with or without the change... or?

**Comment by stefanv** [comment]
The behavior I expected: use user-mail-address if creating a new email, or if replying to an email with a "To:" address not in the list, otherwise choose the appropriate email from the list.

**Comment by danielsz** [comment]
Exactly. 

Wouldn't making `user-mail-address` buffer-local solve this?

**Comment by danielsz** [comment]
Also, in the real world, when you reply to an email with a specific account, it is likely that you will set not only the From address, but also the full name and the signature. 

I have come up with a solution that I am documenting here. If you like it, I can do a pull request to replace the old example in the manual.

```emacs
(cl-defstruct account full-name address signature)
(setq my-accounts (list
                   (make-account :full-name "Stannis Baratheon"
                                 :address "stannis.baratheon@seven-kingdoms.com"
                                 :signature "Best dad ever\nAlso Protector of the Realm")
                   (make-account :full-name "Daenerys Targaryen"
                                 :address "daenerys.targaryen@meereen.com"
                                 :signature "Dragon pup for sale")
                   (make-account :full-name "Melisandre"
                                 :address "melisandre@lordoflight.com"
                                 :signature "I love science")))

(add-hook 'mu4e-compose-pre-hook
          (lambda ()
            "Set the From address based on the To address of the original."
            (let ((msg mu4e-compose-parent-message)
                  (default-account (car my-accounts)))
              (cl-multiple-value-setq (user-mail-address user-full-name mu4e-compose-signature)
                (if msg
                    (loop for account in my-accounts
                          when (mu4e-message-contact-field-matches msg :to (account-address account))
                          return (cl-values (account-address account)
                                            (account-full-name account)
                                            (account-signature account)))
                  (cl-values (account-address default-account)
                             (account-full-name default-account)
                             (account-signature default-account)))))))
```

**Comment by djcb** [comment]
Oh, that looks nice and clean!

It does miss some of the ``smtpmail-``, ``-folder`` settings of the current example though; seems it would be useful to add those.

**Comment by zakkak** [comment]
@djcb if you are planning to pull this upstream, then we should adapt the [Multiple Accounts](http://www.djcbsoftware.nl/code/mu/mu4e/Multiple-accounts.html) documentation as well.

**Comment by danielsz** [comment]
Thanks! Further cleanup yields the following, which I actually prefer:

```emacs-lisp
(add-hook 'mu4e-compose-pre-hook
          (lambda ()
            "Set the From address based on the To address of the original."
            (let* ((msg mu4e-compose-parent-message)
                   (default-account (car my-accounts))
                   (current-account (if msg
                                        (loop for account in my-accounts
                                              when (mu4e-message-contact-field-matches msg :to (account-address account))
                                              return account)
                                      default-account)))
              (setq user-mail-address (account-address current-account)
                    user-full-name (account-full-name current-account)
                    mu4e-compose-signature (account-signature current-account)))))```

**Comment by danielsz** [comment]
@djcb @zakkak 

Regarding smtp configuration for multiple accounts, the configuration in Emacs is superfluous if you use [msmtp](http://msmtp.sourceforge.net/), which knows which smtp server to select based on the `From` address.

**Comment by danielsz** [comment]
Sure, per account `smtpmail-` and `-folder` settings are trivial to add. 
I hadn't seen the [multiple accounts](the http://www.djcbsoftware.nl/code/mu/mu4e/Multiple-accounts.html) page, which is maybe a good thing otherwise I wouldn't have gone to the trouble of writing my solution. If you want, I can do a pull request with the same page, but based on the defstruct solution. I would also recommend to use `msmtp` as this leaves the smtp configuration out of Emacs and mu4e. 
`msmtp` knows which smtp server to choose based on the *From* address. 

```emacs-lisp
(setq sendmail-program (executable-find "msmtp"))
(if sendmail-program
    (setq message-send-mail-function 'message-send-mail-with-sendmail
          message-sendmail-f-is-evil 't
          message-sendmail-extra-arguments '("--read-envelope-from"))
    (setq send-mail-function 'smtpmail-send-it
     ...))
```

**Comment by zakkak** [comment]
Are there any other benefits from using `msmtp` other than the configuration split?

If not, I do not think it is a good idea to introduce a dependency.  I agree however that a mention to `msmtp` (especially if it comes with a short configuration example) is useful.

**Comment by danielsz** [comment]
Mentioning it in the multiple accounts documentation would be good enough. Making the user aware that he can greatly simplify his setup by using `msmtp` instead of the default `sendmail`.  After all, both are dependencies at the same level.

**Comment by zakkak** [comment]
If I am not mistaken you can avoid the dependency on `sendmail` by using `smtpmail-send-it`.

See [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Mail-Sending.html#Mail-Sending)

**Comment by danielsz** [comment]
Yes, you are right, Emacs has

**Comment by zakkak** [comment]
Human nature :)

**Comment by numkem** [comment]
@danielsz Do you happen to have a pull request for this? I'm trying to make it work on my side and the only case I've seen it not work is when I try to forward and email that was already sent. I get `error in process filter: account-address accessing a non-account`.

**Comment by danielsz** [comment]
No PR, sorry. But what you are reporting makes total sense. If the To address of the original mail is not one in the list of accounts, you will see that error message. This will currently happen when forwarding, or hitting reply on a message that was not addressed to you. Fixing that is not hard though. All is needed is to refine the loop in the compose hook. This should do:

```emacs
(loop for account in my-accounts
    when (mu4e-message-contact-field-matches msg :to (account-address account))
         return account
         finally return default-account)
```

**Comment by djcb** [comment]
mu4e now has has 'mu4e-context' built in (git version).

**Comment by danielsz** [comment]
:+1:
