### ISSUE TITLE
Improved thread icons

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#599]
This feature request is somewhat related to this thread https://groups.google.com/forum/#!topic/mu-discuss/5bVvp---X84 requesting alternate treatments of thread subjects, implemented in https://github.com/djcb/mu/commit/910e41e2fe1c8241b73161f1114a5410a3b52ebd

The thread indicator icons are not easy to interpret. I see:

+ open (hollow) squares
+ light filled squares
+ dark filled squares
+ vertical lines
+ bent arrows.

It is obvious the bent arrows signify the final message in a thread, but I can't figure out what the other symbols mean.

They should be documented in the manual, and perhaps improved to better graphically flow the flow or path of the thread.

**Comment by djcb** [comment]
They are documented in the source; see mu4e-headers.el. Patches for the reference documentation and/or improved characters are welcome.

**Comment by mankoff** [comment]
Thanks for the pointer to the source. No need for a patch, since it seems these are user-configurable. For example, see attached screenshot of config settings.

![screen shot 2015-03-23 at 17 26 55](https://cloud.githubusercontent.com/assets/145117/6790970/ea3efa98-d181-11e4-82f6-f75c6776821a.png)

**Comment by mankoff** [comment]
Although alignment gets messed up if these emoji icons are used for flags.

**Comment by djcb** [comment]
Ah, that looks nice, though for the defaults I'd like to be a bit more conservative as the colorful ones are not available everywhere.

**Comment by cslux** [comment]
Hey @mankoff,

may I ask, how you inserted those fancy sybmols, or/and provide a link?
Thanks in advance!

regards,
Christian

**Comment by cslux** [comment]
@mankoff 
The only thing a found was this http://apps.timwhitlock.info/emoji/tables/unicode but still it doesn't have any colors, I guess I need to install some package.

**Comment by mankoff** [comment]
On OS X I brought up the Emoji keyboard menu. Under System Prefs > Keyboard you can check an option for "Show Keyboard, Emoji, and Symbols Viewers in menu bar".

**Comment by cslux** [comment]
Ah ok, no OS X here, this means it doesn't work on Linux on the fly.

**Comment by mankoff** [comment]
I think Linux can display emoji also. Should work, just needs to be entered differently.

**Comment by cslux** [comment]
Yep you are right, it just want display the apple version of the emoji, just the native one :-/
