### ISSUE TITLE
Address autocompletion: fuzzy search

### ISSUE THREAD

**Issue by jinnovation** [djcb/mu#603]
Similar to #152, the ability to search for address completion candidates "fuzzily" would be hugely beneficial.

Say there's an address that the user'd like to access: `John Doe <john@doe.com>`. Currently, the only way to access this address is by tab-completing `John`, `Joh`, etc. Fuzzy search would allow the user to access this address by tab-completing `Doe`, `doe.com`, etc. -- useful in those cases where, for instance, there is only one address with domain `doe.com` or with last name `Doe`.

**Comment by jsrndk** [comment]
You can activate Ido for completion of addresses for this, see https://groups.google.com/group/mu-discuss/browse_thread/thread/551b7a6487a0aeb3

**Comment by djcb** [comment]
By default, mu4e's completion uses substring matching, so completing "Doe" works; if you want something more fancy, you can prepend you favorite to the completion-styles in the mode-hook for mu4e-compose-mode.

**Comment by foudfou** [comment]
In fact, helm-mode seems to conflict with mu4e's completion: substring matching doesn't work.
I don't know how to turn off `helm-mode` when composing only. `(helm-mode -1)` in `mu4e-compose-mode-hook` turns it off completely for all other modes.
`helm-completing-read-handlers-alist` is supposed to help here, but I couldn't find what mu4e handler to use.

**Comment by djcb** [comment]
@foudfou: how are you using helm for completion there?  In any case, mu4e's contact-completion uses emacs very own `completion-at-point-functions`, so I suppose helm should be able to work with that.

**Comment by foudfou** [comment]
```lisp
(helm-mode 1)
(setq mu4e-completing-read-function 'completing-read) ; substring compl doesn't work with default (ido)
```
BTW can you be reached on IRC ?

**Comment by djcb** [comment]
Note, `mu4e-completion-read-function` is only used for completing maildirs, not for completing contacts.

I'm "djcb" in freenet.

**Comment by amosbird** [comment]
I read all the above discussion but still can't get an idea of enabling fuzzy address completion. What `completion-styles` should I use?

**Comment by jsrndk** [comment]
As mentioned, I use ido. I have the following in my emacs setup. Note that the code is ~4 ys old and I haven't touched it, so there might be better ways to do this now -- but it still works. 

```lisp
(defun ido-select-recipient ()
  "Inserts a contact from the mu cache.  Uses ido to select the contact from all
those present in the database."
  (interactive)
  (insert
   (ido-completing-read
    "Recipient: "
    (mapcar
     (lambda (contact-string)
       (let* ((data (split-string contact-string ","))
              (name (when (> (length (car data)) 0)
                      (car data)))
              (address (cadr data)))
         (if name
             (format "%s <%s>" name address)
           address)))
     (remove-if (lambda (string) (= 0 (length string)))
                (split-string (shell-command-to-string "mu cfind --format=csv")
                                            "\n"))))))
```

Then I simply remap `<backtab>` (i.e. shift + tab) to `ido-select-recipient`. When I want to insert an address, I hit `<backtab>` and start fuzzy searching.

My main dissatisfaction with the above is that it doesn't sort the addresses by relevance/last email/or something. So I can easily get an email address suggested for which I 5 years ago received a single email from.

**Comment by amosbird** [comment]
@jsrndk Well, I'm not asking about this kind of fuzzy completion which is already implemented in spacemacs via `helm`. I'm talking about fuzzy completion in company mode. Anyway, thanks for the information. I learnt something from it :+1:
