### ISSUE TITLE
mu4e: Shortcut keys shown as asterisks

### ISSUE THREAD

**Issue by tarjeiba** [djcb/mu#604]
Hello!

I've just started to use mu4e, and I'm encountering a (to me) weird effect: all shortcut keys are shown as asterisks in the `*mu4e-main*` buffer, as shown in the picture below.

![screenshot from 2015-04-15 15 48 24](https://cloud.githubusercontent.com/assets/6142182/7160045/ebeb0488-e386-11e4-8160-e884d88ef02e.png)

Has anyone else seen this effect?

**Comment by jschwab** [comment]
This has long been fixed, please upgrade your mu version to something more recent. (v0.9.9.5 is ~ two years old.)

**Comment by tarjeiba** [comment]
Color me embarrassed, and thank you.
