### ISSUE TITLE
Automatically process new mail

### ISSUE THREAD

**Issue by spacefrogg** [djcb/mu#606]
How do you guys automatically process new mail? I come from sup, a ruby/xapian mail reader comparable to mu/mu4e and I am used to rely completely on tags, when reading e-mail. In mu, adding tags to an e-mail means altering the file storing the mail. How do you realize that reliably? I have patched mu and mu4e to make that possible but before sharing the code I wanted to ask if there are simpler solutions which do not require patching mu. The biggest obstacle was the asynchronous communication between emacs an the mu server and the impossibility to find out, which messages where actually newly added to the xapian database and would thus require initial processing. In my patch the mu server communicates new e-mail back to emacs, which then takes care of further processing.

**Comment by djcb** [comment]
In mu4e, tagging is a bit of a second-class citizen -- reason is that:

a) it wants to keep the useful property of allowing deleting the xapian-database without data lost (so tags can't go there)
b) it doesn't like altering the actual mail messages on disk (which seems risky and be bit unhygienic)

Not all mu4e-users agree with this, but that's how it is :). I'm simply using the maildir for a message as the one interesting tag, and let search deal with the rest. Less powerful that full tagging of course, but does satisfy a) and b).
