### ISSUE TITLE
configure script reports wrong version?

### ISSUE THREAD

**Issue by andreas-h** [djcb/mu#608]
When I check out the tag `v0.9.12`, and run `./configure --prefix=${HOME}/.local`, I get the following output:

    ------------------------------------------------
    mu version                           : 0.9.11
    
    Xapian version                       : 1.2.16
    GLib version                         : 2.40.2
    GMime version                        : 2.6.20
    Emacs version                        : GNU Emacs 24.4.1
    
    Have wordexp                         : yes
    Build mu4e emacs frontend            : yes
    Build 'mug' toy-ui (gtk+/webkit)     : no
    McCabe's Cyclomatic Complexity tool  : no
    
    Have direntry->d_ino                 : yes
    Have direntry->d_type                : yes
    ------------------------------------------------

Shouldn't this read 0.9.12?

**Comment by jschwab** [comment]
Yes, the version string was not bumped until after the tag.  See commit 1fa9aea6e21c2d863d0934f8e435b1fae130e908
