### ISSUE TITLE
can't send attachments in org-mu4e-compose-org-mode

### ISSUE THREAD

**Issue by gambhiro** [djcb/mu#609]
Org-mu4e is great for adding some HTML links and markup, but I can't send attachments at the same time.

To reproduce:

- compose a new message
- `M-x org-mu4e-compose-org-mode`
- go to the message body
- drag in an attachment
- go up to header and `C-c` to send

In the sent message, the attachment markup is escaped and the file is not attached.

**Comment by djcb** [comment]
org-mu4e-compose-mode has been deprecated for a while;
   http://www.djcbsoftware.nl/code/mu/mu4e/Rich_002dtext-messages-with-org_002dmode.html#Rich_002dtext-messages-with-org_002dmode

**Comment by gambhiro** [comment]
Ah, ok. Thanks for the comment.
