### ISSUE TITLE
Sending from multiple accounts, receiving in one

### ISSUE THREAD

**Issue by kostajh** [djcb/mu#612]
This is somewhat a follow up to #76.

In an effort to simplify my life, I've got multiple email accounts (including a work account) forwarding their mail to one primary email account.

When replying to an email sent to my work address (that's been forwarded to my personal address), I would like mu4e to use the SMTP server for my work address, use a signature for my work address, etc.

As far as I can tell from reading the manual, this requires setting up maildirs for all accounts I want to be able to send to.

Is there anyway to tell mu4e to just use a different smtp server/signature when replying to a message, without also setting up maildirs for all those accounts?

**Comment by whirm** [comment]
I Have a bunch of functions such as

```elisp 
(defun identity-foo()
  "Set identity settings to Foo account"
  (interactive)

  (message "Using Foo smtp server")
  (setq
   ;; general emacs mail settings; used when composing e-mail
   user-mail-address "bar@foo.com"
   user-full-name  "John Smith"

   smtpmail-smtp-server "smtp-a.foo.com"
   smtpmail-smtp-service 465
   smtpmail-stream-type 'ssl
   )
  )
```

So I can easily switch settings when I have to reply from one of my legacy accounts for some reason.

**Comment by gleydsonsoares** [comment]
http://www.djcbsoftware.nl/code/mu/mu4e/Multiple-accounts.html

**Comment by kostajh** [comment]
@gleydsonsoares I read that, but I'm asking for something different.

@whirm thanks, I'll try something along those lines.
