### ISSUE TITLE
Inconsistent behavior when URL contains `|` in the content of a mail in view

### ISSUE THREAD

**Issue by xuhdev** [djcb/mu#617]
When a URL contains `|`, it will be shown like this in the view:

    http://example.com/test.php?i=215[1]|216&xxxx=yyyy

Note the `[1]` is not in the correct place. Now what would happen is, when using `g` to go to the URL, `|` and whatever after it is not used. If clicking on the URL, however, the whole URL including whatever after `|` is used.

I understand that `|` appearing in a URL does not comply with the standard, but inconsistent behavior is also strange.

**Comment by djcb** [comment]
These days, mu4e uses emacs' built-in URL-parsing (ie., ``thing-at-point-bounds-of-url-at-point``), so there's not much we can do about it from the mu4e-side. Perhaps file an issue against emacs itself?
