### ISSUE TITLE
mu4e - upload package to MELPA? 

### ISSUE THREAD

**Issue by yitang** [djcb/mu#620]
Hi,

I think having mu4e package hosted in MELPA makes user easier to install and upgrade it.  

What do you think?

**Comment by thierryvolpiatto** [comment]
Yi Tang <notifications@github.com> writes:

> Hi,
>
> I think having mu4e package hosted in MELPA makes user easier to install and upgrade it.
>
> What do you think?

I think @djcb will have tons of bug reports about the backend not
installed.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by djcb** [comment]
Indeed... if mu4e were all lisp, it'd be nice to have it in melpa; however, mu4d depends on mu, and occasionally the protocol between the two changes; would be hard to do that if mu/mu4e were split up.

**Comment by zakkak** [comment]
@djcb actually there are more packages like mu4e on melpa and the process seems to work fine.

You can have a look at [pdf-tools](https://github.com/politza/pdf-tools) and [irony-mode](https://github.com/Sarcasm/irony-mode).

**Comment by priyadarshan** [comment]
You may also want to check how `el-get` does it:
https://github.com/dimitri/el-get/blob/master/recipes/mu4e.rcp
