### ISSUE TITLE
offlineimap failed due to bad certificate; no report from mu4e

### ISSUE THREAD

**Issue by sachdevaprash** [djcb/mu#622]
If offlineimap fails to update email, mu4e should report failure. To reproduce, just change the cert_fingerprint in .offlineimaprc and try to run update in mu4e: mu4e does not return error, even though offlineimap failed.

**Comment by djcb** [comment]
You can influence the error behavior with mu4e-index-update-error-warning and mu4e-index-update-error-continue; does that not work for you?

**Comment by sachdevaprash** [comment]
Nope. It does not show an error or warning, even after setting continue to 'off' (nil) and warning to 'on' (non-nil)

**Comment by thierryvolpiatto** [comment]
Prashant Sachdeva <notifications@github.com> writes:

> Nope. It does not show an error or warning, even after setting
> continue to 'off' (nil) and warning to 'on' (non-nil)

Did you specify the path of your certificate in .offlineimaprc ?

Here on my system it is:

sslcacertfile = /etc/ssl/certs/ca-certificates.crt

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by sachdevaprash** [comment]
I'm confused. How would that make a difference to throwing a warning. If there is a missing certificate, shouldn't it still throw an error? If offlineimap has failed for whatever reason, mu4e should fail when the warning is set to 'on'.

Just to be clear, mu4e is working for me as of now. But this bug (or behavioral quirk) still persists. I had to run offlineimap on a shell to know that there was an error, which imo should not be the case.

**Comment by djcb** [comment]
What version of mu4e are you using?

**Comment by sachdevaprash** [comment]
It's right out of github. I keep it updated. It says 0.9.12 CG as the version

**Comment by sachdevaprash** [comment]
It turns out that offlineimap does not return a non-zero error value even if the update fails. I have reported this bug: https://github.com/OfflineIMAP/offlineimap/issues/248

**Comment by djcb** [comment]
Not much I can do about it then... but you could write a shell script that calls offlineimap and does some string-matching on the output, and return non-zero if the update fails; then tell mu4e to use the shellscript rather than offlineimap directly.

**Comment by sachdevaprash** [comment]
I went ahead and fixed the bug in OfflineIMAP code, but it is in the next branch currently. It should be in the master soon. I was just waiting for it to go through before closing this.
