### ISSUE TITLE
Forward message as-is

### ISSUE THREAD

**Issue by stefanv** [djcb/mu#624]
mu4e only allows capturing and forwarding a message as a .eml attachment.  Often, it is handy to be able to forward an HTML email "as is" (the behavior I currently see is that HTML gets converted to text, which is then included inline in the forward).

**Comment by panjie** [comment]
I need this feature too

**Comment by jackbaty** [comment]
This would be handy, as I often forward HTML messages to things like Evernote that are better-handled intact. This would be similar to Mutt's "resend-message", yes?

> With resend-message, mutt takes the current message as a template for a new message. This function is best described as "recall from arbitrary folders". It can conveniently be used to forward MIME messages while preserving the original mail structure. Note that the amount of headers included here depends on the value of the $weed variable.

> This function is also available from the attachment menu. You can use this to easily resend a message which was included with a bounce message as a message/rfc822 body part.

**Comment by djcb** [comment]
@jackbaty: that's a slightly different function though; however, I think either bouncing messages or forwarding as-is would work in your use-case. Just need to implement them :-)

**Comment by djcb** [comment]
There's `mu4e-compose-resend` now (git); but for simply forwarding as-is, the easiest way is to capture a message (using the 'capture action', ie., 'a c' in headers-mode or view-mode), then compose the message and use `mu4e-compose-attach-captured-message`.

**Comment by semente** [comment]
@djcb I couldn't achieve the 'as-is' using the mu4e-compose-attach-captured-message method when sending the message to a gmail account. It is displayed as attachment there and I couldn't open it, just download. In another webmail I could open the attachment and see the original content. Unfortunately my recipient uses gmail.

A forwarding method preserving the HTML content would be great and also could display the forwarded message inline.

Thanks

**Comment by Chris00** [comment]
@semente You should open a new issue, explaining your case.  Make sure attaching an HTML file solves it (both in Gmail and with Gnus view).
