### ISSUE TITLE
When mu4e-compose-in-new-frame is set to `t`, should `message-kill-buffer` kill the frame?

### ISSUE THREAD

**Issue by zakkak** [djcb/mu#627]
When `mu4e-compose-in-new-frame` is set to `t` I would expect/want `message-kill-buffer` to close the new frame as well.

That said, I believe we need a wrapper for `message-kill-buffer` that will allow us to kill the frame as well.

What is your opinion?

**Comment by panjie** [comment]
You can use something like:
```elisp
(defadvice message-kill-buffer (after kill-frame activate)
  (when mu4e-compose-in-new-frame
    (delete-frame)))
```

**Comment by djcb** [comment]
The defadvice could be an good solution for this -- but we should somehow limit it to only mu4e (so it does not affect other possible uses of message-kill-buffer);  perhaps check for the buffer-mode?

**Comment by zakkak** [comment]
That's why I was thinking about a wrapper (with a `mu4e-*` name, e.g., `mu4e-message-kill-buffer`) that we could bind to `C-c C-k` in the `mu4e-compose-mode`.

**Comment by djcb** [comment]
Okay, we're closing the frame in slightly different way now, by adding `delete-frame' as a message-mode action that is executed with killing/postponing/sending a message.
