### ISSUE TITLE
Newly created directories not showing up; mark-for-move needed twice

### ISSUE THREAD

**Issue by eigengrau** [djcb/mu#628]
When marking e-mails for a move to a folder that doesn’t yet exist, mu4e (0.9.11) helpfully asks if the folder should be created. After responding yes, the headers view shows the «m» mark, but it doesn’t show the «→/foldername» part. After executing marked actions, the e-mail will not have been moved, but still remains in the original folder. To actually move it, it has to be marked again.

Perhaps relatedly, directories created in this fashion do not show up in directory completions (jump/move to), even after quitting and restarting mu4e from within Emacs. The newly created folder only shows up after restarting Emacs wholesale.

**Comment by Chris00** [comment]
Would there be a relation to the [marks lost issue](https://github.com/djcb/mu/issues/474)?

**Comment by Chris00** [comment]
@djcb Since, obviously, your knowledge of `mu4e` is greater that ours, it would help if you could point to the likely places where one has to look to fix this.
