### ISSUE TITLE
Message header :in-reply-to not available in headers view

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#629]
Consider the following code I hacked up:

```
(defun my-switch-to-thread ()
  "Switch to headers view of current thread."
  (interactive)
  (let ((id (or (mu4e-message-field-at-point :in-reply-to)
                (mu4e-message-field-at-point :message-id))))
    (mu4e-headers-search (format "i:%s" (s-replace-all '(("<" . "")
                                                         (">" . ""))
                                                       id)))))
```

This doesn't work in headers mode because (mu4e-message-field-at-point :in-reply-to) returns "" instead of nil. What would be really useful is if it could actually return the in-reply-to field if it has it.

**Comment by djcb** [comment]
To do this reliably, we'd need the thread-id (ie., the message-id) of the thread-parent; and that would require a bit more work, including on the mu server.

**Comment by djcb** [comment]
Closing this for now.
