### ISSUE TITLE
Search term of i: puts mu daemon into a 100% CPU busy loop

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#633]
This is peripherally related to #629 in that before I tweaked my function I was setting a search of i: which sends the mu server into a 100% CPU burning cycle which you have to wait for it to finish. Cancelling to the main menu leaves the server busy until it completes (burning a lot of memory). The server should probably guard against junk queries like that or at least be cancellable by the UI.

**Comment by djcb** [comment]
Can you still reproduce this? If so, can you produce a backtrace?

**Comment by stsquad** [comment]
Yep still occurs on current HEAD.

    #0  0x00007ffff7a197fc in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #1  0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #2  0x00007ffff7b4316d in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #3  0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #4  0x00007ffff7b4316d in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #5  0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #6  0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #7  0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #8  0x00007ffff7b4316d in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #9  0x00007ffff7b4316d in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #10 0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #11 0x00007ffff7b4316d in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #12 0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #13 0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #14 0x00007ffff7b4316d in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #15 0x00007ffff7b4316d in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #16 0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #17 0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #18 0x00007ffff7b4315e in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #19 0x00007ffff7b38f35 in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #20 0x00007ffff7b3b6ef in  () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #21 0x00007ffff7a2a50f in Xapian::Enquire::Internal::get_mset(unsigned int, unsigned int, unsigned int, Xapian::RSet const*, Xapian::MatchDecider const*, Xapian::MatchDecider const*) const () at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #22 0x00007ffff7a2a870 in Xapian::Enquire::get_mset(unsigned int, unsigned int, unsigned int, Xapian::RSet const*, Xapian::MatchDecider const*) const ()
        at /usr/lib/x86_64-linux-gnu/libxapian.so.22
    #23 0x0000000000417f5f in mu_msg_iter_new(XapianEnquire*, size_t, MuMsgFieldId, MuMsgIterFlags, GError**) (flags=0, sortfield=16 '\020', maxnum=500, enq=..., this=0x3cf23900)
        at mu-msg-iter.cc:92
            keymaker = {<Xapian::KeyMaker> = {<No data fields>}, _threadinfo = 0x4afc120}
            descending = false
            threads = false
            iter = <optimised out>
            __PRETTY_FUNCTION__ = "MuMsgIter* mu_msg_iter_new(void**, size_t, MuMsgFieldId, MuMsgIterFlags, GError**)"
            __func__ = "mu_msg_iter_new"
    #24 0x0000000000417f5f in mu_msg_iter_new(XapianEnquire*, size_t, MuMsgFieldId, MuMsgIterFlags, GError**) (enq=enq@entry=0x7fffffffdd50, maxnum=maxnum@entry=500, sortfield=sortfield@entry=16 '\020', flags=flags@entry=13, err=err@entry=0x0) at mu-msg-iter.cc:235
            iter = <optimised out>
            __PRETTY_FUNCTION__ = "MuMsgIter* mu_msg_iter_new(void**, size_t, MuMsgFieldId, MuMsgIterFlags, GError**)"
            __func__ = "mu_msg_iter_new"
    #25 0x000000000041df8d in mu_query_run(MuQuery*, char const*, MuMsgFieldId, int, MuQueryFlags, GError**) (flags=29, sortfieldid=<optimised out>, maxnum=500, iter=<synthetic pointer>, self=0x27dfed0) at mu-query.cc:492
            orig_set = 0x0
            enq = {internal = {dest = 0x35b0400}, static INCLUDE_QUERY_TERMS = 1, static USE_EXACT_TERMFREQ = 2}
            rel_iter = <optimised out>
            iter = 0x3425300
            descending = true
            first_flags = <optimised out>
            inc_related = true
            enq = {internal = {dest = 0x4780d00}, static INCLUDE_QUERY_TERMS = 1, static USE_EXACT_TERMFREQ = 2}
            __PRETTY_FUNCTION__ = "MuMsgIter* mu_query_run(MuQuery*, const char*, MuMsgFieldId, int, MuQueryFlags, GError**)"
            __func__ = "mu_query_run"
    #26 0x000000000041df8d in mu_query_run(MuQuery*, char const*, MuMsgFieldId, int, MuQueryFlags, GError**) (self=0x27dfed0, searchexpr=searchexpr@entry=0x34d0b00 "i:", sortfieldid=<optimised out>, maxnum=maxnum@entry=500, flags=flags@entry=29, err=err@entry=0x7fffffffdee8) at mu-query.cc:552
            iter = 0x3425300
            descending = true
            first_flags = <optimised out>
            inc_related = true
            enq = {internal = {dest = 0x4780d00}, static INCLUDE_QUERY_TERMS = 1, static USE_EXACT_TERMFREQ = 2}
            __PRETTY_FUNCTION__ = "MuMsgIter* mu_query_run(MuQuery*, const char*, MuMsgFieldId, int, MuQueryFlags, GError**)"
            __func__ = "mu_query_run"
    #27 0x000000000040e6bd in cmd_find (ctx=0x7fffffffdef0, args=0x379a580, err=0x7fffffffdee8) at mu-cmd-server.c:961
            iter = <optimised out>
            foundnum = 4294958824
            maxnum = <optimised out>
            sortfield = 16 '\020'
            querystr = 0x34d0b00 "i:"
            qflags = 29
    #28 0x000000000040fff5 in mu_cmd_server (err=0x7fffffffdee8, args=0x379a580, ctx=0x7fffffffdef0) at mu-cmd-server.c:1595
            u = <optimised out>
            cmd = 0x4661300 "find"
            cmd_map =
                {{cmd = 0x42e421 "add", func = 0x40e380 <cmd_add>}, {cmd = 0x431676 "compose", func = 0x40f960 <cmd_compose>}, {cmd = 0x42dfa2 "contacts", func = 0x40e840 <cmd_contacts>}, {cmd = 0x42e1d9 "extract", func = 0x40f570 <cmd_extract>}, {cmd = 0x42e3c4 "find", func = 0x40e580 <cmd_find>}, {cmd = 0x4316a3 "guile", func = 0x40efd0 <cmd_guile>}, {cmd = 0x432b77 "index", func = 0x40e980 <cmd_index>}, {cmd = 0x42e3d5 "mkdir", func = 0x40f4d0 <cmd_mkdir>}, {cmd = 0x42e427 "move", func = 0x40f180 <cmd_move>}, {cmd = 0x435b30 "ping", func = 0x40df80 <cmd_ping>}, {cmd = 0x4316a9 "quit", func = 0x40ded0 <cmd_quit>}, {cmd = 0x42e425 "remove", func = 0x40ee70 <cmd_remove>}, {cmd = 0x4316ae "sent", func = 0x40e290 <cmd_sent>}, {cmd = 0x42e402 "view", func = 0x40ed30 <cmd_view>}}
            args = 0x379a580
            my_err = 0x0
            ctx = {store = 0x662b10, query = 0x27dfed0}
            do_quit = <optimised out>
            __func__ = "mu_cmd_server"
    #29 0x000000000040fff5 in mu_cmd_server (store=<optimised out>, opts=<optimised out>, err=<optimised out>) at mu-cmd-server.c:1644
            args = 0x379a580
            my_err = 0x0
            ctx = {store = 0x662b10, query = 0x27dfed0}
            do_quit = <optimised out>
            __func__ = "mu_cmd_server"
    #30 0x000000000041071b in with_store (func=0x40fc80 <mu_cmd_server>, opts=0x640e60 <MU_CONFIG>, read_only=<optimised out>, err=0x7fffffffe080) at mu-cmd.c:555
            store = 0x662b10
            merr = <optimised out>
    #31 0x000000000040a30b in main(int, char**) (argc=1, argv=0x7fffffffe188) at mu.cc:122
            err = 0x0
            rv = MU_OK
            conf = 0x640e60 <MU_CONFIG>

I'll see if I can get more info with the Xapian debug symbols.

**Comment by stsquad** [comment]
Another log, this time with Xapian debug symbols

    #0  0x00007ffff630c1c3 in __pread_nocancel () at ../sysdeps/unix/syscall-template.S:84
    #1  0x00007ffff7abfe22 in ChertTable::read_block(unsigned int, unsigned char*) const (__offset=1589755904, __nbytes=8192, __buf=0x3e50290, __fd=<optimised out>)
        at /usr/include/x86_64-linux-gnu/bits/unistd.h:83
            bytes_read = <optimised out>
            offset = 1589755904
            m = 8192
    #2  0x00007ffff7abfe22 in ChertTable::read_block(unsigned int, unsigned char*) const (this=this@entry=0x663868, n=n@entry=194062, p=p@entry=0x3e50290 "")
        at ../backends/chert/chert_table.cc:203
            bytes_read = <optimised out>
            offset = 1589755904
            m = 8192
    #3  0x00007ffff7ac043d in ChertTable::block_to_cursor(Cursor*, int, unsigned int) const (this=this@entry=0x663868, C_=C_@entry=0x45f4f20, j=j@entry=0, n=194062)
        at ../backends/chert/chert_table.cc:379
            p = 0x3e50290 ""
    #4  0x00007ffff7ac085f in ChertTable::find(Cursor*) const (this=0x663868, C_=0x45f4f20) at ../backends/chert/chert_table.cc:534
            j = 1
            p = 0x3e3e200 ""
            c = <optimised out>
    #5  0x00007ffff7a9c3d6 in ChertCursor::find_entry(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x429ee90, key="\000\330\016H", <incomplete sequence \327>) at ../backends/chert/chert_cursor.cc:215
            found = <optimised out>
    #6  0x00007ffff7ac7431 in ChertValueManager::get_chunk_containing_did(unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const (this=0x663e10, slot=14, did=did@entry=541655, chunk="") at ../backends/chert/chert_values.cc:164
            exact = <optimised out>
    #7  0x00007ffff7ac799c in ChertValueManager::get_value[abi:cxx11](unsigned int, unsigned int) const (this=<optimised out>, did=541655, slot=<optimised out>)
        at ../backends/chert/chert_values.cc:476
            i = <optimised out>
            chunk = ""
            first_did = <optimised out>
            reader = {p = 0x0, end = 0x7c00000077 <error: Cannot access memory at address 0x7c00000077>, did = 33, value = <error: Cannot access memory at address 0x3e>}
    #8  0x00007ffff7aab9ae in ChertDocument::do_get_value[abi:cxx11](unsigned int) const (this=<optimised out>, slot=<optimised out>) at ../backends/chert/chert_document.cc:40
    #9  0x00007ffff7a21e4a in Xapian::Document::Internal::get_value[abi:cxx11](unsigned int) const (this=<optimised out>, slot=slot@entry=14) at ../api/omdocument.cc:279
    #10 0x00007ffff7a21e80 in Xapian::Document::get_value[abi:cxx11](unsigned int) const (this=this@entry=0x7fffffffd9c0, slot=slot@entry=14) at ../api/omdocument.cc:59
    #11 0x000000000042c4f9 in mu_msg_doc_get_str_list_field(MuMsgDoc*, MuMsgFieldId) (self=self@entry=0xa4ea1bb0, mfid=mfid@entry=14 '\016') at mu-msg-doc.cc:95
            s = ""
            __PRETTY_FUNCTION__ = "GSList* mu_msg_doc_get_str_list_field(MuMsgDoc*, MuMsgFieldId)"
            __func__ = "mu_msg_doc_get_str_list_field"
    #12 0x000000000041c05a in get_str_list_field (self=0xa4e9ef90, mfid=mfid@entry=14 '\016') at mu-msg.c:259
            val = 0x0
    #13 0x000000000041c5cf in mu_msg_get_references (self=<optimised out>) at mu-msg.c:545
            __func__ = "mu_msg_get_references"
    #14 0x0000000000429731 in mu_threader_calculate (c=0x9f387440, id_table=0x27ed640) at mu-threader.c:242
            refs = <optimised out>
            cur = <optimised out>
            parent = <optimised out>
            created = <optimised out>
            msg = <optimised out>
            docid = 541655
            id_table = 0x27ed640
            id_table = 0x27ed640
            thread_ids = <optimised out>
            root_set = <optimised out>
            __func__ = "mu_threader_calculate"
    #15 0x0000000000429731 in mu_threader_calculate (iter=0xb955c40) at mu-threader.c:349
            msg = <optimised out>
            docid = 541655
            id_table = 0x27ed640
            id_table = 0x27ed640
            thread_ids = <optimised out>
            root_set = <optimised out>
            __func__ = "mu_threader_calculate"
    #16 0x0000000000429731 in mu_threader_calculate (iter=iter@entry=0xb955c40, matchnum=1165991, sortfield=sortfield@entry=16 '\020', descending=descending@entry=1) at mu-threader.c:73
            id_table = 0x27ed640
            thread_ids = <optimised out>
            root_set = <optimised out>
            __func__ = "mu_threader_calculate"
    #17 0x0000000000417efb in mu_msg_iter_new(XapianEnquire*, size_t, MuMsgFieldId, MuMsgIterFlags, GError**) (flags=32767, sortfield=16 '\020', maxnum=500, enq=..., this=0xb955c40)
        at mu-msg-iter.cc:88
            keymaker = {<Xapian::KeyMaker> = {_vptr.KeyMaker = 0xdae8110}, _threadinfo = 0x1}
            descending = true
            threads = true
            iter = <optimised out>
            __PRETTY_FUNCTION__ = "MuMsgIter* mu_msg_iter_new(void**, size_t, MuMsgFieldId, MuMsgIterFlags, GError**)"
            __func__ = "mu_msg_iter_new"
    #18 0x0000000000417efb in mu_msg_iter_new(XapianEnquire*, size_t, MuMsgFieldId, MuMsgIterFlags, GError**) (enq=enq@entry=0x7fffffffdd50, maxnum=maxnum@entry=500, sortfield=sortfield@entry=16 '\020', flags=flags@entry=13, err=err@entry=0x0) at mu-msg-iter.cc:235
            iter = <optimised out>
            __PRETTY_FUNCTION__ = "MuMsgIter* mu_msg_iter_new(void**, size_t, MuMsgFieldId, MuMsgIterFlags, GError**)"
            __func__ = "mu_msg_iter_new"
    #19 0x000000000041df8d in mu_query_run(MuQuery*, char const*, MuMsgFieldId, int, MuQueryFlags, GError**) (flags=29, sortfieldid=<optimised out>, maxnum=500, iter=<synthetic pointer>, self=0x27f4470) at mu-query.cc:492
            orig_set = 0x0
            enq = {internal = {dest = 0x422fb60}, static INCLUDE_QUERY_TERMS = 1, static USE_EXACT_TERMFREQ = 2}
            rel_iter = <optimised out>
            iter = 0x37d0520
            descending = true
            first_flags = <optimised out>
            inc_related = true
            enq = {internal = {dest = 0x3bdbc20}, static INCLUDE_QUERY_TERMS = 1, static USE_EXACT_TERMFREQ = 2}
            __PRETTY_FUNCTION__ = "MuMsgIter* mu_query_run(MuQuery*, const char*, MuMsgFieldId, int, MuQueryFlags, GError**)"
            __func__ = "mu_query_run"
    #20 0x000000000041df8d in mu_query_run(MuQuery*, char const*, MuMsgFieldId, int, MuQueryFlags, GError**) (self=0x27f4470, searchexpr=searchexpr@entry=0x51d3d50 "i:", sortfieldid=<optimised out>, maxnum=maxnum@entry=500, flags=flags@entry=29, err=err@entry=0x7fffffffdee8) at mu-query.cc:552
            iter = 0x37d0520
            descending = true
            first_flags = <optimised out>
            inc_related = true
            enq = {internal = {dest = 0x3bdbc20}, static INCLUDE_QUERY_TERMS = 1, static USE_EXACT_TERMFREQ = 2}
            __PRETTY_FUNCTION__ = "MuMsgIter* mu_query_run(MuQuery*, const char*, MuMsgFieldId, int, MuQueryFlags, GError**)"
            __func__ = "mu_query_run"
    #21 0x000000000040e6bd in cmd_find (ctx=0x7fffffffdef0, args=0x27fcea0, err=0x7fffffffdee8) at mu-cmd-server.c:961
            iter = <optimised out>
            foundnum = 4294958824
            maxnum = <optimised out>
            sortfield = 16 '\020'
            querystr = 0x51d3d50 "i:"
            qflags = 29
    #22 0x000000000040fff5 in mu_cmd_server (err=0x7fffffffdee8, args=0x27fcea0, ctx=0x7fffffffdef0) at mu-cmd-server.c:1595
            u = <optimised out>
            cmd = 0x35a4470 "find"
            cmd_map =
                {{cmd = 0x42e421 "add", func = 0x40e380 <cmd_add>}, {cmd = 0x431676 "compose", func = 0x40f960 <cmd_compose>}, {cmd = 0x42dfa2 "contacts", func = 0x40e840 <cmd_contacts>}, {cmd = 0x42e1d9 "extract", func = 0x40f570 <cmd_extract>}, {cmd = 0x42e3c4 "find", func = 0x40e580 <cmd_find>}, {cmd = 0x4316a3 "guile", func = 0x40efd0 <cmd_guile>}, {cmd = 0x432b77 "index", func = 0x40e980 <cmd_index>}, {cmd = 0x42e3d5 "mkdir", func = 0x40f4d0 <cmd_mkdir>}, {cmd = 0x42e427 "move", func = 0x40f180 <cmd_move>}, {cmd = 0x435b30 "ping", func = 0x40df80 <cmd_ping>}, {cmd = 0x4316a9 "quit", func = 0x40ded0 <cmd_quit>}, {cmd = 0x42e425 "remove", func = 0x40ee70 <cmd_remove>}, {cmd = 0x4316ae "sent", func = 0x40e290 <cmd_sent>}, {cmd = 0x42e402 "view", func = 0x40ed30 <cmd_view>}}
            args = 0x27fcea0
            my_err = 0x0
            ctx = {store = 0x662b10, query = 0x27f4470}
            do_quit = <optimised out>
            __func__ = "mu_cmd_server"
    #23 0x000000000040fff5 in mu_cmd_server (store=<optimised out>, opts=<optimised out>, err=<optimised out>) at mu-cmd-server.c:1644
            args = 0x27fcea0
            my_err = 0x0
            ctx = {store = 0x662b10, query = 0x27f4470}
            do_quit = <optimised out>
            __func__ = "mu_cmd_server"
    #24 0x000000000041071b in with_store (func=0x40fc80 <mu_cmd_server>, opts=0x640e60 <MU_CONFIG>, read_only=<optimised out>, err=0x7fffffffe080) at mu-cmd.c:555
            store = 0x662b10
            merr = <optimised out>
    #25 0x000000000040a30b in main(int, char**) (argc=1, argv=0x7fffffffe188) at mu.cc:122
            err = 0x0
            rv = MU_OK
            conf = 0x640e60 <MU_CONFIG>

**Comment by djcb** [comment]
Seems like a Xapian issue... have you still seen this recently?

**Comment by djcb** [comment]
Does this still happen with the current mu (and xapian)?

**Comment by stsquad** [comment]
@djcb no I think we can close this now.
