### ISSUE TITLE
After send hook

### ISSUE THREAD

**Issue by smythp** [djcb/mu#638]
Is there a hook to be called after a message is sent? I'd like to disable returning to the mu4e main page after composing an email.

**Comment by djcb** [comment]
There's `mail-sent-hook`, but you'll return to wherever you started after composing a message, not necessarily the main page.

**Comment by smythp** [comment]
Thanks! It's been returning to the main page for me, even if I 
call the compose function on a differnt page. But I think I've 
found a workaround. Thanks again.
