### ISSUE TITLE
mu4e in workgroups2

### ISSUE THREAD

**Issue by stvharman** [djcb/mu#640]
Hello, I use workgroups2 to create a GTD screen for myself with my org files and agenda open. I would like mu4e to be a part of this screen as one of the windows.

As far as I can understand, special buffers can be handled and there is some information about how to achieve it: https://github.com/pashinin/workgroups2/wiki/How-to-restore-a-specific-type-of-buffer

I was wondering if anyone could have the knowledge about how to set it up so that windows for the mu4e can appear in a window similar to a dired or shell window. I would greatly appreciate your feedback.

thanks in advance!

- Steve

**Comment by djcb** [comment]
Ah, probably better ask the mailing list.
