### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by jhaubrich** [djcb/mu#641]
Help. I get a segmentation fault here when compiling on Arch Linux. 

```
/bin/sh: line 12:  6650 Segmentation fault      (core dumped) emacs --batch $am__subdir_includes -L . -L . --eval "(defun byte-compile-dest-file (f) \"mu4e-lists.elc\")" --eval "(unless (byte-compile-file \"mu4e-lists.el\") (kill-emacs 1))"
Makefile:625: recipe for target 'mu4e-lists.elc' failed
```
[Complete text here](https://gist.github.com/jhaubrich/b1c36d88e567424f7ab1)
GNU Emacs 24.5.1
gcc (GCC) 5.1.0

I tried killing emacs and moving ~/.emacs.d to no avail.

**Comment by djcb** [comment]
Oh, that doesn't look good! But the problems seems to be with emacs itself (which shouldn't segfault no matter what). Can you get a backtrace from the dumped core?

**Comment by jhaubrich** [comment]
I can reproduce this by running the above in the mu4e directory, but it does not produce a core dump. Grr, not sure where to go from here. Everything I can find online about debugging an emacs segfault assumes you have the core.

Anyways, thanks for the tip. I'll try an earlier version of emacs or recompiling with `--with-x-toolkit=lucid`. I'll close this as it has nothgint to do with mu.

Cheers!

**Comment by jhaubrich** [comment]
Updating the microcode for my intel processor fixed my emacs segfaults. Huzzah!

https://bbs.archlinux.org/viewtopic.php?pid=1547352#p1547352
