### ISSUE TITLE
Unsupported header field (:thread-subject) 

### ISSUE THREAD

**Issue by jagrg** [djcb/mu#643]
I was told that this might be a mu4e issue:

1. M-x helm-mu
2. start typing
3. error:
```
Debugger entered--Lisp error: (error #("[mu4e] Unsupported header field (:thread-subject)" 1 5 (face mu4e-title-face)))
  signal(error (#("[mu4e] Unsupported header field (:thread-subject)" 1 5 (face mu4e-title-face))))
  error("%s" #("[mu4e] Unsupported header field (:thread-subject)" 1 5 (face mu4e-title-face)))
  mu4e-error("Unsupported header field (%S)" :thread-subject)
```

**Comment by djcb** [comment]
What version of mu4e are you using? :thread-subject is fairly new

**Comment by jagrg** [comment]
version 0.9.12

**Comment by djcb** [comment]
It's a problem in ``helm-mu-candidate-formatter``, it's missing thread-subject. In general, the code seems to depend on a bunch of mu4e-internals, which is not recommended.

Please take it up with the helm-mu folks -- thanks!

**Comment by tmalsburg** [comment]
I sent @jagrg over here. Sorry about that.  I don't understand the error but will look into it when I have time (which may not be very soon).

@djcb you say it's not recommended to depend on mu4e internals but what is the alternative? Is there a public API?

**Comment by djcb** [comment]
The error looks quite clear at least :)

There's a lot of public API (everything not starting with ``mu4e~``; but if you're missing something specific, let's see if we can do something about that.
