### ISSUE TITLE
Headers view: add hook for when this window is closed

### ISSUE THREAD

**Issue by shackra** [djcb/mu#644]
Why? In case you want to push the changes you have done in your mail to the server!

I find myself doing <kbd>U</kbd> at \**mu4e-main*\* just to push changes (and pull new emails, again!! ugh) to my three mail servers when [isync](http://isync.sourceforge.net/) supports the flag `--push` to just do a push (which is faster than doing a complete sync between my laptop and those three servers).

Or maybe something like `mu4e-get-mail-command` but for running a command that will just push changes later may be better...

**Comment by djcb** [comment]
Probably easiest to write your own function that runs `mu4e-mark-execute-all` ('x' in the headers view) and then set a timer at a few seconds to do the --push. Then, bind it eg. to 'X'.
