### ISSUE TITLE
types of flag? 

### ISSUE THREAD

**Issue by yitang** [djcb/mu#647]
Hi, I've been using mu/mu4e for a while, and think they are amazing. Thanks for that! 

But I only touched the basis and started reading the mu4e manual and wonder where can I find the manual of mu? I only found the mu cheat-sheet after googling. 

I am particular interested in knowing how many flag types it has, I can only see F, S, NAN etc but don't know what they means.

**Comment by djcb** [comment]
``mu`` is documented in various man-pages, check the ones that start with `mu-`, they should be installed when you install mu/mu4e.

The flags that mu/mu4e support is just something we inherit from what maildir (the format for storing the messages) gives us:
    http://cr.yp.to/proto/maildir.html
