### ISSUE TITLE
mu4e: use 'font-lock-face property instead of 'face

### ISSUE THREAD

**Issue by rgmorris** [djcb/mu#649]
Hi,

Please consider using the 'font-lock-face property instead of the 'face property.
Everything will look exactly the same as it does now (but the value of font-lock-mode will be respected). The motivation is, it makes it possible for users to add their own highlighting.

Eg try:
M-: (font-lock-add-keywords nil '(("the" . font-lock-warning-face)))

in a view buffer. If the standard mu4e highlighting uses the 'face property, it all gets removed.
With 'font-lock-face, it is retained.

Thanks for mu4e!

**Comment by djcb** [comment]
Hmmm.... can you make a pull request?
