### ISSUE TITLE
Reply to encrypted messages should be encrypted by default

### ISSUE THREAD

**Issue by stefanv** [djcb/mu#651]
...or, it should be an option, at least.  Otherwise, it is too easy to reply to an encrypted message and quote the decrypted content in plaintext back to the sender.

**Comment by zakkak** [comment]
Setting `gnus-message-replyencrypt` to `t` should do the trick.  I have the following in my configuration:
```
  (setq gnus-message-replyencrypt t
          gnus-message-replysign t
          gnus-message-replysignencrypted t)
```

> Often, you would like to sign replies to people who send you signed messages. Even more often, you might want to encrypt messages which are in reply to encrypted messages. Gnus offers `gnus-message-replysign` to enable the former, and `gnus-message-replyencrypt` for the latter. In addition, setting `gnus-message-replysignencrypted` (on by default) will sign automatically encrypted messages. 
> -- [source](https://www.gnu.org/software/emacs/manual/html_node/gnus/Signing-and-encrypting.html)

**Comment by stefanv** [comment]
This tip seems like exactly what I need, but after setting it I see no change in behaviour.  Is there a special trick to it?

**Comment by zakkak** [comment]
Hmmm, I am currently using a custom hook that always prompts me whether I would like to sign/encrypt the message before I send it so I cannot really confirm it is working.  My old setup used to be 

```
  (require `epg-config)
  (setq mail-user-agent 'mu4e-user-agent
        mml2015-use 'epg
        mml2015-encrypt-to-self t
        mml2015-sign-with-sender t

        gnus-message-replyencrypt t
        gnus-message-replysign t
        gnus-message-replysignencrypted t
        gnus-treat-x-pgp-sig t)
```

But I still cannot remember if this ever really worked.

**Comment by djcb** [comment]
Not mu4e can do about this, closing...

**Comment by semente** [comment]
@djcb hmm, how could I know if the message I'm replying is signed and/or encrypted so I could call the proper mml functions in mu4e-compose-mode-hook? thanks

**Comment by semente** [comment]
@zakkak it is possible you have `mail-user-agent` set to `gnus-user-agent`, so it is considering the values of the `gnu-message-replysign/encrypt` variables.

**Comment by stefanv** [comment]
I think writing this up in the manual would be a very useful addition.

**Comment by stefanv** [comment]
I see this has also been discussed for notmuch: https://notmuchmail.org/pipermail/notmuch/2014/017719.html
