### ISSUE TITLE
mu4e: Add hooks for closing view and compose buffers (e.g. to change back to monospaced font)

### ISSUE THREAD

**Issue by jaksz** [djcb/mu#653]
## Background
The headers buffer needs a monospaced font for everything to align properly.
The view and compose buffers can profit from a sans/sans-serif font for better legibility.

## Default situation
When you enter the view buffer, you can set a message-view-hook, which correctly sets the font for the view buffer. But if you switch back to the headers view (by pressing ```q```) **everything is now in non-monospaced font and misaligned**.

## My current setup
Right now I have to rely several hacks:

### For when reading mail and switching back to headers view
I changed line 538 in ```mu4e-view-el``` to this:

```
(define-key map "q" (lambda () (interactive) (mu4e~view-quit-buffer) (myfont-mono)))
```

### For when composing mail, when mail is sent
And starting at line 410 in ```mu4e-compose.el``` I did the following:
```
(if message-kill-buffer-on-exit
    (myfont-mono)
    (kill-buffer buf))
```
---

### For when composing mail, when buffer is killed
I couldn't find a place to plug-in my ```myfont-mono``` function, so this is currently the only thing **not working**.

But still, even the working hacks are *hacks*, changing the original files is never an optimal solution, better if I could just change some settings, which is why I filed this issue.

## Screenshots
I have attached two screenshots to give a better idea of what the result will be like:

### Headers in mono
<img width="716" alt="2015-08-18 16 25 31" src="https://cloud.githubusercontent.com/assets/13822469/9332701/39eaeb34-45c6-11e5-947e-e74f65d67127.png">

### View in sans
<img width="720" alt="2015-08-18 16 26 06" src="https://cloud.githubusercontent.com/assets/13822469/9332704/3e5f7c34-45c6-11e5-8efb-846917ae532e.png">

**Comment by djcb** [comment]
Hmmm, using hooks like that doesn't seem to be very robust, since they are separate buffers and might both be visible at the same time.

However, making the font mode-specific should be possible, if we have a view-specific face.

**Comment by jaksz** [comment]
Would that be set up within mu4e or is it a general Emacs setting?

**Comment by djcb** [comment]
It would be mu4e-specific, i.e., right now the message view uses 'default', but if we use a `mu4e-message-face' (or something like that), you could override with whatever you fancy.

**Comment by jaksz** [comment]
Great, would it be possible to implement this?

**Comment by djcb** [comment]
There's mu4e-view-body-face now (in git), so you can set e.g. 
        `(set-face-attribute 'mu4e-view-body-face nil :font "Liberation Serif-10")`
