### ISSUE TITLE
All marked-for-trash mails are moved to trash folder of current account

### ISSUE THREAD

**Issue by cslux** [djcb/mu#654]
I have 3  accounts, my default account is gmail. When I mark mails for trash they are all moved to the gmail trash folder, rather than to the trash folder of the corresponding account. 

I would like, that the gmail emails are moved to the gmail trash folder, the gmx emails are moved to the gmx trash folder etc.. How can I achieve this?

Thanks, Chris

**Comment by djcb** [comment]
See: http://www.djcbsoftware.nl/code/mu/mu4e/Dynamic-folders.html#Dynamic-folders

**Comment by cslux** [comment]
Thank you, that was exactly what I was looking for!
