### ISSUE TITLE
mu4e: BUG: When headers split mode is disabled, you cannot use shortcuts

### ISSUE THREAD

**Issue by jaksz** [djcb/mu#656]
## Reproduction

1. Set ```(setq mu4e-split-view nil)```.
2. Enter headers mode.
3. Select a message.
4. Press ```n``` to move to the next message.

## Expected result
The next message will be displayed.

## Actual result
The error ```Wrong type argument: window-live-p, nil``` will appear in the mini-buffer, and the next message will **not** be displayed.

Running ```mu4e 0.9.12```

**Comment by timwraight** [comment]
I'm seeing this in 0.9.13 as well.

**Comment by djcb** [comment]
Fixed in git.
