### ISSUE TITLE
[Question]How can I change the bracket(<) symbol while replying email?

### ISSUE THREAD

**Issue by henry-y** [djcb/mu#657]
I'm using mu4e.

When I reply, the quoted mail lines all begin with a bracket(<) symbol, such as:

On Thu, Aug 27 2015, ... wrote:

> Hi,
> Test

What should I do to change the bracket to something else, for instance, a tab character?

Many thanks!

**Comment by djcb** [comment]
See: http://comments.gmane.org/gmane.mail.mu.general/1835
