### ISSUE TITLE
Unable to reply to message

### ISSUE THREAD

**Issue by friskgit** [djcb/mu#660]
On certain incoming messages am I unable to reply. The error is:
error in process filter: member: Args out of range: "/", 1, 4
or
error in process filter: Args out of range: "/", 1, 4
or
error in process filter: Args out of range: "/", 1, 5

mu4e version: 0.9.11
emacs 24.3.1
Fedora 20

Attached below is a message that yields this error.

Return-Path: <ylva@xxx.se>
Delivered-To: unknown
Received: from imap.xxx.se (46.30.211.94:143) by
  mnemonic.local with IMAP4; 02 Sep 2015 05:49:31 -0000
Delivered-To: <henrik@xxx.se>
Received: from mx2.public.one.com ([10.246.18.22])
	by mail198.local.one.com (Dovecot) with LMTP id +eKNLVK25VXeOgEAoOiYxA
	for <henrik@xxx.se>; Tue, 01 Sep 2015 14:33:24 +0000
X-HalOne-ID: 66ab77ab-50b6-11e5-91df-b82a72d88088
Received: from mailrelay5.xxx.one.com (unknown [91.198.169.199])
	by mx2.xxx.one.com (Halon Mail Gateway) with ESMTPS
	for <henrik@xxx.se>; Tue,  1 Sep 2015 14:33:24 +0000 (UTC)
X-HalOne-WOD: 861e1b019ef783381c44ffd325e31d0d1b466dc1
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple;
	d=xxx.se; s=20140924;
	h=from:subject:date:message-id:to:cc:mime-version:content-type:
	 content-transfer-encoding:in-reply-to:references;
	bh=5Ls05pXHd9t+RvDyYzBOaCWWK45iAafRFvNPUFYfRjY=;
	b=MQJmSX4BZRHiWzd+6GZMV61h1Fnr3RFs0VK96nhatGMaaLT5Z1nYHLYPEKVklH2b55wi4i4CalIHm
	 9/l74277I2EOfYY5Tyh33U0a94iHoWToji1+5zs0y5O+QeuHMzrCsv0D/WwM31wk43jrD9acRRU7Td
	 3OTBYIIzt/YjHm8E=
Received: from [10.0.1.9] (unknown [80.217.38.68])
	by smtpfilter2.xxx.one.com (Halon Mail Gateway) with ESMTPSA;
	Tue,  1 Sep 2015 14:33:22 +0000 (GMT)
Content-Type: text/plain; charset=utf-8
Mime-Version: 1.0 (Mac OS X Mail 8.2 \(2102\))
Subject: Re: Farewell to KFS
From: =?utf-8?Q?Ylva_Gisl=C3=A9n?= <ylva@xxx.se>
In-Reply-To: <D207A218.39EE8%hinrich.sachs@xxx.se>
Date: Tue, 1 Sep 2015 16:33:22 +0200
Cc: Henrik Frisk <henrik@xxx.se>
Content-Transfer-Encoding: quoted-printable
Message-Id: <74719CFD-6FC9-4A7D-95D5-DFFCA9F67803@xxx.se>
References: <D207A218.39EE8%hinrich.sachs@xxx.se>
To: Hinrich Sachs <hinrich.sachs@xxx.se>
X-Mailer: Apple Mail (2.2102)
X-getmail-retrieved-from-mailbox: Inbox

dear Hinrich,
thanks for your farewell - we missed you in the garden!
I=E2=80=99m off to Gothenburg and Bor=C3=A5s, and back again the 4th, =
maybe we could see each other then?
all best/ylva

> 29 aug 2015 kl. 17:53 skrev Hinrich Sachs <hinrich.sachs@xxx.se>:
>=20
> Dear Ylva, dear Henrik,
>=20
> My sincere apologies for runnig late regarding my farewell lines - =
which I
> had palanned to send b e f o r e the goodbye party, yesterday... =
However, a
> few health related issues still keep me from being back to full work - =
had a
> new eye-exam, which each time cause a 6 hours imediment to see clearly =
(best
> is to sleep) and the advice is to keep screentime/reading down for =
another 3
> weeks.=20
>=20
> Anyhow, very sorry that I missed the event and the people, and you =
guys! And
> maybe the book, which, by the way, doesn't look that bad, Henrik - ;-)
> So I will be in sthlm from monday 31 til fr 4 and hope to be able to =
see you
> somewhere, some of those days. I'll be back in touch when landed in =
Swe.
>=20
> All the best for now, and til soon,
> Warmly
>=20
> Hinrich
>=20
>=20

**Comment by djcb** [comment]
Is this still an issue? Might some other package be involved -- ie. can you start with 'emacs -q', then load mu4e, see if this problem still occurs? Thanks.
