### ISSUE TITLE
configure without makeinfo available should fail, as the build requires it later on

### ISSUE THREAD

**Issue by chaoflow** [djcb/mu#662]
Beyond that, should makeinfo be required for building from release tarballs?

**Comment by djcb** [comment]
Well, the problem is that there are no release tarballs, only the ones that github produces. But the next release will appear in https://github.com/djcb/mu-releases

**Comment by chaoflow** [comment]
Still, configure should fail if makeinfo is not available as it is needed by the build.

**Comment by djcb** [comment]
It seems many GNU packages (e.g. binutils) do it way mu does it, ie., using the 'missing' script that gives you the build-time error. It's a bit hard to reliably know (from configure's perspective) whether the docs need to be (re)built.

So, for now I'm going to leave it at the warning at the end of configure. But sure, patches are welcome.
