### ISSUE TITLE
move mu4e-*.el and org-mu4e.el directly into site-lisp?

### ISSUE THREAD

**Issue by chaoflow** [djcb/mu#663]
Currently mu4e lisp files are installed into a `mu4e` subdirectory of `share/emacs/site-lisp`, which requires adding it to emacs' load-path.

I would expect a package installed into `emacs/site-lisp` to be directly loadable without changing load-path and suggest to move the files.

**Comment by jschwab** [comment]
I've never had to tweak my `load-path`.  I was under the impression that it was searched recursively by default.  With `emacs -q` (so no init file), I see

    load-path
    ("/usr/share/emacs/24.5/site-lisp" "/usr/share/emacs/site-lisp" "/usr/share/emacs/site-lisp/mu4e" ...

**Comment by chaoflow** [comment]
Ad the [manual](http://www.djcbsoftware.nl/code/mu/mu4e/Installation.html#mu4e-and-emacs-customization) describes adding the `mu4e` subdirectory to the load-path, I assumed this is needed and the cause for it not working in my case.

However, I'm packaging mu4e for nixpkgs and there it is not installed into a default location, but one that is configured via site-start.el and currently we seem not to add subdirectories. I'll report back once solved.

**Comment by djcb** [comment]
The directories in `load-path` are not added recursively -- there's not much mu4e can do about that. Perhaps it's possible to add something to site-start.el to recursively add subdirs to load-path

**Comment by jschwab** [comment]
Huh, I wonder why this works for me.  Mysteries!  Sorry for the noise.

**Comment by chaoflow** [comment]
@djcb What do you think about installing the files directly into site-lisp and to not use the subdirectory?

**Comment by djcb** [comment]
@chaoflow: I'd rather not clutter up site-lisp itself; adding a subdirectory is what most packages are doing. And I don't think it is needed.

The trick is to put a file called `subdirs.el` in the site-lisp directory, that loads the subdirectories automatically; at least in my case, emacs itself seems to have installed that file, which contains:
``` lisp
 `(if (fboundp 'normal-top-level-add-subdirs-to-load-path)
    (normal-top-level-add-subdirs-to-load-path))
```
So, I'd suggest you could use the same approach.

**Comment by jschwab** [comment]
@djcb Aha.  This explains my confusion. Thanks.
