### ISSUE TITLE
Propagating "tags" back to the server.

### ISSUE THREAD

**Issue by sje30** [djcb/mu#673]
hi Dirk,

What would you recommend for the following issue?  If I use `mu4e-action-retag-message` then the local file containing the message is indeed edited.  However, when I use mbsync to sync my maildir with the (non gmail) server, the edit does not go back to the server.

What would you recommend to get the changes propagated back?

One option might be to amend `mu4e-action-retag-message` to move the file to a new name; another might be to defer the file move until the database is updated using `mu4e-update-pre-hook`.  I think the problem with moving the file immediately is that the user might then lose sight of the message that they were tagging?

Thanks for the latest release.

Stephen

**Comment by djcb** [comment]
Hmmm... it depends a bit on how the server treats this. If it maps a (sub)maildir to a specific tag (ie., that's what gmail does), you could use that.

The 'retag' action just changes some header-field; mbsync should notice that the message file changed, and send it to the server. Not sure about the mbsync details (maybe there's some option?), but if doesn't do that, you could indeed try to rename the file; the retagging functionality is a bit outside the mu4e-core, so mu4e might not notice until you re-index...

In any case, if mbsync doesn't sync-back your changes to the server, I'd ask the mbsync folks -- it seems like it should do that.

**Comment by sje30** [comment]
Hi, thanks for this Dirk.

I did ask the mbsync team a few days ago; if the message contents (header or body) change, then the filename must change - hence why the tags are not propagating back to the server for me now.

http://sourceforge.net/p/isync/mailman/message/34494928/

So, my current plan is simply to move the message back into the same folder after tagging it.  Will try it out and report back.

**Comment by eklitzke** [comment]
> Hi, thanks for this Dirk.
> 
> I did ask the mbsync team a few days ago; if the message contents (header or body) change, then the filename must change - hence why the tags are not propagating back to the server for me now.
> 
> http://sourceforge.net/p/isync/mailman/message/34494928/
> 
> So, my current plan is simply to move the message back into the same folder after tagging it. Will try it out and report back.

Did this end up working for you? I have the same issue and I'm curious what you found.
