### ISSUE TITLE
User mail adress treated in case-sensitive manner

### ISSUE THREAD

**Issue by andreiltd** [djcb/mu#674]
From manual:

Instead of showing the From: and To: fields separately, you can use From/To (:from-or-to in mu4e-headers-fields as a more compact way to convey the most important information: it shows From: except when the e-mail was sent by the user (i.e., you) - in that case it shows To: (prefixed by To23, as in the example above). To determine whether a message was sent by you, mu4e uses the variable mu4e-user-mail-address-list, a list of your e-mail addresses. 

This will fail if address is  Foo.Bar@pookmail.com and we set list of addresses to be foo.bar@pookmail.com even though servers and resolvers see this as the same name.  Is it correct?

**Comment by djcb** [comment]
Hmmm, while most email providers treat the address as case-insensitive, that's not necessarily always true; from the RFC (http://www.rfc-editor.org/rfc/rfc5321.txt):
    "The local-part of a mailbox MUST BE treated as case sensitive"

Anyway, I've added a note to the docs.

**Comment by dato** [comment]
RFC 5321 defines the SMTP protocol, and hence the case-sensitive mandate refers _to relayed mail in transit_: when relaying, involved servers _must not_ change the casing of the local part of the address, and must retransmit it exactly as it arrived. (They may change other parts of the SMTP dialog, though.)

The RFC does not affect each host’s own policy on whether mailboxes are case-insensitive or not.

As for mail users agent, the RFC would apply in so far as they may perform SMTP transactions. At any rate, it would apply only when sending out mail, but not to the UI.

Just my 2¢. I think it’d be really useful for users if you would change your mind.
