### ISSUE TITLE
multi-part messages

### ISSUE THREAD

**Issue by justmytwospence** [djcb/mu#679]
I can't find any documentation about how to view multipart messages. Mutt has a nice hierarchical view for multipart messages that makes browsing mailing lists really nice. Does mu4e have a way to do this? If not, perhaps adding it could be considered.

**Comment by djcb** [comment]
Not sure I understand what you mean... mu4e supports multipart messages (e.g. an e-mail message with attachments) are shown. Or do you mean a message thread?  Those are supported as well, somewhat similar to how mutt does it.

**Comment by justmytwospence** [comment]
Mutt has a "message thread" type of view within single multipart messages, which comes in handy for digests and such. I've now actually gone through my subscriptions and un-digestified (regurgitated?) them, then set up a sieve filter to tuck them out of the way, so my personal use case is not a problem any more. This is still a feature discrepancy between mutt and mu4e though, albeit a minor one.

**Comment by djcb** [comment]
Okay, this works now with the new (experimental) view mode -- `(setq mu4e-view-use-gnus t)` (before starting mu4e). Finally!
