### ISSUE TITLE
error in process filter: mu4e-error-handler: Error 2: unknown command 'cmd:quit'

### ISSUE THREAD

**Issue by zeltak** [djcb/mu#680]
Hi

after conquering mu4e on arch i now am trying to get it working on debian

i installed today from git following the online mu4e documentation but get the following error?

error in process filter: mu4e-error-handler: Error 2: unknown command 'cmd:quit'
error in process filter: Error 2: unknown command 'cmd:quit'

the gui does start yet i cant see any emails in the header view

any clue

best

Z

**Comment by djcb** [comment]
Seems like a version conflict -- are you trying to combine two versions?

**Comment by zeltak** [comment]
mmm dont think so. ill try tomorrow when im at the office to complety remove mu and reinstall from scratch

thx

Z

**Comment by djcb** [comment]
Any update?

**Comment by zeltak** [comment]
Hi djcb and thx for the respone!

i finally had some time at work today. i uninstalled the current mu4e, manually went through all folders and removed any mu4e files left over. then i reinstalled mu4e using git.

i still get this error

For information about GNU Emacs and the GNU system, type C-h C-a.
error in process filter: mu4e-error-handler: Error 2: unknown command 'cmd:ping'
error in process filter: Error 2: unknown command 'cmd:ping'

using mu4e - mu for emacs version 0.9.15 

any ideas what else to try and debug this?

best

Z

**Comment by djcb** [comment]
The issues seems to be on the server side though; I suspect you have an old 'mu' binary lying around -- ie., what does `mu --version` say? And is that the mu that mu4e is talking to? If necessary, you can set `mu4e-mu-binary` to the correct path.

**Comment by zeltak** [comment]
Hi again

yeah that was the issue! there was another binary hidden from an old ubuntu install :)

seems solved now, thx again!

Z
