### ISSUE TITLE
feature request: mu-version, mu-reload

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#683]
A `mu-version` command that reported the *git branch id* would allow people to verify they are running the latest version.

A `mu-reload` command would let people upgrade mu without having to quit and relaunch emacs. I got this idea from Org which has an `org-reload` function that is quite useful when running the git version.

**Comment by djcb** [comment]
Well, I think it'd be hard to get `mu-reload` to work reliably. `mu-version` might be useful in some cases, but has the limitation that it doesn't take into account any non-committed changes.

So, no plans to work on this, sorry...

**Comment by zakkak** [comment]
Regarding `mu-version` you can achieve this with `--dirty` if you use `git describe` to create the version string.

```
--dirty[=<mark>]
    Describe the working tree. It means describe HEAD and appends <mark> (-dirty by default) if the working tree is dirty.
```
