### ISSUE TITLE
Rename org-mu4e.el

### ISSUE THREAD

**Issue by zakkak** [djcb/mu#685]
Hi @djcb ,

I believe `org-mu4e.el` and `org-old-mu4e.el` should be renamed to `mu4e-org.el` and `mu4e-org-old.el` respectively.  Since they ship with mu4e and not with org it seems more appropriate.

Respectively the functions starting with `org-mu4e-` need to be renamed to `mu4e-org-`.

If you agree with the above I can issue a pull request with the changes.

**Comment by djcb** [comment]
Hmmm, I imagined these files as "things for org that come as part of mu4e"; so that's why they have the org-mu4e prefix. I think I'd like to keep it as it is.
