### ISSUE TITLE
mu4e: X-Mailer in mu4e-header-fields

### ISSUE THREAD

**Issue by f0086** [djcb/mu#687]
Add support to show the X-Mailer header field.
(I liked the plugin https://addons.mozilla.org/en-US/thunderbird/addon/display-mail-user-agent/ for thunderbird, so I think it is not a big deal to add this to the possible values for mu4e-header-fields.)

**Comment by djcb** [comment]
mu does not store that particular header (or User-Agent) in its database, so mu4e doesn't have access to it. It is of course possible to get the particular field by parsing the raw message-file, and getting the header value from there, if you really need it.
