### ISSUE TITLE
Creating a new thread: killing ‘In-Reply-To’ could kill ‘References’ too

### ISSUE THREAD

**Issue by dato** [djcb/mu#688]
It’d be nice if a new thread could be created from a reply.

A standard way to do this e.g. in Mutt is to delete the In-Reply-To header.

But if one does that, and the References header is not visible, the MUA could still kill References on its own.

Thanks for considering.

**Comment by zakkak** [comment]
Hi @dato,

Sounds reasonable.  Do you know if mutt does it this way?  Are other clients doing it?

**Comment by dato** [comment]
I only know about Mutt, and yes it does it this way (i.e. it doesn’t include a References header if the user killed In-Reply-To).

Thanks!

**Comment by djcb** [comment]
I have implemented this in master.
