### ISSUE TITLE
mu: db version: 9.9 but we need 9.9; database rebuild is required

### ISSUE THREAD

**Issue by ReneFroger** [djcb/mu#692]
Mu4e worked for a while. When I couldn't get mu4e in Emacs 25.05 working after moving my Maildir, I decided to remove all the mu and mu4e, downloaded everything with offlineimap. After downloading, I indexed everthing of the default folder `Maildir` in my home director. But mu4e in Emacs is still not working. When calling  `mu find some -name-of-sender`, I get the error:

    database needs a rebuild; try 'mu index --rebuild'
    mu: db version: 9.9, but we need 9.9; database rebuild is required

After rebuilding the index, I try it again with `mu find some -name-of-sender` and then I still get the same error message.

How could I solve this? I tried everything.

**Comment by djcb** [comment]
It appears you are using an old version of mu/mu4e. Can you try with the latest? Ie.
  https://github.com/djcb/mu-releases/blob/master/mu-0.9.13.tar.gz

**Comment by ReneFroger** [comment]
Well, I got the latest version from https://code.google.com/p/mu0/downloads/list

I will try the latest version.

<sup><sub>By the way, have you a Dutch ancrestry? Your name is so Dutch, and very common in Netherlands.</sub></sup>

**Comment by djcb** [comment]
Yeah, that's a bit outdated... but it seems google-code won't allow me to delete without also nuking the mailing-list. Anyway, you'll probably be much happier with the new version.

[ and yes, I'm Dutch :-)]

**Comment by ReneFroger** [comment]
I'll be curious then. I got the link from [this](http://wenshanren.org/?p=111). At this moment I'm downloading all the messages with offlineimap, which takes many hours. 

<sup>Ah, je woont in Finland, en ik kon niks typisch Nederlands op je site vinden. Dus ik begon mij af te vragen of je wellicht eerder een Fin was met een typisch Nederlandse naam. :-)</sup>

**Comment by ReneFroger** [comment]
After installing mu-0.9.13, I started mu4e, I got a weird error

    error in process filter: mu4e-error-handler: Error 1: expected: ’<alphanum>+:’ (ping)
    error in process filter: Error 1: expected: ’<alphanum>+:’ (ping)

When I restart Mu4e again, then I see the main screen. When I go to my inbox,
the header list stays empty. I get no any message or error message whatsoever.

When I do the following in command line:

    mu find foobar

Then I see my messages listed in command line.

I did everything following [this setup](http://wenshanren.org/?p=111), except
it's with mu-0.9.13 and the location is set with  

    (setq mu4e-maildir "~/Dropbox/Mail/Maildir")

and 

    ~ $ mu index --maildir=~/Dropbox/Mail/Maildir
    ~ $ mu index --rebuild --maildir=~/Dropbox/Mail/Maildir

How could I debug this?

**Comment by djcb** [comment]
Seems like a mix of some version of mu/mu4e. Uninstall any remaining old ones, and restart.

**Comment by ReneFroger** [comment]
After figuring out how I could uninstall mu (I know only apt-get remove, which is not to be applied here), I ran `sudo make uninstall` in the directory of mu-0.9.13 and installed it again. But I get same error.

Any tips how I could remove everything which is related to `mu`?

**Comment by djcb** [comment]
Hmmm - first check if there's any part of an older mu/mu4e on your system (both old mu binaries or the elisp installation (the .elc files)). Then install as before; check with `mu --version`.

At that point, you should be able to at least do all the command-line actions (indexing, then searching etc.).

Then, for mu4e, I'd recommend using one of the example configurations from the mu4e docs:
   http://www.djcbsoftware.nl/code/mu/mu4e/Example-configurations.html#Example-configurations
edit as nessary.

After that, (re)start emacs, and things should work.

**Comment by ReneFroger** [comment]
Got it figured out, seems that the contents of `el` files in ELPA folder were from the older Mu4e versions, not from the newest release. Everything is working again!

Thanks for your support, it's really appreciated!

**Comment by djcb** [comment]
Ah, great to hear! Veel plezier.
