### ISSUE TITLE
How do I modify main-view in order to insert a new action?

### ISSUE THREAD

**Issue by shackra** [djcb/mu#696]
That's my question.

**Comment by djcb** [comment]
Your bookmarks are added there, but you can't add new items without changing the mu4e source code.

**Comment by shackra** [comment]
Well, I just needed to run a bash script from main-view, I don't think bookmarks would make it...

**Comment by djcb** [comment]
You can always run some script of course, and bind it to any key in the main-view.

**Comment by shackra** [comment]
How should I do such binding? The manual doesn't say anything about this.

**Comment by djcb** [comment]
It's just a general emacs thing -- ie. you could use something like '(define-key mu4e-main-mode-map (kbd "C-c x") 'your-function)'

**Comment by shackra** [comment]
uh, indeed. I thought something fancier was needed...

**Comment by azzamsa** [comment]
> Your bookmarks are added there, but you can't add new items without changing the mu4e source code.

@djcb I was to open the same question. any plan to make main action customizable ?

something like : 

```elisp
(add-to-list 'mu4e-main-actions '("Do something" . my-function) t)
```
