### ISSUE TITLE
wrong moves in mixed mailbox list

### ISSUE THREAD

**Issue by ksjogo** [djcb/mu#699]
If I mix multiple mails from different mailboxes/accounts in one displayed list and press move/delete, they will only be moved to one of the accounts relative folders. Seems to be taken from the first mail.
The relative folder should be calculated for each mail individually.

**Comment by djcb** [comment]
The concept of multiple accounts is only something for *sending* mail. 

However, if you receive the messages from different accounts into separate folders, you can use set up specific folders for refiling them, see:
    http://www.djcbsoftware.nl/code/mu/mu4e/Smart-refiling.html#Smart-refiling
and
    http://www.djcbsoftware.nl/code/mu/mu4e/Refiling-messages.html#Refiling-messages
