### ISSUE TITLE
Insert signature above previous message, instead below?

### ISSUE THREAD

**Issue by ReneFroger** [djcb/mu#706]
For example, we have the following message structure in Mu4e compose window

    From: Frans Bauer <reserveringen@fransbauer.nl>
    To: vermeer@gelredome.nl
    Subject: Re: Tour 2017
    In-reply-to: <1448271936.5652e04023194@vermeer@gelredome.nl>
    --text follows this line--

    Hi there!

    Some text,

    Greetings,
    []

    Gert Vermeer writes:
    > Quoted
    > Text

`[]` stands for the cursor.

When I call `message-insert-signature` with <kbd>C-c</kbd><kbd>C-w</kbd>, then
my name gets inserted below the quoted text.

I prefer to insert it in the place where the cursor stands. Seems more logic to
me.

Or are there reasons behind this way of structure?

**Comment by zakkak** [comment]
Signatures are prefixed with `--`.  By convention anything following this prefix is considered a comment. As a result if you place your signature above the previous message, both will end up being seen as your signature.

Now, if you do not place the `--` prefix it should be OK, but I guess this is the reason mu4e does it the other way.

**Comment by djcb** [comment]
Indeed, `message-insert-signature` (which we re-use from gnus) places it a the bottom, which is the best place if you're not top-posting but might not be if you do. Not much mu4e can do about that... You could try a function to set it by hand though:
``` lisp 
(defun insert-mu4e-sig-here ()
  "Insert the mu4e signature here, assuming it is a string."
  (interactive)
  (when (stringp mu4e-compose-signature)
    (insert mu4e-compose-signature)))
  ```

**Comment by ReneFroger** [comment]
That works also, thanks for that!

**Comment by tobiasBora** [comment]
I would also be interested by this option. Any news?

**Comment by averter** [comment]
This [thread](http://mu-discuss.narkive.com/07EsaRyq/here-s-how-to-insert-your-signature-before-cited-email) is the closest solution which I was able to find. I couldn't get it to work though

**Comment by duzaichuan** [comment]
The insert-mu4e-sig-here function solves this though. I don't want to insert it manually every time especially when replying messages. Any progress?

**Comment by averter** [comment]
@duzaichuan Can't you then run that function in the `mu4e-compose-mode-hook` ? Should be easy enough. At some point I will try and let everyone know.

**Comment by bradyt** [comment]
Please upvote original message, etc. Developer may not have a sense of how many mu4e users engage in email with general population.

**Comment by averter** [comment]
@M4rkD your solution does not work for me :-(

**Comment by AaronJackson** [comment]
@averter Same for me. Turns out I was letting mu4e read from my `.signature` file, so `mu4e-compose-signature` was not a string (it was `t`). Once I set this to a string, I found @M4rkD 's solution worked for a new email but not when replying to an email. My final solution is disgusting and ended up looking like this:

```
(setq mu4e-compose-signature
      (with-temp-buffer
        (insert "\n--\n")
        (insert-file-contents "~/.signature")
        (buffer-string)))

(defun insert-mu4e-sig-here ()
  "Insert the mu4e signature here, assuming it is a string."
  (interactive)
  (search-forward "--text follows this line--" nil t)
  (insert mu4e-compose-signature)
  (goto-line 1)
  (search-forward "--text follows this line--" nil t)
  (newline))

(add-hook 'mu4e-compose-mode-hook 'insert-mu4e-sig-here)
```

Hopefully someone a bit more skilled in elisp can improve this. The only problem I find now is that the default behaviour when composing a new email is to move the cursor to to the To header line. When replying, the default behaviour is to move the cursor to the body. The snippet above places the cursor in the body for all cases.

**Comment by averter** [comment]
Thanks @AaronJackson . I think I finally managed to crack this one down in an elegant way. I have started by setting this variable
```` elisp
(setq mu4e-compose-signature-auto-include nil)
````
then I have adapted the function in the above forum post and added it to the appropriate hooks while using an input argument to move the cursor to the right place.
```` elisp
(defun message-insert-signature-at-point (pmode)
  "Function to insert signature at point."
  (when pmode (mu4e-compose-goto-top))
  (interactive)
  (require 'message)
  (save-restriction
    (narrow-to-region (point) (point))
    (message-insert-signature))
  (mu4e-compose-goto-top))

;; add them to the hooks with appropriate input arguments
(add-hook 'mu4e-compose-mode-hook (lambda () (message-insert-signature-at-point nil)) t)
(add-hook 'mu4e-compose-pre-hook (lambda () (message-insert-signature-at-point t)) t)
````
This solution adds the signature at the top of the message (above the quoted reply) and is 1) context agnostic, 2) automatically moves the cursor to the right place, both if you're replying to or if you are composing a new message. Let me know if you think this can still be improved.

**Comment by nxtruong** [comment]
> Thanks @AaronJackson . I think I finally managed to crack this one down in an elegant way. I have started by setting this variable
> 
> ```emacs-lisp
> (setq mu4e-compose-signature-auto-include nil)
> ```
> 
> then I have adapted the function in the above forum post and added it to the appropriate hooks while using an input argument to move the cursor to the right place.
> 
> ```emacs-lisp
> (defun message-insert-signature-at-point (pmode)
>   "Function to insert signature at point."
>   (when pmode (mu4e-compose-goto-top))
>   (interactive)
>   (require 'message)
>   (save-restriction
>     (narrow-to-region (point) (point))
>     (message-insert-signature))
>   (mu4e-compose-goto-top))
> 
> ;; add them to the hooks with appropriate input arguments
> (add-hook 'mu4e-compose-mode-hook (lambda () (message-insert-signature-at-point nil)) t)
> (add-hook 'mu4e-compose-pre-hook (lambda () (message-insert-signature-at-point t)) t)
> ```
> 
> This solution adds the signature at the top of the message (above the quoted reply) and is 1) context/signature-type agnostic, 2) automatically moves the cursor to the right place, both if you're replying to or if you are composing a new message. Let me know if you think this can still be improved.

This solution didn't fully work for me: when I composed a new message from scratch (not a reply), it messed up the message (the signature was placed after To: and broke the new message). I fixed this issue by adding `(message-goto-body)` right before the `(save-restriction` line.

**Comment by averter** [comment]
@nxtruong Does the breaking of the message include disappearing text after the `--` symbol? Does it then relate to issue #2031?

**Comment by nxtruong** [comment]
> @nxtruong Does the breaking of the message include disappearing text after the `--` symbol? Does it then relate to issue #2031?

No, the text didn't disappear after the `--` in the signature. The signature was just inserted in the wrong place (after the `To:` field).

**Comment by nic0dk** [comment]
@nxtruong thanks after adding `(message-goto-body)` my reply/forward/new mails getting my signature at top-posting.
