### ISSUE TITLE
mu4e manual documentation correction for multiple accounts

### ISSUE THREAD

**Issue by prsarv** [djcb/mu#707]
A quote mark is missing at starttls in the initial default configuration for [Multiple Accounts](http://www.djcbsoftware.nl/code/mu/mu4e/Multiple-accounts.html#Multiple-accounts) 

It should be
```
http://www.djcbsoftware.nl/code/mu/mu4e/Multiple-accounts.html#Multiple-accounts
---------------------------------------------------------------------------------------
... So set up your environment with e.g., your main account:

(setq ...
      smtpmail-stream-type 'starttls
      ...)

Then create a variable my-mu4e-account-alist, ...
```
This is reported as an error by emacs when it loads the mu4e configuration from ~/.emacs.

**Comment by djcb** [comment]
Can you make a pull request?

**Comment by prsarv** [comment]
Done. See [Pull Request](https://github.com/djcb/mu/pull/708)
