### ISSUE TITLE
Can't pass arbitrary options to "mu index"

### ISSUE THREAD

**Issue by avar** [djcb/mu#709]
I wanted to pass the option to adjust the max msg size. I looked through the source and tried this with "mu server" manually and it only understands --path.

**Comment by djcb** [comment]
Yeah, that's not currently supported.

**Comment by sinewalker** [comment]
I'd like to add --nocleanup since mu's taking minutes to reindex old message that I don't plan on deleting. I tried adding .noupate file to the maildir in question but this is not preventing the cleanup.  Or is there a way to do this that I've missed in the manual?

**Comment by djcb** [comment]
There's an option for --nocleanup in mu4e now; see the recent commits.

As the original rfe here, together with the 'lazy-check' and increased memory-limit, I'll close this now.
