### ISSUE TITLE
Index the content of encrypted messages

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#712]
An increasing number of my contacts are starting to encrypt their emails.  One problem that this creates in the context of mu/mu4e is that the content of encrypted email is not indexed and this means that mu/mu4e lose their killer feature (powerful search).  For this reason, it is desirable to have support for the indexing of encrypted content. 

There are two issues related to this feature that need to be discussed:

**1.) PGP/MIME vs inline-PGP**

PGP/MIME is already supported in mu.  So I suppose treatment of emails using this format shouldn't be hard.  However, there is no support for inline-PGP in mu and it is not clear how it could be added (see  #594, #59).  Inline-PGP is considered bad style these days, so it perhaps doesn't have high priority.  Also it might be possible to convert inline-PGP to PGP/MIME in a preprocessing step (suggested by [here](https://github.com/djcb/mu/issues/594#issuecomment-161887429) by @djcb). In this case, the problem is factored out and mu doesn't have to worry about inline-PGP.

**2.) Indexing encrypted content means that the index contains cleartext.**

In some settings this is not much of a problem but in others (shared systems) it may be.  This can be addressed in two ways: a) Indexing of encrypted mails should not be the default but rather be an informed and conscious decision made by the user. b) The index could be encrypted using the user's PGP key.

**Comment by cpitclaudel** [comment]
Regarding 2), couldn't the index be encrypted?

**Comment by tmalsburg** [comment]
Didn't I propose that in the last sentence? ;-)

**Comment by cpitclaudel** [comment]
Ah, indeed :)

**Comment by thomasf** [comment]
I would probably prefer to mount the index on an encrypted volume if I were to enable something like this. Having said that, 2.b is still an interesting option to have.

**Comment by tmalsburg** [comment]
Isn't an encrypted volume less safe?  Other applications can access it while it is mounted.  Encrypting the file means that only mu can read it.

**Comment by zakkak** [comment]
I agree with @tmalsburg on this.  Encrypting the index on its own with a key you use for e-mail purposes should me more secure than using an encrypted volume that usually gets decrypted upon user login.

**Comment by thomasf** [comment]
I would of course manually monunt and unmount that volume when I need it.
The security/confidentiality context isn't that all that different from having an open gpg agent session.. You still have to trust the system configuration and it's administrators before handling any confidential information at all anyway. 
 I actually already have my offlineimapped maildir and mu index on it's own encrypted volume which I mount/unmount when entering or exiting mu4e.

**Comment by cpitclaudel** [comment]
@tmalsburg @zakkak There's no reason that an encrypted volume should be less safe, if things are done properly. Mu could be made to run under its own user, and that user only would have read permissions on the decrypted index contents. In @thomasf's case, however, there is a risk that say a vulnerabilty in an unrealted app would allow a program to run with @thomasf's permissions, and to read the decrypted index.

In any case, both the encrypted file and encrypted mountpoint strategies will be vulnerable to a nosy admin; that's probably acceptable.

**Comment by zakkak** [comment]
@thomasf it would be nice if you could add your configuration on the *Appendix D Tips and Tricks* section of the manual for other people that might be interested in your approach.

@cpitclaudel that's true. I just find it easier to have a different pgp key than having a different user and a different volume for the e-mails.  This is subjective though.

I believe I can deliver this feature before January.  I will just allow the indexer to decrypt the pgp/mime encrypted messages.  The main logic should already be available from `mu view`.  To enable this feature the user will have to set a custom variable to `t`, to avoid *unsafe* default behavior.  Additionaly, It would be nice if the documentation could be extended with one or two ways to encrypt your index to avoid having encrypted files indexed as plaintext.

**Comment by hendi** [comment]
@zakkak have you made any progress on this, any branch that you could share?

**Comment by zakkak** [comment]
@hendi, unfortunately not. I never started working on it and I don't think I will be able to do it any time soon.

**Comment by djcb** [comment]
I'd rather keep decrypting -> index and various measure to make that (a bit) secure out of 'mu`. If you really want to do that, I'd recommend doing it outside of mu (perhaps through `procmail`) or something like that.

**Comment by jgoerzen** [comment]
Late to the party, I know, but it surprises me that mu already supports PGP/MIME. I can't find that reference anywhere in the source, other than mu-verify and in mu4e.  Can mu really index stuff that is PGP/MIME-encrypted already?  If so, how?  If not, I guess one might need to have a command that could specify a filter so that it could decrypt the messages before handing off?

**Comment by djcb** [comment]
Yeah, mu can decrypt / verify messages, and it can index them, but the message won't be decrypted during indexing... so you cannot search them by their contents.

**Comment by falematte** [comment]
I think that this is really a problem for mu users...
