### ISSUE TITLE
Is there a reason for why :status messages are sent when mu4e-hide-index-messages is t?

### ISSUE THREAD

**Issue by avar** [djcb/mu#715]
It seems like a lot of chatter in the protocol could be eliminated if the `:status' messages weren't sent when `mu4e-hide-index-messages' is on.

I noticed this because I'm watching what's going on in the `*mu4e-log*` buffer to debug something, and it'll get a lot of noise every `mu4e-update-interval'.

**Comment by avar** [comment]
This is solved with pull request #722.

**Comment by djcb** [comment]
Thank you & appreciate the work, but not going to take the PR... closing this.
