### ISSUE TITLE
Make the status reporting hardcoded at every 1k messages customizable

### ISSUE THREAD

**Issue by avar** [djcb/mu#716]
See also issue #715. This is currently hardcoded at 1000 in the source, and both this and showing this at all could be arguments to cmd:index.

**Comment by avar** [comment]
This is solved with pull request #722.

**Comment by djcb** [comment]
Thanks for that, but it seems like a lot of extra complexity / changes for little improvement, or?

**Comment by avar** [comment]
I wanted to hack on this before working on the more general issue of issue #709. This makes the debug log a lot more usable for me, and I think in general if mu4e doesn't need something from mu its should pass an option along to suppress that.

**Comment by djcb** [comment]
As discussed in the PR, I think it's a bit too much extra complexity for little gain; still, appreciate the work, thank you!

**Comment by avar** [comment]
If you don't want this pull request do you think you wouldn't like if I implement issue #709 either? The patch for that will likely look very much the same.

I don't really need to customize this, I just want to quite it, do you think you'd take a patch that would just make the hardcoded 1000 number a ./configure time define so I could just pass --report-processed-every=0 or something?
