### ISSUE TITLE
Error trying to build on Fedora 23

### ISSUE THREAD

**Issue by hammerheadlemon** [djcb/mu#720]
Am trying to build from source on Fedora 23:

`aclocal`
`autoheader`
`automake --add-missing`
`autoconf`

`./configure`
gets error `config.status: error: cannot find input file: `Makefile.in'`

Not much experience building with autotools (actually, this is my first time!) - also new to Fedora having been a Debian user for some time. Package in Debian repo makes everything easy but doesn't appear to be a usable rpm for Fedora. Any help appreciated. Thanks!

**Comment by avar** [comment]
Did you first do `autoreconf`: https://github.com/djcb/mu/blob/master/HACKING#L119 ?

**Comment by cslux** [comment]
Hey, I also use Fedora 23, here are my steps for a successful
build/installation.

cd ~/Downloads
git clone https://github.com/djcb/mu.git
cd mu
autoreconf -i
mkdir build
cd build
../configure --prefix=/usr
make -j9
sudo make install

Regards,
Christian

**Comment by hammerheadlemon** [comment]
Thanks guys - will give these a go tomorrow morning and report back.

**Comment by hammerheadlemon** [comment]
Guys - thanks both. Now successfully built and installed. Didn't think to look in HACKING.... All the best.
