### ISSUE TITLE
Automatically opening messages

### ISSUE THREAD

**Issue by cpitclaudel** [djcb/mu#725]
Hi,

I'm still looking at mu4e, considering transitioning from Thunderbird.
I find it a bit cumbersome that the point moves to the message view after opening an email. In TB, moving around the message list displays the currently selected message (marking it read after a few seconds).

I managed to implement something similar in mu4e by adding a local post-command hook that calls `mu4e-headers-view-message`. I also had to change  `mu4e-headers-view-message` and `mu4e-view` slightly.

This still isn't fully ideal (there are timing issues where moving too fast, and contrary to what the docstring claims `mu4e-headers-view-message` doesn't reuse the existing window, causing a lot of flickering), but I'd be happy to discuss a patch if you're interested in this feature.

Clément.

**Comment by djcb** [comment]
Hmm, the idea is that point is in the message view, so I can e.g. scroll through the message; and you can still switch to previous/next message with `p` and `n`. Not sure what is 'cumbersome' about that?

**Comment by cpitclaudel** [comment]
Thanks for the clarification; I hope the comment didn't sound like criticism.

One thing that `p` and `n` don't really cater to is moving around the list by skipping entries. For example if I'm reading a threaded discussion with new messages, I like to see the full discussion so I can go back and forth for context, but I still want to mostly focus on unread entries. The way Thunderbird handles this is that the space key scrolls down in the `view` buffer, moving to the next unread message in the list when the bottom of the current message is reached.

Is this a kind of interaction that wouldn't work well in mu4e (I don't have much experience with it :)? Or are you interested in patches that could make this possible?

**Comment by djcb** [comment]
No problem, constructive criticism is welcome :-)

Anyway, from you writing I suppose it's not so much the view-mode getting focus, but rather that you miss some keybinding? In both header and view you can jump to the prev/next unread with [ and ] (`mu4e-view-headers-(next|prev)-unread`).

**Comment by cpitclaudel** [comment]
Ah, indeed, I missed these keys. Thanks for pointing them out; that's convenient!
I guess I was mostly surprised as I moved from Thunderbird to mu4e to see the point move to the view window when I opened an email. I the point is in the email list window, I can already scroll up and down in the email view window with `C-M-v` and `C-M-S-v` (and in Thunderbird, with `SPC`).
More generally, I guess I was surprised by the idea of "opening" an email; in Thunderbird just clicking an email or navigating to it in the list displays it in the bottom pane.

**Comment by djcb** [comment]
Oh, seems github ate my `[` and `]`. 

It should be possible to do something like you mention with going to the next (unread) messages when reaching the end of the current one; I'll keep that in mind when I find some time :-)

**Comment by cpitclaudel** [comment]
Great, thanks! If you want, I'll also be happy to try and contribute a patch that makes mu4e reuse the view buffer instead of deleting it and recreating it every time a mail is opened.

**Comment by djcb** [comment]
Sure, a patch would be welcome!
