### ISSUE TITLE
Encoding tags are not processed if sender name doesn't include email brackets (<>)

### ISSUE THREAD

**Issue by cpitclaudel** [djcb/mu#726]
Hi,

Sorry if this was in the documentation. Given the following email, `mu` shows `=?utf-8?q?Some_=7C_Name?=` as the sender, instead of `Some | Name` (Thunderbird displays the latter as expected). This is due to a malformed header (mu works fine with `=?utf-8?q?Some_=7C_Name?= <a@b>`). I have no idea why some emails that I have in my mailbox have these invalid headers. Is it worth fixing?

```
Content-Type: multipart/mixed; boundary="===============7245124686030397241=="
MIME-Version: 1.0
From: =?utf-8?q?Some_=7C_Name?=
Subject: =?utf-8?q?Test_subject?=

--===============7245124686030397241==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

VGVzdA==

--===============7245124686030397241==--
```

Thanks!

**Comment by djcb** [comment]
The decoding is done in the gmime library, so that's probably the best place to handle this.
I think the function to look at is `decode_address` in `internet-address.c`.

**Comment by cpitclaudel** [comment]
Thanks. I'll consider raising this issue there then :) In the meantime this can be closed.
