### ISSUE TITLE
Headers are not always decoded

### ISSUE THREAD

**Issue by cpitclaudel** [djcb/mu#728]
Hi there,

I'm running into issues with the `List-Id` header. When it is stored as quoted-printable, `mu4e` doesn't decode it. For example, it shows:

```
=?utf-8?q?Example_of_List_Id?=
```

Instead of decoding this to

```
Example of List Id
```

This decoding works fine for other headers, such as the `From` header.

**Comment by djcb** [comment]
Ah, yes. Fixed in master.

**Comment by cpitclaudel** [comment]
Wonderful. Thanks :)
