### ISSUE TITLE
Less useful fancy chars after recent commits

### ISSUE THREAD

**Issue by avar** [djcb/mu#733]
I don't think they're all bad but I think we're worse off to some extent after 90d2b8a and ddcd2f3.

I think the usefulness of this feature is not to use non-ASCII for the fun of it, but to actually immediately convey more information because we're showing some sensible icon. If we're not conveying more info than the ASCII equivalents let's just use the ASCII.

So some of the changes were:

mu4e-headers:

 * Flagged: ⚑ -> ✚. Good: Symetrical with the + keybinding, Bad: No longer a flag. Also it's just Unicode cross at this point, if we're making it symmetrical with + instead of having a flag icon shouldn't we just use plain +?
* New: ⭑ => ✱. Looks good.
* Trashed: ♻ -> ✀. Going froma  recycling icon to scissors, that doesn't really convey "trashed" to me, but maybe that's just me. I think 🗑 would be better.
* Unread: ☐ -> 🖂. Good. Especially with ☐ being unread now and ⬛ read.
* Duplicate: ⚌ -> ≡. Fine, but I wonder if we shouldn't just use ASCII = here.

mu4e-mark:

* Delete: 🗙 -> ⭙. FWIW for a X cross-like thingy the former looks clearer in my font, but maybe we want it boxed. Although maybe we should be using 🗑 = Trash and ✀ = Delete
* Flag: + -> ✚. I don't mind it really, but as noted above I don't see the point.

The rest I don't mind of they're covered in the mu4e-headers comments.

**Comment by zakkak** [comment]
I mostly agree with @avar. 

I don't see, however, why the marks should be different than the headers in some cases. I would personally prefer them to be the same.

I really liked the flag icon ⚑. I also like the close envelope for unread messages 🖂, however, it looks bigger than the rest probably causing missalignment.  The scissors ✀ are kind of confusing for trashed messages (and for deleted as well), although it could be related to some short of shredding I guess.  Finally I find the trash icon 🗑 hard to read, but ♻ was also not very clean for me.

**Comment by djcb** [comment]
Sure, agreed - the default fancy characters should be:

a) somehow convey what they mean
b) look clear/crisp (some of the unicode chars get really blurry/unclear. So, the trash-icon isn't the best I think, nor is the recyle-icon). The unicode big + looks nicer than the ascii one imho.
c) widely supported (so they'll 'just work' for almost all users). The big X sadly does not work for that, even if it looks nicer than the circled-X.

So, the goal is to come with a set that satisfies all of those criteria :-)

**Comment by zakkak** [comment]
Are you using some tool to check c) ?  Or simply testing with various fonts?

**Comment by tpapp** [comment]
Could we perhaps get a variable for directly setting the delete mark (like eg `mu4e-headers-flagged-mark`), instead of
```lisp
(setcdr (plist-get (cdr (assq 'delete mu4e-marks)) :char) "×")
```

**Comment by avar** [comment]
@tpapp Something similar got mentioned on the mailing list. Yes this should suck less, the reason it sucks is because I wrote it and I don't use customize and generally have no idea what I'm doing other than cargo-culting when it comes to writing Elisp.

I made the variable either a string or a tuple for backwards compatibility with existing customization, but maybe that's not the right move.

**Comment by tpapp** [comment]
Regarding Dirk's [latest e-mail](https://groups.google.com/d/msg/mu-discuss/77WIFjGwQvk/57L6lNLyCQAJ): I can see everything, but 
```lisp
        (defvar mu4e-headers-trashed-mark   '("T" . "✀") "Trashed.")
        (defvar mu4e-headers-unread-mark    '("u" . "🖂") "Unread.")
        (defvar mu4e-headers-first-child-prefix  '("\\" . "┗▶") "First child.")
```
are oversized with `Dejavu Sans Mono` and mess up the alignment of columns in the headers view. ┗▶ is particularly gigantic.

**Comment by djcb** [comment]
@zakkak just trying with a few tools. Perhaps DejaVu/Liberation could be the benchmark
@tpapp that's a good point -- the symbols should also align nicely.

**Comment by zakkak** [comment]
In my case 🖂 (closed envelope) is not available in any of my fonts, not even *Liberation Mono*, which is weird :S.  I am changing the fonts using `set-frame-font`. Any hints?

**Comment by cpitclaudel** [comment]
@zakkak I use Symbola for most symbols; it has the envelope in particular.

**Comment by cpitclaudel** [comment]
Here are the symbols I use for flags, btw:

  '((mu4e-headers-draft-mark     . ("D" . "📝 ")) ;; ✒ ✏
    (mu4e-headers-flagged-mark   . ("F" . "🏴 "))
    (mu4e-headers-new-mark       . ("N" . "★ "))
    (mu4e-headers-passed-mark    . ("P" . "→ ")) ;; ↪
    (mu4e-headers-replied-mark   . ("R" . "← "))
    (mu4e-headers-seen-mark      . ("S" . "")) ;; ✓ 🗸 ✔
    (mu4e-headers-trashed-mark   . ("T" . "✗ ")) ;; 🗑
    (mu4e-headers-attach-mark    . ("a" . "📎 "))
    (mu4e-headers-encrypted-mark . ("x" . "🔐 "))
    (mu4e-headers-signed-mark    . ("s" . "🔏 "))
    (mu4e-headers-unread-mark    . ("u" . "✉ "))

**Comment by zakkak** [comment]
@cpitclaudel @djcb the problem with `(set-fontset-font "fontset-default" 'unicode "Symbola")` is that although it fixes the symbols for me, it changes the font used for greek (unicode) text, as well.

**Comment by cpitclaudel** [comment]
@zakkak Does the following work?

```
(set-fontset-font fontset 'unicode (font-spec :name "YOUR-FAVOURITE-FONT") nil)
(set-fontset-font fontset 'unicode (font-spec :name "Symbola") nil 'append)
```

**Comment by cpitclaudel** [comment]
@zakkak Otherwise you can tell Emacs to use symbol just for mu4e's status indicators, by using variants of the following line:

`(set-fontset-font fontset (cons ?✉ ?✉) "Symbola")`

**Comment by zakkak** [comment]
@cpitclaudel the first approach actually does the trick, thanks!

I had to slightly change it to:

``` lisp
  (set-fontset-font "fontset-default" 'unicode (font-spec :name "YOUR-FAVOURITE-FONT") nil)
  (set-fontset-font "fontset-default" 'unicode (font-spec :name "Symbola") nil 'append)
```

**Comment by cpitclaudel** [comment]
@zakkak Teh first version that I posted was indeed incorrect. The edited version should do just the same as yours, however :) For extra monospace goodness, you may be interested in my comment on https://github.com/djcb/mu/issues/677

**Comment by djcb** [comment]
So, there's an updated set of fancy characters that should work with most setups; and still users can replace them if they want. Closing this....

**Comment by zakkak** [comment]
Hi guys,

I just found that [unicode-fonts](https://github.com/rolandwalker/unicode-fonts) works best for me:
``` lisp
(use-package unicode-fonts
  :commands unicode-fonts-setup
  :config
  (use-package persistent-soft)
  )
(unicode-fonts-setup)
```

**Comment by cpitclaudel** [comment]
Indeed, unicode-fonts does the same as I listed above, just with a lot more fallbacks

**Comment by zakkak** [comment]
I added it to the manual's Tips and Tricks section as well #755.
