### ISSUE TITLE
FR: List maildir shortcuts on the main view

### ISSUE THREAD

**Issue by f0086** [djcb/mu#736]
It would be nice to have some sort of *tree* (or a flat list) of folders which have unread messages. I sort my mails into different folders on the server side with procmail, so I have no idea which folder has unread messages. A folder for "show me all unread messages" is not an option, because some folders are full of unimportant mails (like mailinglists, status mails, ...) and some folders can contain important mails (friends, family, ...). So a list on the main view would be extremely handy.

The free space on the main view is (imho) not used very wisely. Things like the "Misc" section are used once in a year (except q and U, which is going into muscle memory on day 1).

**Comment by nicolasavru** [comment]
https://github.com/agpchil/mu4e-maildirs-extension may do what you want.

**Comment by f0086** [comment]
Thanks, that is perfect!
