### ISSUE TITLE
mu4e-context.el not copied to installation directory

### ISSUE THREAD

**Issue by devogon** [djcb/mu#739]
When installing mu from source, mu4e-context.el is not copied over to the install dir. As a result mu4e will not run in emacs. Copying the file manually to the ~/x/emacs/site-lisp/mu4e dir fixes the problem.

**Comment by djcb** [comment]
Did you autoreconf -i && ./configure first?

**Comment by devogon** [comment]
I did. After copying a fresh copy of the repo, and starting fresh, though, everything worked just fine so it was something in my local copy.
