### ISSUE TITLE
worked with fetchmail.

### ISSUE THREAD

**Issue by zw963** [djcb/mu#741]
mu version: 0.9.13 
system: ubuntu.
I fetch mail with fetchmail. fetchmail is worked, all mail is saved to ~/Maildir/INBOX.

like this:
```sh
$: pwd
/home/zw963/Maildir/INBOX
$: ls
msg.5N4aN  msg.Ap9KN  msg.DizKN  msg.gCnaN  msg.j0GLN  msg.luSiM  msg.OpLLN  msg.RlBLN  msg.uH_KN  msg.xBWGM
msg.5nDLN  msg.apHLN  msg.dIZXN  msg.GCnaN  msg.J0GLN  msg.LuSiM  msg.oPlZN  msg.rlCZN  msg.UhQiM  msg.XBWGM
msg.5nGoN  msg.ApHLN  msg.DIZXN  msg.GdhKN  msg.j0iXN  msg.luUiM  msg.oq0ZN  msg.rLEXN  msg.Ui2YN  msg.xC8KN
msg.5oLLN  msg.apLLN  msg.dJgaN  msg.gDOLN  msg.j0-kN  msg.LuUiM  msg.Oq0ZN  msg.rLGLN  msg.uIgaN  msg.XC8KN
msg.5p5KN  msg.ApLLN  msg.DJgaN  msg.ge0KN  msg.J0PLN  msg.lv1KN  msg.oQ7KN  msg.RlnaN  msg.UI_KN  msg.xcfKN
```

And when I create index, it nothing happen.
```sh
$: mu index --maildir=/home/zw963/Maildir
indexing messages under /home/zw963/Maildir [/home/zw963/.mu/xapian]

cleaning up messages [/home/zw963/.mu/xapian]
\ processing mail; processed: 0; updated/new: 0, cleaned-up: 0
elapsed: 0 second(s)
| processing mail; processed: 0; updated/new: 0, cleaned-up: 0
elapsed: 0 second(s)
```

But , if create a new directory /home/zw963/Maildir/cur, and copy all msg into this directory, and 
run again, it worked now.

```sh
$: mkdir -p /home/zw963/Maildir/cur
$: copy /home/zw963/Maildir/msg* /home/zw963/Maildir/cur
$: mu index --maildir=/home/zw963/Maildir
indexing messages under /home/zw963/Maildir [/home/zw963/.mu/xapian]
/ processing mail; processed: 6750; updated/new: 6750, cleaned-up: 0
cleaning up messages [/home/zw963/.mu/xapian]
| processing mail; processed: 6780; updated/new: 0, cleaned-up: 0
elapsed: 0 second(s)
/ processing mail; processed: 6780; updated/new: 0, cleaned-up: 0
elapsed: 9 second(s), ~ 753 msg/s
```

I think this is a bug? Thanks.

**Comment by zw963** [comment]
en ....
 more questions.

Do you know website `www.djcbsoftware.nl` could not open from HongKong/China ?

Thanks.

**Comment by djcb** [comment]
So - for the first question, mu/mu4e require the mail to be in Maildir format, so you need to set up fetchmail to that; see e.g.,
  http://www.ioncannon.net/system-administration/97/using-fetchmail-and-procmail-for-maildir-style-storage-from-a-pop3-account/

As for question 2... I have no idea.

**Comment by zw963** [comment]
I have resolve this, Thanks.  instead of use fetmail, i use getmail instead. Thanks.

for question 2:   I use proxy from hongkong to view free world,  I could not open your's site,
but I can open any opened website I know.

When I found this email agent, very happy, I have to view document with google cache ... 
it is not cool ... so, just for confirm, your's website could access from internet ??

**Comment by zw963** [comment]
if this not worked, could you please send me a email about mu4e documents?

I am so excite to replace mu4e for GNUS just know, GNUS is too complicate and slow.

my email: zw963@163.com, Thanks.

**Comment by djcb** [comment]
Oh, you can find the mu4e reference manual from the release repo:
   https://github.com/djcb/mu-releases

**Comment by zw963** [comment]
It is so fancy!!  I have already read this.

this document is the most understooding documents about some emacs package since I use emacs!!

**Comment by zw963** [comment]
it the best email package I used. Thanks.
