### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by zobi8225** [djcb/mu#742]
Hi, 
I have rename some folder in gmail, it make some bug with offlilineimap , i delete some maildirs to force the re-sync.
And now, i have this bug....  
i don't know what i can do and how i can solve it...
> mu index
> mu: symbol lookup error: mu: undefined symbol: _ZN6Xapian16WritableDatabaseC1ERKSsi

Sorry for my bad english

**Comment by djcb** [comment]
seems like a xapian linking error. if you compiled mu yourself, try recompiling, otherwise, ask whoever did that... e.g. your distro.

**Comment by zobi8225** [comment]
Ok thx
> $uname -a
> Linux mutationis 4.2.8-1-MANJARO #1 SMP PREEMPT Tue Dec 15 08:34:13 UTC 2015 x86_64 GNU/Linux

**Comment by zobi8225** [comment]
And 
> xapian-compact --version
> xapian-compact - xapian-core 1.2.21
