### ISSUE TITLE
mu4e doesn't seem to play nice with offlineimap draft sync

### ISSUE THREAD

**Issue by Gastove** [djcb/mu#745]
I open `mu4e`, and draft an email. It gets saved correctly to the drafts folder of my maildir, and the next time `OfflineIMAP` runs, the draft is in my drafts folder on the web, and also on every other computer syncing email. So far, so good. 

But now I work on that draft more in `mu4e`, and save it. These changes do _not_ propagate. As I understand it from the folk at OfflineIMAP, the draft will need a new name in order to be seen as having new content (issue [here](https://github.com/OfflineIMAP/offlineimap/issues/283). 

Thoughts? Not sure if this is a known property of the way `mu4e` is designed (more of a wontfix) or a bug or just a todo for future versions of the software.

**Comment by djcb** [comment]
It seems (to me at least!) that the right solution would be for offlineimap to recognize any change in the file, not just a new name. A workaround on mu4e's side, ie. changing the draft name all the time, seems a bit hacky... 

You could of course write a little script that renames the files based on their filetime, and run that just before you run offlineimap.

Did you try 'mbsync' as an alternative to offlineimap?

**Comment by Gastove** [comment]
Interesting -- have not looked at `mbsync`. I was surprised at oflineimaps' behavior myself (expected it to run off, say, `mtime`). 

Well. This seems like not your problem. I might look in to writing a `mu4e` plugin to provide this behavior... if I can't find a less weird solution :P 

Thanks for the excellent software!

**Comment by djcb** [comment]
Okay - good luck!
