### ISSUE TITLE
Use `org-email-link-description` from org for creating link description

### ISSUE THREAD

**Issue by slackorama** [djcb/mu#747]
Org has a function for formatting links to emails: `org-email-link-description`

Using it seems relatively painless:

    diff --git a/mu4e/org-mu4e.el b/mu4e/org-mu4e.el
    index c02fb2a..cf2dea2 100644
    --- a/mu4e/org-mu4e.el
    +++ b/mu4e/org-mu4e.el
    @@ -113,8 +113,8 @@ Example usage:
                                 :date date-ts-ia
                                 :date-timestamp date-ts
                                 :date-timestamp-inactive date-ts-ia
    -                            :subject subject
    -                            :description (funcall org-mu4e-link-desc-func msg))
    +                            :subject subject)
    +        (org-add-link-props :description (org-email-link-description))
             link))))
     
     (org-add-link-type "mu4e" 'org-mu4e-open)

If this looks OK, I'll submit a pull request and remove the docs and code for `org-mu4e-link-desc-func`.

**Comment by djcb** [comment]
Sure -- please do.
