### ISSUE TITLE
[Feature Request] Use regexp in Bookmarks

### ISSUE THREAD

**Issue by zw963** [djcb/mu#748]
I want to filter out all email which subject include some Chinese character.
(e.g. add all mail which subject include Chinese character to a new bookmark)
I know the `regexp' should be used in emacs,but i don't found this function, 
and it is seem like hard to achieve with elisp function in this case.

Thanks

**Comment by djcb** [comment]
mu/mu4e don't use regexp for such searches, but instead the xapian-based query language. See: http://www.djcbsoftware.nl/code/mu/mu4e/Queries.html#Queries

However, it doesn't work too well for Chinese (and other CJK languages) at the moment, see: issue #544.

**Comment by zw963** [comment]
Thanks, and more question.

how to settings a base exclude/include pattern in all bookmarks?
e.g. in any case, I don't want to see any had read email in all bookmarks.
and i dont't want add  `AND flag:unread' to all my bookmarks.

**Comment by djcb** [comment]
Well, you need to add that somehow, but you can add:
``
(dolist (bm mu4e-bookmarks)
  (setcar bm (format "(%s) AND flag:unread" (car bm))))
``
after defining your mu4e-bookmarks.

**Comment by zw963** [comment]
Thanks, it worked.

I use your hack write a little function, to match my requirement.

```cl
(defun add-github-watch (list)
  (let ((pattern (car list)))
        (dolist (bm mu4e-bookmarks) (setcar bm (format (concat "(%s) AND NOT (" pattern ")") (car bm))))
        (add-to-list 'mu4e-bookmarks list)
        ))
```

What I need is distinguish all my bookmarked message(watch in github, and add a new bookmark in mu4e) with other watched github message.

so, when I do this:
```cl
(setq mu4e-bookmarks '(("from:*github.com" "GitHub" ?g)))
(add-github-watch '("list:elixir.elixir-lang.github.com OR phoenix.phoenixframework.github.com" "Elixir" ?e))
```
with create bookmarks like this:
```cl
(("list:elixir.elixir-lang.github.com OR phoenix.phoenixframework.github.com" "Elixir" ?e)
 ("(from:*github.com) AND NOT (list:elixir.elixir-lang.github.com OR phoenix.phoenixframework.github.com)" "GitHub" ?g))
```

I hope this is some feature will support in future version mu4e。

for clarify, just some bookmarks exclusively each other.
