### ISSUE TITLE
Odd/even version numbers

### ISSUE THREAD

**Issue by dunn** [djcb/mu#749]
In `NEWS` it says
> odd minor version numbers are for development versions; thus, 0.9.16 is to be the next stable release.

But "16" is the patch number there, assuming it's major.minor.patch.  Or is the numbering scheme different?

**Comment by djcb** [comment]
Nope, the .16 is the release number. We don't (usually) use patch numbers.

**Comment by dunn** [comment]
Good to know, thanks!
