### ISSUE TITLE
add thread fold/unfold

### ISSUE THREAD

**Issue by zabbal** [djcb/mu#75]
Ability to fold/unfold thread via single click and hotkey will make UI much cleaner and convenient to use - especially in case of ML where long heated threads are not uncommon thing.

**Comment by sachdevaprash** [comment]
I was wondering where this is at and if I can help complete this. Do we have a good idea on the strategy to employ for this feature?

**Comment by zakkak** [comment]
@sachdevaprash please follow #783

**Comment by zabbal** [comment]
https://gitlab.com/ambrevar/mu4e-conversation - this seems to be related.

**Comment by seanfarley** [comment]
Damn, this notification really got my hopes up. Much like the rest of 2020, it was a disappointment.

**Comment by zabbal** [comment]
Pardon, wasn't my intention to give false hopes :)

There's incomplete implementation in PR#783 and there's rather complete implementation of a related thing in mu4e-conversation - I don't know enough elisp to bring those together but some ideas in the latter (using org-mode code for folding for example) seem like they could be useful to fill in gaps in the former.

**Comment by seanfarley** [comment]
I think the two features are orthogonal: this issue is, to my understanding, about folding a thread in the header view (something similar to what `notmuch` does). `mu4e-conversation` implements threading in the main view (the body of the emails). Both are useful, for sure, but I'm more interested in folding threads in the header view.

**Comment by djcb** [comment]
The headers view is quite complicated already, I think it would benefit from being split in a generic tree-view-like widget, and then the mu4e-specific logic.

Perhaps something like https://github.com/kiwanami/emacs-ctable or something else.

**Comment by seanfarley** [comment]
That makes sense, @djcb. I assume the goal would be something like `emacs-ctable` would handle the folding, correct?

**Comment by rougier** [comment]
I've setup a small project at https://github.com/rougier/mu4e-thread-folding for folding/unfoldong threads in headers view.
It is based on overlay. Note this is not foolproof, but usable until  the ctable version. One problem is with `(mu4e~headers-get-thread-info msg 'thread-id)` that does not seem to return a unique id when there are a lot of thread.

**Comment by djcb** [comment]
Thread-folding has been merged in master, so finally closing this.

**Comment by stefanv** [comment]
This is huge! Thank you @djcb, @zabbal, @rougier!

**Comment by djcb** [comment]
> > Thread-folding has been merged in master, so finally closing this.
> 
> Thanks! but how to use it and from which version? Since the message came from "Apr 23, 2023", I think 1.10.7 should contain it, but I'm not sure how to use it.

Ah, no, see https://github.com/djcb/mu/blob/master/NEWS.org
It'll be in the next stable release (1.12).

**Comment by shamefulCake1** [comment]
Bless you for this change!
