### ISSUE TITLE
[Feature Request]   add a bookmark can filter `ruby' `mruby' `cruby' 

### ISSUE THREAD

**Issue by zw963** [djcb/mu#752]
Hi, I want to add a bookmark, it should automatic filter out any in my
subject or content with `ruby`, `cruby`, `mruby` etc. 
the point is: it should match any word which `ruby' inside.

I try following, not work for me.

>> (add-to-list 'mu4e-bookmarks '("ruby" "Ruby" ?r))
>> (add-to-list 'mu4e-bookmarks '("*ruby" "Ruby" ?r))

btw: I sent this problem to `mu-discuss@googlegroups.com`, and it told me
get the target server successful, but i am not get any response several days.
so, I want to know,  what wrong with this maillist address ? thanks.

**Comment by djcb** [comment]
The query language supports '*'-wildcards, but only at the _end_ of a term... so you could search for `ruby*` but not for `*ruby`. That's a limitation of Xapian that we can't easily get around I'm afraid...

You can automate it with a bit of lisp of course...
```
(let ((c ?a) (s "ruby"))
  (while (<= c ?z) (setq s (format "%s OR %cruby" s c)) (incf c))
  s)
```



Don't know about what's causing the mailing-list problem, seems to work just fine here.

**Comment by zw963** [comment]
1. If can support regexp query is the best.

2. I just use my mu to sent mail to maillist.
   perhaps google block the mail from china as plam ?

Thanks.

Dirk-Jan C. Binnema writes:

> The query language supports ''-wildcards, but only at the end of a term... so
> you could search for `rubybut not for*ruby`. That's a limitation of Xapian that
> we can't easily get around I'm afraid...
>
> You can automate it with a bit of lisp of course...
>
> (let ((c ?a) (s "ruby"))
>   (while (<= c ?z) (setq s (format "%s OR %cruby" s c)) (incf c))
>   s)
>
> Don't know about what's causing the mailing-list problem, seems to work just
> fine here.
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Geek, Rubyist, Emacser
Homepage: http://zw963.github.io

**Comment by djcb** [comment]
1. sadly, that's not supported.
2. I don't know, sorry..
