### ISSUE TITLE
[Feature Request]   when open bookmark with binding, update index.   

### ISSUE THREAD

**Issue by zw963** [djcb/mu#754]
I hope a feature add to mu4e, when open one bookmark with binding
update index immediately. 

I don't know other guys if make mistaken in this point.
But, I always spend time to search my email and forget
to update index.

I set auto update index in mu4e with mu4e-update-interval 300
, but it not enough though.

**Comment by zw963** [comment]
I add following script to my config, it seem like work for me.

```cl
(add-hook 'mu4e-headers-mode-hook
          (lambda ()
            (mu4e-update-mail-and-index t)
            ))
```

But, I think this is a better idea to automation this.

**Comment by djcb** [comment]
Hmmm, re-indexing mail whenever you go to headers mode seems a bit heavy, not something for general use...  So the hook you added is the best solution, I think.
