### ISSUE TITLE
Changing dictionary language automatically

### ISSUE THREAD

**Issue by jagrg** [djcb/mu#756]
I want to change the dictionary language automatically based on the contact field information. The idea is to create a list of contacts which mu4e is able to recognise and decide on which dictionary to use. The following works well when replying, but not when composing. Would you have any idea how I could achieve this?

```emacs-lisp
(setq my-list '(("name1@example.com")
		("name2@example.com")
		("name3@example.com")))

(add-hook 'mu4e-compose-pre-hook
	  (defun mu4e-change-dictionary-language ()
	    (let ((msg mu4e-compose-parent-message))
	      (when msg
		(if (or (mu4e-message-contact-field-matches msg :to my-list)
			(mu4e-message-contact-field-matches msg :from my-list))
		    (ispell-change-dictionary "brasileiro"))))))
```

**Comment by whirm** [comment]
Maybe using flyguess and `(add-hook 'mu4e-compose-mode-hook 'flyguess-guess)`?

**Comment by jagrg** [comment]
@whirm thanks for the suggestion, but I would rather not use a separate package for this. As in the example below, one solution is to advice `message-goto-body` (`C-c C-b`), which works well, except it needs to check the entire list and not just the car as it does now.

```emacs-lisp
(setq my-list-2 '("name1@example.com"
		  "name2@example.com"
		  "name3@example.com"))

(defadvice message-goto-body
    (after message-goto-body-after activate)
  (mu4e-compose-mode-dic-language))

(defun mu4e-compose-mode-dic-language ()
  (interactive)
  (let ((contact (car my-list-2)))
    (save-excursion
      (goto-char (point-min))
      (if (re-search-forward contact nil t)
	  (ispell-change-dictionary "brasileiro")))))
```

**Comment by djcb** [comment]
Yeah, you can't use a pre-hook when you compose a new message, as you don't know the recipients yet. You could of course ask user (in `mu4e-compose-pre-hook`) if it's not able to figure it out. Alternatively, you could set up some timer that checks the recipients every n seconds. That has the advantage that the dictionary can change when you change the recipients.

Of course, it's gets hairy when there are multiple recipients with different languages. In that case, guessing the language might be useful. Perhaps searching for some very common English / Portuguese words would be good enough. Or indeed, flyspell-guess might do that work for you...

**Comment by jagrg** [comment]
FYI: Below is what I ended up doing after learning about iteration (`while` and `pop`). Now whenever I reply to anyone on the list, the dictionary changes accordingly. The same happens when composing a new message, in which case the function is called when moving to the body of the message (namely `message-goto-body`). I also included a common Brazilian TLD to the list, which assumes the conversation will be in Portuguese, and a few common Portuguese words as well. The regexp was borrowed from [auto-lang](http://www.marquardt-home.de/auto-lang.el). BTW, thanks for your work with `mu/mu4e`!

```emacs-lisp
;; change dictionary language automatically when COMPOSING

(defadvice message-goto-body
    (after message-goto-body-after activate)
  (mu4e-compose-change-dictionary-language))

(defun mu4e-compose-change-dictionary-language ()
  (setq x my-list-2)
  (let ((y (car x)))
    (save-excursion
      (goto-char (point-min))
      (while x
	(if (re-search-forward y nil t)
	    (ispell-change-dictionary "brasileiro"))
	(setq y (pop x))))))
```

```emacs-lisp
;; change dictionary language automatically when REPLYING

(add-hook 'mu4e-compose-mode-hook
	  (defun mu4e-change-dictionary-language ()
	    (setq x my-list-2)
	    (let ((msg mu4e-compose-parent-message)
		  (y (car x)))
	      (when msg
		(while x
		  (if (or (mu4e-message-contact-field-matches msg :to y)
			  (mu4e-message-contact-field-matches msg :from y)
			  ;; search for common words
			  (save-excursion
			    (re-search-forward (concat "\\<\\(" (regexp-opt
								 (append
								  common-portuguese-words
								  nil)) "\\)\\>") nil t)))
		      (ispell-change-dictionary "brasileiro"))
		  (setq y (pop x)))))))


(setq common-portuguese-words
      '("escreveu" "enviada" "que" "não" "prezado" "abç"
	"abraço" "obrigado" "obrigada" "beijo" "bjs"))
```

**Comment by edumerco** [comment]
Dear Jonathan.

While I didn't tried yet, It seems an excellent idea, thanks for your work.
Please bear in mind that "que" is the same in spanish, and quite a common
word too. ;)

Best...

--
eduardo mercovich

 Donde se cruzan tus talentos
 con las necesidades del mundo,
 ahí está tu vocación. (Aristóteles)

**Comment by jagrg** [comment]
@edumerco, thanks for the feedback. AFAICT common words are only useful for the dictionaries you intend to use. In my case that's English and Portuguese, so hopefully I won't have any problem. Month names might also be good words to add as they are usually included on the header of the message.

**Comment by edumerco** [comment]
Hi Jonathan.

> @edumerco, thanks for the feedback. AFAICT common words are only useful
for the dictionaries you intend to use. In my case that's English and
Portuguese, [...]

You're absolutely correct. :)

> Month names might also be good words to add as they are usually included
on the header of the message.

Great idea! So much, in fact, that (from my POV) it deserves to be made
more generally appliable.

Something that comes in mu4e but the user enables it, and select her/his
languages... which come with a simple/short dictionary as you did...

What do you think? :)

--
eduardo mercovich

Donde se cruzan tus talentos
con las necesidades del mundo,
ahí está tu vocación.  (Aristóteles)

**Comment by jagrg** [comment]
@edumerco there seems to be quite a few packages designed with a similar purpose already, so I doubt that something like this would ever be included in mu4e. In my case, I just thought it would be simple enough to do it myself. Maybe I could share the code (gist?) and add a few user variables as you suggest. I'll think about it. Does the code work for you?

**Comment by edumerco** [comment]
Hi Jonathan. 

> [@edumerco](https://github.com/edumerco) there seems to be quite a few
> packages designed with a similar purpose already, so I doubt that
> something like this would ever be included in mu4e.

I didn't knew, thanks for that information. 

> In my case, I just thought it would be simple enough to do it myself.
> Maybe I could share the code (gist?) and add a few user variables as
> you suggest. I'll think about it. Does the code work for you?

Didn't tried it yet, I will in a couple weeks... 

Best. 


-- 
eduardo mercovich 

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. (Aristóteles)
