### ISSUE TITLE
Add message view action to download URL in email

### ISSUE THREAD

**Issue by inigoserna** [djcb/mu#757]
I often receive emails in plain text with links to some files I want to download.
As they are not HTML emails I can't use eww (open in browser) to view the message and download links, also open URL ('g' key binding) open a new buffer and doesn't behaviour well with compressed files when saving, so I copy the URL to kill-ring ('k' key binding), open eshell and download the file one by one manually with wget.

A simple approach could be something like:

    (defun mu4e-view-download-url (&optional multi)
      "Offer to download urls(s). If MULTI (prefix-argument) is nil,
    download a single one, otherwise, offer to download a range of URLs.
    It saves downloaded items to the same dir of attachments."
      (interactive "P")
      (let* ((path (concat (mu4e~get-attachment-dir) "/")))
        (mu4e~view-handle-urls "URL to download" multi
                               (lambda (url)
                                 (url-copy-file url (concat path (file-name-nondirectory url)))
                                 (mu4e-message "Downloaded %s" url)))))

Do you think it would be useful to include it in mu4e?

**Comment by djcb** [comment]
Sure - but perhaps you could package it as an 'action'? Also, perhaps `mu4e-view-for-each-uri` would useful in implementing this?

**Comment by inigoserna** [comment]
The problem I have with "action" is that I don't know how to handle 'multi' parameter (i.e. optionally pass prefix-argument), as "action" functions are selected from a menu and receive 'msg' as first parameter. My elisp skills are so limited.

    (defun mu4e-action-view-download-url (msg &optional multi)
      (interactive "P")

does not accept C-u when selecting this action.

On the other hand `mu4e-view-for-each-uri` is not useful in my case because I need to select specific links to download, not all.

**Comment by djcb** [comment]
Makes sense. 

I've slightly changed your code and included it as `mu4e-view-fetch-url` (I'm using 'fetch' so we can have an mnemonic 'f' keybinding); available in master. Thanks!

**Comment by inigoserna** [comment]
Thanks to you!
