### ISSUE TITLE
It seems mu4e is eating the dots in mail wrote by Japanese people.

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#759]
See https://github.com/emacs-helm/helm/issues/1322

And here the mail read in mu4e (only first lines) :

>Hello, thanks for the helm-locate
>I am able to run helm-locate on Windows 7 Pro Japanese with esexe
>134686 (Everythingexe command line) and am able to match Japanese
>filenames if the following is
>done:

**Comment by thierryvolpiatto** [comment]
Hmm, maybe it is not a mu4e bug but just github badly formatting mails, as the raw message doesn't contain the dots too.

**Comment by djcb** [comment]
I don't really what see the exact issue is here -- ie.,
a) what's expected
b) what actually happens
in sufficient detail so we can possibly do something about it. 

And yeah, raw email would help.

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> I don't really what see the exact issue is here -- ie.,
> a) what's expected

In the text sent, I expect "Everything.exe" and "es.exe".

> b) what actually happens

In the text sent I have:
"Everythingexe" and "esexe".

> in sufficient detail so we can possibly do something about it.
>
> And yeah, raw email would help.

Is this part enough ? If not how can I send it to you ?

--8<---------------cut here---------------start------------->8---
----==_mimepart_568d21b94e9a7_53be3ff5734b52a0631c1
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hello, thanks for the helm-locate
I am able to run helm-locate on Windows 7 Pro Japanese with esexe 134686 (Everythingexe command line) and am able to match Japanese filenames if the following is done:
--8<---------------cut here---------------end--------------->8---


Thanks.

-- 
Thierry

**Comment by djcb** [comment]
As you say, I see 'esexe' here as well. So, if that's a part of the raw message, then I don't really see how this is a mu4e issue. However, if you have raw message with 'es.exe' but mu4e showing it as 'esexe', please reopen and attach the raw message as a whole -- thanks!

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> As you say, I see 'esexe' here as well. So, if that's a part of the
> raw message, then I don't really see how this is a mu4e
> issue.

Was my thought too but wanted your confirmation, thanks.

-- 
Thierry
