### ISSUE TITLE
global-mode-string

### ISSUE THREAD

**Issue by justmytwospence** [djcb/mu#760]
Currently mu4e clobbers `global-mode-string`. It would be nice if it only appended to it. 

Even better would be an additional way to inhibit placing mu4e info into the `global-mode-string` and instead insert it explicitly anywhere they like.

**Comment by justmytwospence** [comment]
Just noticed Issue #740, which was getting at the same thing. That issue was closed with a change that only co-opted the global-mode-string in the correct buffers, which is good, but I propose making two additional changes:

1. Append to global-mode-string by default, as suggested originally in #740.
2. Create a variable that can be set to nil to disable anything being placed in the global-mode-string.

**Comment by djcb** [comment]
Okay, fixed now, with PR #934.
