### ISSUE TITLE
Discussion: Switching mu4e-contexts after starting composing

### ISSUE THREAD

**Issue by andersjohansson** [djcb/mu#761]
This is perhaps more of a discussion of how mu4e-contexts works or should work than a feature request.
I started configuring mu4e with version 0.9.9.13 but recently wanted to use some of the great features added in master (configurable header-display, thanks @cpitclaudel).

I have multiple accounts that I need to configure in different ways, and with the recent implementation of `mu4e-contexts`, that is of course the way to go. Before seeing this though, I had been using [gnus-alias](https://github.com/hexmode/gnus-alias) with some success (needing a few hacks to make it work with mu4e).

The feature that I will miss from `gnus-alias` when going over to `mu4e-contexts` is the ability to switch "aliases" when I have already started composing a message. I have two "work" email-addresses (aliases) connected with my account (having the same server config) and find it especially useful to be able to switch between these "identities" *after* starting to compose a new message or a reply.

I can do this with `gnus-alias-select-identity`, which alters headers, signatures etc. in the compose-buffer, but not in any simple way with `mu4e-contexts`, which as far as I understand works by setting things up before the compose-buffer is initialized.

Would it be a bad idea to be able to switch context while composing a message, and edit the message buffer in the same way as `gnus-alias-select-identity`, altering from-address, signature etc?

I guess what I will probably do now is hack together some solution for switching address and signature, reusing parts of gnus-alias, since this is all I need for now for switching between the two work-addresses (I shouldn't probably be switching between work and home when composing anyway).

But the question remains, should context-switching be possible when composing? And should it alter the message-buffer? What this would mean for multiple open message-buffers is of course a problem in that case. (But what happens when the context is switched with open message buffers now anyway?)

**Comment by andersjohansson** [comment]
Apparently, open message buffers are not affected by context switches. We have to be sure to use the right context (server-variables) when sending every message.

I actually like the way I had it working with `gnus-alias`, where the logic can be explained more as associating each message-buffer with a context/alias, meaning it is always sent in the right way.

I did this by letting `gnus-alias` set the extra header `X-Message-SMTP-Method: smtp ServerName Port User`, which is interpreted by `smtpmail`. This doesn't contain `smtpmail-stream-type`, so as I needed this to be different for my accounts I had to advice `smtpmail-via-smtp` as well:
````emacs-lisp
(defun aj/temp-smtpmail-stream-type (fun &rest r)
  (let ((smtpmail-stream-type
         (cond 
          ((string= smtpmail-smtp-server "smtp.googlemail.com") 'ssl)
          ((string= smtpmail-smtp-server "localhost") 'plain)
          (t smtpmail-stream-type))))
    (apply fun r)))

(advice-add 'smtpmail-via-smtp :around #'aj/temp-smtpmail-stream-type)
````
In this way, every message buffer had an associated configuration.

**Comment by djcb** [comment]
Oh, I think something like this might make it to the context system; ie.:
- make the context (-variables) buffer-local in compose-buffer
- dynamically change headers (such as From: ) when switching in such a buffer

Not for the mu 0.9.16 release though. The new system is complicated enough as it is, it will be good to get some more feedback "from the field" after it's in an official release.

**Comment by andersjohansson** [comment]
Oh, thats nice to hear. Thanks for your efforts!
I believe that buffer-local variables will not suffice, though. As I remember it, the message is sent from a buffer copy, so for instance smtp variables need to be set wider than the compose buffer. This is a good thing with the `X-Message-SMTP-Method`-header. This is similar to the situation with org-mode exports, where the `#+BIND:`-header is available to overcome the problem.

**Comment by djcb** [comment]
We're working on this in #776.

**Comment by andersjohansson** [comment]
Closing this in favour of #776.
