### ISSUE TITLE
The mu4e-html2text-command interface has no facility to pass along the encoding

### ISSUE THREAD

**Issue by avar** [djcb/mu#763]
When we call the `mu4e-html2text-command` command we write out the `:body-html` to a tempfile and then:

```
 (call-process-shell-command mu4e-html2text-command tmp-file t t)
```

I find that for the most part `html2markdown` is better than `w3m`
etc. See [this ML
post](https://groups.google.com/forum/?fromgroups#!topic/mu-discuss/0QIgZ27x3Is)
but on some messages all I get is:

```
Traceback (most recent call last):
  File "/usr/bin/html2markdown", line 9, in <module>
    load_entry_point('html2text==2014.9.25', 'console_scripts', 'html2text')()
  File "/usr/lib/python2.7/dist-packages/html2text/__init__.py", line 1083, in main
    data = data.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 53939: invalid start byte
```

The reason for this is that the HTML part looks like this:

```
Content-Type: text/html; charset="Windows-1252"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DWindows-1=
252">
[...]
```

And we don't pass that it's windows-1252 encoded to html2markdown,
this can be done as:

```
html2markdown <file> <encoding>
```

And if we pass "Windows-1252" here this just works. Now, the issue we
have is twofold:
- I can't see anywhere in `msg` a field like
  `:body-html-encoding`. AFAICT to get this we'd have to teach the mu
  server to parse this out and return it over the protocol.
- Even if we have the encoding how should we pass it to the command?
  The html2markdown command wants it as its second argv parameter,
  the w3m command has a -I command-line option for it. Presumably
  we'd have to make `mu4e-html2text-command` into an optional lambda
  or something which would take the detected encoding (and maybe
  message?) and return a command string & any extra arguments to
  pass.

Until we have a fix for this I'm just switching back to w3m, I find
that in any case it's good enough except for including links, and for
that I can always just view the original message in the browser.

**Comment by djcb** [comment]
Well, body-txt and body-html are supposed to be utf-8 encoded. So even if the original mail had a different encoding, those should already be decoded by the time we see them in body-html.

If you've found some messages where that's not the case, could you attach one? Thanks!

**Comment by avar** [comment]
Sorry about the late reply, I can't attach any of the raw E-Mails
since it's all from my work inbox so I can't share it publicly, but I
think I can provide enough to show what the bug is about. Here's a
document where I get:

    UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 2716: invalid start byte        

96 (hex 150) in windows-1252 is the "en dash" (–), but it's U+2013 in
Unicode or \xe2\x80\x93 in UTF-8.

The raw E-Mail looks like this:
    
    <abbreviated headers>
    Content-Type: multipart/related;
     boundary="_004_0FA1B816189D2B4AB66B09AED253D96A01081E74LHR4EXMB02corpa_";
     type="multipart/alternative"
    MIME-Version: 1.0
    Subject: <cut but contains> =?utf-8?q?=3D=3FWindows-1252=3FQ=3F<quoted printable>
    <abbreviated body>
    --_004_0FA1B816189D2B4AB66B09AED253D96A01081E74LHR4EXMB02corpa_
    Content-Type: multipart/alternative;
    	boundary="_000_0FA1B816189D2B4AB66B09AED253D96A01081E74LHR4EXMB02corpa_"
    
    --_000_0FA1B816189D2B4AB66B09AED253D96A01081E74LHR4EXMB02corpa_
    Content-Type: text/plain; charset="Windows-1252"
    Content-Transfer-Encoding: quoted-printable
    
    Some text =96 blah blah...
    
    
    --_000_0FA1B816189D2B4AB66B09AED253D96A01081E74LHR4EXMB02corpa_
    Content-Type: text/html; charset="Windows-1252"
    Content-Transfer-Encoding: quoted-printable
    
    <html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
    osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
    xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" xmlns=3D"http:=
    //www.w3.org/TR/REC-html40">
    <head>
    <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DWindows-1=
    252">
    [....]
    </head>
    <body lang=3D"EN-US" link=3D"#0563C1" vlink=3D"#954F72">
    <div class=3D"WordSection1">
    <p class=3D"MsoNormal"><span style=3D"font-size:12.0pt">Some text =
     =96 blah blah...
    [...]

When I mu-view the file and run it through hexdump -C I get the
sequence "20 e2 80 93 20" (space - space) for the en dash, i.e. the
UTF-8 sequence.

When I look at \*mu4e-log\* it's already decoded, and M-x describe-char
returns:

                 position: 2 of 3 (33%), column: 1
                character: – (displayed as –) (codepoint 8211, #o20023, #x2013)
        preferred charset: unicode (Unicode (ISO10646))
    code point in charset: 0x2013
                   script: symbol
                   syntax: _ 	which means: symbol
                 category: .:Base, c:Chinese, j:Japanese
                 to input: type "C-x 8 RET HEX-CODEPOINT" or "C-x 8 RET NAME"
              buffer code: #xE2 #x80 #x93
                file code: #xE2 #x80 #x93 (encoded by coding system utf-8)
                  display: terminal code #xE2 #x80 #x93
    
    Character code properties: customize what to show
      name: EN DASH
      general-category: Pd (Punctuation, Dash)
      decomposition: (8211) ('–')

*But* when I patch mu4e-message-body-text to not delete the tempfile
it creates and hexdump -C that file it contain "20 96 20", i.e. the
windows-1252 sequence.

I don't know how that happens, but I think the \*mu4e-log\* Window
somehow magically encodes it to UTF-8 for me, but if I strace the mu
server process while I get the message it'll include:

    read(9, "<...> =96 <...>"[...]

And :body-html in `mu4e-message-body-text` is that raw escaped
quoted-printable HTML and not the UTF-8 version.

**Comment by djcb** [comment]
The contract is that all the data in the message plists we get from `mu` is utf-8 encoded - and if need be - any decoding/recoding is done on the `mu` side, not in `mu4e`. So, I wonder what's going on here. 

It's easier to analyze with an actual valid message though - can you take one of your raw-emails, remove any secret information / email-addresses (replace with foo@example.com or something like that), and with a stripped down body that shows this problem? It might be even become part of some unit test. Thanks!

**Comment by avar** [comment]
Sorry about the late reply, here's a minimal testcase. The md5sum
should be 40450102d9bd0a7d949d8fd218fb269b once you s/^ //g and save
it to a textfile, but in any case the important thing is the character
set / quoted printable.
    
    From: Bug <bug@example.com>
    To: Bug <bug@example.com>
    Subject: Download the app! 
    Message-ID: <123456789@dath.example.com>
    Content-Type: multipart/related;
    	boundary="_whatever_";
    	type="multipart/alternative"
    MIME-Version: 1.0
    
    --_whatever_
    Content-Type: multipart/alternative;
    	boundary="_whatever_1_"
    
    --_whatever_1_
    Content-Type: text/plain; charset="Windows-1252"
    Content-Transfer-Encoding: quoted-printable
    
    Don=92t miss out!
    
    --_whatever_1_
    Content-Type: text/html; charset="Windows-1252"
    Content-Transfer-Encoding: quoted-printable
    
    <html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
    osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
    xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" xmlns=3D"http:=
    //www.w3.org/TR/REC-html40">
    <head>
    <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DWindows-1=
    252">
    <meta name=3D"Generator" content=3D"Microsoft Word 15 (filtered medium)">
    
    </head>
    <body lang=3D"EN-US" link=3D"#0563C1" vlink=3D"#954F72">
    <p class=3D"MsoNormal"><b><span style=3D"font-size:20.0pt;font-family:&quot=
    ;Arial&quot;,sans-serif;color:#1F497D">Don=92t miss out!</span></b></p>
    </body>
    </html>
    
    --_whatever_1_--

**Comment by djcb** [comment]
Thanks.

I've tested this a bit. Ultimately, what's passed to the html2text command is this:

```
<html xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" xmlns:m=\"http://schemas.microsoft.com/office/2004/12/omml\" xmlns=\"http://www.w3.org/TR/REC-html40\">
<head>
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=Windows-1252\">
<meta name=\"Generator\" content=\"Microsoft Word 15 (filtered medium)\">
<!--[if gte mso 9]><xml>
<o:shapedefaults v:ext=\"edit\" spidmax=\"1027\" />
</xml><![endif]--><!--[if gte mso 9]><xml>
<o:shapelayout v:ext=\"edit\">
<o:idmap v:ext=\"edit\" data=\"1\" />
</o:shapelayout></xml><![endif]-->
</head>
<body lang=\"EN-US\" link=\"#0563C1\" vlink=\"#954F72\">
<p class=\"MsoNormal\"><b><span style=\"font-size:20.0pt;font-family:&quot;Arial&quot;,sans-serif;color:#1F497D\">Don’t miss out!</span></b></p>
</body>
</html>
```
which is valid utf8 (not Window-1252). This displays fine with the programs I tried -- "html2text", the built-in eww browser and other web browsers (firefox and the webkit-based widget). 

So, perhaps html2markdown gets confused by the 'charset=Windows-1252', not sure. You can try by removing that line (you could put that even as a shell expression in mu4e-html2text). 

Alternatively, I would recommend setting mu4e-html2text to 'mu4e-shr2text (if your emacs is at least at version 24.4).

**Comment by avar** [comment]
It definitely *does* get passed Windows-1252 instead of UTF-8, maybe this has to do with my Emacs version or something but when I do:

    cp email $MAILDIR/INBOX/new/1455790136.17914_4.snth,U=1611000:2,

Where `email` is copy/pasted from the above, reindex, reindex, find the mail in Emacs and strace it with:

    sudo strace -s 10000 -p $(pidof emacs) | grep Don

And then open the mail I get (I cut the irrelevant crap):

    "Don\342\200\231t miss out![...]\\\">Don\342\200\231t miss out!</[...]:#1F497D\">Don\222t miss out!

I.e. those first two occurrences are UTF-8 encodings of the Unicode codepoint 0x2019 for ’, but the last one is \222 or 0x92 in hex, and html2markdown throws this error:

    UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 782: invalid start byte

I'm running Emacs 24.4.1 from Debian, what's your version? And what do you get when you set `mu4e-html2text-command` to an external program and strace it like this?

**Comment by avar** [comment]
This doesn't seem to have to do with my Emacs version. I've just compiled and installed the latest version of Emacs from git with:

    git clone git@github.com:emacs-mirror/emacs.git
    ./autogen.sh all
    ./configure --prefix=/home/avar/local --without-x
    make -j 4 all install

That gives me version 25.1.50.1,  Then I start it with:

    ~/local/bin/emacs-25.1.50 -Q --no-init-file -nw

I.e. I'm not loading my `.emacs` config, I thought maybe something about it was screwing with encodings (I set a bunch of locale variables to utf8).

Then I manually loaded just the mu4e part of my `.emacs`, which doesn't have anything I can imagine causing this, and I still get the exact same issue as noted above, and it looks the same under strace.

My mu version is 0.9.17 compiled from Git a couple of days ago (from 93a5b70).

Yeah I could just use mu4e-shr2text, I don't really have a problem with viewing these HTML E-Mails, I just open them up in the browser whenever this happens, but the underlying encoding bug is much more interesting. There's something funny going on with mu4e where it mostly uses utf-8 but sometimes uses the bare quoted-printable stream from these E-Mails.

**Comment by djcb** [comment]
Well, the output format can indeed be non-utf8, that's true... this can most easily be checked with something like
```
   (setq mu4e-html2text-command "tee /tmp/test.html | html2text")
```
which does indeed include the window-1252 quote mark for this particular message.

The strange thing is that when doing almost the same for the view-in-browser action, as well as checking :body-html inside emacs, it's proper utf8.

**Comment by djcb** [comment]
I suppose this is obsolete now since we have the gnus-based view mode. Does it work for you in that case?

**Comment by avar** [comment]
Let's just close this. Probably, and I no longer have a mail setup (coworkers switched from Exchange server to GMail) where I need to deal with this encoding, so this is no longer an itch of mine.
