### ISSUE TITLE
:thread-subject formatter hides subject if start of thread is outside of window..

### ISSUE THREAD

**Issue by thomasf** [djcb/mu#767]
It would be great if it worked like this:

**If the thread starts above the first visible line, make sure that the subject is printed at the first visible line when scrolling.**

It could maybe use text properties for hide/unhide so it would be less slow to
update. I'm sorry but I haven't looked at the current implementation so take
these last words very lightly.

**Comment by djcb** [comment]
Indeed - that's a know limitation of the current approach. Should take a look at that some time...

**Comment by djcb** [comment]
I can't think of an easy way to implement this, and since it's merely a cosmetic issue, solving it would not be worth the effort (imnsho)... if you see this problem a lot, I'd recommend using `:subject` instead of `:thread-subject`.... sorry!
