### ISSUE TITLE
mu4e-actions: Shouldn't the "Keyword"-header be comma-delimited?

### ISSUE THREAD

**Issue by andersjohansson** [djcb/mu#769]
I'm looking at `mu4e-action-retag-message` and noticed that the Keywords-header were expected to use space as a delimiter. But as far as I understand, shouldn't it be a comma? See: https://tools.ietf.org/html/rfc2822#section-3.6.5

Line 237-250 of mu4e-actions.el
```` Emacslisp
	  (sep     (cond ((string= header "Keywords") " ")
		     ((string= header "X-Label") " ")
		     ((string= header "X-Keywords") ", ")
		     (t ", ")))
````

**Comment by djcb** [comment]
Yes, seems you're right! Fixed in git, thanks!
