### ISSUE TITLE
sorting inside threads

### ISSUE THREAD

**Issue by ardpp** [djcb/mu#779]
I use the default sorting of messages by date with thread veiw. Mostly the messages in threads themselves are also sorted by date. Some threads however, for example those containing discussions on  github, are not sorted by date; see the attached screenshot, where the message on top is the first message in the thread. Is there something one can do to force sorting?

![screenshot](https://cloud.githubusercontent.com/assets/12278804/12695746/eeebdd28-c757-11e5-9b0b-9f65e02d03eb.jpg)

Thanks!

**Comment by ardpp** [comment]
Update: I don't know what and where has changed but at the moment the github messages are not even threaded as they used to be (in a partly reversed order).  Apart from github messages all other messages (that I get) are threaded and sorted as expected.

**Comment by djcb** [comment]
This same thing is discussed in #806 which has a bit more detail; so I'm closing this one even though it is the older one.
