### ISSUE TITLE
mu4e:msgid: link breaks on the headline

### ISSUE THREAD

**Issue by jagrg** [djcb/mu#782]
```
mu 0.9.17
Emacs 24.5.1
Org mode 8.3.3
```

**Comment by djcb** [comment]
Please describe exactly what's expected and what actually happening. Can't guess from the title.

**Comment by jagrg** [comment]
Below is a screenshot of the problem. I'm also getting an error message on the Messages buffer, so I think this is not related to mu4e.

![screen shot 2016-01-31 at 18 41 53](https://cloud.githubusercontent.com/assets/8846979/12704265/dad79ba4-c84e-11e5-8532-f0a5d83b27c3.png)

`Error during redisplay: (jit-lock-function 1) signaled (wrong-type-argument listp org-level-1) [12 times]`

**Comment by jagrg** [comment]
Ok, so the problem was introduced by a recent upgrade: `org-20160118` to `org-20160125`. I thought it had to do with mu4e. Sorry about that.
