### ISSUE TITLE
Add option to use a single persistent mu4e-update buffer

### ISSUE THREAD

**Issue by jtmoulia** [djcb/mu#785]
I'd like to be able to keep the `mu4e-update` process buffer open between update calls. Occasionally there's an error with the update process (offlineimap), but the buffer closes before I'm able to glance at it. Also, there's no indication of non-zero exit statuses.

This idea is partially inspred by the `magit-process` buffer which maintains a list of commands and their exit status:

```shell
0 git … add -u -- mu4e/mu4e-draft.el
0 git … checkout -b fix/cancel-compose-gen master
...
```

Also, I've been quite happily using mu4e for about a year now. Thanks!

**Comment by djcb** [comment]
Hmm, if there's a non-zero exit status, it should keep the buffer open, see
   http://www.djcbsoftware.nl/code/mu/mu4e/Retrieval-and-indexing.html

**Comment by jtmoulia** [comment]
Ah cool, looks like I'm running an older version :blush: Handling the exit code was the sharp edge, so I'll close this issue. Thanks!
