### ISSUE TITLE
Error trying to make mu4e

### ISSUE THREAD

**Issue by jtmoulia** [djcb/mu#787]
I'm seeing this error running emacs 24.5.2, with mu at v0.9.16:

```shell
~/repos/mu/mu4e $ make
if test "emacs" != "no"; then \
	  am__dir=. am__subdir_includes=''; \
	  case mu4e-actions.elc in */*) \
	    am__dir=`echo 'mu4e-actions.elc' | sed 's,/[^/]*$,,'`; \
	    am__subdir_includes="-L $am__dir -L ./$am__dir"; \
	  esac; \
	  test -d "$am__dir" || /usr/local/bin/gmkdir -p "$am__dir" || exit 1; \
	  emacs --batch \
	      \
	    $am__subdir_includes -L . -L . \
	    --eval "(defun byte-compile-dest-file (f) \"mu4e-actions.elc\")" \
	    --eval "(unless (byte-compile-file \"mu4e-actions.el\") (kill-emacs 1))"; \
	else :; fi

In end of data:
mu4e-actions.el:285:1:Warning: the function `mu4e-headers-search' is not known
    to be defined.
Cannot create temporary name for prefix: Bad file descriptor, mu4e-actions.elc
make[1]: *** [mu4e-actions.elc] Error 255
make: *** [all-recursive] Error 1
```

`mu4e-headers-search` is defined in mu4e-headers.el, tho it is dependent on mu4e-actions

**Comment by djcb** [comment]
That's a weird error... did you see some file corruption, or perhaps a full drive? Perhaps try again with a freshly cloned mu?

**Comment by jtmoulia** [comment]
I gave it a retry, but ended up with the same error. Here are the commands I entered:

```shell
$ git clone https://github.com/djcb/mu mu2
$ cd mu2
$ git checkout v0.9.16
$ autoreconf -i
$ ./configure
$ cd mu4e
$ make
```

And, yup, looks like my drive has some free space on it.

Honestly tho, byte compiling the elisp isn't critical: the other sub-make targets, e.g. mu, still work.

**Comment by gridaphobe** [comment]
I have run into this same problem (on OSX). It seems that the `byte-compile-dest-file` function is related. If I run

```
emacs --batch --eval "(unless (byte-compile-file \"mu4e-actions.el\") (kill-emacs 1))"
```

the error disappears.

**Comment by jtmoulia** [comment]
Cool -- I'm seeing the same. Getting rid of the following line from `mu4e/Makefile[.in]` fixed it, though I'm not sure how those files are generated. autoconf?

```elisp
--eval "(defun byte-compile-dest-file (f) \"$@\")" \
```

`byte-compile-dest-file` is already defined in my emacs:

```elisp
(byte-compile-dest-file "a.el")
"a.elc"
```

**Comment by gridaphobe** [comment]
I think it is an autoconf thing, I grepped for `byte-compile-dest-file` in a fresh clone and found nothing. Unfortunately I don't know anything about how autoconf deals with emacs-lisp.

**Comment by djcb** [comment]
The build process hasn't changed for a loooong time... did this suddenly come up? What changed?

**Comment by gridaphobe** [comment]
I'm not sure, I haven't built mu4e in a long time. But the latest release of autoconf is even longer ago (2012)...

**Comment by djcb** [comment]
Similar issue reported: https://github.com/NixOS/nixpkgs/issues/11723

Might be a red-herring, but the difference seems to be in one line;  e.g. on Fedora:
``
  test -d "$am__dir" || /bin/mkdir -p "$am__dir" || exit 1; \
``
vs
``
 test -d "$am__dir" || /usr/local/bin/gmkdir -p "$am__dir" || exit 1; \
``
For some reason, the latter triggers this error -- which comes from emacs itself, when it fails to create some tempfile. Perhaps because create the tempdir fails for some reason?

**Comment by djcb** [comment]
I don't think I can do anything about this from the mu side -- so closing this.

**Comment by jtmoulia** [comment]
I haven't had a chance to debug this, but I wanted to chime in that I'm experiencing this issue running Emacs off a [nix](https://github.com/NixOS/nix) install. So, upstream seems likely. Cheers!
