### ISSUE TITLE
Headers View - Include related of message-at-point

### ISSUE THREAD

**Issue by mmatthe** [djcb/mu#788]
It would be very helpful to be able to reveal all messages that belong to the thread of the message-at-point. 

Pressing W in the headers view has this functionality, however, it includes the related messages of all threads, rebuilds the view, and moves the cursor to the beginning of the buffer. Hence, one would need to search again for the thread you were at before. 

It would be nice to have a feature that includes only the related messages of the current thread into the headers view, leaving the point at the message.

Alternatively, instead of including the related messages to the current view, mu4e could create a "narrowed search", that just includes related messages of the current thread. Hence, being able to switch back and forth with M-left, M-right.

Do you think implementing this would be difficult?

**Comment by zakkak** [comment]
There is an action `a s` that enables you to show only the current
thread in the headers. Then, pressing `W` would display only the related
to this thread messages and M-left M-right behave as you would expect.

So the functionality seems to be present you just have to bind it to
some key if you want to reduce the key-presses.

**Comment by mmatthe** [comment]
Great! I did not know about this feature. So, I suppose this issue can be closed.
Thank you!
