### ISSUE TITLE
Attempt to delete minibuffer or sole ordinary window

### ISSUE THREAD

**Issue by strow** [djcb/mu#789]
I keep getting these errors:  Attempt to delete minibuffer or sole ordinary window

They never seem to actually hurt anything.  The general scenario for getting one of these is:
Set a mark to move the message to my allmail folder
   Then hit x to execute the mark, when I hit "y" to tell mu4e to go
   ahead and execute, I then get a beep and the error message, sometimes.

But, it is not repeatable, maybe 30% of the time I get this error.  I put debug_on in emacs and got the following:

error log from emacs:

Debugger entered--Lisp error: (error "Attempt to delete minibuffer or sole ordinary window")
  signal(error ("Attempt to delete minibuffer or sole ordinary window"))
  error("Attempt to delete minibuffer or sole ordinary window")
  byte-code("\204_	\306=\204_\307	!\203\310\311	\n!\"\210\202_\312\n\313\"\203H\314\n!\211\203H\n=\204H\315\f!=\203>\316\317!\210\202_\310\311\320!\"\210\202_
\204S\316\321!\210\202_\n\322\f!=\203_\316\323!\210\324
!)\325\n)\306#*\326\327\f!\n\"+\330\n!\206}\331\n!,\332\f)\"\210-\204\273,\203\273\333,*)\334\306%\203\273\335,*)\334\306%\210\336,\337,)\"\337\n)\"\\\"\210\202\342\340\n*[)\334\211\211\306\211&\203\330\341\n*[)#\210\202\342\341\n*[)\306$\210\342\n!\210\343\f)\"\210+\203\377\312\327\f!\344\"\203\377\345\346\f\"\210\347\f!\210\350\f!\210,\334\207" [ignore-window-parameters function window atom-root frame parent t functionp throw done window-parameter window-atom window-atom-root frame-root-window error "Root of atomic window is root window of its frame" delete-window "Attempt to delete minibuffer or sole ordinary window" window--major-non-side-window "Attempt to delete last non-side window" window-left-child window-size window--in-subtree-p frame-selected-window window-left window-right window--resize-reset window-sizable-p nil window--resize-this-window set-window-new-normal window-normal-size window--resizable-p window--resize-siblings delete-window-internal window--pixel-to-total no-other-window other-window -1 run-window-configuration-change-hook window--check horizontal size frame-selected sibling window-combination-resize] 9)
  delete-window()
  kill-buffer-and-window()
  mu4e~headers-remove-handler(45444)
  mu4e~headers-update-handler((

(Rest of debug output deleted since it contains a long attached file).

I don't think this has anything to do with attachments, it's just that the first debug output I got was for a file with a long attachment.

**Comment by djcb** [comment]
I've added a fix (well, work-around) for this.

**Comment by gpion** [comment]
I've a different, albeit similar, issue with version 25.0.91 running on RHEL 6.7 : delete-windows (ctrl-x 0) gives the same error *everytime*
Should I open another ticket?
