### ISSUE TITLE
mu "cleans up" attachment names; makes it difficult to remove them

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#790]
My "remove attachment" action didn't work on a recent email. I'm using the following function [(source)](https://groups.google.com/forum/#!topic/mu-discuss/rBzb3f1Erug
)

```elisp
(defun remove-attachment (msg num) 
  "Remove attachment." 
  (let* ((attach (mu4e~view-get-attach msg num))
          (path (mu4e-msg-field msg :path))
          (filename (and attach (plist-get attach :name)))
          (cmd (format "altermime --input=%s --remove='%s'"  path filename)))
    (when (and filename
            (yes-or-no-p
	     (format "Are you sure you want to remove '%s'?" filename)))
      (shell-command cmd)
      (message cmd)
      )))
(add-to-list 'mu4e-view-attachment-actions
  '("remove-attachment" . remove-attachment))
```

The reason it didn't work is that mu4e in the header reports the attachment as being named "a-p.pdf" but it is actually named "a b.pdf"

If I look at the raw message (by typing .), I can scroll down and see:

> ------=_NextPart_000_00C8_01D16035.F7327F70
> Content-Type: application/pdf;
> 	name="a b.pdf"
> Content-Transfer-Encoding: base64
> Content-Disposition: attachment;
> 	filename="a b.pdf"
> 

There is never any mention in the file of "a-b.pdf". This seems to be something that mu4e does? I've traced it to "cleanup_filename" in mu-msg-part.c here https://github.com/djcb/mu/blob/master/lib/mu-msg-part.c#L243

Not sure what to do about it, but it would be nice if the remove function worked on all attachments.

**Comment by mankoff** [comment]
FYI, I've commented out the cleanup code:

```diff
$ git diff
diff --git a/lib/mu-msg-part.c b/lib/mu-msg-part.c
index ce02a74..26df527 100644
--- a/lib/mu-msg-part.c
+++ b/lib/mu-msg-part.c
@@ -245,9 +245,9 @@ cleanup_filename (char *fname)
        gchar *cur;

        /* remove slashes, spaces, colons... */
-       for (cur = fname; *cur; ++cur)
-               if (*cur == '/' || *cur == ' ' || *cur == ':')
-                       *cur = '-';
+       /* for (cur = fname; *cur; ++cur) */
+       /*      if (*cur == '/' || *cur == ' ' || *cur == ':') */
+       /*              *cur = '-'; */
 }
```

And have had no adverse effects for the past two weeks...

**Comment by djcb** [comment]
I've changed the function slightly; '/' and ':' (and any control characters) are replaced by '-', but ' ' (Space) is left alone now.

**Comment by tmalsburg** [comment]
Thank you, Ken, for this function.  I think this is really useful and it might make sense to include this in mu4e.

Is there a way to remove multiple attachments on one go (similar to `C-u e`)?

**Comment by mankoff** [comment]
`altermime` can remove based on wild-card matching or `removeall`. It can also replace, which might be useful for a feature from `alpine` that I dearly miss. When deleting an attachment in pine/alpine, it would record the name of the attached file that was deleted, which is sort-of important when reading old emails with deleted attachments (i.e. people often refer to the attached paper, and I need to know the name so I can find it where I filed it).

All this probably goes in a new ticket as a feature request.

**Comment by mankoff** [comment]
> Is there a way to remove multiple attachments in one go (similar to `C-u e`)?

I finally wrote this:

```
(defun remove-all-attachments (msg)
  "Remove all attachments." 
  (let* ((path (mu4e-msg-field msg :path))
	 (cmd (format "altermime --input=%s --removeall" path)))
    (if
	(yes-or-no-p
	 (format "Are you sure you want to remove all attachments?"))
      (shell-command cmd)
      (message cmd)
      )))
(add-to-list 'mu4e-view-actions
	     '("rremove-all-attachments" . remove-all-attachments))
```

Also, as posted here https://github.com/djcb/mu/issues/2247 the remove-one-attachment now replaces with the name of the attached file that was removed.
