### ISSUE TITLE
Bad parsing of doodle links

### ISSUE THREAD

**Issue by slosar** [djcb/mu#791]
Mu4e badly parses doodle.com emails containing links. This happens regardless of html rendering or not. So pressing g1 leads to a badly formed html.
I attach the actual maildir file (with PII removed)

[em.txt](https://github.com/djcb/mu/files/120674/em.txt)

**Comment by djcb** [comment]
Please always include the versions of mu / emacs you're using -- thanks.

Anyway, I'd recommend using mu4e-shr2text for html rendering; if you have a recent emacs and mu from git, that's even the default (since a few hours!)

**Comment by slosar** [comment]
Dirk-Jan C. Binnema writes:

> Please always include the versions of mu / emacs you're using -- thanks.

I'm using 24.5.2 and latest github version of mu4e.

> Anyway, I'd recommend using mu4e-shr2text for html rendering; if you have a recent emacs and mu from git, that's even the default (since a few hours!)

This indeed fixes it: links become clickable (but "g" functionality
seems to be gone). But good enough to close this ticket I guess,

anze

**Comment by djcb** [comment]
Yeah, html-rendered emails don't have 'g' etc. I've added a not to the manual.
