### ISSUE TITLE
Message moving ignores target context

### ISSUE THREAD

**Issue by gaydenko** [djcb/mu#794]
Hi!

Steps:
1. open any message from current context (say, `ctx1`) in view
2. switch to context another than the message belongs to (say, from `ctx1` to `ctx2`)
3. move the message to one of the folders inside `ctx2`

Result:
```txt
error in process filter: mu4e-error-handler: Error 70: error moving /path/to/ctx1/Sent/cur/1454957933.42815d4ce2254f82.hostname,U=12:2,S to /path/to/ctx1/[Gmail]/.Sent Mail/cur/1455132290.1225bac4e2945a49.hostname:2,S
```
As you see, the second path also point to the maildir of the first context. Indeed, the move function ignores `mu4e-maildir` at command call:
```lisp
(defun mu4e~proc-move (docid-or-msgid &optional maildir flags)
  "..."
  (unless (or maildir flags)
    (mu4e-error "At least one of maildir and flags must be specified"))
  (unless (or (not maildir) (file-exists-p (concat mu4e-maildir "/" maildir "/")))
    (mu4e-error "Target dir does not exist"))
  (let* ((idparam (mu4e~docid-msgid-param docid-or-msgid))
	  (flagstr
	    (when flags
	      (concat " flags:"
		(if (stringp flags) flags (mu4e-flags-to-string flags)))))
	  (path
	    (when maildir
	      (format " maildir:%s" (mu4e~proc-escape maildir))))
          (rename
            (if (and maildir mu4e-change-filenames-when-moving) "true" "false")))
    (mu4e~proc-send-command "cmd:move %s %s %s %s"
      idparam (or flagstr "") (or path "")
      (format "newname:%s" rename))))
```
Yes, `mu4e-maildir` is used to verify a target dir exists, but `mu4e~proc-send-command` call doesn't pass any context-related information (`path` is a relative path inside maildir), and doesn't switch session with `mu` server to another context (not sure what is that real mechanics is in use to support contexts).

**Comment by djcb** [comment]
`mu4e-maildir` is not to change while running mu4e (see http://www.djcbsoftware.nl/code/mu/mu4e/Contexts-example.html), so the relative paths stay valid, no matter what the context is.

I.e., all your maildirs must live in the same tree.

**Comment by gaydenko** [comment]
@djcb , then how to separate `accountA/Inbox` and `accountB/Inbox`? I haven't found `mu4e-input-folder` var to set it in `:vars` for each context.

**Comment by gaydenko** [comment]
Sync tools also want dedicated directories for each account.

**Comment by djcb** [comment]
I have a couple of different accounts, but all offlineimap and fetchmail feed different subdirs of the same maildir. So, you'd have `/home/user/Maildir/accountA/...`  and `/home/user/Maildir/accountB/...` and set mu4e-maildir to `/home/user/Maildir`.

Don't know about `mu4e-input-folder`.

**Comment by gaydenko** [comment]
Aha, I see, thanks!

I have added `/ctxN` into all `mu4e-xxx-folder` vars and folders shortcuts for each context, rebuilt `mu`, and now the issue seems to be gone.

P.S. Saying about `mu4e-input-folder` I meant just analogy with other vars as, say, `mu4e-sent-folder`, an so on. So, I don't know about `mu4e-input-folder` also :)

**Comment by djcb** [comment]
Oh, great it works!
