### ISSUE TITLE
Contexts with multiple maildirs in a non-default location

### ISSUE THREAD

**Issue by Demorde** [djcb/mu#798]
Hello, I am trying to setup multiple maildir account as specified in the [context example page](http://www.djcbsoftware.nl/code/mu/mu4e/Contexts-example.html#Contexts-example) however my maildir are not in the default location, I tried adding (mu4e-maildir "location") into it, but it gives me a stringp error.

My maildirs at in ~/.mail/gmail and ~/.mail/uofc . How would I go about adding them so I can get this to work? Outside of the example above I only have the add-to-list and 'require.

**Comment by gaydenko** [comment]
@Demorde , hi!

So, your `mu4e-maildir` must be set to `~/.mail` - and it is context-independent beast. Then for folders use prefixes in accordance with accounts, say: `/uofc/Sent`.

**Comment by Demorde** [comment]
Oh wow, that was _so easy_. I was trying to insert it in each context. Thank you!
