### ISSUE TITLE
Update context on ``message-send``

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#799]
When composing a message in the wrong context I instinctively updated the From: field and sent, but it was archived in the wrong folder.

It feels like that the ``:match-func`` should be evaluated once more just prior to sending in order to pick the final context and update the relevant vars, such as the sent-folder.

Vaguely related to #776, in the sense that I see this as a complementary behavior.

**Comment by djcb** [comment]
This use-case should be covered by #776 already. 

In any case, we don't have the parsed message when sending it, so we couldn't easily pass it to `:match-func` anyway.
