### ISSUE TITLE
[FR] Show threads from email, not header

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#804]
If I'm viewing an email that isn't in the header view (i.e. followed a link from an Org file), and want to see the whole thread, the current implementation of `[s]how this thread` does not support that. Instead I get the error, `mu4e-error: [mu4e] cannot find message in headers buffer.`

`[s]show this thread` should work from the message view, regardless of the header view.

**Comment by djcb** [comment]
This is the same problem as #417; right now, the mu4e-view need an accompanying headers-view to do any changes.

**Comment by mankoff** [comment]
OK, then we can close this. BUT I think I found a work-around. If you kill the header view, then the action works. I think this is referenced in #417 already with this: https://github.com/emacs-helm/helm-mu/commit/6443ead5cfc72bad93f5f0ee600c3ded611172a5

**Comment by djcb** [comment]
Okay, great you found a work-around! I'll take a look at that.
