### ISSUE TITLE
Privacy issue: Opening HTML email in browser

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#807]
When I open HTML email in a browser (via `mu4e-action-view-in-browser`), images are loaded and my privacy is potentially compromised.  (Images are often used to track when a user reads an email.)

Could we edit the HTML before passing it to the browser to remove images or alternatively to replace images by a local placeholder?

**Comment by djcb** [comment]
Well, mu4e-action-view-in-browser is a quite simplistic example of how to write an action, but it can indeed be quite useful. Some other proposed extension would be to allow for inline images as well.

Anyway, no one is stopping you from writing a more complicated view-in-browser that strips images, javascript etc., but I suspect it'd be easier to use the existing one with a browser (or browser profile) that does not load images.

**Comment by djcb** [comment]
I've update the documentation to esp. mention your concern.

**Comment by tmalsburg** [comment]
Thanks. I considered writing a safe version of that action, but there are so many ways in which external resources can be loaded (JavaScript) that it's next to impossible to make this water tight.
