### ISSUE TITLE
Support for long lines for incoming emails

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#808]
Incoming messages using quoted-printable or format=flowed encoding can distinguish between hard or soft newlines. I guess quoted-printable is currently handled by gmime, which just unwraps the message.

However, if a message is text/plain, it can still be format=flowed (it's in the content-type). In substance, f=f can distinguish between a hard and a soft newline as well, but just using trailing whitespace in a way that's completely invisible to the end user. A f=f message looks wrapped and can be replied as-is (preserving it's structure), or can be logically unwrapped without breaking quoting.

Even if the RFC discourages it, a f=f message transmitted in QP still works correctly, for example.

The decoding algorithm is trivial, and it could be implemented completely in mu4e-view if the content-type of the text part was available.

**Comment by andersjohansson** [comment]
:+1:  With the new options for sending format=flowed, it seems silly to not be able to display it (as flowed)

**Comment by djcb** [comment]
Okay, I think this works now with the new (experimental) view mode -- `(setq mu4e-view-use-gnus t)` (before starting mu4e). Finally!
