### ISSUE TITLE
Sorting headers by ascending date in maildir

### ISSUE THREAD

**Issue by tomnor** [djcb/mu#809]
I am trying to use ascending sorting by date in a maildir, like
`<mymail>/INBOX`, so that I get the newest mail in the bottom. I get to
`<mymail>/INBOX` by `mu4e~headers-jump-to-maildir`.

If the `mu4e-headers-full-search` variable is nil, and I have more than 500
mails to be listed, the result is that my very oldest mail in that maildir is
displayed at the top, and the mail chronologically (oldest + 499) is displayed
in the bottom.

Is it supposed to work like that by design? I mean, the default result then is
that I do not see my newest mail in the buffer when "dummy-browsing" mails in a
maildir.

**Comment by djcb** [comment]
It's the way the sorting works, yes... we ask the database for the first (say) 500 messages, then sort the result. We do not ask for _all_ messages, then sort, then take the first 500.

**Comment by tomnor** [comment]
Hmm. Maybe I'm confused on the relation between sorting and "first". I don't think that my *oldest* mail is "first" when I have sorting one way, and then that my *newest* mail is "first" when I have sorting the other way. I am more likely to think that if the result is limited to x number of mails datewise and there is no time-range included in the search terms, it would be the same chronologically last number of mails returned, no matter sorting of the buffer. And then, as you say, they'll be sorted according to the preference.

I don't know. Are you saying that the query to the database is somehow affected by the way I am sorting the buffer? Maybe in that case I should change this to a feature request not to involve the sorting preference in the querys. Or am I missing something?

**Comment by djcb** [comment]
Hmmm, so what I'm seeing when querying for some common word, say, "hi" (which has few 10K hits in my case), when I'm sorting by date in ascending order, the list goes from 2000 - 2003; when I search in descending order, I starts with today, and goes until 500 messages in the past. Are you seeing something else?

In any case, if you would want to see only recent messages, I supose could add a `date:` clause to the query?

**Comment by Ambrevar** [comment]
I'd like to re-open this as I agree with @tomnor: there is some design flaw in the way the query is done.

The way I see it, `mu4e-headers-sort-direction` should drive the way the result is presented, not the way it is queried (which is rather pointless in my opinion).

I prefer to have it ascending because then e-mails read top to bottom chronologically. When sorted by date, I still want my latest e-mail to be displayed as opposed to what mu4e currently does, that is, displaying the 500 earliest e-mail.

As for the `date:` clause, I'm afraid it would not be sufficient: we cannot guess in advance which date will encompass the 500 latest  e-mails. It's brittle and not flexible at all.

**Comment by tomnor** [comment]
Feels like a long time since I was discussing this issue, since then I
have switched over to notmuch (not because of this issue). notmuch and
mu4e are similar in that they use the xapian back-end for indexing and
searching.

I tested this yesterday with notmuch on the command line, (it doesn't
provide an easy option to limit searches in emacs as far as I know),
and the result is the same. It never bothered me since switching over
because I never limit a search.

My workflow nowadays is that for any new session I normally just
search the unread mails or the mails from the last day or so. Be sure
you have an option with mu4e for date ranges as well. In notmuch the
query goes: `date:2d..` for two days back in time until now. (but
again, if you have oldest first sorting and the query yields more than
your limit, you will not get your last mails)

The issue occur when we use those mailers as a more streamline kind of
mailer which by default give all what you have in your "inbox
folder". And if the query is to search the inbox, there might be a
need to limit the search. But really, why would you need to view your
entire inbox? That's what I have come to realize.

It seems this issue comes around *because* there is an option to limit
the search. Then one is tempted to use that and make a not very smart
query. In addition the "sorting" option with oldest first can be
somewhat confusing, it wasn't clear to me that it had anything to do
with the query, but it does.

My opinion is probably that we should just surrender this issue and
embrace the search-based nature of those excellent mailers. Think over
what query you really want to do and then ask on the mu4e mailing list
for help, you will get a perfect answer I am sure. Probably you're
better off turning off the limiting and make proper query's.
