### ISSUE TITLE
Messages disappear from header view before they are rendered

### ISSUE THREAD

**Issue by YoungFrog** [djcb/mu#814]
(Message on mailing list which triggered this bug report : https://groups.google.com/d/msg/mu-discuss/e0HtrPqvNjE/7LAxl6F1AAAJ)

This is the current situation (taken from above thread) :

> When you open an unread message, it's marked as read, then opened again
> (with the updated status). If you C-g in between, then the old message
> has already been removed but the new one is not there yet. Delays can
> happen when the mu server is doing something else when you try to render
> the message.

For my own use case, if there's a way to mark the message as read upon _exiting_ the
message view buffer, that'd be lovely.

**Comment by djcb** [comment]
Hmmm., the good news is that mu can now index and get messages in parallel.. but if you press C-g at the wrong moment, then likely you can break things. Basically mu4e just does what the user says... and I can't see an easy way to handle this specially. So closing this.
