### ISSUE TITLE
mu4e-update-mail-and-index: Show process buffer when update process is already running

### ISSUE THREAD

**Issue by luisgerhorst** [djcb/mu#815]
Would be nice if calling `mu4e-update-mail-and-index` would always result in the process buffer showing the update progress being displayed. No matter if the update process is already running when you call the function. When you have automatic updating enabled this happens frequently.

**Comment by djcb** [comment]
It's tricky to retro-actively show the hidden buffer so not planning to do this. If you have a simple patch, that could change our mind of course :-)

**Comment by alejandroerickson** [comment]
I'm a bit late here, obviously, but I wanted to do this manually by calling `list-processes`, and then clicking on the buffer linked in process list, `*mu4e-update*`.

In spacemacs I get `list-processes` by doing `SPC a p`
