### ISSUE TITLE
mu4e-contexts: provide a function to match what is the message's directory (i.e. which folder it was stored)

### ISSUE THREAD

**Issue by semente** [djcb/mu#817]
Is it currently possible? If I receive a message without my email address in header (e.g. BCC) I could detect the account based on the folder the message was stored.

**Comment by djcb** [comment]
Sure, you can have something like
```
:match-func (lambda (msg)
			(when msg
			  (string= (mu4e-message-field msg :maildir) "/my-folder")))
```
I've added an example to the documentation.

**Comment by semente** [comment]
Great, thanks @djcb!

**Comment by semente** [comment]
Maybe you can add this example in the docs too, I think people will find it useful.
