### ISSUE TITLE
Index all context

### ISSUE THREAD

**Issue by twistedjoe** [djcb/mu#818]
Hi,
I can't figure out how to have all the context indexed at once. I have a different maildir for each context.
I wan't to have them update in the background, but at the moment only the active context update. 

Anyway to do this ? 
If not, that would be a cool feature,  switching context to update them individually is a bit tedious.

**Comment by ardpp** [comment]
I use `isync` and have the following _outside_ context-definitions 
``` elisp
(setq mu4e-get-mail-command "mbsync -a -q")
(setq mu4e-update-interval 120)
```
Here `mbsync -a` is for update all. Similar should work with  `offlineimap` if you are using that.

**Comment by twistedjoe** [comment]
I don't think this will solve it. I have tested my call to `mu4e-get-mail-command` (with offlineimap) and it successfully fetch all the email account.

This was not clear in my first post, but the problem is the indexation(mu) not the fetching(offlineimap). 
When I type "U" which run `mu4e-update-mail-and-index`  it will run the `mu4e-get-mail-command` which fetch the email for all 3 accounts (I can see the email are there in the folders) then it will run `mu4e-update-index` which index only the current context. If I then switch context and run manually `mu4e-update-index`, without calling offlineimap, the email will show. 

The problem is that the call to `mu4e-update-index`  seems to need a path to the maildir to index it and the path it is given is the path of the current mailbox. 
So I was thinking of replacing the internal call to `mu4e-update-index` with a loop what do it on all the context (without switching context). 

Another solution would be to merge all my maildir together since it would always index the same folder for all the accounts. Though, I fear that offlineimap (or mbsync) would sync those emails  between the  3 accounts.

**Comment by andersjohansson** [comment]
The solution is to keep all accounts under the same base maildir-directory (which `mu4e-maildir` should point to). See the discussion in #798.

**Comment by twistedjoe** [comment]
That works, though now my maildir shortcuts can only point to one account at at a time. Previously If I would go to /INBOX I would see the inbox of all the accounts at the same time.  I guess I can use bookmarks instead. 

Thanks!
