### ISSUE TITLE
Error after message send in mu4e

### ISSUE THREAD

**Issue by j0ni** [djcb/mu#819]
After doing `C-c C-c` to send a reply message, the buffer exits, displays the message I'd replied to briefly, then the following is displayed in the minibuffer:

```
[mu4e] Message sent
error in process filter: kill-buffer-and-window: Attempt to delete minibuffer or sole ordinary window
error in process filter: Attempt to delete minibuffer or sole ordinary window
```

and the message exits, sending me back to `mu4e-headers`.

I don't *think* this happens for non-reply messages.

**Comment by djcb** [comment]
When reporting issues, it is really important to state the version you are using - can you do that?

**Comment by j0ni** [comment]
I'm using mu4e 0.9.16 C, with mu 0.9.16, installed via homebrew on Mac OS X. I'm currently using Emacs 25.0.92.2, patched with the mac port patch set, built from source. I've seen the same issue previously using Emacs 24.5.

**Comment by djcb** [comment]
So, there's a change in 0.9.17 (i.e., the git version) that addresses this (or at least this symptom). Can you try that?

**Comment by j0ni** [comment]
One quick test would indicate that this fixes the problem, thanks!

I'll spend some time with it tomorrow and confirm, and then close this (unless you want to leave it open until you've done the release).

**Comment by j0ni** [comment]
I haven't been able to reproduce this problem, so I'm closing this.

**Comment by djcb** [comment]
Great - thanks!
