### ISSUE TITLE
Some issues in mu4e~compose-set-parent-flag

### ISSUE THREAD

**Issue by andersjohansson** [djcb/mu#822]
I've been hacking `mu4e~compose-set-parent-flag` (overriding it with a custom definition) to offer to refile messages that I've replied to or forwarded.

While doing this I noticed some issues.

First, `message-fetch-field` states that the buffer should be narrowed to the headers to avoid false results from the message body. I don't know if this is really a problem, but I don't see why a call to `message-narrow-to-headers-or-head` couldn't be added either. We would get this in `mu4e~compose-set-parent-flag`:
````Emacs-lisp
(with-current-buffer buf
  (message-narrow-to-headers-or-head)
  (let ((in-reply-to (message-fetch-field "in-reply-to"))
        (forwarded-from)
        (references (message-fetch-field "references")))
````
Is there need for widening afterwards?

Second, when forwarding, it seems that the "references"-header can't be extracted (in the let-statement above) since it is hidden via `mu4e~compose-hide-headers` when the draft is constructed. This means that the correct action is never taken for forwarded messages as far as I can see.
A solution would just be to remove `"^References"` from `mu4e-compose-hidden-headers`. So it's definition would be:
````Emacs-lisp
(defvar mu4e-compose-hidden-headers
  `("^Face:" "^X-Face:"
     "^X-Draft-From:" "^User-agent:")
  "Hidden headers when composing.")
````
But I'm not entirely sure whether this is the issue.

**Comment by andersjohansson** [comment]
The narrowing seems to cause some problems for me though. Perhaps needs to test it out more.

**Comment by andersjohansson** [comment]
Ohh, but it works on the saved message in drafts. There is never a "References"-header in these files for some reason. Maybe that doesn't have to do with `mu4e~compose-hide-headers`?

**Comment by andersjohansson** [comment]
Ok. I would guess this is caused by the call to `mu4e~remove-refs-maybe` added to `message-send-hook` by the `mu4e-compose-mode`-initialization. Does this cause "references" to be removed for forwarded messages, and should this really be the case?

**Comment by djcb** [comment]
I'm not really sure what problem you try to solve here - things seems to work just fine as they are or? Perhaps we need the call to `(message-narrow-to-headers-or-head)`, though I haven't seen problems in practice.

**Comment by andersjohansson** [comment]
No, the narrowing or not narrowing doesn't seem to cause any real trouble. The references issue still bothers me though. I'll have to check through my config to see if it is anything more that I do that causes it, but as far as I could see yesterday, forwarded messages were never correctly flagged by `mu4e~compose-set-parent-flag`.

**Comment by djcb** [comment]
I took a look and indeed, forwarded messages had their `References:` header removed... I have fixed this now.

**Comment by andersjohansson** [comment]
Great! I'll consider this closed for now. Don't bother about the narrowing stuff.
