### ISSUE TITLE
Bring back `mu4e-user-mail-address-regexp` or something like it

### ISSUE THREAD

**Issue by rpglover64** [djcb/mu#823]
I can see the logic in removing it, but here is my use case:

I'm using `mu4e` with `mbsync` on top of my Gmail account; I use a lot of plus aliases. I generally use a new one for every site I give my email to. It would be nice if they were all treated as my address, without me having to add each one to `mu4e` individually.

**Comment by jpggithub** [comment]
Same problem here.
Have you a configuration useful to deal with this configuration?

**Comment by bradyt** [comment]
I would like a list of regexes. Like

``` elisp
'("best.intentions@big.enterprise.com"
  ".*@widgets.info"
  ".*@blankstubs.com")
```

Or maybe a list of full email addresses and domains? Like

``` elisp
'("best.intentions@big.enterprise.com"
  "widgets.info"
  "blankstubs.com")
```

**Comment by bradyt** [comment]
Hmm, maybe one of us can write a script that adds to the list when we encounter an email address that matches with custom code.

**Comment by djcb** [comment]
git master has an implementation of this now, basically use something like --my-address='/foo.*@example.*/', and mu4e understands it too.
