### ISSUE TITLE
Deleting a message from mu4e-view destroys other windows

### ISSUE THREAD

**Issue by j0ni** [djcb/mu#824]
If I use mu4e with more than 1 window in a frame, it works fine in its window until I delete a message I'm currently viewing. Then it advances to the next message and destroys all other open windows, taking over the whole frame.

I'm using emacs 25.0.92.2, with mu4e 0.9.17 C build from HEAD on OS X using homebrew. I've observed this using 0.9.16 and also using emacs 24.5.

**Comment by djcb** [comment]
Just checked, this is no longer the case. Closing... finally.
