### ISSUE TITLE
error in process filter: [mu4e] No message at point

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#825]
When refreshing the header view, my cursor is often on the bottom line which reads `End of search results`. When it is there, the refresh fails with `error in process filter: [mu4e] No message at point`. That may be true, but it shouldn't stop the header view from updating.

**Comment by mankoff** [comment]
I still see this issue in latest head.

**Comment by mankoff** [comment]
OK, I see this issue, but it is a tiny subset edge-case compared to before. Now the point has to be after the last character (after the `s` in `results`), **and** a new mail arrives, then the message is still there. But in most cases, it is now gone (no new mail, or anywhere else on the line w/ new mail).

**Comment by mankoff** [comment]
This should be re-opened.

**Comment by djcb** [comment]
Ah yes -- seems it's not fully fixed.

**Comment by djcb** [comment]
Are you still seeing this?

**Comment by djcb** [comment]
Haven't seen this anymore -- closing.
