### ISSUE TITLE
Change the advice for format=flowed 

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#836]
The [advice given in the manual](http://www.djcbsoftware.nl/code/mu/mu4e/Writing-messages.html#Writing-messages) does not send proper `format=flowed` messages — they lack spaces at the end of lines.

It is better to adapt the code given [on the Emacs wiki for Gnus](https://www.emacswiki.org/emacs/GnusFormatFlowed) — which is simple: change `(add-hook 'message-setup-hook` into `(add-hook 'mu4e-compose-mode-hook`.

**Comment by djcb** [comment]
There's a bunch of functions there, and they seem gnus-specific... Did you test that code with mu4e? If so, (and it works of course!) can you provide a pull-request? Thank advance!

**Comment by edumerco** [comment]
I would love formate=flowed to work as it ideally have to. I can't code but I can help with testing. :+1:

**Comment by Chris00** [comment]
Yes, I am using those functions right now.  I am not sure where you want 
me to put them.  If in mu4e-contrib.el, should I just define the 
functions and add some comment on how to add them to the proper hooks or 
would a function that does the activation be welcome?

Ideally, it would be useful to be able to deactivate the message send 
hook from the compose buffer (only for the current message) because some 
recipients (such as github) do not understand format=flowed — this is 
why I set (setq fill-flowed-encode-column 72) so that the width is 
reasonable in case flowing is not applied.

**Comment by Chris00** [comment]
Tentative PR above.  Please comment.
