### ISSUE TITLE
Remove draft backup files

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#837]
When `message-kill-buffer-on-exit` is set to `t`, the backup file of the draft should be removed as well otherwise there will be many backup files (`*~`) in the draft folder.

**Comment by djcb** [comment]
Please always mentions the versions of mu/emacs etc.

Seems they're deleted for me.... perhaps some other variable involved? Can you reproduce with just running emacs -Q and mu4e?

**Comment by Chris00** [comment]
Sorry, I forgot.  I use 0.9.16.

**Comment by Chris00** [comment]
On 2016-04-26, Dirk-Jan C. Binnema wrote:
> 
> Seems they're deleted for me.... perhaps some other variable involved? 
> Can you reproduce with just running emacs -Q and mu4e?

I removed the *~ files from the draft folder and will see if it is OK 
now (I am thinking they may be leftovers prior to me activating 
message-kill-buffer-on-exit).

**Comment by Chris00** [comment]
I tried with the Git version of mu4e and `--Q` but when sending a message the backup file in `mu4e-drafts-folder` is *not* removed.

**Comment by Chris00** [comment]
One possibility to fix this is to disable backup files for drafts with `(setq (make-local-variable 'make-backup-files) nil)`.

**Comment by Chris00** [comment]
See the [pull request](https://github.com/djcb/mu/pull/842) for another — more satisfactory — solution.

**Comment by djcb** [comment]
mu4e depends on the emacs settings for backups/auto-save files for this, you could configure those. In particular, `backup-directory-alist` and `auto-save-file-name-transforms`.
