### ISSUE TITLE
Respect message-signature-insert-empty-line

### ISSUE THREAD

**Issue by tomnor** [djcb/mu#838]
## Expected or desired behavior

The emacs variable `message-signature-insert-empty-line` is respected

## Actual behavior

An empty line is not inserted even though the variable is non-nil.

## Steps to reproduce

Have a signature defined, make `message-signature-insert-empty-line` non-nil and do 
`M-x mu4e-compose-new`, observe for an empty line before the signature.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e 0.9.9.6-5
mu 0.9.9.6
emacs 24.4
Debian 3.2.68-1+deb7u1 i686 GNU/Linux (Jessie)

## Other details

The claim I am making on mu4e not respecting the variable is a strong suspicion I have, I am not certain.
What else? mu4e is almost perfect.

**Comment by djcb** [comment]
mu4e (current versions at least!) always add a newline, mu4e does deviate a bit from message-mode when it makes sense. So my advice would be to get a bit newer mu4e.
