### ISSUE TITLE
thread colors

### ISSUE THREAD

**Issue by arrouan** [djcb/mu#839]
there is something weird when switching from mu v 0.9.13 to latest commit:

in 0.9.13 the thread view (inbox) is fine with unread messages in bold, replied in blue and unread in white (with my theme)

in master: all threads appear in white (no bold, no blue)
I tried various themes (and no theme at all) but the error persists.

I am using emacs 24.3.1
(note that tag v.0.9.16 does not work for me: when I jump to inbox, I get the error:
error in process filter: mu4e~headers-line-apply-flag-face: Symbol's function definition is void: add-face-text-property
error in process filter: Symbol's function definition is void: add-face-text-property
)

**Comment by djcb** [comment]
This is due to issue #811; mu4e received a patch that (unwittingly) added a dependency to use 24.4. The hard dependency was fixed with #811, but you're seeing some reduced functionality when using emacs 24.3.
