### ISSUE TITLE
compile binaries using the mingw-w64 tool chain

### ISSUE THREAD

**Issue by chxiaoxn** [djcb/mu#840]
# my trying on porting mu to mingw-w64
It seems that porting `mu to mingw-w64 is quite possible. This is what I did:

Steps:
- replace every line of 

       #include<time.h> 

with the following 

      #ifdef HAVE_TIME_H
      #include <time.h>
      #endif

- mingw-w64 does not ship with `timegm, but has its equivalent counterpart.

- remove the 'timegm' dependecy from the *configure*.

Result: I am able to compile all files to *.o and *.lo in *mu/lib* except *mu-util.c*. The error is `langinfo.h' is not found.

The code I stole is from the following url:

https://github.com/dajobe/rasqal/blob/master/src/timegm.c

I hope the author would consider adding a compatibility wrapper like the above url. Nowadays, it seems mingw-w64 is the way to go on Windows.

# further effort
As I have checked, *langinfo.h* is shipped with mingw-w64 under the directory /usr/include. This directory is not included in the makefile. But adding it would get errors for all *.c files under *mu/lib*.
So the solution might be write separate compilation options for *mu-util.c* if we want to port.

# Other compatibility issues
Other compatibility issues seem to lie in the following three header files:

    #include <sys/types.h>
    #include <sys/stat.h>
    #include <unistd.h>

This would be easier to solve, because mingw-w64 has these files as well. Although different functions names, for example, *lstat* should be *stat* in mingw-w64.

# why I haven't done it?

Because I know nothing of C and C++. I write a little R, mostly lisp and python. The configuration for compiling *mu* is just too much for me.
Above all, I hope this issue would be helpful. Hope to see *mu* on windows soon.

**Comment by djcb** [comment]
I'd be quite happy to take a clean patch to support mingw-w64, but I can't possibly write it, as I don't even use Windows. I don't know how easy/hard it would be, and there might be quite a few subtle porting issues (the example of lstat vs stat is just one).

Anyway, perhaps there's a kind soul who wants to take this task upon him or her.

**Comment by chxiaoxn** [comment]
I further remove the langinfo.h error by providing `--prefix=/usr` option to `./configure`. Now, the error when running `/configure` becomes
 `aclocal-1.15: error: aclocal: file '/msys2/usr/share/aclocal/xsize.m4' does not exist
autoreconf: aclocal failed with exit status: 1
`

which we can say is the predictable case since `msys2`or `mingw-w64` has a different search path mechanism. The correct path to search is `/usr/share/aclocal/xsize.m4`. I wonder how to do that.

It is possible that the only compatibility issue is `timegm` which is solved.  All others might be just `path` problems.

**Comment by chxiaoxn** [comment]
I am able to reduce compatibility issues to only two functions bu using `gnulib` which is
`getuid` and `readdir_r`(deprecated?, see [https://lists.gnu.org/archive/html/bug-gnulib/2016-02/msg00012.html](https://lists.gnu.org/archive/html/bug-gnulib/2016-02/msg00012.html) ) and dependence on `gmime`(some function is missing) I wonder if it was possible to redefine `getuid`
as a dummy function which returns `0`.

**Comment by chxiaoxn** [comment]
defining `getuid=1` gives more errors. disappointing. It is really hard to port.

**Comment by djcb** [comment]
I think the MinGW-environment should provide the posix function... but I'm not too familiar with it. Did you try the normal configure step? I.e., as explained in http://www.gaia-gis.it/spatialite-3.0.0-BETA/mingw64_how_to.html 

I think with some setup it should get you the header-files (like time.h etc.). E.g., mingw-w64 does seem to provide time.h, probably a matter of `configure` to set things up correctly. 

`readdir_r` is another case; it's a re-entrant version of `readdir`, see the manpage. Perhaps a workaround would be possible.

**Comment by chxiaoxn** [comment]
`time.h` is provided by `gnulib`, however, `timegm` still needs the hack I mentioned above, otherwise ugly errors. Using `gnulib`, It's almost minimal change to the `makefile.am configure.ac`.

My approach is first to solve problems that can be solved by `gnulib` and thus reduce workaround to the minimal. It is quite promising, I think. It is just I am not quite familiar with the C/C++ enviroment. It takes time, I may need a little help in later stages. Currently, I am ignoring tests, `guile, mu4e...` stuff. Hope I can get a binary soon. 

I am relatively busy in the following days, I will put more effort later.

**Comment by chxiaoxn** [comment]
I exchanged the build order of different tests and get more `test.*.exe`'s. Results:

> date, flags, msg-fields, str, util passed.

I add a rookie `readdir_r()` so that `maildir` would compile, but it does not pass all tests.

The rest won't compile because of a dependency gmime.

Questions:
1. Does the build order of the tests matter?
2. The platform lacks definition of SIGHUP, and SIGPIPE, can I just assign arbitrary integers to it?

Conclusion of compatibility issues:
1. getuid, geteuid(does these matter, they are in tests?)
2. readdir_r()
3. SIGHUP, SIGPIPE.
4. gmime_gpg_context is missing.

**Comment by djcb** [comment]
Gmime 2.6 is central to mu, that really has to work. With a bunch of other hacks for the other issues mentioned, it might be possible to get things to compile, but you might get unexpected behavior during runtime. Perhaps using Cygwin is a bit easier?

**Comment by chxiaoxn** [comment]
Gmime issues were solved by =gnulib=. The only issues are now
1. getuid, geteuid(does these matter, they are in tests?)
2. readdir_r()
3. SIGHUP, SIGPIPE.
4. =mu= doesnot seem to recognize the windows path separator?

all binaries including =mu= are able to compile actually.
Tests in =./lib/tests=results:

=test-mu-maildir= with segmentation fault, probably due to my implementation of =readdir_r=

=./mu/mu/= test results:
It produces
=Note: Unit tests require the en_US.utf8 locale. Ignoring test cases.=
and test failures. 

I will look into it later( a week maybe)

**Comment by djcb** [comment]
Hmmm, I think this is a bit of an uphill-battle -- are you still working on this? I think using cygwin might be a bit easier.

**Comment by djcb** [comment]
Closing this for now.
