### ISSUE TITLE
Shouldn't mu4e-message-kill-buffer remove the draft file?

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#843]
When `C-c C-k` (`mu4e-message-kill-buffer`) on a draft message, its file is not deleted and so it remains in the draft folder.  Is this the desired behavior??

**Comment by djcb** [comment]
I wouldn't expect anything else, no; the function simply kills the buffer as its name suggests.

**Comment by Chris00** [comment]
While I agree for the function, my question was more about the action of the binding `C-c C-k` which is described in the manual as
```
C-c C-k      kill the message
```
So maybe the manual should be more precise about the action of that binding.  Alternatively, `C-c C-k` could ask whether to also remove the message from the draft folder.

**Comment by djcb** [comment]
`mu4e-message-kill-buffer` is just some window restoration and  `message-kill-buffer` (its docstring mentions this) which it reuses from gnus/message-mode, so we're just following its behavior. Of course, we could do something different, but in this case I think it's quite okay.
