### ISSUE TITLE
Threading+Include Related brings up trashed messages too 

### ISSUE THREAD

**Issue by jhelberg** [djcb/mu#849]
## Expected behavior
When threading + 'include related' is set, the header-view displays related messages in a thread. Related but trashed messages will not appear. 

## Actual behavior
Trashed messages do appear as related messages in the thread.
It seems that mu find does not apply search criteria to the related messages. There is a case for not displaying trashed messages anyway, regardless of filter-content. Even if the filter NOT flag:trashed is used, related trashed messages appear.

## Steps to reproduce
Enable threads and enable include related.
From a conversation, trash one message and see if it appears as related visiting the maildir.

## Versions of mu, mu4e/emacs, operating system etc.
Emacs version 25.1.50.1
Mu4e version 0.9.17

## Any other detail
I think mu find may be better of with a flag: --skip-trashed-in-related-messages or --apply-filter-to-related-too.

I patched this behaviour (somewhat) in elisp, but this has the consequence of mis-interpreting mu4e-headers-results-limit, as that number is applied in mu before lines are removed. It shows what I want though.

```
; handler which does previous handler and also skips trashed messages
(defun my-line-handler-function (msg line)
  "Skip trashed lines"
  (let* ( (myline (mu4e~headers-line-apply-flag-face msg line))
          (flags (mu4e-message-field msg :flags))
          )
    (cond ((memq 'trashed flags) nil)
          (t myline))
    )
  )
(setq mu4e~headers-line-handler-functions
  '(my-line-handler-function))

; only (if line ...) added 
(defun mu4e~headers-header-handler (msg &optional point)
  "Create a one line description of MSG in this buffer, at POINT,
if provided, or at the end of the buffer otherwise."
  (let ((docid (mu4e-message-field msg :docid))
        (line (mapconcat (lambda (f-w)
                           (mu4e~headers-field-handler f-w msg))
                         mu4e-headers-fields " ")))
    (setq line (mu4e~headers-line-handler msg line))
    (if line (mu4e~headers-add-header line docid point msg))))

```

**Comment by djcb** [comment]
For "related" queries, mu actually does two. 

First, it does a normal search, then iterate over the results, adding a list of message-id's referred to in those messages; then it does another query with a big "OR msgid1 OR msgid2 ...", and that includes thrashed messages. 

Not sure if I'd like any special kind of filter on top of that to go into mu; perhaps better to add a user-settable filter in mu4e, a bit generalized version of what you show above.

**Comment by djcb** [comment]
I've added `mu4e-headers-hide-predicate', to selectively hide messages from display. It's just a display filter. Not planning to add anything to mu itself. Perhaps it's a good reminder to clear your trash now and then :)
