### ISSUE TITLE
mu/mu4e cannot find mkdir and find commands

### ISSUE THREAD

**Issue by yitang** [djcb/mu#851]
I am trying to install mu/mu4e on a EC2 server. I got the following errors when I type M-x mu4e in emacs-snapshot version. 

```
error in process filter: Error2: unknow command 'cmd:mkdir'
```

mu4e complains it can't create the draft folder using mkdir so I create the folders manually.  

then I got this error when I jump to a mail directory.

```
error in process filter: Error 2: unknown command 'cmd:find'
```

I am sure I have the mkdir and find commands installed on the server in /usr/bin/ , but mu and mu4e can't find it. what's wrong?

**Comment by djcb** [comment]
Those are part of the protocol between mu4e (the elisp part) and mu (the C server), they are unrelated to the OS "mkdir" and "find" utilities.

I suspect you might be mixing two different versions? I.e. make sure you are using the same versions of mu / mu4e, you can use `mu4e-mu-binary` if necessary.

**Comment by yitang** [comment]
@djcb thanks for your reply. I will double check and see if it works.
