### ISSUE TITLE
Can you please upload mu4e to melpa, so that we can update this easily

### ISSUE THREAD

**Issue by lujianmei** [djcb/mu#854]
Hi, thank you for this very helpful tools, i use this tool over one year, but one thing that is not convenient is i can not auto upgrade this tool.
So hope this can be solved.
Will be very greatful.
Thanks.

**Comment by jschwab** [comment]
See https://github.com/djcb/mu/issues/620 for some previous discussion of this.

**Comment by djcb** [comment]
mu4e is not just elisp, much of it is in C, and elpa does not support that (afaik). Splitting the elisp / C part would allow for all kinds of incompatibilities. In the end, it would be far *less* convenient...
