### ISSUE TITLE
Draft backup files

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#855]
When composing and sending messages, mu4e [leaves auto-save files and backup files around](https://github.com/djcb/mu/pull/842).  What bothers me with that is that these display as standard messages in the headers view of the `mu4e-drafts-folder'.  (Of course, it is not nice that these files stay around but one can configure Emacs to delete them, say, [when they are too old](https://www.emacswiki.org/emacs/BackupDirectory))  I see two ways around:

- Enable the possibility for `mu' to filter out files so that backup and auto-save files do not show up;
- Save these files in another directory (that `mu` will not visit).

Do you have any preferences?

**Comment by djcb** [comment]
I would recommend moving your backups/autosave files elsewhere, but anyway, I've changed indexing so that they are ignored.

**Comment by Chris00** [comment]
> I would recommend moving your backups/autosave files elsewhere

That's what I did — but I thought other people have the same problem so I asked to know  what PR to submit.

> I've changed indexing so that they are ignored.

Thanks.
