### ISSUE TITLE
Attachments with CJK filename will not be saved/opened properly in mu4e

### ISSUE THREAD

**Issue by panjie** [djcb/mu#862]
## Expected or desired behavior

When using mu4e, attachments with CJK filename will be saved/opened properly, with the correct filename.

## Actual behavior

Attachments with CJK filename will be saved/opened properly in mu4e. To be specific, the file could be saved but with a corruptted filename, and the file could not be opened directly.

## Versions of mu, mu4e/emacs, operating system etc.

- mu: 0.9.17
- OS: cygwin under Windows 7
- Cygwin/Emacs-W32: 24.5 (UTF-8 as default encoding)

## Some digging down

1. When I use `mu server` directly, there will be no problem. So the issue is caused within mu4e
2. I used the `(process-send-string mu4e~proc-process "cmd:extract action:save docid:77 index:2 path:\"/home/panjie/attchments/报告书.docx\"\n")` to test and the issue just reoccured.
3. The coding system of mu4e~proc-process is (binary . utf-8-unix)

**Comment by djcb** [comment]
Can you attach an example message where this happens?

**Comment by panjie** [comment]
Problem solved. I found out that the emacs running in an environment where LANG=zh_CN.GB18030, so after I set the LANG to zh_CN.UTF8, the problem solved. 

So, Please close this issue.
