### ISSUE TITLE
sending gpg-encrypted message fails with No public key for …

### ISSUE THREAD

**Issue by ArneBab** [djcb/mu#864]
## Expected or desired behavior

Sending an encrypted email to a user where the email does not match a key should ask the user to specify a key or an alternate email address to query for the key — and offer saving that key or address so the user need not answer that repeatedly.

## Actual behavior

When I try to send an email message via 

    <#secure method=pgpmime mode=signencrypt>

to a friend where the email address does not match the email address in the gpg key, I get 

> No public key for EMAIL_ADDRESS, skip it? (y/n)

## Versions of mu, mu4e/emacs, operating system etc.

- mu 0.9.16
- emacs 24.5.1
- gnupg 2.0.28

## Any other detail

I also have problems reading encrypted email: To see the content, I have to reply (then the email is decrypted and I can reply).

**Comment by djcb** [comment]
The question / handling is done by `mml-secure-select-preferred-keys` (part of gnus) which mu4e re-uses. So your feature-request has probably better chances there.

**Comment by ArneBab** [comment]
ok — thank you for our answer.
