### ISSUE TITLE
when answering a gpg encrypted message, the answer should by default be encrypted, too

### ISSUE THREAD

**Issue by ArneBab** [djcb/mu#865]
## Expected or desired behavior

- I answer an encrypted message.
- It starts with the mime header: <#secure method=pgpmime mode=signencrypt>

## Actual behavior

I have to hit `C-c RET e` everytime I answer an encrypted message, which makes it far too easy to accidentally answer unencrypted (thereby spilling the quoted parts of the message I received) by simply forgetting to explicitly enable encryption.

## Steps to reproduce

hit R on an encrypted email, then hit a to select “reply to all”.

## Versions of mu, mu4e/emacs, operating system etc.

- mu 0.9.16
- emacs 24.5.1
- gnupg 2.0.28

**Comment by semente** [comment]
Also, when replying signed-only messages, would be great if add mime header to sign. An option to always sign encrypted message is welcome too.

There is three kind of PGP messages: signed, encrypted and signed & encrypted:

```
<#secure method=pgpmime mode=sign>
<#secure method=pgpmime mode=encrypt>
<#secure method=pgpmime mode=signencrypt>
```

My proposal is add three options similarly what we have in Gnus:

``` 
Often, you would like to sign replies to people who send you signed messages. Even more often, you might want to encrypt messages which are in reply to encrypted messages. Gnus offers gnus-message-replysign to enable the former, and gnus-message-replyencrypt for the latter. In addition, setting gnus-message-replysignencrypted (on by default) will sign automatically encrypted messages.
```

**Comment by ArneBab** [comment]
that would be great, yes.

**Comment by rekado** [comment]
I'm using this hook to achieve this:

```elisp
(add-hook 'mu4e-compose-mode-hook
  (defun my/maybe-reply-encrypted ()
    (let ((msg mu4e-compose-parent-message))
      (when (and msg (member 'encrypted (mu4e-message-field msg :flags)))
        (mml-secure-message-sign-encrypt)))))
```

**Comment by ArneBab** [comment]
That looks good. Is there a chance to get this into mainline mu4e (so I don’t have to configure the hook for every installation but have it do the right thing automatically instead)?

**Comment by djcb** [comment]
I've added a `mu4e-compose-crypto-reply-policy` configuration variable for this.

**Comment by ArneBab** [comment]
Thank you!

**Comment by MaximeMaW** [comment]
This seems to conflict systematic signature of all sent emails: `(add-hook 'mu4e-compose-mode-hook 'mml-secure-message-sign-pgpmime)`. Is there a way to have sent mails signed by default, and have this setting overriden when replying to an encrypted email?

**Comment by thierryvolpiatto** [comment]
MaximeMaW <notifications@github.com> writes:

> This seems to conflict systematic signature of all sent emails:
> (add-hook 'mu4e-compose-mode-hook
> 'mml-secure-message-sign-pgpmime). Is there a way to have sent mails
> signed by default, and have this setting overriden when replying to an
> encrypted email?

This is handled in Gnus by `gnus-message-replyencrypt` and
`gnus-message-replysign` but AFAIK this have not been ported yet to
mu4e.
Should not be too hard to have similar vars and write a mu4e function
along `gnus-summary-handle-replysign`.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by MaximeMaW** [comment]
Hi Thierry,

This would be great, however, I would be unable to write such function because I can't write lisp. Nonetheless, if anyone could provide some hints on how to achieve that, this would really be awesome.

**Comment by rileyrg** [comment]
Should an encrypted email not remain encrypted when forwarding?  Or only if you have the pub key for the recipient.?  My, own thought is than an encrypted email should never be forwarded as clear text unless specifically requested.

**Comment by ArneBab** [comment]
That sounds like a good rule of thumb.

**Comment by rileyrg** [comment]
Currently forward forwards it in clear text.

**Comment by thierryvolpiatto** [comment]
RichieHH <notifications@github.com> writes:

> Should an encrypted email not remain encrypted when forwarding? Or
> only if you have the pub key for the recipient.? My, own thought is
> than an encrypted email should never be forwarded as clear text unless
> specifically requested.

Not necessarily, for example all my emails are encrypted on server with
my own key, I don't want my replies to be encrypted with this key.
The best approach is to use autocrypt, see
https://git.sr.ht/~zge/autocrypt
https://en.wikipedia.org/wiki/Autocrypt
https://autocrypt.org/index.html

You can reply to any of my emails with the key found in the autocrypt
header (autocrypt should do this for you).
 
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

**Comment by rileyrg** [comment]
My comment was to do with forwarding. I'm not sure any new packages need to
be pulled in.
