### ISSUE TITLE
mu4e inline images' position not right

### ISSUE THREAD

**Issue by amosbird** [djcb/mu#868]
## Expected or desired behavior

Position the inline images in the right place.

## Actual behavior

All inlined images are placed at the bottom of the content.

## Steps to reproduce

View an email with inlined images.

## Versions of mu, mu4e/emacs, operating system etc.
mu :  0.9.17
emacs : 25.0.95.1  with spacemacs develop branch
os : ArchLinux

**Comment by jschwab** [comment]
As a workaround, whenever I receive a message with inline images, I use the ViewInBrowser action.  See point 9 in the following list:  http://www.djcbsoftware.nl/code/mu/mu4e/Reading-messages.html

**Comment by djcb** [comment]
None of the emacs-based html-renderers support inline ("cid:") images, so we can't really show them inline in text mode. If you want that, you can use either @jschwab 's suggestion or (with emacs 25.x with webkit support) view inside emacs using the webkit renderer.

**Comment by Vslow** [comment]
> None of the emacs-based html-renderers support inline ("cid:") images, so we can't really show them inline in text mode. If you want that, you can use either @jschwab 's suggestion or (with emacs 25.x with webkit support) view inside emacs using the webkit renderer.

I open emails in eww using actions functionality and inline images are showed in the correct positions. Still in mu4e they are in the end of the message — makes emails with screenshots very hard to understand. Did something change? Can I somehow make it work in a regular mu4e as well?

**Comment by Chris00** [comment]
Gnus-based viewer shows CID images.  To enable it, put `(setq mu4e-view-use-gnus t)` in your init file.

**Comment by Vslow** [comment]
> Gnus-based viewer shows CID images. To enable it, put `(setq mu4e-view-use-gnus t)` in your init file.

Works for me, thanks a lot!
