### ISSUE TITLE
Attachment not support opxl format file (ommiplan on mac) 

### ISSUE THREAD

**Issue by lujianmei** [djcb/mu#869]
Today when i try to attach a ommiplan file, i got a error: this is a directory, not a file.
Do you know what was wrong with this?
Thanks.

**Comment by panjie** [comment]
The opxl file is a resource bundle, which is actually a folder although looks like a single file in Finder. Folder could not be attached to a mail directly, so you should zip it and attach it.

**Comment by djcb** [comment]
Thanks @panjie... not much we can do about this in mu4e.
