### ISSUE TITLE
Debian's maildir-utils needs to be updated

### ISSUE THREAD

**Issue by ReneFroger** [djcb/mu#872]
After installing mu with `sudo apt install maildir-utils`, I ran into problems. I couldn't get mu4e started in Emacs: `mu4e-error: [mu4e] mu server has version 0.9.11, but we need 0.9.13`                            

When checking `mu --version`, mu was 0.9.11 while 0.9.13 was at least required.

Is there any way to update the Debian repository?

**Comment by ReneFroger** [comment]
Is this repository still maintained yet?

**Comment by jschwab** [comment]
That seems odd.  While you don't mention your Debian version, the list at https://tracker.debian.org/pkg/maildir-utils does not indicate that 0.9.11 is the version included in either stable or testing.

**Comment by djcb** [comment]
@ReneFroger seems you're mixing different versions of mu/mu4e. Both must be the same. Perhaps you have a self-compiled version still installed?

**Comment by tiborsimko** [comment]
@ReneFroger Do you also use Ubuntu's `mu4e` system package?  It works well together with `maildir-utils` for me.  The current Ubuntu 16.04 LTS's package version is 0.9.12-3.  

Just to be sure, you can run `locate` for some mu4e file, such as:

```
$ sudo locate mu4e-main.el
/usr/share/emacs/site-lisp/mu4e/mu4e-main.el
/usr/share/emacs24/site-lisp/mu4e/mu4e-main.el
[...]
```

to confirm that you don't have some other mu4e version installed somewhere.

**Comment by ReneFroger** [comment]
@tiborsimko thanks for your reply, I got this following

`sudo locate mu4e-main.el
/home/ReneFroger/Dropbox/Emacs/.emacs.d/elpa/mu4e/mu4e/mu4e-main.el
/home/ReneFroger/Dropbox/Emacs/.emacs.d/elpa/mu4e/mu4e/mu4e-main.elc
`

**Comment by tiborsimko** [comment]
This may be your different mu4e version... You can run `M-x package-list-packages RET` to uninstall the ELPA/MELPA version of the `mu4e` package from within Emacs, followed by `sudo apt-get install mu4e` to install Ubuntu's `mu4e` system package, which should work well with your `maildir-utils` system package.

**Comment by djcb** [comment]
As mentioned, mixing versions doesn't work, which is one of the reasons why (m)elpa packages of mu4e are a bad idea. Didn't even know they exist!

**Comment by ReneFroger** [comment]
I did the following:

`sudo apt remove maildir-utils`

With `M-x package-list-packages RET` I found only `mu4e-alert` installed. I removed it.

Then  I did the following:

`rm -rf  /home/ReneFroger/Dropbox/Emacs/.emacs.d/elpa/mu4e/mu4e/mu4e-main.el`
`updatedb`
`locate mu4e` 

gave me nothing. Then `mu --version`:

     The program 'mu' is currently not installed. You can install it by typing:
     sudo apt install maildir-utils

Then I installed `sudo apt install maildir-utils`.

After this, `mu --version` gives me the following:

      mu (mail indexer/searcher) version 0.9.11 
      Copyright (C) 2008-2015 Dirk-Jan C. Binnema
       License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
       This is free software: you are free to change and redistribute it.
       There is NO WARRANTY, to the extent permitted by law.

What the heck is going on here? I use a brandnew Ubuntu 16.04 and Xubuntu 16.04.

**Comment by djcb** [comment]
I think on Debian/Ubuntu you need to install a package `mu4e` separately.

**Comment by tiborsimko** [comment]
@ReneFroger Yes, please run also `sudo apt-get install mu4e` as [indicated above](https://github.com/djcb/mu/issues/872#issuecomment-230289333).  Basically:

```console
$ rm -rf /home/ReneFroger/Dropbox/Emacs/.emacs.d/elpa/mu4e
$ sudo apt-get install mu4e
```

**Comment by averter** [comment]
This issue still persists. I have installed maildir-utils and mu4e both from the linux mint repositories and I get the warning whenever I call mu4e from within emacs. I don't have anything installed in MELPA
Mu4e and maildir-utils are version (0.9.12-3) but in the mu4e GUI I see:  mu4e - mu for emacs version 0.9.17 C. 
My setup is almost fully functional but I suspect that this warning is the culprit behind my headaches.

**Comment by djcb** [comment]
I don't really know how Mint is packing mu4e, but I'd expect them to ship the same versions of mu/mu4e. So, if you get these kind of warnings, it's likely you have a different version of mu or mu4e lying around -- perhaps from a manual installation; so perhaps check /usr/bin, /usr/local/bin or wherever you install things.

**Comment by averter** [comment]
They ought to be the same. Running `sudo locate mu4e-main.el` returns 
/usr/local/share/emacs/site-lisp/mu4e/mu4e-main.el
/usr/local/share/emacs/site-lisp/mu4e/mu4e-main.elc
/usr/share/emacs/site-lisp/mu4e/mu4e-main.el
/usr/share/emacs24/site-lisp/mu4e/mu4e-main.el
/usr/share/emacs24/site-lisp/mu4e/mu4e-main.elc

I am using the `/usr/share/...` ones. Should I simply remove the other files then? 
I think it would be sensible for the mu4e/mu repo mantainers to specify the same installation directory in order to avoid this sort of issues.

**Comment by djcb** [comment]
Typically, `/usr/local` is used for locally (self-compiled etc.) versions, while `/usr` is for distro-packages, and it can be quite useful. But indeed, it can be confusing if you mix them up. And you can of course have both, but it requires some extra care in having $PATH etc. set correctly.

If you only need one, and if you want to use the distro packages, remove any trace of mu/mu4e from /usr/local, that should do the trick.

**Comment by averter** [comment]
I have moved them (run the locate just to make sure) and the issue still persists. It is strange isn't it?

**Comment by djcb** [comment]
Did you restart emacs?

If the problem persists after, there's probably some other, earlier mixup -- remove _all_ of  mu/mu4e from your system (ie., `/usr/`), and then verify that it's really all gone. Then,  reinstall the Mint packages and try again. If the problem still persists after, it might be a problem with the Mint package (unlikely).

**Comment by averter** [comment]
Yes I did. I tried to start from scratch, installing mu4e and maildir-utils. It works now. However it is a quite old version 0.9.11 and certain features that I need, e.g. mu4e-contexts are not available. Possibly the best course of action is to install a compiled version. Thanks for the help.
