### ISSUE TITLE
Right-To-Left languge subject and sender lead to wrong presentaion in headers view in mu4e

### ISSUE THREAD

**Issue by kirmot** [djcb/mu#874]
## Expected or desired behavior
To present mail sender in "From" column and mail subject in subject column in headers view
## Actual behaviour
In case of RTL (tested on hebrew, but probably all RTL languages as arabic ) mail presentation is broken and mail subject present in "From" column and mail sender presented in "Subject" column.  
## Steps to reproduce
1) put in yours maildir email with RTL language text in sender and subject headers
2) open headers view. 
3) check that this specific mail break view format. Date and flags columns formatted good, but subject and from swap. 
## Versions of mu, mu4e/emacs, operating system etc.
mu4e version - 0.9.16
## Any other detail
hebrew text example: "טקסט"

**Comment by djcb** [comment]
Can you attach a  message (i.e. the raw message file) that shows this behaviour? Thanks.

**Comment by kirmot** [comment]
Attached. 
[email.txt](https://github.com/djcb/mu/files/345259/email.txt)

**Comment by djcb** [comment]
For me, the headers view looks like the attached... is that wrong in some way? Admittedly my Hebrew is a bit rusty.

![screenshot from 2016-07-17 22-34-27](https://cloud.githubusercontent.com/assets/199741/16902679/e951aacc-4c6e-11e6-8750-35977fc62c64.png)

**Comment by kirmot** [comment]
Interesting,
In yours screenshot presentation is correct, I have this one: 

![screenshot_2016-07-20_20-44-06](https://cloud.githubusercontent.com/assets/8446647/16996640/d92db7be-4eba-11e6-974c-25f20085739a.png)

And another one to show separator between subject and From that not aligned in first and last lines. 
![screenshot_2016-07-20_20-56-51](https://cloud.githubusercontent.com/assets/8446647/16997122/c45aecf6-4ebc-11e6-95c6-62bec8da0a20.png)

**Comment by djcb** [comment]
I suspect it's an emacs configuration issue. Or perhaps that changed quite recently -- can you check the git version? (ie. 0.9.17)?
