### ISSUE TITLE
Images not displaying inline

### ISSUE THREAD

**Issue by mjj55409** [djcb/mu#878]
I'm trying to switch my email workflow to mu4e and it's working for the most part. What I'm struggling with is getting inline images to display inline (and not at the end of the message).

My emacs configuration:

```
;; Use Imagemagick if available
(when (fboundp 'imagemagick-register-types)
  (imagemagick-register-types))

;; For HTML mails
(setq
 w3m-command "/usr/local/bn/w3m"
 mu4e-html2text-command "w3m -dump -T text/html"
 mu4e-view-show-images t
 mu4e-image-max-width 800
 mu4e-view-prefer-html t
 mu4e-use-fancy-chars t)
```

But an email sent like this:

![image](https://cloud.githubusercontent.com/assets/4040911/16691259/92592c2e-44f1-11e6-8158-c0e13bebc560.png)

Renders like this in mu4e:

![image](https://cloud.githubusercontent.com/assets/4040911/16691303/b719fdd6-44f1-11e6-9da7-e8a0263d5214.png)

Am I missing something?

Cheers,
Michael

**Comment by jschwab** [comment]
See https://github.com/djcb/mu/issues/868

**Comment by mjj55409** [comment]
Thanks. The webkit functionality is intriguing. I'm already running a self-compiled 25.x Emacs. But now I'm banging my head against a desk trying to compile a version with xwidgets. Not having much luck yet...
