### ISSUE TITLE
Add --expr <expr> to find-dups.scm

### ISSUE THREAD

**Issue by sje30** [djcb/mu#881]
V. sorry Dirk, my github powers were fooled just now.  I just submitted a patch to find-dups.scm but put it on the wrong fork of github.com! 

It is at: https://github.com/sje30/mu4e/commit/54cd9a39183e051a8bc298d583c77765a6e86bed

**Comment by djcb** [comment]
Oh! I'd swear I merged it already... somewhere. Can you make a PR against master?

**Comment by sje30** [comment]
On Sun, Jul 17 2016, Dirk-Jan C. Binnema wrote:

> Oh! I'd swear I merged it already... somewhere. Can you make a PR
> against master?

Sorry for delay, just sent.

**Comment by djcb** [comment]
Merged.
