### ISSUE TITLE
Feature request: config file for mu

### ISSUE THREAD

**Issue by toothbrush** [djcb/mu#882]
## Scenario

I sometimes configure a new machine for my email with mu.  What invariably happens is this:

1. Install `mu`
2. Run `mu index`
3. Fire up `mu4e`, be surprised that no contacts are found (i use the personal-contacts-only option)
4. Realise i should've run `mu index --my-address="me@myself.org" --my-address="me@evilcorp.com"`, etc.  I also have to look up the exact incantation every time, because i don't do it often enough.

## What i want

I have all my config files in Git/GNU Stow, so it would be wonderful if somewhere i could have a file like `~/.mu/config` which had a few `my-address=...` lines in it, or something like that, so that when i run `mu index --rebuild` it all automatically does The Right Thing™.

My sincere apologies if there is already a way to persist such settings, feel free to tell me to RTFM better.

**Comment by djcb** [comment]
I don't really like the `--my-address` stuff tbh, but I'm not planning to add a configuration file, though I recognize this inconvenience. A shell alias can be useful!

Perhaps we should have a warning.
