### ISSUE TITLE
Option for mu4e to run with --no-cleanup

### ISSUE THREAD

**Issue by gabhab** [djcb/mu#883]
It would be nice to have an option not to cleanup when refreshing emails in mu4e, but just to reindex, as on slow machines this can take a long time (on a macbook 12" with 280k emails, it's taking me about 45s).

(Also, if there is any information about how frequently a cleanup needs to run, that would be good to know - I may have missed it, but I couldn't find any documentation about this.)

**Comment by djcb** [comment]
This is available now; see the mailing-list message for some details (*)

(*) if you're not subscribed: https://groups.google.com/forum/#!topic/mu-discuss/0Uyu0It1du4
