### ISSUE TITLE
Difficult to see highlighted message header in header view

### ISSUE THREAD

**Issue by mjj55409** [djcb/mu#884]
I'm sure this is more of a Emacs/Theme issue than a mu4e specific issue, but in my mu4e, the highlighted message is really difficult to see in the header view:

![image](https://cloud.githubusercontent.com/assets/4040911/16856307/7631051c-49e7-11e6-9044-f6584635d9c5.png)

What do I need to tweak to fix this?

Cheers,
Michael

**Comment by djcb** [comment]
You change change `mu4e-header-highlight-face`. However, the default should typically be quite usable (see its definition), unless the theme does something funny.
