### ISSUE TITLE
Tracker URL in manpage outdated

### ISSUE THREAD

**Issue by Quintus** [djcb/mu#887]
## Expected or desired behavior

The URL in the mu manpages should be https://github.com/djcb/mu/issues.

## Actual behavior

The URL in the mu manpages is http://code.google.com/p/mu0/issues/list.

## Steps to reproduce

Open any mu manpage in man(1) and scroll to the bottom.

## Versions of mu, mu4e/emacs, operating system etc.

mu 0.9.9.6 on Gentoo.

Vale,
Quintus

**Comment by djcb** [comment]
That's a fairly old version; it has long been fixed.
