### ISSUE TITLE
[FR] Improve signature handling if signature already in email (often quoted)

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#888]
## Expected or desired behavior

Signature should be removed when they already exist

## Actual behavior

When responding to an ongoing conversation, especially if top-posting, signatures get added over and over and over again below. Messages eventually end looking like this:

```
Comment in current email
> A comment
>> Quoted text
>>> Some quoted text
>>> --
>>> mysig
>>>
>> --
>> mysig
>>
> --
> mysig
>
--
mysig
```

## Steps to reproduce

Compose a message with a signature to yourself.
Reply to that message (to yourself)

**Comment by djcb** [comment]
So, automatic signature deletions works fine for me... do you see something else?

Dealing with _quoted_ signatures is a bit different matter; we're at the mercy of `message-cite-original-without-signature` here, in particular the regexp it uses for detecting the `--  ` separator. Perhaps you can experiment with the regexp, to see what works? (We're setting it in `mu4e~draft-cite-original`).

**Comment by mankoff** [comment]
Sorry didn't see the previous comment. Yes I was talking about _quoted_ signatures. It would be nice to tidy them up a bit. I seem to have slightly better behavior if I change

      (let ((message-signature-separator "^-- *$")

to

      (let ((message-signature-separator "^[>]*-- *$")

in `mu4e~draft-cite-original`.

**Comment by mankoff** [comment]
It searches from the bottom up though... I wonder if there is a way to define this regex so it is greedy, and finds the last (top) match, which might be `>>>> --`.
