### ISSUE TITLE
index-level mail ignore filter? ..in mu4e?

### ISSUE THREAD

**Issue by deepfire** [djcb/mu#890]
An pre-index message filter would be a nice feature. 

Original issue:

> The manual process of maildir deletion is prone to human mistakes.
> 
> It would have been nice if the mu/mu4e stack supported the user in this process.

**Comment by djcb** [comment]
Actually, it's precisely for the human-mistakes reasons that mu/mu4e try to not make maildir deletion easy -- including human mistakes in the mu/mu4e code...

**Comment by deepfire** [comment]
@djcb, maybe then an alternative -- flexible ignore lists?

**Comment by deepfire** [comment]
@djcb, flexible ignores would also solve another problem I has -- `crm114` marks spam/unsure with `ADV:` / `UNS:` markers in email topics.  If I could filter out some folders/some matching messages from being indexed _at all_.. that would be jolly..

**Comment by deepfire** [comment]
@djcb, renamed in accordance with the new vision of the issue.

**Comment by djcb** [comment]
I do something like that using procmail.

**Comment by djcb** [comment]
I'd recommend use of a tool like procmail or maildrop. There are no current plans to build such functionality into mu/mu4e, so closing this for now.
