### ISSUE TITLE
Switching `mu4e-mu-home` via contexts doesn't quite work

### ISSUE THREAD

**Issue by deepfire** [djcb/mu#892]
Basically almost nothing works properly, when non-default `mu4e-mu-home` is set through `mu4e-contexts` -- for example to `"~/.mu.acc1"` and `"~/.mu.acc2"`.

Actually, even setting `mu4e-mu-home` to non-default value _globally_ (without contexts involved at all) makes searches yield empty results.

**Comment by djcb** [comment]
You cannot change `mu4e-mu-home` through contexts (or otherwise) without quitting mu4e; see the docs; so this is the expected behavior.
