### ISSUE TITLE
A regression pull request #831 broke mu4e-action-view-in-browser

### ISSUE THREAD

**Issue by avar** [djcb/mu#894]
There's a regression after pull request #831 from @j-hao. On the current master 49bc960 if you follow the "FAQ -> Reading messages" documentation and do:

      (add-to-list
       'mu4e-view-actions
       '("View in browser" . mu4e-action-view-in-browser) t)

Reverting bd0fd4b & d16957d fixes the issue. I reverted the former purely because it's needed due to conflicts with the second, but d16957d introduced the issue according to a bisect, opening the HTML in the browser before that worked just fine. Now I get the "Format specifier doesn't match argument type" error.

**Comment by djcb** [comment]
Works fine for me... can you generate a backtrace?  I.e.  M-x toggle-debug-on-error, then reproduce.

**Comment by avar** [comment]
@djcb: I'm bad at elisp, didn't know about `toggle-debug-on-error` the issue became obvious once I did, fixed in pull request #895.

**Comment by djcb** [comment]
Thanks, it has been merged.
