### ISSUE TITLE
Need a mu4e~raw-view-quit-buffer

### ISSUE THREAD

**Issue by amosbird** [djcb/mu#900]
When viewing a raw message, pressing `q` doesn't bring me back to the previous view. Instead, it brings up a mu4e-unrelated buffer. I have to manually switch to `*mu4e-view*` buffer to get back the mail workflow .

**Comment by djcb** [comment]
That should work as it is.

Anyway, please use the template for filing issues, you're leaving out a lot of essential details like versions etc.
