### ISSUE TITLE
Search for part of sender email address

### ISSUE THREAD

**Issue by tuxella** [djcb/mu#901]
When searching in the sender (or recipient) address, I'd like to be able to search with only a part of the address.

For instance email address in `firstname.lastname@domain.com` is very common, and in this case i'd like to be able to use a query such as `from:firstname` in mu4e.

**Comment by jschwab** [comment]
When you're searching for the first part of a string, you should be able to use a wildcard in the search, i.e.,  `from:firstname*`.

**Comment by tuxella** [comment]
Thank you, I didn't know you had to put the globbing * for it to match the end of the string, I expected mu to split e-mail adresses on punctuation characters (- . and @ at least).

Is it something we can act on, are we somewhat restricted by Xapian or is it not a desirable behaviour?

**Comment by titaniumbones** [comment]
my understanding from #752 is that this is a limitation of Xapian and so nothing can be done. If someone has a lisp-y workaround I would love to hear it. for instance, I would love to be able to filter (in or out) all messages from `*@*.github.com` -- github is cilling me right now

**Comment by djcb** [comment]
mu now has a new query-parser which supports regexps; searching for `from:/firstname.*/` should do the trick.
