### ISSUE TITLE
mu4e-view-toggle-html is clobbered by the mu4e-view-html-plaintext-ratio-heuristic

### ISSUE THREAD

**Issue by avar** [djcb/mu#902]
This logic: https://github.com/djcb/mu/blob/master/mu4e/mu4e-message.el#L169 doesn't play nicely with the "h" option added in 29a44e4.

If you're viewing an E-Mail where the mu4e-view-html-plaintext-ratio-heuristic kicks in pressing "h" in the view mode does nothing to fix the issue, this is because as far as the heuristic goes the text/plain body is still too small.

This occurs e.g. with Facebook's notification E-Mails, where the HTML is so big that I need to set mu4e-view-html-plaintext-ratio-heuristic to 10 (which was changed in 48388c9, see issue #743).

Instead any interactive action like pressing "h" should trump some heuristic set in the config.

**Comment by djcb** [comment]
This is made obsolete with the new gnus-based article mode; closing.

**Comment by phil-s** [comment]
> This is made obsolete with the new gnus-based article mode

How so?  I just tried setting `mu4e-view-use-gnu` and `h` now tells me "binding not supported with the gnus-based view".

It seems as if we now have two different viewers with the same problem -- *neither* of them let us switch to the text view of the message.

This is still a bug in 1.4.9, so far as I can see.  I agree with @avar -- the heuristic should be used for the initial display, but typing "h" should take precedence.
