### ISSUE TITLE
After switching from HTML mode URLs are not clickable

### ISSUE THREAD

**Issue by avar** [djcb/mu#904]
This is because when we enter mu4e-view a bunch of setup stuff like (mu4e~view-make-urls-clickable) is called, but (mu4e-view-refresh) doesn't call that, so when you:

    view html mail(no urls) -> switch to text/plain via "h" (some urls) -> press "g"

You can't select any URLs, because the internal view state hasn't been updated for the view we're actually using.

**Comment by djcb** [comment]
The setup stuff is called, but the mode switch kill the link-map. Fixed.
