### ISSUE TITLE
View multiple messages at the same time

### ISSUE THREAD

**Issue by panjie** [djcb/mu#905]
Sometimes I want to view several messages side by side, while mu4e doesn't provide such mechanism to do so. When I open a new window to view another message, the original message window will just close.

**Comment by edumerco** [comment]
Hi Pan.

> Sometimes I want to view several messages side by side, while mu4e
> doesn't provide such mechanism to do so. When I open a new window to
> view another message, the original message window will just close.

The same happens to me. Wouldn't it be useful to leave that to the User
control? Like Enter to open in the same window and S-Enter to open in a
new one.

This can peacefully coexist with logical defaults, like new or same
window...


-- 
eduardo mercovich 

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación.

**Comment by djcb** [comment]
Currently, messages are always connected to a headers-view, and need that connection to be able to do things with the message. So, there's a 1:1 relation between the two. Of course, that could _change_, but that's not really planned right now.

**Comment by panjie** [comment]
I make a workaround about this, and provide it with [mu4e-goodies](https://github.com/panjie/mu4e-goodies). The workaround is as the following:
```elisp
;;
;; Allow a mu4e-view buffer detached from mu4e-header so that it will be
;; retained in a seperated window or frame.
;;
(defun mu4e-goodies-detach-view-to-win-or-frame (&optional toframe focusnew)  
  "Detach the current mu4e-view buffer from header to a new
splitted window or a new frame.

If toframe is t, the detached message view will be presented in a
new frame. Otherwise it will be presented in a splitted window.

If focusnew is t, the new window/frame will be focused"
  (interactive)
  (let* ((buf (current-buffer))
         (win (selected-window))
         (new-win nil)
         (frm nil))
    (when (string= (buffer-name buf) mu4e~view-buffer-name)
      ;; rename it so that it will not be found by mu4e-view
      (rename-buffer (concat "*mu4e-view*" (mu4e-msg-field mu4e~view-msg :subject) "*") t)
      (setq mu4e~view-buffer nil)
      (if toframe
          (progn
            (setq frm (make-frame))
            (select-window win))
        (setq new-win (split-window-below)))
      (mu4e-view mu4e~view-msg mu4e~view-headers-buffer)
      (when focusnew
        (if toframe
            (select-frame frm)
          (select-window new-win))))))

(define-key 'mu4e-view-mode-map "\'" 'mu4e-goodies-detach-view-to-win-or-frame)
```

**Comment by metalipa** [comment]
Thank you very much, this is very useful. 
Here is just a minor modification which works with current mu4e 1.2.0:

    (require 'mu4e-goodies)
    ;;  
    ;; Allow a mu4e-view buffer detached from mu4e-header so that it will be  
    ;; retained in a seperated window or frame.  
    ;;  
    (defun mu4e-goodies-detach-view-to-win-or-frame (&optional toframe focusnew)    
      "Detach the current mu4e-view buffer from header to a new  
    splitted window or a new frame.  

    If toframe is t, the detached message view will be presented in a  
    new frame. Otherwise it will be presented in a splitted window.  

    If focusnew is t, the new window/frame will be focused"  
      (interactive)  
      (let* ((buf (current-buffer))  
	     (win (selected-window))  
	     (new-win nil)  
	     (frm nil))  
	(when (string= (buffer-name buf) mu4e~view-buffer-name)  
	  ;; rename it so that it will not be found by mu4e-view  
	  (rename-buffer (concat "*mu4e-view*" (mu4e-msg-field mu4e~view-message :subject) "*") t)  
	  (setq mu4e~view-buffer nil)  
	  (if toframe  
	      (progn  
		(setq frm (make-frame))  
		(select-window win))  
	    (setq new-win (split-window-below)))  
	  (mu4e-view mu4e~view-message)  
	  (when focusnew  
	    (if toframe  
		(select-frame frm)  
	      (select-window new-win))))))  

    (define-key 'mu4e-view-mode-map "\'" 'mu4e-goodies-detach-view-to-win-or-frame)

**Comment by djcb** [comment]
You can now "detach" (an "attach") messages in `master`, see "Detaching and reattaching messages" in the manual.
