### ISSUE TITLE
Problems with displaying filled paragraphs (mu4e-fill-paragraph)

### ISSUE THREAD

**Issue by holtzermann17** [djcb/mu#908]
## Expected or desired behavior

<kbd>M-q</kbd> should fill `>`-quoted text nicely.

## Actual behavior

According to copy and paste, <kbd>M-q</kbd> in a mu4e:compose mode buffer turns this text...

```
On Mon, Aug 15 2016, Amazon.co.uk wrote:

> We thought you'd like to know that we've dispatched your item(s). Your order is on the way, and can no longer
> be changed. If you need to return an item or manage other orders, please visit Your Orders on
> Amazon.co.uk.
```

into:

```
On Mon, Aug 15 2016, Amazon.co.uk wrote:
   
> We thought you'd like to know that we've dispatched your item(s). Your
> order is on the way, and can no longer be changed. If you need to
> return an item or manage other orders, please visit Your Orders on
> Amazon.co.uk.
```

(as desired!)

However, here is what it displays:

![mu4e-fill](https://cloud.githubusercontent.com/assets/179958/17697997/48b1341c-63b0-11e6-9b3f-62afe53b52ce.png)

Or, with a narrower window,

![mu4e-fill-narrow](https://cloud.githubusercontent.com/assets/179958/17698002/5020c384-63b0-11e6-9345-8100e0aba2fd.png)

## Versions of mu, mu4e/emacs, operating system etc.

```
GNU Emacs 25.1.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.13)
 of 2016-08-15

joe@Teacup:~/mu$ git log
commit 250793317669f415385623082cf91d35c28c16f5
Date:   Sat Aug 13 23:01:50 2016 +0300
```

**Comment by holtzermann17** [comment]
Note, whitespace seems to be important.  Here's the text above with `whitespace-mode` enabled.

![whitespace-mode](https://cloud.githubusercontent.com/assets/179958/17698176/69f177c6-63b1-11e6-8fe7-a0e87f07b118.png)

If I `delete-trailing-whitespace` before filling the region, I get the desired result.  Otherwise, I get a weird result with gaps in it that are **not** whitespace characters.

**Comment by holtzermann17** [comment]
Quick fix, but I don't know if this will mess anything else up. 

``` lisp
(defun mu4e-fill-paragraph (&optional region)
  "If `use-hard-newlines', takes a multi-line paragraph and makes
it into a single line of text.  Assume paragraphs are separated
by blank lines.  If `use-hard-newlines' is not enabled, this
simply executes `fill-paragraph'."
  ;; Inspired by https://www.emacswiki.org/emacs/UnfillParagraph
  (interactive (progn (barf-if-buffer-read-only) '(t)))
  (if mu4e-compose-format-flowed
    (let ((fill-column (point-max))
	   (use-hard-newlines nil)); rfill "across" hard newlines
      (delete-trailing-whitespace)
      (fill-paragraph nil region))
    (delete-trailing-whitespace)
    (fill-paragraph nil region)))
```

**Comment by djcb** [comment]
Seems it works okay... I've pushed your change, let's see if we hit upon any corner-cases...
