### ISSUE TITLE
Post-indexing hooks

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#916]
I've used notmuch for a month or so in order to give it a try, and one of the features that I came to appreciate were the 'post-indexing' hooks and ability to tag messages arbitrarily.

The basic idea is to tag new messages with an user-customizable keyword, such as "just-indexed".
Run some hooks in order for the user to process "just-indexed" messages. Then remove "just-indexed" after the hook. "just-indexed" is just made-up, as in notmuch I used "new" (not to be confused with the unread flag).

notmuch allows pre/post-index as well as post-insert hooks (for new messages and messages injected via send or move through the UI) to be regular script. In the script, you can query and execute operations on messages from the command line. In mu4e, I would actually like this to be just a guile script loaded in the server instance.

For example, you can implement "muting" (as discussed in #636) by setting any message of a thread with a "muted" keyword. In the post-index hook, search all threads containing both "new" and "muted" messages, then set "muted" on all new messages. From the UI, just exclude "keyword:muted".

I also used the same mechanism to replace almost all server-side processing (via sieve or procmail) locally, which might come in handy if you don't own the server itself.

I think the guile API is already pretty comprehensive. We just need the actual hook mechanism on the server/indexing process.

**Comment by djcb** [comment]
mu doesn't have keyword/tagging support like notmuch does (mu only stores keyword/tag-info it finds in messages). There's also no easy way to hook up guile scripting to new messages.

It's software, so anything could be changed/added given enough time, but I don't see this happening with the current mu.
