### ISSUE TITLE
org-add-link-type deprecated in org development version

### ISSUE THREAD

**Issue by wmzook** [djcb/mu#918]
With the recent development versions of org-mode, storing links to messages in mu4e no longer works because org-add-link-type has been deprecated.  To accomodate this change in org-mode, edit org-mu4e.el, replacing the lines

(org-add-link-type "mu4e" 'org-mu4e-open)
(add-hook 'org-store-link-functions 'org-mu4e-store-link)

with the single line

(org-link-set-parameters "mu4e" :follow #'org-mu4e-open :store #'org-mu4e-store-link)

FWIW, I noticed that org-mew.el, org-notmuch.el, org-vm.el, and org-wl.el are maintained in org-mode/contrib (support for the "distributed with emacs" mail clients is provided in the base package as org-gnus.el, org-mhe.el, and org-rmail.el).  Would it make sense to move org-mu4e.el to org-mode/contrib as well in order to avoid creating another org-old-mu4e.el?

**Comment by djcb** [comment]
This has been merged now.

Indeed, it'd make sense to move the linking support in `org-mu4e.org` to org; some of the other code should probably stay part of of mu4e.
