### ISSUE TITLE
mu4e exceeds the number of allowed Lisp variable bindings

### ISSUE THREAD

**Issue by peterwvj** [djcb/mu#919]
I was trying to view a message that is part of a conversation - see the image below

![mu4e-conversation-dept](https://cloud.githubusercontent.com/assets/5388919/18430718/f6220fde-78d9-11e6-88d7-0715c8f58c1e.png)

When I view the message (by hitting ENTER)  the following error is produced:

![mu4e-error](https://cloud.githubusercontent.com/assets/5388919/18430739/0daa3d84-78da-11e6-9c07-76859ad8fb31.png)

So the number of variable bindings is too small. I should say that the problem seems to be related to the depth of the conversation. The immediate fix is to increase the size of `max-specpdl-size`, for example:

``` Lisp
(setq max-specpdl-size 2600)  
```

I'm using version 0.9.17, running on a Linux 64 bit (Ubuntu Gnome) machine.

My only concern is that this happens for realistic-sized conversations. Would it be better to increase the default value of `max-specpdl-size` to reduce the chances of this happening?

**Comment by djcb** [comment]
Hmm, interesting... I wonder why we're binding so many variables..., but you're right, perhaps we should increase the default value.

**Comment by thblt** [comment]
I've experienced the same issue, but on less nested threads.  In one case, the first message of a thread appeared truncated, and setting max-specpdl-size to 5000 fixed it.  I have kept a copy of the raw message and can sent it by private e-mail if it can be of any help.

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Hmm, interesting... I wonder why we're binding so many variables...,
> but you're right, perhaps we should increase the default value.

I have here 100000 in .emacs since years without any problems...

--
Thierry

**Comment by djcb** [comment]
@thblt oh yes, if you can share that message, that'd be interesting

**Comment by thblt** [comment]
@djcb I sent you an e-mail.

**Comment by djcb** [comment]
@thblt: thanks.

So, I've added a note about increasing `max-specpdl-size` to the documentation now; of course we could increase the value, but that seems a bit unhygienic as it is an emacs-wide setting.
