### ISSUE TITLE
plaintext-ratio-heuristic breaks non-HTML messages 

### ISSUE THREAD

**Issue by eigengrau** [djcb/mu#923]
I’ve noticed that after setting `mu4e-view-html-plaintext-ratio-heuristic` to `most-positive-fixnum`,  a lot of messages which are either just *all* text/plain, or multipart/mixed, will display as if they were empty.

E.g., the following text/plain message is shown as empty when the heuristic is disabled; when it’s reset to a ratio of 5, the message is displayed correctly.

```
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

Sehr geehrter Benutzer,

Die an redacted angeschlossene USV ist wieder zum Akkumodus gewechselt. redacted wird heruntergefahren, sobald der USV-Akku leer ist. Schalten Sie redacted manuell aus oder stellen Sie die externe Stromversorgung so schnell wie möglich wieder her.

Mit freundlichen Grüßen
Synology RackStation
```

The following multipart/mixed message triggers the same behavior.

```
Content-Type: multipart/mixed; boundary="===============7914925388072680638=="
MIME-Version: 1.0

--===============7914925388072680638==
Content-Type: text/plain; charset="gb2312"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

VGhpcyBpcyBhIERNQVJDIGFnZ3JlZ2F0ZSByZXBvcnQgZm9yIGxpbmd1aXN0aWNzLnJ1Yi5kZS4=

--===============7914925388072680638==
Content-Type: Application/octet-stream;
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
[…]
```

This is happening with mu 62370af, Emacs 25.1.1.

BTW is there a way to view an arbitrary buffer as if it were opened via mu4e? I wanted to check whether this is somehow related to the headers I stripped here. I tried pasting a raw message into a buffer and enabling mu4e-view-mode there, but to no avail.

Thanks for making mu!

**Comment by djcb** [comment]
Again, can you attach a message where this happens? Thanks.

**Comment by eigengrau** [comment]
Right, here’s one in full: [raw.txt](https://github.com/djcb/mu/files/501597/raw.txt)

**Comment by djcb** [comment]
I've pushed a candidate fix -- does it solve the problem for you? And perhaps #922 as well?

**Comment by eigengrau** [comment]
@djcb thank you kindly for the patch. Both this issue and #922 don’t occur anymore as of 9a3ff05. 

However, I’ve noticed that now, with `plaintext-ratio-heuristic` set to `most-positive-fixnum`, it is not possible to enable HTML display (`mu4e-view-toggle-html`) anymore (point will return to the first character, but nothing else happens). With `plaintext-ratio-heuristic` set to the default of 5, HTML display can be toggled only for some messages, while for others (even those that have HTML parts), nothing happens. E.g., [here](https://github.com/djcb/mu/files/507888/raw.txt) is a message for which HTML cannot be toggled at all.

**Comment by djcb** [comment]
Thanks -- closing these then. The other issue you mention is tracked in #902.

**Comment by eigengrau** [comment]
Thank you!
