### ISSUE TITLE
mu4e-hide-index-messages still erases minibuffer

### ISSUE THREAD

**Issue by antoine-levitt** [djcb/mu#925]
Set mu4e-hide-index-messages to t, set mu4e-update-interval to a small interval, write something in the minibuffer (e.g. start an isearch, or (message) something), watch it get erased when the indexing does its thing.

I traced it back to a (message nil) in the function mu4e~update-sentinel-func. Removing it fixes this problem. There are a couple others in the code, not sure why they're needed?

**Comment by djcb** [comment]
They clear up the echo area. But I made the one in the sentinel function conditional on `mu4e-hide-index-messages`.
