### ISSUE TITLE
mu4e~mark-in-context is very noisy

### ISSUE THREAD

**Issue by antoine-levitt** [djcb/mu#926]
When I do M-x mu4e-headers-search, mu4e prints the major mode of the mode I'm in, which is pretty weird. That's because that function calls mu4e-mark-handle-when-leaving, which uses the macro mu4e~mark-in-context, which, when there is no mu4e buffer available, does 

(progn (mu4e-message "%S" major-mode) ,@body)

As far as I can tell there's no reason for either the message or indeed the execution of the body, so I guess that's mostly debug? The following patch does not seem to break anything:

```
diff --git a/mu4e-mark.el b/mu4e-mark.el
index 4b17f34..69adbec 100644
--- a/mu4e-mark.el
+++ b/mu4e-mark.el
@@ -119,10 +119,9 @@ is either a headers or view buffer."
        ;; even in other modes (e.g. mu4e-main-mode we try to find
        ;; the headers buffer
        (let ((hbuf (mu4e~mark-find-headers-buffer)))
-	 (if (buffer-live-p hbuf)
+	 (when (buffer-live-p hbuf)
 	   (with-current-buffer hbuf
-	     ,@body)
-	   (progn (mu4e-message "%S" major-mode) ,@body))))))  
+	     ,@body))))))
 
 (defvar mu4e-marks
     '((refile
```

I know it's not a particularly huge bug, but these messages annoy me, and if I submit my patches upstream, then I don't have to maintain them in my .emacs :)

**Comment by djcb** [comment]
Ah thanks, yes, it's a debug string. I've removed it now. Thanks!
