### ISSUE TITLE
jump error

### ISSUE THREAD

**Issue by mfiano** [djcb/mu#931]
## Expected or desired behavior

I expect it to jump to some maildir.
## Actual behavior

When pressing 'j' in the main view, I get: Wrong type argument: characterp, nil
## Steps to reproduce

Press 'j' in the main view of mu4e.
## Versions of mu, mu4e/emacs, operating system etc.

mu/mu4e version 9a3ff05192c0e4a5a6fe8d3abe4d1b1d0e796bbc
Emacs 25.1
## Any other detail

Also occurs with:
mu/mu4e release 0.9.16 under Emacs 25.1

**Comment by djcb** [comment]
Can you get a backtrace from this? Ie. M-x toggle-debug-on-error, then reproduce, than paste the output? Thanks.

**Comment by mfiano** [comment]
Here you go:

```
Debugger entered--Lisp error: (wrong-type-argument characterp nil)
  make-string(1 nil)
  #[(item) "\301\302\303\304A\"\305\306#\307@R\207" [item "[" propertize make-string 1 face mu4e-highlight-face "]"] 5](("/INBOX"))
  mapconcat(#[(item) "\301\302\303\304A\"\305\306#\307@R\207" [item "[" propertize make-string 1 face mu4e-highlight-face "]"] 5] (("/INBOX") ("ther" . 111)) ", ")
  mu4e-ask-maildir("Jump to maildir: ")
  (let ((maildir (mu4e-ask-maildir "Jump to maildir: "))) (list maildir))
  call-interactively(mu4e~headers-jump-to-maildir nil nil)
  command-execute(mu4e~headers-jump-to-maildir)
```

**Comment by djcb** [comment]
And what does `H-v mu4e-maildir-shortcuts RET` say?
