### ISSUE TITLE
[mu4e] Display different colors for different citation levels in the composing buffer, like the viewing buffer

### ISSUE THREAD

**Issue by xuhdev** [djcb/mu#932]
## Expected or desired behavior

The color of the cited texts in composing buffer is different depending on the citation level.
## Actual behavior

Only one color is used for all levels of cited texts.

Possible solution: [colorizing multiply-quoted lines](https://www.emacswiki.org/emacs/MessageMode#toc7)

**Comment by xuhdev** [comment]
But this is not when you hit reply... This setting only works in the viewing buffer.

**Comment by edumerco** [comment]
> But this is not when you hit reply... This setting only works in the
> viewing buffer.

Ah, now I understood you. Yes, you are totally right. :)
Maybe the settings should apply to both type of buffers? 

-- 
eduardo mercovich 

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación.

**Comment by xuhdev** [comment]
Yeah I agree. But something must be done for it.

**Comment by xuhdev** [comment]
I've written a patch to have this feature in `message-mode`, which affects mu4e as well:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25022#8

**Comment by csantosb** [comment]
Try that

    (add-hook 'mu4e-compose-mode-hook
			  (lambda()
			    (require 'gnus-cite)
			    (gnus-message-citation-mode)))

and maybe that too

    (put 'gnus-cite-1 'face-alias 'mu4e-cited-1-face)
    (put 'gnus-cite-2 'face-alias 'mu4e-cited-2-face)
    (put 'gnus-cite-3 'face-alias 'mu4e-cited-3-face)
    (put 'gnus-cite-4 'face-alias 'mu4e-cited-4-face)
    (put 'gnus-cite-5 'face-alias 'mu4e-cited-5-face)
    (put 'gnus-cite-6 'face-alias 'mu4e-cited-6-face)
    (put 'gnus-cite-7 'face-alias 'mu4e-cited-7-face)

it does it for me.

**Comment by edumerco** [comment]
Hola Cayetano.

> Try that
> (add-hook 'mu4e-compose-mode-hook
> 		  (lambda()
> 		    (require 'gnus-cite)
> 		    (gnus-message-citation-mode)))
> (put 'gnus-cite-1 'face-alias 'mu4e-cited-1-face)
> (put 'gnus-cite-2 'face-alias 'mu4e-cited-2-face)
> (put 'gnus-cite-3 'face-alias 'mu4e-cited-3-face)
> (put 'gnus-cite-4 'face-alias 'mu4e-cited-4-face)
> (put 'gnus-cite-5 'face-alias 'mu4e-cited-5-face)
> (put 'gnus-cite-6 'face-alias 'mu4e-cited-6-face)
> (put 'gnus-cite-7 'face-alias 'mu4e-cited-7-face)

It's not working for me... :(

I have here:
+ GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 
2016-03-19 on trouble, modified by Debian
+ mu4e version 0.9.18 CG

GNU is installed by defaul, so I don't know how to diagnose 
this...

Thanks a lot for sharing. :)


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by csantosb** [comment]
Ok, if you follow the discussion in the links above, you'll
see a patch was proposed but never accepted.

Try this, look for `gnus-cite.el` and the line

    (define-minor-mode gnus-message-citation-mode

Then use this code instead of the default one

    nil ;; init-value
    "" ;; lighter
    nil ;; keymap
    (when (derived-mode-p 'message-mode)
      ;; (eq major-mode 'message-mode)   ;FIXME: Use derived-mode-p.
      ;; FIXME: Use font-lock-add-keywords!
      (let ((defaults (car (if (featurep 'xemacs)

I am using emacs "25.2.1", mu 0.9.19 C.

**Comment by edumerco** [comment]
Hi Cayetano.

> Ok, if you follow the discussion in the links above, you'll
> see a patch was proposed but never accepted.

Ah, sorry, didn't understood the dependence... :)

> Try this, look for gnus-cite.el and the line [...]

I have only a gnus-cite.elc in my system. What could be happening?
gnus is built in, and I have version 5.13

Thanks a lot...


PD: if it's not related/useful to other people or the thread, we 
can keep the conversation aside. 
-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by csantosb** [comment]
> 29 mai 2017, 16:36, Eduardo Mercovich ...

> Hi Cayetano.
>
>> Ok, if you follow the discussion in the links above, you'll
>> see a patch was proposed but never accepted.
>
> Ah, sorry, didn't understood the dependence... :)
>
>> Try this, look for gnus-cite.el and the line [...]
>
> I have only a gnus-cite.elc in my system. What could be 
> happening?
> gnus is built in, and I have version 5.13

Same as me then.

> Thanks a lot...

I do have gnus-cite.el.gz along with gnus-cite.elc, don't you ?; I 
modified the former as root. I should be possible to proceed 
differently thought.

> PD: if it's not related/useful to other people or the thread, we
> can keep the conversation aside.
> --
> eduardo mercovich
>
>  Donde se cruzan tus talentos
>  con las necesidades del mundo,
>  ahí está tu vocación.
>  (Anónimo)

**Comment by edumerco** [comment]
Hi Cayetano.

[...]

>>> Try this, look for gnus-cite.el and the line [...]

>> I have only a gnus-cite.elc in my system. What could be 
>> happening? gnus is built in, and I have version 5.13 [...]

> I do have gnus-cite.el.gz along with gnus-cite.elc, don't you ?; 
> I modified the former as root. I should be possible to proceed 
> differently thought.

I don't have it... could it be related to the fact that I 
installed emacs from Debian package manager and so, I don't have 
the source?
I see a separate "emacs24.el" package with this description: 

  Archivos de LISP (.el) del Emacs de GNU 
  
  El Emacs de GNU es un editor de texto extensible y 
  autodocumentado.
  Este paquete contiene los archivos fuente de elisp para 
  conveniencia de los usuarios, ahorrando espacio en el paquete 
  principal para sistemas pequeños.

I can't install it because it creates broken packages and makes 
apt try to install another emacs version...

If this is the case, maybe I can install whatever package gives 
this gnus-cite.el from within emacs package manager?


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by csantosb** [comment]
> 29 mai 2017, 22:15, Eduardo Mercovich ...

>>>> Try this, look for gnus-cite.el and the line [...]
>
>>> I have only a gnus-cite.elc in my system. What could be
>>> happening? gnus is built in, and I have version 5.13 [...]
>
>> I do have gnus-cite.el.gz along with gnus-cite.elc, don't you 
>> ?;
>> I modified the former as root. I should be possible to proceed
>> differently thought.
>
> I don't have it... could it be related to the fact that I
> installed emacs from Debian package manager and so, I don't have
> the source?

Ok, so I solved the issue by just modifiying the relevant minor 
mode. Forget about the patch to the original source code in 
`gnus-cite.el`.

Steps to make it work:

    (add-hook 'mu4e-compose-mode-hook
        (lambda()
            (require 'gnus-cite)
            (gnus-message-citation-mode)))

    (put 'gnus-cite-1 'face-alias 'mu4e-cited-1-face)
    (put 'gnus-cite-2 'face-alias 'mu4e-cited-2-face)
    (put 'gnus-cite-3 'face-alias 'mu4e-cited-3-face)
    (put 'gnus-cite-4 'face-alias 'mu4e-cited-4-face)
    (put 'gnus-cite-5 'face-alias 'mu4e-cited-5-face)
    (put 'gnus-cite-6 'face-alias 'mu4e-cited-6-face)
    (put 'gnus-cite-7 'face-alias 'mu4e-cited-7-face)

Then redefine the relevant section of the source, namely, the 
definition of `gnus-message-citation-mode`


    (define-minor-mode gnus-message-citation-mode
  "Minor mode providing more font-lock support for nested 
  citations.
When enabled, it automatically turns on `font-lock-mode'."
  nil ;; init-value
  "" ;; lighter
  nil ;; keymap
  (when
      (derived-mode-p 'message-mode)
    ;; (eq major-mode 'message-mode)   ;FIXME: Use derived-mode-p.
    ;; FIXME: Use font-lock-add-keywords!
    (let ((defaults (car (if (featurep 'xemacs)
                             (get 'message-mode 
                             'font-lock-defaults)
                           font-lock-defaults)))
          default keywords)
      (while defaults
        (setq default (if (consp defaults)
                          (pop defaults)
                        (prog1
                            defaults
                          (setq defaults nil))))
        (if gnus-message-citation-mode
            ;; `gnus-message-citation-keywords' should be the last
            ;; elements of the keywords because the others are 
            unlikely
            ;; to have the OVERRIDE flags -- XEmacs applies a 
            keyword
            ;; having no OVERRIDE flag to matched text even if it 
            has
            ;; already other faces, while Emacs doesn't.
            (set (make-local-variable default)
                 (append (default-value default)
                         gnus-message-citation-keywords))
          (kill-local-variable default))))
    ;; Force `font-lock-set-defaults' to update 
    `font-lock-keywords'.
    (if (featurep 'xemacs)
        (progn
          (require 'font-lock)
          (setq font-lock-defaults-computed nil
                font-lock-keywords nil))
      (setq font-lock-set-defaults nil))
    (font-lock-set-defaults)
    (cond (font-lock-mode
           (if (fboundp 'font-lock-flush)
               (font-lock-flush)
             (font-lock-fontify-buffer)))
          (gnus-message-citation-mode
           (font-lock-mode 1)))))

The modification with respect to the original is in

    (derived-mode-p 'message-mode)
    ;; (eq major-mode 'message-mode)   ;FIXME: Use derived-mode-p.

Does it make it for you ?

**Comment by djcb** [comment]
Note, this works just fine (with 1.5.x at probably some earlier, too).
