### ISSUE TITLE
Gmail and drafts

### ISSUE THREAD

**Issue by antoine-levitt** [djcb/mu#938]
Hi,

My setup is mu4e + mbsync + gmail, which I suspect many people use. I want to be able to edit drafts, with synchronization going both ways between mu4e and gmail.

The first problem I have is that gmail apparently doesn't set the "D" suffix for drafts. Therefore, when I do "E" in the drafts mailbox, mu4e refuses to edit it. Could mu4e have a workaround for this? A whitelist of maildirs that are allowed to be edited?

The second problem I have is that when I create drafts in mu4e, I get draft files that look like

1476790027.b70383ace79cff96.epsilon:2,DS

When mbsync handles them, it renames them to something like

1476790027.b70383ace79cff96.epsilon,U=53:2,DS

and mu4e gets confused: if I keep editing my draft, it agains creates a file without U=, which mbsync syncs with an increasing U= value, and then I'm left with tons of drafts. I posted on the mbsync mailing list: https://sourceforge.net/p/isync/mailman/message/35436858/, but I'm not sure what to take from that: is it a problem with mu4e, with mbsync, with gmail...?

**Comment by djcb** [comment]
Fundamentally, `mu` / `mu4e` only care about what's in the maildir; how you get it there (through mbsync, offlineimap, fetchmail, a local mailserver,...) is really not of mu's concern; it tries to follow the rules for maildirs.

By happy 'coincidence', offlineimap and mbsync use something that's *almost* a normal maildir as their local cache. The imap protocol (as mentioned in the link) doesn't say anything about how drafts should be treated in the local cache, but of course it's convenient for mbsync to do it the way it does.

AFAIK, there's no current effort for adding more "second-guessing" code to mu, so I'd recommend simply excluding the drafts dir from synchronization, or not saving them too often.... For the "D" issue, you could add a renaming step at the end of the synchronization.

**Comment by antoine-levitt** [comment]
I see. So the problem is that the maildir and IMAP notion of draft editing don't match? Ie maildir says that mail is mutable, and IMAP says it's not? But then why does mu4e, when editing a draft, create a new one? And why does mbsync rename it?

This behavior is very annoying to me, so I'm trying to understand what's going on to see if I can make it work. Do I just have to make mu4e delete all other mail sharing the same prefix when saving a draft?

**Comment by djcb** [comment]
The problem is not in maildir or imap per se -- it's how one is mapped to the other. The way mbsync does the mapping gives us some friction (e.g. renaming files we are editing). So, I'd recommend not syncing draft, at least not while you are editing it (some simple shell scripting should suffice),

Or perhaps mbsync's "alternative" scheme for uids could be helpful.
