### ISSUE TITLE
Capture Template With msg sender in headline?

### ISSUE THREAD

**Issue by titaniumbones** [djcb/mu#939]
Not a bug, a feature request or a request for information.  in `org-mu4e-store-and-capture`, is the message header information exposed in such a way that I can include it in a capture template? I'd like to put "reply to [sender]" after the TODO. Is  this possible?

Thank you -- I am really enjoying it so far, just getting started!

**Comment by ardpp** [comment]
Try something like 
```TODO  Respond to %:fromname on %:subject``` 
in your capture template.

**Comment by titaniumbones** [comment]
oh wow, that did it, thank you so much. Can you explain the syntax to me a bit? How does %:fromname get interpreted by org?

**Comment by djcb** [comment]
See http://orgmode.org/manual/Template-expansion.html for a list.

**Comment by titaniumbones** [comment]
ah, i see it now, thanks.
