### ISSUE TITLE
Incorrect sorting and threading in mu4e

### ISSUE THREAD

**Issue by sachdevaprash** [djcb/mu#940]
![mu-bug2-blurred](https://cloud.githubusercontent.com/assets/1396775/19753440/8c1fd880-9c3f-11e6-91cc-d05ca80848c7.jpg)
![mu-bug-blurred](https://cloud.githubusercontent.com/assets/1396775/19753511/3657fdbe-9c40-11e6-99fb-c58aa5911c31.jpg)
## Expected or desired behavior

Each new thread starts in a consistent fashion with date wise ordering of threads.
## Actual behavior

Mixing of thread markers in an inconsistent fashion. Unclear start to new threads. Date ordering not followed (set to descending).
## Steps to reproduce

Not sure how I can help reproduction. 
## Versions of mu, mu4e/emacs, operating system etc.

mu version 0.9.17, emacs version 26.0.50.1, Ubuntu 16.04
## Any other detail

Probably started on updating emacs. Some details were blurred for sensitivity.

**Comment by djcb** [comment]
As for the thread markers, that might be a font issue, please search the mailing list for some tips. `(setq mu4e-use-fancy-chars t)` might also help.

Can't see anything obviously wrong with the threading; note that within a thread, we sort by thread order.

**Comment by sachdevaprash** [comment]
In the first image, different new threads are starting at different alignments. 

![mu-bug1-blurred](https://cloud.githubusercontent.com/assets/1396775/19844375/5995d0d0-9f6f-11e6-89dd-d7e49c5a14db.jpg)
As for the second pic, I am posting an updated version here. Messages 2 and 6 are supposed to be sibling messages in reply to message 1 and the alignment of the characters makes it appear that they are actually parent-child. Moreover, message 1 does not seem to appear to be a parent to 2 in this ordering.

**Comment by sachdevaprash** [comment]
It definitely appears to be an issue with fonts. I suppose I should have mentioned this earlier. Message 2 in the above pic has Japanese Kanji characters in it. I think that is causing this misalignment of characters maybe?

**Comment by sachdevaprash** [comment]
Probably https://news.ycombinator.com/item?id=10206380 is the relevant issue and this might have nothing to do with mu4e.
As I understand it, each Kanji is supposed to be 2 character width, but isn't and that is causing much of the issue here.

**Comment by sachdevaprash** [comment]
For future reference, using the Togoshi font monospace (http://togoshi-font.osdn.jp/index_en.html) fixed the issue for me. Thanks for the help!
