### ISSUE TITLE
replace deprecated org-mu4e-compose-org-mode

### ISSUE THREAD

**Issue by titaniumbones** [djcb/mu#941]
## Expected or desired behavior
- invoke mu4e-compose
- buffer opens in a hybrid mode of some kind
- on send, the message saves as either html & text, or html & org, then sends as mime-multipart
## Actual behavior
- org-mu4e-compose-org-mode is meant to do most of this, but at least on my laptop with my (unscientific) setup, doesn't always convert the message
## Versions of mu, mu4e/emacs, operating system etc.

mu4e git, emacs-git, org-mode git, all recent
## Any other detail

This is I guess a feature request -- would tag it that way if I could. Thanks!

**Comment by djcb** [comment]
Yeah, in the olden days, mu4e used some trickery to integrate org-mime and automatically convert org-mode etc. But, it never worked reliably, so that's why it was deprecrated.

**Comment by titaniumbones** [comment]
Thanks Dirk. given this,

- is there a suggested workaround i n the meantime, with org-mime 
  etc?
- how would be the first steps towards a more permanent 
  replacement?

Thank you again!



Dirk-Jan C. Binnema writes:

> Yeah, in the olden days, mu4e used some trickery to integrate 
> org-mime and automatically convert org-mode etc. But, it never 
> worked reliably, so that's why it was deprecrated.


--

**Comment by stig** [comment]
I like _part_ of this. I'd love a proper hybrid Email headers / Org editing mode, much like exists now, but I don't actually want to send HTML mail most of the time. I prefer to send the Org source as is (plain text tables and all) -- with the option of converting to HTML before sending, which can be done with `org-mime`.

**Comment by titaniumbones** [comment]
@stig, I submitted some small changes that solved the issue for me, in the pull request below.  You can try checking out & building that branch & see if it helps you.  
#952

**Comment by theophilusx** [comment]
Just wondering what the status is with this? Is there still plans to replace this function with something or is the expectation people will use something like org-msg and org-mime?

FWIW I'd like to use org syntax to author my messages and then either send them as plain text or sometimes as HTML. I want to have source block, footnotes, markup, tables, lists and sections. 

With the exception of having to move back to the headers to send messages, org-mu4e--compose-org-mode seems to be working fine, but as it is marked as deprecated, I don't want to become reliant on it if either it will be removed or there is a preferred alternative approach.

**Comment by thriveth** [comment]
I agree, I would love to see this given some love, possibly even with John Kitchins improvements implemented so it can insert math, images etc., but it\s fine without.

**Comment by bepolymathe** [comment]
I share that wish. We really need an improvement of HTML mail writing from org... it would be wonderful to launch this (Org-msg isn't perfect either, especially with Spacemacs and for attachments)... but I don't have the skills for that.

**Comment by falematte** [comment]
I agree too!

**Comment by Chris00** [comment]
Referencing [this comment](https://github.com/djcb/mu/issues/392#issuecomment-399194287) which points to a fix.  Haven't checked it (attachments, multipart/related...) but it could at least serve as a basis.

**Comment by djcb** [comment]
Yeah, it seems `org-mime` is the way to get with this. I'm open for adding some help in mu4e, but I'm not really planning to add something mu4e-specific for writing org messages. So, closing this. Thanks for all the input.
