### ISSUE TITLE
Display plain text attachments inline

### ISSUE THREAD

**Issue by xuhdev** [djcb/mu#942]
## Expected or desired behavior

When viewing messages, plain text attachments should be displayed inline (at the end of the message), similar to PDF files and image files, especially when mu4e-view-show-images is true.
## Actual behavior

Plain text attachments are not displayed inline.
## Any other detail

A relevant link: https://emacs.stackexchange.com/questions/19164/how-to-display-plain-text-attachments-inline-with-mu4e

**Comment by djcb** [comment]
Can you attach a raw message with a text attachment that should be shown (in your opinion) but isn't? Thanks.

**Comment by xuhdev** [comment]
For example the attachment in [this message](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23436;msg=8;mbox=yes).

**Comment by djcb** [comment]
We don't necessarily want to display _all_ text parts in the body, but it makes sense for patches. Implemented in git.
