### ISSUE TITLE
mu4e: Replace mu4e-contexts with contextual

### ISSUE THREAD

**Issue by akahl-lshift** [djcb/mu#944]
mu4e-contexts reduplicates the functionality provided by the more universal [contextual](https://github.com/lshift-de/contextual) library (disclosure: I am its author).

It would be nice to support it directly. Please let me know if you're missing anything in contextual that's covered by mu4e-contexts.

**Comment by djcb** [comment]
He, nice package!

So, mu4e actually implemented `mu4e-context` to integrate something that replaces the various external solutions people had come up with... so we're really looking to use something external again. But we could reconsider if/when contextual is part of the emacs versions we support.

Anyway, taking a quick look at `contextual`, seems there are also a few things missing (from mu4e's perspective):
* `mu4e-context`s support `match` functions which allow for automatically choosing a context in some situations (ie. we pick the first context whose match function evaluates to t)
* `mu4e-context`s also support enter/leave functions which users can use to invoke custom actions when entering / leaving the context
* there's also a "quick-switch" mechanism; say you have a list of messages and you want to move them to a trash folder, which may be different depending on the message. So, in this case we make that decision by (conceptually at least) let-binding the variables (such as `mu4e-trash-folder`) based on which context matches.

Quite specific of course -- but quite useful as well! Anyway, thanks for the suggestion, but I don't think mu4e will use `contextual` in the near future.
