### ISSUE TITLE
smtpmail documentation

### ISSUE THREAD

**Issue by csasarak** [djcb/mu#945]
I'm not sure where the most appropriate place to contact you about this was, but in the manual the link to the smtpmail documentation is broken on this page: http://www.djcbsoftware.nl/code/mu/mu4e/Sending-mail.html

Did you mean to link to here? https://www.gnu.org/software/emacs/manual/smtpmail.html

Thank you for the excellent software!

**Comment by djcb** [comment]
It's a quirk of the texinfo->html conversion... I'm afraid we can't do much about that.
