### ISSUE TITLE
add/fix customize for contexts

### ISSUE THREAD

**Issue by zabbal** [djcb/mu#953]
## Expected or desired behavior

Open Customize (for example via Options -> Customize Emacs menu) and search for "mu4e policy" - you'll get 3 options:

Show Value Mu4e Compose Context Policy 
   Policy for determining the context when composing a new message. More

Show Value Mu4e Context Policy 
   The policy to determine the context when entering the mu4e main view. More

Show Value Mu4e Decryption Policy 
   Policy for dealing with encrypted parts. More

Expected is to be able to use those to customize things as usual.

## Actual behavior

However, 2 first of those are completely broken: clicking on show will just make it disappear from the buffer.

## Steps to reproduce

This happens always 100% of the time.

## Versions of mu, mu4e/emacs, operating system etc.

This is with mu4e 0.9.16 on ubuntu 16.10 and Emacs 25.1.1

## Any other detail

While we're at it, would be nice to be able to set mu4e-user-mail-address-list as it is described in  http://www.djcbsoftware.nl/code/mu/mu4e/Some-context-tricks.html#Some-context-tricks by just selecting appropriate value via menu in customize.

In general, having ability to setup contexts via Customize facility would make it easier for newcomers to make mu4e work with multiaccount setup.

**Comment by rnkn** [comment]
This is fixed in 0.9.17 but the release has not appeared on distribution package managers yet.

@djcb could you push a release to Homebrew etc.? The current Homebrew formula actually resolves to a 404. I've submitted a PR to resolve for 0.9.16 but it would be nice to have 0.9.17.

**Comment by djcb** [comment]
I can't really influence Homebrew, but I think they should have the latest version now.
