### ISSUE TITLE
forward html emails as html

### ISSUE THREAD

**Issue by titaniumbones** [djcb/mu#958]
## Expected or desired behavior

I often receive HTML-formatted emails that I would like to forward to correspondents. In text modes they are veyr difficult to read.  I would like ot be able to forward the original html

## Actual behavior

Forwarding a mime-multipart message results in only the text part of the message being forwarded.  

## Versions of mu, mu4e/emacs, operating system etc.

recent git versions of mu4e/emacs, running under Arch linux.
## Any other detail
thank you! This is an enhancement issue, not a bug (obviously)

**Comment by djcb** [comment]
From the 0.9.17 FAQ, this is probably the easiest way:

 10. _How can I attach an existing message?_  Use
     ‘mu4e-action-capture-message’ (i.e., ‘a c’ in the headers view) to
     ’capture’ the to-be-attached message, then when editing the
     message, use ‘M-x mu4e-compose-attach-captured-message’.

**Comment by titaniumbones** [comment]
Thanks for the helpful pointer.  

I am tyring  to automate this with the following:
```emacs-lisp
(defun mwp-test-capture ()
  (interactive)
  (mu4e-action-capture-message (mu4e-message-at-point))
  (mu4e-compose 'forward)
  (mu4e-compose-attach-captured-message)
  (message-goto-to))
```
The captured message doesn't get attached here, though if I replace `'forward` with `'new` it works fine.  Does that look like a bug to you? If so I will try to find a fix.
