### ISSUE TITLE
emacs 25 org-mu4e link

### ISSUE THREAD

**Issue by reconmaster** [djcb/mu#959]
## Expected or desired behavior

Prior to finally making the jump to emacs 25, I had no issue with being able to use the `org-store-link` functionality inside the header or message view. Additionally the `org-mu4e-store-and-capture` function used to store a link to that email header with the captured entry.

## Actual behavior

When I now attempt to capture an email with the `org-capture` function in either the header or message view, I an error stating that `user-error: No method for storing a link from this buffer`.

Additionally, when I attempt to use the `org-mu4e-store-and-capture` feature, the function brings up a capture interface, but the org-link to that email is no longer stored with the captured entry.

## Steps to reproduce

Attempt to capture an org-link to an email header in mu4e.

## Versions of mu, mu4e/emacs, operating system etc.

- mu4e 0.9.16
- Org mode version 9.0.1
- GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.9) of 2016-09-18

## Any other detail

Problem only started after migrating to emacs 25. When using emacs 24, there were no problems with my mu4e setup (thanks for a great piece of software btw!). I may be conflating the issue with org-mode being updated as well.

**Comment by jabranham** [comment]
The org-store-link function broke when org-mode updated to version 9.0. There is already a fix for this in mu4e, and will show up when @djcb releases 0.9.18 (hopefully soon!).

**Comment by djcb** [comment]
Yes, @jabranham is right.
