### ISSUE TITLE
Add option to autodetect HTML content

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#967]
Some badly written software (in my case Sharepoint used by my company to dispatch notifications) sends HTML mail with the following incorrect header `Content-Type: text/plain; charset="utf-8"`.  As a workaround, it may be interesting to allow to override the declared `Content-Type` by a function that performs some kind of autodetection.

This is a minor point  — time is probably better invested first elsewhere — but I thought it would be useful to let you know nonetheless (it may be simple to fix! 😊).

**Comment by djcb** [comment]
The best way to do this would be _before_ mu indexing happens, so all the indexing etc. has the right information; with e.g. `procmail` this should be possible. But I think this is best done outside mu.
