### ISSUE TITLE
Company-Mode Completions stopped working

### ISSUE THREAD

**Issue by powellb** [djcb/mu#968]
I upgraded to 0.9.18, and now when composing mail, I no longer get company-mode completions for the to: or cc: addresses. Hitting [tab] will bring up the helm-completion, so the addresses are resolving, but for some reason company-mode has stopped with mu4e. Company-mode is working in other modes (prog-mode, etc.), but not mu4e:compose.

The only configuration changes I made after the upgrade (and re-indexing) were:

(setq
        mu4e-index-cleanup nil
        mu4e-index-lazy-check t)

mu4e Version: 0.9.18
Company Version: 0.9.2

Any suggestions are appreciated to make sure it isn't on my side; however, it had worked fine before upgrading.

**Comment by djcb** [comment]
Hmmm, I really don't know, perhaps the company-mode people can help?

**Comment by powellb** [comment]
Please close the issue. I figured out the culprit: of all things, it was enabled the minor-mode: turn-on-orgtbl.

**Comment by djcb** [comment]
Okay, thanks!

**Comment by amosbird** [comment]
@powellb hmm, I'm experiencing the same problem. How did you solve it?

**Comment by powellb** [comment]
For me, having the following enabled caused company-mode to stop working when composing messages:


(add-hook 'message-mode-hook 'turn-on-orgtbl)
(add-hook 'message-mode-hook 'turn-on-orgstruct++)

I disabled both of those hooks and all was well again...
