### ISSUE TITLE
Always put all attachments at the bottom of the email

### ISSUE THREAD

**Issue by magthe** [djcb/mu#970]
## Expected or desired behavior

mu4e happily accepts that I put an attachment anywhere in the text. I'd like to see mu4e put all attachments *after* the (MIME part containing the) main text.

## Actual behavior

From my experimentation the placement of attachments do influence the order of MIME attachments. In particular, an attachment that is put into the emacs buffer just after the *--text follows this line--* bit have their MIME part appear before the MIME part containing the text of the email. If the attachment happens to be plain text (or something else that mu4e can show) it will appear before the email text, which causes confusion.

## Steps to reproduce

Write an email and attach a file at the top then inspect the resulting email.

## Versions of mu, mu4e/emacs, operating system etc.

Arch Linux, Emacs 25.1, mu/mu4e [14949234](https://github.com/djcb/mu/tree/1494923472c1b009c0b4390270887f54fbaf9369)

## Any other detail

An example of an email with a text attachment appearing above the email text: [top-attachment.txt](https://github.com/djcb/mu/files/638993/top-attachment.txt)

**Comment by panjie** [comment]
The deposit of attachments in mail is handled in message coming with emacs but not in mu4e. I have a ugly solution for this, that is redefine function `mml-dnd-attach-file` by yourself. The following is my redefinition of this function which will always put the attachments to the end of mails.

```elisp
(defun mml-dnd-attach-file (uri action)
  "Attach a drag and drop file.

Ask for type, description or disposition according to
`mml-dnd-attach-options'."
  (let ((file (dnd-get-local-file-name uri t)))
    (when (and file (file-regular-p file))
      (let ((mml-dnd-attach-options mml-dnd-attach-options)
            type description disposition)
        (setq mml-dnd-attach-options
              (when (and (eq mml-dnd-attach-options t)
                         (not
                          (y-or-n-p
                           "Use default type, disposition and description? ")))
                '(type description disposition)))
        (when (or (memq 'type mml-dnd-attach-options)
                  (memq 'disposition mml-dnd-attach-options))
          (setq type (mml-minibuffer-read-type file)))
        (when (memq 'description mml-dnd-attach-options)
          (setq description (mml-minibuffer-read-description)))
        (when (memq 'disposition mml-dnd-attach-options)
          (setq disposition (mml-minibuffer-read-disposition type nil file)))
        (save-excursion
          (goto-char (point-max))
          (mml-attach-file file type description disposition))))))))
```

**Comment by andersjohansson** [comment]
Cleaner to do it with advice though:
````Emacs lisp
(defun mml-attach-file--go-to-eob (orig-fun &rest args)
  "Go to the end of buffer before attaching files."
  (save-excursion
    (save-restriction
      (widen)
      (goto-char (point-max))
      (apply orig-fun args))))

(advice-add 'mml-attach-file :around #'mml-attach-file--go-to-eob)
````
(source: http://mbork.pl/2015-11-28_Fixing_mml-attach-file_using_advice)

**Comment by panjie** [comment]
Thanks. This is a much better solution for it.

**Comment by djcb** [comment]
Thanks -- I've added the snippet to the FAQ in the mu4e manual. Closing this.
