### ISSUE TITLE
mu4e sets a lisp variable named "##" on first launch

### ISSUE THREAD

**Issue by vonkempnz** [djcb/mu#971]
Sometime during its startup, mu4e sets a undefined global variable named `##`. This might be intentional, I'm not sure, but it presents as a nameless variable in the completion list, which chokes ido with an `args-out-of-range` error in `post-command-hook (ido-exhibit)`. Setting `ido-enable-dot-prefix` to nil clears the block, but the variable remains.

Clobbering it with something like `(add-hook 'mu4e-main-mode-hook (lambda () (makunbound '##)))` seems to work around the problem with no observable ill effects. I've reproduced this on 0.9.16, 0.9.18 and master.

**Comment by djcb** [comment]
Do you have some steps to reproduce this? I can't seem to find this `##`. Thanks.

**Comment by vonkempnz** [comment]
I'm not a coder, so forgive me if this isn't all relevant information.

Use describe-variable with ido, no problems:
```
Emacs -Q
(add-to-list 'load-path "~/.emacs.d/lisp/ido-ubiquitous")
(require 'ido-ubiquitous)
(ido-ubiquitous 1)
C-h v C-g
ido-matches --> ("ansi-color-faces-vector" "isearch-message-function" "widget-documentation-link-p" "display-buffer-fallback-action" ...)
```

Now load mu4e and try again:
```
(add-to-list 'load-path "~/.emacs.d/lisp/mu4e")
(require 'mu4e)
(mu4e)
C-h v C-g
ido-matches --> ("" "ansi-color-faces-vector" "isearch-message-function" "widget-documentation-link-p" "display-buffer-fallback-action" ...)
```
Note first item in the list. You can also see it in the *\*Completions\** buffer, indenting the first entry.
In practice, this isn't a problem for me until ido tries to match against the empty string:
```
(setq ido-enable-dot-prefix t)
C-h v
[type any char] --> Error in post-command-hook (ido-exhibit): (args-out-of-range "" 0)
```
From elisp.info > *S2.3.4 Symbol Type* it states that:

> As an exception to the rule that a symbol's name serves as its
> printed representation, `##' is the printed representation for an
> interned symbol whose name is an empty string.

So, try a few things:
```
(describe-variable '##) --> ##'s value is nil. Documentation: Not documented as a variable.
(makunbound '##)
C-h v C-g
ido-matches --> ("ansi-color-faces-vector" "isearch-message-function" "widget-documentation-link-p" "display-buffer-fallback-action" ...)
```

Start mu4e again and the problem doesn't recur:
```
(mu4e)
C-h v
ido-matches --> ("ansi-color-faces-vector" "isearch-message-function" "widget-documentation-link-p" "display-buffer-fallback-action" ...)
```

I did a quick debug against `mu4e-main-mode` and (I think) this screen grab shows it being created.

![grab](https://cloud.githubusercontent.com/assets/9387007/21338026/4d19199a-c6d7-11e6-8254-354809d360d5.png)

Perhaps this should be a bug against ido-ubiquitous for poor handling of a (legal) symbol whose name is an empty string, or something else? Not sure.
If it matters, I'm running macOS 10.12.2 and mac-port Emacs 25.1.1, although I get the same results with a GNU ns build. 

Hope it helps.

**Comment by djcb** [comment]
Thanks for the analysis - very useful! 

What seems to happen is that the emacs machinery for `define-derived-mode` tries to update the abbrev-table and as part of that interns the empty string... `mu4e` has little control over that. Moreover, when I run `emacs -Q`, and evaluate `(describe-variable '##)` I get the
```
## is void as a variable.

Documentation:
Not documented as a variable.
```
So it seems this is not really related to mu4e. It might be that `ido-ubiquitous` is a bit too picky, but I'm not sure. I'd recommend adding something like your hook.
