### ISSUE TITLE
Toggle for bottom/inline display of attachments

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#973]
If a message contains attachments, there should be a toggle to respect the inline Content-Disposition, or to always put attachments at the end.

This makes sense mostly for images, but there's no reason we shouldn't handle any type uniformly and fix #970 at the same time.

Attaching a sample message with an inline image.
[test.zip](https://github.com/djcb/mu/files/644640/test.zip)

**Comment by Chris00** [comment]
See https://github.com/djcb/mu/pull/976 for the (the initial hooks for the) corresponding feature for (the more frequent case of) HTML messages.  I wonder whether `mu4e-view-show-cid-inline` should be renamed `mu4e-view-show-images-inline` and be used for both cases.

**Comment by djcb** [comment]
With the new (experimental) view mode, images are shown as they were sent, ie. potentially in the middle of the message. Don't think we can easily make them appear at the end.

`(setq mu4e-view-use-gnus t)` (before starting mu4e).
