### ISSUE TITLE
Prompt for a file or directory in `mu4e-view-save-attachment-multi`

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#974]
When messages contain many attachments, extracting them though mu4e is a PITA.
`mu4e-view-save-attachment-multi` will prompt for each individual filename.
The vast majority of the time I'd like to export to a target directory with the original filename, and prompt only if the target filename clobbers and existing file.

I'd be fine if this would be a separate function, for example triggered by a negative prefix, but I'd vouch for triggering this behavior if 'a' (all attachments) have been elected for export.

**Comment by j-hao** [comment]
I think you can just set `mu4e-save-multiple-attachments-without-asking` to `t` to achieve what you want

**Comment by wavexx** [comment]
Ah! That does indeed what I was asking for. Sorry, I missed this flag completely.
