### ISSUE TITLE
can't compile latest master

### ISSUE THREAD

**Issue by tpapp** [djcb/mu#975]
checked out dde79288556e2505aff467dd526a299d3bba6abb, tried to compile as usual, got
```bash
 ~/src/mu $ autoreconf -i && ./configure && make
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'xua'.
libtoolize: copying file 'xua/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure:5832: error: possibly undefined macro: dnl
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:5907: error: possibly undefined macro: AS_ECHO
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
On latest Ubuntu.

**Comment by tpapp** [comment]
Last version that compiles for me is 1f232b67371f2acbf2a2e5c42ee7233337f0935a.

**Comment by tuxella** [comment]
I ran into the same problem on commit
dde79288556e2505aff467dd526a299d3bba6abb

Updating autoconf and installing autoconf-archive fixed the problem on
macOS 10.11


On 2016-12-12 at 13:52, Tamas K. Papp <notifications@github.com> wrote:
> checked out dde79288556e2505aff467dd526a299d3bba6abb, tried to compile as usual, got
> ```bash
>  ~/src/mu $ autoreconf -i && ./configure && make
> libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'xua'.
> libtoolize: copying file 'xua/ltmain.sh'
> libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
> libtoolize: copying file 'm4/libtool.m4'
> libtoolize: copying file 'm4/ltoptions.m4'
> libtoolize: copying file 'm4/ltsugar.m4'
> libtoolize: copying file 'm4/ltversion.m4'
> libtoolize: copying file 'm4/lt~obsolete.m4'
> configure:5832: error: possibly undefined macro: dnl
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> configure:5907: error: possibly undefined macro: AS_ECHO
> autoreconf: /usr/bin/autoconf failed with exit status: 1
> ```


--
Thomas Cordival

**Comment by tpapp** [comment]
@tuxella: thanks for the hint, installing `autoconf-archive` fixes the problem on Ubuntu, too.

Perhaps the documentation could mention that it should also be installed prior to compilation.

**Comment by Chris00** [comment]
It would be nice if the error could be transformed into something giving a hint about what to do.

**Comment by djcb** [comment]
I've added an explicit error for a missing autoconf-archive, and added some doc. Thanks, closing this.

**Comment by thierryvolpiatto** [comment]
I could recompile fine on ubuntu 16.04, however I am not able anymore to compile on 14.04.
Here the error after running ./autogen.sh as explained in HACKING:

```sh
./configure: line 5768: syntax error near unexpected token `AX_COMPILER_FLAGS_CFLAGS'
./configure: line 5768: `               AX_REQUIRE_DEFINED(AX_COMPILER_FLAGS_CFLAGS)'
```

**Comment by Chris00** [comment]
@thierryvolpiatto Have you installed `autoconf-archive` and, if so, what version?

**Comment by thierryvolpiatto** [comment]
Christophe Troestler <notifications@github.com> writes:

> @thierryvolpiatto Have you installed autoconf-archive and, if so, what version?

The version is 20131101-1

-- 
Thierry

**Comment by Chris00** [comment]
On 2016-12-19, Thierry Volpiatto wrote:
> 
> Christophe Troestler <notifications@github.com> writes:
> 
> > @thierryvolpiatto Have you installed autoconf-archive and, if so, 
> > what version?
> 
> The version is 20131101-1

This is old.  Mine is 20160916-1.  Please try to upgrade (possibly using 
a PPA).  https://launchpad.net/ubuntu/+source/autoconf-archive may help.

**Comment by thierryvolpiatto** [comment]
Christophe Troestler <notifications@github.com> writes:

> On 2016-12-19, Thierry Volpiatto wrote:
>>
>> Christophe Troestler <notifications@github.com> writes:
>>
>> > @thierryvolpiatto Have you installed autoconf-archive and, if so,
>> > what version?
>>
>> The version is 20131101-1
>
> This is old. Mine is 20160916-1. Please try to upgrade (possibly using
> a PPA). https://launchpad.net/ubuntu/+source/autoconf-archive may help.

Hmm, Don't think it will be possible, there is no ppa there.
Will see later if I can build from source.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Christophe Troestler <notifications@github.com> writes:
>
>> On 2016-12-19, Thierry Volpiatto wrote:
>>>
>>> Christophe Troestler <notifications@github.com> writes:
>>>
>>> > @thierryvolpiatto Have you installed autoconf-archive and, if so,
>>> > what version?
>>>
>>> The version is 20131101-1
>>
>> This is old. Mine is 20160916-1. Please try to upgrade (possibly using
>> a PPA). https://launchpad.net/ubuntu/+source/autoconf-archive may help.
>
> Hmm, Don't think it will be possible, there is no ppa there.
> Will see later if I can build from source.

After building autoconf-archive from source I have now other error:

    configure:5888: error: possibly undefined macro: AS_ECHO
    autoreconf: /usr/bin/autoconf failed with exit status: 1

So for now it seems master is incompatible with ubuntu 14.04.

Please reopen issue.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Christophe Troestler <notifications@github.com> writes:

> This is old. Mine is 20160916-1. Please try to upgrade (possibly using
> a PPA). https://launchpad.net/ubuntu/+source/autoconf-archive may help.

It seems 20160916-1 doesn't work here, I finally installed 

http://launchpadlibrarian.net/211472830/autoconf-archive_20150224-2.1_all.deb

which seems to work, I could build successfully on master.

Thanks.

-- 
Thierry
