### ISSUE TITLE
"mu --help" misses the mandatory <command> part

### ISSUE THREAD

**Issue by bjornfor** [djcb/mu#980]
According to the man page and the output of ```mu``` (without any options or commands at all), mu requires a command. But ```mu --help``` doesn't say that:

```
$ mu --help
Usage:
  mu [OPTION...] - mu general options
...
```

## Version info
mu version 0.9.16.

**Comment by djcb** [comment]
The manpage does mentions the `mu [options]` case. Depending on the flags, there can be different options. I did make a plain 'mu' a shortcut for 'mu help' though.
