### ISSUE TITLE
Display mu4e-view buffer before rendering it

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#984]
It seems that the function `mu4e-html2text-command` is called before the `*mu4e-view*` buffer is attached to a frame, i.e. `(get-buffer-window (current-buffer))` returns `nil`.  This prevents `shr-rescale-image` from working properly to rescale images since the size of the frame cannot be determined.  Other rendering functions may be confronted with the same issue.

**Comment by djcb** [comment]
We use the output of (in this case) `shr` to build the message in a temp-buffer, so sadly, this is not practically possible. We'd need to be able to pass the parameters to `shr`, but haven't found a way to do that so far. Suggestions are welcome of course.

**Comment by Chris00** [comment]
I am afraid that we will need to duplicate the code of shr that does the rendering, capturing the window parameters of the final frame.  Will open a new issue to remember that.
