### ISSUE TITLE
Cfind and duplicate real names 

### ISSUE THREAD

**Issue by hoclun-rigsep** [djcb/mu#987]
Using mu cfind --format=mutt-alias.  If there are duplicate real names (e.g. I have an uncle and a brother both named 'Michael' with the same last name), then when sourcing the alias file in mutt, the second overrides the first and he doesn't appear at all. 

cfind should detect duplicate real names when generating the aliases and use as many additional letters or a nonce character if necessary to avoid duplicate aliases. 

Sample output of mu cfind --format=mutt-alias

> alias MichaelA Michael Ansbro <mikeswire@yahoo.com>
> alias MichaelA Michael Amber <beefchip@gmail.com>
> alias MichaelA Michael Amber <mamber@corporate.com>

Desired output: 

> alias MichaelA1 Michael Ansbro <mikeswire@yahoo.com>
> alias MichaelA2 Michael Amber <beefchip@gmail.com>
> [etc.]

When this is sourced by mutt you're only going to be able to reach mamber@corporate.com
I am not much of a C hacker: if you wanted a patch from me it would be bad code delivered months from now...

**Comment by djcb** [comment]
Okay, implemented!
