### ISSUE TITLE
Resend: inappropriate behavior on quoted-printable email

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#988]
Using the "Resend" (`mu4e-compose-resend`) on an email with `Content-Transfer-Encoding: quoted-printable` (from the `sent` folder) opens a mu4e:compose buffer with a copy of the mail that is still in quoted form (with accented letters as `=C3=A0` and the like).  The content encoding header is still present so it sends correctly but it is not very nice if one wants to modify it.

**Comment by djcb** [comment]
Resend really implies sending something unchanged (but perhaps with a different recipient), and we can't reliably round-trip decoding/re-encoding a message. I guess we'll have to learn to live with this when re-sending messages.
