### ISSUE TITLE
Fontification of message signatures

### ISSUE THREAD

**Issue by dzop** [djcb/mu#989]
First, I just wanted to say thank you for this great piece of code.

I was browsing around the code base and found that `mu4e~fontify-signature` was using `search-forward` to find the starting location of the signature but it is being passed a regex. Replacing `search-forward` with `re-search-forward` will fix this.

**Comment by djcb** [comment]
Ah, can you make a pull-request for that? Thanks!

**Comment by djcb** [comment]
This has been merged -- thanks!
