### ISSUE TITLE
A way to change the default sorting order for headers view (mu4e-headers-sortfield) is missing?

### ISSUE THREAD

**Issue by kuba-orlik** [djcb/mu#990]
Section 4.4 of mu4e info mentions that the user can change the `mu4e-headers-sortfield` variable to change the default sorting order for headers view. However, trying to customize this variable yields `No customizable group, face, or option matching (mu4e-headers-sortfield)`.

I'm using mu4e 0.9.19

**Comment by djcb** [comment]
You can customize it, but not through emacs' customize interface. See `mu4e-headers-sort-field`.

**Comment by kuba-orlik** [comment]
Isn't there a typo in the documentation, then? I think there's a `-` missing between `sort` and `field` in `mu4e-headers-sortfield`? :)

**Comment by kuba-orlik** [comment]
Besides, the variable documentation states: 

> Documentation:
Field to sort the headers by.
Field must be a symbol, one of: :date, :subject, :size, :prio,
:from, :to.

I now know how to change the *fields* taken into consideration when sorting the headers view, but how do I change the default *order* (asc/desc)?

**Comment by djcb** [comment]
You can use `mu4e-headers-change-sorting` to change it. And yeah, there was a typo in the doc.
