### ISSUE TITLE
Add "Delivered-To" information to the mu4e message plist

### ISSUE THREAD

**Issue by noctuid** [djcb/mu#995]
## Desired behavior
- messages contain a `:delivered-to` field

## Reasoning
The main scenario I want this information for is so that I can automatically set the from address when replying to an email. The reason I would want to use `:delivered-to` over `:to` is that the email may have been forwarded from one of my other addresses and I don't want to reply with that original email address. I'd also like to be able to add a custom header for this so that I can display it in the message view.

**Comment by djcb** [comment]
Don't want to complicate the backend further with extra fields, do unfortunately will have to decline this. However, with, say, the `formail` tool you can do it by hand with a bit of elisp:
```
(shell-command-to-string (concat "formail -x Delivered-To < " (shell-quote-argument path)))
 ```

**Comment by m4lvin** [comment]
Found this because I would like to change context (and reply/refile accordingly) depending on `:x-original-to`. I guess this will also not be added? Could I use the shell command to witch context automatically? It seems a bit expensive to run this just before every refile?

**Comment by djcb** [comment]
I think in practice it should work fast enough... but if you really care I guess you could run `procmail` or some such tool beforehand (that's what I do for initial filing). It's even possible to add a _tag_ there, which you could use from mu4e.

**Comment by bradyt** [comment]
I have spam like `To: undisclosed-recipients:;`, and would like easy access to headers like `X-Delivered-to: a@b.c`. I was expecting to see a map from arbitrary string keys to values, but I only see a fixed finite set of keywords as keys, available in functions for `mu4e-header-info-custom`, and debug printing on the message does not provide `a@b.c` there.
