### ISSUE TITLE
Single expression as argument to "mu find"

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#999]
"mu find" currently expects the expression to be tokenized into arguments.
However, this is annoying when building an expression to be programmatically supplied to it.

It would be nice if find supported an expression as a single argument (such as ``-e expr``), or better yet, re-tokenized arguments irregardless, which is more consistent for the user anyway.

**Comment by djcb** [comment]
With the new query parser:
```
% mu find foo and bar --format=xquery
Query(((Tfoo OR Cfoo OR Hfoo OR Ffoo OR Sfoo OR Bfoo) AND (Tbar OR Cbar OR Hbar OR Fbar OR Sbar OR Bbar)))
% mu find "foo and bar" --format=xquery
Query(((Tfoo OR Cfoo OR Hfoo OR Ffoo OR Sfoo OR Bfoo) AND (Tbar OR Cbar OR Hbar OR Fbar OR Sbar OR Bbar)))
```
